### ISSUE TITLE
Swagger UI (with swagger 2) javascript error 

### ISSUE THREAD

**Issue by Paul776** [springfox/springfox#1000]
Hello,

I have added the swagger2 dependency in my Spring MVC application. 
and I have added in my resources/webapp the files found in the list folder in the git swagger-ui project
(I have also added a controller /doc to point to that folder)

When I go to
http://localhost:8080/myapp/v2/api-docs
I can see the JSON.

When I go to 
http://localhost:8080/myapp/doc/index.html

The swagger html shows up but I get a javascript error
swagger-ui.js:1932 Uncaught TypeError: Cannot read property 'definitions' of null

Note: when I use the http://petstore.swagger.io/v2/swagger.json the UI displays fine.. So for some reasons the JSON generated for my app (which has ONE single test controller and a DTO as parameter) is not correct ?

Could someone help me fix this problem?

thank you

**Comment by Paul776** [comment]
I think I found where the problem is, the call to 
http://localhost:8080/myapp/v2/api-docs

returnes in fact a JSON but the whole json string is surrounded by two quote?? 
"{"version":2.0 ......}"

How can I make that simply return a JSON? is it something to do with jackson ?

**Comment by dilipkrish** [comment]
@Paul776 Its definitely seems like a problem with your jackson setup.

**Comment by virtuecai** [comment]
v2/api-docs return "{}", this question how to fix ?

**Comment by dilipkrish** [comment]
@virtuecai Hopefully you're using 2.5.0. This is a closed issue. Please create a new issue with specifics

**Comment by virtuecai** [comment]
@dilipkrish thanks, springfox can not work with fastjson

**Comment by dilipkrish** [comment]
Just to clarify out of the box only Jackson is supported. Other serializers _CAN_ be supported using plugins.
