### ISSUE TITLE
DirectModelSubstitute is not substituting 

### ISSUE THREAD

**Issue by cemo** [springfox/springfox#1003]
I would like to replace all of my `Product` entities with a subclass `ProductMixin `. I found that alternate rules seems right solution for this purpose. 

When I do not use substitution I have such a schema in my swagger ui:  

```
{
  "count": 0,
  "products": [
    {
      "allowedCount": 0,
      "availability": "string",
      "brandId": 0
      //// other properties
    }
}
 ```

however when I use substitution with:

```
return new Docket(DocumentationType.SWAGGER_2)
          .directModelSubstitute(Product.class, ProductMixin.class)
```

I have a `null` in model schema:

```
{
  "count": 0,
  "products": [
    null
  ]
}
``` 

I have used latest 2.2.3 snapshot. Am I missing something?

**Comment by cemo** [comment]
I am not expert of swagger spec but I checked generated JSON and noticed that `ProductMixin` is existing but not `Product`. 

Here is the trace:

```
     "ProductListWrapper":{  
         "properties":{  
            "count":{  
               "type":"integer",
               "format":"int32"
            },
            "products":{  
               "type":"array",
               "items":{  
                  "$ref":"#/definitions/Product"
               }
            }
         }
      },
``` 

In definitions:

There is `ProductMixin` but not `Product`. I think that `$ref` are not updated. This is causing issue. Any help?

**Comment by dilipkrish** [comment]
This might be a bug. Will investigate

**Comment by cemo** [comment]
@dilipkrish We are using springfox and swagger to generate client codes. This is unfortunately stopping us to use springfox. Is there any help I can provide? If you guide me on necessary places to check and debug, I can give a try.

**Comment by dilipkrish** [comment]
@cemo as demonstrated by :point_up: [this commit](https://github.com/springfox/springfox/blob/master/springfox-schema/src/test/groovy/springfox/documentation/schema/AlternateTypesSupport.groovy#L31-L32). If you need to substitute a list or array of a particular type. This is how you'd need to add new rules.

**Comment by cemo** [comment]
I am not substituting a list or array. I am substituting only a bean which is used by another internal class.

**Comment by dilipkrish** [comment]
May be I din't understand the problem. Both your examples indicate that products is a collection/array :point_down: .

```json
...
"products": [
    {
      "allowedCount": 0,
      "availability": "string",
      "brandId": 0
      //// other properties
    }
...
//and
...
           },
            "products":{  
               "type":"array",
               "items":{  
                  "$ref":"#/definitions/Product"
               }
            }
```
are you referring to these examples?

**Comment by cemo** [comment]
@dilipkrish I think that I do not know what is a `substitution`. I would like to change all `Product` references by `ProductMixin`. Should I also add `List<Product>` as a `substitution`? I would be also glad if you shed light on `substitution` a little.
