### ISSUE TITLE
How to define global models

### ISSUE THREAD

**Issue by SamG1000** [springfox/springfox#1006]
I am using Springfox 2.2.2 to generate swagger doc for my Spring MVC project.

I have followed the example in to define globalResponseMessage:
http://springfox.github.io/springfox/docs/snapshot/

I could not find any documentation of how to define global model:
- "​13.. and indicate that it will use the response model Error (which will be defined elsewhere)"

In my case, none of the API's would return an Error object, but when an exception is thrown, I am using @ControllerAdvice and @ExceptionHandler({ ... }) to return non-200 status codes back.

How do I define the response from my @ExceptionHandler as the model object.

If I do not define proper model, 
```
  .responseModel(new ModelRef("Error"))
```
will cause swagger-io to keep looking for "Error" model and 180 times, just like in https://github.com/springfox/springfox/issues/809

Thanks,
Simon

**Comment by dilipkrish** [comment]
@SamG1000 The explain the `(which will be defined elsewhere)` part :)

You need to define a `@ApiResponses` collection that defines a the `Error` class as a response. Unfortunately this is the only way to trick springfox into generating a model for it, until someone sends a PR to support `@ExceptionHandler` (hint, hint... :wink:)

**Comment by architkansal** [comment]
@dilipkrish  could you elaborate about defining @ApiResponses collection that defines the Error class as a response.

**Comment by lppedd** [comment]
@dilipkrish Any news on this? Can you point where the Model is discovered?

**Comment by dilipkrish** [comment]
@lppedd this is a very old issue. There are already ways to define global models, unless you're looking to add support for `ExceptionHandler`. If thats the case, you need to create your own `OperationModelsProviderPlugin` that reads this annotation and adds models to the request mapping context.

**Comment by SamG1000** [comment]
```
List<ResponseMessage> messages = Arrays.asList(ResponseMessageBuilder().code(HttpStatus.INTERNAL_SERVER_ERROR.value())
                                                                                   .message(HttpStatus.INTERNAL_SERVER_ERROR.getReasonPhrase())
                                                                                   .responseModel(new ModelRef("ExceptionDto"))
                                                                                   .build());
      return new Docket(DocumentationType.SWAGGER_2)
          .select()
            .apis(RequestHandlerSelectors.basePackage("..."))
            .paths(PathSelectors.any())
            .build()
            .pathMapping("/")
            .genericModelSubstitutes(ResponseEntity.class)
            .useDefaultResponseMessages(true)
            .globalResponseMessage(RequestMethod.GET, messages)
            .globalResponseMessage(RequestMethod.POST, messages)
            .globalResponseMessage(RequestMethod.PATCH, messages)
            .additionalModels(typeResolver.resolve(ExceptionDto.class))
            .apiInfo(apiInfo());
```

see `ResponseMessageBuilder` and ` .additionalModels(typeResolver.resolve(ExceptionDto.class))`

Hope this helps.

**Comment by mvmn** [comment]
Thanks.

The typeResolver is com.fasterxml.jackson.jr.type.TypeResolver, right? That's not very obvious.

Also, this registration registers ExceptionDto class as "ExceptionDto" model, but what if we have 2 classes with same name from 2 different packages? I understand that in this case registration of one will override registration of the other, and there is no way to refer to both.

**Comment by SamG1000** [comment]
yes, `import com.fasterxml.classmate.TypeResolver`

You will have to give them `ModelRef` that's different... Maybe prefix the part of the package that is different?
