### ISSUE TITLE
swagger-ui Model schema object rendering as "traversableAgain" for scala 

### ISSUE THREAD

**Issue by tenstriker** [springfox/springfox#1007]
I have spring-boot/springmvc project which uses custom ObjectMapper for fasterxml scala. 

I can serialize and deserialize my scala beans just fine when sending normal request. But swagger-ui somehow can't describe scala map in request model. Instead it says "traversableAgain" . I can't find any documentation on why I am getting "traversableAgain" ? 

As you can see in following swagger-ui page I am getting element 'def' is a complex object but it displays as "traversableAgain"

![screen shot 2015-10-14 at 11 22 44 am](https://cloud.githubusercontent.com/assets/5257103/10493802/f7a6b4fa-7267-11e5-9157-5cb7d0ce6574.png)

If I click on "Model" then I get following information but as a normal consumer I'd like to see that in JSON format.

![screen shot 2015-10-14 at 11 39 22 am](https://cloud.githubusercontent.com/assets/5257103/10494070/13f40bd4-7269-11e5-9b37-677de0857fd1.png)

**Comment by dilipkrish** [comment]
I suspect its because of the way the object mapper is configured. Which version of springfox are you using?

**Comment by tenstriker** [comment]
I am using springfox 2.2.2. By the way, I have not annotated my model and controllers with @API, @APIOperation etc as I didn't see any mentioning of them in springfox document as a requirement.

**Comment by tenstriker** [comment]
Why this was closed ?

**Comment by dilipkrish** [comment]
I'm not super familiar with scala, so would need some help reproducing this issue, but with a little googling it sounds like [this is your issue](https://github.com/FasterXML/jackson-module-scala/issues/94)

**Comment by tenstriker** [comment]
Right it's a scala issue. I understand spring and its ecosystem is not best suited for scala. I was however able to successfully use fasterxml scala for data binding. If I were to fork and fix myself can you give some pointers

**Comment by dilipkrish** [comment]
There is nothing to fork/fix... Its not a problem with this library. If you do want the isomorphism with the databinding, you could try using jackson mixins.
