### ISSUE TITLE
swagger annotations not evaluated in separate maven module

### ISSUE THREAD

**Issue by thefunnyman** [springfox/springfox#1012]
Hello,

I have a spring boot web service written with spring mvc. The model for this service exists as a separate maven module in my application. This allows me to publish the api contract separately so api consumers can more easily create requests. For some reason, all of the swagger annotations within my POJOs in the contract module are not honored or evaluated when I view the documentation in swagger ui. I have created a dummy controller method that returns a sample pojo. I have bundled the sample pojo in the actual service module (instead of the contract module). If i provide the same annotations to the sample pojo, I am able to see the result documentation in swagger ui. Am I doing something wrong? Is there something I need to do to register with springfox that the api documentation is in a separate module?

Thanks in advance for any insight you can provide!

**Comment by thefunnyman** [comment]
PEBCAK....

I was expecting when i rebuilt my project with maven that module changes would reflect when i re-run my application. I had to actually run mvn install on the contract module. THEN, the api documentation magically appeared. Thanks for the awesome tool!

**Comment by dilipkrish** [comment]
:+1:
