### ISSUE TITLE
PropertyFileLoaderConfig

### ISSUE THREAD

**Issue by pvpkiran** [springfox/springfox#1014]
In my Spring boot application, I am loading different properties file under different folder based on profiles(dev, stage, prod) using a configuration class where I return an instance of ```PropertySourcesPlaceholderConfigurer``` with locations set to my properties files. 
But after I integrated swagger into it, the default port which I am setting in the properties file as ```server.port``` is not getting picked. Instead the server is starting on default port 8080. 

The reason may be that ```EnableSwagger2``` annotation imports ```SwaggerCommonConfiguration``` class which also returns an instance of ```PropertySourcesPlaceholderConfigurer``` which might be an issue.

Does anyone has any clue?

**Comment by dilipkrish** [comment]
@pvpkiran its possible that that may be the cause of your issue. Is your instance of `PropertySourcesPlaceholderConfigurer` statically created?
