### ISSUE TITLE
Question: hiding parent classes in a model 

### ISSUE THREAD

**Issue by lrk** [springfox/springfox#1015]
Hello,
can i hide all parent classes for model generation ? or do i have to create dummy classes and map them with the dataType or response annotations attributes ?

example: setting an exception as ApiResponse#response :
```
@ApiResponse(code = 400, message = "Validation error",response = FieldsValidationException.class)
```
value give me the whole Exception class hierarchy:
```
FieldsValidationException {
cause (Throwable, optional),
localizedMessage (string, optional),
message (string, optional),
stackTrace (Array[StackTraceElement], optional),
suppressed (Array[Throwable], optional),
validationErrors (Array[ObjectError], optional): validationErrors
}
Throwable {
cause (Throwable, optional),
localizedMessage (string, optional),
message (string, optional),
stackTrace (Array[StackTraceElement], optional),
suppressed (Array[Throwable], optional)
}
StackTraceElement {
className (string, optional),
fileName (string, optional),
lineNumber (integer, optional),
methodName (string, optional),
nativeMethod (boolean, optional)
}
ObjectError {
arguments (Array[Inline Model 1], optional),
code (string, optional),
codes (Array[string], optional),
defaultMessage (string, optional),
objectName (string, optional)
}
Inline Model 1 {
}
```

thank you.

**Comment by dilipkrish** [comment]
You'll probably need to create a `mixin` In Jackson to inform springfox and Jackson what your exception should look like over the wire. In any case it's a bad idea to leak service internals like exception.

**Comment by lrk** [comment]
maybe, but in my current project, exceptions are handled with cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler to transform a json response

for example, the FieldValidationException return something like:
```
{
 status:400,
message:"error message",
fields:[{field:"fieldname",error:"error message"},...]
}
```

**Comment by dilipkrish** [comment]
Do you have a custom serializer for the exception... if so you'd need to train springfox to render it the same way. By train I mean via [jackson mixins](http://www.theotherian.com/2014/02/jackson-mixins-and-modules-external-classes.html)
