### ISSUE TITLE
Download not Working in Firefox

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#1016]
Here are two screens of the same request, it's a download file URL.

Firefox:
<img width="852" alt="firefox" src="https://cloud.githubusercontent.com/assets/932639/10577647/9a535e54-7675-11e5-8912-1122ebe10f38.png">

Chrome:
<img width="1399" alt="chrome" src="https://cloud.githubusercontent.com/assets/932639/10577650/a06212e0-7675-11e5-9ab8-b8de3937ffa3.png">

And here is the response in IE:

![downloadreportie](https://cloud.githubusercontent.com/assets/932639/10577949/a68500cc-7677-11e5-9aae-08cb7db0b2e2.jpg)

These are three identical requests one of firefox (empty a href) and one on chrome (a valid a href).

Any other details you might require?

**Comment by dilipkrish** [comment]
Seems like a swagger-ui bug. You might want to report your situation there

**Comment by wind57** [comment]
@dilipkrish where is that? can you give a link? I've always posted my issues here.

**Comment by dilipkrish** [comment]
[swagger-ui](https://github.com/swagger-api/swagger-ui)
