### ISSUE TITLE
EnableSwagger2 via xml configuration without using java config

### ISSUE THREAD

**Issue by blvp** [springfox/springfox#1017]
(subject) 
Is it possible to make xml namespace that should enabling swagger
something like that: 
```xml
    <swagger:enable-swagger2/>

and the context configuration will require Docket beans and so on..

**Comment by dilipkrish** [comment]
@blvp [there is nothing magical](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/annotations/EnableSwagger2.java#L41) about that annotation its just pulling in the `Swagger2DocumentationConfiguration` bean.

If you define that bean in your xml file it should just work.

**Comment by dilipkrish** [comment]
Also xml bean definitions are a way of the past. Don't really feel it should be perpetuated via this library. Its easy enough to wire in the bean.

**Comment by blvp** [comment]
@dilipkrish Thank you. Legacy is hell and sometimes we must use xml for configuration ;) It is just matter of some sort of convention of a project. When we only use xml, I don't want to user other kinds of configuration except annotations.

**Comment by blvp** [comment]
@dilipkrish adding Swagger2DocumentationConfiguration bean works fine. Thank you again!
