### ISSUE TITLE
Why does this mapping not work?

### ISSUE THREAD

**Issue by Bert-R** [springfox/springfox#1018]
I'm having a method like this:
```java
	@RequestMapping(value = "{id}", method = RequestMethod.GET)
	@ResponseBody
	public HttpEntity<GoalResource> getGoal(@PathVariable UUID id) {
		return createOKResponse(goalService.getGoal(id));
	}
```
Now I want to map the response to a `GoalDTO`. I thought this would be the right way:
```java
.alternateTypeRules(newRule(typeResolver.resolve(HttpEntity.class, GoalResource.class),
						typeResolver.resolve(GoalDTO.class)))
```
However, mapping does not occur. Any suggestions?
Is there a way to see what mappings are being applied?

This occurs with 2.2.2.

**Comment by dilipkrish** [comment]
Couple of questions
- What does `GoalResource` look like?
- When you say,

>> Now I want to map the response to a GoalDTO

You could mean one of 2 things
- You want the serialized types to map to GoalDTO
Or
- You want swagger to generate a type that looks like GoalDTO

Which one is it? 

Also, when you say mapping does not occur, what are you seeing that makes you say that?

**Comment by Bert-R** [comment]
Thanks for looking into this!
I have to be a bit careful. I based my original posting (unknowingly) on 2.0.2 instead of 2.2.2. On that version, I struggled with the mentioned problem related to `Resource` and similarly with `Resources`. With 2.2.2, I don't need to map for `Resource` anymore, so cannot show that it doesn't work. For `Resources`, I still have the same problem.

Here are more details:

This is the method that I'm trying to map, with the related classes:
```java
import org.springframework.hateoas.Resources;
import org.springframework.http.HttpEntity;

@RequestMapping(method = RequestMethod.GET)
@ResponseBody
public HttpEntity<Resources<GoalResource>> getAllGoals() {
	return createOKResponse(goalService.getAllGoals());
}

public static class GoalResource extends Resource<GoalDTO> {
	public GoalResource(GoalDTO goal) {
		super(goal);
	}
}
```

This is the mapping:
```java
AlternateTypeRule goalResourcesRule = newRule(
		typeResolver.resolve(HttpEntity.class, typeResolver.resolve(Resources.class, GoalResource.class)),
		typeResolver.resolve(List.class, GoalDTO.class));

.alternateTypeRules(goalResourcesRule)
```

In Swagger, I see this JSON:
```javascript
{
  "content": {
    "empty": true
  },
  "links": [
    {
      "href": "string",
      "rel": "string",
      "templated": true
    }
  ]
}
```

This corresponds with the `Resources` class, which has method `getContent` returning a `Collection`. Based on this, I conclude the mapping does not occur.

This is the JSON that I practically use and want to document:
```javascript
{
    "_links":{
        "self":{
            "href":"http://localhost:8080/goals/"
        }
    },
    "_embedded":{
        "Goals":[
            {
                "name":"g1",
                "categories":[
                    "a",
                    "b"
                ],
                "_links":{
                    "self":{
                        "href":"http://localhost:8080/goals/15c71c3b-94de-41db-a22b-0ffdfd8ecee5"
                    }
                }
            },
        ]
    }
}
```

Earlier, with 2.0.2, I concluded mapping didn't occur for the situation in my original issue posting because the JSON for a single "goal" had the content twice, once directly and once inside the `content` property. That corresponds to the `Resource` class, which has a method `getContent` returning an instance of the generic type.

Ideally, I shouldn't need a mapping for `Resources`, just like I don't need one for `Resource` anymore after upgrading to 2.2.2.
