### ISSUE TITLE
Cannot access the swagger-ui visual interface

### ISSUE THREAD

**Issue by fofole** [springfox/springfox#1019]
I have a basic configuration in my Spring boot initializer:

@SpringBootApplication(exclude = ErrorMvcAutoConfiguration.class)
@EnableSwagger2
public abstract class ServiceInitializer {
          ............................................................................
@Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo());
    }

And when I try to access the docu I get the json from here
http://localhost:8080/service-webapp/v2/api-docs

I see I got theses 2 endpoints mapped 
Mapped "{[/v2/api-docs] ...  Mapped "{[/swagger-resources]}" 

But there is no swagger-ui.html mapped anywhere ?
All i get is the json in text format. I want to get the good looking ui interface 
but not sure what I'm doing wrong.

Is it because of my older dependencies ?

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.0.1</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.0.1</version>
        </dependency>

I cannot use newer ones because of conflicting dependencies with spring boot.

Thanks.

**Comment by dilipkrish** [comment]
Thats because you have `@SpringBootApplication(exclude = ErrorMvcAutoConfiguration.class)` you have to register the mvc resource handlers for swagger ui manually.

**Comment by dilipkrish** [comment]
Also anything before 2.2 is a fairly buggy codebase and is not going to be compliant with the swagger spec completely (we released before swagger team released their library)

**Comment by fofole** [comment]
Any resources available on adding the mvc handlers manually for swagger ? I'm new to this stuff...

**Comment by dilipkrish** [comment]
The [springfox-demo](https://github.com/springfox/springfox-demos/) project [has examples](https://github.com/springfox/springfox-demos/tree/master/spring-java-swagger)
