### ISSUE TITLE
Request header content type set to application/xhtml+xml instead of application/json

### ISSUE THREAD

**Issue by YLombardi** [springfox/springfox#1020]
I use swagger2 with to document my spring boot application.
When I call the url : http://myapplication/v2/api-docs, the request header says that it accept XML but the api return json.
Here is my configuration :

```java
@Configuration
@EnableSwagger2
public class Swagger2Config {

@Bean
public Docket welcomeMessageApi() {
    return new Docket(DocumentationType.SWAGGER_2)
            .apiInfo(apiInfo())
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(PathSelectors.any())
            .build();
}

private ApiInfo apiInfo() {
    return new ApiInfoBuilder()
            .title("My API")
            .description("Lorem Ipsum is simply dummy text of ...")
            .termsOfServiceUrl("an url")
            .contact("contact")
            .license("")
            .licenseUrl("")
            .version("2.0")
            .build();
}
```

How can I set the request header to accept json ?

I also create a question on stackoverflow http://stackoverflow.com/questions/33211610/swagger-2-accept-xml-instead-of-json

**Comment by dilipkrish** [comment]
@YLombardi not sure I follow, Are you wanting an xml representation of swagger description? if so thats not possible as the swagger specification is a JSON specification. If you're wanting to set your accept header thats not related to this library.

**Comment by YLombardi** [comment]
I don't want XML. I want to set the accept header from xml to json. 
Maybe this is spring boot that set automatically the header to xml.

**Comment by dilipkrish** [comment]
@YLombardi Its your browser thats sending that information.
