### ISSUE TITLE
Add @JsonFormat support for date and time

### ISSUE THREAD

**Issue by YLombardi** [springfox/springfox#1021]
I use swagger 2 to document my project and I have an issue with the Date and Time attribute in my classes.

When I call the service myproject/v2/api-docs, I get this in the json : 

```java
"aString":{
    "type":"string"
},
"localDate":{
    "$ref":" #/definitions/LocalDate"
},
"localDateTime":{
    "$ref":"#/definitions/LocalDateTime"
},
"localTime":{
    "$ref":"#/definitions/LocalTime"
},
"anInteger":{
    "type":"integer",
    "format":"int32"
},
"sqlDate":{
    "type":"string",
    "format":"date"
}
```

Integer, String and java.sql.Date attributes display correctly, but localDate, localTime, java.sql.Time attributes doesn't not take the "format" parameter.

I have this code in my class : 

    @JsonFormat(pattern = "MM-yyyy-dd", shape = JsonFormat.Shape.STRING, timezone="CET")
    private LocalDate localDate;
    @JsonFormat(pattern = "HH:mm", shape = JsonFormat.Shape.STRING, timezone="CET")
    private LocalTime localTime;

**Comment by dilipkrish** [comment]
@YLombardi I think yr seeing this because we don't support `@JsonFormat` or atleast haven't tested with using it.

**Comment by zloster** [comment]
@YLombardi You could try to workaround this issue with addition of Swagger annotation:
```
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
// TODO currently the example setting is not processed by Springfox 2.2.2
@ApiModelProperty(dataType = "java.lang.String", example = "")
private LocalDate localDate;
```
I've used similar workaround for `java.util.Date` field which should be formatted only as `Date`.

**Comment by YLombardi** [comment]
@zloster Thanks for your answer.
I try your solution but it doesn't take account of the JsonFormat annotation.

I get this json : 
```json
 "localDate": 
{
    "type": "string"
}
```

Maybe there is an error in my swagger configuration.
I have this :

```java
@Configuration
@EnableSwagger2
public class Swagger2Config {
    @Bean
    public Docket welcomeMessageApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))
                .paths(PathSelectors.any())
                .build();
    }
}
```

**Comment by zloster** [comment]
@YLombardi No, it's not a error. I was not clear enough about the "workaround"  - I use the provided sample to instruct Springfox to treat the Date field as Swagger Specification string type. But in my case it was worth because I'm using java.util.Date for representation of both date and datetime and I can't use the programmatic configurations. So I've chosen to lost the date representation in Swagger.

**Comment by YLombardi** [comment]
@zloster Thanks for this clarification.

**Comment by cbornet** [comment]
@YLombardi @zloster you can use this:
```java
docket
.directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
.directModelSubstitute(java.time.ZonedDateTime.class, Date.class)
```
You will get
```json
                "localdate":
                {
                    "type": "string",
                    "format": "date"
                },
                "`localdatetime":
                {
                    "type": "string",
                    "format": "date-time"
                },
```
This is for java8's jsr310 but can also be used with joda

**Comment by cbornet** [comment]
@YLombardi note that there is no "time" format in swagger spec

**Comment by zloster** [comment]
@cbornet Thanks for the info.
