### ISSUE TITLE
Springfox swagger ui won't render 1.2 spec

### ISSUE THREAD

**Issue by koukiimonster** [springfox/springfox#1022]
I was asked to include both 1.2 spec and the 2.0 spec in a project that I'm involved in and I'm using Springfox 2.2.2 and Springfox-swagger-ui 2.2.2.

I have an issue where the 1.2 spec will not render in the swagger ui. The 2.0 spec will render fine and I can view the 1.2 JSON objects when hitting their respective default endpoints (/api-docs/default/**). 

When viewing the 1.2 spec from swagger-ui.html the page says "Finished loading resource information. Rendering Swagger UI..." and just sits there. 

Here's what I have for the swagger config:
```
@Configuration
@EnableSwagger
@EnableSwagger2
@ComponentScan(basePackages="org.business")
public class SwaggerConfig {
		
	
	   @Bean
	   public Docket api(){
	        return new Docket(DocumentationType.SWAGGER_2)
	            .select()
	            .apis(RequestHandlerSelectors.any())
	            .paths(PathSelectors.any())
	            .build()
	            .apiInfo(apiInfo());
	            
	    }

```

Is there something else I'm missing or am I doing something wrong?

**Comment by dilipkrish** [comment]
You need to add another docket unfortunately

```java
@Bean
       public Docket api(){
            return new Docket(DocumentationType.SWAGGER_12) //<---- this!
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo());

        }
```

**Comment by koukiimonster** [comment]
Here is what I have now:

```
@Configuration
@EnableSwagger
@EnableSwagger2
@ComponentScan(basePackages="org.business")
public class SwaggerConfig {
		
	
	   @Bean
	   public Docket api2(){
	        return new Docket(DocumentationType.SWAGGER_2)
	       	    .groupName("swagger2")
	            .select()
	            .apis(RequestHandlerSelectors.any())
	            .paths(PathSelectors.any())
	            .build()
	            .apiInfo(apiInfo());
	            
	    }
	   
	   @Bean
	   public Docket api(){
	        return new Docket(DocumentationType.SWAGGER_12)
	            .select()
	            .apis(RequestHandlerSelectors.any())
	            .paths(PathSelectors.any())
	            .build()
	            .apiInfo(apiInfo());
	            
	    }
```

After adding this in I get this in swagger-ui.html:

![api-docs](https://cloud.githubusercontent.com/assets/13238306/10729932/d00b3978-7bba-11e5-9d5d-afdc0e5eab31.PNG)

It seems that two dockets were made for each swagger spec and group when checking the dropdown:
![swagger-list](https://cloud.githubusercontent.com/assets/13238306/10729974/03e0572e-7bbb-11e5-95ff-eb629fed2265.png)

The 2.0 spec can be viewed fine but for the 1.2 spec it hangs on that rendering.

This is after adding the servlet mapping for "/*" since the swagger ui seems to look for the resources on the root context, although the api-docs are served under /rootContext/rest/. Without the mapping the resources for the 1.2 spec will not be found.

**Comment by dilipkrish** [comment]
You can add a custom path mapping per docket using the `pathMapping` method on the docket

**Comment by koukiimonster** [comment]
I've tried doing that and it works fine for the 2.0 spec. However the 1.2 spec generates incorrectly. 

When adding the path mapping to the 1.2 spec the paths for the individual resource listings are wrongly created. The paths get prefixed with "rest" like so:

```
/rest/default/service-controller
```

Swagger UI then looks for the individual resource listings at 
```
/api-docs/rest/default/service-controller
```
when "rest" needs to be at the beginning.

Another thing is that one of the api's resource path is generated incorrectly. 
The resourcePath seems to follow the base path and it is also empty, unless you have the path mapping which it then just shows that. 
```
"resourcePath":"/"
"resourcePath":"/rest"    <-- with rest path mapping
"resourcePath":"/Service"   <-- it should be this
```
Is there a way to specify the resourcePath in the 1.2 spec? How is the resourcePath generated?
Is it possible to generate both versions for the same api?

**Comment by dilipkrish** [comment]
Hmmm it might be a bug.. any particular reason you don't want to move to 2.0? feel free to re-open. However I really don't have the bandwidth to track this down
