### ISSUE TITLE
Provide a method for Model Properties to by sorted by configurable methods

### ISSUE THREAD

**Issue by nickpanaiotov** [springfox/springfox#1023]
Hi, there I trying to rearrange properties of some model in new spring boot application with only installed  spring-fox 2.2.2 and spring-fox-ui 2.2.2. 
Can you provide some demo in which this functionality works. 
Thank you.

pom.xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.2.7.RELEASE</version>
</parent>
<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-swagger2</artifactId>
	<version>2.2.2</version>
</dependency>
<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-swagger-ui</artifactId>
	<version>2.2.2</version>
</dependency>
</dependencies>

**Comment by dilipkrish** [comment]
This is a true statement. It currently sorts it alphabetically.

**Comment by nickpanaiotov** [comment]
I created function in ApiModelPropertyPropertyBuilder which allows the @ApiAnotationProperty to get value for position. Also sorted model properties by this value in DefaultModelProvider.modelFor(), but still something in chain after that reorder them.

**Comment by dilipkrish** [comment]
@nickpanaiotov Currently properties are [sortable](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ModelMapper.java#L120) using [_position and then by name_](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/Properties.java#L106). I would think this to be sufficient for this use case. Closing this issue as fixed. Please feel free to re-open if you think you still have a case where this isn't satisfying your need.
