### ISSUE TITLE
Swagger Ui is not working in Firefox and IE

### ISSUE THREAD

**Issue by sankarku** [springfox/springfox#1024]
Swagger UI is not working in Firefox and IE . I was getting below java script error .

XML Parsing Error: not well-formed
Location: http://localhost:8080/swagger-ui.html
Line Number 52, Column 22:            if (key && key.trim() != "") {
---------------------^

Can you please help me on this . 
Note : I have not customized index.html.

**Comment by nickpanaiotov** [comment]
Which versions of swagger-ui and Firefox you are using ?

**Comment by sankarku** [comment]
springfox-swagger-ui : 2.2.2
Firefox: 41.0.2

**Comment by dilipkrish** [comment]
This is possibly fixed in 2.2.3. Would you mind trying 2.2.3-SNAPSHOT?

**Comment by sankarku** [comment]
No luck. its not working in Firefox.

**Comment by sankarku** [comment]
similar problem like  #1020

**Comment by dilipkrish** [comment]
Not sure whats error you're getting. did you try with the snapshot?
