### ISSUE TITLE
How to make default all types required and only some not required ?

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#1028]
Given

A controller method
```java
import javax.validation.Valid;
@RequestMapping(method = RequestMethod.PUT)
public void create( @RequestBody @Valid MyDTO myDTO) {
    // do something with myDTO
}
```

A command object

```java
public class MyDTO {

    private long myId;

    private Long myId2;

    private String myValue;

    private Optional<String> myValue2;
}
```
Optional - http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Optional.html
or it could be a custom class

should be
```
MyDTO {
   myId (long, required=true),
   myId2 (long, required=true),
   myValue (string, required=true)
   myValue2 (string, required=false)
}
```

Thanks.

**Comment by dilipkrish** [comment]
To do this, you'd have to 
- add an alternate type rule for `Optional<T>` see `genericModelSubstitutes` in docket
- implement your own [ModelPropertyBuilderPlugin](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/schema/ModelPropertyBuilderPlugin.java#L26) and override the read only property if you find an `Optional` type. See [here](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/schema/ApiModelPropertyPropertyBuilder.java#L35) for an example. Keep in mind that you need the plugin to fire after this plugin... so order it accordingly
