### ISSUE TITLE
Content-Type not being set

### ISSUE THREAD

**Issue by mherb63** [springfox/springfox#1029]
Downloaded Swagger Pet Store (Simple) and did a mvn jetty:run

When opening up DevTools on Chrome, I don't see the header Content-Type field being set.  

This is on the GET /pets{id}

![image](https://cloud.githubusercontent.com/assets/1205814/10849742/7b2b7d96-7ef8-11e5-984c-fc19937f5c18.png)

**Comment by dilipkrish** [comment]
When you say 

> Downloaded Swagger Pet Store (Simple) and did a mvn jetty:run

Where did you download it from. Are you referring to the swagger editor?

**Comment by mherb63** [comment]
Yes, http://editor.swagger.io <http://editor.swagger.io/> with the sample pet store(simple) project loaded.  Download a spring-mvc server

**Comment by mherb63** [comment]
Bump.

Any chance we can get someone to look at this and provide a work-around?   

We (the Metro Ethernet Forum) are building our common model and API using this swagger and springfox architecture.  This model will be showcased at the GEN 15 Hackathon in Dallas in 2 weeks:  https://www.gen15.com/index.php/LSO-Hackathon/gen15-lso-hackathon.html

Our idea is to give a working model/api to developers and let them build Restful services that implement this model.  But, right now, we are stuck on this and a couple of other minor issues which we could probably work-around but this one is preventing us from moving forward.

Any help would be appreciated.

Thanks,

Mike

**Comment by dilipkrish** [comment]
I'd be happy to help with anything u need for the hackathon, plus I'm local to Dallas!

That said the problem with the code gen tool is that it's using an older version of springfox. I think just upgrading to version 2.2.2 would fix quite a few issue. Hit me up on gitter if u have questions

**Comment by mherb63** [comment]
We're having this issue with our application using 2.2.2 and 2.2.3-SNAPSHOT.  I modified the spring-mvc-server pom.xml for petstore simple to use either of these and the issue still exists.

I will try to reach out on gitter.

**Comment by mherb63** [comment]
OK, found the root cause of this problem thanks to wing328 on the swagger codegen project on github.

It turns out that at the top of our yaml definition file we have:

<pre>
consumes:
 - application/json
</pre>
That causes all generated controller methods to expect application/json on content-type. This breaks GET, DELETE, and PATCH api calls which in our case do not have any payload.
