### ISSUE TITLE
How do I force the generated swagger.json to preserve the reverse proxy host?

### ISSUE THREAD

**Issue by jbabuscio** [springfox/springfox#1030]
My consumers will retrieve through two unique proxy paths: 1) webapp.proxy.com and 2) externalsystem.proxy.com

My service that is using springfox-swagger2 lives at webserver1.com.  When the swagger-ui (using relative paths or not) requests the http://webapp.proxy.com/myservice/v2/api-docs.json, it returns the host http://webserver1.com/myservice/v2/api-docs.json.  

Can it preserve the incoming request so any codegen calls or "try it now" will actually work?  The main problem is that the firewall and authentication pass-through prevents users from directtly hitting the webserver1 so it's useless other than reading from the swagger-ui.

**Comment by dilipkrish** [comment]
This should be available in v2.3 thanks [to this PR](https://github.com/springfox/springfox/pull/1011) by @cbornet
