### ISSUE TITLE
problem with enums rendering on ui

### ISSUE THREAD

**Issue by mherb63** [springfox/springfox#1031]
I have the following defined in yaml:

![image](https://cloud.githubusercontent.com/assets/1205814/10859578/3ccd832c-7f35-11e5-84fd-7cf0e08d6615.png)

yet it shows up like this: 

![image](https://cloud.githubusercontent.com/assets/1205814/10859569/1bdbab58-7f35-11e5-9f3b-6cc9e8fbae64.png)

anyone else seen this type of problem?  Is the yaml wrong?

Thanks!

**Comment by dilipkrish** [comment]
This seems like a bug in codegen as well
