### ISSUE TITLE
Questions of ApiModelProperty and it's real ui content

### ISSUE THREAD

**Issue by zhugw** [springfox/springfox#1032]
I'm a back-end developer, latest project(use spring boot) we used swagger2 to expose Api to front-end. I have to say swagger is very powerful. But still have some problems puzzle me. For example, I have a Form Object
```
@Data
@ApiModel("GoodsCategoryForm")
public class GoodsCategoryForm {
  @ApiModelProperty(value = "Father id, if it is root category then value should be 0", required = true)
  private int fid;

  @Length(min=1,max = 10)
  private String name;

  @ApiModelProperty(value = "Status", allowableValues = "0-disabled;1-enabled")
  private byte status;

  @ApiModelProperty(value = "The smaller the value, the higher the priority")
  private int priority;
}
``` 
In Swagger UI(http://localhost:8080/swagger-ui.html) Model | Model Schema, it looked like this
``` 
{
  "fid": 0,
  "name": "string",
  "priority": 0,
  "status": "0-disabled;1-enabled"
} 
```
It seems value in ApiModelProerty does't work.Actually I expect the ui effect like below:
```
@ApiModel("News Entry")
public static class NewsEntry {
    @ApiModelProperty(value = "the id of the item", required = true)
    private long id;
    @ApiModelProperty(value = "content", required = true)
    private String content;
}
Model
NewsEntry{
  id(integer): the id of the item,
  content(string): content
}
```
So I don't know how to let my model scheme like below? In addtional, if I change status's type from byte to int, allowableValues does't work,now ui content is
```
  @ApiModelProperty(value = "Status", allowableValues = "0-disabled;1-enabled")
  private int status;

{
  "status": 0
}
```
My swagger dependencies is below,
```
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>2.2.2</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>2.2.2</version>
			</dependency>

```

**Comment by dilipkrish** [comment]
@zhugw for one the allowable values should be comma separated not semi-colon separated 

> So I don't know how to let my model scheme like below? In addtional, if I change status's type from byte to int, allowableValues does't work,now ui content is

Only enums and string types support allowable values. for ints we use ranges. So it might have a value like `"range[1,6]"`
