### ISSUE TITLE
Corrupt file in springfox-swagger-ui maven repo package: droid-sans-v6-latin-700.eot

### ISSUE THREAD

**Issue by the-james-burton** [springfox/springfox#1033]
I had a tricky issue in my company recently. I was unable to download the springfox-swagger-ui-2.1.2 package through the corporate firewall. The Kaspersky virus checker was complaining of a corrupt file. The McAfee checker on my workstation did not report any problem. Thinking this was a bug on their side, we raised an issue and Kaspersky investigated. 

They found that the droid-sans-v6-latin-700.eot file in the springfox-swagger-ui package is corrupt and their virus checker could not scan it, so I was not allowed to download it (and therefore neither was maven).
http://repo1.maven.org/maven2/io/springfox/springfox-swagger-ui/2.1.2/springfox-swagger-ui-2.1.2.jar

Still skeptical, I decided to try https://onlinefontconverter.com/ to convert the droid-sans-v6-latin-700.eot file in your package to a TTF. The conversion failed, although a conversion of the same font in the Kubernetes package works...
https://github.com/kubernetes/kubernetes/blob/master/third_party/swagger-ui/fonts/droid-sans-v6-latin-700.eot

Can you please check the droid-sans-v6-latin-700.eot file in your package? After this lengthy investigation, I think it is corrupt.

Regards,
James

**Comment by the-james-burton** [comment]
Same issue with 2.2.2, by the way.

**Comment by dilipkrish** [comment]
This seems to be an issue with the [swagger-ui packages](https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.3)... Might want to check with that project what the issue is.

**Comment by the-james-burton** [comment]
Ok, thanks. I will raise an issue in their project.

**Comment by the-james-burton** [comment]
[Issue raised](https://github.com/swagger-api/swagger-ui/issues/1728) in swagger-ui project.
