### ISSUE TITLE
Body parameters break Swagger UI

### ISSUE THREAD

**Issue by dejewi** [springfox/springfox#1034]
Hi,

I use the newest Springfox version (2.2.2). I have one body parameter (Boolean leg) which cause problem: the Swagger UI is not showing me any data and I have visible information:
`Finished Loading Resource Information. Rendering Swagger UI...`

in the browser console I can see error:
`Uncaught TypeError: Cannot read property 'toLowerCase' of undefined(anonymous function) @ swagger-ui.min.js:13`

My REST endpoint looks like:
```java
@RequestMapping(value = "/pet/{petId}/legs", method = PUT)
@ApiOperation(value = "Set leg param for pet", notes = "Set leg for pet and return pet", response = Pet.class)
@ApiResponses(value = @ApiResponse(code = 404, message = "pet not found"))
public ResponseEntity setPetLeg(@PathVariable("petId") String petId, Boolean leg) {
```
In api-docs this `Boolean leg` parameter looks:
```javascript
{
    "in": "body",
    "name": "leg",
    "description": "leg",
    "required": false,
    "schema": {
        "type": "boolean"
    }
}
```

**Comment by dilipkrish** [comment]
Body parameters that are primitives will surely break swagger-ui. This is an issue with swagger-ui

**Comment by Walter0507** [comment]
@dilipkrish How to fix this error? Even change Boolean into boolean, swagger ui still show errors.
