### ISSUE TITLE
Unexpected characters in generated spec file.

### ISSUE THREAD

**Issue by smwurster** [springfox/springfox#1036]
When using springfox-swagger2, version 2.2.2, the generated spec file is showing guillemets (i.e. french quotes: «, ») in the spec file for certain generic-based request and response types.  This ends up completely breaking code generation because those characters are obviously invalid.

An example that shows this behavior is a response class that contains the following definition: `List<Status<?>> itemStatuses`.  The JSON spec file will show that inner type as `Status«object»`.  Those are single-glyph guillemets instead of single `<` and `>` characters.

Another issue occurs where the response is a `List<Map<String, Object>>`.  This gets generated in the JSON spec file as `Map«string,object»`.

Both of these break code generation (w/ swagger-codegen) and also just seem to be invalid anyway.  Any idea what is causing this and if there is anything I can do to work around it?

Thanks.

**Comment by dilipkrish** [comment]
Please use `forCodeGeneration` in your dockets

**Comment by smwurster** [comment]
That did it, thanks!

**Comment by dilipkrish** [comment]
:+1:
