### ISSUE TITLE
JSON in to Swagger documents

### ISSUE THREAD

**Issue by Rameeshchandran** [springfox/springfox#1040]
I have to include my JSON schema to the swagger documentation.I have tried with Swagger2markupconvertor and I was not able to include my Json to the generated documents. I have done something like : 
 Swagger2MarkupConverter.from(swagger.json)
.withSchemas(schemaDirectory)
.withMarkupLanguage(MarkupLanguage.ASCIIDOC)
.build()
.intoFolder(outputDirectory);

swagger.json : - Local swagger json
schemaDirectory : - Directory where my json schema resides

The documents (definitions,overview and path) are created successfully but the json schema is not included in them.
Does swagger provides the feature to include the local json schema to the generated documents ?
If so please provide me with some samples.

**Comment by dilipkrish** [comment]
@RobWin any idea what needs to happen here?

**Comment by RobWin** [comment]
Yes, sry. Its not well documented yet.
You have to create a schemaDirectory as you did, but you have to create a JSON Schema per Model Definition so that Swagger2Markup can find the correct Schema file.

For example, if you have a `User` definition model in your Swagger file, you have to place a `User.json` into the schemaDirectory folder.

PR welcome to improve the usability :D

**Comment by Rameeshchandran** [comment]
@RobWin Thanks!
It will be nice if you can provide some examples as this scenario doesn't have examples for us.

**Comment by RobWin** [comment]
I personally don't create the Json Schema by hand, but generate it in the unit tests via:
```
public <T> void documentJsonSchema(Class<T> documentedClass, String schemaOutputDirectory) throws IOException {
        Files.createDirectories(Paths.get(schemaOutputDirectory));
        SchemaFactoryWrapper visitor = new SchemaFactoryWrapper();
        objectMapper.acceptJsonFormatVisitor(objectMapper.constructType(documentedClass), visitor);
        JsonSchema jsonSchema = visitor.finalSchema();
        try (BufferedWriter writer = Files.newBufferedWriter(Paths.get(outputDir, subDir, documentedClass.getSimpleName() + ".json"),
                StandardCharsets.UTF_8)){
            writer.write(objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(jsonSchema));
        }
    }
```

**Comment by RobWin** [comment]
Btw. if you like and use Springfox and Swagger2Markup. We would like to get your GitHub stars.

**Comment by RobWin** [comment]
If you have an existing JSON Schema, the easiest solution would be to create a `schema.adoc` file and copy the content into the AsciiDoc file.
Then include the file into your `index.adoc` as follows:

include::overview.adoc[]
include::paths.adoc[]
include::definitions.adoc[]
include::schema.adoc[]

**Comment by Rameeshchandran** [comment]
@RobWin Thanks!! 
I'm not sure about Asciidoc. First I'll check with the json schema.
Thank you for the support.

**Comment by Rameeshchandran** [comment]
@RobWin I'm using Jackson in the code. But the json schema is used for the documentation purpose so that the others can get idea about the request/response structure and values.

**Comment by RobWin** [comment]
Do you use Swagger2Markup to generate HTML/PDF documentation based on AsciiDoc?
Why are you not sure about AsciiDoc?

**Comment by RobWin** [comment]
You can also use https://github.com/spring-projects/spring-restdocs to create real-live snippets of your request and response message via unit tests.

**Comment by Rameeshchandran** [comment]
@RobWin Thanks.. I've generated the PDF docs based on the generated asciidoc. Thanks for the link too.. It seems to be helpful

**Comment by dilipkrish** [comment]
@RobWin thanks for helping out! :metal:

**Comment by RobWin** [comment]
Can the ticket be closed?

**Comment by Rameeshchandran** [comment]
The issue is solved for me :+1:
