### ISSUE TITLE
Springfox-Swagger doesn't know how differentiate a request with header

### ISSUE THREAD

**Issue by fsnasser** [springfox/springfox#1043]
I was integrating Springfox-Swagger with my REST API and I had the following issue: Springfox-Swagger doesn't know how to differentiate when I create multiple @RequestMapping with the same value but with different header. E.g.:

No version:

	@RequestMapping(value = "test", method = RequestMethod.GET)
	public ResponseEntity<?> test() {
		...
	}
---

Version 1.0:

	@RequestMapping(value = "teste", headers = "Version=1.0", method = RequestMethod.GET)
	public ResponseEntity<?> test1() {
		...
	}
---

Version 2.0

	@RequestMapping(value = "teste", headers = "Version=2.0", method = RequestMethod.GET)
	public ResponseEntity<?> test2() {
		...
	}

This way is not possible to document different versions when the version is sent by header.

**Comment by dilipkrish** [comment]
This is a problem in the swagger spec. Unfortunately this cannot be represented in the specification
