### ISSUE TITLE
Control over swagger contact object

### ISSUE THREAD

**Issue by smwurster** [springfox/springfox#1046]
The `ApiInfo` class has a setter/getter for `contact`.  This ends up being translated into the `contact` object in the swagger spec.  However, this value is always assumed to be the `name` field within that object.  I would like to be able to completely control the `contact` object, including having the ability to define the `email` field and clear out the `name` field.

**Comment by dilipkrish** [comment]
That is a true statement! thanks for pointing that out. A PR would be awesome!

**Comment by smwurster** [comment]
I doubt I can create a PR that would be accepted as-written.  However, if I have time, I might at least be able to create the POJO for the `Contact` class and look into adjusting `ApiInfo` to reflect that.
