### ISSUE TITLE
Missing schema definitions from Controller params

### ISSUE THREAD

**Issue by gaplo917** [springfox/springfox#1047]
Version used 2.2.2
The model definitions is missing in the swagger.json.

sample code
```

  public class MyModel{
    @NotNull
    public String test;

    public String getTest() {
      return test;
    }

    public void setTest(String test) {
      this.test = test;
    }
  }

  @RequestMapping(value = "/api/v1/mymodel",method = RequestMethod.POST)
  public ResponseEntity<String> GetMyModel(
      @Valid MyModel myModel
  ) {
    return ResponseEntity.ok(myModel.getTest());
  }
```

![screen shot 2015-11-10 at 19 19 18](https://cloud.githubusercontent.com/assets/5468398/11061172/09ce66d6-87e0-11e5-9abc-848e9bb9c5ab.png)

---

if I do some hack and change the code into the followings, the model definition can be read. Spring-fox probably ONLY parse `MyModel` to schema definition if it is a response but not a controller parameter.

```
  public class MyModel{
    @NotNull
    public String test;

    public String getTest() {
      return test;
    }

    public void setTest(String test) {
      this.test = test;
    }
  }

  @RequestMapping(value = "/api/v1/mymodel",method = RequestMethod.POST)
  public ResponseEntity<MyModel> GetMyModel(
      @Valid MyModel myModel
  ) {
    return ResponseEntity.ok(myModel);
  }
```
![screen shot 2015-11-10 at 19 22 36](https://cloud.githubusercontent.com/assets/5468398/11061238/97319df4-87e0-11e5-99d6-fdf5d59d79bc.png)

I think it is common to use xxxxRequest Model in the controller to get the JSON request from front-end and Spring with handle the binding JSON -> model.

**Comment by dilipkrish** [comment]
You need to annotate your first example with the `@RequestBody` Annotation in addition to the `@Valid`

**Comment by gaplo917** [comment]
Thanks for your response.

Just notice that the model definition will show after adding `@RequestBody`

However, using a custom object as a controller  parameter for request binding have two scenario:
 
1. As you said, if `@RequestBody` is added, Spring will ONLY allow `application/json` request. (Spring-fox handle it very well)
Sample request 
```
curl -X POST \
-H "Content-Type: application/json" \
-H "Cache-Control: no-cache" \
-d '{
    "test":"test"
}' 'http://localhost:8080/api/v1/mymodel'
```


2. if `@RequestBody` is NOT added, Spring will ONLY allow `application/x-www-form-urlencoded` request and do the auto binding requestKey <-> parameterName (Spring-fox not yet handle this case)

sample request 
```
curl -X POST \
-H "Cache-Control: no-cache" \
-H "Content-Type: application/x-www-form-urlencoded" \
-d 'test=test' 'http://localhost:8080/api/v1/mymodel'
```

It would be nice if spring-fox can handle both two case for those people who use it to generate API documentation for frontend devs :+1

**Comment by dilipkrish** [comment]
@gaplo917 This is totally supported, if you want it to be form url encoded, you can annotate the parameter with the `@ModelAttribute` annotation and optionally set the `@RequestMapping#consumes` to support `application/x-www-form-urlencoded` media type.

**Comment by gaplo917** [comment]
Great! It works by adding `@ModelAttribute`

**Comment by seancarroll** [comment]
I'm likely missing something but with version 2.4.0 using `@ModelAttribute ` with `@RequestMapping#consumes` set to `application/x-www-form-urlencoded` parameters with type QueryParameter 

```
    @RequestMapping(value = "/customer/{customerCode}/account}", method = RequestMethod.POST, consumes = "application/x-www-form-urlencoded")
    public AccountDTO updateAccount(@Valid @ModelAttribute UpdateAccountCommand command) {
    	return dispatcher.send(command);
    }
```

**Comment by dilipkrish** [comment]
@seancarroll for model attributes to work when using spring fix they need to have bean properties with ___BOTH___ getters and setters. If thats not your issue please elaborate the problem yr facing and create a new issue if this is not your issue.

**Comment by seancarroll** [comment]
I think the problem is that my UpdateAccountCommand extends a base class and if I understand issue [issue 868](https://github.com/springfox/springfox/issues/868) inheritance isn't supported. I'll try and replicate the issue in a simpler example and if necessary open a new issue if required

**Comment by dilipkrish** [comment]
That is a :100: % true statement about polymorphism and inheritance
