### ISSUE TITLE
Regular expressions with curly brackets in @RequestMapping breaks Swagger UI TryItOut URL

### ISSUE THREAD

**Issue by mrashisha** [springfox/springfox#1049]
Thanks for the great work!

I am just reporting a small bug and I have added some code to make it easier to reproduce the issue. Please look at 
https://github.com/mrashisha/springfox-demos/commit/a8d56bee08875fff305b202b4457f636dbe5a50c

When looking at the **category-api** section for Swagger2 and more specifically when trying out the **getById_anotherQuanitifer** operation, with an id value of 23, I get the following result

![screen shot 2015-11-11 at 2 39 28 pm](https://cloud.githubusercontent.com/assets/4650963/11102445/2ecad080-8882-11e5-9981-af7395af665f.png)

The root cause is the extra curly brace in the URL:
> @RequestMapping(value="/category/Resource4/{id:\\d{2}}", method=RequestMethod.GET)

**Comment by dilipkrish** [comment]
what version are you using? This may have been fixed in the snapshot

**Comment by mrashisha** [comment]
When I reported this issue, I had tested this against 2.2.2

After your comment, I retested against 2.2.3-SNAPSHOT and yes the issue appears to be fixed. 

Any rough idea on when the next version will be released?

**Comment by dilipkrish** [comment]
:+1: hopefully this week

**Comment by mrashisha** [comment]
Thanks
