### ISSUE TITLE
springfox swagger2 modify host url

### ISSUE THREAD

**Issue by ChrisDevX** [springfox/springfox#1050]
Hi,

im using @EnableSwagger2 in my spring application. Currently i try to find a way to override the base url of the rest interface. So the Swagger UI (try it out) is able to send the request to my load balancer.

That’s the issue the actual request url is:
http://localhost:1234/myApi
it should look like this:
http://mydomain:1234/abc/myApi

i tried o modify the Docket(DocumentationType.SWAGGER_2) but until now without any solution.

**Comment by dilipkrish** [comment]
If you use the `Docket#pathMapping` it should fix your problem. specifically in your case `docket.pathMapping("/abc")`

**Comment by ChrisDevX** [comment]
pathMapping only enables the subpath "abc" the bigger issue to change the url to my domain
"http://mydomain" to forward all request to the loadbalancer

**Comment by RobWin** [comment]
Could you please elaborate your issue? 
You mean that the basePath should look like this?

`"basePath": "http://mydomain:1234/abc"`

**Comment by ChrisDevX** [comment]
yes exactly, i need http://mydomain:1234/abc as request url for the swagger ui ("try it out button")

the reason is is following. My App run on 3 different servers
http://localhost_1:1234/myApi
http://localhost_2:1234/myApi
http://localhost_3:1234/myApi

All requests even form the swagger ui should go against the loadbalancer in front.
http://mydomain:1234/abc/myApi

**Comment by RobWin** [comment]
Same issue here +1

**Comment by RobWin** [comment]
Btw: Use swagger2markup.readme.io instead of swagger-ui and you can change whatever you want.

**Comment by ChrisDevX** [comment]
Nope the "abc" is based on the routing form the load balancer and is used to specify different domains.

**Comment by RobWin** [comment]
Yes, but can't you run your applications under the same domain as the context path?

**Comment by ChrisDevX** [comment]
unfortunately not, because the load balancer adds "abc" to the routing by itself.
if i would add it to the application http://localhost_1:1234/abc/myApi

the final url would look like this automatically
http://mydomain:1234/abc/abc/myApi

**Comment by RobWin** [comment]
Means: you can't change the routing table (balancing group) of the load balancer?

**Comment by ChrisDevX** [comment]
yes because it doesn’t solve the problem. i need something like "abc" for proper routing.

I still need an option to tell swagger ui to call request against a specifically url

**Comment by dilipkrish** [comment]
@ChrisDevX We added a feature to override the [host name per docket](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L217-L221), this is still in incubation, would you mind giving it a whirl and see if that solves your problem? 

:memo: this is in 2.2.3-SNAPSHOT

/c @RobWin

**Comment by ChrisDevX** [comment]
@dilipkrish thx for the snapshot !
how can i add this snapshot as dependency to my pom?

**Comment by shardt68** [comment]
we fixed is by setting the header attribute x-forwarded-host in the "loadbalancer", so you don't need to set it in the implementation

**Comment by dilipkrish** [comment]
@shardt68 thats the recommended way to fix it
