### ISSUE TITLE
swagger-ui.html not accessible in a Spring-MVC setup with SpringFox

### ISSUE THREAD

**Issue by ankit2711** [springfox/springfox#1057]
I have a similar issue as documented in the closed #983 with a spring-mvc and springfox integration. 
The project is not using Spring boot.

I can access 
http://localhost:8080/<context>/v2/api-docs 
and it shows the JSON with all my REST controllers scanned.

But when accessing http://localhost:8080/<context>/swagger-ui.html I get a 404 error.

I already have mvc:default-servlet-handler/ added in my servlet.xml file.

Below my configuration
servlet.xml
<mvc:annotation-driven>
	<mvc:message-converters>
		<bean class="com.hi.cdi.http.converter.CsvMessageConverter"></bean>
	</mvc:message-converters>
</mvc:annotation-driven>

<mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/" />
<mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/" />
	
<mvc:default-servlet-handler />

<context:component-scan base-package="com.hi.cdi.v1.controller" />
<context:component-scan base-package="com.hi.cdi.hm.controller" />

SwaggerConfig.java
@EnableSwagger2
public class SwaggerConfig {
@Bean
public Docket customImplementation() {
return new Docket(DocumentationType.SWAGGER_2);
}
}

applicationContext.xml has the swagger bean definition
<bean name="/swaggerConfig" class="com.hi.cdi.swagger.SwaggerConfig" />

NOTE: I also have Spring-security applied on the /* and have ways to by pass some URL's. I have bypassed /v2/api-docs. Are there any URL patterns I must bypass security for to access 
localhost:8080/<context>/swagger-ui.html

Would appreciate your help, already struggled for more than a day to get this working.

**Comment by dilipkrish** [comment]
Have you looked at [the answer to this question](http://springfox.github.io/springfox/docs/snapshot/#answers-to-common-questions-and-problems)? :point_down: 

* How does one configure swagger-ui for non-springboot applications? *
