### ISSUE TITLE
@ModelAttribute object is not mapped when the setters are not void

### ISSUE THREAD

**Issue by diegogargaro** [springfox/springfox#1058]
I have this controller:
```
@RestController
public class TestController {
    public Result find(@ModelAttribute SomeFilters filters) {
        ...
    }
}
```
If the POJO for the ModelAttribute has the setters like this (returning itself):
```
public class SomeFilters {
    private String param;
    
   public SomeFilters setParam(String param) { this.param = param; return this; }
   public SomeFilters getParam(String param) { this.param = param; }
}
```
It will not map the property **param** as a QueryParameter. The only way that works is if the setter  returns void:
```
public void setParam(String param) { this.param = param; }
```

Is this a known problem / limitation? I didn't find any reference about this.

Thanks!
Diego

**Comment by dilipkrish** [comment]
That is by design. Have you looked at [this section in the documentation](http://springfox.github.io/springfox/docs/snapshot/#answers-to-common-questions-and-problems)?

Only properties that conform to the bean spec are supported.

**Comment by diegogargaro** [comment]
Yes I did. About the bean spec (http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/), if I didn't misread it doesn't say anything about  the setters must return void.
If the Spring Framework understand the properties this way, wouldn't be better if Springfox do the same? This way if anyone who has a running spring application wants to add documentation to it, won't have the need to refactor the code to work.

Anyway, this is a suggestion. This API is awesome with or without this behavior!
