### ISSUE TITLE
Support @RequestParam of type Map<String, String>

### ISSUE THREAD

**Issue by matias2681** [springfox/springfox#1061]
Hi, 

I have a project that is using Spring Cloud and the class [EnvironmentManagerMvcEndpoint.java](https://github.com/spring-cloud/spring-cloud-commons/blob/a6124e7063d924fe192b435e98e1a4c9874410ec/spring-cloud-context/src/main/java/org/springframework/cloud/context/environment/EnvironmentManagerMvcEndpoint.java) seems to be generating a wrong swagger file. The method value (POST) with a parameter that is a Map is mapped as this: 
```
"parameters":[
   {
      "name":"params",
      "in":"query",
      "description":"params",
      "required":true,
      "type":"ref"
   }
]
```
The type:ref makes the file invalid, I tried changing to "string" instead of "ref" and it results in a valid swagger file. 

I also run the debugger that you have available in http://online.swagger.io/validator/debug and I had this error message.

```
[
   {
      "level":"error",
      "domain":"validation",
      "keyword":"oneOf",
      "message":"instance failed to match exactly one schema (matched 0 out of 2)",
      "schema":{
         "loadingURI":"http://swagger.io/v2/schema.json#",
         "pointer":"/definitions/parametersList/items"
      },
      "instance":{
         "pointer":"/paths/~1env/post/parameters/0"
      }
   }
]
```

I created this [project](https://github.com/matias2681/swagger-example-issue) where you can see the problem.

I would like to know if there is a workaround to make this works.
Thanks

**Comment by dilipkrish** [comment]
Thanks for the detailed issue :metal: It will likely not be soon that this is fixed, but ill definitely take a look

**Comment by matias2681** [comment]
Glad to help! 

I can take a look at the code and see what's going on. Do you have a pointer to the code where the problem might be? that would be helpful.

**Comment by dilipkrish** [comment]
@matias2681 I'm unable to see the endpoint in your project. Are you sure you've committed and pushed all the changes to your project?

**Comment by matias2681** [comment]
@dilipkrish I added a readme file to the project. I cloned and I could reproduce the issue. All the endpoints are inside the `initial` folder.

**Comment by dilipkrish** [comment]
ah! I was using the gradle file instead of the maven pom.

I narrowed it down to the endpoint exposing a patter we don't support yet...

specifically

`requestMapping(@RequestParam Map<String, String> params)` we currently only support Maps as `@RequestBody` (and may be as a url encoded form data). I'll create a feature to address this

**Comment by pathikmehta** [comment]
Are there any documentation available to see how to test (@RequestParam Map<String, String> params) params from swagger ui HTML page?

**Comment by dilipkrish** [comment]
It is an *any* type... so you can basically send any arbitrary json with key value pair of string type and it will work.

For e.g.
```json
{
    "a" : "hello",
    "b" : "world"
....
}
```

**Comment by pathikmehta** [comment]
Thank you @dilipkrish.

**Comment by chrisinmtown** [comment]
Yes you can send anything, but the Swagger "try it out" feature doesn't allow me to edit the parameter names as I need to do.

**Comment by dilipkrish** [comment]
@chrisinmtown Strictly per spec, `@RequestParam Map<String, String>` is not supported. thats why the UI will not support it either

**Comment by senthilprabhut** [comment]
@dilipkrish 
I tried annotating the Map<String,String> with  the below annotation
@ApiImplicitParam(name = "urlQueries", dataType = "any", paramType = "query", value = "urlQueries", required = false)

Swagger UI shows a text box where I specified the query in the format   { "a" : "b" }
I was hoping that the request generated by swagger ui will be   /host/path?a=b

Instead I get the request as /host/path?urlQueries=%7B%20%22a%22%20%3A%20%22b%22%20%7D

Is there a documentation where I can look into for configuring the "any" type and invoking from swagger ?

**Comment by kapishmalik** [comment]
It still does not support this feature ?

**Comment by dilipkrish** [comment]
@kapishmalik what is not supported, please report a different issue with additional details, this is an issue pertaining to v2.4.0.
