### ISSUE TITLE
Springfox generates empty types in the definitions (which swagger-codegen struggles with)

### ISSUE THREAD

**Issue by mattsheppard** [springfox/springfox#1063]
I have an api where some of the arguments/return-types refer to interfaces rather than concrete classes. When springfox (2.2.2) produces the swagger JSON schema for them, it is producing something like this...

```
{
   "swagger":"2.0",
   "host":"example.com",
   "basePath":"/api",
   "paths":{
      "/example":{
         "get":{
            "responses":{
               "200":{
                  "description":"OK",
                  "schema":{
                     "$ref":"#/definitions/TriggerActions"
                  }
               }
            }
         }
      }
   },
   "definitions":{
      "TriggerActions":{
         "properties":{
            "actions":{
               "type":"array",
               "items":{
                  "$ref":"#/definitions/Action"
               }
            },
            "trigger":{
               "$ref":"#/definitions/Trigger"
            }
         }
      },
      "Action":{
      },
      "Trigger":{
      }
   }
}
```

That's proving inconvenient to me because swagger-codegen is unable to handle the empty definitions (See https://github.com/swagger-api/swagger-codegen/issues/1594). Since I realize there's no way for springfox to be able to know what implementations might exist, I appreciate there's no obvious 'right' answer here, but perhaps there's something which can be improved to work better with the codegen side?

Perhaps also worth nothing (or maybe it's a separate issue) - I tried to work around this manually using...

```
    @ApiModelProperty(dataType = "java.lang.Object")
```
...but unfortunately that seems to be ignored (as does "object" and a comma separated list of the types which do implement that interface). I'd have expected at least the java.lang.Object one to work.

**Comment by dilipkrish** [comment]
I'll investigate how this may be fixed. Thanks for reporting
