### ISSUE TITLE
Need to override basePath value 

### ISSUE THREAD

**Issue by shobhanandula** [springfox/springfox#1064]
Currently BasePath value is been set to applicationbasepath in the DocumentationBuilder. Need to overide ride this to a different value as the my dispatcher and service are running on different hosts.I need the basePath to show applicationbasepath of the dispatcher.
Need a pointer to modify DocumentationBuilder.

**Comment by RobWin** [comment]
Hi,
 duplicate of #1050.
Is this what you need `docket.pathMapping("/abc")`?

**Comment by shobhanandula** [comment]
No I am not looking at pathMapping. I need to set a custom basePath as the dispatcher is running on a different host . so i need to display the basepath as my dispatcher context root.

**Comment by dilipkrish** [comment]
@shobhanandula I think thats the responsibility of the load balancer to do the url re-writing no?

**Comment by dilipkrish** [comment]
Moving it to 2.4 as there is nothing really here to fix or support.

**Comment by ALEXSSS** [comment]
hi
I'm sorry for being a distraction
Can you provide the correct maven dependency. Or can you say if it is available on other versions?(:

**Comment by dilipkrish** [comment]
Correct maven dependency for what? The latest version is 2.5.0 however, This is just a question and is not a feature or a bug, to be available in a specific version.

**Comment by ALEXSSS** [comment]
i want to get to know in which version there is this functionality
i have already created issue(: i wrote this at the first time (sorry(: maybe you should delete this stupid comment
