### ISSUE TITLE
Disable appending of Using<Method>

### ISSUE THREAD

**Issue by rkaltreider** [springfox/springfox#1066]
How can i disable the appending of my methods with 
~~~
Using<Method>
~~~
.  All methods in my swagger doc have getPartnersUsingGet or similar.  I want to get rid of that.

**Comment by gionn** [comment]
http://springfox.github.io/springfox/docs/current/#docket-spring-java-configuration

5.5.2. Configuring the output of operationId in a Swagger 2.0 spec

**Comment by dilipkrish** [comment]
@rkaltreider There is not a way to get rid of that ... yet. I'll see how we can address that in 2.3 if possible. However keep in mind that you will end up with names like `someOperation_1`, `someOperation_2` etc. if there are multiple endpoints with the same nickname

@gionn I'll fix the documentation to reflect that.

**Comment by rkaltreider** [comment]
That sounds perfectly reasonable to me. I have taken the time to ensure all nicknames are unique and self descriptive. If I fail to solidify the uniqueness. I would expect it to make it unique however it sees fit. Thank you!

Sent from my iPhone

On Dec 1, 2015, at 10:26 AM, Dilip Krishnan <notifications@github.com<mailto:notifications@github.com>> wrote:


@rkaltreider<https://github.com/rkaltreider> There is not a way to get rid of that ... yet. I'll see how we can address that in 2.3 if possible. However keep in mind that you will end up with names like someOperation_1, someOperation_2 etc. if there are multiple endpoints with the same nickname

@gionn<https://github.com/gionn> I'll fix the documentation to reflect that.

-

**Comment by rajeshkamal** [comment]
Thanks @dilipkrish for the fix which I assume also fixes - #880 #990

**Comment by dilipkrish** [comment]
:+1:

**Comment by rkaltreider** [comment]
When do you think the next version will be released? I am anxious to upgrade!

Sent from my iPhone

On Dec 8, 2015, at 4:39 PM, Dilip Krishnan <notifications@github.com<mailto:notifications@github.com>> wrote:


[:+1:]

-

**Comment by dilipkrish** [comment]
Its already released see here for details [2.3.0](https://github.com/springfox/springfox/releases/tag/2.3.0)

**Comment by g-bon** [comment]
Apologies for resuscitating this old discussion. Is the solution to this the use of @ApiOperation to specify a differnt nickname on every operation or is there a way to disable this behavior completely? Thanks

**Comment by g-bon** [comment]
Thank you sir!
