### ISSUE TITLE
/v2/api-docs reback nothing  in the no spring-boot even.

### ISSUE THREAD

**Issue by jerryxing98** [springfox/springfox#1068]
My environment  : 
 Spring 3.2.7
 Spring mvc 3.2.7
 springfox 2.0.3
 jetty 1.6 

/swagger-ui.html  is OK.
/configuration/ui   is OK 
/swagger-resources is OK 

this is the Jetty Log : 

64063 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.web.servlet.DispatcherServlet - DispatcherServlet with name 'dispatcher' processing GET request for [/v2/api-docs]

64065 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Looking up handler method for path /v2/api-docs

64075 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Returning handler method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String)]

64075 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'swagger2Controller'

64076 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.web.servlet.DispatcherServlet - Last-Modified value for [/v2/api-docs] is: -1

64157 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.web.servlet.DispatcherServlet - Null ModelAndView returned to DispatcherServlet with name 'dispatcher': assuming HandlerAdapter completed request handling

64157 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.web.servlet.DispatcherServlet - Successfully completed request

64159 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'documentationPluginsBootstrapper'

64159 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'documentationPluginRegistry'

64159 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'apiListingBuilderPluginRegistry'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'operationBuilderPluginRegistry'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'parameterBuilderPluginRegistry'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'expandedParameterBuilderPluginRegistry'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'resourceGroupingStrategyRegistry'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'operationModelsProviderPluginRegistry'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'defaultsProviderPluginRegistry'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'default'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'objectMapperBeanPropertyNamingStrategy'

64160 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'optimized'

64161 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'beanModelPropertyProvider'

64161 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'constructorModelPropertyProvider'

64161 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'fieldModelPropertyProvider'

64161 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'modelBuilderPluginRegistry'

64161 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'modelPropertyBuilderPluginRegistry'

64161 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'typeNameProviderPluginRegistry'

64161 [2015-11-26 12:21:11 ] - GET /v2/api-docs [ip=127.0.0.1, ref=, ua=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36, sid=4J5WRW4T2-GIO5G4C8VRWEIY5QX4PW1-K9PT1DHI-0]
  DEBUG c.a.c.s.s.c.InheritableListableBeanFactory - Returning cached instance of singleton bean 'sqlSessionFactory'

**Comment by dilipkrish** [comment]
@jerryxing98 you're using a very old version of the library (2.0.3) and a currently unsupported version of spring (3.2.7). I would suggest using 1.0.2 to be compatible with spring 3.x. and 2.2.2 as of this writing if you're on 4.x
