### ISSUE TITLE
Model schema for springfox 2.2.2 doesn't seem to reflect @JsonUnwrapped annotations

### ISSUE THREAD

**Issue by mattsheppard** [springfox/springfox#1070]
I saw https://github.com/springfox/springfox/issues/192 was an issue previously, but I'm wondering if there's been a regression.

Specifically I'm seeing a model schema like...

```
{
  "data": {
    "nextPageNumber": 0,
    "summaries": [
      {
        "dateOfMonth": {
          "month": "string",
          "year": "string"
        },
        "count": 0,
      }
    ]
  },
  "errorMessage": "string"
}
```

...while the actual output looks like...

```
{
  "errorMessage": null,
  "data": {
    "summaries": [
      {
        "year": "2009",
        "month": "12",
        "count": 0
      },
      {
        "year": "2010",
        "month": "01",
        "countount": 0
      }
    ],
    "nextPageNumber": 1
  }
}
```

Being generated form a model class (down at the summary level) like this...

```
public class MonthSummary {

    @JsonUnwrapped
    @Setter private MonthDate dateOfMonth;
    @Setter private long count;
...
}
```

Where MonthDate has year and month properties.

I'd have expected the schema to reflect the fact that the @JsonUnwrapped annotation would cause those properties to appear at the higher summary level, not below under dateOfMonth.

**Comment by dilipkrish** [comment]
@mattsheppard I think the `@JsonWrapped` annotation is on the wrong accessor. Try switching it to be on the getter and see how that affects it.

**Comment by mattsheppard** [comment]
Ah, interesting point. So you think it's incorrect that it's affecting the output and the schema is correct? Or maybe I misunderstood how jsonunwrapped works and it must be on both the field and the getter, and lombok is hiding that from me most of the time... Anyway, thanks for the pointer, I'll poke around further and report back.

**Comment by snowe2010** [comment]
Hey @mattsheppard, what were your findings? We're also using Lombok and springfox and we're seeing this exact issue.

**Comment by mattsheppard** [comment]
Looking back at the code, it seems like I now have this in the model...

```
@JsonUnwrapped
@Getter @Setter private MonthDate dateOfMonth;
```

...and I believe it's working correctly, I'm not sure if I investigated any deeper than that - If I did, I don't remember discovering anything of note.

**Comment by snowe2010** [comment]
Hmm. that doesn't seem to be working for me. :/ dang. What version of springfox are you using?

**Comment by mattsheppard** [comment]
2.2.2 by the look of it.

**Comment by mattsheppard** [comment]
Hmmm, looking agin, it seems like the specific code this example was extracted from was flattened somewhere along the way - https://github.com/springfox/springfox/issues/1070#issuecomment-223399057 was probably just me being fooled by code in a different area which may not be using the schema at all, so it's likely that we ended up stepping around the problem at the time.

I wonder if de-lomboking the code might help in your case.

**Comment by dilipkrish** [comment]
I wonder if u could perhaps check with 2.4.0. Plenty of bug fixes between now and then

**Comment by snowe2010** [comment]
We're using 2.4.0. I wonder if that's maybe the issue. De-lomboking the code would be quite difficult in my case, not the least because I'm new to Lombok. Else I think we're just going to ignore the problem for now as it's not pressing.

**Comment by dilipkrish** [comment]
@snowe2010 I'd say [create a __NEW__ issue with a failing test](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java) and if it fails we can fix it. I don't think lombok is the problem here.
