### ISSUE TITLE
Define a custom json for a specific service

### ISSUE THREAD

**Issue by gustavolira** [springfox/springfox#1071]
Hi,

I'm using a service that has @RequestBody MyEntity entity. But this entity is really huge and has a lot of properties that for this specific service will be populate automatic but for other services I need to receive all properties.
Would be nice if exists some way to define the JSON that we expect to receive for a specific service.

**Comment by dilipkrish** [comment]
@gustavolira There isn't a way to render operation specific models.

**Comment by gustavolira** [comment]
I think that this will happen when JSON View feature (from jackson) be implemented

**Comment by dilipkrish** [comment]
Closing as its a duplicate of #601
