### ISSUE TITLE
can springfox-swagger2 ui support choose multiple file once?

### ISSUE THREAD

**Issue by zhugw** [springfox/springfox#1072]
Latest project I used spring boot and integrated swagger-ui（springfox-swagger2）， I want to once upload multiple files , so operator could batch upload goods images, my controller method is
```
@ApiOperation(value = "batch upload goods cover image", notes = "batch upload goods cover image",
  response = UploadCoverResultDTO.class, responseContainer = "List")

public Result<?> uploadGoodsCover(@ApiParam(value = "Image array", allowMultiple = true,
  required = true) @RequestPart("image") MultipartFile[] files) throws IOException 
```
and real swagger ui effect is:
[![enter image description here][1]][1]
But I want this effect
[![enter image description here][2]][2]
Can springfox-swagger2 support this? or even more convenience once choose all pictures in one folder, like
```
<input type="file" name="img" multiple="multiple"/>
```

[1]: http://i.stack.imgur.com/CYcQ0.png
[2]: http://i.stack.imgur.com/iwV5A.png

**Comment by dilipkrish** [comment]
This is not currently supported in swagger-ui I think

**Comment by SylarChen** [comment]
Same behavior in version 2.6.1. Is it supported now?

**Comment by dilipkrish** [comment]
This is only going to be supported when swagger-ui supports it. The right place to create an issue is in the [swagger-ui project](https://github.com/swagger-api/swagger-ui).
