### ISSUE TITLE
About swagger-ui try it out request url

### ISSUE THREAD

**Issue by zhugw** [springfox/springfox#1075]
Just now I encountered a problem. That is I deployed a project into cloud and config nginx
```
 server {
        listen 80;
        server_name ops.foo.com;
        location / {
                proxy_pass http://127.0.0.1:8086;
                proxy_set_header X-Real-IP $remote_addr;
        }
    }
```
Now I could access `ops.foo.com` in browser. But when I click `try it out` button
Nothing happen.  Response body is `no content`. And Request URL is
`http://127.0.0.1:8086/doSomething`. Why it is not `http://ops.foo.com/doSomething`?
By google I found this solution that is when run spring boot project explicitly add this system parameter:
`-Dspringfox.documentation.swagger.v2.host=ops.foo.com`. I want to know if  is it the only way? could exist some other way to solve this problem?

**Comment by dilipkrish** [comment]
That is the stable way to do it, yes. If you need a per docket host name override there is a feature thats in incubation that hasn't yet been released

**Comment by zhugw** [comment]
Could you give me a link of these configurations like `springfox.documentation.*`,  just as http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
