### ISSUE TITLE
UiConfiguration setting validatorUrl doesn't actually work.

### ISSUE THREAD

**Issue by rockytriton** [springfox/springfox#1077]
This code is supposed to set validatorUrl to null, so it can skip the validation.

@Bean
    UiConfiguration uiConfig() {
      return new UiConfiguration(null);
    }

The problem is, it's implemented like so:

------
window.swaggerUi = new SwaggerUi({
            dom_id: "swagger-ui-container",
            supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
            onComplete: function(swaggerApi, swaggerUi) {

              initializeSpringfox();
------

------
function initializeSpringfox() {
            .....

            window.springfox.uiConfig(function(data) {
              window.swaggerUi.validatorUrl = data.validatorUrl;
            });
          }
------

this uiConfig call is asynchronous, so while it does set the window.swaggerUi.validatorUrl to null, it does so AFTER the validation has already been done.

**Comment by dilipkrish** [comment]
@rockytriton would love to get a pr! Trying to get the release out and would be great to have this fixed!

**Comment by rockytriton** [comment]
I submitted one, not really sure if that's how you want it fixed or not, but it works for me.  I basically just don't create the SwaggerUi object until after calling the ui config REST service.

**Comment by dilipkrish** [comment]
Fixed via #1078 :bow: thank you!
