### ISSUE TITLE
Customizing swagger-ui.html location

### ISSUE THREAD

**Issue by rockytriton** [springfox/springfox#1080]
I've seen that we can customize the swagger api-docs location, i would also like to customize the location of swagger-ui.html and /configuration/ui, /configuration/security.   I can't find anywhere to do this, is it possible?

**Comment by dilipkrish** [comment]
`/configuration/ui` and `/configuration/security` can't be changed unfortunately. Those are known locations to get this information. You could certainly change `swagger-ui.html`, if you're using spring-boot thats the default behavior, and you override that using an implementation of `WebMvcConfigurerAdapter` that adds your endpoint using the `addResourceHandlers`

**Comment by chornyi** [comment]
I was able to move Swagger UI under `/documentation` using this code.

	@Override
	public void addViewControllers(ViewControllerRegistry registry) {
		registry.addRedirectViewController("/documentation/v2/api-docs", "/v2/api-docs");
		registry.addRedirectViewController("/documentation/configuration/ui", "/configuration/ui");
		registry.addRedirectViewController("/documentation/swagger-resources", "/swagger-resources");
		registry.addRedirectViewController("/documentation", "/documentation/swagger-ui.html");
		registry.addRedirectViewController("/documentation/", "/documentation/swagger-ui.html");
	}

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry
			.addResourceHandler("/documentation/**").addResourceLocations("classpath:/META-INF/resources/");
	}

However it still requires a redirect to `/documentation/swagger-ui.html` because the path name is hard-coded here: https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/springfox.js#L4. Maybe this is something that could be improved.

**Comment by dilipkrish** [comment]
@chornyi :+1: thanks for the work-around... will chalk that up as a documentation enhancement

**Comment by nedkoh** [comment]
Is this issue resolved?

**Comment by dilipkrish** [comment]
@nedkoh  there is nothing to resolve. Following @chornyi's [instructions](https://github.com/springfox/springfox/issues/1080#issuecomment-169185653) should help you.

**Comment by nedkoh** [comment]
@dilipkrish I was referring to this part but did not realize the redirect is working as a workaround. Thanks. "However it still requires a redirect to /documentation/swagger-ui.html because the path name is hard-coded here: https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/springfox.js#L4"

**Comment by dilipkrish** [comment]
@nedkoh oh I see. Sorry for the confusion! As a library that is pretty hard (and out of scope) to make configurable, which is why it is just tagged as a _can-use-for-docs_ and will be documented as _when you want to change this behavior, what should one do?_

If you do see a way to make that easier would love feedback and a PR would be even better :wink:

**Comment by nedkoh** [comment]
I had gotten it to work without redirect using the other swagger github project but it required some ugly .js manipulation of the static content and a JSP page which is not ideal. Will think of a cleaner solution. btw. I just tried the above and everything worked as expected.

**Comment by jeroenbellen** [comment]
Why is this issue closed? Redirecting is not a solution?
It should be possible to configure all endpoints to listen to a provided path.

**Comment by jeanchang22** [comment]
This fix doesn't work for groups, could you help to find a better solution for it?

**Comment by jeanchang22** [comment]
my projects have multiple versions of documents, on swagger-ui.html, there is a dropdown to link to different version of doc, however, after applying this fix, it always redirects to the first version of doc, the link to other versions of doc are no longer valid.

**Comment by georgi-staykov** [comment]
For version 2.6.1 if you want your groups to work too use this:

```
@Override
	public void addViewControllers(ViewControllerRegistry registry) {
		registry.addRedirectViewController("/documentation/v2/api-docs", "/v2/api-docs").setKeepQueryParams(true);
		registry.addRedirectViewController("/documentation/swagger-resources/configuration/ui","/swagger-resources/configuration/ui");
		registry.addRedirectViewController("/documentation/swagger-resources/configuration/security","/swagger-resources/configuration/security");
		registry.addRedirectViewController("/documentation/swagger-resources", "/swagger-resources");
	}

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/documentation/**").addResourceLocations("classpath:/META-INF/resources/");
	}
```

In this way the default group and the custom groups will work because of setKeepQueryParams(true) on the redirect. If you have custom path for the /v2/api-docs  use it in the redirect ! This is still workaround. Enjoy

**Comment by dilipkrish** [comment]
Thanks @georgi-staykov for the useful tip!!

**Comment by sankarav** [comment]
Thanks @chornyi for comments, it worked. But I am using spring websecurity in my application. In this case I had to do the following, so the requests related to swagger redirects get to the application.

`
@Configuration
@EnableWebSecurity
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter {

     @Override
      protected void configure(HttpSecurity http) throws Exception {
         http.authorizeRequests()
            .antMatchers(HttpMethod.GET, "/v2/api-docs").permitAll()
            .antMatchers(HttpMethod.GET,"/swagger-resources").permitAll()
            .antMatchers(HttpMethod.GET,"/configuration/**").permitAll()
            .antMatchers(HttpMethod.GET,"/documentation/**").permitAll()
            .antMatchers("/**").fullyAuthenticated()
            .and().csrf().disable();
      }
}
`

Is there a way I could modify your spring redirects/forwards to keep my security authorizations to minimum? I am expecting something like this, so everything under "/documentation/**" is authenticated for swagger-ui.

`
@Configuration
@EnableWebSecurity
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter {

     @Override
      protected void configure(HttpSecurity http) throws Exception {
         http.authorizeRequests()
            .antMatchers(HttpMethod.GET,"/documentation/**").permitAll()
            .antMatchers("/**").fullyAuthenticated()
            .and().csrf().disable();
      }
}
`

**Comment by dilipkrish** [comment]
I think you can get away with 
`.antMatchers(HttpMethod.GET,"/swagger-resources/**").permitAll()`

**Comment by KD4** [comment]
Is there no solution without redirecting? T_T

**Comment by dilipkrish** [comment]
@KD4 Solution to what?

**Comment by river226** [comment]
@dilipkrish Please don't be dense. The issue is that the only way to customize the url is a redirect url. It would be nice if springfox had some build in way to make the necessary updates when it builds the swagger doc. Something like this:https://github.com/domaindrivendev/Swashbuckle#customizing-the-generated-swagger-docs without a need to actually redirect which is at best makeup on the pig that is this problem.

**Comment by dilipkrish** [comment]
@river226 You can customize the [swagger description url](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints). Its only a problem if you want your swagger-ui to be in a different place than the root of the context path.

The location of `swagger-ui.html`, the built in one, is like the north star for where all the other endpoints are located, ui configuration, security configuration, the different grouped swagger descriptions etc.

Im not familiar with swashbuckle, but what specifically of the customizations in swashbuckle are you expecting to see here? Could you perhaps provide an example of a proposed configuration? That will give me a better idea of the problem you're trying to solve with the *makeup* :)

**Comment by river226** [comment]
@dilipkrish Upon a second look, it looks like swashbuckle may not do what I was aiming for. What I and I am pretty sure most of the people in this thread are looking for is simply changing the north star. Instead of swagger-ui.html and make it say: "thisisuseful.whyisntthisathing". I find the idea as you posted previously that this is hard to make configurable doubtful at best, and setting up a workaround redirect is not a good solution to an obviously useful feature.

**Comment by dilipkrish** [comment]
@river226 Open to ideas

**Comment by bob9** [comment]
I solved this problem by using rewrite rule..
add to dependancy 

compile group: 'org.tuckey', name: 'urlrewritefilter', version: '4.0.4'

Make sure this component is in your @ComponentScan path
`
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;
import org.tuckey.web.filters.urlrewrite.Conf;
import org.tuckey.web.filters.urlrewrite.UrlRewriteFilter;

import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import java.io.IOException;


@Component
public class MyUrlRewriteFilter extends UrlRewriteFilter {

    private static final String CONFIG_LOCATION = "classpath:/urlrewrite.xml";

    //Inject the Resource from the given location
    @Value(CONFIG_LOCATION)
    private Resource resource;

    //Override the loadUrlRewriter method, and write your own implementation
    @Override
    protected void loadUrlRewriter(FilterConfig filterConfig) throws ServletException {
        try {
            //Create a UrlRewrite Conf object with the injected resource
            Conf conf = new Conf(filterConfig.getServletContext(), resource.getInputStream(), resource.getFilename(), "@@yourOwnSystemId@@");
            checkConf(conf);
        } catch (IOException ex) {
            throw new ServletException("Unable to load URL rewrite configuration file from " + CONFIG_LOCATION, ex);
        }
    }
}`



Rewrite rules xml put this in resources files name the file urlrewrite.xml.
Change /users/ to be whatever folder to want it to the rewrite rule to to navigate to.

`
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE urlrewrite PUBLIC "-//tuckey.org//DTD UrlRewrite 4.0//EN"
        "http://www.tuckey.org/res/dtds/urlrewrite4.0.dtd">
<urlrewrite>
    <rule>
        <from>/users/swagger-ui.html</from>
        <to type="passthrough">/swagger-ui.html</to>
    </rule>

    <rule>
        <from>/users/webjars/(.*)</from>
        <to type="passthrough">/webjars/$1</to>
    </rule>

    <rule>
        <from>/users/api-docs</from>
        <to type="passthrough">/api-docs</to>
    </rule>

    <rule>
    <from>/users/configuration/(.*)</from>
    <to type="passthrough">/configuration/$1</to>
    </rule>

    <rule>
    <from>/users/swagger-resources</from>
    <to type="passthrough">/swagger-resources</to>
</rule>
</urlrewrite>
`

**Comment by dilipkrish** [comment]
@alfredyctan and @bob9 those are both interesting approaches that seem to work. Thanks for sharing!

**Comment by river226** [comment]
@dilipkrish it would be awesome if one of these approaches were fully supported by the library and even better if they could be used with 1 or 2 additional lines of code.

**Comment by nahguam** [comment]
Hi @dilipkrish ,

This is a feature that would also be useful for us as well. We have multiple apps, each with Swagger endpoints being exposed through Kubernetes Services and an AWS ALB Ingress. Each has to be on a separate endpoint. Up until now we've used the Spring Boot `contextPath` but due to another requirement we can no longer do that so we need another way to relocate the docs. Redirects will not cut it.

I've spent a little time having a look and have got it working by introducing a Swagger `contextPath`, that sits after the Spring Boot `contextPath`. I've started turning into PR but wanted to get your input on the idea first.

https://github.com/springfox/springfox/compare/master...nahguam:contextPath

**Comment by dilipkrish** [comment]
@nahguam Im going to preface by saying, Im not sure a generic solution that can be applied to this particular problem. 

The swagger-ui that is bolted on to this library is only a convenience for the 80% of the use cases. For the remaining 20%, it may be better to not generalize and over-engineer a solution. Not that yours is, Im just expressing the philosophy behind the swagger-ui that is bundled in springfox.

Having said that I like you're idea. We could perhaps build on it so here is my feedback"
- swagger-ui that is bundled is adheres to the web jar specification, so the default behavior is to register resource handlers automatically for spring boot apps.
- [EnableWebMvc](https://github.com/springfox/springfox/compare/master...nahguam:contextPath#diff-6624bcb9856678f9d1ff14a56816ad58R31) is a total no-no when it comes to spring boot apps. It is a signal to tell spring boot you're going to manage your own configuration. A library like springfox shouldnt make that determination.
- We just put considerable effort in removing dependence on `RequestMapping`s with [configuration expressions](https://github.com/springfox/springfox/blob/c18dc1d3469b45eb3dae03c1bb126cd792051ca9/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L75-L83). This is so that we dont assume there is a [`PropertySourcesPlaceholderConfigurer`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/support/PropertySourcesPlaceholderConfigurer.html)

There is already [a solution to let you aggregate swagger specifications from multiple services](http://springfox.github.io/springfox/docs/current/#aggregating-multiple-swagger-specifications-in-the-same-swagger-ui). Its used in projects like jhipster. That might be a thing you could consider.

**Comment by nahguam** [comment]
Hi @dilipkrish,

This is great feedback, Thanks.

I haven't considered how to test this yet. Any pointers here?

**Comment by dilipkrish** [comment]
@nahguam as far as pointers on how to test, sadly it appears I punted testing [PropertySourcedRequestMappingHandlerMapping](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/PropertySourcedRequestMappingHandlerMapping.java) :( 

> However this only scans methods, not types, so is unable to construct a new path if the mapping is on both the type and method, such as with ApiResourceController.

That is true. It was targeting a very simple use case of replacing the path without using `PropertySourcesPlaceholderConfigurer`

> Just taking a step back, is it possible to aggregate swagger specs hosted on other servers? Is that what you meant by 'multiple services'?

It is totally possible. That is what I meant to say, sorry I wasnt clear. Yes, to clarify, you could have one endpoint that hosts swagger-ui (the springfox one) and it can aggregate services living in-the same app and/or in files or combine external swagger specifications in other services. You just need to implement your custom `SwaggerResourcesProvider`.

**Comment by zpf7879** [comment]
My app is a Spring WebFlux app, and I tried all the approaches listed here in the thread. Unfortunately, none of them works in this context. I end up the following solution by using WebFilter (I personally feel not very gracefully but no better approach found yet).

@Component
public class SwaggerWebFilter implements WebFilter {
    @Override
    public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        String path = request.getPath().pathWithinApplication().value();
        if (path.startsWith("/api/swagger-ui.html") || path.startsWith("/api/webjars")
                || path.startsWith("/api/api-docs") || path.startsWith("/api/configuration")
                || path.startsWith("/api/swagger-resources") || path.startsWith("/api/v2")) {
            exchange = exchange.mutate().request(request.mutate().path(path.substring(4)).build()).build();
        }
        return chain.filter(exchange);
    }
}

**Comment by n2696118** [comment]
It seems the only way to fix it (without resorting to redirects) to fork the repository and start renaming... Which resources would need to be changed for everything to work?

**Comment by x1aliang** [comment]
`
@Configuration
@EnableSwagger2
@Controller
public class SwaggerConfig implements WebMvcConfigurer{
	@Bean
    public Docket swaggerSpringMvcPlugin() {
        return new Docket(DocumentationType.SWAGGER_2)
        		.select()
        		.apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class))
        		.build()
        		.securitySchemes(Collections.singletonList(new ApiKey("Bearer", "Authorization", "header")));
    }

	
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/api-docs/**").addResourceLocations("classpath:/META-INF/resources/");
	}
	
	@RequestMapping("/api-docs/swagger-resources")
	public String resource() {
		return "forward:/swagger-resources";
	}
	
	@RequestMapping("/api-docs/swagger-resources/configuration/ui")
	public String ui() {
		return "forward:/swagger-resources/configuration/ui";
	}
	
	@RequestMapping("/api-docs/v2/api-docs")
	public String doc() {
		return "forward:/v2/api-docs";
	}
	

	@RequestMapping("/api-docs/swagger-resources/configuration/security")
	public String security() {
		return "forward:/swagger-resources/configuration/security";
	}
}`

Although this issues has been closed, but i think we can use the above way to modify the ui location~ in which we dnt need to modify spring security setting (i mean to open more accessable path)

**Comment by x1aliang** [comment]
`@Configuration
@EnableSwagger2
@Controller
public class SwaggerConfig implements WebMvcConfigurer{
	@Bean
    public Docket swaggerSpringMvcPlugin() {
        return new Docket(DocumentationType.SWAGGER_2)
        		.select()
        		.apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class))
        		.build()
        		.securitySchemes(Collections.singletonList(new ApiKey("Bearer", "Authorization", "header")));
    }

	
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/api-docs/**").addResourceLocations("classpath:/META-INF/resources/");
	}
	
	@RequestMapping("/api-docs/swagger-resources")
	public String resource() {
		return "forward:/swagger-resources";
	}
	
	@RequestMapping("/api-docs/swagger-resources/configuration/ui")
	public String ui() {
		return "forward:/swagger-resources/configuration/ui";
	}
	
	@RequestMapping("/api-docs/v2/api-docs")
	public String doc() {
		return "forward:/v2/api-docs";
	}
	

	@RequestMapping("/api-docs/swagger-resources/configuration/security")
	public String security() {
		return "forward:/swagger-resources/configuration/security";
	}
}`

Although this issues has been closed, but i think we can use the above way to modify the ui location~ in which we dnt need to modify spring security setting (i mean to open more path)

**Comment by x1aliang** [comment]
```java
@Configuration
@EnableSwagger2
@Controller
public class SwaggerConfig implements WebMvcConfigurer{
	@Bean
    public Docket swaggerSpringMvcPlugin() {
        return new Docket(DocumentationType.SWAGGER_2)
        		.select()
        		.apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class))
        		.build()
        		.securitySchemes(Collections.singletonList(new ApiKey("Bearer", "Authorization", "header")));
    }

	
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/api-docs/**").addResourceLocations("classpath:/META-INF/resources/");
	}
	
	@RequestMapping("/api-docs/swagger-resources")
	public String resource() {
		return "forward:/swagger-resources";
	}
	
	@RequestMapping("/api-docs/swagger-resources/configuration/ui")
	public String ui() {
		return "forward:/swagger-resources/configuration/ui";
	}
	
	@RequestMapping("/api-docs/v2/api-docs")
	public String doc() {
		return "forward:/v2/api-docs";
	}
	

	@RequestMapping("/api-docs/swagger-resources/configuration/security")
	public String security() {
		return "forward:/swagger-resources/configuration/security";
	}
}
```

Although this issue has been closed for a while, but i think we can use this way to redirect the swagger ui since which dnt need to modify spring security settings.

**Comment by sarangajay** [comment]
Hi x1aliang

I have an issue that unless i have the below (/**) , swagger-ui.html does not get load. and doing so impact other handles as now other servlets can't fine the appropriate handlers.  


registry.
                addResourceHandler("/**").addResourceLocations("classpath:/META-INF/resources/");

any idea ?

this a non spring + xml app.

**Comment by Numbernick** [comment]
Wow, this conversation got huuuge...

In my honest opinion the base path of the swagger-ui should be a configuration (I mean e.g. even the spring actuator can have a different base path). I would recomment to add the "SwaggerWebFilter" written from @zpf7879 to the swagger-ui project. I made some small changes to the Filter to support the Spring PathMatcher and a faster rewrite acceptance if the referer is the swagger-ui page.

```kotlin
@Service
class InternalRequestRewriteFilter(
        @Value("\${server.servlet.context-path}") private val contextPath: String): WebFilter {
    private val pathMatcher = AntPathMatcher()
    private val swaggerPaths = setOf("swagger-ui.html", "webjars/springfox-*/**", "swagger-resources/**", "v2/api-docs")
    private val logger = getLogger(javaClass)

    override fun filter(exchange: ServerWebExchange, chain: WebFilterChain): Mono<Void> {
        // Get the path of the request
        val path = exchange.request.path.pathWithinApplication().value()
        // If the path leads to an swagger element -> remove the context path for the internal processing
        val modifiedExchange = if (isSwaggerRequest(exchange.request)) {
            logger.debug("""Swagger request detected for path "$path"""")
            exchange.mutate().request(exchange.request.mutate().path(path.replaceFirst(contextPath, "")).build()).build()
        } else {
            exchange
        }
        // Execute the normal filter chain
        return chain.filter(modifiedExchange)
    }

    private fun isSwaggerRequest(request: ServerHttpRequest): Boolean {
        // Get the referer. If it was swagger-ui, then it is a swagger request
        val referer = request.headers["referer"]?.first() ?: ""
        // Get the path of the request
        val path = request.path.pathWithinApplication().value()

        return pathMatcher.match("**$contextPath/${swaggerPaths.first()}", referer) ||
                swaggerPaths.any {swaggerPath -> pathMatcher.match("$contextPath/$swaggerPath", path)}
    }
}
```
So even with the context-path of "" (empty String) this works like a charm (except for csrf, which I just didn't configure. But with the referer in place it should work as well).

@dilipkrish Please add a basic behaviour to springfox to close this 3 year old topic with so many different and awesome workarrounds.

**Comment by publisherfk** [comment]
in the 2.9.2,some path had changed,eg:
`registry.addRedirectViewController("/api/swagger-resources/configuration/ui", "/swagger-resources/configuration/ui");
        registry.addRedirectViewController("/api/swagger-resources/configuration/security", "/swagger-resources/configuration/security");
`

**Comment by Korzi** [comment]
Apart from property `springfox.documentation.swagger.v2.path` (mentioned in the [doc](http://springfox.github.io/springfox/docs/current/) )  that allows to modify default `/v2/api-docs` path, 
you can use property `springfox.documentation.swagger-ui.base-url`to change default `/swagger-ui/` to custom path

**Comment by kanai0618** [comment]
Hi @zpf7879  @dilipkrish  , i am using spring webflux, my swagger url doesnot work with this url : http://localhost:8080/swagger-ui/index.html but works with http://localhost:8080/webjars/swagger-ui/index.html, why webjars needed in the URL ? how to fix that ?

**Comment by publisherfk** [comment]
@kanai0618 I guest your project set project path is webjars，Please check it.

**Comment by kanai0618** [comment]
Hi @publisherfk , i have not set any project path, is there any way to find out ? or by default its set to webjars ?

**Comment by publisherfk** [comment]
Hi @kanai0618  maybe project web.xml had set path ,maybe webjar project have default path.

**Comment by pdAfy51** [comment]
Hi this solution works for me [https://stackoverflow.com/a/59948001](url)

**Comment by fesabelilla** [comment]
> For example if you have **springfox.documentation.swagger.v2.path: /private/v2/api-docs** for custom api-docs path your
@gstaykov 
If I want to create a custom swagger-resources(/swagger-resources) path how can I do this ??
