### ISSUE TITLE
Replace Guava by java8 predicates function

### ISSUE THREAD

**Issue by ouaibsky** [springfox/springfox#1082]
Hi
last version of springfox rely on guava, maily  to apply predicates for path filtering.
It's an issue for a documentation tools like this to depend of a so hudge library. I means we need this dependencies for swagger support for spring mvc endpoint.

This type of features are now supported natively by java 8

Thx
Christophe

**Comment by dilipkrish** [comment]
Currently we support java 6 through 8. So unless we deprecate support for java 6 and 7 thats not possible at least in the near future.

**Comment by ouaibsky** [comment]
Hi
Thx, it's a shame because guava was not part of swagger 1

Is it possible to envisage something like this:
* Design filtering interface
* Mark guava as an optionnal dep in pom
* Provide an implementation of filtering that check if java 8 is present, if not fall-back on guava

Christophe

**Comment by dilipkrish** [comment]
Absolutely possible! Once we move to java 8 there won't be a need to use explicit guava/java 8 types even. They could just be replaced by lamdas.

Unfortunately, like I said before, we still support java 6 and spring 3.2 and above. So thats not going to happen anytime soon. 

Also needless to say the cost of doing that might be quite high in terms of time. I do this in my spare time and no one is paying me to maintain this library. I don't have cycles to work on large refactoring efforts when nothing is really broken.

**Comment by ouaibsky** [comment]
We all have a limited capex when it's private project ;)

I mean If we propose a PR in this direction is there a chance that it will be accepted ?

**Comment by dilipkrish** [comment]
Abolutely!

**Comment by RobWin** [comment]
You can still use Springfox just as a testCompile dependency and create the Swagger JSON in a unit test and include it into your jar then serve it as static content.
See https://github.com/Swagger2Markup/spring-swagger2markup-demo
No need to include the library into your production code.

**Comment by cleankod** [comment]
@ouaibsky where are you on this PR?

**Comment by dilipkrish** [comment]
@cleankod There have been no takers for it

**Comment by neil1hart** [comment]
I can attempt this.  Some of this is straight forward, cache loading is a little harder, ImmutableSet will be lost...  The big questions is what should be done with VisibleForTesting annotation?

**Comment by dilipkrish** [comment]
@neil1hart `VisibleForTesting` is just a marker annotation to signal why a particular method is not private/restricted than needed. It can go away. Also keep in mind there is also #2086 that you can build on.

**Comment by neil1hart** [comment]
Looking at the other pull request and contributing guidelines, I have got a couple of questions 
before I'm ready to submit

Do you want one big commit or commits like
- cleaned up Optionals
- cleaned up Functions
- etc?


Prefer static includes, for example
`import static java.util.Optional.*`
`Integer count = ofNullable(patchComponents[3]).orElse("0").toInteger()`
or
`Integer count = Optional.ofNullable(patchComponents[3]).orElse("0").toInteger()`

Fully replace Funtions, Comparables with lamdas?
Simple moving from Ordering to Comparable
  `private static Comparator<Tag> byOrder() {`
    `return new Comparator<Tag>() {`
     `@Override`
      `public int compare(Tag first, Tag second) {`
        `return Integer.valueOf(first.getOrder()).compareTo(second.getOrder());`
      `}`
    `};`
  `}`

or lamda
 `private static Comparator<Tag> byOrder() {`
  `  return (Tag first, Tag second)->first.getName().compareTo(second.getName());`
  `}`

thanks
