### ISSUE TITLE
@ApiParam default required = false

### ISSUE THREAD

**Issue by rockytriton** [springfox/springfox#1083]
If you leave @ApiParam off of a field, it defaults to required = true, which is what swagger docs says it should be.

If you add @ApiParam but don't specify required, it sets it to false in the /api-docs json output.

I'm not sure if this is an issue with springfox or with swagger.

**Comment by dilipkrish** [comment]
Thats because the required attribute is [defaulted to false](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiParam.java#L77) in `@ApiParam`. So if you want to use annotations you need to be aware of the annotation defaults.

**Comment by Cejkis** [comment]
Could you please add config option to make it defaultly true? Thanks
