### ISSUE TITLE
Change hardcoded "api_key"  

### ISSUE THREAD

**Issue by JulianaRed** [springfox/springfox#1087]
You have hardocded "api_key" param in addApiKeyAuthorization() in  index.html of swagger-ui, but I need to set my own header-name for authentication and I have no possibility to do this

**Comment by dilipkrish** [comment]
Adventurous enough to help with a PR?

**Comment by the4yeast** [comment]
Is there any chance this might get released soon?

**Comment by dilipkrish** [comment]
In about a week. Have a couple of bugs/ maintenance issues to address.

**Comment by the4yeast** [comment]
sounds great, thanks!

**Comment by gunbas99** [comment]
Any Idea if the above issue has been resolved??

**Comment by mrsarm** [comment]
It's so frustrating when some new feature is available but not documented like this case, close this issue without document it is like if the feature doesn't exist. I had to check the source code of the project to realize how to configure this.

Finally, for Spring Boot you can achieve this with something like:

```java
    @Bean
    public SecurityConfiguration security() {
        return new springfox.documentation.swagger.web.SecurityConfiguration(
            null, null, null,
            "myapp-api",
            "access_token",
            ApiKeyVehicle.QUERY_PARAM,
            "access_token",
            null);
    }
```

**Comment by dilipkrish** [comment]
Its totally [available in the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) and [the commit above](https://github.com/springfox/springfox/commit/fcf3424609d739f39b4226f3203b8ff2ead79096) shows it as well. What are you referring to?
