### ISSUE TITLE
Could not autowire field: private springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper

### ISSUE THREAD

**Issue by choiapril6** [springfox/springfox#1088]
To study the architecture of Springfox, I've downloaded zip file of Springfox 2.0.1 and imported the package into Eclipse. After all the configuration work, however, what the error log on startup of the server says is below:
```
Error creating bean with name 'swagger2Controller': Injection of autowired dependen
cies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private springfox.docume
ntation.swagger2.mappers.ServiceModelToSwagger2Mapper springfox.documentation.swagger2.web.Swagger2Controller.mapper; nested exception is or
g.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [springfox.documentation.swagger2.mappers.ServiceM
odelToSwagger2Mapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency a
nnotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```
 I have done with adding the package into the buildpath of a web project which will be auto-documented by Springfox 2.0.1 and configuring it using a class annotated '@EnableSwagger2'. It keeps showing up every trial on different sample projects. Maybe I am missing out a specific configuration or something. Pleeeease help me out of here. I really want to utilize Springfox on my project. I appreciate your help.

**Comment by dilipkrish** [comment]
@choiapril6 I'd recommend downloading the 2.3.0 version instead.

**Comment by choiapril6** [comment]
Thanks for quick response! I will give it a try.

**Comment by choiapril6** [comment]
I did it with v2.3.0, but still am having same issue.

**Comment by dilipkrish** [comment]
Are you using gradle to load your application? or are u manually setting up all the dependencies?

**Comment by choiapril6** [comment]
I am using Eclipse gradle plugin. So I imported Springfox 2.3.0 using the plugin. 

2015. 12. 10. 오전 12:21 Dilip Krishnan <notifications@github.com> 작성:

**Comment by dilipkrish** [comment]
Could you share your repo perhaps. It seems like a problem in your environment. Have you looked at the [springfox-demos](https://github.com/springfox/springfox-demos) project?

**Comment by choiapril6** [comment]
The project on which Springfox is not working is below.
https://github.com/choiapril6/jwp-spring.git

I will look at springfox-demos too. Thanks.

**Comment by choiapril6** [comment]
omg I can't figure out why it keeps missing ServiceModelToSwagger2Mapper. I did annotate the class as Component but still failed. Anybody else with this same error?

**Comment by dilipkrish** [comment]
It doesn't appear like you've added the following dependencies in your project

```xml
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.3.0</version>
        </dependency>
        <!-- Optional -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.3.0</version>
        </dependency>
```

**Comment by choiapril6** [comment]
Thanks for the answer. However, as I mentioned above, I'm not adding
dependency, but I downloaded full package of Springfox and add them to
build path instead. The reason why I am doing like this is that I want to
add some feature such as reading specific annotation that I made up. That
is why there's no springfox dependency in my pom.xml.

**Comment by dilipkrish** [comment]
I really don't understand what you're trying to do.🤔

 If your project is managed by maven it takes care of all the dependencies; even transitive dependencies. For eg springfox-swagger2 has other dependencies that are required. If your doing something half using maven and half build path, u need to make sure u have all those dependencies as well. 

Sorry I'm not being of much help, but I think ur problem will be solved if u use maven as expected.

**Comment by choiapril6** [comment]
No problem:) Actually you are helping me.

Agree with your words. Half dependency half build path would not work out. But, I've downloaded and add all the projects including springfox-swagger2 into build path from the link(https://github.com/springfox/springfox/archive/2.3.0.zip). Is this way of building the environment a problem too?

Thanks for your patient help.

**Comment by dilipkrish** [comment]
> he reason why I am doing like this is that I want to add some feature such as reading specific annotation that I made up. So, I need to try add some code lines into Springfox source code.

If you're interested is in adding support of an annotation being processed you should just considering developing a plugin implementation and add that as a bean. The plugin architecture will take care of using your plugin implementation. 

I don't think the hackery involved in using the build path etc. is warranted nor maintainable and definitely not supportable.

If you have a specific use-case I could provide you the guidance.

**Comment by choiapril6** [comment]
Thank you so much. I will elaborate the case for you.

**Comment by jfiala** [comment]
The root cause for getting "No qualifying bean of type [springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper]" is that the ServiceModelToSwagger2MapperImpl has to be generated using gradle generateMappers and then add the springfox-swagger2/generated-src/main-folder to the source folders. Then the ServiceModelToSwagger2MapperImpl can be found on the classpath.
