### ISSUE TITLE
Configuring Springfox to use GsonHttpMessageConverter instead of JacksonHttpMessageConverter

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#1089]
Any inputs on this ?

**Comment by dilipkrish** [comment]
Have you looked [at the docs](http://springfox.github.io/springfox/docs/current/#answers-to-common-questions-and-problems)?

**Comment by rajeshkamal** [comment]
Sorry, I did not. Let me look, try and update.

**Comment by rajeshkamal** [comment]
Works fine.
