### ISSUE TITLE
Even for GET operations the consumes defaults to "application/json" when not defined

### ISSUE THREAD

**Issue by wbartensleben** [springfox/springfox#1090]
Many of my GET endpoints should not consume anything.

Looking at the [MediaTypeReader](https://github.com/springfox/springfox/blob/72334193ed210aa60808babd43e82442aa9d871d/springfox-spring-web/src/main/java/springfox/documentation/spring/web/scanners/MediaTypeReader.java#L70) implementation; this defaults to `application/json`. Is there a way to make this empty? We would like to have an empty/null/nonexistent consumes key in the swagger output.

**Comment by dilipkrish** [comment]
The browser/swagger-ui will always send a content type regardless of whether its empty or not. What problem are you facing as a result of this?

**Comment by wbartensleben** [comment]
We would like the consumes section to not show, which swagger2markup supports well.

![screen shot 2015-12-10 at 3 42 22 pm](https://cloud.githubusercontent.com/assets/13022896/11718103/a6242328-9f54-11e5-8469-963137ac9e99.png)

**Comment by Khoulaiz** [comment]
I also think that the consumes parameter in case of a GET request doesn't make any sense. There is no json sent in case of a GET request. 

I use convertSwagger2Markup gradle plugin to create my documentation and when I deliver an empty consumes parameter, the generated markup code will not contain a Consumes section, which I really would prefer. 

Still an amazing project, helps a lot to keep documentation in sync. Good work!

**Comment by seansilvestri** [comment]
Has this been addressed?
If not is there an ETA?
many thanks!
