### ISSUE TITLE
When customize message converter the swagger-ui disappeared

### ISSUE THREAD

**Issue by zhugw** [springfox/springfox#1095]
Right now I encountered a problem when use spring boot default `HttpMessageConverter` , problem is
```
com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.util.ArrayList[0]-
``` 
So I changed to another converter--[FastJsonHttpMessageConverter](https://github.com/alibaba/fastjson/blob/master/src/main/java/com/alibaba/fastjson/support/spring/FastJsonHttpMessageConverter.java). Code is below:
```
	@Bean
	public HttpMessageConverters customConverters() {
		HttpMessageConverter<?> additional = new FastJsonHttpMessageConverter();
		return new HttpMessageConverters(additional);
	}
```
Now above problem is gone, but have another problem that is swagger-ui gone. 
```
curl http://localhost:8080/v2/api-docs
{}%                                          
```

How could I solve this problem?

```
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>2.2.2</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>2.2.2</version>
			</dependency>
```

**Comment by dilipkrish** [comment]
@zhugw We rely quite heavily on jackson to determine object types etc. The workaround you might want to try is similar to [that suggested for supporting Gson](http://stackoverflow.com/questions/30219946/springfoxswagger2-does-not-work-with-gsonhttpmessageconverterconfig/30220562#30220562).
