### ISSUE TITLE
Springfox-Staticdocs - @Deprecated

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#1096]
Swagger spec contains the deprecated information.

The asciidoc does not capture that information and so does the html docs.

**Comment by dilipkrish** [comment]
I think this information is supported in the library. Unless there is a bug it should just work as expected. Perhaps its  not yet supported in swagger2markup. @RobWin?

**Comment by RobWin** [comment]
Funny. I just asked for it in the Gitter Channel :)

**Comment by RobWin** [comment]
Yes its bot Supported yet, but i would like to add it.

**Comment by RobWin** [comment]
@rajeshkamal See Swagger2Markup/swagger2markup#46

**Comment by rajeshkamal** [comment]
Thanks @RobWin @dilipkrish
