### ISSUE TITLE
Is there a way to get #750 and #909 fixed at the same time?

### ISSUE THREAD

**Issue by pavel-mikhalchuk** [springfox/springfox#1097]
Hi!

If I disable enableUrlTemplating to fix #909 then we end up with #750 for some other APIs. What would you suggest?

Thanks!

**Comment by dilipkrish** [comment]
Unfortunately until the spec evolves to support RFC6570 we're stuck with this. If waiting isn't an option you might try patching the swagger-ui with my [forked fix](https://github.com/dilipkrish/swagger.js/commits/feature/rfc6570-support) of swagger.js.

***NOTE:*** this whole enabledUrlTemplating stuff is in incubation.

**Comment by pavel-mikhalchuk** [comment]
Thanks!

**Comment by rajeshkamal** [comment]
Hi,

@dilipkrish any chance that you could incorporate this into the springfox-swagger-ui. So that                 enableUrlTemplating works fine from Swagger UI.

That would be really helpful.

**Comment by dilipkrish** [comment]
It is in [an experimental release](http://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui-rfc6570/0.9.4) :secret: :wink:

**Comment by mvander3** [comment]
Is there a permanent fix for this issue? It seems like even with 2.6.0 that I get only a single operation (#750) without enableUrlTemplating and I get broken urls (#909) with it.

**Comment by dilipkrish** [comment]
It's been fixed. Perhaps create a new issue with steps to reproduce.

**Comment by dilipkrish** [comment]
@mvander3 You have to use the latest rfc6570 swagger-ui library when you turn on templates urls. Please refer the docs.

**Comment by Waterstrong** [comment]
Hi @dilipkrish, It seems that the latest rfc6570 swagger-ui is not compatible with the latest swagger 2.7.0. The swagger ui is not displaying correctly. How can I solve the both issues at the same time?

**Comment by Waterstrong** [comment]
Just did a quite trial, [swagger ui rfc6570 1.0.0](http://mvnrepository.com/artifact/io.springfox.ui/springfox-swagger-ui-rfc6570/1.0.0) is working well with [swagger 2.6.0](http://mvnrepository.com/artifact/io.springfox/springfox-swagger2/2.6.0). Thanks.

**Comment by dilipkrish** [comment]
@Waterstrong it should work with 2.7.0 as well. Whats do you see.
