### ISSUE TITLE
strange warning message from io.swagger.models.parameters.AbstractSerializableParameter

### ISSUE THREAD

**Issue by mherb63** [springfox/springfox#1100]
I'm getting the following output on a GET from my swagger page:

<pre>
 WARN 2015-12-15 07:51:28,834 [tomcat-http--46][] io.swagger.models.parameters.AbstractSerializableParameter - Illegal DefaultValue  for parameter type integer
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:453)
	at java.lang.Long.valueOf(Long.java:540)
	at io.swagger.models.parameters.AbstractSerializableParameter.getDefault(AbstractSerializableParameter.java:161)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.get(BeanPropertyWriter.java:726)
</pre>

I'm not using any DefaultValue annotations, so I don't understand why the code is even taking this path.

Is there a work-around?

**Comment by dilipkrish** [comment]
This is an issue in `swagger-core`. See [here](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java#L202) for details. Nothing we can do about it other than asking you to ignore this in your logs :disappointed:

**Comment by imod** [comment]
how about fixing upstream?

**Comment by dilipkrish** [comment]
Great idea. Could you create an issue with swagger core referencing this issue perhaps? Perhaps a PR to fix it would be super awesome.

**Comment by imod** [comment]
done: https://github.com/swagger-api/swagger-core/issues/1568

**Comment by imod** [comment]
as a temporary workaround, I disabled the logger for that specific class (in logback.xml when using slf4j):

```
<logger name="io.swagger.models.parameters.AbstractSerializableParameter" level="ERROR" />
```

**Comment by dilipkrish** [comment]
:+1: thanks @imod

**Comment by mherb63** [comment]
Yup, I didn't try it.  I had another issue where I wanted some @Controllers to be hidden, ie. not exposed on the Swagger UI.  I used @ApiIgnore for that which worked great and this issue went away.

Having said that, I think, but have not tested, that you want 
<pre>
<logger name="io.swagger.models.parameters.AbstractSerializableParameter" level="WARN" />
</pre>

to be rid of this message, because it is a "WARN" and not an "ERROR".

Anyway, good catch Imod.

**Comment by imod** [comment]
@mherb63 `ERROR` is correct (more restrictive), because I only wanna see no messages of level `WARN`

**Comment by ydp** [comment]
@imod 's method works for me,  I had the same problem too, using log4j, add this line in log4j.properties:

log4j.logger.io.swagger.models.parameters.AbstractSerializableParameter=error

**Comment by TonyLuo** [comment]
Swagger 1.5.6 has been released to fix this issue.

**Comment by tokuhirom** [comment]
I got same warning message. Could you do maintenance release to upgrade dependencies?

**Comment by dilipkrish** [comment]
Should be releasing 2.4.0 pretty soon no point releasing a patch before that

**Comment by tokuhirom** [comment]
okay, i see.

**Comment by evanbross** [comment]
Still seeing this. Wish the exception message would at least tell which api/parameter is causing the problem.
