### ISSUE TITLE
Can I hide @Controllers from Swagger UI

### ISSUE THREAD

**Issue by mherb63** [springfox/springfox#1102]
Question: Is it possible to exclude @Controller classes from rendering in the Swagger UI page?

Sorry if this question has been asked, but this project seems to be pretty dynamic and I wanted to get the latest insights.

Thanks!

**Comment by rajeshkamal** [comment]
Try using the @ApiIgnore annotation at the controller level.

**Comment by mherb63** [comment]
Yes, that works.  Thank you Rajesh!

**Comment by SubinrajS0493** [comment]
What is the alternative for @ApiIgnore ? Where I don't want to add this annotation to  50 controllers from 15 different packages ?

**Comment by psinalberth** [comment]
> What is the alternative for @ApiIgnore ? Where I don't want to add this annotation to 50 controllers from 15 different packages ?

Have you tried 
`paths(Predicates.not(PathSelectors.ant(path)))` or `paths(Predicates.not(PathSelectors.regex(regex)))`

in Docket definition?

**Comment by kanai0618** [comment]
Hi @psinalberth  @apiignore is not found for me, do u know why ? is there any dependency needed ?

**Comment by sharathkolibyle** [comment]
> What is the alternative for @ApiIgnore ? Where I don't want to add this annotation to 50 controllers from 15 different packages ?

did you find any solution for this ?
