### ISSUE TITLE
grouping by @Api value

### ISSUE THREAD

**Issue by imod** [springfox/springfox#1103]
all our controllers have annotations like this one:

`@Api(value = "auth", description = " ")`

in the old implementation of `swagger-springmvc` the operations where grouped by the `value` (here `auth`). e.g. having multiple controllers with the same `@Api` annotation where showing up in the same section in the UI. 

Now since I'm migrating to swagger 2.0, all controllers are listed separately and the `value` of the `API` annotation seems to be ignored.
Is there anything I can do to get the old behavior back?

**Comment by dilipkrish** [comment]
@imod The resource grouping is no longer available. It used to be that way for swagger 1.2. 

Since swagger 2.0 uses tags to facilitate grouping, this feature is no longer supported (hence the deprecation). Keep in mind that while swagger-ui might not respect tags, it will in the future.

**Comment by imod** [comment]
is there any documentation how to use tags with springfox? So I could at least start grouping them already, so it will work with a future version automatically?

**Comment by dilipkrish** [comment]
@imod Details [available in this issue](https://github.com/springfox/springfox/issues/1039). Essentially
tags can be defined via `@Api` at the controller level and `@ApiOperation` annotation at the operation level. The tags on each operation are a union of tags on the Controller and the handler method. Swagger-ui does not support tags yet, but when you use the swagger editor you can use it to group by tags as u see fit

**Comment by imod** [comment]
@dilipkrish grouping by tags is still not available - right?
