### ISSUE TITLE
swagger-ui.html show nothing

### ISSUE THREAD

**Issue by Walter0507** [springfox/springfox#1105]
Hey springfoxer:
I can visit url '/v2/api-docs' and 'swagger-ui.html'. The json document seems ok. But in swagger-ui.html, I cannot find any api here.

So I check the browser and find some error in swagger-ui-min.js:
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined(anonymous function) @ swagger-ui.min.js:13Handlebars.templates.param_list.Handlebars.template.main @ swagger-ui.min.js:1e @ handlebars-2.0.0.js:27SwaggerUi.Views.ParameterView.Backbone.View.extend.render @ swagger-ui.min.js:13SwaggerUi.Views.OperationView.Backbone.View.extend.addParameter @ swagger-ui.min.js:13SwaggerUi.Views.OperationView.Backbone.View.extend.render @ swagger-ui.min.js:12SwaggerUi.Views.ResourceView.Backbone.View.extend.addOperation @ swagger-ui.min.js:13SwaggerUi.Views.ResourceView.Backbone.View.extend.render @ swagger-ui.min.js:13SwaggerUi.Views.MainView.Backbone.View.extend.addResource @ swagger-ui.min.js:12SwaggerUi.Views.MainView.Backbone.View.extend.render @ swagger-ui.min.js:12window.SwaggerUi.Backbone.Router.extend.render

Could you help to check this issue? Thanks.

**Comment by dilipkrish** [comment]
Thats not much information to figure out the problem. See [guidelines for posting issues](https://github.com/springfox/springfox/wiki/Issue-Submission). Plus thats an issue with swagger-ui (unless of course springfox is generating a bad service description)

**Comment by Walter0507** [comment]
I think I may miss some configuration, because the console shows error 'validatorUrl' is not found.

2015-12-21 10:26:58,312 [http-bio-8080-exec-8] WARN  [org.springframework.web.servlet.PageNotFound] - No mapping found for HTTP request with URI [/security/validatorUrl] in DispatcherServlet with name 'springmvc'

I already configure the component scan '<context:component-scan base-package="springfox.documentation"/>' in spring context file. So where should I do more configure?

**Comment by Walter0507** [comment]
@dilipkrish Here is the problem 

the interface ‘/v2/api-docs’ is ok.
![image](https://cloud.githubusercontent.com/assets/11749534/11928807/6d0d93e2-a811-11e5-95e0-17a92270ff53.png)

the interface '/swagger-ui.html' is available, But it seems there is no api here?
![image](https://cloud.githubusercontent.com/assets/11749534/11928865/bdf04d18-a811-11e5-8b43-a7935e2dd5a6.png)

And I also saw there is a js error here:
![image](https://cloud.githubusercontent.com/assets/11749534/11928904/fb5aa630-a811-11e5-94e4-875d2964b0e6.png)

So is there any steps I missed?
Thanks

**Comment by Walter0507** [comment]
@dilipkrish 
ok, I know why this error happens.

I have one method using 'httpservletResponse' as a parameter. So this could impact the js. But I think this situation should commonly be used in 'download' function.

So any adverse on how to solve this issue? I also try to add @ApiIgnore on 'HttpServletResponse', but it seems un-work.

waiting you response. 
Thanks.

**Comment by dilipkrish** [comment]
Instead of using @ApiIgnore you need to use 

```java
//In your docket configuration add...
docket.ignorableTypes(HttpServletResponse.class)
```
