### ISSUE TITLE
How to Customize Swagger-UI

### ISSUE THREAD

**Issue by ashwanikumar04** [springfox/springfox#1108]
Hello:
I am using Swagger UI to document the apis.
```
 compile 'io.springfox:springfox-swagger2:2.3.0'
    compile("io.springfox:springfox-swagger-ui:2.1.1")
```
I use this to show Swagger UI. Is there any way I can customize the static files (html/css).

Thanks,
Ashwani

**Comment by dilipkrish** [comment]
First up upgrade swagger-ui from `2.1.1` to `2.3.0`

If you need to customize the swagger-ui I'd suggest doing it on your own. This library is only to quickly jumpstart your default swagger-ui.

**Comment by ashwanikumar04** [comment]
Thanks Dilip. I am ready to do the modification myself. Can you tell me how to access html/css files, so that they can be modified.

**Comment by dilipkrish** [comment]
Sources available @ [swagger-ui](https://github.com/swagger-api/swagger-ui). Just download -> customize -> package either as a webjar or as resources in your application -> create resource handler mapping if required

**Comment by ashwanikumar04** [comment]
Hello Dilip:

I could not find download -> customize -> package 
@https://github.com/swagger-api/swagger-ui.

**Comment by dilipkrish** [comment]
@ashwanikumar04  those were steps for _YOU_ to do
1. Go to https://github.com/swagger-api/swagger-ui
2. download [latest code](https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.3)
3. customize what ever you want to customize 
4. package either as a webjar or as resources in your application 
5. create resource handler mapping if required

Hope that makes it makes it clearer

**Comment by SumanPoloju** [comment]
@dilipkrish , Hi Dilip Krish can you explain me how to customize the inbuilt swagger-ui.html file.
I have created a spring maven project by adding swagger dependencies in pom.xml file. and then added the below code in dispatcher-servlet.xml file.
<mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/" />
<mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/swagger-ui.html" />
Created SwaggerConfig file , created my respective controllers along with services.
When i run my application : http://localhost:8080/YourWorkPlace/swagger-ui.html , getting the below screen
![swagger_ui](https://user-images.githubusercontent.com/39796577/40778016-430014d0-64ed-11e8-89ba-987d8891c397.png)
i have attached the screen. Now i want to change the swagger title,logo and header.. 
How it can be achieved ? please guide me..

**Comment by dilipkrish** [comment]
@SumanPoloju steps [outlined here](https://github.com/springfox/springfox/issues/1108#issuecomment-167120179)

**Comment by hoangleoiuh** [comment]
> @ashwanikumar04 those were steps for _YOU_ to do
> 
> 1. Go to https://github.com/swagger-api/swagger-ui
> 2. download [latest code](https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.3)
> 3. customize what ever you want to customize
> 4. package either as a webjar or as resources in your application
> 5. create resource handler mapping if required
> 
> Hope that makes it makes it clearer

Hi @dilipkrish , in step 4, I don't know how do it, can you explain details for me. Thanks.

**Comment by aipirvu** [comment]
> > @ashwanikumar04 those were steps for _YOU_ to do
> > 
> > 1. Go to https://github.com/swagger-api/swagger-ui
> > 2. download [latest code](https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.3)
> > 3. customize what ever you want to customize
> > 4. package either as a webjar or as resources in your application
> > 5. create resource handler mapping if required
> > 
> > Hope that makes it makes it clearer
> 
> Hi @dilipkrish , in step 4, I don't know how do it, can you explain details for me. Thanks.

At step 4 you should simply copy the content from either `/dist` or `/src/main/html` with the modifications you made to the resource folder on your application. In my case I coppied it to `resources/swagger-ui/` just to not mix with other resource like `application.properties` or `banner.txt` that I added for my spring boot application. At this point (step 5 in list) you have to configure the application to serve the content from that folder. In my case I mapped the `/swagger-ui/**` to the folder I created in resources:

```java
@Configuration
@EnableWebMvc
public class MvcConfig implements WebMvcConfigurer {
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/swagger-ui/**")
                .addResourceLocations("classpath:/swagger-ui/");
    }
}
```
Here is a look on how I have these arranged on my application. This is a module that I use to make common configurations for my rest microservices.
![image](https://user-images.githubusercontent.com/13658952/72499186-cd7c7b00-3839-11ea-8cc8-a9802041998a.png)

Please note that the swagger-ui source is hardcoded with a demo swagger documentation url. You would probably want to change that to load with your own documentation by default. In my case I changed it to `/v2/api-docs`:
```javascript
...
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "/v2/api-docs";
      }
...
```

Also you don't need any swagger-ui depdencies in the pom.xml file. So remove any depdency like this if you still have it.
```xml
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.9.2</version>
</dependency>
```

**Comment by madvens** [comment]
Hi @aipirvu, you said: 

> At step 4 you should simply copy the content from either /dist or /src/main/html with the modifications you made to the resource folder on your application. 

But there is no `/src/main/html` in [https://github.com/swagger-api/swagger-ui](https://github.com/swagger-api/swagger-ui). Where do I copy that content from? There is a `dist/` folder but its contents are not the same as your `resources/swagger-ui/` folder's content.

**Comment by aipirvu** [comment]
> Hi @aipirvu, you said:
> 
> > At step 4 you should simply copy the content from either /dist or /src/main/html with the modifications you made to the resource folder on your application.
> 
> But there is no `/src/main/html` in https://github.com/swagger-api/swagger-ui. Where do I copy that content from? There is a `dist/` folder but its contents are not the same as your `resources/swagger-ui/` folder's content.

Hi, it took me a while to figure it out. As it seems, I clicked the link in step 2 which directed me to the assets of the release 2.1.3. That was released in 2015. I did not event realized it until now.

Based on what I see in `src/package.json`, the current version seems to have been migrated to react. I am sorry, but I do not have the expertise required to advice you on how to modify the source files for this type of project. I believe you should either learn to work with react if you want to make significant changes or, if you only want to get away with style changes, use the `dist` content, add a new css that overwrites the existing styles and include it in the index.html

**Comment by gdinant** [comment]
Hello guys, with SpringFox 3.0.0 is this still accurate?

To my understanding SpringFox handles several API definitions where swagger-ui doesn't, does it? If I checkout the dist of swagger-ui I run with an entirely different front-end (for instance the select a definition would be missing).

Would there be a way to provide a custom.css or something like that to the framework in order to play with the stylesheet or do we absolutely need to replace everything?
