### ISSUE TITLE
how can i set my requestbody's obj properties

### ISSUE THREAD

**Issue by lmx1989219** [springfox/springfox#1112]
![image](https://cloud.githubusercontent.com/assets/9464485/11975074/f2993dce-a9a4-11e5-9344-f368e6971717.png)

'optional' can set to required/optional according to my need?

**Comment by dilipkrish** [comment]
Adding `@ApiModelProperty(required=true)` should do it

**Comment by lmx1989219** [comment]
thanks for your help.the annotation above should be writen on entity's field?
Java code:
class user{
    @ApiModelProperty(required=true)
     string username;
}

Like this?

**Comment by dilipkrish** [comment]
:heavy_check_mark:

**Comment by lmx1989219** [comment]
so great,it's ok now.
but i have another question,for example:the response data have a number of fields,i hope i can according to my needed to show appointed field.

**Comment by dilipkrish** [comment]
It's not clear what you're expecting to do. Maybe an example would help

**Comment by lmx1989219** [comment]
class Resp{
@ApiModelProperty(required=true)
 int code;
@ApiModelProperty(required=true)
 String msg1;
 String msg2;
}
above described class be multiplexed by more api response entity.
a api  response entity need show code and msg1 , the other one  show code and msg2.

**Comment by dilipkrish** [comment]
For this I would defer to #601

**Comment by lmx1989219** [comment]
so cool.
