### ISSUE TITLE
why have to specify request method explcitly or ui will display all methods of this url mapping

### ISSUE THREAD

**Issue by zhugw** [springfox/springfox#1113]
Used 2.2.2. In ui interface found below phenomenon. 
Request Mapping is
```
@RequestMapping("/count")
```
In ui interface you'll see so many items of `/count`, 
![screenshot from 2015-12-27 14 50 45](https://cloud.githubusercontent.com/assets/4953871/12009220/48f77fc0-acaa-11e5-8eaa-0e9d3e7d3c8c.png)

You must specify method explicitly, e.g.
```
@RequestMapping(value="/count",method=RequestMethod.GET)
```
Now in ui interface it only have
![screenshot from 2015-12-27 14 53 31](https://cloud.githubusercontent.com/assets/4953871/12009213/01b6ccec-acaa-11e5-9e58-69df28eef7a0.png)

**Comment by dilipkrish** [comment]
@zhugw because implicitly thats how the spring mvc controller methods behave.
