### ISSUE TITLE
Could not define global consumes and produces set

### ISSUE THREAD

**Issue by wxjlibra** [springfox/springfox#1115]
I'm trying to add global content-type with add following code snippet.

return new Docket(DocumentationType.SWAGGER_2)
		.groupName("BBI").consumes(Sets.newHashSet("application/json")).produces(Sets.newHashSet("application/json"))

however the response content type keeps showing */* unless I specifically specify the consume/produce field in 'requestMapping' annotation

**Comment by dilipkrish** [comment]
Thanks for reporting! :+1:

**Comment by wxjlibra** [comment]
thanks man!
