### ISSUE TITLE
Documentation Unuseable

### ISSUE THREAD

**Issue by abaile33** [springfox/springfox#1117]
Example: newArrayList (with no space between 'new' and 'ArrayList'), is this an error? Doesn't work in my code but it is used in your documentation and in demo apps for springfox.

Example: Even if I add a space between 'new' and 'ArrayList', the constructor ArrayList(ApiKey) is undefined. What should be used instead of what is shown in the documentation?

There are many errors similar to the examples above. Please save the many developers that may be trying to use your documentation a week by spending a few hours to make the documentation accurate.

I appreciate the work done here. A few more hours would save the rest of the world a few years of man hours.

**Comment by dilipkrish** [comment]
As explained [in this comment](https://github.com/springfox/springfox-demos/issues/15#issuecomment-168465056), Its the usage of guava library that is possibly a cause for confusion. This has now been called out in the documentation.

Also, the code snippets that we have are tested or form the basis for testing for e.g. the example you're referring to above is [an actual configuration](https://github.com/springfox/springfox/blob/master/springfox-spring-config/src/main/java/springfox/springconfig/Swagger2SpringBoot.java) used for functional testing. So they are guaranteed to be a working snippet of code.

**Comment by abaile33** [comment]
Thank you for your clarification. This helps a lot. 
On Jan 3, 2016 7:10 AM, Dilip Krishnan <notifications@github.com> wrote:As explained in this comment, Its the usage of guava library that is possibly a cause for confusion. This has now been called out in the documentation.

Also, the code snippets that we have are tested or form the basis for testing for e.g. the example you're referring to above is an actual configuration used for functional testing. So they are guaranteed to be a working snippet of code.
