### ISSUE TITLE
Release 2.3.1 announcement

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#1118]
# Maintenance
- Remove runtime dependency on `spring-hateoas` #1104 
- Fix the accidental reference to `java.util.Objects` class so that java 6 is still supported
- Upgraded gradle to 2.10
- Upgraded to swagger 1.5.5
- Fix Documentation Formatting
- Upgraded jdk to 8 for building
- Upgrade Classmate to 1.3.1 #1079
- Document use of google guava in code examples #1117

# Pull Requests
- v2/api-docs does not support application/json media type by default  #1110
- Add support for api model property positions.  feature PR #1101 

# Bug Fixes
- Could not define global consumes and produces set #1115
- Support for showing controller methods with defaulted @RequestMapping#params values with different values is incorrect #1114

Big thank you to  @wxjlibra, @abaile33 for reporting bugs and Thanks @sbuettner and @vmarusic for the PRs!

**Comment by marcintokarski** [comment]
Hi,
#1101 seems don't merged to master.
There are differences in https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ModelMapper.java
and 

https://github.com/sbuettner/springfox/blob/326b43e6de7274f115aef0e15f56c4eeae1e111e/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ModelMapper.java

I use 2.3.1 version and position in @ApiModelProperty don't work.

Regards

**Comment by dilipkrish** [comment]
@marcintokarski Its definitely in master. Its different from the commit you've highlighted because its been [polished after its been merged in](https://github.com/springfox/springfox/commit/cdb4c1bb6be2c6fd59aa583bdc4a4acbfcba96ff). It might still be a bug, but I really doubt it. Feel free to open an issue if you've confirmed a regression.

**Comment by marcintokarski** [comment]
Thank you for your response. I will test it again. When bug will be still
exist i will open issue.

śr., 13.01.2016 o 14:42 użytkownik Dilip Krishnan <notifications@github.com>
napisał:

> @marcintokarski <https://github.com/marcintokarski> Its definitely in
> master. Its different from the commit you've highlighted because its been polished
> after its been merged in
> <https://github.com/springfox/springfox/commit/cdb4c1bb6be2c6fd59aa583bdc4a4acbfcba96ff>.
> It might still be a bug, but I really doubt it. Feel free to open an issue
> if you've confirmed a regression.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/springfox/springfox/issues/1118#issuecomment-171293786>
> .
>
-- 

Pozdrawiam
Marcin Tokarski
