### ISSUE TITLE
Infinite loop when springfox tries to determine schema for objects with nested/complex constraints

### ISSUE THREAD

**Issue by ircecho** [springfox/springfox#1121]
First of all, please excuse the vagueness of this bug report. I've been debugging for two days already and this is the best I can come up with. Maybe you can find the problem anyways.

First of all, I added Springfox to our project and now the project cannot start because Springfox is busy with determining the model schema (for as long as I let it). The model schema is self contained in our application and serialization to JSON works without any problems, so the schema should not be at fault. I investigated and this is my theory:

We have the property
``` java
    public List<TransferGrossPricingBasic> getSums() {
        return null;
    }
```
which is defined in a class that looks like this,
``` java
public class TransferCheckoutArticleCollectionBase<T extends AbstractCheckoutArticleCollectionShippingBase, U extends TransferCheckoutArticleBase> extends TransferObjectBase<T> {
```
which we extend, and the extended class is returned by an endpoint. In the extension it is parametrized as follows:
``` java
TransferCheckoutArticleCollectionBase<Order, TransferCheckoutArticle>
```
The property is recognized as follows 
`[Property 'sums'; ctors: null, field(s): null, getter(s): [method com.~.TransferCheckoutArticleCollectionBase#getSums(0 params)][visible=true,ignore=false,explicitName=false], setter(s): null]`
and when determining the type, springfox finds this:
`java.util.List<com.~.TransferGrossPricingBasic<com.~.Order<com.~.TransferCheckoutArticle>,com.~.TransferCheckoutArticle>>`. I left out some packages for clarity. Now I think this is wrong. Type should actually be `java.util.List<com.~.TransferGrossPricingBasic>`. Somehow it seems to take the type parameters from the from the containing class (`TransferCheckoutArticleCollectionBase`) and add them to the return type. Is this even a bug? I think the problem should be around `springfox-schema-2.3.1-sources.jar!/springfox/documentation/schema/property/OptimizedModelPropertiesProvider.java` line 123 and the methods, which are called there. Is it possible that, when determining type, type parameters from containing classes are added to return types under really special circumstances?

In our case I think this leads to Springfox trying to serialize Order class, which in turn pulls in all of our Hibernate classes and more, which takes seemingly forever.

**Comment by dilipkrish** [comment]
Thanks for reporting it. This may very well be a bug, should be simple to write a breaking test for it I would assume. 

However, I would try and see if a work around might fix your problem. How about trying to ignore your hibernate classes for e.g. `Order` using the `docket. ignoredParameterTypes(Order.class)`?

**Comment by ircecho2** [comment]
With your workaround model resolution terminates.

**Comment by dilipkrish** [comment]
:+1: 

Before we push this issue below the rug, you should probably also verify that the swagger description for the models is what you'd expect.

**Comment by ircecho2** [comment]
I checked everything now. The workaround is fully functional.
