### ISSUE TITLE
Default page served isn't configurable and lacks search / listAll functionality

### ISSUE THREAD

**Issue by porcoesphino** [springfox/springfox#1122]
As a new user, exploration of a API is faster if the user can search for endpoints or expand all (not fully, just to list).

The [swagger-ui.html](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/swagger-ui.html) file is not configurable in anyway so adding this would requires serving your own copy of the file. Some options that should be accessible are `docExpansion`, javascript at the end of the page or a div for some custom html.

The default [swagger-ui.html](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/swagger-ui.html) should include a button to expand all to list view. Here is a javascript bookmarklet doing this:

```
javascript:(function(){
  if (window.swaggerUi.getOption('docExpansion') === 'list') {
    window.swaggerUi.collapseAll();
    window.swaggerUi.setOption('docExpansion', 'none');
  } else {
    window.swaggerUi.listAll();
    window.swaggerUi.setOption('docExpansion', 'list');
  }
})();
```

The default [swagger-ui.html](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/swagger-ui.html) should include a searchbox of the api. Here is a bookmarklet using the API key box to do this (taken from [this swagger-ui bug](https://github.com/swagger-api/swagger-ui/issues/1096)):

```
javascript:(function(){

    var checkEmptyResources = function() {
        return $('.resource').each(function(i, res) {
          var visibleChildren;
          visibleChildren = $(res).find('.operation').filter(function(ii, op) {
            return $(op).css('display') !== 'none';
          });
          if (visibleChildren.size() <= 0) {
            return $(res).hide();
          } else {
            return $(res).show();
          }
        });
    };

    var pattern, searchterm;
    searchterm = $('#input_apiKey').val();
    pattern = new RegExp(searchterm, 'i');
    $('.operation').each(function(i, op) {
      var opDescription, opID, opSummary;
      opID = $(op).prop('id');
      opSummary = $(op).find('a.toggleOperation').text();
      opDescription = $(op).find('.markdown p').text();
      if ((pattern.test(opID)) || (pattern.test(opSummary)) || (pattern.test(opDescription))) {
        return $(op).show();
      } else {
        return $(op).hide();
      }
    });
    return checkEmptyResources();
})();
```

Noted that `swagger-ui` are working on adjusting their javascript library to add this but that doesn't change:

- the ease of changing [swagger-ui.html](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/swagger-ui.html) for someone who would rather be working on something else,
- this being a trivial change to a default file that users can't configure in this repository that will have value to most users of the final served page.

**Comment by dilipkrish** [comment]
These are great ideas :metal:. Would love to get a PR since you're more familiar with this than I admit to being.

Having said that, the _swagger-ui_ that ships with this library is more of a convenience for spring framework users rather than a full blown customized swagger-ui. The fewer customizations to the script the better we stand at taking upgrades from the mother ship.

**Comment by porcoesphino** [comment]
Oh yeah, it would only be an alterations to ` swagger-ui.html`. I'll work on an PR for you.

**Comment by dilipkrish** [comment]
also have a look [at this pr](https://github.com/springfox/springfox/pull/1127)

**Comment by porcoesphino** [comment]
Thank you.
