### ISSUE TITLE
JDK 1.6 Compatibility

### ISSUE THREAD

**Issue by loverde** [springfox/springfox#1130]
Ran into an issue with the 2.3.0+ releases.  Not sure if this is the only issue, but at the very least OperationCachingEquivalence.java is using java.util.Objects causing ClassNotFoundExceptions.  Any chance you could switch to using Guava MoreObjects instead or just inline the functions you need?

**Comment by dilipkrish** [comment]
I think it's been fixed in 2.3.1. Could you try that version

**Comment by loverde** [comment]
Thanks, I must have missed that there was a 2.3.1 release.  Changing to that resolved the issue and it's running with JDK 1.6 now.
