### ISSUE TITLE
Api operations on abstract superclass not affected by @API tags

### ISSUE THREAD

**Issue by gionn** [springfox/springfox#1132]
I've a bunch of @RestController annotated via @API( tags="whatever") that extends an abstract class DeleteController, that implements a common DELETE operation.

The delete operation doesn't appears grouped under the whatever tags, but is left stand-alone as if it was without tags, so the @API tags doesn't propagate.

**Comment by dilipkrish** [comment]
Thanks for reporting! That is indeed a bug. The workaround is to add an `@ApiOperation(tags=[<all the service tags>]`, not pretty I know but it should get you by.

**Comment by dilipkrish** [comment]
The fix is to replace `handlerMethod.getMethod().getDeclaringClass();` with `handlerMethod.getBeanClass()` [here](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/SwaggerOperationTagsReader.java#L70).
