### ISSUE TITLE
Finding a way to parse my own annotation

### ISSUE THREAD

**Issue by choiapril6** [springfox/springfox#1135]
Like I mentioned on the issue #1088, I am finding a way for springfox to parse my own annotation.

I thought I could do this by editing springfox source code, but being mentioned by @dilipkrish in the thread of issue #1088, creating a plugin is a better way. 

The annotation that should be read by springfox would look like:

```
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Mapping
public @interface AuthorizeMemberWithAllowedActionList {
	
	MemberAllowedAction[] allowedActions() default {};

}
```
This annotation is what Springfox with some help of custom plugin that I am going to work on should read. 
Since it's my first time developing a plugin, I might need to refer to [Maven: Guide to Develop a Java Plugin] (https://maven.apache.org/guides/plugin/guide-java-plugin-development.html). Still, I guess I have more steps to go to fulfill my needs. If you could give me guidance to do this, I'd very appreciate. Thank you.

**Comment by dilipkrish** [comment]
By _plugin_ I dint mean a maven plugin. sorry if I wasn't being clear. Let me dig up or write up some documentation for you

**Comment by dilipkrish** [comment]
Take a look at this comment to help you [get started with plugin development](https://github.com/springfox/springfox/issues/182#issuecomment-171133102).
