### ISSUE TITLE
How to set data-type for @RequestBody parameter?

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [springfox/springfox#1138]
I have the following restcontroller method which has a generic `Map` parameter which in the method is bound to a `Profile` entity:

```java
@RequestMapping(path = "{id}", method = RequestMethod.PATCH)
public Profile patch(@PathVariable long id, @RequestBody Map data) {

    Profile profile = profileRepository.findOne(id);

    RestDataBinder binder = binderFactory.createBinder(profile);
    binder.bind(data);
    binder.validate();
    binder.close();

    entityManager.merge(profile);
    return profile;
}
```

Is it possible to set the data-type of `@RequestBody Map data` parameter to `Profile` so that the correct model schema is generated? F.e. something like: 

```java
@RequestMapping(path = "{id}", method = RequestMethod.PATCH)
public Profile patch(@PathVariable long id, 
                     @ApiParam(dataType='com.example.Profile') @RequestBody Map data) {
    ... 
}
```

If I need to make a custom plugin for this, can someone point me in the right direction? Thanks!

**Comment by dilipkrish** [comment]
Yeah it appears that hidden property hasn't been made good use off! :) thanks for catching that. I'd recommend creating a new plugin to read it and set it in the parameter builder that is in play. A good example of that would be the [ParameterRequiredReader](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/parameter/ParameterRequiredReader.java#L48). Would love a PR for it!

**Comment by Jaap-van-Hengstum** [comment]
I'm a bit confused why you changed the title of this issue.

> I'd recommend creating a new plugin to read it and set it in the parameter builder that is in play. A good example of that would be the ParameterRequiredReader. Would love a PR for it!

Is this the answer to my question above (about explicitly specifying the datatype of a `@RequestBody` parameter) or with my other issue about the hidden attribute in the `@ApiParam` annotation?

Sorry for the confusion.

**Comment by dilipkrish** [comment]
@Jaap-van-Hengstum sorry wrong issue and wrong answer. :) need more sleep

**Comment by dilipkrish** [comment]
For this issue, its probably not possible to do this as `@ApiParam` _does not_ have a dataType property
