### ISSUE TITLE
@ApiParam(hidden = true) parameter still is shown in the Swagger docs

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [springfox/springfox#1139]
In the following restcontroller method:

```java
@RequestMapping(method = RequestMethod.PATCH)
@Transactional
public Profile patch(@ApiParam(hidden = true) @AuthenticationPrincipal ApiUser user,
                     @RequestBody Map data) {

      ...
}
```

the first parameter `ApiUser` is still shown in the Swagger docs even though I set the `hidden` attribute. Is this a bug?

**Comment by Jaap-van-Hengstum** [comment]
Using `ignoredParameterTypes` on the `Docket` declaration works:

```java
        return new Docket(DocumentationType.SWAGGER_2)
                .ignoredParameterTypes(AuthenticationPrincipal.class)
                .build();
```

**Comment by dilipkrish** [comment]
@Jaap-van-Hengstum thats exactly what Id have suggested. :+1:

**Comment by acurci** [comment]
.ignoredParameterTypes(AuthenticationPrincipal.class) exclude all ocurrences...
in my case, i have a generic controller and i need hide this:
```java
@ApiParam(value="dummy", hidden=true, required=false)  T dummy
```
How can i do for hidden this param?

Thanks

**Comment by dilipkrish** [comment]
Its easier to add @ApiIgnore in from of the parameter

**Comment by gfiguero937** [comment]
Hi!, what if the parameter is inside an object and as part of the request body?. 
e.g.:
@RequestBody List<FilmRental> filmList 
and what I'm trying to hide is:

    private Film film;
    **private LocalDate startDate;**
    private long daysRentedFor;

Thanks!

**Comment by dilipkrish** [comment]
@gfiguero937 You can use the standard jackson facilities to ignore e.g `@JsonIgnore`

**Comment by gfiguero937** [comment]
@dilipkrish Right!, thanks a lot!

**Comment by Zumbolovsky** [comment]
@dilipkrish I don't know if using `@ApiModelProperties` or `@ApiParam` would work this way but on this same topic (following gfiguero937's example) if I had a request with an object as a parameter, just as he did but without the `@RequestBody`, would there be a way for me to hide another object attribute?
e.g.:
I have this set as parameter for the controller method: 

`findAllLite(ContributionDTO dto)`

And this ContributionDTO has the following attributes:

```
@ApiModelProperty(hidden = true)
private PostAnimalDTO postAnimalDTO;

@ApiModelProperty(hidden = true)
private PostItemDTO postItemDTO;
```

but PostItemDTO and PostAnimalDTO have each their own attributes, which may or may not be objects, and so on...

These that have the `@ApiModelProperty(hidden = true)` still show on the model (that is, their attributes). 

What I'm trying to say is that, the model that was generated enters the objects, and I'm not sure how I should stop that from happening. Any suggestions on a way to fix this using annotations?

Thanks in advance

**Comment by dilipkrish** [comment]
@Zumbolovsky This is an old issue, in general please refrain from commenting on issues that are for an older version. What version are you using?

Also, Im not sure what you mean by "that was generated enters the object". In any case, there is a feature being worked on that will help with your issue, essentially what might be happening is that if the model (DTO) is used in a request and a response, it will take the union of all the properties regardless of the hidden attribute.

**Comment by Zumbolovsky** [comment]
@dilipkrish My version is 2.8.0 and thanks for your feedback.

What I meant to say is that the springfox generated API documentation for swagger uses the nested object attributes as model properties when I need them disabled. If there is a feature being worked on regarding this issue I'd be happy if you could link it to me in order for me to follow its development.

Again, I appreciate the attention

**Comment by dilipkrish** [comment]
You can use the `ignoredParameterTypes` in your docket to prevent navigating nested objects of a certain type

**Comment by jaychang9** [comment]
@dilipkrish Greate! It works! @ApiIgnore is very usefull to ignore param in controller's method,especially when you define some Annotation that Custom HandlerMethodArgument to process

**Comment by uqix** [comment]
> Using `ignoredParameterTypes` on the `Docket` declaration works:
> 
> ```java
>         return new Docket(DocumentationType.SWAGGER_2)
>                 .ignoredParameterTypes(AuthenticationPrincipal.class)
>                 .build();
> ```

This will ignore those return types as well

**Comment by javaHelper** [comment]
@dilipkrish - Could you please guide me here : https://stackoverflow.com/questions/57625764/unable-to-hide-pageable-object-from-swagger-ui ?

**Comment by csongithub** [comment]
@dilipkrish 
I have little different scenario.
In SwaggerConfig I have below chunks of code.

public Docket api() {

		ParameterBuilder parameterBuilder = new ParameterBuilder();
		parameterBuilder.name("Authorization").modelRef(new ModelRef("string")).parameterType("header").required(true).pattern("/api/auth/login")
				.build();
		List<Parameter> globalOperationParameters = new ArrayList<Parameter>();
		globalOperationParameters.add(parameterBuilder.build());

		return new Docket(DocumentationType.SWAGGER_2).apiInfo(DEFAULT_API_INFO)
				.globalOperationParameters(globalOperationParameters).produces(DEFAULT_PRODUCES_AND_CONSUMES)
				.useDefaultResponseMessages(false).consumes(DEFAULT_PRODUCES_AND_CONSUMES)
				.pathProvider(new IdaasPathProvider());

	}

So As you can see I am adding an "Authorization" param in globalOperationParameters.

So for all APIs it's coming on Swagger-UI.
But I strictly don't want it for a particular API.

For Example, I have a login API, and I don't need Authorization param for this API.

So is there a way to hide this parameter on login API, and rest everywhere I want to show it.

For your reference below is the loginAPI 

@RestController
@RequestMapping("/auth")
@Slf4j
public class LoginEndPoint {
	
	
	@Autowired
	private ILoginService loginService;
	
	
	@PostConstruct
	 private void init() {
		log.debug("Activated: {}", this.getClass().getName());
	 }
	
	
	
	@PostMapping("/login")
	public ResponseEntity<LoginResponse> login(@RequestBody Credentials creds, HttpServletRequest request) {
		
		log.debug("attempt to logon as: {} remote from ip: {} ",creds.getUsername(), request.getRemoteHost());
		
		LoginResponse response = loginService.login(creds);
		ResponseEntity<LoginResponse> authResponse= ResponseEntity.ok(response);
		
		return authResponse;
	}

}

**Comment by ShanePark** [comment]
`.ignoredParameterTypes` is what i was looking for. Thanks a lot
```java
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .ignoredParameterTypes(Context.class, Pageable.class)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.ant("/**/api/**"))
                .build();
    }

```
it worked for me
