### ISSUE TITLE
Possible incompatibility with Spring Boot

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [springfox/springfox#1140]
I've yet to test this with a clean version of Spring Boot but my guess is that this issue happens there also.

Spring Boot in `HttpMessageConverters` first adds the Spring Boot configured `MappingJackson2HttpMessageConverter` and then it adds the default `MappingJackson2HttpMessageConverter` from Spring MVC. 

This causes the `ObjectMapperConfigured` event to fire twice, first for the configured converter (which is actually used) and then for the default converter. So when you f.e. set a custom property naming strategy then in `ObjectMapperBeanPropertyNamingStrategy`this is overwritten by the second event.

I've added the following code to my project to fix this:

```java
@Configuration
public class MyWebAutoConfiguration extends WebMvcConfigurerAdapter {

    @Override
    public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
        ObjectMapper objectMapper = null;
        for (HttpMessageConverter converter : converters) {
            if (converter instanceof MappingJackson2HttpMessageConverter) {
                MappingJackson2HttpMessageConverter jacksonConverter =
                        ((MappingJackson2HttpMessageConverter) converter);

                if (objectMapper == null) {
                    objectMapper = jacksonConverter.getObjectMapper();
                } else {
                    jacksonConverter.setObjectMapper(objectMapper);
                }
            }
        }
    }
}
```

**Comment by dilipkrish** [comment]
This is a known issue I believe #1051, thank you for researching and providing a work around. I believe the issue of ObjectMapper selection needs to be fixed for sure.

**Comment by Jaap-van-Hengstum** [comment]
The issue with Spring Boot is that it registers two `MappingJackson2HttpMessageConverter` converters. My guess is that the second converter is never used because both converters act upon the same media types (application/json). If that is the case then the listeners for the `ObjectMapperConfigured` event should just use the first event to get the ObjectMapper and ignore the subsequent events.

**Comment by dilipkrish** [comment]
:bulb: moment! I think reversing the order will just fix it for _90%_ of the cases right?

**Comment by Jaap-van-Hengstum** [comment]
> :bulb: moment! I think reversing the order will just fix it for 90% of the cases right?

That would probably work in most cases.

**Comment by zhaoxi1988** [comment]
it also appears in spring boot 1.5

**Comment by kepha-korbit** [comment]
https://springfox.github.io/springfox/docs/snapshot/

I have installed springfox for spring-boot but generated json data(/v2/ap-docs) have errors .

- originalRef KEYWORD make error as following ::
Structural error at definitions.LneQuest.properties.quizList.items
should NOT have additional properties
additionalProperty: originalRef

/internal/v1/quest/list3:
    get:
      tags:
        - lne-quest-controller
      summary: getLneQuestList3
      operationId: getLneQuestList3UsingGET
      produces:
        - '*/*'
      parameters:
        - name: from
          in: query
          description: from
          required: false
          type: string
          format: date-time
        - name: offset
          in: query
          required: false
          type: integer
          format: int64
        - name: paged
          in: query
          required: false
          type: boolean
        - name: pageNumber
          in: query
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          required: false
          type: integer
          format: int32
        - name: sort.sorted
          in: query
          required: false
          type: boolean
        - name: sort.unsorted
          in: query
          required: false
          type: boolean
        - name: to
          in: query
          description: to
          required: false
          type: string
          format: date-time
        - name: type
          in: query
          description: type
          required: false
          type: string
        - name: unpaged
          in: query
          required: false
          type: boolean
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
            **originalRef**: Response
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

**Comment by dilipkrish** [comment]
Replied [here](https://github.com/springfox/springfox/issues/3376)
