### ISSUE TITLE
How does one go about customizing swagger-ui?

### ISSUE THREAD

**Issue by rajkishan-indpro** [springfox/springfox#1144]
I have no idea where to ask this type of question, so asking it here. Please note this is not an issue at all. 

My question is: if i am using swagger in my app, and i did some modifications to the main **swagger.html** file (like adding new css or replacing the header where the swagger name is with new picture or Application Name). What should i do? 
Do i need to add any copyright information at footer about swagger or something else or i am not allowed to modify those? Any help is appreciated. Thank You.:)

**Comment by dilipkrish** [comment]
@rajkishan-indpro swagger-ui is under [apache license](http://www.apache.org/licenses/LICENSE-2.0). and the swagger.html is for you to modify, re-package and re-use as you see fit. 

Not a legal expert but I think if you're selling a commerical offering based on this product, you would need to provide the necessary attribution notices.
