### ISSUE TITLE
Using parameterized types using Void resulting in invalid Swagger

### ISSUE THREAD

**Issue by nigelsim** [springfox/springfox#1147]
I have type Result<A, B> which is returned by many of my methods.

```
class Result<A,B> {
 A value;
 List<B> extra;
...
}
```

When Result<Void, Void> is returned the returned definition correctly removes the `value` property, but the `extra` property is specified as an array with no type.
```
ResultÂ«Void,VoidÂ»: {
    properties: {
        extra: {
            type: "array"
        }
    }
},
```
I tried adding an `alternateTypeRule` to map this to another class type that would have the correct signature, but this didn't result in the expected result. The type name changed in the `definitions` list, but not in the method signatures, and the properties of the original `Result` type were used, not the `SimpleResult` properties.
```
.alternateTypeRules(newRule(typeResolver.resolve(Result.class, Void.class, Void.class),
                        typeResolver.resolve(SimpleResult.class)))
```

**Comment by dilipkrish** [comment]
It appears to be a bug.. the rendering of list of voids, that is. The alternate type rule should just work, not sure what the problem is there.
