### ISSUE TITLE
How to change the tag's description

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#1148]
Hi,

My spec gets generated like this,

```
"tags": [
{
"name": "AcmeService",
"description": "External Acme Controller"
}
],
```

I have two controllers with the same base URL, with different operations in it.

AcmeController - /lcm/acmes
ExternalAcmeController - /lcm/acmes

**Comment by rajeshkamal** [comment]
Looks like I have to do it like this, but what is the alternative, it looks like deprecated.

```
@Api(tags = "VDIService", ~~description~~ = "VDI Controller")
```

**Comment by dilipkrish** [comment]
This is totally a work around. Like you pointed out the description is deprecated. There is already a story to fix this, preferably using the docket to set the tags up as opposed to using `@SwaggerDefinition`. Duplicate of #936.

**Comment by dilipkrish** [comment]
Closing this as its a duplicate
