### ISSUE TITLE
How to Display All Cases about Business Error?

### ISSUE THREAD

**Issue by wjc133** [springfox/springfox#1149]
our team define the response like this:
```
{
    code:123,
    message: "success",
    data:[
        {
            id:xxx,
            xxx:xxx,
            ...
        },
        ...
    ]
}
```
We use 'code' field to represent  various business error. So I want to display all cases in swagger-ui. Specially when the code is the correct one, I want it to show the structure of data. What should I do for this?

**Comment by dilipkrish** [comment]
> So I want to display all cases in swagger-ui. Specially when the code is the correct one, I want it to show the structure of data. 

Your question isn't entirely clear to me. Could you explain with an example perhaps?
