### ISSUE TITLE
Add Polymorphism Support

### ISSUE THREAD

**Issue by Fyro-Ing** [springfox/springfox#1151]
I've added "Polymorphism support" (discriminator on parent, and allOf on child(s)) with springfox

```
{
  "definitions": {
    "Pet": {
      "type": "object",
      "discriminator": "petType",
      "properties": {
        "name": {
          "type": "string"
        },
        "petType": {
          "type": "string"
        }/
      },
      "required": [
        "name",
        "petType"
      ]
    },
    "Cat": {
      "description": "A representation of a cat",
      "allOf": [
        {
          "$ref": "#/definitions/Pet"
        },
        {
          "type": "object",
          "properties": {
            "huntingSkill": {
              "type": "string",
              "description": "The measured skill for hunting",
              "default": "lazy",
              "enum": [
                "clueless",
                "lazy",
                "adventurous",
                "aggressive"
              ]
            }
          },
          "required": [
            "huntingSkill"
          ]
        }
      ]
    },
    "Dog": {
      "description": "A representation of a dog",
      "allOf": [
        {
          "$ref": "#/definitions/Pet"
        },
        {
          "type": "object",
          "properties": {
            "packSize": {
              "type": "integer",
              "format": "int32",
              "description": "the size of the pack the dog is from",
              "default": 0,
              "minimum": 0
            }
          },
          "required": [
            "packSize"
          ]
        }
      ]
    }
  }
}
```

On java models : 
Parent -> @ApiModel(discriminator="id")
Child -> @ApiModel(parent = Parent.class)

see https://github.com/Fyro-Ing/springfox/commit/43923f583dc85e009f11f623655624a903042abb

sorry for my english, not really good :/

**Comment by dilipkrish** [comment]
@Fyro-Ing thats awesome. Could you submit a PR?

**Comment by Fyro-Ing** [comment]
PR on #1152

**Comment by panih2o** [comment]
@dilipkrish Can this be prioritized? Based on the behavior I am seeing, I am missing attributes from my Abstract classes which are extended by the concrete Response classes. Will this solve it?

**Comment by fayndee** [comment]
@dilipkrish is this PR actually going to make into 2.5.0? I'm really looking forward for it. Thx.

**Comment by paulalex** [comment]
Will this make it into the 2.7.0 release, and will that release go out on January 1st?

**Comment by dilipkrish** [comment]
@paulalex The PR as such needs some re-work, and I have some vacation time planned. So I doubt it will make it without some help or pushing that date

**Comment by AhahaGe** [comment]
could i join to solve this problem, but i am new to gradle and springfox and springfox, could you help me start.

**Comment by raderio** [comment]
Any news about this issue?

**Comment by dilipkrish** [comment]
@AhahaGe absolutely! would love to get some help.

**Comment by ikhmurchik** [comment]
Hi @dilipkrish,
Could you share some details about release to this issue?

Thanks

**Comment by dilipkrish** [comment]
I plan to release it over the weekend

**Comment by subbu107** [comment]
Hi, 

I'm trying to use polymorphic support so that my swagger documentation can show a oneOf. I'm using version 2.9.0 from jcenter since it lists polymorphic support as a feature.

These are my models : 

@ApiModel(subTypes = {Dog.class, Cat.class}, discriminator = "type")
public class Animal {
  private String type;
....getters and setter...
}

@ApiModel(value = "Dog", parent = Animal.class)
public class Dog extends Animal{
}

Hoewever, I don't get a oneOf in the swagger ui ; instead I get a javascript error for max call stack exceeded.  

I do see it mentioned as a feature in 2.9.0, so I wanted to check if what I'm using are the right annotations to be used, or am I making a mistake ? 


thanks and regards.

**Comment by dilipkrish** [comment]
Are you using Animal as one of the inputs or the response models? @subbu107

**Comment by subbu107** [comment]
I am using something like this as my input model : 

@apimodel(value="Zoo")
public class Zoo {
    public Animal animal;
}

**Comment by dilipkrish** [comment]
@subbu107 responded to the issue you created!
