### ISSUE TITLE
@Api value attribute does not override auto-generated controller names

### ISSUE THREAD

**Issue by trifox** [springfox/springfox#1153]
@Api("MyApiName")
class AdminUserController extends BaseRepositoryController<User> {

results in 
{
name: "admin-user-controller"
}

auto generated api name, expected behaviour would be "MyApiName"

**Comment by dilipkrish** [comment]
@trifox Currently this feature is in a little bit of a flux as I'd like to rework some of the stuff. Quite a few of the underpinnings are deprecated. So I've pushed it to 2.5

**Comment by dilipkrish** [comment]
This should be fixed via #936
