### ISSUE TITLE
api-docs response wrapped in additional JSON: {"value" = "..."}

### ISSUE THREAD

**Issue by timbuethe** [springfox/springfox#1156]
I added swagger to my Spring Boot application by including the dependency:

```
<dependency>
  <groupId>io.springfox</groupId>
  <artifactId>springfox-swagger2</artifactId>
  <version>2.3.1</version>
</dependency>
```

and adding a config class:

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket api(){
        return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(Predicates.or(PathSelectors.regex("...")))
            .build()
            .apiInfo(apiInfo());
    }

    private ApiInfo apiInfo() {
        return new ApiInfo(...);
    }
}
```

I can now access `/v2/api-docs` and get some JSON that seems to describe my API. However, the JSON is wrapped in another JSON object like this (abbreviated):
```
{"value":"{\"swagger\":\"2.0\",\"info\":...}
```

The `{"value": "..."}` Object isn't needed and causes errors in swagger-ui. The PetStore example doesn't has this extra level. This this a bug? Or a config issue?

PS: I also created this stackoverflow question: http://stackoverflow.com/questions/35034405/

**Comment by dilipkrish** [comment]
By any chance are you using a different json serializer than jackson? It sounds [similar to this issue](http://stackoverflow.com/questions/30219946/springfoxswagger2-does-not-work-with-gsonhttpmessageconverterconfig/30220562#30220562). If you are using GSON there [is a work around](http://springfox.github.io/springfox/docs/snapshot/#q3) you might try.

**Comment by timbuethe** [comment]
Yeah, you are absolutely right. I'm using gson and I understand the problem now. Thanks a lot!
