### ISSUE TITLE
Ignore hypermedia "links" in model

### ISSUE THREAD

**Issue by trossignol** [springfox/springfox#1157]
Hi all,
I'm working on API implementing HAL with Spring Hateoas. Everything's right but my Swagger model are polluted by "links" tag.

`{
  "criteria": [
    {
      "field": "string",
      "links": [
        null
      ],
      "operator": [
        "string"
      ],
      "type": "STRING"
    }
  ],
  "links": [
    null
  ]
}`

I tried 2 things :

- ignore org.springframework.hateoas.Link.class (this is why my links are null)
- override org.springframework.hateoas.ResourceSupport.getLinks(...) method to put @JsonIgnoreProperties or @JsonProperty(acces=READ_ONLY)

But it doesn't work.
Is it possible to configure springfox for ignoring field by name ?

Thanks for your help,
Thomas

**Comment by dilipkrish** [comment]
@trossignol Not sure why you'd want to ignore links. Its should be part of the documentation I'd think. I don't think that `Resource<Model>` is technically equivalent to `Model`. Could you explain your issue more concretely perhaps? in terms of request mappings...

**Comment by trossignol** [comment]
In my example, I have a GET method wich return a list of criteria. The list has hypermedia links (self, search) and each criterion has links (search with this criterion).

The model presented by Swagger could be more readable without "link" tags :
![image](https://cloud.githubusercontent.com/assets/10358421/12650053/9cdadfce-c5e1-11e5-8c53-dccd6d222384.png)

Of course, it's interesting to know that there are "links" but it's defined by the HAL standard.

**Comment by dilipkrish** [comment]
Pardon me if I'm mistaken but It seems like this may be a incorrect usage of spring hateoas. 

If you don't care about those links they should either be modeled as a `List<Criteria>` rather than an `Resource<List<Critieria>>`. What am I missing here?

**Comment by haufe-umantis-ag** [comment]
Hi, I have the same problem trying to hide _links from the springfox. Did you finally found a solution?

**Comment by dilipkrish** [comment]
@haufe-umantis-ag Hiding _links from requests or response?

**Comment by haufe-umantis-ag** [comment]
@dilipkrish From both would be great, but at least from the request

**Comment by dilipkrish** [comment]
@haufe-umantis-ag on the request side you shouldn't be passing in a resource at all. It should just be a domain object. 

On the response side if you don't want it to be a resource with links just use the domain object there as well. I feel you're usage of spring-hateoas is not correct.

**Comment by haufe-umantis-ag** [comment]
@dilipkrish Yes, absolutly agree, as a matter of fact this is my purpose but I can't avoid that Swagger takes the _links part and adds them into the payload of the request

**Comment by haufe-umantis-ag** [comment]
@dilipkrish same that here
http://i.stack.imgur.com/t1mwj.png

**Comment by dilipkrish** [comment]
@haufe-umantis-ag Im not talking about the swagger Im talking about your request mapping. Why does it have a resource in the request? and why does your service return a resource when you don't care about the links

**Comment by haufe-umantis-ag** [comment]
@dilipkrish The resource you are asking me about is the DTO itself, that is defined once in the application and used as payload for a creation endpoint (POST), and as response in a GET endpoint. I think it's a very common HAL response:

{
  "period": 103,
  "title": "Title",
  "creator": "76",
  "description": "How can we manage Hypermedia with Swagger?",
  "recipient": 81,
  "category": "1020001",
  "id": 2454,
  "type": 2,
  "_links": {
    "self": {
      "href": "http://www.server.com/service-api-mm/rest/goals/2454"
    },
    "update": {
      "href": "http://www.server.com/service-api-mm/rest/goals/2454"
    },
    "delete": {
      "href": "http://www.server.com/service-api-mm/rest/goals/2454"
    }
  }
}

So that would be the response of the POST endpoint, and the request payload would be something like this:

{
  "period": 103,
  "title": "Title",
  "creator": "76",
  "description": "How can we manage Hypermedia with Swagger?",
  "recipient": 81,
  "category": "1020001",
  "type": 2,
}


So, the problem, is that using swagger (after code through springfox), he show the _links section as a part of the payload that the client has to use to create the resource.

My wish is to configure swagger so he can ignore the _links section.

**Comment by dilipkrish** [comment]
The `DTO` is different from a resource. My question is why use a `Resource<DTO>` if you don't care about the links?

**Comment by haufe-umantis-ag** [comment]
I do care about links, I just want them to be ignored from swagger... :(

**Comment by dilipkrish** [comment]
In that case Just create an alternate type rule for Resource. Add Resource to the list of `genericModelSubsitutes` in your docket

**Comment by nuth** [comment]
Hi, I'd like to add that in Spring, you have a ResourceSupport class, that adds these links, so like said previously, the links are part of the DTO so it's not an option to remove the links from the request, short of making a complete new DTO for the request.

**Comment by hennejg** [comment]
> In that case Just create an alternate type rule for Resource. Add Resource to the list of genericModelSubsitutes in your docket

Could you please elaborate on that? I, too, am trying to get rid of the `_links` properties. Unsuccessfully so far. Most of my DTOs derive from the `ResourceSupport` class @nuth mentioned above.

A couple of approaches I tried are:

* Using an `AlternateTypeRuleConvention`
```@Component
public class HideHATEOASLinksFromSwagger implements AlternateTypeRuleConvention  {
  @Override
  public int getOrder() {
    return HIGHEST_PRECEDENCE;
  }

  @Override
  public List<AlternateTypeRule> rules() {
    return Arrays.asList(AlternateTypeRules.newRule(ResourceSupport.class, Object.class), AlternateTypeRules.newRule(Link.class, Object.class));
  }
}
```

* the same idea, but configured on the `Docket`: 
```
return new Docket(DocumentationType.SWAGGER_2)
        .alternateTypeRules(AlternateTypeRules.newRule(ResourceSupport.class, Object.class))
```

* modifying the properties using a `ModelPropertyBuilderPlugin` - the plugin is triggered correctly and the property set to be hidden, but later, on the other side of a small mountain of code, it comes out non-hidden.

```@Component
public class HideHATEOASLinksFromSwagger implements ModelPropertyBuilderPlugin {

  @Override
  public boolean supports(final DocumentationType delimiter) {
    return SwaggerPluginSupport.pluginDoesApply(delimiter);
  }

  @Override
  public void apply(final ModelPropertyContext context) {
    if (context.getBeanPropertyDefinition().isPresent()) {
      BeanPropertyDefinition b = context.getBeanPropertyDefinition().get();
      if (b.getField() != null && ResourceSupport.class.equals(b.getField().getDeclaringClass()) && b.getField().getName().contains("links")) {
        context.getBuilder().isHidden(true);
      }
    }
  }

}
```

**Comment by hennejg** [comment]
To answer my own comment from yesterday...

The approach using a `ModelPropertyBuilderPlugin` was correct, but incomplete. Here's the working solution:
```
@Component
public class HideHATEOASLinks implements ModelPropertyBuilderPlugin {

  @Override
  public boolean supports(final DocumentationType delimiter) {
    return true;
  }

  @Override
  public void apply(final ModelPropertyContext context) {
    if (context.getBeanPropertyDefinition().isPresent()) {
      BeanPropertyDefinition b = context.getBeanPropertyDefinition().get();
      AnnotatedField annotatedField = b.getField();
      if (null != annotatedField) {
        Field field = (Field) annotatedField.getMember();
        if (field != null)
          hideLinksField(context, field);
      }
    } else if (context.getAnnotatedElement().isPresent() && context.getAnnotatedElement().get() instanceof Field) {
      Field f = (Field) context.getAnnotatedElement().get();
      hideLinksField(context, f);
    }
  }

  private void hideLinksField(final ModelPropertyContext context, final Field field) {
    if (ResourceSupport.class.equals(field.getDeclaringClass()) && field.getName().contains("links")) {
      context.getBuilder().isHidden(true);
    }
  }

}
```
It didn't work right away because the property is mapped twice: once as a getter/setter and once as a raw field. This, in turn, is caused by `POJOPropertyBuilder.getPrimaryMember()` behaves differently for serialization and deserialization. The two different modes are activated based on whether `springfox.documentation.schema.property.OptimizedModelPropertiesProvider.beanDescription(ResolvedType, ModelContext)` works for a return type context or not.

**Comment by dilipkrish** [comment]
Thanks for the solution and explanation @hennejg

**Comment by JayHelaiya** [comment]
u can customize Resource class and then u can inject model into your customized resource
it work fine with Hateoas URL with resource Object 
not need to extend ResourceSupport toModel
______________________________________________________________
public class HttpUserResource<T> extends Resource<T> {
	
    public HttpUserResource(T content, Link... links) {
      
    	super(content, links);
    }
}
________________________________________________

@PostMapping("/users2")
	public ResponseEntity<HttpUserResource<User2>> saveUser2(@RequestBody User2 user2,UriComponentsBuilder ucBuilder) {
	        
			HttpUserResource<User2> savedResource = new HttpUserResource<>(user2);
	        
	        ControllerLinkBuilder linkTo = linkTo(methodOn(this.getClass()).getUser(user2.getUserId(),null));
			savedResource.add(linkTo.withRel("user"));
	        
	    	HttpHeaders headers = new HttpHeaders();
	        headers.setLocation(linkTo.toUri());
	        
	       return new ResponseEntity<>(savedResource,headers, HttpStatus.CREATED);
	        
	}
