### ISSUE TITLE
The class springfox ... Json requires a zero argument constructor - JAXBException

### ISSUE THREAD

**Issue by NikosDim** [springfox/springfox#1158]
Hi 

I am trying to integrate springfox with our current Spring REST API but I am getting the exception below:

```
...
Caused by: Exception [EclipseLink-50001] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.JAXBException
Exception Description: The class springfox.documentation.spring.web.json.Json requires a zero argument constructor or a specified factory method.  Note that non-static inner classes do not have zero argument constructors and are not supported.
	at org.eclipse.persistence.exceptions.JAXBException.factoryMethodOrConstructorRequired(JAXBException.java:148)
	at org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor.finalizeProperties(AnnotationsProcessor.java:966)
	at org.eclipse.persistence.jaxb.compiler.XMLProcessor.processXML(XMLProcessor.java:468)
	at org.eclipse.persistence.jaxb.compiler.Generator.<init>(Generator.java:154)
	at org.eclipse.persistence.jaxb.JAXBContext$TypeMappingInfoInput.createContextState(JAXBContext.java:1099)
	... 119 more
```

I am using springfox-swagger2-2.3.1.jar and the configuration that I am having is:

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket documentation() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(regex("/v2/.*"))
                .build()
                .pathMapping("/")
                .apiInfo(metadata());
    }

    @Bean
    public UiConfiguration uiConfig() {
        return UiConfiguration.DEFAULT;
    }

    private ApiInfo metadata() {
        return new ApiInfoBuilder()
                .title("My awesome API")
                .description("Some description")
                .version("1.0")
                .contact("my-email@domain.org")
                .build();
    }
}
```

The package of the `SwaggerConfig` class is included in the `<context:component-scan base-package="..."/?>`

My web services are able to return both JSON and XML. Below is an example of my web services

```
@RequestMapping(value = "/{code}", method = RequestMethod.GET)
@CacheControl(directive = CacheControlDirective.PUBLIC, maxAge = 300)
public ProductSearchDTO getProductByCode(@PathVariable final String code,
                                             final HttpServletResponse response) {
    ...
}
```

Any ideas?

Thanks 

Nick

**Comment by dilipkrish** [comment]
Seems like you're trying to load a son bean with a jaxb message processor. Try with an accept header of `application/json` and see what happens

**Comment by NikosDim** [comment]
Hi @dilipkrish 

I added the accept header you specified but same error

Thanks

**Comment by pufik** [comment]
Hi @dilipkrish I'm facinf the same issue. Problem is that springfox.documentation.spring.web.json.Json
is immutable and doesn't have default constructor. Such class is not fine for JAXB. I'm using EclipseLink for XML/JSON serialization/marshaling. Could you please advise?

**Comment by dilipkrish** [comment]
@pufik are you trying to marshal `Json` the object to xml?

**Comment by pufik** [comment]
@dilipkrish I'm trying to serialize Json(and another classes has the same issue, namely springfox.documentation.swagger.web.UiConfiguration, springfox.documentation.swagger.web.SecurityConfiguration etc). I'm using EclipseLink as JAXB implementation. The problem is that you have strict dependency to Jackson(annotations for fields, classes are not supporting POJO/Bean convention etc). Could you advise how I can fix/workaround that?
Thanks in advance!

**Comment by dilipkrish** [comment]
Those types aren't meant to be exposed as xml. There is nothing that would read those types as xml. Not sure what the right fix is
