### ISSUE TITLE
Update documentation for JSR310 and Joda dates

### ISSUE THREAD

**Issue by cbornet** [springfox/springfox#1161]
See #1021 #536 #893 
There is a way to correctly map the "Date" and "DateTime" types to their corresponding swagger types:
* Substitute "Date" types (java.util.LocalDate, org.joda.time.LocalDate)  by java.sql.Date
* Substitute "DateTime" types (java.util.ZonedDateTime, org.joda.time.LocalDateTime, ...) by java.util.Date
```java
docket
.directModelSubstitute(LocalDate.class, java.sql.Date.class)
.directModelSubstitute(LocalDateTime.class, java.util.Date.class)
```

The current doc suggests to subtitute by String but this loses the information on the format.

**Comment by dilipkrish** [comment]
PR? all the docs [are here](https://github.com/springfox/springfox/tree/master/asciidoc)
