### ISSUE TITLE
SpringFox Model and model schema configuration is not working

### ISSUE THREAD

**Issue by dinee432** [springfox/springfox#1166]
Hi,

 I am creating documentation for my web services using swagger. My project is not having any domain class. The architecture directly works on the payload to pull the required values using JsonPath. In this case how will I specify the model and model schema for the payload.

Thanks,
Dinesh

**Comment by dilipkrish** [comment]
Since your services don't seem to enforce any contract on the json payloads/domain representations coming in, I don't see much value in generating swagger-specifications other than documenting all the endpoints. I would really question the need for using swagger.

**Comment by dinee432** [comment]
I have a predefined perfect payload structure which the client needs to send to call the service. So I need to document the payload structure to let the client know what they need to send. If I have a model schema, I cna specify my Json Schema and in the model I can add Json Payload.

**Comment by dilipkrish** [comment]
In your case, I would strongly recommend [spring-restdocs](http://projects.spring.io/spring-restdocs/) instead.

**Comment by dinee432** [comment]
Thank you. I will go through the specified documentation
