### ISSUE TITLE
@API is broken in 2.3.1

### ISSUE THREAD

**Issue by ravi-chaurasia** [springfox/springfox#1167]
For the below code 
@Controller
@RequestMapping("/api/people")
@Api(value = "Person")
public class PersonController {}

In version 2.1.1 
The Api name in UI is 

**person : Person**

but  in version 2.3.1  it is
**person-controller : Person-Controller**

Please let me know if this functionality has been changed or moved to some other annotation.

I need to use it  as after updating from 2.1.1 to 2.3.1 all my api's names are looking ugly.

**Comment by dilipkrish** [comment]
@ravi-chaurasia Yes. That functionality has changed. We deprecated the internals that use the `@Api#value()` for the name of the controller. 

This is probably going to be revisited. So I'll make that a feature request since some folks are interested in reviving the naming.

**Comment by ravi-chaurasia** [comment]
Great Thanks!!

**Comment by dilipkrish** [comment]
This is fixed via #936. Moving forward we should be able to change this using a combination of specifying `Docket#tags` and `@Api#tags`
