### ISSUE TITLE
Changelog not being updated

### ISSUE THREAD

**Issue by jayanderson** [springfox/springfox#1168]
https://github.com/springfox/springfox/blob/master/docs/CHANGELOG.md - this file hasn't been updated since 2015 April. I was looking for changes in the 2.3.x release and couldn't easily find what the difference is.

**Comment by dilipkrish** [comment]
Yeah, its moved to [release-notes](https://github.com/springfox/springfox/blob/master/docs/release-notes.md). Need to consolidate the docs in general. Sorry for the confusion.

**Comment by jayanderson** [comment]
Cool thanks. I originally found CHANGELOG.md from the top-level readme. Fixing that should probably do it.
