### ISSUE TITLE
swagger-springmvc update from 0.8.8 to 1.0.2 changes API response

### ISSUE THREAD

**Issue by TigranTsat** [springfox/springfox#1170]
Hello,

I am doing update for swagger from 0.8.8 to 1.0.2, but facing with issue that response parameter for name changed.
Was:
`"name":"user"`
Now (1.0.2):
`"name":"body"`

Declaration in Spring:
`public ResponseEntity<SuccessResult> updateUser(@RequestBody @Valid UserReqRes user`)

I believe that original one is right one, since that's reflects the real name of parameter.
We are using code-gen so signature is very important for us.

Thanks.

**Comment by dilipkrish** [comment]
Unfortunately thats how the spec reads. It was a bug that it was getting the name as `user`. In any case. Rather than moving to `1.0.2`, please consider moving to `2.3.1`. Swagger 1.2 will not be supported for much longer

**Comment by TigranTsat** [comment]
New version of swagger will output it as `"name":"body"`, correct?
I do not see "2.3.1" version of swagger-springmvc. "1.0.2" is latest. What am I missing?
http://mvnrepository.com/artifact/com.mangofactory/swagger-springmvc

**Comment by dilipkrish** [comment]
You're missing the [latest documentation](http://springfox.github.io/springfox/) :) 

Yeah we renamed the repository and package names as we transitioned from mangofactory to a github organization around ***SpringFox***. Details also available in the [Readme](https://github.com/springfox/springfox/blob/master/README.md) for this project :point_up:

**Comment by TigranTsat** [comment]
OK. Thanks :)
