### ISSUE TITLE
How to configure swagger-ui.html prefix url to access

### ISSUE THREAD

**Issue by raDiesle** [springfox/springfox#1171]
I tried to rewrite the place where browser can view the swagger-ui.html with Spring Boot and JavaConfig.

It is needed because our loadbalancer is configured on special prefix in url,
but I did not suceed to rewrite or configure it.
The webjars docu did not help me to understand

Any idea?

**Comment by dilipkrish** [comment]
Have a look at [this answer](https://github.com/springfox/springfox/issues/1080#issuecomment-169185653). Closing this as a duplicate. Feel free to reopen if that doesn't solve your question
