### ISSUE TITLE
Example Object support

### ISSUE THREAD

**Issue by tjuchniewicz** [springfox/springfox#1173]
Swagger specification define Example Object: http://swagger.io/specification/#exampleObject.
Does SpringFox support this feature?

**Comment by dilipkrish** [comment]
@tjuchniewicz Not currently supported but there is already an issue opened for this -> #853. Closing this in favor of the original issue. This isn't high on the priority list, but  PR's would be awesome!

**Comment by tjuchniewicz** [comment]
@dilipkrish Thanks for quick response.

What do you mean by PR?

**Comment by tjuchniewicz** [comment]
PR = [Pull Request](https://help.github.com/articles/using-pull-requests)

**Comment by dilipkrish** [comment]
yes. Thought I'd responded to your question... sorry!

**Comment by tjuchniewicz** [comment]
No problem. I will discuss possibility of PR with my team. Thanks!
