### ISSUE TITLE
Doc: includePatterns does not exist (anymore?)

### ISSUE THREAD

**Issue by vorburger** [springfox/springfox#1174]
Both  http://springfox.github.io/springfox/docs/current/#docket-spring-java-configuration and http://springfox.github.io/springfox/docs/snapshot/#docket-spring-java-configuration mention `.includePatterns(".*pet.*")`, but there is no `includePatterns` method available (anymore?) on [Docket](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java) - perhaps the doc could clarify where it went?

**Comment by dilipkrish** [comment]
@vorburger thanks for catching that. The documentation needs to be fixed. The [source of truth](https://github.com/springfox/springfox/blob/master/springfox-spring-config/src/main/java/springfox/springconfig/Swagger2SpringBoot.java) (tested code) is however [in the section above](http://springfox.github.io/springfox/docs/snapshot/#springfox-swagger2-with-spring-mvc-and-spring-boot).

In any case, there is a selector api that is predicate based, see 4, 5 & 6. You can select by paths using the path selector, in addition you can also select based on the `RequestHandler`
