### ISSUE TITLE
Custom swagger-ui

### ISSUE THREAD

**Issue by GlennVanSchil** [springfox/springfox#1176]
Is there any method to change the swagger-ui skin with templates or maybe by tweaking the css yourself? Now I'm using [Apiary](https://apiary.io/) which look beautiful but it's still in beta and doesn't show everything as well as swagger-ui does, but I don't really like the look of swagger-ui's default template.

**Comment by dilipkrish** [comment]
You can pull down [the source](https://github.com/swagger-api/swagger-ui) and make whatever modifications you need to make.

**Comment by GlennVanSchil** [comment]
Thank you for the answer! I have one other question though. How can I create a (web)jar from this? i did npm install and nmp run build, but i don't see any jar appearing.

**Comment by dilipkrish** [comment]
you don't need to create a web jar. just copy it into your resources and have your app handle it using resource handlers. See [here](http://springfox.github.io/springfox/docs/snapshot/#q13)

**Comment by GlennVanSchil** [comment]
Thanks a lot!

**Comment by GlennVanSchil** [comment]
The way i did it:
add the dist folder to my resources folder
![screenshot_2](https://cloud.githubusercontent.com/assets/3930037/13170520/df73e42c-d6ec-11e5-8f10-5fd784ed0edd.png)

and replaced
```java
@Override
    public void addResourceHandlers(final ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
```
With this
```java
@Override
    public void addResourceHandlers(final ResourceHandlerRegistry registry) {
        registry.addResourceHandler("**").addResourceLocations("classpath:/dist/");

        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
```

**Comment by vdumpala** [comment]
it all works but forget to add following change springfox.js 

 "baseUrl": function() {
            var urlMatches = /(.*)\/index.html.*/.exec(window.location.href);
            return urlMatches[1];
        }

**Comment by sebasira** [comment]
@GlennVanSchil and @vdumpala could you elaborate more on how to do this? I'm using spring boot with gradle.

I need the whole repo or just the swagger-ui folder?

**Comment by GlennVanSchil** [comment]
@sebasira The dist folder is the only thing you'll need. This is my configuration

```
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger.web.UiConfiguration;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import javax.xml.datatype.XMLGregorianCalendar;

import static springfox.documentation.builders.PathSelectors.regex;

@EnableSwagger2
@EnableWebMvc
public class ApiDocumentationConfiguration extends WebMvcConfigurerAdapter {

    /**
     * Configuration for Swagger
     *
     * @return
     * @see <a https://springfox.github.io/springfox/">Springfox</a>
     */
    @Bean
    public Docket documentation() {
        return new Docket(DocumentationType.SWAGGER_2)
                .directModelSubstitute(XMLGregorianCalendar.class, String.class)
                .select()
                .apis(RequestHandlerSelectors.withMethodAnnotation(RequestMapping.class))
                .apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))
                .paths(regex("/.*"))
                .build()
                .pathMapping("/")
                .apiInfo(metadata());
    }

    @Bean
    public UiConfiguration uiConfig() {
        return UiConfiguration.DEFAULT;
    }

    /**
     * Adds metadata to Swagger
     *
     * @return
     */
    private ApiInfo metadata() {
        return new ApiInfoBuilder()
                .title("Enquire Ask API")
                .description("Enquire Ask is platform that provides powerful, accurate and highly configurable natural language parsers that can interpret phrases, sentences and questions.<br><br>" +
                        "You can create projects that understand phrases with words, dates, times, locations… that matter to you.  The interpretation of a phrase is a user-defined collection of key-value pairs.<br><br>" +
                        "Enquire Ask provides projects in English and Dutch.")
                .version("1.0")
                .contact("Enquire")
                .license("Enquire End User Licence Agreement")
                .licenseUrl("http://enquire.ai/license")
                .build();
    }


    /**
     * Generates the SwaggerUI which can be found at
     * https://api.smartspoken.com/swagger.html
     * custom design is located in /resources/dist/**
     * in case you need to apply changes see
     * https://bitbucket.org/smartspoken/smartsearch-ui
     *
     * @param registry
     */
    @Override
    public void addResourceHandlers(final ResourceHandlerRegistry registry) {
        registry.addResourceHandler("**").addResourceLocations("classpath:/dist/");

        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
    }

}
```

And added this to my existing XML config
```
<bean id="swagger2Config" class="springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration"/>
<bean id="ApiDocumentationConfiguration" class="be.smartask.api.config.ApiDocumentationConfiguration"/>
```
Since you're using Spring Boot you should be able to add the Java config as I did, but I think you'll need a second Java config and convert my 2 lines of XML config to Java config as well.

Good luck

**Comment by sebasira** [comment]
@GlennVanSchil Thanks for your reply

Unfortunately I'm unable to follow your lead... First of all I couldn't even find a **dist** folder to copy

**Comment by dilipkrish** [comment]
@sebasira I think you're looking for [this dist folder](https://github.com/swagger-api/swagger-ui/tree/master/dist)

**Comment by GlennVanSchil** [comment]
@sebasira  @dilipkrish That's Indeed the dist folder i've used but they changed the structure since [this commit](https://github.com/swagger-api/swagger-ui/commit/f22a6289345a3025650c687ab482a9e1a6369b07#diff-2a6d07eef8b10b84129b42424ed99327), The one I used was (similar to) [this commit](https://github.com/swagger-api/swagger-ui/commit/38f74164a7062edb5dc80ef2fdddda24f3f6eb85#diff-2a6d07eef8b10b84129b42424ed99327). If you use the one I used make sure to update the following stuff inside the index.html

Swagger adds the api-key by default as a query parameter, But this can be different for your application. If you have a Header param like I do change the following method 

from
```
function addApiKeyAuthorization(){
  var key = encodeURIComponent($('#input_apiKey')[0].value);
  if(key && key.trim() != "") {
      var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", key, "query");
      window.swaggerUi.api.clientAuthorizations.add("api_key", apiKeyAuth);
      log("added key " + key);
  }
}
```

to
```
function addApiKeyAuthorization() {
    var key = encodeURIComponent($('#input_apiKey')[0].value);
    if (key && key.trim() != "") {
        // make sure to replace MY_HEADER_FOR_KEY with the actual param name
        swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("MY_HEADER_FOR_KEY", key, "header")); 
    }
}
```

Swagger uses a hard coded URL for your swagger which can be annoying when using different environment for example http://localhost:8080 and https://my-production-uri.com because you always need to change it manually at the top of the Swagger UI. To make this dynamic replace the following code

from
```
var url = window.location.search.match(/url=([^&]+)/);
if (url && url.length > 1) {
  url = decodeURIComponent(url[1]);
} else {
  url = "MY_DEFAULT_URL/v2/api-docs";
}
```

to
```
var url = window.location.search.match(/url=([^&]+)/);
if (url && url.length > 1) {
    url = decodeURIComponent(url[1]);
} else {
    // Make sure to replace MY_PATH with the root path of your location
    url = window.location.origin + "/MY_PATH/v2/api-docs";
}
```

Hope this helps

**Comment by sebasira** [comment]
Thank you @GlennVanSchil and excuse me for my late reply! I'll see what I can do with it

**Comment by bhavyakv** [comment]
Hi, I'm trying to do something similar in my Springboot app. Basically I need to zip all the HTML and JS files to give it to a client, and I plan on embedding the swagger-json within this bundle and have the Swagger UI reference this Json file.
To do this, I have downloaded the Swagger UI code and copied it into my project under resources/static directory. I've also added the resource handlers as mentioned above. However, when I open the Swagger UI at localhost:8080/index.html the page still loads the default "swagger petstore" documentation and not my application's. How do I fix this?

**Comment by bhavyakv** [comment]
I'm using the Swagger UI files linked above, and having it load a JSON which was generated by my Springboot application using springfox-swagger. Now I see that all the parameters that I had annotated with @ApiIgnore are showing up on the Swagger UI. This had worked earller when I tested with the swagger-ui.html within the Springboot app. Are the Swagger UI and the JSON incompatible?

**Comment by GlennVanSchil** [comment]
@bhavyakv I think it's better to open a new question/issue for this :smile:
