### ISSUE TITLE
Change the parameters in body request of a method in Swagger

### ISSUE THREAD

**Issue by mohaFazel** [springfox/springfox#1178]
I've been working on a project and try to document it using Swagger-2.0. In this project due to some security issues, every method in controllers that has an object as a return type should change the return object to a completely flat object. In order to do this, we use some custom annotations above each method and the controller itself transform the object to the return type. By which I mean, the Object which is return by the method is not the same Object that pass to the browser. And also we have a same thing for the input parameters of methods in controller. It means that users have to send an Object for the methods which is different with the input parameter of the method. There is a sample method as an example below.

@RequestView(InputParamView.class)
@ResponseView(ReturnObjectView.class)
@RequestMapping(value = "/someMethod", method = RequestMethod.POST)
public ReturnObject someMethod(@RequestBody InputParam inputParam) {
      //do some thing
}

The problem is how to configure the Swagger to recognize InputParamView and ReturnObjectView as the input parameter and return type of this method. We do this for the return type of the method by using the ApiOperation annotation above each method just like below.

@ApiOperation(value = "/someMethod", response = ReturnObjectView.class)

Unfortunately, I have found any way to do the same thing for the input parameters yet. I will be wondering if someone help me with this issue with a proper example.
This question is asked in the StackOverflow [here](http://stackoverflow.com/questions/35426268/change-the-parameters-in-body-request-of-a-method-in-swagger)

**Comment by dilipkrish** [comment]
If you're objects usually have a one to one mapping for example, `InputParam` => `InputParamView` and `ReturnObject` => `ReturnObjectView` then its very simple to solve this problem. All you need to do is to set up alternate type rules in your docket.

```java
    docket
         .directModelSubstitute(InputParam.class, InputParamView.class)
         .directModelSubstitute(ReturnObject.class, ReturnObjectView.class)
```

Now if you have a one to many mapping like `InputParam => [Method1InputParamView, Method2InputParamView]` then its a little bit more involved and it ties into supporting `@JsonView` #601 .

**Comment by mohaFazel** [comment]
Dear dilipkrish, 
Thank you for your response in advance. The matter is there is not just a few classes to map in our project. I think what you said as a response needs to write any of those mappings in our Docket configuration. We have more than hundreds of these mappings in any of our subsystems. Fortunately all of them follow a same pattern. Is there any way to solve this issue without mentioning thousands of mappings in our configuration just using a simple pattern (like concatenating 'View' at the end of the Class name).

**Comment by mohaFazel** [comment]
I have been testing your solution for a while. but it doesn't replacing `InputParam.class` with `InputParamView.class` , the substitute command just merge both class and show the merged class as a response or input parameter in swagger-ui.html instead.
However, when I return to the former method e.g. placing the return class `InputParamView.class` in the response of ApiOperation annotation it works well.

**Comment by bqcuong** [comment]
Is there a solution for dealing with many mappings between single entity and DTOs?
I'm using the latest version (2.9.2)

**Comment by dilipkrish** [comment]
@bqcuong You could create your own alternate type rule convention as [shown here](http://springfox.github.io/springfox/docs/current/#additional-extensibility-options)
