### ISSUE TITLE
Nested structures are not properly resolved

### ISSUE THREAD

**Issue by v9802063** [springfox/springfox#1181]
Hello, I'm new to Springfox (and Swagger), and I faced the following problem. I have controller method:
```
@ResponseBody
public Map<Long, List<Map<String, String>>> find(@RequestBody final SearchRequest searchRequest) {
...
}
```
Springfox produces following definition for the response:
`"responses":{"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"$ref":"#/definitions/List"}}},"201"...`
And there is no List in definitions section, so this swagger json is not valid.
What should I do to fix this problem? I want to have valid swagger and the response looking like
`{0: [{"string":"string"}]}`

**Comment by varghgeorge** [comment]
In my case, I am only getting following

definitions: {
Response: {
type: "object"
},

eventhough Response object contains multiple fields and i tried documenting all gets using @ApiModelProperty.

I am using 2.4.0 release.

**Comment by dilipkrish** [comment]
@v9802063/ @varghgeorge what versions are you using. This should've be fixed in 2.4.0

**Comment by varghgeorge** [comment]
@dilipkrish I am using 2.4.0. This used to work, not sure what changed.

**Comment by varghgeorge** [comment]
@RequestMapping(produces = { MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE }, 
					consumes = MediaType.APPLICATION_JSON_VALUE,
					method = {RequestMethod.POST })
	@ApiOperation(value = "testMethod.", 
				  notes = "Returns the result - String.")
	@ApiResponses(value = { 
            @ApiResponse(code = 200, message = "Success", response = Test.class),
            @ApiResponse(code = 401, message = "Unauthorized")}) 
	public @ResponseBody Test saveTest(@RequestBody Test testinput) {

**Comment by varghgeorge** [comment]
I think I narrowed down the issue. The model object is not part of /v2/api-docs if I @ImportResource("classpath:spring-security.xml"). And this this case, ONLY model objects are missing, everything else is displayed correctly. 

Everything works fine if I don't load the spring-security xml file.

Any ideas?

**Comment by varghgeorge** [comment]
I think the original issue mentioned in this was different so I am moving the issue I reported to a different thread. 

https://github.com/springfox/springfox/issues/1225

**Comment by timazet** [comment]
Hello, I also faced with this original problem like a user **v9802063**. I am using **2.4.0** version of Springfox and I want to have valid swagger with all specified definitions for method which is mentioned in the original message. 
What should I do to fix this?
