### ISSUE TITLE
login to authenticate from a third party server before trying methods

### ISSUE THREAD

**Issue by mohaFazel** [springfox/springfox#1187]
I have been working on a Spring MVC project and try to document it using swagger2. Although every thing goes well, when I want to try methods using 'Try it out' button, I encounter an authentication problem. We are using a third party project in a different Url in order to generate token which is needed in header to run methods. I have searched and come up with different solutions which are changing the swagger-ui.html but I wanna know if there is another solution such as using the SecurityScheme in configuring the Docket in server side. We are using basic authentication but when I try to use BasicAuth in Springfox.Documentation.Service it doesn't make any change. In our project users should login using their username and password and ask for token from the third party project which is accessible from different url. Then, they can simply put it in the header and run every methods in the project they want.

**Comment by dilipkrish** [comment]
@mohaFazel The support for this is kinda sketchy in swagger-ui. You might get better answers on how to do this in the [swagger-ui project](https://github.com/swagger-api/swagger-ui).
