### ISSUE TITLE
Request:Changing the endpoint swagger-ui.html

### ISSUE THREAD

**Issue by igorng** [springfox/springfox#1188]
Hello,

thanks  fr the great work.

It would be nice to be able to change the endpoint served when using swagger-ui (swagger-ui.html) trhoug a property config or something like that.

Thanks

**Comment by dilipkrish** [comment]
Closing this as a duplicate of #1080

**Comment by emreaydin52** [comment]
You refer to this page from the duplicate one and refer to the original @dilipkrish. This issue is not still resolved.
