### ISSUE TITLE
OSGi Bundle

### ISSUE THREAD

**Issue by bsiver** [springfox/springfox#119]
Has anyone had success converting this library to run in an OSGi container?

**Comment by shanmukhm** [comment]
@bsiver Do you have SpringFox bundle uploaded anywhere? I really need it right now

**Comment by jayhamilton** [comment]
I will check what we have and try to get back to you over the next couple days.

Sent from my iPhone

On Aug 23, 2016, at 6:45 AM, shanmukhm <notifications@github.com<mailto:notifications@github.com>> wrote:


@bsiver<https://github.com/bsiver> Do you have SpringFox bundle uploaded anywhere? I really need it right now

-
