### ISSUE TITLE
Springfox not emitting attributes for definitions with some kinds of circular references

### ISSUE THREAD

**Issue by benfowler** [springfox/springfox#1196]
Hi,

(**TL;DR**: I've put together a working minimalist Spring Boot application demonstrating the issue here: <https://github.com/benfowler/springfox-apparent-circular-ref-issue/tree/master/complete>.)

Springfox is handling some definitions (with types where some indirect circular dependencies exists), in a strange way -- sometimes, attributes get dropped.

I annotate my resource classes, expecting to see the following:

```json
"Monkey": {
    "properties": {
        "pirate": {
            "$ref": "#/definitions/Pirate"
        }
    }
},
"Pirate": {
    "properties": {
        "monkey": {
            "$ref": "#/definitions/Monkey"
        }
    }
},
```

But I get

```
"Monkey": {},
"Pirate": {
    "properties": {
        "monkey": {
            "$ref": "#/definitions/Monkey"
        }
    }
},
```

Note that this works just fine:

```json
"Ninja": {
    "properties": {
        "ninja": {
            "$ref": "#/definitions/Ninja"
        }
    }
},
```

So it appears to be a problem where there is at least one degree of separation between types between the objects.

Debugging the code within Springfox when processing the `Monkey` model, I note that it's being dropped from my schema because deep within Springfox, `ModelContext.hasSeenBefore()` is evaluating to `false`, because `Pirate` has been "seen before"...

**Comment by dilipkrish** [comment]
@benfowler Thanks for reporting this, this is definitely a bug. Ideally what should happen is while hasSeenBefore is honored is should still add the model reference as a property.
