### ISSUE TITLE
springfox and spring-integration interface endpoints

### ISSUE THREAD

**Issue by flexguse** [springfox/springfox#1198]
Please take the time to search the repository, if your question has already been asked or answered.

- [X] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [X] Question. Is this a question about how to do a certain thing? 

Hi, 

I have some trouble integrating spring-fox in an existent spring application which uses spring-integration to provide REST endpoints.

An endpoint-interface containing spring-fox annotation looks like this:

```java
@Api(value = "REST endpoint to read / write configurations")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@Path("/configuration")
public interface ConfigurationService {

    @ApiOperation(value = "updates the SOLR configuration", httpMethod = HttpMethod.PUT, consumes = MediaType.APPLICATION_JSON)
    @PUT
    @Path("/solr")
    void updateSolrConfiguration(SolrConfigurationTO configuration);

    @ApiOperation(value = "reads the current SOLR configuration", httpMethod = HttpMethod.GET, produces = MediaType.APPLICATION_JSON)
    @GET
    @Path("/solr")
    SolrConfigurationTO getSolrConfiguration();

}
```

Unfortunately spring-fox (or swagger?) does not inspect the interface and no documentation is created.

Is there any way to let spring-fox inspect spring-integration endpoint interfaces?

**Comment by dilipkrish** [comment]
Jax-rs annotations aren't supported.  You might have better luck with switching the Spring mvc annotations or using the swagger-core library from the mother-ship
