### ISSUE TITLE
Port missing when using nginx port forwarding in docker

### ISSUE THREAD

**Issue by adamtsai** [springfox/springfox#1200]
Hi,

I use docker to run api and have springfox. When I expose the port in api container directly, the curl  in swagger-ui.html work as expected. ex.
    "curl -X POST --header "Content-Type: application/json" "http://192.168.99.100:9002/abc", but when I use nginx in docker to forward the port, the curl show in swagger-ui.html looks like this
    "curl -X POST --header "Content-Type: application/json" "http://192.168.99.100/abc", 
it's missing port number. I can still access swagger-ui.html, just when click the link "try it out", it shows "no content". All the api calls by pass nginx work correctly.

 Nginx config:
     upstream api_backend {
        server api.example.com:8080;
    }
    server {
        listen 9001;
        port_in_redirect on;
        location / {
                proxy_set_header Host $host:$server_port;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://api_backend/;
        }
    }

How can I fix this issue?

Thanks

**Comment by dilipkrish** [comment]
@adamtsai Unfortunately I'm not familiar with nginx and how it is doing your port forwarding. Ideally it should also url re-write to the right ports.

**Comment by koorlan** [comment]
Hello, I know this is old question but i've to managed same issue today
The problem : port is lossed when request is proxified by nignx :

Solution : 

Change : 
 proxy_set_header X-Forwarded-Host $host;

To : 
  proxy_set_header X-Forwarded-Host $host:$server_port;



Explication :
The class  UriComponentsBuilder is called at the end of the Swagger object generation
i will not detail all call but : this methdo is called (adaptFromForwardedHeaders)
With initial request of the documentation
This is here that the real port( ngninx exposure  is resolved) by decoding X-Forwarded-Host header

Good day

**Comment by renepupil** [comment]
In my case the browser was caching the redirect URL before I correctly set `port_in_redirect on;`. So disable browser caching when debugging nginx rules.
