### ISSUE TITLE
improve swagger-ui presentation of information generated by springfox-bean-validators

### ISSUE THREAD

**Issue by grandmasterpixel** [springfox/springfox#1202]
using both artifacts in version 2.4.0
At the moment what I see in chrome and firefox:
No indication that I can mouseover to get more information about some properties.
When I do mouseover all popups for every property appear, which leads to a lot of overlapping.

To me a natural approach to indicating additional information on mouseover would be to add a dotted underline to the property.

**Comment by dilipkrish** [comment]
@grandmasterpixel This perhaps an issue that is better addressed by [swagger-ui project](https://github.com/swagger-api/swagger-ui)
