### ISSUE TITLE
swagger-ui location /configuration/ui configurable?

### ISSUE THREAD

**Issue by flexguse** [springfox/springfox#1203]
Please take the time to search the repository, if your question has already been asked or answered.

- [X] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

In the default settings swagger-ui does a request to 
`/configuration/ui`
ant to
`/configuration/security`

Is there any possibility to configure the path, i.e. to
`/swagger-ui-configuration/ui`
and
`/swagger-ui-configuration/security`?

In our application there already is the webservice endpoint
`configuration`
is defined and can't be changed.

**Comment by dilipkrish** [comment]
@flexguse sadly no. Thats an oversight. It shouldve been _namespaced_. I'll reword this request to address the problem in a patch

**Comment by dilipkrish** [comment]
In any case, the work around for you is to not use the springfox-swagger-ui and package the swagger-ui that comes from the _mother ship_ and not use the one that comes bundled with springfox. I know thats not very convenient at the moment, i'll try and have it fixed

**Comment by dilipkrish** [comment]
@gmarziou this change is probably going to affect your implementation in jhipster

**Comment by gmarziou** [comment]
Yes, it should be no big deal. 
Thanks for the notification, I'll make some test and get prepared for 2.5.0

**Comment by flexguse** [comment]
@dilipkrish Thanks for your reply, I'll try to use the pure swagger-ui.

**Comment by dilipkrish** [comment]
Actual that won't work. I was mistaken about the work around. It needs this fix to be applied for it to work.

**Comment by flexguse** [comment]
@dilipkrish When do you expect 2.5.0 to be released?

Would the workaround work to host the Swagger-UI in a different webproject in the same Tomcat where I give the /v2/api-docs Url?

**Comment by dilipkrish** [comment]
Actually in a couple week perhaps.. want the dust to settle after 2.4.0
