### ISSUE TITLE
Help Needed: Swagger aggregation example application

### ISSUE THREAD

**Issue by varghgeorge** [springfox/springfox#1204]
Aggregating documentation from multiple services is a very important feature. Even though I was able to find different suggestions/discussions, couldn't find a good example which anyone interested can follow easily. 

I have posted the sample application here:
https://github.com/varghgeorge/swagger-single

But, the controller is not being picked up (based on the logs) and I am not able to see the additional services. Can you please take a look at the repo?

Please let me know if there is already an example repo of it with Spring boot.

If I add @EnableSwagger2, it throws (not picking up the new controller I created) 
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'apiResourceController' for bean class [springfox.documentation.swagger.web.ApiResourceController] conflicts with existing, non-compatible bean definition of same name and class [doc.ApiResourceController]

Without @EnableSwagger2:
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [springfox.documentation.swagger.web.SwaggerResourcesProvider] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}

**Comment by dilipkrish** [comment]
I can't elaborate at the moment as this is a little bit involved. I'll try to get back with a detailed response later. Here is [a discussion](https://github.com/springfox/springfox/pull/1189) to get you started.

In the mean while, have you looked at what the [jhipster guys are doing](https://github.com/jhipster/generator-jhipster/issues/3018)? Its really what you're looking for. Im sure they'd appreciate your testing/feedback as well.

**Comment by varghgeorge** [comment]
Thanks a lot @dilipkrish.

I was able to follow jhipster's file and it is working now. Will update and share the sample application (in the same location) later.

Thanks again! We can close this.

**Comment by dilipkrish** [comment]
@varghgeorge The sample repo would be really useful. Please do share the link.

**Comment by varghgeorge** [comment]
Updated with latest, still need enhancements to make the list dynamic. Currently works with a static list.

https://github.com/varghgeorge/swagger-single

**Comment by dilipkrish** [comment]
@varghgeorge :bow: for putting that up!! I've forked it and I might incorporate it into the docs (and may ping you if I have any questions)!

**Comment by varghgeorge** [comment]
@dilipkrish I updated the repo to load the all services configuration from the yaml file. So, no service details in the code now.

Renamed the repo to https://github.com/varghgeorge/microservices-single-swagger

**Comment by GoudGopichand** [comment]
I m facing issue ...
I want to customized swagger ui.html so i extracted swagger ui.html and all its dependenta js css and added in new project 
As swagger custom api and packaged it as jar not as war using spring boot ..i created webapp in project and added swaagerui.html and all its dependencies 
In local env it loads swagger ui html and works fine but when try to run through mginx aerver it i m getting 404

**Comment by GoudGopichand** [comment]
* Nginx server  typo error

**Comment by GoudGopichand** [comment]
Really appreciate if some one can help me on this issue

**Comment by dilipkrish** [comment]
Seems like your nginx server is not configured correct @GoudGopichand
