### ISSUE TITLE
Remove/change mappings

### ISSUE THREAD

**Issue by gaah666** [springfox/springfox#1205]
I enabled springfox with the @EnableSwagger2 annotation on a @Configuration class. When running the   server I see all mappings in the logs:
"/my-crap1"
"/my-crap2" aso...

New mappings added when enabling springfox:
"/v2/api-docs"
"/configuration/security"
"/configuration/ui"
"/swagger-resources"

I only need the one at "/v2/api-docs". I want to:
a) Change this mapping to be somewhere else like "/docs" for instance
b) I want to remove the other mappings since I have no use for them

I've been reading through lots of examples and testing everything I can think of to no avail. How can I do this? Is it even possible?

**Comment by dilipkrish** [comment]
@gaah666 currently we made a fix to change some of the mappings so the new mappings will look like this

| endpoint        | is customizable           |
| ------------- |:-------------:| 
| "/v2/api-docs"      | [yes](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints) |
| "/swagger-resources/configuration/security"     | no      |
| "/swagger-resources/configuration/ui" | no      | 
| "/swagger-resources" | no |

Any ideas that you might have to make that better is welcome

**Comment by gaah666** [comment]
To be able to customize the mapping of "/v2/api-docs" would be great!

The other three... Why not be able to customize them too? For me, I have no use for them at all, so I would like to disable them altogether.

**Comment by rajagkrishnan** [comment]
I am also interested in knowing if it is possible to customize the mappings. We are able to add prefix to the mappings, so it will be great if we can either customize the mapping or atleast remove a part of the mapping.

 For example my endpoints are documented by swagger as /login/abc and /login/xyz etc, but I would like to ignore the Controller level RequestMapping(login) and want the documentation to reflect only the /abc and /xyz .
