### ISSUE TITLE
I know this is not the correct repo to post this but...

### ISSUE THREAD

**Issue by mherb63** [springfox/springfox#1206]
Is there a way via swaggerhub to define the generated java package name for the model and api?  I think this would be a powerful feature.  Sorry for asking here but I didn't see any links on swaggerhub to ask this.

Thanks,

Mike

**Comment by dilipkrish** [comment]
My guess is that would come under the open api [vendor extension support](https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/EXTENSIONS.md). You might want to post the question [here](https://github.com/OAI/OpenAPI-Specification) or in the [swagger tool chain forum](https://groups.google.com/forum/#!forum/swagger-swaggersocket).
