### ISSUE TITLE
Query parameters - complex data types are coerced to 'string' type

### ISSUE THREAD

**Issue by jkasmann** [springfox/springfox#1209]
Hi,

Possible new bug.  In 2.4.0, any query parameters (@ApiImplicitParam or derived from @RequestParam) with types not included in Types.baseTypes are shown as 'string'.  In the case of List<MyObject>, the collection information is lost and the type is still 'string'.  

Swagger json in 2.3.2:
```json
{
    "name":"containsCodes",
    "in":"query",
    "description":"Filter by code groups that contain one or more codes.",
    "required":false,
    "type":"array",
    "items":{"$ref":"#/definitions/CodeFilter"},
    "collectionFormat":"multi"
}
```

Swagger json in 2.4.0:
```json
{
    "name":"containsCodes",
    "in":"query",
    "description":"Filter by code groups that contain one or more codes.",
    "required":false,
    "type":"string"
}
```

**Comment by dilipkrish** [comment]
This is by design. I haven't seen the use case for having that be a complex type.

**Comment by jkasmann** [comment]
Support was removed on purpose for 2.4.0?  It has been working for us for quite some time.  We occasionally have query parameters that need to be complex JSON objects.  Swagger UI then shows the expected model scheme for those parameters.

**Comment by dilipkrish** [comment]
I belive so. Details on the motivations is available in [this issue](https://github.com/springfox/springfox/issues/1145).  

Couple of reasons for doing so, 
- because what it boils down to is tunneling complex objects via serialized json objects, which are ultimately strings or at the very least primitives. 
- it makes things hard from a maintenance perspective having all this conditional logic

**Comment by dilipkrish** [comment]
Perhaps if you have suggestions we could look at how we could make it easy to provide overrides for this behavior without bringing on that burden into this library.

**Comment by jkasmann** [comment]
The reasons you listed makes sense - in fact the first thing I thought when I saw the behavior is that you probably went with string because the idea of passing an "object" in a request parameter is somewhat weird and doesn't make much sense in http.  I was a bit surprised that List<ComplexObject> (or allowMultiple=true for implicit) did not end up as Array<string>.  I was also surprised that the documentation mentions using dataType="<fully qualified class name>", which does not seem to be supported in the latest version.

The tough part is that sometimes it is not easy to represent input data with primitive values, and the <2.4.0 version + swagger UI did a nice job documenting expectations for json parameters.  In 2.4.0 I can stick with 'string' as the type and use the description to try and describe the contract, but that is not very dynamic and does not look very good in swagger UI.

I am not sure what is easy on the springfox side as I am not too familiar with the code.  From the API side, what made sense to me is that the @ApiImplicitParam dataType field would be honored, and the allowMultiple would drive if they type is array.  

Thanks for the quick responses!

**Comment by dilipkrish** [comment]
I'll investigate and see the easiest possible way to make us both :smile:

**Comment by dilipkrish** [comment]
The solution is probably that [this](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OperationImplicitParameterReader.java#L86-L92) should handle allowMultiples as well

**Comment by efiwib** [comment]
@dilipkrish 
Hi,

Are you planning to add support for complex data types in query 
parameter in upcoming releases?
or is there any alternative way to do this this?

Thanks

**Comment by dilipkrish** [comment]
@efiwib No. The only way I can think of is to add an example.

**Comment by sheekaat** [comment]
@dilipkrish I've a use case where request params (Initially 3, and then 4 and now 5) keep on changing because of the new requirements. Whenever we add/delete the request params, we ended up modifying all the files. Now, we're moving the request params to a class. Spring supports this and not finding any option in the swagger to define the class as a request param type.

**Comment by dilipkrish** [comment]
@sheekaat they need to be marked as @ModelAttributes
