### ISSUE TITLE
Context-Path missing when behind Proxy

### ISSUE THREAD

**Issue by matonthecat** [springfox/springfox#1210]
Hey,

I'm using Springfox Swagger2 v2.4.0 with a Zuul as the reverse proxy. My aim is to implement a RESTService documented by swagger. 

Direct links on the host look like this:
`http://service-host:8080/path`

whereas links to be routed via Zuul look like this:
`http://zuul-host:8080/service-context/path`

While the swagger-ui generates the correct URLs when called from the service-host directly. However, when called via the reverse proxy, it fails to produce correct try-out links. The links produced do contain the right server/port but not the routes as assigned on the reverse proxy (albeit the `X-Forwarded-*` are all set) like this:

`http://zuul-host:8080/path`

This is due to the implementation of the  [Swagger2Controller](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L88) where the context path is ignored for some reason.

```java
UriComponents uri = componentsFrom(servletRequest);
String host = uri.getHost();
int port = uri.getPort();
if (port > -1) {
    return String.format("%s:%d", host, port);
}
```

As I saw in debugging mode, the generated `UriComponents` in fact do contain the required path altogether. I would appreciate, if that path would be the one returned, or someone implement context awareness in some other way.

Thx,

mat

**Comment by dilipkrish** [comment]
@matonthecat I haven't had time to try it out myself or create a sample but there has been much success based on using the approach that the jhipster folks have taken. [Check this issue](https://github.com/springfox/springfox/issues/1204#issuecomment-193275322) for more details.

**Comment by matonthecat** [comment]
Hi @dilipkrish ,

thank you for your swift response. 

I found that part of the solution will be configuring [a centralized swagger-resources as in issue 2990 of jhipster](https://github.com/jhipster/generator-jhipster/issues/2990). Then we could have some central swagger-ui pointing to this resource. 

Nevertheless, configured this way the issue stated above remains: all links generated by the swagger-ui will not contain the context path on the reverse proxy.

This could be fixed easiest by setting the `basePath` in the JSON returned by Swagger2Controller.

What do you think?

**Comment by dilipkrish** [comment]
@matonthecat Not really sure what the problem is. 

- The basePath is [overridable by providing a custom  path provider](http://springfox.github.io/springfox/javadoc/current/springfox/documentation/spring/web/plugins/Docket.html#pathProvider(springfox.documentation.PathProvider)). 
- The [default path provider definitely uses the context path](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/paths/RelativePathProvider.java#L37).
- The [swagger2controller](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L88) code that you refer to is only to get the host name and port.

**Comment by matonthecat** [comment]
@dilipkrish okay, the problem description was not quite clear about the problems, I am experiencing. I updated it. To make it clear: it is not about the static configuration of the context path where swagger-routes and api-docs are installed, but the links generated for the try-out-buttons.

**Comment by cbeaujoin** [comment]
In order to avoid the problem I extend of the following class in my main SwaggerConfiguration Class

`public class AbstractSwaggerConfiguration {

	protected String getHost() {
		String host = null;
		try {
			host = InetAddress.getLocalHost().getCanonicalHostName();
		} catch (UnknownHostException e) {
			e.printStackTrace();
		}
		return host;
	}

	protected class BasePathAwareRelativePathProvider extends AbstractPathProvider {
		private String basePath;

		public BasePathAwareRelativePathProvider(String basePath) {
			this.basePath = basePath;
		}

		@Override
		protected String applicationPath() {
			return basePath;
		}

		@Override
		protected String getDocumentationPath() {
			return "/";
		}

		@Override
		public String getOperationPath(String operationPath) {
			UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/");
			return Paths.removeAdjacentForwardSlashes(
					uriComponentsBuilder.path(operationPath.replaceFirst(basePath, "")).build().toString());
		}
	}
}
`
And use it like this in my bean :

`	@Bean
	public Docket apiName() {
		return new Docket(DocumentationType.SWAGGER_2).groupName("name").apiInfo(apiInfo()).select()
				.apis(RequestHandlerSelectors.basePackage("biz.name")).paths(PathSelectors.any()).build()
				.directModelSubstitute(Calendar.class, String.class).genericModelSubstitutes(ResponseEntity.class)
				.pathProvider(new BasePathAwareRelativePathProvider("/api/name")).host(getHost());
	}`
