### ISSUE TITLE
ApiParam allowableValues string with spaces

### ISSUE THREAD

**Issue by pvpkiran** [springfox/springfox#1211]
APiParam annotation has a parameter allowableValue. This takes a comma separated string. But if i have a space in one of the values, it is stripping it off. Which is not good. I can pass a string with spaces from the browser url. So i should be able to pass it from swaagger UI as well. 

I think the issue is with this line
` allowableValueString = allowableValueString.trim().replaceAll(" ", "");`
in `ApiModelProperties.java` file.  Line 59

**Comment by dilipkrish** [comment]
Thanks for catching that @pvpkiran :metal:

**Comment by uriparush** [comment]
Hi,
I have the same issue and I use version 2.8.0
I found the below line in class "ApiModelProperties"
String trimmed = allowableValueString.trim().replaceAll(" ", "");

Is there a good reason for this ?
As written before space can be a valid input.

Thanks
