### ISSUE TITLE
@Extension/@ExtensionProperty usage for Api Gateway Extension json

### ISSUE THREAD

**Issue by lazygarage** [springfox/springfox#1212]
Hi,
 
 I am trying to use the **@Extension** and **@ExtensionProperty** annotation to compose the swagger json required for aws api gateway extension.
 Following is the aws api json snippet, I am trying to create:

 ```
"x-amazon-apigateway-integration" : {
   "type" : "aws",
   "uri" : "my-uri",
   "httpMethod" : "GET",
   "requestTemplates" : {
       "application/json" : "json request template 2",
       "application/xml" : "xml request template 2"
   },
   "requestParameters" : {
       "integration.request.path.integrationPathParam" : "method.request.querystring.latitude",
       "integration.request.querystring.integrationQueryParam" : "method.request.querystring.longitude"
   }
}      

```
 I am able to create the x-amazon-apigateway-integration using @Extension/@ExtensionProperty and was able to add name value pairs.
 i.e. 
   "type" : "aws",
   "uri" : "my-uri",
   "httpMethod" : "POST",

Here's the java code for the same with **@Extension** used on **@ApiOperation**
```
@ApiOperation(value="Get users", nickname="Get Users",
			extensions={
					@Extension(name="x-amazon-apigateway-integration",properties={
							@ExtensionProperty(name="type", value="aws"),
							@ExtensionProperty(name="uri", value="my-uri"),	
							@ExtensionProperty(name="httpMethod", value="GET"),
					})
			})

```

 However, I am currently stuck at using the **@Extension**/**@ExtenstionProperty** to reflect the correct json for **requestTemplates** and **requestParameters** attributes. Both of them contain multiple name/value attributes rather than a simple name/value pair.
 @Extension doesn't allow child @Extension.

 Appreciate if you could help me in this regard.

 Thanks,
 Pawan

**Comment by dilipkrish** [comment]
@lazygarage So while the springfox internal models support your need totally, the annotations provided by *swagger-core* do not. 

The _good news is_ that it is very straight forward to write your own annotations and write a plugin to read the same [just like the one that reads the swagger provided annotations](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/VendorExtensionsReader.java#L49). 

The _bad news is_ that its really an extensibility hook that is available and doesn't really belong in the core library. 

There is [plenty of documentation](http://springfox.github.io/springfox/docs/current/#plugins) to get you started on plugin development and I'm usually lurking to help answer any questions you might have.

**Comment by lazygarage** [comment]
Hi @dilipkrish,

Thanks for the prompt reply and pointing me the right direction.

We are currently exploring the Amazon API Gateway to expose the rest services.
We are using the [aws-apigateway-importer](https://github.com/awslabs/aws-apigateway-importer/ ) tool to import the Swagger definitions to AWS API Gateway.
This requires some manual work on API Gateway console which we want to replace with incorporating the Extention Annotations to produce the required json.

I will check the links you provided. 
Thanks for the help.

-Pawan

**Comment by lazygarage** [comment]
Hi @dilipkrish ,
I tried to implement the custom annotation which could take more than a simple String value along with a custom plugin [VendorExtensionsReader](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/VendorExtensionsReader.java#L49) to process the annotations as suggested by you.

I then debugged into the flow and came across the class [VendorExtensionsMapper.java](https://github.com/springfox/springfox/blob/72334193ed210aa60808babd43e82442aa9d871d/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/VendorExtensionsMapper.java).which processes the VendorExtension.
From what I could infer, the VendorExtensionMapper processes the [ObjectVendorExtension](https://github.com/springfox/springfox/blob/72334193ed210aa60808babd43e82442aa9d871d/springfox-core/src/main/java/springfox/documentation/service/ObjectVendorExtension.java) and use recursion to map all the extension properties as [StringVendorExtension](https://github.com/springfox/springfox/blob/72334193ed210aa60808babd43e82442aa9d871d/springfox-core/src/main/java/springfox/documentation/service/StringVendorExtension.java) which simply takes in the name/value.
My intention is to have the extension values to be more than a simple String.
eg.
"**requestTemplates**" : {
       "application/json" : "json request template 2",
       "application/xml" : "xml request template 2"
   },
   "**requestParameters**" : {
       "integration.request.path.integrationPathParam" : "method.request.querystring.latitude",
       "integration.request.querystring.integrationQueryParam" : "method.request.querystring.longitude"
   }

Appreciate if you could guide me more in this. Do I need to override more core classes ?
I am stuck for a while now and not sure where to proceed.

Thanks,
Pawan

**Comment by dilipkrish** [comment]
I don't follow what the issue is. VendorExtension can be either an object or a string; the only contract is that it has a name. So from that perspective

```java
//nested...
ObjectVendorExtension("amazon,  List(
    ObjectVendorExtension("requestParameters", List(
        StringVendorExtension(
            "integration.request.path.integrationPathParam" , "method.request.querystring.latitude"),
        StringVendorExtension(
            "integration.request.querystring.integrationQueryParam" : "method.request.querystring.longitude")
    ),
)
```

So is the issue that it doesn't accept a singular object like this :point_down: instead?

```java
//nested...
ObjectVendorExtension("amazon,  ObjectVendorExtension("requestParameters", List(
        StringVendorExtension(
            "integration.request.path.integrationPathParam" , "method.request.querystring.latitude"),
        StringVendorExtension(
            "integration.request.querystring.integrationQueryParam" : "method.request.querystring.longitude")
    ),
)
```

**Comment by lazygarage** [comment]
Hi @dilipkrish ,

Thanks for your time and reply.
I think I am able to achieve the required extenstion json now.
I wrote the following custom annotations and created the plugin for processing the same.
```

@AwsExtensions({
		@AwsExtension(name="x-amazon-apigateway-integration",
				properties={
						@AwsExtensionProperty(name="type",value="http"),
						@AwsExtensionProperty(name="httpMethod",value="GET"),
				},
				extensions={
						@Extension(name="requestParameters",properties={
								@ExtensionProperty(name="integration.request.path.integrationPathParam",value="method.request.querystring.latitude"),
								@ExtensionProperty(name="integration.request.querystring.integrationQueryParam",value="method.request.querystring.longitude"),
						})
				})
    })
```

I am getting the desired json string now in the swagger json.

```
"x-amazon-apigateway-integration": {
          "requestParameters": {
            "integration.request.querystring.integrationQueryParam": "method.request.querystring.longitude",
            "integration.request.path.integrationPathParam": "method.request.querystring.latitude"
          },
          "type": "http",
          "httpMethod": "GET"
        }
```
I hope this approach works.

Thanks,
Pawan

**Comment by dilipkrish** [comment]
Awesome! 👍🏻

**Comment by Cyberfrog** [comment]
Hi @lazygarage  i am also facing same issue.
can you post implementation of @AwsExtensions and @AwsExtensionProperty.

**Comment by lazygarage** [comment]
@Cyberfrog You can check this [Sample](https://gist.github.com/lazygarage/d136e269069d933bf72e2055b6b80d20)
Hope it helps.

**Comment by akamanocha** [comment]
Can you please help me with how have you written plugin?

I assume @AwsExtensions dont go into @ApiOperation. So how would I check for this new annotation in plugin?

**Comment by akamanocha** [comment]
Thanks I got it working,

Would be interesting to know if you have written something generic, multi-level jsons though.

My language is java. Also if you have integrated it with swagger-maven-plugin?

**Comment by koderman** [comment]
Hi @akamanocha ,
I have got rid of the new annotations which I mentioned earlier in the thread.
The annotations resulted in lots of boilerplate code and more documentation for the team.
Also, the annotations have their limits to the multi-level jsons.

I have now moved the logic to the custom VendorExtensionsReader class. [CustomAwsExtensionsReader](https://gist.github.com/koderman/d49a67274e33f03405a8e45672794968)

The plugin now basically scans the required Swagger annotations to create the List of **VendorExtension**. list.
You can update the plugin to suit your needs.
Hope it helps.
-Pawan

**Comment by helloworldtang** [comment]
@koderman

CustomAwsExtensionsReader.java compile fail.
use springfox-spi-2.6.1
![customawsextensionreader](https://cloud.githubusercontent.com/assets/13701989/21540065/7b2fd9e2-cde7-11e6-8ba2-15282af82c1d.png)

**Comment by dilipkrish** [comment]
@helloworldtang Sorry I just realized that was a breaking change. You can use the `context.findAnnotation(ApiOperation.class);` instead.

**Comment by bsautner** [comment]
@koderman i'm working through the same problem @lazygarage had in this thread where in order to get AwsApiGateway to import my api-docs i have to go through each api and manually add requestParameters to x-amazon-apigateway-integration.  The fix here looks like exactly what I need - do you have an updated CustomAwsExtensionsReader?  The one posted in this thread looks like it may be based on an older version of springfox.  

I'm also trying to figure out why my api-docs turn Long fields like a timestamp  into 

```
timestamp: {
type: "integer",
format: "int64"
}
```
and AWS turns those into Integers when generating a java client.

**Comment by dilipkrish** [comment]
@bsautner There might be some breaking changes in the API. If you show me what you're trying to do I can possibly help.

**Comment by bsautner** [comment]
@dilipkrish thanks for offering - I hope I can contribute to this project.  Here is a more detailed description of what i'm doing.

My goal is to generate api-docs json that can be uploaded to AWS Api Gateway without any manual modifications. The API will do a http passthrough to a elastic load balancer behind it.   Here is a sample GET annotated with `x-amazon-apigateway-integration` 

 ```
@ApiOperation(
            authorizations = {@Authorization(value = "x-api-key")},
            extensions = {
                    @Extension(
                            name = "x-amazon-apigateway-integration",
                            properties = {
                                    @ExtensionProperty(name = "uri", value = AWS_GATEWAY_PATH),
                                    @ExtensionProperty(name = "passthroughBehavior", value = "when_no_match"),
                                    @ExtensionProperty(name = "httpMethod", value = "POST"),
                                    @ExtensionProperty(name = "type", value = "http_proxy"),
                            }
                    )
            }
    )

    @ApiResponses({
            @ApiResponse(code = 200, message = "Snapshot Posted Successfully", response = Snapshot.class),
            @ApiResponse(code = 404, message = "Topic Not Found"),

    })
    @RequestMapping(
            produces = MediaType.APPLICATION_JSON_VALUE,
            value = END_POINT,
            method = RequestMethod.POST
    )
    public ResponseEntity<Snapshot> postSnapshot(
            @RequestHeader(name = X_API_KEY_HEADER) String apikey,
            @RequestBody Snapshot value,
            @PathVariable String id)
            throws Exception {


}
```

The api-docs generated work just fine with this section being generated:

```
x-amazon-apigateway-integration: {
httpMethod: "GET",
integration.request.path.id: "method.request.path.id",
passthroughBehavior: "when_no_match",
type: "http_proxy",
uri: "http://url-to-my-load-balancer/{id}/snapshot"
}
```
notice the path parameter `{id}`  the problem is that AWS needs to know that there is a path parameter in the pass through url.  If found if i add it manually change this json to this it works perfectly:
```
"x-amazon-apigateway-integration": {
          "requestParameters": {
            "integration.request.path.id": "method.request.path.id"
          },
          "uri": "http://path-to-load-balancer/{id}/snapshot",
          "passthroughBehavior": "when_no_match",
          "httpMethod": "GET",
          "type": "http_proxy"
        }
```

AWS requires this entry: 

```
       "requestParameters": {
            "integration.request.path.id": "method.request.path.id"
          }

```
so this is a json field with an object with a name / value pair - swagger  @ExtensionProperty can only be used to add a key value pair.   I'd need a way to annotate the API with the requestParameters required by AWS Api Gateway. 

As there is no way currently to do this  - `CustomAwsExtensionsReader`  mentioned above seems to do exactly what i need but it doesn't seem compatible with the latest API.

**Comment by dilangathalpegama** [comment]
Hi @koderman can you please show an example with CustomAwsExtensionsReader.java? I would like to see how that is used with a Spring Controller. Thanks in advance!

**Comment by koderman** [comment]
@dilangathalpegama 
Here's the code for [CustomAwsExtensionsReader](https://gist.github.com/koderman/d49a67274e33f03405a8e45672794968)

Note: This code is no longer compatible with the latest API.

**Comment by jorgearal** [comment]
I need this extension, I'm looking in the docs but it's still referenced to the [CustomAwsExtensionsReader](https://gist.github.com/koderman/d49a67274e33f03405a8e45672794968) is there any way to make it work with the latest API?

**Comment by jorgearal** [comment]
After some days I made it work, if you're looking for an update you can find it here: [UpdatedCustomAwsExtensionsReader](https://gist.github.com/jorgearal/f93739d9f8479874c28767705aef4638)

**Comment by LucaFenris** [comment]
How I implements this class(UpdatedCustomAwsExtensionsReader) using springdoc openapi?

**Comment by Kononchuk-B** [comment]
> How I implements this class(UpdatedCustomAwsExtensionsReader) using springdoc openapi?

Hi! Sorry, but did you cope with implementation for spring doc openapi? Seems there are no opensource or embedded solution.
