### ISSUE TITLE
controller methods with different parameters

### ISSUE THREAD

**Issue by rsparkyc** [springfox/springfox#1214]
I have a controller with methods that do various types of filtering on my entities.  However, when using swagger, the UI only shows one (seemingly at random) of those methods.  I'm using the latest version of swagger (2.4.0), and have created a sample repo here:

[https://github.com/rsparkyc/spring-boot-swagger/](https://github.com/rsparkyc/spring-boot-swagger/)

After running `gradle bootRun`, you can make http calls to the following endpoints:
`http://localhost:8080/?name=something`
`http://localhost:8080/?other=somethingElse`

You'll notice each controller method is hit, but swagger UI only picks one of them to display.

**Comment by dilipkrish** [comment]
See [#21 in the documentation](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) & if you want a compatible swagger-ui -> [:secret:](http://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui-rfc6570/0.9.6)
