### ISSUE TITLE
@Api annotation no longer display custom name passed as param to annotation.

### ISSUE THREAD

**Issue by nickpanaiotov** [springfox/springfox#1215]
Hi, guys! When I updated to 2.4.0, spring-fox stopped to respect my custom name for controllers. In older version you can use api annotation just like this @Api(CustomName), now just showing class name. 

Regars, Nick

**Comment by nickpanaiotov** [comment]
Okey, now same behaviour can be achived with tags. @Api(tags = "CustomName")

**Comment by dilipkrish** [comment]
:+1:
