### ISSUE TITLE
How to manually add models/type information to DocumentationCache?

### ISSUE THREAD

**Issue by olegvm** [springfox/springfox#1216]
Hi,

I am using Springfox version 2.4.0 in conjunction with Spring Boot + Spring Boot Actuator. I need to provide Swagger documentation for the endpoints exposed by Actuator - e.g. `/health`, `/trace` and so on. However, Springfox is unable to properly scan those endpoints automatically, because they are configured dynamically. Those resources cannot be annotated with Swagger annotations as they are part of Spring.

I was able to add basic documentation for those resources manually by editing the documentation in `DocumentationCache`. But it is still missing the response models. There appears to be no easy way to manually add response models to documentation - the problem is with adding type information to the models (i.e. `Model `<- `ResolvedType`) and referencing those types.

_Question:_ Could you please help with adding the response models to the documentation, or point me to some direction?

_Example:_

```
new ApiListingBuilder(new Defaults().operationOrdering())
	.apis(apiDescriptionList)   // This list is easier to create and fill in.
	.models(...) 				// How to build models with ResolvedType information?
	.build();
```
	
Or:

```
new OperationBuilder(operationNameGenerator)
	.summary("Summary")
	.notes("Notes")
    .responseModel(...)    // Is it possible to refer to actual classes here?
	.responseMessages(Sets.newHashSet(
		// How to include model references?
		new ResponseMessage(HttpStatus.OK.value(), HttpStatus.OK.name(), null, ...))
	.build();
```

	
Best regards,
Oleg

**Comment by dilipkrish** [comment]
@olegvm haven't really researched this much... but at a high level the idea is to implement a [RequestHandlerProvider](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/service/RequestHandlerProvider.java) and use the [EndpointHandlerMapping](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/mvc/EndpointHandlerMapping.java) to feed it through the SpringFox machinery.

I think however, that getting access to the `EndpointHandlerMapping` is where the challenge lies.

**Comment by olegvm** [comment]
@dilipkrish Thank you for the suggestion - I'll investigate the possibility to use `RequestHandlerProvider`.

A quick test shows that acquiring `EndpointHandlerMapping` is not a problem - it can just be autowired into the constructor of `RequestHandlerProvider` implementation. This mapping allows to get all the necessary endpoints, but their return types are mostly just `Map<String, Object>`. What I'd like to describe is inside that Map, and the mapping does not seem to have this information.

I've got an idea which I'll investigate further - to try actually invoking those endpoints and scanning their resulting objects, then somehow return the schema from `RequestHandlerProvider`.

**Comment by olegvm** [comment]
In the end, I still decided to use manual editing of documentation in `DocumentationCache`, along with making use of the [additionalModels() method in Docket](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L413).

What I did was create several overlay classes which imitated the structure of Spring Boot Actuator's JSON responses, annotated them with Swagger annotations and passed those classes to `docket.additionalModels()`. Then I just referenced these classes when adding `ModelRef`s to `Documentation`.

It is still a bit of a hack, but it does work, and allowed to add the needed classes and their descriptions to the documentation.

**Comment by BetterOfToffy** [comment]
I don't know if this is going here, just let me know.
I'm in the same situation as olegvm, and i tried his solution, but... of course there is a "but"
Models adds on DocumentationContext through the additionalModels() method in Docket is only use by OperationModelsProvider who is an OperationModelsProviderPlugin.
And this solution does work only if your project contain Operations detected by springfox (controller with @RequestMapping) in my case https://github.com/springfox/springfox/issues/2876 calling additionnalModels() method does not change anything.
