### ISSUE TITLE
Using POJOs as GET request parameters

### ISSUE THREAD

**Issue by nickcodefresh** [springfox/springfox#1219]
In order to reduce the number of parameters in my controller method I'm using a POJO:

```
    @ApiOperation(value = "Generates a list of tokens for a list of URI", produces = MediaType.APPLICATION_JSON_VALUE)
    public List<TokenResponse> downloadTokens(@Validated DownloadTokensRequest downloadTokensRequest) {
```

The `DownloadTokensRequest` object is simply defined as:

```
@ApiModel
public class DownloadTokensRequest {

    @ApiModelProperty(name = "uri", value = "List of URIs of secured assets on the Secure Download Server")
    @NotNull
    @Size(min = 1)
    private String[] uris;

    ....
````

Swagger always says that downloadTokensRequest is a JSON GET request body though, rather than seeing the individual query parameters. Any ideas how I get this to work properly?

![untitled](https://cloud.githubusercontent.com/assets/5837418/13804347/2b560c78-eb72-11e5-802d-1d7b3aa31266.png)

Thanks

Nick

**Comment by garakelian** [comment]
Try @ModelAttribute after @Validated

**Comment by nickcodefresh** [comment]
Thanks, that worked

**Comment by nickcodefresh** [comment]
Actually I've just noticed on issue. If my parameters is an array, swagger only shows a single entry box

```

**Comment by dilipkrish** [comment]
@nickcodefresh So what does your parameter definition look like in your swagger definitions?
