### ISSUE TITLE
Changing the default path of swagger-ui.html

### ISSUE THREAD

**Issue by nichuHere** [springfox/springfox#1220]
Hi,

I am having a non-spingboot application.
I have been able to set up springfox with swagger ui and get it working.
Now I would like to change the default path to /swagger/swagger-ui.html.

I have tried the steps mentioned in the swagger doc :

>  Q. How does one configure swagger-ui for non-springboot applications?

However, this doesnt seem to be working. 

https://localhost:8080/v2/api-docs seems to be retuning values, but none under /swagger returns anything.

I also didnt get the last part where its mentioned : 

> However it still requires a redirect to /documentation/swagger-ui.html because the path name is hard-coded.

what url needs to be redirected to this?

**Comment by dilipkrish** [comment]
@nichuHere in your case replace `documentation` in the documentation example with `swagger` when you setup the redirect.

**Comment by nichuHere** [comment]
I did that but i am not able to get it running.  I have followed the steps as is.. it doesn't work for /documentation as well. 

Is ther some controller to be wrotten to facilitate the redireect ??

**Comment by dilipkrish** [comment]
Where are you adding the code snippet to `addViewControllers` and `addResourceHandlers`. It should be in a `WebMvcConfigurerAdapter` implementation that is a configuration bean.

**Comment by nichuHere** [comment]
I am configuring it my spring XML file

**Comment by dilipkrish** [comment]
Cant help much if I have to guess :8ball:   your configuration.

**Comment by nichuHere** [comment]
My Configuration looks like this :+1: 
`	<mvc:view-controller path="/swagger/v2/api-docs" view-name="/v2/api-docs"/>
    <mvc:view-controller path="/swagger/configuration/ui" view-name="/configuration/ui"/>
    <mvc:view-controller path="/swagger/configuration/security" view-name="/configuration/security"/>
    <mvc:view-controller path="/swagger/swagger-resources" view-name="/swagger-resources"/>
    <mvc:view-controller path="/swagger" view-name="/swagger/swagger-ui.html"/>
    <mvc:view-controller path="/swagger/" view-name="/swagger/swagger-ui.html"/>`

`   <mvc:resources mapping="/swagger/**" location="classpath:/META-INF/resources/"/> 
   
    <mvc:resources mapping="/swagger/webjars/**" location="classpath:/META-INF/resources/webjars/"/>`

**Comment by dilipkrish** [comment]
@nichuHere not familiar with the xml configuration, but that doesn't look right. You need to configure _redirects_ not _view-names_

**Comment by nichuHere** [comment]
Thankyou so much @dilipkrish..
Adding the redirect to the view  works like charm.

`	<mvc:view-controller path="/swagger/v2/api-docs" view-name="redirect:/v2/api-docs"/>
    <mvc:view-controller path="/swagger/configuration/ui" view-name="redirect:/configuration/ui"/>
    <mvc:view-controller path="/swagger/configuration/security" view-name="redirect:/configuration/security"/>
    <mvc:view-controller path="/swagger/swagger-resources" view-name="redirect:/swagger-resources"/>
    <mvc:view-controller path="/swagger" view-name="redirect:/swagger/swagger-ui.html"/>
    <mvc:view-controller path="/swagger/" view-name="redirect:/swagger/swagger-ui.html"/>`

**Comment by dilipkrish** [comment]
Updated the docs
