### ISSUE TITLE
Automate swagger ui services

### ISSUE THREAD

**Issue by nichuHere** [springfox/springfox#1221]
Hi,
I would like to know if there are any tools available to automate the services exposed by swagger-ui
which could be integrated with the build process

**Comment by dilipkrish** [comment]
Don't even know what this question means?

**Comment by nichuHere** [comment]
I wanted to know if there is any tool that can read the swagger spec file.. and automatically populate  the input params, fire and test if the services work.

**Comment by dilipkrish** [comment]
There might be. I'm not to sure. Have you looked at [Postman](https://www.getpostman.com)?

**Comment by nichuHere** [comment]
That seem like an independent tool. I would like something that could be integrated with the Maven build.
