### ISSUE TITLE
Issue Detecting HTTP Method for Spring Controller

### ISSUE THREAD

**Issue by sathishk** [springfox/springfox#1222]
In Spring MVC @RequestMapping, If we dont give method parameter, Then Spring considers that as GET Method. i.e

@RequestMapping(value = "/api/myApi",**method=RequestMethod.GET**) is equal to @RequestMapping(value = "/api/myApi")

While we integrate Swagger (Version 2.4.0), **If we dont specify method=RequestMethod.GET**, then in the swagger UI for the same method we could see **documentation for (HEAD,PUT,PATCH and GET)**. But it has to be just GET method

**Comment by dilipkrish** [comment]
@sathishk 

> In Spring MVC @RequestMapping, If we dont give method parameter, Then Spring considers that as GET Method. 

While this is true, not supplying also means the request mapping will support all the other methods as well.

**Comment by nirvanatao** [comment]
If we dont give method parameter for RequestMapping,but i just wanna show the POST method in the doc ,have any idea?

**Comment by dilipkrish** [comment]
Currently there is no way to do that I think.

**Comment by qsLI** [comment]
any workaround?

**Comment by dilipkrish** [comment]
@qsLI no, but if you'd like to see support for it, please create a new issue. This is closed
