### ISSUE TITLE
Swagger Models not displayed when spring security is enabled

### ISSUE THREAD

**Issue by varghgeorge** [springfox/springfox#1225]
I am not able to see the Model definitions when spring security is enabled. 

definitions: {
Response: {
type: "object"
},

eventhough Response object contains multiple fields and i tried documenting all gets using @ApiModelProperty.

I am using 2.4.0 release.

The model object is not part of /v2/api-docs if I add @ImportResource("classpath:spring-security.xml").  ONLY model objects are missing, everything else is displayed correctly.

Everything works fine if I don't load the spring-security XML file.

Any ideas?

**Comment by dilipkrish** [comment]
Can you create a reproducible sample using [springfox-demos](https://github.com/springfox/springfox-demos)?

**Comment by dilipkrish** [comment]
What does spring-security.xml look like?

**Comment by varghgeorge** [comment]
All services are at /ms/ path. 

<?xml version="1.0" encoding="UTF-8"?>
<bean:beans
	xmlns:bean="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:c="http://www.springframework.org/schema/c"
	xmlns="http://www.springframework.org/schema/security"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
		http://www.springframework.org/schema/beans/spring-beans-4.2.xsd
		http://www.springframework.org/schema/security
		http://www.springframework.org/schema/security/spring-security-4.0.xsd"> 
  
	<http realm="Protected API" 
		create-session="stateless"
		entry-point-ref="unauthorizedEntryPoint"
		authentication-manager-ref="restAuthenticationManager">

		<csrf disabled="true"/>

		<custom-filter ref="restAuthenticationFilter" position="FORM_LOGIN_FILTER"/>

		<intercept-url pattern="/**" access="permitAll"/>
		<intercept-url pattern="/ms/**" access="isFullyAuthenticated()"/>
	</http>

	<bean:bean id="unauthorizedEntryPoint" class="com.micro.security.UnauthorizedEntryPoint"/>
	<bean:bean id="userDetailService" class="com.micro.security.UserDetailsServiceImpl"/>

	<authentication-manager id="restAuthenticationManager">
		<authentication-provider user-service-ref="userDetailService">
		</authentication-provider>
	</authentication-manager>

	<bean:bean id="tokenManager" class="com.micro.security.TokenManagerImpl"/>

	<bean:bean id="authenticationService" class="com.micro.security.AuthenticationServiceImpl"
		c:authenticationManager-ref="restAuthenticationManager" c:tokenManager-ref="tokenManager"/>
 
	<bean:bean id="restAuthenticationFilter" class="com.micro.security.TokenAuthenticationFilter"
		c:authenticationService-ref="authenticationService" />
</bean:beans>

**Comment by varghgeorge** [comment]
@dilipkrish 

More details: 
I was able to narrow down the issue to the filter

    <bean:bean id="restAuthenticationFilter" class="com.micro.security.TokenAuthenticationFilter"
        c:authenticationService-ref="authenticationService" />

I tried commenting out everything in that filter and just do a chain (pass through). But still no luck!

Tried removing <custom-filter ref="restAuthenticationFilter" position="FORM_LOGIN_FILTER"/>
and defined bean using @Component. no luck still.

So, at this point, if I enable the filter which does nothing I can't view the models in swagger. In api-docs response the "parameters": object/element (which contains the object details) itself is missing. Works just fine if I remove the filter (api-doc returns the "parameters": object with all the details).

Any ideas?

**Comment by dilipkrish** [comment]
Could you try with the latest snapshot?

**Comment by varghgeorge** [comment]
@dilipkrish 
Tested with io.springfox:springfox-swagger2:2.4.1-SNAPSHOT. Same issue.

Based on more debugging, issue is not with the Filter itself... but with the AuthenticationService in the filter:

	@Autowired
	AuthenticationService authenticationService;

As long as I have it Autowired, swagger object does not show (even if I remove all references to the service).
