### ISSUE TITLE
SpringFox doesn't parse all JSON attributes

### ISSUE THREAD

**Issue by rzilist** [springfox/springfox#1226]
Hi guys,

I'm using Spring boot with springfox and having problems parsing JSON payload from Swagger UI into Java class (JSON->POJO). No errors, but the resulting Java object is missing a field (null). The top class for the class with missing attribute has Mixin to switch datatypes. That part works fine.

I can't really debug since framework does most of the parsing. The req-d attribute is displayed in  Swagger under Model Schema correctly. However, when I submit JSON payload containing same attribute, the corresp POJO's attribute is null. 

Please steer me to the right direction.

**Comment by dilipkrish** [comment]
Seems like a serialization issue. Frankly I'd have no idea without looking at something concrete.

**Comment by rzilist** [comment]
@dilipkrish here's JSON fragment I'm trying to parse:
```css
{
  "Address": [
    {
      "AddressLine1": "50 W Broad St.",
      "AddressLine1Transliterated": "50 W Broad St transliterated"
    }
  ]
}
```
(rest of the attributes removed)

Address is a part of an Org object. AddressLine object (part of Address), is converted to String with abstract Mixin interface. AddressLine1Transliterated should be a String (which is what shows in Swagger model schema):
```java
{
  "Address": [
    {
      "AddressLine1": "string",
      "AddressLine1Transliterated": "string",
      "AddressLine2": "string",
      "AddressLine2Transliterated": "string",
       etc
```

Mixin:
```java
public interface AddressMixin {
    @JsonIgnore
    public void setAddressLine1(AddressLine line);

    @JsonIgnore
    public void setAddressLine2(AddressLine line);
    ......................................
   @JsonProperty
    public void setAddressLine1(String line);

    @JsonProperty
    public void setAddressLine2(String line); 
```

I have setters for transliterated address lines:
```java
@JsonProperty("AddressLine1Transliterated")
    public void getAddressLine1TransliteratedString();
@JsonProperty("AddressLine2Transliterated")
    public void getAddressLine2TransliteratedString();
etc
```

a REST controller method making conversion:
```java
@RestController
public class RoundTripController {
......................................................
@ApiOperation(value = "Round-trip Org JSON", response = OrganizationEx.class)
    @RequestMapping(value = "/v1/roundtrip/json", method = RequestMethod.POST,
                    produces = "application/json")
    public OrganizationEx roundtripJson(@RequestBody OrganizationEx org) {
        log.info("AddressLine1: " + org.getAddresses().get(0).getAddressLine1());
        return org;
    }   
```

log prints **null** instead of a value for transliterated (which is an AddressLine property defined in xsd and generated java class):
AddressLine@1cfa08c[value=50 W Broad St., transliterated=\<null\>]


Let me know if you need any other info.

Thanks!

**Comment by dilipkrish** [comment]
I think this is some kind of bug with jackson. What version of jackson are you using?

**Comment by rzilist** [comment]
we use 2.4.0

**Comment by rzilist** [comment]
I've figured it out my issue: I was missing setter for the field in the Mixin interface. The JSON was being parsed, but the setter was missing, hence null value.

Thanks!

**Comment by dilipkrish** [comment]
wooohoo! :+1:
