### ISSUE TITLE
Bean Validations API (JSR-303) support for Request Parameters

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1227]
Version 2.4.0 added JSR-303 support for the models (https://github.com/springfox/springfox/issues/356).

For Request Parameters the following annotations could be supported as well:
- @Size 
- @Min
- @Max
- @NotNull
  - @RequestParam: not necessary if using @RequestParam(required=true) / by default  all request parameters are required
  - @ModelAttribute: necessary for parameters declared using a POJO/ @ModelAttribute

After Swagger-UI supports picking it up, it could be displayed/rendered in Swagger-UI as well:
https://github.com/swagger-api/swagger-ui/issues/1936

**Comment by jfiala** [comment]
Regarding @Size: As of 2.4.0 the allowableValues are not displayed in the API docs, see #1244

**Comment by jfiala** [comment]
Regarding @NotNull I can already provide a PR.
Regarding @Size/@Min/@Max #1244 should be fixed first to get it to work properly.

**Comment by jjzabkar** [comment]
Perhaps this issue should be tagged as "can-use-for-docs"?
https://github.com/springfox/springfox/labels/can-use-for-docs

**Comment by dilipkrish** [comment]
This has been fixed via #1371

**Comment by raderio** [comment]
Where information about pattern should be shown? I have `@Pattern` annotations but in UI I don't see any infomation.
