### ISSUE TITLE
2.4.0: Api value no longer used as tag name?

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1229]
2.4.0 / Migration from 2.2.0 to 2.4.0

from https://github.com/springfox/springfox/issues/1228

One additional thing I noted when switching between 2.4.0 and 2.2.0 (pls let me know if I should post a separate question):
In 2.4.0 the @Api(value="mycontrollername") is no longer used as tag name, instead the controller class name is always used as a tag name. 
Is it still possible to change the tag name?

**Comment by dilipkrish** [comment]
I believe tag name infected from value before it was introduced in swagger models. You should now be able to use tags to define tags. Additional you can supply tags with descriptions in the docket as well

**Comment by jfiala** [comment]
The tag feature works perfectly.
However, the @Api.description is currently marked @Deprecated, but it is still displayed in the API (and it appears logical to me to add the description there, consistent to @ApiModel at least (see #1228)
