### ISSUE TITLE
JSR-303 support: @NotNull ignored when @ApiModelProperty is present

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1231]
Version: 2.4.0

1.) @NotNull alone works:
@NotNull
private Date createTimestamp;

2.) @NotNull + @ApiModelProperty without required-Attribute:
@NotNull
@ApiModelProperty(value="Timestamp of creation")
private Date createTimestamp;

Now @NotNull is ignored, although the required-attribute is not set in @ApiModelProperty:
Here @NotNull should be picked up, because there is no indication of the required-attribute value.

3.) Invald combination: @NotNull + @ApiModelProperty with required-Attribute set to false
This combination is in fact invalid, maybe a warning could be logged that the not-null indicators are not consistent:
@NotNull
@ApiModelProperty(value="Timestamp of creation", required=false)
private Date createTimestamp;

**Comment by dilipkrish** [comment]
@jfiala this is working as designed. The plugins work in a particular order and layer information on top of each other.
- First the spring annotations have their say @RequestMapping, @RequestParam etc.
- Then the JSR-303 plugins have their say @NotNull etc.
- Lastly the swagger annotations that have the most specific information like description etc. 

These are enforced by the plugin ordering and priority. Also in this case the default value for the `@ApiModelProperty#required` is [`false`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiModelProperty.java#L80). Since they don't have a tri-state annotation value that can represent a not-specified value, there is no way for springfox to make that determination. That is why you see the behavior that you're seeing.

**Comment by jfiala** [comment]
I understand that this is the current behaviour.
However, as I would like to use JSR-303 only, it would be great to allow this. Currently I have to also add the required-attribute if  I add documentation, enforcing redundant input.

My suggestions are:
a) (Optionally) put the JSR-303 plugins at the end so they can overrule the others

b) The swagger-annotations should query if something is already determined as required. If this is the case, it should not mark it as non-required.
Because if something has already been marked as required, why should the Swagger annotations be allowed to overrule this?

**Comment by dilipkrish** [comment]
@jfiala This can be a little tricky. The reasons being sometimes we want `allowable values` from swagger annotations, sometimes we may want the range specified via a JSR-303 annotation. Don't know if its easy to make the ordering configurable. Let me know if you have any suggestions. 

The reason we picked swagger annotations last is that we want to use that as a case for overlaying mostly description information. 

Philosophically, as a library we want to discourage swagger annotations that are not material to the service description at runtime. For e.g. the jackson annotations should always trump or have more weight than `@ApiModelProperty` or for e.g. `@NotNull` or specifying `@RequestParam#required` should always win. Secondly we don't want plugins or builders to be interdependent or know past values. So we don't know if a consuming library is using the JSR plugins for e.g.

Based on those tenets, I'd love suggestions to improve this.

**Comment by jfiala** [comment]
Right now, the behaviour is even worse:
* @RequestParam() is by default required. As soon as I add @ApiParam, without specifying required, the parameter will be no longer required!
So in fact, the descriptive annotations only added to add descriptions change the behaviour in the api-docs!!
I had to add the required=true to the @ApiParam operations to get it working again.
As this also changes the parameter ordering, it is even worse.

I think it could be solved quite easily if every participant in the chain behaves "polite" to the others:
If one participant decides (for whatever reason), that an attribut is required, it MUST stay required.
This way, you don't add interdependencies or whatsoever, just simply check if it is already marked as required and if yes, leave it as is.

What do you think?

**Comment by dilipkrish** [comment]
I think you're right about the "polite" plugins. The solution I believe is to allow a fine grained voting mechanism for contentious properties like required. However that is an invasive change and not realistic for me to do it in the spare cycles that I have to maintain this project. 

So at the moment I'd leave that as a caveat/note/warning in the documentation that using certain swagger annotations ___would require consumers to do X___ as its not unreasonable for someone explicitly introducing a swagger annotation to take the trouble of setting properties that don't work well with defaults.

**Comment by jfiala** [comment]
What about changing the ApiParam/ApiModelProperty.required-attribute from boolean to Boolean.
This way you could distinguish between explicitly set to false or set to null?
Since the default is false, the result will change to true only if other attributes (like RequestParam) explicitly set to true, which is in fact a desired fix. So this should be less invasive to the existing codebases.

Another way would be to make the Api-annotations the first members in the chain, which are then overruled by others (@RequestParam/@NotNull).

**Comment by jfiala** [comment]
To sum things up:
Currently 
* Adding a description to a RequestParam will overrule its required-state:
@RequestParam(required: default true) is overruled by adding @ApiParam("my description") and changes the result required state to FALSE.
* Adding a description to an attribute will overrule the @NotNull-annotation required-state:
@NotNull (required=true) is overruled by @ApiModelProperty("my description") and changes the result required state to FALSE.

Both are non-intuitive for programmers, as adding documentation will change the required state of the property in the API-docs!

**Comment by jfiala** [comment]
It is easy possible to overrule the Spring Component Order by extending the existing component and setting a different @Order-value:

``` java
@Component
@Order(Ordered.LOWEST_PRECEDENCE)
public class OverridesModelNotNullAnnotationPlugin extends NotNullAnnotationPlugin{
}
```

This will overrule the @Order-value set in the NotNullAnnotationPlugin.java.
Using Ordered.LOWEST_PRECEDENCE, the plugin will always be executed as last member of the chain, thus being able to overrule other required-changers finally.

So in fact, the current behaviour can be overruled easily.
However, I still think the current behaviour should be changed anyway to "Boolean required" allowing to check for NULL-values.

**Comment by jfiala** [comment]
Regarding the current behaviour of @ApiParam overruling @RequestParam/@PathVariable-required, this is the fix-all-solution, which checks for @RequestParam, @PathVariable and then @NotNull to set required:

``` java 
@Component
@Order(BeanValidators.BEAN_VALIDATOR_PLUGIN_ORDER)
public class ParameterNotNullAnnotationPlugin implements ParameterBuilderPlugin {

	private static final Logger LOG = LoggerFactory
			.getLogger(ParameterNotNullAnnotationPlugin.class);

	@Override
	public boolean supports(DocumentationType delimiter) {
		// we simply support all documentationTypes!
		return true;
	}

	@Override
	public void apply(ParameterContext context) {

		Optional<RequestParam> requestParam = extractRequestParamAnnotation(context);

		if (requestParam.isPresent()) {
			RequestParam requestParamValue = requestParam.get();
			
			if(requestParamValue.required()==true) {
				LOG.info("@RequestParam.required=true: setting parameter as required");
				context.parameterBuilder().required(true);	
			}
			
		} else {
			Optional<PathVariable> pathVariableParam = extractPathVariableAnnotation(context);
			if (pathVariableParam.isPresent()) {
				LOG.info("@PathVariable present: setting parameter as required");
				context.parameterBuilder().required(true);
				
			} else {
				Optional<NotNull> notNull = extractAnnotation(context);

				if (notNull.isPresent()) {
					LOG.info("@NotNull present: setting parameter as required");
					context.parameterBuilder().required(true);
				} 
			}
			
		}
		
		
	}

	@VisibleForTesting
	Optional<NotNull> extractAnnotation(ParameterContext context) {
		return validatorFromField(context, NotNull.class);
	}
	
	@VisibleForTesting
	Optional<RequestParam> extractRequestParamAnnotation(ParameterContext context) {
		return validatorFromField(context, RequestParam.class);
	}

	@VisibleForTesting
	Optional<PathVariable> extractPathVariableAnnotation(ParameterContext context) {
		return validatorFromField(context, PathVariable.class);
	}


	public static <T extends Annotation> Optional<T> validatorFromField(
			ParameterContext context, Class<T> annotationType) {

		MethodParameter methodParam = context.methodParameter();
		
		T annotatedElement = methodParam.getParameterAnnotation(annotationType);
		Optional<T> annotationValue = Optional.absent();
		if (annotatedElement != null) {
			annotationValue = Optional.fromNullable(annotatedElement);
		}
		return annotationValue;
	}

}

```

**Comment by igor-sokolov** [comment]
Guys,

Sorry to chime in here. Maybe I missed something and not fully in the context but it seems to me that two sentences above 
> The reasons being sometimes we want allowable values from swagger annotations, sometimes we may want the range specified via a JSR-303 annotation. 

contradicts to the second idea:

> Philosophically, as a library we want to discourage swagger annotations that are not material to the service description at runtime. For e.g. the jackson annotations should always trump or have more weight than @ApiModelProperty or for e.g. @NotNull or specifying @RequestParam#required should always win. 

I tend to think that the second part is indeed correct. So can you please provide a couple of examples when you really want to have a different API definition but not the same as it defined through JSR-303 or Spring MVC annotations? I'm asking this because personally I think that the easiest and right fix for the root problem could be just to change plugin order, I mean to handle APiModelProperty firstly and then all other annotation plugins. Furthermore I guess the behavior when we document one restriction but in code through Bean validation annotation is defined another behavior might be quite dangerous. Don't you think so?

**Comment by dilipkrish** [comment]
@igor-sokolov your absolutely right about your observation. 

The reason that the swagger annotations are ordered last is because it's a tool to tweak the service description just-in-tim a manual override of sorts. So what I was implying by the _contradiction_ is just that some times you may have a situation where the jsr annotation cannot describe the situation completely or correctly.  In which case the swagger annotations are useful to provide the arbitration needed to render the spec correctly. 

The problem however is that default values in the annotations in certain cases interfere with this behavior. So the thought was that when swagger annotations are specified one must also specify values for the defaulted properties. 

I understand This can make things make things more verbose and leads to surprising behavior in some cases. So, here is what I think is the ideal solution in my opinion. 
- identify 'default' values in swagger annotations that don't play "politely" as @jfiala suggested; that are conflicting and group them into a swagger annotations impolite plugin order. Once those are identified the order should be. 
1. Spring annotations
2. Material swagger annotation values (those that affect runtime behavior) aka Impolite swagger annotation values
3. Jsr 303 plugins
4. Remaining swagger annotations I.e. Non-material values like description etc. 

hope that makes sense.

**Comment by MaksimOrlov** [comment]
Hi everyone.

May be some **option** should be added to Docket to configure behavior of the swagger annotation?

Some Boolean option that will be related to swagger annotations order.

So, the annotation's sequence could be configured for the needs of the each single project.

**Comment by cbornet** [comment]
@dilipkrish would it be possible to have a springfox annotation that would only consider the description (eg. ApiModelPropertyDescription) ?
So we could do something like:
```
@NotNull
@ApiModelPropertyDescription("Timestamp of creation")
private Date createTimestamp;
```

**Comment by dilipkrish** [comment]
There is a PR for that #1371 ... plan to clean it up and allow something like that.

**Comment by vlad2** [comment]
I don't get it... why was this closed? 
The behaviour described still happens, and the workarounds proposed by  @cbornet  or @MaksimOrlov  were not implemented.

**Comment by MaksimOrlov** [comment]
@vlad2, there is a new issue for that #2210 and described solution there.

**Comment by dilipkrish** [comment]
For future visitors. @cbornet suggestion has been implemented using standard spring annotations.

```java
@NotNull
@Description("Timestamp of creation")
private Date createTimestamp;
```

**Comment by MaksimOrlov** [comment]
I'm really sorry, maybe I'm not correctly understand, but

```
package org.springframework.context.annotation;

.....

@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Description {

	/**
	 * The textual description to associate with the bean definition.
	 */
	String value();

}
```

The `Target` is only **Method** or **Type** and I haven't managed to get it work, if I annotated getter/setter for the related **property**.

**Comment by dilipkrish** [comment]
Thanks for pointing that out yes I fixed the example above

**Comment by hrzrok** [comment]
I solved it like this.

@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 100)
public class SwaggerModelBuilderPlugin implements ModelPropertyBuilderPlugin {

	TypeResolver typeResolver = new TypeResolver();

	@Override
	public boolean supports(DocumentationType delimiter) {
		return DocumentationType.SWAGGER_2.equals(delimiter);
	}

	@Override
	public void apply(ModelPropertyContext context) {
		Optional<ApiModelProperty> annotation = Optional.absent();
		Optional<Annotation> requiredAnnotation = Optional.absent();

		if (context.getAnnotatedElement().isPresent()) {
			requiredAnnotation = requiredAnnotation.or(Optional.fromNullable(AnnotationUtils.findAnnotation(context.getAnnotatedElement().get(), NotBlank.class)));
			requiredAnnotation = requiredAnnotation.or(Optional.fromNullable(AnnotationUtils.findAnnotation(context.getAnnotatedElement().get(), NotNull.class)));
			requiredAnnotation = requiredAnnotation.or(Optional.fromNullable(AnnotationUtils.findAnnotation(context.getAnnotatedElement().get(), NotEmpty.class)));

			annotation = annotation.or(findApiModePropertyAnnotation(context.getAnnotatedElement().get()));
		}
		if (context.getBeanPropertyDefinition().isPresent()) {
			requiredAnnotation = requiredAnnotation.or(findPropertyAnnotation(context.getBeanPropertyDefinition().get(), NotBlank.class));
			requiredAnnotation = requiredAnnotation.or(findPropertyAnnotation(context.getBeanPropertyDefinition().get(), NotNull.class));
			requiredAnnotation = requiredAnnotation.or(findPropertyAnnotation(context.getBeanPropertyDefinition().get(), NotEmpty.class));

			annotation = annotation.or(findPropertyAnnotation(context.getBeanPropertyDefinition().get(), ApiModelProperty.class));
		}
		if (annotation.isPresent()) {
			context.getBuilder().required(annotation.transform(toIsRequired(requiredAnnotation.isPresent())).or(false));
		}
	}

	static Function<ApiModelProperty, Boolean> toIsRequired(boolean required) {
		return new Function<ApiModelProperty, Boolean>() {
			@Override
			public Boolean apply(ApiModelProperty annotation) {
				return required || annotation.required();
			}
		};
	}

}
