### ISSUE TITLE
Externalizing Descriptions of Api-Annotations (ApiModel/ApiModelProperty/...)

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1232]
Release: 2.4.0

I have a project where descriptions are reused in multiple places.
I think it would be nice to be able to only reference the documentation from the annotations, so it is not necessary to maintain in at several places.

Current solution:
@ApiModelProperty(value="The identifier ...")
private String identifier;

Reference solution:
@ApiModelProperty(descriptionKey="identifier")
private String identifier;

And have a properties file (or some other external source) for keeping the documentation:
identifier=The identifier....

This way it would be possible to keep all documentation in a central place.
What do you think?

**Comment by dilipkrish** [comment]
This is something that would benefit from using the extensibility. IMO it doesn't belong in the core library, I've added it as a `someday` feature in case someone wants to implement it

**Comment by jfiala** [comment]
Currently I solved this with a Constants-class and reference this throughout the application.

**Comment by jfiala** [comment]
Added a rough implementation (see ApiDescriptionPropertiesReader + associated plugins)

**Comment by jfiala** [comment]
Currently I used @Order(Ordered.LOWEST_PRECEDENCE) for the component order, as the plugin would otherwise be overruled by the current default Springfox plugins.
In case someone adds this to the component-scan, this is intended to work immediately without having to overrule it to add @Order(Ordered.LOWEST_PRECEDENCE).

**Comment by sac10nikam** [comment]
Hi Dilip,

I have created custom plugins and using it from project. The properties file having key-values is created. but I don't know how to call it from Swagger Controller.

1) 
**ControllerInterface- method**

**@ApiOperation(value = "get_contribution_api_name", notes = "get_contribution_api_notes", responseContainer = "List<Plan>")**
    **@DescriptorKey("get_contribution_api_notes")**
    @ApiResponses(value = { @ApiResponse(code = 200, message = "Success"),
            @ApiResponse(code = 400, message = "Bad Request", response = Response.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = Response.class),
            @ApiResponse(code = 403, message = "Forbidden", response = Response.class),
            @ApiResponse(code = 404, message = "Not Found", response = Response.class),
            @ApiResponse(code = 500, message = "Internal server error occured", response = Response.class) })
    @RequestMapping(value = URIConstants.PLAN_CONTRIBUTION, method = RequestMethod.GET)
    public Response<List<Plan>> **getContribution**(@PathVariable String employeeId,
            @PathVariable String company);

2) property reader class
@Service(value = "environmentConfig")
@Scope(value = "singleton")
@PropertySources
({
@PropertySource(value=**"classpath:/Project/swagger/api-plan-specs/src/resources/swagger-messages.properties**",ignoreResourceNotFound=true)
})
public class **EnvironmentConfig** {

    private static final Logger LOGGER = LoggerFactory.getLogger(EnvironmentConfig.class);
    @Autowired
    private Environment environment;
    private static Environment env;

    @PostConstruct
    public void init() {
        env = environment;
    }

    public static String getProperty(String key) {
        LOGGER.debug("Getting property  :" + key);
        return env.getProperty(key);
    }
}

3) Properties file
swagger-messages.properties

#Swagger errors
get_contribution_api_name=getContribution
get_contribution_api_notes=Gets the list of plan

4) plugins
![image](https://cloud.githubusercontent.com/assets/6522168/17772304/bb1ce6ac-6565-11e6-9b1a-71f614773fac.png)

5) Validators
![image](https://cloud.githubusercontent.com/assets/6522168/17772337/d70e50da-6565-11e6-8b39-9b4347f902a7.png)

Please guide me here. I want to show property values from resource bundle.

**Comment by dilipkrish** [comment]
Partially implemented in #1423
