### ISSUE TITLE
@ApiParam(hidden=true) does nothing

### ISSUE THREAD

**Issue by trifox** [springfox/springfox#1234]
When annotating a parameter with @ApiParam(hidden=true) it is displayed in the swagger output as if it wouldnt be there:

    public final ResponseEntity<BackendResponseTemplate<T>> readElements(
            @PathVariable String token,
            @ApiParam(hidden = true,required = false)
            @RequestParam Map<String, String> allRequestParams ) {...}

in that case i want to have all request params for additional filtering of the result, but it is by no means required and furthermore should be hidden in the swagger output completely

**Comment by dilipkrish** [comment]
@trifox why is marked as hidden then? You already have the `required=false`

**Comment by trifox** [comment]
i mean it is visible in the swagger output, "as if 'hidden=true' was not there " ;)

**Comment by hbprotoss** [comment]
@dilipkrish `hidden` still does nothing in version 2.5.0 :(

**Comment by dilipkrish** [comment]
@hbprotoss Could you open a new issue if its still not fixed?
