### ISSUE TITLE
swagger-ui not found deployed in Google Compute Engine.

### ISSUE THREAD

**Issue by kamleshg** [springfox/springfox#1235]
Swagger 2.2.2 version used on Spring 4.2.1 MVC webapp.

When i run locally, all is well. Problem is when i deploy to my cloud env. on GCE.

http://X.X.X.X/DataManagement/v2/api-docs returns valid json
but
http://X.X.X.X/DataManagement/swagger-ui.html returns 404 Not Found

Editor.swagger.io displays JSON fine, sans some unused definition warnings....

Any tips would be greatly appreciated!

**Comment by dilipkrish** [comment]
Please move to using 2.4.0. Is this a boot app? if not verify that you have registered the resource handlers

**Comment by kamleshg** [comment]
Its not SpringBoot. Its SpringMVC... here is my SwaggerConfig:

`@Configuration
@EnableSwagger2
@EnableWebMvc
public class SwaggerConfig extends WebMvcConfigurerAdapter{                                    
    @Bean
    public Docket api() {                
        return new Docket(DocumentationType.SWAGGER_2)          
          .select()
          .apis(RequestHandlerSelectors.any())
          .paths(PathSelectors.any())
          .build()
          .apiInfo(apiInfo());
    }
     
    private ApiInfo apiInfo() {
        ApiInfo apiInfo = new ApiInfo(
          "My REST API",
          "Some custom description of API.",
          "API TOS",
          "Terms of service",
          "myeaddress@company.com",
          "License of API",
          "API license URL");
        return apiInfo;
    }
    
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
          .addResourceLocations("classpath:/META-INF/resources/");
     
        registry.addResourceHandler("/webjars/**")
          .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}`

**Comment by kamleshg** [comment]
DO i need to have swagger.properties to point to base url?

**Comment by kamleshg** [comment]
Any other ideas on how to solve my issue?
Is swagger.properties still required?

Regards,
Kamlesh Gokal

**Comment by dilipkrish** [comment]
Im not familiar with google compute engine. :disappointed: You do not need swagger.properties. Whats is prompting you for the properties file?

**Comment by kamleshg** [comment]
Nothing I'm just looking at other tutorials that mention it. 

Regards,
Kamlesh Gokal

**Comment by dilipkrish** [comment]
Have you seen the [official documentation](http://springfox.iol)?

**Comment by kamleshg** [comment]
Yup, line for line... was just looking at other tutorials 
Does SpringFox use $CATALINA_HOME or $CATALINA_BASE?

Google Compute Engine uses both of them...

**Comment by dilipkrish** [comment]
No it does not.
