### ISSUE TITLE
@Api.authorizations don't seem to work 

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1237]
Version: 2.4.0

@Api(..., authorizations=...)
doesn't work for all methods of the controller class.

I have to add it to all operations of the controller class manually:
@ApiOperation(..., authorizations=...)

It would be great if the definition at the controller-class would be working.
Or is it even possible to add it at the Docket for all operations in the Docket?

**Comment by dilipkrish** [comment]
@jfiala thats what the [security context](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) (see no. 17) does.

**Comment by jfiala** [comment]
Perfect, works greatly, thank you for the hint!
However the attribute "authorizations" (@Api(...., authorizations=...) ) should probably be deprecated/removed for clarity.

**Comment by dilipkrish** [comment]
@jfiala we don't own/control those annotations. They re part of the swagger-core that we're just using to stay DRY

**Comment by jfiala** [comment]
OK thanks, so they have to stay as they are....
Maybe it should be commented in the docs that the authorizations are not picked up by Springfox?
