### ISSUE TITLE
Swagger UI showing incorrect URLs

### ISSUE THREAD

**Issue by martin3361** [springfox/springfox#1238]
just like the question has been asked [here](http://stackoverflow.com/questions/36198827/how-to-change-basepath-for-swagger-2-0-via-annotations)

I'm running a service, where Swagger UI is accessible at:

> http://serviceURL/swagger-ui.html

However, it is behind a proxy, such as:

> http://proxyURL/serviceName

Generated URLs by Swagger UI are looking like:

> http://proxyURL/

instead of the actual URL with the serviceName as suffix. As far as I get it, this means manipulating the basePath property. As per documentation:

A swagger API documentation can no longer describe operations on different base paths. In 1.2 and earlier, each resource could have had a separate basePath. In 2.0, the basePath equivalents (schemes+host+basePath) are defined for the whole specification.

@Api(basePath) is deprecated, and it doesn't say what to use and how to use it. How to make the paths generated by Swagger appear properly?

I'm using Spring Boot, Springfox Swagger 2.4.0 and annotations.

**Comment by dilipkrish** [comment]
I think this issue is probably fixed via https://github.com/springfox/springfox/pull/1217

**Comment by dilipkrish** [comment]
@martin3361 would be good if you can confirm its fixed using 2.4.1-SNAPSHOT

**Comment by dilipkrish** [comment]
Closing this as fixed in 2.5.0. please reopen if its not fixed
