### ISSUE TITLE
Renaming of title "Model Schema" to "Example Value"

### ISSUE THREAD

**Issue by Hronom** [springfox/springfox#1243]
Hello,
I need to change `Model Schema` to `Example Value` like in [Swagger example](http://petstore.swagger.io/#/):
![swagger example value](https://cloud.githubusercontent.com/assets/429993/14111979/8da5b12c-f5d5-11e5-9ffa-7b7a43c61220.png)
How I can do this?
Thnx.

**Comment by dilipkrish** [comment]
You can use the @ApiModelProperty#example annotation to get those values to show I believe. Tho' that is really a swagger-ui question.

**Comment by Hronom** [comment]
@dilipkrish We already use `@ApiModelProperty#example` and we see example but on tab `Model Schema` not on tab `Example Value`.

I don't familiar how swagger-ui communicate with Springfox, so from my point, maybe Springfox must do some additional moves to get this work?
