### ISSUE TITLE
@ApiParam - Allowable values not displayed in Swagger API docs

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1244]
Version 2.4.0

If e.g. @ApiParam(allowableValues="range[1, 11]") is set, it is never displayed in the API docs (minLength=1, maxLength=11).
It doesn't work directly for a Request parameter:

``` java
@RequestParam @ApiParam(value="description", allowableValues="range[1, 11]") String sample;
``` 

It also doesn't work if the parameter is declared using @ModelAttribute.

For @ApiModelProperty it works as desired:
``` java
@ApiModelProperty(value="description", allowableValues="range[1, 11]")
```
=> will display minLength=1, maxLength=11.

Can you pls check why this is missing for @ApiParam?

**Comment by jfiala** [comment]
In fact, this also affects other ParameterBuilderPlugin / ExpandedParameterBuilderPlugin who also set allowableValues, but it never shows up in the API docs.

**Comment by jfiala** [comment]
This had to be fixed in springfox.documentation.swagger2.mappers.EnumMapper, there was only support for AllowableListValues implemented. Added AllowableRangeValues.

**Comment by dilipkrish** [comment]
- Need to [add range as well here](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/SerializableParameterFactories.java#L69)

**Comment by johnsonlegend** [comment]
tested version 2.8.0 and 2.9.2, looks like it's not working as expected

**Comment by hiejulia** [comment]
Is it fixed yet ? Same problem happened with `swagger-jersey2-jaxrs`.

**Comment by dilipkrish** [comment]
Yes it should be. Please move to 3.0.0. Also `swagger-jersey2-jaxrs` is not part of this project.
