### ISSUE TITLE
Problem with boot-swagger demo example

### ISSUE THREAD

**Issue by gosiaw** [springfox/springfox#1247]
Hi,
I have downloaded demos from https://github.com/springfox/springfox-demos
I am particularly interested in demo:
https://github.com/springfox/springfox-demos/tree/master/boot-swagger

I followed all the instructions and started the demo, but I can see only a blank page when I access:
Swagger UI endpoint: http://localhost:8080/springfox/swagger-ui.html
Swagger docs endpoint: http://localhost:8080/springfox/v2/api-docs

On page http://localhost:8080/springfox/swagger-resources I can see the following:
[{"name":"category-api","location":"/api-docs?group=category-api","swaggerVersion":"1.2"},{"name":"full-petstore-api","location":"/api-docs?group=full-petstore-api","swaggerVersion":"1.2"},{"name":"multipart-api","location":"/api-docs?group=multipart-api","swaggerVersion":"1.2"},{"name":"user-api","location":"/api-docs?group=user-api","swaggerVersion":"1.2"},{"name":"category-api","location":"/v2/api-docs?group=category-api","swaggerVersion":"2.0"},{"name":"full-petstore-api","location":"/v2/api-docs?group=full-petstore-api","swaggerVersion":"2.0"},{"name":"multipart-api","location":"/v2/api-docs?group=multipart-api","swaggerVersion":"2.0"},{"name":"user-api","location":"/v2/api-docs?group=user-api","swaggerVersion":"2.0"}]

I also tried to use example spring-java-swagger and it worked.

Am I doing anything wrong?

Regards,
Gosia

**Comment by dilipkrish** [comment]
Added the `?group=<docket-name>` e.g. `?group=category-api`
