### ISSUE TITLE
Question: Any way of providing the swagger base url

### ISSUE THREAD

**Issue by anthofo** [springfox/springfox#1248]
All my paths are prefixed by `"/v2"` : 
`"/v2/foo"`
`"/v2/bar"`

And the base url is `"/"`

I would like to set the base url on` "/v2"` so that the paths can be displayed without that prefix : 
`"/foo"`
`"/bar"`

I didn't find a way to do that

**Comment by dilipkrish** [comment]
Check [this section](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints)

**Comment by anthofo** [comment]
I don't want to customize the location on my swagger doc, but set the `basePath` of my api in the generated json.
My paths are under /v2 just like swagger, but they could have been under /v3 or other.

**Comment by smwurster** [comment]
@anthofo, can you solve this via the `pathProvider` option on `Docket`?

**Comment by anthofo** [comment]
@smwurster no, if I do that to set the basePath as "/v2" all my path are doubled prefixed by "/v2/v2"
