### ISSUE TITLE
Bug: Templated url are submited with the template part

### ISSUE THREAD

**Issue by anthofo** [springfox/springfox#1249]
Given the following endpoint : 
```
http://localhost:8080/v2/foo{?size,page}
```

The called url is : 
```
curl -X GET --header 'Accept: application/json' 'http://localhost:8080/v2/foo{?size,page}'
```
Which is invalid, it should be the url without the optional template part.

**Comment by dilipkrish** [comment]
Thanks for reporting that.

**Comment by dilipkrish** [comment]
Fixed via [springfox-swagger-ui-rfc6570 0.9.7-SNAPSHOT](https://github.com/springfox/springfox-swagger-ui-rfc6570/commit/2841b4fdeb685bbf7c4c19329157fe198741e713). 

Will still need to release 0.9.7 but would be great to get your feedback on the snapshot build

**Comment by bobwenx** [comment]
When is springfox-swagger-ui-rfc6570 0.9.7 Released?

**Comment by dilipkrish** [comment]
Would you be able to build a snapshot and try it out? Don't want to release it without feedback

**Comment by bobwenx** [comment]
i already tried and the snapshot work fine, 
origin template url: `/das/v1.0/mysql/cluster{?userId,domainId}`,
with the snapshot swagger-ui, generated curl script:
`curl -X GET --header 'Accept: application/json' 'http://10.125.0.179:8080/mc-server/das/v1.0/mysql/cluster?userId=11&domainId=5e28e320-0ca2-11e3-8761-1ee9d37cf1ab'`

However, i found the spec editor still generate java client code with template part.

**Comment by dilipkrish** [comment]
> However, i found the spec editor still generate java client code with template part.

What does that mean? example?

**Comment by bobwenx** [comment]
i mean the `swagger editor`(http://editor.swagger.io/#/) still show url with template part and generate wrong client code.

![image](https://cloud.githubusercontent.com/assets/2533748/16290650/d23bcf02-3931-11e6-8a3f-8d211b4f9540.png)

i see it has nothing to do with springfox.

**Comment by FrostbittenKing** [comment]
Except this is not fixed. Still same bug in 1.0.0. Maybe this was fixed in 0.9.7, but it is not in 1.0.0. :(.

**Comment by prulloac** [comment]
same thing still happens in version 2.8.0

**Comment by dilipkrish** [comment]
I really doubt this is a bug @FrostbittenKing it is most likely because you may need to refresh your browser cache.

@prulloac version 2.8.0 of what? If you mean swagger-ui then you need to turn off `enableUrlTemplating`. Swagger ui does not natively support rfc6570.

**Comment by power721** [comment]
springfox-swagger-ui 2.9.0 doesn't work.
curl -X GET "http://localhost:8080/users{?offset%2CpageNumber%2CpageSize%7D=" -H "accept: */*"

springfox-swagger-ui-rfc6570 1.0.0 works, but oauth2 doesn't work and old style.

**Comment by dilipkrish** [comment]
@power721 if you want oauth2 and newer UI you need to turn off the experimental feature `enableUrlTemplating(false)`
