### ISSUE TITLE
Allow reusable enumerations in parameters/models

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1250]
Version: 2.4.0

For enumerations:
``` java
public enum MyEnum {
	Value1, Value2;
}
```
	
``` java
private MyEnum myvalue;
```

the API-docs are currently rendered as a enum to the parameter/attribute:
```
"myvalue":{"type":"string","enum":["Value1","Value2"]}
``` 

When generating client code using Swagger-codegen (Java), the Enumeration is generated as inner class:
```java
public class MyObject   {

public enum MyEnum {
    VALUE1("Value1"),
    VALUE2("Value2");

    private String value;

    MyEnum (String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return value;
    }
  }

}
``` 
If you have multiple variables of type MyEnum in different classes, this leads to the fact, that the enumeration is contained as inner classes in every class where it is used (and who don't know each other/have no common parent or reference).

It would be much better to have a reference to the enumeration, so the client code can generate a separate class for the Enumeration (same as done in the API model classes).

According to the OpenAPI-spec, this should be possible using a reference to a Set/List of type String and the enumeration of the possible values:
https://github.com/OAI/OpenAPI-Specification/issues/300

I think this would be the more clean way of rendering the enumerations.

**Comment by dilipkrish** [comment]
This is really a swagger-code-gen issue I believe. AFAIK this is not supported in swagger 2.0

**Comment by jfiala** [comment]
This should be possible with Swagger 2.0 using a reference to a List of type string with the enum values listed, pls see the example at 
https://github.com/OAI/OpenAPI-Specification/issues/300#issuecomment-77669429

**Comment by Kjens93** [comment]
This is a duplicate of #1738, but neither of these issues are an issue with swagger-codegen. Springfox should be writing first-class enums to the definitions section of the generated spec and referencing them using `$ref` where they are used, not writing them as inline enums.

**Comment by dilipkrish** [comment]
@Kjens93 While I understand [this](https://github.com/springfox/springfox/issues/1738#issuecomment-353333556) is the reason this is not a simple change.

**Comment by fzyzcjy** [comment]
Hi is there any updates (after 3 years?) This is very useful!
