### ISSUE TITLE
Question: reusing complex swagger annotation

### ISSUE THREAD

**Issue by blinse** [springfox/springfox#1251]
First of all, thanks for the great tool (spring-fox)!

Is there a way of reusing a complex springfox annotation on multiple methods without copy and pasting?

My question is described in more detail here: http://stackoverflow.com/questions/36475452/reuse-complex-spring-fox-swagger-annotation

I am using springfox-swagger2, version 2.2.2 .

Thanks in advance.

**Comment by dilipkrish** [comment]
@blinse in 2.4.0 you can [add additional operation parameters via the docket](http://stackoverflow.com/a/36481473/19219).

**Comment by blinse** [comment]
great that works.
