### ISSUE TITLE
BeanPropertyDefinitions not compatible with Jackson 2.7.x

### ISSUE THREAD

**Issue by Stephan202** [springfox/springfox#1253]
We use Springfox in a project that we'd like to upgrade from Jackson 2.6.x to 2.7.x. However, `BeanPropertyDefinitions` is indirectly used and this class is not compatible with Jackson 2.7.x, due to a change to the `POJOPropertyBuilder` constructors.

The issue can easily be reproduced by building Springfox with the following change:
```diff
diff --git a/gradle/dependencies.gradle b/gradle/dependencies.gradle
index bf13446..cc3bf8f 100644
--- a/gradle/dependencies.gradle
+++ b/gradle/dependencies.gradle
@@ -3,7 +3,7 @@ ext {
   classmate = "1.3.1"
   groovy = "2.4.5"
   guava = "18.0"
-  jackson = '2.6.4'
+  jackson = '2.7.3'
   joda = "2.9.1"
   jsonPath = "2.1.0"
   mockito = "1.10.19"
```

The build then fails as follows:
```
.../springfox/springfox-schema/src/main/java/springfox/documentation/schema/property/BeanPropertyDefinitions.java:70: error: no suitable constructor found for POJOPropertyBuilder(PropertyName,AnnotationIntrospector,boolean)
            = new POJOPropertyBuilder(new PropertyName(beanProperty.getName()),  annotationIntrospector,  true);
              ^
    constructor POJOPropertyBuilder.POJOPropertyBuilder(POJOPropertyBuilder,PropertyName) is not applicable
      (actual and formal argument lists differ in length)
    constructor POJOPropertyBuilder.POJOPropertyBuilder(MapperConfig<?>,AnnotationIntrospector,boolean,PropertyName,PropertyName) is not applicable
      (actual and formal argument lists differ in length)
    constructor POJOPropertyBuilder.POJOPropertyBuilder(MapperConfig<?>,AnnotationIntrospector,boolean,PropertyName) is not applicable
      (actual and formal argument lists differ in length)
```

Are there plans to make Springfox compatible with the latest version of Jackson?

**Comment by dilipkrish** [comment]
2.7 jackson has been a terrible release causing quite a few breaking changes. Since were [tracking springs dependencies](https://spring.io/blog/2016/04/06/spring-framework-4-3-goes-rc1, really trailing by one release, just to ensure compatibility It might not be until 4.4 spring is released. Really the upgrade to jackson dependencies have been pretty seamless up until now, so we want to error on the side of caution and uprev the dependency in lockstep with projects like spring-data, spring-hateoas etc.

**Comment by Stephan202** [comment]
@dilipkrish, thanks a lot for this. The change seems to work well!

One little snag: on large projects with Jackson 2.7 the log statement statement at `PojoPropertyBuilderFactory.java:98` produces a _lot_ of ERROR log messages with lengthy stacktraces. We can suppress these on our side, of course, but arguably the message should be DEBUG level, rather than ERROR. WDYT?

**Comment by dilipkrish** [comment]
@Stephan202 thats an oversight. I'll fix that
