### ISSUE TITLE
Question: Make it easier to checkout & build & contribute

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1255]
Current obstacles:
- [x] Generated sources are missing
>>> Use gradle generateMappers if connecting directly to the swagger-springfox projects; the recommended approach is to publish to a local maven repo (see bottom)
- [x] Troubles with the Logger (Logback vs. slf4j)
>>> Only exists when connecting directly to the swagger-springfox projects
- [x] Deploy gradle artificats into maven repository (for reuse with maven-based projects) (/)
>>> see replies at the bottom
- [x]  Default IDE is idea: Eclipse will be added by @dilipkrish to the gradle buildfile

###  Generated sources are missing
Currently, after checkout & build using gradle, it is not possible to start the springfox modules with the springfox demos, because the generated sources are missing completely.
(see my comment at #1088 regarding ServiceModelToSwagger2MapperImpl).
One has to find out that the ServiceModelToSwagger2MapperImpl has to be generated & the generated-src/main folder has to be added to the buildpath in order to use the Springfox libraries.

So it would be nice if the generateSrc target is also added to the build.gradle build options.
The sources should be generated & added to the buildpath automatically.
Then it would be possible to checkout & build and immediately reuse the sources with the springfox-demos (for analyzing/contribution).

### Troubles with the Logger (Logback vs. slf4j)
I couldn't start my project connected to the Springfox-sources due to troubles with multiple loggers.
After removing all dependencies in the Springfox-modules to logback manually, I was able to start the Spring Boot server eventually.

Log output after cleaning up:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/c:/mymavenrepo/ch/qos/logback/logback-classic/1.1.5/logback-classic-1.1.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/MyUser/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.13/8f0d8b5bf0ff295162360a0a5ebb9c945bd2b685/slf4j-simple-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

### Deploy gradle artificats into maven repository
It would be nice to give hints how to deploy the gradle artifacts into a maven-repository, so they can be reused easily in maven-based projects (for now I added the springfox-modules directly as referenced projects).

### Default-IDE is idea
Maybe it would make sense to use a non-commercial IDE as default (i.e. eclipse)

**Comment by dilipkrish** [comment]
@jfiala Sorry Ive been  a lil busy.

> Currently, after checkout & build using gradle, it is not possible to start the springfox modules with the springfox demos, because the generated sources are missing completely.

This doesn't seem right. Everything should build just fine o/w the CI builds would be failing. Are you perhaps referring to IDE specific issues?

> So it would be nice if the generateSrc target is also added to the build.gradle build options.
The sources should be generated & added to the buildpath automatically.

This is exactly what [this does](https://github.com/springfox/springfox/blob/master/gradle/mapstruct.gradle). Now this could be improved perhaps.

> It would be nice to give hints how to deploy the gradle artifacts into a maven-repository, so they can be reused easily in maven-based projects (for now I added the springfox-modules directly as referenced projects).

I'll add notes on how to do that. Basically you'd need to run, to publish to you local maven 

```bash
    ./gradlew clean build publishToMavenLocal
```

> Maybe it would make sense to use a non-commercial IDE as default (i.e. eclipse)

👍 for that. Only that I don't use Eclipse and don't have the time to invest in figuring out or supporting eclipse configurations. Would applying the eclipse plugin work? Would be great if you could perhaps chip in.

**Comment by jfiala** [comment]
> This doesn't seem right. Everything should build just fine o/w the CI builds would be failing. Are you perhaps referring to IDE specific issues?
I can start the Springfox demos (directly connected to the Springfox sources) only if I run gradle generateMappers. If I don't do so, I'm missing the generated sources (and get "No qualifying bean of type [springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper]").

>This is exactly what this does. Now this could be improved perhaps.
Yes, but generateMappers is not part of the default build (running simply gradle with no tasks specified)

>Would applying the eclipse plugin work? 
I'm using Eclipse and all I had to do so far was adding "apply plugin: 'eclipse'" to the subprojects root build.gradle file:
```
subprojects {
  apply plugin: "com.ofg.uptodate"
  //Not strictly groovy projects but useful for the IDE to recognise groovy test sources
  apply plugin: 'groovy' //gradle groovy plugin extends the java plugin
  apply plugin: 'com.github.adrianbk.jvmsrc'
  apply plugin: 'checkstyle'
// this is all to get eclipse to work
apply plugin: 'eclipse'
```
Then I run "gradle eclipse" and the eclipse specific project files are generated correctly (.project, .classpath).

**Comment by dilipkrish** [comment]
Not sure I follow your comment about the springfox demos. Your workflow should be to build springfox locally and use the SNAPSHOT published to your maven local repo as a dependency. i.e.

1. Build springfox `./gradlew clean build publishToMavenLocal`
2. update the springfox-demos to use the [snapshot version](https://github.com/springfox/springfox-demos/blob/master/gradle/dependencies.gradle#L4) in this case currently it is `2.4.1-SNAPSHOT`
3. Build demos using `./gradlew clean build`

There is no *default* gradle task. Just like in maven you need to run `mvn clean install` in gradle you need to run `./gradle clean build`

I'll add eclipse plugin to the projects so that its easier and update these instructions in the documentation. Thanks for that feedback! 👍

**Comment by jfiala** [comment]
Great thank you, the problem only exists if I'm connecting directly to the swagger-springfox projects, and using generateMappers it's easy to fix that. So all tasks except the eclipse plugin are resolved.

**Comment by dilipkrish** [comment]
The last point [has been addressed](https://github.com/springfox/springfox/blob/master/gradle/ide.gradle#L3) as well
