### ISSUE TITLE
Empty Model Schema in Swagger UI

### ISSUE THREAD

**Issue by kabennett** [springfox/springfox#1261]
In the Swagger UI, I see the name of the class under Model in the Parameters section (e.g., IntraAccountActivityResponse {}), but the Model Schema is empty. I have a HelloWorld example that works perfectly using the lastest springfox-swagger2 and springfox-ui dependencies (2.4.0), but when I'm trying to do the same thing in my real project, I get the empty Model Schema.

In addition to springfox 2.4.0, I am using Spring Cloud Brixton.RC1 release and all of its dependencies, including Feign, Ribbon, etc.  I've gone down the path of reading the springfox documentation to see if there were any possible solutions that might address this issue, and I tried adding the following code to no avail.

```
	@Bean
	public WebMvcConfigurerAdapter webMvcConfigurerAdapter() {
		return new WebMvcConfigurerAdapter() {
			@Override
		    public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
		        ObjectMapper objectMapper = null;
		        for (HttpMessageConverter converter : converters) {
		            if (converter instanceof MappingJackson2HttpMessageConverter) {
		                MappingJackson2HttpMessageConverter jacksonConverter =
		                        ((MappingJackson2HttpMessageConverter) converter);

		                if (objectMapper == null) {
		                    objectMapper = jacksonConverter.getObjectMapper();
		                } else {
		                    jacksonConverter.setObjectMapper(objectMapper);
		                }
		            }
		        }
		    }
		};
	}
```

**Comment by dilipkrish** [comment]
This is a know issue that has [a fix in the works](https://github.com/springfox/springfox/pull/1239)
