### ISSUE TITLE
Groups support in Swagger UI URLs

### ISSUE THREAD

**Issue by alex-konkov** [springfox/springfox#1262]
If one group is used, it's possible to copy and paste a link to certain API resource, which is very convenient feature for devs collaboration.

E.g.
http://localhost:8080/swagger-ui.html#/some-resource

However, if there are several API groups, the interested resource is not found and the whole idea of auto expanding doesn't work at all.

**Proposed solution:** include group into URL and automatically switch to the right group before scrolling to the target resource from this group.

**Comment by dilipkrish** [comment]
@alex-konkov I thought it already did that. If not this is a great idea for [swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by alex-konkov** [comment]
Is the feature implemented?

**Comment by dilipkrish** [comment]
This would be a feature for the swagger-ui team to implement.

**Comment by alex-konkov** [comment]
Would it be possible if you file the feature request? I just have not enough understanding which project addresses what, so it has technical wording they can get right. Thanks a lot in advance.

**Comment by alex-konkov** [comment]
springfox.js script seems to have groups populating code, so it seems this is the right project to request the feature
