### ISSUE TITLE
Change app context path to add a version

### ISSUE THREAD

**Issue by rzilist** [springfox/springfox#1266]
Hi Springfox experts,

I've looked over the issues, but didn't find the answer, hence creating new post. 

We have springfox/swagger2.2.2 webapp which has the app name as a context path: `/federated-api`. We access it by going to index html which links schema docs and swagger ui page. Swagger  page lists our rest controllers which use `@RequestMapping` annotation with /v1 in front, ie: `@RequestMapping(value = "/v1/roundtrip/sample", method = RequestMethod.GET, produces = "application/json")`. Controllers are accessed like this: domain/federated-api/v1/roundtrip/sample

We have a standard SpringBootApplication class:
```
@SpringBootApplication
@EnableSwagger2
..................................................
other stuff

@Bean
    public Docket fedApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                        .select()
                        // .apis(RequestHandlerSelectors.any())
                        .paths(PathSelectors.regex("/v1/.*"))
                        .build()
                        //.pathMapping("/federated-api/v1/")
                        // .directModelSubstitute(LocalDate.class,
                        // String.class)
                        // .genericModelSubstitutes(ResponseEntity.class)
                        /*
                         * .alternateTypeRules(
                         * newRule(typeResolver.resolve(DeferredResult.class,
                         * typeResolver.resolve(ResponseEntity.class, WildcardType.class)),
                         * typeResolver.resolve(WildcardType.class)))
                         */
                        .useDefaultResponseMessages(false)
                        /*
                         * .globalResponseMessage(RequestMethod.GET,
                         * newArrayList(new ResponseMessageBuilder()
                         * .code(500)
                         * .message("500 message")
                         * .responseModel(new ModelRef("Error"))
                         * .build()))
                         */
                        .securitySchemes(Arrays.asList(apiKey()))
                        .securityContexts(Arrays.asList(securityContext()))
                        .enableUrlTemplating(true)
                        ..................................................................................
                        other stuff

    }
```
Our gateway  (API Garden) has added version (v1) to the end of their proxy base paths. As a result, we would need to change our app context path from /federated-api to /federated-api/v1 to match. 

What would be the easiest way to do it? Currently, we can't even serve index.html under new context path.

Thanks in advance, Roman

**Comment by dilipkrish** [comment]
@rzilist Its not clear to me what the problem is, so let me restate...

- You have an app that has the context path defined @ `/federated-api` and you have request mappings that are defined like this `@RequestMapping("/v1/some-controller")`.
- You have a proxy thats fronting your app @ `/domain/federated-api/v1`

Its this correct?

What is the expectation from a client that talks to the proxy in terms of url coordinates?

**Comment by rzilist** [comment]
@dilipkrish: Thanks for looking

- the app by default has context path `/federated-api` and each controller has an end point annotated with `@RequestMapping("/v1/some-controller/some-endpoint")`
- the proxy which calls our app looks like `/domain/federated-api/v1`
- the client calls our app via proxy service `https://domain/federated-api/v1`; proxy service then forwards the request to our app via base path `/federated-api/v1` which our app cannot currently handle
- I think I need to do a few things in order for this to work:

1. Change the app context path to match the proxy (add v1 to the end)
2. Change swagger page to load all the controllers
3. Change each controller end point to remove `/v1`
4. Change Docket in SpringBootApplication class to allow for `/federated-api/v1`

let me know if that makes sense 
Thanks, Roman

**Comment by dilipkrish** [comment]
@rzilist I don't think that the app should change its context path to match the proxy. The proxy should do the translation from `/domain/*` => `/*`. If you think about it, your app should work in multiple contexts, first and foremost, your local machine. Secondly, your dev/test environments and lastly should be able to work with the proxy. All of these capabilities cannot be translated easily by this library, without really knowing specifics.
