### ISSUE TITLE
Using complex objects as request GET parametes

### ISSUE THREAD

**Issue by ramonchu** [springfox/springfox#1267]
Hi, I'm newbie using springfox, sorry if I ask something stupid, but I have two questions:

1. Why swagger_ui.html puts '{?...}' into url? Example: "/api/company/access{?auth,companyId}", and

2. If "auth" is a pojo object with _username_ and _hash_ attributes as Strings with getters and setters. How can I get parameters like auth_username or authUsernane in swagger ui? I tried with @ModelAttribute and @ApiModel into controller argument, but doesn't works.

Thanks!

**Comment by dilipkrish** [comment]
> Why swagger_ui.html puts '{?...}' into url? Example: "/api/company/access{?auth,companyId}", and

You're seeing this url template because you've enabled url tempting in your docket. Set it to false and that will go away.

> If "auth" is a pojo object with username and hash attributes as Strings with getters and setters. How can I get parameters like auth_username or authUsernane in swagger ui? 

You'd need to create getters and setters with that name
