### ISSUE TITLE
How to set global default parameter type and httpMethod in @ApiOperation?

### ISSUE THREAD

**Issue by MonKong** [springfox/springfox#1270]
![image](https://cloud.githubusercontent.com/assets/10125679/14636516/86fa420e-065e-11e6-9467-9c90dd802760.png)
For simplify code , I hope parameter be parsed as `query` type by default without any extract annotation,because it's a common situation.

It's the best if can be the same with POJO as parameter.

> @RequestMapping(value = "/test1")
> 	public String test1(String str)  {
>        return "xx"
> }

And how to set `@ApiOperation`'s attribute  `httpMethod = "GET"` by default ?

...and can remove `Response Messages` content? Because I don't need it in my project.
I use Maven POM to import Swagger-UI.
![image](https://cloud.githubusercontent.com/assets/10125679/14637715/b082089e-0665-11e6-81f6-a6f58fb0ed4e.png)

**Comment by dilipkrish** [comment]
Please [see the docs](http://springfox.github.io/springfox/docs/current/) on how to disable global response messages.

I'll have to look into your suggestion about using query param by default.

**Comment by MonKong** [comment]
@dilipkrish  If I haven't set httpMethod attribute, Swagger UI will list all the method with the same API.
![image](https://cloud.githubusercontent.com/assets/10125679/14694279/67fd567a-0799-11e6-9bf7-793f96f40ddb.png)


So,how to set default value,so that I don't have to set it in every API in Java method. 
I think that maybe about the concept of "Convention Over Configuration" that can simplify lot of codes.
> @RequestMapping(value = "/test1")
> public String test1(String str) {
> return "xx"
> }

**Comment by dilipkrish** [comment]
This is the default behavior or spring-mvc. If you need to disable the other http methods you'd need to make the method explicit
