### ISSUE TITLE
@ResponseHeader description not generated in apidocs

### ISSUE THREAD

**Issue by basvanstratum** [springfox/springfox#1271]
After seeing that the new 2.4.0 version supports @ResponseHeaders (#937) in generated json I went and updated my libraries and code. However using the example given in #937 I am not seeing the description element in the output.

```
@ApiResponse(code = 201, message = "Resource created.",
    responseHeaders = {
        @ResponseHeader(name = "ETag", 
              description = "The version id of the newly created resource", 
              response = String.class)})
```

Results in:

```
"responses": {
    "201": {
        "description": "Resource created.",
        "headers": {
            "ETag": {
                "type": "string"
                }
```

Instead of:

```
"responses": {
    "201": {
        "description": "Resource created.",
        "headers": {
            "ETag": {
                "type": "string",
                "description": "The version id of the newly created resource."
                }
```

I hope I'm doing something wrong, otherwise I guess this is a bug or shortcoming in the introduced feature.

A minor annoyance is that I also have to add `response = String.class` to every header because the default is `Void.class` and that appears to be skipped during generation, looking at the `ResponseHeaders` class. Perhaps String shouldn't be the default, but having an annotation skipped due to a missing `response` property seems undesirable to me.

**Comment by dilipkrish** [comment]
Yeah the description is not getting used. Perhaps its a later addition to the annotation and wasn't available at the time the plugin was written. Would be great to get a PR to fix this.
