### ISSUE TITLE
Display @ExtensionProperty on the swagger-ui.html

### ISSUE THREAD

**Issue by mibeumer** [springfox/springfox#1272]
Release: 2.4.0

Swagger-Core has the @ExtensionProperty annotation. It would be nice if these would be visible on the swagger-ui.html.

Is there a configuration to make them visible or can we provide a function to make the additional properties visible?

Kind Regards
mibeumer

**Comment by dilipkrish** [comment]
This is not related to this project. That would be a feature request for [swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by mibeumer** [comment]
Okay, sorry.
I opened an Issue there: https://github.com/swagger-api/swagger-ui/issues/2110

Regards
mibeumer
