### ISSUE TITLE
how to get document for param in post body

### ISSUE THREAD

**Issue by catinred2** [springfox/springfox#1273]
I have create a test repo in https://github.com/catinred2/swagger_test
springfox version:2.4.0
```java
@RequestMapping(value = "/hello/world", method = { RequestMethod.POST })
	@ResponseBody
	@ApiOperation(value="Notes",response = GetInfoResult.class)
	public void getInfo() throws Exception {
		GetInfoParam param = readParamByBody(GetInfoParam.class);
		GetInfoResult result = new GetInfoResult();
		result.setText(param.getId().toString());
		writeValue(result);
	}
```
How to generate GetInfoParam document in api-docs ?

**Comment by dilipkrish** [comment]
The easiest way to allow spring mvc to do the model binding/ message conversion

```java
    @RequestMapping(value = "/hello/world", method = { RequestMethod.POST })
    @ResponseBody
    public GetInfoResult getInfo(GetInfoParam input) throws Exception { //<-- like this
```

**Comment by catinred2** [comment]
@dilipkrish it does not work for me. Exception would occur that says  **com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input**
Apparently readParamByBody can not get any data.
I've update my test repo to reproduce.

**Comment by catinred2** [comment]
BTW  would the Model GetInfoParam property detail included in swagger document in version 2.5.0 ?

**Comment by dilipkrish** [comment]
You already have the [input](https://github.com/catinred2/swagger_test/blob/master/src/main/java/com/test/action/TestAction.java#L29) value. Not sure why you're trying to manually get the value using r`eadParamByBody`. Spring pretty much does all this work for you.

**Comment by catinred2** [comment]
@dilipkrish because i want to do some business logic in [readParamByBody](https://github.com/catinred2/swagger_test/blob/master/src/main/java/com/test/action/TestAction.java#L55).

**Comment by catinred2** [comment]
finally I decide to put body parameter into response of 201. a little dirty but it'll do for me.
