### ISSUE TITLE
multiple URL path mapping

### ISSUE THREAD

**Issue by E006840** [springfox/springfox#1274]
We have multiple Spring servlet mapping like:
servlet-mapping
		servlet-name SpringmvcDispatch servlet-name
		url-pattern /secure/user/* url-pattern
		url-pattern /public/user/* url-pattern
servlet-mapping

It seems springfox API only can take one path mapping like pathMapping("/secure/user/"). I don't find a way to make it support multiple path mapping. In other words, for some rest routes, swagger ui doesn't display correct url of rest routes and I can't use it to retrieve real data.

**Comment by dilipkrish** [comment]
Just create a new `Docket`and select the right paths and apis in each one. 

e.g. In psuedocode

`Docket().groupName("Secure").select().<only secure endpoints>.pathMapping("secure")`
`Docket().groupName(""Public").select().<only public endpoints>.pathMapping("public")`
