### ISSUE TITLE
Appends port 80 to the host name

### ISSUE THREAD

**Issue by Vinoth-LearningThings** [springfox/springfox#1278]
I have implemented the Swagger in my microservice and hosted in Pivotal Cloud. When I hit 'Try it out' Swagger sends the request with port 80 along with the hostname. And hence my service couldn't recognize the request. This doesn't happen when I hit my application from local or with http request. I am getting this issue only if I access my application with https.

Any ideas ? Thanks

**Comment by dilipkrish** [comment]
Are you using a gateway/proxy?
