### ISSUE TITLE
Set Default for Expand/collapse on swagger-ui

### ISSUE THREAD

**Issue by mibeumer** [springfox/springfox#1279]
Version: 2.4.0

It would be nice, if I could set the the Default for expand, list or collapse on the swagger-ui in springfox. 

In swagger-ui I can set this with docExpansion (none, list, full). See: https://github.com/swagger-api/swagger-ui#parameters

Kind Regards
mibeumer

**Comment by dilipkrish** [comment]
This should be available already. If you provide a custom [UIConfiguration bean](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/UiConfiguration.java#L37) with the expectation, it should just work.

**Comment by mibeumer** [comment]
Yes, It just works :-) Thank you, dillipkrish!

Maybe the documentiation should be updated, because there is the sentence:
"20. Optional swagger-ui ui configuration currently **only supports the validation url**"
But also some other options are supported through this UIConfiguration Bean.

**Comment by dilipkrish** [comment]
@mibeumer we could use some help with a pr for that 👍

**Comment by dilipkrish** [comment]
See no. 20 [here](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)
