### ISSUE TITLE
Upgrade to the latest swagger spec/ library

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#128]

**Comment by TomDePauw** [comment]
I also would like to know what happened to #195 is it documented, or was it not released?

**Comment by dilipkrish** [comment]
#195 is supported in the sense that we use Jackson to describe the minimum set of (de)serializable properties, that is common across the sub types. But it does not describe the *oneOf* relationship. Might be worth adding support for this in 2.0
