### ISSUE TITLE
@ApiModelProperty.position not respected

### ISSUE THREAD

**Issue by marceloverdijk** [springfox/springfox#1280]
I'm using Springfox `2.4.0` but the output does not respect the @ApiModelProperty position field.
Instead the fields in the resource are ordered alphabetically.

**Comment by dilipkrish** [comment]
Don't believe [that](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ModelMapper.java#L120) is [correct](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/Properties.java#L107-L109). Could you perhaps create a breaking test?

**Comment by marceloverdijk** [comment]
@dilipkrish What can we expect? 

When I have class like:

    public class HotelResource {

    @ApiModelProperty(value = "The unique id of the hotel", required = true)
    private String id;

    @ApiModelProperty(value = "The name of the hotel", required = true)
    private String name;

    @ApiModelProperty(value = "The unique alpha2 code of the hotel", required = true)
    private String countryAlpha2Code;

    ..

Now the Springfox generated swagger.json contains a `HotelResource` definition containing these properties but ordered like: `country_alpha2_code`, `id`, `name`.

Is that expected? Should it not keep the order of the properties in the class?

**Comment by dilipkrish** [comment]
@marceloverdijk yes that is expected. It orders by position and then by name.

**Comment by marceloverdijk** [comment]
Hmm thx for feedback. It's not what I see in result.

E.g. with the following class:

    public class CircuitResource {

        @ApiModelProperty(value = "The unique id of the circuit", position = 1, required = true)
        private String id;

        @ApiModelProperty(value = "The name of the circuit", position = 2, required = true)
        private String name;

        @ApiModelProperty(value = "The short name of the circuit", position = 3, required = true)
        private String shortName;

        @ApiModelProperty(value = "The type of the circuit", position = 4, required = true)
        private String type;

        @ApiModelProperty(value = "The direction of the circuit", position = 5, required = true)
        private String direction;

        // getters and setters omitted
        ..

The following definition is generated in the swagger spec:

    "CircuitResource": {
      "type": "object",
      "required": ["direction", "id", "name", "short_name", "type"],
      "properties": {
        "direction": {
          "type": "string",
          "description": "The direction of the circuit"
        },
        "id": {
          "type": "string",
          "description": "The unique id of the circuit"
        },
        "name": {
          "type": "string",
          "description": "The name of the circuit"
        },
        "short_name": {
          "type": "string",
          "description": "The short name of the circuit"
        },
        "type": {
          "type": "string",
          "description": "The type of the circuit"
        }
      }
    }

I would have expected the order to be `"id", "name", "short_name", "type", "direction"` but it was alphabetically, ignoring the `position` attribute of the `@ApiModelProperty` annotation.

(I'm using springfox `2.4.0`)

**Comment by garakelian** [comment]
@dilipkrish See #766. ModelMapper has ability to sort by position, but BaseModelProperty.position() always returns 0, except for ParameterModelProperty which overrides it.  Couldn't a quick change be made to BeanModelProperty or FieldModelProperty to initialize the position value from ApiModelProperty.property()?

**Comment by dilipkrish** [comment]
@garakelian thanks for catching that miss... @marceloverdijk thanks for reporting. Can't believe its not been discovered before 😕

**Comment by marceloverdijk** [comment]
Thx, will try snapshot soon!

**Comment by marceloverdijk** [comment]
@dilipkrish I can confirm it now works in 2.4.1-SNAPSHOT.

Btw would it also be possible to remove the explicit position in the annotation and order by default as the order of the fields in the class. E.g using a general settings?

**Comment by dilipkrish** [comment]
@marceloverdijk thats not guaranteed to be in the order so it may not be easy to do

**Comment by jedvardsson** [comment]
@dilipkrish Jackson JSON serializer is able to output the fields in order. I haven't looked into how its done.

**Comment by franz-see** [comment]
This seems to be broken again as of 2.9.2

**Comment by shevek** [comment]
Broken for me too in 2.9.2

**Comment by javaHelper** [comment]
@dilipkrish - Could you please suggest how to fixed this?

**Comment by zhugw** [comment]
same problem in 3.0.0
