### ISSUE TITLE
Link to contribution guidelines broken

### ISSUE THREAD

**Issue by ry4n-sc0tt** [springfox/springfox#1281]
The link to the contribution guidelines in README.md is broken. I have a fix ready, which changes the link from: `[Contributing](CONTRIBUTING.md)` to: `[Contribution Guidelines](https://github.com/springfox/springfox/wiki/Contribution-guidelines)`. Trivial, I know, but should I go ahead and create a PR?

**Comment by dilipkrish** [comment]
sure why not! much appreciated!
