### ISSUE TITLE
Missing model definitions in swagger json document when return type is array syntax (CustomModel[])

### ISSUE THREAD

**Issue by namkee** [springfox/springfox#1282]
i'm using 2.4.0 version

    compile ("io.springfox:springfox-swagger2:2.4.0") {
        exclude group: "org.springframework"
    }
    compile ('io.springfox:springfox-swagger-ui:2.4.0') {
        exclude group: "org.springframework"
    }

when Controller method return array 

    @RequestMapping(value = "/apis/roles", method = RequestMethod.GET)
    @ResponseBody
    public Role[] getRoleTestStatus() {
        ...
    }

responses json is correct.

    responses: {
        200: {
            description: "OK",
            schema: {
                type: "array",
                items: {
                    $ref: "#/definitions/Roles"
                }
            }
        },
        401: {
            description: "Unauthorized"
        },
        403: {
            description: "Forbidden"
        },
        404: {
            description: "Not Found"
        }
    }

but definitions json node don't contain 'Roles' model property. 
How can i represent array type model?
thanks for your help.

**Comment by dilipkrish** [comment]
What does `Role` look like? is it an enum?

**Comment by namkee** [comment]
hi dilipkrish
`Role` is just POJO class. 

    @Controller
    public class WorldController {
    
    	@RequestMapping(value = "/test1", method = RequestMethod.GET)
    	@ResponseBody
    	public Role[] test() {
    		return null;
    	}
    
    	static class Role {
    		private String id;
    		private String name;
    	}
    }


change the return type `Role[]` to `List<Role>`. then result json is correct. only array return type is allways missing model Role.

**Comment by dilipkrish** [comment]
let me investigate

**Comment by woco** [comment]
I think it's like my issue https://github.com/springfox/springfox/issues/1259. 
Enough information supplied?

**Comment by namkee** [comment]
i think there is no logic to add the model for return type 'Array'.
in method 'resolvedDependecies' of 'DefaultModelDependencyProvider.java' 
only models of Generic types are added.
(only generic types will return dependent models through getTypeParameters() method of ResolvedType.java') 
http://fasterxml.github.io/java-classmate/javadoc/1.3/com/fasterxml/classmate/ResolvedType.html#getTypeParameters()

need to add logic for 'array type'
https://github.com/namkee/springfox/commit/0a7f0ebd2db015e70c479a8ea71369f2c41c19e7

**Comment by woco** [comment]
Just for the issue, I don't care the imeplements of dependencies. I think It's necessary that recognize the model from list or array result, because it's a frequent situation.

**Comment by dilipkrish** [comment]
@namkee thanks for the hint. That was it. would you like to submit a PR?
