### ISSUE TITLE
Swagger JSON Not getting generated properly

### ISSUE THREAD

**Issue by mkvivek** [springfox/springfox#1283]
Hi All,

I am using SpringFox to generate my Spring Rest API documentation, but having  a strange issue while creating the swagger.json,Swagger version is 2.0("swagger":"2.0"). The issue is one of the models is not parsing properly(Please find the hilited objects which is not generated properly). 

ListResultModel.java

**public class ListResultModel &lt;MODEL extends BaseModel&gt; {
  // Code 
}**

Can anybody please help me!.

"schema":{"$ref":"#/definitions/RedirectAttributes"}}],"responses":{"200":{"description":"OK","schema":{"type":"string"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}},"/admin/migration/vat":{"get":{"tags":["migration-controller"],"summary":"vatMigration","operationId":"vatMigrationUsingGET","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"retailerId","in":"query","description":"retailerId","required":true,"type":"string"}
{"$ref":"#/definitions/**ListResultModel**«Item»**"**}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}},"/api/items/withoutPictures/{departmentId}/{vendorId}/{status}":{"200":{"description":"OK","schema":{"$ref":"#/definitions/ListResultModel**«Item»**"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not }
{"$ref":"#/definitions/ListResultModel**«Lead»**"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}}

Thanks in advance!
Vivek

**Comment by dilipkrish** [comment]
Whats not parsing correctly. Just highlighting only tells me ___what___ is wrong not ___why___ its wrong?

**Comment by mkvivek** [comment]
Hi dilipkrish,

Thanks for the Help.

ListResultModel«Item» is not a valid json notation, this should converted in to json format. I am using the generated json to import the API in to Amazone(https://aws.amazon.com/about-aws/whats-new/2015/07/introducing-swagger-importer-easily-import-swagger-api-definitions-into-amazon-api-gateway/) and which is failing because of the below symbol in the json

> «

Regards
Vivek

**Comment by dilipkrish** [comment]
[Please see the docs](http://springfox.github.io/springfox/docs/current/#changing-how-generic-types-are-named)

**Comment by mkvivek** [comment]
Many thanks for the help Dilip.I will update you the result

**Comment by mkvivek** [comment]
Dilip helped to fix the issue.Closing now!
