### ISSUE TITLE
Enable and disable the "Try it out!" functionality

### ISSUE THREAD

**Issue by mibeumer** [springfox/springfox#1286]
Release: 2.4.0

It would be nice if we could enable and disable the "Try it out!" functionality (maybe per http method). If the application is in production, then it is disabled and it is only a static documentation.

For example like the **supportedSubmitMethods** from swagger-ui: https://github.com/swagger-api/swagger-ui#parameters

Thank your :+1: 

Kind Regards
mibeumer

**Comment by dilipkrish** [comment]
Seems like a very similar request to #1291

**Comment by dilipkrish** [comment]
Fixed via #1295
