### ISSUE TITLE
Feature: Headers in @RequestMapping are not documented

### ISSUE THREAD

**Issue by ry4n-sc0tt** [springfox/springfox#1287]
Query parameters in `@RequestMapping` annotations are documented, but headers are not. I know there is a workaround using `@ApiImplicitParam`, but since all the information is there in the `@RequestMapping` annotation, it seems reasonable to use that info for documentation.

Using version 2.4.0

**Comment by ry4n-sc0tt** [comment]
I have a fix that works, but before submitting a PR, I wanted to get your thoughts on whether this should go in `OperationParameterRequestConditionReader`, or if it should be its own `OperationBuilderPlugin`, with common code between the two refactored into an abstract class.

**Comment by dilipkrish** [comment]
@ry4n-sc0tt I think it should be in its own plugin `OperationParameterHeadersConditionReader` thanks for catching that feature and thanks even more for volunteering to send in a PR! :metal:
