### ISSUE TITLE
Swagger UI is not showing all the rest end points

### ISSUE THREAD

**Issue by amitmawkin** [springfox/springfox#1288]
Github URL for code
https://github.com/capitalone/Hygieia

We are trying to use Swagger for our open source project, the api on swagger page are shown till certain rest api-endpoint and after that it does not render the other end points.

Please advise what could be causing this, I tried to open an issue with Swagger and they said this is a spring fox issue.

the issue link is here
https://github.com/swagger-api/swagger-ui/issues/2031

**Comment by dilipkrish** [comment]
You probably want map `JsonNode` to some other type and I'd say the closest to it is `Map<String, Object>` which is an any type basically. You need to use the alternate rules to define this mapping. There should be good info in http://springfox.io on how to do that. Let me know if you can't find it

**Comment by amitmawkin** [comment]
Can you please point to it. Many thanks

**Comment by dilipkrish** [comment]
[See No. 10](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)

For e.g. the you might try something like this 👇 (not compiler checked)
```java
...
        .alternateTypeRules(
            newRule(typeResolver.resolve(JsonNode.class),
                           typeResolver.resolve(Mapclass, String.class, Object.class)))
....
```

**Comment by fidelcoria-aa** [comment]
@dilipkrish I tried your suggestion in the code base mentioned above. I upgraded the springfox version to 2.7.0 and added the following Bean but this did not work. Is there some other configuration needed or should this bean be in a different place?
```
@SpringBootApplication
@EnableSwagger2
@EnableEncryptableProperties
public class Application extends SpringBootServletInitializer {
    // ... //
    @Bean
    AlternateTypeRuleConvention jsonObjectConvention(final TypeResolver tr) {
        return new AlternateTypeRuleConvention() {
            @Override public int getOrder() { return Ordered.HIGHEST_PRECEDENCE; }
            @Override public List<AlternateTypeRule> rules() {
                return newArrayList(AlternateTypeRules.newRule(
                        tr.resolve(JSONObject.class),
                        tr.resolve(Map.class, String.class, Object.class)
                    )
                );
            }
        };
    }
}
```
REST Methods that are annotated as `consumes = APPLICATION_JSON_VALUE` and have a parameter annotated with `@RequestBody` of type JSONObject cause Swagger UI to halt rendering the controllers in alphabetical order. 
Inspecting the page reveals this error:
```
Uncaught TypeError: Cannot read property '0' of undefined
    at getInlineModel (index.js:24)
    at Object.createParameterJSONSample (index.js:24)
    at s.render (index.js:24)
    at s.addParameter (index.js:24)
    at s.render (index.js:24)
    at s.addOperation (index.js:24)
    at s.render (index.js:24)
    at s.addResource (index.js:24)
    at s.render (index.js:24)
    at s.render (index.js:24)
```
The JSON Swagger definition from http://localhost:8080/api/v2/api-docs shows that JSONObject is converted to "schema":{"type":"object","additionalProperties":{"type":"object"}}. This conversion happens with the AlternateTypeRuleConvention and without it.

As a work around: annotating the offending REST method `@ApiOperation(value=<copy path>, hidden = true)` causes Swagger to ignore the method and all the other methods can be seen in Swagger UI. Not a solution, though.

**Comment by fidelcoria-aa** [comment]
Looks to me like the real solution is to define a Java class for the Request Body instead of using JSONObject. This way the structure of the Request Body is explicit, documented, and unambiguous to Swagger.
