### ISSUE TITLE
@ApiModelProperty "name" attribute has no effect

### ISSUE THREAD

**Issue by tjuchniewicz** [springfox/springfox#1289]
I can use `@JsonProperty(value = "changed-name")` as a workaround but...

**Comment by tjuchniewicz** [comment]
I can use `@JsonProperty(value = "changed-name")` as a workaround but...

**Comment by dilipkrish** [comment]
@tjuchniewicz that is by design. We don't want ever to have a case where the serialization model is different from whats being documented.

**Comment by tjuchniewicz** [comment]
It is difficult to accept existence of `@ApiModelProperty(name)` but your explanation make sense. Thanks!

**Comment by dilipkrish** [comment]
@tjuchniewicz Actually the existence of `@ApiModelProperty` is explained by the fact that we want to use the same annotations that [swagger-core](https://github.com/swagger-api/swagger-core) uses. However we take the philosophy of using the annotations just to supplement documentation. If for e.g. you've annotated your models with `@JsonProperty` etc we don't want to duplicate that using `@ApiModelProperty` as it is very easy to get out of sync.

**Comment by tjuchniewicz** [comment]
OK. I get the idea.

**Comment by tjuchniewicz** [comment]
@dilipkrish bot for example `@JsonProperty(required)` is not used. I must use `@ApiModelProperty(required)`.

**Comment by dilipkrish** [comment]
true that!! 

I should clarify, we don't parse _any_ jackson annotation with exception of may be a couple, e.g. `JsonUnwrapped`. We delegate to jackson to tell us what the model is supposed to look like. 

Where as we look at the swagger annotations for anything that might supplement what we know about the model i.e. description, required/not-required etc.

Its totally possible to add that as part of library, but that would mean we need to know the internals of jackson  So now we would need to keep up with changes in jackson, in addition to changes in the swagger (OAS) spec and changes in spring fx itself.

So in the interest of having a life outside of this project :) that is supported via the swagger annotations or as an exercise for the consumers of this library to implement their own plugin. The extensibility is pretty rich, but [the docs ](http://springfox.github.io/springfox/docs/current/#plugins)may not do it justice

**Comment by tjuchniewicz** [comment]
I don't get why `JsonProperty(value)` is supported but `JsonProperty(required)` is not...
When you use Jackson to tell you what is a model, it does not return information about `required`?

Plugins seem very interesting! I've just created support for `JsonProperty(required)` for my case.
If you use [bean-validators](https://github.com/springfox/springfox/tree/master/springfox-bean-validators) example to start it is not so hard to do it. Thanks!

**Comment by dilipkrish** [comment]
You are right. Thanks for pursuing it. I'll create a chore the fix that.

**Comment by rajeshkamal** [comment]
@dilipkrish We are using GSON for models. I was expecting that @ApiModelProperty "name" would work for overriding property name. 

Do you think though you use GSON for overriding the property name one has to use Jackson's annotations? Wouldn't it be better to have the @ApiModelProperty's name to work.

Any inputs would be helpful.

**Comment by zkuku** [comment]
@apissdks  I think the same. I use GSON and do not want to add @SerializedName and @JsonProperty together

**Comment by dilipkrish** [comment]
Really there isn't first class gson support. We'd need to implement [`ModelProvider`](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/ModelProvider.java), [`ModelDependencyProvider`](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/ModelDependencyProvider.java) and [`ModelPropertiesProvider`](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/property/ModelPropertiesProvider.java) interfaces for gson.

**Comment by xinbimingjingtai** [comment]
Not support fastjson.
