### ISSUE TITLE
Docket.pathMapping not working

### ISSUE THREAD

**Issue by Frezzaldo** [springfox/springfox#1290]
Hello

Im using the 2.4.0 version.

Im currently trying to add a prefix to the Swagger api-docs. My configuration looks like this:

@Bean
public Docket swaggerSpringMvcPlugin(final ServletContext servletContext) {
    return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .paths(regex(".*1.0.*"))
            .build()
            .apiInfo(apiInfo())
            .**pathMapping("/api");**
}

I want the api-docs to be on path: `context-path/api/v2/api-docs` but this is not working. Instead `context-path/v2/api-docs` is working.

**Comment by dilipkrish** [comment]
@Frezzaldo Thats not the way to change the path where swagger api docs is served from. See [here](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints) for how to do that
