### ISSUE TITLE
Make 'supportedSubmitMethods' configurable in springfox-swagger-ui

### ISSUE THREAD

**Issue by thomseno** [springfox/springfox#1291]
Hi, 

currently only HTTP methods `'get', 'post', 'put', 'delete' & 'patch'` are supported by springfox-swagger-ui (see `springfox.js:25`). Some actuator endpoints from spring boot (e.g. `/health`) use `'head' and 'option'` and are therefore not 'executable' from swagger-ui.

This is related to issue #1286, because if you configure no HTTP methods the "Try it out!" functionality is disabled according to the swagger-ui documentation.

Regards, Oliver

**Comment by dilipkrish** [comment]
Thanks for reporting the feature. Any chance you could submit a Pr to implement that by augmenting the [UiConfiguration](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/UiConfiguration.java) bean and using the values from there?

**Comment by thomseno** [comment]
Provided PR... thanks for your tip regarding `UiConfiguration`.

**Comment by dilipkrish** [comment]
This has been fixed via #1295 :metal: @thomseno

**Comment by thomseno** [comment]
Thanks 👍
