### ISSUE TITLE
Utilize the jackson property definition to determine additional information

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#1294]
Currently the isRequired property from the [jackson property is ignored](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/property/BaseModelProperty.java#L73). There are additional properties that might be ignored as well.

Thanks to @tjuchniewicz for reporting issue #1289.

**Comment by tjuchniewicz** [comment]
`@JsonProperty` and `@JsonRootName` aren't supported.
