### ISSUE TITLE
Support for JSR-303: @Pattern annotation

### ISSUE THREAD

**Issue by ashutosh-shirole** [springfox/springfox#1296]
For starters, this is a great library and has been of great help.
I am currently using 2.4.0 version and springfox-bean-validators plugin for JSR 303 bean validation annotations @NotNull @Min @Max.

Have seen [#356](https://github.com/springfox/springfox/issues/356) and comments on [this](https://github.com/springfox/springfox/commit/04065109fb8ce566e7fa8016a00a31202e733d37) commit, which states the support for @Pattern annotation is not available. 

I could not find ModelPropertyBuilderPlugin for Pattern annotation. Am I missing out on something or this annotation is not yet supported?

**Comment by dilipkrish** [comment]
Its not supported.... but it could be :) PR?

**Comment by jjzabkar** [comment]
Perhaps this issue should be tagged as "can-use-for-docs"?
https://github.com/springfox/springfox/labels/can-use-for-docs

Related: https://github.com/springfox/springfox/issues/1227

**Comment by igor-sokolov** [comment]
> Its not supported.... but it could be :) PR?
Here you are! (:
