### ISSUE TITLE
Duplicate Model In Swagger File Because Of Same RequestBody variable Name

### ISSUE THREAD

**Issue by mkvivek** [springfox/springfox#1297]
Hi All, 
we are using SpringFox to generate our Spring Rest API documentation, but having an issue while creating the swagger.json,Swagger version is 2.0("swagger":"2.0").

One of the spring controller we have a set of end points like shown below(marked as bold).

public @ResponseBody ResponseEntity<BulkUpdateResult> bulkUpdateEmployee(RequestBody List<Long> **contactIdList**,RequestHeader(Constants.TOKEN_KEY) String authToken) {}

public @ResponseBody ResponseEntity<BulkUpdateResult> bulkUpdateCategory(RequestBody List<Long> **contactIdList**,@RequestHeader(Constants.TOKEN_KEY) String authToken) {} etc.

So the Json Created is also having the same 

[{"in":"body",**"name":"contactIdList"**,"description":"contactIdList","required":true,"schema":{"type":"array","items":{"type":"integer","format":"int64"}}},{"name":"categoryId","in":"path","description":"categoryId","required":true,"type":"integer","format":"int64"},{"name":"token","in":"header","description":"authToken","required":true,"type":"string"}],"responses":controller"],"summary":"bulkUpdateEmployee","operationId":"bulkUpdateEmployeeUsingPOST","consumes":["application/json"],"produces":["*/*"],"parameters":[{"in":"body",**"name":"contactIdList"**,"description":"contactIdList","required":true,"schema":{"type":"array","items":{"type":"integer","format":"int64"}}},{"name":"employeeId","in":"path","description":"employeeId","required":true,"type":"integer","format":"int64"}

I am using this schema to import the API in to amzone using a tool. The tool is giving error like " **contactIdList** duplicate and the same model name already exist" because of the same name and parameters.

Is there a way to overcome springfox generating the same name ?

Thanks in advance.
Vivek

**Comment by dilipkrish** [comment]
Rename your variable

**Comment by mkvivek** [comment]
Thanks for the quick response Dilip. 
It is in to many places. We have around 100 controllers and each controller we have duplicate variable in to different APIs!. Do we have any work around?

**Comment by mkvivek** [comment]
Hi Dilip,
Any work around for this?.Because it is something common in any application, where two methods are having  same variable name for parameter!.

Thank you
Vivek

**Comment by dilipkrish** [comment]
Parameter names are inherently scoped to the operation, So Im not sure what error is. Could you copy the resulting api docs json and paste it in http://editor.swagger.io/#/ and see what validation errors it gives you.

**Comment by mkvivek** [comment]
Hi Dilip,
I have tried the editor to validate the the Json, No validation errors, but the amazone API importer (https://github.com/awslabs/aws-apigateway-importer) is not accepting this file because of the  same name. I may get some help from the Amazone API Importer team.
----------------------------------------------------------------------------------------------------------------------------------
One final question!

Most of my spring end point we didn't specifically mention the produces. For example we don't have the highlighted code in most of the cases

@RequestMapping(method = RequestMethod.POST, **produces = "application/json"**)
public @ResponseBody ResponseEntity<Contact> create(@RequestBody Contact model) {}

So as expected the producer generated as producer[*/*]. For overcome this I have added the below code in to plugin

                Set<String> prod = new HashSet<String>();
		prod.add("application/json");
		Docket doc = new Docket(DocumentationType.SWAGGER_2);
		**doc.produces(prod);**
                doc.forCodeGeneration(true);
	        return doc;

But still the generated json have same **producer[*/*]** . Is it a bug??. I know this not the place to ask a new question. But already I have opened few tickets!!

Thanks & Regards
Vivek

**Comment by dilipkrish** [comment]
Not sure what `producer[/] ` means. Where are you seeing this? It should generate requests using the default accept header `*/*`

**Comment by mkvivek** [comment]
Hi Dilip,
Correct in my post `*/*` missed some how!.It is still generating requests using the default accept header `*/*` even though I have given the code below to overcome this issue.

Set<String> prod = new HashSet<String>();
prod.add("application/json");
Docket doc = new Docket(DocumentationType.SWAGGER_2);
doc.produces(prod);
doc.forCodeGeneration(true);

Sample Json Generated

`{"description":"Not Found"}}}},"/api/contacts/contactsWithNoPurchaseHistory/{departmentId}/{status}":{"get":{"tags":["contact-controller"],"summary":"contactsWithNoPurchaseHistory","operationId":"contactsWithNoPurchaseHistoryUsingGET","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"departmentId","in":"path","description":"departmentId","required":true,"type":"integer","format":"int64"},{"name":"status","in":"path","description":"status","required":true,"type":"string"}`

Thanks for the help.
Regards
Vivek
