### ISSUE TITLE
swagger2 documentation of Integer[]

### ISSUE THREAD

**Issue by Frezzaldo** [springfox/springfox#1300]
I recently updated from 2.2.2 to 2.4.0.

In my code I have the following path variabel in my @requestMapping:
`@PathVariable final Integer[] codeTypeIds`

This was in version 2.2.2 documentet as:
`{"name":"codeTypeIds","in":"path","description":"codeTypeIds","required":true,"type":"array","items":{"type":"integer","format":"int32"},"collectionFormat":"csv"}`

But now in 2.4.0 it's:
`{"name":"codeTypeIds","in":"path","description":"codeTypeIds","required":true,"type":"string"}`

**Comment by dilipkrish** [comment]
This was an intentional regression. Let me see what needs to happen

**Comment by dilipkrish** [comment]
I did investigate this. This is by design. You cannot have an array of path variables
