### ISSUE TITLE
Tags in @ApiOperation are not rendered in 2.4.0

### ISSUE THREAD

**Issue by soumeny2k** [springfox/springfox#1302]
Currently, as of Springfox master Swagger 2.4.0 snapshot, if I use tags inside an @ApiOperation block, they are not rendered in the api-doc output. 
How to add Operation specific description using SppringFox.

**Comment by dilipkrish** [comment]
Use the [docket](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L425) to register tags and descriptions

**Comment by maklemenz** [comment]
@dilipkrish actually I don't see how we can set the tags (and the description/summary) for each action with dockets, since they seem to be used for global springfox configurations and don't seem to be meant for configuring every single api-operation.

**Comment by dilipkrish** [comment]
@maklemenz May need to elaborate a bit here, as Im guilty of assuming everyone has the same context that I have in my head. 

Well the docket registers `Tags` which are first class constructs just like operations, models etc. and what you see on operations are references to those `Tag`s. The _hack_ we have in place just to reduce the amount of boiler plate for the developer is to provide a default description that happens to be the same as the tag name. So in effect we are synthesizing a pseudo `Tag` by referencing one on the operation. 

By defining the `Tag` on the docket, we are referencing a real tag defined by you. 

makes sense?

**Comment by maklemenz** [comment]
At first I wanted to open a new issue but it seems to be very strongly related to this question.

I'm using springfox 2.4.0 and created a simple rest api with each operation documented using `@ApiOperation`. This annotation is used in the documentation of springfox to set the operationId and a nickname, but it does not say anything about the summary.

According to the java-doc on `ApiOperation`, the annotation value is used to set the summary on an action, but it does not get rendered to the output.

Given this oversimplified code:

    @ApiOperation(
        value = "This Operation does nothing",	// does not show up in /swagger-ui.html, why?
        notes = "This is meaningless, you may not use it at all", // does not show up in /swagger-ui.html, why?
        tags = "stuff" // is used for categorizing the ApiOperations in /swagger-ui.html
    )
    @RequestMapping(value = "/no-operation", method = RequestMethod.GET)
    public ResponseEntity<Void> doNothing() {
        return new ResponseEntity<Void>(HttpStatus.OK);
    }
    
I would expect this action to be in the `stuff` group in my swagger-ui.html, it should have the summary "This Operation does nothing" and the notes should appear.
Indeed it is in the group `stuff` but the summary is "doNothing" and the notes aren't rendered at all.

From my understanding `Dockets` are used for overall api configuration like the direct model substitutes and what the api consumes or produces.
