### ISSUE TITLE
Customizing basePath

### ISSUE THREAD

**Issue by vijayansrinivasan** [springfox/springfox#1303]
Is it possible to remove basePath as empty / remove from v2/api-docs response?

Using version 2.2.2, Using with SpringBoot & Maven

What kind of issue is this?

Question

**Comment by vijayansrinivasan** [comment]
Is it possible to set basePath as empty or remove from v2/api-docs response?

**Comment by vijayansrinivasan** [comment]
Below steps did the trick

class BasePathAwareRelativePathProvider extends AbstractPathProvider {
        private String basePath;

        public BasePathAwareRelativePathProvider(String basePath) {
            this.basePath = basePath;
        }

        @Override
        protected String applicationPath() {
            return basePath;
        }

        @Override
        protected String getDocumentationPath() {
            return "/";
        }

        @Override
        public String getOperationPath(String operationPath) {
            UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/");
            return Paths.removeAdjacentForwardSlashes(
                    uriComponentsBuilder.path(operationPath.replaceFirst(basePath, "")).build().toString());
        }
    }

@Bean
	public Docket newsApi() {
		return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).select().paths(regex("/v1/*.*")).build().pathProvider(new BasePathAwareRelativePathProvider(""));
}

**Comment by dilipkrish** [comment]
👍 sorry I wasn't able to respond earlier.
