### ISSUE TITLE
Configuration without spring boot not working

### ISSUE THREAD

**Issue by zonorion** [springfox/springfox#1305]
Hi all,
I try config springfox with springmvc but it's not working.
My code:
```java

@Configuration
@EnableSwagger2
public class SwaggerConfig {                                    
    @Bean
    public Docket api() { 
        return new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())                          
          .build();                                           
    }
}
```

And 

```java
@Override
public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("swagger-ui.html")
      .addResourceLocations("classpath:/META-INF/resources/");
 
    registry.addResourceHandler("/webjars/**")
      .addResourceLocations("classpath:/META-INF/resources/webjars/");
}
``` 

a class that extends WebMvcConfigurerAdapter, and is annotated with @EnableWebMvc.

Could you tell me what's my problem? And how to fix it?
Thanks.

**Comment by dilipkrish** [comment]
> I try config springfox with springmvc but it's not working.

What is not working?

**Comment by dilipkrish** [comment]
@zonorion ping!

**Comment by Pyohwan** [comment]
I try springfox 2.5.0 and springfox-ui 2.5.0 with non spring boot java configuration.
but, can't connect 'swagger-resources/configuration/ui'
I used @EnableWebMvc and @Configuration

**Comment by dilipkrish** [comment]
@Pyohwan Cant help without additional info... Please submit a new issue with [more details](https://github.com/springfox/springfox/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Vepis** [comment]
Good night, I have the same error, I have a spring mvc project and the json of api documentacion works, I added the dependencies, the xml configurations, but /swagger-ui.html doesnt work, I have been looking forward for any example but I have no succes, with the v2 of swagger, do you have an example to show how should I configure correctly swagger2 with spring mvc project, pleas?

**Comment by dilipkrish** [comment]
Have you looked at the demos?
