### ISSUE TITLE
Move Springfox annotations like ApiIgnore into a separate module

### ISSUE THREAD

**Issue by RobWin** [springfox/springfox#1308]
Hello @dilipkrish 

Is it possible to move the Springfox annotations like ApiIgnore into a separate module?
I use Springfox as a testCompile dependency and I just need the annotations as a compile dependency to be able to ignore certain operations.
Similar to the swagger-annotations.

**Comment by dilipkrish** [comment]
@RobWin it seems like an overhead to create a new module for just that one annotation. Easier to create your own annotation instead and create a predicate to ignore it.
