### ISSUE TITLE
@RequestBody parameter ignored in GET request

### ISSUE THREAD

**Issue by gallifabio** [springfox/springfox#1309]
Hi, I'm currently using springfox to document our REST API and until now it works fine. Yesterday I found an issue with a GET request containing a requestBody object encoded as JSON. I'm using the following dependencies in my project:

Spring-* 4.2.6
- springfox-swagger2
- springfox-swagger-ui
- springfox-bean-validators
Version is the latest 2.4.0

The Json is really simple:

`{
  "active": "UNDEFINED",
  "emailDomain": "domain.com"
}`

![springfox](https://cloud.githubusercontent.com/assets/3372532/15206983/40aed482-1823-11e6-9664-6e622c9f4806.png)

When I hit the "Try it now!" button the request is sent WITHOUT the filter object (I inspected the request in both Firefox and Chrome). The generated CURL request is correct and returns the correct result:

`curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Authorization: 6134fc94-0535-449c-b2c5-2d4ecdff8273' -d '{
  "active": "UNDEFINED",
  "emailDomain": "domain.com"
}' 'http://localhost:8080/customers'`

Here's the detail of the method of my rest controller:

```java
@RequestMapping(method = RequestMethod.GET, consumes = MediaType.APPLICATION_JSON_VALUE)
@ApiOperation(value = "Get all the customers")
@ApiResponses({
	@ApiResponse(code = 403, message = "Unauthorized")
})
public ResponseEntity<CustomerList> getCustomers(@RequestBody(required=false) CustomerFilter filter) {
	return new ResponseEntity<>(customerManager.findCustomers(filter), HttpStatus.OK);
}
```

Any help will be greatly appreciated, if you need more details let me know. Thanks in advance,

**Comment by dilipkrish** [comment]
This is a [swagger-ui](https://github.com/swagger-api/swagger-ui) issue.
