### ISSUE TITLE
'enum' query parameter type(annotated with @ModelAttribute) is 'ref'.

### ISSUE THREAD

**Issue by namkee** [springfox/springfox#1310]
hi 
i'm using springfox 2.4.0.

when bind query parameters into Model Object using @ModelAttribute annotation, the 'Enum' field is not converted correctly. I know that type must be 'string' but 'ref'.

    @Controller
    public class TestController {
      @RequestMapping(method = RequestMethod.Get, value = "/search");
      public void search(@ModelAttribute SearchModel model) {
        //...
      }

      public static class SearchModel {
        private SearchType searchType;
        private String keyword;
    
        public enum SearchType {
          TITLE, AUTHOR
        }
      }
    }

result json is like below

    /api/v1/search: {
        get: {
            parameters: [
                {
                    name: "searchType",
                    in: "query",
                    description: "searchType",
                    required: false,
                    type: "ref",
                    enum: [
                        "TITLE",
                        "AUTHOR"
                    ]
                },
                {
                    name: "keyword",
                    in: "query",
                    description: "keyword",
                    required: false,
                    type: "string"
                }
            ],
            responses: {
                ...
            }
        }
    }

searchType's type is "ref". i think it must be "string".

so i took a look 'ExpandedParameterBuilder.java' file. and setting typeName to "string' manually.
https://github.com/namkee/springfox/commit/5b46d31a724d0d4ebbfdf34e0f0642f486b5d17e

i just wonder is it correct code for solve this problem?

**Comment by dilipkrish** [comment]
Not really sure. Will see if this is a bug. Could you perhaps create a failing test

**Comment by dilipkrish** [comment]
👍 for reporting. Confirmed the bug
