### ISSUE TITLE
@JsonPropertyDescription support

### ISSUE THREAD

**Issue by activey** [springfox/springfox#1315]
Hi,

I'm using Springfox 2.4.0 version and just wondering, would it be possible to take @JsonPropertyDescription annotation into consideration while generating an API description? Right now I have to use some additional stuff like @ApiModelProperty that is in most cases pretty much the same as @JsonPropertyDescription. If such feature is not implemented - could you please point out in source code when jackson annotations are being processed? Then I can do a pull request on my own. I spent some time yesterday on tracing it up but wasn't really able to locate the correct spot ;/

**Comment by dilipkrish** [comment]
Thank you very much for volunteering to do a PR :metal: 

A good start is by looking at the [plugin development section](http://springfox.github.io/springfox/docs/current/#plugins). What you need to do is to create an new `ModelPropertyBuilderPlugin` and implement it. Its very similar to the [validator plugins](https://github.com/springfox/springfox/blob/master/springfox-bean-validators/src/main/java/springfox/bean/validators/plugins/NotNullAnnotationPlugin.java#L35).

**Comment by activey** [comment]
Will definitely do ;) I'm considering incorporating springfox-swagger2 annotations so stay tuned ;)

**Comment by activey** [comment]
Thx, will do :)

**Comment by dilipkrish** [comment]
@activey ping!

**Comment by activey** [comment]
Hey ;) Decided not to do it here in springfox. The whole idea behind it was to have two libraries to cooperate each other nicely: springfox swagger and jsonschema2pojo that is capable of generating java bindings out of provided json schema file. I went with some slightly different approach - I have a modified version on jsonschema2pojo that is right now able to generate swagger annotations as well ;) Sorry for a delay, will close this task, not relevant anymore.
