### ISSUE TITLE
@ApiModelProperty(value="something") on bean annotated with @ModelAttribute changes dataType to "ref"

### ISSUE THREAD

**Issue by mpostelnicu** [springfox/springfox#1317]
Hi,
I am using springfox version 2.4.0.

I initialize Swagger2 like this:

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any()).build();
	}
}
```

I have a requestmapping like this:

```
@RequestMapping(value = "/api/costEffectivenessAwardAmount", method = RequestMethod.GET,
produces = "application/json")
	public List<DBObject> costEffectivenessAwardAmount(@ModelAttribute @Valid final DefaultFilterPagingRequest filter) {
.....

}

```

Then on DefaultFilterPagingRequest i have

```
public class DefaultFilterPagingRequest extends GenericPagingRequest {

	@EachPattern(regexp = "^[a-zA-Z0-9]*$")
	@ApiModelProperty(value = "Some description")
	private List<String> bidTypeId;

.....

}
```

This leads to the v2/api-docs to show : 

```
"parameters": [
          {
            "name": "bidTypeId",
            "in": "query",
            "description": "Some description",
            "required": false,
            "type": "ref"
          },
 .....
```

obviously showing in the UI as type="undefined". Any attempt to manually set dataType in @ApiModelProperty is completely ignored and the result is always "ref".

If i comment @ApiModelProperty and just let it autodetect, type works perfectly, but i lose the description field:

``` 
        "parameters": [
          {
            "name": "bidTypeId",
            "in": "query",
            "required": false,
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi"
          }
``` 

Notice i just want to add a description/text to that property, not to change the dataType in any way, but for some reason the dataType is also changed and wrongly set to "ref". So i am forced either to use the default type detection but add no label/description to my properties, or to add description text but break the type detection.

Ideas welcome. Please tell me i have configured something wrongly and this can be fixed with 2 lines of code :-)

**Comment by mpostelnicu** [comment]
oh and i have also tried the 2.4.1-SNAPSHOT, more exactly 
`springfox-core-2.4.1-20160516.122923-18.jar`.

Same result.

**Comment by mpostelnicu** [comment]
hey. @dilipkrish do you have any comments about this ? not sure why is it flagged for 2.5.0, isn't this a bug in 2.4? 

I am just trying to understand if this is a defect or not, if i am using springfox the way i should or maybe im trying to do something that i am not supposed to and as a consequence i see it as a bug.

thanks much

**Comment by dilipkrish** [comment]
I'll get back to you on this. Its flagged for 2.5.0 because thats the next targeted release, which is just around the corner. If there is a more urgent patch we'd release a for e.g. 2.4.1 to get something out earlier than planned.

It would help greatly, if you could perhaps add a failing test. It will aide in making this faster for me and you, as I'm busy with other projects as well.

**Comment by dilipkrish** [comment]
Thanks for reporting this is an issue in the [swagger annotation plugin](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/SwaggerExpandedParameterBuilder.java#L93-L102) doesn't handle collections very well.

**Comment by mpostelnicu** [comment]
working perfectly starting `springfox-swagger2-2.4.1-20160531.190357-34`.

@dilipkrish ,  thanks a lot for addressing this ! It means we can now document our endpoints , we use beans for parameters.
