### ISSUE TITLE
Cannot fully change swagger and swagger ui path

### ISSUE THREAD

**Issue by nikit-cpp** [springfox/springfox#1321]
> What version of the library are you using? 

    compile 'io.springfox:springfox-swagger2:2.4.0'
    compile 'io.springfox:springfox-swagger-ui:2.4.0'

> What kind of issue is this?

 - Feature Request. 

I want to fully change documentation url like http://127.0.0.1:8080/aaa/v3/public/swagger-ui.html for further simplyfy nginx configuration i want to use "/public" subpath:
```
http://127.0.0.1:8080/aaa/v3/public
http://127.0.0.1:8080/aaa/v3/secured
```

I add property source:
```
@Configuration
@EnableSwagger2
@PropertySource("classpath:/config/swagger.properties")
public class SwaggerConfig {
...
```

I set path in swagger.properties:
```
springfox.documentation.swagger.v2.path=/public
```

And I tested GET http://127.0.0.1:8080/aaa/v3/public, json are present in response:
```
{
"swagger": "2.0",
"info":{
"description": "Some custom description of API.",
"version": "API TOS",
"title": "AAA REST API",
"termsOfService": "Terms of service",
"contact":{
...
```

Further, i changed webjar's path in my Spring Boot WebMvcConfigurerAdapter:
WebConfig.java
```
@Configuration
public class WebConfig extends WebMvcConfigurerAdapter{
    private static final String[] CLASSPATH_RESOURCE_LOCATIONS = {
            "classpath:/META-INF/resources/",
            "classpath:/static/", "classpath:/public/" };

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        if (!registry.hasMappingForPattern("/webjars/**")) {
            registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
        }
        if (!registry.hasMappingForPattern("/public/**")) {
            registry.addResourceHandler("/public/**").addResourceLocations(CLASSPATH_RESOURCE_LOCATIONS);
        }
    }
}
```

Now i open http://127.0.0.1:8080/aaa/v3/public/swagger-ui.html in Firefox, but load nothing [PNG image](http://i.imgur.com/kfhFLCR.png) because javascripts attempt to call http://127.0.0.1:8080/aaa/v3/public/configuration/ui.

I found In ApiResourceController.java hard-coded paths - it is root cause.

Please consider to parametrize hard-coded paths.
It does swagger more flexible.

Something like
```
@RequestMapping(value = "${springfox.documentation.swagger.v2.path}/configuration/security")
...
@RequestMapping(value = "${springfox.documentation.swagger.v2.path}/configuration/ui")
...
```

**Comment by dilipkrish** [comment]
Thanks for reporting, we should probably try and fix that. Would you like to take a shot at a PR since you're right in there?

**Comment by dilipkrish** [comment]
I looked into this and its not really easy to fix. Really the expectation is that [swagger-ui is served from the context root](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/springfox.js#L3-L6) and any url we configure every other url relative to the context root. 

The reason we need to have this static convention is that there is no way for us to know what the context root in swagger-ui.html thats packaged as a web jar. Do you have any idea perhaps to get it to work other than the suggestion to change the request mappings to be configurable (cos they cannot be) ☝️

**Comment by dilipkrish** [comment]
Closing this as not really fixable

**Comment by nikit-cpp** [comment]
Ok, probably you right, it' s not easy as I want =(
I simple write it here -- nginx locations for swagger2 and swagger ui:
`  #http://127.0.0.1/aaa/v3/swagger-ui.html
   #http://127.0.0.1/aaa/v3/webjars/springfox-swagger-ui/
   #http://127.0.0.1/aaa/v3/swagger-resources/
   #http://127.0.0.1/aaa/v3/v2/api-docs
   #http://127.0.0.1/aaa/v3/configuration/ui
   #http://127.0.0.1/aaa/v3/configuration/security

    location ~* ^/(\w+)/v3/swagger-ui.html {
        proxy_pass  http://$1:8080;
    }
    location ~* ^/(\w+)/v3/webjars/springfox-swagger-ui/ {
        proxy_pass  http://$1:8080;
    }
    location ~* ^/(\w+)/v3/swagger-resources {
        proxy_pass  http://$1:8080;
    }
    location ~* ^/(\w+)/v3/v2/api-docs {
        proxy_pass  http://$1:8080;
    }
    location ~* ^/(\w+)/v3/configuration/ui {
        proxy_pass  http://$1:8080;
    }
    location ~* ^/(\w+)/v3/configuration/security {
        proxy_pass  http://$1:8080;
    }`

**Comment by jeffnelson** [comment]
I understand the challenges in making the swagger-ui.html path configurable. Instead, could it just not be at root? Having it at root gets in the way of anything else (like business functionality) being at root.

In many microservices, we have request mappings similar to
`/{userId}`

These are legacy paths that would be a huge pain to change. Really anywhere besides root would be better.

**Comment by dilipkrish** [comment]
It is a the root... the context root.

**Comment by GoudGopichand** [comment]
I have swagger2 configuration in my spring boot service locally it runs fine but when i try to run behind nginx load balancer it is not running
Any configuration change is require in nginx.config file ..please help

**Comment by dilipkrish** [comment]
You need to make sure you set the upstream url etc using the X-FORWARD.... headers

**Comment by GoudGopichand** [comment]
Thank you Sir.
Please help me on one more issue
I want to add header : authorization : basic  through java config whenever  api is called from swagger ui 
I dont want to amend js to add header as i have microservices and we are uaing springfox implememtation of swaager.

**Comment by dilipkrish** [comment]
You need to setup your `SecurityConfiguration` bean as described.

**Comment by GoudGopichand** [comment]
This is my configuration ...
@Override
	protected void configure(HttpSecurity http) throws Exception {
		 	 String params = "'" + hostname + "','" +  filePath + "','"+password+"','" + uriPattern+"'";
			
			 http.csrf().disable();
			 http.authorizeRequests()
			.antMatchers("/swagger-ui.html").permitAll().and()
			.authorizeRequests().antMatchers("/swagger-resources/configuration/ui").permitAll().and()
			.authorizeRequests().antMatchers("/swagger-resources").permitAll().and()
			.authorizeRequests().antMatchers("/v2/api-docs").permitAll().and()
			.authorizeRequests().antMatchers("/swagger-resources/configuration/security").permitAll().and()
			.authorizeRequests()
			.expressionHandler(new CustomWebSecurityExpressionHandler())
			.anyRequest()
			.access();
			 http.formLogin().and().httpBasic();
	}
But when I try to hit api from swagger ui , spring security default login form not pops up . Please advice

**Comment by dilipkrish** [comment]
@GoudGopichand This is a closed issue. If you believe you've found a bug, please report a new issue.

To your question, you've `permitAll`ed it, so how would you expect a default spring security login?
