### ISSUE TITLE
Use springfox to generate class model

### ISSUE THREAD

**Issue by gallifabio** [springfox/springfox#1323]
Hi, I was wondering if it's possible to call some springfox java API to dynamically generate a string that represent an object class model, exactly what is displayed by springfox-ui in the "Model" panels:

![springfox-model](https://cloud.githubusercontent.com/assets/3372532/15422071/c375cb4c-1e76-11e6-8df9-d45ef653d2db.png)

If it's possible can you please post an example or at least which classes to use? Thank you for your help

**Comment by dilipkrish** [comment]
@gallifabio Its not possible currently, but I agree it will be useful.

**Comment by dilipkrish** [comment]
Could you perhaps describe how you foresee using this as an API?
