### ISSUE TITLE
I don't want to generate api doc including all controllers, what should i do?

### ISSUE THREAD

**Issue by XiaodongDu** [springfox/springfox#1327]
By using `<context:component-scan base-package="...">` to scan controllers I found that springfox generated the api doc including all controllers in the package.
If I don't want to generate api doc including all controllers, what should i do?
:D

**Comment by dilipkrish** [comment]
Filter it out using the selection api. See [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) no. 4, 5, 6.

**Comment by XiaodongDu** [comment]
I fixed it.Thanks.
