### ISSUE TITLE
Multiple Allowable Values for Lists does not show options in UI

### ISSUE THREAD

**Issue by smwurster** [springfox/springfox#1329]
When an `ApiModelProperty` is on a `List` type, the `allowableValues` entry is not shown in the UI.

When the code looks like this:
```
@ApiModelProperty(value="a list of values", allowableValues="foo,bar,baz", required=false)
public void setValues(List<String> values) {
    this.values = values;
}
```

The generated JSON looks like this:
```
"values": {
    "type": "array",
    "description":  "a list of values",
    "items": {
        "type": "string",
        "enum": [
            "foo",
            "bar",
            "baz"
        ]
    }
}
```

But it should look like this:
```
"values": {
    "type": "array",
    "description": "a list of values",
    "items": {
        "type": "string"
    },
    "enum": [
        "foo",
        "bar",
        "baz"
    ]
}
```

This occurs in version 2.4.0.

**Comment by dilipkrish** [comment]
@smwurster that looks right to me. The _what it should look like_ is an artifact of a bug in swagger-ui/swagger-editor. 

To me it is difference between _Values is an array of enums_ ✅ vs _Values is an array of string and an enum_ ❌ 

May be we can get clarification [from OAS](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#items-object)?

**Comment by smwurster** [comment]
Hmmm.  The Schema definition also contains "enum", which is probably why for a single value with allowable values we get something like this:

```
"someValue": {
    "type": "string",
    "description": "asdf",
    "enum": [
        "foo",
        "bar"
    ]
}
```

So which is correct?

If there's a bug in the UI portion, could you fix it in your version, or do you just pull that directly from an external source?

**Comment by dilipkrish** [comment]
[It is a bug](https://github.com/swagger-api/swagger-core/issues/375) in the ui. However I don't maintain the ui libraries, just a mirror with slight modifications.

**Comment by smwurster** [comment]
Ah, looks like they fixed it in the spec, but Swagger Core hasn't caught up.

I wonder if I could work around this with a local fork...
