### ISSUE TITLE
Swagger UI cannot load static resources behind nginx 

### ISSUE THREAD

**Issue by mariomatar** [springfox/springfox#1330]
Hi, 

I use a jar Spring Boot application behind nginx 

On local host Swagger UI works fine

The configuration is : 

  upstream back {
        server localhost:8080;
  }
  server {
        listen 80 default_server;

        server_name app.com;

        location / {
                    proxy_set_header Host               $host;
                    proxy_set_header X-Real-IP          $remote_addr;
                    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Host   $host;
                    proxy_set_header X-Forwarded-Server $host;
                    proxy_set_header X-Forwarded-Proto  $scheme;

                proxy_pass          http://back;
       }

  }

My java swagger config is 

    @Configuration
    @EnableSwagger2
    public class SwaggerConfig {
    
    
        @Bean
        public ApiInfo apiInfo() {
            return new ApiInfoBuilder()
                    .title("APP API")
                    .description("APP REST API Documentation")
                    .termsOfServiceUrl("http://www.app.com")
                    .contact("ME")
                    .license("private")
                    .licenseUrl("")
                    .version("1.0")
                    .build();
        }
    }

And look at the picture, resources are load at server_name/swagger-ui.html/resource 
instead of  server_name/resource 

![screenshot 2016-05-27 17 01 24](https://cloud.githubusercontent.com/assets/1669985/15611984/2ee7f588-242d-11e6-999d-eab9e104499c.png)

**Comment by dilipkrish** [comment]
Could you try with 2.4.1-SNAPSHOT, this may have been fixed

**Comment by mariomatar** [comment]
It works with 2.4.1-SNAPSHOT !
thanks

**Comment by mariomatar** [comment]
I was wrong, it's not works

**Comment by dilipkrish** [comment]
@mariomatar what is not working... would be great to get a PR if you've identified what the problem is cos' frankly I don't have the expertise with nginx.

**Comment by mariomatar** [comment]
The URL is wrong for loading resources
http://my.server/swagger-ui.html/webjars/springfox-swagger-ui/lib/jquery-1.8.0.min.js

**Comment by dilipkrish** [comment]
I think that may be a problem with your nginx configuration

**Comment by victorfu** [comment]
Edit your nginx configuration and add the following setup:

        location /webjars {
                proxy_pass         http://localhost:8080; #change to your port
                proxy_redirect     off;

                proxy_set_header   Host              $host;
                proxy_set_header   X-Real-IP         $remote_addr;
                proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto $scheme;
        }

**Comment by dilipkrish** [comment]
@victorfu thanks for the answer! 🙇

**Comment by radishlee** [comment]
@victorfu thank you  it works for me
