### ISSUE TITLE
Unable to access springfox api-docs URL

### ISSUE THREAD

**Issue by shubhendu-shekhar** [springfox/springfox#1336]
A portion of my web.xml looks like this

	<filter>
        <filter-name>springSecurityFilterChain</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>springSecurityFilterChain</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

	
	<servlet>
		<servlet-name>model</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<init-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>*</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>

	<servlet-mapping>
		<servlet-name>model</servlet-name>
		<url-pattern>/</url-pattern>
	</servlet-mapping>

After following the tutorial at [http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api](http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api), I tried accessing the api-docs URL but I keep getting HTTP Status 500 - Missing or invalid Authorization header. I'm extremely new to Spring and Swagger. Please help!

**Comment by dilipkrish** [comment]
You're not sending in the the authentication/authorization error. try disabling the `springSecurityFilterChain` section

**Comment by dilipkrish** [comment]
Alison that article I don't see any `web.xml`

**Comment by shubhendu-shekhar** [comment]
Can't I do it with `springSecurityFilterChain` setting on?

**Comment by shubhendu-shekhar** [comment]
Also my WebSecurityConfig file's configure function looks like this.

```
@Override
	protected void configure(HttpSecurity httpSecurity) throws Exception {
		httpSecurity
		.csrf()
			.disable()
		.exceptionHandling()
			.authenticationEntryPoint(this.unauthorizedHandler)
			.and()
		.sessionManagement()
			.sessionCreationPolicy(SessionCreationPolicy.STATELESS)
			.and()
		.authorizeRequests()
			.antMatchers("/auth/login", "/auth/logout").permitAll()
			.antMatchers("/api/**").authenticated()
			.anyRequest().authenticated();

		// custom JSON based authentication by POST of {"username":"<name>","password":"<password>"} which sets the token header upon authentication
		httpSecurity.addFilterBefore(loginFilter(), UsernamePasswordAuthenticationFilter.class);

		// custom Token based authentication based on the header previously given to the client
		httpSecurity.addFilterBefore(new StatelessTokenAuthenticationFilter(tokenAuthenticationService), UsernamePasswordAuthenticationFilter.class);
	}
```

**Comment by dilipkrish** [comment]
My recommendation is to first try and see if everything is configured correctly without any security. And then work yourself back to your desired end state.
