### ISSUE TITLE
How to override @RequestBody annotated method parameter Model Schema  definition

### ISSUE THREAD

**Issue by licc** [springfox/springfox#1342]
Hello
Im using the 2.5.0 version.
spring boot 1.3.5

I just want to show   {account ; password}

so use
**@ApiParam>@Example    but is   not work?  why?**

 ```java 
@RequestMapping(value = "/login", method = {RequestMethod.POST})
    public SealResult<User> login(@Validated @RequestBody @ApiParam(value = "user",
            examples = @Example(value = {
                    @ExampleProperty(mediaType = "application/json", value = "{\"account\": \"aaa\",\"password\": \"1234\"}")
            })) User user, HttpServletRequest request) {
        User userModel = userService.findModel(user);
        return SealResult.createSealResult(userModel).setCode(ObjectUtils.isEmpty(userModel) ?
                StatusCode.ERROR_LOGIN_FAIL : StatusCode.OK);
    }
```

**Comment by dilipkrish** [comment]
@licc examples are not supported everywhere -> #853.

**Comment by evser** [comment]
Doesn't work for 2.6.0:

	@PostMapping
	public Driver createDriver(@RequestBody @ApiParam(examples = @Example({ @ExampleProperty("{\n" +
			"  \"car\": {\n" +
			"    \"model\": \"Nissan\",\n" +
			"    \"seatsCount\": 4,\n" +
			"    \"vehicleNumber\": \"7777-7\"\n" +
			"  },\n" +
			"  \"contacts\": [\n" +
			"    {\n" +
			"      \"contactType\": \"skype\",\n" +
			"      \"data\": \"mySkype\"\n" +
			"    }\n" +
			"  ],\n" +
			"  \"email\": \"ee@ee.ee\",\n" +
			"  \"firstName\": \"FirstName\",\n" +
			"  \"lastName\": \"LastName\",\n" +
			"  \"homeLocation\": {\n" +
			"    \"address\": \"Street st.\",\n" +
			"    \"coordinate\": {\n" +
			"      \"latitude\": \"11\",\n" +
			"      \"longitude\": \"11\"\n" +
			"    }\n" +
			"  },\n" +
			"  \"interests\": [\n" +
			"    {\n" +
			"      \"description\": \"Films\"\n" +
			"    }\n" +
			"  ],\n" +
			"  \"jobTitle\": \"Engineer\",\n" +
			"  \"office\": {\n" +
			"    \"id\": 1\n" +
			"  }\n" +
			"}") })) Driver driver) {
		return userService.save(driver);
	}

**Comment by evser** [comment]
![image](https://cloud.githubusercontent.com/assets/11527468/19554875/2a1463ee-96c3-11e6-86f1-55f3f56ebccd.png)
