### ISSUE TITLE
Using Map<Enum,Object> in model response 

### ISSUE THREAD

**Issue by burnaz** [springfox/springfox#1343]
Hi, I searched for several hours about this problem and I didn't find any solution, I just want to be sure it hasn't support yet.

I would like to return `ResponseEntity<Map<Season, LeagueDto>>`. `Season` is ENUM and `LeagueDto` is an object -` Map<Enum, Object>`.

I tried to use "Map" in responseContainer but didn't work.
`@ApiOperation(value = "Get leagues by summoner id", response = LeagueDto.class, responseContainer = "Map")`

![image](https://cloud.githubusercontent.com/assets/7516541/15993497/b3fc43bc-30be-11e6-97f5-f74379bf3d6c.png)

JSON hasn't attribute "type: map" in response. I tried to use "Map[Season,LeagueDto]", but didn't work too.
`@ApiOperation(value = "Get leagues by summoner id", response = LeagueDto.class, responseContainer = "Map[Season,LeagueDto]")`

I appreciate any help and support. Thanks very much.

**Comment by dilipkrish** [comment]
@burnaz what happens if you remove the `@ApiOperation#response` and `@ApiOperation#responseContainer`? It should generate a `Map<string, LeageDTO>`

**Comment by burnaz** [comment]
@dilipkrish I tried to return Response<Map<Enum, LeagueDto>>, Map<Enum, LeagueDto> and Map<String, LeagueDto> without `response` and `responseContainer`, the result is an empty model and model schema.

![image](https://cloud.githubusercontent.com/assets/7516541/16006064/4d9e8a34-3141-11e6-8874-977cfb21bd66.png)

I tested on version 2.4.0 and 2.5.0

**Comment by dilipkrish** [comment]
What does clicking *Model Schema* look like? Better still what does the operation look like in json?

**Comment by burnaz** [comment]
I removed `response `and `responseContainer` and tested the following returns:

`return Response<Map<Enum, LeagueDto>>`

![response-map](https://cloud.githubusercontent.com/assets/7516541/16025779/f3d51022-319f-11e6-92b1-e971dcf1b7a3.png)

`return Response<Map<String, LeagueDto>>`

![response-map](https://cloud.githubusercontent.com/assets/7516541/16025785/033ad902-31a0-11e6-9f00-62c04f7421a9.png)

`return Map<Enum, LeagueDto>`

![map-season](https://cloud.githubusercontent.com/assets/7516541/16025799/17e51e80-31a0-11e6-8caa-3d6a3dc265f1.png)

`return Map<String, LeagueDto>`

![map-season](https://cloud.githubusercontent.com/assets/7516541/16025810/24acdb94-31a0-11e6-9a26-2b0ce57712ad.png)
