### ISSUE TITLE
@ApiImplicitParam is not resolving class of the dataType correctly

### ISSUE THREAD

**Issue by psivolob** [springfox/springfox#1344]
I am using swagger version 2.50

```
@ResponseBody
@ApiImplicitParam(name = "account", value = "new account",
        dataType = "com.company.model.Account", paramType = "body")
public Account createAccount(HttpServletRequest request) throws IOException {
       ...
}
```

The value in the dataType is the name of the class. Class.forName() should be able to resolve it. However in the swagger output it simply says that dataType is **string**
What I am doing wrong? Is that a bug?

**Comment by shildondu** [comment]
Is it fixed?

**Comment by dilipkrish** [comment]
ApiImplicitParams are supposed to be used for headers, cookies (parameters that are implicit). As a result it only supports scalar types and for simplicity they are always `string.

**Comment by andrew-garland** [comment]
@dilipkrish I added implicit parameter of type cookie and this creates a usable field in embedded swagger-ui.  So far, so good.

However, if i export the definition and import to editor.swagger.io, it complains that the parameter is not valid.  relevant piece of swagger yaml is:

```yaml
 parameters:
        - name: XSRF-TOKEN
          in: cookie
          required: false
          type: string
          format: uuid
```

Note that http://23.22.16.221/v2/schema.json# has a reference schema that includes the following definition:

```json
"nonBodyParameter": {
"type": "object",
"required": [
"name",
"in",
"type"
],
"oneOf": [
{
"$ref": "#/definitions/headerParameterSubSchema"
},
{
"$ref": "#/definitions/formDataParameterSubSchema"
},
{
"$ref": "#/definitions/queryParameterSubSchema"
},
{
"$ref": "#/definitions/pathParameterSubSchema"
}
]
},
```

Was cookie parameter dropped or was it never supported officially?

**Comment by dilipkrish** [comment]
Perhaps cookies aren't supported in editor.swagger.io. It is supported in the spec for sure
