### ISSUE TITLE
@ApiIgnore is not respected on a method (2.5.0-SNAPSHOT)

### ISSUE THREAD

**Issue by ben-pearson** [springfox/springfox#1346]
We have a few method parameters we ignore:

```
public List<Stuff> doStuffAndShow( @ApiIgnore User user, @ApiIgnore AnotherProvidedParam param2 )
{ ... }
```

Previously we could annotate these with @ApiIgnore and now it seems to be ignored.

**Comment by dilipkrish** [comment]
I don't think that has ever been true.

**Comment by givenuponlife** [comment]
It works in version 2.4.0. I've rolled back to keep it working for now.

**Comment by longbe00** [comment]
It is same as our project. 
it was working in version 2.4.0 but it doesn't work when we have updated lib version 2.5.0 .
we can't roll back because of  processing multipart file.
please check this.

**Comment by longbe00** [comment]
I figured out about it.
Defaults class in springfox.documentation.spi.service.contexts  on version 2.4.0  included this code.
Defaults.java
=======================
private void initIgnorableTypes() {
    ignored = newHashSet();
    ignored.add(ServletRequest.class);
    ignored.add(Class.class);
    ignored.add(Void.class);
    ignored.add(Void.TYPE);
    ignored.add(HttpHeaders.class);
    ignored.add(ServletResponse.class);
    ignored.add(HttpServletRequest.class);
    ignored.add(HttpServletResponse.class);
    ignored.add(HttpHeaders.class);
    ignored.add(BindingResult.class);
    ignored.add(ServletContext.class);
    ignored.add(UriComponentsBuilder.class);
    **ignored.add(ApiIgnore.class);**
  }
=================
but  it on version 2.5.0  excluded ApiIgnore.class

==================
  private void initIgnorableTypes() {
    ignored = newHashSet();
    ignored.add(ServletRequest.class);
    ignored.add(Class.class);
    ignored.add(Void.class);
    ignored.add(Void.TYPE);
    ignored.add(HttpHeaders.class);
    ignored.add(ServletResponse.class);
    ignored.add(HttpServletRequest.class);
    ignored.add(HttpServletResponse.class);
    ignored.add(HttpHeaders.class);
    ignored.add(BindingResult.class);
    ignored.add(ServletContext.class);
    ignored.add(UriComponentsBuilder.class);
  }

Did you remove it from  source code. on purpose? 

i'm supposed  that it could work well if you rollback that code.

**Comment by dilipkrish** [comment]
@givenuponlife you are correct. It is a regression. For now the work around is to add it back via the Docket.

```java 
       docket.ignoredParameterTypes(ApiIgnore.class)
```

**Comment by longbe00** [comment]
i appreciate your fast feedback.
