### ISSUE TITLE
POST with ResponseEntity<InputStreamResource> not shown correctly in swagger-ui

### ISSUE THREAD

**Issue by helt** [springfox/springfox#1347]
I have a spring-boot app with springfox 2.5.0 running.

The `@RequestMapping` is responsible for generating an `image/PNG` out of a rather complex parameter-set. Thats why the parameters are `POST`-ed to the resource. as result, the image is transmitted in the `ResponseBody`

This approach works, when I use postman, or use the resource in my actual webapplication frontend. However, swagger does something strange:

a) the result image is the default "browser-didnt-find-an-image-at-this-url" image 
b) in the console, swagger POSTs the correct request, but then triggers a subsequent GET on the same address which is not bound:
![swagger-bug](https://cloud.githubusercontent.com/assets/1732112/16151754/fd8a7416-349e-11e6-8fe0-742a9047dcc1.png)

Here is the concrete RequestMapping:
```
  @RequestMapping(path = "getImage", method = RequestMethod.POST, produces = MediaType.IMAGE_PNG_VALUE)
  public ResponseEntity<InputStreamResource> getImage(@RequestBody ImageParameters parameters) throws IOException {

    final BufferedImage image = rendererService.getImage(parameters);
    final File tempFile = File.createTempFile("image-", ".png");
    final FileOutputStream oos = new FileOutputStream(tempFile);
    final ImageOutputStream imageOutputStream = new MemoryCacheImageOutputStream(oos);
    ImageIO.write(image, "PNG", imageOutputStream);
    imageOutputStream.close();
    oos.close();

    // construct baseUri for image and add to headers

    return ResponseEntity.ok().contentLength(tempFile.length())
        .contentType(MediaType.IMAGE_PNG)
        .header("filename", tempFile.getAbsolutePath())
        .body(new InputStreamResource(new FileInputStream(tempFile)));
  }
```

Any thoughts on that one? I dont know whether its springfox or swagger-ui or me who is doing things wrong (apart from "you should respond with 201 and add the location header for the actual image")

**Comment by helt** [comment]
Okay. It appears like swagger-ui simply inserts a `<img>` tag into the response body area which obviously doesnt know anything about the fact that it should POST to the address.

Would make sense to insert the POST response body into the `<img>`-tag as base64-encoded image, right?

**Comment by dilipkrish** [comment]
Is this perhaps a [swagger-ui](https://github.com/swagger-api/swagger-ui) issue?

**Comment by helt** [comment]
I created an issue in the swagger-ui project: https://github.com/swagger-api/swagger-ui/issues/2226
