### ISSUE TITLE
Attempting to integrate Swagger within Virgo OSGI container

### ISSUE THREAD

**Issue by jayhamilton** [springfox/springfox#135]
I have moved swagger-springmvc version 0.53 to OSGI. I have a Web Archive Bundle (WAB)  running inside of an OSGI container called Virgo. I have gotten this version of swagger-springmvc to run within a non-OSGI war file successfully. Reading an older issue, I understand that you guys have not done much work with OSGI so I am not expecting a definitive answer here. I am just looking for hints at how I can troubleshoot this issue. 

I have the swagger properties file pointing to a base url where the DispatchServlet is expected to be. OSGI requires the root web context path to be placed in the manifest of the jar file containing the spring mvc app. So this path is in the form of /api/something/endpoint.  The web.xml request mapping has the generic url pattern of /*. 

So a request coming into the api takes on the forms of http://localhost:port/api/something/endpoint. This is defined in the swagger.properties file. 

I get 404 when running  http://localhost:port/api/something/endpoint/api-docs. This tells me that the controller serving api-docs has not been created. I see no errors during startup and when executing http://localhost:port/api/something/endpoint/api-docs i see in the log or console lines indicating RequestMappingHandlerMapping is getting executed on my controller that includes my api(endpoint) so I see 
Mapped "{[/..... onto ...
lines. I also see these lines in my non-osgi example as well. However what I don't see, which is another indication that the controller serving api-docs is not available, is lines resembling:
Mapped "{[/api-docs..... onto ...
which I do see in my working (non-OSGI) version. 

So my suspicion is that the controller bean is not being created where it is expected. I also get a No mapping found for HTTP request with URI [/api/something/endpoint/api-docs] in DispatchServlet with name 'servler name'.

There seems to be a disconnect between my web.xml request mapping, swagger base url and my context root as defined in the jar's manifest.

**Comment by shanmukhm** [comment]
Hi @jayhamilton do you have Springfox bundle uploaded anywhere? I really need it right now

**Comment by shanmukhm** [comment]
@jayhamilton And also were you able to fix the problem finally? Because I want to use Springfox as a bundle in Felix container.
