### ISSUE TITLE
Any way to rebuild the docs while process is running?

### ISSUE THREAD

**Issue by ericxiong** [springfox/springfox#1351]
Release 2.5.0

Is there any way rebuild the docs while process is running?
I use jrebel to auto reload classes, the api path or param changed without restarting the process. 
But swagger docs can not update unless restart the program.

**Comment by dilipkrish** [comment]
Assuming there is a way to react to `reloading` the classes, you can reference the `DocumentationPluginsBootstrapper` as a bean and `stop` and `start` when you reload your classes. My understanding is that if jrebel triggers a spring context refresh, it should just work.

**Comment by yanzhenyu** [comment]
@dilipkrish hi，Why didn't swagger parameters change after I stopped starting.
![image](https://user-images.githubusercontent.com/11738089/49126359-3df6ce80-f2fe-11e8-8d7a-be909da0ed86.png)

**Comment by dilipkrish** [comment]
What were you expecting to change @yanzhenyu ?

**Comment by yanzhenyu** [comment]
![image](https://user-images.githubusercontent.com/11738089/49144110-8088cd00-f337-11e8-8b80-835adc47738b.png)
![image](https://user-images.githubusercontent.com/11738089/49144123-8a123500-f337-11e8-83e6-dc252179370f.png)
when i just add another parameter，swagger docs can't update
@dilipkrish

**Comment by dilipkrish** [comment]
It will not unless it has had a chance to reload the new binaries... assuming you're trying to do a hot reload

**Comment by yanzhenyu** [comment]
![image](https://user-images.githubusercontent.com/11738089/49192712-3c3d1180-f3b7-11e8-82c6-cb0a51a1a8c5.png)
When I recompiled, I triggered the updateSwagger method, but it didn't work, swagger docs can't update
