### ISSUE TITLE
Does Springfox 2.5.0 support Jersey Controller?

### ISSUE THREAD

**Issue by eyaqub** [springfox/springfox#1352]
Hi, I have a scenario similar to [1]. It seems Springfox is not able to support Jersey Controllers. Can you please comment? Thanks

[1] http://stackoverflow.com/questions/37640863/springfox-swagger-no-api-docs-with-spring-boot-jersey-and-gardle

**Comment by dilipkrish** [comment]
Here is the [answer I posted](http://stackoverflow.com/a/38004323/19219)
