### ISSUE TITLE
RequestParam with a map crashes swagger-ui

### ISSUE THREAD

**Issue by BryceMehring** [springfox/springfox#1353]
When adding `@RequestParam Map<String, String> params` to an endpoint, swagger-ui throws: `Uncaught TypeError: Cannot read property 'type' of undefined`. This works in version 2.4.0

- Version 2.5.0

**Comment by dilipkrish** [comment]
I researched this and I've added an [issue in the swagger-ui project](https://github.com/swagger-api/swagger-ui/issues/2241).
