### ISSUE TITLE
springfox swagger ui returning 404 for valid resource

### ISSUE THREAD

**Issue by soumeny2k** [springfox/springfox#1354]
Hi,

I am getting 404 for valid resource request using swagger. Swagger is failing and returning me 404, while Postman is returning the result.
The parameter for which swagger is failing is the authDtls, I have to pass a json in this parameter, if I pass json then it's failing with 404, but working fine with a non json input.
I am using springfox swagger ui version 2.5.0

Is this a bug in swagger or springfox?

**Swagger Json:**

    "/swaggerIssueReproduce": {
			"post": {
				"tags": ["preview-integration-controller"],
				"summary": "swaggerIssueReproduce",
				"operationId": "swaggerIssueReproduceUsingPOST",
				"consumes": ["multipart/form-data"],
				"produces": ["application/json"],
				"parameters": [{
					"name": "sourceArchive",
					"in": "formData",
					"description": "sourceArchive",
					"required": true,
					"type": "file"
				}, {
					"name": "authDtls",
					"in": "query",
					"description": "authDtls",
					"required": true,
					"type": "string"
				}, {
					"name": "mode",
					"in": "query",
					"description": "mode",
					"required": false,
					"type": "string"
				}],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"type": "string"
						}
					}
				}
			}
		}

**Spring Controller:**

    @RequestMapping(value= "/swaggerIssueReproduce", method = RequestMethod.POST,
            consumes = { MediaType.MULTIPART_FORM_DATA_VALUE },
            produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> swaggerIssueReproduce(
            @ApiParam(required = true)
                    MultipartFile sourceArchive,
            @RequestParam
                    String authDtls,
            @RequestParam(required = false)
                    String mode
    ) {
        LOG.info(" sourceArchive ###################" + sourceArchive);
        LOG.info(" authDtls ###################" + authDtls);
        LOG.info(" mode ###################" + mode);
        return new ResponseEntity<String>("{\"_id\":\"Hello World\"}", HttpStatus.OK);
    }

**Comment by dilipkrish** [comment]
> I am getting 404 for valid resource request using swagger. Swagger is failing and returning me 404, 

when you do what? swagger-ui? curl?

Change the `consumes = { MediaType.MULTIPART_FORM_DATA_VALUE },` to `consumes = { MediaType.APPLICATION_JSON_VALUE },` and it should work

**Comment by soumeny2k** [comment]
I am getting that error when use swagger ui. I can't use  consumes = { MediaType.APPLICATION_JSON_VALUE }, as I have to send a file. Using application/json giving me 415.

**Comment by dilipkrish** [comment]
@soumeny2k In that case add a message converter to handle `application/json`
