### ISSUE TITLE
How do I configure springfox so that it doesnt generate its own documentation for APIs?

### ISSUE THREAD

**Issue by LMCGOW200** [springfox/springfox#1358]
Hi, 

I have provided my own custom documentation for the individual parameters in my REST API using the "@ApiImplicitParams" annotation, however when I run the application and view the docs in swagger UI, I can see my own definition and the default definition generated by springfox. This means I end up having two definitions in the docs for a single parameter. Is there any way to force springfox to only use my own custom definition and not generate its own?

I am using version 2.0.1

**Comment by dilipkrish** [comment]
First off, please use [the latest version 2.5.0](https://github.com/springfox/springfox/blob/master/.github/ISSUE_TEMPLATE.md) and see if that fixes your problem. Secondly `@ApiImplicitParams` are to use used when the parameters are _implicit_. If you want to add documentation to a param, Id recommend using `@ApiParam` instead

**Comment by LMCGOW200** [comment]
Ok. Thanks.
