### ISSUE TITLE
Swagger-ui 2.5.0 API documentation is not visible.

### ISSUE THREAD

**Issue by codebusta** [springfox/springfox#1362]
I just upgraded to swagger-ui 2.5.0, i was using 2.4.0. When I run my spring boot application, the documentation is not visible anymore at localhost/#/docs. I looked at the network requests, one call is responding as 404 not found:

Request URL:http://localhost/configuration/ui
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:80

But when I downgrade to 2.4.0 and gradle rebuild, the documentation is back, and the above call is successful. 

Here is my gradle dependency:

compile("io.springfox:springfox-swagger2:2.5.0") {
        exclude module: 'mapstruct'
}

Can you help me with this one, as I need the fixes from this new release. Thank you.

**Comment by dilipkrish** [comment]
What version of swagger-ui are u using? Try clearing the browser cache?

**Comment by codebusta** [comment]
What do you mean? Isn't the following dependency mean that I'm using swagger-ui 2.5.0 ?

compile("io.springfox:springfox-swagger2:2.5.0") {
exclude module: 'mapstruct'
}

**Comment by dilipkrish** [comment]
No you need to have the latest `springfox-swagger-ui` dependency as well.

**Comment by codebusta** [comment]
Oh well, let me try it now.

**Comment by codebusta** [comment]
Bu howcome I was able to use it without springfox-swagger-ui, just this below:
compile("io.springfox:springfox-swagger2:2.4.0") {
exclude module: 'mapstruct'
}

**Comment by codebusta** [comment]
I did include springfox-swagger-ui dependency, but no luck. The dependency is as follows:
compile("io.springfox:springfox-swagger2:2.5.0") {
        exclude module: 'mapstruct'
    }
    compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.5.0'

**Comment by codebusta** [comment]
The swagger config class is annotated as following:

@Configuration
@EnableSwagger2
@Profile("!" + Constants.SPRING_PROFILE_NO_SWAGGER)
@ConditionalOnProperty(prefix="jhipster.swagger", name="enabled")
public class SwaggerConfiguration {

**Comment by dilipkrish** [comment]
Ah you're using jhipster! The generator needs to be updated

**Comment by dilipkrish** [comment]
In the man time u can work around this by replacing `/configuration/ui` With /swagger-resources/configuration/ui`  You would need to do the same for /configuration/security`

**Comment by codebusta** [comment]
Sweet, thank you! It worked. I only included swagger2 dependency, no need to included swagger-ui.
