### ISSUE TITLE
Question: How to add query parameters to documentation when using HandlerMethodArgumentResolver and no RequestParam annotation

### ISSUE THREAD

**Issue by SundeepK** [springfox/springfox#1363]
Hi, I've been reading through documention but was unable to find any advice on how to show query parameters in api documention when the `@RequestMapping` method doesn't contains any `@RequestParam` annotation. But instead is a an object generated via using an `HandlerMethodArgumentResolver` which intercepts the incoming parameters and creates an object out of it. More concrectly, here's a generic dumb down example:

```java 
class PetHandlerMethodArgumentResolver implements HandlerMethodArgumentResolver {
    PetHandlerMethodArgumentResolver() {
    }

    @Override
    boolean supportsParameter(final MethodParameter parameter) {
        return Pet.class.equals(parameter.getParameterType());
    }

    @Override
    Object resolveArgument(
            final MethodParameter parameter,
            final ModelAndViewContainer mavContainer,
            final NativeWebRequest webRequest, final WebDataBinderFactory binderFactory) throws Exception {
        final Map<String, String[]> parameterMap = webRequest.getParameterMap()
        return new PetQueryFilters(parameterMap)
    }
}
``` 
Where `PetQueryFilters` might be:

```java
class PetQueryFilters {
     long height;
     long age;
     long pageNumber;
     String sort;
    //etc
}
```
Then you can set that up in the WebConfig and use it like below:

```java
@RequestMapping(value = "/pets", method = RequestMethod.GET)
    Pets pets(PetQueryFilters petQueryFilters, HttpServletResponse response) {
        return petsResource.doSomethingWithQueryFilters(petQueryFilters);
    }
```
As you can see from above example, the request params that would normally be annotated with `@RequestParam` is just an object. But, the documentation generated doesn't show the query fitlers suported/field of the `PetQueryFilters` class. Instead, it shows `petQueryFilters` as the only request parameter with type `PetQueryFilters`. 

Is there any way to generate documentation for the actual fields of the `PetQueryFilters` class, which would actually be the parameters? I should also add, I'm looking to convert the field from `PetQueryFilters` to snake_case.

im using the below version in gradle:
'io.springfox:springfox-swagger2:2.4.0'
'io.springfox:springfox-swagger-ui:2.4.0'

**Comment by dilipkrish** [comment]
@SundeepK It seems to me that for this use case you're better off adding a `@ModelAttribute` annotation and not even needing an argument resolver.

**Comment by SundeepK** [comment]
Thanks @dilipkrish. I've previously tried the `@ModelAttribute`, but unfortunatly my request prameters are in snake_case and the only way I've been able to get that to work is to have the domain object in snake_case format (which doesn't follow java conventions). Is there a way of getting the class to still be in camelCase but accept snake_case request prameters and have it show in the documentation as snake_case?

I think I've set up `ObjectMapper` corrrectly since my response objects have camelCase fields and it shows correctly in the swagger documentation and in the response body. I can share my `ObjectMapper` setup code if it will help, thanks.

**Comment by dilipkrish** [comment]
1. Upgrade to 2.5.0

Option 1 to try.
1. Add model attribute
2. Create a `PetQueryFiltersMixin` class with the getters and setters that are snake cased
3. Add an alternate type rule to map `PetQueryFilters` to `PetQueryFiltersMixin`

Option 2 to try
1. Add `PetQueryFilters` to the list of ignorables
2. Annotate your operation with `@ApiImplicitParams` and manually declare your expected params

**Comment by SundeepK** [comment]
Thanks, I've basically gone for option one in this case.

**Comment by gsbtech** [comment]
I had a similar situation, but resorted to use a ServletModelAttributeMethodProcessor.
What is "alternate type rule" in 
 (Option 1) Add an alternate type rule to map PetQueryFilters to PetQueryFiltersMixin

**Comment by dilipkrish** [comment]
@gsbtech in your docket you can add a rule 

```java
AlternateTypeRules.newRule(
typeResolver.resolve(PetQueryFilters.class), 
typeResolver.resolve(PetQueryFiltersMixin.class));
```

[The docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) have more info

**Comment by gsbtech** [comment]
Thank you.
