### ISSUE TITLE
response status 200 enum model schema not displayed

### ISSUE THREAD

**Issue by danny95djb** [springfox/springfox#1366]
I'm using springfox 2.5.0 and springfox 2.5.0 swagger-ui. I'm unable to get an enum displayed as the model schema in the response code section. The json generated is as follows.

`"responses":{  
               "200":{  
                  "description":"OK",
                  "schema":{  
                     "type":"string",
                     "enum":[  
                        "SUCCESS",
                        "FAILED"
                     ]
                  }
               },`

but nothing appears, not even the OK description.

**Comment by dilipkrish** [comment]
The json looks just like its supposed to look. When you say you're unable to "_get the enum to display_", what do you mean?

**Comment by danny95djb** [comment]
@dilipkrish i mean the model schema for that enum is not being displayed. Also the ok description part isn't displayed above

**Comment by dilipkrish** [comment]
I think thats a [swagger-ui](https://github.com/swagger-api/swagger-ui) problem. you might want to create an issue there.

**Comment by danny95djb** [comment]
ok thank you, wasn't sure where to post this.
