### ISSUE TITLE
model properties missing for RequestBody object

### ISSUE THREAD

**Issue by chip-rosenthal** [springfox/springfox#1368]
Springfox version: 2.5.0
Issue type: bug report

For the following endpoint:

    @RequestMapping(path = "/{id}/elements", method = POST, consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> associateElement(
        @PathVariable("id") final String id,
        @RequestBody final ElementReferenceEntity element
    ) {
        .
        .
        .
    }

Swagger UI shows an empty Model Schema {} for the "element" parameter:
![image](https://cloud.githubusercontent.com/assets/1208924/16422388/cfb753d8-3d1d-11e6-8b60-10cec9ae2996.png)

The generated Swagger spec shows:

    ElementReferenceEntity: {
        type: "object"
    },

The ElementReferenceEntity datatype isn't used anywhere else in the project.

If I add a dummy endpoint:

    @RequestMapping(path = "/ElementReferenceEntity", method = GET)
    @ApiOperation(value = "", hidden = true)
    public ElementReferenceEntity swaggerWorkaroundElementReferenceEntity() {
        return null;
    }

Now Swagger UI is correct:
![image](https://cloud.githubusercontent.com/assets/1208924/16422527/5a64f260-3d1e-11e6-9da5-2ea40eabb136.png)

as is the Swagger spec:

    ElementReferenceEntity: {
      type: "object",
      properties: {
        connector: {
          type: "string"
        },
       identifiers: {
          type: "object",
          additionalProperties: {
            type: "string"
          }
        }
      }
    }

The ElementReferenceEntity is defined in another jar and has no Swagger or Spring annotations.

**Comment by dilipkrish** [comment]
@chip-rosenthal Thats probably because the model `ElementReferenceEntity` doesn't have any setters nor `@JsonCreator` annotated constructors.

**Comment by chip-rosenthal** [comment]
Yes, that's correct. It's using the org.immutables:value package.

Here's the model:

    @Value.Immutable
    @JsonSerialize(as = ImmutableElementReferenceEntity.class)
    @JsonDeserialize(as = ImmutableElementReferenceEntity.class)
    public interface ElementReferenceEntity {
        String getConnector();
        Map<String, String> getIdentifiers();
    }

Is there any chance the @JsonDeserialize annotation can be handled? It points to ImmutableElementReferenceEntity, which is where the setter methods are.

**Comment by chip-rosenthal** [comment]
It keeps the controller method from modifying the object parameters.

Thanks for the quick response on the issue.
