### ISSUE TITLE
@RequestHeader for Object has 'undefined' as dataType

### ISSUE THREAD

**Issue by soupy989** [springfox/springfox#1374]
Library Version: 2.5.0

Issue:
I have been trying to get an example model to show for a RequestHeader variable.
![image](https://cloud.githubusercontent.com/assets/11248759/16598266/a4c634e6-42c2-11e6-8194-162cfd86e991.png)
When I annotate Restrictions using @RequestHeader as shown above, I get the following result in the swagger-ui page. I have set the 'supportHeaderParams' field to true in the SwaggerUi object.
![image](https://cloud.githubusercontent.com/assets/11248759/16598308/de1f5646-42c2-11e6-8d38-64b4eda16cd7.png)

Should I try to force it using ApiImplicitParams() and a dataType of 'Restrictions,' the dataType defaults to string. This happens with the full path of the object as the dataType.

My question is how can I have a RequestHeader object that allows for example model population like the @RequestBody objects? Being able to have a model example or a pre-populated field with formatting for a RequestHeader  is absolutely necessary for my current project, so any assistance would be greatly appreciated.

**Comment by dilipkrish** [comment]
Really you're trying to tunnel a json payload in a header which is always a string. You could perhaps give it an example but schema support will not be there for headers.

**Comment by soupy989** [comment]
Thanks for the response/info, I'll either add some jquery to the swagger index or write the api-documentation separate swagger for these specific actions.
