### ISSUE TITLE
How to hide Locale parameter from swagger-ui ?

### ISSUE THREAD

**Issue by hidekuro** [springfox/springfox#1375]
How to hide locale (and any other spring optional parameters) from swagger-ui ?
I'm looking for Annotations properties like "hidden".
but `@ApiImplicitParam` does not has "hidden" attribute.

**Comment by dilipkrish** [comment]
Where is the local defined. If its a parameter just use the `@ApiParam#hidden`

**Comment by hidekuro** [comment]
@dilipkrish thanks for reply.

The `Locale` parameter defined at last of Controller methods parameters. besides this, there is such as `BindingResult`.

their is supplied by spring mvc if defined in method args list. and neccesary to my programs.
but I won't to display in swagger-ui.

I think `@ApiParams` for JAX-RS. I don't use it.

any ides?

**Comment by dilipkrish** [comment]
You can add those types `Locale`, `BindingResult` to the ignorableTypes in your docket

**Comment by SujithaC** [comment]
@hidekuro Did you get it solved? If yes, could you please share here the solution?
