### ISSUE TITLE
AlternateTypeRules outputs unresolved #ref

### ISSUE THREAD

**Issue by mikerott** [springfox/springfox#1376]
Version:

    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger2</artifactId>
        <version>2.4.0</version>
    </dependency>

Partial code snippet:

    return new Docket(DocumentationType.SWAGGER_2)
        // we want Swagger to describe URL types as String:
        .alternateTypeRules(AlternateTypeRules.newRule(URL.class, String.class));

In the places I use a `java.net.URL`, the swagger api-docs JSON (partial) output shows:

    "$ref": "#/definitions/URL"

This is a problem because there is no `URL` generated among the `definitions`.  So when I try to consume the JSON into a swagger codegen tool (like http://editor.swagger.io/#/) it complains:

    code:  "UNRESOLVABLE_REFERENCE"
    message:  "Reference could not be resolved: #/definitions/URL"
    error: "JSON Pointer points to missing location: #/definitions/URL"

My current workaround is to hand-code something like `"URL":{"type":"string"}` among the `definitions`.

Is my use of `alternateTypeRules` correct?  Should SpringFox be outputing `"type": "string"` instead of `"$ref": "#/definitions/URL"`?  Should SpringFox be generating `"URL":{"type":"string"}` among the `definitions`?

**Comment by dilipkrish** [comment]
Have you tried this with `2.5.0`?

**Comment by mikerott** [comment]
Same output under 2.5.0.

**Comment by dilipkrish** [comment]
I'll take a look

**Comment by dilipkrish** [comment]
Thanks for reporting! I verified its a bug. :metal:

**Comment by dilipkrish** [comment]
Actually I take that back, it appears to be working as expected. See the above tests. Please reopen if you have a specific case that doesn't work
