### ISSUE TITLE
Support for multi-value String vendor extension

### ISSUE THREAD

**Issue by michael-pratt** [springfox/springfox#1377]
I'm wondering if support for a multi-value String vendor extension is necessary and/or possible? We're using the VendorExtension interface to add custom metadata (so to speak) to our operations, and it would be very useful to have something between the String and Object extensions, such as:

```java
public class MultiValueStringVendorExtension implements VendorExtension<List<String>> 
 {
    @Override
    public String getName()
    {
       ...
    }
    @Override
    public List<String> getValue()
    {
       ...
    }
 }
```

The goal is to write the list of values as an actual JSON list, instead of a quoted string of comma-separated values.

Does this use case make sense, or am I missing existing functionality that may achieve this? I'm happy to contribute the code, just don't want to put in the effort if it's not needed.

**Comment by dilipkrish** [comment]
@michael-pratt this functionality in springfox but [doesn't in swagger core as annotations](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/annotations/Extension.java). However, you can create your own plugin to read a customer extension that provides a list of values. Basically you need a way to populate the MultiValueStringVendorExtension.

**Comment by michael-pratt** [comment]
Thanks @dilipkrish. I think it's trivial to create a plugin that can create MultiValueStringVendorExtension objects and populate them, but what would be needed to then look for and understand these new MultiValueStringVendorExtension objects and make sure they get placed into the generated JSON?

**Comment by dilipkrish** [comment]
It is supposed to be a simple Map<String, Object> So I would be surprised if it doesn't work.

**Comment by piroxxi** [comment]
Hi dilipkrish !

I had the same "problem" recently. I created a custom implementation of `VendorExtension` (in my case, to return a `List<Object>`.

To have this work, I created a "custom" mapper, extending the current one (VendorExtensionsMapper).

Here is my code :
`@Primary
@Component
@Mapper
public class RicherVendorExtensionsMapper extends VendorExtensionsMapper {

	@Override
	public Map<String, Object> mapExtensions(final List<VendorExtension> from) {
		Map<String, Object> extensions = super.mapExtensions(from);
		Iterable<CodeExamplesVendorExtension> codeExamplesExtensions = from(from)
				.filter(CodeExamplesVendorExtension.class);
		for (CodeExamplesVendorExtension each : codeExamplesExtensions) {
			extensions.put(each.getName(), each.getValue());
		}
		return extensions;
	}
}
`

I don't find that solution to be perfect, as if a "plugin" adds a new type of VendorExtension, all this will become quite a mess.

An ideal solution would be to modify the VendorExtensionsMapper to support any type of custom VendorExtension (the condition beeing that the Object returned by getValue() can be serialized... IMOO, the third bloc of the current mapper shoudn't filter using `filter(StringVendorExtension.class)` but should get all remaining VendorExtensions...

In my case, the intent of the creation of `CodeExamplesVendorExtension` was to have the following structure in the JSON :
`
"x-code-samples": [{
  "lang": "Java",
  "source": "// This is some code"
}, {
  "lang": "JavaScript",
  "source": "// This is some other code"
}]
`

This type of Extension having an array of "unnamed" extensions is hard to do with the current types. Maybe a small modification of the current springfox API could help with that ?

Is there any improvement that could be done to the code and that would lead the project in a desired direction ?

Thanks in advance for your answer.

Raphaël

**Comment by dilipkrish** [comment]
@piroxxi FYI there is also native support for this via #1636. You could use a `ListVendorExtension`

**Comment by pgghosh** [comment]
Hi dilipkrish !
I also agree with @piroxxi and would vote for the VendorExtensionMapper to support other variations of the VendorExtensionMapper.
In my case I need to output the value of an extension property as an Integer instead of a String. I tried creating a Integer version of it, but cannot see that in the generated swagger. I traced back to the VendorExtensionMapper and saw that it only supported the ones defined in Springfox. 

Hi @piroxxi, Can you let me know how you managed to use the extension to the VendorExtensionMapper class. In may case I was trying to add the extension to my securityDefinition and I need to be able to provide a Integer value for an extension property.

Thanks in advance for any help you can provide.

**Comment by dilipkrish** [comment]
@pgghosh please create a new issue for that so that it can be tracked.

**Comment by cesarblum** [comment]
@dilipkrish Has @pgghosh's issue ever been addressed? I'm running into a similar problem where I want to generate an extension with an integer value. If a new issue wasn't created back then, I'll be happy to create one.

**Comment by slaverda** [comment]
Hi,

Any updates on this issue ? I'm running into same problem.
