### ISSUE TITLE
api-docs is mapped to  this path "${springfox.documentation.swagger.v2.path:/v2/api-docs}"

### ISSUE THREAD

**Issue by vidhya17** [springfox/springfox#1381]
I am not able to access the swagger json at v2/api-docs.But I can access it at   http://localhost:8080/project_name/$%7Bspringfox.documentation.swagger.v2.path:/v2/api-docs%7D

I can see in the logs that it is incorrectly mapped 

INFO : org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped "**{[/${springfox.documentation.swagger.v2.path:/v2/api-docs}]**,methods=[GET],params=[],headers=[],consumes=[],produces=[application/json || application/hal+json],custom=[]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)

My application is simple spring-mvc (no spring boot)

I am using following version
```xml
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.5.0</version>
		</dependency>
```
Below is my SwaggerConfig
```java
package com.intuit.qbo.migration.swagger;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig {    
	
	
    @Bean
    public Docket api() { 
        return new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())                          
          .build();                                           
    }
}
```
Looks like the @Value annotation in Controller is not getting replaced properly.

Could you please pinpoint if I am doing anything wrong?

I am using JDK6 and spring-version:3.2.6

**Comment by dilipkrish** [comment]
@vidhya17 Add a static bean of type `PropertySourcesConfigurer` and see if it fixes it.

**Comment by vidhya17** [comment]
Thanks for your reply!
Already tried that , didn't work though.

**Comment by dilipkrish** [comment]
Seems like [this might work](http://stackoverflow.com/questions/16481206/spring-property-placeholder-not-working)?

**Comment by vidhya17** [comment]
Tried out , not working.

**Comment by dilipkrish** [comment]
😕 No idea... you do know its a very old version of spring. So its likely something in the configuration thats causing the property configurer to not resolve.

**Comment by vidhya17** [comment]
Hmm yeah, Upgrading to higher version breaks few other things in the application.

Thanks for your inputs. Let me know if you come across any other solution.

**Comment by vidhya17** [comment]
Upgrading to spring version 4.3.1 fixed this issue.
