### ISSUE TITLE
@ApiModelProperty set hidden with true not work when I Use  @ModelAttribute Annotation

### ISSUE THREAD

**Issue by leacoleaco** [springfox/springfox#1382]
Good evening! I found `@ApiModelProperty(hidden=true)` is not work on  my spring mvc project when I use `@ModelAttribute` annotation  ,the springfox version is 2.5.0 .   

the model is like this:

public class QueryOrder {
	@ApiModelProperty(hidden = true)
	private Integer uid;
        public Integer getUid() {
		return uid;
	}
	public void setUid(Integer uid) {
		this.uid = uid;
	}
}

the spring mvc controller is like this:

@RequestMapping(value = "list", method = RequestMethod.GET)
@ApiImplicitParams({
			@ApiImplicitParam(name = "token", value = "token", dataType = "java.lang.String", paramType = "header"),
			@ApiImplicitParam(name = "pageNo", value = "pageNo", example = "1", dataType = "java.lang.Integer", paramType = "query"),
			@ApiImplicitParam(name = "pageSize", value = "pageSize", example = "10", dataType = "java.lang.Integer", paramType = "query") })
public Object list(Token token, Page page,@ModelAttribute QueryOrder queryParam){...}

the uid property is still show in the api document.

 I don't konw what I did wrong.

**Comment by MaksimOrlov** [comment]
Good afternoon.

I think, _for now_ there is no way  to hide some properties from **@ModelAtrribute** annotated class.

If you look at  source:

package springfox.documentation.swagger.readers.parameter

public class SwaggerExpandedParameterBuilder 

```
 private void fromApiParam(ParameterExpansionContext context, ApiParam apiParam) {
    String allowableProperty = emptyToNull(apiParam.allowableValues());
    AllowableValues allowable = allowableValues(fromNullable(allowableProperty), context.getField());
    context.getParameterBuilder()
            .description(apiParam.value())
            .defaultValue(apiParam.defaultValue())
            .required(apiParam.required())
            .allowMultiple(apiParam.allowMultiple())
            .allowableValues(allowable)
            .parameterAccess(apiParam.access())
            .build();
  }

  private void fromApiModelProperty(ParameterExpansionContext context, ApiModelProperty apiModelProperty) {
    String allowableProperty = emptyToNull(apiModelProperty.allowableValues());
    AllowableValues allowable = allowableValues(fromNullable(allowableProperty), context.getField());
    context.getParameterBuilder()
            .description(apiModelProperty.value())
            .required(apiModelProperty.required())
            .allowableValues(allowable)
            .parameterAccess(apiModelProperty.access())
            .build();
  }
```

None of two methods consider **_hidden_** parameter of the annotations.

**Comment by MaksimOrlov** [comment]
But you can use some workaround:

You can split your QueryOrder class for two classes, the first will be with id property and the second will be with all other properties.

For example:

```
class QueryOrderId
{
private id;

....
setter
getter;
....

}
```

And then, add  _ignoredParameterTypes_  to your swagger configuration.

So, it will look likes next:

```
return new Docket(DocumentationType.SWAGGER_2).useDefaultResponseMessages(false).enableUrlTemplating(true)
		        .globalOperationParameters(globalParametrs).forCodeGeneration(true).ignoredParameterTypes(QueryOrderId.class);
```

**Comment by MaksimOrlov** [comment]
@dilipkrish may be we can add property **_visibility_** to _springfox.documentation.builders.ParameterBuilder_ class to determine at the **SwaggerExpandedParameterBuilder** if parameter must be expanded or not?

**Comment by MaksimOrlov** [comment]
Hi. Dilip.

I can prepare a PR with functionality that will support _hidden attributes_.
Would you mind considering it.
Because I'm affected with this issue too.

**Comment by dilipkrish** [comment]
@MaksimOrlov absolutely!

**Comment by MaksimOrlov** [comment]
Hi. I've created a PR.

**Comment by cah-shilpa-chaudhary** [comment]
Is this ever going to be fixed?
