### ISSUE TITLE
Generic types in responses

### ISSUE THREAD

**Issue by satahippy** [springfox/springfox#1383]
Hi!

We have some generic response class, and we want to show responses with specified types.
Can we show response with considering parameter type?
We're using 2.5.0 version.

For example.

Swagger now shows respose schema:
```json
{
  "body": {},
  "error": "string"
}
```

We want:
```json
{
  "body": {
    "id": "string",
    "login": "string",
    "email": "string"
  },
  "error": "string"
}
```

Controller:
```java
@RequestMapping("/info")
public Response<JsonUser> info() {
    Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
    User user = userService.getUserByUsername(authentication.getName());
    return new Response<>(null, new JsonUser(user));
}
```

Response:
```java
public class Response<T> {

    private String error;

    private T body;

    public Response(String error) {
        this.error = error;
    }

    public Response(T body) {
        this.body = body;
    }

    public Response(String error, T body) {
        this.error = error;
        this.body = body;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public Object getBody() {
        return body;
    }

    public void setBody(T body) {
        this.body = body;
    }
}
```

JsonUser:
```java
public class JsonUser {

    private String id;

    private String login;

    private String email;

    public JsonUser(User user) {
        this.id = user.getId();
        this.login = user.getLogin();
        this.email = user.getEmail();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
```

**Comment by dilipkrish** [comment]
yes you can

**Comment by satahippy** [comment]
but how?

**Comment by dilipkrish** [comment]
Not sure what you're asking i.e. are you reporting a bug or is this a question? What is it doing and what do you think its supposed to be doing? What have you tried?

Here is [an example](https://github.com/springfox/springfox-demos/blob/master/boot-swagger/src/main/java/springfoxdemo/boot/swagger/web/CategoryController.java#L19) in the demos project.

**Comment by satahippy** [comment]
We want structure like this:
```json
{
  "body": {
    "id": "string",
    "login": "string",
    "email": "string"
  },
  "error": "string"
}
```

We have tried to use `genericModelSubstitutes`

With `genericModelSubstitutes(Response.class)`:
```json
{
  "email": "string",
  "id": "string",
  "login": "string"
}
```

Without `genericModelSubstitutes(Response.class)`:
```json
{
  "body": {},
  "error": "string"
}
```

**Comment by sac10nikam** [comment]
Hi Dilip,

I have been trying to create API specification using springfox-swagger-ui, springfox-swagger, and swagger-springmvc. I have spring 4.X with interface drivern REST services.

- I have interface which is having REST annotations. In the same file I have added Swagger annotations like @Api, @ApiResponse, @ApiOperation etc along with all details

I have its implementation. But at the moment I guess we are not supporting interfaces as part of swagger project. I have found a way out using RestEasy 2.3.5 but It is also not supporting Spring 4.x.

Using RestEasy we can support interface driven swagger specification. But I would like to do it using your way.

Thanks,
Sachin

**Comment by sac10nikam** [comment]
Guys please help me out..

**Comment by sac10nikam** [comment]
Swagger REST API annotation not working on interface but working on implementation class
I want to support it.

**Comment by dilipkrish** [comment]
@sac10nikam please create a new issue and not add unrelated requests onto existing issues in the future.

Springfox totally supports interface based approach. Here is an example of an [Abstract Controller](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/AbstractController.java) and its [Concrete Implementation](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/ConcreteController.java).

**Comment by sac10nikam** [comment]
Hi Dilip,

Thanks for your quick reply. I will create new issue for sure. It would be
great if you could share an example having interface with spring 4.x
annotations and swagger annotations. My interface has @RequestMapping at
interface level and as well as at method level. Methods has @PathVariable's.

My controller  should have just its implementation. This class will have
@RestController at class level.

Note: I am using springfix-swagger-ui, springfox-swagger2 and
swagger-springmvc pom entries. Will share my code in next email.

I will highly appreciate your reply on this. I have been working on this
from last 3 days. My client has this requirement.

Have a nice day ahead man.

Many Thanks,
Sachin

**Comment by dilipkrish** [comment]
You don't need `swagger-springmvc` entries. Please check the [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)? There are [the demos](https://github.com/springfox/springfox-demos) for you to use as well.

**Comment by dilipkrish** [comment]
Seems like you'd need to @RestController annotation on the interface implementation otherwise it will not work. No need to repeat the request mappings, swagger annotations etc.

**Comment by satahippy** [comment]
i made an example for this issue - https://github.com/satahippy/springfox-issue-demo
```
$ git clone git@github.com:satahippy/springfox-issue-demo.git
$ cd springfox-issue-demo
$ git checkout 1383-generic-types-in-response
$ ./gradlew bootRun
```
Open `http://localhost:8080/swagger-ui.html#!/user-controller/infoUsingGET`

**Comment by dilipkrish** [comment]
This is what I see... which seems like it is what you want

<img width="607" alt="swagger_ui" src="https://cloud.githubusercontent.com/assets/73257/16877303/0cd191f0-4a6d-11e6-8cd1-2e7147f1e257.png">

**Comment by sac10nikam** [comment]
Thanks Dilip. If you look at my example if will find interface has swagger
annotations and spring 4.x annotations. And it's controller implementation
class has just a overridden method which returns address json.

But only one annotation named as @Restcontroller is there.

I want to execute all HTTP statuses with this example. I could run this
example.

Thanks,
Sachin

**Comment by satahippy** [comment]
@dilipkrish, sorry, my bad)
thnx!
feel free to close issue

**Comment by sac10nikam** [comment]
Can you please send my example with changes if there are any. I want to
test all HTTP statuses. I don't know how to test swagger statuses.
Thanks.

**Comment by tbwork** [comment]
I don't know why do you think it is easy to support Generic Type. I still can not get the correct result which show the generic type successfully.

**Comment by dilipkrish** [comment]
@tbwork does that mean it works as expected?

**Comment by sendreams** [comment]
@dilipkrish  but, how to do?

**Comment by 9you** [comment]
@dilipkrish Hello. This behavior has been broken in `3.0.0`. Should I open new issue for this?
