### ISSUE TITLE
Map<String, Object> UI representation

### ISSUE THREAD

**Issue by perov-alexey** [springfox/springfox#1385]
Hi! I have question about representation of maps on UI. 
I use spingfox-swagger2-2.5.0 and springfox-ui-2.5.0, spring 4.3.0 (without spring boot).

I have a simple controller:  

![1](https://cloud.githubusercontent.com/assets/15108540/16796257/6625084c-48ea-11e6-87e9-20287aa13ab2.PNG)

But on UI I see that models and schemas:

![2](https://cloud.githubusercontent.com/assets/15108540/16795889/65110c3c-48e8-11e6-8b2c-5b1cab357240.PNG)

![3](https://cloud.githubusercontent.com/assets/15108540/16795893/681e1c62-48e8-11e6-9adb-0394958f3f7a.PNG)

I want to see something like that:

{
    "key": {}
}

How can I get it? In theory I can try to use genericModelSubstitutes, but that is undesirable because in future I can use already written code with great amount of different parameterized collections and I don't want substitutes every type (but if this is true way, I will).

My simplest swagger configuration: 

![4](https://cloud.githubusercontent.com/assets/15108540/16796156/c77d959c-48e9-11e6-9593-ba7d5b7226fe.PNG)

**Comment by dilipkrish** [comment]
@perov-alexey This is by design. JSON by definition is a `Map<String, Object>` So what you're seeing there is an `any` type.
