### ISSUE TITLE
How to set port?

### ISSUE THREAD

**Issue by Pyohwan** [springfox/springfox#1387]
This is Springfox sample.
https://staging.jakduk.com:8080/swagger-ui.html#!/%EA%B2%8C%EC%8B%9C%ED%8C%90/getPostsUsingGET

It used 8080 port.
But, request URL not use 8080 port.

https://staging.jakduk.com/api/board/free/posts?category=ALL

Why request URL not set 8080 port?
or How to set port manually?

```java
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
//                .apis(RequestHandlerSelectors.basePackage("com.jakduk.restcontroller"))
                .paths(PathSelectors.ant("/api/**"))
                .build()
                .apiInfo(apiInfo());
    }

    private ApiInfo apiInfo() {
        ApiInfo apiInfo = new ApiInfo(
                "JakduK REST API",
                "Some custom description of API.",
                "API TOS",
                "Terms of service",
                new Contact("pio.", "https://jakduk.com", "phjang1983@daum.net"),
                "License of API",
                "https://github.com/JakduK/JakduK/blob/master/LICENSE");
        return apiInfo;
    }
}
```

**Comment by dilipkrish** [comment]
Is this API sitting behind an api gateway?

**Comment by Pyohwan** [comment]
What's mean api gateway?

Client(8080) -> nginx(8080) -> Springfox(8080)

**Comment by dilipkrish** [comment]
nginx is the api gateway/ proxy whatever you want to call it. It isn't configured correctly to add the expected headers.

**Comment by bingoogolapple** [comment]
> config host and port

```
@Profile("!product")
@Configuration
@EnableSwagger2
public class SwaggerConfig {
    @Autowired
    private Environment environment;

    @Bean
    public Docket testApi() {
        // api.bingoogolapple.com:8080
        String host = environment.getProperty("springfox.swagger2.host");
        return new Docket(DocumentationType.SWAGGER_2)
                .host(host)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.basePackage("cn.bingoogolapple.test.controller"))
                .paths(PathSelectors.any())
                .build();
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("BGA Test API")
                .version("1.0")
                .build();
    }
}
```

**Comment by vijayakumar-psg587** [comment]
@bingoogolapple  @dilipkrish  is there a way that this can be set dynamically from HttpRequest. Because the host name and the port will keep changing in my environments (atleast the port for now. The host might change when I move it to PR)?

**Comment by johnsonlegend** [comment]
> @bingoogolapple @dilipkrish is there a way that this can be set dynamically from HttpRequest. Because the host name and the port will keep changing in my environments (atleast the port for now. The host might change when I move it to PR)?

Is there a way you found out?
