### ISSUE TITLE
Swagger 2.4 still does not use customized ObjectMapper in Spring-Boot 1.4 with Hateoas

### ISSUE THREAD

**Issue by MichaelZett** [springfox/springfox#1390]
I'm using Swagger 2.4, Spring-Boot 1.4.0.RC1, Spring-Hateoas and the Java 8 date/time library as well as the zalando.jackson.money library. The automatically produced swagger-api does not show the correct api but the api of an unchanged ObjectMapper. I tried all tricks in the faq (set objectMapper and _halObejctMapper as the same bean, use an ApplicationInitializer to set the libraries to all objectMapper and the HtttpConverter switch).
My first question: If there is a custom Jackson module in an ObjectMapper that is used by swagger, will this show in the api (lik eMonetaryAmount as two fields and not as many fields)?
Couldn't you provide a well known name for an ObjectMapper to use?

**Comment by dilipkrish** [comment]
Please try with 2.5.0 and let me know if its still an issue

**Comment by MichaelZett** [comment]
Hi,
same with 2.5. Here is a small test project: https://github.com/MichaelZett/swaggertest
The swagger-ui shows all MonetaryAmount attributes and seconds and nano for Instant but the ObjectMapper correctly understands: currency&amount or the ISO-date-string.

Bye,
Michael

**Comment by dilipkrish** [comment]
@MichaelZett there is no way for springfox to know jackson modules (yet). You'd need to tell springfox how you intend for java 8 date types to be serialized. You do this using alternate type rules.

**Comment by MichaelZett** [comment]
I see, thank you. I thought youd'd use the objectmapper to generate the JSON.

**Comment by dilipkrish** [comment]
Yes but there is no way to infer the types when you have custom serializers as in your case where you have jackson modules that have custom serializers for java 8 date types.

**Comment by MichaelZett** [comment]
Ok.
