### ISSUE TITLE
Remove contextPath from base url

### ISSUE THREAD

**Issue by xprojectmanager** [springfox/springfox#1394]
Is there a way to remove contextPath from the base url using 2.5 version ?

I can't use the 'try out ' button since all rest url's are prefixed with the tomcat contextPath.

There's an apache server in front of apache which rewrite all url's without the contextPath...

I've tried to extend an AbstractPathProvider, and overriding 

`@Override
		public String getApplicationBasePath() {
			return "/";
		}`

seems to have no effect...

**Comment by dilipkrish** [comment]
That will not work if you're request mappings are pointing to urls with the context path. You'd have to make your url re-writing work differently
