### ISSUE TITLE
Swagger ui dose not work when @RequestParam annotation dose not set to method parameter

### ISSUE THREAD

**Issue by azizkhani** [springfox/springfox#1395]
i asked a question in stackoverflow and gitter and Dilip Krishnan  suggest to create issue in github for request new feature

this is my question [ http://stackoverflow.com/questions/38284796/swagger-ui-dose-not-work-when-requestparam-annotation-dose-not-set-to-method-pa]

**Comment by dilipkrish** [comment]
Thank you for submitting this issue. 👍

**Comment by dilipkrish** [comment]
This has been fixed via #1444
