### ISSUE TITLE
SecurityConfiguration can't be transformed to json

### ISSUE THREAD

**Issue by miborra** [springfox/springfox#1397]
Hi! I'm using springfox 2.5.0 and I'm integrating it in spring boot. 
I detected a bug, when the class SecurityConfiguration of the library springfox-swagger-common-2.5.0.jar is transformed to json, the converter produces an exception: 

`source to convert from must be an instance of springfox.documentation.swagger.web.ApiKeyVehicle; instead it was a java.lang.String`

 I think that this is because the property apiKeyVehicle is ApiKeyVehicle and the getter of this property returns a String. 

``` 
@JsonProperty("apiKeyVehicle") 
public String getApiKeyVehicle() { 
  return apiKeyVehicle.getValue(); 

} 
``` 

Furthermore, this property can't be null, because throws a nullpointerexception in the getter.

**Comment by dilipkrish** [comment]
Have you customized the object mapper to use fields?
