### ISSUE TITLE
Custom model and adding custom model properties to it

### ISSUE THREAD

**Issue by danny95djb** [springfox/springfox#1399]
I'm trying to document oauth end points but they don't have enough information so I'm implementing ApiListingBuilderPlugin to achieve this and its going fine up until the point of creating models to reference. I want to create my own models to link to explain the schema, so far i have
```
public void apply(ModelContext modelContext){
        
modelContext.getBuilder()
                .id("clientCredentials")
                .name("Client Credentials")
                .description("the client credentials")
                .build();
    }
```
this creates the custom model and then i want to add custom properties to it, so i have another class that implements `ModelPropertyBuilderPlugin` to create the properties.
```
public void apply(ModelPropertyContext modelPropertyContext){
        modelPropertyContext
                .getBuilder()
                .name("grant_type")
                .type(typeresolve.resolve(String.class))
                .required(true)
                .isHidden(false)
                .description("Grant Type")
                .position(0);
    }
```
this creates one parameter and that gets added to the custom model, but i can't add anymore to it. 
So my question is how do i add multiple custom properties to a model?

**Comment by dilipkrish** [comment]
There might be an easier way to do this... will get back to u

**Comment by danny95djb** [comment]
just a quick update i can also only create one custom model at a time with this method which isn't ideal as i need multiple ones

**Comment by danny95djb** [comment]
@dilipkrish any update on this?

**Comment by dilipkrish** [comment]
Haven't had time. Hopefully will get back this weekend

**Comment by dilipkrish** [comment]
@danny95djb Sorry for getting back so late. I take it that the oauth properties you're trying to set up are support to be in the headers? Assuming that is the case you could just add `Docket#globalOperationParameters`. Curious why you are trying to document them as models and properties.

**Comment by dilipkrish** [comment]
Closing it as I haven't heard back in on this?
