### ISSUE TITLE
How to show description of response property

### ISSUE THREAD

**Issue by hbprotoss** [springfox/springfox#1400]
I can add @ApiParam to request param to show param description, but how can I apply it to the response?

I've tried to add @ApiParam to the properties of response, but descriptions are not shown on neither Model nor Example Value

![qq20160720-0 2x](https://cloud.githubusercontent.com/assets/2310905/16977213/5c4bb8b4-4e87-11e6-9115-1fe7cc912d0d.png)

**Comment by dilipkrish** [comment]
Use the `@ApiModelProperty` annotation

**Comment by hbprotoss** [comment]
@dilipkrish thanks, it works

**Comment by raderio** [comment]
How to show description if the property is not a `String` but an object?

https://github.com/swagger-api/swagger-ui/issues/5139
