### ISSUE TITLE
Cannot hide param in spring. 

### ISSUE THREAD

**Issue by paweljanowiak2** [springfox/springfox#1401]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

My objective is to hide @RequestHeader because this param is added by nginx (so it is irrelevant for end user). The problem is that springfox does not allow to use io.swagger.core.filter.SwaggerSpecFilter so we are obligated to use @ApiIgnore, but it does not seems to work. My example annotated method: 

```java
@RequestMapping(path = "/login", method = RequestMethod.POST)
@ApiOperation("Login user")
@ApiImplicitParams({
        @ApiImplicitParam(name = "x-csrf-token", paramType = "header", dataType = "UUID"),
        @ApiImplicitParam(name = "x-auth-token", paramType = "header", dataType = "UUID"),
    })
    @ResponseStatus(code = HttpStatus.NO_CONTENT)
    public ResponseEntity<?> login(@ApiIgnore @RequestHeader("host") String host,
                                    @RequestBody LoginModifier loginModifier) { }
```
Processed json: 

```json
   "/login": {
      "post": {
        "tags": [
          "authorization-controller"
        ],
        "summary": "Login user",
        "operationId": "loginUsingPOST",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "*/*"
        ],
        "parameters": [
          {
            "name": "host",
            "in": "header",
            "description": "host",
            "required": true,
            "type": "string"
          },]
      }
    }

```

And of course on the UI it appears. The question is: Have I done everything right ? 

I have looked through a mass of posts about hiding params in springfox and answer for this would be really nice.

**Comment by dilipkrish** [comment]
@paweljanowiak2 you are right it was a regression. The temporary fix is to add `ApiIgnore.class` to the ignorables in your docket

**Comment by paweljanowiak2** [comment]
Thanks @dilipkrish for replying so quickly. This workaround works! Thanks in advance.

**Comment by dilipkrish** [comment]
Closing this as a duplicate of #1346
