### ISSUE TITLE
Parent inheritance property not working in @ApiModel

### ISSUE THREAD

**Issue by prashanth02** [springfox/springfox#1402]
@ApiModel (value = "Dog",  parent = Animal.class)
public class Dog extends Animal {
 ...............
}

@ApiModel (value = "Animal")
public class Animal extends ResourceSupport {
....
}

Swagger showing as shown below, it is not picking up the Dog class. Let me know how to fix it.

Inline Model [
Animal
]
Animal {
....
}

**Comment by prashanth02** [comment]
I figured out the issue, not a bug with springfox

**Comment by sanneboshuizen** [comment]
Hi, I can't find much documentation about how to get your implementation of swagger to show inheritance. When I try the above example the output isn't altered. Should I expect the following output?

{code}
"Dog": {
    "description": "A representation of a dog",
    "allOf": [
      {
        "$ref": "#/definitions/Pet"
      },
     {
        "properties": {....

{code}

Thanks!

**Comment by sanneboshuizen** [comment]
I guess I should wait for the implementation of this issue, is that right?
https://github.com/springfox/springfox/issues/868

Thanks!

**Comment by dilipkrish** [comment]
@sanneboshuizen Or help with a PR :) but yes.
