### ISSUE TITLE
Want to remove unwanted proeprties from Swagger Documentation like Error, Throwable and Stacktrace from model  and model schema

### ISSUE THREAD

**Issue by sac10nikam** [springfox/springfox#1403]
Want to remove unwanted proeprties from Swagger Documentation like Error, Throwable and Stacktrace from model  and model schema

Please see below attached images for more details.

![model and model schema2](https://cloud.githubusercontent.com/assets/6522168/17020176/e3877de6-4f5d-11e6-8123-ff834c078d9e.jpg)
![unwanted-model and model schema1](https://cloud.githubusercontent.com/assets/6522168/17020177/e3b92c2e-4f5d-11e6-9495-10a95ba97be2.jpg)
![model schema and model1](https://cloud.githubusercontent.com/assets/6522168/17020178/e3d66744-4f5d-11e6-81dd-7c15b1d067db.jpg)

**Comment by sac10nikam** [comment]
Dilip K.. Please guide me here.

**Comment by dilipkrish** [comment]
Add the types to the ignorable types in the docket.

**Comment by sac10nikam** [comment]
for example? In my shared example it is showing all error, throwable and stacktrace.. see above images.
Can you send me sample please.

**Comment by dilipkrish** [comment]
Have you read [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)?

**Comment by sac10nikam** [comment]
Thanks Dilip. I have gone through documentation. Can you guide me with the exact point. In given doc code I could see lot of methods chained in Docket method. Didn't understand the exact method to hide error, throwable and stacktrace from model and model schema.
