### ISSUE TITLE
How can we change the swagger-ui access URL?

### ISSUE THREAD

**Issue by prathap413** [springfox/springfox#1406]
I have a issue changing the Swagger-Ui URL. I integrated swager2 and swagger-ui using below dependencies in my project and using DOCKET to get all apis

<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.4.0</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.4.0</version>
        </dependency>

Right now i am able to access to swagger Ui using : http://localhost:8080//rest/swagger-ui.html

So i want to change that URL to : http://localhost:8080/swagger or http://localhost:8080//swagger.

Can any one help me with this.

**Comment by dilipkrish** [comment]
Have you read [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)? There are notes on how to do this. also please use 2.5.0

**Comment by prathap413** [comment]
@dilipkrish  I went through it, and tried to do below modifications. 

@Bean
  UiConfiguration uiConfig() {
    return new UiConfiguration(
        "http://localhost:8080/swagger",
        "none",       
        "alpha",      
        "schema",     
        UiConfiguration.Constants.DEFAULT_SUBMIT_METHODS,
        false,        
        true);      
  }

But it didn't work for me. I am new to swagger so, can you please tell what  i  need to change?
Thanks

**Comment by stokescomp** [comment]
Where is the document does it say how to change the path to the swagger-ui.html?
