### ISSUE TITLE
Include the generated MapStruct sources in the released source artifacts

### ISSUE THREAD

**Issue by diamondq** [springfox/springfox#1407]
Currently using SpringFox 2.5.0. During the debugging of some unrelated issues, I ran into the fact that all the MapStruct generated files are NOT included in the provided -sources.jar artifacts. This makes descending through code a pain. I realize that there's very little 'meaningful' value in those files, but it just breaks the flow of debugging, since clicking on some files in the stack trace give me source code and others don't.

I don't know Gradle enough to suggest a patch, but from what I can tell from the MapStruct docs, the source for the generated files should be being generated in an output directory, so it should be pretty straightforward to include those files when constructing the source jar.

Thanks for a great tool.

**Comment by dilipkrish** [comment]
Thanks for pointing that out... hadn't realized it was missing!
