### ISSUE TITLE
Swagger UI: OAuthSchemeKey undefined in onOAuthComplete()

### ISSUE THREAD

**Issue by ralfstuckert** [springfox/springfox#1408]
I set up swagger 2.0 with spring boot in order use implicit flow with a login page. I f I click the authentication button, my login site pops up, a bearer token is generated and passed to the swagger UI site. But the bearer token (resp. the authorization header) is not set in requests. After some debugging I isolated the problem:

In `o2c.html` the method `window.opener.onOAuthComplete(qp);` is called, where qp in this case contains the access token, e.g.
```{ "access_token": "e680a84e-9719-40a2-91d9-9989c5b4c22b" }```

But the method `onOAuthComplete` in `swagger-oauth.js` accepts two parameters, the token and the oauth schema key:
```window.onOAuthComplete = function onOAuthComplete(token,OAuthSchemeKey) {```

At the end of this method the second parameter is used to add an authorization:

```window.swaggerUi.api.clientAuthorizations.add(OAuthSchemeKey, new SwaggerClient.ApiKeyAuthorization('Authorization', 'Bearer ' + b, 'header'));```

Since the `OAuthSchemeKey` is now undefined, it will not be found (and used) later on when making an actual request. When I fixed this live in debugger and set the `OAuthSchemeKey` to my scheme name "oauth2", everything worked quite well, the bearer token was set in every request.

**Comment by ralfstuckert** [comment]
I guess I should address this directly to the swagger-ui project, right?

**Comment by dilipkrish** [comment]
@ralfstuckert thanks for the detailed analysis (its hard to come by) :metal: 

> I guess I should address this directly to the swagger-ui project, right?

To answer your question, yes if its a bug in anything other than a possible error in `springfox.js`. And it sounds like its a swagger-ui bug. 

One thing to note is that it may have been fixed, but we only take dependencies on the latest released bits.

**Comment by ralfstuckert** [comment]
Opened an [issue at swagger-ui](https://github.com/swagger-api/swagger-ui/issues/2296)
