### ISSUE TITLE
How to show description of enum value

### ISSUE THREAD

**Issue by hbprotoss** [springfox/springfox#1411]
I have an enum like this:

```
class enum Status{
    @ApiModelProperty(value = "blablabla")
    DISABLE(0L),
}
```

And an entity like this:

```
class Entity {
    @ApiModelProperty(dataType = "com.xxx.Status")
    private Long status;
}
```

But in the doc, only String values of the enum `Status` are shown.

![image](https://cloud.githubusercontent.com/assets/2310905/17093360/601c99b6-527b-11e6-91c0-51582cfd0e3c.png)

**Comment by dilipkrish** [comment]
Enums with descriptions aren't supported because they translate to allowable values. And values itself cannot have descriptions.

**Comment by hbprotoss** [comment]
May I ask how to express the mapping of Long value to the enum literal? 

For example:

```
status(integer, optional) = {0:"DISABLE", 1:"PENDING"}
```

**Comment by dilipkrish** [comment]
Its hard to express as an enum. Enum over the wire only has a notion of a `name` for the enum value. If it is something other than that you're better off with a class and annotated `@Apixxxxxxx#allowableValues` annotation where xxxx could be model, model property etc.
