### ISSUE TITLE
Mixing string and Properties parameters causes display error in 2.5.0

### ISSUE THREAD

**Issue by rherrick** [springfox/springfox#1412]
I've found a bug that breaks the swagger-ui display in 2.5.0. The symptom is that only a couple of our APIs will appear in the Swagger UI page. The error is encountered when it goes to display the third API. An error appears in the Javascript console:

`swagger-ui.min.js Uncaught TypeError: "Cannot read property 'type' of undefined"`

That's on Opera. Firefox displays:

`TypeError: e.schema is undefined swagger-ui.min.js:1:6309`

I've tracked this down to two methods in the third API, each of which takes a number of string parameters from a submitted form and then a Properties object (this is a standard Spring pattern that lets you identify specific form values but also collect any remaining form values in the Properties object). Each parameter has **@ApiParam** and **@RequestParam** annotations. Here's an example:

```java
@ApiOperation(value = "foo.",
              notes = "bar.",
              response = Properties.class)
@RequestMapping(value = "smtp", produces = MediaType.APPLICATION_JSON_VALUE, method = {RequestMethod.POST})
public ResponseEntity<Properties> setAllMailProperties(@ApiParam("one") @RequestParam(value = "host", required = false, defaultValue = NOT_SET) final String host,
                                                       @ApiParam("two") @RequestParam(value = "port", required = false, defaultValue = "-1") final int port,
                                                       @ApiParam("three") @RequestParam(value = "username", required = false, defaultValue = NOT_SET) final String username,
                                                       @ApiParam("four") @RequestParam(value = "password", required = false, defaultValue = NOT_SET) final String password,
                                                       @ApiParam("five") @RequestParam(value = "protocol", required = false, defaultValue = NOT_SET) final String protocol,
                                                       @ApiParam("six") @RequestParam final Properties properties) {
     ...
}
```

If I comment out those two methods, this API and all the subsequent APIs render correctly. If I include those two methods, I only see the APIs before this API in alphabetical order.

This works correctly using 2.4.0. I'm not sure if the error is in the generated JSON or in the display logic handling the generated JSON, but the generated JSON does differ between 2.4.0 and 2.5.0. I've attached the generated JSON from both versions below. I've also attached the class where I encountered the error originally. Finally, I've attached a small sample application that demonstrates the problem. If you comment out the method **SandboxRestController.setAllMailProperties()** and run the application, you'll be able to see the Sandbox REST API on the Swagger UI page at http://localhost:8080/static/swagger-ui.html. If you uncomment that method, the page will start to display but won't show the Sandbox REST API docs.

[api-docs.zip](https://github.com/springfox/springfox/files/382251/api-docs.zip)
[NotificationsApi.java.zip](https://github.com/springfox/springfox/files/382247/NotificationsApi.java.zip)
[swagger-bug.zip](https://github.com/springfox/springfox/files/382320/swagger-bug.zip)

I haven't been able to find a workaround for this, meaning that we have to stay on 2.4.0 until there's a fix.

**Comment by dilipkrish** [comment]
You could work around this by creating an alternate type for this. Specifically replacing `Properties` with `Map<String, Object>`. Or replace Properties in code with that.

**Comment by dilipkrish** [comment]
This should work as expected, however this is [not supported entirely by swagger tooling](https://github.com/swagger-api/swagger-ui/issues/2241)

**Comment by dilipkrish** [comment]
Closing this as its working as designed in 2.5.0+
