### ISSUE TITLE
Ability to set VendorExtensions on ApiInfo?

### ISSUE THREAD

**Issue by michael-pratt** [springfox/springfox#1413]
The Swagger specification states that vendor extensions are applicable to multiple parts in a definition:

https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/EXTENSIONS.md

Currently, it appears springfox only supports vendor extensions at the Operation level. Is there a good way to apply vendor extensions in the other places the Swagger spec allows, perhaps using a plugin, or would this be new functionality?

**Comment by dilipkrish** [comment]
@michael-pratt That is a true statement! However it is open to extension [via plugins](http://springfox.github.io/springfox/docs/current/#plugins) and you could write your own using the plugin ecosystem. Here [is an example](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/VendorExtensionsReader.java) for the operation like you guessed.

**Comment by dilipkrish** [comment]
Would love a PR for this!

**Comment by michael-pratt** [comment]
Thanks @dilipkrish. It seems like an implementation of ApiListingBuilderPlugin is the right call, but I'd have to update ApiListingBuilder and ApiListing to accept a List<VendorExtension>, just like OperationBuilder and Operation do.

Am I missing something?

**Comment by dilipkrish** [comment]
@michael-pratt It depends on what you're trying to extend. `ApiListingBuilderPlugin` can extend and customize and `ApiListing`. Just like `VendorExtensionReader` customizes and `Operation`. Plugins are meant for extensibility to enrich certain types of objects, not (currently) to add to a list or modify one.

If I may ask, what are you expecting to extend?

**Comment by michael-pratt** [comment]
@dilipkrish Well, my use case is that I need to attach some vendor extensions to the API itself, not an operation:

    {
      "swagger": "2.0",
      "info": {
      "description": "API Description",
      "version": "2.3.2",
      "title": "Documentation for my API",
      "contact": {
        "name": "Team Awesome",
        "url": "https://www.homeadvisor.com/"
      },
      x-custom-extension-1: { ... },
      x-custom-extension-2: { ... },
    },

So I can write a `ApiListingBuilderPlugin` to create the vendor extensions, but I don't see a way to attach them to the underlying `ApiListing`. The `ApiListingBuilder` and `ApiListing` classes do not have any place to set vendor extensions (compared to `OperationBuilder` and `Operation` classes, which do accept a `List<VendorExtension>`).

`VendorExtensionReader` customizes `Operation` by examining the `ApiOperation` annotation. The `Info` annotation does provide a `Extension[]` field, but I think my point above still holds: there is no place in springfox `ApiListing` to add this into? Unless I'm missing something?

**Comment by PvanHengel** [comment]
Hi does anyone have any updates on this, I have been looking for a way to add "vendor extensions" to the info node of the swagger 2 docs produced by spring fox.

**Comment by dilipkrish** [comment]
Looking for contributions on this one. Would be awesome if you could chip in @PvanHengel

**Comment by javaHelper** [comment]
@michael-pratt  - Were you able to solve this issue ? Could you please share some code ?
