### ISSUE TITLE
SwaggerCommonConfiguration disables own PropertySourcesPlaceholderConfigurer

### ISSUE THREAD

**Issue by tde-desc** [springfox/springfox#1414]
In https://github.com/spring-projects/spring-boot/issues/6457 I'm discussing the way `PropertySourcesPlaceholderConfigurer` is implemented. Due to the fact `SwaggerCommonConfiguration` uses its own Dummy-`PropertySourcesPlaceholderConfigurer` we cannot define our own `PropertySourcesPlaceholderConfigurer`.

Regarding spring-boot this seems to work as designed. If so, I'm wondering why springfox is implemented this way. Maybe this is a bug?

**Comment by dilipkrish** [comment]
@tde-desc Im not sure there is a good fix that the spring folks are going to offer. I've let it remain as an investigation so that there is opportunity to look at this when we have a good solution.

**Comment by wilkinsona** [comment]
Our recommendation is to use a `PropertyPlaceholderConfigurer`

**Comment by dilipkrish** [comment]
Thanks @wilkinsona!
