### ISSUE TITLE
Some Request Handlers are missing in Swagger Ui?

### ISSUE THREAD

**Issue by prathap413** [springfox/springfox#1416]
When i test with 
http://localhost:8080/viva-services/rest/v2/api-docs, i can see all the handlers in the json format. But when i check with swagger Ui
 http://localhost:8080/viva-services/rest/swagger-ui.html, some of the handlers are missing.

 @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }

can any one help?

**Comment by dilipkrish** [comment]
No idea! if you see everything in the json you should see everything in the UI too.
