### ISSUE TITLE
Autoremove zero from integer param

### ISSUE THREAD

**Issue by Atherus** [springfox/springfox#1417]
Hi, I came across small issue regarding of correct displaying 0 (zero) value as default value on @RequestParam which is type of Integer.
If I change it to String, zero will show up, but not with integer. Of course I can correct this in my code it self but It will be good if also swaggerui (generated by springfox) should add zero default value to the textbox.

Sample code of annotation for actual param I am using:
` @ApiParam(value = "Number of results to skip", defaultValue = "0" ) @RequestParam(value = "offset", required = false) Integer offset`

- This default value will not show up, it is Integer so also can not add whitespace or anything else because it is converting from String to Integer.
Sincerely, i didn't find clues in another question or issues.
I am using springfox version 2.5.0

![image](https://cloud.githubusercontent.com/assets/18306468/17164824/10c76a1a-53cc-11e6-9c01-4931813679ff.png)

**Comment by dilipkrish** [comment]
Do you know if swagger ui honors default values. I don't think it does. This may be a swagger-ui issue.
