### ISSUE TITLE
the request that generate is wrong when it has query params

### ISSUE THREAD

**Issue by igreenfield** [springfox/springfox#1419]
I have this URL:

GET /cp/om/bo/v{version}/offers 
with parameters: view, limit, offset

I populate all the parameters and the generate request is:

 http://localhost:6091/cp/om/bo/v1/offers%7B?view,limit,offset}?limit=10&offset=0

And this is wrong

I do little debug and found that this class `ApiDescriptionBuilder`

on this method:
```java
  public ApiDescription build() {
    return new ApiDescription(pathDecorator.apply(path), description, operations, hidden);
  }
```  
this `pathDecorator.apply(path)` adds the  `{?view,limit,offset}`
![image](https://cloud.githubusercontent.com/assets/5586356/17172411/a7eb8c9c-53fd-11e6-80b9-01901e1fbf7d.png)

![image](https://cloud.githubusercontent.com/assets/5586356/17172427/bdcc80a2-53fd-11e6-88b6-2d40bb886733.png)

**Comment by dilipkrish** [comment]
Try refreshing your browser cache...

**Comment by igreenfield** [comment]
Same after clear browser cache.

**Comment by dilipkrish** [comment]
I just realized... which swagger-ui library are you using. Are you using the [rfc6750 version](http://springfox.github.io/springfox/docs/current/#rfc6570-support-strong-incubating-strong)?

**Comment by igreenfield** [comment]
@dilipkrish How I can know which version?

**Comment by dilipkrish** [comment]
What dependency have you brought in? `springfox-swagger-ui` or `springfox-swagger-ui-rfc6570`?

**Comment by igreenfield** [comment]
![image](https://cloud.githubusercontent.com/assets/5586356/17667311/12737160-630d-11e6-8d09-a40ee845168f.png)

**Comment by dilipkrish** [comment]
you need to use [this version](https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui-rfc6570/0.9.6)

**Comment by igreenfield** [comment]
instead?

**Comment by igreenfield** [comment]
with this version the ui even not loads.

**Comment by dilipkrish** [comment]
Yes, instead of springfox-swagger-ui:2.5.0.

**Comment by dilipkrish** [comment]
@BarryLoo not sure why thats coming there. Looks like its the `{` character

**Comment by BarryLoo** [comment]
Thanks for reply. The urltemplate's setting which i set it as "true". This make the query request were forced turn to RESTful style. 
like:
/***/{id=#id,age=#age}
In my demo turn to /***/***{id=#id,age=#age}, also i need is /***/***?id=#id&age=#age.
Anyhow, thanks.

**Comment by dilipkrish** [comment]
Dont set the url template to true if you're using a version greater than 2.7.0
