### ISSUE TITLE
type/format not suitable to generate the original Java types

### ISSUE THREAD

**Issue by ralfstuckert** [springfox/springfox#1422]
If you use the swagger api doc generated by springfox to generate a (feign-) client using **swagger-code-gen**, some of the generated types in the client does not match the original types. Since this leads to parse errors, you cannot use the spec for client generation. The following types hurt my case (there may be more):

`BigInteger` currently results in `"type":"number", "format":"double"`, which gives you a `Double` in the generated code. It should be ``"type": "string", "format": "number"` in order to generate `BigInteger`.

`byte[]` currently results in `"type":"array", "items":{ "type":"string", "format":"byte" }` , which gives you a `List<byte[]>` in the generated code. It should be `"type": "string", "format": "byte"` in order to generate `byte[]`. (Spring internally converts the byte array to base64 encoded string, which is the preferred way to transport binary in json)

`LocalDate` currently results in `"type":"string", "format":"date-time"`, which gives you a `OffsetDateTime` in the generated code. It should be `"type": "string","format": "date"` in order to generate `LocalDate`.

`Map<String, Object>` currently results in `"type":"object"`, which gives you a `Object` in the generated code. It should be `"type": "object", "additionalProperties": {"type": "object"}` in order to generate `Map<String, Object>`.

**Comment by dilipkrish** [comment]
Its not designed to reflect the same types over the wire.

**Comment by ralfstuckert** [comment]
Are you serious? If you cannot generate a working client from the swagger spec, what is the point? I always expected swagger to be a valuable toolchain, not an academic idea.

**Comment by ralfstuckert** [comment]
I'm on with you, that it is out of scope to transport types over the wire, but the generated type/format should reflect the original language type. And at least using `date-time` for LocalDate is wrong, it is `date`.

**Comment by ralfstuckert** [comment]
And for good reason the swagger-code-gen guys use `string/number` for `BigDecimal`, since a `Double` cannot handle the arbitrary precision.

**Comment by ralfstuckert** [comment]
And Spring automagically converts a byte array (correctly) to a base64 encoded String, and due to the swagger spec the type/format of base 64 encoded String is `string/byte`, so this is also an issue.

**Comment by ralfstuckert** [comment]
So, I'm still on with you, that this' issues intention may be wrong, but the handling of `LocalDate`, `BigDecimal` and `byte[]` seems to be wrong, so I will open seperate issues for those, ok?

**Comment by dilipkrish** [comment]
@ralfstuckert I responded to a couple of the new issues you created! There is room to improve for sure. Thanks for taking time to report the issues.

**Comment by ralfstuckert** [comment]
Since I've opened separate issues for the items above I am closing this one.

**Comment by snmaddula** [comment]
How to generate Long data type? Specifying `type: number` always ends up in `BigDecimal`.

**Comment by dilipkrish** [comment]
where are you specifying `type: number`. Also if this is a new problem please open a new issue rather than commenting on closed issues
