### ISSUE TITLE
@RequestParam with placeholders syntax like ${x.y}

### ISSUE THREAD

**Issue by blelem** [springfox/springfox#1423]
Bug report: springfox doesn't handle spring placeholders.

  I'm using springfox 2.5.0 in a spring boot project. 

  When I am using placeholders in my functions @RequestParam, springfox fails to interpret them up and displays an error message instead.

```
@RestController
public class MainController {
    @RequestMapping(value = "/getFoo", method = RequestMethod.GET)
     public Integer getFoo( @RequestParam(name = "foo", defaultValue = "${defaultValues.foo}") final Integer foo ) {
    return foo;
}
```

 The error thrown looks like this:

```
java.lang.NumberFormatException: For input string: "${defaultValues.foo}"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_91]
at java.lang.Long.parseLong(Long.java:578) ~[na:1.8.0_91]
at java.lang.Long.valueOf(Long.java:803) ~[na:1.8.0_91]
at io.swagger.models.parameters.AbstractSerializableParameter.getDefault(AbstractSerializableParameter.java:193) ~[swagger-models-1.5.9.jar:1.5.9]
```

 Spring itself copes well with the placeholder and replaces it with the value I defined in my application.yml. 

 I created a repo to easily reproduce the problem. https://github.com/blelem/springFoxDefaultParams
 Just run it, and visit http://localhost:8080/swagger-ui.html#!/main-controller/getFooUsingGET

**Comment by dilipkrish** [comment]
@blelem thanks for reporting. Not sure how to go about fixing this. It may or may not be easily fixable

**Comment by blelem** [comment]
@dilipkrish In my case, it would be perfectly ok if springfox would simply ignore the default values that are using placeholders instead of trying to parse them. Would that be simpler to bake in?

**Comment by dilipkrish** [comment]
@blelem will see what we can do about that. It should ignore it by default if its not able to parse non-int values.
