### ISSUE TITLE
byte array should have type string and format byte

### ISSUE THREAD

**Issue by ralfstuckert** [springfox/springfox#1430]
Spring/Jackson converts a byte array to a base64 encoded string, which is the preferred way to transport binary in json. Due to the swagger spec, a base64 encoded string should be represented by `"type": "string", "format": "byte"`, but springfox currently generates `"type":"array", "items":{ "type":"string", "format":"byte" }` for a byte[].

**Comment by ralfstuckert** [comment]
See `io.swagger.models.properties.ByteArrayProperty`

**Comment by ralfstuckert** [comment]
No improvement with 2.6.0, I still get 
```
"document": {
	"type": "array",
	"items": 
	{
		"type": "string",
		"format": "byte"
	}
},
```
for 
```
private byte[] document;
```

**Comment by dilipkrish** [comment]
This may be a bug.. Could you create a new issue for this?
