### ISSUE TITLE
@ApiModelProperty should support a dataFormat attribute

### ISSUE THREAD

**Issue by ralfstuckert** [springfox/springfox#1431]
There are cases where a (Java) Type results in an undesired type and/or format in the generated swagger spec. You can actually override the data type deduced from the java type using the `dataType` attribute in the `@ApiModelProperty` annotation. Complemental, there should be a `format` attribute also in the annotation, in order to let you override the format also.

**Comment by dilipkrish** [comment]
@ralfstuckert this would be a suggestion for the [swagger-core team](https://github.com/swagger-api/swagger-core)

**Comment by ralfstuckert** [comment]
Oh sorry, I just had a flow opening issues ;-)
Closing this one
