### ISSUE TITLE
Map should translate to type object with additional properties

### ISSUE THREAD

**Issue by ralfstuckert** [springfox/springfox#1433]
`Map<String, Object>` currently results in `"type":"object"` in springfox. Due to the swagger spec it should be `"type": "object", "additionalProperties": {"type": "object"}` 

From the swagger spec:

```
Model with Map/Dictionary Properties
For a simple string to string mapping:

{
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}

For a string to model mapping:

{
  "type": "object",
  "additionalProperties": {
    "$ref": "#/definitions/ComplexModel"
  }
}
```

**Comment by dilipkrish** [comment]
Of you think about it `Map<String, Object>` is an `any` object. So over the wire you an send in anything that is serializable and it should still be equivalent. When you have something like `Map<String, ComplexObject>` you will see that it does in fact generate 

```json
{
  "type": "object",
  "additionalProperties": {
    "$ref": "#/definitions/ComplexModel"
  }
}
```

**Comment by ralfstuckert** [comment]
After all, I'm using the swagger spec as a contract and for generating clients. Therefore I'm interested that the generated swagger is as close to the spec as possible, in order that the generated client reflects the data structures sent by the server.

So if I generate a client from `"type":"object"` I will get an 
```
private Object myMap;
```
If it is - conforming to the spec - `"type": "object", "additionalProperties": {"type": "object"}` , I will get
```
private Map<String, Object> myMap;
```

So it makes perfect sense to adhere to the spec in this case also.

**Comment by dilipkrish** [comment]
You could take that to its logical conclusion :)

Over the wire...

`private Map<String, Object> myMap;`

is the same as 

`private Map<String, Map<String, Object>> myMap;`

is same as 
`private Map<String, Map<String, ....>> myMap;`

From a json perspective (which is nothing but a map of key value pairs), when you say your serialized type is `Map<String, Object>` what you're doing is saying that the wire representation is a json _any_ type. Which translates to `Object`

**Comment by ralfstuckert** [comment]
Yes. After all, we could just translate every structure into plain Object. That would make the swager files much more readable :-D

Or we could obey the spec and use `"type": "object", "additionalProperties": {"type": "object"}` for dictionaries (which a map actually is).

I would prefer the latter.

**Comment by rajeshkamal** [comment]
@dilipkrish with this fix, the classes/models/definitions with these names will not more be generated right.

```
MapOfstringAndstring
MapOfstringAndComponent
MapOfstringAndListOfComponent
```

Instead when java client bindings are generated using codegen, we should get,

```
  private Map<String, String> componentStatuses = new HashMap<String, String>();
  private Map<String, Component> componentMap = new HashMap<String, Component>();
  private Map<String, List<Component>> componentMapList = new HashMap<String, List<Component>>();
```

**Comment by dilipkrish** [comment]
@rajeshkamal this is not a fix. This is how its always been. Just explaining why.

**Comment by rajeshkamal** [comment]
I am not getting it @dilipkrish.

I am having client bindings, generated with such class names. 

MapOfstringAndstring
MapOfstringAndComponent
MapOfstringAndListOfComponent

Why is that, shouldn't it be proper Maps.

**Comment by dilipkrish** [comment]
Springfox only guarantees wire compatibility. Not type system compatibility. Plus the codegen project is not maintained by me.

**Comment by rajeshkamal** [comment]
Thanks for the comment @dilipkrish 

I am still getting a feel that something is wrong here. Since the Swagger spec clearly specifies on how to handle,

Model with Map/Dictionary Properties

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-mapdictionary-properties

```
For a simple string to string mapping:

{
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}

For a string to model mapping:

{
  "type": "object",
  "additionalProperties": {
    "$ref": "#/definitions/ComplexModel"
  }
}

```

If I write a spec manually like below,

```
Sample Model Properties referencing the Sample Component Model below.

            "componentStatuses": {
               "description":"Map of component statuses by name",
              "type": "object",
              "additionalProperties": {
                "type": "string"
               }
            },
            "componentMap": {
               "description":"Map of component by name",
              "type": "object",
              "additionalProperties": {
                  "$ref":"#/definitions/Component"
               }
            },
            "componentMapList": {
               "description":"Map of components by name",
              "type": "object",
              "additionalProperties": {
                  "type":"array",
                  "items":{
                     "$ref":"#/definitions/Component"
                  }
               }
            }

Sample Component Model

"Component":{
         "type":"object",
         "properties":{
            "id":{
               "type":"string",
               "description":"Component unique identifier",
               "readOnly":true
            },
            "name":{
               "type":"string",
               "description":"Component name",
               "readOnly":true
            },
            "ip":{
               "type":"string",
               "description":"Component ip",
               "readOnly":true
            }
         },
         "description":"Component Model"
      }

```
The java client codegen generates Map with type safe data models.

```
  private Map<String, String> componentStatuses = new HashMap<String, String>();
  private Map<String, Component> componentMap = new HashMap<String, Component>();
  private Map<String, List<Component>> componentMapList = new HashMap<String, List<Component>>();
```

I am assuming that if Springfox can generate the spec as described here - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-mapdictionary-properties only for Map of 
-- string to string mapping
-- string to model mapping

That would be really cool. Let me know if I am missing something here.

**Comment by dilipkrish** [comment]
AFAIK,  these should all be supported.  
- [`Map<String, String>`](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java#L40-L42), sample [json](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/test/resources/contract/swagger2/declaration-bugs-service.json#L107-L120)
- [`Map<String, Example>`](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/FeatureDemonstrationService.java#L163-L166), sample [json](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/test/resources/contract/swagger2/declaration-feature-demonstration-service-codeGen.json#L1006-L1011)

As regards
- [`Map<String, List<Component>>`](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/PetService.java#L146-L149), example [json](nameToNickNamesMap), for which there is a bug (#1475)

Not sure what is not working.

**Comment by rajeshkamal** [comment]
Thanks @dilipkrish for letting me know that it works. Do you think it might be because, I am using Springfox 2.3.0 by any chance?

**Comment by dilipkrish** [comment]
That's very possible
