### ISSUE TITLE
Setting a Custom basePath Requires Setting a Static Host in 2.5

### ISSUE THREAD

**Issue by asdcdow** [springfox/springfox#1435]
I have a Spring MVC application that can be reached URLs like:

```
http://my.host.com:8080/my-context/controller-name
```

In order to simplify access to this application, I'm using Apache as a reverse proxy.  As a result of this, my application can be reached (through apache) by URLs like:

```
http://my.host.com/controller-name
```

This creates problems for Springfox because by default it it includes the servlet context in API URLs.  It assumes that the way to reach my controller endpoint is:

```
http://my.host.com/my-context/controller-name
```

This 404s.  So, in order to fix that I created a custom PathProvider that removes the servlet context from the URL.  This works fine in Springfox 2.4 but appears to have been broken in 2.5 by #1217.  Now the custom path generated by the PathProvider is ignored unless I explicitly set a host as well.  I can't set a host because my application is served under multiple domains so I want Springfox to continue to dynamically determine the host.

**Comment by dilipkrish** [comment]
Not sure what needs to change. Seems like the change in #1217 was a valid one. It uses standard x-forward mecahnisms. Would you like to get it to work and propose a PR. 

Also jhipster is using the service registry and the paths are looking just fine. Perhaps there is an opportunity to extract a reusable component.

**Comment by asdcdow** [comment]
As far as I can tell the x-forward support only lets you add a prefix to the path with `X-Forwarded-Prefix`.  It doesn't allow you to make arbitrary changes to the path.  In my case it doesn't allow me to remove the servlet context from the path.

In order to fix my problem, I suggest modifying the x-forward logic so so it builds the path based the existing basePath configured in the Swagger object rather than the servlet context path.

Let me know if this sounds reasonable and I will see if I can put together a pull request in the next week.

**Comment by dilipkrish** [comment]
@asdcdow That doesn't sound right. You'd be breaking the compatibility with regular well-behaved citizens to fit your custom need. This solution is designed for hosting the swagger apidocs on the same machine as that influenced by the x-forward mechanism. If I understand how this is supposed to work; your load balancer would need to set the right x-forward headers such that it routes correctly on the API server.

**Comment by asdcdow** [comment]
Why would that break comptibility?  The default `RelativePathProvider`sets the base path on the `Swagger` object to be the servlet path by default.  So, if you don't set a custom `PathProvider`, what would break?  If you are setting a custom `PathProvider`, then the behavior goes back to how it was in 2.4.

I may be missing something here.  What x-forward header can I set to to remove the servlet context path from the URL path?  As far as I can tell, that isn't possible.

**Comment by dilipkrish** [comment]
The reason being servlet context path is inferred from those headers automatically. So that _IS_ the source of truth. Setting it to something different is just going mess it up for load balanced, reverse proxy scenarios.

Easier would be to get the reverse proxy to set the right x-forward headers no?

**Comment by asdcdow** [comment]
I agree that having the proxy set an x-forward header to correct the path would be a reasonable solution for my particular situation, if such a header existed.  So, once again, what header can I use to remove the servlet context from the path?

**Comment by asdcdow** [comment]
It looks like somebody else is having the same problem in #1394

**Comment by dilipkrish** [comment]
@asdcdow Is this still a problem?

**Comment by asdcdow** [comment]
Yes, it is still a problem

**Comment by dilipkrish** [comment]
Not familiar with apache reverse proxy, but a little bit of googling lead me [to this](http://stackoverflow.com/questions/1393706/how-to-use-a-different-path-name-in-proxypass-than-the-tomcat-context-name). Really somehow you need to tell the reverse proxy to map
`http://my.host.com/controller-name` -> `http://my.host.com:8080/context-path/controller-name`

**Comment by asdcdow** [comment]
I already have that mapping.  The first 4 lines of this ticket are me describing that very mapping.  I'm having this problem because I have that mapping.

**Comment by asdcdow** [comment]
Also, this is the same problem as #1507

**Comment by dilipkrish** [comment]
Don't know what the fix is. Perhaps you could submit a PR with your proposed fix.

**Comment by dilipkrish** [comment]
ping!

**Comment by asdcdow** [comment]
I'll see if I can put together a PR in the next week

**Comment by dilipkrish** [comment]
Thanks that would be awesome!!

**Comment by asdcdow** [comment]
Pull request added
