### ISSUE TITLE
Explicit value JsonProperty ignored when PropertyNamingStrategy is configured 

### ISSUE THREAD

**Issue by mborkunov** [springfox/springfox#1436]
Hello,

I've a DTO with several fields. One field is declared as camelCase in JsonProperty.
Naming strategy in objectMapper is declared as 
PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

Jackson serializes/deserializes this dto correctly - all fields are snake_case except this one
But it seems like that naming strategy has a priority over the explicit name in JsonProperty in springfox
Am I right?

- io.springfox: springfox-swagger2:  2.5.0
- com.fasterxml.jackson.core: jackson-databind: 2.6.7
- com.fasterxml.jackson.core: jackson-annotations: 2.6.7

**Comment by dilipkrish** [comment]
This may be a bug. Thanks for reporting!

**Comment by durimkryeziu** [comment]
@dilipkrish it is still happening even in the latest version, check the demo: https://github.com/durimkryeziu/demo-json-property-is-ignored
