### ISSUE TITLE
 How to avoid @ApiModelProperty on DTO

### ISSUE THREAD

**Issue by kmadanu** [springfox/springfox#1437]
I have a scenario where a DTO is used for POST and PUT operations. I am currently using Spring MVC (RESTful). I would like to reuse DTO in multiple cases. So I want to avoid any annotations in the DTO. I prefer them on the controller instead. I may be wrong but, please advise.

Below is the scenario: There are three fields id, a, b in the DTO. For POST operation a and b are required and for PUT operation all three are required. I am currently using attribute "required" in @ApiModelProperty annotation (in model).

a. How do I enforce conditional required for "id" incase of PUT operation using @ApiModelProperty?

b. I would like to have something on the controller itself where I can specify all conditions instead on the DTO itself. That way I can reuse DTO in many scenarios. I tried @ApiImplicitParams with paramType as "body". If I do this, I am seeing multiple body fields instead of one in swagger html documentation.

Any suggestions would be greatly helpful.

Thanks!!

**Comment by dilipkrish** [comment]
@kmadanu This is currently not possible, as we don't separate models based on method. There is a related feature request to do that #601. 

Secondly, its preferable to use different DTOs if the requirements of it are different.
