### ISSUE TITLE
swagger-codegen-cli.jar dont understand ResponseEntity<byte[]>

### ISSUE THREAD

**Issue by IsmaTeddy** [springfox/springfox#1439]
I am documenting my microservices with " springfox - swagger- ui" but when I use the " swagger- codegen - cli.jar " java library to generate customers must specify the type :
Jersey1
feign
jersey2 ,
okhttp - GSON
retrofit
retrofit2
I try to jersey2 but my notes SpringMVC microservices are therefore not able to translate customer responseEntity < byte [ ]> and I generated a method that returns List < byte [ ]> . Any solution ?, springfox generator does not have customers?

**Comment by dilipkrish** [comment]
I think it may be related to #1430

**Comment by dilipkrish** [comment]
Let me know if thats not correct?

**Comment by IsmaTeddy** [comment]
@dilipkrish  I agree. this may be the problem. any ideas? any solution?

**Comment by dilipkrish** [comment]
Should be fixed with 2.6.0

**Comment by IsmaTeddy** [comment]
that's great. when will you know ?
