### ISSUE TITLE
collectionFormat is always multi

### ISSUE THREAD

**Issue by rkaltreider** [springfox/springfox#1442]
Is there a way I can specify which collectionFormat to use?  it appears to always use multi wether allowMultiple is specified as true or false.  I need multiple values to be specified as comma delimites lists so csv.  Is there a way this can be done easily?

**Comment by dilipkrish** [comment]
Unfortunately none of the swagger annotations support changing this and [per this pr](https://github.com/swagger-api/swagger-core/issues/1160) multi is the preferred format

**Comment by gkozyryatskyy** [comment]
There is a support of collectionFormat now available in annotations https://github.com/swagger-api/swagger-core/issues/1180

**Comment by deripas** [comment]
Yes, problem with `collectionFormat `not resolve yet (version 2.9.2).
