### ISSUE TITLE
how to change base path for swagger 2.0

### ISSUE THREAD

**Issue by jiangchuan1220** [springfox/springfox#1443]
Currently the generated API description is as follows:
````
{
    "swagger": "2.0",
    "info": {
        "description": "This API is for test",
        "version": "SNAPSHOT",
        "license": {
            "name": "License",
            "url": "/public/footer.html"
        }
    },
    "host": "localhost:8080",
    "basePath": "/",
````
I want to change it to 
````
{
    "swagger": "2.0",
    "info": {
        "description": "This API is for test",
        "version": "SNAPSHOT",
        "license": {
            "name": "License",
            "url": "/public/footer.html"
        }
    },
    "host": "localhost:8080",
    "basePath": "/myapi",
````
My project is Spring boot, current the swagger configuration is:
````
@Configuration
@EnableSwagger2
public class SwaggerConfig {
	@Bean
    public Docket api() { 
        return new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())                          
          .build()
          .apiInfo(apiInfo())
          .globalResponseMessage(RequestMethod.GET,                     
            newArrayList(new ResponseMessageBuilder()   
              .code(500)
              .message("500 message")
              .responseModel(new ModelRef("Error"))
              .build(),
              new ResponseMessageBuilder() 
                .code(403)
                .message("Forbidden!")
                .build()));
    }
	
	private ApiInfo apiInfo() {
	    ApiInfo apiInfo = new ApiInfo(
	      "REST API",
	      "Some custom description of API.",
	      "API TOS",
	      "Terms of service",
	      "",
	      "License of API",
	      "API license URL");
	    return apiInfo;
	}
	

}
````

how should I change the code?

**Comment by dilipkrish** [comment]
You can just change the servlet context path in spring boot to `/myapi` using `server.contextPath=/myapi` in your application property file.

**Comment by jiangchuan1220** [comment]
I changed the basepath by adding a custom path provider into Docket.

**Comment by jonaskoperdraat** [comment]
For anyone else interested in the solution to this problem; in addition to providing a custom path provider, make sure you set the `host` property of the `Docket`. Otherwise, the `basePath` will be determined based on the request url (see [`Swagger2Controller.getDocumentation(..)`](https://github.com/springfox/springfox/blob/2.6.1/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L85)).

(The relevant parts of) my Docket configuration looks like this now:

```java
new Docket(DocumentationType.SWAGGER_2)
    .host("www.mydomain.com")
    .pathProvider(new RelativePathProvider(servletContext) {
        @Override
        public String getApplicationBasePath() {
            return "/myapi";
        }
    });
```

**Comment by nicklhw** [comment]
jonaskoperdraat's solution worked for me, adding the host property did the trick. I also used sioulin custom PathProvider in issue [963](https://github.com/springfox/springfox/issues/963) in my implementation.

**Comment by hydra1983** [comment]
```java
@Configuration
@EnableSwagger2
@EnableConfigurationProperties({
    SwaggerProperties.class
})
public class SwaggerAutoConfiguration extends WebMvcConfigurerAdapter {
    @Autowired
    private SwaggerProperties swaggerProperties;

    @Bean
    public Docket swaggerDocket() {

        return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.withClassAnnotation(Api.class))
            .build()
            .pathMapping(swaggerProperties.getInvokingBasePath());
    }

    @Bean
    public HandlerMapping swagger2ControllerProxyMapping(
        Environment environment,
        DocumentationCache documentationCache,
        ServiceModelToSwagger2Mapper mapper,
        JsonSerializer jsonSerializer) {

        return new Swagger2ControllerRequestMappingHandlerMapping(
            environment,
            new Swagger2Controller(environment, documentationCache, mapper, jsonSerializer),
            swaggerProperties.getBrowsingBasePath());
    }

    @Bean
    public HandlerMapping apiResourceControllerProxyMapping(
        ApiResourceController apiResourceController) {

        return new ProxiedControllerRequestMappingHandlerMapping(
            apiResourceController,
            swaggerProperties.getBrowsingBasePath());
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {

        String basePath = swaggerProperties.getBrowsingBasePath();

        registry.
            addResourceHandler(basePath + "/swagger-ui.html**")
            .addResourceLocations("classpath:/META-INF/resources/swagger-ui.html");
        registry.
            addResourceHandler(basePath + "/webjars/**")
            .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}
```

**Comment by hydra1983** [comment]
```java
@ConfigurationProperties(SwaggerProperties.PREFIX)
@Data
public class SwaggerProperties {
    public static final String PREFIX = "app.swagger";

    private Boolean enabled = true;

    private String browsingBasePath = "/api/swagger";

    private String invokingBasePath = "";
}
```

**Comment by hydra1983** [comment]
```java
public class ProxiedControllerRequestMappingHandlerMapping extends RequestMappingHandlerMapping {
    protected final Map<String, HandlerMethod> handlerMethods = new LinkedHashMap<String, HandlerMethod>();
    protected final Object handler;
    protected final String basePath;

    public ProxiedControllerRequestMappingHandlerMapping(
        Object handler,
        String basePath) {

        this.handler = handler;
        this.basePath = basePath;
    }

    @Override
    protected void initHandlerMethods() {

        logger.debug("initialising the handler methods");
        setOrder(Ordered.HIGHEST_PRECEDENCE + 1000);
        Class<?> clazz = handler.getClass();
        if (isHandler(clazz)) {
            RequestMappingInfo classMapping = createRequestMappingInfo(clazz);

            for (Method method : clazz.getMethods()) {
                if (isValidMethod(method)) {
                    RequestMappingInfo methodMapping = getMappingForMethod(method, clazz);

                    if (methodMapping == null && classMapping == null) {
                        logger.warn(String.format(
                            "Cannot map any URL path onto method [%s] for class [%s]",
                            method.getName(),
                            clazz.getName()));
                        continue;
                    }

                    RequestMappingInfo mapping = ObjectUtils.defaultIfNull(methodMapping, classMapping);
                    HandlerMethod handlerMethod = createHandlerMethod(handler, method);
                    doMapping(clazz, method, mapping, handlerMethod);
                }
            }
        }
    }

    protected void doMapping(
        Class<?> clazz,
        Method method,
        RequestMappingInfo mapping,
        HandlerMethod handlerMethod) {

        for (String path : mapping.getPatternsCondition().getPatterns()) {
            path = basePath + path;

            logger.info(String.format(
                "Mapped URL path [%s] onto method [%s]",
                path,
                handlerMethod.toString()));
            handlerMethods.put(path, handlerMethod);
        }
    }

    @Override
    protected boolean isHandler(Class<?> beanType) {

        return ((AnnotationUtils.findAnnotation(beanType, Controller.class) != null) ||
            (AnnotationUtils.findAnnotation(beanType, RequestMapping.class) != null));
    }

    @Override
    protected HandlerMethod lookupHandlerMethod(
        String urlPath,
        HttpServletRequest request) throws Exception {

        logger.debug("looking up handler for path: " + urlPath);
        HandlerMethod handlerMethod = handlerMethods.get(urlPath);
        if (handlerMethod != null) {
            return handlerMethod;
        }
        for (String path : handlerMethods.keySet()) {
            UriTemplate template = new UriTemplate(path);
            if (template.matches(urlPath)) {
                request.setAttribute(
                    HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE,
                    template.match(urlPath));
                return handlerMethods.get(path);
            }
        }
        return null;
    }

    private RequestMappingInfo createRequestMappingInfo(AnnotatedElement element) {

        RequestMapping requestMapping = AnnotatedElementUtils.findMergedAnnotation(element, RequestMapping.class);
        RequestCondition<?> condition = (element instanceof Class ?
            getCustomTypeCondition((Class<?>) element) : getCustomMethodCondition((Method) element));
        return (requestMapping != null ? createRequestMappingInfo(requestMapping, condition) : null);
    }

    private boolean isValidMethod(Method method) {

        return (AnnotationUtils.findAnnotation(method, RequestMapping.class) != null)
            && Modifier.isPublic(method.getModifiers());
    }
}
```

**Comment by hydra1983** [comment]
```java
public class Swagger2ControllerRequestMappingHandlerMapping extends ProxiedControllerRequestMappingHandlerMapping {
    private final Environment environment;

    public Swagger2ControllerRequestMappingHandlerMapping(
        Environment environment,
        Object handler,
        String basePath) {

        super(handler, basePath);
        this.environment = environment;
    }

    @Override
    protected void doMapping(
        Class<?> clazz,
        Method method,
        RequestMappingInfo mapping,
        HandlerMethod handlerMethod) {

        PropertySourcedMapping mapper = AnnotationUtils.getAnnotation(method, PropertySourcedMapping.class);

        if (mapper != null) {
            String mappingPath = mappingPath(mapper);
            if (mappingPath != null) {
                mappingPath = basePath + mappingPath;

                logger.info(String.format(
                    "Mapped URL path [%s] onto method [%s]",
                    mappingPath,
                    handlerMethod.toString()));
                handlerMethods.put(mappingPath, handlerMethod);
            } else {
                super.doMapping(clazz, method, mapping, handlerMethod);
            }
        }
    }

    private String mappingPath(final PropertySourcedMapping mapper) {

        final String key = mapper.propertyKey();
        return Optional.ofNullable(environment.getProperty(key))
            .map(input -> input.replace(String.format("${%s}", key), input))
            .orElse(null);
    }
}
```

**Comment by hydra1983** [comment]
![image](https://user-images.githubusercontent.com/488235/27466660-dd26bdee-580e-11e7-85ff-69078178c5e9.png)

**Comment by hydra1983** [comment]
![image](https://user-images.githubusercontent.com/488235/27466707-2b10b924-580f-11e7-8a89-3dcced2b5b8a.png)


![image](https://user-images.githubusercontent.com/488235/27466711-2fbfcad2-580f-11e7-98f1-c4c6b53c2eaf.png)

**Comment by dilipkrish** [comment]
@hydra1983 thanks for the solution for a reverse-proxy scenario

**Comment by beykery** [comment]
@hydra1983 how?
i tried buf faild

**Comment by dilipkrish** [comment]
@beykery 😢  Tried what tho'

**Comment by hydra1983** [comment]
@beykery you need to configure the swagger as what I described in the previous comments :D

**Comment by LuChunQi** [comment]
@jonaskoperdraat how do you create a servletContext object?

Thanks,
Kevin

**Comment by dilipkrish** [comment]
Its auto wired of type `ServletContext` in by spring @LuChunQi

**Comment by LuChunQi** [comment]
@dilipkrish I am using spring boot, it looks like ServletContext could not be auto wired in spring boot by default.
How should I do?

Thanks a lot.

**Comment by wubinhong** [comment]
If you use spring cloud `Zuul` to proxy your micro-services, you can take my example.
![image](https://user-images.githubusercontent.com/7396720/38403515-9043b2e2-3996-11e8-80a9-033dc574fd37.png)

I found this what it work by taking a look at the source code of `springfox-swagger2-2.5.0`:
- The `BASE URL` determined by the ajax request: `/v2/api-docs` , so I look deep into the `Swagger2Controller#getDocumentation()` --> `springfox.documentation.swagger2.web.HostNameProvider#componentsFrom` --> `org.springframework.web.servlet.support.ServletUriComponentsBuilder#fromServletMapping` --> `org.springframework.web.servlet.support.ServletUriComponentsBuilder#prependForwardedPrefix`

The key coding like this:
```
	private static String prependForwardedPrefix(HttpServletRequest request, String path) {
		String prefix = null;
		Enumeration<String> names = request.getHeaderNames();
		while (names.hasMoreElements()) {
			String name = names.nextElement();
			if ("X-Forwarded-Prefix".equalsIgnoreCase(name)) {
				prefix = request.getHeader(name);
			}
		}
		if (prefix != null) {
			path = prefix + path;
		}
		return path;
	}
```
So, If we want to change the `BASE URL`, we can just simply change the `Http Header` in zuul filter like this:
```
    @Override
    public Object run() {
        RequestContext context = RequestContext.getCurrentContext();
        context.addZuulRequestHeader("x-forwarded-prefix", null);     // 解决swagger base url问题
    }
```

**Comment by dilipkrish** [comment]
@wubinhong thanks for sharing!

**Comment by rickgong** [comment]
After ContextPathCompositeHandler enabled in webflux application, the bathpath is still the root path "/".

Seems the Swagger2ControllerWebFlux hard coded base path to "/".

Compiled from master branch, version springfox-swagger2-2.9.0-SNAPSHOT.jar.

**Comment by dilipkrish** [comment]
@rickgong springfox 2.9.0 isn't event released!

**Comment by gvinay** [comment]
I was able to get it to work with the below property in application.yml. 
**Note:** The api adds the protocol so just have the host name for the value along with the service name if you have Zuul & Eureka setup
springfox.documentation.swagger.v2.host= <hostname>/<Eureka Service>

**Comment by vivekvarya** [comment]
@hydra1983 Unable to resolve dependencies for 
AnnotationUtils.getAnnotation, PropertySourcedMapping, new Swagger2Controller
in the code you've posted. i'm also in need of a reverse proxy solution do share!

**Comment by dilipkrish** [comment]
@vivekvarya dont know what version you're using but please use the latest released version of springfox (2.9.0 currently). Also for reverse proxy you need to set it up with the right X-Forward-xxxxx headers for your upstream

**Comment by vivekvarya** [comment]
@dilipkrish Thanks for the tip! upgraded dependency to 2.9.0 and the application would refuse to start. Hence downgraded to 2.8.0 and added @hydra1983  code. seems to be working fine through reverse proxy. For some reason did not have to upstream in proxy.

**Comment by dilipkrish** [comment]
@vivekvarya Great its working in 2.8.0. Mind sharing why it failed to start? I'd like to fix it if possible. BTW 2.9.2 is the latest.

**Comment by vivekvarya** [comment]
@dilipkrish Yeah 2.9.2 is what i meant(just kept with your syntax). Have attached the error! Do let me know!, will like to use the latest possible version itself.
[Swagger error.txt](https://github.com/springfox/springfox/files/2140210/Swagger.error.txt)

**Comment by dilipkrish** [comment]
You most likely have an incorrect version of google guava resolved. Make sure you're [using the right version](https://github.com/springfox/springfox/blob/2.9.2/gradle/dependencies.gradle#L7)

**Comment by mlippens** [comment]
@dilipkrish I also stumbled upon this (the need to upgrade guava to 20.0 at least) this should be in the release notes of swagger 2.9.2, where can I report this?

**Comment by vijaychd** [comment]
i have plenty of api with swagger 2.4 giving issues in registration to zuul.  Changing all APIs to latest swagger version is not an option at this time.  Is there a way i can change basePath in aggrgated swagger resources in zuul gateway?

**Comment by dilipkrish** [comment]
@mlippens Guava dependency has been removed in the upcoming 3.0.0

**Comment by dilipkrish** [comment]
@vijaychd The best way I know is to upgrade dependencies.

**Comment by rickgong** [comment]
The solution from @jonaskoperdraat seems only works with WebMvc, since WebFlux's bathPath is hardcoded to ROOT. See: [Swagger2ControllerWebFlux.java](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2ControllerWebFlux.java#L91). Mentioned this [here](https://github.com/springfox/springfox/issues/1443#issuecomment-382220147) and [#2629](https://github.com/springfox/springfox/issues/2629).  Please correct me if i did something wrong.

**Comment by patpatpat123** [comment]
Hello, any update on this?
with 3.0.0, /something/v2/api-docs is not working anymore, while it was with previous versions.

**Comment by marvatom** [comment]
Hi all, I was able to get it working behind Zuul reverse proxy.

I'm using  Spring Cloud proxy with Zuul and Spring cloud discovery using Eureka (cloud dependecies in version Finchley.SR1). All in Spring Boot (version 2.0.5.RELEASE). I use Springfox 2.9.2 as Swagger implementation.

Services in my architecture exposes Swagger using standard Docket configuration. To change basePath from default is sufficient to provide following property in Spring Boot property source:
`springfox.documentation.swagger.v2.path=/apidoc`
Springfox in version 2.9.2 is able to deal with requests from proxy out of the box. When request come from proxy (headers x-forwarded-... are present) Springfox turns on base path resolver which is able to construct base path from such headers. This would work out of the box if there wouldn't be exception during resolving path. During process of resolvig Springfox tries to get spring version using static method `org.springframework.core.SpringVersion.getVersion()` which returns null in my case. To overcome this issue I have to add my own class `org.springframework.core.SpringVersion` on classpath. My custom class returns version as static string (in my case "5.0.9.RELEASE"). This is in my oppinion an ugly hack but I didn't discover any other simple solution (I don't want to play with classloaders :)). Any help on this will be appreciated!

Swagger UI is only on gateway. UI collects Swagger doc from services - I use custom resource provider to achive this. There is no need to add the custom filter injecting x-forwarded-path header - Zuul in version 1.3.1 (version is automatically picked up by cloud dependencies BOM) do it automatically. My gateway config:
**properties**
```
zuul:
  prefix: /api
    address:
      path: /address/**
      service-id: address-service
```
**spring boot configuration**
```java
@Primary //to choose this bean instead of InMemorySwaggerResourcesProvider one (and of course to prevent conflict on startup)
@Bean
public SwaggerResourcesProvider swaggerResourcesProvider(InMemorySwaggerResourcesProvider defaultResourceProvider){
        return () -> {
            List<SwaggerResource> swaggerResources = List.of(
                    createSwaggerResource("address-service", "/api/address/apidoc", "2.0")
            );
            return swaggerResources;
        };
    }
```
.... where `createSwaggerResource` is only factory method for SwaggerResource.

Hope it helps...

**Comment by silentsnooc** [comment]
@jonaskoperdraat So.. should

```

@Bean
public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2)
            .host("localhost:8443")
            .pathProvider(new RelativePathProvider(servletContext) {
                @Override
                public String getApplicationBasePath() {
                    return "/r/api/v1/docs";
                }
            });
}
``` 

change

https://localhost:8443/swagger-ui.html

to

https://localhost:8443/r/api/v1/docs/swagger-ui.html

..? Because if so, it's now working for me. Am I missing something?

**Comment by jonaskoperdraat** [comment]
@silentsnooc honestly, I don't know. It's been 2,5 years, and I haven't worked with Swagger on this level since.

As I recall, I came up with the solution by looking through the source code. That might help you as well.

Good luck!

**Comment by Boblebol** [comment]
Hi, 
I've exactly the same issue as @silentsnooc . 
Here is any news on this subject ?

**Comment by 4dk1998** [comment]
/**
     * @OA\OpenApi(
     *     @OA\Info(
     *         version="1.0.0",
     *         title="Lumen Swagger Tutorial",
     *     ),
     *     @OA\Server(
     *         description="Base url server",
     *         **url="http://localhost/lumen2020/",**
     *     ),
     * )
     */

try in this way

**Comment by jpli** [comment]
> If you use spring cloud `Zuul` to proxy your micro-services, you can take my example.
> ![image](https://user-images.githubusercontent.com/7396720/38403515-9043b2e2-3996-11e8-80a9-033dc574fd37.png)
> 
> I found this what it work by taking a look at the source code of `springfox-swagger2-2.5.0`:
> 
>     * The `BASE URL` determined by the ajax request: `/v2/api-docs` , so I look deep into the `Swagger2Controller#getDocumentation()` --> `springfox.documentation.swagger2.web.HostNameProvider#componentsFrom` --> `org.springframework.web.servlet.support.ServletUriComponentsBuilder#fromServletMapping` --> `org.springframework.web.servlet.support.ServletUriComponentsBuilder#prependForwardedPrefix`
> 
> 
> The key coding like this:
> 
> ```
> 	private static String prependForwardedPrefix(HttpServletRequest request, String path) {
> 		String prefix = null;
> 		Enumeration<String> names = request.getHeaderNames();
> 		while (names.hasMoreElements()) {
> 			String name = names.nextElement();
> 			if ("X-Forwarded-Prefix".equalsIgnoreCase(name)) {
> 				prefix = request.getHeader(name);
> 			}
> 		}
> 		if (prefix != null) {
> 			path = prefix + path;
> 		}
> 		return path;
> 	}
> ```
> 
> So, If we want to change the `BASE URL`, we can just simply change the `Http Header` in zuul filter like this:
> 
> ```
>     @Override
>     public Object run() {
>         RequestContext context = RequestContext.getCurrentContext();
>         context.addZuulRequestHeader("x-forwarded-prefix", null);     // 解决swagger base url问题
>     }
> ```

Thank you @wubinhong , your share provides the missing part on configuring nginx reverse proxy for swagger service: **x-forwarded-prefix**.

```
http {
    upstream swagger_server {
        server 127.0.0.1:12345 fail_timeout=0;
    }

    server {
        # ...
        location /proxy_path/ {
                proxy_set_header        Host $host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
                proxy_set_header        X-Forwarded-Prefix /proxy_path; # Send swagger the base path
                proxy_redirect off;
                proxy_pass http://swagger_server/;
        }
    }
    # ...
}
```

**Comment by alexmuntean** [comment]
I fixed this just by adding `server.servlet.context-path: /api/authentication` to my application.properties in spring. you need it anyway :)

**Comment by dilipkrish** [comment]
Possible duplicate of #3104 ... definitely has information that can be used to help in the future

**Comment by snagiel** [comment]
The problem with `server.servlet.context-path` is that it affects everything in Spring-land, so if you have an ingress controller (or other reverse proxy) that routes requests based on some path, then setting this value in Spring would effectively double-bag your requests (/myapi/myapi/...).

The solution that worked for me is buried above, namely using the [Docket.pathMapping("/myapi")](http://springfox.github.io/springfox/javadoc/2.4.0/springfox/documentation/spring/web/plugins/Docket.html#pathMapping(java.lang.String)) setter, which, combined with an environment variable, allows us to do without it on local builds but apply it when behind the reverse proxy.

**Comment by zwbetz-gh** [comment]
@snagiel Thanks for the advice. 

For future readers, this seemed to work for us. Will include the relevant snippets from each file:

File `build.gradle`

```groovy
// ...

implementation "io.springfox:springfox-swagger2:2.9.2"
implementation "io.springfox:springfox-swagger-ui:2.9.2"
```

File `src/main/resources/application.yml`

```yml
# For higher environments using nginx reverse proxy
swagger:
  pathMapping: ${SWAGGER_PATH_MAPPING:/api}

---

# For local environments
spring:
  profiles: local
swagger:
  pathMapping: ${SWAGGER_PATH_MAPPING:/}
---
```

File `src/main/java/.../SwaggerConfig.java`

```java
// ...

@Log4j2
@Configuration
public class SwaggerConfig {

  @Value("${swagger.pathMapping}")
  private String swaggerPathMapping;

  @Bean
  public Docket customDocket() {
    log.info("swaggerPathMapping: '{}'", swaggerPathMapping);
    
    return new Docket(DocumentationType.SWAGGER_2)
        .useDefaultResponseMessages(false)
        .pathMapping(swaggerPathMapping)
        // ...
        .build();
  }

}
```
