### ISSUE TITLE
Support for rendering parameters and model attributes when no annotations are present

### ISSUE THREAD

**Issue by tianchengbaihe** [springfox/springfox#1444]
I am using 2.5.0 version.

I have a method like:
`list(Integer size, Integer page, String name)`

When it renders, the parameterContentType of these params are all application/json, but not their own types(int, string).

Is there anyway to render them correctly without any annotations?

Thanks

**Comment by dilipkrish** [comment]
What do you mean `parameterContentType`? They should be rendered as query parameters if they have the right annotations like `@RequestParam` or `@PathVariable`. May be I'll make this a feature to implement with a flag to use to render primitives  and objects without `@ModelAttribute` as query parameters
