### ISSUE TITLE
Without @ComponentScan - how?

### ISSUE THREAD

**Issue by achoice** [springfox/springfox#1446]
Quick question: can I use springfox swagger *without* @ComponentScan annotation?
If so - how? (2.5.0 springfox & springboot 1.3+)

**Comment by dilipkrish** [comment]
Could you clarify? without `@ComponentScan` where? If you're talking about not using `@EnableSwagger2` annotation then its possible Only you'd have to do all of the bean registration yourself. I believe someone has done it already

**Comment by dilipkrish** [comment]
Here is [the issue](https://github.com/springfox/springfox/issues/1092) where @SergiiShapoval has an example with direct bean registration

**Comment by achoice** [comment]
@EnableSwagger2 is ok, but we create beans "manually" (in @Configuration components, with constructor arguments) and hence does not use @ComponentScan (Less magic - more control)

I looked at the linked issue but cant understand how to do the "direct bean registration"?

**Comment by dilipkrish** [comment]
@achoice Check out [this fork](https://github.com/SergiiShapoval/springfox-demos/tree/directBeanDeclaration) especially how he's done the [direct bean registration](https://github.com/SergiiShapoval/springfox-demos/tree/directBeanDeclaration/spring-java-swagger/src/main/java/springfoxdemo/java/swagger/beans)

**Comment by achoice** [comment]
@dilipkrish in that example I still see
`@ComponentScan(basePackageClasses` = PetController.class)`
I am OK enabling Componentscan for Swagger/springfox-stuff if needed. But I do want to create the actual rest-controller myself. I expected something like;
`docket.addController(restController) // manually add a controller for Swagger to document`

**Comment by dilipkrish** [comment]
Ah ok. You can register the controller yourself as a bean. No need to add it specifically to the docket. It will automatically be picked up.

```java
// In your config

@Bean 
public PetController pets() {
    return new PetContoller(...);
}

```

thats it. Springfox will pick it up as long as its a controller.

**Comment by achoice** [comment]
Thanks again for prompt reply. server-error-controller is picked up. I now see we create our controllers in separate **sub-web-application-contexts**. Perhaps that confuses/ makes them invisible for Springfox. (This complexity is to separate context for internal/ external use / security stuff.)

`
/* ProviderNotificationConfiguration creates the Controller as a bean */
@Bean
public ServletRegistrationBean providerCallbackApiServletRegistrationBean() {
    return createChildContext(ProviderNotificationConfiguration.class,
            "providerCallbackApiServletRegistrationBean",
            "/entercash/provider-api/*");
}
private ServletRegistrationBean createChildContext(Class context, String name, String... urlMappings) {
    /* create the context */
    AnnotationConfigWebApplicationContext annotationConfigWebApplicationContext = new AnnotationConfigWebApplicationContext();
    annotationConfigWebApplicationContext.register(context);
    annotationConfigWebApplicationContext.setParent(this.applicationContext);

    /* create the dispatcher servlet */
    DispatcherServlet dispatcherServlet = new DispatcherServlet();
    dispatcherServlet.setDetectAllHandlerExceptionResolvers(false);
    dispatcherServlet.setApplicationContext(annotationConfigWebApplicationContext);

    /* create the servlet registration bean */
    ServletRegistrationBean servletRegistrationBean = new ServletRegistrationBean(dispatcherServlet, urlMappings);
    servletRegistrationBean.setName(name);
    servletRegistrationBean.setLoadOnStartup(1);
    return servletRegistrationBean;
}
//...
`

**Comment by dilipkrish** [comment]
@achoice yeah it is complex. Perhaps if you can isolate your problem to a small working sample repo and share I could take a look
