### ISSUE TITLE
Swagger ui lists POST/PUT/DELETE/OPTIONS/HEAD/PATCH  operations for every GET op

### ISSUE THREAD

**Issue by mshridhar** [springfox/springfox#1447]
I am using Swagger 2 in my Spring Boot application. I have 2 GET methods in my rest controller class which I expose through Swagger. Now in the Swagger page when I bring up the list of operations, for each of these GETs it also lists POST/PUT/DELETE/OPTIONS/HEAD/PATCH ops which I clearly do not want. How do I turn this off so that I could see only the 2 GETs that I intended ?

This is what I have in my POM. 

 ```
       <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.2.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.2.2</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by mshridhar** [comment]
I could resolve this. My RequestMapping was not using method parameter earlier. The following illustrates it.

```
 //@RequestMapping("/greeting/{lang}")
@RequestMapping(value = "/greeting/{lang}", method = RequestMethod.GET)

```

**Comment by FarianHadi** [comment]
You are right!!! After looking the answer for couple hours, finally .... I follow your suggestion and it works.
Thanks bro

**Comment by dilipkrish** [comment]
Please use 2.7.0 tho' @FarianHadi

**Comment by FarianHadi** [comment]
hemm, I use 2.6.1 at the moment, okay perhaps I will try later, thanks

**Comment by muwednesday** [comment]
Do you have another sulotion?  My project is too old and has hundreds of method only using @RequestMapping annotation. I just want to show all GET and PUST methods in swagger docs. Could you please help? @dilipkrish

**Comment by darkjune** [comment]
> Do you have another sulotion? My project is too old and has hundreds of method only using @RequestMapping annotation. I just want to show all GET and PUST methods in swagger docs. Could you please help? @dilipkrish

me too
