### ISSUE TITLE
ApiIgnore/ApiParam#hidden not work for global paramters

### ISSUE THREAD

**Issue by steventong** [springfox/springfox#1451]
version: 2.5.1-snapshot

there is a header type paramter "Authorization"  defined in my Swagger2Configuration.class globalOperationParameters.
`parameterList.add(new ParameterBuilder().name("Authorization").description("Bearer Token").modelRef(new ModelRef("string")).parameterType("header").required(false).defaultValue("Bearer Token XXXX").build());`

`.globalOperationParameters(parameterList)`

 When i use ApiIgnore in my Controller like this.
`@ApiIgnore @RequestHeader String AuthorizationTemp`
it work.

But like this:
`@ApiIgnore @RequestHeader String Authorization`
"Authorization" still here.

**Comment by steventong** [comment]
version 2.5.1-snapshot

**Comment by dilipkrish** [comment]
Added `ApiIgnore.class`to the ignorableTypes in your docket and see if t fixes your problem

**Comment by steventong** [comment]
Add ApiIgnore.class to the ignorableTypes not work for globalOperationParameters

**Comment by dilipkrish** [comment]
Sorry I dint understand what you asked initially.

Global parameters are meant to be not ignorable. I believe there is a feature to implement a predicate based parameter addition.

**Comment by steventong** [comment]
@dilipkrish 
OK.
What i want to do is to ignore the "Authorization" header param at my login api.

**Comment by dilipkrish** [comment]
Add it to the ignorableTypes.

**Comment by steventong** [comment]
Thanks for the relpy.
And I sensed there might be some misunderstanding here.
So, let me make myself more clear.
I have a "Authorization" head value, I would let to include in most of my api, so I added  "Authorization" as globalOperationParameters. 
And when I want to exclude "Authorization" in some of the apis, I found "@ApiIgnore @RequestHeader String Authorization" not working as I expected. 
And I already added ApiIgnore.class to the ignorableTypes in docket as you suggested.
`        return new Docket(DocumentationType.SWAGGER_2)
                .ignoredParameterTypes(CurrentUser.class, ApiIgnore.class)
                .globalOperationParameters(parameterList)
                .useDefaultResponseMessages(false)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.basePackage("io.xxxxxx.api.controller"))
                .paths(PathSelectors.any())
                .build();`
And I don't know if it's a bug, or it's the correct behavior.

**Comment by dilipkrish** [comment]
Ah got it! sorry for the misunderstanding.

Hmm thats a tricky one. Not sure if there is a good way to do that just yet. There is however a plan to provide a way to specify predicates for the global parameters.

**Comment by steventong** [comment]
:+1:

**Comment by paulocdf** [comment]
Is there something similar to what was suggested in this issue available now?, where a global parameter is defined but excluded for a particular method or controller?

**Comment by dilipkrish** [comment]
Not yet unfortunately

**Comment by wenzuowei110** [comment]
any update?
