### ISSUE TITLE
Enable Externalization in Swagger Springfox i.e. read @APIResponse messages from properties files

### ISSUE THREAD

**Issue by sac10nikam** [springfox/springfox#1452]
Externalization in Swagger Springfox i.e. read @APIResponse messages from properties files.

Problem statement.
@ApiOperation(value = "updateMe", notes = "Updates the retirement plan", responseContainer = "Object")
    @ApiResponses(value = { @ApiResponse(code = 200, message = "Success"),
            @ApiResponse(code = 400, message = "Bad Request", response = ReturnResponse.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = ReturnResponse.class),
            @ApiResponse(code = 403, message = "Forbidden", response = ReturnResponse.class),
            @ApiResponse(code = 404, message = "Not Found", response = ReturnResponse.class),
            @ApiResponse(code = 500, message = "Internal server error occured", response = ReturnResponse.class) })
    @RequestMapping(value = MoneyURIConstants.RETIREMENTPLAN_CONTRIBUTION, method = RequestMethod.PUT)
    public ReturnResponse<?> updateMe(@PathVariable String employeeId, @PathVariable String company,
            @RequestBody Employee, HttpServletRequest request);

Here I would like enable/add messages of api responses from property file.

like
@ApiResponses(value = { @ApiResponse(code = 200, message = "${get.success}"),

**Comment by dilipkrish** [comment]
This is under implementation via this #1371

**Comment by sac10nikam** [comment]
I have created custom plugins and using it from project. The properties file having key-values is created. but I don't know how to call it from Swagger Controller.

1) 
**ControllerInterface- method**

**@ApiOperation(value = "get_contribution_api_name", notes = "get_contribution_api_notes", responseContainer = "List<Plan>")**
    **@DescriptorKey("get_contribution_api_notes")**
    @ApiResponses(value = { @ApiResponse(code = 200, message = "Success"),
            @ApiResponse(code = 400, message = "Bad Request", response = Response.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = Response.class),
            @ApiResponse(code = 403, message = "Forbidden", response = Response.class),
            @ApiResponse(code = 404, message = "Not Found", response = Response.class),
            @ApiResponse(code = 500, message = "Internal server error occured", response = Response.class) })
    @RequestMapping(value = URIConstants.PLAN_CONTRIBUTION, method = RequestMethod.GET)
    public Response<List<Plan>> **getContribution**(@PathVariable String employeeId,
            @PathVariable String company);

2) property reader class
@Service(value = "environmentConfig")
@Scope(value = "singleton")
@PropertySources
({
@PropertySource(value=**"classpath:/Project/swagger/api-plan-specs/src/resources/swagger-messages.properties**",ignoreResourceNotFound=true)
})
public class **EnvironmentConfig** {

    private static final Logger LOGGER = LoggerFactory.getLogger(EnvironmentConfig.class);
    @Autowired
    private Environment environment;
    private static Environment env;

    @PostConstruct
    public void init() {
        env = environment;
    }

    public static String getProperty(String key) {
        LOGGER.debug("Getting property  :" + key);
        return env.getProperty(key);
    }
}

3) Properties file
swagger-messages.properties

#Swagger errors
get_contribution_api_name=getContribution
get_contribution_api_notes=Gets the list of plan

4) plugins
![image](https://cloud.githubusercontent.com/assets/6522168/17772304/bb1ce6ac-6565-11e6-9b1a-71f614773fac.png)

5) Validators
![image](https://cloud.githubusercontent.com/assets/6522168/17772337/d70e50da-6565-11e6-8b39-9b4347f902a7.png)

Please guide me here. I want to show property values from resource bundle.

**Comment by dilipkrish** [comment]
@sac10nikam please don't cross post to unrelated issues.

**Comment by sac10nikam** [comment]
Ok. Sorry
