### ISSUE TITLE
Example of Supply the text values for `@ApiOperation, @ApiResponse, @ApiParam, @ApiModelProperty from an external resource file, instead of hardcoding

### ISSUE THREAD

**Issue by sac10nikam** [springfox/springfox#1455]
I want to see running example of 

Supply the text values for `@ApiOperation, @ApiResponse, @ApiParam, @ApiModelProperty from an external resource file, instead of hardcoding

**Comment by dilipkrish** [comment]
There is no running example. You'd have to write your own plugins to do that.

**Comment by sac10nikam** [comment]
Can you guide here please

**Comment by sac10nikam** [comment]
I have created custom plugins and using it from project. The properties file having key-values is created. but I don't know how to call it from Swagger Controller.

1) 
**ControllerInterface- method**

**@ApiOperation(value = "get_contribution_api_name", notes = "get_contribution_api_notes", responseContainer = "List<Plan>")**
    **@DescriptorKey("get_contribution_api_notes")**
    @ApiResponses(value = { @ApiResponse(code = 200, message = "Success"),
            @ApiResponse(code = 400, message = "Bad Request", response = Response.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = Response.class),
            @ApiResponse(code = 403, message = "Forbidden", response = Response.class),
            @ApiResponse(code = 404, message = "Not Found", response = Response.class),
            @ApiResponse(code = 500, message = "Internal server error occured", response = Response.class) })
    @RequestMapping(value = URIConstants.PLAN_CONTRIBUTION, method = RequestMethod.GET)
    public Response<List<Plan>> **getContribution**(@PathVariable String employeeId,
            @PathVariable String company);

2) property reader class
@Service(value = "environmentConfig")
@Scope(value = "singleton")
@PropertySources
({
@PropertySource(value=**"classpath:/Project/swagger/api-plan-specs/src/resources/swagger-messages.properties**",ignoreResourceNotFound=true)
})
public class **EnvironmentConfig** {

    private static final Logger LOGGER = LoggerFactory.getLogger(EnvironmentConfig.class);
    @Autowired
    private Environment environment;
    private static Environment env;

    @PostConstruct
    public void init() {
        env = environment;
    }

    public static String getProperty(String key) {
        LOGGER.debug("Getting property  :" + key);
        return env.getProperty(key);
    }
}

3) Properties file
swagger-messages.properties

#Swagger errors
get_contribution_api_name=getContribution
get_contribution_api_notes=Gets the list of plan

4) plugins
![image](https://cloud.githubusercontent.com/assets/6522168/17772304/bb1ce6ac-6565-11e6-9b1a-71f614773fac.png)

5) Validators
![image](https://cloud.githubusercontent.com/assets/6522168/17772337/d70e50da-6565-11e6-8b39-9b4347f902a7.png)

Please guide me here. I want to show property values from resource bundle.
