### ISSUE TITLE
@APIResponse for client errors(400+), server errors(500+) from common place

### ISSUE THREAD

**Issue by sac10nikam** [springfox/springfox#1457]
@APIResponse for client errors(400+), server errors(500+) from common place

Query:
I want to use common APIResponse from some common place. Instead of writing APIResponses like Bad Request, NotFOund, server error, unauthorized to every endpoint/service method. I want to use common error messages for these responses from single place.

**Comment by dilipkrish** [comment]
You need to use the [global response messages](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L178) method

**Comment by sac10nikam** [comment]
Thanks it works.
