### ISSUE TITLE
fetching resource list: http://localhost:8080/v2/api-docs; Please wait.

### ISSUE THREAD

**Issue by xuminwlt** [springfox/springfox#1459]
I use springfox 2.5.0 with springmvc xml config.

```xml
<!--api swagger-->
    <!-- Standard xml based mvc config-->
    <mvc:annotation-driven enable-matrix-variables="true"/>

    <!-- Enables swgger ui-->
    <mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/"/>
    <mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/"/>

    <!-- Include a swagger configuration-->
    <bean name="applicationSwaggerConfig" class="com.fotoplace.config.ApplicationSwaggerConfig"/>
```

```java
@EnableSwagger2
public class ApplicationSwaggerConfig {


    @Bean
    public Docket customDocket(){
        return new Docket(DocumentationType.SWAGGER_2);

    }
}
```

but,i don't get the v2/api/docs response content,now it's = {}

**Comment by xuminwlt** [comment]
I have used the spring Converter in my config.
com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter

<mvc:message-converters register-defaults="true">
            <bean class="org.springframework.http.converter.StringHttpMessageConverter">
                <constructor-arg value="UTF-8"/>
            </bean>
            
            <bean class="com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter">

</mvc:message-converters>

if i remove the xml, then it works.

**Comment by dilipkrish** [comment]
Springfox supports jackson out of the box. Try [this suggestion](https://github.com/springfox/springfox/issues/1339#issuecomment-236146481) to see it lets you move forward with your problem

**Comment by xuminwlt** [comment]
hi，fastjson1.2.15+ has fix this bug，do not need to modify any code.
该问题解决已合并入fastjson 1.2.15版本，请使用1.2.15+版本就不需要做下面的改造了

**Comment by dilipkrish** [comment]
@xuminwlt thanks for the update

**Comment by dilipkrish** [comment]
@xuminwlt could you elaborate what the fix was in fastjson and how it affected your setup. It will help other people having similar issues.

**Comment by dilipkrish** [comment]
Closing this for now, once you update details I can update the documentation. Thanks in advance 🙇
