### ISSUE TITLE
Getting HTTP 404 error on /swagger-ui.html but other swagger endpoint works

### ISSUE THREAD

**Issue by meetmrdeepak** [springfox/springfox#1460]
Getting HTTP 404 error on http://localhost:8080/myapp/swagger-ui.html, while integrating swagger-ui in RESTful API app (spring-boot app). 

Other swagger endpoints are working as expected (/swagger-resources/configuration/ui, /swagger-resources/configuration/security, /v2/api-docs). I can see the JSON response. 

- Versions Info
   - spring-boot 1.3.5 (spring-boot-starter-tomcat). 
   - Swagger 2.5.0 for both springfox-swagger2 & springfox-swagger-ui
- This is a spring-boot app and serves RESTful api's and does not have any static content. Hence no webapp, web, META-INF/resources etc folders in source code. 
- pom.xml
```xml
<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.5.0</version>
        </dependency>
```
- I am not using @EnableWebMvc anywhere in code 
- SwaggerConfiguration.java
```java
@Configuration
@EnableSwagger2
@Profile("dev")
public class SwaggerConfiguration implements EnvironmentAware {
  @Bean
  public Docket swaggerSpringfoxDocket() {
    Docket docket = new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo())
            .genericModelSubstitutes(ResponseEntity.class).forCodeGeneration(true)
            .genericModelSubstitutes(ResponseEntity.class)
            .directModelSubstitute(LocalDate.class, String.class)
            .directModelSubstitute(LocalDateTime.class, Date.class)
            .directModelSubstitute(ZonedDateTime.class, Date.class).select()
            .paths(regex("/api/.*")).build();
    return docket;
  }
  private ApiInfo apiInfo() {
    return new ApiInfo(propertyResolver.getProperty("title"),
            propertyResolver.getProperty("description"),
            propertyResolver.getProperty("version"),
            propertyResolver.getProperty("termsOfServiceUrl"),
            new Contact(propertyResolver.getProperty("contact.name"),
                    propertyResolver.getProperty("contact.url"),
                    propertyResolver.getProperty("contact.email")),
            propertyResolver.getProperty("license"),
            propertyResolver.getProperty("licenseUrl"));
  }
```
- Not sure if this will impact, but i do have below for configuring Metrics
```java
@Configuration
public class WebConfigurer implements ServletContextInitializer, EmbeddedServletContainerCustomizer {
  @Autowired(required = false)
  private MetricRegistry metricRegistry;
```

**Comment by dilipkrish** [comment]
Just guessing it seems like spring boot isn't picking up the resources automatically. You may have to [manually set up the resources](http://springfox.github.io/springfox/docs/current/#q13).

**Comment by meetmrdeepak** [comment]
Found the root cause in my case. Was stupid mistake. 

application.yml (app config) has below preventing other static mappings to be resolved.
```yaml
# Locations of static resources.
spring.resources.static-locations: classpath:/webapp/
```
Removed the same from application configuration and swagger-ui.html came up.

**Comment by jjathman** [comment]
I realize this is closed, but for people with similar problems the issue I had was we had a class extending the WebMvcConfigurationSupport and overriding methods, but we should have been using WebMvcConfigurerAdapter and overriding methods there. That fixed our issues.

**Comment by dilipkrish** [comment]
@jjathman thanks for that tip! Yes If I remember right, when you implement `WebMvcConfigurationSupport`, spring boot assumes you're in charge of all the configuration and will disable auto configuration.

**Comment by Mohan74** [comment]
I am facing similar problem for integrate with swagger with spring boot. Using **http://localhost:8080/v2/api-docs** URL, JSON dump that Swagger 2 generates for my endpoints but not in human friendly (in Swagger UI). When I try to access http://localhost:8080/swagger-ui.html URL I am getting following error in console. 
No mapping found for HTTP request with URI [/swagger-ui.html] in DispatcherServlet with name 'dispatcherServlet'
Any idea to solve the problem ?

**Comment by dilipkrish** [comment]
@Mohan74 No idea, it depends on the configuration of your project

**Comment by Srimukh99** [comment]
i am facing the same problem too .. No webpage was found for the web address: http://localhost:8085/
HTTP ERROR 404

**Comment by dilipkrish** [comment]
@Srimukh99 if you can share your repository or may be reproduce it minimally in a separate project without revealing proprietary code, ill take a look and see if I can help.

**Comment by vinayjangir7** [comment]
@dilipkrish - I have tried all the above solutions and i am still facing this issue. But still getting "No mapping found for HTTP request with URI [/swagger-ui.html] in DispatcherServlet with name 'dispatcherServlet'" error. 
I am running Spring boot 2.0.2.RELEASE with Swagger 2.8.0 version. I have added below manual mappings for Swagger-ui.html also. See the below code - 
`@Configuration
@AutoConfigureAfter(DispatcherServletAutoConfiguration.class)
@SuppressWarnings("deprecation")
public class ResourceHandlerConfig extends WebMvcConfigurerAdapter {
	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/swagger-ui.html**")
				.addResourceLocations("classpath:/resources/swagger-ui.html");
		registry.addResourceHandler("/webjars/**")
				.addResourceLocations("classpath:/resources/webjars/");
	}
}
`

**Comment by dilipkrish** [comment]
With spring boot you dont need to add the resource handling configuration at all @vinayjangir7

**Comment by Vladis466** [comment]
Either way, the same behaviour persists. 
Once Spring Security package is included, cannot navigate to /swagger-ui.html but every other swagger resource is available.
Kind of an interesting tidbit that if I remove that package spring boot is able to route correctly again,

**Comment by dilipkrish** [comment]
You need to tell spring security to permit the swagger resources and swagger-ui.

**Comment by dilipkrish** [comment]
@Vladis466 I plan to create a demo project with spring security and how its done. For one, most of these problems/solutions are one-offs and documentation [is already available](http://springfox.github.io/springfox/docs/current/#q26), its just a matter of looking.

**Comment by BahgatMashaly** [comment]
I have encountered this problem before and the problem was in the below line in application.properties
spring.resources.add-mappings=false

remove it or change it's value to true

**Comment by geektcp** [comment]
I found the really reason, because of @ComponentScan, and u must to annotate it , for example: 
//@ComponentScan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})

and then , it will be ok,  u can open the swagger-tui.html and /swagger-resources/configuration/ui

**Comment by geektcp** [comment]
swagger启动后，老是报错下面的url无法打开swagger-ui.html，
提示内部url无法打开swagger-resources/configuration/ui

原因是：
启用了组件扫描导致：@ComponentScan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})
这个问题真是费解。

解决办法：注释掉扫描注解即可：
//@componentscan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})

**Comment by sarangajay** [comment]
Hi, I have a non spring boot app configured as explained in this doc , http://springfox.github.io/springfox/docs/current/#q13, but it fails to server the swagger-ui.html 
unless i add the 
**registry.("/**").addResourceLocations("classpath:/META-INF/resources/");**

but doing so made all the existing handler look up failed. basically i have swagger working and it broke the application. 

appreciate help please

**Comment by harsh342** [comment]
While loading the static resource like swagger-ui.html the request is getting routed via dispacher servlet as your servlet path is  /
Below change in application.yml, changing my dispacher servlet path worked for me.
server:
  servlet:
  path: /app/*

**Comment by farithjhg** [comment]
I was having the same issue but in the end it was matter to resolve maven dependency problems. just in case please see if you have any problem with the swagger dependency.

**Comment by muthusankar54** [comment]
can anyone explain how to map swagger configuration into dispatcher servlet file? currently am using spring version of 3

**Comment by islombektoshev** [comment]
Hi, Also I was facing this problem, I found `@EnableWebMvc` annotation If I use this annotation Swagger UI will not work then I removed that now It's working

**Comment by DoronRippel** [comment]
> Hi, Also I was facing this problem, I found `@EnableWebMvc` annotation If I use this annotation Swagger UI will not work then I removed that now It's working

This worked for me - thanks!

**Comment by springamruta** [comment]
> Hi, Also I was facing this problem, I found `@EnableWebMvc` annotation If I use this annotation Swagger UI will not work then I removed that now It's working

Saved my day! Thanks!!

**Comment by pavelkryl** [comment]
I also received 404 on getting HTML UI docs. I am having spring boot webflux project and the resolution was fairly simple: current 3.0.0-SNAPSHOT version changed the UI URL to /swagger-ui/ instead of the old /swagger-ui.html

Remove all you explicit tweaks and [hacks](https://stackoverflow.com/questions/59440108/404-error-with-swagger-ui-and-spring-webflux) and just depend on the new springfox-boot-starter as written [here](https://github.com/springfox/springfox).

**Comment by txiasummer** [comment]
Hello! I had the same issue today. For me the problem was using springfox-swagger2:3.0.0 and springfox-swagger2-ui:3.0.0 but my spring boot is at 2.0.6.RELEASE. I cannot upgrade Spring Boot due to some dynamoDB depencies holding me back. Anyway, I kept getting the 404 when i went to /swagger-ui.html. I tried everything people suggested before and nothing worked. So in the end, I downgraded to swagger 2.9.2 and that worked for me. Hope this helps someone else! :)

**Comment by dilipkrish** [comment]
@txiasummer unfortunately that is true, I think spring boot 2.2 is significantly different that 3.0.0 had to make some implicit breaking changes. However until that time 2.9.2 is your best friend

**Comment by yura2201** [comment]
Faced the same problem and the [official migration recommendations](http://springfox.github.io/springfox/docs/current/#migrating-from-existing-2-x-version) have helped me.

**Comment by JuliusFaeustel** [comment]
For me worked http://localhost:9090/swagger-ui/index.html, together with the migration guide. :)
Found at https://github.com/springfox/springfox/issues/3345

**Comment by kalewp** [comment]
For me, it is working fine locally and able to access swagger-ui.html. But when deployed to containers in cluster and accessing the url from ALB, it's giving 404 NOT FOUND. Other swagger endpoints are accessible in dev env just not the swagger-ui.html. I do not have any class extending WebMvcConfiguration or adapter.

**Comment by makeajourney** [comment]
I faced the same problem using springfox 3.0.0. and I solved it by implementing the bean method defaultViewResolver.

```kotlin
@Bean
fun defaultViewResolver(): InternalResourceViewResolver? {
    return InternalResourceViewResolver()
}
```

**Comment by sidpro-hash** [comment]
I faced the same problem using springfox 3.0.0 and the [official migration](http://springfox.github.io/springfox/docs/current/#migrating-from-existing-2-x-version) and this [setup guide](https://keepgrowing.in/tools/how-to-set-up-spring-boot-app-documentation-with-springfox-3/) helped me.
