### ISSUE TITLE
Custom DocumentationPlugin

### ISSUE THREAD

**Issue by sac10nikam** [springfox/springfox#1461]
Any example of custom DocumentationPlugin

**Comment by dilipkrish** [comment]
This is [an example](https://github.com/springfox/springfox/blob/6220a370029213fac53b6bc76323fb2cbedb2a2e/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/DocumentationPluginsBootstrapper.java).

**Comment by sac10nikam** [comment]
Thanks.
