### ISSUE TITLE
Enable custom plugin like SwaggerOperationResponseClassReader

### ISSUE THREAD

**Issue by sac10nikam** [springfox/springfox#1462]
How to enable custom plugin like SwaggerOperationResponseClassReader or DocumentationPlugin in Swagger Springfox.

In configuration class we need to add @Bean for it and but Would like detailed steps and want to read properties from resource bundle file.

**Comment by dilipkrish** [comment]
Have you read [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)?
