### ISSUE TITLE
Type-level @ApiResponses are ignored

### ISSUE THREAD

**Issue by sworisbreathing** [springfox/springfox#1465]
Swagger-core allows the `@ApiResponses` annotation to be declared at either the type-level or the method-level, and the [javadoc for `@ApiResponse`](http://docs.swagger.io/swagger-core/current/apidocs/index.html?io/swagger/annotations/ApiResponse.html) says that

> ... class level annotations will be parsed only if an @ApiResponse annotation with the same code is not defined at method level or in thrown Exception

However, it seems that springfox only handles the `@ApiResponses` annotation when it is declared at method-level (even when using `useDefaultResponseMessages(false)`)

I've created a sample app to reproduce the issue. There are two copies of the same API, but one has the `@ApiResponses` annotation on the class declaration and the other has it at only the method-level.

### To reproduce:

---

1. clone https://github.com/sworisbreathing/springfox-issues
2. Start application via mvn spring-boot:run
3. Open URL http://localhost:8080/v2/api-docs (swagger specs) or http://localhost:8080/swagger-ui.html (html version).

Only the successful response is shown for `/type-level-annotation-api` endpoints, while `/method-level-annotation-api` endpoints have both the success and failure responses shown.

---

This issue is somewhat similar to #702, except that I'm using the current release of springfox (2.5.0 as of this writing) and the issue is specific to having the `@ApiResponses` annotation on the class instead of the method. I think there were a few other issues opened requesting a common place to define error responses, and while it's great that there's a place to put this globally (as noted in #1457), this still feels like a bug.

**Comment by dilipkrish** [comment]
You're right there is currently no way to provide controller level globals. Would love for community contributions on this one. 

The work around is to use globals provided via the docket configuration.

**Comment by marcellodesales** [comment]
:( That's sad... Getting into the same exact problem

**Comment by sworisbreathing** [comment]
@dilipkrish: I found a bit of spare time and created a PR for this one. Let me know what you think.
