### ISSUE TITLE
{} for Model Schema for all REST methods

### ISSUE THREAD

**Issue by cwhankey** [springfox/springfox#1466]
I'm not getting a model schema for any of my REST methods.  How can I resolve this?  

![image](https://cloud.githubusercontent.com/assets/10787463/17946928/6aef7610-6a18-11e6-9e3a-b5508beaeb3b.png)

**Comment by dilipkrish** [comment]
You could start by providing [more details](https://github.com/springfox/springfox/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by cwhankey** [comment]
- I'm using Springfox 2.5, with Spring  4.3.2, not Springboot.  
- Model has the Return type name but that is it, as shown in the "Swagger HTML" image.   Model Schema has {}, as shown in the original image.
- I listed the Java REST method declaration and the JSON returned by v2/api-docs that relate to that methods return type.  Swagger just seems to mark the return type as "Object".  The actual public properties are supposed to be here, correct?
- My Springfox config is listed below.  I needed the "requestMappingHandlerAdapter" section to avoid a NPE in Springfox.

**Swagger HTML**
![image](https://cloud.githubusercontent.com/assets/10787463/17976178/579632dc-6aba-11e6-8863-2a6bb208fc00.png)



**Swagger JSON returned by v2/api-docs**
```
   "definitions":{
      "Input":{
         "type":"object"
      }
   }
```


**Here is the Java REST service method declaration.**
```
	@ApiOperation(value="get Input for  ID", response=Input.class)
	@RequestMapping(value = "get/input/{Id}", method = RequestMethod.GET)
	public @ResponseBody Input getInput(@PathVariable int Id) throws Throwable 
	{	
		return _UserInterfaceImpl.getInput(Id);
	}
```


**My Springfox Config**
   ```
 <context:annotation-config/>
	 
	<mvc:annotation-driven/>
	
 	<bean id="jacksonObjectMapper" class="com.fasterxml.jackson.databind.ObjectMapper" />
 	
 	<context:component-scan base-package="com.application.controllers"/>
 	 	
	<bean id="swagger2Config" class="springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration" />
	<mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/" />
	<mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/" />
 
	<bean id="requestMappingHandlerAdapter"
	      class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">
      <property name="messageConverters">
        <list>
          <!--  We need MappingJackson2HttpMessageConverter for Swagger to work. --> 
          <ref bean="json2Converter" />
        </list>
      </property>
	 </bean>
	
	<bean id="json2Converter"   class="org.springframework.http.converter.json.MappingJackson2HttpMessageConverter">
```
	
	    <property name="supportedMediaTypes" value="application/json" />
	</bean>

**Comment by dilipkrish** [comment]
What does your `Input` class looks like?

**Comment by cwhankey** [comment]
The image below is what should appear.  I tried to create a slimmed-down code base that reproduced the issue, that I could send to you, but during the  slimming-down process, the issue went away.   Not sure how to proceed?  I can't send my app as is, but I'm not sure which "slimming down" action solved the issue.  Any thoughts?  Where in the Springfox code is the Model info being generated?

![image](https://cloud.githubusercontent.com/assets/10787463/18011003/170faf14-6b81-11e6-87fd-031863c21cef.png)

**Comment by dilipkrish** [comment]
Most likely its how you've configured the object mapper.

**Comment by cwhankey** [comment]
What is the solution?  No matter what I try, I just get {} for my Model Schema.  I tried things like Docket.alternateTypeRules() & Docket.directModelSubstitute(), but they do not seem to do anything.  

-  Are there any work-arounds?
-  Can I enable any extra logging to help resolve this?
-  What are the alternatives for configuring object mapper?
-  How can I set up Springfox so I can step thru the code while its running on my app?

**Comment by dilipkrish** [comment]
Would be useful if you could create a small working project that demonstrates the issue. There are so many variables that its hard to know whats going on. Have you tried moving to 2.5.0?

**Comment by cwhankey** [comment]
Have you tried moving to 2.5.0?   I can't run 2.5.0 at all.  My app gets to the following line in the console and stops: "s.d.s.w.s.ApiListingReferenceScanner - Scanning for api listing references ".

ill try & set up a sample.

**Comment by dilipkrish** [comment]
😖 sounds like a recursive problem. Looking forward to you example

**Comment by cwhankey** [comment]
OK, my sample is attached.  I slimmed this down to as small as possible a project.  Run it as is & you'll see that the Model Schema just gets a { }.

I did manage to figure out that the issues are due the Active MQ config entries in this spring file:bootstrap.clients.xml.  Comment out the two beans & the Model Schema will be populated.  However, I need those entries for my real app.

While created the small sample app I got past the "s.d.s.w.s.ApiListingReferenceScanner - Scanning for api listing references ." issue, though im not really sure how.  I can try & create another sample for that.

Let me know if you need more info.

[MySpringfoxTest2.zip](https://github.com/springfox/springfox/files/470850/MySpringfoxTest2.zip)

**Comment by dilipkrish** [comment]
@cwhankey I spent 10 mins trying to get it to run, unfortunately, doesn't run out of the box. I'd expect it to just work using a `mvn jetty:run` or `mvn tomcat7:run` and see what problem is. Honestly I don't have the time, sorry! Plus this project has way too many dependencies and Im not capable of wading through this.
