### ISSUE TITLE
Supporting of #issue1050 changing host url

### ISSUE THREAD

**Issue by ALEXSSS** [springfox/springfox#1468]
If you can please provide relevant maven dependency for this 
https://github.com/springfox/springfox/issues/1050
changing host url

**Comment by dilipkrish** [comment]
2.5.0. Have you read [the docs](http://springfox.github.io/springfox/docs/current/#q17)?

**Comment by ALEXSSS** [comment]
Thanks
Sorry for my stupid question(:
it is the first day with springfox
how can i add it in SwaggerConfig?

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket pscApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                //.groupName("PSC");
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.basePackage("restService.com.websystique.springmvc"))
                .paths(PathSelectors.any())
                .build();
        //PathSelectors.regex("/api/.*")
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("RestApiOfPSC")
                .description("REST API for PSC.")
                .build();
    }
}
```

**Comment by dilipkrish** [comment]
In your docket where you define your bean add the following 

`docket.host("http://yand.ru")`

**Comment by ALEXSSS** [comment]
It doesn't work for me
If you have time please look at 
http://stackoverflow.com/questions/39147582/how-to-set-host-url-for-springfox-more-exact-springfox-swagger2-in-spring-mvc

**Comment by varra4u** [comment]
I think you should not prefix with http/https, seems by default it is prefixing like below: 
I think he makes use of protocols option and if not available takes it from server url's protocol.

Looks good, thanks for commit.

**Comment by narraboss** [comment]
Hi,
I am facing the same issue, how to get the host name "yand.ru" if it is dynamic. in my case my rest service is running under DNS name and it doesn't need a port but in request spring url it appends the port to the dns when the rest call so the server is not reaching and get {error : no response from server } 
can some one help how to configure the docket for the DNS and running under load balancer . 

thank you
