### ISSUE TITLE
Can swagger document a SpringBoot MvcEndpoint?

### ISSUE THREAD

**Issue by nickgrealy** [springfox/springfox#1472]
- [x] What version of the library are you using? **`io.springfox:springfox-swagger2:2.5.0`**
- [x] Is it the latest version? **Yes**
- [x] Is this a question about how to do a certain thing? **Yes**

---

I'm currently in the process of trying out `Swagger2` on my `SpringBoot` project (it works great), however, it only picks up my `@RestController` classes.

I was wondering:

 1. Can it be used to pick up a `Spring-Actuator` [MvcEndpoint](http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/endpoint/mvc/MvcEndpoint.html) (how does it find handlers)?
 1. Can the `Swagger2` components (e.g. `/swagger-ui.html`, `/v2/api-docs`) be hosted under the management `address:port`, instead of `server.port`?

**Application.java**

```Java
@EnableSwagger2
@SpringBootApplication
public class Application {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }
}
```

**AdminController.java** (aka custom Actuator endpoint)

```Java
@Component
public class AdminController implements MvcEndpoint { ... }
```

**application.yml**

```Java
server.port: 8080
management.address: 127.0.0.1
management.port: 8081
```

**build.gradle**

```Groovy
compile("org.springframework.boot:spring-boot-starter-actuator")
compile "io.springfox:springfox-swagger2:2.5.0"
compile "io.springfox:springfox-swagger-ui:2.5.0"
```

**Versions:**

 - SpringBoot: `1.4.0.RELEASE`
 - Gradle: `3.0`

**Related:** 

- [#1446 - Without @ComponentScan - how?](https://github.com/springfox/springfox/issues/1446)
- [Issue on Stackoverflow](http://stackoverflow.com/questions/39159998/swagger2-document-a-springboot-mvcendpoint)

**Comment by dilipkrish** [comment]
The short answer is it is [totally possible](https://github.com/springfox/springfox/issues/1184). It is not supported out of the box, however.

Now about the question of detecting MvcEndpoints, it should automatically detect them. Its probably not seeing them because its loaded in a separate context, but @tokuhirom's example should help with that.

**Comment by dilipkrish** [comment]
Duplicate of  #1184

**Comment by nickgrealy** [comment]
Thanks @dilipkrish!
