### ISSUE TITLE
@ApiModelProperty(example = "") is not honored 

### ISSUE THREAD

**Issue by mrwanny** [springfox/springfox#1473]
I am wondering if there is a way to use empty strings as example in the api model

in swagger2:2.5 when I annotate my model with 
@ApiModelProperty(value = "Test empty example",
                      example = "")

```
test: {
type: "object",
properties: {
emptyExample: {
       type: "string",
description: "Test empty example"
      }
    }
}
```

this is a problem when you try to use the swagger-ui.html, 
because when an example is not provided it will default it to the type

```
{
  "emptyExample": "string",
}
```

is there any way to have it honor the empty strings

**Comment by dilipkrish** [comment]
Unfortunately since we're using annotations (from swagger-core) we don't control default values. We may need to write custom plugins to set the value. There might be opportunity to also recognize empty values as well. I'll investigate
