### ISSUE TITLE
Map<LocalDateTime, List<String>> not displayed correctly

### ISSUE THREAD

**Issue by jlaugesen** [springfox/springfox#1475]
Hi
Im using above map in my springboot application, but seem not to be able to make it work.
- api-docs shows object, $ref:#def/List, but def/List is not in json.
- swagger ui shows empty schema{}.

using ->  springfox-swagger2 - version 2.5.0

https://github.com/springfox/springfox/issues/1324 discusses the issue, but it does not seem resolved.

```
   @RequestMapping(path = "{id}/testit/", method = RequestMethod.GET, produces = {MediaType.APPLICATION_JSON_VALUE})
    public Map<LocalDateTime, List<String>> testit(@PathVariable("id") String id) {
        HashMap returnmap = new HashMap();
        returnmap.put(LocalDateTime.now(), new ArrayList<String>(Arrays.asList(new String())));
        return returnmap;
    }
```

v2/api-docs
```
{"200":
  {"description":"OK","schema":
    {"type":"object",
     "additionalProperties": { "$ref":"#/definitions/List"}
   }
 }
}
```

/swagger-ui.html
```
Response Class (Status 200) OK
Model  Model Schema
{}
```

**Comment by dilipkrish** [comment]
👍 thanks for reporting this bug!

**Comment by benfowler** [comment]
+1

**Comment by xiamubobby** [comment]
But still this thing comes up.

>     @RequestMapping(value = "data/manureProperties", method = RequestMethod.GET)
>     @ApiOperation(value = "获取用以大便信息的类别")
>     JsonResponseEntity<Map<String, List<EnumEntity>>> fetchManureProperties() {
>         List<EnumEntity> colors = shitColorRepository.findAll()
>         List<EnumEntity> shapes = shitShapeRepository.findAll()
>         return new JsonResponseEntity<Map<String,List<EnumEntity>>>(
>                 ret_values:  (colors + shapes).stream()
>                                 .collect(Collectors.<EnumEntity, String>groupingBy{ entity ->
>                     def className = entity.getClass().simpleName
>                     if (className.length() == 0) return "";
>                     return "" + Character.toLowerCase(className.charAt(0)) + className.subSequence(1, className.length());
>                 })
>         )
>     }



> trait EnumEntity {
>     @Transient @JsonIgnore static String enumName = "类别"
>     @Column(name = "name") String name
>     @Column(name = "description") String description
> }

**Comment by dilipkrish** [comment]
@xiamubobby what is do you see in the api-docs?
