### ISSUE TITLE
Invalid property structure for HATEOAS classes

### ISSUE THREAD

**Issue by Naid405** [springfox/springfox#1482]
I'm using spring-hateoas 0.20.0.RELEASE and springfox-swagger2 2.5.0.
HATEOAS resource classes (ResourceSupport, Resource, Resources and PagedResources) store the hyperlinks in a property named "links" and resource collection classes (Resources and PagedResources) store the collection in a property "content". The actual API calls utilise this naming strategy, but Swagger seems to be substituting these properties: "links" is replaced with "_links" and "content" is replaced with "_embedded". This is just not what API users expect from documentation.

**Actual API call:**
`{
  "links": [
    ...
    }
  ],
  "content": [
    {
      "links": [
       ...
      ],
      ...
    }
  ],
  "page": {
    "size": 1,
    "totalElements": 42,
    "totalPages": 42,
    "number": 0
  }
}`
**Swagger output:**
`{
  "_embedded": [
    {
      "_links": [
        {
          "href": "string",
          "rel": "string",
          "templated": true
        }
      ],
      ...
    }
  ],
  "_links": [
    {
      "href": "string",
      "rel": "string",
      "templated": true
    }
  ],
  "page": {
    "number": 0,
    "size": 0,
    "totalElements": 0,
    "totalPages": 0
  }
}`

**Comment by Naid405** [comment]
Apparently Swagger ignores actual content type specified on a controller methods (was "application/json" for me). Switched content type to hal+json and documentation and actual responses are more like each other, though not identical.
**API call:**
`{
  "_embedded": {
    "templates": [
      {
        "_links": {
          ...
        },
...
      }
    ]
  },
  "_links": {
    ...
  },
  "page": {
    "size": 1,
    "totalElements": 42,
    "totalPages": 42,
    "number": 0
  }
}`
**Swagger:**
`{
  "_embedded": [
    {
      "_links": [
        {
          "href": "string",
          "rel": "string",
          "templated": true
        }
      ],
...
    }
  ],
  "_links": [
    {
      "href": "string",
      "rel": "string",
      "templated": true
    }
  ],
  "page": {
    "number": 0,
    "size": 0,
    "totalElements": 0,
    "totalPages": 0
  }
}`

**Comment by dilipkrish** [comment]
This is by design. The rendering of the elements is controlled by the `Accept` header. when its `application/json` you'll see no underscores like `_link`. When you use `application/hal+json` it will generate it by default.

**Comment by Naid405** [comment]
Thank you for the response.
So if I perform GET /v2/docs with Accept: application/json I should get the pure JSON representation (link/content) and if I perform it with Accept: application/hal+json I should get the HAL representation (_links, _embedded). Is that correct?

If so, then how can I set up swagger-ui for it? If not, then how can I force the JSON representation (I understand that i should set up Jackson somhow, but I'm not sure how)?

**Comment by Naid405** [comment]
The main issue here, though, is the incorrect representation of HAL (_links as array instead of map and array of elements directly inside _embedded). but that is a known issue, am I correct?

**Comment by dilipkrish** [comment]
> Is that correct?

Yes that is correct.

You can fix it by manually setting the order of the message converters (hal+json gets first dibs based on what yr telling me).

**Comment by Naid405** [comment]
Tested today - "Accept" header is ignored by documentation endpoint. Even if you set "application/json", HAL representation is returned.

**Comment by Naid405** [comment]
Also "order of message convertes" won't change it, since apparently Spring HATEOAS is not adding a new converter, but rather registering an additional ObjectMapper with an existing converter.

**Comment by jihlee** [comment]
I think there is another problem around this example.

When you look at @Naid405 's second post

API call:
{ "_embedded": { "**templates**": [ { "_links": { ... }, ... } ] }, "_links": { ... }, "page": { "size": 1, "totalElements": 42, "totalPages": 42, "number": 0 } }

Swagger:
{ "_embedded": [ { "_links": [ { "href": "string", "rel": "string", "templated": true } ], ... } ], "_links": [ { "href": "string", "rel": "string", "templated": true } ], "page": { "number": 0, "size": 0, "totalElements": 0, "totalPages": 0 } }

Spring HATEOAS makes _embedded as object which has "templates" as a child, when Springfox generates it as an array.

I thought it would be similar to #1440 , but the workaround used to solve it couldn't be used here since ResourceMixin (which Jackson uses when mapping Resource to HAL) defines getContents() as generic Collection<?>.

**Comment by dilipkrish** [comment]
@jihlee you can fix that problem by adding an alternate type rule to turn collection -> list

**Comment by jihlee** [comment]
@dilipkrish Thanks for fast reply!

Although I add the alternate type rule ( collection -> list ), it generates somewhat like 

_embedded": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/(SomeResouce)"
          }

What I expected for SpringFox to generate was something like

_embedded": {
          "type": "object",
          "properties": {
                    "templates" : {
                              "type": "array"
                              "itmes": {
                                        "$ref": "#/definitions/(SomeReousrce)"
                             }
                    }
          }

Is there something that I missed?

**Comment by raffaelschmid** [comment]
I am facing the same issue (after introducing the alternate type mapping, i get the _embedded property mapped as array which in fact is an object). Is there any progress on that?

**Comment by dilipkrish** [comment]
@raffaelschmid/ @jihlee  I think this is a bug... Would you mind creating a new issue for it?

**Comment by socket70** [comment]
Was this ever resolved?

 I'm in the same boat, with a Spring Hateoas project and Springfox rendering things incorrectly. I've tried creating alternate type rules but haven't had any luck getting my _links and _embedded resources to render correctly.

**Comment by jeeftor** [comment]
I'm assuming not.  I thought Hateoas would be nice to implement - but I think i'm going to punt on it because I'd rather have clear docs than a nice API.

**Comment by dilipkrish** [comment]
Its not really fixed @socket70 & @jeeftor. I think at that time it was felt that the output for json is what it should reflect.. for e.g. requesting an application/json representation of the resource one would receive a response without the `_`. Why dont you create another issue for it.

**Comment by jeeftor** [comment]
Maybe i have something configure incorrectly, but if i query (wiht curl) with either "accept: application/json" or "accept: application/hal+json" i get the same response (which doesn't match the documentation).  Should that be happening?
