### ISSUE TITLE
Query Parameters with enableUrlTemplating set to true

### ISSUE THREAD

**Issue by safari137** [springfox/springfox#1484]
Fill details of my issue can be seen at : [http://stackoverflow.com/questions/39439214/swagger-param-documentation]

I have also read the closed issue at [https://github.com/springfox/springfox/issues/986]

My dilemma is that I need enableUrlTemplating set to true in order to have documentation on similar routes/maps that are only distinguished by certain query parameters (/students/{id}?age=20 and /students{id}?age=20&gender=male).  I also can't stand seeing the swagger ui showing url/students{id}{?age}?age=20 and it obviously doesn't work either.

Is there any work around for presenting this correctly in the UI?

**Comment by dilipkrish** [comment]
Are you using this dependency `io.springfox.ui:springfox-swagger-ui-rfc6570:0.9.7` for swagger-ui? Just released `0.9.7` but `0.9.6` should work too.

**Comment by safari137** [comment]
I thought I was, but apparently I'm not.  What repository should I use for that?  I'm using gradle.

**Comment by dilipkrish** [comment]
0.9.6 is available in both maven central and jcenter. However 0.9.7 is only available as of now on jcenter.

**Comment by safari137** [comment]
In any case I have 0.9.6 working, I just can't find a repo that has 0.9.7.  

However, now when I load localhost:8080/swagger-ui.html I see the navbar on the top with no data.  
"Failed to load resource: the server responded with a status of 404 () http;//localhost:8080/configuration/ui" is in the console.

**Comment by dilipkrish** [comment]
😫 I just remembered, 0.9.6 will not work, you'll need to use [0.9.7](https://bintray.com/springfox/maven-repo/springfox-swagger-ui). It takes a few hours to sync to maven central but if you include `jcenter()` as a repo in your gradle build you should find it.

**Comment by safari137** [comment]
Ahh okay.  It doesn't seem to be available on jcenter for me just yet.  0.9.6 seems to be the last version.

https://jcenter.bintray.com/io/springfox/springfox-swagger-ui-rfc6570/

**Comment by dilipkrish** [comment]
Yeah there seems to be a hiccup. Switched the artifacts group id from io.springfox to io.springfox.ui. Will update this thread when that is fixed

**Comment by dilipkrish** [comment]
Ok it should be [available now](https://jcenter.bintray.com/io/springfox/ui/springfox-swagger-ui-rfc6570/0.9.7/)

**Comment by safari137** [comment]
That works great!  Thank you very much.

**Comment by thomaszbz** [comment]
@dilipkrish I have the same issue with springfox versions 2.7.0 and 2.8.0: With `enableUrlTemplating(true)`, swagger ui does not replace the template and therefore receives 404 errors only.

Me too, my maven can only resolve 0.9.6 but not 0.9.7. Could you please publish 0.9.7 in common repos? It should be made available here:

https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui-rfc6570

**Comment by thomaszbz** [comment]
@dilipkrish It changed location and I found 0.9.7 and 1.0.0 here:

https://mvnrepository.com/artifact/io.springfox.ui/springfox-swagger-ui-rfc6570

**Comment by thomaszbz** [comment]
With springfox version 2.7.0 and springfox-swagger-ui-rfc6570 version 1.0.0, it seems to work and swagger ui produces GET requests like:
`https://example.com/api&user_id=1`

But with springfox version 2.8.0 and springfox-swagger-ui-rfc6570 version 1.0.0, the RFC6570 handling is broken again:
`https://example.com/api%7B?user_id%7D=&user_id=1`

**Comment by dilipkrish** [comment]
@thomaszbz you can use it with the latest springfox versions I believe 2.6+ atleast.

**Comment by sivashanthini** [comment]
@dilipkrish I am using springfox and swagger-ui of version 2.9.2. I needed the support of RFC6570 in the swagger-ui version 2.9.2. It would be great if RFC6570 support can be provided in swagger-ui 2.9.2 version also rather than in swagger-ui-rfc6570 1.0.0.

**Comment by membersound** [comment]
Is `enableUrlTemplates` still experimental, or could it be merged into master?
