### ISSUE TITLE
Programmatically Enable Swagger2

### ISSUE THREAD

**Issue by qfrank** [springfox/springfox#1489]
I know using @EnableSwagger2 is a way to enable Swagger2,enable swagger2 in development environment is good for our developer, but i need disable swagger2 in production environment because i don't want expose api doc in public...Any way e.g. programmatically other than annotation?

**Comment by qfrank** [comment]
Oh,i haven't seen this! I've tried google before..maybe my keywords are wrong..It solved my problem,thanks!

**Comment by dilipkrish** [comment]
Woohoo!
