### ISSUE TITLE
Infer alternate type rules using serializers and deserializers

### ISSUE THREAD

**Issue by justcoon** [springfox/springfox#1490]
if in request body is used interface, only with getters, with custom serialization and deserialization

```
@Value.Immutable 
@JsonSerialize(as =  ImmutableCreateRoleCommand.class)
@JsonDeserialize(as = ImmutableCreateRoleCommand.class)
public interface CreateRoleCommand  {
 String getAggregateId();
 String getName();
}

@RestController
public class RoleController {

    @ApiOperation(httpMethod = "POST", value = "create role", response = RoleAggregate.class)
    @RequestMapping(path =  "/role/create", method = RequestMethod.POST)
    RoleAggregate createRole(@RequestBody CreateRoleCommand command) {
       ...
    }
}

```

model is not detected correctly

![swagger_requestbody_model_problem](https://cloud.githubusercontent.com/assets/5932736/18551153/9054c2fc-7b57-11e6-9af3-73f72bdfdb9b.png)

problem is probably in implementation of

```
springfox.documentation.schema.property.OptimizedModelPropertiesProvider

method: BeanDescription beanDescription(ResolvedType type, ModelContext context)
```

**Comment by dilipkrish** [comment]
Create an alternate type rule to map `CreateRoleCommand.class` to `ImmutableCreateRoleCommand.class`. Springfox cannot infer serializers, may be it should but as of now its not supported. So you need to assist it by telling it what your object looks like.

**Comment by kinbiko** [comment]
As a followup to this feature request, could someone take a look at [this link](http://stackoverflow.com/questions/41675459/springfox-swagger-generation-creates-odd-schema) and let me know if it's the same problem? I'm finding it a bit hard to read from context. If so, could you also elaborate on `Create an alternate type rule to map A to B` in the previous comment? I'm struggling to find documentation on how to do this.
Thank you.

**Comment by dilipkrish** [comment]
@kinbiko answered in SO.
