### ISSUE TITLE
Swagger UI displays Java Character as {} and char as "string" datatype

### ISSUE THREAD

**Issue by neildcruz19** [springfox/springfox#1491]
Swagger UI version : 2.5.0

I have a field in my Spring API which is defined as a Java wrapper Character type. But in the Swagger UI the definition is considered as an empty object {} or if I change the type to a primitive char the UI model property shows "string" as an example.

As a requirement, I need to keep the property as a wrapper Character type. I'm not able to figure out a good way to document it in Swagger UI.

Here is the swagger definition:

activeIndicator: {
    $ref: "#/definitions/Character"
},
I have tried:
@ApiModelProperty(dataType = "char")

But, this does not work either. Any pointers or a better way to do this?

**Comment by dilipkrish** [comment]
`char` is not a valid dat type. Open api spec does not support a single character it is treated as a string. As for the solution, add an alternate type rule that substitutes `CharacterWrapper.class` with `String.class` in your docket
