### ISSUE TITLE
Swagger fails when Map/JsonObject used as Model

### ISSUE THREAD

**Issue by srinikandula** [springfox/springfox#1493]
Swagger UI version : 2.5.0
springfox version : 2.5.0

When my API is returning List<org.json.simple.JSONObject> swagger fails to build the documentation. I found the offensive code in file '**springfox.documentation.swagger2.mappers.ModelMapper.java**' line:129. For JSONObject the TypeParameters would be empty. The mentioned line will fail with '`java.lang.IndexOutOfBoundsException`'

The method in the above mentioned class can we changed like below 

```
@VisibleForTesting
  Optional<Class> typeOfValue(springfox.documentation.schema.Model source) {
    Optional<ResolvedType> mapInterface = findMapInterface(source.getType());
    if (mapInterface.isPresent()) {
      if (mapInterface.get().getTypeParameters().isEmpty()) {
        return Optional.absent();
      } else {
        return Optional.of((Class) mapInterface.get().getTypeParameters().get(1).getErasedType());
      }
    }
    return Optional.absent();
  }
```

**Comment by dilipkrish** [comment]
This has been fixed via #1062

**Comment by srinikandula** [comment]
@dilipkrish I'm sorry there has been a typo in my original description on this issue. When my API returns List<JsonObject> it fails with the mentioned error. Let me know if you prefer to check via a sample git project to demonstrate this.

**Comment by dilipkrish** [comment]
@srinikandula Try [this suggestion](https://github.com/springfox/springfox/issues/1288#issuecomment-215982890) to specify an alternate type rule for JsonNode related return types or parameters.
