### ISSUE TITLE
Define a reason for applying @ApiIgnore

### ISSUE THREAD

**Issue by gdrouet** [springfox/springfox#1494]
When you annotate a service `@ApiIgnore`, there is always a good reason for this and you might want to explain it in your code for the developers that will come after you. This can be done currently with a comment, but it would be even better you have `reason` attribute in the annotation to have something like that:

    @ApiIgnore(reason = "A very good reason why ignore this API.")

**Comment by dilipkrish** [comment]
Thanks for the suggestion!
