### ISSUE TITLE
Can not get Swagger-ui to work in Spring application

### ISSUE THREAD

**Issue by jsvachon2** [springfox/springfox#1499]
Hi,

I am trying to integrate swagger-ui into our Spring based application (4.3.2) by following this guide (http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api). 

The page /services.app/v2/api-docs.json works fine. I can see all my services and their complete definitions but when I try to go to /services.app/swagger-ui.html I am receiving an error like the following:

Can't read swagger JSON from http://localhost:8080/services.appundefined

the dropdown list contains four entries all labeled the same: undefined (undefined)

I opened the dev tool in Chrome and reloaded the page and I am receiving a 404 for the following path: /services.appundefined

My maven project has dependencies over  springfox-swagger2 and springfox-ui.

I am pretty sure this is only a configuration issue on my end but I could not find any information about this error message

Any thoughts?

Here is a screenshot showing the current state:

![screen shot 2016-09-28 at 10 29 47 am](https://cloud.githubusercontent.com/assets/15382846/18917737/9d7214c6-8566-11e6-8fca-4b6eeb837ef9.png)

**Comment by dilipkrish** [comment]
@jsvachon2 What version of swagger-ui do you have?

**Comment by dilipkrish** [comment]
I'd recommend moving to version 2.5.0 on both those dependencies

**Comment by jsvachon2** [comment]
Here is my pom.xml

	<dependency> 
		  <groupId>io.springfox</groupId> 
		  <artifactId>springfox-swagger2</artifactId> 
		  <version>2.5.0</version> 
		</dependency> 

        <dependency> 
          <groupId>io.springfox</groupId> 
          <artifactId>springfox-swagger-ui</artifactId> 
          <version>2.5.0</version> 
        </dependency> 

I tried downgrading to 2.4.0 but got the same problem

Thanks for your fast response

**Comment by dilipkrish** [comment]
One thing to also try is to clear your cache after upgrading to 2.5.0. The reason yr getting this error is because the path changed (to get the swagger-ui configuration) between 2.4.0 and 2.5.0

**Comment by jsvachon2** [comment]
Hi,

I tried flushing my browser's cache and I still have the same issue. I also tried on Safari (I never use it) and got the same error message.

Any other things I can check?

**Comment by jsvachon2** [comment]
Some additional informations.. here is a part of my Spring configuration...  (I removed the real name of classes and packages for security concerns from a few people in our organization)

Please let me know if you need anything else...

===========
 <bean class="com.ceb.tn.services.SwaggerConfiguration"/>

    <mvc:resources mapping="swagger-ui.html"   
            location="classpath:/META-INF/resources/" />
    <mvc:resources mapping="/webjars/**"
           location="classpath:/META-INF/resources/webjars/" />
    <context:component-scan base-package="some.package" />

Here is the main section of the SwaggerConfiguration class...

@Configuration
@EnableSwagger2
public class SwaggerConfiguration {
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any()).build();
       }
}

**Comment by dilipkrish** [comment]
Ok first off I think its not correctly configured. swagger-ui needs to be at the root of your web context. I think that may be the source of your issues.

For e.g. you need to check if you can access this endpoint correctly

`http://localhost:8080/services.app/swagger-resources/configuration/security` and see that you get json back. If not its not configured correctly.

**Comment by dilipkrish** [comment]
IOW the algorithm we use to determine the meta-endpoints are

- take the url of swagger-ui.html `http://localhost:8080/services.app/swagger-ui.html`
- strip`swagger-ui...`
- replace with `swagger-resources/...`

So you need to make sure that can happen.

**Comment by jsvachon2** [comment]
Hi again,

Here is the output of http://localhost:8080/services.app/swagger-resources/configuration/security 

{
  "isError": false,
  "message": "SUCCESS",
  "statusCode": 200,
  "data": {
    "apiKeyVehicle": "header",
    "scopeSeparator": ",",
    "apiKeyName": "api_key"
  }
}

**Comment by jsvachon2** [comment]
And the output of http://localhost:8080/services.app/swagger-resources/configuration/ui

{
  "isError": false,
  "message": "SUCCESS",
  "statusCode": 200,
  "data": {
    "validatorUrl": null,
    "docExpansion": "none",
    "apisSorter": "alpha",
    "defaultModelRendering": "schema",
    "supportedSubmitMethods": [
      "get",
      "post",
      "put",
      "delete",  
      "patch"
    ],
    "jsonEditor": false,
    "showRequestHeaders": true
  }
}

**Comment by dilipkrish** [comment]
Ok looks like everything setup correctly. Can you share the stack trace in your javascript console... it only shows `springfox.js line:64`. Im interested in whats the offending line...

**Comment by jsvachon2** [comment]
Here are two screenshots... one is showing the Javascript console and the other showing the state when I put a breakpoint in the code to see the state of the different variables... hope that helps... let me know if you need more information

![screen shot 2016-09-29 at 3 41 25 pm](https://cloud.githubusercontent.com/assets/15382846/18969492/6c86508e-865b-11e6-8109-e71043b1e319.png)

![screen shot 2016-09-29 at 3 42 08 pm](https://cloud.githubusercontent.com/assets/15382846/18969491/6c841468-865b-11e6-80b8-5369fdfd719b.png)

**Comment by dilipkrish** [comment]
Hmm  not sure, in any case would be great if you try it out with `2.6.0` releasing shortly

**Comment by jsvachon2** [comment]
Hi,

just to let you know what the problem was... as expected it was something on our end... :(

it turns out that we had a class extending a ResponseEntityExceptionHandler and implementing a ResponseBodyAdvice<Object> in our project. This class was wrapping up any response served into a fixed format but that was not compatible with Springfox. I modified the @ControllerAdvice annotation to limit the scope of the class and TADA! it is working

Thanks for your help

**Comment by niculistana** [comment]
@jsvachon2 What did you limit the scope to?

**Comment by nachomezzadra** [comment]
If it helps to someone else, in my case, i had the exact same issue using spring boot v1.5.9.RELEASE, and didn't work using springfox-swagger-ui v2.7.0, neither 2.6.x.  Downgrading to 2.5.0 did the trick.

**Comment by dilipkrish** [comment]
@nachomezzadra thats weird. Since its just a regular web jar, wondering what the difference might be.
