### ISSUE TITLE
Security definition spec missing tokenName property for Spring Boot + OAuth2 security scheme

### ISSUE THREAD

**Issue by hnluu** [springfox/springfox#1500]
I've got a Spring Boot project that implements OAuth2-protected APIs.

My project is using the 2.5.0 versions of springfox-swagger2 and springfox-swagger-ui.

I can authorize successfully with my OAuth2 provider from the Swagger UI. I'm using Auth0 which returns both an access_token and an id_token, and it is the id_token that I need Swagger to pass in the Authorization header.

But every time upon redirect to o2c.html, it is the access_token that Swagger retrieves from the redirection response. I can see from line 133 of swagger-oauth.js that this behavior can be overridden with the tokenName property of the SecurityDefinition object.

Here's the block of code that I'm referring to in swagger-oauth.js:
```javascript
if(authSchemes[key].type === 'oauth2' && flow && (flow === 'implicit' || flow === 'accessCode')) {
          var dets = authSchemes[key];
          url = dets.authorizationUrl + '?response_type=' + (flow === 'implicit' ? 'token' : 'code');
          window.swaggerUi.tokenName = dets.tokenName || 'access_token';
          window.swaggerUi.tokenUrl = (flow === 'accessCode' ? dets.tokenUrl : null);
          state = key;
}
``` 

My question is: how do I specify this tokenName in the SwaggerConfig of my Spring Boot project?

I was under the impression that the tokenName is taken from the second argument of the ImplicitGrant object. Here's how I've configured my OAuth2 security scheme in the SwaggerConfig:
```java
private OAuth securityScheme() {
        String auth0Endpoint = issuer + "authorize";
        AuthorizationScope authorizationScope = new AuthorizationScope(AUTHORIZATION_SCOPE, AUTHORIZATION_SCOPE_DESC);
        LoginEndpoint loginEndpoint = new LoginEndpoint(auth0Endpoint);
        GrantType grantType = new ImplicitGrant(loginEndpoint, "id_token");
        return new OAuth(SECURITY_DEFINITION_NAME, Collections.singletonList(authorizationScope),
                Collections.singletonList(grantType));
    }
```

When I check the Security Definition part of my Swagger spec, I see everything but the tokenName:
```json
	"securityDefinitions": {
		"jwt": {
			"type": "oauth2",
			"authorizationUrl": "auth0-authorization-url",
			"flow": "implicit",
			"scopes": {
				"openid": "jwt"
			}
		}
	}
```

Appreciate any insights into this issue. Thanks!

**Comment by dilipkrish** [comment]
Sounds like this is an issue that we may need to join forces to solve. Im not familiar with the internals of swagger-ui and how much/little it supports oauth. Also I don't know too much about the situation you're describing. It is very likely we haven't pushed the boundaries of swagger-ui oauth support.

**Comment by hnluu** [comment]
Looks like the the class io.swagger.models.auth.OAuth2Definition doesn't define a tokenName member:
```java
public class OAuth2Definition extends AbstractSecuritySchemeDefinition {
    private String type = "oauth2";
    private String authorizationUrl;
    private String tokenUrl;
    private String flow;
    private Map<String, String> scopes;

    ...
}
```
That explains why the tokenName doesn't appear in the securityDefinitions of the Swagger spec.

Looks like the tokenName was removed for the OAuth2 spec starting with Swagger 2.0: https://github.com/OAI/OpenAPI-Specification/issues/37

Bummer! This flexibility would have helped with Auth0 JWT protected APIs.

**Comment by dilipkrish** [comment]
😿
