### ISSUE TITLE
Add version controler

### ISSUE THREAD

**Issue by blackshadowwalker** [springfox/springfox#1501]
1. Hope support 'version controler' feature, every api json data get a verison if md5 not change. save the it(json data, version, createTime) to file or db.

In swagger-ui.html, we can switch to some version.
1. hightlight the latest change like git 

![image](https://cloud.githubusercontent.com/assets/5380980/18938695/1a9bec26-862d-11e6-8538-72ff89f0ea99.png)

**Comment by dilipkrish** [comment]
Not exactly sure what you're asking. Could you elaborate?

**Comment by blackshadowwalker** [comment]
Add Version Controller for all rest uri, with that We can quikly know which rest uri changed  an which parameters changed clearly. 

Hope the reset api data can persistent to disk or git.

**Comment by blackshadowwalker** [comment]
May by the db use Noms.

**Comment by dilipkrish** [comment]
Sounds like a great idea, but I don't think its in scope for this library
