### ISSUE TITLE
Response Message schemas for lists, maps, and sets in springfox-swagger-ui

### ISSUE THREAD

**Issue by hogancr** [springfox/springfox#1502]
Hi,

I'm using version 2.5 of springfox-swagger2 and springfox-swagger-ui, and I've got controller methods annotated to use '@ApiResponse' to define some of the response values for my endpoints. One returns a list of  QuizDTO objects (converted to JSON).

```java
@ApiResponses( value = { 
      @ApiResponse(code = 400, message = "Details of error accessing the API", response = ApiErrorDTO.class),
      @ApiResponse(code = 201, message = "Quizzes successfully added to the database", response = QuizDTO.class, responseContainer = "List")
 })
  @RequestMapping(method = PUT, path = "quizzes", produces = APPLICATION_JSON_VALUE)
  public ResponseEntity<?> setQuizzes(@RequestBody List<QuizDTO> quizzes) {
...
```

First is a question, the top of the SwaggerUI API definition shows response schema for 200 (OK) by default. Is there a way to change this so that it will show the schema for 201 (or something else) instead?

Second is a problem. While that top section shows the schema correctly when 200 (OK) is defined this way with responseContainer set to "list" and response set to "QuizDTO.class", if I change that to 201 as in the code snippet above, it appears at the bottom of the SwaggerUI API documentation instead, with all of the other "non-OK" responses, and the schema doesn't show up at all, that box of the table is just blank. 

I looked at the swagger api-docs.json and in either case they are defined the same, it's just the display in the bottom doesn't process it correctly while the one at the top does. Note that the annotations work fine for simple responses that don't have a container, even in the lower section of the SwaggerUI page. So this means you can't really return a list of anything with a non-OK return code and have it show up correctly in the SwaggerUI doc page. 

Swagger api-docs.json output

```javascript
  "responses" : { 
      "200" : {
          "description" : "OK",
          "schema" : {
              "type" : "array",
              "items" : {
                  "$ref" : "#/definitions/QuizDTO"
              }
          }
      },
      "201" : {
          "description" : "Quizzes successfully added to the database",
          "schema" : {
              "type" : "array",
              "items" : {
                  "$ref" : "#/definitions/QuizDTO"
              }
          }
      } ,
      "400" : { ... }
}
```

In case it matters here is my swagger config:
```java
@Configuration
@EnableSwagger2
public class SwaggerConfig {
  @Bean
  public Docket api() {
    final List<ResponseMessage> responseMessageList = new ArrayList<ResponseMessage>();
    responseMessageList
        .add(new ResponseMessageBuilder().code(500).message("500 message").responseModel(new ModelRef("Error")).build());
    responseMessageList.add(new ResponseMessageBuilder().code(403).message("Forbidden!!!!!").build());

    return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.basePackage("our base package"))
        .paths(PathSelectors.any()).build().apiInfo(apiInfo()).useDefaultResponseMessages(false)
        .globalResponseMessage(RequestMethod.GET, responseMessageList);
  }

  private ApiInfo apiInfo() {
    final Contact contact = new Contact("Chris Hogan", "our web address", "my email");
    final ApiInfo apiInfo = new ApiInfo("My REST API", "Some custom description of API.", "API TOS", "Terms of service", contact,
        "License of API", "API license URL");
    return apiInfo;
  }
}
```

**Comment by dilipkrish** [comment]
> First is a question, the top of the SwaggerUI API definition shows response schema for 200 (OK) by default. Is there a way to change this so that it will show the schema for 201 (or something else) instead?

Annotate your operation with `@ResponseStatus(HttpStatus.CREATED)`

> While that top section shows the schema correctly when 200 (OK)

Top section where? swagger-ui? Could you perhaps share a screenshot?

**Comment by hogancr** [comment]
I'm talking about the swagger-ui page.notice that the model schema looks fine at the top where status is 200, but when the same schema is displayed at the bottom of the section in that table (in the 201 row), it's just blank.

![image](https://cloud.githubusercontent.com/assets/20046777/18966489/585efb58-864f-11e6-8a1f-06e937720dbc.png)

**Comment by FinleySmile** [comment]
![image](https://user-images.githubusercontent.com/12446331/31760761-5ec8dbfc-b47b-11e7-92e5-4cf34705f3e6.png)
Is thera a way to describe the field of response ?
for example,above the reponse is person list,I want to descripe id,name for detail.Just similar to describe request parameter
thx

**Comment by jawpio** [comment]
@FinleySmile yes you can on the model add `@ApiModelProperty` annotations. The results are visible in the "Model" link (not in Example Value).
cheers
