### ISSUE TITLE
How to properly annotate and present a Map type request body? 

### ISSUE THREAD

**Issue by Jeckyli** [springfox/springfox#1503]
I'm using `springfox-swagger2` 2.2.2 with Spring Boot.

One of my REST APIs takes a `Map<String, Object>` object in request body, like this,

```java
@ApiOperation(
		value = "Submit user data")
@RequestMapping(
		value = "/userData",
		method = RequestMethod.POST,
		consumes = {MediaType.APPLICATION_JSON_VALUE},
		produces = "application/json")
public ResponseEntity<?> submitUserData(
		@RequestBody
		@ApiParam(
			value = "JSON format input, keys allowed are key1, key2, key3."
		) Map<String, Object> userInput
```
I want to present the users a sample or the `userInput`, by default it only shows `Model Schema` as `{}` , I'd like to see something like,

```json
{
	"key1":"sample value1",
	"key2":"sample value2",
}
```

The generated Swagger JSON is as follows,

```json
{
  "in": "body",
  "name": "userInput",
  "description": "JSON format input, keys allowed are key1, key2, key3.",
  "required": false,
  "schema": {
    "type": "object"
  }
}
```

So here are my main questions based on my understanding,

1. Looks like if I can manage to add `additionalProperties` into the generated JSON, I should be able to get what I want, a key list for the users to follow. But I'm really not sure how to achieve this with annotations.

2. Seems there is another key called `example` that can gets me what I want, but not sure how can I use it with Springfox-Swagger. 

I think the bottom line is I'm using a Map for request body type instead of having a dedicated class for it, thus I cannot utilize `@ApiModel` and `@ApiModelProperties` to customize the documents. Or can I?

**Comment by dilipkrish** [comment]
@Jeckyli The short answer for you is that you'd need to write your own `ParameterBuilderPlugin` plugin. 

A quick way that I can think of is to create an annotation `@AlternateType(MyTypeWithKey1AndKey2.class)` at the parameter level.  Where `MyTypeWithKey1AndKey2` is a type that has `key1` and `key2` bean properties.

**Comment by Jeckyli** [comment]
@dilipkrish Thanks for the response. But seems to me this is different from what I understand.

The fundamental issue in my case is that I don't have a class `MyTypeWithKey1AndKey2.class`, but rather used a generic `Map<String, Object>` that I'll use to retrieve `key1` and `key2`. Otherwise I would put `MyTypeWithKey1AndKey2` directly as the request body type and Swagger will display the schema directly right?

**Comment by dilipkrish** [comment]
> Otherwise I would simply put MyTypeWithKey1AndKey2 as the request body type and Swagger will display the model schema directly right?

@Jeckyli that is right. Unless of course you don't control the contract.

There is no way for springfox to figure out the contents (and keys) in your `Map`. Its a run-time construct. And at the moment the easiest way to do it is to supply a mixin. You could write your own variant of the plugin, and provide a more open ended way to do it without defining new types... perhaps something like `@AlternateTypeProperties(properties={"key1", "key2"})` and be able to generate Models and properties from it, but I think its a little harder to do. Might be a good enhancement to add arbitrary types.

**Comment by Jeckyli** [comment]
OK, I see. Guess I'll have to write a dummy class for this Map. Thanks.

**Comment by Trii** [comment]
@Jeckyli did you end up coming up with a solution for this?

**Comment by Jeckyli** [comment]
@Trii Unfortunately no. Open to suggestions.

**Comment by Trii** [comment]
This is the exact use-case I am trying to solve for: http://stackoverflow.com/questions/41861164/how-can-i-manually-describe-an-example-input-for-a-java-requestbody-mapstring

```java
@RequestMapping(value = "/start", method = RequestMethod.POST)
public void startProcess(
    @ApiParam(examples = @Example(value = {
        @ExampleProperty(
            mediaType="application/json",
            value = "{\"userId\":\"1234\",\"userName\":\"JoshJ\"}"
        )
    }))
    @RequestBody(required = false) Map<String, String> fields) {
    // .. does stuff
}
```
I couldn't care less what the user send in, my api is just storing user defined data. What I do care about is being able to document it in swagger ui with some sort of example data, but `@ExampleProperty` doesn't seem to work as I understood it from the docs.

**Comment by Jeckyli** [comment]
@Trii Yup, we are in the same bucket. Will keep an eye on your question.

**Comment by jsandesha** [comment]
I am also facing the same issue. And also what to do if your response is a Map<String,Object> ?

**Comment by forever-programmer** [comment]
So, as of now, whats the suggested approach to document a Map<String, Object>?

**Comment by dilipkrish** [comment]
There is nothing to do if the type is `Map<String, Object>`. That is basically an open contract equivalent to an json *any* type.

**Comment by pteki345** [comment]
Have added, 
 @ApiModelProperty(value = "My Variables", reference = "Map")
    private Map<String, Object> variables;
It works.

**Comment by creid31** [comment]
@pteki345 I tried this approach and swagger complains. Is there a missing step in order to get your suggestion to work?

Resolver error at paths./orders/{id}.patch.parameters.2.schema.properties.map.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/Map does not exist in document

**Comment by dilipkrish** [comment]
@Jeckyli the proper way to annotate a Map type is to not annotate. Springfox will figure out your generic types

**Comment by jtktam** [comment]
hi if i have a controller that returns a Map<String, ArrayMap> what annotation should i use to get the map to display correctly? thanks

**Comment by dilipkrish** [comment]
What are you expecting the display to look like. Its a Map of Maps.

**Comment by zhangfei9734** [comment]
@dilipkrish, Hi, Having a specific type of map does not work either
e.g. LinkedHashMap<String, User> userMap in requestBody

**Comment by dilipkrish** [comment]
That should totally work @zhangfei9734. What are u seeing. Would you mind creating a new issue with specific details like version, steps to reproduce etc.

**Comment by zhangfei9734** [comment]
[#2188](#2188)

**Comment by johanvogelzang** [comment]
I have the same issue with List<Map<String, Object>>

Resolver error at paths./api/overzicht/bevindingen.get.responses.200.schema.items.$ref
**Could not resolve reference because of: Could not resolve pointer: /definitions/Map«string,object» does not exist in document**

We're using SpringFox version 2.8.0

**Comment by jeeftor** [comment]
I've got the same issue with  **Set**

>Resolver error at definitions.AdvertisementSubscriptions.additionalProperties.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/Set does not exist in document

**Comment by dilipkrish** [comment]
@johanvogelzang & @jeeftor I believe its fixed via #2231. Would be great to get your feedback using 2.8.1-SNAPSHOT. If it doesnt work please create a new issue

**Comment by apoorvatarento** [comment]
Hi Guys,
I have an API which takes accepts the input from request body in form of a string, which is a JSON. Can anyone let me now how to create a input in swagger for this.

**Comment by dilipkrish** [comment]
@apoorvatarento [like this](http://springfox.github.io/springfox/docs/snapshot/#q27)

**Comment by apoorvatarento** [comment]
when i tried, when i check on swagger ui, i am not getting any expansion for that particular  controller

**Comment by Shashika** [comment]
@dilipkrish `@RequestParam Map<String, String> params` any luck to describe a map?

**Comment by apoorvatarento** [comment]
i am using spring mvc project and the datatype is not being indentified, but it dosent shoe an error it just take the data type as string.

**Comment by dilipkrish** [comment]
@Shashika Map<String, String> should just work. I dont believe swagger ui supports it. 

@apoorvatarento What does the snippet of the swagger specification that is generated look like?

**Comment by peerit12** [comment]
in controller param is of type ArrayList<Map<String, Object>> so error comes in swagger-ui 
Resolver error at paths./forms.post.parameters.0.schema.items.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/Map«string,object» does not exist in document

Any solution to this???

**Comment by dilipkrish** [comment]
Dont know. Why dont u create a new issue for this @peerit12 ?

**Comment by dilipkrish** [comment]
@leapingbytes thats because it is an object, there[ is a rule](https://github.com/springfox/springfox/blob/ac4c54ea7b2d9aa5816b1bff43de1e757cd66791/springfox-spi/src/main/java/springfox/documentation/spi/service/contexts/Defaults.java#L102-L106) that maps certain Map data types to an Object

**Comment by lubinson** [comment]
@dilipkrish 

I have the same issue of @zhengl7.  I use swagger codegen to generate java api from OpenAPI spec. Like below:

```
    @ApiOperation(value = "Create a Account", nickname = "createAccount", notes = "Create a account", response = AccountResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = AccountResponse.class),
        @ApiResponse(code = 400, message = "Bad request", response = AccountError.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = AccountError.class),
        @ApiResponse(code = 200, message = "Generic Error") })
    
    @RequestMapping(value = "/account",
        produces = { "application/json", "application/problem+json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<AccountResponse> accountCreate(@ApiParam(value = "" ,required=true )  @Valid @RequestBody AccountRequest body);
 ```

But we need to deep control the json serialization/deserialization, so we change the request and response type to Map, it works for our purpose.  Like below:
```
    @ApiOperation(value = "Create a Account", nickname = "createAccount", notes = "Create a account", response = AccountResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = AccountResponse.class),
        @ApiResponse(code = 400, message = "Bad request", response = AccountError.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = AccountError.class),
        @ApiResponse(code = 200, message = "Generic Error") })
    
    @RequestMapping(value = "/account",
        produces = { "application/json", "application/problem+json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Map> accountCreate(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Map body);    

```

But we still need the swaggerUI to generate the request and response json sample from models, e.g. AccountRequest and AccountResponse. We found even we change the response to Map, the response sample can still be displayed in swagger UI. I think it is because `response = AccountResponse.class` in 
annotation `ApiOperation` shows below:
```
    @ApiOperation(value = "Create a Account", nickname = "createAccount", notes = "Create a account", response = AccountResponse.class, tags={  })
```
I was thinking if Swagger can generate doc from ApiOperation which includes both request and response class and optionally ignore `RequestBody`.  But unfortunatelly the request class (AccountRequest.class) can not be added into  `ApiOperation`.

Thanks.

**Comment by lubinson** [comment]
@dilipkrish 

Thanks for your reply. Should I send message here or in the new issue page?

For my understanding, the Swagger UI uses the `response = AccountResponse.class` in the  annotation `ApiOperation` to generate the response sample. Its what we want if the request sample can do the same thing. 

Thanks.

**Comment by donghuawei** [comment]
@lubinson    I am also facing the same issue,  did you get the solution to generate  json sample for Map ?

**Comment by mallikarjunpunna** [comment]
here am in 2022 sill facing the issue

**Comment by ssuhana1** [comment]
I am also facing same issue.any solution for this?

**Comment by hqhangyu** [comment]
has this problem been resolved?

**Comment by alexlitovsky** [comment]
2024 and there is still no sensible way to describe a Map<A, B> via annotations. Please add 1st class support for Maps.

**Comment by riarurainey** [comment]
As of 2025, I’ve encountered this issue and couldn’t find any proper fix.
