### ISSUE TITLE
"infinity" in allowableValues property of @ApiModelProperty annotation

### ISSUE THREAD

**Issue by SomeoneToIgnore** [springfox/springfox#1504]
Hello.

I've faced some problem with `allowableValues` property recently: if I annotate some numeric field with something like `@ApiModelProperty(value = "Just a number", allowableValues = "range[1,infinity]")` (note the infinity in range here), I receive an exception when I open the Swagger UI.

I've created small project to demonstrate the problem with latest library version, here's the repo: [https://github.com/SomeoneToIgnore/swagger-infinity-bug-example](https://github.com/SomeoneToIgnore/swagger-infinity-bug-example)
The stacktrace for that example can be found in the project: [https://github.com/SomeoneToIgnore/swagger-infinity-bug-example/blob/master/stacktrace.txt](https://github.com/SomeoneToIgnore/swagger-infinity-bug-example/blob/master/stacktrace.txt)

Although I'm a little confused with the fix approach: I've browsed through the `AbstractNumericProperty` and its superclasses and had not found any suitable class that can hold a String value.
Don't you think that holding range values as String types would be preferable?

Best regards,
Kirill.

P.S. One more tiny question: class `MinMaxAnnotationPlugin` uses `Double.MIN_VALUE` as a value to represent negative infinity, as I guess. This is not correct, because `Double.MIN_VALUE` is, actually, the closest value to zero possible. I presume, `-Double.MAX_VALUE` should be used instead :)

**Comment by dilipkrish** [comment]
@SomeoneToIgnore thanks for reporting this! I think it may be a shortcoming in the object model in swagger-core. Not sure [how swagger-ui handles null values](https://github.com/iushankin/swagger-core/commit/8fb4b63d37dbf1fd0684dfdf711933eba3ce98f2).

**Comment by SomeoneToIgnore** [comment]
@dilipkrish thank you so much for the fix!
Yes, definitely, swagger-core should have objects for these kinds of values.
