### ISSUE TITLE
Broken basePath with AbstractPathProvider in version 2.5.0 of springfox-swagger2

### ISSUE THREAD

**Issue by danielbcorreia** [springfox/springfox#1507]
- Version 2.5.0 (same in 2.6.0)
- Bug: AbstractPathProvider extension point is broken for swagger2 due to this code block in Swagger2Controller:

``` java
    Swagger swagger = mapper.mapDocumentation(documentation);
    if (isNullOrEmpty(swagger.getHost())) {
      final UriComponents uriComponents = componentsFrom(servletRequest);
      swagger.basePath(Strings.isNullOrEmpty(uriComponents.getPath()) ? "/" : uriComponents.getPath());
      swagger.host(hostName(uriComponents));
    }
```

Here you can see that even if the new path is getting to the Swagger object (line 1), it gets overwritten when "getHost" is checked. According to the swagger spec the host isn't even required, so this kind of assumptions should not be made.

On the other hand, the basePath is overwritten when a host is not provided which is the main reason for this bug.

The last version that we know that works is 2.3.1.

Sample implementation of AbstractPathProvider:

``` java
    class BasePathAwareRelativePathProvider extends AbstractPathProvider {
        private String basePath;

        public BasePathAwareRelativePathProvider(String basePath) {
            this.basePath = basePath;
        }

        @Override
        protected String applicationPath() {
            return basePath;
        }
        ...
    }
```

**Comment by danielbcorreia** [comment]
This is the commit that breaks this:

https://github.com/springfox/springfox/commit/a1ceac24e7cd0c646a6217391baa9d8a44fdb324

**Comment by dilipkrish** [comment]
@danielbcorreia this was introduced to allow the application to work correctly in a load balanced environment. Not sure what is breaking here, the fact that the host name isn't what was supplied or that the host name is incorrect?

**Comment by danielbcorreia** [comment]
Specifying the hostname is optional. It's fine to assume the hostname from the current servlet context as it was done before, even though that field is optional in the swagger spec, but overwriting the basePath when the hostname is not supplied creates a lot of issues.

**Comment by dilipkrish** [comment]
Issues like? Could you provide a breaking test or an example?

**Comment by danielbcorreia** [comment]
Sample entrypoint (springboot):

```java

@EnableSwagger2
@SpringBootApplication
public class SampleAPI {

    public static void main(String[] args) {
        SpringApplication.run(SampleAPI.class, args);
    }

    @Value("${api.basePath:}")
    public String apiBasePath;

    @Bean
    public Docket newsApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .pathProvider(new BasePathAwareRelativePathProvider(apiBasePath))
                .select().apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class))
                .paths(regex(".*"))
                .build();
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("Sample API")
                .build();
    }

    class BasePathAwareRelativePathProvider extends AbstractPathProvider {
        private String basePath;

        public BasePathAwareRelativePathProvider(String basePath) {
            this.basePath = basePath;
        }

        @Override
        protected String applicationPath() {
            return basePath;
        }

        @Override
        protected String getDocumentationPath() {
            return "/";
        }

        @Override
        public String getOperationPath(String operationPath) {
            UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/");
            return Paths.removeAdjacentForwardSlashes(
                    uriComponentsBuilder.path(operationPath.replaceFirst(basePath, "")).build().toString());
        }
    }
}
```

Setting an environment variable here (-Dapi.basePath=/something) still causes the "basePath" property of the swagger spec to be "/" (forward slash).

If you step through the code, you will see that the basePath is fine in this line:

```java
Swagger swagger = mapper.mapDocumentation(documentation);
```
(https://github.com/springfox/springfox/commit/a1ceac24e7cd0c646a6217391baa9d8a44fdb324#diff-e390517b6c056ed00ed0f28b8b4d3b77R82)

But then it gets overwritten when the hostname check is done.

**Comment by dilipkrish** [comment]
@danielbcorreia Perhaps you don't need to use a path provider. All you may need is to use the `docket#pathMapping("/something")` api.

**Comment by danielbcorreia** [comment]
That's a workaround that actually doesn't work for us. It changes all operations to have a /something prefix, instead of changing the "basePath" property on the swagger spec.

**Comment by dilipkrish** [comment]
Hmmm so the base path is specific to the docket? 

- how does your controller look? Could you give me an example based on below?
```java
@Controller
@RequestMapping("???")
class SomethingController {
     @RequestMapping("???")
     public void someMethod() {
     }
}
```

- What is your context path?
- Do you perhaps have a [dynamic dispatch servlet](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/WebApplicationInitializer.html) configured?

At the end of the day, in the docket we're trying to map reality using configuration. So somehow in your world the docket is not configuring things correctly. Without a concrete example or details its hard to be helpful.

**Comment by danielbcorreia** [comment]
```
@RestController
public class PingController {

    @ApiOperation(value = "Ping endpoint", notes = "Ping endpoint")
    @RequestMapping(value = "/ping", method = RequestMethod.GET, produces = MediaType.TEXT_PLAIN_VALUE)
    @ApiResponses(value = {@ApiResponse(code = 200, message = "OK")})
    public ResponseEntity<String> ping() {
        return ResponseEntity.ok("pong");
    }
}
```

We're just trying to set the "basePath" property on the swagger spec to be, for example, "/something" (instead of the default "/").

This was working before the change that I mentioned for X-Forwarded-Host was introduced. The blank/null host should not mean that the basePath should be touched.

We can avoid the problem by setting the hostname ourselves before that code takes place, but that is another workaround, and that is an optional field on the swagger spec.

In my opinion, a further check needs to exist when you check for ```isNullOrEmpty(swagger.getHost())```, so you don't override the basePath when you don't need to. We are not using X-Forwarded-Host, so our basePath should not be overwritten.

I can try to put together a pull request to try to fix this.

**Comment by jwbagger** [comment]
I've encountered the same problem and found version 2.3.1 to indeed function as expected. We are hosting a site with external url "http://site.com/apicall" but which is stored on a local folder. Swagger uses this folder somehow as base url, giving "try it out" calls like "http://site.com/folder/apicall" which is obviously not right and the base url needed to be corrected to be "/". Using the pathProvider (and even added an override for getApplicationBasePath() on top of the code for the BasePathAwareRelativePathProvider by @danielbcorreia  ), the path was still "/apicall". After moving back to version 2.3.1 the base url works flawlessly again (however, this version suffers from issue #1280 which is quite painful). Is it possible to correct the base url in a different way using 2.6.0 , or correct the property position in a different way using 2.3.1 .... or is this an issue I would just have to wait for v 2.7.0?

**Comment by dilipkrish** [comment]
The path provider or any of the usages haven't changed at all since 2.3.1. I suspect this is a changed behavior from spring 4.1.x -> 4.2.x. What ever you're using to front the service/proxy is not setup correctly.

**Comment by crisaltmann** [comment]
Hi guys.

I have the same issue on my docket configuration.
I have more than one version of an api. So, I have two docket definitions with the basePath set to api-context/version:

Example:
people/v1
people/v2

but as @danielbcorreia point, the basePath is overriden if host is not configured.

The url of my swagger is: http://localhost:8080/swaguer-ui.html
My service endpoint is: http://localhost:8080/people/v1

I think if I define a basePath, I want to ensure the swagger json use them.
My workaround attempt is to discover the host, and set them at the Docket creation. But at this moment, I'm searching a solution to do this.

**Comment by crisaltmann** [comment]
I create a workaround by adding a filter to v2/api-docs and create a new document with the current host and setting them to document cache.

It works, but i'm waiting for a fix to this issue.

Thanks.

**Comment by jonathannaguin** [comment]
Is this available in a SNAPSHOT build for testing?
