### ISSUE TITLE
2.6.0 update overrides the default behavior for the PropertyPlaceholderHelper

### ISSUE THREAD

**Issue by apixandru** [springfox/springfox#1508]
The 2.6.0 update seems to automatically configure a default for the whole application. This code works perfectly fine with 2.5.0 but crashes in 2.6.0 if spring.horse is undefined.

This is caused by a change in SwaggerCommonConfiguration when PropertySourcesPlaceholderConfigurer was replaced with PropertyPlaceholderConfigurer

I think that the new behavior is actually the default that spring boot had, I just wanted to log a side effect that I received by updating the library.

    @SpringBootApplication
    @RestController
    @EnableSwagger2
    public class Swagger2SpringBoot {
    
        @Value("${spring.horse}")
        private String horse;
    
        public static void main(String[] args) throws Exception {
            new SpringApplication(Swagger2SpringBoot.class).run(args);
        }
    
        @RequestMapping(value = "/dummy")
        String meGet() {
            return null;
        }
    
    
    }

**Comment by dilipkrish** [comment]
See this [thread discussion](https://github.com/springfox/springfox/issues/1414) for details. In your case it appears that you have a `PropertyPlaceholderConfigurer` that doesn't ignore unresolved values.

**Comment by apixandru** [comment]
Actually that is the only class in the project. I didn't configure any PropertyPlaceholderConfigurer so by default it does not ignore the unresolved values. 

I just wanted to log that before 2.6.0 springfox automatically configured the placeholder configurer for the whole application to ignore placeholders and now it doesn't anymore.

**Comment by cbornet** [comment]
Maybe fixed by https://github.com/springfox/springfox/commit/d3c18b9969648958811d3fcdff9b9fd5ff25a2e9 ?

**Comment by apixandru** [comment]
No, however that's a good thing. The new behavior is the correct behavior, it was actually wrong in 2.5.0.
I mainly created this issue to track the change in case someone else comes across this behavior.

That commit does however fix https://github.com/springfox/springfox/issues/1525

**Comment by dilipkrish** [comment]
Fixed has been fixed
