### ISSUE TITLE
Programmatically adding response models in plugins

### ISSUE THREAD

**Issue by woemler** [springfox/springfox#1509]
I have a controller, much like Spring Data REST's default controller type, where URL path variables define the return type for the method.  I have created a `ApiListingBuilderPlugin` that creates the appropriate documentation for each possible iteration of the path variable, but the response model does not resolve correctly.  It would seem that the way to add new response models is with a `ModelBuilderPlugin`, but it is not clear how the `ModelContext` and `ModelBuilder` are supposed to be utilized in this respect.  Is it possible to add response models on demand in a `ApiListingBuilderPlugin`, or is a secondary plugin needed to support this?

For context,  here is a method I am using to create `Operation` objects for the `ApiDescription`:

```java
private static Operation getFindByIdOperation(Class<?> model, TypeResolver typeResolver){
		return new Operation(
				HttpMethod.GET,
				"Fetch a single record by ID",
				"Fetches a single record by the primary key ID.  If no record is found, a 404 error is returned.",
				new ModelRef(model.getName()),  // <-- Here is the response model assignment
				"FindById",
				0,
				Collections.singleton(ModelUtil.getDisplayName(model)),
				new HashSet<>(ApiMediaTypes.getAllResponseTypeValues()),
				new HashSet<>(ApiMediaTypes.getAllAcceptTypeValues()),
				Collections.emptySet(),
				new ArrayList<>(),
				findByIdParameters(model, typeResolver),
				new HashSet<>(getStandardGetResponseMessages(model)),
				null,
				false,
				new ArrayList<>()
		);
	}

```

The Swagger JSON generated at `/v2/api-docs` shows this model reference in the `responses` map:

```
responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/me.project.models.MyEntity"
            }
          },
          ...
       }
```

But the `definitions` map does not actually include a reference to my model.

**Comment by dilipkrish** [comment]
@woemler Couple of things to get it to work
- Instead of model.getName(), try using model.getSimpleName() i.e. eliminate package name
- Use the docket api to add `additionalModels`

**Comment by woemler** [comment]
Thanks, this did the trick!  Is there any particular reason why the `Docket` method signature is `.additionalModels(ResolvedType, ResolvedType...)` and not simply `.additionalModels(ResolvedType...)`?  It would be useful to expand on the plugin documentation a little.  These are powerful and useful tools, but it is not very clear how each plugin is intended to be used.  In any case, keep up the great work!

**Comment by dilipkrish** [comment]
@woemler 🙇

Would be great and super useful if you could update the docs (PR) as you see appropriate. Here are [the docs](https://github.com/springfox/springfox/tree/master/docs/asciidoc).

About your question regarding varargs, its a [pattern to guard against null values](http://stackoverflow.com/a/25218196/19219)
