### ISSUE TITLE
2.6.0 update from 2.5.0 swagger UI error

### ISSUE THREAD

**Issue by qhwj2006** [springfox/springfox#1511]
![image](https://cloud.githubusercontent.com/assets/2918452/19218126/cfb9d232-8e23-11e6-9d6b-90214fb0fd10.png)

I use springfox 2.5.0 works well, but after update to 2.6.0, swagger UI errors come out,
error: SyntaxError: JSON Parse error: Unexpected identifier "undefined",// springfox.js row 43

![image](https://cloud.githubusercontent.com/assets/2918452/19218160/d3362540-8e24-11e6-9158-17ef1c69389f.png)

**Comment by dilipkrish** [comment]
It seems like you're `ObjectMapper` isn't configured correctly. Are you by any chance only using fields for serialization? Really you should be seeing a[ property called `jsonEditor`](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/UiConfiguration.java#L85-L88)

**Comment by qhwj2006** [comment]
@dilipkrish   I use fastjson, it seems not compatible with this,  but   2.5.0  works well with fastjson.

**Comment by dilipkrish** [comment]
Could you [try this suggestion](https://github.com/springfox/springfox/issues/1339#issuecomment-236146481) and see if it solves your problem?
