### ISSUE TITLE
Swagger ui not displaying model when using Map<String, Object>

### ISSUE THREAD

**Issue by baramsinsa** [springfox/springfox#1512]
Hi, 
I am having an application in Spring having Maven dependency
springfox-swagger2   - version 2.4.0
springfox-swagger-ui - version 2.4.0

Swagger UI not displaying Model and Model Schema when using Map <String, Object>
it shows empty schema {}

``` java
      public Map<String, Object> getPromotionDetail(
            @PathVariable("promotionId") String promotionId
            HttpServletRequest request) {
        Map<String, Object> resultMap = new HashMap<String, Object>();

        resultMap.put("promotion", promotionService.getPromotionDetail(promotionId);

        return resultMap;
    }
```

**Comment by dilipkrish** [comment]
The reason it shows an empty schema is that, in the schema world a `Map<String, Object>` is equivalent to an *ANY* type.

As an aside please upgrade to `2.6.0`

**Comment by baramsinsa** [comment]
i tried to Map<String, Object> -> Map<String, String>
but, it still shows empty schema {}

`public Map<String, String> getPromotionDetail(
            @PathVariable("promotionId") String promotionId
            HttpServletRequest request) {
        Map<String, String> resultMap = new HashMap<String, Object>();

        resultMap.put("promotion", promotionService.getPromotionDetail(promotionId);

        return resultMap;
    }`
