### ISSUE TITLE
Presentation of maps in static docs

### ISSUE THREAD

**Issue by wbauern** [springfox/springfox#1516]
I have a question about how maps are displayed in the static docs generated from SpringFox.  I'm currently using version 2.6.0.  I have a class that contains a List<Item> and a Map<String,Item>.  The list is presented as I would expect in the static docs with a schema of **Item** array (with the **Item** being a link to the Item spec in the doc).  The map field itemMap however just shows a schema type of object with no reference to the Item spec at all.  Is this expected behavior?  I understand that there is no map type in the Swagger spec but I was hoping it would at least keep the relationship to the Item type which is correctly generated in the additionalProperties field of the spec.

The generated Swagger Spec from springfox contains:
```
      "Memo" : {
            "itemMap" : {
               "additionalProperties" : {
                  "$ref" : "#/definitions/Item"
               },
               "type" : "object"
            },
            "itemList" : {
               "items" : {
                  "$ref" : "#/definitions/Item"
               },
               "type" : "array"
            }
         },
         "type" : "object"
      },
```

Thanks for the help!

**Comment by dilipkrish** [comment]
I suspect that the version you're using of static docs isn't the latest version. You might want to check [the latest version](https://github.com/Swagger2Markup/swagger2markup).

**Comment by wbauern** [comment]
I was using the SpringFox Swagger2MarkupResultHandler for the static doc generation.  Are you saying try using the latest version of Swagger2Markup directly?  Or is there a version of SpringFox available that is using that version of Swagger2Markup?

**Comment by dilipkrish** [comment]
@wbauern Yes @RobWin has made tremendous improvements on that library since it was last updated here. The static docs on this library is still stuck in java 6 compatibility land. To a large extent  much of what is provided in the static docs repository is superseded by the swagger2markup project itself. There is plenty of examples there as well.

**Comment by wbauern** [comment]
@dilipkrish Got it working with the latest version of Swagger2Markup.  Thanks for pointing me in the right direction.

**Comment by RobWin** [comment]
If you have any questions, then feel free to join our Swagger2Markup Gitter channel
