### ISSUE TITLE
use urldecode content in tags cause a problem that i can't expand the api dom

### ISSUE THREAD

**Issue by blackshadowwalker** [springfox/springfox#1518]
see here https://github.com/swagger-api/swagger-ui/issues/2357

**Comment by blackshadowwalker** [comment]
##  Version-2.5.0 work's OK:
![qq 20161012164542](https://cloud.githubusercontent.com/assets/5380980/19303513/81419480-909b-11e6-83fe-f091f8feea88.png)

##  Version-2.6.0 can not expand api 


![qq 20161012164558](https://cloud.githubusercontent.com/assets/5380980/19303801/aef7f95e-909c-11e6-8cdd-a973a0d9c613.png)

**Comment by dilipkrish** [comment]
This seems like a swagger ui issue.  What did they say?
