### ISSUE TITLE
SpringBoot with external Tomcat

### ISSUE THREAD

**Issue by eboats** [springfox/springfox#1519]
I have no problems using springfox swagger 2 when running my Spring Boot Rest API app with its embedded Tomcat server.  However, I get Maven build errors when trying to package my app as war to be used with an external Tomcat server.

Various build errors I've gotten are :
 org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping] found

No qualifying bean of type [javax.servlet.ServletContext] found for dependency

I'm using the springfox-swagger-ui/springfox-swagger2    2.6.0 dependencies and my Swagger config class has the @Configuration and @EnableSwagger2 annotations.

I've tried having my config class extend WebMvcConfigurerAdapter and overriding addResourceHandlers but no luck.  I've also tried removing @Configuration but no luck there either.

I'm guessing there's some additional config I need to do if I'm not running this with the embedded SpringBoot tomcat?

**Comment by dilipkrish** [comment]
There is a mis configuration in how you're building the war. Otherwise, you should be able to see those beans as they are what make spring mvc work.

**Comment by eboats** [comment]
Not sure what you mean.  I'm just doing a standard mvn clean package.   When I run my app as a SpringBoot app with embedded tomcat, it works fine, probably because SpringBoot takes care of providing a servlet context when it runs.  

But when I try to package it as a standard war, I get the errors related to spring/swagger, so I'm wondering what additional Spring config I need to get your swagger integration working.  When I don't include the Swagger Config class (or if I remove the @EnableSwagger2), I'm able to build/package my app fine and run it in my external Tomcat.  

My pom is using the spring-boot-starter-parent and spring-boot-starter-data-rest dependencies.  My swagger config is :

@Configuration
@EnableSwagger2
public class SwaggerConfig  {
	
    @Bean
    public Docket documentation() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("plan")              
                .select()
                	.apis(RequestHandlerSelectors.any())
                  	.paths(regex("/plan.*"))
                	.build()
                .pathMapping("/")
                .useDefaultResponseMessages(false)
                .apiInfo(metadata());
    }

**Comment by eboats** [comment]
Oh, the errors should be reproducible if you :
 
- create a Spring Boot project
- include the spring-boot-starter-data-rest  dependency
- include the Swagger Config class
- try to package it as a standard war with maven

**Comment by dilipkrish** [comment]
Have you tried following [this guide](https://spring.io/blog/2014/03/07/deploying-spring-boot-applications). I think you might be missing setting up the servlet initializer
