### ISSUE TITLE
Proposal to remove defaults for min / max in MinMaxAnnotationPlugin

### ISSUE THREAD

**Issue by jamesbassett** [springfox/springfox#1521]
Hi :)

As part of #1517, I noticed that min/max gets defaulted to `-Double.MAX_VALUE`/`Double.MAX_VALUE` by the `MinMaxAnnotationPlugin` when `@Min`/`@Max` is not present.

I wasn't expecting that, so when I generated my asciidoc, I was surprised to see a max value when I hadn't specified it. Is there a particular reason for the defaults?

I'd like to propose removing the defaults - if someone wants to specify a min/max, they can do it by specifying the appropriate annotation.  No min/max implies the default for that data type (there's no need to document it explicitly).

Failing that, the defaults should be a bit smarter. `@Min`/`@Max` can be applied to `byte`, `short`, `int`, `long` and their wrappers, as well as `BigDecimal` (which can be insanely big) - so `Double.MAX_VALUE` isn't always appropriate. It's a lot easier to just only use the provided values with no defaults.

This also applies to the `DecimalMinMaxAnnotationPlugin` from #1517.

Thoughts ??

**Comment by dilipkrish** [comment]
There is no particular reason for the defaults other than to give it an explicit range. Im cool with omitting defaults if not specified

**Comment by jamesbassett** [comment]
Cool, I'll submit a PR today then :)

**Comment by dilipkrish** [comment]
Fixed via #1517
