### ISSUE TITLE
baseUrl | context path

### ISSUE THREAD

**Issue by gangakrishh** [springfox/springfox#1522]
i'm using springfox for rest api documentation.. i'm using embedded tomcat in local (spring-boot)

/auto - local 
but in other environment (qa or production) context name will be added to uri 
/abc/auto -- production

 how to resolve this?

**Comment by dilipkrish** [comment]
Create two dockets with different profiles... and a `docket.pathMapping("/abc")` to the production one. Tho i'd venture to say that that may not be required.

**Comment by gangakrishh** [comment]
Thanks @dilipkrish it is working... would you want me to close this?
