### ISSUE TITLE
Is Swagger UI XmlHttpRequest timeout configurable?

### ISSUE THREAD

**Issue by neildcruz19** [springfox/springfox#1523]
Swagger UI version : 2.5.0

Question:

Is there a way to increase or configure the timeout for the Swagger UI XmlHttpRequests when performing an operation?

I have a scenario where the service running as a spring boot micro-service on Tomcat which takes a little longer than usual to respond(45 secs - 1 min) and gets a Broken pipe exception even though it completes the request successfully.

I am assuming that the Swagger UI XmlHttpRequest has a timeout specified for the operation and times out after 5-10 secs.

I've looked around the swaggerUI js code which does specify timeouts for operations but could not find a way to configure or override the defaults.

**Comment by dilipkrish** [comment]
Swagger-ui underneath the scenes uses ajax. So you could set the [options on ajax requests](http://api.jquery.com/jquery.ajax/) globally. However if you're using the bundled swagger-ui that isn't an option.

**Comment by neildcruz19** [comment]
Was not able to resolve this by using the jquery global ajaxSetup, since, swagger-ui uses jQuery only selectively for some operations.

The only way it worked was to add the timeout option when instantiating the SwaggerUI object from springfox.js which gets propogated to all requests.

```
 window.swaggerUi = new SwaggerUi({
      dom_id: "swagger-ui-container",
      validatorUrl: data.validatorUrl,
      supportedSubmitMethods: data.supportedSubmitMethods || ['get', 'post', 'put', 'delete', 'patch'],
      timeout: 60000,
      onComplete: function(swaggerApi, swaggerUi) {

        initializeSpringfox();

        if (window.SwaggerTranslator) {
          window.SwaggerTranslator.translate();
        }

        $('pre code').each(function(i, e) {
          hljs.highlightBlock(e)
        });

      },
```
Above is a crude implementation used to test. May be add to the UiConfiguration object?

**Comment by dilipkrish** [comment]
Thanks for researching that. It seems like a simple enough feature to support.

**Comment by Cloudmersive** [comment]
This didn't work - we really need this to be implemented
