### ISSUE TITLE
SpringFox integration with Spring Boot + Spring Security OAuth 2

### ISSUE THREAD

**Issue by mohan-gliimpse** [springfox/springfox#1524]
Is there any sample code that implements Spread ngFox + Spring Boot Application + Spring Security OAuth2, such that all end ponta are naturally exposed and documented, including, crucially, the OAuth 2 end points?  The OAuth flow we are using is Aithorization Code Flow.

Cheers

**Comment by dilipkrish** [comment]
@mohan-gliimpse the best example is to use [jhipster](https://jhipster.github.io) to generate a project for you with oauth.
