### ISSUE TITLE
Is there any way to add a wrapper class to all response types in api-docs?

### ISSUE THREAD

**Issue by veysiertekin** [springfox/springfox#1527]
I have search anywhere but could not find any solution to my problem;

Consider that i have a rest method:

``` java
    @GetMapping
    public ResponseType method() {
        return new ResponseType();
    }
```

And an aspect like:

``` java
@Aspect
@Component
public class MyResponseInterceptor {
    @Pointcut("execution(public * com.mypackage.*(..)) && @annotation(org.springframework.web.bind.annotation.RequestMapping)")
    public void allControllerMethods() {
        // this is a pointcut
    }

    @Around("allControllerMethods()")
    public Object aroundAllControllerMethods(ProceedingJoinPoint proceedingJoinPoint) throws Throwable {
        MyWrapperResponseType response = new MyWrapperResponseType();

        Object data = proceedingJoinPoint.proceed();

        response.setData(data);

        return response;
    }
}
```

So, springfox generates api-doc response type as `ResponseType` but it should be

``` java
class MyWrapperResponseType {
    Object data =  // ResponseType 
}
```

Is there any way to do this you know?

**Comment by dilipkrish** [comment]
The only way I can think of right now is to create alternate type rules for each of the return types (which kind of sucks a little I know).

`newRule(ResponseType.class, MyWrapperResponseType.class);`

**Comment by veysiertekin** [comment]
Hi @dilipkrish,

Thank you for your response, yes may be `newRule` fixes for a single type but i need a generic solution for all response types or package restricted way. Something like:

```java
  @Autowired
  private TypeResolver typeResolver;

...
newRuleResolver(
    "com\\.example.*" /*regex for class name!*/,
    this::ruleResolver // for java 1.7 we can use an interface :)
); 
...

public <T> Type ruleResolver(T inputType){
    return typeResolver.resolve(new GenericType<MyWrapperResponseType<T>>() {})
}
...

class MyWrapperResponseType<T> {
    T data =  // ResponseType 
}
```

By the way, if we agree on a solution, i can try to make changes and send a PR for this.

**Comment by dilipkrish** [comment]
If you pass in a `WildcardType.class` it should work, but that will wrap all models. Essentially its hard to do it across the API today. Might be worth considering as a feature to only create rules for top level models.
