### ISSUE TITLE
The service does not work after using Swagger 2.6 in Spring Cloud

### ISSUE THREAD

**Issue by puras** [springfox/springfox#1528]
After using Swagger 2.6, when registering with the registration module, the registered instance name becomes "Unknown", which causes the corresponding service can not be found correctly when the service is found by the service name.

Ask for help!

**Comment by dilipkrish** [comment]
Yeah this is a known issue that has been addressed via #1514

**Comment by dilipkrish** [comment]
Could you verify that 2.6.1-SNAPSHOT fixes it?

**Comment by puras** [comment]
I try, the results and then feedback
