### ISSUE TITLE
how to enable cors

### ISSUE THREAD

**Issue by gangakrishh** [springfox/springfox#1530]
how to enable cors for swagger rest apis (springfox implementation) if i'm using swagger-ui (hosted on other server)

example:
xyz-service/v2/api-docs?group=xyz-service

**Comment by dilipkrish** [comment]
Add in a `CorsFilter`. Here is an example taken from the [jhipster](https://jhipster.github.io/) generated project.

```java

    @Bean
    @ConditionalOnProperty(name = "jhipster.cors.allowed-origins")
    public CorsFilter corsFilter() {
        log.debug("Registering CORS filter");
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = jHipsterProperties.getCors();
        source.registerCorsConfiguration("/api/**", config);
        source.registerCorsConfiguration("/v2/api-docs", config);
        source.registerCorsConfiguration("/oauth/**", config);
        source.registerCorsConfiguration("/*/api/**", config);
        source.registerCorsConfiguration("/*/oauth/**", config);
        return new CorsFilter(source);
    }

```

**Comment by gangakrishh** [comment]
Thanks Dilip for answer, i've tried this approach https://spring.io/guides/gs/rest-service-cors/, working well

@Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurerAdapter() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/greeting-javaconfig").allowedOrigins("http://localhost:9000");
            }
        };

**Comment by dilipkrish** [comment]
@gangakrishh thanks for reporting back

**Comment by aklakl** [comment]
could you provide the whole code?

**Comment by dilipkrish** [comment]
@aklakl it should be available in `https://spring.io/guides/gs/rest-service-cors/`

**Comment by shanekenyon87** [comment]
Yes, adding this method to my Application class did the trick.  Note this also opens up the API so that you can accept CrossOrigin requests.  The details of the `addMapping()` bit are up to you, but this example opens up everything from everywhere.  Here is the full class.

```Java
@SpringBootApplication
@EnableSwagger2
public class Application {
  public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
  }

  @Bean
  public WebMvcConfigurer corsConfigurer() {
    return new WebMvcConfigurerAdapter() {
      @Override
      public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**").allowedOrigins("*");
      }
    };
  }
}
```
