### ISSUE TITLE
UI configuration problem

### ISSUE THREAD

**Issue by yangyang0507** [springfox/springfox#1531]
<img width="1279" alt="qq20161020-1 2x" src="https://cloud.githubusercontent.com/assets/5666807/19549332/531ff178-96d6-11e6-9ac7-bbc30ccad687.png">
<img width="1275" alt="qq20161020-0 2x" src="https://cloud.githubusercontent.com/assets/5666807/19549331/531cf630-96d6-11e6-9b56-151021406ca1.png">

why the json result is enableJsonEditor?

**Comment by dilipkrish** [comment]
Not sure what you're asking.

**Comment by yangyang0507** [comment]
my project default jsonutil is fastjson, when i use swagger-ui, the result of ui configuration url(/configuration/ui) is enableJsonEditor, there should be jsonEditor, so suggest this json result use default name, not annotation
