### ISSUE TITLE
SpringFox and Eureka failing 

### ISSUE THREAD

**Issue by sundarsy** [springfox/springfox#1532]
I have several microservices and all of them are registered in Eureka (Discovery Client). Recently I have enabled Swagger2 (SpringFox) for all the microservices.

As soon as I enabled swagger my microservices started registering to Eureka as "UNKNOWN" service and registering with default 8080 port.

My Application Class goes like this.

```
@SpringBootApplication
@EnableDiscoveryClient
@EnableSwagger2
public class Application {
    private static final Logger LOG = LoggerFactory.getLogger(CaseApplication.class);

    public static void main(String[] args) {
        LOG.debug("Bootstrapping Case Service");
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public Docket caseApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("Audit")
                .apiInfo(apiInfo())
                .select()
                .paths(regex("/app.*"))
                .build();
    }

     @Bean
        public UiConfiguration uiConfig() {
          return new UiConfiguration("validator", UiConfiguration.Constants.NO_SUBMIT_METHODS);
        }


    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("Application Service")
                .description("Application Microservice API Documentation")
                .version("1.0")
                .build();
    }
}
```
I have tried moving my some of the configuration from application.yml to bootstrap.yml. But if I move my ribbon client is not able to get the application instance and the Eureka registry.

If I remove the Swagger2 configurations, I am able to seamlessly connect/register with y discovery service.

Any help will be appreciated.

**Comment by dilipkrish** [comment]
This is a bug related to #1514 Could you try with 2.6.1-SNAPSHOT and see if fixes your issue. If so Im planning to release 2.6.1 shortly

**Comment by sundarsy** [comment]
Works like a charm. I will post the results once I completely integrate it with all the microservices. 

Do we have a release date for 2.6.1?

**Comment by dilipkrish** [comment]
Im going to see if I can release in the next week

**Comment by sundarsy** [comment]
Hi Dilip - It works fine with the entire set of microservices and I do not see any problem with the Eureka or Zuul. Thanks for the help.
