### ISSUE TITLE
Support PropertyNamingStrategy SNAKE_CASE

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#1534]
I have spring boot application.

I use 
`objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);`

after this appears exeception

> DEBUG com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder - Unable to instantiate jackson 26 object
> java.lang.NoSuchMethodException: com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.&lt;init>(com.fasterxml.jackson.databind.PropertyName, com.fasterxml.jackson.databind.AnnotationIntrospector, boolean)
>   at java.lang.Class.getConstructor0(Class.java:3082)
>   at java.lang.Class.getConstructor(Class.java:1825)
>   at springfox.documentation.schema.property.PojoPropertyBuilderFactory.constructorWithParams(PojoPropertyBuilderFactory.java:105)
>   at springfox.documentation.schema.property.PojoPropertyBuilderFactory.jackson26Instance(PojoPropertyBuilderFactory.java:89)
>   at springfox.documentation.schema.property.PojoPropertyBuilderFactory.create(PojoPropertyBuilderFactory.java:42)
>   at springfox.documentation.schema.property.BeanPropertyDefinitions.getName(BeanPropertyDefinitions.java:69)
>   at springfox.documentation.schema.property.BeanPropertyDefinitions.access$000(BeanPropertyDefinitions.java:28)
>   at springfox.documentation.schema.property.BeanPropertyDefinitions$2.apply(BeanPropertyDefinitions.java:58)
>   at springfox.documentation.schema.property.BeanPropertyDefinitions$2.apply(BeanPropertyDefinitions.java:55)
>   at com.google.common.base.Present.transform(Present.java:71)

It seems that springfox doesn't like this parameter.

**Comment by raderio** [comment]
similar to https://github.com/jhipster/generator-jhipster/issues/4303

**Comment by dilipkrish** [comment]
This is a debug message. Are you seeing an actual problem?

**Comment by raderio** [comment]
Well, yeap it is not an actual problem, but it is noise what could make debug harder.
