### ISSUE TITLE
Swagger documentation erroneously consumes application/json

### ISSUE THREAD

**Issue by richmeyer7** [springfox/springfox#1539]
When our code annotates a PATCH with @ApiOperation and sets consumes = "application/merge-patch+json", the Spring Fox Swagger 2.6.0 HTML documentation erroneously shows that the method consumes both "application/json" and "application/merge-patch+json". And worse, the erroneous "application/json" choice is the default and first entry in the drop-down.

I traced the behavior in the debugger, and this is apparently caused by springfox.documentation.spring.web.scanners.MediaTypeReader being first in DocumentationPluginsManager's operationBuilderPlugins, and because the consumesList is empty at that time, its method apply(OperationContext) adds MediaType.APPLICATION_JSON_VALUE.

Later, SwaggerMediaTypeReader calls method springfox.documentation.swagger.readers.operation.SwaggerMediaTypes.apply(OperationContext), which adds "application/merge-patch+json" to the OperationBuilder's consumes Set, which already contains MediaTypeReader's erroneous first entry.

One potential fix is to apply plugin SwaggerMediaTypeReader before plugin MediaTypeReader. Then MediaTypeReader would not see an empty consumesList and thus would not add "application/json". However, I don't know if a plugin order dependency is appropriate. Perhaps MediaTypeReader should not add a default media type just because it sees an empty consumesList when it gets its turn at an unknown point in the iteration through a large set of plugins? If a mechanism to ensure a non-empty consumesList is required, then perhaps it should be coordinated between all of the plugins. Then a default could be decided if no plugin detected a specified media type.

Also, for clarity, variables consumesList and producesList in method MediaTypeReader.apply(OperationContext) should be renamed to consumesSet and producesSet.

**Comment by dilipkrish** [comment]
This is by design. If one don't specify a consumes media type, it will accept any media type and application/json is one of them.

**Comment by richmeyer7** [comment]
We do specify the consumes media type.

The problem seems to be that the plugin that recognizes that fact is
applied after the plugin that adds the default media type.

**Comment by richmeyer7** [comment]
Please see the first sentence of the issue write-up: consumes = "application/merge-patch+json".

**Comment by dilipkrish** [comment]
I saw that, I should have been more explicit.. You need to set the consumes on the ***[request mapping](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestMapping.html#consumes--)***

**Comment by richmeyer7** [comment]
Thank you, Dilip.
I set the consumes on the @RequestMapping annotation, and the documentation drop-down behaved as desired.
Should I also keep the consumes set on the @ApiOperation annotation? Removing it there seemed to have no adverse effect on my displayed documentation.

**Comment by dilipkrish** [comment]
[Philosophically](http://springfox.github.io/springfox/docs/current/#goals) we prefer to _ONLY_ use annotations where we cannot infer details from the operation.
