### ISSUE TITLE
Swagger ui not displaying model when using Map<String, String>

### ISSUE THREAD

**Issue by baramsinsa** [springfox/springfox#1543]
I am having an application in Spring having Maven dependency
springfox-swagger2   - version 2.6.0
springfox-swagger-ui - version 2.6.0

i tried to `Map<String, Object>` -> `Map<String, String>`
but, it still shows empty schema {}

``` java
public Map<String, String> getPromotionDetail(
            @PathVariable("promotionId") String promotionId
            HttpServletRequest request) {
        Map<String, String> resultMap = new HashMap<String, String>();
        String promotionDetail = promotionService.getPromotionDetail(promotionId);
        resultMap.put("promotion", promotionDetail);

        return resultMap;
    }
```

**Comment by dilipkrish** [comment]
This is working as expected. If you look at the generated api-docs @ `/v2/api-docs` you'll find that it generates he response like so:

```json
"responses":
{
    "200": {
        "description": "OK",
        "schema": {
            "additionalProperties": {
                "type": "string"
            },
            "type": "object"
        }
    }
   ...
}
...
```

This is a swagger-ui issue that it doesnt render a map response

**Comment by baramsinsa** [comment]
If so.. I don't use Map ?
for example, ```java Map<String, Promotion>``` , ```java Map<String ,String> ```

**Comment by dilipkrish** [comment]
You can use it, just that it won't work as expected in swagger-ui

**Comment by baramsinsa** [comment]
I understand.
Sorry, but i want know that when  will support ```Map<String, String>``` in swagger-ui

**Comment by dilipkrish** [comment]
No idea you have to ask the maintainers of swagger-ui
