### ISSUE TITLE
[Feature request] JDK8 JSR310 types support

### ISSUE THREAD

**Issue by cbornet** [springfox/springfox#1544]
Today we need to map JSR310 types to corresponding java.util.Date and java.sql.Date in the docket configuration using
```java
            .directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
            .directModelSubstitute(java.time.Instant.class, Date.class)
            .directModelSubstitute(java.time.ZonedDateTime.class, Date.class)
            .directModelSubstitute(java.time.OffsetDateTime.class, Date.class)
            .directModelSubstitute(java.time.LocalDateTime.class, Date.class)
```
I think it is easy to provide these mappings by default by adding AlternateTypeRule rules in springfox.documentation.spi.service.contexts.Defaults like has been done for java.util.Optional.

I can do the PR if OK.

**Comment by dilipkrish** [comment]
Those are java 8 types. So may be a conditional check just like optional so that it compiles in Java 7 as well? 

```java
void maybeAddJava8DateTypes(Docket docket) {
      if (jdk8) {
        docket.directModelSubstitute(Class.forName("java.time.LocalDate"), java.sql.Date.class);
        //More
      }
}
```

**Comment by cbornet** [comment]
Yes, I think I'll reuse the check on Optional since if you have Optional you have java.time

**Comment by cbornet** [comment]
Any idea on how to add unit tests ? Or do I just forget about them ?

**Comment by dilipkrish** [comment]
Its tested [indirectly here](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/groovy/springfox/documentation/spring/web/plugins/DocketSpec.groovy#L151-L165). Might be a good idea to test explicitly using a similar technique.
