### ISSUE TITLE
Swagger UI ignores certain HTML tags

### ISSUE THREAD

**Issue by zolcsi** [springfox/springfox#1549]
Question: I am using v.2.6.0 and have in @ ApiOperation in 'notes' field a well formatted html, which was shown perfectly before in version 2.1.5.
Newly some tags seem to be ignored/filtered out/who knows?
Like: `<br>, <ul></ul>`
Do you have any thoughts about it?

**Comment by dilipkrish** [comment]
That would be a question for the [swagger-ui project](https://github.com/swagger-api/swagger-ui)

**Comment by zolcsi** [comment]
ok
