### ISSUE TITLE
Authentication Filter

### ISSUE THREAD

**Issue by Viacheslav-Petriaiev** [springfox/springfox#1551]
Hello, thanks a lot for your awesome library!

Right now, I have a problem like this one
http://stackoverflow.com/questions/37671125/how-to-configure-spring-security-to-allow-swagger-url-to-be-accessed-without-aut

My rest services path is /rest/api, so I get 401 error when tried to open /rest/api/swagger-ui.html
I have tried start swagger in url /rest/docs, using custom SwaggerWebMvcConfigurer, but I got 2 problems:
1) SwaggerWebMvcConfigurer exposes all my rest controllers at url /rest/docs without any authnentication logic of course)))
2) Do I have any opportunity change base url for swagger-ui.html (/rest/docs -> /rest/api)?

Or maybe you have any suggestions how to solve my problem?

Thanks a lot

**Comment by dilipkrish** [comment]
I'd say you should follow the security implementation used to by [jhipster](https://jhipster.github.io).
