### ISSUE TITLE
@RequestParam with a Collection of non-primitives

### ISSUE THREAD

**Issue by kevinm416** [springfox/springfox#1556]
I'm using springfox-swagger2 v2.6.0

I have an endpoint:

    @RequestMapping(value = "/getStuff", method = RequestMethod.GET)
    @ResponseBody
    public String getStuff(@RequestParam("uri") List<String> uris) {
        System.out.println(uris);
        return "hi";
    }

And this outputs reasonable the following json for the uris parameter, which looks good to me:

        "parameters" : [ {
          "name" : "uri",
          "in" : "query",
          "description" : "uri",
          "required" : true,
          "type" : "array",
          "items" : {
            "type" : "string"
          },
          "collectionFormat" : "multi"
        } ],

However, when I change that String uri to a Java type, the swagger json output becomes incorrect. In particular:

    @RequestMapping(
            value = "/getStuff",
            method = RequestMethod.GET)
    @ResponseBody
    public String getStuff(@RequestParam("uri") List<WrappedString> uris) {
        System.out.println(uris);
        return "hi";
    }

    public class WrappedString {
        private final String uri;

        @JsonCreator
        public WrappedString(String uri) {
            this.uri = uri;
        }

        @JsonValue
        public String getUri() {
            return uri;
        }

    }

With the docket:

            TypeResolver resolver = new TypeResolver();
            ResolvedType wrappedStringType = resolver.resolve(WrappedString.class);
            ResolvedType stringType = resolver.resolve(String.class);
            return new Docket(DocumentationType.SWAGGER_2)
                    .alternateTypeRules(
                            new AlternateTypeRule(wrappedStringType, stringType));

Produces this parameter:

        "parameters" : [ {
          "name" : "uri",
          "in" : "query",
          "description" : "uri",
          "required" : true,
          "type" : "string"
        } ],

It no longer has the "collectionFormat" key, even though the json serialization format has not changed at all. Is this expected, or is it a bug? If this is expected, is there a way that I have missed so that @RequestParam's that are collection types produce the "collectionFormat" key in the swagger json?

**Comment by dilipkrish** [comment]
@kevinm416 Thanks for reporting. Its not easy to support `@JsonValue`. The workaround is to setup alternate type rules to map `WrappedString` to `String`

**Comment by kevinm416** [comment]
Hi @dilipkrish, could you please expand on your answer? In my original question, I showed how I did set up alternateTypeRules. Did I do it correctly? Is there anything else I need to do?

**Comment by dilipkrish** [comment]
@kevinm416 Sorry, that earlier answer was from a mobile phone :)

You need to set up rules explicitly for the types. This is by design, we don't want rules to be an arbitrary pattern match. So a you'd need to create a rule to replace `List<WrappedString>` and it will not suffice to have a rule for `WrappedString`. In your case, it that translates to

```java
       TypeResolver resolver = new TypeResolver();
        ResolvedType listOfWrapped = resolver.resolve(List.class, WrappedString.class);
        ResolvedType listOfString = resolver.resolve(List.class, String.class);
        return new Docket(DocumentationType.SWAGGER_2)
                .alternateTypeRules(
                        new AlternateTypeRule(listOfWrapped, listOfString));
```

**Comment by kevinm416** [comment]
Cool, that worked, thank you! 

This solution will work for me, but it does seem a bit cumbersome. It seems like I will have to add alternativeTypeRules for `Set<WrappedString>`, `ImmutableSet<WrappedString>`, `Collection<WrappedString>`, `Iterable<WrappedString>`, etc. for every type that I use `@JsonValue` with. Is that accurate?

**Comment by dilipkrish** [comment]
That is true. Might be a worthy enhancement, don't have time for it at the moment
