### ISSUE TITLE
Using Docket.enableUrlTemplating(true) causes unnecessary curly braces in request URL.

### ISSUE THREAD

**Issue by JaspreetKaur16** [springfox/springfox#1557]
I am using springfox-swagger-ui-2.6.0.jar

On using following configuration with  .enableUrlTemplating(true), the request URL has curly braces appended and such a URL is incorrect and cannot be processed.

return new Docket(DocumentationType.SWAGGER_2)  
         .select()                                  
         .apis(RequestHandlerSelectors.any())              
         .paths(PathSelectors.any())
         .build()
         .enableUrlTemplating(true)
         .globalOperationParameters(parameters);

For example the REQUEST URL formed in swagger-ui.html will look like

`http://jkaur2k12:61400/rest/service/admin/attributes/2{?loginname,loginpassword,view}& loginname=Admin&loginpassword=Admin&view=xmlView`

**Comment by dilipkrish** [comment]
@JaspreetKaur16 Your choices are to either list all the operations or Have the docket support url templating. Cant have both.

**Comment by JaspreetKaur16** [comment]
![curlybraceissue](https://cloud.githubusercontent.com/assets/23232273/19995427/2a93a7c4-a27d-11e6-893c-7d593e4566c0.jpg)

Now if we look at the attached image of issue, I believe in following Request URL the part 
{?loginname,loginpassword,view} is unneccessary. Ideally the Request URL should be this
http://jkaur2k12:61400/rest/service/admin/attributes/2?loginname=Admin&loginpassword=Admin&view=xmlView

rather than the following incorrcet one.
http://jkaur2k12:61400/rest/service/admin/attributes/2{?loginname,loginpassword,view}& loginname=Admin&loginpassword=Admin&view=xmlView

How to fix this ?


Thanks,
Jaspreet
