### ISSUE TITLE
Coercing Optional<DateTimeZone> to String

### ISSUE THREAD

**Issue by kevinm416** [springfox/springfox#1558]
I'm using springfox-swagger2 v2.6.0

I have an endpoint:

    @RequestMapping(
            value = "/getStuff",
            method = RequestMethod.POST)
    @ResponseBody
    public StringResponse getStuff() {
        return new StringResponse(Optional.of(DateTimeZone.UTC), Optional.of("abc"), "def");
    }

    public static class StringResponse {
        private final Optional<DateTimeZone> dtz;
        private final Optional<String> optionalString;
        private final String nonOptionalString;

        @JsonCreator
        public StringResponse(
                @JsonProperty("dtz") Optional<DateTimeZone> dtz,
                @JsonProperty("optionalString") Optional<String> optionalString,
                @JsonProperty("nonOptionalString") String nonOptionalString) {
            this.dtz = dtz;
            this.optionalString = optionalString;
            this.nonOptionalString = nonOptionalString;
        }

        public Optional<DateTimeZone> getDtz() {
            return dtz;
        }

        public Optional<String> getOptionalString() {
            return optionalString;
        }

        public String getNonOptionalString() {
            return nonOptionalString;
        }
    }

And I have configured the Docket like this. I have also tried a number of different combinations of alternativeTypeRule and directModelSubstitute.

    public Docket getSwagger() {
            Contact contact = null;
            final ApiInfo apiInfo = new ApiInfo(
                    null,
                    null,
                    null,
                    null,
                    contact,
                    null,
                    null);
            TypeResolver resolver = new TypeResolver();
            ResolvedType dtzType = resolver.resolve(DateTimeZone.class);
            ResolvedType optionalDtzType = resolver.resolve(Optional.class, DateTimeZone.class);
            ResolvedType stringType = resolver.resolve(String.class);
            return new Docket(DocumentationType.SWAGGER_2)
                    .apiInfo(apiInfo)
                    .genericModelSubstitutes(Optional.class)
                    .directModelSubstitute(DateTimeZone.class, String.class)
                    .alternateTypeRules(
                            new AlternateTypeRule(dtzType, stringType),
                            new AlternateTypeRule(optionalDtzType, stringType));
        }

The swagger.json that gets produced for StringResponse looks like this:

    "StringResponse" : {
      "type" : "object",
      "properties" : {
        "dtz" : {
          "$ref" : "#/definitions/DateTimeZone"
        },
        "nonOptionalString" : {
          "type" : "string"
        },
        "optionalString" : {
          "type" : "string"
        }
      }
    }

I expect the json to look like this:

    "StringResponse" : {
      "type" : "object",
      "properties" : {
        "dtz" : {
          "type" : "string"
        },
        "nonOptionalString" : {
          "type" : "string"
        },
        "optionalString" : {
          "type" : "string"
        }
      }
    }

I've put together a runnable test for this: https://github.com/kevinm416/swagger-test/blob/master/src/main/java/com/kevinm416/SwaggerController.java. That repo is built with gradle, so you should be able to check it out, and run SwaggerController as a JUnit test easily.

Is this a bug, or is there some way to configure the Docket to achieve the result that I want?

**Comment by dilipkrish** [comment]
This may be a bug... let me investigate.
