### ISSUE TITLE
Support multiple apis() in swagger config

### ISSUE THREAD

**Issue by cloudhuang** [springfox/springfox#1559]
Here I tried to add the Spring-Actuator endpoints according to the stackoverflow issue - http://stackoverflow.com/questions/39159998/swagger2-document-a-springboot-mvcendpoint,

So I created the following swagger config, but seems the sendond apis will override the first one.
```
@Configuration
@EnableSwagger2
public class Swagger2Config {
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2)
				.select()
				.apis(RequestHandlerSelectors.any())
				.apis(RequestHandlerSelectorsExt.withInterface())
				.paths(PathSelectors.any()).build();
	}

	static class RequestHandlerSelectorsExt {
		public static Predicate<RequestHandler> withInterface() {
			return new Predicate<RequestHandler>() {
				@Override
				public boolean apply(RequestHandler input) {
					return declaringClass(input) == EndpointMvcAdapter.class;
				}
			};
		}

		private static Class<?> declaringClass(RequestHandler input) {
			return input.getHandlerMethod().getMethod().getDeclaringClass();
		}
	}
}
```

Fome the source codes, seems this is a bug?

**Comment by dilipkrish** [comment]
MvcEndpoints are not supported, However implementing this is just a [plugin away.](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/service/RequestHandlerProvider.java)

**Comment by cloudhuang** [comment]
@dilipkrish Seems the `.apis(RequestHandlerSelectors.any())` will collect all the spring boot actuator endpoints by default, do not need to a customize implementation.

**Comment by dilipkrish** [comment]
Love it when the fix is _no to do anything_

**Comment by cloudhuang** [comment]
@dilipkrish yes, pretty cool. So back to the question, can a `Docket` has multiple `apis()` or only one?

**Comment by dilipkrish** [comment]
It can have only one api call (last one wins) but can have multiple predicates. For e.g. `.apis(Predicates.or(firstApi(), secondApi()`

**Comment by Lovelseh** [comment]
What if I want to select some particular fields of my API ?

**Comment by dilipkrish** [comment]
Can you give an example @Lovelseh? In any case, this is an old issue and you might want to create a new question/issue as it may not be applicable

**Comment by OkieOth** [comment]
I solved a similar problem by defining my own controller annotation and attach it to the classes I want include ...
```
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Component
public @interface ControllerDocumentation {
}
```
to find my documentation classes I used the following code ...
```
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                    .apis(RequestHandlerSelectors.withClassAnnotation(ControllerDocumentation.class))
                    .build()
                .directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
                .directModelSubstitute(java.time.OffsetDateTime.class, java.util.Date.class)
                .apiInfo(apiInfo());
```
