### ISSUE TITLE
Store swagger output in variable

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#1560]
How to store swagger output in variable? I want to do some manipulations on the output.

**Comment by dilipkrish** [comment]
This is not supported. What is it that you want to customize?

**Comment by raderio** [comment]
I want to build something like https://dev.twitter.com/rest/reference/get/followers/list
I need to specify Resource URL.
I need to specify if action requires authentication.
I need to specify "Example Response".

**Comment by dilipkrish** [comment]
I would consider using [swagger2markup](https://github.com/Swagger2Markup/swagger2markup) for that kind of documentation.
