### ISSUE TITLE
Exceptions thrown in TypeNameProviderPlugin#forName are silently dropped

### ISSUE THREAD

**Issue by ircecho** [springfox/springfox#1561]
Exceptions thrown in TypeNameProviderPlugin#forName are silently dropped and then springfox outputs an incomplete swagger document.

Instead, springfox should, deal with the exception properly.

**Comment by dilipkrish** [comment]
Not sure what you mean. Could you illustrate with an example?

**Comment by ircecho** [comment]
I tried to do this:

```java
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class ModelNameBeautifier implements TypeNameProviderPlugin {

    @Override
    public boolean supports(DocumentationType delimiter) {
        return true;
    }

    @Override
    public String nameFor(Class<?> type) {
         // [...]

        String name = type.getSimpleName();

        if (!name.startsWith("Transfer")) {
            // SwaggerException is an unchecked exception.
            throw new SwaggerException("Model class '" + name + "' does not start with 'Transfer'.");
        }

        return name.substring("Transfer".length());
    }
}
```
However, the Exception does not lead to any output, and it does not abort the startup. Instead, some models are silently dropped from the swagger document.

**Comment by dilipkrish** [comment]
You should [see a warning](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/CachingModelProvider.java#L61-L62). However it seems weird to me that you would use the documentation to stop the app server from coming up.

I would recommend a different method to enforce rules around your model types.

**Comment by ircecho** [comment]
You are right. I will of course use a different method now, but I thought it might be a bug, that an incomplete swagger document is put out.
