### ISSUE TITLE
Customize Controller name display on the UI

### ISSUE THREAD

**Issue by opncity** [springfox/springfox#1563]
Hi

I am using springfox-swagger2 version 2.2.2 in my project. My question is how to control the display of the Controller name.

I have a CustomerController, it shows up as follows:

**customer-controller: CustomerController**

I just want to show 'Customer Controller'. I have tried using value, description, tags with different combinations, but somehow I can't get rid of the - in the name, please suggest.

**Comment by dilipkrish** [comment]
You can add an `@Api(tags="Customer Controller")` and it should work as expected. Also please move to the latest version. 2.6.1 will be released over the weekend

**Comment by rtempalli** [comment]
I still see a hyphen in the name after just using the tags @dilipkrish

**Comment by dilipkrish** [comment]
Did you also add a `@Api#description`?

**Comment by dilipkrish** [comment]
But it is the tag description all the same. Maybe make the tag description human readable?

**Comment by frosiere** [comment]
In my opinion, it's more than just a question. It looks impossible to have a human friendly name in the Swagger UI. 

`customer-controller: CustomerController` is really poor from a user point of view and the name looks redundant with the description. 

So, maybe an option to customize (pattern, formatter, etc) or simply remove the name would be useful.

**Comment by dilipkrish** [comment]
@frosiere you can add an annotation to change that. The `@Api` annotation specifically. Also this is a very old issue.

**Comment by jayeshpatel06** [comment]
you can add @Api(tags= {"Customer Management"} ) in the controller and make sure tag value must be with in { }.

**Comment by Fractaliste** [comment]
> Did you also add a `@Api#description`?

Hi, the description attribute has now been deprecated ([see here](https://github.com/swagger-api/swagger-core/blob/1.5/modules/swagger-annotations/src/main/java/io/swagger/annotations/Api.java)), but there is no replacment indication... What should we use now?
