### ISSUE TITLE
Odd @Value behaviour change

### ISSUE THREAD

**Issue by nickcodefresh** [springfox/springfox#1565]
When I upgraded my Spring Boot 1.4.1 project, which uses Spring Cloud Camden.RC1, from springfox 2.5.0 to 2.6.0,  one of the @Value field started misbehaving:

    @Value("${mysql.host:}")
    private String host;

With springfox 2.5.0 the value is set via a Consul Key/Value as expected. With springfox 2.6.0 it's always set to the default, which in this case is an empty string. I'm at a loss to explain why this is the case, but it totally broke my application.

Any ideas what it could be?

Thanks

Nick

**Comment by nickcodefresh** [comment]
Ah, after reading some of the other issues, upgrading to 2.6.1 fixed the issue

**Comment by dilipkrish** [comment]
These are the best kinds of issues :)
