### ISSUE TITLE
Issue with AlternativeTypeRules and generics.

### ISSUE THREAD

**Issue by kevinm416** [springfox/springfox#1567]
Springfox v2.6.1

I've got the following controller setup:

    @RequestMapping(
            value = "/getStuff",
            method = RequestMethod.POST)
    @ResponseBody
    public StringResponse getStuff() {
        return new StringResponse(Optional.of(new RevisionIdentifier<Integer>("abc")));
    }

    public static class StringResponse {
        private final Optional<RevisionIdentifier<Integer>> wrapped;

        @JsonCreator
        public StringResponse(
                @JsonProperty("wrapped") Optional<RevisionIdentifier<Integer>> wrapped) {
            this.wrapped = wrapped;
        }

        public Optional<RevisionIdentifier<Integer>> getWrapped() {
            return wrapped;
        }
    }

    public static class RevisionIdentifier<T> {
        private final String revisionId;

        @JsonCreator
        public RevisionIdentifier(String revisionId) {
            this.revisionId = revisionId;
        }

        @JsonValue
        public String getRevisionId() {
            return revisionId;
        }
    }

With this docket:

                        Contact contact = null;
            final ApiInfo apiInfo = new ApiInfo(
                    null,
                    null,
                    null,
                    null,
                    contact,
                    null,
                    null);
            TypeResolver resolver = new TypeResolver();
            ResolvedType stringType = resolver.resolve(String.class);
            ResolvedType optionalStringWrapper = resolver.resolve(Optional.class, RevisionIdentifier.class);
            return new Docket(DocumentationType.SWAGGER_2)
                    .apiInfo(apiInfo)
                    .genericModelSubstitutes(Optional.class)
                    .alternateTypeRules(
                            new AlternateTypeRule(optionalStringWrapper, stringType));

This produces these definitions:

    "definitions" : {
      "StringResponse" : {
        "type" : "object",
        "properties" : {
          "wrapped" : {
            "$ref" : "#/definitions/RevisionIdentifier«int»"
          }
        }
      },
      "RevisionIdentifier«int»" : {
        "type" : "object"
      }
    }

The json I expect is:

    "definitions" : {
      "StringResponse" : {
        "type" : "object",
        "properties" : {
          "wrapped" : {
            "type" : "string"
          }
        }
      }
    }

This commit: https://github.com/kevinm416/swagger-test/commit/91e7fa666278f21e6242f4da2cf2db0002e5ddf5 provides a minimal, runnable, example of the issue. Please let me know if this is an issue with the way I have things configured or if this is a bug in springfox. Thank you!

**Comment by dilipkrish** [comment]
Replacing the docket with this snippet will fix it

```java
            ResolvedType stringType = resolver.resolve(String.class);
            // Needs to be explicit
            ResolvedType revisionIdentifier = resolver.resolve(RevisionIdentifier.class, Integer.class);
            ResolvedType optionalStringWrapper = resolver.resolve(Optional.class, revisionIdentifier);
            return new Docket(DocumentationType.SWAGGER_2)
                    .apiInfo(apiInfo)
//                    .genericModelSubstitutes(Optional.class) // Not needed
                    .alternateTypeRules(
                            new AlternateTypeRule(optionalStringWrapper, stringType));
```

**Comment by kevinm416** [comment]
Ah, I didn't realize you could pass ``ResolvedType`` back into ``TypeResolver.resolve``.
