### ISSUE TITLE
Springfox-swagger2 : 2.6.0 forced spring @Value annotation to always get default value

### ISSUE THREAD

**Issue by anouarchattouna** [springfox/springfox#1568]
I m working on a REST/JSON API using the following stack:
spring-boot : 1.4.1.RELEASE
springfox-swagger2 : 2.5.0
When I updated springfox-swagger2 to 2.6.0, I've got a strange behavior : the spring **@Value** annotation is always getting the default value of a property even if it exists.
For example, this is always returning "FRA" 
>@Value("${client.country:FRA}")
   private String clientCountry;

even if I have **client.country=SAMPLE** in my properties file.

How to reproduce:

- git clone https://github.com/anouarchattouna/spring-boot-sample-logback-access-swagger.git
- cd spring-boot-sample-logback-access-swagger
- mvn clean install && java -Dspring.profiles.active=dev -jar target/spring-boot-sample-logback-access-swagger-0.0.1-SNAPSHOT.jar
- open the swagger ui : http://localhost:8080/swagger-ui.html and try the GET /api/v1/ping1
- you will get **"SAMPLE"** value for the "country" field of the json response [***OK***]

Now stop the running server, update the swagger version to 2.6.0 from the pom.xml : 
>			
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>2.6.0</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>2.6.0</version>
			</dependency>

- mvn clean install && java -Dspring.profiles.active=dev -jar target/spring-boot-sample-logback-access-swagger-0.0.1-SNAPSHOT.jar
- open the swagger ui : http://localhost:8080/swagger-ui.html and try the GET /api/v1/ping1
- you will get **"FRA"** value for the "country" field of the json response [***KO***]

From the /spring-boot-sample-logback/config/application-dev.properties I have 
>client.country=SAMPLE

And from /spring-boot-sample-logback/src/main/java/org/anotherdev/sample/service/SampleService.java I have
>  @Value("${client.country:FRA}")
     private String clientCountry;

Which is supposed to get the property value or the default one if the property doesn't exist !

Can you please tell me what is going on?

Thank you for your help.

**Comment by dilipkrish** [comment]
Please upgrade to 2.6.1

**Comment by anouarchattouna** [comment]
From where I work, I can only use artifacts from maven central which doesn't contain yet the 2.6.1 : 
https://mvnrepository.com/artifact/io.springfox/springfox-swagger2

**Comment by dilipkrish** [comment]
That may not be the [best place](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22springfox-swagger2%22) to look for it

**Comment by anouarchattouna** [comment]
Thank you, now it is working.
But it would be better to know what was the problem with that 2.6.0 version.

**Comment by dilipkrish** [comment]
@anouarchattouna https://github.com/springfox/springfox/releases/tag/2.6.1
