### ISSUE TITLE
Security ApiKey "keyname" does nothing

### ISSUE THREAD

**Issue by jmattheis** [springfox/springfox#1569]
Version: 2.6.0

I'm trying to add the securityDefinitions to the swagger generation. 
I'm using the apiKey in which it is possible to specify the ``name``, ``keyname`` and ``passAs``.
For me ``keyname`` is the value of the header-key in which the auth token should be set.
But the keyname has no effect on the generated end result, it just does nothing:

```
List<SecurityScheme>    SECURITY_SCHEMES    = asList(new ApiKey("nameApi", "keyNameApi", "header"));
List<SecurityReference> SECURITY_REFERENCES = asList(SecurityReference.builder().reference("nameApi").scopes(new AuthorizationScope[0]).build());
List<SecurityContext>   SECURITY_CONTEXTS   = asList(SecurityContext.builder().forPaths(PathSelectors.any()).securityReferences(SECURITY_REFERENCES).build());

new Docket().securityContexts(SECURITY_CONTEXTS).securitySchemes(SECURITY_SCHEMES)..
```
Currently this goes to:
```
"securityDefinitions": {
    "nameApi": {
      "type": "apiKey",
      "name": "nameApi",
      "in": "header"
    }
},
```
I expect it to be:
```
"securityDefinitions": {
    "nameApi": {
        "type": "apiKey",
        "name": "keyNameApi",
        "in": "header"
    }
},
```

**Comment by dilipkrish** [comment]
Please upgrade to the latest stable version 2.6.1. Old versions are not supported.

**Comment by jmattheis** [comment]
There error is still present in 2.6.1.

**Comment by dilipkrish** [comment]
Hmm thats a good catch... wonder why no one reported it. Perhaps change the value of name to keyName. I'll add a chore to deprecate the constructor

**Comment by jmattheis** [comment]
> Perhaps change the value of name to keyName. 

Yes currently I'm doing somethings similar, which is:

    new ApiKey(HttpHeaders.AUTHORIZATION, "currently not used", "header")
the "name" then goes to `Authorization` which is not very nice because it starts with an upper A, but this also change the "keyName" to `Authorization` which is needed that swagger knows to put the value of the apiKey inside the `Authorization`-header.

**Comment by rakeshgoelrg** [comment]
Hi,
When would the fix for this be available? I am also facing this issue.

**Comment by dilipkrish** [comment]
Hopefully first half of Feb.

**Comment by Vanderhoof** [comment]
Did you decide against fixing this?
In 3.0.0 `keyname` is still ignored.

**Comment by twerszko** [comment]
As mentioned by @Vanderhoof. It stopped working when switched from `DocumentationType.SWAGGER_2` to `DocumentationType.OAS_30`
