### ISSUE TITLE
Support for Response examples

### ISSUE THREAD

**Issue by KinOSurvival** [springfox/springfox#1570]
Any plans to support http://swagger.io/specification/#exampleObject?

I trace down to ResponseMessage.java, and found out that it doesn't have "example" property.

This close down my own plugin, trying to insert response samples(after parsing my own annotations)

I would love to have some suggestions on this. Thanks a lot.

**Comment by dilipkrish** [comment]
Its simple enough to add it. Would you like to try your had at submitting a PR?

**Comment by KinOSurvival** [comment]
yes, just one quick question:
@ApiResponse in swagger-annotation.jar is used to donate the Swagger Response, but it doesn't include examples right now. I guess we have to use our own annotation, and which annotation should I use?

**Comment by dilipkrish** [comment]
@KinOSurvival gaah! that can be a problem. You could mint your own @Example annotation.

**Comment by blvp** [comment]
there is some pitfalls with original annotation it is not required to set media type for example property. 
```java
@RequestMapping(consumes="application/json")
public void doSmth(
    @ApiParam(examples=@Example({@ExampleProperty("{\"test\":\"val\"}")})) TestVal testVal
) {}
```
Ignore it or extract Consumes from OperationContext?
And what to do when we have several ExampleProperty without mediaType or we have one ExampleProperty with several consumes? Like so:
```java
@RequestMapping(consumes={"application/json", "application/xml"})
public void doSmth(
    @ApiParam(examples=@Example({@ExampleProperty("{\"test\":\"val\"}")})) TestVal testVal
) {}
```
or 
```java
@RequestMapping(consumes={"application/json")
public void doSmth(
    @ApiParam(examples=@Example({
                @ExampleProperty("{\"test\":\"val\"}"),
                @ExampleProperty("<test>val</test>")
           })
    ) 
            TestVal testVal
) {}
```
I know that last  2 cases are least possible, but we must define some default logic for it like skipping or try to parse examples with defined consumes. 
By default we know if we have one consumes and one example it surely with consumes media type.

**Comment by dilipkrish** [comment]
@blvp Yeah I agree. My personal opinion is that the swagger annotations are the ***manual knobs*** and tweaks to get the specification just right. They are a last resort for when the spring annotations do not describe enough for e.g. descriptions etc. So at that point Im cool with experimentation on the consumers part to set the right media types on the example.

**Comment by quickwind** [comment]
When will this be added?

**Comment by dilipkrish** [comment]
When someone can help with a PR. I don't have the bandwidth to work on this, thats why its marked as `looking-for-contributions`

**Comment by Q1nt** [comment]
Hi @dilipkrish, I would love to have this feature or at least some extension point for response examples.

What do you think if I'll add new `Map<String, Object>` examples property to the `ResponseMessage`, so we could add our own examples via plugins?
