### ISSUE TITLE
2.6.1 Cannot read property of custom enum list

### ISSUE THREAD

**Issue by jearton** [springfox/springfox#1571]
Custom enum like this:
```
@Getter
@AllArgsConstructor
public enum AccountType {
    CASH("现金账户", 2),
    BANK("银行账户", 3);

    private String name;
    private int code;
}
```

Pojo like this:
```
@Data
public class AccountQuery {
    @ApiParam(value = "账户号类型，支持多值", allowMultiple = true)
    private List<AccountType> type;
}
```

Controller method like this:
```
    @RequestMapping(value = "/account", method = GET)
    @ApiOperation(value = "查询账户", notes = "分页查询")
    JsonResult getPage(@ModelAttribute AccountQuery query) {
        return ok();
    }
```

Then the html page does not show the property 'type', I can not figure out why.

I found that ExpandedParameterBuilder#apply skiped this property.

**Comment by dilipkrish** [comment]
add a `@Setter` annotation to account type and everything should be fine. This is a requirement by springfox to simplify model attribute evaluation

**Comment by jearton** [comment]
Er……It doesn't seem to work.
**First, I add a @Setter annotation to the class like this:**
```
@Setter
@Getter
@AllArgsConstructor
public enum AccountType {
    CASH("现金账户", 2),
    BANK("银行账户", 3);

    private String name;
    private int code;
}
```
It will cause a compile error.

**Then, I add setter manually, like this:**
```
@Getter
@AllArgsConstructor
public enum AccountType {
    CASH("现金账户", 2),
    BANK("银行账户", 3);

    private String name;
    private int code;

    public void setName(String name) {
        this.name = name;
    }

    public void setCode(int code) {
        this.code = code;
    }
}
```
The ui shows  "type[0].code" and "type[0].name" as the parameters,  and not multiple values, which is out of my expectation.

**I want the ui to display that parameter is "type", and value is a textarea with the placeholder of "Provide multiple values in new lines."**

**Comment by jearton** [comment]
I remember the version 2.5.x can display what I expected.

**Comment by jearton** [comment]
I pushed my code to https://git.coding.net/jearton/springfox-demos.git

**Comment by dilipkrish** [comment]
@jearton Sorry I haven't had ⏲to get to it. With the holidays it might be a couple of weeks.
