### ISSUE TITLE
Is it possible to ignore at Docket initialization specific methods/endpoints from actuator?

### ISSUE THREAD

**Issue by rwanderc** [springfox/springfox#1578]
I'm interested in ignoring all /health endpoints but the GET /health.
Is it possible to exclude specific methods from the documentation?

From the example bellow, I'm ignoring all /health.json endpoints from /health, but I still want to ignore:
DELETE /health
HEAD /health
OPTIONS /health
PATCH /health
POST /health
PUT /health

    @Bean
    public Docket swaggerSettings() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(any())
                .paths(not(regex("/error")))
                .paths(not(regex("/health.json")))
                .build();
    }

**Comment by dilipkrish** [comment]
This is currently not possible unfortunately. I believe there is an issue for this already
