### ISSUE TITLE
2.6.0, 2.6.1: ParameterContext given to ParameterBuilderPlugin#apply loses type information if type in Controller method is unannotated

### ISSUE THREAD

**Issue by 9numbernine9** [springfox/springfox#1579]
- Affects Springfox 2.6.0 and 2.6.1
- This issue is strongly related to the `PageableParameterBuilderPlugin` that is described in #755.

Consider the following trivial REST controller:

```java
@RestController
public static class TestRestController
{
    @RequestMapping(method = GET, value = "/pageable")
    public String getPageable(Pageable pageable)
    {
        return "The pageable.";
    }
}
```

Now, also assume that you wish to write an implementation of `ParameterBuilderPlugin` that will do something when it encounters a `Pageable` parameter, such as this trivial implementation:

```java
public class TrivialParameterBuilderPlugin implements ParameterBuilderPlugin
{
    @Override
    public boolean supports(DocumentationType delimiter)
    {
        return true;
    }

    @Override
    public void apply(ParameterContext parameterContext)
    {
        if (Pageable.class.isAssignableFrom(parameterContext.resolvedMethodParameter().getParameterType().getErasedType())
        {
            System.err.println("Pageable received!");
        }
    }
}
```
In Springfox < 2.6.0, given the above setup, when `ParameterBuilderPlugin#apply` is invoked, the value returned by `#getErasedType` will be a `Pageable` as expected. In Springfox >= 2.6.0, however, `#getErasedType` will return a `String` and thus prevent the `if` block from being executed.

I think the changes in dde6f4129c2a159bff38f6b9eac03522560023c0 (PR #1444) might be responsible for the change in behaviour with `Pageable` (and other types). Previously, `OptionalParameterReader#shouldExpand` would return `false` when looking at a `Pageable` parameter, which would cause the `parameters.add(pluginsManager.parameter(parameterContext))` line to get executed and trigger the correct evaluation of our `ParameterBuilderPlugin` with a `Pageable` parameter. Since dde6f4129c2a159bff38f6b9eac03522560023c0 , however, `shouldExpand` now returns `true` and the plugin doesn't get called correctly.

Ideally, I would think it would be good if it were possible to _both_ expand any types in a controller method's parameter list _and_ invoke any registered `ParameterBuilderPlugin`s with the type(s) used in the controller method's signature.

**Comment by dilipkrish** [comment]
Its a little awkward this one... need to think about how to handle this long term, but at this point I can offer a work around.
- Create a mixin class class called `PagableMixin.class` with getters/setters for the properties you care to document about
- Annotate you method with @ModelAttribute which will signal to springfox that this expands to request params.
