### ISSUE TITLE
Can't expand the operation when I set @Api tags by chinese

### ISSUE THREAD

**Issue by letorn** [springfox/springfox#1580]
In past version, I can set value and  description of annotation Api to remark the controller, but In the version 2.6.1, it's changed, adding tags instead of value(value is not used).
First, I set tags by chinese, I can't expand the operation on the swagger-ui.html. 
Second, the description is Deprecated, Why?anything Instead of it?

**Comment by ouyangyaxiong** [comment]
swagger-ui的js bug，要展开的内容的id被encode了
![image](https://cloud.githubusercontent.com/assets/13805316/20865466/fe5c80de-ba4d-11e6-8a47-b8152894ee68.png)

**Comment by dilipkrish** [comment]
@letorn this is a known bug in swagger-ui. I think you should probably bring it up in that project. The description is deprecated by the swagger-core project. They don't use it anymore. I don't think there is anything to use instead.

**Comment by letorn** [comment]
@ouyangyaxiong 你截图中的数据在哪看？

**Comment by letorn** [comment]
@dilipkrish ok, I will.

**Comment by ouyangyaxiong** [comment]
f12打开开发者工具，查看源码

**Comment by letorn** [comment]
好的
