### ISSUE TITLE
Path w/ params does not generate parameters section for the OPTIONS operation

### ISSUE THREAD

**Issue by saturnism** [springfox/springfox#1584]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? io.springfox:springfox-swagger2:2.6.1

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [x] spring xml/java config that is relevant
    - [x] springfox specific configuration if it makes sense
    - [x] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Bug Report:
Using springfox-swagger2 + springfox-data-rest + spring-boot-starter-data-rest

Created a simple `Movie` entity with `id`, `name`, and `description` fields

```
@Entity
@Data
public class Movie {
  @Id
  @GeneratedValue
  private Long id;
  private String name;
  private String description;
}
```

Expose as CRUD service w/ Spring Data Rest:
```
@RepositoryRestResource
public interface MoviesRepository extends PagingAndSortingRepository<Movie, Long>{
}
```

Configure Springfox:
```
public Docket api() {
  return new Docket(DocumentationType.SWAGGER_2)
    .select()
    .apis(RequestHandlerSelectors.withClassAnnotation(RepositoryRestController.class))
      .paths(PathSelectors.any())
      .build()
      .host(host)
      .apiInfo(new ApiInfoBuilder()
        .description("Movies REST API")
        .title("Movies")
        .version(version)
        .build());
}
```

The generated Swagger JSON seems mostly complete, except for the OPTION method, where the path is `id` parameter, but the the generated Swagger JSON is missing the `parameters` section.  All other verbs has the `parameters` section.

```
"paths": {
...
        "/movies/{id}": {
            ...
            "options": {
                "consumes": [
                    "application/json"
                ], 
                "operationId": "optionsForItemResourceUsingOPTIONS", 
                "produces": [
                    "application/*+json;charset=UTF-8", 
                    "application/json", 
                    "application/hal+json"
                ], 
                "responses": {
                    "200": {
                        "description": "OK"
                    }, 
                    "204": {
                        "description": "No Content"
                    }, 
                    "401": {
                        "description": "Unauthorized"
                    }, 
                    "403": {
                        "description": "Forbidden"
                    }
                }, 
                "summary": "optionsForItemResource", 
                "tags": [
                    "Movie Entity"
                ]
            }, 
...
```

**Comment by dilipkrish** [comment]
@saturnism this may be a bug. Thanks for the detailed bug report! and also the first one related to spring-data-rest :)

**Comment by saturnism** [comment]
Let me know how i can help. I'd like to use this pretty soon!

**Comment by dilipkrish** [comment]
Its fairly simple I believe. Since yr familiar, could you help with a PR?

**Comment by saturnism** [comment]
I'm trying - but it's a bit hard to figure out where the params is to be or isn't being generated :)

**Comment by saturnism** [comment]
quick ping @dilipkrish for pointers

**Comment by dilipkrish** [comment]
I thought I did...sorry haven't had time recently. Let me write that up. Thanks for the reminder

**Comment by saturnism** [comment]
I'd love to demo this as well. Only blocked on the validation. Much appreciate it!

**Comment by dilipkrish** [comment]
I finally got to this question. In this situation the id parameter is kind of weird. Really what this operation is trying to do is given an operation with an endpoint`/movies/{id}` give me all the `OPTIONS` available. So there is no parameter in this particular case. Hope that makes sense.

**Comment by saturnism** [comment]
Thanks @dilipkrish for taking a look. It doesn't pass the spec though :( It should still have the parameter listed like the GET operation.

**Comment by dilipkrish** [comment]
As I mentioned in the gitter channel.

> I understand. But that may be an oversight. Really what you are doing with the options method is asking the service for some metadata for the path `http://example.org/{path`}. Just like Java reflection if u will. You never have parameter values when u ask for method definition.

**Comment by saturnism** [comment]
But that's not what's defined in the swagger doc. In which case, the defined swagger doc shouldn't have path parameter in it?

I'd love to fix this up if only I can get a slight help on navigating the code as far as where the actual generation occurs, and also where the metadata/internal structure are collected

would much appreciate it!

**Comment by saturnism** [comment]
Ping @dilipkrish

**Comment by dilipkrish** [comment]
This should be fixed. In the sense that t has been reworked in 2.7.0 and we don't expose all the meta endpoints any more.

**Comment by saturnism** [comment]
Oh cool! Thanks!!
