### ISSUE TITLE
How to configure basePath according to project?

### ISSUE THREAD

**Issue by hemaRamesh** [springfox/springfox#1586]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 
How to configure basePath according to my project?
 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by dilipkrish** [comment]
You can have a using the `Docket#pathMapping` to adjust the base path

**Comment by barmic** [comment]
This solution don't work if you use a reverse proxy.
The UI can't choose the URL from current URL ?

**Comment by dilipkrish** [comment]
@barmic would be able to help getting it to work with the reverse proxy? There are a few problems reported and without having something to test it with it becomes difficult to provide a solution. Would be great if you could help with a PR that works for regular services and with reverse proxy.

**Comment by barmic** [comment]
I think it's possible :) Can I see list of issues about it ?
