### ISSUE TITLE
/v2/api-docs not coming up

### ISSUE THREAD

**Issue by webkitez** [springfox/springfox#1595]
I am using gradle build for 

```gradle
compile ("io.springfox:springfox-swagger-ui:2.6.1")
compile ("io.springfox:springfox-swagger2:2.6.1")
```

My spring server logs says swagger has been mapped correctly to v2/api-docs

```log
[2016-12-02 00:25:44,649] [] [localhost-startStop-1] [INFO] [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] - Mapped "{[/v2/api-docs],methods=[GET],produces=[application/json || application/hal+json]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)
[2016-12-02 00:25:44,653] [] [localhost-startStop-1] [INFO] [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] - Mapped "{[/swagger-resources/configuration/ui]}" onto org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.UiConfiguration> springfox.documentation.swagger.web.ApiResourceController.uiConfiguration()
[2016-12-02 00:25:44,653] [] [localhost-startStop-1] [INFO] [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] - Mapped "{[/swagger-resources/configuration/security]}" onto org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.SecurityConfiguration> springfox.documentation.swagger.web.ApiResourceController.securityConfiguration()
[2016-12-02 00:25:44,654] [] [localhost-startStop-1] [INFO] [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] - Mapped "{[/swagger-resources]}" onto org.springframework.http.ResponseEntity<java.util.List<springfox.documentation.swagger.web.SwaggerResource>> springfox.documentation.swagger.web.ApiResourceController.swaggerResources()
```

But when i try to visit
`localhost:8080/rootpath/v2/api-docs` I get not found however swagger ui is coming up on 

My Sprinfox configuration file is

@EnableSwagger2
@Configuration
@EnableWebMvc
@ComponentScan("org.jasig.cas.support.snapdeal")
public class SwaggerConfig {

	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).groupName("leads")
                .apiInfo(apiInfo()).select().apis(RequestHandlerSelectors.basePackage("org.jasig.cas.support.snapdeal.resource"))
				.paths(PathSelectors.ant("/v1")).build();
	}

**Comment by webkitez** [comment]
![screen shot 2016-12-02 at 12 39 17 am](https://cloud.githubusercontent.com/assets/22659755/20808217/cbb9df6e-b827-11e6-8d61-d39fc11cac03.png)

**Comment by dilipkrish** [comment]
Going by your logs, it appears your resources should be available @ `/cas-server/v2/api-docs`, where `cas-server` is your web context root

**Comment by awoods12** [comment]
Hi, I'm also getting a 404 when trying to connect to /v2/api-docs. My logs show a mapping for the endpoint, but I cannot visit it. 

It seems the problem may be that I cannot find the correct web context root. The project I am working on is organized as raptor-webservice/src/main/...... so I think the default should be raptor-webservice, but localhost:8080/raptor-webservice/v2/api-docs gives me a 404 error as well.

Other endpoints do not require the web context root before the path as well. For example, I have 'RequestMappingHandlerMapping:220 - Mapped "{[/jobs/pm/submit' and this can be visited with localhost:8080/jobs/pm/submit. So this leads me to believe that 'RequestMappingHandlerMapping:220 - Mapped "{[/v2/api-docs]' should make localhost:8080/v2/api-docs available, but as I said before that gives me a 404.

So, I'm just wondering if you might be able to tell me if I need some we context root in that path and if I do, I was wondering if you could tell me how I could figure out what that root is because I have been searching for a way to view it and haven't had any luck.

Thanks.

**Comment by wxjlibra** [comment]
i use the very same version 2.6.1 also and found that host:port/{appname}/v2/api-docs could not be visited also. very confused.

**Comment by dilipkrish** [comment]
@wxjlibra There is a whole lot of configuration that Im sure you're doing. Without knowing that its hard to help

**Comment by sarangajay** [comment]
I have the same issue and get not found for v2/api-docs.
i am using version: '2.9.2'.

springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping   - initialising the handler methods
09:08:04,930 INFO  springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping   - Mapped URL path [/v2/api-docs] onto method 
[public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]

springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper   - Context refreshed
09:08:12,831 INFO  springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper   - Found 1 custom documentation plugin(s)
09:08:12,908 DEBUG springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner   - Total number of request handlers 4
09:08:12,909 DEBUG springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner   - Adding key: [/mc/resource/filenames/{projectId}], WebMvcRequestHandler{key=RequestHandlerKey{pathMappings=[/mc/resource/filenames/{projectId}], supportedMethods=[GET], supportedMediaTypes=[application/json], producibleMediaTypes=[application/json]}}
09:08:12,915 DEBUG springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner   - Adding key: [/swagger-resources/configuration/security], WebMvcRequestHandler{key=RequestHandlerKey{pathMappings=[/swagger-resources/configuration/security], supportedMethods=[], supportedMediaTypes=[], producibleMediaTypes=[]}}
09:08:12,915 DEBUG springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner   - Adding key: [/swagger-resources/configuration/ui], WebMvcRequestHandler{key=RequestHandlerKey{pathMappings=[/swagger-resources/configuration/ui], supportedMethods=[], supportedMediaTypes=[], producibleMediaTypes=[]}}
09:08:12,915 DEBUG springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner   - Adding key: [/swagger-resources], WebMvcRequestHandler{key=RequestHandlerKey{pathMappings=[/swagger-resources], supportedMethods=[], supportedMediaTypes=[], producibleMediaTypes=[]}}
09:08:12,924 DEBUG springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner   - Combined number of request handlers 4
09:08:12,926 INFO  springfox.documentation.spring.web.scanners.ApiListingReferenceScanner   - Scanning for api listing references
09:08:13,029 DEBUG springfox.documentation.spring.web.readers.operation.OperationModelsProvider   - Adding return parameter of type Ljava/util/List<Ljava/lang/String;>;
09:08:13,032 DEBUG springfox.documentation.spring.web.readers.operation.OperationModelsProvider   - Reading parameters models for handlerMethod |getResourceFileNames|
09:08:13,043 DEBUG springfox.documentation.spring.web.readers.operation.OperationModelsProvider   - Finished reading parameters models for handlerMethod |getResourceFileNames|
09:08:13,050 DEBUG springfox.documentation.swagger.readers.operation.SwaggerOperationModelsProvider   - Reading parameters models for handlerMethod |getResourceFileNames|
09:08:13,088 DEBUG springfox.documentation.schema.DefaultModelProvider   - Skipping model of type Ljava/util/List<Ljava/lang/String;>; as its either a container type, map, enum or base type, or its already been handled
09:08:13,098 DEBUG springfox.documentation.spring.web.scanners.ApiModelReader   - Did not find any parameter models for java.util.List<java.lang.String>
09:08:13,103 DEBUG springfox.documentation.schema.DefaultModelDependencyProvider   - Adding type for parameter Ljava/lang/String;
09:08:13,103 DEBUG springfox.documentation.schema.DefaultModelDependencyProvider   - Recursively resolving dependencies for parameter Ljava/lang/String;
09:08:13,104 DEBUG springfox.documentation.schema.DefaultModelDependencyProvider   - Marking base type Ljava/lang/String; as seen
09:08:13,214 DEBUG springfox.documentation.spring.web.readers.operation.OperationResponseClassReader   - Setting spring response class to: List
09:08:13,215 DEBUG springfox.documentation.swagger.readers.operation.SwaggerOperationResponseClassReader   - Setting response class to:List
09:08:13,219 DEBUG springfox.documentation.swagger.readers.operation.OperationAuthReader   - Authorization count 0 for method getResourceFileNames

**Comment by praveenambati1233** [comment]
I too have a same issue , what I observed is spring boot is not initiated maps for swagger-ui.html resources

**Comment by BinmingWen** [comment]
so，do you how to solve it.
