### ISSUE TITLE
lssues of generic type in apimodel

### ISSUE THREAD

**Issue by donald2008** [springfox/springfox#1596]
I'm using springfox-swagger2 , version 2.6.1.

Here is a sample:
```
@ApiModel(description = "this is a result")
public class PageResult<T> {

	@ApiParam(hidden = true)
	private List<T> list;
	private int pageNo = 1;
	@ApiParam(hidden = true)
	private int pageCount;
	
	//getters and setters
}
```

and here is a spring-mvc http request:

```
        @PostMapping("/testModelT")
	@ApiOperation("/TestModel")
	public PageResult<Cat> createResultCat(@ModelAttribute PageResult<Cat> result) {
		List<Cat> list = new LinkedList<Cat>();
		list.add(new Cat("kitty", 1));
		result.setList(list);
		return result;
```
Maybe I hide two param (list and pageCount) . Infact pageCount is hidden but list is not.
![qq 20161205182645](https://cloud.githubusercontent.com/assets/22805597/20881667/68a9b22a-bb18-11e6-8d73-e22766f23260.png)

**Comment by dilipkrish** [comment]
Model attributes don't support generics as of 2.6.1. Also as long as the `PagedResult` doesnt have getter/setter pairs the property will be ignored.
