### ISSUE TITLE
 ApiModelProperty(name="property_name") on @ModelAttribute annotated models

### ISSUE THREAD

**Issue by dekan-kob** [springfox/springfox#1598]
Controller:

```
@ResponseBody
@RequestMapping(value="articles", method=RequestMethod.POST, produces = "application/json; charset=UTF-8")
public String getArticles(HttpServletRequest request, @ModelAttribute FilterParameters filterParameters){}
```

```
@JsonNaming(value = PropertyNamingStrategy.SnakeCaseStrategy.class)
public class FilterParameters {

    @ApiModelProperty(name = "start_millis")
    private Long startMillis;

    public FilterParameters() {
    }

    public Long getStartMillis() {
        return startMillis;
    }

    public void setStartMillis(Long startMillis) {
        this.startMillis = startMillis;
    }
}
```

On swagger-ui.html, parametr name is "startMillis". Why isn't "start_millis"?

**Comment by dilipkrish** [comment]
@ApiModelProperty [doesnt affect name](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/SwaggerExpandedParameterBuilder.java#L82-L92). May be it should?

**Comment by dekan-kob** [comment]
Yes.
When I use @JsonNaming(value = PropertyNamingStrategy.SnakeCaseStrategy.class) in ApiModel class, then the names of the parameters are changed.

**My model:**
```
@JsonNaming(value = PropertyNamingStrategy.SnakeCaseStrategy.class)
public class FilterParameters {
    private Long startMillis;

    public Long getStartMillis() {
        return startMillis;
    }

    public void setStartMillis(Long startMillis) {
        this.startMillis = startMillis;
    }
}
```


```
@ResponseBody
@RequestMapping(value="articles", method=RequestMethod.POST, produces = "application/json; charset=UTF-8")
public String getArticles(HttpServletRequest request, @RequestBody FilterParameters filterParameters){}
```
_Here i use **@RequestBody** annotation, so the name of the parameter is "start_millis" in swagger-ui.html._


But when i use @ModelAttribute, @JsonNaming not working.
```
@ResponseBody
@RequestMapping(value="articles", method=RequestMethod.POST, produces = "application/json; charset=UTF-8")
public String getArticles(HttpServletRequest request, @ModelAttribute FilterParameters filterParameters){}
```
_Here i use **@ModelAttribute**  annotation, so  the name of the parameter is "startMillis" in swagger-ui.html._

I tried to change the name of the parameter using "name" in @ApiModelProperty annotation. But it's not working. What do I do?

**Comment by dilipkrish** [comment]
@dekan-kob Not convinced that `@JsonNaming` and `@ApiModelProperty` should be allowed to override the property name. Could you check by curling with snake cased property names to see if `@JsonNaming` has any effect @ runtime? I would be surprised if it did, I think model attributes are based on java bean specification.

**Comment by dekan-kob** [comment]
Yes, @JsonNaming change the names of the parameters. 
I have created two classes:
```
public class TestClassWithoutJsonNaming {
    private String propertyName;

    public String getPropertyName() {
        return propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }
}
```
and
```
@JsonNaming(value = PropertyNamingStrategy.SnakeCaseStrategy.class)
public class TestClassWithJsonNaming {
    private String propertyName;

    public String getPropertyName() {
        return propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }
}
```
Also, i have created two methods in controller:

```
@ApiOperation(value = "test1")
@RequestMapping(value = "/api/v3/test1", method = RequestMethod.POST)
public TestClassWithoutJsonNaming test1(HttpServletRequest request) {
    return null;
}

@ApiOperation(value = "test2")
@RequestMapping(value = "/api/v3/test2", method = RequestMethod.POST)
public TestClassWithJsonNaming test2(HttpServletRequest request) {
    return null;
}
```

After application starting, I get the following:
![test1](https://cloud.githubusercontent.com/assets/7036804/21032128/17c7f802-bdf3-11e6-941f-2b973a61ea92.PNG)
![test2](https://cloud.githubusercontent.com/assets/7036804/21032129/1a493ad2-bdf3-11e6-9106-90762d30ef04.PNG)

It's very good for me. But i have problems when using @ModelAttribute.

**Comment by dilipkrish** [comment]
This has nothing to do with springfox/swagger. I was actually suggesting you do the following instead

```
@RequestMapping(value = "/api/v3/test1", method = RequestMethod.POST)
public void test1(@ModelAttribute TestClassWithoutJsonNaming request) {
    return null;
}

@RequestMapping(value = "/api/v3/test2", method = RequestMethod.POST)
public void test2(@ModelAttribute TestClassWithJsonNaming request) {
    return null;
}
```

Then doing a curl 

```bash
curl http://host/api/v3/test2?property_name=test
```

and seeing if spring creates a model correctly with the value test. I suspect it will not

**Comment by dekan-kob** [comment]
You are right. It doesn't work. Thanks for the help. I will continue to investigate with the ModelAttribute.
