### ISSUE TITLE
docket "host" not work?

### ISSUE THREAD

**Issue by steventong** [springfox/springfox#1599]
version 2.6.1

I have two docket with different "host", but the swagger-ui.html always explore the same api-docs.

I have three microservice projects, A-service is swagger-ui service with port 8080, B-service is web-api-service with port 8081, C-service is mobile-api-service with port 8082.

A-service have two docket method like:

`  @Bean
    public Docket createWebRestApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .host("http://localhost:8081");
    }`

`  @Bean
    public Docket createMobileRestApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .host("http://localhost:8082");
    }`

but swagger-ui.html always explore http://localhost:8080/api-docs?group-name=xxxx

**Comment by dilipkrish** [comment]
The bundled swagger-ui will not support multiple hosts

**Comment by dilipkrish** [comment]
Take a look at [jhipster](https://jhipster.github.io) for how to support multihost aggregation.

**Comment by steventong** [comment]
OK

**Comment by steventong** [comment]
`
@RequestMapping
@RestController
public class SwaggerController {

    @RequestMapping(value = "/swagger-resources", method = RequestMethod.GET)
    public List<SwaggerResourceModel> swaggerResource() {
        List<SwaggerResourceModel> models = new ArrayList<>();
        models.add(new SwaggerResourceModel("Web Api", "/web/v2/api-docs?group=web-api", "2.0"));
        models.add(new SwaggerResourceModel("Mobile Api", "/mobile/v2/api-docs?group=mobile-api", "2.0"));
        return models;
    }
}
`

then I can use two swagger api doc at one swagger-ui.html
