### ISSUE TITLE
JRebel class reloading

### ISSUE THREAD

**Issue by ingeniak** [springfox/springfox#1600]
Really liking swagger and began using it last week. I however noticed that I am unable to see changes in the json that is generated when I make changes in my class models and my spring methods that JRebel reloads. It appears that Swagger caches all of the documentation and does not refresh unless the module is reloaded.

I am still waiting for an answer from ZeroTurnaround on this to see why I am not seeing changes in Swagger.

How would I force the documentation cache to be reset so that it picks up the latest changes in my models and spring mvc definitions?

Thank you in advance.

**Comment by dilipkrish** [comment]
There is a [guard](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/DocumentationPluginsBootstrapper.java#L119-L133) to prevent reloading the documentation as an optimization. I doubt JRebel would be able to signal to the bootstrapper that something relevant has changed. It is out of scope for this project, but if you have a solution/suggestion, would be happy to consider.

**Comment by ingeniak** [comment]
Sorry I missed this. Thank you for responding. Been a busy month.

Perhaps a function to reload or re-read the annotations. Or the documentation is not built until this method is executed. From there there could be a synchronized object that is locked or watched. As long as it is null, documentation states cached. When Jrebel reloads a class, the object would be null and therefore cause the annotations to be reloaded.

As of now, I've had to use pure swagger and a different plugin to build a Json file built during the package phase. It's a few more annotations, but with such a large API like ours, it's our only choice.

Thanks,

Myron L Stewart
CEO/Founder | Ingeniak
http://ingeniak.com
http://www.linkedin.com/company/ingeniak
Twitter: @IngeniakMyron
Skype: ingeniak
Mobile: 1.704.340.5630

Sent from my mobile

_____________________________

**Comment by dilipkrish** [comment]
@ingeniak The documentation bootstrapper [participates](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/DocumentationPluginsBootstrapper.java#L137-L140) in spring's [`SmartLifeCycle`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/SmartLifecycle.html), so if/when you see appropriate you could call [the stop](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/DocumentationPluginsBootstrapper.java#L137-L140) and thats the supported way of resetting the cache.

I'm not sure how you'd do that with JRebel.

**Comment by ingeniak** [comment]
Interesting. I might try that out and/or pass that info to ZeroTurnaround.

Myron L Stewart
CEO/Founder | Ingeniak
http://www.ingeniak.com<http://www.ingeniak.com/>
http://www.linkedin.com/company/ingeniak<http://www.linkedin.com/in/ingeniak>
Twitter: @IngeniakMyron
Twitter: @Ingeniak
Skype: ingeniak
Office: 1.980.272.8264
Mobile: 1.704.340.5630

**Comment by ingeniak** [comment]
Wanted to thank you again for your info.

I had a little time on my hand to try out what you mentioned. I did the following in my api controller

@Autowired
private ApplicationContext appContext;

@Autowired
DocumentationPluginsBootstrapper documentationPluginsBootstrapper;

Then in one of my request methods, I stop the bean and start it again. I had to do a little research to understand the SmartLifecycle of Spring components.
documentationPluginsBootstrapper.stop();
documentationPluginsBootstrapper.start();

I simply need a smart method of telling when JRebel has reloaded a class which will in turn only stop and start and stop the bean when needed.

I’m going to pass this information to the JRebel as they might automatically implement it.

Thanks,

Myron L Stewart
CEO/Founder | Ingeniak
http://www.ingeniak.com<http://www.ingeniak.com/>
http://www.linkedin.com/company/ingeniak<http://www.linkedin.com/in/ingeniak>
Twitter: @IngeniakMyron
Twitter: @Ingeniak
Skype: ingeniak
Office: 1.980.272.8264
Mobile: 1.704.340.5630

**Comment by dilipkrish** [comment]
@ingeniak excellent! Let me know when JRebel gets back to you.

**Comment by ingeniak** [comment]
Will do. For now, I have my system IngenoGears allow a command line option of devMode=true. With that option, the plugin is reload each time the APIDoc rest controller loads.

Thanks,

Myron L Stewart
CEO/Founder | Ingeniak
http://ingeniak.com
http://www.linkedin.com/company/ingeniak
Twitter: @IngeniakMyron
Skype: ingeniak
Mobile: 1.704.340.5630

Sent from my mobile

________________________________

**Comment by jkeruzec** [comment]
Thanks, much appreciate it.
I used this to secure Swagger API associated with (as spring security is not yet impleted) : 
Get PluginRegistry 
`@Autowired
 @Qualifier("documentationPluginRegistry")
 private PluginRegistry<DocumentationPlugin, DocumentationType> documentationPlugins;`

and then disable/enable required plugin 
`((springfox.documentation.spring.web.plugins.Docket) documentationPlugins.getPlugins().get(0)).enable(false);`

Stop/Start conf : 
`springSwaggerConfig.stop();springSwaggerConfig.start()`
