### ISSUE TITLE
Generate json file from docs using springfox

### ISSUE THREAD

**Issue by sac10nikam** [springfox/springfox#1601]
**Goal: Generate json file from docs using springfox**

1) I don't want to use any third editor
2) I have looked at couple of solutions like 
a) http://host:port/root/v2/docs
It gives me raw json file. I don't want this.

b) swagger-maven-plugin. Tried it plugin in pom but it didn't work for me.

etc

Is there any easy way to do it using springfox API or any other way?

**Comment by dilipkrish** [comment]
Don't know what you're asking. Json file from docs? What does that mean?

**Comment by shaqq** [comment]
I'm looking for something similar. I'm trying to output all of the swagger docs to a JSON file in an automated fashion. Is there a way to do that?

**Comment by dilipkrish** [comment]
@shaqq you can use the [maven plugin](https://github.com/kongchen/swagger-maven-plugin) for that.

**Comment by sac10nikam** [comment]
I am asking.. How can we download swagger json file from swagger docs

**Comment by dilipkrish** [comment]
@sac10nikam Don't know what you're asking. you can download the swagger json by navigating to `http(s)://host:port/context-path/v2/api-docs`

**Comment by shaqq** [comment]
@dilipkrish The maven plugin requires you to list all of the annotated classes in the `locations` config, which sort of defeats the purpose. Is there anything that can figure out what's been annotated without me specifying it?

**Comment by dilipkrish** [comment]
@shaqq Please ask the maven plugin authors. Not familiar with it.
