### ISSUE TITLE
apikey isn't being sent in the query, what am I missing?

### ISSUE THREAD

**Issue by ahatzz11** [springfox/springfox#1602]
**Version**: 2.6.1

First off, thanks for the awesome project! 

I'm trying to implement this into my own project, but I'm having issues getting the api key security working properly. 

Next up, some code: 

```
@Configuration
@EnableSwagger2
@Profile("swagger")
public class SwaggerConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
            .select()
                .apis(RequestHandlerSelectors.basePackage("com.my.package"))
                .paths(PathSelectors.any())
                .build()
            .pathMapping("/")
            .directModelSubstitute(LocalDate.class,
                    String.class)
            .useDefaultResponseMessages(false)
            .securitySchemes(Lists.newArrayList(apiKey()))
            .securityContexts(Lists.newArrayList(securityContext()));
    }


    private ApiKey apiKey() {
        return new ApiKey("mykey", "key", "query");
    }

    private SecurityContext securityContext() {
        return SecurityContext.builder()
                .securityReferences(defaultAuth())
                .forPaths(PathSelectors.regex("/anyPath.*"))
                .build();
    }

    List<SecurityReference> defaultAuth() {
        AuthorizationScope authorizationScope
                = new AuthorizationScope("global", "accessEverything");
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0] = authorizationScope;
        return Lists.newArrayList(
                new SecurityReference("mykey", authorizationScopes));
    }

    @Bean
    SecurityConfiguration security() {
        return new SecurityConfiguration(
                null, null, null,
                "project-name-v2",
                "123",
                ApiKeyVehicle.QUERY_PARAM,
                "key",
                ","/*scope separator*/);
    }
}
```

I'm able to successfully navigate to `http://localhost:8083/api-docs?key=123`. The API key is required to get to this page. Otherwise I get `{"message":"Api key is missing."}`.

I'm also able to successfully get to `http://localhost:8083/swagger-ui.html`. This doesn't require an API key. To get this working, I had to override the AddResourceHandler which I found on #776. 

When I go to the UI, nothing is loaded. In my application I get the following messages. These are small pieces of the total message.

```
"api-key":"",
"api-exception":"Api key is missing.",
"api-request-headers":{"referer":"http://localhost:8083/swagger-ui.html",  [...]
```

Here is the chrome network logs:

![](https://puu.sh/sJVsM/e0e0c585b6.png)

`/swagger-resources/configuration/ui` is a valid url when I also send `?key=123`, but that query param isn't being sent in the request from the ui.

Any ideas? Potential solutions? I feel like I'm missing something to get the key to send, but I've been looking around for hours and can't seem to find what's wrong.

Other notes:
- `123` is a valid API key
- `apiKeyName` should be `key`
- Thanks again!

**Comment by dilipkrish** [comment]
I think you need to set it up so that the swagger related pages are unprotected. Take a look at how [jhipster](https://jhipster.github.io) does it.

**Comment by ahatzz11** [comment]
@dilipkrish I'll look into it this week! However, isn't that what the api key is for on the springfox side? Maybe I'm missing what the purpose of that security configuration is.

**Comment by dilipkrish** [comment]
The purpose of the security configuration isn't to configure spring security and access to the api-docs. It is to ___describe___ how actual services can be accessed in a secure fashion.

**Comment by ahatzz11** [comment]
@dilipkrish Thanks for helping with this, I think I've got everything figured out now!
