### ISSUE TITLE
How do required fields get set?

### ISSUE THREAD

**Issue by kevinm416** [springfox/springfox#1604]
I have classes that have `Optional` fields. I would like only the fields that are not `Optional` to show up in the list of `required` fields. As far as I can tell, all fields are included in the list of required fields. 

I'm trying to recreate a standalone example of this behavior, but when I generate the swagger json in my [demo repo](https://github.com/kevinm416/swagger-test/blob/master/src/main/java/com/kevinm416/SwaggerController.java), there is no `required` key at all!

```
public class StringResponse {
    private final String field1;
    private final Optional<String> field2;
    @JsonCreator
    public StringResponse(
            @JsonProperty("field1") final String field1,
            @JsonProperty("field2") final Optional<String> field2) {
        this.field1 = field1;
        this.field2 = field2;
    }
    public String getField1() {
        return field1;
    }
    public Optional<String> getField2() {
        return field2;
    }
}

        @Bean
        public Docket getSwagger() {
            Contact contact = null;
            final ApiInfo apiInfo = new ApiInfo(
                    null,
                    null,
                    null,
                    null,
                    contact,
                    null,
                    null);
            return new Docket(DocumentationType.SWAGGER_2)
                    .apiInfo(apiInfo)
                    .genericModelSubstitutes(Optional.class);
        }
```
produces:
```
   "StringResponse" : {
      "type" : "object",
      "properties" : {
        "field1" : {
          "type" : "string"
        },
        "field2" : {
          "type" : "string"
        }
      }
    }
```

Based on what I'm seeing elsewhere, I would expect it to produce:

```
   "StringResponse" : {
      "type" : "object",
      "required": ["field1", "field2"],
      "properties" : {
        "field1" : {
          "type" : "string"
        },
        "field2" : {
          "type" : "string"
        }
      }
    }
```

My questions about the `required` field are:
1. What controls whether the `required` field itself is present in the generated json?
2. What controls whether a `@JsonProperty` is marked as required or not?

This is the output that I would like to produce. `field2` is not included in `required` because it is `Optional`.
```
   "StringResponse" : {
      "type" : "object",
      "required": ["field1"],
      "properties" : {
        "field1" : {
          "type" : "string"
        },
        "field2" : {
          "type" : "string"
        }
      }
    }
```

**Comment by kevinm416** [comment]
Update: I've discovered the `ModelPropertyBuilderPlugin` and wrote a plugin that sets`required` based on whether the property is `Optional`:

```
public class OptionalModelPropertyBuilderPlugin implements ModelPropertyBuilderPlugin {
    @Override
    public boolean supports(DocumentationType delimiter) {
        return true;
    }
    @Override
    public void apply(ModelPropertyContext context) {
        Optional<BeanPropertyDefinition> beanPropertyDefinition = context.getBeanPropertyDefinition();
        if (beanPropertyDefinition.isPresent()) {
            AnnotatedParameter constructParameter = beanPropertyDefinition.get().getConstructorParameter();
            if (constructParameter != null) {
                Class<?> rawType = constructParameter.getRawType();
                if (rawType.isAssignableFrom(Optional.class)) {
                    context.getBuilder().required(false);
                }
            }
        }
    }
}
```

This appears to work for classes that are used in the`@RequestBody`, but not classes that are used in the `@ResponseBody`. Hopefully I'll be able to make this work for `@RequestBody` classes too.

**Comment by kevinm416** [comment]
Answers to my own questions:
1. The `required` field is present if at least one field in the class is required. This is behavior comes from `com.wordnik.swagger.models.ModelImpl.getRequired`.
2. Classes marked with `@RequestBody` are `ParameterModelProperty`, and `ParameterModelProperty.isRequired` always returns `true`. Classes marked with `@ResponseBody` go through `BaseModelProperty.isRequired` which determines `required` based on `@JsonProperty.required`. This isn't particularly useful to me, since I'm not going to go through and add `required = true` to all the Jackson serialized classes. Instead, I've opted to set `required` to `true` via my `OptionalModelPropertyBuilderPlugin` for any class that is not `Optional`.

**Comment by dilipkrish** [comment]
@kevinm416 One suggestion I would have so that your plugin will work in all cases (even when not using the `@JsonCreator`/constructor pattern) is to check for optional on any bean property definition.

**Comment by kevinm416** [comment]
Did you mean check for optional on any `AnnotatedParameter` instead of `BeanPropertyDefinition`? I see multiple `AnnotatedParameter`s on a `BeanPropertyDefinition`, but I only see one `BeanPropertyDefinition`.

**Comment by ryanb93** [comment]
For anyone else trying to work this out we ended up writing the following:

`
  @Bean
  @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 10000)
  def optionalModelPropertyBuilderPlugin: ModelPropertyBuilderPlugin = new ModelPropertyBuilderPlugin {
    override def supports(delimiter: DocumentationType) = true

    override def apply(context: ModelPropertyContext): Unit = {
      val resolvedType = context.getBuilder.build().getType
      val erasedType   = resolvedType.getErasedType
      if (classOf[Optional[_]].isAssignableFrom(erasedType)) {
        context.getBuilder.required(false)
        val innerType = resolvedType.getTypeParameters.get(0)
        context.getBuilder.`type`(innerType)
      } else {
        context.getBuilder.required(true)
      }
    }
  }
`
