### ISSUE TITLE
Bug report: Swagger Spec / Doc difference using byte as response

### ISSUE THREAD

**Issue by maukito** [springfox/springfox#1605]
I do encounter the same issue as described in issue: https://github.com/springfox/springfox/issues/1430

As proposed to open a new issue for that i just created one.

Short description:

In Swagger Spec yaml:
--------------------
schema:
            type: string
            format: byte
![image](https://cloud.githubusercontent.com/assets/24587817/21224716/c9d41a10-c2cd-11e6-812f-3a648c0a5730.png)

In generated api-doc.json
--------------------
"schema":{"type":"array","items":{"type":"string","format":"byte"}}}
![image](https://cloud.githubusercontent.com/assets/24587817/21224741/e6578500-c2cd-11e6-9dbf-136eeb9eb6d6.png)

So instead of a string (byte) the documentation shows Inline Model [string].

Info: Our java implementation returns ResponseEntity<byte[]> (as code gen does also)

br
Thomas

**Comment by beaumkr** [comment]
I encountered a similar issue using the swagger maven plugin (from kongchen).
I fixed it by defining an additional ModelConverter that verifies if it's a byte[] and then returns a ByteArrayProperty:

`

import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.type.ArrayType;
import com.fasterxml.jackson.databind.type.SimpleType;
import io.swagger.converter.ModelConverter;
import io.swagger.converter.ModelConverterContext;
import io.swagger.jackson.AbstractModelConverter;
import io.swagger.models.properties.ByteArrayProperty;
import io.swagger.models.properties.Property;
import io.swagger.util.Json;

import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import java.util.Iterator;

public class ByteArrayFixerModelConverter extends AbstractModelConverter implements ModelConverter {
    public ByteArrayFixerModelConverter() {
        super(Json.mapper());
    }

    public Property resolveProperty(Type type, ModelConverterContext context, Annotation[] annotations,
            Iterator<ModelConverter> chain) {
if(isByteArray(type)) {
            //bypass the chain! It would convert the ByteArrayProperty to an Array of ByteArrayProperty (bug in ModelModifier I think)
            return new ByteArrayProperty();
        }
        Property property = null;
        if (chain.hasNext()) {
            property = (chain.next()).resolveProperty(type, context, annotations, chain);
        }

        return property;

    }

    private boolean isByteArray(Type type) {
        boolean ret = type instanceof Class && type == byte[].class;
        if(!ret && type instanceof ArrayType){
            ArrayType at = (ArrayType) type;
            JavaType contentType = at.getContentType();
            if(contentType instanceof SimpleType){
                SimpleType st = (SimpleType) contentType;
                ret = st.getRawClass() == byte.class;
            }
        }
        return ret;
    }
}


`

and it helped returning my operation returns and my model properties having the correct format.
