### ISSUE TITLE
JSR-303 @valid or @validted conflict with @ApiParam parameters

### ISSUE THREAD

**Issue by JcacMing** [springfox/springfox#1606]
this is my controller 
@ApiOperation(value = "close", notes = "close", httpMethod = "GET", response = ResultEntity.class, produces = MediaType.APPLICATION_JSON_VALUE)
    @RequestMapping("/feedbackUpdate")
    public @ResponseBody Object feedbackUpdate(**@Validated** FeedbackBean feedbackBean) {
        feedbackService.UpdateFeedback(feedbackBean);
        return log.exit(ResultUtils.sussess("sussess", null));
    }
}

this is FeedbackBean
`@ApiModel( value = "aaa")
    public class FeedbackBean implements IA
    {
        @ApiModelProperty( value = "bla", required = true )
        @NotNull
          private Integer id;
      @ApiModelProperty( value = "ab", required = true )
        @NotNull   
          private long user_id;
     
}`
 I use swagger 2.6
 I need swagger UI show 
![image](https://cloud.githubusercontent.com/assets/24521657/21250409/eaf63c70-c37f-11e6-853e-8d4b5bd4e901.png)

but if I use JSR-303 @valid or @validted  it show
![image](https://cloud.githubusercontent.com/assets/24521657/21250425/15266178-c380-11e6-80d5-dc9e79e89317.png)

 **I don't know why,plase help me @dilipkrish**

**Comment by JcacMing** [comment]
@johnktims

**Comment by JcacMing** [comment]
@dilipkrish

**Comment by MaksimOrlov** [comment]
Hi, @JcacMing.

Did you try to annotate your FeedbackBean with @ModelAttribute annotation?

So, it will looks like 

```
...
@RequestMapping("/feedbackUpdate")
public @ResponseBody Object feedbackUpdate(@Validated @ModelAttribute FeedbackBean feedbackBean) {
feedbackService.UpdateFeedback(feedbackBean);
return log.exit(ResultUtils.sussess("sussess", null));
...
```

**Comment by JcacMing** [comment]
Thank you very much@MaksimOrlov  ,the problem has been solved
