### ISSUE TITLE
Problem with ResourceOwnerPasswordCredentialsGrant

### ISSUE THREAD

**Issue by TodorSusnjevic** [springfox/springfox#1607]
I am using version 2.6.1 of sprintfox and want to make swagger ui use sprint boot oauth service before invoking my REST controller.
I added grant type as ResourceOwnerPasswordCredentialsGrant("http://localhost:8080/oauth/token");

 So when press toggle button I can see pop up with title Available authorizations and 
Authorization URL:
flow: password

So, Authorization URL is empty.
When check scopes I want to grant (all) I have bean redirected to new page 
http://localhost:8080/null&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fwebjars%2Fspringfox-swagger-ui%2Fo2c.html&realm=pets&client_id=clientapp&scope=write%3Apets%20read%3Apets&state=undefined

and I'm stack here.

Thanks 

 .

**Comment by dilipkrish** [comment]
I don't think ResourceOwnerPasswordCredentialsGrant is supported as of 2.6.1

**Comment by TodorSusnjevic** [comment]
@dilipkrish  thanks for response. What You suggest then for how to make a call from swagger io (pressing Try out button) when documented controller is under oauth with spring boot? I need to send header with valid access_token to be able to test it from swagger ui.


Thanks

**Comment by wbauern** [comment]
@TodorSusnjevic Did you ever figure out how to make this work?  We are running into the same issues.
Thanks!

**Comment by androidzhaoxiaogang** [comment]
Here's my solution:

@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket newApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("appserver")
                .apiInfo(apiInfo())
                .select()
                .paths(regexPaths())
                .build()
                .securitySchemes(apiKeys())
                .securityContexts(securityContext());

    }

    private ApiInfo apiInfo() {
        ApiInfo apiInfo = new ApiInfo("back server",
                "rest api ",
                "1.0",
                "NO terms of service",
                new Contact("andy zhao", "", "286505491@qq.com"),
                "more-tech",
                ""
        );//

        return apiInfo;
    }

    private Predicate<String> regexPaths() {
        return or(
                regex("/admin/.*"),
                regex("/api/.*"),
                regex("/v[0-9]/.*")
        );
    }

    private List<SecurityContext> securityContext() {
        List<SecurityContext> securityContexts = new ArrayList<>();
        SecurityContext context = SecurityContext.builder()
                .securityReferences(defaultAuth())
                .forPaths(regexPaths())
                .build();
        securityContexts.add(context);
        return  securityContexts;
    }
    List<SecurityReference> defaultAuth() {
        List<AuthorizationScope> authorizationScopeList = new ArrayList<>();
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[2];
        authorizationScopes[0] = new AuthorizationScope( "read", "read only" );
        authorizationScopes[1] = new AuthorizationScope( "write", "read and write" );
        List<SecurityReference> list=  new ArrayList<SecurityReference>();
        SecurityReference s = new SecurityReference("Authorization", authorizationScopes);
        list.add(s);
        return list;
    }

    @Bean
    public SecurityConfiguration securityInfo() {
        return new SecurityConfiguration(
                "client_id",
                "client_secret",
                "realm",
                "XXX",
                "Bearer ",
                ApiKeyVehicle.HEADER,
                "Authorization",
                ",");
    }

    private List<SecurityScheme> apiKeys() {
        ArrayList<SecurityScheme> securitySchemes = new ArrayList<>();
        securitySchemes.add(new ApiKey("Authorization", "Authorization", "header"));
        return securitySchemes;
    }

step1: 
get the access token by the command as below:

curl  -vu client_id:client_secret http://localhost:8080/oauth/token -d "grant_type=password&username=xxxxx&password=xxxxx"

step2: 
 
add the access_token in the swagger "key" edittext of the swagger-ui page at the top right place;

 Bearer access_token 

there's a blank between the Bearer  word and the access_token

then u invoke the secured methods that should be worked.

Anyhow, the annoying thing is that when the page has been refreshed, u have to added the access_token again and again.Then u can invoke the secured method to do test with the swagger.

if any problems, feel free to contact me.

and my email: 286505491@qq.com

**Comment by dilipkrish** [comment]
Thank you @androidzhaoxiaogang!!

**Comment by TodorSusnjevic** [comment]
@androidzhaoxiaogang If I add valid access token on swagger ui it generates curl like
curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer**%20**0de17b0d-82bf-4905-87cb-fbf6b203bdc3' 'http://localhost:8080/antennas'

and it is not accepted cause rest returns invalid token. It encodes this white space.
