### ISSUE TITLE
2.6.1  api url encoding issue

### ISSUE THREAD

**Issue by Shaun-Yao** [springfox/springfox#1610]
2.5.0 is working, but not work with 2.6.0 and 2.6.1 when the url include chinese
<img width="758" alt="a1eae283-d4ed-4539-8714-643c7d151083" src="https://cloud.githubusercontent.com/assets/18024481/21291433/27b77e80-c51a-11e6-9022-6157ce47ab83.png">

**Comment by dilipkrish** [comment]
Thats because 2.5.0 uses a different version of swagger-ui than 2.6.1.

**Comment by xhusky** [comment]
Same issue , I removed @Api(tags = SOME_CHINESE_WORD) , use the default setting

**Comment by dilipkrish** [comment]
This is an issue with [`swagger-ui`](https://github.com/swagger-api/swagger-ui) I'll be happy to look at this if the swagger specification json is not rendered correctly.
