### ISSUE TITLE
@RequestBody nested object custom schema

### ISSUE THREAD

**Issue by Shaun-Yao** [springfox/springfox#1612]
original model schema like this
{
  "address": "string",
  "description": "string",
  "patient": {
    //"id": "string", //id is @ApiModelProperty(hidden = true)
    "idCard": "string",
    "name": "string"
  }
}

I want model schema like this
{
  "address": "string",
  "description": "string",
  "patient": {
        "id": "string"
  }
}

how can i do ?

**Comment by dilipkrish** [comment]
If you have the same model in the request and response it is not possible to hide it.

**Comment by yaoshenghong** [comment]
thanks for the reply！My opinion is just send nested object id and resquestbody will load the object by id.
my model like this:
<img width="701" alt="qq20161220-1 2x" src="https://cloud.githubusercontent.com/assets/18024481/21352115/0599e238-c6fb-11e6-9adf-b05ee797bb08.png">


my controller like this:
@ApiOperation(value = "save", notes = "save")
@RequestMapping(method = RequestMethod.POST)
@ResponseStatus(HttpStatus.CREATED)
public void add(@RequestBody ServiceItems serviceItems) {
	orderService.add(serviceItems);
}
