### ISSUE TITLE
HTML code in API description in ignored using springfox-swagger-ui 2.6.1

### ISSUE THREAD

**Issue by anouarchattouna** [springfox/springfox#1613]
I m working on a REST/JSON API using the following stack:
spring-boot : 1.4.2.RELEASE
springfox-swagger2 : 2.5.0 + HTML code in API description : 

![swagger-ui-2 5 0](https://cloud.githubusercontent.com/assets/9251649/21343909/635d85bc-c699-11e6-95b4-7134afe376ea.png)

When I updated springfox-swagger2 to 2.6.1, the HTML code is ignored:

![swagger-ui-2 6 1](https://cloud.githubusercontent.com/assets/9251649/21343952/975fe47c-c699-11e6-89c2-9782ac7c5410.png)

How to reproduce:

- git clone https://github.com/anouarchattouna/spring-boot-sample-logback-access-swagger.git
- cd spring-boot-sample-logback-access-swagger
- mvn clean install && java -Dspring.profiles.active=dev -jar target/spring-boot-sample-logback-access-swagger-0.0.2-SNAPSHOT.jar
- open the swagger ui : http://localhost:8080/swagger-ui.html [***OK***]

Now stop the running server, update the swagger version to 2.6.1 from the pom.xml : 
>			
			<springfox.swagger2.version>2.6.1</springfox.swagger2.version>

- mvn clean install && java -Dspring.profiles.active=dev -jar target/spring-boot-sample-logback-access-swagger-0.0.2-SNAPSHOT.jar
- open the swagger ui : http://localhost:8080/swagger-ui.html [***KO***]

Can you please tell me how to keep the first look and feel?

Thank you for your help.

**Comment by dilipkrish** [comment]
This may be a regression. I'll take a look.

**Comment by anouarchattouna** [comment]
Hello @dilipkrish, do you have any news about this issue?

**Comment by kyrill007** [comment]
Yeah, this is definitely a problem. Hard stop for us to upgrade from 2.5.0. Please fix it. The regression is here: https://github.com/springfox/springfox/commit/487e9742229901a02ac27ce8d1275f1f8e4b760c#diff-12d7f28d8f01c16562b3be87ecd15981

**Comment by dilipkrish** [comment]
@anouarchattouna/ @kyrill007  Springfox has 2 parts, 
- one is the piece that generates the specification json 
- second is the piece thats a customized swagger-ui that is provided as a convenience. This piece is optional. So you're free to use your own customized swagger ui. 

Having said that, the customized swagger-ui is unmodified (outside of the UI changes you point above). So if you see problems with json its a problem with springfox, o/w its a problem with swagger-ui.

**Comment by matdelong** [comment]
I can still reproduce this issue with version 2.7.0.

**Comment by dilipkrish** [comment]
Yes it is a problem with swagger ui rendering HTML descriptions

**Comment by sathyamahendran** [comment]
Hi Dilip, 

Any update about this issue

**Comment by dilipkrish** [comment]
@sathyamahendran There is nothing to fix. the version of swagger-ui being used does not render inlined html.
