### ISSUE TITLE
unable to get download file

### ISSUE THREAD

**Issue by ssahni30** [springfox/springfox#1614]
```java
public void getLabel(@QueryParam("orderItemsId") String orderItemsId,HttpServletRequest httpServletRequest,HttpServletResponse response) {
        String dataDirectory = httpServletRequest.getSession().getServletContext().getRealPath("/WEB-INF/files/label.pdf");
        Path file = Paths.get(dataDirectory);
        if (Files.exists(file))
        {
            response.setContentType("application/pdf");
            response.addHeader("Content-Disposition", "attachment; filename=\"label.pdf\"");
            try
            {
                Files.copy(file, response.getOutputStream());
                response.getOutputStream().flush();
            }
            catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
```

i am using `@ApiResponses(value = { @ApiResponse(code = 200, message = "Perfect") })` 

without content-Disposition header swagger is unable to sync output file and whereas is with this header is get a link in ResponseBody which also corrupts my file.

I am not sure what i am missing ?

`@RequestMapping(value = "/orders/labels", method = RequestMethod.GET, produces = MediaType.APPLICATION_OCTET_STREAM)`

Still i am receiving corrupted pdf file

[application-pdf-labels-orderItemsId=ff-blob-http---localhost-8080-f1e0b4e0-7b63-439b-8eeb-1a281524bfa1.pdf](https://github.com/springfox/springfox/files/664343/application-pdf-labels-orderItemsId.ff-blob-http---localhost-8080-f1e0b4e0-7b63-439b-8eeb-1a281524bfa1.pdf)

![screen shot 2016-12-20 at 9 38 54 pm](https://cloud.githubusercontent.com/assets/16645148/21360805/783898c8-c707-11e6-84c4-85e9c7c47dae.png)

**Comment by ssahni30** [comment]
`public void getLabel(@QueryParam("orderItemsId") String orderItemsId,HttpServletRequest httpServletRequest,HttpServletResponse response) {
        String dataDirectory = httpServletRequest.getSession().getServletContext().getRealPath("/WEB-INF/files/label.pdf");
        Path file = Paths.get(dataDirectory);
        if (Files.exists(file))
        {
            response.setContentType("application/pdf");
            response.addHeader("Content-Disposition", "attachment; filename=\"label.pdf\"");
            try
            {
                Files.copy(file, response.getOutputStream());
                response.getOutputStream().flush();
            }
            catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }`

**Comment by dilipkrish** [comment]
Did you resolve this issue? If not have you tried seeing if it works with a simple curl request?
