### ISSUE TITLE
Example values for Java 8 types OptionalInt, OptionalLong, and OptionalDouble are rendered as strings.

### ISSUE THREAD

**Issue by garakelian** [springfox/springfox#1616]

**Comment by dilipkrish** [comment]
I believe examples are always strings in the spec.

**Comment by dilipkrish** [comment]
Yes but example values are just textual representations for api consumers. They aren't meant to be used as literal values.

**Comment by dilipkrish** [comment]
Im a little confused. Could you share how your model with annotations for your example? The reason I ask is that property examples are not yet supported. Secondly when you see `Example value` in the UI it will try to generate sample values if the example is not provided. And from my experience, those have the right types usually.
