### ISSUE TITLE
Spring Data Rest base endpoints of repository not shown

### ISSUE THREAD

**Issue by cglantschnig** [springfox/springfox#1619]
I use version 2.6.1.

I am trying to generate a api documentation with my spring bootstrap application. I am using Spring Data Rest and I have Repository like you can see below. The problem is that in the swagger json is just the "findByLastname" Endpoint. The standard endpoints, which exists like the default GET, PUT, PATCH, DELETE endpoints are not visible. Is there somewhere a hidden configuration, which I have to set?

```java
@RepositoryRestResource(collectionResourceRel = "records", path = "records")
public interface RecordRepository extends PagingAndSortingRepository<Record, UUID>, ExternalRepository {
    List<Record> findByLastname(@Param("name") String name);
}

```

**Comment by dilipkrish** [comment]
There shouldn't be any other configuration other than importing the SDR configuration. How have you configured it?

**Comment by cglantschnig** [comment]
ok the issue can be closed. I figured out that my filter at the Swagger Configuration Class has been too strict.
