### ISSUE TITLE
Swagger-UI shows more information on the model window than the one that is being sent

### ISSUE THREAD

**Issue by TorrentBeast** [springfox/springfox#1620]
Hello, i using swagger to produce documentation for my spring Rest API, i am using json MixIn and JsonView to choose which data my domain objects should send to the client.

Everything seems to work fine except for the model and example value showed by the swagger UI which shows all the information of my domain object instead of showing only the filtered information done my JsonView.

Image of the model and example value and the response body send by the server in the swagger UI
![modelandresponse](https://cloud.githubusercontent.com/assets/11476328/21547598/078bdcf0-cddf-11e6-8e4a-338a33d51cf8.PNG)

My controller method
![controllermethod](https://cloud.githubusercontent.com/assets/11476328/21547645/57b2ff2e-cddf-11e6-9638-027b59583080.PNG)

My MixIn class to filter domain information:
![mixin](https://cloud.githubusercontent.com/assets/11476328/21547690/86152842-cddf-11e6-8ad4-debc198103f4.PNG)

How can i manage the data showed in the model and example value window to show the same amount of information as my response body ?

Note: in the example i not showing the Order domain object.

My swagger version is 2.6.1

**Comment by dilipkrish** [comment]
added an direct model substitution in your docket

```java
    docket.directModelSubstitute(Order.class, OrderMixin.class);

```

**Comment by TorrentBeast** [comment]
HI @dilipkrish  , thanks in advice for the quick answer , the problem of using that approach is that the i lose the advantage of using different views to enable or disable fields from being send by my Rest API. 
In my case i have two views Expose and Test and Expose is the only active view as you can see in my controller, however the flowKey param (with view Test associated) is being showed in the Model and example Value window.
![image](https://cloud.githubusercontent.com/assets/11476328/21550155/88ec821c-cdef-11e6-8bd9-f81d366c0528.png)

**Comment by dilipkrish** [comment]
Really you're looking for #601 which we don't have

**Comment by pavanthota1998** [comment]
@dilipkrish we are trying to using the `directModelSubstitute` method to serve the same purpose. In the swagger endpoint example we are getting the overridden model's examples. is there any way we can show the actual fields examples. for more info please take a look at the issue #3284. 
Thanks in advance 🙂.
