### ISSUE TITLE
Is it possible to extract parameters from an object to show in parameters in documentation?

### ISSUE THREAD

**Issue by ahatzz11** [springfox/springfox#1625]
I have the following API endpoint: 

```
    @ApiResponses(
        value = {
            @ApiResponse(code = 200, message = "OK",
                responseHeaders = {
                    @ResponseHeader(name = "X-RateLimit-Limit", description = "The defined maximum number of requests available to the consumer for this API.", response = Integer.class),
                    @ResponseHeader(name = "X-RateLimit-Remaining", description = "The number of calls remaining before the limit is enforced and requests are bounced.", response = Integer.class),
                    @ResponseHeader(name = "X-RateLimit-Reset", description = "The time, in seconds, until the limit expires and another request will be allowed in. This header will only be present if the limit is being enforced.", response = Integer.class)
                }
            )
        }
    )
    @ApiOperation(httpMethod = "GET", hidden = false, nickname = "Get Network Availability in JSON", value = "Get network availability for a product", response = AvailableToPromise.class, position = 1)
    @RequestMapping(value = "/{product_id}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<?> networkAvailabilityJsonResponse(
        @RequestHeader HttpHeaders headers,
        @PathVariable("product_id") String productId,
        @Valid NetworkAvailabilityCmd cmd,                  //query params
        BindingResult result)
        throws Exception {}
    }
```

Certain parameters, such as `key` are taken from the query and mapped into this object through Spring MVC.

However, in the parameters section of my endpoint in the swagger-ui, it's showing me quite a few odd things: 

![](https://puu.sh/ta5j9/61ee4e6a17.png)

None of the variables that are in `NetworkAvailabilityCmd` show in this parameters list, and cmd itself shows as being located in the request body (it's actually located in the query). Is there a way to hide `cmd` and extract the params inside this object to show on the params list? I'd like the params list to look like this (with more params): 

![](https://puu.sh/ta5z9/29fe9af032.png)

I'm able to do this if I use `@ApiImplicitParams` on the method endpoint, and write out each of the params. However, this `NetworkAvailabilityCmd` is used for many endpoints, and having the list of params on each endpoint is very messy. Being able to extract the variables from in the object would be far cleaner, and would prevent people from forgetting to add the entire list to new endpoints. 

I imagine that it requires an annotation on `NetworkAvailabilityCmd cmd`, and potentially something on the variables in that class, but I can't seem to find what I'm looking for. Is this possible?

Thanks!

**Comment by dilipkrish** [comment]
In any case if you add the @ModelAttribute to `NetworkAvailabilityCmd` parameter it will also fix your issue.

**Comment by ahatzz11** [comment]
Awesome - That does exactly what I wanted to do, thanks!

However, now I'm running into the issue where `ApiModelProperty(position = x)` isn't properly working. Inside `NetworkAvailabilityCmd` I have a few properties. 

Here is some code from that class: 

```
    @ApiModelProperty(required = true, position = 1)
    private String key;

    private Boolean is_parent_id;

    @Min(0)
    @ApiModelProperty(position = 4)
    private double radius = 10d;

    private Nearby nearby = null;

    @ApiModelProperty(position = 2)
    private String nearby_store;

    @IsValidChannelId
    @ApiModelProperty(position = 3)
    private String channel_id = ChannelId.ESTORE.toString();
```

And here is the JSON output, which matches the ui:

```
"parameters":[
  {
    "name":"product_id",
    "in":"path",
    "description":"product_id",
    "required":true,
    "type":"string"
  },
  {
    "name":"multichannel_option",
    "in":"query",
    "required":false,
    "type":"array",
    "items":{
      "type":"string"
    },
    "collectionFormat":"multi"
  },
  {
    "name":"location_ids",
    "in":"query",
    "required":false,
    "type":"array",
    "items":{
      "type":"string"
    },
    "collectionFormat":"multi"
  },
  {
    "name":"key",
    "in":"query",
    "required":true,
    "type":"string"
  },
  {
    "name":"radius",
    "in":"query",
    "required":false,
    "type":"number",
    "format":"double"
  },
  {
    "name":"nearby_store",
    "in":"query",
    "required":false,
    "type":"string"
  },
  {
    "name":"channel_id",
    "in":"query",
    "required":false,
    "type":"string"
  }
``` 

`radius` should be at the bottom, but it isn't. I do have `@ApiModel` on the `NetworkAvailabilityCmd` class. Any ideas on this? I'm not sure if this is SpringFox related or not, but thank you for the assistance.

**Comment by dilipkrish** [comment]
Unfortunately thats a function of the data structures used by the original swagger-core project for DTOs. Using regular hash maps does not guarantee order.

**Comment by ahatzz11** [comment]
Alright, good to know. I'll probably submit an issue over on there end. 

One last question for you - when using the `@ModelAttribute` on an object that contains objects (as an array), it shows the entire path of the array. 

![](https://puu.sh/tdqyB/f79569fa4b.png)

Is it possible to only show the final parameter? All of the mapping is done through Spring, so consumers only ever have to put in the end parameter, e.g. `NetworkDemandEventTimestamp`.

**Comment by dilipkrish** [comment]
These are nested parameters and spring will not be able to do the mappings if they aren't fully qualified

**Comment by ahatzz11** [comment]
Interesting, thanks for the info!
