### ISSUE TITLE
Error with group handling response

### ISSUE THREAD

**Issue by marchc** [springfox/springfox#1627]
Springfox version 2.6.1

Issue with the way in which group handling returns group data

Hi 

I have found  an issue with the way the group parameter is applied to, I am prepared to accede that this might be my reading of the documentation but I have spent some time searching and failed to find a similar issue.

Given this configuration:
```java
        @Bean
        public Docket cruiseSearch() {
            return new Docket(DocumentationType.SWAGGER_2)
                    .groupName("cruise")
                    .directModelSubstitute(XMLGregorianCalendar.class, Date.class)
                    .directModelSubstitute(Duration.class, String.class)
                    .ignoredParameterTypes(
                            io.travelthing.api.v2016a.commontypes.AccommodationIdList.class,
                            io.travelthing.api.v2016a.commontypes.BasketType.class,
                            io.travelthing.api.v2016a.commontypes.Boat.class,
                            io.travelthing.api.v2016a.commontypes.Car.class,
                            io.travelthing.api.v2016a.commontypes.CarPark.class,
                            io.travelthing.api.v2016a.commontypes.Flight.class,
                            io.travelthing.api.v2016a.commontypes.Hotel.class,
                            io.travelthing.api.v2016a.commontypes.ImagesType.class,
                            io.travelthing.api.v2016a.commontypes.PaymentCardCharges.class,
                            io.travelthing.api.v2016a.commontypes.RequiredTransferInfo.class,
                            io.travelthing.api.v2016a.commontypes.Transfer.class,
                            io.travelthing.api.v2016a.requestcommontypes.BoatRequest.class,
                            io.travelthing.api.v2016a.requestcommontypes.CarRequest.class,
                            io.travelthing.api.v2016a.requestcommontypes.CarParkRequest.class,
                            io.travelthing.api.v2016a.requestcommontypes.ExtraRequest.class,
                            io.travelthing.api.v2016a.requestcommontypes.FlightRequest.class,
                            io.travelthing.api.v2016a.requestcommontypes.HolidayRequest.class,
                            io.travelthing.api.v2016a.requestcommontypes.HotelRequest.class,
                            io.travelthing.api.v2016a.requestcommontypes.TransferRequest.class

                    )
                    .select()
                    .apis(RequestHandlerSelectors.any())
                    .paths(PathSelectors.ant("/cruise-search"))
                    .build().apiInfo(getApiInfo());
        }

        @Bean
        public Docket productSearch() {
            return new Docket(DocumentationType.SWAGGER_2)
                    .groupName("product")
                    .directModelSubstitute(XMLGregorianCalendar.class, Date.class)
                    .directModelSubstitute(Duration.class, String.class)
                    .select()
                    .apis(RequestHandlerSelectors.any())
                    .paths(PathSelectors.ant("/product-search"))
                    .build().apiInfo(getApiInfo());
        }

        @Bean
        public UiConfiguration uiConfig() {
            return new UiConfiguration(
                    "validatorUrl",
                    "list",
                    "alpha",
                    "schema",
                    UiConfiguration.Constants.DEFAULT_SUBMIT_METHODS,
                    true,
                    true,
                    60000L);
        }

        @SuppressWarnings("deprecation")
        private ApiInfo getApiInfo() {
            return new ApiInfo(
                    "Reader offers Cruise API",
                    "Provides a series of JSON messages to manipulate and book cruises",
                    "1.0.0",
                    "There are no terms of service associated with this API",
                    "support@ttsltd.com",
                    null,
                    null);
        }


```

I would expect the following web application calls to return a different response

http://api.tts.io/v2/api-docs?group=product
http://api.tts.io/v2/api-docs?group=cruise

They dont, they both produce identical responses, the response being that of the cruise bean which is the first to be defined.

Can you let me know if this is a bug or my reading of the scenario

**Comment by dilipkrish** [comment]
Are you saying the operations that are in both those groups are completely alike? Keep in mind that the two groups may share the same models (beans as you're referring to them).

**Comment by marchc** [comment]
The modes share the same underlying objects, one is has the ignore parameters, one does not. The issue is not with the Documentation cache retreive code as I have just breakpointed it 

The issue is that Documentation cache underlying ApiListing has identical data in it. See attached images 
<img width="933" alt="screen shot 2017-01-09 at 17 21 31" src="https://cloud.githubusercontent.com/assets/1128052/21775964/28db7136-d690-11e6-9d1c-f26b514e5dfe.png">
<img width="936" alt="screen shot 2017-01-09 at 17 21 53" src="https://cloud.githubusercontent.com/assets/1128052/21775965/28dde52e-d690-11e6-93b5-4e404f9b7533.png">

If you look you will see that models are identical, the wider model picture has much all the excluded classes in it which I think should be there in the product instance

**Comment by dilipkrish** [comment]
Ah I see! thats very much a new use case that we haven't thought off.... er... bug if you will. The models are cached across dockets. So its luck of the draw as to which types get ignored based on the order the dockets are loaded. Thanks for catching that! 👍

**Comment by marchc** [comment]
OK, Ill leave it with you, have you got an idea of a workaround that I could use?

**Comment by dilipkrish** [comment]
Going to mark it a feature FWIW, mainly because it might be hard to disentangle the caching of the models and may not make it to 2.7.

One question I have tho' is that, assuming you did not have springfox, when you have these models in your product search, how are you ensuring that the in models, the ignored child properties are not populated? Don't you have different models for your product search than your cruise search?

**Comment by marchc** [comment]
The issue is more to do with the product search request which is a highly complex request and us wanting to slim it down into a series of smaller requests whilst retaining the functionality of the big one.

We can easily fail the message if the fill in parts they shouldn't as they are different endpoints
iIf I did not have springfox I would document it by hand I guess
