### ISSUE TITLE
Back slash in @Api tags breaks the ui

### ISSUE THREAD

**Issue by gintarasbar** [springfox/springfox#1630]
Please take the time to search the repository, if your question has already been asked or answered.

- Using version 2.6.1 

 - If I put "/" symbol in Api tags annotation it breaks the UI (the operations do not expand anymore, though they are rendered.  e.g. @Api(tags = "/v1/foobar") breaks, but @Api(tags = "v1-foobar") is working fine.
   
GET /v1/foobar is rendered, but when I click on it, it doesn't expand anymore if back slash used.
Browser: Chrome Version 55.0.2883.95 (64-bit)

- Console output: nothing, no errors.

I used tags to overwrite the default value of foobar-controller as value property doesn't override it.

**Comment by dilipkrish** [comment]
This is a swagger-ui bug. As long as you can render the specification fine in json, its not an issue in this library.
