### ISSUE TITLE
Q: How to ignore generic Controller type in definitions

### ISSUE THREAD

**Issue by jschoedt** [springfox/springfox#1631]
Using version 2.6.1

Question: I have a generic Controller that I use for all my controllers. I want to ignore the S type form the "definitions" as it is not exposed to the end user and it drags in some other types as well. 
T type is ok as it is the type returned by the specific implementation of the GenericRestController.

```
public abstract class GenericRestController<T extends Moao, S extends IGenericService<T>> extends CommonRestController {


  @Autowired
  protected S genericService;
....

```

**Comment by dilipkrish** [comment]
Adding S (the type) to the ignorable types doesnt work for you?

**Comment by jschoedt** [comment]
I have found the root of the problem but I am not sure why. If I have a method:
`  @PostMapping("foo")
  public ResponseEntity<Void> test() {
    return new ResponseEntity(HttpStatus.OK);
  }`

It drags in all the S types but if I change this to:

`  @PostMapping("foo")
   @ResponseStatus(value = HttpStatus.OK)
  public void test() {
    return;
  }`

Now it does not? 

Note that I have a lot of other methods returning ResponseEntity<T> , ResponseEntity<String> ...etc. in the same generic controller and they are not showing this issue. So I think it has to do with the void return type.

**Comment by dilipkrish** [comment]
It is possible that this is a bug in `classmate`. Might see if I can reproduce it.
