### ISSUE TITLE
Invalid response model for class with name "File"

### ISSUE THREAD

**Issue by dreambrother** [springfox/springfox#1632]
Documentation generation for class with name `File` is invalid. I've created a sample project https://github.com/dreambrother/springfox-bug-example with two identical classes `File` and `File1`, and used them in a controller:
```java
@RequestMapping(path = "/files/{fileId}", method = RequestMethod.GET)
public File file(@PathVariable String fileId) {
    return new File().id(fileId);
}

@RequestMapping(path = "/files1/{fileId}", method = RequestMethod.GET)
public File1 file1(@PathVariable String fileId) {
    return new File1().id(fileId);
}
```
 `File` and `File1` exist in definition section of generated JSON doc. Documentation for the response with `File1` model is valid:
```json
{"description":"OK","schema":{"$ref":"#/definitions/File1"}}
```
But for the `File` is not:
```json
{"description":"OK","schema":{"type":"file"}}
```
Version: 2.6.1

**Comment by dilipkrish** [comment]
Thanks for reporting it! Especially awesome to have an example project demonstrating it.
