### ISSUE TITLE
Consumer Aware Feature

### ISSUE THREAD

**Issue by prakass1** [springfox/springfox#1635]
I am using springfox-swagger-2.4.0, and was successfully able to view the doc on separately deployed swagger-ui.

Screenshot below:
![image](https://cloud.githubusercontent.com/assets/6094960/22011195/bf0d7f22-dcb3-11e6-8db4-407695decca5.png)

Currently, we have around 20 API and all the listing are on /rest/v2/api-docs json file.

We have a request and they are looking for a feature as : 
1:Consumer Aware application : That is the swagger application to be listed based on role. (Example: If a role obtained is mobile then the API listing in swagger UI should be only mobile APIs and if the role is like admin then he would be able to view all the APIs as it is already doing).

My question for the above feature is that how we could split the one json which is rendered though swagger-springfox into multiple jsons so that based on each role obtained that specific url can be shown on the swagger-ui ?

2: Is there a way to save these listings as POSTMAN collection ?

Any inputs on them will help me a lot !!!

**Comment by dilipkrish** [comment]
You can [use groups](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints) for that. Create two dockets one for  "mobile" and one "regular" (`Docket#groupName`) and you can specify which API's appear in each group using a combination of `RequestHandlerSelectors` and/or `PathSelectors`.

The groups can be accessed using the group query param e.g. `/v2/api-docs?group=mobile`

**Comment by prakass1** [comment]
@dilipkrish 

Thanks for the information, I think I can proceed with it.

Additionally, on firing http://<<domain>>:<<port>>/rest/v2/api-docs on browser I am able to get the swagger json, but when I try to do a import by link in POSTMAN i get an error "Must contain a swagger field (2.0)".

Note: If the copy the whole json and paste as raw text in import for POSTMAN, it works and I can see all the collections being saved.

Could you provide any help on this ?

Thanks,
Subash

**Comment by dilipkrish** [comment]
No idea... thats a postman question

**Comment by prakass1** [comment]
It seems to be working perfect now!!
Thank you
