### ISSUE TITLE
VendorExtension support in ApiKey

### ISSUE THREAD

**Issue by mlstocks** [springfox/springfox#1636]
I'm trying to add AWS API gateway extensions to a custom api key type authorizer.  From what I can see the swagger ApiKeyAuthDefinition will handle VendorExtensions but the ApiKey and ApiKeyAuthFactory won't.

Is this a feature that might be added?

**Comment by dilipkrish** [comment]
Would be happy if you could issue a PR to address that.

**Comment by cfernandezh** [comment]
I'm working on this issue because I will work with aws api gateway and I need to support the following security definition:

"securityDefinitions": {
    "MyUserPool": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "x-amazon-apigateway-authtype": "cognito_user_pools",
      "x-amazon-apigateway-authorizer": {
        "type": "cognito_user_pools",
        "providerARNs": [
          "arn:aws:cognito-idp:{region}:{account_id}:userpool/{user_pool_id}"
        ]
      }
    }

**Comment by dilipkrish** [comment]
@cfernandezh thank you very much!

**Comment by cfernandezh** [comment]
I sent the following pull request:

https://github.com/springfox/springfox/pull/1717
