### ISSUE TITLE
Swagger generation issue with @JsonDeserialize on request objects

### ISSUE THREAD

**Issue by kevinm416** [springfox/springfox#1639]
version: 2.6.1

I've got an interface that specifies the concrete class for serialization and deserialization:
```
@JsonSerialize(as = ImmutableMyClass.class)
@JsonDeserialize(as = ImmutableMyClass.class)
public interface MyClass {
    String getBar();
}

public class ImmutableMyClass implements MyClass {
    private final String bar;
    public ImmutableMyClass(String bar) {
        this.bar = bar;
    }
    @JsonProperty("bar")
    public String getBar() {
        return null;
    }
}
```

When `MyClass` is returned from a controller method, the swagger json looks good:
```
    @RequestMapping(
            value = "/endpoint",
            method = RequestMethod.POST)
    @ResponseBody
    public MyClass package1() {
        return new ImmutableMyClass("abc");
    }
```

```
  "definitions" : {
    "MyClass" : {
      "type" : "object",
      "properties" : {
        "bar" : {
          "type" : "string"
        }
      }
    }
  }
```

However, when `MyClass` is taken as the `@RequestBody`, then none of the fields are populated:

```
    @RequestMapping(
            value = "/endpoint",
            method = RequestMethod.POST)
    @ResponseBody
    public String package1(@RequestBody MyClass req) {
        return "abc";
    }
```

```
  "definitions" : {
    "MyClass" : {
      "type" : "object"
    }
  }
```

The reason I'm using `@JsonSerialize` and `@JsonSerialize` like that is https://immutables.github.io/. The example I provided exhibits the issue without using Immutables. However, all classes generated with Immutables suffer from this issue when used with `@RequestBody`. You can run an example of this issue at this commit: https://github.com/kevinm416/swagger-test/commit/92241a6a072bec461d8353bef127c12d9a73d12f.

**Comment by john-roj87** [comment]
@kevinm416 This is related to https://github.com/springfox/springfox/issues/1490 The way I "solve" this was to create a custom  alternateTypeRules in the Docket config.


```
@Bean
public Docket docket() {
  return new Docket(DocumentationType.SWAGGER_2)
    .alternateTypeRules(AlternateTypeRules.newRule(MyClass.class,
                ImmutableMyClass.class));
```

Which is kind of a pain since you need to make the Immutable visible outside the package. Maybe there is an alternative way.
