### ISSUE TITLE
Swagger-ui reads always the same group from dropdown, redirection problem

### ISSUE THREAD

**Issue by oksett** [springfox/springfox#1640]
I have a problem with switching between groups of API that i have configured .
Here is my configuration:

    @Configuration
    @EnableSwagger2
    public class SwaggerConfig{
    @Bean
    public Docket api(){
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .paths(PathSelectors.any())
                .build();
    }

    @Bean
    public Docket apiERP(){
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("erp")
                .select()
                .apis(RequestHandlerSelectors.basePackage("org.erp.api.controller"))
                .build();
    }

    @Bean
    public Docket apiWarehouse(){
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("warehouse")
                .select()
                .apis(RequestHandlerSelectors.basePackage("org.warehouse.api.controller"))
                .build();
    }
}

And i also made addViewControllers and addResourceHandlers for customize paths:
    
    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        registry.addRedirectViewController("/docApi/v2/api-docs", "/v2/api-docs");
        registry.addRedirectViewController("/docApi/swagger-resources/configuration/ui", "/swagger-resources/configuration/ui");
        registry.addRedirectViewController("/docApi/swagger-resources/configuration/security", "/swagger-resources/configuration/security");
        registry.addRedirectViewController("/docApi/swagger-resources", "/swagger-resources");
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/docApi/swagger-ui.html**").addResourceLocations("classpath:/META-INF/resources/swagger-ui.html");
        registry.addResourceHandler("/docApi/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
    }

In swagger-ui.html when i switch between groups in my dropdown i always see the same api docuemntation.

This is JSON which i get from http://localhost:8080/swagger-resources/
   [ {
   "name" : "default",
   "location" : "/v2/api-docs",
   "swaggerVersion" : "2.0"
    }, {
   "name" : "erp",
   "location" : "/v2/api-docs?group=erp",
   "swaggerVersion" : "2.0"
    }, {
   "name" : "warehouse",
   "location" : "/v2/api-docs?group=warehouse",
   "swaggerVersion" : "2.0"
    } ]

I have different JSON response when i entering those locations.

The main problem is that, it redirects me always to http://localhost:8080/v2/api-docs no matter if i hit 
http://localhost:8080/docApi/v2/api-docs?group=erp or http://localhost:8080/docApi/v2/api-docs?group=warehouse and of course http://localhost:8080//docApi/v2/api-docs

How to resolve this problem?

**Comment by dilipkrish** [comment]
All your redirects are not working in cohesion. Sorry I can't be of much help here.
