### ISSUE TITLE
How to write to swagger.json

### ISSUE THREAD

**Issue by Bikesh-tricon** [springfox/springfox#1643]
I am using java spring boot framework to create REST api for my project and I am using "springfox-swagger2 and springfox-swagger-ui" for generating swagger documentation. I am able to see my documentation using the url http://localhost:8080/swagger-ui.html. 

**How can I crate or generate swagger.json / spec.json**, The documentation should not be with this application we are using a separate application for listing the api docs

**Comment by dilipkrish** [comment]
Whatever is produced when you `GET /v2/api-docs` is the same as `swagger.json`

**Comment by mhuisman** [comment]
@Bikesh-tricon @dilipkrish I demonstrated how to accomplish this in https://github.com/springfox/springfox-demos/pull/28 .  Since then the springfox-staticdocs module has been removed from the project, but the methodology should still be valid.

**Comment by dilipkrish** [comment]
Thanks for the reminder.. will pull the PR in  :)

**Comment by pathikmehta** [comment]
If I try to hit *http://[Host]:[Port]/MyApp/v2/api-docs* url from browser, It doesn't return any json data.
And if I try with *http://[Host]:[Port]/MyApp/v2/api-docs?group=myGroupName* url, It returns me appropriate json data for given group name.

**Q) Why it is not returning any json data if I use */v2/api-docs* url?**

I have tried with the similar test case as described by @mhuisman. But I am not able to get swagger json details for */v2/api-docs*. Then I tried with */v2/api-doc?group=myGroupName* and it works partially. It gives me only overview details which I have set in api info bean but all other paths and definition details are empty. It creates empty definition.adoc and paths.adoc files.

**Q) Why it returns only overview details and *not returning any definition or path details?* I can see the definition and path details if I try to hit the */v2/api-docs?group=myGroupName* URL from a browser.**
