### ISSUE TITLE
Support for Spring 5

### ISSUE THREAD

**Issue by binkley** [springfox/springfox#1644]
When adding springfox-swagger2 2.6.1 to a project using Spring 5.0.0.M4, runtime fails with a missing class: `java.lang.NoClassDefFoundError: org/springframework/web/servlet/mvc/annotation/AnnotationMethodHandlerAdapter`.

This class has been removed in Spring Framework 5 after deprecation in 4.2.  Though I did not find the specific issue for that, I did find reference to it with Spring HATEOAS: https://github.com/spring-projects/spring-hateoas/issues/469.

Would you be able to remove dependency on `AnnotationMethodHandlerAdapter` so I can use SpringFox with Spring 5?

**Comment by dilipkrish** [comment]
Thank you for reporting!!  Will try and fix it in the next release!

**Comment by dilipkrish** [comment]
This may be because of a dependency on hateoas. Will see if I can pull in the latest bits
