### ISSUE TITLE
swagger-ui won't work because json responses have java object names in them

### ISSUE THREAD

**Issue by wshao518** [springfox/springfox#1646]
I am trying to integrate swagger-ui to a spring-boot project. I am using the latest versions and following the demos and keep getting swagger-ui.html with undefined in selection box. After I debugged it, and I realized instead of getting a expected JSON object like this:

`[
    {
        "@class": "springfox.documentation.swagger.web.SwaggerResource",
        "name": "batch-rest-api",
        "location": "/v2/api-docs?group=batch-rest-api",
        "swaggerVersion": "2.0"
    }
]`

I will get this:

`[
    "java.util.ArrayList",
    [
        {
            "@class": "springfox.documentation.swagger.web.SwaggerResource",
            "name": "batch-rest-api",
            "location": "/v2/api-docs?group=batch-rest-api",
            "swaggerVersion": "2.0"
        }
    ]
]`

When this URL is being queried: http://localhost:8080/swagger-resources

Because of that, the AJAX code won't work. I think there are some other module's setup requires the Java object to present in Jackson's serialization, and this messed up swagger-ui. Is there a way to get this to be working? Thanks!

**Comment by dilipkrish** [comment]
No idea. 

Please share more details about how you've configured your spring application, is it a boot application etc. [See guidelines](https://github.com/springfox/springfox/blob/master/.github/ISSUE_TEMPLATE.md) for issue submission.

**Comment by wshao518** [comment]
Fixed. There is a Jackson MessageConverter brought in by Spring Batch Admin: https://github.com/spring-projects/spring-batch-admin/blob/master/spring-batch-admin-domain/src/main/java/org/springframework/batch/admin/domain/support/VariableTypeJackson2ObjectMapperFactoryBean.java

I removed it and now swagger works.
