### ISSUE TITLE
swagger-ui, the ui broke when using @GetMapping annotation

### ISSUE THREAD

**Issue by gilsheps** [springfox/springfox#1647]
I using swagger-ui with maven and spring mvc, I am using the last version, 2.6.1.
I have this function:
 @RequestMapping(value = "**",method = RequestMethod.GET)
    @ResponseBody
    public void getResponse(HttpServletRequest request, HttpServletResponse response) {
        if (!(request.getRequestURL().toString().contains("webjars")) && !(request.getRequestURL().toString().contains("localhost"))) {
            getResponseHome(request, response);
        }
    }

this function will get all get traffic, when swagger booting and requesting the resources(css files and js files), i access the function.

Is there a way to hide or ignore this function, when swagger booting?

**Comment by dilipkrish** [comment]
Can we try and use the [@CrossOrigin](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/CrossOrigin.html) and see if that fixes your problem.

**Comment by dilipkrish** [comment]
Moving to complete... think its more to do with how the urls are configured for CORS.
