### ISSUE TITLE
operation ordering is not working

### ISSUE THREAD

**Issue by neil-dang** [springfox/springfox#1648]
version 2.6.1

I wanna operations sorted by http methods and paths, so I configured it  by using `springfox.documentation.spring.web.plugins.Docket.operationOrdering(Ordering<Operation> operationOrdering)`, but it didn't work.

I found out that `List<Operation> springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(RequestMappingContext outerContext)` didn't add all operations at a time, so this maybe the bug.

Please check it.

**Comment by dilipkrish** [comment]
The operation ordering may not have the desired effect in swagger 2.0. However I've put in a fix to make the path lexically sorted based on comparable path strings. Thanks for reporting this issue!
