### ISSUE TITLE
In swagger-ui endpoints are not visible in version > 2.4

### ISSUE THREAD

**Issue by pvpkiran** [springfox/springfox#1649]
Hi,
  I am using swagger 2.6.1. I had basic auth in my application. And I recently added outh2 to my application. Since then Swagger-UI doesn't show any endpoints. 

This is what I have in my security config

``` 
http     
    .csrf().disable()  
                .requestMatchers().antMatchers("/swagger-ui.html", "/swagger-resources",  
                "/configuration/ui", "/configuration/security",  
                "/v2/api-docs", "/webjars/**")  
                .antMatchers("/product/**")  
                .and()
                .authorizeRequests()
                .antMatchers("/swagger-ui.html", "/swagger-resources",
                        "/configuration/ui", "/configuration/security",
                        "/v2/api-docs", "/webjars/**", "/product/**").hasRole(API_ROLE)
                .and()
                .httpBasic()
                .and()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.NEVER);
```

so when I open swagger-ui in the browser, it ask for authentication. And when I authenticate, I expect to see all the endpoints. 
I know only the endpoints starting with /product/ will work. and others will not work(That is expected behaviour)

This works in version 2.4.0 but not with any version after 2.4.0. I cannot see the endpoints itself.

Can you please suggest.Do I need to include any other patterns?

**Comment by dilipkrish** [comment]
Try changing `"/configuration/ui", "/configuration/security"` to "/swagger-resources/configuration/ui", "/swagger-resources/configuration/security"`

**Comment by pvpkiran** [comment]
Hi,
  Thanks for the reply, I got it work by doing this 

```
   .requestMatchers().antMatchers("/swagger-ui.html", "/swagger-resources/**",
                "/configuration/**",
```

Thanks
