### ISSUE TITLE
Setting / to open swagger-ui.html

### ISSUE THREAD

**Issue by binkley** [springfox/springfox#1650]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] SpringFox 2.6.1
- [x] Question. Is this a question about how to do a certain thing?

I'm looking for the shortest, cleanest way to get my Spring Boot app to open the UI page when client hits the root URL, rather than an index or other intro page.  Q13 in the FAQ addresses this, but the answer feels like too much magic on the part of a developer.  Ideally would be something simple and short.

So I'm unsure if my question reveals: 1) Poor reading on my part, 2) A gap in documentation, or 3) a feature request.

This is what I have now, creating a bean in some context (source is in Kotlin, but it's a straight translation of the equivalent Java, and compiles down to the same thing):

```
    @Bean
    open fun forwardToIndex(): WebMvcConfigurerAdapter
            = object : WebMvcConfigurerAdapter() {
        override fun addViewControllers(registry: ViewControllerRegistry?) {
            registry!!.addRedirectViewController("/", "/swagger-ui.html")
        }

        override fun addResourceHandlers(registry: ResourceHandlerRegistry) {
            registry.addResourceHandler("/swagger-ui.html**").
                    addResourceLocations("classpath:/META-INF/resources/swagger-ui.html")
            registry.addResourceHandler("/webjars/**").
                    addResourceLocations("classpath:/META-INF/resources/webjars/")
        }
    }
```

I experimented with other approaches, such as setting the `spring.application.index` property or using `forward:/swagger-ui.html` in a plain controller for `/` (not REST controller).  I saw various drawbacks, and used the verbose solution, above.

Among the drawbacks was an odd one: the `swagger-ui.html` page displayed, but showed **no** controllers.  (Also, not SpringFox's problem, using 302 for permanent redirect makes debugging in browser a challenge, as they reuse any previously cached result rather than contacting the server after I've changed code.  Least bad workaround was to use `curl` on command line and examine the headers and body, but then I don't see if controllers are present as no JavaScript is executed.)

**Comment by dilipkrish** [comment]
Not sure what the right solution is... may be easier to just include your own hand rolled solution to include the swagger-ui resources.

**Comment by binkley** [comment]
Thanks.  Ultimately I went with this bean in my top-level Spring configuration (again in Kotlin, equivalent to Java):

```
    /**
     * @see <a href="https://springfox.github.io/springfox/docs/current/#q13">Q. How does one configure swagger-ui for non-springboot applications?</a>
     * @todo This is less than elegant, can it be done better?
     * */
    @Bean
    open fun forwardToIndex() = object : WebMvcConfigurerAdapter() {
        override fun addViewControllers(registry: ViewControllerRegistry?) {
            registry!!.addRedirectViewController("/", "/swagger-ui.html")
        }
    }
```
