### ISSUE TITLE
Problem sprinfox custom model-schema

### ISSUE THREAD

**Issue by jvirriel** [springfox/springfox#1652]
Hello, I apologize in advanced for my awful english.
I'm having trouble specifying the Model Schema of our REST Services' API (and providing examples). 

As I understand it, springfox generates the Model Schema based on method's parameters and return type. The thing's that the client's specification require us to use one only parameter for every service, which is a single String containing all the data in json format, the same for the responses.
This causes springfox to generate an empty model (I asume this is because it's a single empty string).

The questions are: 
- Is there a way to specify a different model schema so I can tell the consumers of the API the form this json string should have?
- If so, what's the way?
- Also, Is there a way to include custom examples along with these custom Schema definitions?

I've been using version 2.5.0

Thanks in advanced for any help you could give me, this would solve a huge issue for me and all my coworkers.

**Comment by dilipkrish** [comment]
Not sure how to solve your problem. `@ApiParam` annotation doesnt support overriding types. And `@ApiImplicitParams` is not what we should be using for complex data types.

**Comment by jvirriel** [comment]
Are you working on adding support for this on a next version? If so, is there a way I can help on it?

**Comment by dilipkrish** [comment]
Possibly the next version will have some improvements to this use case
