### ISSUE TITLE
springfox-data-rest: 2.6.1 spring-data-rest: 2.6 RepositoryRestHandlerMapping constructor broken

### ISSUE THREAD

**Issue by cbbs** [springfox/springfox#1653]
Informational. This appears to be a spring-data-rest issue, [DATAREST-994](https://jira.spring.io/browse/DATAREST-994). EntityServicesProvider creates RepositoryRestHandlerMapping using a broken 2 arg constructor.

springfox-data-rest: 2.6.1 
spring-data-rest: 2.6 and 2.6.1

> **Caused by: java.lang.IllegalArgumentException: repositories is null
> 	at org.springframework.data.rest.webmvc.RepositoryRestHandlerMapping$RepositoryCorsConfigurationAccessor.<init>(RepositoryRestHandlerMapping.java:265) ~[spring-data-rest-webmvc-2.6.0.RELEASE.jar:na]**
> 	at org.springframework.data.rest.webmvc.RepositoryRestHandlerMapping.<init>(RepositoryRestHandlerMapping.java:105) ~[spring-data-rest-webmvc-2.6.0.RELEASE.jar:na]
> 	at org.springframework.data.rest.webmvc.RepositoryRestHandlerMapping.<init>(RepositoryRestHandlerMapping.java:83) ~[spring-data-rest-webmvc-2.6.0.RELEASE.jar:na]
> 	at springfox.documentation.spring.data.rest.EntityServicesProvider.<init>(EntityServicesProvider.java:74) ~[springfox-data-rest-2.6.1.jar:2.6.1]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_102-1-ojdkbuild]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_102-1-ojdkbuild]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_102-1-ojdkbuild]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_102-1-ojdkbuild]
> 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

**Comment by dilipkrish** [comment]
Thanks for reporting!

**Comment by cbenaveen** [comment]
@dilipkrish, is this issue fixed? can i get a SNAPSHOT version details to overcome this issue?

**Comment by dilipkrish** [comment]
No... ready = prioritized for this release.

ready -> in progress -> done

**Comment by niroussel** [comment]
I have the same issue: have you found a way to use springfox for data-rest?

**Comment by dilipkrish** [comment]
Looks like it depends on https://github.com/spring-projects/spring-data-rest/pull/257 landing in a release.

**Comment by pjskyboy** [comment]
@dilipkrish - will this make the 2.7.0 release do you think? If not is there a workaround - I have been trying to use the guidance on issue [699](https://github.com/springfox/springfox/issues/699) to generate swagger UI docs for CrudRepository services

**Comment by dilipkrish** [comment]
@pjskyboy I'd like to get it in... haven't figure out what the dependencies are.

**Comment by pjskyboy** [comment]
@dilipkrish I have a local build working off a fork of 2.6.2-SNAPSHOT can I make a pull request?

**Comment by dilipkrish** [comment]
Absolutely... that would be much appreciated. 👍

**Comment by dilipkrish** [comment]
Fixed via #1693
