### ISSUE TITLE
How to dynamically hide APIs based on incoming header ?

### ISSUE THREAD

**Issue by ptro-development** [springfox/springfox#1654]
Hi there,

Sorry if this has been already answered somewhere else, but I did not have much lack with finding an answer.

I am trying to find out if there is a way how to hide swagger API generated documentation based on value of incoming HTTP headers dynamically.

Example: Let say I want to make visible only GET API endpoints if the value of incoming header was "X"  (represents less privileged user)

/api/v1/album/{resourceId}
/api/v1/album/{resourceId}/song/{resourceId}

however if the same incoming header had value "Y" instead (represents more privileged users) also POST API endpoints would be visible on ../swagger-ui.html page.

/api/v1/album
/api/v1/album/{resourceId}/song

I am already handling a direct access to REST-API endpoints by my own authorisation module ( in spring security context) yet I would like to hide endpoints in documentation on ../swagger-ui.html page to avoid confusing any unprivileged users. The idea is that they should be able to see only smaller set of REST-API endpoints they have an access to.

Is there some springfox interface I can implement to hook logic for filtering visibility of generated API documentation ? If you could point me in right direction that would be great help.

Cheers,

ptro

**Comment by dilipkrish** [comment]
You can certainly `group` the API's that are shown by defining separate dockets. However swagger is not designed to provide dynamic runtime discovery.

**Comment by ptro-development** [comment]
Hi,

Thanks for your answer. I ended with multiple dockets as you suggested. One for standard users and another for admins.

Thanks for your time,

ptro

**Comment by kaustubh111** [comment]
How did u achieve this can you elaborate more.
Thanks in advance
