### ISSUE TITLE
Is there a way to hide properties in a model based on controller ?

### ISSUE THREAD

**Issue by yesvike** [springfox/springfox#1656]
For example
I have two controllers which has same model as request. Properties which are required in controller 1 are not required/not need to be present in controller 2.

**Comment by yesvike** [comment]
For example
I have two controllers which has same model as request. Properties which are required in controller 1 are not required/not need to be present in controller 2.

**Comment by MaksimOrlov** [comment]
Hi, @yesvike.

I think, you should look at the related issues #1356 and #807

**Comment by dilipkrish** [comment]
Its currently not possible. However there is a plan to support this in the future as @MaksimOrlov points out
