### ISSUE TITLE
Support @ApiImplicitParams at the class level

### ISSUE THREAD

**Issue by dan-kirberger** [springfox/springfox#1659]
Feature request: Support the @ApiImplicitParams annotation at the class level. It was recently updated in swagger-core to be applicable to the class level.

We use this feature to add a parameter to every controller mapping asking for a special auth header:
`@ApiImplicitParams({@ApiImplicitParam(name = "Authorization", value = "Authorization token", required = true, dataType = "string", paramType = "header", defaultValue = "Bearer X")})`

It would be handy to annotate the controller and get this automatically on every endpoint.

For now we have created a custom annotation to at least make our controller code look cleaner:
```
@Inherited
@Documented
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@ApiImplicitParams({@ApiImplicitParam(name = "Authorization", value = "Authorization token", required = true, dataType = "string", paramType = "header", defaultValue = "Bearer X")})
public @interface AddSwaggerToken {
}
```

We then simply annotate all controller methods with @AddSwaggerToken

**Comment by dilipkrish** [comment]
You can already do this at the docket see `Docket#globalOperationParameters`

**Comment by clementdevos** [comment]
:+1: we also need this merge :)

**Comment by dan-kirberger** [comment]
globalOperationParameters did the job just fine for us (in fact, if anything it was better than this feature request), though we were adding the same parameter to every endpoint globally.

**Comment by clementdevos** [comment]
Ok I'll look into it but i'd like to factorize some of our parameters into this kind of annotations.

**Comment by watery** [comment]
@dilipkrish `Docket#globalOperationParameter()` does it, but IMHO this should remain open as there currently is no way to declare implicit parameters for all resources contained in a single `@RestController` &mdash; hence the need to support the annotation at class level.

**Comment by dilipkrish** [comment]
💯 agree. I think there is should be another issue for that...

**Comment by watery** [comment]
Done: #2550
