### ISSUE TITLE
@Deprecated is not supported？？？

### ISSUE THREAD

**Issue by yuxiaoqi-seven** [springfox/springfox#1663]

**Comment by dilipkrish** [comment]
It is on operations.

**Comment by yuxiaoqi-seven** [comment]
config
```
@Bean
public Docket createAlarmRestApi() {
		return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).groupName("告警").select().apis(RequestHandlerSelectors.basePackage("com.harmazing.openbridge.api")).paths(Predicates.or(PathSelectors.regex("/api/v1/alarms.*|/api/v1/teams.*"))).build();
}
```
api
```
       @Deprecated
	@RequestMapping(value = "/getAllAlarmCount", method = RequestMethod.GET)
	@ApiOperation(value = "获取告警数", notes = "获取告警数")
	public ResponseEntity<?> getAllAlarmCountDTO(HttpServletRequest request) {
		try {
			IUser user = WebUtil.getUserByRequest(request);
			String tenantId = user.getTenantId();
			String userId = user.getUserId();
			Map<Object, Object> allAlarmCount = super.getAllAlarmCount(tenantId, userId);
			return new ResponseEntity<>(allAlarmCount, HttpStatus.OK);
		} catch (Exception e) {
			logger.error("失败", e);
			return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
		}
	}
```
view in swagger
![image](https://cloud.githubusercontent.com/assets/17722295/23207448/4d02b1fa-f92c-11e6-82e8-dee6a90fffcb.png)
but i want view like this
![image](https://cloud.githubusercontent.com/assets/17722295/23207739/50572cea-f92d-11e6-884d-2c1e731f38fb.png)

**Comment by dilipkrish** [comment]
Per [the tests](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/test/resources/contract/swagger/declaration-pet-service.json#L376), given [this controller definition](https://github.com/springfox/springfox/blob/master/springfox-petstore/src/main/java/springfox/petstore/controller/PetController.java#L167-L174) it should be supported. If it doesnt show up it might be an issue with either swagger-ui or that you're running with an older version of swagger-ui.

**Comment by yuxiaoqi-seven** [comment]
my version is old.  thank you!
