### ISSUE TITLE
/v2/api-docs not showing. 404 Status

### ISSUE THREAD

**Issue by battamirsugarjav** [springfox/springfox#1665]
I've tried with many maven dependencies in a non-spring-boot application. but none seem to work. I'm so annoyed. plz help. 

  <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.3.1</version>
        </dependency>

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.3.1</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-common</artifactId>
            <version>2.3.1</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-spring-web</artifactId>
            <version>2.3.1</version>
        </dependency>

The URL with context root is valid, pls don't respond with classical check context root....http://localhost:8080/swagger-ui.html, http://localhost:8080/v2/api-docs etc..

I got a stackoverflow from lots of these : springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:86)

The http://localhost:8080/swagger-ui.html shows empty.  The Configuration is correct. Don't know what else to try.

**Comment by acolak** [comment]
Didy you try add "?public-api" param to your url. Please note that public-api name depends your swagger conf.

**Comment by dilipkrish** [comment]
@acolak Thanks for trying to help, but not sure adding `public-api` has anything to do with it.

> Didy you try add "?public-api" param to your url. Please note that public-api name depends your swagger cons.

@battamirsugarjav Instead of being **_annoyed_**, It would help if you could submit issues with [more details](https://github.com/springfox/springfox/blob/master/.github/ISSUE_TEMPLATE.md). Cannot help without more details of how your app is configured etc. Also you need to use 2.6.1 which is the supported version.

**Comment by battamirsugarjav** [comment]
Thanks for reply @dilipkrish. 

The Bean Docket definition is here : 

@Configuration
public class SwaggerConfig {
    @Bean
    public Docket swaggerSpringfoxDocket() {
        return new Docket(DocumentationType.SWAGGER_2).forCodeGeneration(true)
                    .genericModelSubstitutes(ResponseEntity.class)
                    .select()
                    .paths(PathSelectors.regex("/api/.*"))
                    .build().directModelSubstitute(LocalDate.class,String.class)
                    .genericModelSubstitutes(ResponseEntity.class);
    }
}

The WebMvcConfigurerAdapter is annotated with : 

@Configuration
@EnableWebMvc
@EnableSpringDataWebSupport
@EnableSwagger2

and has the method which maps to swagger resources :   

public void addResourceHandlers (ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
}

**Comment by battamirsugarjav** [comment]
this swagger shit sucks.

**Comment by liubo404** [comment]
too complicated to use....

**Comment by hypery2k** [comment]
just as a hint: If you configured a group you have to append it as a param, e.g. /v2/api-docs?group=my-group

**Comment by jackmatt2** [comment]
@hypery2k works thanks. I did indeed start using groups before I discovered this issue in my own project.  The 404 page that renders is very confusing as a default response.

**Comment by vishwass** [comment]
@battamirsugarjav 
I was facing the same issue with 2.4.0 . I guess the version has nothing to do with this.
I fixed this issue by adding the following code in swagger UI.
	@Bean 
	public Docket api(){
		return new Docket(DocumentationType.SWAGGER_2).select()                                  
		          .apis(RequestHandlerSelectors.any())              
		          .paths(PathSelectors.any())                          
		          .build();     
	}
`}`

**Comment by Jovons** [comment]
why a query param has anything to do with 404???
