### ISSUE TITLE
How to have swagger-ui reflects the format produced by custom HttpMessageConverter

### ISSUE THREAD

**Issue by tamseo** [springfox/springfox#1669]
Hi,

I am using springfox-swagger to generate swagger files in my Spring boot project, all configuration works fine but I have custom converters to convert the payload and the generated files and swagger-ui don't reflect the converted format.

Any way to "register" custom converters to Swagger configuration?

Thanks

**Comment by dilipkrish** [comment]
That is not possible. Most likely you're trying to instruct jackson to provide output in a certain way via the message converters. The only way for us to infer that is to provide alternate types to the docket.

**Comment by tamseo** [comment]
Thanks @dilipkrish for the answer.
