### ISSUE TITLE
Swagger-UI giving 405 (Method not allowed) when called

### ISSUE THREAD

**Issue by GarrettMosier** [springfox/springfox#1672]
I've added the swagger and swagger-ui dependencies as well as the "@enableSwagger2" annotation. When I go to localhost:8080/swagger-ui.html, I get the error message pasted below. This error is fixed by changing another endpoint which has the path of "/**". The part which makes me think this is a bug in springfox is that all the other endpoints interact nicely with that method (which is used for CORS) whereas it doesn't seem to get past the annotation for requestMapping when using swagger-ui. Please let me know if any other information is required. 

```json
{
    "error": "Method Not Allowed",
    "message": "Request method 'GET' not supported",
    "report": "org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:207) at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:374) at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:314) at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:61) at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:352) at org.springframework.web.servlet.DispatcherServlet.getHandler(DispatcherServlet.java:1131) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:936) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745) ",
    "status": "405"
}
```

**Comment by dilipkrish** [comment]
I really doubt this is a bug with springfox. Have you tried the same request with a different client like Postman or even just a plain curl?

**Comment by GarrettMosier** [comment]
I've tried both of those and get the same error.

**Comment by GarrettMosier** [comment]
Are there any other steps you'd like for more debugging information?

**Comment by dilipkrish** [comment]
Have you tried using the the [cors annotation](https://spring.io/guides/gs/rest-service-cors/)

**Comment by GarrettMosier** [comment]
I have not but I'd strongly prefer not to as it is central to our code
base.

On Feb 13, 2017 7:44 PM, "Dilip Krishnan" <notifications@github.com> wrote:

Have you tried using the the cors annotation
<https://spring.io/guides/gs/rest-service-cors/>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/springfox/springfox/issues/1672#issuecomment-279599858>,
or mute the thread

**Comment by dilipkrish** [comment]
Not sure what the best way to do it is. Swagger-ui that comes with this project is really a convenience. Its difficult to address specific usages in a library.

**Comment by GarrettMosier** [comment]
I feel like this would be a common use case as a lot of teams will have the need for custom CORS implementations. Do you have any ideas on how to fix this issue for myself as it appears Spring and Swagger-UI are competing for path resolution.

**Comment by codeMmaster** [comment]
Hi @GarrettMosier 

Are you using Spring boot?

**Comment by GarrettMosier** [comment]
Yes

**Comment by jaychang9** [comment]
When I use @RestController("goods")     I got the error
` {"timestamp":1490883127218,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'GET' not supported","path":"/paycenter/swagger-ui.html"} `
and @RestController @RequestMapping("goods") is right

**Comment by dhermanns** [comment]
Why has this issue been closed?

Seems to be the same problem for me as for jaychang9:

This code leads to a HTTP 405 error:

```
@RestController
public class VerteilOrganisationenController {

	@RequestMapping(value = "/verteilorganisationen", method = RequestMethod.GET)
	public Iterable<VerteilOrganisationenEntry> getVerteilOrganisationen() {

		...
	}
...
}
```

This works fine:

```
@RestController
@RequestMapping("/")
public class VerteilOrganisationenController {

	@RequestMapping(value = "/verteilorganisationen", method = RequestMethod.GET)
	public Iterable<VerteilOrganisationenEntry> getVerteilOrganisationen() {

		...
	}
```

So adding @RequestMapping("/") is a quick workaround - but this looks like an error. Or do a miss something?

**Comment by dilipkrish** [comment]
Will investigate

**Comment by navinvishy** [comment]
Just in case it helps, I ran into this issue because I had endpoints with request mappings that had path variables of this form: /{var}. Turns out that this is an issue for *both* GET and POST endpoints i.e. GET /{var} and POST /{var} block swagger-ui. Once I made the paths more specific, I got swagger-ui to work.

**Comment by henriquesschmitt** [comment]
@navinvishy and is there any solution to this problem?

**Comment by dilipkrish** [comment]
@henriquesschmitt One thing to try is to check if curl/postman client works with your endpoints. That way you'll know if its a problem in the endpoints or if its a problem with springfox

**Comment by henriquesschmitt** [comment]
@dilipkrish Yes, in postman it works perfectly, so much so that if I access springfox directly at the address of the service everything works perfectly, but when I route the service via zuul in api-gateway, error 405 occurs

**Comment by dstarcev** [comment]
Using `@RestController("/some-path")` causes many problems, not only with Swagger UI.
In RestController's javadoc we can see the following:
```/**
	 * The value may indicate a suggestion for a logical component name,
	 * to be turned into a Spring bean in case of an autodetected component.
	 * @return the suggested component name, if any (or empty String otherwise)
	 * @since 4.0.1
	 */```

So this property is not about paths at all and should not be used for that. The right way to set the base path for a rest controller is:
```
@RestController
@RequestMapping("/some-path")
```

**Comment by anijadhav** [comment]
I had the same issue but I have question here.
I'm writing  as server.servlet.path=/xyz path in my **.properties** file so its not picking it from my **.properties** file 
can anyone one help me here?

**Comment by UngeheurenUngeziefer** [comment]
The issue might be related to a forgotten path in the @PutMapping/@GetMapping annotations in the controller class.

**Comment by igayashan** [comment]
I had a similar issue in one of my projects with the openapi docs.. the issue was caused by the endpoints that was configured in such a was that they started with two dynamic path params for getting ids.. {{base_url}}/{path-param-1}/{path-param-2}. since the default swagger ui endpoint is colluding with that ANT Pattern Dispatcher Servlet is throwing this error of 405. 

if you could define the value for **springdoc.swagger-ui.path** in the property file to avoid that pattern in the endpoint. you should be able to access the swagger ui with that path

eg: 
springdoc.swagger-ui.path=/project-name/swagger/index.html
