### ISSUE TITLE
Why generic method names are being generated for Spring Data Rest?

### ISSUE THREAD

**Issue by tahir-gvs** [springfox/springfox#1675]
I am using spring-fox-swagger2 and spring-fox-data-rest version 2.6.1

I have just added following annotations on my configuration:
@EnableSwagger2
@Import({springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration.class})

I have entities like Business Category and Product, the generated swagger is giving operationId that are generic sounding like
getCollectionResourceCompactUsingGET
getCollectionResourceCompactUsingGET_1
getCollectionResourceCompactUsingGET_2

Instead of something like 
getProductsCollection
getCategoryCollection
getBusinessCollection

Am I missing some configuration or is this a limitation of spring-fox-data-rest?

I am using the swagger json to generate client side code which is using operationIds to name the client methods. Clearly such method names are not helpful for client-side developers.

**Comment by dilipkrish** [comment]
@tahir-gvs Thanks for noticing that. Yes that would be nice to have it not be a generic method name.

**Comment by tahir-gvs** [comment]
Thanks @dilipkrish 
So are you planning to address this in near future?
