### ISSUE TITLE
OAuth2 request adds `vendorExtension` scope to all auth requests

### ISSUE THREAD

**Issue by pmlido** [springfox/springfox#1677]
I use springfox-swagger2 and springfox-swagger-ui version 2..6.1 

I configured Swagger to use Oauth2, but when I click Authorize, first it displays a dialog where I can select scopes and it adds: " vendorExtensions [object Object]" as an option.
And even if I dont select the vendorExtenstions, it adds it to the scope:

Swagger sends the following Oauth2 request:

https://authserver/https/api/rest/v3.0/oauth/authorize?
response_type=token&
redirect_uri=http%3A%2F%2Flocalhost%3A20300%2Fwebjars%2Fspringfox-swagger-ui%2Fo2c.html&
realm=undefined&
client_id=swagger&
scope=report%2C**vendorExtensions**&
state=oauth2schema

I beleive the problem is addressed in swagger-ui : https://github.com/swagger-api/swagger-ui/issues/2483

**Comment by dilipkrish** [comment]
I believe it will be fixed via [this commit ](https://github.com/springfox/springfox/commit/d8bdf6ba8819415a3af2e74a4e00d61ff3bd3e5b) when released.

**Comment by mbogusiak** [comment]
Hi @dilipkrish ,
do you know (roughly) when final version 2.7 is going to be released?

--
Thanks
Marcin

**Comment by dilipkrish** [comment]
Hopefully this month... trying to wrap-up the backlog of bugs
