### ISSUE TITLE
handling location headers and different models for inbound and outbound

### ISSUE THREAD

**Issue by jbedalov** [springfox/springfox#1679]
We are using 2.4.0 and wanted to know if there's a simple way to handle the following use case with our APIs.

Suppose a resource is created in the following manner

`POST /resource
{ "key":"value"}
returns
void body with location header /resource/123`

When calling get we have 

`GET /resource/123
returns
{ "resourceId" : "123", "key":"value" }`

Is there a simple way to achieve this where the inbound and outbound objects are similar aside from a unique identifier? Is there a way to handle setting location header with this technique as well?

**Comment by dilipkrish** [comment]
There isn't a good way to do this other than having different models for the two endpoints, but there have been a few suggested alternatives like this => #601
