### ISSUE TITLE
Using a different constructor for different response statuses?

### ISSUE THREAD

**Issue by filpano** [springfox/springfox#1681]
Hello everyone! I have custom `HttpErrorResponse` class that I use for non-2xx responses. This is rendered how I wish it to, but there is a catch:

I have two constructors for this class: one that takes a `code` and a `message`, and one that additionally takes a `List<FieldError>`, for example.

I wish to use the second constructor for `400 Bad Request` responses in which I fill out the list of fields that yielder validation failures, and the first constructor for all other non-2xx response statuses. Unfortunately, Swagger UI renders only the second constructor in all cases.

Is it possible to achieve this, or would I need to split my response classes (something I want to avoid because there is not much point in splitting them, logically)?

**Comment by dilipkrish** [comment]
This is a similar issue to #601. Unfortunately today you'd have to split the objects to get it to appear differently.
