### ISSUE TITLE
Swagger POST String Body gets enclosed in additional quotes

### ISSUE THREAD

**Issue by StasKolodyuk** [springfox/springfox#1684]
When trying to post string value via swagger-ui, the request body gets enclosed into additional quotes.

Here's my request mapping:
```
    @RequestMapping(value = "/echo", method = POST, consumes = "text/plain", produces = "text/plain")
    public String echo(@RequestBody String str) {
        return str;
    }
```

Here's swagger-ui

![image](https://cloud.githubusercontent.com/assets/7199271/23136112/3b6258be-f7ac-11e6-92ba-c26e2d2987be.png)

As you can see, string gets enclosed with additional quotes that is not satisfactory for my needs.

I've created a repo demonstrating the issue https://github.com/StasKolodyuk/swagger-issue-demo

**Comment by dilipkrish** [comment]
Seems like a bug in [swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by StasKolodyuk** [comment]
I've noticed that this issue appears only when using `UiConfiguration` constructor with `jsonEditor = true`.

**Comment by dilipkrish** [comment]
Hmmm.. Not sure without looking at the swagger-ui code.
