### ISSUE TITLE
can you delete  springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator  file?

### ISSUE THREAD

**Issue by huqiao** [springfox/springfox#1685]
![image](https://cloud.githubusercontent.com/assets/3814630/23159760/fbd6c208-f85e-11e6-8c68-625b8db01e54.png)

for Generator project  ,will make method name with nickname+"_"+index  ;

**Comment by dilipkrish** [comment]
@huqiao No we cannot. We need that so that we generate unique operation names. If you want to override the name you can use the @ApiOperation annotation.
