### ISSUE TITLE
Swagger-UI using Spring boot loaded in AWS beanstalk: 404 error config../ui

### ISSUE THREAD

**Issue by codeMmaster** [springfox/springfox#1686]
Please take the time to search the repository, if your question has already been asked or answered.

- [2.6.1] What version of the library are you using?

What kind of issue is this?

When reporting a bug, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue

I got the latest version of swagger 2 and swagger ui:  2.6.1

This is my swagger config

```java
@Configuration
@EnableSwagger2
public class SwaggerConfig {                                    
    @Bean
    public Docket api() { 
        return new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())                          
          .build();                                           
    }
}
```

My Main App.

```java
@SpringBootApplication
@EnableCaching
@EnableScheduling
public class ExternalCloudApplication {

	public static void main(String[] args) {
		new SpringApplicationBuilder(ExternalCloudApplication.class)
			.properties("spring.config.name:application,dev-application")
			.build()
			.run(args);
	}
}
```

On Localhost it works fine!
`http://localhost:8080/swagger-ui.html`

but on cloud...I get this;

![image](https://cloud.githubusercontent.com/assets/20556254/23207492/bfe00064-f8f1-11e6-972a-83b98d7d9612.png)

I am pretty new to Swagger and Spring boot

Thanks in advance!!

 - [ Yes] Question. Is this a question about how to do a certain thing?

**Comment by dilipkrish** [comment]
Could you tell me where the api-docs are available... it should be something like this...

`http://cloud-dev.changetocomm.com[/some-path]/v2/api-docs`

**Comment by codeMmaster** [comment]
Hmm.. I don't know do I have to do anything besides this? I might be missing steps.

**Comment by codeMmaster** [comment]
http://localhost:8080/v2/api-docs works for me but not online on cloud

**Comment by dilipkrish** [comment]
I know... Im just trying to understand how your cloud host is configured. So if you can find out the exact path that works in the cloud to show the api-docs that will be helpful.

**Comment by codeMmaster** [comment]
I have not configured something for this at all. I wouldn't know where to look unfortunatly could you direct me where to look please?

**Comment by dilipkrish** [comment]
The logs will give you a clue

**Comment by codeMmaster** [comment]
Hii, @dilipkrish I have not been able to find anything. 

I have tried looking in the logs when uploading the war file; nothing there. 

I have also tried looking at the logs when building the application. This is the following output:

![image](https://cloud.githubusercontent.com/assets/20556254/23360055/9fdb4c32-fce9-11e6-8cee-acf50aab3d6b.png)

I have also looked at the logs when building a war but nothing there in particular. 

The web application uses Spring boot + build is used by gradle and package structure is
 *.cloud > ExternalCloudApplication
*.cloud.config > SwaggerConfig

project name caseware-cloud-project

**Comment by codeMmaster** [comment]
The application is deployed on Amazon Beanstalk on a Tomcat Environment

**Comment by codeMmaster** [comment]
I have come up with the solution:

`
public class ExternalCloudApplication extends SpringBootServletInitializer{

	public static void main(String[] args) {
		SpringApplication.run(ExternalCloudApplication.class, args);
		
	}
}`

When you deploy onto AWS Tomcat instance you will need to deploy an war. You should not use gradle bootRepackage that would package within the war an embedded tomcat server; you could guess that it goes wrong there. 

No need for "@CrossOrigin" as well in any of the application this way. 

org.springframework.boot.web.support.SpringBootServletInitializer

An opinionated WebApplicationInitializer to run a SpringApplication from a traditional WAR deployment. Binds Servlet, Filter and ServletContextInitializer beans from the application context to the servlet container.
