### ISSUE TITLE
Swagger-Ui not showing any controller even though api-docs are there

### ISSUE THREAD

**Issue by jvirriel** [springfox/springfox#1688]
I'm trying to make a single REST controller integrated with Springfox using only Java Based configuration.

The json is being generated correctly so Swagger UI should display the doc as well, but this is not happening, the UI is shown as well but with no documentation in it.

I'm using Springfox 2.5.0
Here are the main parts of the configuration:
**Swagger Configuration**
```java
@EnableSwagger2
 public class ConfigSwagger {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("Información")
                .build();
    }

}
```

**MVC configuration**
```java
@EnableWebMvc
@Configuration
@Import(ConfigSwagger.class)
@ComponentScan(basePackages = {"confbase"})
public class MvcConfig extends WebMvcConfigurerAdapter{

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/resources/**").addResourceLocations("/resources/");
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
    @Override
    public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
        configurer.enable();
    }
}
```

**WebAppInitializer**
```java
@Configuration
public class WebAppInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {

    @Override
    protected Class<?>[] getRootConfigClasses() {
        return new Class[] { MvcConfig.class, ConfigSwagger.class };
    }

    @Override
    protected Class<?>[] getServletConfigClasses() {
        return null;
    }

    @Override
    protected String[] getServletMappings() {
        return new String[] { "/api/*" };
    }

}
```

**The Controller**
```java
@Controller
@RestController
public class AController {
    @RequestMapping(method = RequestMethod.GET, value = "/string")
    public String getString() {
        return "String";
    }
}
```

They're all in the same package.

I don't know what the problem could be.
Thanks in advanced for any help you could give!

**Comment by dilipkrish** [comment]
Would you mind trying with 2.6.1?

Also since your servlet is looking for apis at `/api/*` you might have to play around with your configuration a bit. Try changing that to `/` and work yourself up to `/api`

**Comment by jvirriel** [comment]
Thanks DIlip.

Tried changing the mapping to /, that way the api-docs  don't get generated, I tried that solution with both versions 2.6.1 and 2.5.0 but doesn't seem to be any difference

**Comment by codeMmaster** [comment]
Hi, @jvirriel 

Are you perhaps using spring boot?

**Comment by jvirriel** [comment]
Hi @codeMmaster

No,  i'm using JBoss as server

**Comment by dilipkrish** [comment]
@jvirriel What do you see when you navigate to 
- `/api/v2/api-docs` and 
- `/v2/api-docs`

**Comment by chanduthedev** [comment]
I also faced similar issue with swagger version 2.7.0. This got resolved by using 2.6.1 swagger version

**Comment by vsix27** [comment]
it worth to check pom.xml for presence of 
      <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>2.....</version>
    </dependency>

**Comment by IamGiel** [comment]
any updates here?  

Im getting:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Apr 07 14:02:25 EDT 2019
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by syeddanishzakir8080** [comment]
I'm facing the same issue. Even though I have added the swagger-ui but I can't still figure out why the ui is getting 404.

**Comment by vsix27** [comment]
Do you min sharing your project?

Sent from my iRotary phone

On Mar 28, 2020, at 4:48 PM, syeddanishzakir8080 <notifications@github.com> wrote:

﻿

I'm facing the same issue. Even though I have added the swagger-ui but I can't still figure out why the ui is getting 404.
