### ISSUE TITLE
XMLAttribute is ignored

### ISSUE THREAD

**Issue by JuanMallorca** [springfox/springfox#1695]
I am using Springfox to generate the documentation for some Rest Services which are using objects with XmlAttributes but these are not generated in the json generated by springfox.

How can I solve this problem?

Thanks in advance.

**Comment by dilipkrish** [comment]
You need to configure the `ObjectMapper` the [jackson jaxb module](http://wiki.fasterxml.com/JacksonJAXBAnnotations). There is an example in the docs on how to do that.
