### ISSUE TITLE
because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled

### ISSUE THREAD

**Issue by Jarvens** [springfox/springfox#1696]
--Swagger2  
--version 2.2.2
this is my pom.xml
`<dependencies>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.2.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.2.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.hsqldb</groupId>
			<artifactId>hsqldb</artifactId>
			<scope>runtime</scope>
		</dependency>
		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.21</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
			<version>3.0.4.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
		</dependency>
	</dependencies>`

error happend 
`Refused to execute script from 'http://localhost:8080/webjars/springfox-swagger-ui/lib/underscore-min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
swagger-ui.html:1 Refused to execute script from 'http://localhost:8080/webjars/springfox-swagger-ui/lib/backbone-min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
swagger-ui.html:1 Refused to execute script from 'http://localhost:8080/webjars/springfox-swagger-ui/swagger-ui.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
swagger-ui.html:1 Refused to execute script from 'http://localhost:8080/webjars/springfox-swagger-ui/springfox.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
swagger-ui.html:1 Refused to execute script from 'http://localhost:8080/webjars/springfox-swagger-ui/lib/highlight.7.3.pack.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
swagger-ui.html:1 Refused to execute script from 'http://localhost:8080/webjars/springfox-swagger-ui/lib/marked.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
swagger-ui.html:1 Refused to execute script from 'http://localhost:8080/webjars/springfox-swagger-ui/lib/swagger-oauth.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
swagger-ui.html:27 Uncaught ReferenceError: $ is not defined`

**Comment by dilipkrish** [comment]
Could you uprev the library version to 2.6.1 please. 2.2.2 is not supported

**Comment by Jarvens** [comment]
@dilipkrish   I found that both the 2.6.1 version and the 2.7.0 version  are problematic

**Comment by dilipkrish** [comment]
Not really sure what the problem is.

**Comment by amittrips** [comment]
I am getting the same issue on weblogic. I have created a war file and deploying on Tomcat works perfectly and swagger-ui comes up however on weblogic I get an error:
Refused to execute script from 'webjars/springfox-swagger-ui/springfox.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Could you please look into this?

**Comment by dilipkrish** [comment]
Cannot really unfortunately  😞  Seems like web logic is serving it up as text/html. It is clearly a JavaScript file that is included as the [right mime type](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/swagger-ui.html#L29).

**Comment by amittrips** [comment]
The problem is with the swagger-ui html file only since rest endpoint v2/api-docs seem to be working really  well, when I remove spring security from application the errors in console disappear about the mime type however UI does not load well still.
