### ISSUE TITLE
[BUG] 2.7.0 custom swagger endpoint returns a 404. Default endpoint works.

### ISSUE THREAD

**Issue by ahatzz11** [springfox/springfox#1698]
This was first mentioned in #1692, but I'm submitting a new issue.

version: `2.7.0-SNAPSHOT`

The custom endpoint that I created now returns a 404. 

`xxxxxxx.properties`:
```
#springfox
springfox.documentation.swagger.v2.path=/api-docs
```

On `2.6.1` I can hit `http://localhost:8083/api-docs?key=123`  and I get the generated swagger file. 

When I run my app with `2.7.0-SNAPSHOT`, this same page returns a 404. The default endpoint works just fine: `http://localhost:8083/v2/api-docs?key=123`

Here's a log:
```
{
    "@timestamp":"2017-02-27T19:45:05.063-06:00",
    "message":"Request Complete",
    "level":"INFO",
    "api-version":"v2",
    "api-request-method":"GET",
    "api-response-status":"404",
    "api-request-uri":"/api-docs?key=123",
    "api-request-headers":{
        ...
    }
}
```

**Comment by dilipkrish** [comment]
@ahatzz11 Is this a boot app or a regular spring-mvc app?

**Comment by ahatzz11** [comment]
@dilipkrish It's a springboot app.
