### ISSUE TITLE
Make ApiResourceController methods public

### ISSUE THREAD

**Issue by psyho** [springfox/springfox#1701]
[ApiResourceController](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/ApiResourceController.java) is a `public` class with no `public` methods in it. It would be useful to make the 3 actions that it defines `public`.

In my use case, I need to put certain additional annotations on these methods to make them publicly visible to our routing library. I'd like to either be able to inherit from the class or delegate to the controller instance from my own controller to achieve this, but with the code as is, I have to define my class within the `springfox.documentation.swagger.web` package.

**Comment by dilipkrish** [comment]
Would you mind sharing what it is in the controller that you need to make public to your routing library? Seems like your routing library shouldn't have to care about this class.

**Comment by psyho** [comment]
@dilipkrish I need to add a certain annotation to each of these methods, so that they are detected by the piece of code that registers routes in external configuration, so that they can later be accessed through our level 7 load balancer/router. Routes published by this controller are used by Swagger UI, which is the thing that I want to make accessible in the first place.

Making these public will also simplify cases when people want to remap these endpoints to other URLs. Right now you have to use redirects for this.
