### ISSUE TITLE
Spring-Data-Rest with Springfox "sometimes" exposes json correctly

### ISSUE THREAD

**Issue by mtung2017** [springfox/springfox#1709]
I'm using springfox 2.6.1 on all components (ui,fox,rest) and for some weird reason sometimes swagger let's me fire off my api requests and return the proper payload of json but other times it would send just plain text-uri back.

I've been trying to figure this out for days and am stuck as to why this happens.

**Comment by dilipkrish** [comment]
Please provide [more details](https://github.com/springfox/springfox/blob/master/.github/ISSUE_TEMPLATE.md)
