### ISSUE TITLE
How to select the Entity endpoints generated by Spring Data Rest?

### ISSUE THREAD

**Issue by pluttrell** [springfox/springfox#1712]
Using v2.6.1 and following [these instructions](https://springfox.github.io/springfox/docs/snapshot/#springfox-spring-data-rest), I am able to get the search endpoints to show up, but not the entity endpoints, such as viewing a single value.

Using the following class to configure springfox:

```
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig {

  @Bean
  public Docket api() {

    return new Docket(DocumentationType.SWAGGER_2)
       .select()
       .apis(RequestHandlerSelectors.any())
       .paths(PathSelectors.any())
       .build()
       .apiInfo(buildMetadata());
  }

  private ApiInfo buildMetadata() {
    return new ApiInfoBuilder()
        .title("....")
        .description(".....")
        .version("1.0")
        .contact(new Contact("John Smith", null, "jsmith@example.com"))
        .build();
  }

}
```

I can see a ton of endpoints in Swagger, including really the only two that I want: 
* {My Type} Entity: Repository Entity Controller 
* {My Type} Entity Search: {My Type} Repository

I know that I can trim it down to just the Entity Search endpoints, by specifying the following to the `Docket` construction: `.apis(RequestHandlerSelectors.basePackage({my-repository-class}.class.getPackage().getName()))`, where `{my-repository-class}` is the interface where I've defined my Repository, which is annotated with `@RepositoryRestResource`.

How do I select/specify the Entity Controller calls themselves, which is auto generated by Spring Data Rest?

**Comment by dilipkrish** [comment]
By using the `RequestHandlerSelectors#basePackage("org.springframework.data.rest.webmvc")` predicate. If u want to combine the two you need to use the `Predicates#or`

**Comment by pluttrell** [comment]
Many thanks. That might be a good thing for the docs ;)

**Comment by dilipkrish** [comment]
@pluttrell yr welcome. Would really appreciate if you be able to contribute to [improving it](https://github.com/springfox/springfox/blob/master/docs/asciidoc/getting_started.adoc#springfox-spring-data-rest) via a PR!

**Comment by florianrusch** [comment]
I think to create a PR to integrate it in the docu. I'm just not sure on which section this shoud be. @dilipkrish what do you think?

**Comment by dilipkrish** [comment]
@florianrusch where-ever you think it will be most helpful if you were to read through the documentation.
