### ISSUE TITLE
swagger host not setting to empty string

### ISSUE THREAD

**Issue by nitin02** [springfox/springfox#1715]
Using the latest version 2.6.1.

I have set the swagger host to an empty string ("") using the Docket.host() method. However the swagger JSON generated, overrides this parameter and shows the machine's IP instead.

For example, my swagger JSON contains,

"host":"127.0.0.1" {or whatever IP my server is running in}

Please note, setting host to other values work.

I want to set it to "" as the default behavior of the **swagger-js** library is to default **host** to the domain name of my web-application which makes the request (API call).

Please identify the bug which causes this issue.

**Comment by dilipkrish** [comment]
That is correct and by design. Your use case of setting it to blank is not clear to me. In what condition would you set it to blank?

**Comment by nitin02** [comment]
The swagger-js library is the use case.

If the host is empty, the js client defaults the host name to whatever
domain the js client method is called from.

**Comment by cyril2maq** [comment]
I am not sure why it is closed ?

The use case seems important : when host is empty, then the default behavior of swagger-ui is to use the current host. When your server is behind a proxy, he may not be aware of the actual FQDN; hence have no idea of the host to set. Leaving it blank is usefull in that case.

Furthermore, overriding an empty host by some other value is a good idea; but it may be best not to define this behavior in the Swagger2Controller; where we do not have a hand to cancel this behavior. Maybe with a properties like 'allowEmptyHost' or in the Docket config?

On my hand, to achieve an empty host, I had to duplicate the @EnableSwagger2 and @Swagger2DocumentationConfiguration annotations to add an exclusion on Swagger2Controller.class in @ComponantScan; and 'duplicate' Swagger2Controller without the forced host.

**Comment by nitin02** [comment]
Please consider the use-case mentioned and let us know on the status of this issue
