### ISSUE TITLE
Not able to create swagger documentation for MultipartHttpServletRequest

### ISSUE THREAD

**Issue by anthammas** [springfox/springfox#1716]
Hi. I am trying to create documentation for my controller having a POST method with a 'MultipartHttpServletRequest' parameter. My controller code is

```
@ApiOperation(value = "upload a specific preview image file", notes = "", response = ImageInfo.class)
	@io.swagger.annotations.ApiResponses(value = {
			@io.swagger.annotations.ApiResponse(code = 201, message = "upload a preview image file successful") })
	@RequestMapping(value = "/v1/a/{id}/upload", produces = {
			APPLICATION_JSON_VALUE }, method = RequestMethod.POST)
	public ImageInfo uploadImage(
			@ApiParam(value = "unique id", required = true) @PathVariable("id") Long adId,
			@ApiParam(value = "file detail") @RequestParam("fileRequest") MultipartHttpServletRequest request) { ... }
```
But I am getting the following error

```
Swagger Error
Not a valid parameter definition
Jump to line 1090
Details
 Object
code:  "ONE_OF_MISSING"
 params: Array [0]
message:  "Not a valid parameter definition"
 path: Array [5]
schemaId:  "http://swagger.io/v2/schema.json#"
 inner: Array [2]
level: 900
type:  "Swagger Error"
description:  "Not a valid parameter definition"
lineNumber: 1090
```
I am using the following properties in my pom.xml

```
<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.2.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.2.2</version>
		</dependency>
<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-jersey-jaxrs</artifactId>
			<version>1.5.7</version>
		</dependency>
```
What should be annotation to be used for the MultipartHttpServletRequest so that my documentation becomes valid. Can anyone help me out here. Thanks.

**Comment by dilipkrish** [comment]
Couple of things... 
- please upgrade to `2.6.1`
- There is no need to add `swagger-jersey-jaxrs`
- try using `MultipartFile` instead of `MultipartHttpServletRequest`

**Comment by anthammas** [comment]
As @dilipkrish suggested, the swagger version is upgraded to 2.6.1. 
But according to https://api.everbridge.net/#!/uploads/upload_post_1 , the MultiPartHttpServletRequest is allowed and perfectly documented.
And also, using MultipartFile, how can I annotate it for uploading multiple files.

Thanks.

**Comment by dilipkrish** [comment]
@anthammas that doesnt seem to be using springfox. You could add an alternate type rule to map MultipartHttpServletRequest => MultipartFile and everything will just work. 

Multiple file uploads may not be supported by swagger-ui
