### ISSUE TITLE
@ApiImplicitParam with paramType="form" outputs undefined when dataType set to custom model.

### ISSUE THREAD

**Issue by ghost** [springfox/springfox#1718]
That title is a mouthful.

I'm using Springfox 2.6.1.  Here is a snippet of my controller method, which handles a multipart upload.  One part is metdata, and the other part contains the file:

	@ApiImplicitParams({
		@ApiImplicitParam(
			name = "metadata",
			dataType = "Metadata",
			required = true,
			paramType = "form"),
		@ApiImplicitParam(
			name = "file",
			dataType = "file",
			required = true,
			paramType = "form")
	)}
	@PostMapping(value = "/files", consumes = "multipart/form-data")
	public FileId uploadFile(@PathVariable String container, HttpServletRequest req) {
		...
	}

I am using HttpServletRequest and not MultipartFile intentionally and for good reason.

Swagger UI outputs the metadata part as having an 'undefined' data type.  the 'Metadata' type is a POJO, and the UI correctly outputs its schema when paramType="body".  Here is a picture (the file picker is cropped out of the picture):

![springfox_bug1](https://cloud.githubusercontent.com/assets/3186025/23826004/ddd9b962-066a-11e7-81f8-c9649d95f3bc.png)

**Comment by dilipkrish** [comment]
I should add this to the docs... Recently fixed a bug to address this issue. If you change the datatype to "__file" once 2.7.0 is released, it will fix your issue. Infact could you try with 2.7.0-SNAPSHOT, and report back.
