### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by 4everinbeta** [springfox/springfox#1719]
Hello all,

I am attempting to get my first spring boot webservice documented with swagger. I have followed the tutorial [here](http://kubecloud.io/guide-using-swagger-for-documenting-your-spring-boot-rest-api/) but am getting the 404 when trying to hit http://localhost:8080/swagger-ui.html

I'm not sure what I could be missing. Any suggestions?

`package com.mytest;

import com.github.javafaker.Faker;
import com.mytest.models.MYAR_Order;
import com.mytest.repositories.IOrderRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@EnableSwagger2
public class TestsvcApplication {
	private final Faker faker = new Faker();

	public static void main(String[] args) {
		SpringApplication.run(TestsvcApplication.class, args);
	}

	@Bean
	public CommandLineRunner initializeDb(IOrderRepository repository){
		return (args) -> {
			repository.deleteAll();
			//Insert some random orders
			for(int i = 0; i < 20; i++) {
				repository.save(new Order(
						faker.number().randomNumber(),
						faker.number().randomNumber(),
						faker.number().randomNumber(),
						faker.number().randomNumber(),
						faker.number().randomNumber(),
						faker.number().randomNumber(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.number().randomNumber(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters(),
						faker.lorem().characters()));
			}
		};
	}

	@Bean
	public Docket swaggerSettings() {
		return new Docket(DocumentationType.SWAGGER_2)
				.select()
				.apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any())
				.build()
				.pathMapping("/");
	}
}
`

**Comment by 4everinbeta** [comment]
Disregard this. Turns-out that I missed the springfox-swagger-ui dependency in aforementioned tutorial. Sorry!

**Comment by dilipkrish** [comment]
Please upgrade to 2.6.1 to get the lates fixes!
