### ISSUE TITLE
If you have both Read and Write operation in single Controller readOnly do not work. But if only Write it works.

### ISSUE THREAD

**Issue by dzmitryhil** [springfox/springfox#1725]
# Bug report

Problem with readOnly mode

`
 @ApiModelProperty(readOnly = true)
 @JsonProperty(access = JsonProperty.Access.READ_ONLY)
`

It works, but not always.

Example:
__Model__
```java
@ApiModel("Unit sensor monitoring parameters")
public class MyParams implements Serializable {

    @ApiModelProperty("int val")
    private int intVal;

    @ApiModelProperty(readOnly = true)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String readOnlyString;

    public int getIntVal() {
        return intVal;
    }

    public String getReadOnlyString() {
        return readOnlyString;
    }
}
```
__1) Controller (only Post operation)__
```java
@RestController
@RequestMapping("/test")
@Api
public class MyController {

    @ApiOperation("post operation")
    @PostMapping
    public void subscribeSensor(@RequestBody MyParams params) {

    }
}
```
__1) Swagger output__
![image](https://cloud.githubusercontent.com/assets/6096171/24100721/73db8144-0d86-11e7-9d3c-a4d1267fdabf.png)

__2) Controller (only Post and GET operations)__
```java
@RestController
@RequestMapping("/test")
@Api
public class MyController {

    @ApiOperation(value = "get operation")
    @GetMapping
    public MyParams get()
    {
        return new MyParams();
    }

    @ApiOperation("post operation")
    @PostMapping
    public void subscribeSensor(@RequestBody MyParams params) {
    }

}

```
![image](https://cloud.githubusercontent.com/assets/6096171/24100790/c32a8420-0d86-11e7-9c30-b61474259720.png)

**So. If you have both Read and Write operation in single Controller readOnly do not work.
But if only Write it works.**

**Comment by dzmitryhil** [comment]
springfox-swagger2, 2.6.1 version

**Comment by dilipkrish** [comment]
This is a known issue that has a solution in the works #1671

**Comment by dzmitryhil** [comment]
Thanks for the answer. How the issue will be fixed? Removed support of ReadOnly or fixed?

**Comment by dilipkrish** [comment]
fixed hopefully.

**Comment by dilipkrish** [comment]
__NOTE:__ the bug is not closed because it is fixed. Rather it is waiting on #1671
