### ISSUE TITLE
@Api(hidden = true) does not hide

### ISSUE THREAD

**Issue by rlewan** [springfox/springfox#1731]
#995 fixed the problem for `@ApiOperation`, but `@Api(hidden = true)` on a controller still does not work. We use springfox-swagger 2.6.1.

**Comment by dilipkrish** [comment]
You should use the `RequestHandlerSelector` predicates for that

**Comment by rlewan** [comment]
Yeah, that would work. *Still* -- isn't `@Api(hidden = true)` a part of Swagger specification that should be implemented and working?

**Comment by dilipkrish** [comment]
It would be surprising if it did not work based on the annotation itself, yes; but not part of the specification. Goes back to [the philosophy of this project](http://springfox.github.io/springfox/docs/current/#goals), to prefer not adding or using annotations other than what is needed by the spring-mvc runtime.
