### ISSUE TITLE
Default value of "supportedSubmitMethods" in springfox.js

### ISSUE THREAD

**Issue by thadc23** [springfox/springfox#1732]
In using the **supportedSubmitMethods** field on `UiConfiuguration`, I have run into a problem where configuring the Jackson `ObjectMapper` to only include NON_EMPTY values breaks the desired functionality when using `Constants.NO_SUBMIT_METHODS`.  Since `Constants.NO_SUBMIT_METHODS` is an empty array, the field is omitted from the JSON response and the javascript defaults the value back to `['get', 'post', 'put', 'delete', 'patch']`.  I feel that since `supportedSubmitMethods` is either defaulted to `['get', 'post', 'put', 'delete', 'patch']` or required in the constructors of `UiConfiguration`, having the javascript default to an empty array would cover this scenario without breaking the current functionality.

**Comment by dilipkrish** [comment]
You could create a mixin to work around the problem

**Comment by thadc23** [comment]
Thanks.
