### ISSUE TITLE
swagger ui not showing the default parameter value zero

### ISSUE THREAD

**Issue by liudonghua123** [springfox/springfox#1734]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [x] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful. 

I have a simple spring-boot web application, in my control, I have several method like this
```
	@ApiOperation(value = "查询活动告警", notes = "根据siteId以及可选的limit/offset查询活动告警")
	@RequestMapping(path="/{siteId}/alarm/activeAlarm", method = RequestMethod.GET, produces = "application/json")
	public FCSDKResponse<PageList<Alarm>> queryActiveAlarms(
			@ApiParam(name = "siteId", value = "The id of the site", defaultValue = "3F7B07E2") @PathVariable String siteId, 
			@RequestParam(value="limit", defaultValue="10", required=false) int limit, 
			@ApiParam(name = "offset", value = "The value of offset", defaultValue = "0") @RequestParam(value="offset", defaultValue="0", required=false) int offset)
```
If I set default value zero whether using @ApiParam or not, on the `/swagger-ui.html`, the default value of this parameter is empty.

![image](https://cloud.githubusercontent.com/assets/2276718/24177575/69412dfc-0ede-11e7-8755-243d9a15af51.png)

**Comment by lm231290** [comment]
This bug is still present. Version 2.9.2. The default field value stays empty or filled with a placeholder if '0' is set to 'defaultValue' or/and 'example' args of 'ApiParam'

**Comment by wade-bigdata** [comment]
This bug is still present. Version 3.0.0
