### ISSUE TITLE
@api with  spring boot 1.4.2

### ISSUE THREAD

**Issue by kanouken** [springfox/springfox#1739]
env :   springfox 2.6.1   Spring Boot(1.4.2)  

if i  used the  anotation     @api(tag="") , Swagger-Ui can not expand  the  Api  

what is the error below

<img width="760" alt="2017-03-28 11 31 01" src="https://cloud.githubusercontent.com/assets/4925886/24387865/329eb33e-13aa-11e7-91c8-c622f4cde2ac.png">

**Comment by dilipkrish** [comment]
Api tags are required for providing names/grouping of controllers. So empty tags will not work. Either don't annotate with an `@Api` annotation with an empty tag or annotate and let it override the value.
