### ISSUE TITLE
Path Issue

### ISSUE THREAD

**Issue by mithunns** [springfox/springfox#1744]
Hi,

I want to split path as basepath and relative path.

I want to display swagger document like this:
 
![2](https://cloud.githubusercontent.com/assets/13430628/24451686/7cc51cde-149d-11e7-968d-4f2ef2392364.jpg)

But when I use @RequestMapping all I can get is this:

![3](https://cloud.githubusercontent.com/assets/13430628/24451879/3ba63e76-149e-11e7-80a7-2dfaeccf1604.jpg)

How to split basepath and pathvariable and display that in swagger document.

**Comment by dilipkrish** [comment]
Have you tried overriding the path provider?

**Comment by mithunns** [comment]
Hi,
Thanks for the reply. Yes I tried that. But same error.

This is how my code looks like.

ApplicationManager:
```

    @Bean
    public Docket newsApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .useDefaultResponseMessages(false)
                .enableUrlTemplating(false)
                .groupName("svc-service-inventory")
                .apiInfo(apiInfo())
                .host("9081")
                .pathProvider(new PathProvider() {
                    @Override
                    public String getApplicationBasePath() {
                        return "/application/v1/legacy-services-inventory/services/";
                    }

                    @Override
                    public String getOperationPath(String s) {
                        return s;
                    }

                    @Override
                    public String getResourceListingPath(String s, String s1) {
                        return s+s1;
                    }
                })
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.telstra.digitalservices.serviceinventory.controllers"))
                .build();
    }
```

At Class level I used :
```
@RequestMapping
@MicroserviceController
public class CeaseServiceDetailsController {

```
Method level:```

    @CrossOrigin
    @MicroserviceMethod
    @GetMapping(value = "/{serviceId:.+}", produces = "application/json")
    @ApiOperation(value = "Get-Service-Details",
            notes = "This is documentation for ServiceInventory Facade Service")
    public MicroserviceResponse doGet(@PathVariable("serviceId") final  String serviceId,
                                      final MicroserviceResponse microserviceResponse) {
```

But the output I get is an error on browser:

**Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Apr 12 12:07:11 IST 2017
There was an unexpected error (type=Not Acceptable, status=406).
Could not find acceptable representation**

**Comment by dilipkrish** [comment]
I don't think this is possible to do in a simple way
