### ISSUE TITLE
How to override API-Documentation of generated endpoints (spring-data-rest)

### ISSUE THREAD

**Issue by florianrusch** [springfox/springfox#1746]
**My question:**
I use the `JpaRepository` and the `PagingAndSortingRepository` from spring-data without a custom repository implementation. How can I override the api documentation of the inherited methods?

I've tried the following with no result:
```Java
@RepositoryRestResource
public interface BikesRepository extends PagingAndSortingRepository<Bike, UUID> {
    @Override
    @ApiOperation("Find all bikes")
    Page<Bike> findAll(Pageable pageable);
}
```

Springfox-Version: 2.7.0-Snapshot
I also use the workaround for the `Pageable` param as I posted it a view days ago.

**Comment by florianrusch** [comment]
So there is no solution for it?

**Comment by dilipkrish** [comment]
For some reason my comment did not get saved. Sorry.

This is a duplicate of #1623
