### ISSUE TITLE
404 when use swagger2-ui with spring-boot-1.5.2

### ISSUE THREAD

**Issue by Tneciv** [springfox/springfox#1747]
Already add dependencies of swagger :
```xml
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.6.1</version>
        </dependency>
```
Get `localhost:9000/v2/api-docs` is ok, but `localhost:9000/swagger-ui.html` returns 404 .
Spring-boot version is `1.5.2.RELEASE`

**Comment by Tneciv** [comment]
When I use swagger version 2.6.0 , it works well .

**Comment by dilipkrish** [comment]
That is odd. There might be a duplicate of this issue. Might be similar to #1752

**Comment by dilipkrish** [comment]
Have you resolved this issue? Don't have any idea why it might not be available.

**Comment by dilipkrish** [comment]
@Tneciv  Could you try adding the following bean and see if that fixes your problem. Better still could you try 2.7.0-SNAPSHOT and let me know if that fixes your problem.

```java
@Bean
  public static PropertySourcesPlaceholderConfigurer swaggerProperties() {
    PropertySourcesPlaceholderConfigurer properties = new PropertySourcesPlaceholderConfigurer();
    return properties;
  }
```

**Comment by Tneciv** [comment]
@dilipkrish After I upgrade` spring-cloud-dependencies` to` Dalston.RELEASE` , `swagger-ui v2.6.1` swagger-ui.html could be visited . Maybe the issue caused by spring . 
Very thanks for your attention !

**Comment by ihappyk** [comment]
i am still facing this issue with spring-boot version 1.5.6.RELEASE , when i use Swagger of 2.6.0 its working but 2.6.1 says 404 not found.
