### ISSUE TITLE
Error resolving $ref pointer for input DTO

### ISSUE THREAD

**Issue by gionn** [springfox/springfox#1749]
I am facing the same issue already reported in https://github.com/springfox/springfox/issues/1230#issuecomment-211834198 also with the latest 2.6.1.

Workaround mentioned there still works.

**Comment by dilipkrish** [comment]
Thanks for reporting ... again! :) Will take a look and see. It might not be easy to fix if it is still broken

**Comment by gionn** [comment]
I think that springfox is not supporting well that with Spring is possibile to bind request parameters to a class instance (PageRequestDTO  in my case).

I have not looked at the generated spec itself, but after rendering the spec with https://github.com/Rebilly/ReDoc, it was interpreting the class field as a single parameter, and not as a collection of GET parameters.

Thanks.

**Comment by dilipkrish** [comment]
@gionn could you perhaps try with the latest 2.7.0-SNAPSHOT and see if that fixes your problem. If not could you share the your `PageRequestDTO` definition

**Comment by gionn** [comment]
Tried the snapshot, without any luck.

[PageRequestDTO](https://gist.github.com/gionn/09893044c56dcd8ed5f63fbff945d68d)

This is the spec generated with the latest snapshot, if can help:
[api-docs.json.zip](https://github.com/springfox/springfox/files/934126/api-docs.json.zip)

Example usage in controller method:
```
    @ApiOperation ( value = "Retrieve all the companies" )
    @RequestMapping ( method = RequestMethod.GET )
    public List<CompanyDTO> getAllPaged( @Valid PageRequestDTO request,
            HttpServletResponse response,
            @RequestParam ( required = false ) String email,
            @RequestParam ( required = false ) String companyName,
            @RequestParam ( required = false ) Boolean like ) throws Exception
```

Thanks!

**Comment by gionn** [comment]
:+1: :+1: :+1:
