### ISSUE TITLE
[Question] - how to remove response model for specific @ApiResponse

### ISSUE THREAD

**Issue by laur89** [springfox/springfox#1750]
- ver *2.6.1*

Related to #1633 

Not following how no response model could be set for specific `@ApiResponse`.

    @ApiOperation(
            value = "get some data",
            notes = "Retrieves list of IDs",
            response = MyResponseBody.class )
    @ApiResponses( value = {
            @ApiResponse( code = 200,
                    message = "list of ids",
                    response = MyResponseBody.class ),
            @ApiResponse( code = 204,
                    message = "no ids found",
                    response = Void.class )
    } )
    @RequestMapping( value = "/ids, method = GET )
    public ResponseEntity<MyResponseBody> getIds()

Generated swagger-ui still contains `MyResponseBody` as the response model for 204, instead the expected void. How to handle this case?

**Comment by dilipkrish** [comment]
If you remove the `@ApiOperation` annotation or remove the value in response in `@ApiOperation` you'll see the right results
