### ISSUE TITLE
Spring Boot deployed in jar can't open swagger-ui.html

### ISSUE THREAD

**Issue by Valery-Dm** [springfox/springfox#1752]
Greetings,
I searched through other issues and the are many problems with initial springfox configuration.
Looks like mine is different. I'm trying to deploy the app. Sorry if I missed something similar.

I'm using:
Springfox version is 2.6.1. Spring Boot is 1.5.2.

I have properly working Spring Boot application with Swagger. Everything works great from within STS (Eclipse IDE), but when I run app from the jar file (which is built with maven) I cannot reach swagger-ui page anymore (v2/api-doc and others are still there).

I see Whitelabel Error Page from Spring at address http://localhost:8080/swagger-ui.html

some lines from stack-trace:
java.io.IOException: Unable to open root Jar file 'war:file:/home/user/Desktop/myapp.jar*/BOOT-INF/lib/springfox-swagger-ui-2.6.1.jar'
	at org.springframework.boot.loader.jar.Handler.getRootJarFile(Handler.java:282)
...
Caused by: java.lang.IllegalStateException: Not a file URL
	at org.springframework.boot.loader.jar.Handler.getRootJarFile(Handler.java:269)

BOOT-INF/lib/springfox-swagger-ui-2.6.1.jar - this file actually exists

I've read something about Spring problem with reading webjar files.
It was pointing out to this page http://www.webjars.org/documentation#springmvc
But I can't understand what's going on under the hood. So I just have blindly copied over the dependency and that config class with addResourceHandlers method. And... not surprisingly, it didn't help.

Is it possible to get swagger-ui from within jar file at all?

**Comment by Valery-Dm** [comment]
Well, I was close enough.
This line also needs to be in the addResourceHandlers method
registry.addResourceHandler("swagger-ui.html")
		.addResourceLocations("classpath:/META-INF/resources/");
Now it's working.

**Comment by dilipkrish** [comment]
Since you're using spring boot it is usual that you have to manually add resource handlers. Do you have `@EnableWebMvc` annotation in your configuration?

**Comment by Valery-Dm** [comment]
dilipkrish, no I don't have it in my config.
If you are interested in details that may help you understand the issue, my source code is available here at Github.
It's a simple and relatively small demo Application, with Restful services, for which I decided to use Swagger documenting tool.

Main config file
https://github.com/Valery-Dm/restjdbc/blob/master/src/main/java/dmv/spring/demo/RestjdbcApplication.java

One of annotated controllers
https://github.com/Valery-Dm/restjdbc/blob/master/src/main/java/dmv/spring/demo/rest/controller/UserRestController.java

I'm not using any external configuration, everything in those annotations. 
And it actually works now. I still have some minor issues with Response HTTP codes: UI page does not show 200s in the Responses list down below for all GET methods, and it mistakenly shows that 200 code for DELETE where it's not needed (I have 204 for success there).

**Comment by Valery-Dm** [comment]
BTW, how soon we can see your 2.7.0 version? I'm especially interested in that 'resource reading feature'.
That is analogous to @Value("${some.resource}"). It would be great if someday that feature will support some internationalization possibility, like ResourceBundle has for example

**Comment by dilipkrish** [comment]
@Valery-Dm Thanks for updating the issue! 🙇 

Im hoping in the next week.
