### ISSUE TITLE
Spring boot with swagger can not run when package a jar

### ISSUE THREAD

**Issue by kengan** [springfox/springfox#1753]
I used the example about the spring boot with swagger2 from url (http://www.tuicool.com/articles/Ibe6BzY) and download the source code from git (https://github.com/springframeworkguru/springboot_swagger_example) . After that I import the source  into Eclipse,everything is ok. 
After I package the source code into a jar and run with " java -jar spring-boot-web-0.0.1-SNAPSHOT.jar" I get the error as following and the spring boot application can not be run.

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/D:/sourcecode/springboot_swagger_example-master/springboot_swagger_example-master/target/spring-boot-web-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/springfox-swagger2-2.6.1.jar!/springfox/documentation/swagger2/mappers/LicenseMapper$License.class]; nested exception is java.lang.IndexOutOfBoundsException

How can I solve this problem? Thank you !

**Comment by dilipkrish** [comment]
How are you generating the jar?

**Comment by kengan** [comment]
I make jar with eclipse .I right click the project then open a menu.I select run as --- maven build----enter package in the goal---- click run.After a while , eclipse shows build success.

**Comment by dilipkrish** [comment]
You need to use the [spring boot maven plugin](http://docs.spring.io/spring-boot/docs/current/maven-plugin/usage.html). The goal should `repackage` I believe
