### ISSUE TITLE
[Question] Spring Boot Swagger Not working

### ISSUE THREAD

**Issue by MadhuraMaddali** [springfox/springfox#1755]
Hi,
Version Info:
<spring.boot.version>1.5.1.RELEASE</spring.boot.version>
        <spring.version>4.3.5.RELEASE</spring.version>
<springfox.version>2.6.1</springfox.version>

I am trying to apply a custom Content Negotiagtion scheme only for my REST Endpoints and Swagger needed a deault one.
To acheive this I ended up adding two diffrerent Dispatcher servlets. One for swagger and one for REST calls. It was working fine and I was using Spring 4 with XML configuration.

Recently we started moving it to Spring Boot and started migrating to JavaConfig, and I am stuck with an issue now. If I enable @Configuration tag in WebConfig file, it will Not display The swagger page End points.
The reason is ContentNegotiation Manager is getting applied to Swagger UI Page and I am not understanding how to apply it to only REST endpoints.
I tried many ways with no luck. Any help is greately appreciated.

{code}
package com.inq.test;

import com.inq.test.config.WebConfig;
import com.inq.test.doc.SwaggerConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;
import org.springframework.web.servlet.DispatcherServlet;

TestAPIApplication.class
{code}
@SpringBootApplication(exclude={DispatcherServletAutoConfiguration.class})
public class TestAPIApplication {
public static void main(String[] args) throws Exception {
SpringApplication.run(testAPIApplication.class, args);
}

@Bean
public ServletRegistrationBean test() {
DispatcherServlet dispatcherServlet = new DispatcherServlet();
AnnotationConfigWebApplicationContext applicationContext = new AnnotationConfigWebApplicationContext();
applicationContext.register(WebConfig.class);
dispatcherServlet.setApplicationContext(applicationContext);
ServletRegistrationBean servletRegistrationBean = new ServletRegistrationBean(dispatcherServlet, "/testAPI/v2/test/*");
servletRegistrationBean.setName("test");
servletRegistrationBean.setAsyncSupported(true);
return servletRegistrationBean;
}

@Bean
public ServletRegistrationBean testSwagger() {
DispatcherServlet dispatcherServlet = new DispatcherServlet();
AnnotationConfigWebApplicationContext applicationContext = new AnnotationConfigWebApplicationContext();
applicationContext.register(SwaggerConfig.class);
dispatcherServlet.setApplicationContext(applicationContext);
ServletRegistrationBean servletRegistrationBean = new ServletRegistrationBean(dispatcherServlet, "/testAPI/v2/test/doc/*");
servletRegistrationBean.setName("test-swagger");
servletRegistrationBean.setAsyncSupported(true);
return servletRegistrationBean;
}

}
{code}

SwaggerConfig class
{code}
package com.inq.test.doc;

import com.google.common.base.Predicates;
import com.inq.test.config.AppConfig;
import com.inq.test.config.WebConfig;
import com.inq.test.config.oauth2.OAuth2ResourceServerConfig;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.FilterType;
import org.springframework.context.annotation.Import;
import org.springframework.web.context.ServletContextAware;
import springfox.documentation.PathProvider;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.ImplicitGrantBuilder;
import springfox.documentation.builders.OAuthBuilder;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.AuthorizationScope;
import springfox.documentation.service.GrantType;
import springfox.documentation.service.LoginEndpoint;
import springfox.documentation.service.SecurityScheme;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.paths.RelativePathProvider;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger.web.ApiKeyVehicle;
import springfox.documentation.swagger.web.SecurityConfiguration;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import javax.servlet.ServletContext;
import java.util.List;

import static com.google.common.collect.Lists.newArrayList;

@Import({ AppConfig.class })
@Configuration
@ComponentScan(excludeFilters={
@ComponentScan.Filter(type= FilterType.ASSIGNABLE_TYPE, value=WebConfig.class),
@ComponentScan.Filter(type= FilterType.ASSIGNABLE_TYPE, value=OAuth2ResourceServerConfig.class)})
@EnableSwagger2
public class SwaggerConfig implements ServletContextAware {
private static final String SECURITY_SCHEMA_OAUTH2 = "oauth2";
private ServletContext servletContext;

@Value("${springfox.documentation.swagger.v2.host}")
private String hostName;

@Value("${swagger.ui.oauth2.authorize.url}")
private String authorizeUrl;

@Value("${swagger.ui.oauth2.clientId}")
private String swaggerAppClientId;

@Value("${swagger.ui.oauth2.clientSecret}")
private String swaggerClientSecret;

@Bean
public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2)
            .pathProvider(pathProvider())
            .host(hostName)
            .select()
            .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
            .build()
            .apiInfo(apiInfo())
            .securitySchemes(newArrayList(oauth()));
}

@Bean
public SecurityScheme oauth() {
    return new OAuthBuilder()
            .name(SECURITY_SCHEMA_OAUTH2)
            .grantTypes(grantTypes())
            .scopes(scopes())
            .build();
}

@Bean
public SecurityConfiguration securityInfo() {
    return new SecurityConfiguration(swaggerAppClientId, swaggerClientSecret, "realm", "swagger", "", ApiKeyVehicle.HEADER, "", " ");
}

private List<AuthorizationScope> scopes() {
    return newArrayList(
            new AuthorizationScope("write", "write and read"),
            new AuthorizationScope("read", "read only"));
}

private List<GrantType> grantTypes() {
    GrantType grantType = new ImplicitGrantBuilder()
            .loginEndpoint(new LoginEndpoint(authorizeUrl))
            .tokenName("access_token")
            .build();

    return newArrayList(grantType);
}

private PathProvider pathProvider() {
    return new RelativePathProvider(servletContext) {
        @Override
        protected String applicationPath() {
            return "/testAPI/v2/test/doc";
        }
    };
}

private ApiInfo apiInfo() {
    return new ApiInfoBuilder()
            .title("Test API")
            .description("The TouchCommerce Test engagement API is designed to allow any application that can support the HTTP protocol "
                    + "to develop or extend existing applications to implement TouchCommerce Test services using a REST API")
            .version("2.0")
            .build();
}

@Override
public void setServletContext(ServletContext servletContext) {
    this.servletContext = servletContext;
}
}
{code}

WebConfig class

{code}
package com.inq.test.config;

import com.inq.test.config.AppConfig;
import com.inq.test.doc.SwaggerConfig;
import com.inq.test.services.testDeferredResultInterceptor;
import com.inq.test.web.testParameterContentNegotiationStrategy;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.FilterType;
import org.springframework.context.annotation.Import;
import org.springframework.core.Ordered;
import org.springframework.web.context.request.async.DeferredResultProcessingInterceptor;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;
import org.springframework.web.filter.CorsFilter;
import org.springframework.web.servlet.config.annotation.AsyncSupportConfigurer;
import org.springframework.web.servlet.config.annotation.ContentNegotiationConfigurer;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

@Configuration
//@EnableWebMvc
//@EnableAsync
@Import({ AppConfig.class })
@ComponentScan(basePackages = "com.inq.test",
excludeFilters={@ComponentScan.Filter(type= FilterType.ASSIGNABLE_TYPE, value=SwaggerConfig.class)})
public class WebConfig extends WebMvcConfigurerAdapter {

@Override
public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
configurer.favorPathExtension(false).
useJaf(false).
ignoreAcceptHeader(true).
// parameterName("output").
defaultContentTypeStrategy(new testParameterContentNegotiationStrategy());
}

@Bean
public FilterRegistrationBean corsFilter() {
    UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
    CorsConfiguration config = new CorsConfiguration();
    config.setAllowCredentials(true);
    config.addAllowedOrigin("*");
    config.addAllowedHeader("*");
    config.addAllowedMethod("*");
    config.addExposedHeader("Authorization");
    config.addExposedHeader("Content-Type");
    source.registerCorsConfiguration("/**", config);
    FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
    bean.setOrder(Ordered.HIGHEST_PRECEDENCE);
    return bean;
}

@Override
  public void configureAsyncSupport(AsyncSupportConfigurer configurer) {
    System.out.println("Test ");
    DeferredResultProcessingInterceptor testDeferredResultInterceptor = new testDeferredResultInterceptor();

    configurer.registerDeferredResultInterceptors(testDeferredResultInterceptor);
    configurer.setDefaultTimeout(50000); //in milliseconds

  }
/*@Override
public void configureAsyncSupport(AsyncSupportConfigurer configurer) {
configurer.setDefaultTimeout(50000); //in milliseconds
super.configureAsyncSupport(configurer);
} */

/* @Override
public void addInterceptors(InterceptorRegistry registry) {
registry.addInterceptor(new testDeferredResultInterceptor());
} */

/* @Override
public void addResourceHandlers(ResourceHandlerRegistry registry) {
registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");
registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
}
*/
}
{code}

@Configuration
//@ComponentScan(basePackages = {"com.inq.test"})
@ComponentScan(basePackages = "com.inq.test",
excludeFilters = {@ComponentScan.Filter(type = FilterType.ANNOTATION, value=org.springframework.context.annotation.Configuration.class),
@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, value=WebConfig.class),
@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, value=SwaggerConfig.class)})
@PropertySource({"classpath:application.properties"})
@EnableScheduling
public class AppConfig {
.....
}

{code}

**Comment by dilipkrish** [comment]
Its not clear to me why you need to servlets? May be simplifying the setup will help you with isolating the problem. It may be easier to trouble shoot if you share your repository/

**Comment by MadhuraMaddali** [comment]
Hi
Thank you for your quick response.
 Please see the test App I Uploaded here.
https://github.com/MadhuraMaddali/SpringFoxTestApp
 If you run the app with URL http://localhost:10082/testAPI/v2/agent/swagger-ui.html , you see that swagger page is not completely displayed (Reason: We have Custom Conent Negotiation scheme default to xml.Swagger requests expect json as deafult)
To overcome this trying to handle seperate content negotiation using Two dispatcher servlets that we did it before in Spring 4 but not working in  Spring Boot.

Do you suggest any other approach.

**Comment by MadhuraMaddali** [comment]
Hi Dilip,
Still we have  same issue. Looking for your inputs.

**Comment by dilipkrish** [comment]
Hello @MadhuraMaddali Sorry I haven't had time recently to look at this. Let me take a look at your repo and get back to you

**Comment by dilipkrish** [comment]
I spent 1/2 hr with it and it looks like the repo mix of spring 3 and spring 4 (content negotiation etc.) Why don't u use start.spring.io and start over?
