### ISSUE TITLE
[Question] SwaggerSpecFilter when using SpringFox Swagger UI

### ISSUE THREAD

**Issue by mubinahmed** [springfox/springfox#1756]
Is it possible to use SwaggerSpecFilter from swagger-core while using swagger-ui to dynamically hide some of the APIs?
If yes, is there any example which I can refer? If not, is there a way that this can be implemented?

**Comment by dilipkrish** [comment]
No it is not possible to use `SwaggerSpecFilter`. However it is possible to use the docket to filter which actions you want to expose. There is the `docket#select()` API which allows you to provide `Predicate<RequestHandler>` to select `apis` or if you want to filter by `paths()` you could provide a `Predicate<String>`. There are some handy canned ones in `RequestHandlerSelectors` and `PathSelectors`

**Comment by mubinahmed** [comment]
Thanks @dilipkrish. That answers my question. `RequestHandlerSelectors` was helpful in my scenario.
