### ISSUE TITLE
[Question]My swagger-ui does not support JSON Array as RequestBody[Question]

### ISSUE THREAD

**Issue by helxiong** [springfox/springfox#1763]
**i use swagger-ui/dist as a new Java Web project,
when i pass JSON array as RequestBody, it happened exception like this:**
2017-04-10 16:16:32.557 [http-bio-8080-exec-5] DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Resolving exception from handler [public com.swaggerui.list.api.model.response.Result com.swaggerui.list.api.controller.CustomerRegisterApi.registrationPost1(java.util.ArrayList<com.swaggerui.list.api.test.BaseParam>)]: org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Can not instantiate value of type [simple type, class com.swaggerui.list.api.test.BaseParam] from String value ('['); no single-String constructor/factory method

**This is my pom.xml:**
com.mangofactory
swagger-springmvc
1.0.2

com.fasterxml.jackson.core
jackson-databind
2.4.2

commons-lang
commons-lang
2.6

**This is swagger-ui.js:**
swagger-ui - Swagger UI is a dependency-free collection of HTML, JavaScript, and CSS assets that dynamically generate beautiful documentation from a Swagger-compliant API
@version v2.2.10
@link http://swagger.io
@license Apache-2.0

**This is my swagger config:**

package com.swaggerui.list.api.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.DefaultServletHandlerConfigurer;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;

import com.mangofactory.swagger.configuration.SpringSwaggerConfig;
import com.mangofactory.swagger.models.dto.ApiInfo;
import com.mangofactory.swagger.plugin.EnableSwagger;
import com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin;

@Configuration
@EnableWebMvc
@EnableSwagger
public class SwaggerConfig extends WebMvcConfigurerAdapter {

private SpringSwaggerConfig springSwaggerConfig;

// Required to autowireSpringSwaggerConfig
@Autowired
public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
	this.springSwaggerConfig = springSwaggerConfig;
}

/**
 * EverySwaggerSpringMvcPlugin bean is picked up by the swagger-mvc
 * framework - allowing for multiple swagger groups i.e. samecode base
 * multipleswagger resource listings.
 */
@Bean
public SwaggerSpringMvcPlugin customImplementation() {
	return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(apiInfo()).includePatterns(".*")
			.useDefaultResponseMessages(false).apiVersion("1.0").build();
}

private ApiInfo apiInfo() {
	ApiInfo apiInfo = new ApiInfo("Test API List Platform", "Test Api list based on Swagger and built using Java.",
			"", "", "Test", "");
	return apiInfo;
}

@Override
public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
	configurer.enable();
}

**This is Spring MVC controller:**

package com.swaggerui.list.api.controller;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.swaggerui.list.api.test.BaseParam;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;

@Controller
@Api(value = "commodity", description = "商品管理", produces = MediaType.APPLICATION_JSON_VALUE)
public class CommodityController {

@RequestMapping(value = "/maps", method = RequestMethod.POST)
@ResponseBody
@ApiOperation(value = "获得商品信息", notes = "获取商品信息(用于数据同步)", httpMethod = "POST", produces = MediaType.APPLICATION_JSON_VALUE)
@ApiResponses(value = { @ApiResponse(code = 200, message = "商品信息"),
		@ApiResponse(code = 201, message = "(token验证失败)", response = String.class),
		@ApiResponse(code = 202, message = "(系统错误)", response = String.class) })
public void getCommodity(@ApiParam(value = "Json参数", required = true) @RequestBody ArrayList<BaseParam> param)
		throws Exception {
	System.out.println("size:" + param.size());
	System.out.println(param.get(0).getShopName());
}

**Comment by dilipkrish** [comment]
Unfortunately 1.0.2 isn't really supported. Could you please upgrade to 2.x?

**Comment by helxiong** [comment]
Could you give me a download address of jar file?
THK

**Comment by dilipkrish** [comment]
They are all in maven central

**Comment by helxiong** [comment]
Which version of the springfox and swagger-api/swagger-ui compatibility is best?
