### ISSUE TITLE
Question -Is there a way to substitute the model specification/definition where ResponseEntity<?> is used for an actual class?

### ISSUE THREAD

**Issue by smanglani** [springfox/springfox#1764]
Question - 
We're using these versions of SpringFox:
```xml
<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
             <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
             <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-spring-web</artifactId>
             <version>2.6.1</version>
        </dependency>
```

And instantiate SpringFox/Swagger 2 using the below bean: 
```java
@Bean
    public Docket api(){
        return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(PathSelectors.any())
            .build()
            .alternateTypeRules(
          AlternateTypeRules.newRule(typeResolver.resolve(ResponseEntity.class, WildcardType.class),
                        typeResolver.resolve(WildcardType.class)))
            .apiInfo(apiInfo());
    }
```

We are using ResponseEntity generic for the return type:

```java
@RequestMapping(value = “/someMethod”, method = RequestMethod.POST)
    public ResponseEntity<?> someMethod(@RequestBody Application app) {
    	try {
    		return new ResponseEntity<>(aService.someMethod(app), HttpStatus.OK);
    	} catch (Exception ex) {
    		String errorMessage = ex.getMessage() + " <== error";
    		LOG.error(errorMessage, ex);
    		return new ResponseEntity<>(errorMessage, HttpStatus.BAD_REQUEST);
    	}
    }
```

Using ResponseEntity<?> we are getting empty model schema {} when we try to view the response model Schema using swagger-ui.html. If we change the return type to ResponseEntity<Application> in the above method "someMethod", then the model schema is populated for the response.

We were wondering if there is a way by using an annotation, or some configuration to substitute the model specification/definition where ResponseEntity<?> is used for an actual class? 
Thanks!

**Comment by dilipkrish** [comment]
You should be using 

```java
   @RequestMapping(value = “/someMethod”, method = RequestMethod.POST)
   @ApiResponses({ @ApiResponse(code = 400, message = "The error message", response=String.class) })
    public ResponseEntity<SomeObject> someMethod(@RequestBody Application app) {
    	try {
    		return new ResponseEntity<>(aService.someMethod(app), HttpStatus.OK);
    	} catch (Exception ex) {
    		String errorMessage = ex.getMessage() + " <== error";
    		LOG.error(errorMessage, ex);
    		return new ResponseEntity<>(errorMessage, HttpStatus.BAD_REQUEST);
    	}
    }
```

**Comment by smanglani** [comment]
Thanks for your response but your suggestion will not work for us. We can't have the predetermined error message as we are taking the error message value from the exception that is thrown. That's why we are using ResponseEntity<?> to switch between the object returned or the string error message.
Also, Using ResponseEntity<?> we are getting empty model schema {} when we try to view the response model Schema using swagger-ui.html. Is there a way to actually get the model schema?

**Comment by dilipkrish** [comment]
@smanglani You don't need to set the error message. It is only for illustration. The important aspect to note is that you can set the response for `400` to be of type `String`. In any case, you'll only know the exception message when you invoke the operation :)
