### ISSUE TITLE
@Api(value="...") not working

### ISSUE THREAD

**Issue by vijethKA** [springfox/springfox#1765]
Hi,

```
@Api(value="Location Rest Controller")
@Controller
public class LocationRestController 
{
```
for the above code i'm getting this json 

```
 "host": "172.30.55.67:8080",
  "basePath": "/rest",
  "tags": [
    {
      "name": "location-rest-controller ",
      "description": "Location Rest Controller"
    },
```
Excpected :

```
 "host": "172.30.55.67:8080",
  "basePath": "/rest",
  "tags": [
    {
      "name": "Location Rest Controller ",
      "description": ""
    },
```

Why am i getting   "name" separated by hyphen?

**Comment by dilipkrish** [comment]
Use `@Api(value="Location Rest Controller", tags="Location Rest Controller")`

**Comment by punkmonday** [comment]
Use `@Api(value="Location Rest Controller", tags="Location Rest Controller")`,it's not working,
this is my config:
`@Configuration
@ComponentScan(basePackages = {"com.amoebo.backend.api.controller"})
@EnableWebMvc
@EnableSwagger2
public class SwaggerConfig {

    public static final String SWAGGER_SCAN_BASE_PACKAGE = "com.amoebo.backend.api.controller";
    public static final String VERSION = "1.0.0";

    @Bean
    public Docket customDocket() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.basePackage(SWAGGER_SCAN_BASE_PACKAGE))
                .paths(PathSelectors.any())
                .build();
    }
}
`

`@Api(value = "brand", tags = "brand")
@RestController
@RequestMapping("/v1/api/brands")
public class BrandController {
`

**Comment by dilipkrish** [comment]
@punkmonday what is not working? What are u seeing?

**Comment by punkmonday** [comment]
@dilipkrish ui show "brand-controller"

**Comment by punkmonday** [comment]
@dilipkrish i found solution, verymethod @ApiOperation must add attr `tags="brand"` , it works for me

**Comment by dilipkrish** [comment]
👍 thanks for reporting back @punkmonday

**Comment by onacit** [comment]
Has adding `tags` on every `@ApiOperation` been regarded as a solution?

**Comment by RainThinks** [comment]
@Api(tags = "brand") would do the trick.
