### ISSUE TITLE
No "try it out" button  and params are missing if request method is HEAD

### ISSUE THREAD

**Issue by roger-gl** [springfox/springfox#1766]
The annotations look like this:

```
@RequestMapping(value = "/subject/{id}", method = RequestMethod.HEAD)
@ApiResponses(value = {@ApiResponse(code = 200, message = "OK"),
                                           @ApiResponse(code = 404, message = "subject not found")})
public void doesExist(HttpServletResponse response, Long id)
```

The Problem is, that I can not try this request since I can not enter the ID and the "try it out" button is missing. If I change HEAD to GET everything works as expected.

**Comment by dilipkrish** [comment]
You can supply your own `UiConfiguration` [bean](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/UiConfiguration.java#L90-L131) and override the `supportedHttpMethods` to include HEAD
