### ISSUE TITLE
Unable to implement and use ApiListingScannerPlugin

### ISSUE THREAD

**Issue by stacysimpson** [springfox/springfox#1767]
This issue is related to the new plugin ApiListingScannerPlugin created due to #1335

I've tried both 2.6.0 and 2.6.1 and have the same problem. My implementation of ApiListingScannerPlugin doesn't run. I'm guessing that the plugin registry isn't being updated properly.?.?

If I modify the plugin to implement ApiListingBuilderPlugin and alter the apply() method signature, the apply() method is executed.

Is there another step that I'm missing?

**Comment by dilipkrish** [comment]
That is true, it should've been tested. Thanks for catching that!

**Comment by stacysimpson** [comment]
Great, thanks!

**Comment by stacysimpson** [comment]
Was able to verify today against the HEAD of master.
