### ISSUE TITLE
How to generate a swagger.json i a build step?

### ISSUE THREAD

**Issue by triptec** [springfox/springfox#1768]
- [x] Question. Is this a question about how to do a certain thing? 

How do I generate a swagger.json within a build step?
I would like to feed swagger-codegen with that to generate a client.

**Comment by dilipkrish** [comment]
You can make it part of your build step by running an integration test. See instructions of how to do that [here](http://swagger2markup.github.io/swagger2markup/1.3.1/#_spring_boot_and_springfox). The idea is to use springfox to generate the specification at build time, which u can use to for codegen.

**Comment by triptec** [comment]
Yeah, I've looked at those but I think it's a little late in the process. I better explain my use case,
what we would like to do is use a swagger-codegen generated java client as the client for the integration tests.

**Comment by dilipkrish** [comment]
You have a 🐔and 🍳 problem. The only way to do that is for your swagger-code-gen to use the contract generated from the previous build that is cached. At least that way you'll know if the service changes broke the swagger-codegenned client. Once successful you can re-gen the client. Caution: Slippery slope
