### ISSUE TITLE
不支持中文

### ISSUE THREAD

**Issue by chinafuhai** [springfox/springfox#1769]
Hello, I am a Chinese, English is not good, when in use, I found that the @API in the use of Chinese tags, the page can not be launched api.

**Comment by chinafuhai** [comment]
在2.6.1版本中发现这个问题

**Comment by dilipkrish** [comment]
I think this is a duplicate of https://github.com/swagger-api/swagger-ui/issues/2708

Basically the issue is that swagger-ui doesnt support unicode (chinese characters) in tags.
