### ISSUE TITLE
Swagger interfering the spring PropertySourcesPropertyResolver

### ISSUE THREAD

**Issue by huherto** [springfox/springfox#1771]
Using  version 2.6.1

We installed swagger in an existing large application.  The spring PropertySourcesPropertyResolver stopped working for one bean.  We have  tested it commenting in/out the @EnableSwagger2 annotation.  

```
@Configuration
//@EnableSwagger2
public class SwaggerConfig {                                    
    @Bean
    public Docket api() { 
        return new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())                          
          .build();                                           
    }
}

```
```
    @Autowired
    public void setEmailCleansingNegativeExpressions(@Value("${email.negatives: }")
                                                     final String rawEmailNegatives) {
            // rawEmailNegatives is now an emtpy string.
    }
```
Turning debug logging for spring we see these when it logs. But not when it doesn't work.
```
2017-04-14 08:27:28 DEBUG [localhost-startStop-1] PropertySourcesPropertyResolver - Searching for key 'email.negatives' in [class path resource [data-cleanse.properties]]
2017-04-14 08:27:28 DEBUG [localhost-startStop-1] PropertySourcesPropertyResolver - Searching for key 'email.negatives' in [class path resource [data-cleanse-replacements.properties]]
2017-04-14 08:27:28 DEBUG [localhost-startStop-1] PropertySourcesPropertyResolver - Searching for key 'email.negatives' in [class path resource [data-cleanse-negatives.properties]]
2017-04-14 08:27:28 DEBUG [localhost-startStop-1] PropertySourcesPropertyResolver - Found key 'email.negatives' in [class path resource [data-cleanse-negatives.properties]] with type [String] and value '.
```
It is hard to replicate in a small app. We caught this because some existing functionality stopped working. We will do more research. I will leave this here in case anyone has any ideas.

**Comment by dilipkrish** [comment]
Yeah this is fixed in 2.7.0 I believe. I suspect the reason is we introduced a PropertySourcesPlaceholderConfigurer that attempts to resolve the variable a little too early. You might need to introduce `PropertySourcesPlaceholderConfigurer` as a bean 

```java
@Bean
  public static PropertySourcesPlaceholderConfigurer swaggerProperties() {
    PropertySourcesPlaceholderConfigurer properties = new PropertySourcesPlaceholderConfigurer();
    return properties;
  }
```

**Comment by dilipkrish** [comment]
Is this a boot application?

**Comment by huherto** [comment]
It is not a boot application.

The fix works.  Thanks!!

 Why was this bean affected  but not all the rest of beans that use that property values ?

**Comment by dilipkrish** [comment]
I believe it has to do with the order in which the properties are resolved. The bean that came with springfox, tried to resolve it and when it did not find it it left it unresolved.
