### ISSUE TITLE
BasePath can't be defined without host

### ISSUE THREAD

**Issue by astafev** [springfox/springfox#1772]
Hello, application base path provided by PathProvider gets overriden if host property is not set.

My use case is the following (might be a bit unusual though): I have nginx that works as reverse proxy for java application installed on the same host. Nginx adds additional context to the path (localhost/appName/api => localhost:8080/api).

So I need to add base path to swagger, but without host. It can't be done in latest versions because of check in Swagger2Controller (https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L87). Personally I don't understand why this check was introduced and the fact that it doesn't print at least any warning.

Basic usage for me would be the following: to define bean like in below snippet, open swagger-ui and swagger-ui should use this base path. To make this work I had to use old version.
```
 @Bean
    public Docket newsApi(ServletContext servletContext) {
        return new Docket(DocumentationType.SWAGGER_2).pathProvider(new RelativePathProvider(servletContext) {
            @Override
            public String getApplicationBasePath() {
                return "/appName" + super.getApplicationBasePath();
            }
        });
    }
```

**Comment by astafev** [comment]
test project https://github.com/astafev/swagger-host-basepath

**Comment by dilipkrish** [comment]
@astafev Could you confirm that you're seeing this behavior in 2.7.0-SNAPSHOT?

**Comment by astafev** [comment]
yep, it works fine with 2.7.0-SNAPSHOT, thanks
