### ISSUE TITLE
Which version of the springfox and swagger-api/swagger-ui compatibility is best?

### ISSUE THREAD

**Issue by helxiong** [springfox/springfox#1774]
which version is the most stable of springfox?
which version is the most stable of swagger-api/swagger-ui?
Which version of the springfox and swagger-api/swagger-ui compatibility is best?

**Comment by dilipkrish** [comment]
The most stable version is the latest which is `2.6.1`. Since every version of springfox comes with a bundled version of swagger-ui `springfox-swagger-ui`, that is the most compatible version for it. However, the latest version of `swagger-api/swagger-ui` should always work.
