### ISSUE TITLE
javax @Valid annotation makes parameter as requestbody-parameter

### ISSUE THREAD

**Issue by jmattheis** [springfox/springfox#1778]
Version: 2.6.1

When using the `javax.validation.Valid`-annoatation on an method parameter, it will be displayed in springfox as body-param, but it shouldn't because it is still parsed as query parameter from spring.

when:
```
class TestClass {
	private String s;
        // getter + setter
}
class TestClass2 {
	private String e;
        // getter + setter
}
@RestController
public class Controller {
	@RequestMapping(value = "controllerWithStringList", method = RequestMethod.GET)
	public ResponseEntity<Void> get( @javax.validation.Valid TestClass testClass, TestClass2 testClass2) {
		return ResponseEntity.ok().build();
	}
}
```
Actual Result:
```
"parameters":[
    {"in":"body","name":"testClass","description":"testClass","required":false,"schema":{"$ref":"#/definitions/TestClass"}},
    {"name":"e","in":"query","required":false,"type":"string"}
]
```
Expected Result (also without the `@Valid`-annotation):
```
"parameters":[
    {"name":"s","in":"query","required":false,"type":"string"},
    {"name":"e","in":"query","required":false,"type":"string"}
]
```

**Comment by dilipkrish** [comment]
Thanks for reporting. I'll verify that this is fixed in 2.7.0!

**Comment by jmattheis** [comment]
@dilipkrish The `@Valid`-annotation wasn't used the the commit f29278a. The annotation is from this dep: `javax.validation:validation-api:1.0.0.GA`

**Comment by dilipkrish** [comment]
Yeah I realize that this commit does not add `@Valid`. However #1749 does test that in a subsequent fix/commit.

**Comment by jmattheis** [comment]
Ohh ok, that test has the annotation, so it should work.
