### ISSUE TITLE
Please make either SecurityConfiguration#DEFAULT public or the default constructor public

### ISSUE THREAD

**Issue by cooniur** [springfox/springfox#1788]
Version: [2.6.1]

### Issue
In 2.5.1, the `springfox.documentation.swagger.web.SecurityConfiguration#DEFAULT` field is public, as is shown here: https://github.com/springfox/springfox/blob/2.5.0/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/SecurityConfiguration.java#L26. However this was changed in 2.6.x. I'd like to know the reason why it has been changed. And if possible, please make it public again to accommodate the following use case.

### Use case
Programmatically configure Swagger's API key, example code in 2.5.0:

```
@EnableSwagger2
@Configuration
class SwaggerConfiguration {
    private ApiKey apiKey = null;

    @PostConstruct
    void init() {
        // some logic to assign apiKey according to some configuration
    }

    @Bean
    springfox.documentation.swagger.web.SecurityConfiguration security() {
        if (this.apiKey == null) {
            return springfox.documentation.swagger.web.SecurityConfiguration.DEFAULT;
        } else {
            return new springfox.documentation.swagger.web.SecurityConfiguration(null, null, null, null,
                    "Your access token", ApiKeyVehicle.HEADER, apiKey.getKeyname(), null);
        }
    }
``` 

Now 2.6.x in order to use the default security config, one needs to do the following, which is very cumbersome.
```
@EnableSwagger2
@Configuration
class SwaggerConfiguration {
    // This line is really cumbersome, and will potentially cause issues if the default parameters don't match with Swagger's.
    private static final springfox.documentation.swagger.web.SecurityConfiguration DEFAULT_SWAGGER_SECURITY_CONFIG = 
        new springfox.documentation.swagger.web.SecurityConfiguration(null, null, null, null, null, ApiKeyVehicle.HEADER, "api_key", ",");

    private ApiKey apiKey = null;

    @PostConstruct
    void init() {
        // some logic to assign apiKey according to some configuration
    }

    @Bean
    springfox.documentation.swagger.web.SecurityConfiguration security() {
        if (this.apiKey == null) {
            return springfox.documentation.swagger.web.SecurityConfiguration.DEFAULT;
        } else {
            return new springfox.documentation.swagger.web.SecurityConfiguration(null, null, null, null,
                    "Your access token", ApiKeyVehicle.HEADER, apiKey.getKeyname(), null);
        }
    }

```

### Ideal Solution
Please make either of the following public:
- `springfox.documentation.swagger.web.SecurityConfiguration#DEFAULT`
- `SecurityConfiguration`'s default constructor 

Or please advise other ways or workarounds.

Thanks!

**Comment by dilipkrish** [comment]
@cooniur Thanks for the suggestions. We don't want to expose DEFAULT because it is really used for when there is no configurations specified. And the default constructor is not exposed because if someone is overriding the configuration they should be deliberate about it. You could define that constant in your code or create a factory method with only the overridden values.

**Comment by cooniur** [comment]
Hi @dilipkrish, I totally understand the reason why you want to keep the default constructor private. 

Maybe at least could you make the DEFAULT public? Therefore, users wouldn't have to maintain their own default security config if they just need to use whatever the default one is out of the box. And moreover, users wouldn't need to worry about keeping it up to date with the constructor if the constructor would change in the future.

It seems there is no obvious harm by doing so, is it?

**Comment by ris58h** [comment]
@cooniur, maybe you could use Conditional annotation instead of the field check. It depends on the logic in your init() method.
As I can see (I checked it for 2.6.1), you could just return null value instead of DEFAULT in your Bean annotated method.

**Comment by dilipkrish** [comment]
Closing this issue for now. We can reopen if you feel strongly after the 2.7.0 release

**Comment by cooniur** [comment]
Hi @ris58h , thanks for the advice of using the `@Conditional`. I actually took this approach, too. 

I'm ok not to use the `DEFAULT` security configuration for now. So closing this ticket is fine with me, too.

Thanks everyone for the help! :)

**Comment by bademux** [comment]
Can you please add builder to the class?
I also suggest to use ```@Singular `` list fields. https://projectlombok.org/api/lombok/Singular.html
Thanks!

**Comment by dilipkrish** [comment]
@bademux thats a great idea! However we would still like to validate the `built` configuration, so may be a hand written builder. Would you like to help?

**Comment by bademux** [comment]
@dilipkrish We can use annotations like @NotNull with lombok.
Or if more control is needed we can use factory method annotated with @Builder
