### ISSUE TITLE
@PreAuthorize("hasRole('ROLE_SYSTEM')")  java.lang.NullPointerException in the 2.6.1 release

### ISSUE THREAD

**Issue by bthorington** [springfox/springfox#1791]
Using:
```
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.6.1</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.6.1</version>
		</dependency>
```

with Spring Boot 1.5.2.RELEASE

If i have a controller like this:
```
@RestController
@PreAuthorize("hasRole('ROLE_ADMIN')")
public class MyRestController {
...
}

```
I get:
`org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException`

If I roll back to 2.5x I dont get an error, the controller just doesnt show up in the UI document.

I think this is a bug.

**Comment by dilipkrish** [comment]
A full stack trace will be useful. Cant really say much by looking at this other than "yeah, thats a possibility"
