### ISSUE TITLE
How to add logic into "Try it out!" button.

### ISSUE THREAD

**Issue by flytosm** [springfox/springfox#1794]
Hi, all
I got a problem when I use swagger to create the dynamic document.
I hope someone can help me.
When Document reader want to try out the api, an parameter can not be input by reader, it should be generated by some logic (need to use input parameter and request url).
May I  customize the swagger ui, and add the logic into "Try it Out" button.
Is there anyone could share me the detail document (steps) or a sample.
Thanks.

**Comment by dilipkrish** [comment]
I don't think you can customize that button. You can try asking in the [swagger-ui project](https://github.com/swagger-api/swagger-ui)

**Comment by flytosm** [comment]
Hi Dilip

thank you so much for your reply.
Can i use both springfox and swagger-ui at the same time？ i need to create
a signature by using the input parameter and request url. do you have any
idea for this ？

Best Regards，
Fly



2017年4月28日(金) 20:26 Dilip Krishnan <notifications@github.com>:

**Comment by dilipkrish** [comment]
You can use infact a customized swagger-ui is bundled with springfox.
