### ISSUE TITLE
Swagger is not compatible with Spring 4.2.6 and app engine

### ISSUE THREAD

**Issue by robinsonrengaraj** [springfox/springfox#1795]
spring-version : 4.2.6.RELEASE
 appengine.version>1.9.42
Tried different version of swagger:
Swagger version : 2.6.1, 2.5.0, 2.4.0
Error:
ERROR [org.springframework.web.servlet.DispatcherServlet] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter': Initialization of bean failed; nested exception is java.lang.**NoSuchMethodError**: com.google.common.collect.Lists.reverse(Ljava/util/List;)Ljava/util/List;

Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Lists.reverse(Ljava/util/List;)Ljava/util/List;
	at springfox.documentation.spring.web.ObjectMapperConfigurer.jackson2Converters(ObjectMapperConfigurer.java:76)
	at springfox.documentation.spring.web.ObjectMapperConfigurer.configureMessageConverters(ObjectMapperConfigurer.java:63)
	at springfox.documentation.spring.web.ObjectMapperConfigurer.postProcessBeforeInitialization(ObjectMapperConfigurer.java:47)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)

**Comment by dilipkrish** [comment]
What version of guava do you have in your class path?

**Comment by robinsonrengaraj** [comment]
Here is my dependency tree

[INFO] com.ca.micromech:micromech-api:war:SNAPSHOT
[INFO] +- org.springframework:spring-web:jar:4.2.6.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.2.6.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.2.6.RELEASE:compile
[INFO] |  \- org.springframework:spring-context:jar:4.2.6.RELEASE:compile
[INFO] +- org.springframework:spring-core:jar:4.2.6.RELEASE:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- org.springframework:spring-tx:jar:3.1.2.RELEASE:compile
[INFO] |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] +- org.springframework:spring-aspects:jar:4.2.6.RELEASE:compile
[INFO] |  \- org.aspectj:aspectjweaver:jar:1.8.9:compile
[INFO] +- org.springframework:spring-webmvc:jar:4.2.6.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.2.6.RELEASE:compile
[INFO] +- org.springframework.data:spring-data-jpa:jar:1.11.0.RELEASE:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:1.13.0.RELEASE:compile
[INFO] |  \- org.aspectj:aspectjrt:jar:1.8.10:compile
[INFO] +- org.springframework:spring-orm:jar:4.1.6.RELEASE:compile
[INFO] |  \- org.springframework:spring-jdbc:jar:4.2.6.RELEASE:compile
[INFO] +- org.apache.axis:axis:jar:1.4:compile
[INFO] +- commons-discovery:commons-discovery:jar:0.5:compile
[INFO] +- javax.xml:jaxrpc-api:jar:1.1:compile
[INFO] +- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO] +- org.springframework.security:spring-security-web:jar:3.2.5.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-core:jar:3.2.5.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-config:jar:3.2.5.RELEASE:compile
[INFO] +- org.springframework:spring-context-support:jar:4.0.0.RELEASE:compile
[INFO] +- com.google.apis:google-api-services-storage:jar:v1-rev89-1.22.0:compile
[INFO] |  \- com.google.api-client:google-api-client:jar:1.22.0:compile
[INFO] |     +- com.google.oauth-client:google-oauth-client:jar:1.22.0:compile
[INFO] |     +- com.google.http-client:google-http-client-jackson2:jar:1.22.0:compile
[INFO] |     \- com.google.guava:guava-jdk5:jar:17.0:compile
[INFO] +- com.google.oauth-client:google-oauth-client-jetty:jar:1.22.0:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client-java6:jar:1.22.0:compile
[INFO] |  \- org.mortbay.jetty:jetty:jar:6.1.26:compile
[INFO] |     +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO] |     \- org.mortbay.jetty:servlet-api:jar:2.5-20081211:compile
[INFO] +- io.jsonwebtoken:jjwt:jar:0.6.0:compile
[INFO] +- org.dspace.dependencies:dspace-geoip:jar:1.2.3:compile
[INFO] +- com.google.http-client:google-http-client:jar:1.21.0:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.1:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.5.1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.5.1:compile
[INFO] +- org.hibernate:hibernate-core:jar:4.1.8.Final:compile
[INFO] |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.1.0.GA:compile
[INFO] |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar:1.0.0.Final:compile
[INFO] |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  +- org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.1.Final:compile
[INFO] |  +- org.javassist:javassist:jar:3.15.0-GA:compile
[INFO] |  \- org.hibernate.common:hibernate-commons-annotations:jar:4.0.1.Final:compile
[INFO] +- org.hibernate:hibernate-entitymanager:jar:4.1.8.Final:compile
[INFO] +- commons-io:commons-io:jar:1.3.2:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] +- commons-fileupload:commons-fileupload:jar:1.3.2:compile
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.liquibase:liquibase-core:jar:3.5.3:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.17:compile
[INFO] +- com.itextpdf:itextpdf:jar:5.5.9:compile
[INFO] +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  \- commons-lang:commons-lang:jar:2.4:compile
[INFO] +- javax.activation:activation:jar:1.1.1:compile
[INFO] +- com.google.appengine:appengine-api-1.0-sdk:jar:1.9.42:compile
[INFO] +- com.google.appengine:appengine-endpoints:jar:1.9.42:compile
[INFO] +- javax.inject:javax.inject:jar:1:compile
[INFO] +- mysql:mysql-connector-java:jar:5.1.38:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.13:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.13:runtime
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.13:runtime
[INFO] +- log4j:log4j:jar:1.2.16:compile
[INFO] +- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] |  \- commons-pool:commons-pool:jar:1.5.4:compile
[INFO] +- junit:junit:jar:4.11:test
[INFO] +- org.springframework:spring-test:jar:4.2.6.RELEASE:test
[INFO] +- org.skyscreamer:jsonassert:jar:1.2.3:compile
[INFO] |  \- org.json:json:jar:20090211:compile
[INFO] +- com.jayway.jsonpath:json-path:jar:0.8.1:test
[INFO] |  \- net.minidev:json-smart:jar:1.1.1:test
[INFO] +- com.jayway.jsonpath:json-path-assert:jar:0.8.1:test
[INFO] +- org.dbunit:dbunit:jar:2.4.9:test
[INFO] +- org.mockito:mockito-core:jar:2.2.25:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.5.5:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.5.5:test
[INFO] |  \- org.objenesis:objenesis:jar:2.4:test
[INFO] +- javax.servlet:javax.servlet-api:jar:3.0.1:provided
[INFO] +- com.google.cloud:gcloud-java-datastore:jar:0.2.0:compile
[INFO] |  +- com.google.cloud:gcloud-java-core:jar:0.2.0:compile
[INFO] |  |  +- com.google.auth:google-auth-library-credentials:jar:0.3.1:compile
[INFO] |  |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.3.1:compile
[INFO] |  |  +- com.google.api-client:google-api-client-appengine:jar:1.21.0:compile
[INFO] |  |  |  +- com.google.oauth-client:google-oauth-client-appengine:jar:1.21.0:compile
[INFO] |  |  |  |  +- com.google.oauth-client:google-oauth-client-servlet:jar:1.21.0:compile
[INFO] |  |  |  |  |  \- com.google.http-client:google-http-client-jdo:jar:1.21.0:compile
[INFO] |  |  |  |  \- javax.servlet:servlet-api:jar:2.5:compile
[INFO] |  |  |  +- com.google.api-client:google-api-client-servlet:jar:1.21.0:compile
[INFO] |  |  |  |  \- javax.jdo:jdo2-api:jar:2.3-eb:compile
[INFO] |  |  |  |     \- javax.transaction:transaction-api:jar:1.1:compile
[INFO] |  |  |  \- com.google.http-client:google-http-client-appengine:jar:1.21.0:compile
[INFO] |  |  \- com.google.http-client:google-http-client-jackson:jar:1.21.0:compile
[INFO] |  |     \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  +- com.google.cloud.datastore:datastore-v1beta3-protos:jar:1.0.0-beta:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java:jar:3.0.0-beta-1:compile
[INFO] |  \- com.google.cloud.datastore:datastore-v1beta3-proto-client:jar:1.0.0-beta:compile
[INFO] |     \- com.google.http-client:google-http-client-protobuf:jar:1.20.0:compile
[INFO] +- com.google.appengine:appengine-testing:jar:1.9.42:test
[INFO] +- com.google.appengine:appengine-api-stubs:jar:1.9.42:test
[INFO] +- com.twilio.sdk:twilio:jar:7.9.0-alpha-2:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- joda-time:joda-time:jar:2.5:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  \- javax.xml.bind:jaxb-api:jar:2.2:compile
[INFO] |     \- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] +- io.springfox:springfox-swagger2:jar:2.6.1:compile
[INFO] |  +- io.swagger:swagger-annotations:jar:1.5.10:compile
[INFO] |  +- io.swagger:swagger-models:jar:1.5.10:compile
[INFO] |  +- io.springfox:springfox-spi:jar:2.6.1:compile
[INFO] |  |  \- io.springfox:springfox-core:jar:2.6.1:compile
[INFO] |  +- io.springfox:springfox-schema:jar:2.6.1:compile
[INFO] |  +- io.springfox:springfox-swagger-common:jar:2.6.1:compile
[INFO] |  +- io.springfox:springfox-spring-web:jar:2.6.1:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.3.1:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
[INFO] |  \- org.mapstruct:mapstruct:jar:1.0.0.Final:compile
[INFO] +- io.springfox:springfox-swagger-ui:jar:2.6.1:compile
[INFO] +- org.webjars:bootstrap:jar:3.3.5:compile
[INFO] |  \- org.webjars:jquery:jar:1.11.1:compile
[INFO] \- org.datanucleus:datanucleus-maven-plugin:jar:4.0.0-release:compile
[INFO]    +- org.codehaus.plexus:plexus-utils:jar:3.0.8:compile
[INFO]    +- org.apache.maven:maven-artifact:jar:3.0.4:compile
[INFO]    +- org.apache.maven:maven-plugin-api:jar:3.0.4:compile
[INFO]    |  +- org.apache.maven:maven-model:jar:3.0.4:compile
[INFO]    |  \- org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0:compile
[INFO]    |     +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[INFO]    |     \- org.sonatype.sisu:sisu-inject-bean:jar:2.3.0:compile
[INFO]    |        \- org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[INFO]    |           \- org.sonatype.sisu:sisu-guava:jar:0.9.9:compile
[INFO]    \- org.codehaus.plexus:plexus-container-default:jar:1.5.5:compile
[INFO]       +- org.codehaus.plexus:plexus-classworlds:jar:2.2.2:compile
[INFO]       +- org.apache.xbean:xbean-reflect:jar:3.4:compile
[INFO]       |  \- commons-logging:commons-logging-api:jar:1.1:compile
[INFO]       \- com.google.collections:google-collections:jar:1.0:compile

**Comment by robinsonrengaraj** [comment]
This is the version

com.google.guava:guava:jar:18.0:compile

**Comment by dilipkrish** [comment]
I think perhaps guava version used in 2.7.0 may not be compatible

**Comment by piyushdubeygithub** [comment]
what version of guava should be used in 2.7.0
