### ISSUE TITLE
NullPointerException in ApiResourceController.swaggerResources

### ISSUE THREAD

**Issue by 1106285275** [springfox/springfox#1798]
springboot +swagger 2.5.0
when I have annoation like @Aspect @Pointcut @Around and some defination like Advisor ,swagger worked failed,said as title . how to work out this problem?

Can it work with the interceptor, if not, it would be a problem

**Comment by dilipkrish** [comment]
Cannot guarantee that it would or not based on how you've implemented your aspects. Also please upgrade to 2.6.1 for better results
