### ISSUE TITLE
Add Support to block Swagger-ui via Spring Profiles

### ISSUE THREAD

**Issue by pluttrell** [springfox/springfox#1799]
Based on this [SO answer](http://stackoverflow.com/a/27976261/1930325), it appears the recommended way to disable the swagger endpoint hosting is by using an `@Profile` annotation on the `@Configuration` class for Springfox. This works great for the swagger endpoints themselves. But how do you also disable the `/swagger-ui.html` and `webjars/` endpoints with that same profile?

For example, if you're using these dependencies in `build.gradle`:
```
    compile 'io.springfox:springfox-swagger2:2.6.1'
    compile 'io.springfox:springfox-swagger-ui:2.6.1'
```

**Comment by dilipkrish** [comment]
If you're using spring-boot, you can disable `WebMvcAutoConfiguration` and create an `@Component` bean that implements `WebMvcConfigurerAdapter`

```java
@Configuration
@Profile("development,test")
public class WebConfig extends WebMvcConfigurerAdapter {
 
  @Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/public/**").addResourceLocations("classpath:/public/");
    ... code to register resource handlers for swagger-ui
  }
}
```

**Comment by pluttrell** [comment]
@dilipkrish Thanks for getting back to me, but I don't understand how to do what you're suggesting in a way that won't break Spring's REST support. 

Yes, I am using Spring Boot (v1.5.3). I think you're suggesting that I change my main class annotation from `@SpringBootApplication` to `@SpringBootApplication(exclude = WebMvcAutoConfiguration.class)`. Isn't that the most critical part of Spring Boot's autoconfiguration, which provides all of the base Servlet handling for Spring's `@RestController` support, which I'm of course using (and what  SpringFox is documenting)?

Also, you mentioned that I should create my own `@Component` and implement `WebMvcConfigurerAdapter` and override the `addResourceHandlers(..)` method. A couple questions on this:

1. What is this line for?
 `registry.addResourceHandler("/public/**").addResourceLocations("classpath:/public/");` I don't see a `/public` path used or referenced anywhere in the SpringFox docs, nor any resources in a `public` directory that'll end up in my classpath.
2. You mentioned I should add the code to register resource handlers for swagger-ui. Where do I find out what that code is? I've looked through the SpringFox source on GitHub and don't see this anywhere.

Also, the answer to this question might be a great thing for the SpringFox docs, as I think many people would be interested in how to do this.

**Comment by Pyohwan** [comment]
+1

**Comment by dilipkrish** [comment]
> Isn't that the most critical part of Spring Boot's autoconfiguration, which provides all of the base Servlet handling for Spring's @RestController support, which I'm of course using (and what SpringFox is documenting)?

A little googling [leads me to believe](http://stackoverflow.com/a/27500835/19219) you can easily do this via a setting in your property/yaml file under specific profiles.

`spring.resources.add-mappings=false`

**Comment by vrudikov** [comment]
@dilipkrish Thank you. Helped me a lot

**Comment by pluttrell** [comment]
@vrudikov Care to post your final solution? Or maybe add it to the [docs](http://springfox.github.io/springfox/docs/current/)?

**Comment by vrudikov** [comment]
@pluttrell i've used ``spring.resources.add-mappings=false`` and it helped me a lot, because my server is API only. i don't have any web-resources there
