### ISSUE TITLE
How to add spring security authentication to swagger(2.4.0)??

### ISSUE THREAD

**Issue by pranotiB** [springfox/springfox#1801]
I have done spring security project and I have added swagger in it. When spring security is disabled everything works fine on swagger url. But when I enable the spring security, the swagger url is no more accessible. How can I access swagger with spring security? I want spring security active on swagger too.. Is it possible?

**Comment by pranotiB** [comment]
Does swagger work with spring security ?? How can I pass my JWT token to the web services in swagger..

**Comment by ris58h** [comment]
@pranotiB 
Just ignore some paths in your spring security configuration:
http://stackoverflow.com/a/37683455

**Comment by dilipkrish** [comment]
@pranotiB please upgrade to at least 2.6.1.  2.7.0 will be released shortly

**Comment by kushsharma1001** [comment]
Hi, I think question was : How can we enable username and password based security on swagger-ui.html?
I would like to know the same.
