### ISSUE TITLE
Lazy load springfox beans

### ISSUE THREAD

**Issue by janpachol** [springfox/springfox#1803]
I'm wondering, if there is a way to lazy load whole springfox configuration. Normally it is done by spring `@Lazy` annotation on class level. Now, when springfox initializes eagery, it very affects app startup time. It would be very useful to delay load all beans and then also search for all api after first call to any springfox controller.

I'm using version 2.6.1, Modules `compile "io.springfox:springfox-swagger2:+"` and `compile 'io.springfox:springfox-swagger-ui:+'`

**Comment by dilipkrish** [comment]
We could certainly do that. However I'm afraid it might better to encounter the load during startup time, rather than having the load just in time when there are people/consumers using the service.

**Comment by janpachol** [comment]
Thanks for your care, I absolutely agree, in many cases. But in my case, I don't care about first long-time swagger-ui loading, which is targeted for minor user group. But I care about startup time, which with `@EnableSwagger2` annotation took about 5 seconds more.
Maybe I could configure all springfox beans manually, but I would rather use nice spring auto configuration system.

**Comment by dilipkrish** [comment]
> Maybe I could configure all springfox beans manually, but I would rather use nice spring auto configuration system.

Im afraid that might be a better option. Would be awesome if you could share your solution.

**Comment by raisercostin** [comment]
My workaround was to configure `springfox.documentation.auto-startup=false` and manually call later at a more convenient time the `DocumentationPluginsBootstrapper.start()`. This saves a ton of startup time particularly at development time.
