### ISSUE TITLE
UiConfiguration.jsonEditor ignored in springboot

### ISSUE THREAD

**Issue by elli-shaklee** [springfox/springfox#1805]
Version 2.6.1 (latest), using springboot as a war and jettyRun locally.

**Swagger UI for a json POST web service does not allow the user to edit the data sent in the request.**

Spring configuration for **UiConfiguration.jsonEditor**  is true:
```
@Bean
public UiConfiguration uiConfig() {
  return new UiConfiguration(null,null, null, null, null, true, true, null); 
  //                                                      ^^^^
}
```

Gradle:
```
dependencies {
 compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '1.5.3.RELEASE'
  compile "io.springfox:springfox-swagger2:2.6.1"
  compile "io.springfox:springfox-bean-validators:2.6.1"
  compile "io.springfox:springfox-swagger-ui:2.6.1"
}
```
Controller:
```
@RestController
public class GreetingController {
	@RequestMapping(path = "/greeting", method = POST)
	public Greeting save(Greeting g) {
		return g;
	}
}
```
Using spring boot to generate a war file, not executable jar. There is no resource configuration since everything works without it.

Swagger correctly shows the input object (Greeting) schema.

When clicking "Try it out!", it sends a hard coded json post. It does not allow the user to edit it.

Attached screenshot:
![swagger](https://cloud.githubusercontent.com/assets/15895777/25831900/0eecb700-341c-11e7-96db-6ea9d395249d.png)

**Comment by dilipkrish** [comment]
Add a `@ModelAttribute` annotation which should fix it. If not report back

**Comment by elli-shaklee** [comment]
Tried:
```
@RequestMapping(path = "/greeting", method = POST)
public Greeting save(@ModelAttribute Greeting g) {
	return g;
}
```
The ui behavior is the same (cannot edit).

**Comment by elli-shaklee** [comment]
Added a github repo with the bug. Please follow the readme on the repo page to replicate:

https://github.com/shaklee/springfox_issue_1805/

**Comment by dilipkrish** [comment]
For model attributes to work they need accessors, at least a getter.

**Comment by elli-shaklee** [comment]
Adding getters and setters creates a different problem, the values in the form are sent as **query parameters** and not as json body. See screenshot:
![screen shot 2017-05-22 at 5 46 38 pm](https://cloud.githubusercontent.com/assets/15895777/26334005/cd2e0822-3f16-11e7-976e-71d40f4a3712.png)

Also there is no need for getters and setters since jackson works fine without them, as well as Jackson's schema generator.

**Comment by elli-shaklee** [comment]
I updated the git repo with getters and setters, to replicate this problem.

**Comment by dilipkrish** [comment]
Instead of using `@ModelAttribute` just use `@RequestBody` That will get the json editor in play

**Comment by elli-shaklee** [comment]
`@RequestBody` solves it. Getters and setters are not required as expected. See updated git repo, all works fine. I think it is worth mentioning in the docs that this is the preferred way to make everything work seamlessly. Thanks
