### ISSUE TITLE
OIDC Implicit flow requires nonce query parameter

### ISSUE THREAD

**Issue by VineetReynolds** [springfox/springfox#1807]
I'm using version 2.6.1 of Springfox in a Spring MVC REST API protected by Keycloak 3.0. I've configured Springfox to use Keycloak as the OIDC provider. When using the implicit flow, Springfox (and by extension, swagger-oauth.js) does not send the nonce in the request, resulting in an authentication failure.

Springfox/swagger-ui sends the following request to Keycloak:

    https://sso.xx.yy/auth/realms/myrealm/protocol/openid-connect/auth?response_type=token&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fmyapp%2Fwebjars%2Fspringfox-swagger-ui%2Fo2c.html&realm=myrealm&client_id=app-ui&scope=&state=app-auth

The response from the Keycloak, redirects the client to the following location:

    http://localhost:8080/myapp/webjars/springfox-swagger-ui/o2c.html#error=invalid_request&error_description=Missing+parameter%3A+nonce&state=oauth2schema

The OpenID Core spec is quite explicit on the need to send nonces in implicit flow, as one can see [here](http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest)

I've omitted putting down the Springfox configuration code, as I believe it is correct. Eventually, I got the authentication flow to work with authorization code flow, with minor changes. But, having OIDC implicit flow support would be good.

**Comment by dilipkrish** [comment]
I believe this is a swagger-ui issue. Would you mind reporting in that project. Closing this for now, but definitely reopen if you feel that is incorrect.
