### ISSUE TITLE
Spring Fox + Spring Boot + OAuth2 Client credentials Flow not working.

### ISSUE THREAD

**Issue by MadhuraMaddali** [springfox/springfox#1808]
Hi,
I am trying to configure OAuth2 Client credentials Flow for Swagger. 
In swagger page,  it shows the Authorize button and I can see the flow as "application".
After selecting the scope, if I click on authorize button, not authorized.
In net tab,  I can see it is redirecting from Token end point url(/oauth/token) to  login Page. 

My configuration is :
```java
@Configuration
@PropertySource({"classpath:application.properties"})
@EnableSwagger2
public class SwaggerConfig implements ServletContextAware {
    private static final String SECURITY_SCHEMA_OAUTH2 = "oauth2";
    private ServletContext servletContext;

    @Value("${springfox.documentation.swagger.v2.host}")
    private String hostName;

    @Value("${swagger.ui.oauth2.clientId}")
    private String swaggerAppClientId;

    @Value("${swagger.ui.oauth2.clientSecret}")
    private String swaggerClientSecret;

    @Value("${swagger.ui.oauth2.token.url}")
    private String swaggerTokenURL;

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .pathProvider(pathProvider())
                .host(hostName)
                .select()
                .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
                .build()
                .apiInfo(apiInfo())
                .securitySchemes(newArrayList(oauth()));
    }

    @Bean
    public SecurityScheme oauth() {
        return new OAuthBuilder()
                .name(SECURITY_SCHEMA_OAUTH2)
                .grantTypes(grantTypes())
                .scopes(scopes())
                .build();
    }

    @Bean
    public SecurityConfiguration securityInfo() {
        return new SecurityConfiguration(swaggerAppClientId, swaggerClientSecret, "realm", "swagger", "", ApiKeyVehicle.HEADER, "", " ");
    }

    private List<AuthorizationScope> scopes() {
        return newArrayList(
                new AuthorizationScope("write", "write and read"),
                new AuthorizationScope("read", "read only"));
    }

    private List<GrantType> grantTypes() {
        GrantType grantType = new ClientCredentialsGrant(swaggerTokenURL);
        return newArrayList(grantType);
    }
```

Is it know issue? Am i missing any thing ?

**Comment by MadhuraMaddali** [comment]
Hi,
Looking for some word on this issue :)

**Comment by dilipkrish** [comment]
@MadhuraMaddalli Not sure how that oauth dance is supposed to work in swagger-ui. Would you mind asking that project and reporting back.

**Comment by MadhuraMaddali** [comment]
@dilipkrish  

In Spring Fox, I see already ClientCredentialsGrant class accepts Token URL. 
My understanding is on Authorize button click, the Token call has to be made by passing the  Base 64 encoded clientId:clientSecret in the Authorization header, apart from passing the params
client_id=appClientId&grant_type=client_credentials.
Header
{"Authorization":"Basic Y2VhcGlDbGllbnRJZDpjZWFwaUNsaWVudFNlY3JldA=="}
 
Right now I see that Token rest call is taking place with out passing the  Authorization header. Token call returns Access Token.

Not sure whom to ask that question you are suggesting me to ask.

**Comment by dilipkrish** [comment]
Im suggesting you ask the [swagger-ui](https://github.com/swagger-api/swagger-ui) team

**Comment by gongrico** [comment]
i have same issue

**Comment by Ripul89** [comment]
Hi dilipkrish
i am getting error as below
{"error":"invalid_client","error_description":"Browser requests to the token endpoint must use Proof Key for Code Exchange."}

I am new to this , please guide me
