### ISSUE TITLE
Spring data rest models/fields empty

### ISSUE THREAD

**Issue by Ramblurr** [springfox/springfox#1814]
Using springfox `2.7.0-SNAPSHOT` all the spring-data-rest entities have empty attributes/model values in the swagger ui. That is, you cannot view the entity fields in the swagger docs.

### Examples: 
![swagger_ui](https://cloud.githubusercontent.com/assets/14830/25997251/a92a1ac2-371b-11e7-833b-2874561f6f2a.png)
![swagger_ui](https://cloud.githubusercontent.com/assets/14830/25997260/b679ace2-371b-11e7-91be-3e2566c39418.png)

### Config

```
@EnableSwagger2
@Import({ SpringDataRestConfiguration.class })
@Configuration
public class SwaggerConfiguration
{
    @Bean
    public Docket api()
    {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build()
                .apiInfo(buildMetadata());
    }
}
```

**Comment by Ramblurr** [comment]
Did this get fixed?

**Comment by dilipkrish** [comment]
I believe it was.  Would be great it u can confirm
