### ISSUE TITLE
Is it possible to add logic in the procedure of creating json file

### ISSUE THREAD

**Issue by flytosm** [springfox/springfox#1816]
Hi everybody, here is the image of springfox that I have. Is it right?
1.	Springfox read the source code (on spring framework), then create the JSON file (swagger specification). This file is not written on disk, instead it is in memory.
2.	Springfox (with swagger.ui) read this JSON file and create the API document page.

Then I have two question about 1.
1.	Where is procedure (in source code) to create the JSON file?
2.	Is it possible to add logic in this procedure, like add some information, which is not written in source code, to API document page?

**Comment by ris58h** [comment]
@flytosm, hi!
(I use 2.5.0 version)
Springfox doesn't read the source code. It works at runtime. Springfox doesn't create a JSON file. It keeps  information about your API in memory (take a look at springfox.documentation.service.Documentation).
As you can see in springfox.documentation.swagger2.web.Swagger2Controller, it gets the documentation from  springfox.documentation.spring.web.DocumentationCache and then maps it to the JSON representation.

Answers:
1. There is no procedure to create the JSON file. There is a JSON mapping from Documentation data structure in Swagger2Controller. If you want to generate the swagger specification at compiletime you probably should use another tools/libraries (may be this demo https://github.com/digvijaykatoch/spring-swagger2markup-demo can help you).
2. What kind of logic/information do you like to add? You could use some annotations to provide additional information about your API, but of course it will affect your source code.

**Comment by flytosm** [comment]
Hi ris58h,

Thank you very much for your reply.
I want to add some description of parameters and  response message.
I know add annotations can resolve the problem quickly. 
But the client didn`t want to add  annotations to the source code because the code has already been deployed.
So i want to find a way to do something what the annotations can do.
If you have any idea, please contact me.

Best Regards,
Fly

**Comment by dilipkrish** [comment]
You [don't need to use](http://stackoverflow.com/a/43959574/19219) any special non-spring annotations to use springfox.
