### ISSUE TITLE
JsonFormat for enum and other cases

### ISSUE THREAD

**Issue by yelhouti** [springfox/springfox#1818]
Please take the time to search the repository, if your question has already been asked or answered.

- [2.6.1 latest] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
   
   `@JsonFormat(shape=JsonFormat.Shape.OBJECT)` is not supported
   this property allows to threat enums as objects:
  
example: 

```
@JsonFormat(shape= JsonFormat.Shape.OBJECT)
@ApiModel(value = "Card Error", description = "Information about the error")
public enum CardError {
    BLOCKED("Token Blocked"),
    EXPIRED("Token Expired"),
    UNKNOWN("Token Unknown");
    @ApiModelProperty(value = "Error description")
    private String description;

    CardError(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public String getValue(){
        return this.name();
    }
}
```

Controller Methode:
```
    @RequestMapping(value = "/error",method = RequestMethod.GET)
    @ApiOperation(value = "get Error", notes = "test get Error", response = CardError.class)
    @ApiResponses({
            @ApiResponse(code = 401, message = "BLOCKED", response = CardError.class)
    })
    public ResponseEntity<CardError> getError(){
        return new ResponseEntity<>(CardError.EXPIRED, HttpStatus.UNAUTHORIZED);
    }
```

What is returned by spring :
```
{
  "description": "Token Expired",
  "value": "EXPIRED"
}
```
What Swagger displays:
```
HTTP Status Code   Reason        Response Model    Headers
401                BLOCKED       string
```

what happens is that Swagger doesn't take into account the JsonFormat and instead convert the enum to a String.

What do you think please

**Comment by yelhouti** [comment]
After some digging in the code this what I have understood so fare:
The problem happens in `springfox/springfox-core/src/main/java/springfox/documentation/schema/Enums.java` when getting allowable values.
Since they are Enums, springfox expect the `AllowableValues` to be an instance of `AllowableListValues` which is not the case if you annotate your enum with `@JsonFormat(shape= JsonFormat.Shape.OBJECT)` this makes jackson threat it as an Object when serializing.
This, I guess, could be fixed by changing "AllowableListValues" to return a `List<Model>` allowing also nested enums.

**Comment by yelhouti** [comment]
Another more important thing I think, is in springfox-schema-main:
```
public com.google.common.base.Optional<Model> modelFor(ModelContext modelContext) {
    ResolvedType propertiesHost = modelContext.alternateFor(modelContext.resolvedType(resolver));
    if (isContainerType(propertiesHost)
        || isMapType(propertiesHost)
        || propertiesHost.getErasedType().isEnum()
        || isBaseType(propertiesHost)
        || modelContext.hasSeenBefore(propertiesHost)) {
      LOG.debug("Skipping model of type {} as its either a container type, map, enum or base type, or its already "
          + "been handled", resolvedTypeSignature(propertiesHost).or("<null>"));
      return Optional.absent();
    }
...
```
this causes the Enum to have emptyModelMap and therefore to be threated as a String.
This can be fxied by creating a customTypeResolver (which I think is not a very goos idea), or easier check that the enum shouldn't be threated as Enum by reading the Annotation. when doing `propertiesHost.getErasedType().isEnum()`. could you help me to find how to get `jsonFormatAnnotation` like in the `BaseModelProperty` without poluating the code?
Thank you in adavance.

**Comment by dilipkrish** [comment]
Thanks for reporting this is certainly a feature gap

**Comment by yelhouti** [comment]
I'm working on fixing it right now, could we discuss that via slack or something?

**Comment by dilipkrish** [comment]
Im available on gitter
