### ISSUE TITLE
how to hide the parameter in swagger document

### ISSUE THREAD

**Issue by flytosm** [springfox/springfox#1820]
Hi everybody

There are some internal parameters which i don`t want to show in swagger document.
Is there any way to do this? Such as annotation and so on.

Best Regards

**Comment by dilipkrish** [comment]
You can either use @ApiIgnore individually for each operation or you can globally ignore parameters. Please check the documentation at http://springfox.io

**Comment by flytosm** [comment]
Hi @dilipkrish 

Thank you so much for your answer.
I will check the document.

Best Regards.

**Comment by dublintech** [comment]
Is there anyway to do this if you are using Swagger but not Spring?
