### ISSUE TITLE
default API group

### ISSUE THREAD

**Issue by eztinkerdreams** [springfox/springfox#1822]
How would I go about setting the defaultApi group that is selected?
The docs seem to indicate that you apply a custom sort function for the apiSorter, but I'm not clear on how to do this. 
This is a Spring Boot MVC application.
```java
@Bean
  UiConfiguration uiConfig() {
    return new UiConfiguration(
        "validatorUrl",// url
        "none",       // docExpansion          => none | list
        "alpha",      // apiSorter             => alpha
        "schema",     // defaultModelRendering => schema
        UiConfiguration.Constants.DEFAULT_SUBMIT_METHODS,
        false,        // enableJsonEditor      => true | false
        true,         // showRequestHeaders    => true | false
        60000L);      // requestTimeout => in milliseconds, defaults to null (uses jquery xh timeout)
  }
```

**Comment by dilipkrish** [comment]
If you're referring to the API group that is selected in the dropdown in swagger ui it is whatever is first on the list of dockets. [Swagger-ui](https://github.com/swagger-api/swagger-ui) comes with custom sort functions. From the docs:

> Apply a sort to the operation list of each API. It can be 'alpha' (sort by paths alphanumerically), 'method' (sort by HTTP method) or a function (see Array.prototype.sort() to know how sort function works). Default is the order returned by the server unchanged.
