### ISSUE TITLE
How to avoid parameter expansion when the parameter should be replaced?

### ISSUE THREAD

**Issue by ircecho** [springfox/springfox#1825]
Due to the following change ce035279f44990a1e71e4d4bf552dc84587d11fd we run into an infinite loop. We have a method parameter, which may contain recursions but we use an IdToEntity Converter so the Parameter should really be calles as Long. For this, I wrote a ParameterBuilderPlugin that replaces all such occurrences with Long and it works like a charm in 2.6.1. However, due to the above-mentioned change, in 2.7.0 the parameter is selected for expansion, which cannot complete because of the recursion and the ParameterBuilderPlugin is never even called.

Question: What is the correct way to handle this situation in 2.7.0?

PS: Due to the fact that this occurs in hundreds of places, I would like to avoid e.g. annotating all those occurences manually.

**Comment by dilipkrish** [comment]
So the change you're referring to is to fix the scenario where we want to expand properties not explicitly marked as `@RequestBody`/`@RequestPart` this is basically transforming the condition from a whitelist to a blacklist. 

So if your parameter is one of those, then the solution is to use an `@ApiModelProperty(dataType="java.lang.Long"...)` to in-place convert the type from the recursive type to `Long`. If its a model attribute then it should work as before. Would be nice if we had a concrete example. Perhaps create a breaking test in [BugsController](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java)?

**Comment by ircecho** [comment]
Unfortunately I could not reproduce the infinite loop in a test setup. However, I created a project to illustrate the problem here:

https://github.com/ircecho/super-duper-barnacle

I guess the problem is, that in 2.6.1 and before, the parameter Payment payment was not expanded because it had the annotation @RequestParam (or @PathVariable), then the IdConverterDataTypeReader was called, the parameter was translated to Long and everything was in order. In 2.7.0, however, due to ce035279f44990a1e71e4d4bf552dc84587d11fd, the Parameter payment gets expanded, and the IdConverterDataTypeReader is never called. In the example project, the parameter is therefore missing completely, in our real project this leads to an infinte loop.

As far as I can tell, the ParameterBuilderPlugin should be called before it is checked wether a Paramter needs to be expanded because the ParameterBuilderPlugin may change the parameter from shouldExpand to not shouldExpand or vice versa.

**Comment by dilipkrish** [comment]
@ircecho thanks for the example will take a look

**Comment by dilipkrish** [comment]
I went through your sample and here is my suggestion based on [what I see](https://github.com/ircecho/super-duper-barnacle/blob/master/src/main/java/com/example/demo/IdConverterDataTypeReader.java#L72-L82). You can do one of the following

1. If you have some mechanism of adding an argument resolver (outside of springfox, which I do not see in your sample). You can add alternate type rule for specific types say all `Payment.class` is substituted with `Long.class` using `Docket#directModelSubstitute`
2. If you don't want to do it explicitly you could implement an `AlternateTypeRuleConvention` and programmatically use reflection to find all subclasses of `AbstractEntity` and add a rule for the objects you care about.

**Comment by ircecho** [comment]
I still don't get why you would want to disallow the ParameterBuilderPlugin for all shouldExpand types. In my opinion this defeats the purpose of the ParameterBuilderPlugin as a whole, if I can only use it for basic types.

That way there is a ParameterBuilderPlugin that would allow, for example, to replace "String" by "Long" or the other way round, which could easily be solved by using a direct model substitute, but to replace a whole inheritance tree of hundreds or thousands of classes, which could easily be solved using a ParameterBuilderPlugin, you tell me to use reflection to enumerate all the classes and use direct model substitutes.

In my opinion it would be much more useful if the ParameterBuilderPlugin were to be called before the shouldExpand check in the OperationParameterReader, so that it could also be used to programmatically replace all kinds of parameter types.

**Comment by dilipkrish** [comment]
Have you tried it with 2.8.0?
>I still don't get why you would want to disallow the ParameterBuilderPlugin for all shouldExpand types. 

The reason is at this point it is already been determined if a parameter needs to be expanded or not. Its right there in the [link to the commit](https://github.com/springfox/springfox/commit/ce035279f44990a1e71e4d4bf552dc84587d11fd) you posted. Its at that point, either we use `ParameterBuilderPlugin` or `ExpandedParameterBuilderPlugin`. 

> That way there is a ParameterBuilderPlugin that would allow, for example, to replace "String" by "Long" or the other way round

Actually you can already do that with the `ParameterBuilderPlugin`, so Im a little confused? 

> In my opinion it would be much more useful if the ParameterBuilderPlugin were to be called before the shouldExpand check in the OperationParameterReader, so that it could also be used to programmatically replace all kinds of parameter types.

Thats the reason why you can create your own `OperationBuilderPlugin` plugin to do what you expecting to do by implementing your version of 👇 

https://github.com/springfox/springfox/blob/ce035279f44990a1e71e4d4bf552dc84587d11fd/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/operation/OperationParameterReader.java#L66-L69
