### ISSUE TITLE
[Question] Set up Swagger behind OAuth2

### ISSUE THREAD

**Issue by Ziemowit** [springfox/springfox#1826]
I have the Service which is a Resource Server (in term of OAuth2). 
So access to it is protected by access token.

Now I would like to give the possibility to make some operations on this Resource Server via Swagger and Springfox for users who has appropriate access token and administrator rights.

What is unclear for me is:

Should I open the access to Swagger endpoints for all users and the authorization should be made via Springfox itself? So the site should be visible by anyone but by default nothing should be doable there?

Or there is other correct way of set-up?

**Comment by dilipkrish** [comment]
@Ziemowit This is murky territory. Personally I feel swagger-ui (pre 3.0) is designed to be an open (un-protected) resource. The security definitions we add to describe operations are intended to protect the resources being exercised @ runtime. So if there are sensitive APIs that you do not want everyone to see, much less execute, then you may need to re-think/re-tool the existing setup.

**Comment by Ziemowit** [comment]
Thank you for your help!
I will be asking then on swagger-ui :)
