### ISSUE TITLE
Error when rendering recursively defined models

### ISSUE THREAD

**Issue by tcsw1221** [springfox/springfox#1827]
This error causes the stack to overflow in the ModelAttributeParameterExpander class：

![qbj 2eso wr344td igf0](https://cloud.githubusercontent.com/assets/28040861/26306123/c22c119a-3f24-11e7-9511-1c721cecc1c7.png)

I tried to fix it in my code：
`if (Types.isBaseType(itemType) || itemType.getErasedType().isEnum()) {
        parameters.add(simpleFields(context.getParentName(), context.getDocumentationContext(), each));
      } else {
        parameters.addAll(
            expand(
                    context.childContext(
                            nestedParentName(context.getParentName(), each.getField()),
                            each.getFieldType(),
                            context.getDocumentationContext())));
      }
    }`

In addition, because of the large number of my project interface, the project started very slow, compared to 2.5.0 version of a slow slow for a whole minute

**Comment by dilipkrish** [comment]
Would be able to create a minimal reproducible scenario? I don't understand what your implying by the highlighted code and your fix. Perhaps create a PR with a breaking test and your fix that solves the problem. 

That said. This tool isn't really meant for documenting controller methods with model attributes. It's for documenting http APIs.

**Comment by tcsw1221** [comment]
`class A {
  List<B> bList;
}`
`class B{
  List<A> aList;
}`

**Comment by tcsw1221** [comment]
The parameter is a non-aggregate type in the judgment of avoiding the collection type dead loop

**Comment by dilipkrish** [comment]
@tcsw1221 Thanks for the example thats what I suspected would be the case.

> The parameter is a non-aggregate type in the judgment of avoiding the collection type dead loop

I don't understand what that means.

Also, Im curious why you have a model thats so complicated. The ModelAttribute support is very basic and doesnt handle complex scenarios. It is only there for naive use cases. More complex models are better handled via `@RequestBody`s

**Comment by muka** [comment]
I have the same issue, the models causing such issue are those

https://github.com/raptorbox/raptor/tree/v4/raptor-models/src/main/java/org/createnet/raptor/models/auth

(It used to work in 2.5)

A log extract as example
```
Expanding parameter type: java.security.Principal
Expanding parameter type: org.createnet.raptor.models.auth.User
Expanding parameter type: java.util.List<org.createnet.raptor.models.auth.Device>
Expanding parameter type: java.util.List<org.createnet.raptor.models.auth.Token>
Expanding parameter type: java.util.List<org.createnet.raptor.models.auth.Role>
Expanding parameter type: org.createnet.raptor.models.auth.Device
Expanding parameter type: org.createnet.raptor.models.auth.User
Expanding parameter type: org.createnet.raptor.models.auth.Device
Expanding parameter type: org.createnet.raptor.models.auth.Token
Expanding parameter type: org.createnet.raptor.models.auth.Token
Expanding parameter type: org.createnet.raptor.models.auth.Role
Expanding parameter type: java.util.List<org.createnet.raptor.models.auth.User>
Expanding parameter type: org.createnet.raptor.models.auth.User
Expanding parameter type: org.createnet.raptor.models.auth.Device
Expanding parameter type: org.createnet.raptor.models.auth.Token
Expanding parameter type: org.createnet.raptor.models.auth.Token
...
```

Thanks

**Comment by dilipkrish** [comment]
@Muka sorry for the regression. For now you could ignore the offending operations (not a long term solution). Also curious about the preference for model attributes over request body, why??

**Comment by muka** [comment]
Hi @dilipkrish sorry but seems I jumped in in a "similar sounding" issue..  In fact I am using `@RequestBody` with the same looping situation. 

Do not know if this is related at this point or just a misuse on my side.

Here a companion usage example for your reference

https://github.com/raptorbox/raptor/blob/v4/raptor-api/raptor-auth/src/main/java/org/createnet/raptor/auth/controller/UserController.java

Thanks

**Comment by dilipkrish** [comment]
Thanks for the example @muka. Will take a look

**Comment by muka** [comment]
@dilipkrish  this issue is blocking and prevent the usage of the library at all. Do you have a workaround to suggest in the meanwhile?

If you can give me a few pointer to start looking at it, I would be happy to try followup on this

Thank you

**Comment by dilipkrish** [comment]
@muka TL;DR; version of it is that `ExpansionContext` is a poormans version of `ModelContext` it doesnt have the [ability to remember visited models](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/schema/contexts/ModelContext.java#L233-L235). We need to implement that.

**Comment by muka** [comment]
@dilipkrish I gave a look to that however I am currently unable to setup a proper environment due to my lack of knowledge of gradle. 
Do you thing would it be possible to generate maven pom.xml files for those legacy people like me? 

Best

**Comment by dilipkrish** [comment]
@muka What environment are you trying to set up? just running `/.gradlew clean build publishToMavenLocal ` will build the repository and publish to your maven local. thats the same as `mvn clean install`. As long as you're working with a git repo everything should just work. Unfortunately I don't have time to create an equivalent pom.

**Comment by juneryo** [comment]
Hello, I think I have the same problem when I use @ModelAttribute in controller ...
```
public String addBook(@ModelAttribute Book book) {
    // ......
}
```
Entities like:
```
public class Book {
    private String name;
    private Set<Author> authors;
    // ... set, get functions
}

public class Author {
    private String name;
    private List<Book> books;
     // ... set, get functions
}
```
Is there any solutions for this question for now ? (except use @RequestBody instead @ModelAttribute)

**Comment by 13482477** [comment]
Dear sir! I'm using an Hibernate Entity that include a collection with another Hibernate Entity, the recursive exception happend.
I hope a way to exclude attribute of Hibernate Entity using annotation when code execution,
or another way to customized filter logic.

**Comment by dilipkrish** [comment]
@13482477 You can annotated the attributes causing recursion using `@ApiModelProperty(hidden=true)`

**Comment by 13482477** [comment]
@dilipkrish Thank u for your help!..
