### ISSUE TITLE
The same RequestMapping with different params

### ISSUE THREAD

**Issue by hybaken** [springfox/springfox#1828]
Hi,

The below user controller contains two GET methods mapped to the same URL. Both got RequestParam.
```java
@RestController
@Api(value = "USER")
@RequestMapping("/users")
public class UserController {

        @RequestMapping(method = RequestMethod.GET, produces="application/json", params={"username"})
    @ResponseStatus(value= HttpStatus.OK)
    public Collection<User> getUsersByName(@RequestParam String username) {
        throw new NotImplementedException();
    }

    @RequestMapping(method = RequestMethod.GET, produces="application/json", params={"status"})
    @ResponseStatus(value= HttpStatus.OK)
    public Collection<User> getUsersByStatus(@RequestParam String status) {
        throw new NotImplementedException();
    }

}
```
UI will display just one.

Seems its related to this one:
https://github.com/springfox/springfox/issues/750

**Comment by dilipkrish** [comment]
This is a known problem with open api spec v 2.0. However an [incubating feature](http://springfox.github.io/springfox/docs/current/#springfox-rfc6570-support-strong-incubating-strong) allows you to work around the problem by `enablingUrlTemplating` in the docs. However keep in mind that this is not supported by swagger-ui out of the box.

**Comment by BetterWork4BetterWorld** [comment]
Hello, can you give more information or a link that explain how to use this feature plz ?

Google doesn't give anything on that...

**Comment by dilipkrish** [comment]
See link above @BetterWork4BetterWorld ☝️ 

Just support for RFC6570 to support url templating. This generates swagger endpoints with templated query parameters and there is a modified swagger-ui that supports having url templates for request parameters as well.

So in your example before the change you'd have only one url

`http://host:port/users`

after turning `enableUrlTemplating` on you'll see

`http://host:port/users{?username}`
`http://host:port/users{?status}`

**Comment by plfgavilan** [comment]
Hi, thanks @dilipkrish but I changed to this dependency springfox-swagger-ui-rfc6570:1.0.0 to support url templating, but I still have only one endpoint intead of two (with the same uri but diferent parameters)

What's still missing?

Thank in advance

**Comment by dilipkrish** [comment]
@plfgavilan you're missing configuring your docket with `enableUrlTemplating(true)`
