### ISSUE TITLE
CORS headers disappeared after upgrading to 2.7.0

### ISSUE THREAD

**Issue by gionn** [springfox/springfox#1830]
Hi,

after upgrading springfox from 2.6.1 to 2.7.0, all the /api-docs endpoint started to have missing CORS headers.

I am configuring CORS at spring-level with:

```
    @Override
    public void addCorsMappings( CorsRegistry registry )
    {
        registry.addMapping( "/**" ).allowedMethods( "GET", "HEAD", "POST", "PUT", "DELETE", "PATCH" );
    }
```

**Comment by dilipkrish** [comment]
This may be a regression. In 2.7.0 we [hand rolled the controller](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/configuration/Swagger2DocumentationConfiguration.java#L50-L58) that is responsible for /api-docs. Not sure how to add Cors settings when its not loaded as a `RequestMapping` automatically.

**Comment by shavo007** [comment]
wow. i have spent the last hour trying to figure out why this was not working. be great if the docs reflected this as a known issue. http://springfox.github.io/springfox/docs/current/#answers-to-common-questions-and-problems *21. How to add CORS support? (thanks @gangakrishh)

**Comment by zlangbert** [comment]
This bit me as well, and chance there will be a fix / release soon? Without being able to configure cors I'm unable to use springfox unfortunately.

**Comment by dilipkrish** [comment]
@zlangbert working on that in the next few weeks.

**Comment by zlangbert** [comment]
@dilipkrish Awesome, thanks!
