### ISSUE TITLE
@ApiParam hidden=true does not work on @RequestHeader

### ISSUE THREAD

**Issue by scottf** [springfox/springfox#1831]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Bug report. 

Using `@ApiIgnore` hides the header in the documentation
```
@ApiIgnore
@ApiParam(value = "x-foo-hiddenTrue-apiIgnoreOn", required = false, hidden = true, defaultValue = "should be hidden")
@RequestHeader("x-foo-hiddenTrue-apiIgnoreOn") String xFooHiddenTrueApiIgnoreOn,
```
But without `@ApiIgnore` it does not hide
```
@ApiParam(value = "x-foo-hiddenTrue-apiIgnoreOff", required = false, hidden = true, defaultValue = "should be hidden")
@RequestHeader("x-foo-hiddenTrue-apiIgnoreOff") String xFooHiddenTrueApiIgnoreOff,
```

**Comment by dilipkrish** [comment]
Thanks for catching that!

**Comment by scottf** [comment]
So I was not entirely clear regarding the issue. It happens regardless of @ApiIgnore when there is a Global version of the header So I'm going to re-document the issue. First here is my truth table:

|name|Required|hidden|defaultValue|global description|use ApiIgnore|
|----|----|----|----|----|----|
|x-foo-g1-ft|false|true|should be hidden|foo desc global 1 ft|false|
|x-foo-g1-ff|false|false|this is visible|foo desc global 1 ff|false|
|x-foo-g1-tt|true|true|should be hidden|foo desc global 1 tt|false|
|x-foo-g1-tf|true|false|this is visible|foo desc global 1 tf|false|
|x-foo-g2-ft|false|true|should be hidden|foo desc global 2 ft|true|
|x-foo-g2-ff|false|false|this is visible|foo desc global 2 ff|true|
|x-foo-g2-tt|true|true|should be hidden|foo desc global 2 tt|true|
|x-foo-g2-tf|true|false|this is visible|foo desc global 2 tf|true|


My Gradle:
``` 
springfoxVersion = '2.7.0'
dependencies {
 ... 
 compile "io.springfox:springfox-swagger2:${springfoxVersion}"
 compile "io.springfox:springfox-data-rest:${springfoxVersion}"
 compile "io.springfox:springfox-bean-validators:${springfoxVersion}"
 compile "io.springfox:springfox-swagger-ui:${springfoxVersion}"
```

My Docket contains this:
```
.ignoredParameter`Types(ApiIgnore.class)
.globalOperationParameters(globalOperationParameters)
```
globalOperationParameters was built like this:
```
List<Parameter> globalOperationParameters = new ArrayList<>();
globalOperationParameters.add( header("x-foo-g1-ft", "foo desc global 1 ft", false) );
globalOperationParameters.add( header("x-foo-g1-ff", "foo desc global 1 ff ", false) );
globalOperationParameters.add( header("x-foo-g1-tt", "foo desc global 1 tt", true) );
globalOperationParameters.add( header("x-foo-g1-tf", "foo desc global 1 tf", true) );
globalOperationParameters.add( header("x-foo-g2-ft", "foo desc global 2 ft", false) );
globalOperationParameters.add( header("x-foo-g2-ff", "foo desc global 2 ff", false) );
globalOperationParameters.add( header("x-foo-g2-tt", "foo desc global 2 tt", true) );
globalOperationParameters.add( header("x-foo-g2-tf", "foo desc global 2 tf", true) );

...
private Parameter header(String name, String description, boolean required) {
    return new ParameterBuilder().name(name).description(description)
            .required(required).parameterType("header").modelRef(new ModelRef("string")).build();
}
```

My controller:
```
@RequestMapping(method = RequestMethod.GET)
public ResponseEntity fooGet(
	
  @ApiParam(value = "x-foo-g1-ft", required = false, hidden = true, defaultValue = "should be hidden")
  @RequestHeader("x-foo-g1-ft") String xFooG1Ft,

  @ApiParam(value = "x-foo-g1-ff", required = false, hidden = false, defaultValue = "this is visible")
  @RequestHeader("x-foo-g1-ff") String xFooG1Ff,

  @ApiParam(value = "x-foo-g1-tt", required = true, hidden = true, defaultValue = "should be hidden")
  @RequestHeader("x-foo-g1-tt") String xFooG1Tt,

  @ApiParam(value = "x-foo-g1-tf", required = true, hidden = false, defaultValue = "this is visible")
  @RequestHeader("x-foo-g1-tf") String xFooG1Tf,


  @ApiIgnore
  @ApiParam(value = "x-foo-g2-ft", required = false, hidden = true, defaultValue = "should be hidden")
  @RequestHeader("x-foo-g2-ft") String xFooG2Ft,

  @ApiIgnore
  @ApiParam(value = "x-foo-g2-ff", required = false, hidden = false, defaultValue = "this is visible")
  @RequestHeader("x-foo-g2-ff") String xFooG2Ff,

  @ApiIgnore
  @ApiParam(value = "x-foo-g2-tt", required = true, hidden = true, defaultValue = "should be hidden")
  @RequestHeader("x-foo-g2-tt") String xFooG2Tt,

  @ApiIgnore
  @ApiParam(value = "x-foo-g2-tf", required = true, hidden = false, defaultValue = "this is visible")
  @RequestHeader("x-foo-g2-tf") String xFooG2Tf
) 
{...}
```
I'm hitting `http://localhost:8080/swagger-ui.html#!/foo/getFoo` . Any header name that ends with "t" should be hidden. This is the result where things aren't hidden. Ordering is weird and descriptions end up weird too.

![image](https://cloud.githubusercontent.com/assets/215946/26466702/ab5d2a90-415d-11e7-8348-fc287f23b189.png)

So the issues I see are:
* Items that should be hidden are not, with or without ApiIgnore
* some descriptions are the field name, instead of the global description
* required items that have a default value show (required). Not sure this is a real use case, but just noting it.

**Comment by dilipkrish** [comment]
👏 this might be the most detailed issue I've received! thank you so much. It makes fixing these bugs so much easier.

**Comment by mmaenzaFandango** [comment]
Hi, is there a fix for this?

**Comment by dilipkrish** [comment]
Not yet @mmaenzaFandango. But there should be in the next release

**Comment by dilipkrish** [comment]
__breadcrumbs__ in case someone is willing to take a shot a fixing it.

https://github.com/springfox/springfox/blob/d32ef1a1620e16def01aa18495b36a846322ab07/springfox-core/src/main/java/springfox/documentation/builders/ParameterMerger.java#L70-L97

We need to make sure we assign priorities to parameters. Global parameters should have lower priority than specific annotated parameters as shown by @scottf.
