### ISSUE TITLE
best way to handle ResponseEntity<?> with two object types

### ISSUE THREAD

**Issue by xdecroc** [springfox/springfox#1834]
I'm using springfox 2.6.1

I have a controller which returns a config object or if there is an exception a ErrorDTO object.
because I am using ResponseEntity<?> when I generate the swagger i'm getting an  empty model schema {}. Is there a recommended pattern for this as I would image this a common use case ?

issue1764: recommends replacing ResponseEntity<?> with a type but I need to able to return either type and not a primitive type.

    @ApiOperation(value="getCurrentConfig")
    @GetMapping(value="/current/internal", produces = {"application/json" })
    	public ResponseEntity<?> getCurrentConfig(){
		
		DataConfiguration config  = configService.getCurrentConfig();		
		if (currentConfig != null){			
			return new ResponseEntity<DataConfiguration>(currentConfig, HttpStatus.OK);
		}else{			
			ErrorDTO errDTo = ErrorDTO.builder().clientMsg("error msg ...").httpStatus(HttpStatus.NOT_FOUND.toString()).build();
			return new ResponseEntity<ErrorDTO>(errDTo, HttpStatus.NOT_FOUND);
		}		
	}

Thank you for your time.

**Comment by dilipkrish** [comment]
My recommendation is to make the following changes:
- Change the method signature to this `public ResponseEntity<DataConfiguration> getCurrentConfig(){..`
- Add `@ApiResponses` annotation for the ErrorDTO along with the `NOT_FOUND` status code
