### ISSUE TITLE
2.7.0 not rendering json for /v2/api-docs

### ISSUE THREAD

**Issue by kcornelsen** [springfox/springfox#1835]
[ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

I am trying to upgrade to 2.7.0 from 2.6.1 in my spring boot application but am unable to get the json to render in the browser at the /v2/api-docs endpoint (works correctly for the 2.6.1 version and is working for swagger-ui.html)

chrome error: 
This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

firefox error:
XML Parsing Error: not well-formed Location: http://localhost:8084/v2/api-docs?group=users Line Number 1, Column 1:

**Comment by dilipkrish** [comment]
I think you might have perhaps a JAXB binding taking precedence over jackson. Try curling or using a rest client tool with Accept header of `application/json` and see what it gives you

**Comment by bjpe** [comment]
Hi @dilipkrish, I also have this issue after I added jackson-dataformat-xml as a dependency. The problem is that the response body contains the JSON string as requested, but the content type is set to `application/xhtml+xml;charset=UTF-8` since the browser originally requested `Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`.

Do you know a solution/workaround such that I can open the URL in my browser?

**Comment by csbxvs** [comment]
Hi @dilipkrish, we are also encountering this error, exactly as @bpe has described, the body contains JSON but the content type is set to application/xml. We are running 2.7.0. When we rolled back to 2.6.1, the error disappeared and we were able to load JSON in the browser again.

**Comment by dilipkrish** [comment]
Spring automatically adds message converters by looking at the class path. So in your case xml seems like the first one on the list.

**Comment by csbxvs** [comment]
Thanks @dilipkrish , it ended up being similar to what you described, the wrong object mapper (an internal xml one) was being used because of a bean misconfiguration. The only thing I'm still curious about is the reason why the api spec generation still worked on 2.6.1 but not 2.7.0, were there changes to the way springfox handles request responses or do you still think it was just a random classpath ordering?

**Comment by dilipkrish** [comment]
It could be spring related. The versions of spring dependencies did change.

**Comment by jonbcs** [comment]
Hi @csbxvs  what changes did you make in your bean configuration? I am having this same issue.

**Comment by ptheohar** [comment]
Hi @jonbcs,
Try adding the below configuration in your WebMvcConfigurerAdapter:

```@Override
public void addResourceHandlers(ResourceHandlerRegistry registry) {
	registry.addResourceHandler("swagger-ui.html")
			.addResourceLocations("classpath:/META-INF/resources/");
	registry.addResourceHandler("/webjars/**")
			.addResourceLocations("classpath:/META-INF/resources/webjars/");
}

**Comment by aarunbala** [comment]
Hi @dilipkrish, I'm currently using Spring boot 1.5.8/9 with Swagger 2.8.0, also using Jackson-databind-xml for consuming a XML webservice, but I still get the below issue when trying to access /v2/api-docs, any way to get around it other than removing jackson-databind-xml

**This page contains the following errors:
error on line 1 at column 1: Document is empty**

**Comment by dilipkrish** [comment]
You need to send in an accept header of `application/json` or ensure that the jackson message converter has higher priority than xml.

**Comment by shafsongithub** [comment]
how can we expect the result in browser?

**Comment by dilipkrish** [comment]
@shafsongithub in json if the message converter that gets priority is the json message converter

**Comment by ahctang** [comment]
Is there any real fix for this problem other than calling the endpoint in postman instead of the browser?

**Comment by ahctang** [comment]
Forcing the accept content header does in fact fix the problem. But having the entire feature not functioning out of the box, if you have Jackson xml included as a dependency is in my opinion a fairly serious problem. 

I would have never have figured out that Jackson xml was the problem had I not stumbled upon this issue thread.

**Comment by dilipkrish** [comment]
@ahctang it is serious problem that the [Swagger-ui](https://github.com/swagger-api/swagger-ui) is not sending in accept headers by default. Unfortunately thats not in the purview of this library.

**Comment by huksley** [comment]
it is still the same problem with 2.9.2 version of springfox
reproducible
https://github.com/huksley/spring-boot2-template

**Comment by dilipkrish** [comment]
Could you create a simple project that illustrates the issue or may be create a breaking test. It seems like a lot of setup needs to happen to load up the project and launch it.

**Comment by huksley** [comment]
@dilipkrish 
Here you are, I removed all not neccessary, just run `TestSystem.testSwaggerAsRequestedByBrowser` or `mvn clean package`

https://github.com/huksley/springfox-issue-1835

The problem appears when running with `Accept` header as in browser, i.e. then `Accept` header does not explicitely requests `application/json`.

**Comment by dilipkrish** [comment]
@huksley thanks for that! I see whats happening. Im not aware of any mechanism to restrict the content negotiation machinery in spring mvc other than [specifying the produces](https://github.com/springfox/springfox/blob/09d4a734b64a216bb5c26c0329f3d15b8276c0e4/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L84). Now we did fix the swagger-ui to send in the [accept headers](https://github.com/springfox/springfox/blob/09d4a734b64a216bb5c26c0329f3d15b8276c0e4/springfox-swagger-ui/src/web/js/springfox.js#L11-L14), that way it doesnt render arbitrary content based on the browser defaults.

In your case, it appears that the `jackson-dataformat-xml` is in the class path, which is why your test is failing as spring machinery finds the xml message converter based on the specified `Accept` header.

**Comment by huksley** [comment]
Thanks @dilipkrish !
As far as I understood, it will work now if I remove `jackson-dataformat-xml` from dependencies.
But your change, will it work now without removing it? Maybe in next release?

**Comment by dilipkrish** [comment]
I dont think it will fix it, it seems like a spring fx issue. I'll ask, or may be you could in the [spring framework project](https://github.com/spring-projects/spring-framework)

**Comment by vijayakumar-psg587** [comment]
@huksley Just curious, was a contentnegotiationManager implemented to get over it? Something similar to this?. You might have tried with this already but just wanted to make sure
```
@Override
	public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
		configurer.favorPathExtension(false)
		.favorParameter(false).ignoreUnknownPathExtensions(true).useRegisteredExtensionsOnly(true)
	     .defaultContentType(MediaType.APPLICATION_JSON); 
	}
	
```

**Comment by vajahatalee** [comment]
I have the same issue, i am simply running the sample [spring boot starter project](https://github.com/ff4j/ff4j-samples/tree/master/ff4j-sample-springboot-starter). 
I didn't modify any file at all and I can reproduce the issue. /v2/api-docs link results in the empty page. looking forward for fixing/suggestions.

**Comment by huksley** [comment]
@vijayakumar-psg587 I haven`t fixed this bug. 
As suggested by @dilipkrish removing `jackson-dataformat-xml` should fix the bug

**Comment by vijayakumar-psg587** [comment]
@huksley thanks for response and I am sorry for the delay in getting back.

Here what has happened in my case.

 So apparently the issue was becasuse of the default "Content-type" getting sent in the request seem to have "application/xml" instead of "application/json" only when triggering /v2/api-docs. Seems to work perfectly in postman if the "Content-type" is being set. I wrote a filter to modify the content-type for this request alone and now it works fine, 

The other lengthy workaround and I got that working as well . Here it is 
https://stackoverflow.com/questions/53867077/cannot-write-new-response-in-servlet-filter/53920744#53920744

I actually got it working with the second fix but one of my collegue pointed out the obvious issue with the "Content-type" which kind of left me "face-palm" moment. :)

**Comment by huksley** [comment]
@vijayakumar-psg587 yes, I have a similar fix. But I thought that it should work out of the box and not do any content renegotiation so content type stays the same.

**Comment by Schacal** [comment]
I have also described problem like author
I'm using springfox version `2.9.2`
When I go to [http://localhost:8080/v2/api-docs](http://localhost:8080/v2/api-docs) then error is returned:

`This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.`
But when I clicked "View Page Source" in Chrome then I can see all JSON body content with generated endpoints.

When I reverted springfox version to `2.6.0` the everything is ok. JSON is returned properly.

**Comment by vijayakumar-psg587** [comment]
> @vijayakumar-psg587 yes, I have a similar fix. But I thought that it should work out of the box and not do any content renegotiation so content type stays the same.

I tried removing the jackson-dataformat-xml from my dependencies but it did not help. Hence opted for the other solution

**Comment by huksley** [comment]
@vijayakumar-psg587 Check this out 
https://github.com/huksley/spring-boot2-template/blob/master/src/main/java/com/github/huksley/app/system/SwaggerConfig.java#L172

**Comment by raminsrad** [comment]
Yes, **jackson-dataformat-xml** is definitely causing this issue. I couldn't remove it because it's needed; I just overrode and added a **RequestMappingHandlerAdapter** to force it to use JSON as the media type. (Note, this is for Spring Boot, if you have Spring MVC, then I think you have to override **AnnotationMethodHandlerAdapter** bean instead.

```java 
@Bean
public RequestMappingHandlerAdapter requestHandler() {
    RequestMappingHandlerAdapter adapter = new RequestMappingHandlerAdapter();
    MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
    List<MediaType> mediaTypeList = new ArrayList<>();
    mediaTypeList.add(MediaType.APPLICATION_JSON);
    converter.setSupportedMediaTypes(mediaTypeList);
    adapter.getMessageConverters().add(converter);
    return adapter;
}
```

**Comment by muneshshar** [comment]
did we get any resolution to populate the /v2/apidocs with header application/json?

**Comment by b-d-m-jones** [comment]
> 
> 
> Yes, **jackson-dataformat-xml** is definitely causing this issue. I couldn't remove it because it's needed; I just overrode and added a **RequestMappingHandlerAdapter** to force it to use JSON as the media type. (Note, this is for Spring Boot, if you have Spring MVC, then I think you have to override **AnnotationMethodHandlerAdapter** bean instead.
> 
> ```java
> @Bean
> public RequestMappingHandlerAdapter requestHandler() {
>     RequestMappingHandlerAdapter adapter = new RequestMappingHandlerAdapter();
>     MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
>     List<MediaType> mediaTypeList = new ArrayList<>();
>     mediaTypeList.add(MediaType.APPLICATION_JSON);
>     converter.setSupportedMediaTypes(mediaTypeList);
>     adapter.getMessageConverters().add(converter);
>     return adapter;
> }
> ```

Thank you, @raminsrad ! This worked for me.

**Comment by acolak** [comment]
Hello All,

I resolved this issue by updating jackson-dataformat-xml to version 2.9.4

**Comment by edisonan** [comment]
> jackson-dataformat-xml

how to updating jackson-dataformat-xml?

**Comment by acolak** [comment]
> > jackson-dataformat-xml
> 
> how to updating jackson-dataformat-xml?

by pom.xml

**Comment by copitz** [comment]
It's definitely jackson xml that introduces the problem (2.9.8 in my case) but I couldn't find out why Spring maps the response to XML as the Swagger2Controller clearly defines that it doesn't produce XML...

@raminsrad workaround didn't work for me as it broke request mappings with other media types than JSON so I ended up with this configuration that fixes it based on the swagger path:

```java
@Configuration
public class SwaggerWebConfig {
  private static final List<MediaType> SWAGGER_MEDIA_TYPES = Arrays.asList(
    MediaType.APPLICATION_JSON, MediaType.valueOf("application/hal+json")
  );

  /**
   * Avoid swagger api being mapped to XML with jackson xml on the class path
   *
   * @param manager     Using the ready built content negotiation manager instead of
   *                    {@link org.springframework.web.servlet.config.annotation.ContentNegotiationConfigurer}
   *                    to not mess with other configurations
   * @param swaggerPath The path on which the swagger specs are served
   */
  @Autowired
  public void addSpringfoxContentNegotiation(
    ContentNegotiationManager manager,
    @Value("${springfox.documentation.swagger.v2.path:" + Swagger2Controller.DEFAULT_URL + "}") String swaggerPath
  ) {
    manager.getStrategies().add(0, webRequest -> {
      HttpServletRequest request = webRequest.getNativeRequest(HttpServletRequest.class);
      if (request != null && request.getServletPath().startsWith(swaggerPath)) {
        return SWAGGER_MEDIA_TYPES;
      }
      return ContentNegotiationStrategy.MEDIA_TYPE_ALL_LIST;
    });
  }
}
```

**Comment by AmirBen78** [comment]
My workaround without code or pom modification:
You have to replace the "/v2/api-docs" path by a path with .json extension by setting up the following property:
springfox.documentation.swagger.v2.path=/v2/api-docs.json
Of course the URL to access the JSON will change by the new one.

To explain why a path with json works, the native ServletPathExtensionContentNegotiationStrategy will interpret the extension (.json) and set the MediaType as "application/json".

**Comment by gillianbc** [comment]
> Yes, **jackson-dataformat-xml** is definitely causing this issue. I couldn't remove it because it's needed; I just overrode and added a **RequestMappingHandlerAdapter** to force it to use JSON as the media type. (Note, this is for Spring Boot, if you have Spring MVC, then I think you have to override **AnnotationMethodHandlerAdapter** bean instead.
> 
> ```java
> @Bean
> public RequestMappingHandlerAdapter requestHandler() {
>     RequestMappingHandlerAdapter adapter = new RequestMappingHandlerAdapter();
>     MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
>     List<MediaType> mediaTypeList = new ArrayList<>();
>     mediaTypeList.add(MediaType.APPLICATION_JSON);
>     converter.setSupportedMediaTypes(mediaTypeList);
>     adapter.getMessageConverters().add(converter);
>     return adapter;
> }
> ```

Thank you.  That worked for me too (in Chrome only, not Safari) :-)
