### ISSUE TITLE
id input box not generated for "HEAD" request

### ISSUE THREAD

**Issue by eztinkerdreams** [springfox/springfox#1836]
```java
@GetMapping(value = "/{id}")
default HttpEntity<Resource<T>> findOne(@PathVariable(value = "id") String id)
```
Generates a convenient input field like this:
<img width="634" alt="screen shot 2017-05-24 at 11 52 49 am" src="https://cloud.githubusercontent.com/assets/7387907/26417897/ae1c7cc2-4077-11e7-9cae-02926b72e1f0.png">

But changing to use a 'HEAD' method doesn't generate the input field. The closest I've been able to get is this:

```java
@RequestMapping(method = HEAD, value = "/{id}")
@ApiImplicitParams(
     @ApiImplicitParam(name = "id", dataType = "string", required = true)
)

default HttpEntity exists(@PathVariable(value = "id") String id)
```
<img width="633" alt="screen shot 2017-05-24 at 11 56 32 am" src="https://cloud.githubusercontent.com/assets/7387907/26418066/1f0ab7a0-4078-11e7-9216-00201795373c.png">

**Comment by dilipkrish** [comment]
Have you tried without the `@ApiParams...` annotation?

**Comment by eztinkerdreams** [comment]
@dilipkrish Yes sir, without that, no input field shows at all, the only way I was able to get one to show up was using the `@ApImplicitParams` annotation, but It's something specific to a 'HEAD' request, everything works normally with normal with other typical Http method verbs.

**Comment by vijaykalidindi** [comment]
I am having the same problem. However, even when I use `@ApiImplicitParams(
     @ApiImplicitParam(name = "id", dataType = "string", required = true)
)` , the text field is not editable. The documentation for using the `paramtype="path"` is also not very clear. Could you please post an example on its usage, google did not help me on this. All the examples shoe only `paramtype="query"`

**Comment by eztinkerdreams** [comment]
@vijaykalidindi This is the only way I was able to get it to work, and have the field be editable

```
public interface Exists<T extends GbEntity, ID extends Serializable> extends Operation<T, ID> {

	@ApiOperation(value = EXISTS_NAME)
	@RequestMapping(method = HEAD, value = EXISTS_PATH)
	@ApiImplicitParams(
		@ApiImplicitParam(name = "id", dataType = "string", required = true)
	)
	default HttpEntity exists(@PathVariable(value = "id") String id) {
		return Operations.exists(
			this.getEntityService(),
			this.getEntityClass(),
			this.getEntityLinks(),
			id
		);
	}
}
```

**Comment by dilipkrish** [comment]
Not sure need to investigate.

**Comment by dilipkrish** [comment]
@eztinkerdreams You need to create your own ui configuration bean and define the `supportedSubmitMethods`property
