### ISSUE TITLE
Primary keys are added to path parameters for Spring Data Rest Entities POST request after upgrading to 2.7.0

### ISSUE THREAD

**Issue by jadhavsuhas** [springfox/springfox#1839]
After upgrading to 2.7.0  from 2.6.2-SNAPSHOT, 
Springfox adds  primary keys as path parameters in Post requests for Spring Data Rest Entities.
Swagger Editor throws
"Semantic error at paths./api/EntityNames.post.parameters[0]
Path parameter id was defined but never used"

Is there a way to get rid of the primary key from the path params?
 - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32

**Comment by dilipkrish** [comment]
This may be a bug, Could you describe where you're seeing this error? Would you mind providing a breaking scenario using [one of these repositories](https://github.com/springfox/springfox/tree/master/swagger-contract-tests/src/main/java/springfox/test/contract/swagger/data/rest) as an example?

**Comment by jadhavsuhas** [comment]
Hi,
I am getting the primary keys in input for all the entities . Consider an Test entity 
FunctionToRole{
@EmbeddedId
	private FunctionToRoleId functionToRole;

..getter,setter
}
where,
public class FunctionToRoleId implements Serializable  {
	@Column(name = "FUNCTION_ID")
	private long fkUserFunctionId;
	
	@Column(name = "ROLE_ID")
	private long fkUserRoleId;
...getter setter
}

I get in the YAMLfor post:

post:
      tags:
        - FunctionToRole Entity
      summary: saveFunctionToRole
      operationId: saveFunctionToRoleUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: fkUserFunctionId
          in: query
          required: false
          type: integer
          format: int64
        - name: fkUserRoleId
          in: query
          required: false
          type: integer
          format: int64
        - in: body
          name: body
          description: body
          required: true
          schema:
            $ref: '#/definitions/FunctionToRole'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Resource«FunctionToRole»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

I tested post method in swagger ui by providing values in body only, it works fine.But when the entity does not have embedded id, the path parameter id is required=true.
So the documentation is incorrect in that case.

As 2.7.0 is listing the associations nicely as separate apis, wanted to upgrade to this version.
Let me know if I can help with anything else.

**Comment by jadhavsuhas** [comment]
I was able to hide the primary keys as query params using below snippet in ParameterBuilderPlugin,couln't remove from entities containing embedded pk though

if(parameterContext.getOperationContext().httpMethod().matches("POST"))
    {
    	if(parameterContext.resolvedMethodParameter().defaultName().isPresent()&&
    			parameterContext.resolvedMethodParameter().defaultName().toString().equalsIgnoreCase("Optional.of(id)")){
    		
    		parameterContext.parameterBuilder().hidden(true);
    		
    	}

**Comment by jadhavsuhas** [comment]
https://github.com/springfox/springfox/blob/master/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/EntitySaveExtractor.java

for post methods,path param id should not be introduced, will create a pull request

**Comment by jadhavsuhas** [comment]
corrected file at 
https://github.com/springfox/springfox/issues/1866

**Comment by rasheedamir** [comment]
@dilipkrish wondering how can I use this fix? Is there any snapshot version? Its blocking us.

**Comment by dilipkrish** [comment]
There is a snapshot version. Please refer the docs
