### ISSUE TITLE
Overloaded method does not respect the "tag" option

### ISSUE THREAD

**Issue by jackmatt2** [springfox/springfox#1841]
springfox@2.7.0

It appears that if you have two overloaded methods with different media types and add a `tag = {"User"}` in the `@Api` annotation as follows:

![image](https://cloud.githubusercontent.com/assets/6348088/26477163/0b090f32-4207-11e7-94b7-40acefeec6be.png)

The generated swagger output splits the operations into different panels and does not respect the tag annotation for the overloaded method.

![image](https://cloud.githubusercontent.com/assets/6348088/26477199/4eb85ada-4207-11e7-93ca-d3452f21459d.png)

**Comment by dilipkrish** [comment]
Hmm. That's an oddish bug! Thanks for reporting. While the tags deftly don't match up, I would expect that you would still see bothe media types documented correctly in the findall method. IOW it should be semantically correct in in terms of wire representation.

**Comment by jackmatt2** [comment]
Yes, inside `findAll()` I can select both media types in the dropdown on the swagger html output.

**Comment by dilipkrish** [comment]
👍🏼 I'll look at why it's not respecting the tag.
