### ISSUE TITLE
BasePath overriding using a custom PathProvider

### ISSUE THREAD

**Issue by cbeaujoin** [springfox/springfox#1845]
Hello,

since 2.6 I used a custom PathProvider in order to override the base path provided by the swagger generated doc.

I tried to upgrade to 2.7 (in order to fix an issue around proxy host & port => it fix it) but I'm not able to override the base path anymore using the following code:

```
protected class BasePathAwareRelativePathProvider extends AbstractPathProvider {
        private String basePath;

        public BasePathAwareRelativePathProvider(String basePath) {
            this.basePath = basePath;
        }

        @Override
        protected String applicationPath() {
            return basePath;
        }

        @Override
        protected String getDocumentationPath() {
            return "/";
        }

        @Override
        public String getOperationPath(String operationPath) {
            final UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/");
            return removeAdjacentForwardSlashes(
                    uriComponentsBuilder.path(operationPath.replaceFirst(basePath, "")).build().toString());
        }
    }
```

It results in the following base path : 

> basePath: "{myCustomBasePath}/{servletContextBasePath}",

It's like the pathProvider acts as the pathMapping.

Any sugestion ?

**Comment by dilipkrish** [comment]
That looks to be correct (though not what you might be expecting). The right way to influence the base path for proxy situations is to use the standard `X-Forwarded` headers.

**Comment by dilipkrish** [comment]
Would be useful to know how to accommodate your scenario as well. Your inputs would be greatly appreciated.

**Comment by dilipkrish** [comment]
Also worth trying [this solution](https://github.com/springfox/springfox/issues/1443#issuecomment-274540681). I should know this, but I can't say without looking at how the code works.

**Comment by gajanan999** [comment]
Hi @dilipkrish 

Could you please provide the best solution to add a base path to swagger 3.0.0 if you have any solution for it
