### ISSUE TITLE
HTML code in API description in ignored using springfox-swagger-ui 2.7.0

### ISSUE THREAD

**Issue by anouarchattouna** [springfox/springfox#1847]
## Should be fixed by [#1613](https://github.com/springfox/springfox/issues/1613), but the problem persists !

spring-boot : 1.5.3.RELEASE
springfox-swagger2 : 2.5.0 + HTML code in API description :

![swagger-ui-2 5 0](https://cloud.githubusercontent.com/assets/9251649/21343909/635d85bc-c699-11e6-95b4-7134afe376ea.png)

When I updated springfox-swagger2 to **2.7.0**, the HTML code is ignored:

![swagger-ui-2 6 1](https://cloud.githubusercontent.com/assets/9251649/21343952/975fe47c-c699-11e6-89c2-9782ac7c5410.png)

How to reproduce:

- git clone https://github.com/anouarchattouna/spring-boot-sample-logback-access-swagger.git
- cd spring-boot-sample-logback-access-swagger
- mvn clean install && java -Dspring.profiles.active=dev -jar target/spring-boot-sample-logback-access-swagger-0.0.3-SNAPSHOT.jar
- open the swagger ui : http://localhost:8080/swagger-ui.html [***OK***]

Now stop the running server, update the swagger version to **2.7.0** from the pom.xml : 
>			
			<springfox.swagger2.version>2.7.0</springfox.swagger2.version>

- mvn clean install && java -Dspring.profiles.active=dev -jar target/spring-boot-sample-logback-access-swagger-0.0.3-SNAPSHOT.jar
- open the swagger ui : http://localhost:8080/swagger-ui.html [***KO***]

Can you please tell me how to keep the first look and feel?

Thank you for your help.

**Comment by anouarchattouna** [comment]
@dilipkrish can you have a look please ?
@kyrill007

**Comment by dilipkrish** [comment]
Swagger-ui may be still busted. Let me look

**Comment by anouarchattouna** [comment]
@dilipkrish any news ?

**Comment by anouarchattouna** [comment]
@dilipkrish is it a Swagger-ui version issue?

**Comment by dilipkrish** [comment]
Yes it is very possible that the swagger-ui version is the problem.

**Comment by mikegodber** [comment]
Hopefully this will help anyone who stumbles across this like me. It looks like it is not a bug in Swagger UI but an intentional decision to defend against XSX attacks, see here: https://github.com/swagger-api/swagger-ui/issues/830. 

You will need to use markdown to format your descriptions with this version
