### ISSUE TITLE
Java 8 Optional @RequestParam lost from the swagger-ui

### ISSUE THREAD

**Issue by anouarchattouna** [springfox/springfox#1848]
spring-boot : 1.5.3.RELEASE
springfox-swagger2 : 2.5.0 :

`@ApiParam(value = "Optional String optionalCountryName", required = false) @RequestParam("optionalCountryName") final Optional<String> optionalCountryName`

![swagger-ui-2 5 0](https://cloud.githubusercontent.com/assets/9251649/26547317/b12e9666-446e-11e7-8d39-61adc3db413e.png)

When I updated springfox-swagger2 to **2.7.0**, the request parameter was lost from the UI:

![swagger-ui-2 7 0](https://cloud.githubusercontent.com/assets/9251649/26547402/29ce8b94-446f-11e7-98ef-037ed919a45e.png)

How to reproduce:

- git clone https://github.com/anouarchattouna/spring-boot-sample-logback-access-swagger.git
- cd spring-boot-sample-logback-access-swagger
- mvn clean install && java -Dspring.profiles.active=dev -jar target/spring-boot-sample-logback-access-swagger-0.0.3-SNAPSHOT.jar
- open the swagger ui : http://localhost:8080/swagger-ui.html ==> the optional parameter is present [***OK***]

Now stop the running server, update the swagger version to **2.7.0** from the pom.xml : 
>			
			<springfox.swagger2.version>2.7.0</springfox.swagger2.version>

- mvn clean install && java -Dspring.profiles.active=dev -jar target/spring-boot-sample-logback-access-swagger-0.0.3-SNAPSHOT.jar
- open the swagger ui : http://localhost:8080/swagger-ui.html ==> the optional parameter is not present [***KO***]

Can you please tell me how to keep showing optional parameters ?

Thank you for your help.

**Comment by janview** [comment]
You have to add ".genericModelSubstitutes( Optional.class )" to your Docket-Bean creation:
```java
public Docket sampleApi() {
  return new Docket(DocumentationType.SWAGGER_2)
    .useDefaultResponseMessages(false)
    .groupName("sample-api")
    .apiInfo(apiInfo())
    .select()
    .paths(regex("/api.*"))
    .build()
    .genericModelSubstitutes(Optional.class); // add this
}
```

**Comment by anouarchattouna** [comment]
Thank you @janview
