### ISSUE TITLE
Don't want schema for non-json response

### ISSUE THREAD

**Issue by jakubneubauer** [springfox/springfox#1849]
Hello,
I have REST method, that produces text/csv. Return type is my own class "CsvResponse", that is later converted by HttpMessageConverter to a response of text/csv content type.

The problem is that the generated swagger contains "response" with schema.

I think the response section of the swagger shouldn't contain the schema at all in case there is no "json" content type in the "produces" section.
Maybe there is a reason for it. But **how can I prevent the schema to be generated for the response**?

Springfox version: 1.5.10

my method signature:
```
@ApiOperation(value="foo")
@RequestMapping(value = "/export/csvlog", method = RequestMethod.GET, produces = "text/csv")
CsvResponse myMethod()
```

and I get this in swagger:
```
"responses": {
    "200": {
        "description": "OK",
        "schema": {
            "$ref": "#/definitions/CsvResponse"
        }
    },
    etc...
```

I would expect something like:

"responses": {
```
    "200": {
        "description": "OK"
    },
    etc...
```

**Comment by jakubneubauer** [comment]
BTW, the best I was able to achieve was to use
```
@ApiResponses({
            @ApiResponse(code = 200, message = "OK", response = String.class)
    })
```
But this is also not correct, since the meaning of the result schema is that it produces JSON string, which is not true in this case. (the result is not a json string, which would mean it is in double quotes and the  special characters would be escaped etc.)

**Comment by dilipkrish** [comment]
I think what you've run into is a limitation of 2.0 of the spec and the springfox inference. 

Ideally this should get the response to be as you'd expect
```
@ApiResponses({
            @ApiResponse(code = 200, message = "OK", response = Void.class)
    })
```
However this may also be an alternative
```
@ApiResponses({
            @ApiResponse(code = 200, message = "OK", response = MultipartFile.class)
    })
```

Another way of doing it is globally creating an alternate rule for `CsvResponse` => `MultipartFile`
