### ISSUE TITLE
RequestBody with boolean throwing error in swagger UI

### ISSUE THREAD

**Issue by VishGov** [springfox/springfox#1850]
I have a controller with a RequestBody that is returning boolean
@RequestBody final boolean isTrue

When running swagger UI, I am getting the following error in the js /:
TypeError: undefined is not an object (evaluating 'e.type.toLowerCase')

I can see that in for the request body parameter, the type in the schema is set as boolean. However in the js, I can see that an extra "type" field is present, outside the schema and is set as undefined, hence throwing this error.

I have scoured the net regarding this issue and I have already seen that it has been addressed by swagger UI team in some release. However I am using the following latest dependencies for spring fox swagger:

                 <dependency>
    			<groupId>io.springfox</groupId>
    			<artifactId>springfox-swagger2</artifactId>
    			<version>2.7.0</version>
    		</dependency>
    		<dependency>
    		    <groupId>io.springfox</groupId>
    		    <artifactId>springfox-swagger-ui</artifactId>
    		    <version>2.7.0</version>
    		</dependency>

Please let me know if this is still a bug in swagger UI and how to rectify this.

**Comment by dilipkrish** [comment]
Seems like its [this issue](https://github.com/swagger-api/swagger-ui/issues/2004) My guess is that you're browser is caching an older version of the files
