### ISSUE TITLE
Running Springfox in an isolated application context

### ISSUE THREAD

**Issue by akobyakov** [springfox/springfox#1851]
The current implementation of Springfox is rather intrusive. That means that putting it into the existing application context of some mature highly customized Spring Web application may become tricky, since the customizations the library make may clash (and they do, in our case) with the production code.
So the question is whether it's currently possible or it could be possible to integrate Springfox into the existing application in the way it exists in a completely isolated context, while still being able to introspect production contexts for building swagger specifications?

Anyway, thanks for the great job you're doing!

**Comment by dilipkrish** [comment]
Thank you!

Can you be a little specific on whats causing the `intrusion`. It should be fairly un-intrusive in 2.7.0 onwards. Also there is a way to isolate it into the [actuator context](https://github.com/springfox/springfox/issues/1184#issuecomment-189031751) thanks to @tokuhirom

**Comment by dilipkrish** [comment]
:bellhop_bell:

**Comment by akobyakov** [comment]
Hi Dilip,

Sorry for the delay.

> Can you be a little specific on whats causing the intrusion.

Consider a very minimalistic runnable *surrogate* example:

```java
@SpringBootApplication
@EnableSwagger2
public class DemoApplication extends WebMvcConfigurationSupport {
    @Bean
    public Docket docket() {
        return new Docket(DocumentationType.SWAGGER_2);
    }


    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        converters.add(new MappingJackson2HttpMessageConverter(
                new ObjectMapper()
                        .enable(SerializationFeature.WRAP_ROOT_VALUE)
                )
        );
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry
                .addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");
        registry
                .addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}
```

With such configuration, Springfox is unable to produce valid Swagger specification anymore (note the `WRAP_ROOT_VALUE` feature), since it relies on some implicit defaults it expects from the existing application. And unfortunately, that is not the problem of the application. 

So my original question was more about how hard would it be for the library to have its own isolated environment with an application context, HttpMessageConverter, ResourceHandlerRegistry, etc. (so there's no any chance for misconfiguration at all) but still be able to traverse Controllers from a "neighbour" context and build a specification for it. 
I understand the risks of getting not fully valid specification output because of differences in the object mappers's configurations, but that sounds solvable. 

Sorry, I haven't looked deeply into the actuator proposal yet. At the first glance it looks not exactly like what I mean.
