### ISSUE TITLE
Swagger not supporting @JsonProperty with a @ModelAttribute annotation 

### ISSUE THREAD

**Issue by apeckstl** [springfox/springfox#1852]
Using version: 
```xml
 <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>2.5.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger2</artifactId>
      <version>2.5.0</version>
      <scope>compile</scope>
    </dependency>
```
What kind of issue is this?

   When using the @ModelAttribute in Spring to map URL Parameters to an object,  swagger does not respect the @JsonProperty annotation and always displays camelCase.   I did find in the issues documented this - https://github.com/springfox/springfox/issues/1363  however since our API is using kabob-case (with the dashes) we can't use the mapping solution.   Is there a way to avoid the manual work of the @APIImplictParameter, and have swagger map the camelCase to kebob-case automatically? 

FYI - I know this Spring mapping to Kebob case in the URL parameters is a custom solution we built, but thought maybe somebody might have a solution for the automapping in swagger  
Example: 

**controller:** 
```java
  @ApiOperation(value = "Search Customers", notes = Constants.SEARCH_CUSTOMER_DESCRIPTION)
    public ResponseEntity<Response> search(@Kebabable @ModelAttribute CustomerSearchRequest customerSearchRequest, HttpServletRequest request, @ModelAttribute(binding = false) Pageable pageable)
```
The bean CustomerSearchRequest  has @jsonProperty annotation: 
      
**CustomerSearchRequest**
```java
	@JsonProperty(value = "page-size")
	private String pageSize;
```

**Comment by dilipkrish** [comment]
Please upgrade to 2.7.0

**Comment by apeckstl** [comment]
I updated to 2.7.0 but it still doesn't work.

**Comment by gintarasbar** [comment]
Having same issue. Doesn't work with ModelAttribute with 2.7.0

**Comment by dilipkrish** [comment]
Is this a valid scenario? Model attributes are _NOT_ json properties?

**Comment by gintarasbar** [comment]
I meant the @ModelAttribute doesn't work in general with springfox-swagger-ui 2.7.0, even if all integration tests pass and Spring Boot passes all annotations. It seems springfox doesn't support variables with dashes, like request-id for RequestHeader even if I annotate on the ModelAttribute pojo with ApiParam it is just being ignored.

**Comment by dilipkrish** [comment]
@gintarasbar very possible.

**Comment by gintarasbar** [comment]
Would it help if I would create the project that recreates the problem?
