### ISSUE TITLE
Query strings in paths are not allowed / Partial path templating is not allowed.

### ISSUE THREAD

**Issue by scottf** [springfox/springfox#1853]
- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Bug report? I'm not exactly sure how to categorize this.

<br/>
1. For this controller:

```
@RequestMapping(value = "/foo/{id}", method = RequestMethod.GET)
public ResponseEntity getFooById(
        @ApiParam(value = "Id of foo that needs to be fetched", required = true)
        @PathVariable(value = "id") String id,

        @ApiParam(value = "My Query Param is some param")
        @RequestParam(value = "myQueryParam, required = false) String myQueryParam
) {
```

The json generated contains this:

```
"paths": {
    "/foo/{id}{?myQueryParam}": {
```

Swagger Editor ( http://editor.swagger.io ) says this is an error.
> Semantic error at paths./foo/{id}{?myQueryParam}
> Query strings in paths are not allowed.

<hr size=1/>
2. This controller:

```
@RequestMapping(value = "/foo/bar", method = RequestMethod.GET)
public ResponseEntity fooBar(
            @ApiParam(value = "My Query Param is some param")
            @RequestParam(value = "myQueryParam, required = false) String myQueryParam
```
makes this path:

```
"/foo/bar{?myQueryParam}": {
```

Swagger Editor ( http://editor.swagger.io ) says this is an error.
> Semantic error at paths./foo/bar{?myQueryParam}
> Partial path templating is not allowed.
> 
> Semantic error at paths./foo/bar{?myQueryParam}
> Query strings in paths are not allowed.

**Comment by dilipkrish** [comment]
This is an [experimental feature](http://springfox.github.io/springfox/docs/current/#springfox-rfc6570-support-strong-incubating-strong) and is only guaranteed to work with [springfox-swagger-ui-rfc6570](https://github.com/springfox/springfox-swagger-ui-rfc6570).

**Comment by scottf** [comment]
I am not using the experimental ui version, I'm using the 2.7.0 version. Is there a way to turn this feature off?

**Comment by dilipkrish** [comment]
The link at the bottom of that section is broken, but it should be [under # 21 enableUrlTemplating](http://springfox.github.io/springfox/docs/current/#springfox-spring-mvc-and-spring-boot) in your docket. Keep in mind with that feature off you're going to be missing one of the two endpoints.
