### ISSUE TITLE
/v2/api-docs/ no longer works with 2.7.0 the trailing slash is no longer supported

### ISSUE THREAD

**Issue by fredboutin** [springfox/springfox#1855]
This is really easy to reproduce, just boot this demo https://github.com/springfox/springfox-demos/tree/master/spring-java-swagger and then this endpoint works : http://localhost:8080/spring-java-swagger/v2/api-docs but not this one http://localhost:8080/spring-java-swagger/v2/api-docs/

Think it has to do with the new class PropertySourcedRequestMappingHandlerMapping overriding spring's RequestMappingHandlerMapping.

**Comment by dilipkrish** [comment]
It was never advertised to work. If it did it was by chance. Have you tried overriding (to `v2/api-docs/`) it in the properties file to see if it works for you.

> Think it has to do with the new class PropertySourcedRequestMappingHandlerMapping overriding spring's RequestMappingHandlerMapping.

Yes that is true. Had to change it so that we don't assume a property source configurer.

**Comment by fredboutin** [comment]
I just thought that since spring supports by default this behaviour it would make sens to support it in this lib.
We've fixed our code to query specifically this path without the /. Think I tried to change it in the properties file but we wanted both working so it's not a good work around for us.

**Comment by dilipkrish** [comment]
Also the trailing `/` is incorrect anyways because the controller can use groups as request parameters for e.g. `/v2/api-docs?group=blah` to get the docs for a specific group `blah`
