### ISSUE TITLE
/configuration/ui 404 (not found)

### ISSUE THREAD

**Issue by englishhaze** [springfox/springfox#1856]
I'm using Springfox swagger2 and ui version 2.6.1 with Spring 4.3.8 and Spring security 3.2.10.

My API Swagger markup at endpoint /v2/api-docs appears in the browser fine. /swagger-resources endpoint shows the expected configuration locations but when I try and run the UI with /swagger-ui.html I see the documentation web page with the heading but no content and I see a 404 (not found) in the console trying to load /swagger-resources/configuration/ui

Neither /swagger-resources/configuration/ui or /swagger-resources/configuration/security can be found.

I have a very simple configuration class:

```java
@EnableSwagger2
public class SwaggerConfig {
    /**
     * @return a Swagger Docket instance that controls which APIs will be documented.
     */
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                   .select()
                   .apis(RequestHandlerSelectors.any())
                   .paths(PathSelectors.any())
                   .build()
                   .pathMapping("/api")
                   .apiInfo(apiInfo());
    }
        
    /**
     * @return an instance of ApiInfo
     */
    private ApiInfo apiInfo() {
        
        ApiInfoBuilder apiInfoBuilder = new ApiInfoBuilder();
        
        apiInfoBuilder.title(
                PropertyResolver.getProperty("api.name"));
        apiInfoBuilder.description(
                PropertyResolver.getProperty("api.description"));
        apiInfoBuilder.version(
                PropertyResolver.getProperty("api.version"));
        apiInfoBuilder.termsOfServiceUrl(
                PropertyResolver.getProperty("api.tos"));
        apiInfoBuilder.contact(
                new Contact(
                        PropertyResolver.getProperty("api.contact.name"), 
                        PropertyResolver.getProperty("api.contact.url"), 
                        PropertyResolver.getProperty("api.contact.email")));
        apiInfoBuilder.license(PropertyResolver.getProperty("api.license"));
        apiInfoBuilder.licenseUrl(PropertyResolver.getProperty("api.license.url"));
        
        return apiInfoBuilder.build();
    }
}
```
I cannot work out why I get the 404 for the /swagger-resources/configuration/ui request. 

Any assistance greatly received.

Thanks.

Paul

**Comment by dilipkrish** [comment]
It appears like you have something preventing those endpoints from being exposed. Is there any reason you're using such an old version of spring security?

**Comment by englishhaze** [comment]
You are correct. My servlet mapping URL patterns were not allowing the requests through. I've updated to the latest Spring security now as well and all is working.

Sorry to trouble you.

**Comment by chamarts** [comment]
I ran into similar issue. I wasn't sure how these endpoints are served. I am trying to use the springfox-swagger-ui for just the UI to load the hand coded swagger.json file. I find it hard to get this working. looks like I am missing something very basic. Could you pls. help me how swagger-resources/configuration/ui is served ?

**Comment by nutmix** [comment]
Is there any solution for this issue? I am stumped.
