### ISSUE TITLE
java.util.Optional value not recognized

### ISSUE THREAD

**Issue by timhovius** [springfox/springfox#1858]
java.util.Optional and related values (for example OptionalDouble) are not recognized yet. I have created an example below. Normal (Double) object are recognized (like `var4` in the example). 

I'm using version 2.7.0 with Spring Boot 1.4.2

```
public void test(
            @PathVariable String var1,
            @RequestParam(required = false) OptionalDouble var2,
            @RequestParam(required = false) Optional<Double> var3,
            @RequestParam(required = false) Double var4) {
    }
```
This will result in:
![image](https://user-images.githubusercontent.com/7972792/26872518-1812235c-4b77-11e7-9eb8-f84a146da1ca.png)

**Comment by janview** [comment]
See #1848

**Comment by timhovius** [comment]
Okay thanks!
