### ISSUE TITLE
[Spring boot] @EnableAspectJAutoProxy cause endpoint scanning failed

### ISSUE THREAD

**Issue by jdupont22** [springfox/springfox#1860]
Just add a java configuration with @EnableAspectJAutoProxy and the swagger ui doesn't display the endpoint anymore.

Spring boot 1.4.5 / Springfox 2.6.1
Spring boot 1.5.4 / Springfox 2.7.0

**Comment by dilipkrish** [comment]
This may be related to #1876. Could you provide more details (stacktrace/errors). Closing this as duplicate in the mean while. Feel free to re-open
