### ISSUE TITLE
Springfox 2.7.0 setting incorrect base path, it appends the servlet mapping to the context root

### ISSUE THREAD

**Issue by codependent** [springfox/springfox#1861]
I recently upgraded from Springfox 2.2.0 to Springfox 2.7.0 and have experienced an unexpected change.

My API is served using a servlet mapping `/api`. and Springfox showed a base path that it got correctly from the context root. Thus, the generated swagger info indicated in 2.2.0 `/myPath` and a collection of endpoints starting with `/api/v1/xxx`.

However after upgrading the new basePath is `/myPath/api` instead of just `/myPath`. 

This is caused by a change in Springfox 2.7.0 where Swagger2Controller updates the basePath:

```java
  public ResponseEntity<Json> getDocumentation(
      @RequestParam(value = "group", required = false) String swaggerGroup,
      HttpServletRequest servletRequest) {
    Swagger swagger = mapper.mapDocumentation(documentation);
    UriComponents uriComponents = componentsFrom(servletRequest, swagger.getBasePath());
    swagger.basePath(Strings.isNullOrEmpty(uriComponents.getPath()) ? "/" : uriComponents.getPath());
```

After getting `Swagger swagger` from the mapper I see that the basePath is `/myPath`, but, `componentsFrom()` changes it to `/myPath/api`.

What's the logic behind this change? How could I get the correct (expected) basePath that corresponds the context root?

My SwaggerConfig.java:

```java
@Configuration
@EnableSwagger2
public class SwaggerConfig {

	private static final String SLASH_API = "/api";
    private static final String API_KEY_NAME = "api_key";
            
    @Value("${api.key:dummyAPIKey}")
    private String apiKey;

    /*-----------------------------------------------------------------------*/
    /*                                 V1                                    */
    /*-----------------------------------------------------------------------*/
    
    /**
     * bean de configuración principal de Swagger
     * @return objeto docket
     */
    @Bean
    public Docket fooV1Api() {
        return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(PathSelectors.regex("/v1/.*"))                
            .build()
            .apiInfo(new ApiInfo("Foo Rest API","Foo REST API","v1","","","",""))
            .pathMapping(SLASH_API)
            .securitySchemes(newArrayList(apiKey()))
            .securityContexts(newArrayList(securityContext()))
            .useDefaultResponseMessages(false)
        	.groupName("authV1");
    }
    
    @Bean
    protected SecurityConfiguration securityConfiguration() {
    	return new SecurityConfiguration(
    			"test-client-id", 
    			"test-client-secret", 
    			"test-client-realm", 
    			"test-app", 
    			apiKey, 
    			ApiKeyVehicle.HEADER, 
    			API_KEY_NAME, 
    			",");
    }
    
    /**
     * Seguridad acceso al API
     * @return
     */
    private ApiKey apiKey() {
        return new ApiKey(apiKey, API_KEY_NAME, "header");
    }
    
    /**
     * Establece contexto de seguridad para el API a través de Swagger
     * @return security contextO
     */
    private SecurityContext securityContext() {
        return SecurityContext.builder()
                .securityReferences(defaultAuth())
                .forPaths(PathSelectors.regex("/api/v1/.*"))
                .build();
    }
    
    /**
     * Definición contextos de seguridad para el API
     * @return
     */
    private List<SecurityReference> defaultAuth() {
        AuthorizationScope authorizationScope=new AuthorizationScope("global", "accessEverything");
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0]=authorizationScope;
        return newArrayList(new SecurityReference(apiKey, authorizationScopes));
    }
    
}
```

**Comment by dilipkrish** [comment]
I think there is some confusion cos your servlet mapping is `/api` and also your request mapping start with `/api`. Most likely this is the right behavior unless you tell me otherwise.

**Comment by codependent** [comment]
Hi dilipkrish, I don't understand why I am seeing now `/myPath/api` instead of just `/myPath` as a basepath. According to Springfox' documentation:

.pathMapping("/") -> Adds a servlet path mapping, when the servlet has a path mapping. this prefixes paths with the provided path mapping.

So in my case I think I did it correctly setting .pathMapping("/api"), didn't I?

Previously to 2.7.0, with this configuration I got a basePath of `/myPath' and bunch of endpoints such as `/api/v1/xxx` After the update I have `/myPath/api' and '/api/v1/xxx' URLs which doesn't make sense.

**Comment by dilipkrish** [comment]
It may be a regression, Would you mind creating a test for [HostNameProvider.java](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/HostNameProvider.java) that shows your issue when you excercise it [like so](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L93-L97).

**Comment by codependent** [comment]
I'l try to create the test in the following days. In the meantime I've uploaded a sample project where you can see the wrong base path:

https://github.com/codependent/springfox-sample

Just access: http://localhost:8080/myApp/api/swagger-ui.html and you'll see it.

Regards

**Comment by dilipkrish** [comment]
Its because you have [configured it to add a path mapping](https://github.com/codependent/springfox-sample/blob/master/src/main/java/com/codependent/springfox/SwaggerConfig.java#L49) and you've [also set the context-path](https://github.com/codependent/springfox-sample/blob/master/src/main/resources/application.yml#L2-L3). The `pathMapping` is only for when you have dynamic servlet registrations.

**Comment by codependent** [comment]
But isn't the doc kind of misleading? .pathMapping() -> Adds a servlet path mapping, when the servlet has a path mapping. **this prefixes paths with the provided path mapping.** That is to say, it prefixes paths with the servlet mapping. However the servlet mapping is now being automatically included in the basePath.

To me 2.2.0 followed that doc and 2.7.0 doesn't.

**Comment by dilipkrish** [comment]
@codependent the documentation is predominantly with vanilla spring-mvc in mind. With spring boot since the container is embedded it accounts for the servlet-path as well. 

When its deployed as a war the spring run-time doesnt have any idea what the servlet-path-mapping is. Hopefully that makes sense.

**Comment by dilipkrish** [comment]
Would you awesome if you improve the docs as you see appropriate.

**Comment by codependent** [comment]
Hi @dilipkrish

So you mean that pathMapping() is only necessary to indicate the servlet mapping in plain Spring MVC (no Spring Boot) applications, right?

I'm sorry but I think I'm still missing something: I just tested a Spring MVC application deployed as WAR and the base path is still automatically set up as /<contextRoot>/<servletMapping> although I have pathMapping("/") in the Swagger cfg and the web.xml servlet-mapping url is /api/*. It doesn't add up, well, that or I still don't graps the reason for the change.

By the way, I'd like to thank you for taking the time to clear this up.

**Comment by dilipkrish** [comment]
@codependent thats good feedback, its worth revisiting for sure. Its bean a while so my memory is also kind of sketchy, but IIRC, it was to allow for [dynamic servlet registration](http://javaevangelist.blogspot.com/2012/11/dynamic-servlet-registration-example.html), where the servlet mapping cannot be inferred.

**Comment by north911** [comment]
@codependent Hi, i have very close issue, did you fix it? because i can't understand how
