### ISSUE TITLE
strange endpoint url generated in swagger-ui 2.7.0

### ISSUE THREAD

**Issue by chengyukpong** [springfox/springfox#1863]
This issue is related to springfox-swagger-ui:​2.7.0 only.

in springfox-swagger-ui:​2.6.1
a typical endpoint will be #!/my-endpoint-controller/xxxUsingGET
It converts MyEndpointController to my-endpoint-controller

but in  springfox-swagger-ui:​2.7.0
the url becomes #!/my45endpoint45controller/xxxUsingGET

I believe it is related to url-encoding as '-' is supposed to be encoded to '%45'.

**Comment by dilipkrish** [comment]
Thats how swagger-ui generates the new endpoints unfortunately

**Comment by alex-konkov** [comment]
Any chance to apply a workaround? This broke our existing shared links too.
