### ISSUE TITLE
@NotNull not working to mark field as required

### ISSUE THREAD

**Issue by sddakoty** [springfox/springfox#1864]
@NotNull on a field does not mark it as required.

maven:
```
       <swagger.version>2.7.0</swagger.version>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>${swagger.version}</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>${swagger.version}</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-bean-validators</artifactId>
            <version>${swagger.version}</version>
        </dependency>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.3.RELEASE</version>
        <relativePath/>
    </parent>
```

java:
```
public class MyReq {
	@NotEmpty
	@NotBlank
	@NotNull
	private String somename; //getter, setter
}

@RestController
public class MyServlet {
    @GetMapping("/test")
    public void test(@Valid MyReq req) {

   }
}

@SpringBootApplication
@EnableSwagger2
@Import(BeanValidatorPluginsConfiguration.class)
public class StartApp extends SpringBootServletInitializer {
}

```

Result json:
```
{
            "name": "somename",
            "in": "query",
            "required": false,
            "type": "string"
          }
```

What is strange:
I debugged, and I can see the ```NotNullAnnotationPlugin``` setting the ```required(true)``` as is finds the @NotNull annotation on the field. But the json response always returns false, so there must be some code that later overrides this propery?

**Comment by dilipkrish** [comment]
Are you using `MyReq` in a response perhaps? Why don't you create a PR with a breaking test?

**Comment by igorko** [comment]
I guess this caused regression. Just writing here, because you are aware of changes.
When I put auto-generated swagger into online swagger editor I get next error

> Schema error at definitions['MyClass'].properties['id']
> should NOT have additional properties
> additionalProperty: allowEmptyValue
> Jump to line 1523

and

> Schema error at definitions['MyClass'].properties['description']
> should NOT have additional properties
> additionalProperty: allowEmptyValue
> Jump to line 1523

And class definition is next
`public final class MyClass {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(readOnly = true)
    @Setter
    @Getter
    private String id;

    @NotNull
    @ApiModelProperty(required = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Setter
    @Getter
    private String description;
}`

Definition in swagger is next

`  MyClass:
    type: object
    required:
      - description
    properties:
      description:
        type: string
        allowEmptyValue: false
      id:
        type: string
        readOnly: true
        allowEmptyValue: false
    title: Source`

As I understand allowEmptyValue is not valid property for scheme propery. Btw I am using MyClass as @RequestBody.
Is it possible to avoid adding allowEmptyValue to property definition? In my case I have @NotNull and required = true, but none of them says value cannot be empty. I am using swagger-ui 2.8.0
