### ISSUE TITLE
2.7.0 does not list PATCH methods from Spring Data Rest

### ISSUE THREAD

**Issue by jadhavsuhas** [springfox/springfox#1866]
After updating from 2.6.2-SNAPSHOT to 2.7.0, SpringDataRest patch requests are not listed.
Thought I can see that they are exposed by SDR
[/api/{repository}/{id}],methods=[PATCH]
Surprisingly,PATCH methods for associations are listed by Springfox
[/api/{repository}/{id}/{property}],methods=[PATCH || PUT || POST]

Please let me know if something can be done for this?

**Comment by jadhavsuhas** [comment]
Hi,
https://github.com/springfox/springfox/blob/master/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/EntitySaveExtractor.java


PATCH is missing, any idea how we can add it?
@dilipkrish , thanks  in advance

**Comment by drenda** [comment]
+1

**Comment by jadhavsuhas** [comment]
package springfox.documentation.spring.data.rest;

import com.fasterxml.classmate.TypeResolver;
import org.springframework.data.mapping.PersistentEntity;
import org.springframework.data.repository.core.CrudMethods;
import org.springframework.data.repository.core.RepositoryMetadata;
import org.springframework.hateoas.Resource;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.method.HandlerMethod;
import springfox.documentation.RequestHandler;
import springfox.documentation.service.ResolvedMethodParameter;

import java.util.HashSet;
import java.util.List;

import static com.google.common.collect.Lists.*;
import static com.google.common.collect.Sets.*;
import static springfox.documentation.spring.data.rest.RequestExtractionUtils.*;

class EntitySaveExtractor implements EntityOperationsExtractor {
 @Override
 public List<RequestHandler> extract(EntityContext context) {
   final List<RequestHandler> handlers = newArrayList();
   final PersistentEntity<?, ?> entity = context.entity();
   CrudMethods crudMethods = context.crudMethods();
   if (crudMethods.hasSaveMethod()) {
     HandlerMethod handler = new HandlerMethod(
         context.getRepositoryInstance(),
         crudMethods.getSaveMethod());
     RepositoryMetadata resource = context.getRepositoryMetadata();
     ActionSpecification put = saveActionSpecification(
         entity,
         RequestMethod.PUT,
         String.format("%s%s/{id}",
             context.basePath(),
             context.resourcePath()),
         handler,
         context.getTypeResolver(),
         resource);
     handlers.add(new SpringDataRestRequestHandler(context, put));
     ActionSpecification post = saveActionSpecification(
         entity,
         RequestMethod.POST,
         String.format("%s%s", context.basePath(), context.resourcePath()),
         handler,
         context.getTypeResolver(), resource);
     handlers.add(new SpringDataRestRequestHandler(context, post));
     ActionSpecification patch = saveActionSpecification(
         entity,
         RequestMethod.PATCH,
         String.format("%s%s{id}", context.basePath(), context.resourcePath()),
         handler,
         context.getTypeResolver(), resource);
     handlers.add(new SpringDataRestRequestHandler(context, patch));
   }
   return handlers;
 }

 private ActionSpecification saveActionSpecification(
     PersistentEntity<?, ?> entity,
     RequestMethod method,
     String path,
     HandlerMethod handler,
     TypeResolver typeResolver,
     RepositoryMetadata repository) {
	 
	 if(method.equals(RequestMethod.POST)){
		   return new ActionSpecification(
			       actionName(entity, handler.getMethod()),
			       path,
			       newHashSet(method),
			       new HashSet<MediaType>(),
			       new HashSet<MediaType>(),
			       handler,
			       newArrayList(
			           new ResolvedMethodParameter(
			               0,
			               "body",
			               bodyAnnotations(handler),
			               typeResolver.resolve(repository.getDomainType()))),
			       typeResolver.resolve(Resource.class, repository.getReturnedDomainClass(handler.getMethod())));
	 } else{
		   return new ActionSpecification(
			       actionName(entity, handler.getMethod()),
			       path,
			       newHashSet(method),
			       new HashSet<MediaType>(),
			       new HashSet<MediaType>(),
			       handler,
			       newArrayList(
			           new ResolvedMethodParameter(
			               0,
			               "id",
			               pathAnnotations("id", handler),
			               typeResolver.resolve(repository.getIdType())),
			           new ResolvedMethodParameter(
			               0,
			               "body",
			               bodyAnnotations(handler),
			               typeResolver.resolve(repository.getDomainType()))),
			       typeResolver.resolve(Resource.class, repository.getReturnedDomainClass(handler.getMethod()))); 
	 }


 }
}
//correct file

**Comment by dilipkrish** [comment]
@jadhavsuhas could you please submit a PR to fix?

**Comment by dilipkrish** [comment]
Fixed via commit ☝️
