### ISSUE TITLE
Multiple APIs within one Spring MVC app?

### ISSUE THREAD

**Issue by kilsbo** [springfox/springfox#1867]
We've recently built a Spring MVC based REST API application using SpringFox. We are going to have it versioned for continous development.

I'm wondering if SpringFox in its current state supports multiple APIs within one app? Configurable, like two endpoints with their own Swagger files, for instance:
`/api/v1/api-docs`
`/api/v2/api-docs`

And then the operations:
`/api/v1/security/authenticate`
`/api/v1/customer/{id}`
`/api/v2/security/authenticate`
`/api/v2/customer/{id}`

The possible solutions I can think of, of the top of my head are:
1. One Spring MVC app per version.
2. Using version paths within controller RequestMapping annotations.
3. Using multiple servlets in web.xml, in combination with component scanning divided into packages in its configuration.

Second option will have both versions within one swagger file, which we do not want. First option is the quick and dirty one. Third option is a theory, haven't tested but should be possible.

Are there any SpringFox possibilities here I've missed?

Thank you.

**Comment by dilipkrish** [comment]
You've missed the ability to partition the api documents. You can create multiple dockets with different selection criteria
