### ISSUE TITLE
Custom Schemas for Models

### ISSUE THREAD

**Issue by anthonyroach** [springfox/springfox#187]
In my project I'm using JSON-schema to specify my REST resources model, and then I'm generating POJOs from the JSON-schema. the POJOs are then used in my SpringMVC requests, and swagger-springmvc then uses those POJOs to generate JSON-schema models in the swagger docs. This basically works, but the resultant models in the swagger docs are missing some of the things that were in my original JSON-schema:

1) "title" and "description" fields that provide nice documentation for the models and model fields
2) validation fields that, although not used by swagger, would be nice to include in the JSON for anyone who looks at the raw json
3) "required" property arrays

It would be nice if swagger-springmvc had an optional way to provide a custom schema for POJOs so I could make the the swagger json use my original JSON-schemas directly. An alternative would be to provide annotations that I could put on my POJOs to include the information from #1, #2 and #3 on the POJOs and have swagger-springmvc replicate that information in the model schemas it generates.

**Comment by parinss** [comment]
![image](https://cloud.githubusercontent.com/assets/5884176/9157206/64b705ce-3ea9-11e5-889c-8b7628a8b4e3.png)
I would like to remove the Response Model from my UI. How can I do that? I am using Springmvc/Swagger
@dilipkrish

**Comment by dilipkrish** [comment]
Unfortunately if you need that you'll have to use a custom swagger-ui based on your modifications.

**Comment by dilipkrish** [comment]
@parinss Also please open a new issue and not pile on to old unrelated and closed issues!
