### ISSUE TITLE
The lasted version supported for swagger3.x?

### ISSUE THREAD

**Issue by maliqiang** [springfox/springfox#1870]
The swagger has upgraded to 3.x. Is it spring-fox2 supported the swagger3.x?Or when can support it ?

**Comment by dilipkrish** [comment]
You mean swagger-ui? It is slated for support in the next version. But you can use the webinar supplied by the swagger-ui project as well.

**Comment by Eloo** [comment]
is there currently progress for this topic?

**Comment by dilipkrish** [comment]
No but we could use some help porting the existing swagger-ui to 3.x

**Comment by litttlefisher** [comment]
Please give some hints for how to use swagger-ui 3.*. I don't know what the webinar is.

**Comment by dilipkrish** [comment]
Chalk omen up for autocorrect. 😂 I meant [swagger 3.x webjar](https://mvnrepository.com/artifact/org.webjars/swagger-ui).

**Comment by litttlefisher** [comment]
@dilipkrish Oh,my god! I don't know how to use this webjar. In [SwaggerUI](https://github.com/swagger-api/swagger-ui), I can use only the catalog of dist to build a SwaggerUI, but I don't know how to generate a json or yaml of my project. Maybe I need to wait springfox to supply SwaggerUI 3.*.

**Comment by dilipkrish** [comment]
It should be pretty simple. Just a google away 😉 It might Ben a while before 3.x lands in springfox

**Comment by Poeschl** [comment]
@litttlefisher Just include a html page like the following in your spring application and create a controller for it. And of course include the webjar as a dependency.

``` html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org">
<head>
  <meta charset="UTF-8">
  <title>Rest Doc</title>
  <link rel="stylesheet" type="text/css" href="https://raw.githubusercontent.com/swagger-api/swagger-ui/master/dist/swagger-ui.css"
        th:href="@{/webjars/swagger-ui/3.0.17/swagger-ui.css}">
</head>
<body>

<div id="swagger-ui"></div>

<script src="https://raw.githubusercontent.com/swagger-api/swagger-ui/master/dist/swagger-ui-bundle.js"
        th:src="@{/webjars/swagger-ui/3.0.17/swagger-ui-bundle.js}">
</script>
<script src="https://raw.githubusercontent.com/swagger-api/swagger-ui/master/dist/swagger-ui-standalone-preset.js"
        th:src="@{/webjars/swagger-ui/3.0.17/swagger-ui-standalone-preset.js}"></script>
<script>
  window.onload = function () {

    // Build a system
    window.ui = SwaggerUIBundle({
      url: "/v2/api-docs",
      dom_id: '#swagger-ui',
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      plugins: [
        SwaggerUIBundle.plugins.DownloadUrl
      ],
      layout: "StandaloneLayout"
    })
  }
</script>
</body>
</html>
```

**Comment by dilipkrish** [comment]
Thanks @Poeschl!

**Comment by shockey** [comment]
Jumping in from the Swagger-UI side - looks like this is well on its way, but feel free to ping me if you're working on integrating 3.x and get stuck on something related to the UI itself.

**Comment by dilipkrish** [comment]
@shockey would really appreciate if you could get 3.x of swagger-ui working. Haven't had time to look at that recently

**Comment by nobe0716** [comment]
Thanks for @Poeschl 

I have finally got a 3.1.2 versioned view, so I am willing to share additional configuration with above html

* pom.xml > dependencies
  ```xml
  <dependency>
    <groupId>org.webjars</groupId>
    <artifactId>swagger-ui</artifactId>
    <version>3.1.2</version>
  </dependency>
  ```
* SwaggerController
  ```java
  @Controller
  public class SwaggerIndexController {
    @RequestMapping("/")
    public String greeting() {
      return "index";
    }
  }
  ```
* and locate index.html at resources/templates/index.html (change version to latest one, 3.1.2)

**Comment by dilipkrish** [comment]
@nobe0716 Hey would love for your contributions to upgrade 3.1.2

**Comment by dilipkrish** [comment]
Implemented via #2153

**Comment by user20161119** [comment]
> Thanks to @Poeschl
> 
> I have finally got a 3.1.2 versioned view, so I am willing to share additional configuration with above html
> 
> * pom.xml > dependencies
>   ```
>   <dependency>
>     <groupId>org.webjars</groupId>
>     <artifactId>swagger-ui</artifactId>
>     <version>3.1.2</version>
>   </dependency>
>   ```
> * SwaggerController
>   ```java
>   @Controller
>   public class SwaggerIndexController {
>     @RequestMapping("/")
>     public String greeting() {
>       return "index";
>     }
>   }
>   ```
> * and locate index.html at resources/templates/index.html (change version to latest one, 3.1.2)

hi how config in spring mvc project without thymeleaf template?
we use this link access api document http://dev.api.yqfoodec.com/swagger-ui.html

**Comment by ravikancherla** [comment]
>  Upgrading Swagger UI to 3.7.0

I see that swagger ui is upgraded to 3.x but the release version is still 2.9.2 ? I am confused.

**Comment by chandrakanthm** [comment]
> > Upgrading Swagger UI to 3.7.0
> 
> I see that swagger ui is upgraded to 3.x but the release version is still 2.9.2 ? I am confused. Is webjars still the solution to use swagger api 3.x as well as for UI ?

io.springfox:springfox-swagger-ui:2.8.0  supports OpenAPI spec 3.0 with new swagger-ui
<img width="1672" alt="swagger-ui" src="https://user-images.githubusercontent.com/10018764/57554567-a4a8fb00-7326-11e9-9cd4-67a7740a6747.png">

**Comment by vijrahul** [comment]
Hi, are there any steps to integrate the swagger 3 ui into springboot?

**Comment by mskurup** [comment]
I have also need to update swagger 3.24 in Spring boot REST api application. Currently, I am using 2.9.2. Could you please someone help me on some concrete steps? Do I need to index and controller class in spring boot appalication.

**Comment by mskurup** [comment]
> Jumping in from the Swagger-UI side - looks like this is well on its way, but feel free to ping me if you're working on integrating 3.x and get stuck on something related to the UI itself.

I need your help for integrating 3.x

**Comment by mskurup** [comment]
> > Thanks to @Poeschl
> > I have finally got a 3.1.2 versioned view, so I am willing to share additional configuration with above html
> > 
> > * pom.xml > dependencies
> >   ```
> >   <dependency>
> >     <groupId>org.webjars</groupId>
> >     <artifactId>swagger-ui</artifactId>
> >     <version>3.1.2</version>
> >   </dependency>
> >   ```
> > * SwaggerController
> >   ```java
> >   @Controller
> >   public class SwaggerIndexController {
> >     @RequestMapping("/")
> >     public String greeting() {
> >       return "index";
> >     }
> >   }
> >   ```
> > * and locate index.html at resources/templates/index.html (change version to latest one, 3.1.2)
> 
> hi how config in spring mvc project without thymeleaf template?
> we use this link access api document http://dev.api.yqfoodec.com/swagger-ui.html

getting below issue
Could not resolve view with name 'index.html' in servlet with name 'dispatcherServlet'
