### ISSUE TITLE
Regex pattern in URI not recognized

### ISSUE THREAD

**Issue by pemmasanikrishna** [springfox/springfox#1872]
When regex is used in the request mapping like `@RequestMapping("/{(?i)greet}/{name}")` to make uri case insensitive, then the request uri is getting generated as `http://localhost:8989/{(?i)greet}/user`.
Which should actually be `http://localhost:8989/greet/user`

**Comment by dilipkrish** [comment]
Complex regular expressions are not really supported unfortunately. Writing a regex to parse that introduces complexity thats not worth bringing in to the library.
