### ISSUE TITLE
Tags should be orderable

### ISSUE THREAD

**Issue by rainoko** [springfox/springfox#1875]
version 2.7.0

Tags are not orderable.
Even though tags are held in Treeset and should be ordered by name Documentation builder takes this treeset and converts to HashSet. This means that no real benefit about using treeset at all.

DocumentationBuilder.java:43
private Set<Tag> tags = newHashSet();

It seems to be bug. Because Tags.java method toTag uses TreeSet with name comparator. So it seems that until the builder tags are ordered alphabetically.

Even better when int order can be specified for tag and namecomparator first order by that integer and after that by name.

**Comment by dilipkrish** [comment]
While its not technically a bug, I agree it is an oversight. Would really appreciate a PR.
