### ISSUE TITLE
Dynamic @ApiParam(allowableValues)

### ISSUE THREAD

**Issue by ROMzombie** [springfox/springfox#1877]
We have a need to specify a set of allowableValues at runtime for our documentation rather than through a static list.  Is there a best-practice way to include these values?  

We were considering adding additional functionality wherein the ModelMapper would invoke a method on a Service to generate the result, then process that result as normal.   We're willing to do the work on a pull request to make this happen, if it would be accepted.

Currently:
`@ApiParam(allowableValues = "valueOne, valueTwo")`
`private String field;`

Possibly: 
`@ApiParam(allowableValues = ServiceName.MethodName)`
`private String field`

**Comment by dilipkrish** [comment]
You can create your own plugin to do it. I don't think this belongs in the base library. 

Anyhow, I don't think the right place to inject this behavior is in the mapper. The mapper is a dumb mapping between internal models and the the target specification `swagger 1.2` or `swagger 2.0`.

My recommendation is to have your own annotation 

`@DynamicAllowableValues(beanName = "myValuesSupplier")`
`private String field`

and your plugin (I know it is an anti pattern to reach in to the bean factory, but this is just one approach), would look for the bean that implements an internal interface `AllowableValueSupplier#get()`

**Comment by rehevkor5** [comment]
@dilipkrish The documentation appears to be gathered once and cached via DocumentationPluginsBootstrapper, and there is no mechanism to refresh it.

Do you think it'd work to extend `AllowableListValues` with an implementation that retrieves the dynamic values when `getValues()` is called?

**Comment by kroka** [comment]
> Do you think it'd work to extend `AllowableListValues` with an implementation that retrieves the dynamic values when `getValues()` is called?
> 
> Edit: Yes, it worked!

@rehevkor5 could you please give me a hint on how you've extended `AllowableListValues` without having to create this class in the package _springfox.documentation.service_? Or have you written a Springfox plugin for that purpose?

**Comment by rehevkor5** [comment]
@kroka It is a public class with public methods, so it does not need to be in any particular package. Yes, we have one class that implements `ParameterBuilderPlugin` and one that implements `ExpandedParameterBuilderPlugin`. We started with one, but had to add the second later to cover some gaps. I created some gists for you:
https://gist.github.com/rehevkor5/6374faa255a56174ec9307df5049f9a1
https://gist.github.com/rehevkor5/e77d1e5f2f17ac784e3da3be56e9c7ca

**Comment by kroka** [comment]
Thanks @rehevkor5, just today I've implemented a pretty similar approach with a class implementing `ParameterBuilderPlugin` (instead of creating a sub class or overriding the library's `AllowableListValues` as I've understood your first post).
