### ISSUE TITLE
Model for Map<String, List<Something>>

### ISSUE THREAD

**Issue by smwurster** [springfox/springfox#1881]
I've got an endpoint that returns a `Map<String, List<Something>>`.  This comes out as an empty (`{}`) model in the Swagger UI.  The `Something` class is annotated correctly, and I can see its reference definition in the resulting JSON, however nothing is referencing that definition.

Is there a way I can get this response type to come out correctly in the JSON / UI?  I've tried a couple Alternate Type Rules but nothing seemed to work.

Thanks.

**Comment by dilipkrish** [comment]
What does the api-docs look like?

**Comment by smwurster** [comment]
The api-docs does indeed show the reference to the definition in the endpoint's schema:

`"schema":{"type":"object","additionalProperties":{"type":"array","items":{"$ref":"#/definitions/Something"}}}`

However the UI shows it as `inline_model_9 {}`

The definition for `Something` in the api-docs looks to be a typical definition.

**Comment by dilipkrish** [comment]
The generated spec seems correct. The swagger-ui is probably to blame.

**Comment by smwurster** [comment]
I think you're right.  The current online Swagger editor seems to show everything correctly, so it must just be an issue with the version currently being packaged.  That's fine for now.

**Comment by gihad** [comment]
I hit the exact same issue today - When I paste the api-docs in http://editor.swagger.io/ everything looks good. Is there a way to fix this for the embedded api-docs ui?

**Comment by dilipkrish** [comment]
We could use some help upgrading to 3.0 for sure 🤔

**Comment by europa1613** [comment]
@smwurster For me the spec for `Map<String, List<Something>> data;` is generated incorrectly by springfox like below.

              `"data": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/List"
                    }
                }`
Versus the correct translation:
             `"data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/Something"
                        }
                    }
                }`

I'm using springfox-swagger2 annd springfox-swagger-ui versions 2.4.0. 

Any help/pointer is much appreciated.
Thanks!

**Comment by dilipkrish** [comment]
@europa1613 That is working as expected in 2.8.0. Please see test above ☝️

**Comment by europa1613** [comment]
I opened #2274. Yes its working in 2.8.0. Thanks @dilipkrish

**Comment by vpm911** [comment]
Is this bug fixed? I have a private Map<String, Map<String, List<Thumbnail>>> thumbnails;
which is causing the following json to be generated

"MapOfstringAndListOfThumbnail": { "type": "object", "title": "MapOfstringAndListOfThumbnail", "additionalProperties": { "$ref": "#/definitions/List" } }
and the $ref: "#definitions/List" is not present in the documentation. This is causing Semantic error at definitions.MapOfstringAndListOfThumbnail.additionalProperties.$ref
$refs must reference a valid location in the document

**Comment by dilipkrish** [comment]
@vpm911 As far [as I can tell yes](https://github.com/springfox/springfox/blob/f0d8b5aa54075b914d13d526c0e92ba538299ce3/swagger-contract-tests/src/test/resources/contract/swagger2/declaration-bugs-service.json#L2078-L2100)

**Comment by vpm911** [comment]
@dilipkrish Can you please check [https://github.com/springfox/springfox/issues/3356](url)? I have mentioned the details there. Thanks in advance!
