### ISSUE TITLE
Spring's 'ResponseEntity' class is being added to every custom response code

### ISSUE THREAD

**Issue by jcslater09** [springfox/springfox#1884]
- springfox version 2.7.0

What kind of issue is this?
- Question:

Hi, first off I love this project, so thank you!

I am trying to write a spring API that uses POST and PUT requests that return an empty body (i.e. JUST a status code), and I'm having a hard time getting swagger to indicate that.

What that translates to in spring is that all of my api return types use the generic ResponseEntity class (without a templated object type)   eg)
`ResponseEntity postProfile ( .... )`

I have tried numerous ways to get swagger to indicate a simple status code, but am finding it difficult.  Here is what I've tried so far:

1) Using `@ResponseStatus(HttpStatus.XXX)`
This makes the "Response Class" section of the UI look right, but it adds the model of the ResponseEntity like so:
<img width="404" alt="screen shot 2017-06-24 at 2 40 41 pm" src="https://user-images.githubusercontent.com/18624990/27511491-2652427c-58eb-11e7-9247-07a3aa02b298.png">

2) Adding the `directModelSubstitute` method to transform `ResponseEntity` into `String`
This eliminates the ResponseEntity model, but it also removes the status code message that I added in the `@ApiResponses` section:
<img width="348" alt="screen shot 2017-06-24 at 2 43 52 pm" src="https://user-images.githubusercontent.com/18624990/27511509-ae61af90-58eb-11e7-82d7-d4bdfb4d57a0.png">

3) Substituting for other object types - Integer, Long, HttpStatus, all of these also failed to preserve the status code message like the first example.

What I'd like is for it to simply say 
"Response Class (Status 201)
Profile Written"

and then start the Parameters section.

Is there a way to do this?

Thanks!

**Comment by jcslater09** [comment]
After some more tinkering I found the magic sauce for this.

The answer is to do `directModelSubstitute(ResponseEntity.class, java.lang.Void.class)`.  This ends up with exactly what I was trying to achieve

**Comment by vipingupta5352** [comment]
Found the workaround,
As the default behavior of @ApiOperation is to return the return type of method, so for every status, the return type of method will be returned.
If you want to send empty response then write
 `@ApiResponse(code = 204, message = "No User found for that Id",response = Object.class)`

And in the SwaggerConfig write 

 ```
@Bean
    public Docket productApi() {
        return new Docket(DocumentationType.SWAGGER_2)
        		.useDefaultResponseMessages(false)
        		.directModelSubstitute(Object.class, java.lang.Void.class);          
    }
```

So whenever an Object.class  is returned swagger will automatically convert it into Void.class
