### ISSUE TITLE
the @Api annotation dons't work corrected.

### ISSUE THREAD

**Issue by shuzhongling** [springfox/springfox#1885]
i use @Api annotation on a controller class,  the code is below:
```java
@Api(value = "rest")
@RestController
public class MqttRestController {
```
but when i open the swagger-ui.html, the value is not display on the tags position. it turn out as below. 
```
rest service
mqtt rest service of iot platform
Created by szl
Contact the developer
mqtt-rest-controller : Mqtt Rest Controller Show/Hide List Operations Expand Operations
```
the value “rest” in @Api annotation dons't take effect.

V2.7, the latiest version
```xml
      <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.7.0</version>
        </dependency>
```

- [V] V? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [V] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by dilipkrish** [comment]
Change the annotation to `@Api(value = "rest", tags= {"rest"})`
