### ISSUE TITLE
Response with Enum type

### ISSUE THREAD

**Issue by Hronom** [springfox/springfox#1886]
I use springfox `2.7.0` and I have next problem.
Here is my crontroller:
```
@RestController
public class TestController {
    private static final Logger logger = LogManager.getLogger();

    @RequestMapping(value = "/test", method = {RequestMethod.GET}, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    @ResponseBody
    public TestEnum getTest() {
        return TestEnum.x;
    }
}
```

Here is my enum:
```
public enum TestEnum {
    x,
    y,
    z
}
```

Here is what I got in swagger:
![screenshot_swagger](https://user-images.githubusercontent.com/429993/27518955-a21ab6e2-59f3-11e7-871e-275a58afd7c3.png)

Why I don't have model in response with the listed possible values?

**Comment by dilipkrish** [comment]
That is how swagger-ui displays enums unfortunately
