### ISSUE TITLE
@ApiResponses tag does not override default responses

### ISSUE THREAD

**Issue by muff1nman** [springfox/springfox#1887]
Reading https://github.com/springfox/springfox/issues/632 seems to imply that the `@ApiResponses` annotation, if present should override the default response messages . However it looks like that is not the behavior and reading the code `/home/ademaria/.m2/repository/io/springfox/springfox-core/2.7.0/springfox-core-2.7.0-sources.jar!/springfox/documentation/builders/OperationBuilder.java:205` it looks like you only ever merge the response messages. Can you please clarify on desired behavior here? I for one, would like to see `@ApiResponses` be an override rather than a merge.

**Comment by dilipkrish** [comment]
You could use the Docket#useDefaultResponseMessages(false)`

**Comment by muff1nman** [comment]
Yes, but I was hoping to use that as a last resort since it would require more annotations.

**Comment by dilipkrish** [comment]
Could you clarify with an example or may be create a breaking test with how you intend it to work vs. how its working now. Happy to consider a contribution if you think its a feature gap.

**Comment by muff1nman** [comment]
Will do.

**Comment by lanwen** [comment]
Example:

```java
   @PostMapping(value = "/lists/{env}/{list-id}/emails", produces = APPLICATION_JSON_UTF8_VALUE, consumes = APPLICATION_JSON_UTF8_VALUE)
    @ApiOperation(value = "Add new emails to list", response = MailListEntry.class)
    public CompletableFuture<Map<MailListEntryState, List<MailListEntry>>> addEmailsToList(@PathVariable String env, @PathVariable("list-id") String listId, @RequestBody List<String> emails) {
```

But it generates definition:

```
"Map«string,List«MailListEntry»»": {
"type": "object",
"additionalProperties": {
"$ref": "#/definitions/List"
}
},
```
problem is `definitions/List` which have no real definition. For example it breaks https://github.com/Rebilly/ReDoc
