### ISSUE TITLE
Inject custom scripts to springfox swagger-ui

### ISSUE THREAD

**Issue by Mario-Eis** [springfox/springfox#1888]
What version of the library are you using?
2.7.0

What kind of issue is this?
Question / Feature Request

Is it possible to inject custom java scripts to the springfox swagger-ui? 
As I understand my request should be similar to what swashbucke does here: https://github.com/domaindrivendev/Swashbuckle/#injecting-custom-content

**Comment by dilipkrish** [comment]
Not really easy to do. Simpler to download the swagger-ui and customize it youself

**Comment by aniketbhatnagar** [comment]
Is it possible to put this in as feature request? We could add a new field to UiConfiguration for custom script and then in onSuccess(data) JS method, we can inject the custom script. Sounds like an easy enough change?

**Comment by dilipkrish** [comment]
Thanks a great idea. Would you like to try your hand at a PR? The caveat to that is that there is a pending update to swagger 3.0 that needs to happen.

**Comment by Mario-Eis** [comment]
Is this feature included in 2.8.0?

**Comment by dilipkrish** [comment]
@Mario-Eis No it is not. Its closed because we migrated to swagger ui 3.x in this release and this issue is no longer relevant.

**Comment by mzhokha** [comment]
@dilipkrish Hi, does it mean that swagger ui 3.x supports injecting custom scripts? Didn't find info about that. Thanks in advance.

**Comment by dilipkrish** [comment]
Actually swagger-ui 3.x has a better extensibility model, so it might be possible  to load custom scripts. I havent investigated it. However, this issue is closed because its no longer relevant
