### ISSUE TITLE
ParameterBuilderPlugin not picking up custom objects from method input params

### ISSUE THREAD

**Issue by pamput** [springfox/springfox#1889]
We are trying to write a parameter builder plugin to ease the docs generation.

We are using `springfox-2.7.0` with `spring-mvc-4.3.3`.  We are not using `spring-boot`.

We have a couple of parameter resolvers configured in our mvc stack, so the mapping methods in our controllers look something like:

```
public List doStuff(
            @RequestParam(value = "id", required = false) String[] ids,
            @CustomAnnotation CustomClass custom
    ) {
   // A lot of magic
}
```
We would like to generate some automatic documentation for `custom` if it's annotated with `@CustomAnnotation`.

We are following various examples on how to write the plugin, and it mostly works. Our only problem is that our plugin is not invoked for custom input classes (in other words, the `apply` method of the plugin is not invoked for params as `custom` in the above example). We tried many combinations and we can see the plugin being fed and working with different types of fields:

- Strings
- Integers
- Maps
- etc.

But as soon as we provide a class from our own domain, the input parameter is completely skipped. Is this the expected behaviour? Is there any reason behind this? Is there a way to override this behaviour or force it?

Cheers

**Comment by pamput** [comment]
I think I have figured out what's the issue :\

The issue is `OperationParameterReader`. It sees our object as something to expand:

```
  private boolean shouldExpand(final ResolvedMethodParameter parameter, ResolvedType resolvedParamType) {
    return !parameter.hasParameterAnnotation(RequestBody.class)
        && !parameter.hasParameterAnnotation(RequestPart.class)
        && !isBaseType(typeNameFor(resolvedParamType.getErasedType()))
        && !resolvedParamType.getErasedType().isEnum()
        && !isContainerType(resolvedParamType)
        && !isMapType(resolvedParamType);

  }
```

Even if I can sorta see the reason behind that, if you use a custom object and don't want (can't) annotate it yourself, it would be useful to make it not expandable. In the current situation you can't even use a Guava Multimap :\

**Comment by dilipkrish** [comment]
a Guava `Multimap` should resolve to a `Map`. You can indicate if a parameter needs to be expanded or not by using a `RequestBody` annotation of course. If you do want to use it as a non-body parameter you can implement your own `ExpandedParameterBuilderPlugin` rather than a `OperationParameterReader` plugin.

**Comment by pamput** [comment]
>  a Guava Multimap should resolve to a Map

Unfortunately they don't since they don't extend the Map interface.

> If you do want to use it as a non-body parameter 

Yes, this is the case

> you can implement your own ExpandedParameterBuilderPlugin

Does this require me to use a specific annotation to trigger?

**Comment by dilipkrish** [comment]
> Unfortunately they don't since they don't extend the Map interface.

I realized as soon as I posted. I'll see how that can be handled.

> Does this require me to use a specific annotation to trigger?

If its a regular bean then no. But if its a custom object reconstituted by an argument resolver (string -> custom object) it can be a little tricky to describe.

**Comment by zhaojigang** [comment]
hi, pamput, you said
"The only solution I can see for now is to create an operation builder plugin instead of a parameter one",  how is it realized in detail?
@pamput
