### ISSUE TITLE
Can't declare Docket in multiple Configuration classes

### ISSUE THREAD

**Issue by lorenzobenvenuti** [springfox/springfox#1890]
Hi,

we're trying to figure out if it's possibile to declare `Docket` beans in `@Configuration` classes different from the "main" one. The scenario is the following: we have a multi-module application and each module should define its Controllers. A common module is defining the SpringFox configuration:

```java
@Configuration
@EnableSwagger
public class SpringFoxConfig {

    @Bean
    public Docket allApisDocket() {
       // ...
    } 

}
```

This configuration scans all the controller of the context and returns the json docs for all the APIs.

Now we'd like that each module could define a `Docket` with a specific `groupName` (which is basically a partial view of the APIs). In another configuration class (loaded via `@ComponentScan` in the same context) we've put

```java
@Configuration
public class ModuleXConfig {

   public Docker moduleXDocket() {
       return new Docket(DocumentationType.SWAGGER_2)
                 /* ... */
                 .groupName("moduleX");
   }

}
```

Unfortunately this is not working; if we move the `moduleXDocket` to the `SpringFoxConfig` then everything is fine. 
We did a couple of tests, without luck: 
- Use `@EnableSwagger2` in the second configuration
- Load the second configuration via `@ComponentScan` from `SpringFoxConfig`

We're not using Spring Boot; spring-mvc is at version 4.3.9 and we're stuck with SpringFox version 2.2.2 (our application must be compatibile with JEE6 specs, our understanding is that newer version depends on servlet-api 3.1 => JEE7).

Are we missing something? Is it a bug? Is this an unsupported feature? 

Thank you,

lorenzo

**Comment by dilipkrish** [comment]
Firstly you should upgrade to springfox 2.7.0 while it uses a provided dependency of servlet api 3.1 it [can run under a 2.5 spec compliant container](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/new-in-4.0.html#_java_ee_6_and_7).

Frankly I haven't tried importing dockets from modules. Are you explicitly importing your `ModuleXConfiguration` or are you component scanning it. It might be a timing issue.

**Comment by lorenzobenvenuti** [comment]
Thank you (and please excuse me for the late replay). I'll try to upgrade to v2.7.0 as soon as I can. Regarding my tests I tried to include the dockets both importing the configuration and using component scan, with no success.

Thank you,

lorenzo

**Comment by dilipkrish** [comment]
@lorenzobenvenuti great! let me know what you find with 2.7.0

**Comment by vijaykalidindi** [comment]
I have exactly the same situation. I am using springfox-2.7.0 and I have tried the pretty much the same steps before stumbling on this page. No success so far, only the second config
- Use @EnableSwagger2 in the second configuration
- Extend the second configuration from the first
- Declare the Bean Order(1) in the second configuration.

@lorenzobenvenuti  Have you managed to get it running.
@dilipkrish any help is much appreciated.

Cheers

**Comment by lorenzobenvenuti** [comment]
Hi @vijaykalidindi, I'm sorry but I didn't investigate further.

lorenzo

**Comment by dilipkrish** [comment]
I'll investigate thanks for reporting @vijaykalidindi

**Comment by cgraefe** [comment]
I am using version 2.9.2 and I seem to be having the exact same issue. From reading the above, I'm not sure if this is supposed to be fixed? Or was it working all along if done right? If so, what do I need to do in order to define Dockets in different classes?
