### ISSUE TITLE
Swagger2 UI - how to by pass oAuth2 configuration

### ISSUE THREAD

**Issue by KpGitHub04** [springfox/springfox#1891]
Hi experts,
am facing an issue in my application. i have enabled oauth for my spring boot project ( rest service). i have created a rest client to access the oauth enabled api. 
when i load my swaggerui ( 2.5 version) 
```json
{
  "error": "unauthorized",
  "error_description": "Full authentication is required to access this resource"
}
```

if i hit the end point via post man it works. because post man is a nice tool where i can enter bearer token and invoke the service. 

```java
@EnableResourceServer
@Configuration
@Component
public class ResourceServerConfiguration extends ResourceServerConfigurerAdapter
{
    // default url used by the resource server to check if the incoming toekn is
    // valid
    @Value("${resource.token.clientUrl}")
    private String clientUrl;
 
    @Value("${resource.token.id}")
    private String resourceId;

    @Value("${resource.token.clientId}")
    private String clientId;

    @Value("${resource.token.clientSecret}")
    private String clientSecret;

    @Bean
    public RemoteTokenServices remoteTokenServices()
    {
        final RemoteTokenServices tokenServices = new RemoteTokenServices();
        tokenServices.setCheckTokenEndpointUrl(clientUrl);
        tokenServices.setClientId(clientId);
        tokenServices.setClientSecret(clientSecret);
        tokenServices.setAccessTokenConverter(new JwtAccessTokenConverter());
        return tokenServices;
    }

    @Override
    public void configure(ResourceServerSecurityConfigurer resources) throws Exception
    {
        resources.tokenServices(remoteTokenServices()).resourceId(resourceId);
    }


    /**
     * this section can be modified to suit your service's url patterns if need
     * be. this default config will allow for swagger resources to be
     * un-protected, while everything else requires 'myapp.read' authority
     */
    @Override
    public void configure(HttpSecurity http) throws Exception
    {
        http.csrf().disable().antMatcher("/**") // this will apply to the entire
                                                // web server
                .authorizeRequests()
                .antMatchers("/v2/api-docs", "/configuration/ui", "/swagger-resources", "/configuration/security",
                        "/swagger-ui.html", "/webjars/**", "/swagger-resources/configuration/ui", "/swagger-ui.html",
                        "/swagger-resources/configuration/security")
                .permitAll() // this
                .antMatchers(HttpMethod.GET, "/**").access("#oauth2.hasScope('myapp.read')").anyRequest()
                .authenticated();

    }
```

Please guide me with the right configuration which will enable me to access the application through swagger UI as well. we test our application via swagger most of the times. 

if i remove the `   .antMatchers(HttpMethod.GET, "/**").access("#oauth2.hasScope('myapp.read')").anyRequest()
                .authenticated();` able to hit the service with out any authentication. my scope is to enable a REST APP with oauth enabled and test via swagger2.

**Comment by KpGitHub04** [comment]
i also tried with `@Override
    public void configure(HttpSecurity http) throws Exception {
        http
            .csrf().disable()
            .antMatcher("/**") // this will apply to the entire web server
            .authorizeRequests()
                .antMatchers("/swagger-ui.html", "/swagger-resources/**", "/v2/**").permitAll() // this should allow swagger to operate
                .anyRequest().hasAuthority("myapp.read"); // everything else requires 'myapp.read' authority
    }`

**Comment by dilipkrish** [comment]
You need to use `WebSecurityConfigurerAdapter` I believe. Similar to [this configuration](https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/config/SecurityConfiguration.java#L136-L148)

**Comment by danylo-dubinin** [comment]
i solved a similar issue by creating one more config for development profile:
```java
@Configuration
@EnableWebSecurity
@Profile("development")
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    public void configure(final WebSecurity web) throws Exception {
        web.ignoring().antMatchers("/**");
    }
}
```
and excluded resource server config
```java
// ...
@Profile("!development")
public class ResourceServerConfiguration extends ResourceServerConfigurerAdapter {
  // ...
```

**Comment by dilipkrish** [comment]
@danylo-dubinin thanks!

**Comment by danylo-dubinin** [comment]
also, there is the other way that doesn't require creating another config class
in your `configure(HttpSecurity http)`:
```
if (!requireAuth) { // define require auth in development profile properties as false and true in other profiles
  http.authorizeRequests().anyRequest().permitAll();
  http.anonymous().authorities( /* add an array of your security roles here */ );
}
```

**Comment by KramerIT** [comment]
@Configuration
@EnableResourceServer
@EnableWebSecurity
public class ResourceServerConfig extends ResourceServerConfigurerAdapter {

    @Override
    public void configure(ResourceServerSecurityConfigurer resources) throws Exception {
        resources.resourceId("webresource");
    }

    @Override
    public void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .antMatchers("/swagger-ui.html").permitAll()
                .antMatchers(HeartbeatController.REQUEST_MAPPING + "/**").permitAll()
                .antMatchers(AdvertController.REQUEST_MAPPING + "/**").hasAnyAuthority(UserRole.VALIDATED_USER.name(), UserRole.ADMIN.name(), UserRole.SUPER_ADMIN.name())
                .anyRequest().permitAll();
    }
}

**Comment by delgorx** [comment]
`@Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring().antMatchers("/v2/api-docs", "/configuration/**", "/swagger-resources/**",  "/swagger-ui.html", "/webjars/**", "/api-docs/**");
    }`

**Comment by delgorx** [comment]
Sorry for the format

`@Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring().antMatchers("/v2/api-docs", "/configuration/**", "/swagger-resources/**",  "/swagger-ui.html", "/webjars/**", "/api-docs/**");
    }`

**Comment by mishatim** [comment]
The above solution worked as a charm.  Many thanks!

**Comment by blakrin** [comment]
Thanks.

**Comment by celovivas** [comment]
> Sorry for the format
> 
> ```java
> @Override
>     public void configure(WebSecurity web) throws Exception {
>         web.ignoring().antMatchers("/v2/api-docs", "/configuration/**", "/swagger-resources/**",  "/swagger-ui.html", "/webjars/**", "/api-docs/**");
>     }
> ```

For me it worked too. 
Thanks!
But, how can I pass the token in my uri methods?
