### ISSUE TITLE
filtering on Http methods PATHS

### ISSUE THREAD

**Issue by mahesh-uma** [springfox/springfox#1893]
```java      
  @Bean
  public Docket apiForUser() {
      return new Docket(SWAGGER_2)
          .groupName("users")
          .select()
          .paths(pathsForUser())
          .apis(customRequestHandlers())
          .build();
  }
  private Predicate<String> pathsForUser() {
     return or(regexFor(Paths.REQUESTS), regexFor(Paths.RESULTS));
  }
  private Predicate<RequestHandler> customRequestHandlers() {
    return (RequestHandler input) -> {
    Set<RequestMethod> methods = input.supportedMethods();
    return (methods.contains(RequestMethod.GET) || methods.contains(RequestMethod.POST));
    };
 }
  private Predicate<String> regexFor(String path) {
      return regex("/?/" + path + ".*");
   }
 }
```

For one Docket group I have two controllers and able swagger view like this

**In first controller**
GET requests/
GET requests/{id}
GET requests/matches/{id}
POST request

**second controller**
GET results/
GET results/{id}
GET results/matches/{id}
POST results

Now I want view only one post request from two controller  **HOW TO ACHIEVE BELOW OUTPUT**
GET requests/
GET requests/{id}
GET requests/matches/{id}
POST request

**second controller**
GET results/
GET results/{id}
GET results/matches/{id}

**Comment by dilipkrish** [comment]
You can define your predicate `customRequestHandlers` to exclude that method alone.
