### ISSUE TITLE
@EnableSwagger2 unable to handle MvcEndpoint beans marked with @RefreshScope

### ISSUE THREAD

**Issue by mmoayyed** [springfox/springfox#1895]
> Please take the time to search the repository, if your question has already been asked or answered.

- [X] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ]

2.7.0 w/ Spring Boot 1.5.4 and Spring Cloud

What kind of issue is this?

 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

## Problem

In a Spring Boot 1.5.4 configuration class, there exists the following bean:

```java
    @Bean
    @RefreshScope
    public MvcEndpoint testController() {
        return new TestController();
    }
```

The `TestController` is a child of `AbstractNamedMvcEndpoint` from Spring Boot. When `@EnableSwagger2` annotation is added to a configuration class, the following error pops up:

```bash
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'endpointHandlerMapping' defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointWebMvcManagementContextConfiguration.class]: 
Invocation of init method failed; nested exception is java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'org.example.TestController@54629f32' method 
public org.springframework.web.servlet.ModelAndView org.example.TestController.handle(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception
to {[/status/dashboard || /status/dashboard.json],methods=[GET]}: There is already 'org.example.TestController@54629f32' bean method
public org.springframework.web.servlet.ModelAndView org.example.TestController.handle(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception mapped.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
```

## Solution

Removing `@RefreshScope` fixes the problem.

## Diagnosis

It appears that when `EndpointWebMvcManagementContextConfiguration` begins to find `MvcEndpoint` bean definitions it actually does find two of them: a `TestController` and second `@TestController` that is proxy instance created as a result of `RefreshScope`. My suspicion is that the first instance of `TestController` is created by the swagger auto-configuration and maybe that configuration does not respect `@RefreshScope` such that it simply creates a vanilla bean instance which then duplicates what `EndpointWebMvcManagementContextConfiguration` finds.

**Comment by dilipkrish** [comment]
@mmoayyed Really not sure how this bean configuration and the `RefreshScope` are supposed to work together. If this is a bug, which I suspect it might be, I have no way of fixing and verifying if its fixed. Would you mind taking charge and seeing what the cause might be and see if there is a way to fix?

**Comment by mmoayyed** [comment]
Sure. Before I do, let me ask: 

1. What component in this library is mainly in charge of locating request mappings and MvcEndpoints? 
2. Note that `AbstractNamedMvcEndpoint` [1] inherits from `WebMvcConfigurerAdapter`. Could that cause any issues that might be relevant here ?


[1] http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/endpoint/mvc/AbstractNamedMvcEndpoint.html

**Comment by dilipkrish** [comment]
@mmoayyed actually we don't try to locate request mappings other than spring mvc `RequestMapping`s usually all `RequestMappingHandlerMapping` beans. With the spring-data-rest support we do slurp in `BasePathAwareHandlerMapping`; but thats about it.

It is very likely that the `WebMvcConfigurerAdapter` beans might interfere, but Im not sure how.

**Comment by mmoayyed** [comment]
OK That sort of makes sense. Take a look at this example:

```java
public class TestController extends AbstractNamedMvcEndpoint {

    ...

    @GetMapping
    public ModelAndView handle(final HttpServletRequest request, final HttpServletResponse response) throws Exception {
         ...
    }
}

...

@Bean
@RefreshScope
public MvcEndpoint testController() {
      return new TestController();
}

```

So `@GetMapping` is an alias for `RequestMapping`. Event through this component is not a controller of any kind, could you confirm that the scanning process does in fact pick up `TestController` because of that `@GetMapping`?

**Comment by dilipkrish** [comment]
Will need to check if that causes the request mapping to show up.
