### ISSUE TITLE
Spring boot with swagger issue

### ISSUE THREAD

**Issue by coder38** [springfox/springfox#1898]
I am using spring fox swagger v 2.7.0 and spring boot 1.5.4

I have tomcat running through eclipse but the browser gives a 404 error in console saying:
Failed to load resource: the server responded with a status of 404 ()

URL I am using is http://localhost:9000/api/swagger-ui.html

/api is the context path I gave in application.properties

My WebConfig has : 
@Configuration
public class WebConfig extends WebMvcConfigurerAdapter{
	
	  @Override
	    public void addResourceHandlers(ResourceHandlerRegistry registry) {
	        registry.addResourceHandler("swagger-ui.html")
	                .addResourceLocations("classpath:/META-INF/resources/");

	        registry.addResourceHandler("/webjars/**")
	                .addResourceLocations("classpath:/META-INF/resources/webjars/");
	}
}

**Comment by naXa777** [comment]
Based on your example I can say that you don't need custom `WebMvcConfigurerAdapter`. Your resources should be automatically discovered by Spring Boot. Get rid of the unnecessary code and see if the error is gone. Try to run your project with this simple WebConfig:

```
@Configuration
public class WebConfig {}
```

**Comment by dilipkrish** [comment]
@coder38 try @naXa777's suggestion. Also you don't need a `WebConfig` class that contributes to configuration if it doesnt add any configuration.

**Comment by coder38** [comment]
Thank you for your response!
I tried removing it but was not able to resolve the issue. 
 http://localhost:9000/api/ doesn't work either. Would tomcat run if there was anything missing? I cannot figure out what went wrong

**Comment by dilipkrish** [comment]
Just navigating to  `http://localhost:9000/swagger-ui.html` should bring up the swagger definitions.

**Comment by coder38** [comment]
still 404 on swagger-ui.html

**Comment by dilipkrish** [comment]
Do you have `@EnableWebMvc` annotation in your project?

**Comment by coder38** [comment]
no since I am using @SpringBootApplication annotation and it includes @Enablewebmvc I read

**Comment by Pyohwan** [comment]
I think, didn't need below code in Spring boot.
Basically, /resource/ is registered in web container.
```
@Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
}
```
