### ISSUE TITLE
Tag custom ordering

### ISSUE THREAD

**Issue by rainoko** [springfox/springfox#1900]
Right not tags are ordered by name comparator. May be its more useful if tag contains order numer. And comparator should order by that number falling back to name if order by number is equal.

I can contribute with that.

**Comment by dilipkrish** [comment]
Could you describe how you'd provide the order on the tag?

**Comment by rainoko** [comment]
I would add int order for tag. which should be optional and default 0 or max int.  and rewrite namecomparator for using this new field.

public class Tag {
  private final String name;
  private final String description;
  **private final int order;**

https://github.com/rainoko/springfox/commit/bc5af62e9757afb60fdc90a7d8c6a46bf7588e58

**Comment by dilipkrish** [comment]
🎱 Not really looking how to do it. Im asking how you'd specify a value for the order (via annotations etc. I presume?) You'd have to create new annotation because the existing swagger annotations don't support it.

**Comment by rainoko** [comment]
First solution that I thought was through docket.
.tags(new Tag("Pet Service", "All apis relating to pets", 1)) 

So custom ordering supported only when explicitly defining tags in docket.

**Comment by dilipkrish** [comment]
That seems reasonable. How about implementing the spring `Ordered` interface. Happy to take in the contribution.
