### ISSUE TITLE
Pattern Bean Validations API (JSR-303) support for Request Parameters

### ISSUE THREAD

**Issue by simonamc** [springfox/springfox#1901]
It looks like #1227 aded support for `@Min`, `@Max`, `@NotNull` and `@Size` validators, these are working great although should they be added to BeanValidatorPluginsConfiguration as per schema plugins?

We would like to document parameter regex too with the `@Pattern` annotation.

I don't see such a plugin in sprinfox-bean-validators springfox.bean.validators.plugins.parameter.  I can see that this would be trickier to implement than the other validators as springfox.documentation.builders.ParameterBuilder and springfox.documentation.service.Parameter are also missing pattern fields.

Is there a reason for the exclusion of this?  If I found time to implement this would a pull request be welcome?  We can almost work around this using vendorExtensions but looks like they aren't mapped as already tracked by #1657

Cheers.

**Comment by dilipkrish** [comment]
There is no particular reason. Really would welcome a contribution

**Comment by simonamc** [comment]
I've created the above pull request, I've not pushed to github before so let me know if I've done anything wrong.

**Comment by dilipkrish** [comment]
Thanks for helping out with this @simonamc!! very much appreciated 🙇

**Comment by raderio** [comment]
Where information about pattern should be shown? I have @Pattern annotations but in UI I don't see any information.

**Comment by dilipkrish** [comment]
It will validate the pattern if Im not mistaken

**Comment by raderio** [comment]
Bu it is possible to show that in UI? 
like 
`@JsonFormat(pattern = "yyyy-MM-dd", shape = JsonFormat.Shape.STRING, lenient = OptBoolean.FALSE)`
is shown in UI in "Example Value"
