### ISSUE TITLE
Nondeterministic output for Models used in multiple controllers

### ISSUE THREAD

**Issue by kevinm416** [springfox/springfox#1904]
springfox-swagger2 version 2.6.1

I create two controllers:
```java
@Controller
@RequestMapping("controller1")
public class Controller1 {
    @RequestMapping(
            value = "/endpoint1",
            method = RequestMethod.GET)
    @ResponseBody
    public MyClass getMyClass() {
        return ImmutableMyClass.of("abc");
    }
}

@Controller
@RequestMapping("controller2")
public class Controller2 {
    @RequestMapping(
            value = "/endpoint2",
            method = RequestMethod.GET)
    @ResponseBody
    public void getMyClass(@RequestBody MyClass request) {
    }
}

@Value.Immutable
@Value.Style(allParameters = true)
@JsonSerialize(as = ImmutableMyClass.class)
@JsonDeserialize(as = ImmutableMyClass.class)
public interface MyClass {
    String getFoo();
}
```

The swagger generated for MyClass from Controller1 looks like:
```json
    "MyClass" : {
      "type" : "object",
      "required" : [ "foo" ],
      "properties" : {
        "foo" : {
          "type" : "string"
        }
      }
    }
```

The swagger generated for MyClass from Controller2 looks like:
```json
    "FrontendExternalDataCallConfiguration" : {
      "type" : "object",
      "properties" : {
      }
    },
```

I understand why each controller [generates different swagger](https://github.com/springfox/springfox/issues/1490), and that is not what this ticket is about. The issue is that the version of generated swagger used is not deterministic.

In [ModelMapper#modelsFromApiListings](https://github.com/springfox/springfox/blob/5f2caafdc07da6a95d88fba38a6ffd394a215074/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ModelMapper.java#L219), the Model for MyClass comes up twice. Depending on the order the ``ApiListings`` are visited, the swagger could either contain the output from Controller1 or Controller2. The ``ApiListings`` are not visited in a deterministic order, because they are visited by iterating through the keys in a Multimap.

**Comment by dilipkrish** [comment]
This is because you're using immutables with the `JsonSerialze`/`JsonDeserialize` annotation. To automatically include model properties correctly you need to do the following.

1. Create a jackson serializer convention bean 
```java
@Bean
@Autowired
public AlternateTypeRuleConvention jacksonSerializerConvention(TypeResolver resolver) {
    return new JacksonSerializerConvention(resolver, "com.your.package.to.scan.for.models")
}
```

See an [example here](https://github.com/springfox/springfox/blob/c48a8bb019371cb1e3c79d24c3db3791ac5025cc/swagger-contract-tests/src/test/groovy/springfox/test/contract/swaggertests/FunctionContractSpec.groovy#L187-L205).

**Comment by kevinm416** [comment]
I'm having issues with JacksonSerializerConvention. I know that the JacksonSerializerConvention is being used by springfox and is having an affect on the swagger that gets produced. It replaced all references to my interfaces with their immutable classes. However, I'm still seeing the same non-deterministic behavior where sometimes the immutable objects do not have any properties.

OptimizedModelPropertiesProvider#propertiesFor gets called twice with the ResolvedType for my request class. The first time, this produces the correct ModelProperty with the properties set. The second time, ``annotatedMember`` is absent for each entry in ``propertyLookup``, no properties are generated for the class. ``annotatedMember`` is absent because the BeanPropertyDefinition is a POJOPropertyBuilder with ``_forSerialization`` set to false, so POJOPropertyBuilder looks for a mutator via ``getMutator()``, which doesn't exist on these immutable objects.

**Comment by kevinm416** [comment]
I think I see what's going on. In ``OptimizedModelPropertiesProvider#beanDescription``, when the deserialization context is used, I get the POJOPropertyBuilder with ``_forSerialization`` set to false, because, well, it's not being used for serialization. 

I think the feature I'm really asking for is the ability to say that the serialized form of the object should be used in both the request and response situation. That may sound a bit strange, but it would be useful for people who are using custom deserialization code with Jackson that can't be identified by springfox (including immutables users). I think it's likely that objects serialize and deserialize with the same fields.

Or maybe a plugin point that would allow me to create the BeanDescription myself, so I could replace the implementation of ``OptimizedModelPropertiesProvider#beanDescription`` with something along the lines of:
```
      SerializationConfig serializationConfig = objectMapper.getSerializationConfig();
      return serializationConfig.introspect(serializationConfig.constructType(type.getErasedType()));
```
where the serialized form is used, whether or not ``context.isReturnType()`` is true.

**Comment by dilipkrish** [comment]
> I think the feature I'm really asking for is the ability to say that the serialized form of the object should be used in both the request and response situation. 

Totally correct. There is some work in progress that make that experience better. However we're not there yet. 

However I've run into issues with `Immutables` that are not particularly obvious. Immutables are great, except that, unless u craft your model correctly it might lead to confusing results, as you've seen. Also how springfox infers the model is opposite to how the service consumes it. By that I mean that, take for e.g. `Model` has properties `a`  (read/write), `b` (write only), c (readonly)  we read the writable properties for requests and readable properties for responses. 

So if your model is only used for requests, it will have `a` and  `b`
And if your model is only used of responses it will have `a` and `c`
and if it is present in both request and response it will have `a`, `b` and `c`.

That said these properties need to be readable/writable according to jackson.

Hope that clarifies.

__NOTE:__ We're working on making this better in a couple of ways by adding support for request-response differentiation, projects (`@JsonView` or `@Projection`) and if possible inheritance as well.

**Comment by kevinm416** [comment]
> unless u craft your model correctly it might lead to confusing results

Is it possible for me to craft a correct model using immutables in 2.7.0? Ignoring my feature request, there appears to be non-deterministic behavior for which representation is produced. In the swagger json file that gets produced, there is only one representation of ``ImmutableMyClass``. Depending on which order the two calls to ``OptimizedModelPropertiesProvider#propertiesFor`` occur,  the single representation that gets written either contains the serialization or the deserialization representation. 

I don't see how I can create an immutables class that has the correct representation for deserialization. If I can't, that's fine - I just will not be able to use immutables for request classes until the next release springfox :)

**Comment by dilipkrish** [comment]
@kevinm416 Let me try and put a sample together
