### ISSUE TITLE
@ApiParam hidden=true not work on object

### ISSUE THREAD

**Issue by Shaun-Yao** [springfox/springfox#1908]
I use v2.7.0

       @ApiParam(hidden=true)
	@JsonIgnore
	@UpdateTimestamp
	@Column(name = "MODIFIED_DATE", nullable = false, updatable = false)
	protected Date modifiedDate;
	
	
	@ApiParam(hidden=true)
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIER")
	protected Admin modifier;
	
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	protected Admin creator;

![qq 20170711104156](https://user-images.githubusercontent.com/18024481/28048763-a055f784-6625-11e7-9236-45d5b2fd89ba.png)

creator is automatically hidden ？？

**Comment by dilipkrish** [comment]
@Shaun-Yao `@ApiParam` annotations are not supported on fields/accessors. Only on operations

**Comment by Shaun-Yao** [comment]
@dilipkrish got it, thanks!
