### ISSUE TITLE
Does globalOperationParameters support setting exclusion paths?

### ISSUE THREAD

**Issue by wf2311** [springfox/springfox#1910]
For example, I defined a global parameter named userToken, I don't want this parameter appears in the api for the login method, how to configure this?

**Comment by dilipkrish** [comment]
@wf2311 there was a feature for this. If I can find it I'll link it here and mark it as duplicate. In anycase thanks for reporting!

**Comment by mbausdorf** [comment]
Would love to see this included - currently facing a similar issue

**Comment by utkarsh-bodake-n26** [comment]
I am too facing the same issue, are there any plans to add this feature?

**Comment by herbola** [comment]
bruh
