### ISSUE TITLE
Create ModelRef from ResolvedType

### ISSUE THREAD

**Issue by pamput** [springfox/springfox#1911]
I'm developing a springfox plugin and I need to create a `ModelRef` from a `ResolvedType`.

The ResolvedType is parametrized (es. `MyClass<Parameter>`) and I can see a constructor inside ModelRef that takes a String as input which should look like `MyClass«Parameter»`.

Is there a utility class I can use instead of having to create the String myself?

**Comment by dilipkrish** [comment]
You should be able to create your own `TypeNameProviderPlugin` and register it as a bean
