### ISSUE TITLE
Exclude RequestMapping parameters

### ISSUE THREAD

**Issue by dmitrychief** [springfox/springfox#1912]
How to exclude query params from the description when they are defined in @RequestMapping?
For example, the parameter "op" need to be omitted. I'm using springfox-2.5.0
```
    @ApiOperation(value = "list folder contents")
    @RequestMapping(
        params = "op=LIST",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_UTF8_VALUE
    )
    @ResponseStatus(HttpStatus.OK)
    public Page<FileSystemItem> list() {
    }
```

**Comment by dilipkrish** [comment]
Currently you cannot, but I see your point about being able to

**Comment by dmitrychief** [comment]
@dilipkrish Thank you for your reply! Probably, one can work around this by explicitly introducing "op" as a controller method parameter and annotating it by `@ApiIgnore`.

**Comment by dilipkrish** [comment]
@dmitrychief true. Plus you could set the defaultValue on the RequestParam to `LIST` and it would be equivalent.
