### ISSUE TITLE
Space getting added to oAuth scope while making authorization request

### ISSUE THREAD

**Issue by mojaiq** [springfox/springfox#1913]
I am using Springfox UI v 2.7.0 and have integrated OAuth authorization successfully with the Swagger UI. However I noticed an issue when I am specifying multiple scopes as part of defining the AuthorizationScopes. It seems that the Http request being made to request Authorization code appends a space to the scope string and this causes the authorization request to fail.  
Relevant code snippets are ..

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {
@Bean
	public Docket postsApi() {
		return new Docket(DocumentationType.SWAGGER_2).groupName("public-api")
				...
				.build()		
				.securitySchemes(Collections.singletonList(oauth()))
		;
	}

@Bean
    SecurityScheme oauth() {
        return new OAuthBuilder()
                .name("OAuth2")
                .scopes(scopes())
                .grantTypes(grantTypes())
                .build();
    }
	
	private List<AuthorizationScope> scopes() {
		List<AuthorizationScope> list = new ArrayList();
		list.add(new AuthorizationScope("scope_write","Grants read and write access to All"));
		list.add(new AuthorizationScope("scope_read","Grants read access to All"));	
		return list;
    }    	

	@Bean
    public SecurityConfiguration securityInfo() {
        return new SecurityConfiguration(clientId, clientSecret, "realm", clientId, "", ApiKeyVehicle.HEADER, "api_key", "");
    }
```
While selecting a scope for authorization on the Swagger UI, the first scope selected always works as the request is framed correctly. In this case i.e.
 http://myauthserver/oauth/authorize?response_type=code&redirect_uri=http://myhost/mycontextpath/webjars/springfox-swagger-ui/o2c.html&realm=realm&client_id=myclientId&scope=scope_write&state=OAuth2

However if I select the second scope from the Swagger UI, then the request gets sent as http://myauthserver/oauth/authorize?response_type=code&redirect_uri=http://localhost:8083/api/v1/xms-pt-routemgmt/webjars/springfox-swagger-ui/o2c.html&realm=realm&client_id=myclientId&scope=%20scope_write&state=OAuth2
This fails the scope match because of a leading space character in the scope.
If I change the scope separator to space or , then that gets appended to the scope. Do I need to mention the scope separator anywhere else apart from security Info in order for the request to be constructed correctly ? 

Thanks..

**Comment by mojaiq** [comment]
Line 157, swagger-oauth.js
`url += '&scope=' + encodeURIComponent(scopes.join(scopeSeparator));`

**Comment by dilipkrish** [comment]
@mojaiq This is probably the weakest link of this library. My gut tells me its a problem with swagger-ui but sine I haven't got a demo to showcase this against, I cannot say that for sure. I'll look and see if I can figure it out. 

On the other hand since you're closer to figuring it out, would be a great help if we can partner to create a working demo.

**Comment by mojaiq** [comment]
@dilipkrish , sure thing. I do have a working environment on my end that is integrated with UAA (Cloud foundry OAuth server). So I can help with testing any fixes.

**Comment by dilipkrish** [comment]
If its not too much to ask could you perhaps create a very basic sample. I'd be happy to create a repository and give you access to it.

**Comment by mojaiq** [comment]
Ok. I will try to put up a sample over the weekend. Let me know once the repo is ready and I will push the sample along with instructions on how to run it.

**Comment by mojaiq** [comment]
Sample project is ready. Let me know the repo details to upload.

**Comment by dilipkrish** [comment]
@mojaiq thank you so much. Here is the repository. I've given you access to push as well.

**Comment by mojaiq** [comment]
@dilipkrish , pushed files to the repo. Please take a look and let me know if you face any issues in set up.

**Comment by dilipkrish** [comment]
@mojaiq this is fantastic! Thanks so much for helping out. I'll try it out later this evening

**Comment by mojaiq** [comment]
@dilipkrish , any update on this. Thanks...
