### ISSUE TITLE
https url for swagger ui using springfox opens in port 80. Shouldn't the port be defaulted to 443 when its https? Can we set the port no alone in host?

### ISSUE THREAD

**Issue by Divzz** [springfox/springfox#1918]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x ] Question. Is this a question about how to do a certain thing? 

Description:
This issue is similar to : https://github.com/springfox/springfox/issues/1634 but issue is closed.

I have a https url. But swagger ui using springfox opens in port 80.  Using version 2.7.0 I can update the host. But updating host needs hostname as well as port no. Shouldn't the port be defaulted to 443 when its https? Can there be a provision of setting port no alone because host name is something which we wouldn't want to hardcode in the application and would prefer to be picked up by SwaggerUi where-ever its launched. Adding the port no: 80 messes up things. I wish to update only port no here but wish to keep the hostname generic and picked up by swagger-ui based on the environment. Do we have a provision for that?

**Comment by dilipkrish** [comment]
How are you using it. It should work out of the box. Are you overriding the host?

**Comment by Divzz** [comment]
I have version 2.7.0. I have deployed my application on kubernetes and accessing it as a https URL.  I am not overriding the host. Using it out of the box. The Swagger UI comes up fine but when I press "Try it out!" it forwards the request to port 80 although I havent defined it anywhere. I saw in v2/api-docs that the host is getting appended with port 80 and messes up the request. So my question is shouldn't port 443 be inferred when it knows its a https URL. Should I be overriding it using Docket#host(hostname:port)? Or is there something else that I need to set to ensure Swagger UI infers port 443?

**Comment by dilipkrish** [comment]
Sounds like you're using an API gateway. If thats the case, you need to make sure you're setting the `X-FORWARD-...` headers appropriately.

**Comment by pparthigithub** [comment]
@Divzz Did you resolve this issue? I'm facing a similar issue with port 80 appended to the request.
My service is not using an API gateway, and I'm on 2.7.0.

**Comment by CluEleSsUK** [comment]
Having a similar issue behind a proxy.  Setting the x-forward-for header, but all the ports get rewritten to 80.
