### ISSUE TITLE
Add support to rename  ApiModel property name in Model Attributes

### ISSUE THREAD

**Issue by peterjurkovic** [springfox/springfox#1919]
I have not found out the way how would be possible to rename `@ApiModelProperty`. The name of the property is inferred from actual  POJO property name which is not quite ideal, because request parameters can be different then the name of to property itself. 

```
@ApiModel
public class SearchCriteria {

	@ApiModelProperty(name = Params.EVENT_TYPE,  value = "Event type", )
	@ParamName("event_type")
	private List<EventType> eventTypes;
}
```
In this case is used name `eventTypes` but I would like to override this name and used custom value defined in `ParamName`.

This is the result:

![](http://upload.peterjurkovic.com/uploaded_files/selection-009.png)

The expected query parameter name is `event_type` in this case.

**Comment by dilipkrish** [comment]
Thanks for reporting. It should pickup the name from the @ApiModelProperty annotation. Also if you have a convention that resolves parameter names using the `ParamName` annotation you could also create a plugin that will use that rather than defining an annotation like `ApiModelProperty`

**Comment by tanadeau** [comment]
There is a similar problem for `@ApiParam`'s `name` for fields.

**Comment by dilipkrish** [comment]
@tanadeau noted... Just to clarify these are problems only for model attributes and not request body.

**Comment by tanadeau** [comment]
I think this may be that `fromApiParam` and `fromApiModelProperty` in `SwaggerExpandedParameterBuilder` doesn't set the `name` on the `ParameterBuilder`.

**Comment by tanadeau** [comment]
Also, if this is fixed relatively soon, can there be a 2.7.1? This bug prevents our swagger JSON from matching the real parameters (e.g., the field is `tags` which is a `Set` but the actual parameter is `tag` that can accept multiple values).

**Comment by dilipkrish** [comment]
Working on 2.8.0 😉

**Comment by dilipkrish** [comment]
Thank you for the pointer @tanadeau!
