### ISSUE TITLE
swagger-ui.html is not loading when deployed in container

### ISSUE THREAD

**Issue by sureshgarrepalli** [springfox/springfox#1921]
Hi,

I'm able to see the swagger-ui.html when I run my springboot application locally using eclipse. But when I build a docker container for the spring boot application and deploy it, I'm not able to see the /swagger-ui.html page

Here's my configuration - 
pom.xml
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.4.0</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.4.0</version>
		</dependency>

Config class for swagger -
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
          .select()
          .apis(RequestHandlerSelectors.basePackage("com.adp.wlp.dsc.rest.controller"))
          .paths(PathSelectors.any())
          .build();
    }
}

I observed some javascript is generated as highlighted in below screenshot 

![image](https://user-images.githubusercontent.com/30242097/28282309-fd28ea6c-6af7-11e7-863a-74c7f2ffe3ae.png)

Where as the same application running local is loading the swagger-ui.html properly as below screenshot - 

![image](https://user-images.githubusercontent.com/30242097/28282446-78b588c0-6af8-11e7-82a1-2ea8bbdf500e.png)

Could somebody help me if I'm missing anything? or what is causing this behaviour ?

Thanks,
Suresh Garrepalli

**Comment by dilipkrish** [comment]
Please use 2.7.0 of the library

**Comment by sureshgarrepalli** [comment]
I tested with 2.7.0, still same issue.

**Comment by dilipkrish** [comment]
Looks like a browser extension injecting some javascript

**Comment by sureshgarrepalli** [comment]
@dilipkrish , I tried disabling all the browser extensions. I tried it in multiple machines. Same Issue.. :(

**Comment by dilipkrish** [comment]
Not sure, it may be your gateway or analytics introducing javascript

**Comment by shahsurajk** [comment]
same issue.

**Comment by sreedhar85in** [comment]
same issue, swagger-ui.html of the application not visible in the container/docker. I used swagger version 2.9.2. When trying to take swagger-ui.html page, I get the message " There was an unexpected error (type=Not Found, status=404).
No message available"

**Comment by sapkotasuren** [comment]
same issue, 404 error/not found when i visit the url: http://localhost:8080/swagger-ui.html 
Could somebody help, i'm running it on docker container, if i run it on my local machine, then i'm able to acccess swagger-ui.

**Comment by sm-xh** [comment]
did anybody manage to fix this? got similar issue, didn't find solution on similar topics unfortunately
