### ISSUE TITLE
The use of the process encountered some problems

### ISSUE THREAD

**Issue by tcsw1221** [springfox/springfox#1922]
1. Do you have a maven plugin that generates .json files?
2. In the generated document, how to unify the url to add. Htm suffix

**Comment by tcsw1221** [comment]
I remember where to see, you can generate through the maven plugin. Json, and then introduced in the ui json file on it

**Comment by dilipkrish** [comment]
Did you get what you were looking for?

**Comment by tcsw1221** [comment]
I have some ideas
Deploy the swagger ui in a single server, and then run the maven command through jenkins to generate the .json file, pointing the address in swagger ui to that file. Because the project is large, running the swagger locally is slow to start, by submitting the code to git, and then using jenkins build to speed up. Finally, ui can be delayed through the rendering and add search function to enhance the searchability of the document
