### ISSUE TITLE
@JsonProperty(access = READ_ONLY) is treated differently on model and inner model

### ISSUE THREAD

**Issue by victorSenia** [springfox/springfox#1928]
Versions:
```    
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.4.RELEASE</version>
    </parent>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.7.0</version>
        </dependency>
```

On models, which are used directly in controllers (as return types) or set (with `@ApiOperation(response=)`) or added by `Docket.additionalModels()` this annotation:     `@JsonProperty(access = JsonProperty.Access.READ_ONLY)` works fine.
But if this model is not used in controllers or set directly, than this field is ignored. As well as all information passed  in `@ApiModelProperty` to this field.
It occurs in any inner level and any type of link (direct or in array).
Also it happens, if first such model is met as part of outer model, and after that as direct in return from controller.
I have not seen such errors with another accesses.
I have managed to resolve this by adding all models to `Docket.additionalModels()`, but it is confusing, why this occurs.

**Comment by dilipkrish** [comment]
@victorSenia It hs happening because models are generated for requests and responses. And because we do not differentiate between them, we currently merge the readable and writable properties if the model appears in both the request and response.

**Comment by victorSenia** [comment]
If they have been merged (I mean all properties was present), it will be good enough.
But for some reason they are not always merged.

**Comment by dilipkrish** [comment]
Weird. I know we don't explicitly support `access=READONLY` would be great if you could create a breaking test like [this one](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java#L235-L237).

**Comment by victorSenia** [comment]
I have not understood how this test must look like, bu t this result will be on this code
```
    @RestController
    @RequestMapping(path = "inner2")
    public static class Controller2 {
        @PostMapping(path = "", consumes = MediaType.APPLICATION_JSON_UTF8_VALUE, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
        protected Inner_2 create(@RequestBody Inner_2 object, Principal principal) {
            return null;
        }
    }

    @RestController
    @RequestMapping(path = "inner1")
    public static class Controller1 {
        @PostMapping(path = "", consumes = MediaType.APPLICATION_JSON_UTF8_VALUE, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
        protected Inner_1 create(@RequestBody Inner_1 object, Principal principal) {
            return null;
        }
    }

    @RestController
    @RequestMapping(path = "outer")
    public static class Controller0 {
        @PostMapping(path = "", consumes = MediaType.APPLICATION_JSON_UTF8_VALUE, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
        protected Outer create(@RequestBody Outer object, Principal principal) {
            return null;
        }
    }

    public static class Inner_1 {
        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        private Integer id;
        @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
        private Outer outer;
        public Inner_1() {}
        public Inner_1(Integer id) {this.id = id;}
        public Integer getId() {
            return id;
        }
        public void setId(Integer id) {
            this.id = id;
        }
        public Outer getOuter() {
            return outer;
        }
        public void setOuter(Outer outer) {
            this.outer = outer;
        }
    }

    public static class Inner_2 {
        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        private Integer id;
        @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
        private Inner_1 inner_1;
        public Inner_2() {}
        public Inner_2(Integer id) {this.id = id;}
        public Integer getId() {
            return id;
        }
        public void setId(Integer id) {
            this.id = id;
        }
        public Inner_1 getInner_1() {
            return inner_1;
        }
        public void setInner_1(Inner_1 inner_1) {
            this.inner_1 = inner_1;
        }
    }

    public static class Outer {
        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        private Integer id;
        private Integer number;
        public Outer() {}
        public Outer(Integer id) {this.id = id;}
        public Integer getId() {
            return id;
        }
        public void setId(Integer id) {
            this.id = id;
        }
        public Integer getNumber() {
            return number;
        }
        public void setNumber(Integer number) {
            this.number = number;
        }
    }
```

**Comment by victorSenia** [comment]
From this code id is present only in `Inner_2 `(I think I rename then wrong and `Outer `must be `Inner_2`)
If you remove `Controller2 `then `id` will appears at Inner_1 and `Inner_2 `will be removed.

**Comment by dilipkrish** [comment]
@victorSenia This is a known issue. Most likely whats happening is that because of the Readable/Writable properties being loaded, depending on the context of one of the Inner_N objects being either part of the request or response, we might find some properties missing. 

We try to merge the Request view of properties with the Response view of properties so that you don't see this issue for the most part. However if you have that in a setup like yours, you'll find certain properties missing depending on how the models are loaded.

We're looking to solve this problem more intelligently, but thats not in this release.
