### ISSUE TITLE
Spring RepositoryRestResource tag and description

### ISSUE THREAD

**Issue by zmcode** [springfox/springfox#1929]
Hi everyone,
I am using springfox 2.7.0 and spring boot data rest.
I have set up different RepositoryRestResource repositories which are automatically exposed through rest by spring.
The springfox data rest extension handle them quite nicely, however I cannot understand how and if it is possible to globally modify the default tag and description that are assigned to a given repository.
Currently it simply says "Simple Jpa Repository" for each one of them and I would like to change it to a custom description.
Thank you for your help and for this really great library.

**Comment by fquinner** [comment]
Yeah you can do something like this for configuring the tags:

```
    @Bean
    public Docket restApi(ServletContext servletContext) {
        return new Docket(DocumentationType.SWAGGER_2)
                .tags(new Tag("Tag1", "Description for tag 1"))
                .tags(new Tag("Tag2", "Description for tag 2"));
    }
```

And then refer to the tag alongside the RepositoryRestResource annotation:

```
@Api(tags = "Tag1")
@RepositoryRestResource
```

**Comment by zmcode** [comment]
@fquinner Thank you very much, it worked, although I had to overwrite the default tag name otherwise it will still keep showing up.

**Comment by dilipkrish** [comment]
@fquinner thanks!

**Comment by ceefour** [comment]
@fquinner @zmcode How about supporting the built-in `collectionResourceDescription` ? So that use of custom tags is not needed.

```java
@RepositoryRestResource(
        collectionResourceDescription =
            @Description("Countries of the world"))
```

**Comment by dilipkrish** [comment]
@ceefour thanks for the suggestion.

**Comment by EugenMaysyuk** [comment]
@ceefour your approach doesn't work.

At least not with the springfox-data-rest:3.0.0-SNAPSHOT.
