### ISSUE TITLE
io.springfox:springfox-swagger2:2.7.0 doesn't pull io.springfox:springfox-swagger2 jar

### ISSUE THREAD

**Issue by yapith** [springfox/springfox#1930]
Library: springfox-swagger2:2.7.0
Repository: https://jcenter.bintray.com/ 
From my gradle build log:
Download https://jcenter.bintray.com/io/springfox/springfox-swagger-ui/2.7.0/springfox-swagger-ui-2.7.0.pom
Download https://jcenter.bintray.com/io/springfox/springfox-spring-web/2.7.0/springfox-spring-web-2.7.0.pom
Download https://jcenter.bintray.com/io/springfox/springfox-spi/2.7.0/springfox-spi-2.7.0.pom
Download https://jcenter.bintray.com/io/springfox/springfox-core/2.7.0/springfox-core-2.7.0.pom

Bug Report:
Notice springfox-swagger2.jar doesn't get pulled

I then went back to redownload springfox-swagger2 2.6.1 from the same repository with the same result -- doesn't include springfox-swagger.jar. I used to work with springfox-swagger2 2.6.1

I found a stackoverflow post asking about the same issue:
https://stackoverflow.com/questions/44506883/cant-find-enableswagger-annotation/45178483#45178483

Downloading via mvn dependency to https://repo.maven.apache.org includes springfox-swagger2-2.7.0.jar

**Comment by yapith** [comment]
Human error

**Comment by wxjlibra** [comment]
experienced with the same issue. pull but could not see the path for the cached dependencies in m2. very annoyed..how should I do now.

**Comment by dilipkrish** [comment]
@wxjlibra what are you looking for. The dependencies should just work as it is.

**Comment by VravikumarV** [comment]
I am facing the same issue and its not able to pull springfox-core-2.7.0.jar with required classes like RequestHandlerSelectors, PathSelectors etc...

**Comment by dilipkrish** [comment]
No idea. Its an environmental issue
