### ISSUE TITLE
spring security default login logout api not showing

### ISSUE THREAD

**Issue by bluewayll** [springfox/springfox#1931]
Hello,

spring security default login logout api not showing in the swagger docs

my conf :

```java
        @Bean
	public Docket productApi() {
		return new Docket(DocumentationType.SWAGGER_2).select()
				.apis(RequestHandlerSelectors.any()).paths(PathSelectors.any())
				.build().securitySchemes(Lists.newArrayList(apiKey()))
				.apiInfo(apiInfo());

	}
```

**Comment by dilipkrish** [comment]
I don't think those are request mappings (not sure, just guessing) that may be why. You can add it manually.

**Comment by bluewayll** [comment]
how can i add it manually ?

**Comment by dilipkrish** [comment]
Like [this](http://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin)

**Comment by bluewayll** [comment]
please where to put that ? with the swagger conf file ?

**Comment by dilipkrish** [comment]
You need to create a `ApiListingScannerPlugin` spring bean as shown above.
