### ISSUE TITLE
BasePathAwareController docs aren't base path aware

### ISSUE THREAD

**Issue by fquinner** [springfox/springfox#1932]
Please take the time to search the repository, if your question has already been asked or answered.

- [2.7.0] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful. 

I have a project which uses both spring data rest and custom controllers for overrides. To keep the base path spring configuration aware, I use the `@BasePathAwareController` annotation:

```
@RestController
@BasePathAwareController
@Api(tags = "banana", description = "Banana Controller")
public class BananaController {

    @PostMapping("/banana")
    public Banana create(@RequestBody Resource<Banana> entity) throws Exception {
        return null;
    }

    @PutMapping("/banana/{id}")
    public Banana update(@PathVariable Long id, @RequestBody Resource<Banana> entity) throws Exception {
        return null;
    }

    @DeleteMapping("/banana/{id}") // Define mappings at method levels only
    public void delete(@PathVariable Long id) throws Exception {
    }
}
```

Meanwhile i have the spring rest prefix set to `/api` so this will expose the resources over `/api/banana/*` and the repository resources with your wonderful `SpringDataRestConfiguration` class detects this fine, but these custom controllers do not, and instead are registered in the documentation relative to `/`.

Also the spring data rest configuration does not seem to honour the `@RestResource(exported = false)` annotation and continues to document it even though export of all duplicate resources has been disabled.

**Comment by drenda** [comment]
Hi @fquinner, I found your reference to `@RestResource(exported = false)` not working. Do you know if there are bugs opened for this issue? Thanks

**Comment by fquinner** [comment]
I think this issue *is* the opened bug.

**Comment by drenda** [comment]
Oh, I din't realize that ;-) I've the same problem with the version 2.7.1-SNAPSHOT. My methods annotated with `@RestResource(exported = false)` are still visible in Swagger.

I hope it will be fixed. Thanks

**Comment by drenda** [comment]
@fquinner Thanks. The workaround works fine, and I agree: it's a little verbose. Thanks
