### ISSUE TITLE
Support Swagger's "allOf"

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#1933]
Does Springfox support Swagger's "allOf" ?

[Composition and Inheritance (Polymorphism)](https://swagger.io/specification/#composition-and-inheritance--polymorphism--83)

Swagger allows combining and extending model definitions using the allOf property of JSON Schema, in effect offering model composition. allOf takes in an array of object definitions that are validated independently but together compose a single object.

**Comment by raderio** [comment]
As I understand this is not supported yet https://github.com/springfox/springfox/pull/1152

**Comment by dilipkrish** [comment]
There is a plan to support some of it (not allOf) in 2.8.0. Poor pun I know 😳

On a serious note there is going to be support for atleast the following
- different request/response properties based on same Class/Type
- Models belonging to the different packages with the same Class name
- JsonView support #563 
- Projection support for spring-data-rest projections 
- May be some form of inheritance support (not sure).

**Comment by ssozonoff** [comment]
Its such a basic requirement however amazed that there has not been more push for it.

**Comment by dilipkrish** [comment]
@ssozonoff Basic, possibly, but its not easy to describe such a type in Java IMO. Just curious, would love for you to share the syntax of the request mapping that would produce a parameter with `allOf`.

**Comment by raderio** [comment]
@dilipkrish what do you think about
```
@ApiModel(discriminator = "type", subTypes = {Cat.class, Dog.class})
public class Animal {
}

@ApiModel(parent = Animal.class)
public class Cat extends Animal {
}

@ApiModel(parent = Animal.class)
public class Dog extends Animal {
}
```

**Comment by dilipkrish** [comment]
@raderio that is an example of inheritance.

**Comment by raderio** [comment]
My bad, I mean "oneOf".
