### ISSUE TITLE
swagger-resources returns an unexpected object, prompts error in springfox.js

### ISSUE THREAD

**Issue by drewctaylor** [springfox/springfox#1934]
In my application, when I attempt to access http://localhost:8080/api/swagger-ui.html, the page shows the following message:

> Can't read swagger JSON from http://localhost:8080/apiundefined

Upon investigation, it appears that in springfox.js, this function:
```
  function initializeBaseUrl() {
    var relativeLocation = springfox.getBaseUrl();

    $('#input_baseUrl').hide();

    $.getJSON(relativeLocation + "/swagger-resources", function(data) {

      var $urlDropdown = $('#select_baseUrl');
      $urlDropdown.empty();
      $.each(data, function(i, resource) {
        var option = $('<option></option>')
            .attr("value", maybePrefix(resource.location, relativeLocation))
            .text(resource.name + " (" + resource.location + ")");
        $urlDropdown.append(option);
      });
      $urlDropdown.change();
    });
}
```

Expects that the call to "http://localhost:8080/api/swagger-resources/" to return an array of objects, each of which should have a location property; however, in my case, it returns the following:

```
{
    "swagger-resources": [
        {
            "name": "default",
            "location": "/v2/api-docs",
            "swaggerVersion": "2.0"
        }
    ]
}
```

It appears that this object has a property ("swagger-resources") with the expected array of objects. Is this a bug, or have I misconfigured my application and caused the "swagger-resources" endpoint to incorrectly format its response?

I'm using springfox 2.7.0; maven dependencies:

```
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.7.0</version>
        </dependency>
```

**Comment by dilipkrish** [comment]
You may need to refresh you browser cache.

**Comment by dilipkrish** [comment]
If your app responds to the following urls with valid json then you should be all set. It is possible that your browser is caching a version of the swagger-ui html/js/css.
`http://localhost:8080/api/swagger-resources/`
`http://localhost:8080/api/swagger-resources/configuration/security`
`http://localhost:8080/api/swagger-resources/configuration/ui`

**Comment by drewctaylor** [comment]
Clearing the cache did not have any effect. Those URLs do return valid JSON:

```
{
    "swagger-resources": [
        {
            "name": "default",
            "location": "/v2/api-docs",
            "swaggerVersion": "2.0"
        }
    ]
}
```

```
{
    "apiKeyVehicle": "header",
    "scopeSeparator": ",",
    "apiKeyName": "api_key"
}
```

```
{
    "docExpansion": "none",
    "apisSorter": "alpha",
    "defaultModelRendering": "schema",
    "supportedSubmitMethods": [
        "get",
        "post",
        "put",
        "delete",
        "patch"
    ],
    "jsonEditor": false,
    "showRequestHeaders": true
}
```

Is the object returned by the "swagger-resources" URL in the expected format? It doesn't seem like it can be, given what the swingfox.js seems to expect.

**Comment by dilipkrish** [comment]
That seems [correct](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/springfox.js#L42-L48). What happens when you use `http://localhost:8080/swagger-ui.html` as the url?

**Comment by drewctaylor** [comment]
Without the context path, (no `/api/`), I receive a 404. However, with the context path (`http://localhost:8080/api/swagger-ui.html`), I receive a page with the swagger header and this message:

`Can't read swagger JSON from http://localhost:8080/apiundefined`

From debugging, I see that when the system calls `maybePrefix`, `location` is `undefined` and `withRelativePath` is `http://localhost:8080/`, so the result of the operation is `http://localhost:8080/apiundefined`.

The reason that `location` is `undefined` appears to be because the code in `initializeBaseUrl` expects `http://localhost:8080/api/swagger-resources/` to return an _array of objects_ with the properties `location` and `name`, but instead, that URL returns an _object that contains an array of objects_, and as a result, when the code attempts to access the `location` property, it receives `undefined`.

That's why I'm wondering if the `swagger-resources` URL is returning the expected result.

**Comment by dilipkrish** [comment]
You are correct in your observation that it should return an array of swagger resources. But it is returning an object with an array of swagger resources. I would check how you've got your ObjectMapper configured.

**Comment by drewctaylor** [comment]
Ok - when I have it configured correctly, should it return the following from the `swagger-resources` URL:

```
    [
        {
            "name": "default",
            "location": "/v2/api-docs",
            "swaggerVersion": "2.0"
        }
    ]
```

**Comment by dilipkrish** [comment]
Yup. It seems like your object mapper is configured to wrap.

**Comment by KingNight2014** [comment]
Hey, i am in trouble, need help.
when i use swagger2 with springboot  application based on version 2.7.0 or 2.6.1, it doesn't show the api list in my browser.
as you mentioned below: 

**http://localhost:8080/api/swagger-resources/
http://localhost:8080/api/swagger-resources/configuration/security
http://localhost:8080/api/swagger-resources/configuration/ui**

the first request response is always empty, another two url response correct. 

so  what't wrong ? please help...


the below is my code:
`@Configuration
@EnableSwagger2
@EnableConfigurationProperties({SwaggerProperties.class})
public class SwaggerAutoConfiguration {
    public SwaggerAutoConfiguration() {
    }

    @Bean
    public Docket createRestApi(SwaggerProperties swaggerProperties) {
        return (new Docket(DocumentationType.SWAGGER_2)).apiInfo(this.apiInfo(swaggerProperties)).select().apis(RequestHandlerSelectors.basePackage(swaggerProperties.getBasePackage())).paths(PathSelectors.any()).build();
    }

    private ApiInfo apiInfo(SwaggerProperties swaggerProperties) {
        return (new ApiInfoBuilder()).title(swaggerProperties.getTitle()).description(swaggerProperties.getDescription()).termsOfServiceUrl(swaggerProperties.getTermsOfServiceUrl()).contact(new Contact(swaggerProperties.getContactName(), swaggerProperties.getContactUrl(), swaggerProperties.getContactEmail())).version(swaggerProperties.getVersion()).license(swaggerProperties.getLicense()).licenseUrl(swaggerProperties.getLicenseUrl()).build();
    }
}`


@EnableDiscoveryClient
@SpringBootApplication
@EnableTransactionManagement
public class Application extends SpringBootServletInitializer {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}

@dilipkrish

**Comment by dilipkrish** [comment]
I think its creating the resources in a different application context. Here is something to try.. move the `@EnableSwagger2` annotation to your application class and see if that helps. Also please move to 2.9.2 since that is the latest supported version.
