### ISSUE TITLE
configuration for adding dynamic api-key(access token value).

### ISSUE THREAD

**Issue by akashgupta08** [springfox/springfox#1936]
I need to provide a access token on the swagger-ui page  so that all the request can be authenticated.

I have implemented the following.

>  @Bean
>  SecurityConfiguration security() {
>   return new SecurityConfiguration(null, null, null, "Spring Boot Swagger", "baedeb03-5142-466e-8d8f-c0987a8078f8", ApiKeyVehicle.HEADER, "X-AUTH-TOKEN",",");
>  }

Above: I have fixed the value of X-AUTH-TOKEN value, I want this to be added with swagger ui, whenever user testing the api.

Any suggestion would be of great help.

**Comment by dilipkrish** [comment]
It should work, Is it not working? what version of springfox are you using?

**Comment by akashgupta08** [comment]
This is working , you see I have hardcoded the value of "X-AUTH-TOKEN: baedeb03-5142-466e-8d8f-c0987a8078f", **I want this value to be entered by tester like from swagger-ui**,
btw I am using 2.7.0 for both.

**Comment by dilipkrish** [comment]
We'll have that when we do the 3.x swagger-ui migration.

**Comment by akashgupta08** [comment]
any expected date for availability of 3.x swagger-ui.

**Comment by dilipkrish** [comment]
None yet. Looking for contributions.

**Comment by dilipkrish** [comment]
This is fixed via upgrade to swagger 3.x (#2153)
