### ISSUE TITLE
@ModelAttribute with getters and no setters

### ISSUE THREAD

**Issue by bademux** [springfox/springfox#1937]
@ModelAttribute param name depends on setter method, eg.

```java
class MyPojo{
 private String testProperty;
 public void setBoomProperty(String testProperty){
   this.testProperty = testProperty;
 }
}
```
for  @ModelAttribute  MyPojo myPojo Springfox will generate *testProperty* attrubute, but boomProperty will be used by Spring

see for more info org.springframework.beans.BeanWrapperImpl.BeanPropertyHandler#setValue

**Comment by dilipkrish** [comment]
What version are you using of springfox? This is fixed in 2.7.0

**Comment by bademux** [comment]
@dilipkrish thanks for updating title, here the part of my build.gradle
```groovy
    compile('io.springfox:springfox-swagger2:2.7.0')
    compile('io.springfox:springfox-bean-validators:2.7.0')
    compile('io.springfox:springfox-swagger-ui:2.7.0')
```

**Comment by dilipkrish** [comment]
@bademux could you create a [breaking test perhaps](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java)?

**Comment by bademux** [comment]
sorry for delay
<details> 
  <summary>Sample App, see TestPojo::setTest_prop2</summary>
```java
@SpringBootApplication
@EnableSwagger2
@RestController
public class DemoApplication {

    public static void main(String[] args) { SpringApplication.run(DemoApplication.class, args); }

    @GetMapping("/test") public void test(TestPojo testPojo) { }

    @Bean public Docket api() { return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any()) .paths(PathSelectors.any()) .build(); }
}

class TestPojo {
    private String testProp1;
    private String testProp2;

    public String getTestProp1() {return testProp1;}
    public void setTestProp1(String testProp1) {this.testProp1 = testProp1; }

    public String getTestProp2() {return testProp2; }
    //expecting test_prop2 query param
    public void setTest_prop2(String testProp2) {
        this.testProp2 = testProp2;
    }
}
```
</details>

**Comment by bademux** [comment]
as per https://github.com/springfox/springfox/issues/1219 ``` @ModelAttribude ``` approach is broken in 2.7.0.
It seems that Springfox requires to have the property and the getter method with the same name, eg.
```java
class Test{
 String test;
 void getTest(){}
}
```
imho, 
geter should be enough, as Spring itself operates on setter\getter.

How about handling ``` @ApiParam ``` for getter? From my understanding it allows to override parameterType (query\formData ...)

**Comment by dilipkrish** [comment]
@bademux thanks for the example! 🤘

**Comment by dilipkrish** [comment]
@bademux This is a bit involved. Im going to move this back so that I can release 2.8.0 shortly. Sorry for the delay

**Comment by dilipkrish** [comment]
I pushed an update to fix this issue. Would be awesome to get your feedback using 2.8.1-SNAPSHOT
