### ISSUE TITLE
Inconsistent behaviour of (Docket)directModelSubstitute

### ISSUE THREAD

**Issue by abelsromero** [springfox/springfox#1938]
v 2.6.1

Using  `directModelSubstitute` to replace the examples of a class with a custom serialization does not work equally across all elements in the generated site.

- When applied to a class (e.g. `directModelSubstitute(Myclass.class, Mysubstitute.class)` ), and when the class is part of an attribute of type List of another class, `[null]` is shown in the examples. When the class (Myclass) is a direct input parameter, no substitution is applied, `MyClass` properties are shown.

- When applied to an array (e.g. `directModelSubstitute(Myclass[].class, Mysubstitute[].class)` ), substitution is successfully applied and shown (no null), but only for examples where List<MyClass> is the output of a rest service. No substitution is applied when List<MyClass> is an attribute of another class.

- When both are applied, the first scenario applies. No proper substitution happens in any case.

**Comment by dilipkrish** [comment]
@abelsromero The substitution is explicit and naive if you will. 

For e.g. If you have `MyClass` the papers in generics like `List<MyClass>` or `Map<String, MyClass>` you need to define that rule explicitly as well.

**Comment by abelsromero** [comment]
Thanks a lot for the answer, but I don't get it.

> For e.g. If you have MyClass the papers in generics like List<MyClass> or Map<String, MyClass> you need to define that rule explicitly as well.

But generics use erasure and are not preserved at runtime right? It's not possible to do something like this `directModelSubstitute(List<MyClass>.class, List<Mysubstitute>.class)`.
And even if possible, the type is removed.

Also, what about the other cases, like:


> When the class (Myclass) is a direct input parameter, no substitution is applied, MyClass properties are shown.

This seems to be a bug, or maybe some other API affecting swagger :/

**Comment by dilipkrish** [comment]
Have you looked at [`genericModelSubsitutes` and `alternateTypeRules`](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) see `<9>` and `<10>`

**Comment by adrianmsmith** [comment]
I think it would make sense to extend Springfox to make the method `directModelSubstitute` deep? (feature request)

I cannot think of a case where you want e.g. `LocalDateTime` to be rendered as `String` in the Swagger JSON, but you don't want `List<LocalDateTime>` to be rendered as `List<String>`?

**Comment by dilipkrish** [comment]
@adrianmsmith That is true. The extensibility point available to do that is [AlternateTypeRuleConvention](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/schema/AlternateTypeRuleConvention.java).

**Comment by vijays2017** [comment]
Hi, if I have something like below 

interface Message <T> 
{
 T payload()
}

interface B {
...some props 
}

interface C {
Message <B> myMethod()
} 
Any how can I setup the Docket object() ?

**Comment by vijays2017** [comment]
btw my input from Swagger is C

**Comment by vijays2017** [comment]
I have something like 

public interface pmtIs{
    String id();

  //  @JsonProperty("paymentTxns")
    @ApiModelProperty(value = "Sample transactions", dataType = "java.util.List")
    List<PaymentTransaction> paymentTxns();

} 

How can I get List <PaymentTxns) input ?


    public Docket provideSwaggerApiDocket() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build()
                .additionalModels(typeResolver.resolve(List.class,
                        ImmutablePaymentTransaction.class))
                .alternateTypeRules(
                AlternateTypeRules.newRule(
                        typeResolver.resolve(List.class,
                                typeResolver.resolve(List.class, ImmutablepmtIs.class)),
                        typeResolver.resolve(List.class, ImmutablepmtIs.class),
                        Ordered.HIGHEST_PRECEDENCE));
        }
