### ISSUE TITLE
@RequestParam(required = false) ignored?

### ISSUE THREAD

**Issue by rtomsick** [springfox/springfox#1939]
Description
---

It appears that the `required` property of Spring's `RequestParam` is ignored.  As the raison d'être for `springfox` is to help automate the generation of API documentation, ignoring this information if it's available seems to be a bug.

Steps to reproduce
---
1. Annotate controller method with something like the following:

```java

@RequestMapping(value = "/auth",
	method = RequestMethod.GET,
	produces = "application/jwt")
@ApiOperation(value = "authenticate a user using a given set of "
			+ "credentials, producing a JWT token that may be "
			+ "used for future API operations if successful",
	response = Jwt.class)
@Valid
public ResponseEntity<String>
authenticate(@RequestParam("username") 
			String username, 
		@RequestParam("password") 
			String password, 
		@RequestParam(required = false, name = "credential-source-id") 
			String credentialSourceID)

```

2. Set up project to generate documentation

Expected outcome
---
Documentation for the endpoint is created, denoting the `username` and `password` request parameters as mandatory, and the `credential-source-id` parameter as optional.

Actual outcome
---
All three parameters appear to be optional.

Workaround
---
Manually specifying `required=true` in the `@RequestParam` annotations has no effect.

Add `@ApiParam` annotations to the required parameters, setting `required=true` within.  This appears to produce the desired results.

Environment
---
* `io.springfox:springfox-swagger2:2.7.0`
* Project derived from `org.springframework.boot:spring-boot-starter-parent:1.5.4.RELEASE`
* Java 8
* documetnation viewed in `swagger-ui` revision `febd5ff`

Please let me know if you need further information.  Thanks!

**Comment by rtomsick** [comment]
So I'm confused.  You marked it as not-reproducible, yet tagged it for 2.8.0... so... is it a bug or not?

**Comment by dilipkrish** [comment]
Its tagged as 2.8.0 so that people (including me) that comments on this question have context of the version this question is reported on. For e.g. it might've been reproducible in 2.7.0 but it is not reproducible in 2.8.0 snapshot builds. Hope that clarifies. Its a way to keep this issue tracker sane for me to manage.

**Comment by rtomsick** [comment]
OK, got it.  Thanks.

**Comment by wusthuke** [comment]
springfox-bean-validator @NotNull also not work,  when 2.8.0 will release?

**Comment by dilipkrish** [comment]
@wusthuke trying to wrap up the remaining issues. Hopefully in the next couple weeks

**Comment by BJSS-JD** [comment]
Hi, I'm facing the same issue with the JDK8.
