### ISSUE TITLE
@Api#description deprecated with no working replacement?

### ISSUE THREAD

**Issue by rtomsick** [springfox/springfox#1940]
`@Api#description` has been deprecated.  Fair enough.

But there appears to be no usable replacement for adding a description for a controller.

`@ApiModel#description` is not used for this purpose.

And the following seems to be ignored:

```java
@SwaggerDefinition(tags = {
	@Tag(name = "foo", description = "some description of foo controller")
})
public class FooController
{/* ... */}
```

Given the above, what is the "correct" way to do this?  (Right now `@Api#description` works fine and is, in fact, used contrary to the documentation!  So for the time being I'll use that...)

IMHO there is at least one bug here (that the documentation for `@Api#description` claims it's not used, but it is), and possibly a second if descriptions have been deprecated with no replacement.

Tested against 2.7.0

Thanks!

**Comment by dilipkrish** [comment]
The springfox-way if you will is to do the following on the controller.

`@Api(tags={"foo"})`

[In your docket](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L415-L426) you can add tags and descriptions for them. This is the equivalent of the `SwaggerDefinition` annotation.

**Comment by rtomsick** [comment]
OK, that makes sense.  Not the way I'd do it, but fair enough.

That said, perhaps some JavaDoc improvement for `@Api#description` is in order to 1) point out that it is still functional, despite being deprecated and 2) that one should use `tags` and `Docket` to accomplish the same.

Thanks.

**Comment by dilipkrish** [comment]
Would be much appreciated if you could [update the docs](https://github.com/springfox/springfox/tree/master/docs/asciidoc), a PR perhaps!

**Comment by rtomsick** [comment]
No thanks.  I don't have time to maintain the library.

**Comment by dilipkrish** [comment]
Wasn't asking help to maintain the library. 😃 Just seeing if you can help edit the docs/markdown to  as you saw fit. Its also an area we need help and a great way to help folks just like yourself.

**Comment by nikhil4326** [comment]
In swagger-core package, they mentioned to use @SwaggerDefinition instead of @API description. I dont see any changes in json or HTML . Is springfox supporting new tag? or is there any way to add description (without tags)

**Comment by dilipkrish** [comment]
Please youse @Api#tags and @Api#description for that.
