### ISSUE TITLE
swagger-ui does not remove java string escape char "\" from @ApiModelProperty example

### ISSUE THREAD

**Issue by heapifyman** [springfox/springfox#1941]
Using version 2.7.0 of springfox-swagger2 and springfox-swagger-ui with spring-boot 1.5.4.RELEASE

I have defined some example value in `@ApiModelProperty` like this
```java
@ApiModelProperty(example = "{\"name\": \"foo\", \"age\": 42}")
```
as part of a model for a body param.

The escape chars `\` are kept in swagger-ui's `Example Value`, so that when clicking on it to paste the `Example Value` into body param value for testing the REST endpoint, the escape chars `\` are still included - thus transmitting invalid JSON to the endpoint.

**Comment by dilipkrish** [comment]
I think this might be a [Swagger-ui](https://github.com/swagger-api/swagger-ui) issue

**Comment by heapifyman** [comment]
@dilipkrish [swagger-ui](https://github.com/swagger-api/swagger-ui) team says, it's a springfox issue:
https://github.com/swagger-api/swagger-ui/issues/3465#issuecomment-318174407

The `example` string from

```
@ApiModelProperty(example = "{\"name\": \"foo\", \"age\": 42}")
```
is indeed passed as is to `springfox.documentation.schema.ModelProperty` and then to `io.swagger.models.properties.Property`.

In my case, I am trying to provide an example for a property, which is a `Map<String, AnotherObject>`.
Maybe there is some other way to achieve this than by  using `@ApiModelProperty`'s `example`?

**Comment by heapifyman** [comment]
@dilipkrish I was looking into springfox code and to workaround my problem I think I could register a custom JSON serializer via MixIn, like it is done in `springfox.documentation.swagger2.configuration.Swagger2JacksonModule`.

The [springfox documentation](https://springfox.github.io/springfox/docs/current/#configuring-the-objectmapper) says I could do that by implementing `ApplicationListener<ObjectMapperConfigured>`.

I tried that and called
```
event.getObjectMapper().addMixIn(Property.class, CustomPropertySerializer.class);
```
on it.
But unfortunately, my CustomPropertySerializer's `serialize` method is never called ...
Any idea what I might be doing wrong?

I verified, that when I add the CustomPropertySerializer in `springfox.documentation.swagger2.configuration.Swagger2JacksonModule` itself and then build my own springfox-swagger2 jar, the `serialize` method gets called and output looks like I want it to be.
However, doing that does not seem to be very flexible if I or someone else wants to change the serializer later on.

**Comment by heapifyman** [comment]
I finally ended up with providing my own `JacksonModuleRegistrar` bean, annotated with `@Primary`.
The bean is a custom `Swagger2JacksonModule`, which overrides `setupModule` method with:

```
@Override
public void setupModule(SetupContext context) {
    super.setupModule(context);
    context.setMixInAnnotations(Property.class, CustomPropertySerializer.class);
}
```

I'm not sure if that is the "correct" way to do it (it does not feel quite right), but was the only way to get it working.

BTW, is there a reason why `Swagger2JacksonModule`'s `maybeRegisterModule` calls
```
objectMapper.registerModule(new Swagger2JacksonModule());
```
instead of
```
objectMapper.registerModule(this);
```
?


If it had used the latter, I wouldn't have had to copy the method to my custom `Swagger2JacksonModule`

**Comment by dilipkrish** [comment]
@heapifyman would be of great help if you could help fixing this issue in the library. Seems like a real issue regardless of what swagger team says. Any chance you might be able to help?

**Comment by heapifyman** [comment]
@dilipkrish I can try to help, yes

**Comment by aadarshsingh191198** [comment]
I am using using `springfox-boot-starter:3.0.0` and see the same bug while using `ApiParam` annotation. Was the bug fixed only for `@ ApiModelProperty `?

**Comment by aadarshsingh191198** [comment]
@heapifyman @dilipkrish any help or direction on the same would be great!

**Comment by bekirtaskin** [comment]
> I am using using `springfox-boot-starter:3.0.0` and see the same bug while using `ApiParam` annotation. Was the bug fixed only for `@ ApiModelProperty `?

I am facing same issue with version 3.0.0 and `@ ApiModelProperty ` :(

**Comment by MissakaI-ObjectOne** [comment]
It is the same with new `@Schema` annotation too. It won't resolve the escaped characters.
I think we will have to reopen this for version 3.x.x
