### ISSUE TITLE
@ApiResponse(... response = Void.class) produces empty model, (... response = void.class) does not

### ISSUE THREAD

**Issue by rtomsick** [springfox/springfox#1944]
Given the code below, I would like to know if what I'm seeing is the correct behavior:

```java
@ApiResponses({
	@ApiResponse(code = 404, message = "No object was found with the given ID"),
	@ApiResponse(code = 200, message = "The object was deleted successfully.",
			response = Void.class)
})
public ResponseEntity<?>
delete(@PathVariable("id") int id)
```

I would expect for the 200 response to not show a model of any sort when the resulting documentation is viewed in `swagger-ui`.  

Instead, it appears to have a model, however the model is `{}`, an empty object.

As this is not what the API produces (it does not send anything as a response body on success) I believe that this is wrong.

I thought this was the "correct" way to do this according to #1750, no?

Thanks!

**Comment by rtomsick** [comment]
Solved, sort of.

`Void.class` produces an empty model.  `void.class` omits it.

There is no way that this is intentional, right?   I'm assuming not, so I'm leaving this open as a bug.

**Comment by dilipkrish** [comment]
That is an oversight. Thanks for catching that.

**Comment by dilipkrish** [comment]
The other way to solve this is to change the return value to `ResponseEntity<Void>`

**Comment by dcp65** [comment]
I am seeing something similar to this in Kotlin using Springfox 2.9.0.

I have the following POST API that does not expect a response body:

```
@ResponseStatus(CREATED)
    fun sendFoo(@RequestBody foo: Foo) {
        fooApiService.save(foo, session.id)
    }
```

 I have tried the following:

```
@ApiResponses(
     ApiResponse(code = 201, message = "Created", response = Void::class)
    )
```

```
@ApiResponses(
     ApiResponse(code = 201, message = "Created", response = Unit::class)
    )
```

and 

```
@ApiResponses(
     ApiResponse(code = 201, message = "Created", response = Nothing::class)
    )
```

However, the generated `swagger.json` shows this for the API:

```
"produces": [
                    "*/*"
                ]
```

Any suggestions?

**Comment by prabhushrikant** [comment]
This is still creating empty model in swagger ui `{}` when I specify 
`@ApiResponse(code = 204, message = MESSAGE_204, response = Void.class)
@ResponseStatus(HttpStatus.NO_CONTENT) //avoids producing default 200 documentation.
@RequestMapping(value = "/new-privilege", method = RequestMethod.POST)
public ResponseEntity<?> createPrivilege() { ... }`

**Comment by asnewman** [comment]
Still an issue in 2.9.1

**Comment by mayureshharsha** [comment]
> This is still creating empty model in swagger ui `{}` when I specify
> `@ApiResponse(code = 204, message = MESSAGE_204, response = Void.class) @ResponseStatus(HttpStatus.NO_CONTENT) //avoids producing default 200 documentation. @RequestMapping(value = "/new-privilege", method = RequestMethod.POST) public ResponseEntity<?> createPrivilege() { ... }`

@prabhushrikant use void.class and not Void.class

**Comment by pavelkryl** [comment]
Does this work also for swagger maven plugin? I guess not, because there is no such thing like 'void.class'. Could you please provide fully qualified name of such **void**? In std Java there is only Void.class. If it should be there, you should fix maven dependencies to have it on classpath automatically.
