### ISSUE TITLE
@ApiParam behavior wrong when used w/ @PathVariable

### ISSUE THREAD

**Issue by rtomsick** [springfox/springfox#1945]
Given the following example:

```java
@RequestMapping(value = "/{id}/foo",
		method = RequestMethod.DELETE)
public ResponseEntity<?>
delete(@PathVariable("id")
	@ApiParam("ID of the object to delete") 
	int id)
```

One would expect the ID parameter to be marked as required, as there is no logical way to omit a path segment (since doing so would result in a different path not handled by this controller method.)

It is not.

Instead, it is considered optional as long as `@ApiParam` is present.  If `@ApiParam` is omitted, the parameter is once again seen as required.

This is in _direct contradiction_ to the documentation of `@ApiParam#required`, which states: "Path parameters will always be set as required, whether you set this property or not."   

Tested against 2.7.0

**Comment by dilipkrish** [comment]
The springfox plugin system requires explicit configuration of these properties to work correctly. This issues #1371, #1231 go into more detail but [here is an explanation](https://github.com/springfox/springfox/issues/1231#issuecomment-219332782) of why its designed that way (and deviates from the annotation behavior)

**Comment by rtomsick** [comment]
So this kinda gets into a recurring issue with `springfox`: that lots of stuff is either documented incorrectly, incompletely, or not at all.  It's frustrating to know that something is possible in theory, but to have to trawl through the issue tracker trying to find someone with a similar problem and infer a solution from there.

In this case, even after reading the above, I am __still__ not sure of the answer to my original question: how do I get `springfox` to actually behave like it claims it does and understand required parameters without requiring me to re-annotate them?!

Sorry to vent a bit here, but this has been the third or fourth time where I've run into this with `springfox`. It's more than a little irritating to wonder how to do something, read the documentation, find it either doesn't mention it or specifies something that doesn't actually work, and then find out "oh, well if you had read through the magic bug #, you'd know that it *actually* requires you to do <completely non-obvious thing> instead"  Add this to the complete lack of JavaDoc on many classes, and I hope you can appreciate why using this library has been an exercise in frustration.

**Comment by dilipkrish** [comment]
> It's frustrating to know that something is possible in theory, but to have to trawl through the issue tracker

Apologies, I should do a better job at documentation. Pointing folks to issues is not really a solution as you've pointed out. I do try to go back to such issues by marking them `can-use-for-documentation` and getting back to documenting it. However I don't have the bandwidth. Really do rely on good samaritans to help improve it. 

Would you mind outlining all the things you're having trouble with and I can see if I can make the documentation better around those areas.
