### ISSUE TITLE
Make ApiParam#required optional

### ISSUE THREAD

**Issue by ScienJus** [springfox/springfox#1948]
# What version of the library are you using? 

2.7.0(the latest version)

# What kind of issue is this?

Feature Request

# Details

When i use springfox with spring mvc, i want to add some description to parameters, so i uses `@ApiParam` like:

```
@ApiParam(value = "current user id")
@RequestParam(value = "user_id")
long userId,
```

By default, `RequestParam#required` is `true`. so this param is required. but `ApiParam#required` is `false` and it has the highest priority.

I know i can explicitly specifies `ApiParam#required` to be `true`, but i think it will be better to make `ApiParam#required` optional. if it doesn't have a definite value. we can ignore it and uses value from other plugins like spring mvc.

Maybe it is hard because annotation's field can not be `null`, so we have to define a enum like `DEFAULT/OPTIONAL/REQUIRED`.

**Comment by dilipkrish** [comment]
Please use `@Description` spring annotation instead.

**Comment by ScienJus** [comment]
Thanks

**Comment by ScienJus** [comment]
@davidnewcomb `org.springframework.context.annotation.Description` can not used on a Parameter.

**Comment by inad9300** [comment]
Yes, could you please be more specific on how to use the `@Description` annotation?
