### ISSUE TITLE
Document support customized  param using HandlerMethodArgumentResolver

### ISSUE THREAD

**Issue by neil4dong** [springfox/springfox#1950]
Hi folks ,Is there any way to Show the JSON model and remove the form argument in blow condition?
We don't use @RequestBody for reason( CORS will need preflight request) 

```Java
public  class JSONArgumentResolver implements HandlerMethodArgumentResolver{

    @Autowired
    private Validator validator;

    @Override
    public boolean supportsParameter(MethodParameter parameter) {
        return parameter.hasParameterAnnotation(JSONParam.class);
    }

    @Override
    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {

        JSONParam parameterAnnotation = parameter.getParameterAnnotation(JSONParam.class);
        String parameterName = parameterAnnotation.value();
        String json = webRequest.getParameter(parameterName);
        Type type = parameter.getGenericParameterType();
        try {
            Object object = JSON.parseObject(json, type);
            if(object != null ){
                BindingResult bindingResult = new BeanPropertyBindingResult(object, object.getClass().getSimpleName());
                validator.validate(object, bindingResult);
                if (bindingResult.hasErrors()) {
                    if (bindingResult.hasErrors()) {
                        throw new BindException(bindingResult);
                    }
                }
            }else if(parameterAnnotation.required()){
                throw new IllegalStateException("Missing Parameter: " + parameterName);
            }

            return object;
        } catch (JSONException ex) {
            throw new HttpMessageNotReadableException("JSON parse error: " + ex.getMessage(), ex);
        }

    }

}
```

Use case
`@ApiOperation(value = "Add Rule")
@RequestMapping(value = "/add", method = RequestMethod.POST)
public RestResponse addRule(@JSONParam Rule uiRule)  {
 }`

**Comment by dilipkrish** [comment]
Why not use use it as a RequestBody? That is essentially what yourre doing. Regardless you need to write a plugin that can replace JsonParam annotated parameters with some resource model or alternately relate an alternate type rule that maps `Rule.class` to some mixin class that u know maps correctly.

**Comment by neil4dong** [comment]
I looked up the Plugin system.  It seems no way to remove the form data.   A field in Rule.class named 'ruleName' will show in the document as  ‘ruleName’ . If there has some other Nested Object or List ,it will show like "xxx[0].name" or "xxx.name", that's definitely not I want.

**Comment by dilipkrish** [comment]
@neil4dong if you use `@ApiModeProperty(hidden=true)` on the properties you wish to hide it should be hidden.

**Comment by neil4dong** [comment]
Thanks, it works.  
It will be nice if we add some extension point ,so we can deal the customized annotations since spring-mvc provide the extension point for customized parameter resolve( HandlerMethodArgumentResolver)

**Comment by neil4dong** [comment]
This could be a **feature** instead of a **question**.

**Comment by dilipkrish** [comment]
@neil4dong You can do much of this using alternate type rules already. Just needs documentation

**Comment by dilipkrish** [comment]
Added documentation via #1904
