### ISSUE TITLE
JSON PUT request with String Request Body not formatting correctly

### ISSUE THREAD

**Issue by zmacomber** [springfox/springfox#1951]
I'm using Springfox 2.7.0 to generate Swagger UI docs for my Spring REST API. All operations (GET, PUT, DELETE) are testing fine on all of my endpoints via my integration test cases. The GET requests are returning data fine via Swagger UI but PUT operations via the "Try it out!" part are failing due to how the request body is sent. I have the following signature in one of my REST API endpoints (which is typical of how my PUT endpoints are):

```
@RequestMapping(value = "/runSql", method = RequestMethod.PUT)
public ResponseEntity<String> runSql(@RequestBody String json, HttpServletRequest request)

```
When I use "Try it out!" via the Swagger UI produced by Springfox, the json request body comes in looking like this:

`"{ \"id\" : \"1234\", \"sql\" : \"select * from users\" }"`

Jackson doesn't like that json String.

How can I configure Springfox and/or Spring to process a json String correctly via the "Try it out!" section on Swagger UI?

**Comment by dilipkrish** [comment]
Swagger-ui seems to be doing the right thing by escaping the json you're sending in. It _is_ looking like a string and it _is_ escaping the quotes that are normal in json for keys.

**Comment by zmacomber** [comment]
But Jackson fails when it tries to read it.  Is this a Jackson issue then?
