### ISSUE TITLE
Swagger2 not finding Model annotations when Model is in dependent jar file

### ISSUE THREAD

**Issue by RudyBone** [springfox/springfox#1953]
I am using Swagger2 v2.7.0

I have an REST Service in which the Models used for Requests/Responses are defined in a separate jar file (so that clients can use the models when accessing the service).  I have the models annotated with ApiModel etc and in my Swagger config declaration I have an ComponentScan configuration to include the model package in the dependent jar, however the model descriptions do not show up in the UI.

Are the annotations run-time or compile time?  Any help would be appreciated

**Comment by dilipkrish** [comment]
The annotations are run-time. ComponentScanning will not automatically annotate the models. It will only annotate models that are used in the service operations.

**Comment by RudyBone** [comment]
My models ARE being used by the service operations, but their documentation is not appearing in the Swagger UI

**Comment by RudyBone** [comment]
Never mind, I'm an idiot
