### ISSUE TITLE
Multiple swagger JSON's in swagger-ui.html

### ISSUE THREAD

**Issue by dreambrother** [springfox/springfox#1954]
Hello, I have a question. Looks like springfox doesn't automatically document spring-ws endpoints (websocket). I didn't find any solution how to document it manually, so I decided to write Swagger JSON doc manually, serve it as a static content and add it to Springfox's swagger-ui.html page. I was able to do this by adding another <option> tag directly in a browser ![image](https://user-images.githubusercontent.com/1213759/28725712-f6f216aa-73c6-11e7-83d7-81e4acdcc6bd.png)
Now I want to add it in the application the code. Could you tell me how to do this? Or how to add endpoints to existing generated documentation manually? 

Thanks :)

**Comment by dilipkrish** [comment]
You need to create a bean that implements [the SwaggerResourcesProvider interface](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/SwaggerResourcesProvider.java). You'd have to make a composite bean that uses the [InMemorySwaggerResourcesProvider.java](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.java) and adds your own json file to it as well. Keep in mind you need to make this _new_ bean a `@Primary` bean.

**Comment by dreambrother** [comment]
This works! Thank you! 

```java
@Configuration
public class SwaggerWsEndpointsConfig {

    @Primary
    @Bean
    public SwaggerResourcesProvider swaggerResourcesProvider(InMemorySwaggerResourcesProvider defaultResourcesProvider) {
        return () -> {
            SwaggerResource wsResource = new SwaggerResource();
            wsResource.setName("ws endpoints");
            wsResource.setSwaggerVersion("2.0");
            wsResource.setLocation("/v2/websockets.json");

            List<SwaggerResource> resources = new ArrayList<>(defaultResourcesProvider.get());
            resources.add(wsResource);
            return resources;
        };
    }
}
```
