### ISSUE TITLE
Add support for inclusive and exclusive ranges for allowable values

### ISSUE THREAD

**Issue by JohnNiang** [springfox/springfox#1955]
The @ApiParam(allowableValue="range[1,40]") is not worked in Spring Boot.

eg:
@ApiParam(name = "page", value = "页数", allowableValues = "range[0, infinity)", allowMultiple = true) //
			@RequestParam(value = "page", required = false) Integer page, //
			@ApiParam(name = "rpp", value = "每页记录数(records per page)", allowableValues = "range[0, 40]") //
			@RequestParam(value = "rpp", required = false) Integer rpp

**Comment by dilipkrish** [comment]
Range like `range[1,40]` should work however I don't believe exclusive min/max isn't supported I believe.

**Comment by JohnNiang** [comment]
Maybe I should config the swagger more?

**Comment by dilipkrish** [comment]
There is no extra configuration. Not are what is happening that is not picking up the range

**Comment by JohnNiang** [comment]
Okay, thanks for your reply. The function is not important so far.

**Comment by dilipkrish** [comment]
Adding support for inclusive and exclusive ranges and mixed ranges.
e.g. range[1, 1]
range(1, 1)
range(infinity, infinity]
