### ISSUE TITLE
Tool to generate Swagger spec from JAR

### ISSUE THREAD

**Issue by packleader** [springfox/springfox#1959]
I'm trying to write a simple Maven plugin that will inspect a JAR file and generate a Swagger spec based on the Spring MVC endpoints in the JAR file.  That way, our team can generate the Swagger file at build time.  Springfox looks like it would be very useful for this, but I'm having a hard time getting it to work.  My biggest hurdle is that Maven plugins are not Spring containers, so I cannot count of all of the dependencies beign `@Autowire`d.  Do you feel that this an appropriate use of Springfox?  If so, can you provide some guidance on how to get started?  Thanks.

**Comment by ris58h** [comment]
@packleader, take a look at [swagger-maven-plugin](https://github.com/kongchen/swagger-maven-plugin)

**Comment by yissachar** [comment]
We were able to get build time generation working by using a test with Spring's mocks.

```
@RunWith(SpringRunner.class)
@SpringBootTest
public class GenerateSwagger {

    @Autowired
    WebApplicationContext context;

    @Test
    public void generateSwagger() throws Exception {
        MockMvc mockMvc = MockMvcBuilders.webAppContextSetup(context).build();
        mockMvc.perform(MockMvcRequestBuilders.get("/v2/api-docs").accept(MediaType.APPLICATION_JSON))
                .andDo((result) -> {
                    FileUtils.writeStringToFile(new File("swagger.json"), result.getResponse().getContentAsString());
                });

    }
}
```

This assumes that you have SpringFox set to generate the spec at runtime at the `/v2/api-docs` path, e.g. with the following config:

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }
}
```

Perhaps a slight abuse of tests, but we couldn't see another easy way to get this to work.

**Comment by dilipkrish** [comment]
@yissachar that is totally a valid technique. Infact it is the basis for how [swagger2markup](https://github.com/Swagger2Markup/swagger2markup) generates documentation and how http://www.jhipster.tech uses it.
