### ISSUE TITLE
Springfox - Authorization value didn't update after Authorize confirmed..

### ISSUE THREAD

**Issue by thomasharin** [springfox/springfox#1961]
Hi, I'm using springfox swagger2 a swagger-ui version 2.7 and I have problem with passing token to Authorization param.

I click on Authorize and after I fill authorization value and confirm by authorize button in Authorize window the token is showing, but when I make some request in header I see just default value, so "Authorization: Authorization" instead "Authorization: Bearer yeJSKA......."

**This is my Authorize window, when I fill value and click on Authorize.**

![swagger-api](https://user-images.githubusercontent.com/22837519/28826560-d6d04c00-76ca-11e7-980c-bd077aa731a7.png)

**And after I click on request in swagger ui**

![requestsending](https://user-images.githubusercontent.com/22837519/28826736-705aea42-76cb-11e7-8fd5-e0ee3214d045.png)

**In request header is still this default Authorization value**

![requestheader](https://user-images.githubusercontent.com/22837519/28827721-bae5482a-76ce-11e7-85e5-2f65d7be80f9.png)

**My swagger configuration here**
```java
@Bean
	public Docket parkingApi() {
		return new Docket(DocumentationType.SWAGGER_2)
				.select()
					.apis(RequestHandlerSelectors.any())
					.paths(paths())
					.build()
				.enable(true)
				.apiInfo(parkingApiInfo())
				.securityContexts(Arrays.asList(securityContext()))
				.securitySchemes(Arrays.asList(apiKey()))
				
				.tags(new Tag("User profile endpoint", "Use to retrieve users and logged user basic profile, or to manage basic profile of logged user."),
						new Tag("Car profile endpoint", "Use to retrieve user's car profile, or to manage them."),
						new Tag("Schedule profile endpoint", "Use to retrieve user's schedule profile, or to manage them."),
						new Tag("Card profile endpoint", "Use to retrieve user's card profile, or to manage them."),
						new Tag("All profiles endpoint", "Use to retrieve all data about logged userr."));
	}
	
	@Bean
	SecurityConfiguration security() {
		return new SecurityConfiguration(null, null, null, null, "Authorization", ApiKeyVehicle.HEADER,
				"Authorization", ",");
	}
	
	private ApiKey apiKey() {
	    return new ApiKey("Authorization", "Authorization", "header");
	  }

	  private SecurityContext securityContext() {
	    return SecurityContext.builder()
	        .securityReferences(defaultAuth())
	        .forPaths(paths())
	        .build();
	  }

	  List<SecurityReference> defaultAuth() {
	    AuthorizationScope authorizationScope
	        = new AuthorizationScope("global", "accessEverything");
	    AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
	    authorizationScopes[0] = authorizationScope;
	    return new ArrayList<SecurityReference>(){{
	        new SecurityReference("Authorization", authorizationScopes);}};
	  }
```

**And controller code here**

```java
	@ApiOperation(value = "Get user's favourite parking spaces", notes = "Retrieves user's favourite parking spaces.") 
	@GetMapping(produces = "application/json; charset=UTF-8")
	ResponseEntity<DTOFavouriteSpaces> getUserFavouriteSpaces() {
		return favouriteSpacesReader.getUserFavouriteSpaces();
	}
```

So is something that is missing in my configuration? I really don't know what is wrong.
Thanks.

**Comment by robsonhermes** [comment]
+1 up
I am having a problem that might be related. Using springfox version 2.5.0 (and spring-boot  1.5.4.RELEASE), my configuration was working fine:

```
	@Bean
	public Docket apiDocket() {
		return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).pathMapping("/v1").select()
				.apis(and(basePackage("com.package.example"), not(withMethodAnnotation(ApiIgnore.class)), not(withClassAnnotation(ApiIgnore.class)))).build()
				.securitySchemes(Lists.newArrayList(apiKey()));
	}

	private ApiKey apiKey() {
		return new ApiKey("apiKey", "Authorization", "header");
	}

	@Bean
	public SecurityConfiguration security() {
		return new SecurityConfiguration(null, null, null, "calendar-api", "Bearer", ApiKeyVehicle.HEADER, "Authorization", ",");
	}
```
When calling my endpoints I got token added as expected:
--header 'Authorization: Bearer xxxxxxxxxxxxxxxxxxxxx'

However, when trying any version from 2.6.0 and up, seems header was damaged:
--header 'Authorization: Bearer' --header 'apiKey: Bearer xxxxxxxxxxxxxxxxxxxxx'

Not quite sure why it's now adding the token under header attribute apiKey. I was expecting keyname of 
ApiKey to be used to name the attribute.

**Comment by dilipkrish** [comment]
Thanks for reporting sorry I'm just getting to these issues

**Comment by vinoth-jeremy** [comment]
Hi @dilipkrish ,
I need to have common default Authorization header as above in swagger configuration. And after creating client jar, I want to add in APIClient as below
`apiClient.addDefaultHeader("Authorization","accessToken")`

Not as
`ControllerApi.getDetails(id, authorization)`

Please let me know the solutions for this

**Comment by vinoth-jeremy** [comment]
Hi @dilipkrish ,
Please let me know do we have any update on this issue,
I am also dependant on it.
Still **Authorization** in coming as accesstoken value

**Comment by dilipkrish** [comment]
@vinoth-jeremy @robsonhermes I think api key and value were switched around post 2.5.0. Might need to play around with the `ApiKey` security scheme. I think the name/keyName have been switched

**Comment by krmao** [comment]
I also got the problem

**Comment by thomasharin** [comment]
@krmao my problem was sloved just wit different version of swagger2 and swagger-ui. swagger-ui must be 2.5.0 version.  At the moment I don't know about other options.

**Comment by krmao** [comment]
thank you @thomasharin 
I solved not by switch version to 2.5.0
my result preview image at [here](https://github.com/springfox/springfox/issues/1812)

**Comment by artem-emelin** [comment]
Hi all, I've solved the problem for myself by creating `SecurityConfiguration` with _apiKey_ as `null`:

```java
new SecurityConfiguration(null, null, "Customer API Realm", "Customer API", null, ApiKeyVehicle.HEADER, authHeaderName, null)

**Comment by dilipkrish** [comment]
Fixed via upgrading to swagger 3.x (#2153)

**Comment by unsiv** [comment]
new SecurityConfiguration(null, null, "Customer API Realm", "Customer API", null, ApiKeyVehicle.HEADER, authHeaderName, null);

Here im using swagger 2.8.0. SecurityConfiguration is deprecated.. what can i use instead of SecurityConfiguration for swagger 2.8.0?

Thanks,
Unsiv

**Comment by dilipkrish** [comment]
You can use the `SecurityConfigurationBuilder`

https://github.com/springfox/springfox/blob/b1cf9529c7337afe98076482d36e88bce11e2183/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/SecurityConfigurationBuilder.java#L41-L43

**Comment by deviant-studio** [comment]
It is totally broken in 2.8. The header hasn't been added at all.
In 2.7 it works but i have to pass null to SecurityConfiguration as Artem suggested

**Comment by robsonhermes** [comment]
@deviant-studio I could not make it work with 2.7.0 like you said. Mind providing the code of your Swagger Configuration class?
