### ISSUE TITLE
Spring Data Rest Integration adds non-existing path param "id" to save operation

### ISSUE THREAD

**Issue by thombergs** [springfox/springfox#1962]
I have just evaluated generating a Swagger Documentation for a Spring Data Rest repository with the Spring Data Rest Integration feature in the current 2.7.0 release and came upon the following bug.

For the `save` method of a Spring Data repository exposed with Spring Data Rest, Springfox correctly documents a POST endpoint. However, the documentation generated by Springfox includes a mandatory path parameter named "ID" (see screenshot below). However, a POST endpoint creating a new resource doesn't and shouldn't have an ID parameter in the path.

I have found no working solution to remove that parameter from the documentation (i.e. by using Swagger annotations). Is there a workaround?

![invalid_param](https://user-images.githubusercontent.com/1363578/28845978-0fa238e2-770a-11e7-8fe2-d731fb26edda.png)

Example with this problem at https://github.com/thombergs/code-examples/blob/master/spring-data-rest-springfox/src/main/java/com/example/demo/AddressRepository.java (the "save" method).

**Comment by dilipkrish** [comment]
I think this is fixed. Could you try the snapshot build and confirm?

**Comment by thombergs** [comment]
Yep, works with 2.7.1-SNAPSHOT.
