### ISSUE TITLE
required a bean of type 'com.mangofactory.swagger.configuration.SpringSwaggerConfig' that could not be found.

### ISSUE THREAD

**Issue by Aatika-Fatima** [springfox/springfox#1970]
Error:required a bean of type 'com.mangofactory.swagger.configuration.SpringSwaggerConfig' that could not be found.
If you remove @configuration annotation, springSwaggerConfig bean is not created
@EnableSwagger2
@Configuration
public class SwaggerConfig {

	@Inject
	private SpringSwaggerConfig springSwaggerConfig;
	 

	@Bean
	public SwaggerSpringMvcPlugin configureSwagger() {
		SwaggerSpringMvcPlugin swaggerSpringMvcPlugin = new SwaggerSpringMvcPlugin(this.springSwaggerConfig);
		ApiInfo apiInfo = new ApiInfoBuilder().title("QuickPoll REST API")
				.description("QuickPoll Api for creating and managing 	polls")
				.termsOfServiceUrl("http://example.com/terms-of-service").contact("info@example.com")
				.license("MIT License").licenseUrl("http://opensource.org/licenses/MIT").build();
		swaggerSpringMvcPlugin.apiInfo(apiInfo).apiVersion("1.0");
		return swaggerSpringMvcPlugin;
	}

	@Bean
	public Docket mainConfig() {// @formatter:off
		return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any()).build()

				.directModelSubstitute(LocalDate.class, String.class).genericModelSubstitutes(ResponseEntity.class);

	}// @formatter:on
}

 dependency: 
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.4.RELEASE</version>
	</parent>

	
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.2.2</version>
		</dependency>
		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.2.2</version>
		</dependency>
		
		<dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>1.0.2</version>
		</dependency>

**Comment by dilipkrish** [comment]
Please remove 

```xml
<!-- https://mvnrepository.com/artifact/com.mangofactory/swagger-springmvc -->
	<dependency>
		<groupId>com.mangofactory</groupId>
		<artifactId>swagger-springmvc</artifactId>
		<version>1.0.2</version>
	</dependency>
```

You're mixing two versions that are incompatible. Refer the documentation in http://springfox.io
