### ISSUE TITLE
Vavr/Javaslang Jackson module support

### ISSUE THREAD

**Issue by Sir4ur0n** [springfox/springfox#1971]
Hi guys,

I recently tried to add Swagger to our SpringBoot application (using Springfox) but I'm struggling on the integration with Vavr (ex-Javaslang).
`io.springfox:springfox-swagger2:2.6.1`
`io.springfox:springfox-swagger-ui:2.6.1`
`io.vavr:vavr:0.9.0`
`io.vavr:vavr-jackson:0.9.0`
(I somehow had issues with 2.7.0 so I used 2.6.1 instead)

Some of our exposed models (in controllers) use Vavr (e.g. `io.vavr.collection.List` or `io.vavr.control.Option`) and it works fine with SpringBoot thanks to the `io.vavr.jackson.datatype.VavrModule` which is a Jackson module to support Vavr objects.

However it does not seem to integrate well with Swagger. I tried in several ways to register a `VavrModule` to the ObjectMapper, but the result in Swagger does not look good:
<img width="967" alt="image" src="https://user-images.githubusercontent.com/1204125/29027560-77fabe7a-7b81-11e7-9c3b-90042177a675.png">
Notice the `io.vavr.collection.List<String> invalidityCategoryReasons` which appears with many inner fields (which are Vavr implementation details) like `async`, `distinct`, `empty`...

Here's a few of the things I tried so far:
```java
// In the Docket bean
import io.swagger.util.Json;
import io.vavr.jackson.datatype.VavrModule;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfiguration {

  @Bean
  public Docket api() {
    Json.mapper().registerModule(new VavrModule());
    return new Docket(DocumentationType.SWAGGER_2)
        .select()
        .apis(RequestHandlerSelectors.any())
        .paths(PathSelectors.any())
        .build();
  }

}

// Using an event listener on ObjectMapperConfigured as explained in https://springfox.github.io/springfox/docs/current/#configuring-the-objectmapper
import io.vavr.jackson.datatype.VavrModule;
import org.springframework.context.ApplicationListener;
import org.springframework.stereotype.Component;
import springfox.documentation.schema.configuration.ObjectMapperConfigured;

@Component
public class SwaggerJacksonModuleWithVavr implements ApplicationListener<ObjectMapperConfigured> {

  @Override
  public void onApplicationEvent(ObjectMapperConfigured event) {
    event.getObjectMapper().registerModule(new VavrModule());
  }
}

// Using a proposed fix from https://springfox.github.io/springfox/docs/current/#answers-to-common-questions-and-problems in case of custom object mapper being ignored
import com.fasterxml.jackson.databind.ObjectMapper;
import io.vavr.jackson.datatype.VavrModule;
import java.util.List;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.converter.HttpMessageConverter;
import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

@Configuration
public class MyWebAutoConfiguration extends WebMvcConfigurerAdapter {

  @Override
  public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
    ObjectMapper objectMapper = null;
    for (HttpMessageConverter converter : converters) {
      if (converter instanceof MappingJackson2HttpMessageConverter) {
        MappingJackson2HttpMessageConverter jacksonConverter =
            ((MappingJackson2HttpMessageConverter) converter);

        if (objectMapper == null) {
          objectMapper = jacksonConverter.getObjectMapper();
          objectMapper.registerModule(new VavrModule());
        } else {
          jacksonConverter.setObjectMapper(objectMapper);
        }
      }
    }
  }
}
```

I'm new to Swagger and Springfox so I might have done or overlooked something silly, I appreciate any help.

Thanks!

**Comment by dilipkrish** [comment]
I'll take a look and see whats going on

**Comment by Sir4ur0n** [comment]
Hi @dilipkrish,

Did you have some time to check this please? I took another look, hoping a fresh eye would spot a misconfiguration, but I did not manage to make it work :(

Thanks!

**Comment by nicolasrosado** [comment]
Any news about this problem ?

**Comment by imode69** [comment]
@dilipkrish 
Having a very similar issue. My web service uses Vavr and a 3rd party library that includes Jackson mixins registered in a module to control marshaling. Works well with the exception of Swagger. 

@Sir4ur0n 
Have you found an answer yet?

**Comment by Sir4ur0n** [comment]
@imode69 Nope :( Unfortunately for the moment we declare all our controllers with vanilla Java until this can be resolved.

**Comment by dilipkrish** [comment]
@Sir4ur0n It would be easier to create rules for the Vavr classes to map to native jdk8 collections. For e.g.  create a alternate type rule for `vavr.List<WildcardType>` => jdk8.List<WildcardType>` etc.

**Comment by Sir4ur0n** [comment]
@dilipkrish I'm not sure I understand what you mean by "rule"?

Also, how come Springfox doesn't let us customize the ObjectMapper? At least by injecting additional Jackson modules to it...

**Comment by dilipkrish** [comment]
@Sir4ur0n [see here](http://springfox.github.io/springfox/docs/current/#q14) on how to substitute list/array types. You can use the same technique to substitute wildcard vavr collection types => jdk8 types.

> Also, how come Springfox doesn't let us customize the ObjectMapper? At least by injecting additional Jackson modules to it...

It does ... you can listen for `ObjectMapperConfigured` application events like here...

https://github.com/springfox/springfox/blob/4427e23933629d1dce3ac2a80f7c8cd4d75f8ef6/springfox-schema/src/main/java/springfox/documentation/schema/property/OptimizedModelPropertiesProvider.java#L108-L111

**Comment by allienna** [comment]
Hi,
Effectively, with rules it works, but Wildcard don't. We have to define a rule per generic:
```java
  private AlternateTypeRule[] getListRules() {
    return new AlternateTypeRule[]{
        buildRuleForList(String.class),
        buildRuleForList(Integer.class)
    };
  }

  private AlternateTypeRule buildRuleForList(Class<?> type) {
    return newRule(typeResolver.resolve(List.class, type), typeResolver.resolve(java.util.List.class, type));
  }
```

**Comment by dilipkrish** [comment]
@allienna I'd be surprised if it doesnt work. Are you sure you're using spring fox's `WildcardType`? Also for this use case ☝️ it is supported out of the box, so Im confused why its not working.

**Comment by allienna** [comment]
My bad, maybe some issue with my browser refresh routine. Sorry, it works fine with WildcardType.
Thanks

**Comment by dilipkrish** [comment]
@allienna Also you can use the short for for that `genericModelSubstitutes`

**Comment by allienna** [comment]
Effectively, it's cleaner. 
Thanks

**Comment by Sir4ur0n** [comment]
@dilipkrish As stated in my initial post, I tried adding the VavrModule on the ObjectMapperConfigured event, but it doesn't work... :(

**Comment by Sir4ur0n** [comment]
Hi @dilipkrish 

Here's a test project to demonstrate adding a module to the ObjectMapper does not work:
https://github.com/Sir4ur0n/springfox-swagger-vavr

1) Run as a simple Spring Boot application
2) Go to http://localhost:8080/swagger-ui.html
3) The Main Controller exposed API is not correct:
![image](https://user-images.githubusercontent.com/1204125/31306421-2f4886cc-ab50-11e7-8d87-2e9e6047100b.png)

**Comment by dilipkrish** [comment]
For reference the easy way to add the rules is to use an `AlternateTypeRulesConvention`

https://gist.github.com/dilipkrish/2bf80a0285a04b4037c8994fd8cb8b80
