### ISSUE TITLE
Springfox Swagger configuration breaks customized ObjectMapper in Spring Boot

### ISSUE THREAD

**Issue by avillev** [springfox/springfox#1973]
Versions used:

io.springfox:springfox-swagger2:2.6.1
Spring boot:1.5.4.RELEASE

When customizing a Spring Boot object mapper via Jackson2ObjectMapperBuilder, Jackson2ObjectMapperBuilderCustomizer or by directly modifying an ObjectMapper instance on MappingJackson2HttpMessageConverter, a situation may arise where the ObjectMapper instance used by Spring Boot for message conversion may be different to the one you customized (actually it looks like the one from springfox is used, which causes problems since it does not have the same modules at all).

Examples of custom serializers:
```java
@Component
public class BigDecimalToStringSerializer extends StdSerializer<BigDecimal> {
  private static final long serialVersionUID = 7201096151443152536L;

  public BigDecimalToStringSerializer() {
    super(BigDecimal.class);
  }

  @Override
  public void serialize(BigDecimal value, JsonGenerator gen, SerializerProvider provider) throws IOException {
    gen.writeString(value.stripTrailingZeros().toPlainString());
  }
}

@Configuration
public class JacksonConfig {
  private final BigDecimalToStringSerializer bigDecimalToStringSerializer;

  @Autowired
  public JacksonConfig(BigDecimalToStringSerializer bigDecimalToStringSerializer) {
    this.bigDecimalToStringSerializer = bigDecimalToStringSerializer;
  }

  @Bean
  public Jackson2ObjectMapperBuilderCustomizer addCustomBigDecimalDeserialization() {
    return builder -> builder.serializerByType(BigDecimal.class, bigDecimalToStringSerializer);
  }
}
```
When using the above and converting a ResponseEntity with a BigDecimal field, the gen.writeString line should be executed. If the mapper is incorrect, it won't be.

Just having the springfox dependency, a @ComponentScan and a Docket configuration generates the problem. The serializer is not executed anymore.

I do not know if this problem is linked to those, but it seems it is not fixed yet :)
https://github.com/springfox/springfox/issues/1140
https://github.com/springfox/springfox/issues/1051
https://github.com/springfox/springfox/issues/1051

**Comment by avillev** [comment]
So, since the problem is that the Spring MappingJackson2HttpMessageConverter uses springfox's objet mapper instead of the default one, i finally solved my problem by doing this:

`@Bean
	@DependsOn("requestMappingHandlerAdapter")
	public Docket api() {...}`

`@Component
public class SwaggerObjectMapperListener implements ApplicationListener<ObjectMapperConfigured> {

	/**
	 * The default object mapper from spring. This is the one which should be used
	 */
	@Autowired
	private ObjectMapper jacksonObjectMapper;

	/**
	 * The object containing all request mappers used by Spring MVC to handle the queries
	 */
	@Autowired
	private RequestMappingHandlerAdapter requestMappingHandlerAdapter;

	/**
	 * Reception of the configuration event
	 * Since spring-fox/swagger/spring have a tendency to override the default jackson, we need to ensure that the default, potentially customised, object mapper from spring is used.
	 *
	 * @param event The received event
	 */
	@Override
	public void onApplicationEvent(ObjectMapperConfigured event) {
		if (requestMappingHandlerAdapter != null && requestMappingHandlerAdapter.getMessageConverters() != null && jacksonObjectMapper != null) {
			for (HttpMessageConverter<?> converter : requestMappingHandlerAdapter.getMessageConverters()) {
				if (converter instanceof MappingJackson2HttpMessageConverter) {
					MappingJackson2HttpMessageConverter m = (MappingJackson2HttpMessageConverter) converter;
					m.setObjectMapper(this.jacksonObjectMapper);
				}
			}
		}
	}
}`

Of course it would be nice if springfox would have a fix for it.

**Comment by dilipkrish** [comment]
Closing this is, as it is related to 2.6.1. Also springfox doesnt ever create an object mapper. There are different jackson2 message converters in play and you need to use the `JacksonObjectMapperBuilder` to configure your object mapper.

**Comment by jgawron525** [comment]
@dilipkrish I am encountering this issue with SpringFox 2.9.2 ... unclear what your suggested solution is.

**Comment by vinu** [comment]
Try with a controller advice like this
``` java
@Slf4j
@ControllerAdvice
public class SwaggerResponseAdvice implements ResponseBodyAdvice<Object> {

    @Autowired
    private HttpServletRequest httpServletRequest;

    private final ObjectMapper objectMapper;

    public SwaggerResponseAdvice() {
        objectMapper = new ObjectMapper();
    }

    @Override
    public boolean supports(MethodParameter methodParameter, Class<? extends HttpMessageConverter<?>> aClass) {
        if (httpServletRequest.getRequestURI().equalsIgnoreCase("/v2/api-docs")) {
            return true;
        }
        return httpServletRequest.getRequestURI().startsWith("/swagger-resources");
    }

    @Override
    public Object beforeBodyWrite(Object o, MethodParameter methodParameter, MediaType mediaType, Class<? extends HttpMessageConverter<?>> aClass, ServerHttpRequest serverHttpRequest, ServerHttpResponse serverHttpResponse) {
        try {
            serverHttpResponse.getBody().write(objectMapper.writeValueAsBytes(o));
        } catch (IOException e) {
            log.warn("Error writing from advice", e);
        }
        return null;
    }
}
```
