### ISSUE TITLE
Hiding a model property in swagger using @ApiModelProperty(hidden= true) hides from all the api endpoints

### ISSUE THREAD

**Issue by angsdey2** [springfox/springfox#1975]
Hi,
In my application I am using auto generated id for all models. Now for add api endpoint I want to hide the auto generated id property in Swagger Documentation . So I hide it using @ApiModelProperty(hidden= true) directly on model's id attribute. But it hides from all the endpoints that id attribute from all the endpoints. So how can I customize to hide a property in swagger UI, based on api endpoints? Any help will be appreciated

**Comment by rehevkor5** [comment]
Use different classes for each endpoint? Use subclasses to avoid too much code duplication?

**Comment by dilipkrish** [comment]
Closing this as a duplicate for some of the work done in #1671
