### ISSUE TITLE
Attachment file gets corrupted if application/zip but not if application/octet-stream

### ISSUE THREAD

**Issue by sergio-otero** [springfox/springfox#1979]
* Problem description:

Downloading an attachment with mime-type application/zip via swagger-ui gets the file corrupted.
Downloading directly via browser (chrome or firefox) gets downloaded ok.
The same file downloaded with application/octet-stream via swagger-ui gets downloaded ok.

spring-boot-1.5.6.RELEASE springfox-swagger2, springfox-spring-web and swagger-ui 2.7.0

The problem has a simple solution (changing mime-type) and i'm not sure if it's a browser problem and can be solved, but it's worth leaving this info so that nobody loses time with the problem again.

* How to reproduce:

```
@GetMapping(path="/zip", produces = "application/zip")
	public ResponseEntity<InputStreamResource> zip() throws Exception {
		byte[] test = Files.readAllBytes(Paths.get(ClassLoader.getSystemResource("test.zip").toURI()));
		
		return ResponseEntity.ok()
				.contentType(MediaType.parseMediaType("application/zip"))
				.header("Content-Disposition", "attachment; filename=test.zip")
				.body(new InputStreamResource(new ByteArrayInputStream(test)));
	}
	

	// It works both in url and swagger-ui
	@GetMapping(path="/octet", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public ResponseEntity<InputStreamResource> octetStream() throws Exception {
		byte[] test = Files.readAllBytes(Paths.get(ClassLoader.getSystemResource("test.zip").toURI()));
		
		return ResponseEntity.ok()
				.contentType(MediaType.APPLICATION_OCTET_STREAM)
				.header("Content-Disposition", "attachment; filename=test.zip")
				.body(new InputStreamResource(new ByteArrayInputStream(test)));
	}
```

Open http://localhost:8080/swagger-ui.html

Click test-controller -> /test/octet -> Try it out -> Download test.zip -> it's ok (see src/main/resources/test.zip)

Click test-controller -> /test/zip -> Try it out -> Download test.zip -> it's corrupted (see src/main/resources/testDownload.zip)

Try the URL directly in the browser http://localhost:8080/test/zip -> it's ok

* Testcase

https://github.com/sergio-otero/test-springfox-rest-attachment

**Comment by dilipkrish** [comment]
Don't think this has anything to do with springfox.

**Comment by dohoon-oh** [comment]
I met similar problem. I used "application/png", the file was corrupted.
Of course, it worked well to download png file directly.

But, this issue seems to be related to Swagger-ui.
Refer this link : [https://github.com/swagger-api/swagger-ui/issues/1605](url)
