### ISSUE TITLE
Duplicate Listing in api view

### ISSUE THREAD

**Issue by stealheadyote** [springfox/springfox#198]
I have a simple controller with one exposed method /trails that is type get that returns list of trails. when I visit http://localhost/trails/api I have duplicate listings of the get call. 

/trails
GET : /trails
GET : /trails 

They both work as expected, but why are they duplicated within the api view?  For simplicity I have it boiled down to the simple case.  

The application is within a java spring environment using gradle for build and dependency management.

**Comment by ninaddk1980** [comment]
I am using tomcat 7 and i have integrated swagger-springmvc in my project. 
My Controller is as follows 

@RestController
public class HelloController {
	@RequestMapping(method=RequestMethod.GET,value="ninad/hello")
	@ApiOperation(httpMethod = "GET", value = "Say Hello To World using Swagger")
	public ResponseDate sayHelloInMobileGateway() {
		ResponseDate res= new ResponseDate();
		res.setMessage("Greetings from ninad!");
		return res ;
	}
}

When i deploy it as war file, on Spring UI, i can see this method picked up 4 times.  Did i missed out anything?
