### ISSUE TITLE
spring-data-rest RepositoryRestResource.collectionResourceRel not Mapped in Model

### ISSUE THREAD

**Issue by n3utrino** [springfox/springfox#1980]
Using Springfox 2.7.1-SNAPSHOT

Repo demonstrating the issue https://github.com/n3utrino/hal-test

Maybe it is just a configuration issue.

Swagger Model
```
{
  "content": [
    {
      "id": "string",
      "name": "string"
    }
  ],
  "links": [
    {
      "href": "string",
      "rel": "string",
      "templated": true
    }
  ]
}
```

Return from service
```
{
  "_embedded": {
    "guys": []
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/guys"
    },
    "profile": {
      "href": "http://localhost:8080/profile/guys"
    },
    "search": {
      "href": "http://localhost:8080/guys/search"
    }
  }
}
```

**Comment by n3utrino** [comment]
I got it almost working.

by using the http://springfox.github.io/springfox/docs/snapshot/#answers-to-common-questions-and-problems ObjectMapper Wierdness FAQ Code

Now the remaining problem is the `_embedded` collection rel which looks like this in the definition

```
"_embedded": [
    {
      "id": "string",
      "name": "string"
    }
  ],
```
but is returned as
```
"_embedded": {
    "guys": []
  },
```
it seems like springfox is not taking in 
``@RepositoryRestResource( collectionResourceRel = "guys",itemResourceRel = "guy")
``

**Comment by n3utrino** [comment]
related to #1879 ?

**Comment by dilipkrish** [comment]
Thanks for reporting.

**Comment by dilipkrish** [comment]
Related to #1927
