### ISSUE TITLE
Parent inheritance not working in @ApiModel

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#1983]
```
@ApiModel(discriminator = "type", subTypes = {Cat.class, Dog.class})
public class Animal {
}

@ApiModel(parent = Animal.class)
public class Cat extends Animal {
}

@ApiModel(parent = Animal.class)
public class Dog extends Animal {
}
```

But in generated json I don't see any "discriminator"

**Comment by roberterdin** [comment]
+1

**Comment by ssozonoff** [comment]
Any updates on this. Is there a version where it does work ?

**Comment by dilipkrish** [comment]
There is none as of now @ssozonoff . Hopefully in 2.8

**Comment by kbyyd24** [comment]
+1.  I really need this.

**Comment by unintended** [comment]
+1

**Comment by Josef-Reichardt** [comment]
+1

**Comment by jeroldwilson** [comment]
+1

**Comment by raderio** [comment]
Why this was closed?

**Comment by dilipkrish** [comment]
This will not be supported going forward as we move to Open API 3.0 support @raderio. The annotations will no longer work with 3.0 swagger annotations (packages changed). Also, It was part of a bulk closing of open `question` issues.

**Comment by TomJahncke** [comment]
Is there a workaround to this that anyone found?

**Comment by dilipkrish** [comment]
Its a feature that needs to be implemented. In general, making your resource models not expose the object models underneath is an overall better approach i.e. inheritance and polymorphism are not useful in service contracts given that on the other side the client could be one that doesnt work as well with inheritance, e.g. javascript.

**Comment by raderio** [comment]
> inheritance and polymorphism are not useful in service contracts
But OpenAPi supports it, which mean it is useful in service contracts

> on the other side the client could be one that doesnt work as well with inheritance, e.g. javascript.
I am JavaScript Developer, what problems JavaScript have with inheritance?

**Comment by raderio** [comment]
@dilipkrish at the moment a lot of people uses TypeScript which has class hierarchy.
Also in new versions of JavaScript you can create class hierarchy https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

**Comment by duckladydinh** [comment]
+1

**Comment by michalkutyla** [comment]
+1

**Comment by raderio** [comment]
TypeScript is primary language for Angular 
https://angular.io/guide/typescript-configuration
It has classes and hierarchy

**Comment by raderio** [comment]
This will allow to have such great API like 
https://github.com/Rebilly/ReDoc/blob/master/docs/images/discriminator-demo.gif
http://rebilly.github.io/ReDoc/

**Comment by atkawa7** [comment]
@raderio Checkout an example on how you could integrate springfox and redoc on https://github.com/atkawa7/httpsnippet
