### ISSUE TITLE
Display human readable resource name

### ISSUE THREAD

**Issue by igorbljahhin** [springfox/springfox#1990]
Hello,

My controllers are shown in Swagger UI using real bean name instead of human readable name:

![2017-08-18 18_26_57-swagger ui](https://user-images.githubusercontent.com/1252230/29465715-e9157f54-8442-11e7-9f63-ffd3c2c37202.png)

![2017-08-18 18_29_00-swagger ui](https://user-images.githubusercontent.com/1252230/29465830-453da5e0-8443-11e7-9b4c-a20fc6ee7795.png)

This is caused by that some controllers have their request mapping defined in interface, like:

    @Api(value = "pier", description = "operations with pier")
    @RequestMapping("/api/v1/pier")
    @Validated
    public interface PierResource {
        @ApiOperation(value = "Find pier by ID")
        @ApiResponses(value = {
            @ApiResponse(code = 404, message = "No pier found")
        })
        @GetMapping("{id}")
        @ResponseBody
        PierDTO loadPier(@PathVariable("id") String id) throws PierNotFoundException;
    }

    @RestController
    public class PierController implements PierResource {
        @Inject
        private PierService pierService;

        @Override
        public PierDTO loadPier(final String id) throws PierNotFoundException {
            return pierService.loadPier(id);
        }
    }

Is it possible to define "display name" for the resource?

**Comment by dilipkrish** [comment]
You'd need to add `@Api(tags={"Piers"})` to get it to show the tag name. Also optionally you need to add the same `Tag` with description to the docket.
