### ISSUE TITLE
Two get methods in one controller with diffrent  params, only one is documented

### ISSUE THREAD

**Issue by Shaun-Yao** [springfox/springfox#1992]
I am using v2.7.0

```java
@Api(tags = { "Statistics related" })
@RestController
@RequestMapping(value = "/statistics")
public class StatisticsController {

	@ApiOperation(value = "get one", notes = "get one")
	@GetMapping(params = "date")
	public ResponseEntity<ResultModel> get(@RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate date) {
		.....
	}


	@ApiOperation(value = "get list", notes = "get list")
	@GetMapping(params = "days")
	public ResponseEntity<ResultModel> list(int days) {
		.....
	}
	
	
}
```

**Comment by dilipkrish** [comment]
You need to enableUrlTemplating in your docket. See [RFC 6570 Support](http://springfox.github.io/springfox/docs/current/#springfox-rfc6570-support-strong-incubating-strong).

**Comment by Shaun-Yao** [comment]
@dilipkrish thanks for the reply! 
I have added
compile("io.springfox:springfox-swagger2:2.7.0")
compile("io.springfox:springfox-swagger-ui:2.7.0")
compile("io.springfox.ui:springfox-swagger-ui-rfc6570:1.0.0")
 and Docket enableUrlTemplating true
 but the Request URL is http://localhost:9000/api/statistics{?days}&days=5

**Comment by dilipkrish** [comment]
Please remove compile("io.springfox:springfox-swagger-ui:2.7.0")

**Comment by Shaun-Yao** [comment]
@dilipkrish Thank you patiently!  I have removed compile("io.springfox:springfox-swagger-ui:2.7.0"),  but the the Request URL  is the same  http://localhost:9000/api/statistics{?days}&days=5

**Comment by dilipkrish** [comment]
You may need to clear the browser cache.

**Comment by Shaun-Yao** [comment]
I verify that i have cleared the browser cache. 
return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage(SWAGGER_SCAN_BASE_PACKAGE))
                .build().**enableUrlTemplating(true)**
                .globalResponseMessage(RequestMethod.GET, error)
                .globalResponseMessage(RequestMethod.POST, error)
                .globalResponseMessage(RequestMethod.PUT, error)
                .globalResponseMessage(RequestMethod.DELETE, error)
                .ignoredParameterTypes(CurrentUser.class)
                .apiInfo(apiInfo());

![qq 20170822194143](https://user-images.githubusercontent.com/18024481/29564070-d7ff3952-8772-11e7-9a07-7d1095f02cf7.png)
