### ISSUE TITLE
Document end-points not defined in Spring

### ISSUE THREAD

**Issue by inad9300** [springfox/springfox#1993]
This is a question, and possibly a feature request.

I would like to include in the Swagger specification end-points not present in the host Spring application. The most obvious example would be to include `/v2/api-docs` on the documentation. More generally, the project might be using tools that expose their own end-points. In the particular case of the project I'm working on, a (custom) library is being used that exposes authentication end-points. Without including them in the documentation, the users of the REST API would have no idea of how to actually use it, since all end-points require authentication.

Is there any mechanism whereby arbitrary end-points can be declared?

**Comment by dilipkrish** [comment]
Yes there is. Take a look at [this example](http://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin)
