### ISSUE TITLE
@RequestMapping params overwrite @ApiParam values 

### ISSUE THREAD

**Issue by ctruzzi** [springfox/springfox#1994]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? 2.7.0

What kind of issue is this?
- [x] spring xml/java config that is relevant
- [x] springfox specific configuration if it makes sense

When adding query params as required in a `@RequestMapping` all primitive data associated to the `@ApiParam` that describes the resource gets overwritten. Below is a snippet

```
@RequestMapping(method = RequestMethod.GET, value = "/path/", params = "id")
@ApiOperation(value = "description", notes = "note")
public ResponseEntity<?> getFoo(
    @ApiParam(value="description", required = true, allowMultiple=true)
    @RequestParam(value="id") 
    final Set<UUID> ids) { ...}
```

This will result in the SpringFox `ParameterMerger.java` to overwrite assigned primitives like `allowMultiple=true` with the default value of `false`.

JSON snippet output

```
{
    "description": "description",
    "in": "query",
    "name": "id",
    "required": true,
    "type": "string"
}
```
Which is incorrect. This appears to be caused by `AbstractOperationParameterRequestConditionReader` creating a new Parameter for the `RequestMapping` parameter and assigning default values.

**Comment by dilipkrish** [comment]
You can remove `params='id'` from the `RequestMapping` and that should fix your issue.
