### ISSUE TITLE
View APIs from different Spring Cloud Instances registered in Eureka

### ISSUE THREAD

**Issue by s-mop** [springfox/springfox#1995]
I want view all APIs from different  Spring Cloud Instances in one page(or instance/server)
is there any config can help me to do that?

**Comment by dilipkrish** [comment]
Implement your own subclass of [`SwaggerResourcesProvider`](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/SwaggerResourcesProvider.java), based on [this implementation](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.java). Just be sure to mark it as the `@Primary` bean.

**Comment by PierreBesson** [comment]
@s-mop, have a look at the JHipster project: we have developed a custom registry app based on Eureka and it includes a Swagger UI + Zuul proxy which lets you do exactly what you want.
See: http://www.jhipster.tech/jhipster-registry/
Note: the Swagger feature is still undocumented and can be enabled with the "swagger" profile.

Indeed we use the SwaggerResourcesProvider but we also need to rewrite the basepath of json docs with a Zuul filter for the `try it out` button to work.

**Comment by dilipkrish** [comment]
Added documentation as part of #1954
