### ISSUE TITLE
PathVarible composed of Custom Objects are not parsed correctly

### ISSUE THREAD

**Issue by frbo42** [springfox/springfox#1998]
I noticed a regression in version 2.7.0 compared to version 2.6.1
When passing an object as path variable opposed to a simple type, the parsing is not done correctly

`public void myId(@PathVariable(value = "myId") MyId myId)`

The value in 'MyId' is not set.

I attached a small spring-boot application demonstrating the problem
By calling  `swagger-application->s/{myId}` with e.g. 42, the value received in the controller will be:
{myId}

[swagger-bug.zip](https://github.com/springfox/springfox/files/1246295/swagger-bug.zip)

**Comment by dilipkrish** [comment]
Thank you for reporting a detailed example. It goes a long way in helping to identify the fix @frbo42

**Comment by dilipkrish** [comment]
Fixed via #2114
