### ISSUE TITLE
Generated JSON for endpoints with PathVariables converted to non-trivial objects is incorrect

### ISSUE THREAD

**Issue by joel-ws** [springfox/springfox#1999]
Since switching to springfox 2.7.0 from 2.6.1 we've noticed that endpoints defined with non-trivial objects for `@PathVariable` parameters, e.g. not Integer, Long, String, etc., are not being documented properly. The generated JSON shows the object's fields as **query** parameters for the endpoint and extra information for the parameter in `@ApiImplicitParam` annotations is included as a separate parameter.

To reproduce:
- Download and extract [testBuildApi.zip](https://github.com/springfox/springfox/files/1247672/testBuildApi.zip)
- Run `./gradlew bootRun`
- Browse to http://localhost:8080/v2/api-docs and compare this to the definition in `com.joelws.testBuildApi.TestController`. This endpoint should only have one integer path parameter but the doc also shows 2 query parameters which are the fields in the object.

If the springfox version is reverted to 2.6.1 this works as expected - only the path parameter is documented.

**Comment by dilipkrish** [comment]
Thanks for your detailed example. goes a long way! 🤘

**Comment by dilipkrish** [comment]
Fixed via #2114
