### ISSUE TITLE
Upgrade to latest version of swagger-ui (3.1.5)

### ISSUE THREAD

**Issue by madheshr** [springfox/springfox#2000]
Hi
Are there any plans to upgrade to the latest swagger-ui?  We use springfox-swagger-ui and are facing some issues - most importantly: https://github.com/swagger-api/swagger-ui/issues/3041
Thanks

**Comment by raderio** [comment]
last version is 3.1.7

**Comment by raderio** [comment]
As I understand, we only nee to change this line. I ma right @dilipkrish ?

**Comment by dilipkrish** [comment]
@raderio no its [more than that](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/springfox.js). `springfox.js` needs to work with the new react based ui.

**Comment by dilipkrish** [comment]
Fixed via #2153
