### ISSUE TITLE
Int authorization code grant type I get access token using springfox ui the client_id and client_secret parameter should basic auth?

### ISSUE THREAD

**Issue by jast90** [springfox/springfox#2006]
Actually `client_id` and `client_secret` parameter is pass in form data using springfox ui ?But my Oauth2 Server get `token` need pass a header `Authorization Basic Zm9vOmJhcg==` .Can springfox ui do it?

**Comment by dilipkrish** [comment]
@jast90 Might have to do some hacks. For more complex scenarios it is easier to use the swagger-ui library web jar than the one that comes with springfox

**Comment by jast90** [comment]
@dilipkrish The  swagger-ui is support,I checked it out.
