### ISSUE TITLE
Show bean validation @Pattern

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#2008]
At the moment 
`@JsonFormat(pattern = "yyyy-MM-dd", shape = JsonFormat.Shape.STRING, lenient = OptBoolean.FALSE)`
is shown in UI in "Example Value".
Please make the same for `@Pattern` annotation

**Comment by dilipkrish** [comment]
> Please make the same for @Pattern annotation

What same?

**Comment by raderio** [comment]
> is shown in UI in "Example Value".
