### ISSUE TITLE
redirection (303) fails when domain of "location" is different form domain in request

### ISSUE THREAD

**Issue by gsbtech** [springfox/springfox#2009]
A REST endpoint returns an HTTP Status 303 with a Location header, where the Location has a different server name than the incoming request.

     response.setStatus(HttpServletResponse.SC_MOVED_TEMPORARILY);
     response.setHeader(HttpHeaders.LOCATION, url);
     addCorsHeaders(response);   

It works with curl, and chrome POSTMAN, but spring/swagger fails.

- What version of the library are you using? 
  springfox-swagger2/springfox-swagger-ui 2.6.1 and spring 4.2.5.RELEASE.

Is there a set of CORS headers I need to include?

I tried a few combinations of CORS headers but neither worked.

**Comment by dilipkrish** [comment]
Not really sure if swagger-ui handles 303s. You could try with 2.7.0 of springfox libraries to see if it was fixed but I doubt it. You'd need to create an issue in the [swagger-ui project](https://github.com/swagger-api/swagger-ui)

**Comment by gsbtech** [comment]
2.7.0 did not do the trick either. I noticed that our spring-boot wrapper for the application had CORS enabled, "*" configuration. So,By adding the header @CrossOrigin to the "redirected to" REST endpoint, I was able to get the redirection to work.

Probably having spring boot being configured for CORS at the application level, interfered with my CORS settings at the individual HTTP response level.

**Comment by dilipkrish** [comment]
@gsbtech did you find a solution?

**Comment by gsbtech** [comment]
The approach I took mentioned above worked. I ave not had time to play with modifying the Spring Boot default config.
