### ISSUE TITLE
Duplicated swagger.json document

### ISSUE THREAD

**Issue by cesartl** [springfox/springfox#2012]
version `2.7.0` (also tested with `2.6.1`)

Swagger configuration

```java
@Configuration
@EnableSwagger2
public class SwaggerConfiguration {
    @Bean
    public Docket revenueModelerApi() {

        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.###"))
                .paths(PathSelectors.any())
                .build();
    }
}
```
When doing a GET to `/v2/api-docs` I get two identical JSON documents one after the other:

```
{
   "swagger":"2.0",
   "info": {...},
   "paths": {...}
}{
   "swagger":"2.0",
   "info": {...},
   "paths": {...}
}
```
If I cut the file in half I get a valid Swagger.json file. But what could trigger the duplication in the response?

**Comment by dilipkrish** [comment]
Could you create a sample project that demonstrates this bug? surprised by this

**Comment by dilipkrish** [comment]
No idea how to reproduce this. This is not even valid json. I would attribute it to something environmental
