### ISSUE TITLE
Add support for generics

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#2015]
```
public void todo(@Valid @RequestBody dto: Dto<Obj>) {
}
public void todo2(@Valid @RequestBody dto: Dto<Obj2>) {
}
```

In Swagger model I see only 

> Dto«string» {
> }

And for both actions is shown same model/object, but I have 2 model/object `Dto<Obj>` and `Dto<Obj2>`

**Comment by raderio** [comment]
For Response is everything ok, the issues is only with Request.

**Comment by dilipkrish** [comment]
Thanks for reporting @raderio

**Comment by dilipkrish** [comment]
Generics of this type are supported. Also as you can see, it infers a type of `string` as the generic type parameter.  Is it perhaps something to do with how you're using kotlin? I don't have a way to reproduce this. sorry!
