### ISSUE TITLE
Importing Maven dependencies for springfox

### ISSUE THREAD

**Issue by purushot057** [springfox/springfox#2016]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by purushot057** [comment]
Hi Dilip, I have added below dependencies in pom.xml  <dependency>             <groupId>io.springfox</groupId>             <artifactId>springfox-swagger-ui</artifactId>             <version>2.6.1</version>             <scope>compile</scope>         </dependency>         <dependency>             <groupId>io.springfox</groupId>             <artifactId>springfox-swagger2</artifactId>             <version>2.6.1</version>         </dependency> They are not getting resolved even after doing explicit maven import . Also, there are no errors in pom.xml. Kindly suggest what could be the issue.

**Comment by dilipkrish** [comment]
@purushot057 your maven setup must be incorrect. The jars are totally [available in maven central](http://mvnrepository.com/artifact/io.springfox/springfox-swagger2)
