### ISSUE TITLE
Add support for Open API 3.0

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#2022]

**Comment by deki** [comment]
Hi, I see there is a branch for it, but last commit was half year ago. Are you still working on it?

**Comment by dilipkrish** [comment]
Yes, hope to add that back in the upcoming release.

**Comment by akhilgupta01** [comment]
Hi, Do we have any indicative timeline when this would be available?

**Comment by dilipkrish** [comment]
Hoping to get an initial cut along with 2.9.0

**Comment by fsamir** [comment]
Any update? 
v2.9.1-SNAPSHOT is out and I can't see it, is it safe to assume it won't make it?
If so, is there a branch or some direction on how to help to move this ticket forward?
Cheers

**Comment by dilipkrish** [comment]
@fsamir have to get back to it. Just back from a break. Definitely in 3.0

**Comment by TomasZuklys** [comment]
Hi @dilipkrish, when we can expect 3.0 release?

**Comment by dilipkrish** [comment]
@TomasZuklys Thats the plan for the next release :)

**Comment by marcellisdon** [comment]
@dilipkrish Hi Krishnan, any update about the next release? Can we expect it end of Aug-2018?

**Comment by dilipkrish** [comment]
@marcellisdon I am going to try

**Comment by yomiex** [comment]
Hey, looking forward on v3 release.

**Comment by surajrrao** [comment]
@dilipkrish Any update on 3.0? When this will be available.

**Comment by bhanu1942** [comment]
OpenAPI 3.0 support availability please?

**Comment by cmayne-r7** [comment]
Looking forward to v3 support! Thanks for the great work. I'm at the cusp of releasing an api and building documentation, so having to fallback to v2 for now. Do you know yet, if it will be possible to generate/host both v2 and v3 swagger docs from the same runtime?

**Comment by deki** [comment]
I'm willing to contribute. We already did a OAS 3 implementation for Apache CXF. Any subtasks you need help with?

**Comment by sebastiandg7** [comment]
Any news about this? @dilipkrish, I think you should talk to @deki... maybe this can be out earlier with his support. Thanks a lot for the efforts!! Keep it up!

**Comment by dilipkrish** [comment]
@dilipkrish I would absolutely like some help. There is a bunch of work that needs to happen, and I could certainly use help. Let me know if you'd like to get on a hangout or Skype.

**Comment by dilipkrish** [comment]
@cmayne-r7 sorry I've been on a hiatus for the last few weeks, plan to start working on this

**Comment by 6sco** [comment]
Any news for this feature ? @dilipkrish 
Thanks.

**Comment by raderio** [comment]
@dilipkrish have you contacted @deki for help ?

**Comment by Ravibabu-Nannuri** [comment]
Please let me know if you need some help with this feature?

**Comment by raderio** [comment]
@dilipkrish has tried to discuss with Spring team about this project to be part of framework? Will be much better to have their support.
For example Micronaut framework https://github.com/micronaut-projects/micronaut-core, which was developed with inspiration from Spring, has OpenAPI support builtin.

**Comment by jhg023** [comment]
> I do plan to get it out in Feb for sure.

Any updates on this goal?

**Comment by atkawa7** [comment]
Ping @dilipkrish

**Comment by lamberto82** [comment]
Hi Guys, apologies if this is not the place to ask this:
I would like you know if with that fix will allow the possibility to document dynamic query parameters in a free form.
Thank you

**Comment by codependent** [comment]
Hi @dilipkrish, first off, I (like many others) appreciate the work you have been doing on this project which is the the facto Open API Solution for Spring projects.

It's a real pity, but completely understandable that certain features are taking so much to be released in a stable 3.0.0 version, such as Spring Boot 2 or Open API 3 support.

Since I am relying on Springfox for many current and future projects I'd appreciate if you could give us some feedback about an estimate release schedule for those features.

**Comment by dilipkrish** [comment]
I’m working on it. I’m hoping to focus on this the month of April and have it out latest by end of the month. Apologies for this.

**Comment by ladyskynet** [comment]
@dilipkrish Hi! Any updates on progress being made towards OAS 3?

**Comment by atkawa7** [comment]
@dilipkrish PING

**Comment by ylastapis** [comment]
@dilipkrish PING

**Comment by dmnized** [comment]
I need it and I would help

**Comment by bartoccioni** [comment]
@dilipkrish same here

**Comment by atkawa7** [comment]
@dilipkrish Just saw your recent commit. I am so excited and I can't wait to test the current master using [`https://jitpack.io`](https://jitpack.io) Thank you.

**Comment by lpandzic** [comment]
@atkawa7 I've tried asking on gitter but with no answer - how can I use the latest master to enable openapi?
Currently the farthest I was able to get is to generate an openapi spec with no paths detected...

**Comment by opticyclic** [comment]
Where is the code for this?
The issue is 21 months old but there are only 2 days of commits in March 2019 in the branch 
https://github.com/springfox/springfox/compare/feature/2022/oas-3-support

Is it all going on in master?

Where can we see what has been done, what is outstanding and what needs help with?

**Comment by lpandzic** [comment]
I've managed to create a workaround:
1. generate swagger2
2. use SwaggerConverter to convert swagger2 to openapi spec

```
// autowire springfox.documentation.spring.web.DocumentationCache
// autowire springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper
var documentation = documentationCache.documentationByGroup("default");
var swagger = mapper.mapDocumentation(documentation);
var deserializationResult = new SwaggerDeserializationResult();
deserializationResult.setSwagger(swagger);
OpenAPI openAPI = return new SwaggerConverter().convert(deserializationResult).getOpenAPI();
```

Dependency for converter:
```
<dependency>
	<groupId>io.swagger.parser.v3</groupId>
	<artifactId>swagger-parser</artifactId>
	<version>2.0.12</version>
</dependency>
```

**Comment by vaibhavn** [comment]
> 
> 
> I've managed to create a workaround:
> 
>     1. generate swagger2
> 
>     2. use SwaggerConverter to convert swagger2 to openapi spec
> 
> 
> ```
> // autowire springfox.documentation.spring.web.DocumentationCache
> // autowire springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper
> var documentation = documentationCache.documentationByGroup("default");
> var swagger = mapper.mapDocumentation(documentation);
> var deserializationResult = new SwaggerDeserializationResult();
> deserializationResult.setSwagger(swagger);
> OpenAPI openAPI = return new SwaggerConverter().convert(deserializationResult).getOpenAPI();
> ```
> 
> Dependency for converter:
> 
> ```
> <dependency>
> 	<groupId>io.swagger.parser.v3</groupId>
> 	<artifactId>swagger-parser</artifactId>
> 	<version>2.0.12</version>
> </dependency>
> ```
My workaround:
I am using 'convert' api from http://oai.swagger.io/ to convert my Swagger-2.0 JSON to Open API 3.0

**Comment by lpandzic** [comment]
This was my approach before as well but I wanted to automate this.
With runtime conversion you have more options, e.g. put those steps into your build pipeline or override your openapi spec endpoint to do it on the fly.

**Comment by vaibhavn** [comment]
Yes..I agree with you. Trying your suggested approach now. Thanks for sharing !

**Comment by tanoliusman** [comment]
> All, sincere apologies. I've been a little busy with my day job the last couple of months and haven't been able to devote much time, at least as much as I'd like to. There have been some terrific contributions for 3.x by @MaksimOrlov, @deblockt, @dschulten, to name a few and I do plan to get it out in Feb for sure.
> 
> NOTE: It would be nice not rely on just my bandwidth/availability to work on this. I am looking for contributors who can come in, partner and help shape the future of this project. You're experience doesn't matter, novice to senior. If you're just starting out and looking for a way to contribute to open source, I'd be happy to mentor you and we can figure this out together. If you're interested please drop me a line in the comments.
> 
> @Ravibabu-Nannuri definitely need help :)

I would like to help on this.

**Comment by jefersonfrancisco** [comment]
> All, sincere apologies. I've been a little busy with my day job the last couple of months and haven't been able to devote much time, at least as much as I'd like to. There have been some terrific contributions for 3.x by @MaksimOrlov, @deblockt, @dschulten, to name a few and I do plan to get it out in Feb for sure.
> 
> NOTE: It would be nice not rely on just my bandwidth/availability to work on this. I am looking for contributors who can come in, partner and help shape the future of this project. You're experience doesn't matter, novice to senior. If you're just starting out and looking for a way to contribute to open source, I'd be happy to mentor you and we can figure this out together. If you're interested please drop me a line in the comments.
> 
> @Ravibabu-Nannuri definitely need help :)

I would like to help on this. How can I do ?

**Comment by SleepyDeb** [comment]
Please guys.....

**Comment by jredoules** [comment]
Last commit > 4 month.  :( 
You should accept help from community

**Comment by thiagohmoreira** [comment]
Guys/community,

I see lots of comments on the thread about people willing to help and such. I didn't saw a single PR though. Let's get past the saying and get to action. Raise PRs and we can discuss it. 

The author never declined any help, seems he's busy with his life maybe(?!). But if there are developments and he is not around anymore or can't spend the time to mantain the library we all can move to some fork and proceed. This is the beauty of open source.

**Comment by mindej** [comment]
+1 I need this feature.

**Comment by springdoc** [comment]
Hi guys,

We have released a new version of springdoc-openapi library:
It supports OpenAPI 3 with the spring-boot.

More details are available on:

- http://springdoc.org

**Comment by takashima2000** [comment]
> Hi guys,
> 
> We have released a new version of springdoc-openapi library:
> It supports OpenAPI 3 with the spring-boot.
> 
> More details are available on:
> 
> * http://springdoc.org

Is there any workaround for those not using boot? 
I know we should upgrade it, but meanwhile can we use it with Spring Web 4.x.x ?

**Comment by jefersonfrancisco** [comment]
> Hi guys,
> 
> We have released a new version of springdoc-openapi library:
> It supports OpenAPI 3 with the spring-boot.
> 
> More details are available on:
> 
> * http://springdoc.org

Thanks for share this solution. I certainly will test !!

**Comment by springdoc** [comment]
Hi takashima2000 , 

 This should work, but you have to setup manually all what spring-boot autoconfigures for you:

- Basically, you have to add a @ComponentScan for "org.springdoc"

- If you want to use the swagger UI as well and you are using @EnableWebMvc annotation, you shoud override addResourceHandlers when you extend WebMvcConfigurerAdapter 
```java
@Override
public void addResourceHandlers(ResourceHandlerRegistry registry) {
registry.addResourceHandler("/webjars/**").addResourceLocations("/webjars/").resourceChain(false);
}
```


If you have more questions or issues, please raise them on: https://github.com/springdoc/springdoc-openapi/issues

**Comment by patricklucas** [comment]
> Guys/community,
> 
> I see lots of comments on the thread about people willing to help and such. I didn't saw a single PR though. Let's get past the saying and get to action. Raise PRs and we can discuss it.

My guess is that many of those offering to help saw the promises of progress from the maintainer and didn't want to engage in what would become duplicate work. But like you say, maybe now is the time for such a volunteer to fork and move on.

**Comment by holoduck** [comment]
Personally, I think the number of non-reviewed PR is not encouraging. Some of them would solve issues I had with springfox. This brings me to believe that what this project needs the most is people helping out with code reviews.

I could fork the project and dedicate my time only to reading PR and that would not enough. I think the best would be to form a team, preferably including @dilipkrish (in which case, there might be no need to fork at all).

**Comment by dilipkrish** [comment]
@springdoc That is awesome! Would love to chat sometime about the direction you're going with it and if we could collaborate.

**Comment by jremenec** [comment]
I also started working on spring openapi 3 json generator in meantime. So far it is able to generate components part with javax validation annotations. It also integrates oneOf inheritance/polymorphism mechanism using Jackson (JsonSubTypes etc annotations) and new discriminators approach, because for many client developers that I worked with, this was also main point of confusion. Generally, it so far consists of 2 parts - maven plugin + generally reusable module.
@dilipkrish  if you find something useful there or you would also like to collaborate we can chat as well ;)

**Comment by dilipkrish** [comment]
Absolutely @jremenec! Would love to see if we can consolidate efforts to make this library better. Do you have a link to the repo that you can share?

**Comment by jremenec** [comment]
@dilipkrish https://github.com/jremenec/spring-openapi it is not even first version so only snapshot now. I would like to finalize operations part in 1-2 weeks so then there will be complete picture of swagger.json being generated. Now only components.

**Comment by membersound** [comment]
It may be noteworthy that spring started an official swagger-ui generator based on openapi 3: https://github.com/springdoc/springdoc-openapi

Maybe you guys could collaborate, instead of writing both a framework with the same purpose? 
While @dilipkrish is doing a fantastic job here. But the advantage for of an official spring framework will be much more manpower over the long run. Maybe you could contribute with your experience to springdoc?

**Comment by sdeleuze** [comment]
@membersound I am happy to see some move on OpenAPI Spring support, but notice that https://github.com/springdoc/ is not an official Spring project. https://github.com/springdoc/ != https://github.com/spring-projects/.

**Comment by jremenec** [comment]
@sdeleuze  no, it's not you're right. Do you propose to change name ? I chose this as the operations part will work with spring-rest annotations, so it will be in this part spring specific generator plugin.

**Comment by membersound** [comment]
Oh ok, then I probably misread unfortunately. Anyways, maybe you guys can still collab instead of creating the same framework twice.

**Comment by christophs78** [comment]
Asked the springdoc-team a few days ago:
https://github.com/springdoc/springdoc-openapi/issues/44
Also thought about opening a issue regarding OpenAPI-support in the official Spring project. Think it would make sense to have one official solution for OpenAPI-support. IMO OpenAPI-support is a must-have for much projects with REST-APIs. CXF on the JAXRS-side has officiall OpenAPI-support.

**Comment by membersound** [comment]
As springfox lacks openapi3 support for so long, I migrated all of my projects to springdoc-openapi. Issue where fixed within days, and all my docs are now running up to date with openapi3. So, though having used springfox for several years, I had to quit here.

But the same problem may arise in 2 years for springdoc-openapi too.

I would love the spring team itself could fork one of the existing projects to create an officially supported library. The question is, how could they be reached for those type of requests?

**Comment by christophs78** [comment]
Maybe the Spring-team thinks, their approach is better: https://spring.io/projects/spring-restdocs#overview
But OpenAPI is some kind of standard and has a good ecosystem (eg swagger) including generating client-code.
I'll try to read into their documentation and prepare some argumentation afterwards. I'll Google what people think about the Spring approach vs OpenAPI. Finally I think I will try it via the issue - tracker of the Spring project.
But it may really help if someone knows someone inside the Spring-team...

**Comment by membersound** [comment]
Biggest advantage: any `@RestController` can be added as documented endpoint by simply applying some openapi annotations.

Biggest disadvantage of spring-restdocs: you have to generate the documentation by writing *Tests*.
I don't think testing should have anything to do with exposing a try-out/documented frontend to the users.

**Comment by jremenec** [comment]
What I also found out when I was trying to write my own OpenAPI v3 generator was that when using swagger codegen to generate back the client code - it doesn't take into mind discriminator custom mapped values. It generates Jackson annotations but discriminator gets getClass().getSimpleName() value. So the mapping part of discriminator (OpenAPI3) is ignored.
Besides also swagger ui does not display this info so testers don't see what they can fill into the discsriminator property.
When implementing new version or merging with some project it could be good to have in mind also this for client generation and ui interpretation.

btw @membersound  you're right, it's not good to enforce tests in this way - some development teams might test but in a different way.

**Comment by christophs78** [comment]
@membersound - Seems like the Spring-team does not like OpenAPI. There already has been a long discussion: https://github.com/spring-projects/spring-restdocs/issues/213
They think their test-driven approach is supperior.
Their only „official“ suggestion is to use Spring REST Docs together with https://github.com/ePages-de/restdocs-api-
So i we wont get official OpenAPI-support by Spring within the next few years.

**Comment by membersound** [comment]
I don't like to hear that, but we (any many many others) are probably out of luck for an official supported library providing openapi3 plugin with spring...

**Comment by gogoyqj** [comment]
any progression? nullable support is needed

**Comment by jrcodeza** [comment]
I needed openapi 3 support more quickly due to better inheritance support so I implemented https://github.com/jrcodeza/spring-openapi . It can generate spec from code and also client from spec. Supports Jacskson, javax and spring annotations. Also allows to define own interceptors for altering generation of certain sections of schema generation.
Of course I'm opened to further collaboration.

**Comment by RajuReddy7777** [comment]
Is there any update on this issue?

**Comment by goodlux** [comment]
The milestones for Springfox v3.0 are here:

https://github.com/springfox/springfox/milestone/44

I think there is a Springfox v3.0 RC version. 

Here's more info. 

https://github.com/springfox/springfox/issues/2699

**Comment by kostya05983** [comment]
@dilipkrish Can I help with openapi v3? We need it to use in our company. I need some instruction what we need to do to make it work properly.

**Comment by jrcodeza** [comment]
@kostya05983  if you need this more quickly you can have a look on https://github.com/jrcodeza/spring-openapi (which generates OAS v3 schema) together with OAS-UI for GUI interpretation ( https://github.com/vahanito/oas-ui )  - it can be used as react component or also in plain html site as described in usage.

**Comment by runenielsen** [comment]
@kostya05983: springdoc-openapi looks promising and has more usage / activity / stars than the project mentioned above: https://github.com/springdoc/springdoc-openapi.

**Comment by dilipkrish** [comment]
Folks interested in helping out OAS support, the rough cuts has landed! Would love your feedback on this (excuse this really long PR, its pretty much a rewrite of the service/schema models.

If you'd like to help testing the snapshot locally or have questions I'm happy to jump in and answer. Again thank you for your patience and continued support. 

If you'd like to participate in the development please reach out to me in my email as well dilip.krishnan at gmail.

**Comment by atkawa7** [comment]
@dilipkrish I am happy to test.  Kindly share the snapshots repo configurations

**Comment by dilipkrish** [comment]
@atkawa7 at the moment it hasn't been pushed to master... so you'd have to build it locally. Also swagger-ui isn't fully integrated yet

**Comment by cbornet** [comment]
Can be closed ?

**Comment by dilipkrish** [comment]
Yeah :)
