### ISSUE TITLE
[Bug] SpringFox-Data-Rest 2.7.0: Missing camelCase with generated Associations operationIds

### ISSUE THREAD

**Issue by stoetti** [springfox/springfox#2025]
OperationId that is generated for Spring Data Rest association endpoints has ist missing and uppercase Letter at the beginning of the propertyname.

In my searches the source of the missing uppercase seems to be copy-paste-error in ReqestExtractionUtils:
```java
public static String lowerCamelCaseName(String stringValue) {
    return CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_CAMEL, stringValue);
  }

  public static String upperCamelCaseName(String stringValue) {
    return CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_CAMEL, stringValue);
  }

**Comment by dilipkrish** [comment]
Thanks for reporting
