### ISSUE TITLE
Produces/Consumes do not maintain order

### ISSUE THREAD

**Issue by jgaribay21** [springfox/springfox#2026]
Produces and Consumes for API operation have meaningful order when multiple formats are specified (the first being the preferred).  Swagger supports ordering these, but the internal implementation in springfox uses HashSets instead of LinkedHashSets.  Changing to LinkedHashSets would allow end users to specify the order the formats are specified.

**Comment by dilipkrish** [comment]
This should be fixed in the next release

**Comment by dilipkrish** [comment]
That would be awesome! @ayakovlevgh

**Comment by obirider** [comment]
@ayakovlevgh have you already submited the PR?
