### ISSUE TITLE
Non-nullable types in Kotlin data classes are optional in generated Swagger definition when springfox-bean-validators is present

### ISSUE THREAD

**Issue by breun** [springfox/springfox#2027]
**Update:** After some discussion it was discovered that the presence of `springfox-bean-validators` makes a difference.

----

I'm using Springfox 2.7.0 with Spring Boot 1.5.6 and Kotlin 1.1.4-3. I've converted some response classes that were generated using the Immutables library (https://immutables.github.io) to Kotlin data classes (https://kotlinlang.org/docs/reference/data-classes.html).

When using Immutables classes fields that are annotated with `@Nullable` are correctly seen as optional fields in the generated Swagger definition. However, when using a Kotlin data class, all fields are seen as optional fields in the generated Swagger definition, even fields with non-nullable types (e.g. `String` instead of `String?`). I found that I can add `@ApiModelProperty(required = true)` to every field with a non-nullable types to get rid of the 'optional' in the generated Swagger definition, but of course I would prefer not having to do this. Could Springfox support this?

**Comment by raderio** [comment]
Have you add jackson-module-kotlin dependency?

**Comment by breun** [comment]
Yes, I have the following bean in my configuration, which registers the `KotlinModule` from jackson-module-kotlin:

```
@Bean(name = "objectMapperSerializer")
public ObjectMapper objectMapper() {
    ObjectMapper mapper = new ObjectMapper();

    mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
    mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
    mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);

    mapper.registerModule(new KotlinModule())
            .registerModule(new JavaTimeModule());

    return mapper;
}
```

But apparently that's not enough.

**Comment by breun** [comment]
Looks like I'll have to provide a `Jackson2ObjectMapperBuilder` bean instead: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-customize-the-jackson-objectmapper I'll try that.

**Comment by raderio** [comment]
It works for me, but I do not create `ObjectMapper` bean

**Comment by breun** [comment]
I simplified my configuration to this:

```
@Bean
    public Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder() {
        return new Jackson2ObjectMapperBuilder()
                .modules(new KotlinModule(), new JavaTimeModule())
                .serializationInclusion(JsonInclude.Include.NON_EMPTY)
                .failOnUnknownProperties(false)
                .featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    }
```

However, non-nullable fields in Kotlin data classes are still marked as optional unless I add `@ApiModelProperty(required = true)` to each non-nullable field.

Adding `@JsonProperty(required = true)` to a non-nullable field myself also doesn't seem to change anything, because then that field is still marked as optional in Swagger.

**Comment by breun** [comment]
> It works for me, but I do not create `ObjectMapper` bean

What do you do exactly then?

**Comment by raderio** [comment]
I use gradle, and have only these dependencies
```
compile group: "org.jetbrains.kotlin", name: "kotlin-stdlib-jre8", version: kotlinVersion
compile group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.9.0"
compile group: "com.fasterxml.jackson.module", name: "jackson-module-kotlin", version: "2.9.0"
compile group: "org.springframework.boot", name: "spring-boot-starter-web", version: springBootVersion
compile group: "io.springfox", name: "springfox-swagger2", version: "2.7.0"
compile group: "io.springfox", name: "springfox-swagger-ui", version: "2.7.0"
```

```
data class TestDto(val name: String)

@RestController
class TestingController {
    @PostMapping("/testing")
    fun testing(@Valid @RequestBody dto: TestDto) {
    }
}
```

**Comment by breun** [comment]
Thanks for your example. I see the data class here is used for the request. Does it also work if you use it for the response?

Did you register `KotlinModule` yourself somehow, or is that automatically registered?

My project is using kotlin-stdlib-jre8:1.1.4-3, jackson-databind:2.8.9, jackson-module-kotlin:2.9.0, spring-boot-starter-web:1.5.6.RELEASE, springfox-swagger2:2.7.0. I'll see if making the version of all of my Jackson dependencies the same helps.

**Comment by raderio** [comment]
>Thanks for your example. I see the data class here is used for the request. Does it also work if you use it for the response?

Yes it works

>Did you register KotlinModule yourself somehow, or is that automatically registered?

automatically

**Comment by breun** [comment]
Just to make sure: when you say 'it works' you mean that the string in `TestDto` isn't marked as optional in the Swagger UI?

I've removed `.modules(new KotlinModule(), new JavaTimeModule())` from my configuration and it indeed seems that those modules are auto-detected, but still non-nullable fields in data classes are marked as optional unless I annotate them with `@ApiModelProperty(required = true)`.

I upgraded all my Jackson dependencies from 2.8 to 2.9, but that also doesn't seem to make a difference.

Would you happen to know what code is responsible for adding the annotations to those non-nullable fields and what code determines whether a field should be marked as optional or not, so I can put some breakpoints in there and debug?

**Comment by raderio** [comment]
> Just to make sure: when you say 'it works' you mean that the string in TestDto isn't marked as optional in the Swagger UI?

Yeap

Also remove this bean
```
@Bean
public Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder() {
```

**Comment by breun** [comment]
I removed that bean (which also removed some serialization configuration the app needs, but ok), but after that my non-nullable fields in Kotlin data classes were still marked as optional in the Swagger UI.

**Comment by raderio** [comment]
I think you should ask [here](https://github.com/FasterXML/jackson-module-kotlin) it's not related to springfox

**Comment by breun** [comment]
If I manually add `@JsonProperty(required = true)` to non-nullable fields, they are also still marked as optional in the Swagger spec. The only way I have found I can manually get a field to be not marked as optional in the Swagger spec, is when I add `@ApiModelProperty(required = true)`, but that is of course not an annotation which `jackson-module-kotlin` would add.

**Comment by raderio** [comment]
Well, it also works for me with `@JsonProperty(required = true)`

**Comment by breun** [comment]
Here is a demo project which reproduces this issue: https://github.com/utwyko/springfoxkotlintest

It uses this data class for the response:

```
import com.fasterxml.jackson.annotation.JsonProperty
import io.swagger.annotations.ApiModelProperty

data class TestResponse(
        val nonNullableString: String = "non-null",
        val nullableString: String? = null,
        @JsonProperty(required = true) val jsonPropertyRequiredString: String = "non-null",
        @ApiModelProperty(required = true) val apiModelPropertyRequired: String = "non-null"
)
```

The `nullableString` field is correctly marked as optional in the Swagger UI, but `nonNullableString` is also marked as optional, which it shouldn't be.

This can also be seen directly in the Swagger spec:

```
$ curl -s localhost:8080/v2/api-docs | jq .definitions.TestResponse
{
  "type": "object",
  "required": [
    "apiModelPropertyRequired",
    "jsonPropertyRequiredString"
  ],
  "properties": {
    "apiModelPropertyRequired": {
      "type": "string"
    },
    "jsonPropertyRequiredString": {
      "type": "string"
    },
    "nonNullableString": {
      "type": "string"
    },
    "nullableString": {
      "type": "string"
    }
  }
}
```

Adding either `@JsonProperty(required = true)` or `@ApiModelProperty(required = true)` to a field does cause it to not be marked optional, but ideally you wouldn't need to add either annotation manually.

(Why adding `@JsonProperty(required = true)` in the bigger code base I'm working on (which I can't share) doesn't work seems to be a separate issue.)

**Comment by raderio** [comment]
Change version of jackson-module-kotlin
`compile "com.fasterxml.jackson.module:jackson-module-kotlin:2.9.0"`

```
data class TestResponse(
        val nonNullableString: String = "non-null",
        val nullableString: String? = null,
        val jsonPropertyRequiredString: String = "non-null",
        @ApiModelProperty(required = true) val apiModelPropertyRequired: String = "non-null"
)
```

The result is
```
curl -s localhost:8080/v2/api-docs | jq .definitions.TestResponse
{
  "type": "object",
  "required": [
    "apiModelPropertyRequired",
    "jsonPropertyRequiredString",
    "nonNullableString"
  ],
  "properties": {
    "apiModelPropertyRequired": {
      "type": "string"
    },
    "jsonPropertyRequiredString": {
      "type": "string"
    },
    "nonNullableString": {
      "type": "string"
    },
    "nullableString": {
      "type": "string"
    }
  }
}
```

**Comment by breun** [comment]
Ah, thanks! Upgrading `jackson-module-kotlin` to 2.9.x indeed fixes the issue in the demo project. I picked 2.8.9 at first, since that's the version of Jackson that comes with the version of Spring Boot used by the project (1.5.6.RELEASE), but apparently that's not recent enough.

So, that's one part of the solution, but then the second part of my issue seems that `@JsonProperty(required = true)` doesn't cause a field to not be marked optional in the Swagger spec my other project, while this does work in the demo project. Any idea what could be causing this or where I could check?

**Comment by raderio** [comment]
Maybe some issues with dependencies, try to put all jackson dependencies to be the first ones.

However, this is not a issue related to springfox.

**Comment by dilipkrish** [comment]
@breun and @raderio thanks for the helpful conversation! Im sure it will be useful to folks who will come here first to check. big 👍

**Comment by breun** [comment]
I think the issue is indeed not in SpringFox, so I'll close this issue. If I find the cause, I'll add a comment here.

**Comment by breun** [comment]
After looking at this again we found that this issue occurs when `springfox-bean-validators` is present.

This is what we have observed:

1. First `ModelPropertyBuilder#required` (correctly) shows that the non-nullable Kotlin field is required (because `jackson-module-kotlin` adds the `@JsonProperty(required = true)` annotation to all non-nullable Kotlin fields).
2. Afterwards `springfox.bean.validators.plugins.schema.NotNullAnnotationPlugin#apply` runs and overwrites the `required` field purely based on whether the field is annotated with `javax.validation.constraints.NotNull`.

**Comment by dilipkrish** [comment]
@breun if it is missing it will not mark it as not required

**Comment by breun** [comment]
Indeed, and I’d say that’s it’s kind of silly to have to annotate a field with non-nullable type as not null. It’s already determined that the field is required based on Jackson annotation, so why does the NotNullAnnotationPlugin ignore that information?

**Comment by dilipkrish** [comment]
@breun Its the way that the plugin architecture works. Bean validation plugins do not know what other plugins may have been applied (including consumer library plugins). May be your bug is that its not picking up the `JsonProperty` annotation. Perhaps a breaking test would be in order in this class.

https://github.com/springfox/springfox/blob/4427e23933629d1dce3ac2a80f7c8cd4d75f8ef6/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java#L63
