### ISSUE TITLE
try it out

### ISSUE THREAD

**Issue by ljp510016132** [springfox/springfox#2029]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by ljp510016132** [comment]
hello,when user @RequestParam, I try to test by "try it out",find error "Required String parameter 'date' is not present",please help me!

my code:

    @ApiOperation(value="测试RequesetParam", notes="测试RequesetParam")
    @ApiImplicitParams({
            @ApiImplicitParam(name = "date", value = "日期：2017-09-01", required = true, dataType = "String",paramType="path"),
            @ApiImplicitParam(name = "name", value = "名称", required = false, dataType = "String")
    })
    @GetMapping("/test")
    public String test(@RequestParam(required = true,value = "date")String date,
                               @RequestParam(required = false,value = "name")String name) throws RemoteException {
        return date+wharfName;
    }

**Comment by dilipkrish** [comment]
@ljp510016132 could you try without the `@ApiImplicitParams` annotation
