### ISSUE TITLE
How can make the custom annotation work right in the Swagger

### ISSUE THREAD

**Issue by Kasthuribai89** [springfox/springfox#2030]
I'm including a custom annotation in my model, and there is a required (boolean) attribute there that I want to get the right value(true/false) in the swagger UI

I always get "false" in the api-docs json

```java
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
public @interface JsonField {

	// field name, supports nesting
	String value() default DEFAULT_NONE;

	// if the property is required
	boolean required() default true;

	// default value to use if not found
	// will implicitly make required=false
	String defaultValue() default DEFAULT_NONE;

	// default string which is unlikely to conflict
	// with any real string provided by a user
	public static final String DEFAULT_NONE = "\n\t\t\n\t\t\n\uE000\uE001\uE002\n\t\t\t\t\n";
}
```
 
if I set the @JsonField(required = true) String value.  I see it always as "false"

How can I make it work

Thanks,
Kasthuribai

**Comment by raderio** [comment]
https://github.com/springfox/springfox/issues/2032

**Comment by dilipkrish** [comment]
You need to create a [plugin that can read](http://springfox.github.io/springfox/docs/current/#plugins) your annotation.
