### ISSUE TITLE
Make possible to create custom annotation that is annotated with @ApiModelProperty

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#2032]
Add `ElementType.ANNOTATION_TYPE` to `@ApiModelProperty`. This will make possible to create custom annotations, such like

```
@ApiModelProperty("Should be greater than 1")
@Min(1)
@Target(value= ElementType.FIELD)
@Retention(value= RetentionPolicy.RUNTIME)
public @interface Price {
}
```

so, no need to specify two annotations for field
```
@ApiModelProperty("Should be greater than 1")
@Min(1)
long price;
```
will be 
```
@Price
long price
```
is more clear, and if we have price in multiple places it is easier to refactor

**Comment by dilipkrish** [comment]
This is not possible as that is a class that belongs to [swagger-core](https://github.com/swagger-api/swagger-core)

**Comment by raderio** [comment]
https://github.com/swagger-api/swagger-core/issues/2428
