### ISSUE TITLE
HashMap<String,Object> Does not show up in parameters

### ISSUE THREAD

**Issue by malkochoglu** [springfox/springfox#2033]
Hi,
I have an API Model Class that I use as controller input. When I generate swagger ui by sprinfox, all fields except for a HashMap field are shown as text boxes under Parameters. I was expecting to show it. Am I missing something or can't swagger show HashMap fields like others under Parameters?

My controller method
```
    @RequestMapping(method = RequestMethod.POST)
    public ResponseEntity<XObject> createTemplate(@ModelAttribute @Valid @RequestBody XObject obj) 
```
API Model Class

```
@ApiModel(value = "XObject")
public class XObject {
    @NotNull
    @ApiModelProperty(value = "Prm 1", position = 0, required = true)
    private Integer abc1;
     @ApiModelProperty(value = "Parameter Map",dataType ="java.util.HashMap" ,position = 1, required = false)
    private HashMap<String, Object> myMap;

    public XObject() {
    }

    public Integer getAbc1() {
        return abc1;
    }
    public void setAbc1(Integer a) {
        this.abc1= a;
    }

    public HashMap<String, Object> getMyMap() {
        return myMap;
    }

    public void setMyMap(HashMap<String, Object> myMap) {
        this.myMap= myMap;
    }
}
```

**Comment by dilipkrish** [comment]
That is because `HashMap<String, Object>` is equivalent to `any` type. You can send in anything in place of myMap.

**Comment by malkochoglu** [comment]
Thanks for reply. I tried Map without any generics signature, I was able to see a text box. When I change it to HashMap again without generics signature, again it is not visible. But this is not the way I want to do. Is there a way or work around to show HashMap<Sting, Object> or HashMap<String, String>?
Thanks

**Comment by dilipkrish** [comment]
@malkochoglu 

> I tried Map without any generics signature, I was able to see a text box.

That doesnt sound right. Map is the same as HashMap<Object, Object>.

**Comment by eastwoodwang** [comment]
if i use Map and just give the example for tester, what i should do ?

**Comment by dilipkrish** [comment]
@eastwoodwang I think you can use something like this `@ApiModelProperty(example="{'some-key': 'some-value'}"`
