### ISSUE TITLE
415 error from call any endpoint from swagger-ui

### ISSUE THREAD

**Issue by adiIspas** [springfox/springfox#2036]
I want to make a call from swagger-ui.html page for a GET endpoint. But I receivedthe 415 error code.
My annotations for method is:

```
@ApiOperation(value = "...", response = MyClass.class)
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "...",
                    responseHeaders = @ResponseHeader(name = "ResponseEntity", description = "...", response = ResponseEntity.class))})
    @RequestMapping(value = "/{id}", method = RequestMethod.GET, produces = "application/json")
    @ResponseBody
    public ResponseEntity getMethod(
            @ApiParam(value = "...", required = true) @PathVariable("id") Long id) { ... }
```

And the response headers is:

```
{
  "pragma": "no-cache",
  "date": "Wed, 13 Sep 2017 13:10:27 GMT",
  "x-content-type-options": "nosniff",
  "server": "Apache-Coyote/1.1",
  "x-frame-options": "DENY",
  "access-control-allow-methods": "POST, GET, PUT, OPTIONS, DELETE, PATCH",
  "accept": "application/json",
  "access-control-max-age": "3600",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Access-Control-Request-Method, Access-Control-Request-Headers, Origin, X-Requested-With, Authorization, Accept, Origin, Content-Type, X-Requested-By, version",
  "content-length": "0",
  "x-xss-protection": "1; mode=block",
  "x-application-context": "application:production,docker-db,sql-debug:8081",
  "expires": "0",
  "content-type": null
}
```

What is wrong and how I can call endpoints?

**Comment by dilipkrish** [comment]
@adiIspas I suspect its not hitting the correct endpoint. Seems like docker is involved and Im not sure what url swagger-ui is attempting to hit. You could try using a rest client other than swagger and see if that works.

**Comment by adiIspas** [comment]
I tried in Postman and work all endpoint.

**Comment by adiIspas** [comment]
> I tried in Postman and works all endpoint

**Comment by dilipkrish** [comment]
In that case its a problem in swagger-ui. My guess is swagger-ui isn't doing something right. What does the generated curl command in the swagger-ui say?

**Comment by adiIspas** [comment]
Curl is: `curl -X GET --header 'Accept: application/json' 'http://localhost:8081/web/house/123'`

**Comment by adiIspas** [comment]
Any ideea to resolve that @dilipkrish? Thanks!

**Comment by adiIspas** [comment]
@dilipkrish I found the problem. WinOs vs Linux :)) I called from Windows and for curl I need `"` not `'`. But still I need to have in header 'content-type:application/json'. How I can set that?

**Comment by dilipkrish** [comment]
Not sure what u mean by `general route in swagger-ui` aren't they all operations?
