### ISSUE TITLE
404 when use swagger2-ui with spring-boot-1.5.6

### ISSUE THREAD

**Issue by ihappyk** [springfox/springfox#2037]
Please take the time to search the repository, if your question has already been asked or answered.

```
<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.6.1</version>
        </dependency>
```

 Get localhost:8080/v2/api-docs is ok, but localhost:8080/swagger-ui.html returns 404 .
Spring-boot version is 1.5.6.RELEASE

# Steps to Reproduce

1. Clone https://github.com/ihappyk/Springboot-practice.git
2. Change the version of Swagger Jars to 2.6.1 in Pom.xml
2. Start application via mvn spring-boot:run 
3. Open URL http://localhost:8080/api-docs
4. Open URL http://localhost:8080/swagger-ui.html

Similar to the issue #1747

**Comment by adiIspas** [comment]
Remove this dependencies and update versions to 2.7.0. If you try localhost:8080/swagger-resources/swagger-ui.html you will see work good.

**Comment by ihappyk** [comment]
@adiIspas i am still facing the same issue. 👎

**Comment by adiIspas** [comment]
You have a 404 response for hole page or for another links from page, for example link to `/configuration/ui`?

**Comment by ihappyk** [comment]
@adiIspas below screenshot has the list of swagger url's that is available when i run the app.
<img width="1013" alt="screen shot 2017-09-19 at 8 26 37 pm" src="https://user-images.githubusercontent.com/3413629/30599197-5c36f3ce-9d79-11e7-8934-b8df6f9338d0.png">

**Comment by imkratos** [comment]
i use spring-boot version 1.5.6.RELEASE,swagger2 2.7.0,has same problem,need add some config in WebConfiguration
```java 

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
```
it's working

**Comment by ihappyk** [comment]
@imkratos  can you share the full class file?

**Comment by imkratos** [comment]
```java

**Comment by srouquette** [comment]
@imkratos if you are using a spring boot application with autoconfiguration, the problem is that you have a @EnableWebMvc and it disables spring boot autoconfiguration.

but I still have the problem even without @EnableWebMvc. I have a custom config so I had to override WebMvcConfigurerAdapter, I'm not sure if it conflicts with swagger-ui. In the end, I also had to add the resource config in my class to load swagger-ui.

@Configuration
@AutoConfigureAfter(DispatcherServletAutoConfiguration.class)
public class WebConfig extends WebMvcConfigurerAdapter {
	
	private static final Logger log = LoggerFactory.getLogger(Application.class);
	
	private static final String[] CLASSPATH_RESOURCE_LOCATIONS = {
	       "classpath:/static/" };
	
	@Autowired
	private Environment env;

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		super.addResourceHandlers(registry);
        /*registry.addResourceHandler("swagger-ui.html")
        	.addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
        	.addResourceLocations("classpath:/META-INF/resources/webjars/");*/
	}

**Comment by dilipkrish** [comment]
@srouquette it may be an ordering issue.

**Comment by denis111** [comment]
I have tried with Spring Boot 2.0.0.M5 and also 404 and this workaround doesn't work:
`@Configuration
@AutoConfigureAfter(DispatcherServletAutoConfiguration.class)
public class WebMvcConfig extends WebMvcConfigurationSupport {
  @Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    super.addResourceHandlers(registry);
    registry
        .addResourceHandler("swagger-ui.html")
        .addResourceLocations("classpath:/META-INF/resources/");

    registry
        .addResourceHandler("/webjars/**")
        .addResourceLocations("classpath:/META-INF/resources/webjars/");
  }
}`
I see in logs Mapped URL path [/swagger-ui.html] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler] but still have 404.

**Comment by dilipkrish** [comment]
@denis111 For spring boot you don't need to do the above changes

**Comment by denis111** [comment]
@dilipkrish Sure, first i tried it without this changes but also had 404 so I don't know what to do more.

**Comment by imkratos** [comment]
@denis111   u can see spring boot starting info log , swagger-ui.html is mapped and check config

**Comment by denis111** [comment]
@imkratos If i don't add that "addResourceHandlers" it's not mapped in logs and I get 404. If i do log says it's mapped but it seems to be mapped nowhere, I still get 404. BTW I run it as standalone spring boot application (not war).

**Comment by dilipkrish** [comment]
@denis111 Id ask the question, what is making your application  such that you're having to do the `addResourceHandlers` manually? Spring boot makes it so that you don't have to.

**Comment by denis111** [comment]
@dilipkrish I don't have to do addResourceHandlers manually, I just wanted swagger-ui to work and I tried this workaround suggested in this topic. Anyway, today I've done something(maybe updates something) and now it works without addResourceHandlers. Thanks everybody for support.

**Comment by silentsnooc** [comment]
@denis111 Any idea what you did? 

I've been following [this tutorial](http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api). I added the dependencies

```xml
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>2.7.0</version>
</dependency>

<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.7.0</version>
</dependency>
```

and created the configuration:

```java
@Configuration
@EnableSwagger2
public class SwaggerConfig {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }
}
```

from the logs I see that the swagger endpoints are there:


![screenshot from 2017-11-05 20-58-45](https://user-images.githubusercontent.com/1429426/32418527-2504b144-c26c-11e7-8f08-eeb7162737c2.png)

but like others, I'm getting a 404 when accessing [`http://localhost:8080/spring-security-rest/api/swagger-ui.html`](http://localhost:8080/spring-security-rest/api/swagger-ui.html).

**Comment by imkratos** [comment]
@simonamc 
u log just swagger api it's mapped,but swagger-ui.html not mapped, it's different, u can check the following
```java
       registry.addResourceHandler("swagger-ui.html")
        	.addResourceLocations("classpath:/META-INF/resources/");
```

**Comment by dilipkrish** [comment]
@silentsnooc it is very likely that spring security is interfering with your web jar being visible

**Comment by silentsnooc** [comment]
@dilipkrish Yes, in fact that was the issue in my case. Thank you :)

**Comment by prabhakar349** [comment]
@silentsnooc  were you able to get the swagger ui working?

**Comment by NickEngland** [comment]
I've also had this issue. Investigating it further I found that I got the 404 when the jar was built on Ubuntu16, but not on Windows or Ubuntu14, or Ubuntu17.

Is Spring Security OS dependent? The effective POMs were identical, and the java and maven versions were the same .targz file manually installed onto fresh VMs.

I do have @EnableWebMvc annotation once, in the WebConfiguration extends WebMvcConfigurerAdapter class. If I remove it, it stops working on all systems.

**Comment by dilipkrish** [comment]
@NickEngland seems like a classloader issue that is environmental. If yours is a spring boot app you shouldn't have to do an `@EnableWebMvc`

**Comment by gannonex** [comment]
Had the same issue, but nothing above helped. Started to wonder if it was a problem with the version 2.7.0. I had also followed [this](http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api) tutorial attempted to adapt it to gradle adding this to build.gradle:

compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.7.0'

It seems this was horribly wrong.

While looking at another project of ours I found that we used the following instead for 2.4.0:

compile "io.springfox:springfox-swagger2:${swaggerVersion}"
compile "io.springfox:springfox-swagger-ui:${swaggerVersion}"
compile "io.springfox:springfox-bean-validators:${swaggerVersion}"

It solved my problem with 2.4.0 so I tried it with 2.7.0 and it also worked. Perhaps, if you are having this problem as a gradle project, this might solve your issue too.

Good luck!

**Comment by dilipkrish** [comment]
Sounds like it was a problem with your browser cache. 😕

**Comment by ewillia1983** [comment]
I had the same setup as silentsnooc above, spring boot 1.5.9, swagger2 and swagger-ui 2.7.0.  It did not map the /swagger-ui.html endpoint for me until I added the WebMvcConfig as noted above.  One small change though, 

`.addResourceHandler("/swagger-ui.html")`

The code above did not have the /.

**Comment by DemianTinkiel** [comment]
I would like to report the same issue. All endpoints except swagger-ui working fine.
```
    compile 'io.springfox:springfox-swagger2:2.6.1'
    compile 'io.springfox:springfox-swagger-ui:2.6.1'
```

Things I tried and did not work
* Added swagger ui to resource handler.
* No @enablewebmvc anywhere.
* Tried ignoring the swagger endpoints in my WebSecurityConfigurerAdapter but this seems to have no effect, the endpoints that do work do not need this.

springBootVersion = '1.5.6.RELEASE'

**Comment by dilipkrish** [comment]
You may need to ignore `swagger-ui.html**` since it has `#!` parameters at the end

**Comment by parallelbgls** [comment]
Same issue to @denis111 @DemianTinkiel

swagger2 = 2.7.0
swagger-ui = 2.7.0
springBootVersion = '1.5.9.RELEASE'

**Comment by parallelbgls** [comment]
Clear maven repository cache and reinstall all dependencies it again, issue disappeared.

By the way I change editor from eclipse java to eclipse j2ee. I don't know if this would cause the issue.

**Comment by DemianTinkiel** [comment]
I just tested this with 2.8 + adding swagger-ui.html** to WebSecurityConfigurerAdapter  ignore + clearing build cache. No Joy :'(
relevant parts of log
`18:22:17.217 INFO  [main] o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/documentation/swagger-ui.html**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
18:22:18.213 INFO  [main] o.s.s.web.DefaultSecurityFilterChain - Creating filter chain: Ant [pattern='/swagger-ui.html**'], []
18:23:54.889 ERROR [http-nio-0.0.0.0-8080-exec-1] o.i.s.error.GlobalExceptionHandler - unknown request to path /swagger-ui.html
`

**Comment by dilipkrish** [comment]
Could you create a fork of [the demos](https://github.com/springfox/springfox-demos) that replicates the issue @DemianTinkiel? I'll have a look.

**Comment by fredssbr** [comment]
I had the same problem. I was following this tutorial here http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api. 

I had a default @RequestMapping from a leftover test that was mapped to the root of the application.

```java
   @RequestMapping(method = RequestMethod.GET)
    public Greeting greeting() {
        return new Greeting("Greetings from Planet Earth!");
    }
```

I removed that (no default @RequestMapping), ran again and everything was working fine.
**LESSON: no default root mapping with Swagger UI.**

**Comment by dilipkrish** [comment]
@fredssbr Thanks for the tip. Not sure if there is an elegant fix for this

**Comment by oaoit** [comment]
User Spring Boot add the following code in the Application file can fix.

  @Bean
  public WebMvcConfigurerAdapter adapter() {
    return new WebMvcConfigurerAdapter() {
      @Override
      public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
            .addResourceLocations("classpath:/META-INF/resources/swagger-ui.html");
        registry.addResourceHandler("/webjars/**")
            .addResourceLocations("classpath:/META-INF/resources/webjars/");

        super.addResourceHandlers(registry);
      }
    };
  }

I use spring boot version 1.5.10-REALSE,springfox version 2.8.0.

**Comment by lawrencewamala** [comment]
@oaoit solution worked for me after 2 days of hustling. Many thanks!

**Comment by sorinvasilescu** [comment]
Issue for me was what @fredssbr described.
But for the record, I don't find being unable to use root mapping as an acceptable side-effect of Swagger-UI.

**Comment by rssarto** [comment]
Hi I was having the same problem... After applying the below configuration the problem was solved:

1. Spring Security Configuration - I have a WebSecurityConfig class extending WebSecurityConfigurerAdapter and here I used the configuration below:

![image](https://user-images.githubusercontent.com/13918367/37852744-8a61b164-2ec2-11e8-94b6-a05a11520fba.png)

2. WebMvcConfigurerAdapter - I have a WebConfig class extending WebMvcConfigurerAdapter and here I used the configuration below:

![image](https://user-images.githubusercontent.com/13918367/37852853-f6e54abc-2ec2-11e8-8ecc-fa0bfbc91ef9.png)

**Comment by dilipkrish** [comment]
@rssarto You don't need step 2 for spring boot applications. Also it would be nice if you pasted code with formatting rather than images. Hard to copy code from an image to replicate the problem

**Comment by aslackers** [comment]
I have tried add addResourceHandlers, but it doesn't work(create bean name error). Then I run application with debug, and look up the log, found this info:

> 2018-03-26 21:43:47.414  INFO 43267 --- [           main] b.a.s.AuthenticationManagerConfiguration : 

Using default security password: 2d2f9a3d-660e-427b-9cad-5ecc3ac46d49

use this password, and username "user", it works!!!

**Comment by conan-z** [comment]
I had the same problem on my own test project today. The root cause of my problem is that **there is already a handler mapped at the base URL**. (This handler seem to take precedence over the handler of swagger-ui). As a result, the swagger ui is hidden

The solution is simple: I remapped that handler at a different URL and voila, the swagger-ui.html is there!

Relavent dependency (Gradle):
    compile("org.springframework.boot:spring-boot-starter-web:1.5.11.BUILD-SNAPSHOT")
    compile ("io.springfox:springfox-swagger2:2.7.0")
    compile ("io.springfox:springfox-swagger-ui:2.7.0")

**Comment by dilipkrish** [comment]
@aslackers I dont follow what the problem is, could you perhaps elaborate or state it differently? Also if you believe this is a new issue create one. This ☝️ is closed.

**Comment by aditi-goel** [comment]
@dillipkrish I am facing same issue which u were facing with spring boot and swagger. Can you please tell me what changes you made. And one more question we have micro services project so our rest api is in different module and main class class is in different module. Does it make any difference. Can can you please tell me what changes you made in your application what make it work for you?

**Comment by dilipkrish** [comment]
What issue are you facing @aditi-goel? Are you seeing a 404 error? Yes different modules should work.

Also take a look at [the demos](https://github.com/springfox/springfox-demos) project.

**Comment by dilipkrish** [comment]
@jonje Somehow spring boot auto configuration for the web is not kicking in. Either you have a configuration bean that overrides it or you have `EnableWebMvc`. If you haven't done anything special regarding a dynamic servlet or changed the context path, swagger-ui should be available at `http://localhost:8080/swagger-ui.html`

**Comment by AnkBurov** [comment]
I removed @EnableWebMvc annotation and /swagger-ui.html worked like a charm.

**Comment by jonje** [comment]
@dilipkrish Do you know what type of configuration bean could possibly cause this?

**Comment by dilipkrish** [comment]
There can be many causes for this...
- most common is if you enable spring security you need to be careful about either making the springfox resources public or ensuring that if swagger-ui is public it can access the resources (inspecting the browser console should not have 401 errors)
- The second cause is if you have a spring boot app and have the `EnableWebMvc` annotation set. In which case you need to ensure you add the resource handlers for swagger ui manually
- Lastly there might a case where another endpoint is already responding to `<host:port>/swagger-ui.html` because you might have a RequestMapping that is like `@RequestMapping("/{path}") at the root of a controller.

**Comment by Sytten** [comment]
Not sure why it his the case, but I also needed to add a web mvc configurer. I do use a requestmapping at the root of my controller to add `/api` everywhere. Anyway there is the kotlin + spring 5 version:
```
@Configuration
@EnableSwagger2
class SwaggerConfig {

    @Bean
    fun api(): Docket = Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.basePackage("com.github"))
            .build()

    @Bean
    fun adapter(): WebMvcConfigurer = object : WebMvcConfigurer {
        override fun addResourceHandlers(registry: ResourceHandlerRegistry) {
            registry.addResourceHandler("swagger-ui.html")
                    .addResourceLocations("classpath:/META-INF/resources/swagger-ui.html")
            registry.addResourceHandler("/webjars/**")
                    .addResourceLocations("classpath:/META-INF/resources/webjars/")

            super.addResourceHandlers(registry)
        }
    }
}
```

**Comment by dilipkrish** [comment]
@Sytten Is your repo shareable? Just curious to see why its needed

**Comment by Sytten** [comment]
@dilipkrish For now it is public: https://github.com/Sytten/degel-backend/

**Comment by dilipkrish** [comment]
Thank you @Sytten!

**Comment by wisien92** [comment]
@dilipkrish I have simillar issue  to @NickEngland  - I can build it and run on windows fine and there is 404 on ubuntu 16 (not using EnableMVC). Swagger json is fine so it's only the UI that has some issues. Any suggestions on how to solve it?

**Comment by dilipkrish** [comment]
@wisien92 how are u running the application?

**Comment by wisien92** [comment]
I am using docker to build jar then start the artifact

**Comment by dilipkrish** [comment]
@wisien92 Its easiest if you can create a minimal repository and build instructions that I can see what the problem might be. Its hard to diagnose a problem without any facts.

**Comment by wisien92** [comment]
@dilipkrish suer - silly of me that I forgot. This setup is working fine on windows machine as well as on Ubuntu17. But I get 404 on Linux Mint 18 Sarah distribution. Swagger Json is fine so I am considering moving UI to seperate docker service - but the configuration is much easier on Spring side.

the basic docker file

    FROM maven:3.5-jdk-8 AS build
    WORKDIR /app
    # Copy sources
    COPY src ./src
    COPY pom.xml .
    # Build app
    RUN mvn clean package -DskipTests
    FROM maven:3.5-jdk-8 AS app
    # Copy files from first container
    COPY --from=build /app/target/target.jar .
    # Start app
    CMD ["java", "-jar", "expo-backend.jar"]


and later in docker compose


     version: '3.4'
     services:
      spring:
        build: .
        ports:
          - "80:8080"
        entrypoint: ["java", "-jar", "expo-backend.jar"]
        volumes:
          - maven_cache:/root/.m2
     volumes:
       maven_cache:

**Comment by rs-renato** [comment]
I have upgrade from 2.7.0 to 2.8.0 and I have this same issue, despite of dont use spring boot. :(
Still facing 404 for swagger-ui.html, since configuring the handlers.

2.7.0 works fine.

**Comment by mpanicker** [comment]
I pretty much tried everything in the posts above but the issue would stubbornly refuse to go away.
Finally by trial and error,  I commented out the swagger-ui.html mapping(in WebFluxConfig.java) and it worked. I am using 
1. org.springframework.cloud:spring-cloud-dependencie:Finchley.SR1
2. org.springframework.boot:spring-boot-starter-webflux
3. org.springframework.boot:spring-boot-starter-web(needed for Swagger)
4. io.springfox:springfox-swagger2:3.0.0-SNAPSHOT //support for Reactive apps is not in main release yet
5. io.springfox:springfox-swagger-ui:3.0.0-SNAPSHOT
6. io.springfox:springfox-spring-webflux:3.0.0-SNAPSHOT

@Configuration
public class WebFluxConfig implements WebFluxConfigurer {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {

        //swagger resource
        //registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources");
        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
        registry.addResourceHandler("/swagger/**").addResourceLocations("classpath:/static/swagger/");
    }
}

Hope this helps someone

**Comment by mpanicker** [comment]
I created a sample application that uses Spring 5 Reactive WebFlux and Springfox 3.0.0-SNAPSHOT
that gets around the 404 issue for swagger-ui.html
https://github.com/mpanicker/reactive-spring-swagger

**Comment by BahgatMashaly** [comment]
I have encountered this problem before and the problem was in the below line in application.properties
spring.resources.add-mappings=false

remove it or change it's value to true

**Comment by sharecapital** [comment]
if you has add following code, but still get 404 when get file **/webjars/springfox-swagger-ui**, you can clean your browser cache then try again, another way is use the google chrome clean mode to open the swagger, command(ctrl) + shift + N can open chrome clean mode, this mode will not use the cache file.
`
    registry
        .addResourceHandler("/swagger-ui.html")
        .addResourceLocations("classpath:/META-INF/resources/");
    registry
        .addResourceHandler("/webjars/**")
        .addResourceLocations("classpath:/META-INF/resources/webjars/");
`

**Comment by anuragthakur16** [comment]
I had the same problem , but removing @enableWebMVC solved it for me
