### ISSUE TITLE
How to generate the api-docs.json file during compilation(without bootstrapping the application)

### ISSUE THREAD

**Issue by half-dead** [springfox/springfox#2038]
HI, so far, I've got it working perfectly with springfox-swagger2 and springfox-swagger-ui-rfc6570, well done for this awesome project.

I've got some questions here, we think that adding a "/v2/api-docs" endpoint directly inside the application is a good idea, it's quite convenient during developing and testing, but may be a little bit risky when it's in a production environment, another thing is that our documentation is hosted at a different location other than the real web server.

So we are looking for a way to generate the swagger file without bootstrapping the application, maybe something like a maven/gradle plugin? I've been searching and so far nothing came up.

Many thanks!

**Comment by dilipkrish** [comment]
@half-dead thanks for your kind words. Please look at the awesome [Swagger2Markup](https://github.com/Swagger2Markup/swagger2markup) by @RobWin

**Comment by RobWin** [comment]
@half-dead You can have a look at https://github.com/Swagger2Markup/spring-swagger2markup-demo.
Springfox is a testCompile dependency and not included at runtime. You only need Swagger annotations at compile type.
We generate the Swagger JSON file in a unit test and convert it into AsciiDoc with Swagger2Markup at build-time. We convert AsciiDoc into HTML/PDF with Asciidoctor at build-time. You can copy the HTML documentation either as a static file into your Application Jar-File or serve it from another web server.
You can even include test snippets (HTTP Request/Response examples) from your test into your documentation.

**Comment by half-dead** [comment]
Thanks for responding, I'll take a look.

**Comment by bob-walters** [comment]
In the example quoted, the swagger generation is actually done by a specific test.  I.e. via that test the service is brought up, and the swagger generated by springfox is fetched and thus can end up being a product of the testing phase of the build.  See https://github.com/Swagger2Markup/spring-swagger2markup-demo/blob/master/src/test/java/io/github/robwin/swagger2markup/petstore/Swagger2MarkupTest.java

**Comment by ptheohar** [comment]
@half-dead regarding this part
> but maybe a little bit risky when it's in a production environment

Docket builder has an `enabled` option. You can set it to `false` in your production environment

**Comment by tharindusathis** [comment]
@RobWin can we only generate json instead md file?

**Comment by dilipkrish** [comment]
That would be a question for a different project @tharindusathis
