### ISSUE TITLE
Spec generation is non-deterministic

### ISSUE THREAD

**Issue by yissachar** [springfox/springfox#2042]
The swagger.json generated by SpringFox varies between builds, even if the underlying code did not change.

The methods for a particular API are not guaranteed to be generated in any particular order, instead being ordered at random every time the spec is generated. While this doesn't affect the functionality of the swagger.json file, it is annoying for our workflow where we commit both swagger.json and a generated client to git. Given that the swagger.json is constantly changing due to the random method order, this results in spurious diffs, and makes actual changes harder to see.

**Comment by yissachar** [comment]
It seems everything is ordered by path, but when the path is the same for two methods, this causes problems.

```
@PostMapping
public void doSomething(@RequestBody Foo foo) {
// ...
}

@PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public void doAnotherThing(@RequestParam MultipartFile file) throws IOException {
// ...
}
```

In this example, the order of the two methods will change from run to run.

**Comment by dilipkrish** [comment]
Thanks for reporting! Will take a look

**Comment by dilipkrish** [comment]
Moving it to oas3 support since this situation is not supported in swagger 2.0
