### ISSUE TITLE
Simple @PathVariable Api results in a 406 error in swagger-ui

### ISSUE THREAD

**Issue by NeVeX** [springfox/springfox#2044]
I have created a simple API, [that can been seen here](https://github.com/NeVeX/springfox-issue), that cannot render the `swagger-ui.html` page - it gives a WhiteLabel error with a `406` status.

In the above repo, the [README.md](https://github.com/NeVeX/springfox-issue/blob/master/README.md) has information about running and testing for the problem locally.

The above is a simple API that has a `@PathVariable`.
When using SpringFox and navigating to the `/swagger/swagger-ui.html`, I get the following:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Sep 21 13:53:50 PDT 2017
There was an unexpected error (type=Not Acceptable, status=406).
Could not find acceptable representation
```

But, if you hit the `/swagger/api-docs` endpoint, you get the json payload about the API:
```
{"swagger":"2.0","info":{"description":"Api Documentation","version":"1.0","title":"Api Documentation","termsOfService":"urn:tos","contact":{},"license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0"}},"host":"localhost:8080","basePath":"/swagger","tags":[{"name":"swagger-controller","description":"Swagger Controller"}],"paths":{"/{message}":{"get":{"tags":["swagger-controller"],"summary":"pathHello","operationId":"pathHelloUsingGET","consumes":["application/json"],"produces":["application/json"],"parameters":[{"name":"message","in":"path","description":"message","required":true,"type":"string"}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/MessageDto"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}}},"definitions":{"MessageDto":{"type":"object","properties":{"message":{"type":"string"}}}}}
```

I've tried different versions of SpringFox and SpringBoot, but got the same problem. 

Note, the api works fine though; i.e. `http://localhost:8080/swagger/hello`.
```
{"message":"hello"}
```

##### Library versions:
* SpringFox `2.7.0`
* SpringBoot `1.5.6.RELEASE` 

##### Maybe related issues:
* https://github.com/springfox/springfox/issues/1573 - thought this was closed with a solution it seems

**Comment by dilipkrish** [comment]
This error is happening because your request mapping is consuming the `/swagger-ui.html`. If you change your request mapping to this on the swagger controller class, you'll see what I mean.

```java
@RestController
@RequestMapping("/api")
public class SwaggerController {
...
```
This is not really a bug.

**Comment by diegotissoni** [comment]
> This error is happening because your request mapping is consuming the `/swagger-ui.html`. If you change your request mapping to this on the swagger controller class, you'll see what I mean.
> 
> ```java
> @RestController
> @RequestMapping("/api")
> public class SwaggerController {
> ...
> ```
> 
> This is not really a bug.

What if I can't change the path mapping for the endpoint consuming /swagger-ui.html? Is there something else I can do?

**Comment by amardeepkhera** [comment]
Hi @dilipkrish,
Can you please confirm if this issue has been addressed in Swagger 3 SNAPSHOT?
