### ISSUE TITLE
Code parameter to @ApiOperation does not override documentation

### ISSUE THREAD

**Issue by jasonab** [springfox/springfox#2045]
Springfox(swagger-ui) 2.7.0

When I set @ApiOperation(code=201), I would expect the main response body to show Response Class (Status 201) instead of (Status 200).

I understand that using the @ResponseMapping annotation can override this, but I'm not clear what other effect that might have on Spring.

**Comment by dilipkrish** [comment]
You mean `@ResponseStatus`? Yes that the right way to do it.

**Comment by jasonab** [comment]
Sure, I guess my point it that @ResponseStatus changes Spring's behavior. I'd rather control the documentation using documentation annotations rather than adding a Spring behavior annotation.

**Comment by dilipkrish** [comment]
Im confused do you want it to return 201 or 200? And if you expect 201 why not indicate the response status. The documentation is to support the implementation and not the other way around

**Comment by jasonab** [comment]
Right now my code uses the ResponseEntity to return the code, not the annotation. As far as I understand, that's a legitimate Spring use case. I'd rather not have to use an annotation to drive behavior if I'm already driving it via code, but it appears that I have to in order to get the documentation to read correctly.

I'm just expressing a desire to support a usage of Spring that doesn't use ResponseStatus, since it's not the only way to return a certain status.

**Comment by dilipkrish** [comment]
This is not a simple change. Will address this as part of implementing 3.0 of the spec

**Comment by glmars** [comment]
@dilipkrish so what is purpose of ` @ApiOperation.code` right now?

**Comment by glmars** [comment]
I use `HttpServletResponse.setStatus` with a status code that depends on some conditions so I could not use the `ResponseStatus` annotation. I thought I could use `@ApiOperation.code` to select the default response code in the documentation, but it doesn't work completely (the documentation shows 200, but this code is never returned by my controller :( )
