### ISSUE TITLE
swagger-ui version 2.7

### ISSUE THREAD

**Issue by 546168949** [springfox/springfox#2049]
When using swagger- UI 2.7 ,  click try it out! the invoke url following:
curl -X GET --header 'Accept: */*' 'http://**/**/**/find/1{?value,page,limit}&value=2&page=1&limit=20'
/find{?flag,value,page,limit}?page=1
That causes code 400 error!

**Comment by dilipkrish** [comment]
You'd need to set `docket.enableUrlTemplating(false)`

**Comment by 546168949** [comment]
Thank you, that's it
