### ISSUE TITLE
spring @Aspect can not work with swagger2

### ISSUE THREAD

**Issue by longzl2015** [springfox/springfox#2050]
pom.xml version info:

 - springfox-swagger2: 2.5.0 
 - swagger-core: 1.5.10
 - springfox-swagger-ui: 2.6.1
 - springboot: 1.5.3

I has a project with swagger2 and springboot. 

The project code without @Aspect works very well.The code reads as follows.

    public interface TestApi {
        WfExecution test(Long temp);
    }

    @Api(value = "TestAPI")
    @RequestMapping(value = "/test")
    @RestController
    public class TestApiImpl implements TestApi {
    
        @Override
        @RequestMapping(value = "/test")
        @ApiOperation(value = "", notes = "", produces = MediaType.APPLICATION_JSON)
        public WfExecution test(@ApiParam(value = "", required = true) @RequestParam(required = true, value = "temp")
                                            Long temp) {
            return new WfExecution();
        }
    }

the right result:

[![success picture][1]][1]

But when I add the follow code, the swagger-ui doesn't show the test-api-impl.

    @Aspect
    @Component
    public class LoggerAop {
        @Before("execution(* com.XXX.controller.impl.TestApiImpl.*(..))")
        public void doBeforeAdvice(JoinPoint joinPoint){
                System.out.println("XXX");
        }
    }

the error result:

[![fail picture][2]][2]

Is there a conflict between swagger and spring AOP?

  [1]: https://i.stack.imgur.com/if4a5.jpg
  [2]: https://i.stack.imgur.com/H2JrC.jpg

**Comment by dilipkrish** [comment]
Please upgrade to 2.7.0

**Comment by longzl2015** [comment]
I upgrade to 2.7.0. But It not works.
And I find that there is one proxy class in webUi. Its method is the same as that of the TestApi class.

![image](https://user-images.githubusercontent.com/12516505/30893875-ff3ee47e-a372-11e7-8fc8-da622cd84bcc.png)

**Comment by longzl2015** [comment]
When I add the `@EnableAspectJAutoProxy(proxyTargetClass=true)` , swagger and aop work well.

![image](https://user-images.githubusercontent.com/12516505/30950785-a4fe7774-a451-11e7-977b-cd1df796b60c.png)

**Comment by Easwer** [comment]
Hi,

I am using openapi3 and spring boot 2.3.1.

I am facing the similar kind of issue.

@Aspect
@Configuration
@EnableAspectJAutoProxy(proxyTargetClass = true)
public class UserAccessAspect {}
