### ISSUE TITLE
Swagger UI is empty in spring MVC 

### ISSUE THREAD

**Issue by chiyanram** [springfox/springfox#2051]
@dilipkrish Hi , i am also facing the same problem(/v2/api-docs shows all the json but swagger-ui.html is empty) . Project is Spring MVC (4.3.3.RELEASE) swagger(2.7.0) .

My Docket Configuration is,

```java
@configuration
@enableswagger2
public class TravelSwaggerConfig {

@Bean
public Docket swaggerApi() {

    return
        new Docket(DocumentationType.SWAGGER_2)
            .select()
            .paths(PathSelectors.any())
            .apis(RequestHandlerSelectors.withClassAnnotation(TravelApi.class))
            .build();
}
}
```
My Spring configuration is,

```java
@override
public void addResourceHandlers(final ResourceHandlerRegistry registry) {

    registry.addResourceHandler("swagger-ui.html")
        .addResourceLocations("classpath:/META-INF/resources/");

    registry.addResourceHandler("/webjars/**")
        .addResourceLocations("classpath:/META-INF/resources/webjars/");
}

@override
public void configureDefaultServletHandling(final DefaultServletHandlerConfigurer configurer) {
configurer.enable();
}
```

http://localhost:8080/travel/swagger-resources/configuration/ui gives :
```json
{"docExpansion":"none","apisSorter":"alpha","defaultModelRendering":"schema","supportedSubmitMethods":["get","post","put","delete","patch"],"jsonEditor":false,"showRequestHeaders":true}
```

http://localhost:8080/travel/swagger-resources:
```json
{
"name": "default",
"location": "/v2/api-docs",
"swaggerVersion": "2.0"
}
```
Maven:

io.springfox springfox-swagger-ui 2.7.0 io.springfox springfox-swagger2 2.7.0
web.xml:

travel /
Please let me now the issue.

Thanks,
Ram

**Comment by dilipkrish** [comment]
Try removing the @Configuration in `TravelSwaggerConfig` and see if it works?

**Comment by vbnhfylbh** [comment]
Hello, I am experiencing the same issue. Removing @Configuration does not help (why should it?) - I'm getting just "Finished Loading Resource Information. Rendering Swagger UI..." in browser and no much  else. Using Spring Boot 1.5.6. Any advice? 
Thanks

**Comment by dilipkrish** [comment]
@vbnhfylbh adding a @Configuration in some situations affects how application contexts are created. 

However since you're using spring boot that shouldn't be an issue. what do you get when you navigate to `/v2/api-docs`

**Comment by vbnhfylbh** [comment]
@dilipkrish, /v2/api-docs returns valid json - all my models and methods are there.
I made a /v2/api-docs response comparison against /v2/api-docs response from working variant (showing proper Swagger UI page, I mean) which was build with Spring Boot 1.5.6 + Springfox 2.0.0 + Swagger UI 2.5.0, do not ask why such combination:)
There is a lot of little differences between them but should I bother about that? How can I output some debugging information about what is wrong with "Rendering Swagger UI"?

**Comment by vbnhfylbh** [comment]
@dilipkrish, I apologize for the trouble - looks like there was something ulgy with my classpath. I've tried running executable jar instead of running from IDE - and now everything is ok.

**Comment by chiyanram** [comment]
@dilipkrish i tried removing @Configuration still the problem exists.

**Comment by vbnhfylbh** [comment]
@chiyanram, is your swagger ui accessible on http://localhost:8080/travel/swagger-ui.html? Or  http://localhost:8080/swagger-ui.html?

**Comment by gilgameshs** [comment]
+1 
/v2/api-docs return expected json value, but /swagger-resources/configuration/ui return {}

**Comment by dilipkrish** [comment]
@gilgameshs gson isn't supported. If it works partly its by chance
