### ISSUE TITLE
docket.directModelSubstitute is not working with List of enums

### ISSUE THREAD

**Issue by rasmusviben** [springfox/springfox#2052]
I got an issue with docket.directModelSubstitute. 

I'm trying to replace a List of enums to the type String as following:

**docket.directModelSubstitute(RemovalType.class, String.class);**

The RemovalEnum is declared in a Removal class as this: List<RemovalType> removalTypes.

When I'm generating my swagger contract, it doesn't replace the **RemovalType.class with String class.**

There is only a issue, when it is used with a List - if im trying with a normal enum class, it is working fine.

springfox-staticdocs version 2.6.1

Any suggestion?

**Comment by dilipkrish** [comment]
You need to also add an explicit alternate type rule for `List<RemovalType>` to `List<String>`
