### ISSUE TITLE
Swagger-ui don't render additionalProperties

### ISSUE THREAD

**Issue by deblockt** [springfox/springfox#2057]
- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?
 - [x] Bug report. 
       swagger.json : https://gist.github.com/deblockt/4c1b3057194b211a39376888c40a0902

My model `OUJsonAttributes`avec "phones" properties describe like this 

```yaml
phones:
        type: object
        additionalProperties:
          $ref: '#/definitions/OUJsonApiPhoneNumber'
OUJsonApiPhoneNumber:
    type: object
    properties:
      number:
        type: string
      prefix:
        type: string
``` 

on [swagger-ui editor](https://editor.swagger.io/) generated example is like this : 
``` json
"phones": {
   "additionalProp1": {
      "number": "string",
       "prefix": "string"
     },
     "additionalProp2": {
       "number": "string",
       "prefix": "string"
     },
     "additionalProp3": {
       "number": "string",
       "prefix": "string"
     }
}
```

on springfox swagger ui, example is like this 
``` json
"phones": {}
```

On swagger-ui editor, model is like this : 

![capture d ecran 2017-10-02 a 10 21 43](https://user-images.githubusercontent.com/5050163/31069166-8aa7a51e-a75b-11e7-8520-587c6751b586.png)

and with springfox swagger-ui, on the `model`tag, the phone model is like this : 
```
phones (inline_model, optional),
inline_model {}
```

It's a bug? Or a configuration exists to display additionalProperties?

**Comment by dilipkrish** [comment]
@deblockt The model you posted in the gist is rendered correct in swagger-ui other than the fact that there seems another problem with rendering `Map«string,Option«string»»` which seems to be missing.

Also, swagger-ui that comes with springfox is version `2.2.10`So it is not the same level of support as swagger-editor

**Comment by deblockt** [comment]
Yes, I agree. 

There are any possibility to increase springfox version? Will the update be done soon?

**Comment by dilipkrish** [comment]
I hope to get one out soon not sure when.

**Comment by dilipkrish** [comment]
This should be fixed via upgrade to swagger-ui 3.x (#2153)
