### ISSUE TITLE
AuthorizationCodeGrant working?

### ISSUE THREAD

**Issue by miwoe** [springfox/springfox#2060]
Hi,

we have an Oauth-Server with AuthorizationCode and Password granttype. I am typically connecting with AuthorizationCode and Postman which works.

I am not able to get that working in Swagger/Springfox. I started without SecurityConfiguration, as everything, I actually needed is in the AuthorizationCodeGrant, but then clicking Authorize fails.

When I add the SecurityConfiguration, the Swagger UI opens successfully out Ouath Login page, I login and then the token fetch fails with 401: unauthorized, although the code, clientId and client parameters are passed.

```
private List<AuthorizationScope> scopes() {
        ArrayList al = new ArrayList();
        al.add( new AuthorizationScope("openid", ""));
        return al;
    }

    private List<GrantType> grantTypes() {

        GrantType grantType = new AuthorizationCodeGrant(
                new TokenRequestEndpoint(".../oauth/authorize", "myclient",
                        "mysecret"),
                new TokenEndpoint(".../oauth/token", "JWT-TOKEN"));
        ArrayList al = new ArrayList();
        al.add(grantType);
        return al;
    }

    @Bean
    public SecurityConfiguration security() {
        return new SecurityConfiguration(
                "myclient", "mysecret", "openid", "openid", "openid", ApiKeyVehicle.HEADER, "api_key", ",");
    }
```

**Comment by dilipkrish** [comment]
Forgive my ignorance in the the support of various flows. I know that @mojaiq graciously put together [this demo](https://github.com/springfox/springfox-oath2-demo) that might provide some clues.

Also [this](https://github.com/swagger-api/swagger-ui/issues/2406) seems to indicate limited support which is (approximately) the current swagger-ui version.
