### ISSUE TITLE
How to change location of /swagger-resources/** 

### ISSUE THREAD

**Issue by titoc** [springfox/springfox#2062]
Version used: 

```
springfox-swagger2:2.7.0
springfox-swagger-ui:2.7.0
Springboot: 1.5.1.RELEASE
```

Question: 
I need to change the default path of swagger-ui.html to `documentation/swagger-ui.html` and it worked and I can access: http://mydomain.com/documentation/swagger-ui.html
I [followed this comment](https://github.com/springfox/springfox/issues/1080#issuecomment-294807906) to change the path

```
@Override
	public void addViewControllers(ViewControllerRegistry registry) {
		registry.addRedirectViewController("/documentation/v2/api-docs", "/v2/api-docs").setKeepQueryParams(true);
		registry.addRedirectViewController("/documentation/swagger-resources/configuration/ui","/swagger-resources/configuration/ui");
		registry.addRedirectViewController("/documentation/swagger-resources/configuration/security","/swagger-resources/configuration/security");
		registry.addRedirectViewController("/documentation/swagger-resources", "/swagger-resources");
	}

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/documentation/**").addResourceLocations("classpath:/META-INF/resources/");
	}
```
The problem:

This is served from an apache reverse proxy.  The swagger-ui.html loads fine, but then the 302 redirects to `/swagger-resources/*` paths fails because it wont be mapped in the reverse proxy.

How do I make springfox to serve  `/swagger-resources/* from /documentation/ `?

**Comment by dilipkrish** [comment]
You'd need to set the X-Forward headers if you're going through a proxy

**Comment by maddyjs88** [comment]
Is there a way to anyways modify the location of /swagger-resources/* even if am not using reverse proxy? 

My use case is I have 2 service running using the same base url so both the service specific /swagger-resource conflicts since it will be http://someurl.com/swagger-resources 

I was able to change http://someurl.com/myapp/v2/api-docs for both service but due to swagger-resources being same it does not work as expected.

**Comment by dilipkrish** [comment]
@maddyjs88 You can create different context paths for each of the apps and it would make it 
`http://someurl.com/app1/swagger-resources/...`
`http://someurl.com/app2/swagger-resources/...`

**Comment by maddyjs88** [comment]
Do you have a a reference to how that can be done in java based spring config?
