### ISSUE TITLE
[Question] Disable Using{{HttpMethod}} postfixing

### ISSUE THREAD

**Issue by wingsofovnia** [springfox/springfox#2068]
Is it possible to disable adding `Using{{http_method_name}}` ending to endpoints that don't have `nickname` defined in `@ApiOperation`? Those are generated during build in my project with Swagger Codegen that apparently doesn't provide nicknames. 

I've submitted a fix https://github.com/swagger-api/swagger-codegen/pull/6688 there, but till then I want to overcome this with a temporal solution (like overriding naming strategy or smth).

**Comment by dilipkrish** [comment]
You can create your own plugin like [this one](https://github.com/springfox/springfox/blob/4427e23933629d1dce3ac2a80f7c8cd4d75f8ef6/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OperationNicknameIntoUniqueIdReader.java#L33) Only make sure that your plugin order is after the swagger order
