### ISSUE TITLE
Deprecated Annotation Causing Endpoint to Appear Deprecated

### ISSUE THREAD

**Issue by robzahm** [springfox/springfox#2070]
When a controller endpoint is decorated with an annotation that has been deprecated, the endpoint itself will appear in the JSON/Swagger UI as being deprecated.

# How to Reproduce
1. Clone https://github.com/robzahm/springfox
2. Start application via ```gradle bootRun```
3. Access http://localhost:8080/swagger-ui.html
4. Expand Foo Controller, note that one endpoint appears deprecated, and the other does not.
5. Look in the source ```Controller``` package, and note that the ```deprecated``` endpoint itself has not been deprecated, but does have an annotation that has been deprecated.

---

Please take the time to search the repository, if your question has already been asked or answered.

- [X] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [X] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by dilipkrish** [comment]
@robzahm thanks for reporting. The `DeprecatedAnnotation` class has a `Deprecated` annotation.

https://github.com/robzahm/springfox/blob/b0c43d5fa54dcf8dd019a83c34ab0bf516a60482/src/main/java/com/springfox/deprecated/sample/annotation/DeprecatedAnnotation.java#L14

As I recall this is a feature. Your Not clear what the expectation is?

**Comment by robzahm** [comment]
I would expect that annotation to show up as deprecated in the source, but would not expect the consumers of the annotation to be deprecated.  For example:

```
@Foo
public void someControllerEndpoint() {}
```

When Foo is deprecated, the documentation is showing someControllerEndpoint as being deprecated.  This is misleading because someControllerEndpoint hasn't been deprecated, though it should be modified to move away from its usage of Foo.

I would only expect someControllerEndpoint to appear as deprecated in the docs if it is tagged directly:

```
@Foo
@Deprecated
public void someControllerEndpoint() {}
```

**Comment by dilipkrish** [comment]
@robzahm Ah I see what the confusion is. It is deprecating the use of the annotation vs deprecating the use of the operation itself. I think spring itself treats that as a composite annotation. Similar to [@GetMapping](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/GetMapping.html).

**Comment by robzahm** [comment]
@dilipkrish Are composed annotations declared and documented as such?  The API docs for and [source](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/bind/annotation/GetMapping.java) for GetMapping explicitly call out that this is a composed annotation that acts as a shortcut for another.  I'm not sure how this applies to our case.

If Spring deprecated @GetMapping in favor of @NewAndImprovedGetMapping, it doesn't seem to me that this should deprecate all endpoints decorated with @GetMapping.
