### ISSUE TITLE
SecurityReference should support multiple references

### ISSUE THREAD

**Issue by lack** [springfox/springfox#2074]
I'm running 2.7.0 but also confirmed in the github master: SecurityReference only allows exactly one "reference", and it should allow multiples.  The reason for this is to support the full range of ANDing multiple security schemes as supported in swagger 2.

Reference: https://swagger.io/docs/specification/2-0/authentication/#multiple where it says:
```yaml
security:    # (A AND B) OR (C AND D)
  - A
    B
  - C
    D
```
> That is, security is an array of hashmaps, where each hashmap contains one or more named security schemes. Items in a hashmap are combined using logical AND, and array items are combined using logical OR. Security schemes combined via OR are alternatives — any one can be used in the given context. Security schemes combined via AND must be used simultaneously in the same request.

I belive in Springfox this *should* correspond to something like the following;

```java
docket
  .securitySchemes(Arrays.asList(
    new ApiKey("A", "A", "header"),
    new ApiKey("B", "B", "header"),
    new ApiKey("C", "C", "header"),
    new ApiKey("D", "D", "header"),
  ))
  .securityContexts(Arrays.asList(
    SecurityContext.builder()
                .securityReferences(securityReferenceList())
                .forPaths(PathSelectors.any())
                .build();
  ));

...

private List<SecurityReference> securityReferenceList() {
        AuthorizationScope authorizationScope
                = new AuthorizationScope("global", "accessEverything");
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0] = authorizationScope;
        SecurityReference abHeaderAuth = new SecurityReference(Arrays.asList("A", "B"), authorizationScopes);
        SecurityReference cdHeaderAuth = new SecurityReference(Arrays.asList("C", "D"), authorizationScopes);
        return Arrays.asList(singleHeaderAuth, multiHeaderAuth);
}
```

Obviously this won't compile today because the SecurityReference only holds a single `String reference;` and not a ```List<String> references;``` as I think it would need to in order to fully support the swagger spec here.

Or am I simply missing something?  Is there some other way I can tell springfox to add the following security info?
```json
"security": [
  {
    "A": ["global"],
    "B": ["global"]
  },
  {
    "C": ["global"],
    "D": ["global"]
  }
]
```

**Comment by dilipkrish** [comment]
Verified this is a gap. Would be good to address as part of upgrading to OAS 3.0

**Comment by benfonty** [comment]
Hello,

I am using springfox in our project where the api is secured by a pair of ApiKey (that is, an applicationKey and a HMAC signature). I wanted to configure this in [a way described by the swagger guys](https://swagger.io/docs/specification/2-0/authentication/api-keys/) (see Pair of API Keys). 
It seems that I encounter the same problem as the creator of this issue.
Is there a chance that the feature will be available for swagger 2.0 spec or that I could find a solution developing a plugin ?

**Comment by dilipkrish** [comment]
You might be able to figure it and contribute back to this project. Its a gap as has been identified and since its a fairly big change, I decided to put it out to the time we support OAS 3.0

**Comment by bruceadowns** [comment]
> You might be able to figure it and contribute back to this project. Its a gap as has been identified and since its a fairly big change, I decided to put it out to the time we support OAS 3.0

@dilipkrish, would you layout your findings and suggest possible approaches to solving? I may be willing to contribute. I am currently working on an api that requires 2/3 api keys and the current behavior is funky.

**Comment by dilipkrish** [comment]
@bruceadowns this involves modification of the internal models that represent OAS. I'm currently working on this repo to get that done, I will take a look at this as part of https://github.com/springfox/springfox/tree/feature/2022/oas-3-support-experiment1

**Comment by dilipkrish** [comment]
Closing this as fixed

**Comment by minhnguyenvan95** [comment]
thanks
