### ISSUE TITLE
[question] How to remove a default annotation from defaultExcludeAnnotations list

### ISSUE THREAD

**Issue by ottawaBird** [springfox/springfox#2075]
With SwaggerSpringMVC plugin, this can be done by following for example:

`springSwaggerConfig.defaultExcludeAnnotations().remove(ApiIgnore.class);`

And how this can be done in SpringFox with Docket? This is very useful when we want to hide/show controllers by certain condition.

**Comment by dilipkrish** [comment]
@ottawaBird what exactly are u trying to do?

**Comment by ottawaBird** [comment]
@dilipkrish 

How do remove "ApiIgnore.class" from defaultExculdeAnnotations list in SpringFox?

With SwaggerSpringMVC plugin, it can be removed as following:
`springSwaggerConfig.defaultExcludeAnnotations().remove(ApiIgnore.class);`

How to do it with SpringFox?

**Comment by dilipkrish** [comment]
It is intended to not allow you to do that. Its an internal annotation that you shouldn't be using if you don't want something ignored.

**Comment by ottawaBird** [comment]
Thank for the reply @dilipkrish

It would make the migration from swagger 1.2 to swagger 2.0 harder for us, since we were able to do it with SwaggerSpringMVC, but not with SpringFox anymore.

**Comment by dilipkrish** [comment]
True but 1.2 => 2.0 is a breaking change. Also the package names are different so you'd have to make changes anyways.
