### ISSUE TITLE
How to convert a model Property to an Attribute in XML based req/res spring boot application?

### ISSUE THREAD

**Issue by vinodamity** [springfox/springfox#2076]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by vinodamity** [comment]
In my Spring boot application which has xml base req/res. I am using dependencies 
<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.6.1</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.6.1</version>
			<scope>compile</scope>
		</dependency>
and I have to generate the below request structure in swagger api:

<addressValidationRequestType>
	<inputAddress>
		<addressInfo recordId="1">
			<addressKey></addressKey>
			<address></address>
			<zip></zip>
		</addressInfo>		
	</inputAddress>
</addressValidationRequestType>

But its generating as 
<?xml version="1.0"?>
<AddressValidationRequestType>
  <inputAddress>
    <addressInfo>
      <address>string</address>
      <addressKey>string</addressKey>
      <recordId>string</recordId>
      <zip>string</zip>
    </addressInfo>
  </inputAddress>
</AddressValidationRequestType>

How to create the attribute "recordId" of  <addressInfo> tag instead of a property in my model and which annotation and property i have to use here.
public class AddressInfoType {

	@ApiModelProperty(name = "This field should have minimum first line address information to validate it from Code1 API", position = 1  )
    protected String addressKey;
    @XmlElement(required = true)
    protected String address;
    @ApiModelProperty(name = "This represents 5 digits zip code of an address")
    @XmlElement(required = true)
    protected String zip;
    @ApiModelProperty(name = "This is number which represents address index in request")
    @XmlAttribute(name = "recordId")
    protected String recordId;

Thanks,

**Comment by dilipkrish** [comment]
Thanks for reporting

**Comment by dilipkrish** [comment]
This should be fixed in 2.8.0. Closing this as fixed. If not please report back
