### ISSUE TITLE
Question - Support of Open API Specification V3

### ISSUE THREAD

**Issue by jmpascal** [springfox/springfox#2077]
Hello,

As [Open API Specification V3 ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) has been released this summer, I would know if there's a plan for SpringFox to support this new format in the coming period ?

Thanks in advance.

**Comment by dilipkrish** [comment]
Yes definitely there is.. here is some [WIP](https://github.com/springfox/springfox/tree/feature/2022/oas-3-support)

**Comment by rachana1101** [comment]
Any ETA around when springfox will start supporting Open Api V3 ?

**Comment by marcellisdon** [comment]
We need OpenAPI 3.0, especially for the feature of defining the security scopes of each endpoint. When can we expect to have Springfox to support OpenAPI 3.0?

**Comment by dilipkrish** [comment]
@marcellisdon when its complete. Currently I hope to have it by September sometime

**Comment by vmavromatis** [comment]
@dilipkrish thank you very much! is there some tag/branch to follow? Really interested in this.

**Comment by dhamudeva** [comment]
@dilipkrish - Any comment on dates for this feature support?

**Comment by RvdHNL** [comment]
@dilipkrish Any thoughts on the ETA?

**Comment by dilipkrish** [comment]
@RvdHNL @dhamudeva I haven't had a chance to work on springfox the last couple weeks. Im hoping mid november 🤞

**Comment by jakubvimn** [comment]
Could you, please, re-open this issue and post some update about the progress, or ETA (if any)?

**Comment by monsterbilligt-service** [comment]
How far are you with implementing OpenAPI 3.0?

**Comment by slawiko** [comment]
@dilipkrish this is really very painful question

**Comment by larsnaesbye** [comment]
A smaller request: could the changes of the main branch be retroactively applied to the 'oas-3-support' branch, so more of us could take a look at OAS 3 support?

**Comment by TobiasBales** [comment]
That sounds like a great idea. Any news?

**Comment by okohub** [comment]
Hey, any update on this issue?

**Comment by R3dRuM** [comment]
Also looking forward to this.

**Comment by holoduck** [comment]
For anyone looking for this feature, the actual tracking ticket is: https://github.com/springfox/springfox/issues/2022

Here's the [list of tickets labelled for this epic](https://github.com/springfox/springfox/labels/epic%2Foas3).

[Here](https://github.com/springfox/springfox/issues/2124#issuecomment-385133812) the main author hints how to convert the Swagger 2.0 currently generated by springfox to Open API v3.
