### ISSUE TITLE
Explicit Mapping for swagger-ui.html

### ISSUE THREAD

**Issue by gborges0727** [springfox/springfox#2078]
I have a small issue. On my project, I have a route that expects a parameter in the path 

Example: localhost.com/serverContext/{parameter}

This presents an issue when trying to access swagger-ui, as when I try to hit the swagger-ui URL, locahost.com/serverContext/swagger-ui.html, spring complains, saying it does not match the {parameter} specification. Is there a way to explicitly define a mapping for swagger-ui.html, so that spring knows when I put it in the URL to hit the page and not treat it as me putting the value in as a parameter? 

I've tried changing the mapping to swagger-ui (i.e. putting it behind /documentation), as described in issue 1080, (https://github.com/springfox/springfox/issues/1080), however this presents a new issue with the serverContext being mapped to a different path, so I'm trying to avoid any complexities there.

Any help is appreciated. Thanks!

**Comment by dilipkrish** [comment]
In your case you should simply point to `locahost.com/swagger-ui.html` for swagger ui

**Comment by gborges0727** [comment]
How do I have swagger ignore the servercontext?

**Comment by dilipkrish** [comment]
I see... can't say without looking at the code. But the [springfox-demo](https://github.com/springfox/springfox-demos/tree/master/boot-swagger) does exactly that. It creates a context path `springfox` instead of `servercontext`

**Comment by gborges0727** [comment]
So in that example project you have server.contextPath=/springfox. In my project, I'm doing something very similar where my server.contextPath=/serverContext

**Comment by gborges0727** [comment]
I found a way to solve the issue by making the path parameter more explicit so that it wouldn't try to include swagger-ui.html

**Comment by dilipkrish** [comment]
@gborges0727 Would you mind sharing your way, just so it might help someone else with the same problem you had?

**Comment by gborges0727** [comment]
Sure. So I know for my {parameter} I expect a number. I simply defined that path mapping explicitly with a regex to expect a number, by doing: 
`@RequestMapping(value="/{parameter:\\d+}", method=RequestMethod.GET)`
In this way, spring doesn't complain when I try to hit swagger-ui.html. In theory, if this issue is faced by somebody, you could make your parameter definition explicit using a regex so that there is no conflict when trying to hit swagger-ui.html
