### ISSUE TITLE
[question] When do you plan to release 2.7.1?

### ISSUE THREAD

**Issue by mzeijen** [springfox/springfox#2079]
Hi,

We are happy users of Springfox. Thank you for all the hard work?

We are wondering though when you plan to release the next version (2.7.1?) of SpringFox because there is a bug fix in there we are eagerly waiting on :).

Regards,

Maurice Zeijen

**Comment by dilipkrish** [comment]
@mzeijen I'll package a patch and have it out in the next week or so

**Comment by mzeijen** [comment]
That would be awesome. Thx!

**Comment by mohsenzamani** [comment]
Hi, We would like to thank you for your time and effort ;)  Will JsonView be supported in the next version (releasing next week :+1: )? We are looking forward to it

**Comment by MaksimOrlov** [comment]
@mohsenzamani

JsonView unfortunately is not stable for this moment. It will take, I think, one more month. (Related pulls are #2004, #2056, #1671)

**Comment by mzeijen** [comment]
@dilipkrish Hi Dilip, it is been a while but the patch release didn't happen yet. Can you give a status update on it? Thanks.

**Comment by dilipkrish** [comment]
Working through the bugs/investigations that have piled up. Unfortunately theres a lot of them and going through each one is painfully slow. The reason I'd like to do that is so we can make room for breaking changes coming
- EOL java 6/7 support 
- EOL swagger 1.2 support
- OAS 3.0 support
- Java 8 support/ Remove guava

**Comment by mzeijen** [comment]
Hi Dilip,

Thanks for the update.

Are there maybe any bugs/investigations you can use some help with? Maybe I can contribute some more.

Regards,

Maurice

**Comment by dilipkrish** [comment]
Here are the [issues under investigation](https://github.com/springfox/springfox/labels/investigating). Some may not be bugs, but I usually create a contract test to prove if there is an issue or not. Some of them may have steps to reproduce some don’t. That’s why it’s a little time consuming.  Any help identifying if they are bugs and possibly a fix would be super helpful.
