### ISSUE TITLE
springfox-bean-validators not activated @NotNull in Spring @GetMapping Controller

### ISSUE THREAD

**Issue by sayseakleng** [springfox/springfox#2083]
Hello guys!
I'm having a problem with springfox-bean-validators. @NotNull not activated on bean with @ModelAttribute annotation in Spring @GetMapping Controller.

PS: I tried @NotNull on bean with @RequestBody annotation in Spring @PostMapping Controller, It works.

Best Regards,
Seakleng

**Comment by dilipkrish** [comment]
@sayseakleng what version are you using?

**Comment by sayseakleng** [comment]
Hello sir!
I'm using swagger 2 version **2.7.0**
compile "io.springfox:springfox-swagger-ui:2.7.0"
compile "io.springfox:springfox-bean-validators:2.7.0"
compile "io.springfox:springfox-swagger2:2.7.0"

**Comment by dilipkrish** [comment]
I believe you need to import the configuration `BeanValidatorPluginsConfiguration`.

**Comment by sayseakleng** [comment]
Hello Sir!
Yes I already initialize the bean:

<bean class="springfox.bean.validators.configuration.BeanValidatorPluginsConfiguration" />

I think the library misses to scan on @GetMapping because I found as below:
- @NotNull on bean with @requestbody annotation in Spring @postmapping 
- @NotNull not activated on bean with @modelattribute annotation in Spring @getmapping Controller

Works on Post HTTP method:
![untitled](https://user-images.githubusercontent.com/19582007/32877670-3288f48a-cad5-11e7-8212-8f3060503a5d.png)

**Comment by dilipkrish** [comment]
I think this is a bug that was fixed, but hasn't been released.

**Comment by matt-shaw** [comment]
When will this fix be released?

**Comment by sayseakleng** [comment]
Thank you so much sir! I hope it will be released so soon :)
