### ISSUE TITLE
Resources hang once Swagger Config is added to WebMvcConfigurerAdapter

### ISSUE THREAD

**Issue by niculistana** [springfox/springfox#2084]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

> I am using SpringFox `2.7.0` and Spring framework `4.2.0.RELEASE`.

What kind of issue is this?

- [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
- [x] spring xml/java config that is relevant
> My WebAppConfig.java class
```
@EnableWebMvc
@ComponentScan(basePackages= "com.foo.bar.controller")
@Import({SwaggerConfig.class})
public class WebAppConfig extends WebMvcConfigurerAdapter {
// autowire beans

  @Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/**").addResourceLocations("/");
  }

  @Bean
  public ViewResolver viewResolver() {
    InternalResourceViewResolver viewResolver = new InternalResourceViewResolver();
    viewResolver.setViewClass(JstlView.class);
    viewResolver.setPrefix("/WEB-INF/");
    viewResolver.setSuffix("");
    return viewResolver;
  }

  @Bean
  public static PropertySourcesPlaceholderConfigurer properties() {
    PropertySourcesPlaceholderConfigurer props = new PropertySourcesPlaceholderConfigurer();
    props.setIgnoreUnresolvablePlaceholders(true);
    return props;
  }

  @Override
  public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
    // add message converters
  }

  @Override
  public void addInterceptors(InterceptorRegistry registry) {
    // add interceptors
  }
}
```
- [x] springfox specific configuration if it makes sense
> My SwaggerConfig.java class
```
@EnableSwagger2
public class SwaggerConfig {

  @Bean
  public Docket foobarApiDocumentation() {
    return new Docket(DocumentationType.SWAGGER_2)
        .select()
        .paths(Predicates.not(PathSelectors.regex("/error.*")))
        .build()
        .genericModelSubstitutes(ResponseEntity.class)
        .useDefaultResponseMessages(false)
        .apiInfo(apiInfo());
  }
...
}
```
- [x] include any output you've received; logs, json snippets etc.; and what the expected output should be
> The logs stopped at: **2017-10-30 17:40:14,800 [localhost-startStop-1] INFO  scanners.ApiListingReferenceScanner:41 () - Scanning for api listing references**
```
2017-10-30 17:40:14,637 [localhost-startStop-1] INFO  handler.SimpleUrlHandlerMapping:341 () - Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-10-30 17:40:14,670 [localhost-startStop-1] INFO  web.PropertySourcedRequestMappingHandlerMapping:69 () - Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2017-10-30 17:40:14,705 [localhost-startStop-1] INFO  support.DefaultLifecycleProcessor:341 () - Starting beans in phase 2147483647
2017-10-30 17:40:14,706 [localhost-startStop-1] INFO  plugins.DocumentationPluginsBootstrapper:147 () - Context refreshed
2017-10-30 17:40:14,721 [localhost-startStop-1] INFO  plugins.DocumentationPluginsBootstrapper:150 () - Found 1 custom documentation plugin(s)
2017-10-30 17:40:14,800 [localhost-startStop-1] INFO  scanners.ApiListingReferenceScanner:41 () - Scanning for api listing references
```

**Comment by dilipkrish** [comment]
Is it in an endless loop?

**Comment by niculistana** [comment]
Seems like it is, I’m not 100% sure. The browser UI blocks and waits for the response to load for a really long time. The logs just stop.

**Comment by niculistana** [comment]
I placed a debugger in the ApiListingReferenceScanner class, and looks like the code is stuck at:

```
    while(i$.hasNext()) {
      RequestHandler handler = (RequestHandler)i$.next();
      ResourceGroup resourceGroup = new ResourceGroup(handler.groupName(), handler.declaringClass(), Integer.valueOf(0));
      RequestMappingContext requestMappingContext = new RequestMappingContext(context, handler);
      resourceGroupRequestMappings.put(resourceGroup, requestMappingContext);
    }
```

**Comment by niculistana** [comment]
@dilipkrish Upon further investigation, it looks like my project is too big for the initial scanning to finish. By any chance, would you happen to know if there a way to scan specific classes one by one instead of using `basePackageClasses`? Because if I do `basePackageClasses=FooController.class` it also scans the rest of the other classes within the package.

**Comment by niculistana** [comment]
@dilipkrish It looks like I have a lot of routes for my project. I placed `@APIIgnore` annotation to all of my other controllers and left one without the ignore annotation and it began to work. I there a way to make it faster?

**Comment by niculistana** [comment]
Looks like the issue over here is that I have a bunch of routes with `@SecureEndpoint` annotation which causes the lag.

**Comment by niculistana** [comment]
@dilipkrish I e-mailed the swagger folks and they mentioned that my api has a lot of models that are composed from each other therefore causing a huge slowdown in both compilation and rendering the swagger UI. By any chance would there be a way to turn of auto-generating model definitions?

**Comment by dilipkrish** [comment]
You could generate the swagger specification offline as part of an integration test and include it as a resource so you don't pay the penalty at run-time.

**Comment by niculistana** [comment]
Yeah that makes sense. That's what I am doing right now actually. Is there
a way to include a flag to skip compile time?

**Comment by filipemb** [comment]
How to do this (generate the swagger specification offline as part of an integration test and include it as a resource)? Any tutorial?
@dilipkrish @niculistana

**Comment by dilipkrish** [comment]
It's been an while but have you looked at this? https://github.com/Swagger2Markup/swagger2markup?
