### ISSUE TITLE
Problem with type rules from List<Object> to List<byte[]>

### ISSUE THREAD

**Issue by benweet** [springfox/springfox#2087]
In one of my DTOs, I have this:

```java
  @ApiModelProperty("The certificate path.")
  private List<X509Certificate> certificatePath;
```

I've configured the Jackson parser/serializer to automatically parse/serialize X509Certificates from/to bytes. Then I've added this in the Docket configuration:

```java
        .alternateTypeRules(
            new AlternateTypeRule(
                typeResolver.resolve(X509Certificate.class),
                typeResolver.resolve(byte.class)),
            new AlternateTypeRule(
                typeResolver.resolve(List.class, X509Certificate.class),
                typeResolver.resolve(List.class, byte.class)))
```

But I keep getting this:

<img width="248" alt="screen shot 2017-11-03 at 11 43 09" src="https://user-images.githubusercontent.com/1005257/32372314-3939de8c-c08c-11e7-81ac-652f71a546a4.png">

Whereas it should be an array of strings.

**Comment by dilipkrish** [comment]
I believe swagger-ui treats an array of bytes as string. What does your swagger description look like?

**Comment by benweet** [comment]
The swagger.json contains a string instead of an array of strings.

**Comment by dilipkrish** [comment]
Based on your rules it seems to expect a List<byte> not List<String>

**Comment by benweet** [comment]
I'm not sure about that actually. As I understand, the way you represent a binary string is via the `byte` type (I need binary strings in my API, not just strings).

This is the rule I use to substitute `X509Certificate` with a binary string and it works fine:

```java
new AlternateTypeRule(
                typeResolver.resolve(X509Certificate.class),
                typeResolver.resolve(byte.class)),
```

However the second rule doesn't. It substitutes a `List<X509Certificate>` with a binary string instead of a list of binary strings.
