### ISSUE TITLE
@ApiParam(allowableValues = "range(0, infinity)") does not work

### ISSUE THREAD

**Issue by filiphr** [springfox/springfox#2088]
As explained in the issue excluisve min / max does not work.

I am using `2.7.0`

This looks like explicitly not supported in springfox. See [`ApiModelproperties#L61`](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/schema/ApiModelProperties.java#L61). There is only check for `range[` and nothing for `range(`.

Is there a reason why this is not supported? especially as it looks like a pretty simple thing to be supported?

**Comment by dilipkrish** [comment]
There is no particular reason. Just haven't had a request to support it. Would you be able to submit a PR for it? Will be much appreciated!

**Comment by filiphr** [comment]
Just wanted to know the reasoning thanks. Yes I can provide a PR for this. I actually already started working on it. I have only few questions:

* If the range is not exclusive I will set `null` for the exclusive (so we can keep the same behaviour).
* In the `EnumMapper` there are 2 places when then mapping from `AllowableRangeValues` is not copied to `SerializableParameter` / `Property`:
** `SerializableParameter maybeAddAllowableValuesToParameter(SerializableParameter, AllowableValues)`
** `Property maybeAddAllowableValues(Property, AllowableValues)`

Should this also be updated? Because If I update that, then some tests fails because `RangeAnnotations#allowableRange` sets `exclusiveMin` / `exlusiveMax` to `false` and not `null`. So I am not sure what the "correct" implementation :)

**Comment by dilipkrish** [comment]
This is fixed via #1955

**Comment by dilipkrish** [comment]
Sorry I accidentally closed it. Will take a look at this PR. It goes much further than my fix.

**Comment by filiphr** [comment]
The PR is #2106. Yes your fix only adds support for exclusive ranges. The issue with infinity is the same.

If you want to I can rebase the PR, just let me know

**Comment by dilipkrish** [comment]
@filiphr thanks! 🙇 its merged

**Comment by filiphr** [comment]
Thanks for merging it
