### ISSUE TITLE
When using AlternateTypeRuleConvention ApiModelProperty annotation does not work

### ISSUE THREAD

**Issue by snimavat** [springfox/springfox#2090]
When using AlternateTypeRules as with the springfox-grails. ApiModelProperty has no effect.
See https://github.com/springfox/springfox-grails-integration/issues/20 for some more details.

What I would expect is:
When alternate type rule are added as DynamicTypes using AlternateTypeBuilder. The ModelPropertyBuilderPlugin should have enough information available in context, to know which original type this property belongs to so it can work accordingly, and process annotations or do whatever it needs for the given property based on original type or the new alternate type.

**Comment by dilipkrish** [comment]
@snimavat again thanks for detailed report. It helps improve the library overall 👍
