### ISSUE TITLE
How do I use springfox inside a library?

### ISSUE THREAD

**Issue by apurvjain17** [springfox/springfox#2091]
I have a library which exposes a couple of endpoints in the application which adds it as a dependency. I am using springfox for documenting the endpoints.

Now I have a couple of questions,
Should swagger-config be a part of the application or the library or should be present at both the places?
Moreover is it important for both the application and library to add spring-fox into pom.xml or just the library would be enough?
Because when I didn't add it in the application I started receiving errors as :- 

`Error creating bean with name 'apiDocumentationScanner' defined in URL [jar:file:`

What would be the right approach for a clean inclusion of springfox-swagger2/ swagger-ui into the application?

Can swagger-config reside at both places i.e. application as well as library and still not override each other?

Thanks,
Apurva

**Comment by dilipkrish** [comment]
Could you share an example repository? This is a very loaded question. Hard to generalize with an answer.

In general. The springfox configuration should only happen in the application. However, it might be that  spring isolates your configuration into its own application context, as a result, the `RequestMapping`s that you've defined in the library may not be visible.
