### ISSUE TITLE
Custom Exception on invalid @RequestBody JSON

### ISSUE THREAD

**Issue by Giolla** [springfox/springfox#2092]
Hi, i'm Using SpringFox 2.5.0. Here's my configuration:

```java
@ComponentScan
@Configuration
@EnableSwagger2
public class SwaggerConfiguration {

    ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("ProjectTitle")
                .description("ProjectDescription")
                .license("")
                .licenseUrl("")
                .termsOfServiceUrl("")
                .version("1.0.0")
                .contact(new Contact("", "", ""))
                .build();
    }

    @Bean
    public Docket customImplementation() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.project.controllers"))
                .build()
                .directModelSubstitute(org.joda.time.LocalDate.class, java.sql.Date.class)
                .directModelSubstitute(org.joda.time.DateTime.class, java.util.Date.class)
                .apiInfo(apiInfo());
    }
}
```

I have my Controllers annotated with @RestController and my POST looks like this:

```java
@PostMapping("/cars")
        public ResponseEntity<CarsDto> create(@RequestBody CarsDto model) {
        
        CarsDto car= CarsService.create(model);
        if (car== null) {
            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
        }
        return new ResponseEntity<>(car, HttpStatus.CREATED);
    }
```

I have CustomExceptionHandler implementd via `@ControllerAdvice` and have an `@ExceptionHandler({Exception.Class}) catchAll()` method that catches everything else that's not specified by `@Override` methods (TypeMismatch.. etc)

Issue i have is if i pass an invalid JSON in swagger, it instantly returns 400 with "No Content":
![image](https://user-images.githubusercontent.com/16195901/32450961-aa2722ea-c2e3-11e7-8df5-e329c52c1dd7.png)

I thought about adding an `@Override` for `ClassCastException` to my `@ControllerAdvice` class, but the thing is swagger returns 400 without hitting my Controller so my CustomExceptionHandler never catches it so that i could return a message to UI saying the model is wrong.  Where can i override the default 400/No Content that gets set on schema validation?

Thanks

**Comment by dilipkrish** [comment]
It appears that your `car` is null which is why you're getting the response you're seeing
