### ISSUE TITLE
swagger2ControllerMapping NoSuchMethodError

### ISSUE THREAD

**Issue by tmurray3** [springfox/springfox#2094]
I am having an issue deploying .war file to Weblogic 12.1.3, with swagger2 version 2.7.0.   The following exception is throw:

_Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'swagger2ControllerMapping' defined in class path resource [springfox/documentation/swagger2/configuration/Swagger2DocumentationConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.google.common.base.Optional.transform(Lcom/google/common/base/Function;)Lcom/google/common/base/Optional;_

Here are the dependencies from the pom.xml file:

```

	  <dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	  </dependency>
	  <dependency>
		<groupId>io.springfox</groupId>
		<artifactId>springfox-swagger2</artifactId>
	    <version>2.7.0</version>		
	  </dependency>
	  <dependency>
		<groupId>io.springfox</groupId>
		<artifactId>springfox-swagger-ui</artifactId>
	    <version>2.7.0</version>		
	  </dependency>	  	  
	  <dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-tomcat</artifactId>
		<scope>provided</scope>
	  </dependency>      
```

Reference code in:
https://www.concretepage.com/spring-4/download/spring-rest-swagger-2-integration-with-annotation-xml-example-1.zip

It appears the missing method is in the guava-18.0.jar, which is deployed in the WEB-INF/lib directory.

Any direction would be appreciated.

Thanks.

**Comment by dilipkrish** [comment]
I think most likely you're getting the wrong guava jar loaded into the class path

**Comment by petrdvorak** [comment]
Yes, but I believe this is an issue caused by Swagger and the fact it depends on a specific library version of well known libraries. We had the same issue here by our application suddenly crash on `canDecode` method (check for Base64 encoding) missing after adding Swagger...

I suggest Swagger only defines minimum version ('+'), not only for Guava, but for Jackson etc. See here - these are all candidates for similar issues:

https://github.com/springfox/springfox/blob/640c75a6900fa284c754e7dc4cc4c3982e7f4469/gradle/dependencies.gradle

**Comment by dilipkrish** [comment]
@petrdvorak We don't enforce dependencies except for guava because usually every application will provide their own versions of those libraries like jackson

https://github.com/springfox/springfox/blob/ef61361a3082e8fff9e2dcdd454cf72f25fd0186/gradle/dependencies.gradle#L66-L70

**Comment by petrdvorak** [comment]
Ah - sorry, I overlooked this...

We solved the issue on our end by forcing our Guava version in the top-most `pom.xml` of the project. I believe this discussion will help random visitors who meet a similar issue.

**Comment by vinogradov-evgeniy** [comment]
I am facing a similar issue when trying to add swagger... 
guava-22 dependency is there, tried adding guava dependency to top level pom.xml and even to lib folder of weblogic install. However, still facing same issue.... any suggestions? 

Any help much appreciated!
Thank you!

**Comment by dilipkrish** [comment]
@vinogradov-evgeniy are u using 2.8.0?

**Comment by vinogradov-evgeniy** [comment]
@dilipkrish using 2.7.0

**Comment by dilipkrish** [comment]
@vinogradov-evgeniy sounds like you're managing dependencies outside of maven. So Im not entirely sure why your guava dependency isn't being used.
