### ISSUE TITLE
@ApiParam is ignored on ValueObjects wrapped with @JsonCreator

### ISSUE THREAD

**Issue by dkellenb** [springfox/springfox#2096]
Bug: Using `springfox-swagger2` version `2.7.0` swagger ignores `@ApiParam` documentation on parameters with ValueObjects.

Given a ValueObject with one field:
```java
@Data
public class Key {

    @JsonCreator
    public Key(@JsonProperty("key") String keyContent) {
        key = keyContent;
    }

    // if enabled, name will be shown @ApiModelProperty(value = "my description")
    private final String key;
}
```

And a method on a controller:
```java
@Controller
@RequestMapping("/store")
@Api(value="property", description="Retrieve values for an environment")
public class EnvironmentKeyValueStoreController {

   @RequestMapping(method = RequestMethod.GET, path = "{propertyKey}/{environmentKey}")
   public ResponseEntity<String> getProperty(
      @ApiParam(name = "propertyKey", value = "Key of the property", required = true) @PathVariable("propertyKey") Key propertyKey,
      @ApiParam(name = "environmentKey", value = "Key of the environment", required = false) @PathVariable("environmentKey") Key environmentKey
    ) {
      return "";
  }
}
```

All  `@ApiParam` on the two parameters are ignored. The only way i can show a description in swagger-ui, is by enabling `@ApiModelProperty` on the field `Key.key`.

Actual:

| Parameter | Value | Description |
|-----------------|----------|------------------|
| key           |          |                 |
| key           |          |                 |

Expected:

| Parameter | Value | Description |
|-----------------|----------|------------------|
| **propertyKey** |          | Key of the property |
| environmentKey |          | Key of the environment |

**Comment by dilipkrish** [comment]
Try giving the `@ApiParam#type` a value of "string"

**Comment by dkellenb** [comment]
Thank you for your proposal. It's not working. I've created a project where you can reproduce the issue easily:
https://github.com/dkellenb/spring-fox-issue-2096

Actual:
![selection_095](https://user-images.githubusercontent.com/9881798/32778471-4a3cd9c6-c93a-11e7-8624-919b7348bc82.png)

Expected:
![expected](https://user-images.githubusercontent.com/9881798/32778476-52c12b9c-c93a-11e7-9bc0-768b11bde7c3.png)

**Comment by dilipkrish** [comment]
@dkellenb Thanks it appear to be a bug!
