### ISSUE TITLE
No content response code 0 on Swagger UI

### ISSUE THREAD

**Issue by Arun8460** [springfox/springfox#2098]
Hi Team,
When I execute Try Now from Swagger UI, I am seeing "no content" in the response body with response code as "0". This happens only when the return type is String from REST API.

 I am using springfox - 2.7.0. When I return "String" from the REST api, swagger-ui is displaying "no content" in the response body with response code as "0". I knew that swagger is not able to parse String to JSON. I have tried giving "text/plain" in swagger java file as producer, but no luck. How can I fix this.

I could see the response from REST API under Network tab in the browser (on pressing F12), but the same response was not rendered on Swagger UI.

Following is the dependency used:
io.springfox
springfox-swagger2
2.7.0
io.springfox
springfox-swagger-ui
2.7.0

SwaggerConfig.java :
```java
@Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("xxxxxxxx"))
                .paths(PathSelectors.regex("/xx/.*"))
                .build()
                .directModelSubstitute(LocalDate.class, java.sql.Date.class)
                .directModelSubstitute(LocalDateTime.class, java.util.Date.class)
                .consumes(Sets.newHashSet(APPLICATION_JSON_VALUE))
                .securityContexts(Lists.newArrayList(securityContext()))
                .securitySchemes(Lists.newArrayList(new ApiKey("Authorization", "Authorization", "header")))
                .ignoredParameterTypes(xxxxxxx.class, xxxxxx.class);
```

**Comment by dilipkrish** [comment]
Could you confirm that the api is working when you exercise it using curl or clients such as postman

**Comment by Arun8460** [comment]
Yes, using curl, I could see the response.

**Comment by dilipkrish** [comment]
What does you swagger definition for the operation look like and what does your controller request mapping look like.

**Comment by Arun8460** [comment]
SwaggerConfig.java :

@bean
public Docket api() {
return new Docket(DocumentationType.SWAGGER_2)
.select()
.apis(RequestHandlerSelectors.basePackage("xxxxxxxx"))
.paths(PathSelectors.regex("/xx/.*"))
.build()
.directModelSubstitute(LocalDate.class, java.sql.Date.class)
.directModelSubstitute(LocalDateTime.class, java.util.Date.class)
.directModelSubstitute(HttpStatus.class, String.class)
.consumes(Sets.newHashSet(APPLICATION_JSON_VALUE))
.securityContexts(Lists.newArrayList(securityContext()))
.securitySchemes(Lists.newArrayList(new ApiKey("Authorization", "Authorization", "header")))
.ignoredParameterTypes(xxxxxxx.class, xxxxxx.class);

Request mapping:
@RequestMapping(value = "xxxxxxxx",method = RequestMethod.POST)
    public **String** syncAccountsAdhoc(xxxxxxxxx){
        return xxxx.xxx(user.getUsername(),updateForAllUsers);

**Comment by Arun8460** [comment]
Similar issue reported:
[https://github.com/swagger-api/swagger-ui/issues/2584](url)

**Comment by Arun8460** [comment]
On hitting http://xxxxxxxxxx:xxxx/rw/user/v2/api-docs, I got api-docs, swagger version is 2.0 I guess from the following info:

{"swagger":"2.0","info":{"description":"Api Documentation","version":"1.0","title":"Api Documentation","termsOfService":"urn:tos","contact":{},"license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0"}},"host":"xxxxxxxxxxx}

I doubt whether swagger 2.0 has a limitation. Springfox 2.7.0 is mapped with Swagger-UI 2.0 (from the above api-docs info).

**Comment by dilipkrish** [comment]
I dont mean swagger 2.0 I mean swagger-ui as you've rightly unearthed issue [#2584](https://github.com/swagger-api/swagger-ui/issues/2584)

**Comment by Arun8460** [comment]
What should be the resolution. Do we need to track the issue under [#2584](https://github.com/swagger-api/swagger-ui/issues/2584).
How can I get the swagger-ui version mapped to springfox 2.7.0.

**Comment by dilipkrish** [comment]
Yes @Arun8460

**Comment by Arun8460** [comment]
Following info is from springfox-swagger-ui-2.7.0.jar:
Manifest-Version: 1.0
Build-Time: 2017-05-20T22:12:34-0500
Built-With: gradle-3.5, groovy-2.4.10
Implementation-Title: springfox-swagger-ui
Implementation-Version: 2.7.0
Built-On: ISDV161716L.local/192.168.1.163
Built-By: d_krishnan
Created-By: 1.7.0_79 (Oracle Corporation)
**SwaggerUi-Version: 2.2.10**

Is there a way to upgrade swagger-ui version to limit the issue?

**Comment by dilipkrish** [comment]
You can use your own desired version of swagger-ui by adding resource handlers.

**Comment by Arun8460** [comment]
registry.addResourceHandler("/webjars/**") .addResourceLocations("classpath:/META-INF/resources/webjars/")
Is this what you referring?

**Comment by dilipkrish** [comment]
Yes

**Comment by venki-hiya** [comment]
well, I ran into this issue with 2.9.2 as well, on Spring boot app - latest version. 
After trail and error i found out that i forgot the @RequesMapping("xxxx") for controller annotated with @RestController. Looks like it does not take request mapping from @RestController() and Swagger UI generation trips. Once, i fixed it worked beautifully.
Great library. It needs to keep maintained
