### ISSUE TITLE
Possible to generate swagger manually in code without annotation?

### ISSUE THREAD

**Issue by mrshawn191** [springfox/springfox#2099]
Hi was wondering if you could lead me into the right direction.

I have a special situation where i need to generate swagger for many apis, however the api/dtos are very similar so I don't want to go through the annotation hassle.. and look instead if I can generate the swagger spec manually? 

I was trying to look for a swagger builder in the library but couldn't find any.. any help?

**Comment by dilipkrish** [comment]
@mrshawn191 Firstly, there is no need for __ANY__ annotations when using springfox. I you do need to add descriptions or perhaps alter what is inferred by default is when you need to add some amount of annotations.

In anycase, there are a [whole host of builders](https://github.com/springfox/springfox/tree/master/springfox-core/src/main/java/springfox/documentation/builders). You can use to build api listings.

**Comment by mrshawn191** [comment]
@dilipkrish Ok thanks great link. 

Another question how to add custom description & example on @PathVariable and @Requestparam etc..

Ive tried with @ApiParam with value and example doesn't seems to work

**Comment by dilipkrish** [comment]
Just use springs native @Description annotation.
