### ISSUE TITLE
Authorization key is cleaned after page refresh

### ISSUE THREAD

**Issue by IrinaMaximenko** [springfox/springfox#2104]
Each time user refreshes the page api key (entered earlier) is lost and user has to enter it again.
The same happens when oauth is used.
Expected behaviour would be to keep the key in the local storage (for example) to avoid going through authorization process again.
Springfox version: 2.7.0.

**Comment by dilipkrish** [comment]
This is a stateless web UI. I don't think this feature can or will be supported, unless swagger-ui itself supports it.
