### ISSUE TITLE
display error with @RequestParam(value = "order",required = false,defaultValue = "-crtdate")LinkedList<String> order

### ISSUE THREAD

**Issue by ysjiang4869** [springfox/springfox#2108]
Please take the time to search the repository, if your question has already been asked or answered.

- What version of the library are you using?
 2.7.0
What kind of issue is this?
 - Bug report. 

using spring @requestrarm as title written ,but display wrong.
![screenshot-localhost-8088-2017-11-16-10-54-27-463](https://user-images.githubusercontent.com/20201786/32875002-960d1cb6-cad0-11e7-868c-e27b271824b0.png)

The execute button will be invalid and the order param can use.

I have tried many times and found the problem is the default value; if don't provide the default value for list there will be no problem. So it is a bug or I used wrong default value?

api-docs json can be see follow
`{ "name": "order", "in": "query", "description": "order", "required": false, "type": "array", "items": { "type": "string" }, "collectionFormat": "multi", "default": "-crtdate" }`

**Comment by ysjiang4869** [comment]
I have known the main problem. For type of array, the format should be:
```
{
     "name": "order",
     "in": "query",
      "description": "order",
       "required": false,
       "type": "array",
       "items": {
                     "type": "string"
                       "default": "-crtdate"
                     },
        "collectionFormat": "multi",                        
 }
```
but spring fox generate default value ad fllows:
```
{
     "name": "order",
     "in": "query",
      "description": "order",
       "required": false,
       "type": "array",
       "items": {
                     "type": "string"                       
                     },
        "collectionFormat": "multi",  
         "default": "-crtdate"                      
 }
```
@dilipkrish

**Comment by dilipkrish** [comment]
@ysjiang4869 my guess is the its a bug with swagger-ui. Looks like you're using the new swagger-ui with the swagger 2.0 format description

**Comment by ysjiang4869** [comment]
@dilipkrish I am using the swagger ui version 2.2.5. It supports swagger 2.0 format description. I have just tried springfox-swagger-ui and there is no problem. Maybe I should using the old version of swagger ui, thanks

**Comment by ysjiang4869** [comment]
I think it doesn't support  swagger-ui with tag 3.0.0 . Will it support in the future? The new ui is more beautiful. Thans for reply and this perfect project

**Comment by dilipkrish** [comment]
@ysjiang4869 thank you! yes there is a plan to support it in the next release.
