### ISSUE TITLE
Swagger UI gives 404 if there is a mapping with just one PathVariable

### ISSUE THREAD

**Issue by pvpkiran** [springfox/springfox#2109]
I have a controller with a GET mapping like this   
`/{someId}`.   
With this my spring boot application starts without any error. But when I try to reach swagger-ui.html, I get 404.   
But I can access /v2/api-docs. I am using spring boot version 1.5.8 and springfox 2.7.0. But If i change the mapping to `/something/{someId}` or `/{someId}/{someOtherId}`, Swagger UI works fine.

**Comment by dilipkrish** [comment]
What is your context root? And what URL does swagger-ui think you're using?
