### ISSUE TITLE
swagger

### ISSUE THREAD

**Issue by GoudGopichand** [springfox/springfox#2110]
I am running two spring boot microservices on two port 8081 8082 however when i try to access swagger.ui.html i can only access one

**Comment by dilipkrish** [comment]
Swagger-ui runs on the same port as the micro service. Would you mind explaining how you're hosting it on 2 different ports?

**Comment by GoudGopichand** [comment]
Basically i have  two webservices running on localhost but on port 8081 and 8082 and in both services i have swaager configuration. However when i try to access http://localhost:8081/swagger-ui.html
Http://localhost:8082/swagher-ui.html 
Only one is working .i.e i am able to see only api doc in swagger ui

**Comment by dilipkrish** [comment]
You will see the API that is being hosted by the service. So there is one swagger ui for 8081 and one for 8082. And just because they are both swagger-ui they will not show all the APIs that are on you machine.
