### ISSUE TITLE
java long numbers are getting rounded off in swagger-ui

### ISSUE THREAD

**Issue by koushikroy1989** [springfox/springfox#2112]
JavaScript doesn't support java long values, Hence if any model has long value, like **2339525510812146419**, java script is rounding it to **2339525510812146000** on the swagger ui. Can this be fixed in swagger ui, so that it supports java long numbers?

Latest 2.7.0 spring fox swagger ui is used along with 2.7.0 swagger2.

**Comment by dilipkrish** [comment]
This is a swagger-ui issue I believe

**Comment by fein91** [comment]
I am still facing this issue, are you sure that it was fixed in 2.8.0?

**Comment by koushikroy1989** [comment]
I took the workaround to represent long numbers as strings on rest API.
JavaScript has this limitation with long numbers so tried to avoid this.

**Comment by dilipkrish** [comment]
@fein91 This is not an issue in this project. Its a swagger-ui issue like I mentioned above.
