### ISSUE TITLE
Generate swagger UI with YAML file, instead of annotations

### ISSUE THREAD

**Issue by tomiok** [springfox/springfox#2115]
Hi team, I am using springfox v2.7.0 and i'd like to generate my Swagger UI with a yaml file, instead of annotate my .java files.
My config is something like this now.

`@Bean
  public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2)
        .useDefaultResponseMessages(false)
        .select()
        .apis(RequestHandlerSelectors.any())
        .paths(PathSelectors.ant("/api/**"))
        .build();
  }`

I 've generate get the json and translate to yaml using the Swagger editor.

Regards, !

**Comment by dilipkrish** [comment]
There is an outstanding PR/issue for it #1488 #2102

**Comment by dilipkrish** [comment]
Closing this a duplicate since there is an issue and PR already waiting in the wings for it.
