### ISSUE TITLE
Question: Separating methods with path variable

### ISSUE THREAD

**Issue by Jeff-Walker** [springfox/springfox#2116]
I have a controller that includes a path parameter that's based on a enum. Is there an easier way to force the documentation to show separate methods instead of a single one with a path variable among the parameters.

Right now I'm using an `ApiListingScannerPlugin`, but that forces me to specify everything by hand, that is, each operation and parameter list, instead of using the automatic generation.

I understand that it isn't something that you could do automatically because you wouldn't know what the possible values are.

Thanks.

**Comment by dilipkrish** [comment]
@Jeff-Walker Its not easy. Like you said you may have to do it by hand.
