### ISSUE TITLE
Question: how to add a model definition without a Java class

### ISSUE THREAD

**Issue by Jeff-Walker** [springfox/springfox#2117]
I have a controller that writes it's response directly to the output stream using the Jackson streaming api. I don't have a Java class for it because the structure depends on some internal logic. I see how to add `additionalModels()` but it only takes Java types.

I've tried to write a `ModelBuilderPlugin` but it's not clear how to actually add it to the list of models available in the api.

**Comment by dilipkrish** [comment]
@Jeff-Walker You can add models, but Im not sure you can tie it back to operations using builders. You can annotate the operations with annotations to aid springfox, and that might be the easier solution.

**Comment by Jeff-Walker** [comment]
Thanks for the reply. Can you elaborate? I don't think I understand.

I don't mind writing json/yml by hand. Is there maybe a way to inject it into the stuff springfox generates?

**Comment by dilipkrish** [comment]
Sorry for not being clear, what I meant was say you have an operation `String A()` where string is actually a type, or your case where `void B(HttpResponse resp)` where you can write to the response. You can add models to the schema easily, but you need to some how tell swagger that A uses/responds with the model you just added. 

I would say you can implement your own `OperationModelsProviderPlugin` that looks at your own custom annotation perhaps and adds the input params and/or return values to the `RequestMappingContext`

**Comment by a100488** [comment]
您好,可以给个demo吗   ,我想自定义返回的注释
![image](https://user-images.githubusercontent.com/12635040/33536783-2f057d4e-d8f2-11e7-8d35-660886b02772.png)
