### ISSUE TITLE
Request type mapping doesn't work if using both RequestBody and ModelAttribute on the same parameter

### ISSUE THREAD

**Issue by andrea-sdl** [springfox/springfox#2118]
Hello everyone,
I think I found a small bug,

I'm using version 2.7.0 with spring boot 1.3.1 and spring 4.2.4.
## Setup and Bug description
We have a rest service that has a input object annotated both with `RequestBody `and `ModelAttribute`.
Once we go into the `swagger-ui.html` the `Data Type` of the parameter is `undefined`.

If we remove one of the 2 annotations (`RequestBody `or `ModelAttribute`) everything works fine.
Looking at the api-docs json seems like it's configured as type "ref" but it doesn't reference anything.

 ```
{
      "get": {
        "tags": [
          "rest-model-bug"
        ],
        "summary": "test",
        "operationId": "testUsingGET",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "*/*"
        ],
        "parameters": [
          {
            "name": "person",
            "in": "query",
            "description": "person",
            "required": true,
            "type": "ref"
          }
        ],
          //....
        }
      }
    }
```
## Expected result
What I would expect is that it should result either in expecting a JSON (Like if we only have `RequestBody `annotation) or with 1 parameter per field (as if we have only the `ModelAttribute `annotation).
instead it goes to type "ref" and it doesn't work.

## How to see the bug
You can check the bug using my repo https://github.com/andrea-sdl/springfox-bug-example and executing it with ` mvn spring-boot:run` , refer to class [RestModelBug.java](https://github.com/andrea-sdl/springfox-bug-example/blob/master/src/main/java/com/springfox/examplebug/RestModelBug.java) to see the code.

My guess is that there's some conflicts between the two annotations, I noticed that if I switch the order of the ifs in the ParameterTypeReader by having the modelattribute _before_ the `RequestBody `it works.

Right now I workaround the bug by having a second `ParameterTypeReader`  with the `@Primary` spring annotation and the aforementioned change ([here it is how the java class should be changed](https://gist.github.com/andrea-sdl/ef03c3753460e1438134ce8becacabaf)  ).

I dunno though if this should be the correct way to address the bug (If yes, I can do a small PR to the project).

**Comment by dilipkrish** [comment]
@andrea-sdl thanks for the detailed bug report. Yes its a bug, would you mind trying 2.7.1-SNAPSHOT to see if its fixed

**Comment by andrea-sdl** [comment]
@dilipkrish can confirm, works perfectly with 2.7.1-SNAPSHOT ;) can't wait for the release ;) thanks!
