### ISSUE TITLE
Question: How to change the base url?

### ISSUE THREAD

**Issue by ALeonard9** [springfox/springfox#2121]
Version: Latest

I am using springfox to generate my api documentation. Everything is working and generating successfully. 

However, I am using Akana to protect my API, which means I have a different base url than the one on my box. Is it possible to configure the base url?

**Comment by dilipkrish** [comment]
@ALeonard9 You'd need to have `Akana` (sorry I haven't used it), send in the appropriate X-FORWARD-XXXXX headers to get it to translate correctly.

**Comment by ALeonard9** [comment]
@dilipkrish Do you have an example header?
