### ISSUE TITLE
How to display "/oauth/token" endpoint on swagger-ui?

### ISSUE THREAD

**Issue by steventong** [springfox/springfox#2122]
My project use spring cloud oauth to authenticate user with "/oauth/token" endpoint, but i can't find any way to display this api operation on swagger ui. What should I do?
 
Thank you!

**Comment by andreabreu-me** [comment]
You need to define the paths in docket bean. Look at [http://springfox.github.io/springfox/docs/current/#docket-spring-java-configuration](url)

**Comment by dilipkrish** [comment]
@steventong You can manually add that documentation for the endpoint.

**Comment by ChanggyunCho** [comment]
If you want to list path manually, you need to implement ApiListingScannerPlugin like <http://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin>.

```java
public class SwaggerManualApiPlugin implements ApiListingScannerPlugin {

    @Override
    public boolean supports(DocumentationType delimiter) {
        return DocumentationType.SWAGGER_2.equals(delimiter);
    }

    @Override
    public List<ApiDescription> apply(DocumentationContext context) {
        ...
    }

}

```

And declare bean and include path to Docket in the swagger config.

```java
@Configuration
@EnableSwagger2
public class SwaggerConfig {
    ...
    
    @Bean
    public ApiListingScannerPlugin listingScanner() {
        return new SwaggerManualApiPlugin();
    }
```

Now you can see your api on swagger-ui.

**Comment by dilipkrish** [comment]
@ChanggyunCho Also keep in mind that you want to order the bean to happen after the spring web plugins have run.

**Comment by steventong** [comment]
ApiListingScannerPlugin is working for me. Thanks, @ChanggyunCho

**Comment by ShradhaFielddata** [comment]
Hi, I am using the custom API but the token url also contains the base path of the API.
My token url is a separate auth0 server token url.
How can I remove the api base path from my token url?

**Comment by HungUnicorn** [comment]
Can the example listed here https://springfox.github.io/springfox/docs/current/#security meets the requirement that displays oauth endpoints?

**Comment by dilipkrish** [comment]
@HungUnicorn that is pre 3.0 it needs to be updated
