### ISSUE TITLE
How to make springfox use my own swagger.json file?

### ISSUE THREAD

**Issue by artizjma** [springfox/springfox#2126]
Hello,

I am creating a springboot app based on Jersey. I configure everything and I have a swagger.json available at localhost:8080/api/swagger.json. However I'd still like to use springfox for swagger UI.

I cannot find a proper way to configure everything to make it work. Would you be able to give me some guidance about how we can customize swagger-resources and docket to just make it use my own provided swagger.json URL ? I tried setting a RelativePathProvider without success.

**Comment by dilipkrish** [comment]
You need to create a bean as described in [this comment](https://github.com/springfox/springfox/issues/2123#issuecomment-348217949). Load the swagger.json and serve it up.

**Comment by vspiliopoulos** [comment]
@dilipkrish Could you elaborate a little  bit more on how to use a custom json swagger file?

More specifically:

`@Component
@Primary
public class CustomInMemorySwaggerResourcesProvider implements SwaggerResourcesProvider {
 @Override
	public List<SwaggerResource> get() {
               // how do we load the locally available swagger.json?
	}
}`

Also, is InMemorySwaggerResourcesProvider able to load a different swaggere json file? Or it can only expose the annotations based generated swagger.json to a different url?

Many Thanks!

**Comment by dilipkrish** [comment]
You dont need to load the locally available, you just need to link to it. For e.g. if you have swagger.json in your resources folder, spring boot will automatically serve it up at `http://localhost:8080/swagger.json` when you're running it locally, so your swagger resource should point to that link.

**Comment by hacki11** [comment]
this was helpful for me, using my own swagger.json with springfox-swagger-ui:
indrabasak/springfox-ui-from-json-example#2
