### ISSUE TITLE
Endpoints not exported with Spring Data REST

### ISSUE THREAD

**Issue by drenda** [springfox/springfox#2127]
I've a project using Spring Boot, Spring Data REST, Spring HATEOAS. Lately I did a refactoring of my methods following Spring best practice. Mainly I use a combination of custom @RepositoryRestController and normal Repository that are automatically exposed from Spring.

Given this repository:

```
@Transactional
@PreAuthorize("isAuthenticated()")
public interface EmailRepository extends JpaRepository<Email, Long> {

	@ApiIgnore
	@RestResource(exported = false)
	@Override
	public <S extends Email> List<S> save(Iterable<S> entities);

	@ApiIgnore
	@RestResource(exported = false)
	@Override
	public <S extends Email> S save(S entity);

	@ApiIgnore
	@RestResource(exported = false)
	@Override
	public <S extends Email> S saveAndFlush(S entity);

	@ApiIgnore
	@RestResource(exported = false)
	@Override
	public void delete(Email entity);

	@ApiIgnore
	@RestResource(exported = false)
	@Override
	public void delete(Iterable<? extends Email> entities);

	@ApiIgnore
	@RestResource(exported = false)
	@Override
	public void delete(Long id);

	@ApiIgnore
	@RestResource(exported = false)
	@Override
	public void deleteAll();

	
	public List<Email> findByStatus(EmailStatus status);

	
	@ApiIgnore
	@RestResource(exported = false)
	@Query("SELECT m FROM Media m WHERE m.parentType='Email' AND m.parentId=:id ORDER BY m.createdDate DESC, m.id DESC")
	public Page<Media> findAllMedia(@RequestParam(value = "id", required = true) @Param("id") long id, Pageable pageable);

	
	@Query("SELECT m FROM Media m WHERE m.parentType='Email' AND m.parentId=:id")
	public List<Media> findAllMedia(@RequestParam(value = "id", required = true) @Param("id") long id);
}
```

and this is the controller:

```
@Api(tags = "Email Entity")
@RepositoryRestController
@PreAuthorize("isAuthenticated()")
public class EmailController extends RevisionController<LicensePlate> {
	private Logger log = LogManager.getLogger();

	@Autowired
	private LocalValidatorFactoryBean validator;

	@Autowired
	private EmailRepository emailRepository;

	@Autowired
	private EmailService emailService;

	@Autowired
	private MediaRepository mediaRepository;

	@Value("${storage.path}")
	private String storagePath;

	@InitBinder
	protected void initBinder(WebDataBinder binder) {
		binder.addValidators(validator);
	}
        @PostMapping(path = "/emails")
	public ResponseEntity<?> saveEmail(@Valid @RequestBody(required = true) RestEmail email, Locale locale,
			PersistentEntityResourceAssembler resourceAssembler) {
		Email emailToSave = new Email();
		emailToSave.setFrom(email.getFrom());
		emailToSave.setText(email.getText());
		emailToSave.setSubject(email.getSubject());
		emailToSave.setTo(email.getTo());

		List<Media> media = AppUtils.getObjectsFromUris(email.getMedia(), mediaRepository);

		emailToSave = emailService.saveWithMedia(emailToSave, media, locale);
		return new ResponseEntity<Resource<?>>(resourceAssembler.toResource(emailToSave), HttpStatus.OK);
	}
        @PostMapping(path = "/emails/{id}/cancel")
	public ResponseEntity<?> cancelSending(@PathVariable(value = "id") long id, Locale locale,
			PersistentEntityResourceAssembler resourceAssembler) {
		Email email = emailRepository.findOne(id);
		if (email != null) {
			email = emailService.cancelSending(email);
			return new ResponseEntity<>(resourceAssembler.toResource(email), HttpStatus.OK);
		}
		throw new ResourceNotFoundException();
	}

}
```
This is what I see from swagger:

![swagger](https://user-images.githubusercontent.com/3420646/33548912-26d8fdfc-d8e9-11e7-9dc9-8af799852da9.png)

As you can see, I don't see my custom methods.
This is the configuration of Swagger:

```
@Configuration
@EnableSwagger2
@Import({ springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration.class,
		springfox.bean.validators.configuration.BeanValidatorPluginsConfiguration.class })
@ComponentScan(basePackageClasses = { RebusApplication.class })
public class SwaggerConfig {

	@Autowired
	private TypeResolver typeResolver;

	@Bean
	public Docket internalAngularApi() {
		return new Docket(DocumentationType.SPRING_WEB)// Enable swagger2
				.select().//
				apis(RequestHandlerSelectors.any())// what list in the doc
				.paths(paths()).build()// select which paths shows
				.pathMapping("/").// the api base path
				// directModelSubstitute(LocalDate.class, String.class).//
				// replace
				// specific
				// model
				genericModelSubstitutes(ResponseEntity.class)// generic
																// replacement
				.alternateTypeRules(
						newRule(typeResolver.resolve(DeferredResult.class, typeResolver.resolve(ResponseEntity.class, WildcardType.class)),
								typeResolver.resolve(WildcardType.class)))
				.useDefaultResponseMessages(false).//
				enableUrlTemplating(false).apiInfo(apiInfo()).groupName("Internal API for Angular UI");//
	}

	// Here is an example where we select any api that matches one of these
	// paths
	private Predicate<String> paths() {
		return or(regex("/api/v1/.*"), regex("/error/.*"));
	}

	@Bean
	public UiConfiguration uiConfig() {
		return new UiConfiguration("validatorUrl", // url
				"none", // docExpansion => none | list
				"alpha", // apiSorter => alpha
				"schema", // defaultModelRendering => schema
				UiConfiguration.Constants.DEFAULT_SUBMIT_METHODS, //
				false, // enableJsonEditor
				true, // showRequestHeaders => true | false
				6000L); // requestTimeout => in milliseconds
	}
```

Am I doing something wrong?

**Comment by dilipkrish** [comment]
You've only shown a snippet of your swagger spec. Couple of things that stand out are
- Did you intend to expose `EmailRepository` as a REST service? If not you should consider not exporting it (#2072 recently addressed that).
-You should probably make your controller a `@BasePathAwareController` instead of a rest controller. 
- Try chasing `enableUrlTemplating` to true
My guess is that your controllers are getting hidden because the paths match.

**Comment by drenda** [comment]
Thanks for your quick reply:

- I want export it as a REST reservice and is what it is doing. The code already do that. In fact you can see methods /search/xxx
- My controller is a `@RepositoryRestController` that is already `@BasePathAwareController`
- I tried to set `enableUrlTemplating` to true but it doesn't make any difference

Probably you are right, but this just happens for swagger. My endpoint works perfectly when I call them. Seems Swagger doesn't recognize it. Some advice? 

Thanks

**Comment by dilipkrish** [comment]
Would you mind changing your path selection to allow any path. Just want to check if perhaps thats what is causing your request mappings to be ignored.

**Comment by drenda** [comment]
Do you mean in my swagger config do something like:

`private Predicate<String> paths() {
		return or(regex("/*"));
	}`

?

**Comment by dilipkrish** [comment]
Yes. Or you could use the `PathSelectors#any()`

**Comment by drenda** [comment]
I tried but I had not luck.

**Comment by dilipkrish** [comment]
Could you share a minimal project with the issue reproduced?

**Comment by drenda** [comment]
I created a minimal project. Just run it and you will see these endpoints in swagger:

<img width="1265" alt="schermata 2018-01-16 alle 12 55 22" src="https://user-images.githubusercontent.com/3420646/34987741-8ee9b194-fabc-11e7-93ad-848d00a72e95.png">

but like you can see in UserController, also these endpoints should be displayed:

- /users/loggedUser
- /users/{id}
- /users/{id}/password

Like I said, the controller is annotate with @RepositoryRestController that is already @BasePathAwareController

[swagger-problem.zip](https://github.com/springfox/springfox/files/1634947/swagger-problem.zip)

**Comment by drenda** [comment]
Can this issue be reopened?

**Comment by baurchanu** [comment]
I have the same problem with @RepositoryRestController and @BasePathAwareController. 
Please reopen the issue.

**Comment by drenda** [comment]
Still closed. Are we supposed to open a new one?

**Comment by dilipkrish** [comment]
@drenda reopening

**Comment by dilipkrish** [comment]
@drenda I assumed since you created the issue you could always reopen it.

**Comment by drenda** [comment]
@dilipkrish No I can't. I have not enought rights I guess.

**Comment by drenda** [comment]
Some news about this issue? Thanks

**Comment by dilipkrish** [comment]
None yet, but its slated for 2.9

**Comment by dilipkrish** [comment]
@drenda based on this answer and your project, adding `@RequestMapping("/")` to you controller fixes the issue.

**Comment by predrag-viceic** [comment]
Hello,

The solution provided in the answer isn't applicable to ``@RepositoryRestController `` because it's advised against annotating on class level for this type of interfaces:

https://jira.spring.io/browse/DATAREST-535

Wouldn't be possible to include @RepositoryRestController annotation in automatically parsed annotations ?

**Comment by kabasakalis** [comment]
Please remove the "has a workaround" tag. Adding a type leve `@RequestMapping` annotation destroys the  proper overriding of the spring data rest controllers, see  https://jira.spring.io/browse/DATAREST-535 link . I can't believe one year later this issue is not resolved. Is this project still under development?
