### ISSUE TITLE
Rendering swagger-ui.html

### ISSUE THREAD

**Issue by jonbcs** [springfox/springfox#2128]
Hi guys,
swagger-ui.html has just stopped loading all css. The page loads correctly with correct controllers etc but the css has stopped loading. This happened after I made changes to the basepath in the context.xml file. The project is being deployed as a war on Tomcat. All other springfox projects I am running are all of a sudden behaving in the same manner. Please help!
![renderissue](https://user-images.githubusercontent.com/34251448/33574912-91164d46-d943-11e7-8504-d98a0196d3d8.png)

**Comment by dilipkrish** [comment]
You need to find the path the css is being served, once you know that, adjust the path using the `Docket#pathMapping` method.

**Comment by jonbcs** [comment]
Thanks for the response. I believe I must be using it incorrectly as it makes no difference. My Docket config is as follows. 
`    @Bean
    public Docket customImplementation(){
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("za.co.ubunye.users.server.api"))
                .build()
                .pathMapping("/webjars")
                .directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
                .directModelSubstitute(java.time.OffsetDateTime.class, java.util.Date.class)
                .apiInfo(apiInfo());
    }
`
On page load I am getting the following in the console.
![springfox-e1](https://user-images.githubusercontent.com/34251448/33650706-c62ee398-da6b-11e7-8eb0-c57d31ed17b4.png)

Apologies if this is not enough info. I am a newbie with swagger and springfox and finding my way around. Thanks again.

**Comment by dilipkrish** [comment]
Remove that setting (`.pathMapping('/webjars')`) and try pointing your address bar location on the browser to `http://localhost:8080/swagger-ui.html`

**Comment by jonbcs** [comment]
I have removed it. The address is correct `http://localhost:8080/ubunye/api/user-manager/swagger-ui.html` and all functionality works great, it is just not loading the css. http://localhost:8080/swagger-ui.html returns a 404 as expected.

**Comment by dilipkrish** [comment]
What is your spring context root? if is `ubunye` then try `http://localhost:8080/ubunye/swagger-ui.html`. Your swagger-ui needs to be at the context root.

**Comment by jonbcs** [comment]
Context is `ubunye/api/user-manager`. This will form part of multiple micro services. This component's context is `ubunye/api/user-manager`, another component will be `ubunye/api/customers` etc...

**Comment by dilipkrish** [comment]
got it. Do you have spring security turned on by any chance?

**Comment by jonbcs** [comment]
This issue started when I changed the context.xml `<Context path="/ubunye/user-manager"/>` to `<Context path="/ubunye/api/user-manager"/>`. That is when I lost all css on the swagger-ui.html page. As I toggled between the two contexts I would have css and then not have css. Eventually it made no difference what the context path was I now have the page but no css. I am confused ;). Another strange thing is that all my other netbeans swagger/springfox trials started rendering without css.

Is it possible that some sort of path is written to the springfox library at load. I have even removed my local springfox maven libraries and then re-downloaded. Am still getting the same result.

In response to your question above. I am also rather new to spring and so don't know. I initially created swagger yaml and then had codegen generate the springboot server stubs for me. I made a few further changes including adding `CorsConfig extends WebMvcConfigurerAdapter` and others.

As a basis this is my POM. It may be that I have conflicting libraries?
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ubunye</groupId>
    <artifactId>ubunye-users</artifactId>
    <packaging>war</packaging>
    <name>ubunye-users</name>
    <version>1.0.0</version>
    <properties>
        <java.version>1.8</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <springfox-version>2.7.0</springfox-version>
    </properties>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.8.RELEASE</version>
    </parent>
    <build>
        <sourceDirectory>src/main/java</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.7.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>${springfox-version}</version>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        
        <dependency>
            <groupId>jlogs</groupId>
            <artifactId>JLogsMV</artifactId>
            <version>1.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.10.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.10.0</version>
        </dependency>
        
        
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>1.1.0.Final</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
`

**Comment by dilipkrish** [comment]
@jonbcs it might help to clear your browser cache as well just to be sure

**Comment by jonbcs** [comment]
Thanks again. I have just started a build of a new component with the exact same dependencies and it is rendering perfectly.
![issue-1](https://user-images.githubusercontent.com/34251448/33717986-93154638-db64-11e7-86da-a0608c878393.png)

The original issue still persits.
![issue-2](https://user-images.githubusercontent.com/34251448/33718014-a6787fb0-db64-11e7-805c-5617022b5172.png)

I am going to strip the project and start again and see if I can pinpoint at what stage this is happening. Will let you know if I can find it.
As a newbie I go through a lot of trial and error, springboot alone is quite a large task to get a grip on. Am loving the use of Swagger and Springfox and so will persist until I get it working. It will make integration by multiple devs on multiple components an absolute pleasure.

**Comment by dilipkrish** [comment]
@jonbcs thank you for your kind words. These are what makes working on OSS so worth It!
