### ISSUE TITLE
@ApiModelProperty has no effect on some variables (name starting with one lowercase)

### ISSUE THREAD

**Issue by bbrenne** [springfox/springfox#2132]
When using `@ApiModelProperty` to describe a model property, it fails in some cases. 

Also the name is modified (yMax become ymax).

Case that works:
```java
   @ApiModelProperty(required = true, value = "test")
   private double ylMax;
```
Case that does not work:
```java
   @ApiModelProperty(required = true, value = "test")
   private double yMax;
```
Result:
```json
"ROIRequest":{
         "type":"object",
         "required":[
            "ylMax"
         ],
         "properties":{
            "ylMax":{
               "type":"number",
               "format":"double",
               "description":"test"
            },
            "ymax":{
               "type":"number",
               "format":"double"
            }
         }
      },
```
Version used:
```xml
         <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.7.0</version>
         </dependency>
```

**Comment by dilipkrish** [comment]
@bbrenne Not really sure. Can you create a breaking test in the [BugsController](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java)

**Comment by bbrenne** [comment]
I'm not really comfortable with gradle and your testing framework.

It should be something like this:
```java
  @RequestMapping(value = "2132", method = GET)
  public void apiModelPropertyXMax(@RequestBody Bug2132 body) {
    throw new UnsupportedOperationException();
  }

  class Bug2132 {

    @ApiModelProperty(value = "the maximum x", required = true)
    private int xMax;

    public int getXMax() {
      return xMax;
    }

    public void setXMax(int xMax) {
      this.xMax = xMax;
    }

  }
```

And this in declaration-bugs-service.json:
```json
    "/bugs/2132": {
      "get": {
        "tags": [
          "Bugs"
        ],
        "summary": "bug2132",
        "operationId": "bug2132UsingGET_1",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Bug2132"
            }
          }
        }
      }
    },
...
"definitions": {
    "Bug2132": {
      "type": "object",
      "required": [
        "xMax"
      ],
      "properties": {
        "xMax": {
          "type": "integer",
          "description": "the maximum x"
        }
      }
    },
...
```

Can you try that on your side?

**Comment by bbrenne** [comment]
After heavy debugging I have more information on that issue, it will not be easy to fix.

By default underlying fasterxml/jackson library compute properties using fields and methods. Field is find in our case, it gets xMax, but on setter and getter setXMax will give you a property named xmax. This is due to default strategy of fasterxml/jackson.

You can change that using the standard bean naming (spring.jackson.mapper.USE_STD_BEAN_NAMING=true). If you do that you get a different result: a property named XMax. In both cases the information on the field are not found and the description or the required flag are ignored.

So naming a variable with a lower case followed by an upper case is a NO-GO. 

If you want to investigate further on that, this is the stack involved:
springfox.documentation.schema.property.OptimizedModelPropertiesProvider
com.fasterxml.jackson.databind.DeserializationConfig
com.fasterxml.jackson.databind.introspect.BasicClassIntrospector
com.fasterxml.jackson.databind.introspect.BasicBeanDescription
com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector

**Comment by dilipkrish** [comment]
Thanks for you example, I dug in some more and for it to work as you expect the getter/setter needs to conform to the bean spec. O/w you're just going to swim upstream

```java
    public int getxMax() {
      return xMax;
    }

    public void setxMax(int xMax) {
      this.xMax = xMax;
    }
```
