### ISSUE TITLE
Optional<LocalDateTime>

### ISSUE THREAD

**Issue by kitsjory** [springfox/springfox#2133]
spring-boot : 1.5.7.RELEASE
springfox-swagger2 : 2.7.0

This does not seem to get picked up by swagger ui:
`@RequestParam(name = "time", required = false) Optional<LocalDateTime> time`
or
`@RequestParam(name = "time2", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Optional<LocalDateTime> time2`

While this does:
`@RequestParam(name = "bla", required = false) Optional<String> someString`

considering that `genericModelSubstitutes(Optional.class)` is set

Am I missing something?

Kind regards

**Comment by dilipkrish** [comment]
@kitsjory This has been verified to work. Here is another [example I just created](https://github.com/springfox/springfox-demos/tree/bug/2133/showcase-fix). Bring the project down and `./gradlew :boot-swagger:bootRun` and `http://localhost:8080/springfox/swagger-ui.html` and select category api to see the newly added endpoint with your use case.

Also there is no need to add genericModelSubstitutes. It is already baked in 
https://github.com/springfox/springfox/blob/11c3f2254d20a050964465262523c62747f589f0/springfox-spi/src/main/java/springfox/documentation/spi/service/contexts/Defaults.java#L119-L125

**Comment by kitsjory** [comment]
@dilipkrish 
Yeah, just checked out the source and found out that Optional<LocalDateTime> works with 2.7.1-SNAPSHOT, but not with 2.7.0. 

Thanks.

**Comment by dilipkrish** [comment]
Cool release for that coming up pretty soon! Thanks for checking @kitsjory
