### ISSUE TITLE
No qualifying bean error when launching spring 5.0.x application with springfox

### ISSUE THREAD

**Issue by gauravphoenix** [springfox/springfox#2135]
Using version `2.7.0` and Spring `5.0.1.RELEASE` 
When I start my Jetty server (version 9.4.6.v20170531), I get following exception - 

```Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}```

has 2.7.0 been tested with Spring 5?

**Comment by dilipkrish** [comment]
It has not see #1773
