### ISSUE TITLE
Adding ability to override baseUrl in springfox.js to change the swagger-ui.html reference

### ISSUE THREAD

**Issue by andrea-sdl** [springfox/springfox#2136]
Hi there, 

using springfox 2.7.0 here.
I know that the reference to the swagger-ui.html is hard-coded :) so the only way to have it on a different url without breaking the interface is to change the springfox.js by hand.

Still, I think it'd be nice to give users some kind of workaround to easily change it without the need to change the springfox.js file so that they can benefit from including the js from the webjars.

I noticed that in the 2.7.0 you added the setBaseUrl, but it isn't used anywhere (mostly because the definition of var baseUrl overrides any possibility to have it in the global variables)

I created a small gist as an example of an effective workaround to allow people customize the baseUrl, thus introducing the ability to have the swagger ui in any path.
We'd still need to take in the swagger html by hand (no way to add custom CSS or JS at the moment), but it's still better than nothing.

Here it is the gist. https://gist.github.com/andrea-sdl/f0df23b398a6bb3a4794af18c26395e5
the interesting part are these 3 lines right before the init.

```js
//Adds support for overriding the baseUrl
if (typeof window.springfoxBaseUrlOverride === 'string'){
	  springfox.setBaseUrl(springfoxBaseUrlOverride);
}
```

This way you only need to define the 
`springfoxBaseUrlOverride`
into the html and you're done.

What do you think? 
Would it be possible in the future to have some kind of workaround?

**Comment by dilipkrish** [comment]
Thats a great suggestion. Couple of things to think about before implementing it tho. 
- Currently if you don't find the url you can still override it by hand, which is equivalent of your suggestion.
https://github.com/springfox/springfox/blob/11c3f2254d20a050964465262523c62747f589f0/springfox-swagger-ui/src/web/js/springfox.js#L137-L145
- The swagger ui is completely revamped, to use react. So I'd wait to make this change

Also swagger-ui.html isn't hardcoded really (other than the name itself), it is pinning the location of all the other resources relative to swagger-ui.html.

**Comment by andrea-sdl** [comment]
@dilipkrish thanks for the quick reply!
I saw the onError function but there's no way at the moment to avoid the popup entirely, which is my concern. I'd like to have springfox automatically use the new baseUrl without user intervention.

As for the revamp I saw the issues on github, good news. 
Is there any estimate about the revamp completion? 
Lemme know if you do need some help to push it forward, I'm no react expert, but I did develop with it some things in the past, so I might give a hand if you need it.

I agree that it's not a top priority fix, but if the estimate to see the revamp live is far from now, it could be nice to offer this workaround even to those that won't instantly upgrade to the react version. 
I suspect not everyone will jump right away in the new version, but that's my opinion.

**Comment by dilipkrish** [comment]
@andrea-sdl that’s more experience than I have.l with react!! Let me think about your suggestion and see if I can get it to work like you expect in th upcoming 2.8.0. 

In the mean while if you’d like to help with moving to swagger-ui 3.0 let me know I’d be happy to set up a branch for you to work on.

**Comment by andrea-sdl** [comment]
@dilipkrish thanks, if it makes it into the 2.8.0 it'll be awesome! I'd avoid some overriding here and there.

As for react, yeah! is there any deadline to keep in mind for this transition? 
I'll be out for my honeymoon the whole month of january, so it might take at least a month or 2 to see it completed. 
If it's ok let's go with the new branch for this ;)

**Comment by artem-emelin** [comment]
Would be great to have this option in the upcoming 2.8.0 release.
The baseUrl could be auto-detected from `Docket` configured `pathProvider` field plus a property value _springfox.documentation.swagger.v2.path_.

**Comment by andrea-sdl** [comment]
Any news about it? If you need help I'll be glad to lend a hand.

**Comment by dilipkrish** [comment]
@andrea-sdl would definitely appreciate your help.
