### ISSUE TITLE
From swagger editor able to get the JWT auth token, but from application which enabled swagger-ui using springfox is not working

### ISSUE THREAD

**Issue by ranjithap7576** [springfox/springfox#2137]
Tested my auth server from swagger editor and is working fine. I'm able to get the token and authorization is happening without any issues. But, when I tried to integrate it with my web service where swagger UI is enabled using springfox dependencies is not working. 

Success form swagger editor

![success](https://user-images.githubusercontent.com/4425063/33711894-a243f1d4-db6b-11e7-9fde-d79e5ac0f008.JPG)

Failed from application

![failed](https://user-images.githubusercontent.com/4425063/33711904-aa5a188a-db6b-11e7-8091-39795eabed33.JPG)

   Noticed that in the failed case, swagger UI is sending only a single POST request, but swagger editor had an OPTIONS & POST request to get the token.

Suspected CROS filter initially, so I took my swagger json and tested in swagger editor and it worked. My auth server and resource server with application is also working fine when tested via curl.

Sample auth server and resource server is this:- https://github.com/ranjithap7576/OAuth2-JWT

And swagger configuration is below
```
@Configuration
@EnableSwagger2
public class SwaggerConfigNew {

	@Value("${security.jwt.resource-ids}")
	private String clientId;
	@Value("${security.signing-key}")
	private String clientSecret;

	@Value("${security.oauth2.authserver}")
	private String authLink;

	@Bean
	public Docket api() {

		return new Docket(DocumentationType.SWAGGER_2).select()
				.apis(RequestHandlerSelectors.basePackage("my.package")).build().groupName("test")
				.directModelSubstitute(org.joda.time.LocalDate.class, java.sql.Date.class)
				.directModelSubstitute(org.joda.time.DateTime.class, java.util.Date.class)
				.securitySchemes(Collections.singletonList(securitySchema()))
				.securityContexts(Collections.singletonList(securityContext()));

	}

	private OAuth securitySchema() {
		List<AuthorizationScope> authorizationScopeList = newArrayList();
		authorizationScopeList.add(new AuthorizationScope("read", "read all"));
		authorizationScopeList.add(new AuthorizationScope("trust", "trust all"));
		authorizationScopeList.add(new AuthorizationScope("write", "access all"));
		List<GrantType> grantTypes = newArrayList();
		GrantType creGrant = new ResourceOwnerPasswordCredentialsGrant(authLink + "/oauth/token");
		grantTypes.add(creGrant);
		return new OAuth("oauth2schema", authorizationScopeList, grantTypes);

	}

	@Bean
	UiConfiguration uiConfig() {
		return new UiConfiguration("validatorUrl", // url
				"none", // docExpansion => none | list
				"alpha", // apiSorter => alpha
				"schema", // defaultModelRendering => schema
				UiConfiguration.Constants.DEFAULT_SUBMIT_METHODS, false, // enableJsonEditor => true | false
				true, // showRequestHeaders => true | false
				60000L); // requestTimeout => in milliseconds, defaults to null (uses jquery xh timeout)
	}

	@Bean
	public SecurityConfiguration securityInfo() {
		return new SecurityConfiguration(clientId, clientSecret, "", "", "", ApiKeyVehicle.HEADER, "", " ");
	}

	private SecurityContext securityContext() {
		return SecurityContext.builder().securityReferences(defaultAuth()).forPaths(PathSelectors.ant("/user/**"))
				.build();
	}

	private List<SecurityReference> defaultAuth() {
		final AuthorizationScope[] authorizationScopes = new AuthorizationScope[3];
		authorizationScopes[0] = new AuthorizationScope("read", "read all");
		authorizationScopes[1] = new AuthorizationScope("trust", "trust all");
		authorizationScopes[2] = new AuthorizationScope("write", "write all");
		return Collections.singletonList(new SecurityReference("oauth2schema", authorizationScopes));
	}

	// @Bean
	public WebMvcConfigurer corsConfigurer() {
		return new WebMvcConfigurerAdapter() {
			@Override
			public void addCorsMappings(CorsRegistry registry) {
				registry.addMapping("/**");
			}
		};
	}
```
I'm using springfox 2.7.0

**Comment by dilipkrish** [comment]
@ranjithap7576 Part of the reason is because we're using an older version of swagger-ui with limited ouath capabilities.

**Comment by ranjithap7576** [comment]
@dilipkrish Thanks for the prompt reply.. :) Any suggestions/workaround/patch for this?

**Comment by dilipkrish** [comment]
You could use [__THE__ swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by Jotaro132** [comment]
Hello,

i have the same issue...
Iam searching how i can use Swagger 3.X with Spring Boot and oAuth combination.

**Comment by dilipkrish** [comment]
seen [this](https://github.com/springfox/springfox-oath2-demo) @Jotaro132 ?

**Comment by Jotaro132** [comment]
@dilipkrish 
Iam using Spring Boot, H2 Database and oauth2.
I dont have any experience with YAML, so i have to research to re-write the yml config to my  config.

What i cant understand is this: As you can see above @ranjithap7576 get the Token but Swagger doesent use it, so i get this error "Full authentication is required to access this resource".

I get the token as you can see here : 
https://www.pic-upload.de/view-34805657/2018-02-0812_18_13-SwaggerUI.png.html
https://www.pic-upload.de/view-34805658/2018-02-0812_18_45-SwaggerUI.png.html

As you can see in the curl of swagger, there is no use of the token. I dont know how to change the curl so, that the token always get taken. 
See here: https://www.pic-upload.de/view-34805678/2018-02-0812_23_40-SwaggerUI.png.html

@ranjithap7576 Did you fix the problem?

**Comment by ranjithap7576** [comment]
@Jotaro132 , Not fixed yet. Waiting for the official release.

**Comment by MartinX3** [comment]
Yes.
Getting a 401 from swagger-resources/configuration/ui because the backend is behind a reverse proxy. which wants a bearer token in the auth header.

**Comment by dilipkrish** [comment]
@ranjithap7576 @MartinX3 @Jotaro132 Would you mind trying the 2.8.1-SNAPSHOT to see if that fixes the problem

**Comment by MartinX3** [comment]
I searched for the SNAPSHOT but don't find it.

**Comment by abhijitvk** [comment]
@dilipkrish : We are currently on 2.7.0 but planning to upgrade for the new UI features. However, auth header bearer token is broken on 2.8.0 for UI. Any plan to upgrade or fix 2.8.0 with a patch?

**Comment by MartinX3** [comment]
@abhijitvk
Did you read my post?

**Comment by abhijitvk** [comment]
@MartinX3 : Per your last comment, I see that the issue has been fixed in 2.8.1-SNAPSHOT

**Comment by MartinX3** [comment]
@abhijitvk
Yeahr
And in my first Tests I didn't saw any New bugs

**Comment by dilipkrish** [comment]
@abhijitvk thats been fixed, would be great if you tried the latest snapshot.
