### ISSUE TITLE
Should support "title" property, set via @ApiModel annotation.

### ISSUE THREAD

**Issue by ngbalk** [springfox/springfox#2139]
https://github.com/springfox/springfox/blob/11c3f2254d20a050964465262523c62747f589f0/springfox-core/src/main/java/springfox/documentation/schema/Model.java#L40

Should support "title" in accordance with OpenAPI 2.0: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by ngbalk** [comment]
We wanted to use the ModelBuilderPlugin to set the "title" field on one of our models, but that field does not exist in the springfox.documentation.schema.Model.  Trying to think of a work around that doesn't involve changing the Model class.  Is there any reason why Model isn't symmetrical to https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Model.java ?

**Comment by ngbalk** [comment]
btw this is important because DapperDox (http://dapperdox.io/), an automatic API documentation tool, requires the "title" field be present (https://github.com/DapperDox/dapperdox/blob/7505264d285b2a8455fb04b4a1f884fc0c4a9b8e/spec/spec.go#L1047)

**Comment by ngbalk** [comment]
@kameroli

**Comment by andermirik** [comment]
how can i generate title in schema automatically? need for DapperBox (http://dapperdox.io/) 
my schema in generated file looks like 
```
"responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/StorePart"
              }
            }
          },
        ...
}
```
@dilipkrish

**Comment by TAUnionOtto** [comment]
Any update of this issue? And how about "title" property via `@ApiModelProperty`? It is necessary too.
