### ISSUE TITLE
Dynamic tags display based on process name in java

### ISSUE THREAD

**Issue by pandiaraj2** [springfox/springfox#2142]
I am having single request object for both process(savepropserdetails and saveproposercommunicationdetails), like below

```
private String firstName;
private int age;
private String lastName;
private Date dob;
private String addressOne;
private String addressTwo;
private String city;
private String pincode;

//getters and setters;
```

Each process having separate webservices but swagger generating below json as input and its displays all variables as input.

```
{
    "firstName"  : "xyz",
    "age"     :  20,
    "lastName":  "abc" ,
    "dob" : "12/08/1990", 
    "addressOne" : "No 1",
    "addressTwo" : "Civic Street",
    "city" : "Chennai",
    "pincode" : "123456"
}
```

But instead of above i need swagger to generate below as inputs.

For **savepropserdetails** Web-Serivce: 

```
{
    "firstName"  : "xyz",
    "age"     :  20,
    "lastName":  "abc" ,
    "dob" : "12/08/1990"
}
```

For **saveproposercommunicationdetails** Web-Service:

```
{
     "addressOne" : "No 1",
    "addressTwo" : "Civic Street",
    "city" : "Chennai",
    "pincode" : "123456"
}
```

**Comment by dilipkrish** [comment]
The easiest way is to create two separate objects that represent those processes

**Comment by pandiaraj2** [comment]
Hi @dilipkrish, Is there any other way to do this.

**Comment by dilipkrish** [comment]
There will be in the next release thanks to @MaksimOrlov. Support for `JsonView`. However it would still mean that you need to create separate objects
