### ISSUE TITLE
Swagger not identified

### ISSUE THREAD

**Issue by gnanayakkara** [springfox/springfox#2146]
- [ ] What version of the library are you using? 2.6.1

This is my code.

![image](https://user-images.githubusercontent.com/34508294/33936086-402ee932-e024-11e7-9888-c1f32b0a497d.png)

Controller-

![image](https://user-images.githubusercontent.com/34508294/33936128-78050620-e024-11e7-825d-a7fb075f1cb3.png)

web.xml

![image](https://user-images.githubusercontent.com/34508294/33936242-e7a2c7a6-e024-11e7-97e9-a70b7f751437.png)

And after I execute the program its not showing properly.I dont know wht happen.

![image](https://user-images.githubusercontent.com/34508294/33936334-370f3c02-e025-11e7-99c1-9ec423863761.png)

Wht I have done wrong?plz help me.

**Comment by dilipkrish** [comment]
Where are you getting `myapp` from?

**Comment by gnanayakkara** [comment]
Im getting from jersey server

**Comment by gnanayakkara** [comment]
Im getting from jetty sever

**Comment by dilipkrish** [comment]
Could you find out where the api-docs are being served from? usually it is relative to `<server:port>/<context-path>`

**Comment by gnanayakkara** [comment]
this is my context param -:

![image](https://user-images.githubusercontent.com/34508294/33942378-c1cfb5a4-e03b-11e7-88f5-31641ff1a9cf.png)

could u plz tell me wht should be the url?
Is that **http://localhost:8080/lk.idea.app.modules.core** ?

**Comment by gnanayakkara** [comment]
I think another problem.I removed @EnableSwagger2 annotation and beans.Then send a request and got the same result.

![](https://user-images.githubusercontent.com/34508294/33936334-370f3c02-e025-11e7-99c1-9ec423863761.png).

@dilipkrish wht do u think?

**Comment by dilipkrish** [comment]
First could you upgrade to using 2.7.0 of the library.  One more thing to try is to add `.pathMapping("/myapp")` to your docket configuration. It would be useful if you could share your repository.

**Comment by gnanayakkara** [comment]
Thanks for ur reply.But its not working .same result.Really appreciate if u can log through the team viewer.Because im working on the security app

**Comment by dilipkrish** [comment]
don't know what team viewer is or security app.

**Comment by gnanayakkara** [comment]
oky.I will share my web.xml file

**Comment by gnanayakkara** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">

    <context-param>
        <param-name>contextClass</param-name>
        <param-value>org.springframework.web.context.support.AnnotationConfigWebApplicationContext</param-value>
    </context-param>
    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>lk.ideahub.symphony.modules.core</param-value>
    </context-param>

    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>
    <filter>
        <filter-name>simpleFilter</filter-name>
        <filter-class>lk.ideahub.symphony.controller.security.PreAuthFilter</filter-class>
    </filter>

    <filter-mapping>
        <filter-name>simpleFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
	
	<filter>
        <filter-name>xssFilter</filter-name>
        <filter-class>lk.ideahub.symphony.controller.xssfilter.XSSFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>xssFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
    
    <servlet>
        <servlet-name>restsvc</servlet-name>
        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
        <init-param>
            <param-name>contextClass</param-name>
            <param-value>org.springframework.web.context.support.AnnotationConfigWebApplicationContext</param-value>
        </init-param>
        <init-param>
            <param-name>contextConfigLocation</param-name>
            <param-value>lk.ideahub.symphony.controller.core</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
        <servlet-name>restsvc</servlet-name>
        <url-pattern>/rs/*</url-pattern>
    </servlet-mapping>

</web-app>

**Comment by dilipkrish** [comment]
I see a couple things going on. Would you mind trying `http://localhost:8080/rs/swagger-ui.html`

**Comment by gnanayakkara** [comment]
same result @dilipkrish .Im fed up with this.

**Comment by dilipkrish** [comment]
If it helps here [is a sample app](https://github.com/springfox/springfox-demos/tree/master/spring-xml-swagger). See what differs and might be missing in the way you're doing things.

**Comment by gnanayakkara** [comment]
http://localhost:8080/myapp/v2/api-docs  also return 404  :(

**Comment by gnanayakkara** [comment]
Finally I was able to get things work.But only works **/v2/api-docs** url only.
When I access http://localhost:8080/myapp/swagger-ui.html# ,I got below window.

![image](https://user-images.githubusercontent.com/34508294/34402063-7e1d8e4a-ebc5-11e7-99a7-9ec3e5a267d9.png)


There is an error in console 
![image](https://user-images.githubusercontent.com/34508294/34402074-92f18fba-ebc5-11e7-8081-05d7b48a9f10.png)


![image](https://user-images.githubusercontent.com/34508294/34402098-af4e1610-ebc5-11e7-9262-7e82242384c2.png)

Appreciate ur help

**Comment by gnanayakkara** [comment]
Bump :)

**Comment by dilipkrish** [comment]
Looks like jetty is adding a context path for you (based on your screen shot) of `symphony-server-2.0-SNAPSHOT`. This is just a guess, but you probably need to add try something like `http://localhost:8080/symphony-server-2.0-SNAPSHOT/myapp/v2/api-docs`

**Comment by gnanayakkara** [comment]
localhost:8080/symphony-controller-2.0-SNAPSHOT/v2/api-docs works fine and return json content well

**Comment by gnanayakkara** [comment]
I changed 2.4.0 to 2.6.0 and got below error

![image](https://user-images.githubusercontent.com/34508294/34597493-fe91fce4-f20c-11e7-9495-f7a7e73e14d2.png)

**Comment by dilipkrish** [comment]
Please use 2.7.0 and clear the browser cache or force reload the page.

**Comment by gnanayakkara** [comment]
Still getting below error

![image](https://user-images.githubusercontent.com/34508294/34602047-64d785f2-f224-11e7-91e6-5575883436fe.png)
