### ISSUE TITLE
Creating a custom library of swagger for the application

### ISSUE THREAD

**Issue by susmitbansod** [springfox/springfox#2147]
We have a microservice based application having nearly 10 services. We wanted to add swagger in all the services. So to avoid redundancy we have created a custom swagger spring boot application having configurations for swagger only. This custom swagger boot app has JAR as packaging.

Please find the code below:
**pom.xml**
```xml
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>${swagger.version}</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>${swagger.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<id>exec</id>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<classifier>exec</classifier>
						</configuration>
					</execution>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<!-- Need this to ensure application.yml is excluded -->
							<forceCreation>true</forceCreation>
							<excludes>
								<exclude>application.properties</exclude>
							</excludes>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```

**Configuration class**
```java
@Configuration
@EnableSwagger2
public class SwaggerConfiguration {

	@Value("${swagger.documentation.description: VMWare Documentation for Rest APIs}")
	private String swaggerDocDescription;

	@Value("${swagger.controller.path.regex:/api.*}")
	private String swaggerControllerPathRegex;

	@Value("${spring.application.name:VMWare API Documentation}")
	private String swaggerDocTitle;

	@Value("${api.version:1.0}")
	private String apiVersion;

	public SwaggerConfiguration() {
		// Default Constructor
	}

	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).host("http://localhost:9090").apiInfo(apiInfo()).select().apis(RequestHandlerSelectors.any())
				.paths(regex(swaggerControllerPathRegex)).build();
	}

	private ApiInfo apiInfo() {
		return new ApiInfoBuilder().title(swaggerDocTitle)
				.description(swaggerDocDescription).version(apiVersion).build();
	}

}
```

We are including this JAR in all the other projects using maven. So when I am running the actual services it's giving following error

![swagger_error](https://user-images.githubusercontent.com/25456943/33940345-9a7b7288-e034-11e7-94ca-f0d910b1e6e2.png)

Please let where did I go wrong or how can I solve this issue. Thanks in advance.

**Comment by dilipkrish** [comment]
Couple of things incorrect in your configuration.

`.host("http://localhost:9090")` not sure why you're doing that and secondly it should be only host name not the base url.

Also, could you share what your context path is?

**Comment by susmitbansod** [comment]
in our application path, we have given following config for context:

`
server.context-path=/upu
server.port=7080
`

Also, as I am currently running the application locally that why I have used host as "localhost:9090". if this is wrong then can you please elaborate what should I use in the host.

**Comment by dilipkrish** [comment]
host is automatically determined and is ___optional___. So unless you want it to always be localhost you should not set it.

Try using the url `http://foobar.locktex.com:9090/upu/swagger-ui.html` instead

**Comment by susmitbansod** [comment]
Hi, 

Yes, I tried `http://foobar.locktex.com:9090/upu/swagger-ui.html` but it didn't work.

**Comment by dilipkrish** [comment]
No idea. I could may be try and help if you have a repo that you can share.
