### ISSUE TITLE
Is is possible to support both password and client_credentials flow in swagger-ui?

### ISSUE THREAD

**Issue by mrshawn191** [springfox/springfox#2150]
Is is possible to support both password and client_credentials flow in swagger-ui?

    @Bean
    public SecurityScheme oauth() {
        return new OAuthBuilder()
                .name(OAUTH2_SECURITY_SCHEMA)
                .grantTypes(grantTypes())
                .scopes(scopes())
                .build();
    }

    private List<GrantType> grantTypes() {
        GrantType passwordGrant = new ResourceOwnerPasswordCredentialsGrant(TOKEN_URL);
        GrantType clientCredentialsGrant = new ClientCredentialsGrant(TOKEN_URL);
        return Arrays.asList(passwordGrant, clientCredentialsGrant);
    }

This doesn't seem to work, and my passwordGrant also gets broken. But if I remove clientCredentialsGrant then password flow works fine via the authorize button in the swagger ui.

What is the recommended way to support multiple flows when pressing the authorize button?

**Comment by dilipkrish** [comment]
I think it might be a limitation with the current swagger-ui version supported by springfox
