### ISSUE TITLE
404 when rendering swagger-ui.html and webjars

### ISSUE THREAD

**Issue by codebyamir** [springfox/springfox#2151]
I'm attempting to integrate this into an existing Spring 4 MVC application and running into issues with rendering some of the pages.   

I'm running version 2.50 due to some stackoverflow exceptions I encountered when running the latest version.

The following pages return 404 errors:

- `/swagger-ui.html`
-  Anything under webjars

The following pages work fine and return JSON:

 - 	`/swagger-resources/configuration/security`
 -	`/swagger-resources/configuration/ui`
 -  `/v2/api-docs`

I've added the following to my MVC configuration:

    <mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/"/>
    <mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/"/>

Going to `/swagger-ui.html` shows a 404 error:

    [15/Dec/2017:16:36:07 -0500] "GET /swagger-ui.html HTTP/1.1" 404 36691 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36"

Going to `/webjars/springfox-swagger-ui/springfox.js` shows the same:

    [15/Dec/2017:15:10:08 -0500] "GET /webjars/springfox-swagger-ui/springfox.js HTTP/1.1" 404 36691 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36"

Just looking for some guidance on why this is occurring and how to resolve it.

**Comment by dilipkrish** [comment]
Do you by any chance have spring-security turned on

**Comment by codebyamir** [comment]
Yes, Spring Security is enabled in the application.   Is there something specific I need to look for in that configuration to get it to work?

**Comment by dilipkrish** [comment]
You need to mark all the springfox resources as permitted.

**Comment by codebyamir** [comment]
The request is getting all the way to my controller so I don't think Spring Security is the culprit here.

**Comment by codebyamir** [comment]
I was able to get it to work by adding the following servlet mappings to my web.xml:

```
<servlet-mapping>
    <servlet-name>default</servlet-name>
    <url-pattern>/swagger-ui.html</url-pattern>
    <url-pattern>/webjars/*</url-pattern>
</servlet-mapping>
```

**Comment by dilipkrish** [comment]
@codebyamir thanks of reporting back with the solution!

**Comment by BahgatMashaly** [comment]
I have encountered this problem before and the problem was in the below line in application.properties
spring.resources.add-mappings=false

remove it or change it's value to true
