### ISSUE TITLE
[Question] Is springfox supported for Spring Web Flux?

### ISSUE THREAD

**Issue by balajeetm** [springfox/springfox#2154]
- Spring fox 2.7.0

 - Question. Is springfox supported for Spring Web Flux and Spring web reactive? Will it work without Servlet API?

**Comment by dilipkrish** [comment]
It is currently not supported, but the plan is to support it.

**Comment by balajeetm** [comment]
Thanks

**Comment by o-l-o** [comment]
Do you already have any concrete plans regarding Web Flux support? (some release dates, etc.)

**Comment by dilipkrish** [comment]
April 1st the plan is to release 2.9.0. The last release supporting jdk versions prior to java 8. There are already a couple of PR's to support webflux that provide support for it, post that

**Comment by o-l-o** [comment]
Thank you very much for the answer

**Comment by jivimberg** [comment]
I believe this is the issue you want to subscribe to: #1773

**Comment by dilipkrish** [comment]
Closing as a Duplicate of #1773
