### ISSUE TITLE
Swagger-UI and missing HTTP OK Headers

### ISSUE THREAD

**Issue by sebasira** [springfox/springfox#2156]
I've notice that the swagger-ui from the [swagger editor](https://editor.swagger.io/) is different from what I see in my spring boot project.
Are there any plans in changing this?

Also I notice that when I paste the generate JSON from my spring boot app, I see more fields than in my project swagger-ui. For example, I can only see the header for the response 200 on this new interface

**Comment by dilipkrish** [comment]
Yes. There is already a PR #2153 thanks to @kasecato that should address this.

**Comment by sebasira** [comment]
Nice! Thank you @dilipkrish
