### ISSUE TITLE
How to set a default value to a field of a model?

### ISSUE THREAD

**Issue by michele-mancioppi** [springfox/springfox#2161]
- What version of the library are you using? 2.7.0
- Issue type: Question / Feature request (depending on whether it is possible to do what I wanna dp :D)

How can I assign a default value to a Model property so that it is shown in the example? Case in point, the "default" default value shown in Swagger-UI is `true` for `Boolean` types (btw: weird, I expected false, as that is the default value in Java).

The model I am dealing with is Jackson-based, passing values with `@JSONCreator` in the constructor. I would kinda expect the default value to having to be set there, but I would happily set it on the getter method (too?) if needed.

Besides, I remember vaguely something way back about setting default values using JAXB annotations, bit I cannot find anything about it in the docu or in the issues of this repo.

**Comment by dilipkrish** [comment]
Could you provide a concrete example of your model and its output and contrast it what you were expecting to see. The description is too vague as such for me to do a quick research. It might be easier for you to provide since you're already seeing the issue.

**Comment by michele-mancioppi** [comment]
Sure:

```
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Status {

  private final Boolean enabled;

  private final String mode;

  @JsonCreator
  Status(
      @JsonProperty("enabled") final Boolean enabled,
      @JsonProperty("mode") final String mode) {
    this.enabled = enabled;
    this.mode = mode;
  }

  @JsonProperty("enabled")
  public Boolean isEnabled() {
    return enabled;
  }

  @ApiModelProperty(allowableValues = "all,some,none")
  @JsonProperty("mode")
  public String getMode() {
    return mode;
  }

}
```

Example:

```
{
  "enabled": true,
  "mode": "all"
}
```

Desired:

```
{
  "enabled": false,
  "mode": "all"
}
```

**Comment by dilipkrish** [comment]
Awesome! 🤘

**Comment by dilipkrish** [comment]
Added an example

**Comment by metaruslan** [comment]
@dilipkrish Could you help me with a similar problem?
If I have java.net.URI somewhere in the input or output type structure of my MVC rest endpoint then it'll be displayed with this example:
`{
    "absolute": true,
    "authority": "string",
    "fragment": "string",
    "host": "string",
    "opaque": true,
    "path": "string",
    "port": 0,
    "query": "string",
    "rawAuthority": "string",
    "rawFragment": "string",
    "rawPath": "string",
    "rawQuery": "string",
    "rawSchemeSpecificPart": "string",
    "rawUserInfo": "string",
    "scheme": "string",
    "schemeSpecificPart": "string",
    "userInfo": "string"
  }`
and with this model
`	URI{
absolute	boolean
authority	string
fragment	string
host	string
opaque	boolean
path	string
port	integer($int32)
query	string
rawAuthority	string
rawFragment	string
rawPath	string
rawQuery	string
rawSchemeSpecificPart	string
rawUserInfo	string
scheme	string
schemeSpecificPart	string
userInfo	string
}`

Clearly Springfox just looks at URI as a Java bean, but I want to have it on UI as string. One workaround is to do, for example:
`@RequestParam @ApiParam(example = "s3://path/to/output/")...`
But this only fixes the example and not the model. Also I have to put it in many many places, everywhere basically where I use URI.
Is there a way to somehow globally specify the example and model for the java.net.URI type? If not - is there a hook somewhere I can use to change this representation logic for a specific type?

**Comment by metaruslan** [comment]
I found an approach where I have to list all the possible generics for URI
`.alternateTypeRules(AlternateTypeRules.newRule(
                        typeResolver.resolve(URI.class),
                        typeResolver.resolve(String.class)
                ))
                .alternateTypeRules(AlternateTypeRules.newRule(
                        typeResolver.resolve(List.class, URI.class),
                        typeResolver.resolve(List.class, String.class)))
                .alternateTypeRules(AlternateTypeRules.newRule(
                        typeResolver.resolve(Map.class, WildcardType.class, URI.class),
                        typeResolver.resolve(Map.class, WildcardType.class, String.class)))
                .alternateTypeRules(AlternateTypeRules.newRule(
                        typeResolver.resolve(Map.class, String.class, URI.class),
                        typeResolver.resolve(Map.class, String.class, String.class)))
                .alternateTypeRules(AlternateTypeRules.newRule(
                        typeResolver.resolve(List.class, typeResolver.resolve(Map.class, WildcardType.class, URI.class)),
                        typeResolver.resolve(List.class, typeResolver.resolve(Map.class, WildcardType.class, String.class))
                ))`
But I'm not sure I caught all the cases as we are having a big project. Is there a more generic way to handle URI's at once?

**Comment by dilipkrish** [comment]
@metaruslan thanks for your solution.
