### ISSUE TITLE
 invalid scope , additional space in the scope param when redirect 

### ISSUE THREAD

**Issue by abdushkur** [springfox/springfox#2164]
I use 2.7 version for both jars 
i have three scope, i choose the second ,
 after redirect and debug spring security has parsed it to two scope [,write]
then spring called method clientScopes.contains(requestScopes)   it says invalid scope,
in the parameter map scope= read 
which has two space

**Comment by abdushkur** [comment]
if I choose the first scope it adds two space before redirect , hopefully it was stripped

**Comment by dilipkrish** [comment]
I don't understand the question. Is this a springfox related issue?

**Comment by abdushkur** [comment]
sorry , it was swagger-ui problem
