### ISSUE TITLE
Response Model Empty

### ISSUE THREAD

**Issue by codebyamir** [springfox/springfox#2167]
Version: 2.50

If I have an API controller method like below:

```
@RequestMapping(value = "/requestforquote/entry", method = RequestMethod.POST)
public @ResponseBody Map<String,String> addEntriesToList(@RequestBody MoveToList moveToList)
  Map<String,String> result = new HashMap<String,String>();
  result.put("data", "my data");
  result.put("message", "my message");
		
  return result;
}
```

My Swagger page shows an empty response model:
![capture](https://user-images.githubusercontent.com/5330669/34440871-2f48dbd2-ec86-11e7-892c-f96feac0e3b3.PNG)

I would expect to see something like this:
```
{
    "data": "my data",
    "message":"my message"
}  
```

**Comment by dilipkrish** [comment]
There is no way for springfox to know what runtime values you put into the Map. Also please upgrade to 2.7.0

**Comment by rplees** [comment]
@dilipkrish Hi, In this case, how to quote in the code Custom Model Schema or from custom json file definition like "$ref": "#/definitions/CashierLoginSuccView", Thanks

**Comment by dilipkrish** [comment]
Currently there is no way to do that. Would you mind creating a feature request for that @rplees

**Comment by rplees** [comment]
Hi, @dilipkrish I have already submitted feature in  #2181
