### ISSUE TITLE
springfox swagger-ui.html cannot find swagger-resources with right path.

### ISSUE THREAD

**Issue by gitforpushpak** [springfox/springfox#2168]
Hi @dilipkrish ,

I'm running in springfox v2.7.0 in my java spring based application. We have 3 dispatch serverlets configured in web.xml:

1)common springmvc servlet [Active]

```
<servlet>
		<servlet-name>springmvc</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<init-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>WEB-INF/config/common/springmvc-servlet.xml</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
</servlet>
```

2 ) springmvc-v1 servlet [inactive]: which is disabled by commenting out it in web.xml and not in use.

```
	<servlet>
		<servlet-name>springmvc-v1</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<init-param>
			<param-name>contextClass</param-name>
			<param-value>
				org.springframework.web.context.support.AnnotationConfigWebApplicationContext
			</param-value>
		</init-param>
		<init-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>
				com.test.mywebservices.v1.config.WebConfig
			</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>
```

3) springmvc-v2 servlet [Active]: for this I am implimenting swagger.

```
	<servlet>
		<servlet-name>springmvc-v2</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<init-param>
			<param-name>contextClass</param-name>
			<param-value>
				org.springframework.web.context.support.AnnotationConfigWebApplicationContext
			</param-value>
		</init-param>
		<init-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>
				com.test.mywebservices.v2.config.WebConfig
			</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>
	
	<servlet-mapping>
		<servlet-name>springmvc-v2</servlet-name>
		<url-pattern>/v2/*</url-pattern>
	</servlet-mapping>



```

And it works fine, and i can get to the swagger-resources from here:
https://localhost:9002/mywebservices/v2/swagger-resources

And i can view the api from here:
https://localhost:9002/mywebservices/v2/v2/api-docs

And Swagger-UI is accessible from here:
https://localhost:9002/mywebservices/swagger-ui.html

The problem is when i load the https://localhost:9002/mywebservices/swagger-ui.html page it is trying to access the swagger-resources from here:
https://localhost:9002/mywebservices/swagger-resources

And they are not available. But it is available at https://localhost:9002/mywebservices/v2/swagger-resources

How can i fix this so that the swagger-ui.html :
  I think Swagger-ui.html should be available at: https://localhost:9002/mywebservices/v2/swagger-ui.html so that springfox.js will get the right baseUrl.

```
https://localhost:9002/mywebservices/swagger-ui.html  >>> pages loads but gives popup to enter the Base URL

https://localhost:9002/mywebservices/swagger-resources/configuration/ui >>> gives 404 hence popup appears

https://localhost:9002/mywebservices/webjars/springfox-swagger-ui/springfox.js >>> Able to access.This is working fine.


```

Please suggest the solution.
Thanks in advance.

**Comment by dilipkrish** [comment]
Add a pathMapping in your docket `docket.pathMapping("/v2")`

**Comment by gitforpushpak** [comment]
I tried the below code, but it is not working.

`	
	@Bean
	public Docket apiDocumentation()
	{
		return new Docket(DocumentationType.SWAGGER_2).pathMapping("/v2").apiInfo(apiInfo()).select().paths(PathSelectors.any()).build();
	}
`

**Comment by gitforpushpak** [comment]
@dilipkrish am I doing anything wrong here ?

**Comment by dilipkrish** [comment]
Im sorry you're having so much trouble with this. Its possibly having to do with mixing legacy xml configuration with a modern spring application. 

Here is something to try. Try turning on logging for the spring packages especially `org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping`. You might not need to do anything, special. It should automatically spit it out at startup. If not you may need to tweak your log settings.

Once you have that, you should see something like this 👇 

```log
[Test worker] INFO org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped "{[/bugs/{propertyKey}/{environmentKey}],methods=[GET]}" onto public org.springframework.http.ResponseEntity<java.lang.String> springfox.documentation.spring.web.dummy.controllers.BugsController.getProperty(springfox.documentation.spring.web.dummy.controllers.BugsController$Key,springfox.documentation.spring.web.dummy.controllers.BugsController$Key)
[Test worker] INFO org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped "{[/bugs/1864],methods=[GET]}" onto public void springfox.documentation.spring.web.dummy.controllers.BugsController.test(springfox.documentation.spring.web.dummy.controllers.BugsController$Model1864)
[Test worker] INFO org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped "{[/bugs/1939],methods=[GET],produces=[application/jwt]}" onto public org.springframework.http.ResponseEntity<java.lang.String> springfox.documentation.spring.web.dummy.controllers.BugsController.authenticate(java.lang.String,java.lang.String,java.lang.String)
[Test worker] INFO org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped "{[/bugs/1841],methods=[GET],produces=[application/atom+xml]}" onto public void springfox.documentation.spring.web.dummy.controllers.BugsController.method1()
[Test worker] INFO org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped "{[/bugs/1841],methods=[GET],produces=[application/json;charset=UTF-8]}" onto public void springfox.documentation.spring.web.dummy.controllers.BugsController.method2()

```

See how it gives you shows you the path. You be able to locate where your controllers are hiding.
