### ISSUE TITLE
Springfox does not read individual item annotation in Collection

### ISSUE THREAD

**Issue by jehanzeb114** [springfox/springfox#2170]
I have a use case where I am using javax validation annotation for each item in Collection. As an example this is one of the field I have

_@ApiModelProperty(value = "This is a set of strings")
  class myModel {
    Set<@Size(max = 5) String> setOfStrings;_
}

Is there any way that swagger model can have this defined for each field. I want to make it look like this 

_"setOfStrings": {
          "type": "array",
          "description": "This is a set of strings",
          "items": {
            "type": "string",
            "minLength : 0,
            "maxLength : 5
          }
        }_

**Comment by dilipkrish** [comment]
I don't think that is possible off the top my head

**Comment by jehanzeb114** [comment]
Is there any way we can achieve this, e.g by creating custom plugin. I tried to write a plugin by implementing _ModelPropertyBuilderPlugin_ but it didn't help much

**Comment by dilipkrish** [comment]
Doesnt the size annotation plugin already work? You may need to create a wrapper for your items in the list. A little googling lead me [to this](https://stackoverflow.com/a/22233776/19219).

**Comment by jehanzeb114** [comment]
No. Size annotation plugin does not work here. It looks for annotation at field level but in our use case we are performing validation for each item. `SizeAnnotationPlugin` works as expected for 

```
@Size(max = 10)
Set<String> setOfStrings
```

but we are validating each item. i.e `Set<@Size(max = 10)> setOfStrings`. Wrapper class is one of the solution but we want to avoid a separate object. Is there any way if we can extend SizeAnnotationPlugin or write another plugin to read this annotation and then set the min/max values in allowableValues. This is a sample snippet what I am trying to do

```
class SizeAnnotationPlugin implements ModelPropertyBuilderPlugin {
...
...

@Override
public void apply(ModelPropertyContext context) {
        Optional<Size> sizeOptional = extractSizeAnnotation() // looking for its implementation
       if(sizeOptional.isPresent()) {
       AllowableValues allowableValues = new AllowableRangeValues(sizeOptional.get().min(), 
       sizeOptional.get().max())
       context.getBuilder.allowableValues(allowableValues)
       //this plugin should run last and should have the allowable min/max values in propertybuilder
       }
    }
}
```

**Comment by dilipkrish** [comment]
I think this should work, however instead of `Size` create your own custom annotation for e.g. `@ItemLength` that way you're not going to have @Size have two different meanings in different situations.

**Comment by jehanzeb114** [comment]
but with this one I am running into two issues

1- I am not able to find any way to  read **Type annotation** , i.e in `List<@Size(max=10)>String` there is no such meta data that can provide me this information

2- In ModelPropertyBuilder, if i explicitly set `allowablevalues`, it is overwritten and min/max values are ignored in the final model and property looks like this

```
fieldName: {
type: "array",
description: "The field description",
allowEmptyValue: false,
items: {
type: "string"
}
}
```

Model looks like this

public class myModel {
Set<@Size(max=10)> fieldName;
.....
//getters and setters
}
