### ISSUE TITLE
If able to build Swagger doc with springfox in the case of homemade rest dispatching logic. 

### ISSUE THREAD

**Issue by wxjlibra** [springfox/springfox#2171]
Our product is written with springMVC framework, however we just roughly use RequestMapping '/**' to accept all the requests and  do dispatching with our own framework instead of leveraging the spring mvc restful api build convention.
My question here is if in this case I could still be able to build such an swagger api doc leverage springfox. and if yes what part in Docket should I write customized implementation.
Really thanks in advance.

**Comment by dilipkrish** [comment]
In you're case you'd have to essentially build your specification by hand [like this](http://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin). In anycase, if all yr endpoints are that way, you might swell just have a hand written swagger specification and include it as a resource.
