### ISSUE TITLE
Why there are no externalized properties for Swagger?

### ISSUE THREAD

**Issue by tomaszglinski** [springfox/springfox#2172]
I have very same issue to use swagger both locally and behind reverse proxy like in https://github.com/springfox/springfox/issues/1443

The solution proposed there is basically to externalize configuration. I am wondering, why is it not implemented already like this with reasonable defaults? I mean at least the most basic, singleton properties...

**Comment by dilipkrish** [comment]
Because it is supposed to be handled by setting the right X-FORWARD headers. One shouldn’t have to configure anything.
