### ISSUE TITLE
Custom Model Schema from json file OR Code definition like @Schema(ref = "#/components/schemas/CashierLoginSuccView")

### ISSUE THREAD

**Issue by rplees** [springfox/springfox#2181]
Hi All,
I am having an application in Spring Boot having dependency
springfox-swagger2 - version 2.7.0

- [ ] Feature Request. 
`@RequestMapping(value = "/requestforquote/entry", method = RequestMethod.POST)
public @ResponseBody Map<String,String> addEntriesToList(@RequestBody MoveToList moveToList)
  Map<String,String> result = new HashMap<String,String>();
  result.put("data", "my data");
  result.put("message", "my message");
		
  return result;
}`

I want to return custom map content, how to quote in the code Custom Model Schema or from custom json file definition like "$ref": "#/definitions/CashierLoginSuccView", like swagger-core
`schema = @Schema(ref = "#/components/schemas/CashierLoginSuccView")

`

- [ ] Feature Request. 
How to [add param button] in swagger-ui ,can add custom with key-pairs, Thanks.

> 
Parameter | Value | Description | Parameter Type | Data Type
-- | -- | -- | -- | --
deviceId |   | device desc | header | string
account |   | desc | query | string
placeId |   | desc | query | long
password |   | desc | query | string

[add param btn] <--Here Function

- [ ] Feature Request. 
Can you add a tree menu on the left, Thanks.

**Comment by dilipkrish** [comment]
@rplees thanks for the feature request
