### ISSUE TITLE
Swagger-UI authorization headers stopped being sent in 2.8.0 

### ISSUE THREAD

**Issue by ctmay4** [springfox/springfox#2194]
I just updated from 2.7.0 to 2.8.0 and the authorization headers in Swagger-UI stopped working.

My config looks like this:

```java
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo())
                .securitySchemes(Collections.singletonList(new ApiKey(RestSecurityFilter.HTTP_REQUEST_API_KEY, RestSecurityFilter.HTTP_REQUEST_API_KEY, "header")))
                .useDefaultResponseMessages(false);
    }
```

Under 2.7, I enter the key:

![image](https://user-images.githubusercontent.com/444345/35054278-2e717838-fb7a-11e7-8b12-f8baa118e7db.png)

And this is an example of the URL sent (with key starred out).  Note that it adds the key as a `--header`.

```
curl -X GET --header 'Accept: application/json' --header 'X-SEERAPI-Key: *************' 'https://api.seer.cancer.gov/rest/mph/groups'
```

If I only switch to the 2.8.0 release, I add the key the same way

![image](https://user-images.githubusercontent.com/444345/35054389-6b161d98-fb7a-11e7-8a33-6834815c59e0.png)

But the call that swagger-ui makes does not include the header:

```
curl -X GET "https://seerapi-dev.imsweb.com/rest/mph/groups" -H "accept: application/json"
```

Is there additional configuration required for 2.8.0?  I didn't see anything in the release notes.

I also see an error at the bottom of the swagger ui page which says there is an error:

```json
{
"schemaValidationMessages": [
{
"level": "error",
"message": "Can't read from file https://seerapi-dev.imsweb.com/v2/api-docs"
}
]
}
```

However that URL loads fine and I entered it in the online swagger editor and there were no warnings.

Are there migration changes to get from Swagger 2.7.0 to Swagger 2.8.0

**Comment by eighthw** [comment]
I also have the same issue after upgrade from 2.7 to 2.8

**Comment by ptheohar** [comment]
Try adding securityContext() and Security bean in the SwaggerConfiguration. Check chapter 3 in the [documentation](https://springfox.github.io/springfox/docs/snapshot/#swagger-1-2-vs-swagger-2-0)

**Comment by goodlifeinc** [comment]
@ptheohar could you checkmy securityContext() and Security Bean, bcs I have them in SwaggerConfiguration but still Authorization headers are not being sent with v2.8 while with v2.7 it was ok with same config:

```java
@Bean
SecurityConfiguration security() {
	return new SecurityConfiguration(null, null, null,
			null,
			null,
			ApiKeyVehicle.HEADER, AUTHORIZATION,
			null);
}

private SecurityContext securityContext() {
	return SecurityContext.builder()
			.securityReferences(defaultAuth())
			.forPaths(PathSelectors.regex(apiPath + "/*"))
			.build();
}
```

**Comment by ctmay4** [comment]
I'll try to reconfigure it, but `securitySchemes` was all that was needed in 2.7 and it worked perfectly:

```java
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo())
                .securitySchemes(Collections.singletonList(new ApiKey(RestSecurityFilter.HTTP_REQUEST_API_KEY, RestSecurityFilter.HTTP_REQUEST_API_KEY, "header")))
                .useDefaultResponseMessages(false);
    }
```

**Comment by ptheohar** [comment]
Here is my configuration:

1) Docket
`.securitySchemes(Arrays.asList(apiKey())).securityContexts(Arrays.asList(securityContext()))`

**Comment by ptheohar** [comment]
Here is my configuration

1) Docket
`.securitySchemes(Arrays.asList(apiKey()))
.securityContexts(Arrays.asList(securityContext()))`

**Comment by dilipkrish** [comment]
I'll take a look, sorry for the inconvenience folks. @kasecato any ideas? seems like a UI regression.

**Comment by kasecato** [comment]
@dilipkrish I have no idea. It seems that api_key is added to curl for locked API.
<img width="955" alt="2194" src="https://user-images.githubusercontent.com/10364603/35550843-904f802c-05cf-11e8-8e27-da340b73dec2.png">

**Comment by ctmay4** [comment]
@ptheohar I copied your configs from above, only changing the path to my endpoint and the name of my API key.  I still do not get the API key added to the curl command.  

```java
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo())
                .securitySchemes(Collections.singletonList(apiKey()))
                .securityContexts(Collections.singletonList(securityContext()))
                .useDefaultResponseMessages(false);
    }

    private ApiKey apiKey() {
        return new ApiKey("apiKey", RestSecurityFilter.HTTP_REQUEST_API_KEY, "header");
    }

    private List<SecurityReference> defaultAuth() {
        AuthorizationScope authorizationScope = new AuthorizationScope("global", "accessEverything");
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0] = authorizationScope;
        return Collections.singletonList(new SecurityReference("apiKey", authorizationScopes));
    }

    private SecurityContext securityContext() {
        return SecurityContext.builder()
                .securityReferences(defaultAuth())
                .forPaths(PathSelectors.regex("/rest/*"))
                .build();
    }

    @Bean
    public SecurityConfiguration security() {
        return SecurityConfigurationBuilder.builder()
                .clientId("api-client-id")
                .clientSecret("api-client-secret")
                .realm("api-realm")
                .appName("api-app")
                .scopeSeparator(",")
                .additionalQueryStringParams(null)
                .useBasicAuthenticationWithAccessCodeGrant(false)
                .build();
    }
```

The auth popup works:

![image](https://user-images.githubusercontent.com/444345/35571861-4278beaa-05a1-11e8-962c-81983aae01b4.png)

But the curl still doesn't include the header.  Note that unlike the screenshot above, I don't see the lock icon on the same line as the API. 

![image](https://user-images.githubusercontent.com/444345/35571904-5c11f28c-05a1-11e8-972a-1b3885e84d4d.png)

It's very strange because the security auth and security context were not needed in 2.7 and all worked perfectly.  Wonder what changed in 2.8?

**Comment by dilipkrish** [comment]
@ctmay4 Thanks for the configuration. I'll try to see if I can reproduce

**Comment by MaximAntonovich** [comment]
I have the same issue. Thanks

**Comment by neolsun** [comment]
I have the same issue too. Thanks.

**Comment by JotaroJewstar** [comment]
Hello Guys, i finally found a very very stupid solution to my problem.
See here to: https://github.com/springfox/springfox/issues/2137

It works with **2.8 Springfox**
My gear: Spring Boot + H2 db, oauth2 and Swagger 2.8

Here are all my Settings i hope someone make is a better solution of it.

`		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-bean-validators</artifactId>
			<version>2.8.0</version>
		</dependency>`

You dont need those but i think its better if you want to change is someday, so you only need to change the **application.properties.**

```
    @Value("${security.oauth2.client.clientId}")
    private String clientId;

    @Value("${security.oauth2.client.clientSecret}")
    private String clientSecret;

```
```
  @Bean
    public Docket api() {

        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                    .apis(RequestHandlerSelectors.basePackage("com.bla.de.blub"))
                    .paths(PathSelectors.regex("/api.*"))
                    .build()
                .pathMapping("/")
                .securitySchemes(Arrays.asList(apiKey()))
                .securityContexts(Arrays.asList(securityContext()))
                .apiInfo(apiInfo());
    }
```

Thats the important part. If you use oauth2, your keyname has do be "**Authorization**" only!
```
    private ApiKey apiKey() {
        return new ApiKey("apiKey", "Authorization", "header");
    }
```

```
    private SecurityContext securityContext() {
        return SecurityContext.builder()
                .securityReferences(defaultAuth())
                .forPaths(PathSelectors.regex("/api.*"))
                .build();
    }
```

```
    private List<SecurityReference> defaultAuth() {
        AuthorizationScope authorizationScope = new AuthorizationScope("global", "accessEverything");
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0] = authorizationScope;
        return Arrays.asList(new SecurityReference("apiKey", authorizationScopes));
    }
```

```
    @Bean
    public SecurityConfiguration security() {
        return SecurityConfigurationBuilder.builder()
                .clientId(clientId)
                .clientSecret(clientSecret)
                .realm("realm")
                .appName("test-app")
                .scopeSeparator(",")
                .additionalQueryStringParams(null)
                .useBasicAuthenticationWithAccessCodeGrant(false)
                .build();
    }

```

**application.properties**
```
security.oauth2.client.clientId=cliendid
security.oauth2.client.clientSecret=secret
```

So after you set everthing up, no comes the my stupid solution ^^
After you create a token it should look like this:

```
{"access_token":"d5660fa9-6d96-4c5b-af3b-feb6e312956c",
"token_type":"bearer","refresh_token":"acc17965-177b-4c15-afd8-f501e9f6164b",
"expires_in":3599,"scope":"read write trust"}
```

The tokentype is "bearer".
Enter this in your Swagger UI (notice that the "b" in bearer should be uppercase)
<a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/34811460/2018-02-0911_11_06-SwaggerUI.png" title="Bilder oder Fotos hochladen"></a>

I notice that if you type Authorization: Bearer in the keyname of apiKey you get another ":" (colon).
Thats why i get an error, saying my token is invalid. But in fact my curl is wrong.

I hope anybody finde a better solution,

**Comment by dilipkrish** [comment]
Thanks @JotaroJewstar

**Comment by MaximAntonovich** [comment]
I resolved issue with missed authorization header by setting `authorizations` parameter in `@ApiOperation` annotation for all methods in my controller. @kasecato message helped me to check authorization settings.

**Comment by dilipkrish** [comment]
@MaximAntonovich The security context in the configuration is supposed to help with that. If thats not working there seems to be a bug

**Comment by MartinX3** [comment]
Getting a 401 from swagger-resources/configuration/ui because the backend is behind a reverse proxy. which wants a bearer token in the auth header.

**Comment by Damore** [comment]
I've solved the problem only adding the annotation at my controller method:

@ApiOperation(value="Enviar um log para o servidor", authorizations=@Authorization(value="oauth2", scopes=@AuthorizationScope(description="write", scope="write")))

the "oauth2" value refers to the SwaggerConfig method I've declared:

    @Bean
    public SecurityScheme oauth() {
        return new OAuthBuilder()
                .name("oauth2")
                .grantTypes(grantTypes())
                .build();
    }

    private List<GrantType> grantTypes() {
        GrantType grantType = new ClientCredentialsGrant(authLink);
        List<GrantType> grantTypes =  new ArrayList<GrantType>();
        grantTypes.add(grantType);
        return grantTypes;
    }

    @Bean
    public SecurityConfiguration securityInfo() {
        return new SecurityConfiguration("", "", "", "", "", ApiKeyVehicle.HEADER, "", " ");
    } 

I know the SecurityConfiguration is deprecated, I've changed it yet. However, worked for me...

**Comment by MartinX3** [comment]
But still, we can't send an Bearer Token for Basic Username:Password Auth, right?

**Comment by dilipkrish** [comment]
That is correct. swagger-ui doesnt support basic authentication

**Comment by balasenthil-d** [comment]
Still facing the same issue. Is there any workaround for this ? The swagger-ui with 2.7.0 looks quite primitive compared to 2.8.0

**Comment by MartinX3** [comment]
The UI looks better, but the "try" button is disturbing me.
Now I need a second step to execute the statement....

Am 16. März 2018 09:55:50 MEZ schrieb balasenthil-d <notifications@github.com>:
>Still facing the same issue. Is there any workaround for this ? The
>swagger-ui with 2.7.0 looks quite primitive compared to 2.8.0
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/springfox/springfox/issues/2194#issuecomment-373645739

-- 
Mit freundlichen Grüßen

Martin Dünkelmann

**Comment by dilipkrish** [comment]
@MartinX3 unfortunately that is not maintained by this project. It is the [Swagger-ui](https://github.com/swagger-api/swagger-ui) project.

@balasenthil-d could you try with `2.8.1-SNAPSHOT` I think its fixed.

**Comment by balasenthil-d** [comment]
@dilipkrish I tried 2.8.1-SNAPSHOT and I am not even able to load http://localhost:8080/swagger_ui.html. I used the same configuration as I had for 2.7.0.

**Comment by dilipkrish** [comment]
@balasenthil-d that doesn't help me figure out what your configuration is in the first place. Ideally if you can share a repository I can see what is happening.

**Comment by balasenthil-d** [comment]
The solution mentioned by @ptheohar works. In addition you need to add authorizations to the needed APIs as in 
`@ApiOperation(value = "", authorizations = {
            @Authorization(value="apiKey", scopes = {
                    @AuthorizationScope(scope = "global", description = "accessEverything")
            })
    })`

This will ensure the API needs to be authorized (as can be seen with lock icon) and would start sending out Authorization token.

The client_id, client_secret and realm can be null if you are adding the token manually.

This works in 2.8.0 itself and I believe this ticket can be closed.

**Comment by razorblade446** [comment]
Hi, Silly  question, but I cant find "SecurityConfigurationBuilder"...

**Comment by razorblade446** [comment]
Uh, Gradle was caching 2.7...

**Comment by ctmay4** [comment]
Just wanted to follow up that I have this working now.  As @balasenthil-d mentioned I used the template supplied by @ptheohar and also needed to add the following to every one of my endpoints.

```
@ApiOperation(value = "", authorizations = { @Authorization(value="apiKey") })
```

This was not required in the prior version and would have definitely been nice to have been able to set it as a default programmatically.  

Thanks to everyone for their help getting this resolved.

**Comment by kranthi610** [comment]
here is what I did after reading the open API doc and it works


* @OAS\SecurityScheme(
 *   securityScheme="bearerAuth",
 *   type="http",
 scheme="bearer",
      bearerFormat="JWT"
 *  
 * )

/////////////////////////////////////////

security={
*           {"bearerAuth": {}}
*         }

**Comment by dilipkrish** [comment]
@kranthi610 what language is that in?

**Comment by kranthi610** [comment]
@dilipkrish Those are swagger annotations and I used them in php language

**Comment by selvaebi** [comment]
Hi All , is there a way to include for all methods by default instead of providing @ApiOperation to all the methods. And also am using restrepository resources so can need to include it by default.

**Comment by dilipkrish** [comment]
You can provide a security context and security reference in the docket to the methods you want to protect @selvaebi

**Comment by sg-garg** [comment]
Below configuration works for me. I found to make Authorization header to pass in curl please make sure APIkey have name and keyname have same value like.
```
private ApiKey apiKey() {
    return new ApiKey("Authorization", "Authorization", "header");
}
```
Refer below code 
public class SwaggerConfig extends WebMvcConfigurationSupport {

  @Bean
  public Docket productApi() {
    return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo())
        .select().apis(RequestHandlerSelectors.basePackage("com.roche.platform.auth.controller"))
        .paths(PathSelectors.any()).build()
        .useDefaultResponseMessages(false)
        .securitySchemes(Collections.singletonList(apiKey()))
        .securityContexts(Collections.singletonList(securityContext()));

  }

  @Override
  protected void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("swagger-ui.html")
        .addResourceLocations("classpath:/META-INF/resources/");

    registry.addResourceHandler("/webjars/**")
        .addResourceLocations("classpath:/META-INF/resources/webjars/");
  }

  private ApiInfo apiInfo() {
    return new ApiInfoBuilder().title("Auth Microservice")
        .description("Interface between services and UI")
        .termsOfServiceUrl("Terms of Service")
        .contact(new Contact("Test", "", "test@test.com"))
        .license("License").licenseUrl("License Url").version("1.0").build();
  }

  private ApiKey apiKey() {
    return new ApiKey("Authorization", "Authorization", "header");
  }

  private SecurityContext securityContext() {
    return SecurityContext.builder()
        .securityReferences(defaultAuth())
        .forPaths(PathSelectors.any())
        .build();
  }
  // Below method is to override Authorization header value 
  private List<SecurityReference> defaultAuth() {
    AuthorizationScope authorizationScope = new AuthorizationScope("global", "accessEverything");
    AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
    authorizationScopes[0] = authorizationScope;
    return Arrays.asList(new SecurityReference("Authorization", authorizationScopes));
  }

}

**Comment by dilipkrish** [comment]
Thanks for sharing @sg-garg

**Comment by alisonatwork** [comment]
A lot of the examples posted here and in the Springfox documentation felt too complicated for our use case, which is just to send a JSON Web Token and that's it. We don't have OAuth or cookies or anything. Here is a minimal config I found that works for us:

```java
@Bean
public Docket jsonApi() {
    return new Docket(SWAGGER_2)
        .securitySchemes(singletonList(new ApiKey("JWT", AUTHORIZATION, HEADER.name())))
        .securityContexts(singletonList(
            SecurityContext.builder()
                .securityReferences(
                    singletonList(SecurityReference.builder()
                        .reference("JWT")
                        .scopes(new AuthorizationScope[0])
                        .build()
                    )
                )
                .build())
        )
        .select()
        .apis(RequestHandlerSelectors.basePackage(/* package here */))
        .build();
}
```

This will apply the header to every endpoint - you do not need to add any `authorizations` arguments. You also do not have to set up a security bean or a fake scope or anything, because that is only important for OAuth. See Swagger docs here: https://swagger.io/docs/specification/2-0/authentication/api-keys/

The user flow, then, is:
1. Open Swagger UI
2. Call the login endpoint
3. Copy the token from the response
4. Click the Authorize button
5. Type "Bearer " into the Authorization text box and then paste the token to complete the header
6. Now all subsequent requests will be authenticated

@kranthi610 has a good answer that got me on the right track, but I think it will only work in Open API 3.0. See https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by camdav** [comment]
Thanks for the example. Can you provide a list of imports?

**Comment by alisonatwork** [comment]
Hi @camdav sure, this should be all you need to create the bean.

```java
import org.springframework.context.annotation.Bean;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiKey;
import springfox.documentation.service.AuthorizationScope;
import springfox.documentation.service.SecurityReference;
import springfox.documentation.spi.service.contexts.SecurityContext;
import springfox.documentation.spring.web.plugins.Docket;

import static io.swagger.models.auth.In.HEADER;
import static java.util.Collections.singletonList;
import static org.springframework.http.HttpHeaders.AUTHORIZATION;
import static springfox.documentation.spi.DocumentationType.SWAGGER_2;
```

**Comment by artificerpi** [comment]
Is it possible to set authorization header per class? 
Just like this
```java
@Api(value = "api/owners", authorizations = { @Authorization(SwaggerConfig.BEARER_API_KEY) })
...
public class OwnerController {
...
```
Why `authorizations` not work by using above solutions?

**Comment by VishalNehra** [comment]
Connecting to swagger-ui now calls project root `/` and `/csrf` after adding above examples. 
I'm not sure why csrf is being called as I have disabled in in my `WebSecurityConfigurerAdapter#configure`

**Comment by Ramjeet89** [comment]
Any body has complete code then please send me ramjeet.mahto77@gmail.com

**Comment by hugo53** [comment]
> Is it possible to set authorization header per class?
> Just like this
> 
> ```java
> @Api(value = "api/owners", authorizations = { @Authorization(SwaggerConfig.BEARER_API_KEY) })
> ...
> public class OwnerController {
> ...
> ```
> 
> Why `authorizations` not work by using above solutions?

Did you find solution for this problem? I tried some but still no luck here.

**Comment by sen4ik** [comment]
@alisonatwork Thanks for your solution [here](https://github.com/springfox/springfox/issues/2194#issuecomment-463448861). Is there a way to apply the header to specific endpoints only?

**Comment by alisonatwork** [comment]
Hi @sen4ik I am not working on a service using Springfox any more so i cannot help directly with this, but I think one place you could start looking is the `SecurityContextBuilder`. In there it allows some filtering of only applying to some paths, which might solve your problem.

**Comment by sen4ik** [comment]
@alisonatwork Thanks for reply. I was able to figure it out. In case someone will need to restrict authentication to specific endpoints, here is my code.

`
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .securitySchemes(
                        singletonList(
                                new ApiKey("JWT", AUTHORIZATION, HEADER.name())
                        )
                )
                .securityContexts(
                        securityContext()
                )
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.sen4ik.oacapi.controllers"))
                .paths(PathSelectors.any())
                .build();
    }

    private List<SecurityReference> securityReference = singletonList(SecurityReference.builder()
            .reference("JWT")
            .scopes(new AuthorizationScope[0])
            .build()
    );

    private List<HttpMethod> methods = Arrays.asList(
            HttpMethod.POST,
            HttpMethod.PUT,
            HttpMethod.DELETE
    );

    private List<SecurityContext> securityContext() {
        List<SecurityContext> lsc = new ArrayList<>();

        lsc.add(SecurityContext.builder()
                .securityReferences(securityReference)
                .forPaths(PathSelectors.ant(Constants.API_PREFIX + "/category/**"))
                .forHttpMethods(Predicates.in(methods))
                .build()
        );

        lsc.add(SecurityContext.builder()
                .securityReferences(securityReference)
                .forPaths(PathSelectors.ant(Constants.API_PREFIX + "/tag/**"))
                .forHttpMethods(Predicates.in(methods))
                .build()
        );

        lsc.add(SecurityContext.builder()
                .securityReferences(securityReference)
                .forPaths(PathSelectors.ant(Constants.API_PREFIX + "/file/**"))
                .forHttpMethods(Predicates.in(methods))
                .build()
        );

        lsc.add(SecurityContext.builder()
                .securityReferences(securityReference)
                .forPaths(PathSelectors.ant(Constants.API_PREFIX + "/user/**"))
                .build()
        );

        return lsc;
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        if (enableSwagger) {
            registry.addResourceHandler("swagger-ui.html")
                    .addResourceLocations("classpath:/META-INF/resources/");
            registry.addResourceHandler("/webjars/**")
                    .addResourceLocations("classpath:/META-INF/resources/webjars/");
        }
    }`
