### ISSUE TITLE
 swagger2.8 Use the false report

### ISSUE THREAD

**Issue by eighthw** [springfox/springfox#2196]
![lalpbbcc1vxdr8_na73nbzo_1850_957](https://user-images.githubusercontent.com/6425929/35085691-c34ac370-fc64-11e7-9dc3-05e5a2129f9b.png)
Upgrade to 2.8 error, unable to jump back to the original page after authentication。
Hope everyone helps

**Comment by dilipkrish** [comment]
@eighthw could you translate the words in the screenshot please?

**Comment by dilipkrish** [comment]
:call_me_hand: ?
