### ISSUE TITLE
String array query parameter is not rendered at Swagger UI when default value is present

### ISSUE THREAD

**Issue by Halynsky** [springfox/springfox#2200]
- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Bug report.
    - [x] include any output you've received; logs, json snippets etc.; and what the expected output should be

![image](https://user-images.githubusercontent.com/8502557/35195710-3ce7dd4a-fed0-11e7-932a-c4576dfd395f.png)

Regular (String array - String[]) query parameter can't be rendered at Swagger UI.
Everything worked fine before update to 2.8.0. Last used version was 2.7.1-SNAPSHOT.
I think it is bug of the current Swagger version that is used in current version of SpringFox.

**One more note!**
Bug is disappeared when I removed default value from annotation
@RequestParam(defaultValue = "20001")

**Comment by timorohwedder** [comment]
+1 :-)

**Comment by dilipkrish** [comment]
The above examples work perfectly fine @Halynsky. Could you verify again please

**Comment by irlyanov** [comment]
I'm not sure it's the same issue @Halynsky met, but the following doesn't work for me (I've modified the sample you've provided):
```java
  @RequestMapping(value = "/categories", method = RequestMethod.POST)
  public ResponseEntity<List<Category>> map(@RequestParam @ApiParam(defaultValue="category1") List<String> categories) {
    return ResponseEntity.ok(null);
  }
```

**Comment by dilipkrish** [comment]
Seems like a bug in [Swagger-ui](https://github.com/swagger-api/swagger-ui), the moment default value comes into play it chokes

**Comment by jearton** [comment]
+1 :-)

```java
@ApiParam(defaultValue = "test") String[] categories
```

**Comment by dilipkrish** [comment]
Pasting the following contract in http://editor.swagger.io demonstrates the problem in swagger-ui

<details>
	<summary>Contract</summary>

```json
swagger: '2.0'
info:
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
  version: '2.0'
  title: Springfox petstore API
  termsOfService: 'http://springfox.io'
  contact:
    name: springfox
  license:
    name: Apache License Version 2.0
    url: 'https://github.com/springfox/springfox/blob/master/LICENSE'
host: 'localhost:8080'
basePath: /springfox
tags:
  - name: category-controller
    description: Category Controller
paths:
  '/categories':
    post:
      tags:
        - category-controller
      summary: map
      operationId: mapUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: categories
          in: query
          description: category
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
#          default: test
#          allowEmptyValue: false
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
              enum:
                - ONE
                - TWO
                - THREE
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
```
</details>

**Comment by imdreamrunner** [comment]
Any update on this issue? Will springfox upgrade the Swagger UI version?

**Comment by countrogue** [comment]
This should already be fixed in the latest version of swagger-ui, as i cant seem to replicate the issue anymore on http://editor.swagger.io/. What is the timeline to support the newer versions of swagger-ui?

**Comment by shintasmith** [comment]
FYI, we were facing this same issue. Our app was using Springfox 2.9.2 when we saw this issue. I upgraded to version 3.0.0 and that seemed to have fixed the issue.

**Comment by thejavator** [comment]
To make this happen, put the request params inside an object as below : 

 ```
   @GetMapping(value = "/filter")
    public ResponseEntity filterValues(RequestFilter requestFilter) {
```

```
public class RequestFilter {
    private List<String> filters;
    private List<Long> ids;
}

```


The rendered swagger operation is : 

![image](https://user-images.githubusercontent.com/6198887/210096886-e100bee1-0549-4d92-898b-471b9d7271d6.png)
