### ISSUE TITLE
Disabling validation of schema trough validatorUrl(null) not works for 2.8.0

### ISSUE THREAD

**Issue by Hronom** [springfox/springfox#2201]
Disabling trough validatorUrl(null) not works for 2.8.0

My pom.xml:
```
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>2.8.0</version>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>2.8.0</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>1.5.14</version>
            </dependency>
```
```
@Configuration
@EnableSwagger2
public class SwaggerConfig {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
            .pathMapping("/")
            .select()
            .apis(RequestHandlerSelectors.basePackage("com.github.hronom"))
            .paths(PathSelectors.any())
            .build()
            .apiInfo(apiInfo());
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
            .title("Test API")
            .build();
    }

    @Bean
    UiConfiguration uiConfig() {
        return UiConfigurationBuilder.builder()
            .displayRequestDuration(true)
            .validatorUrl(null)
            .build();
    }
}
```

**Comment by Hronom** [comment]
Found temporary workaround: empty string as value for `validatorUrl`, so my work ui config bean looks like:
```
    @Bean
    UiConfiguration uiConfig() {
        return UiConfigurationBuilder.builder()
            .displayRequestDuration(true)
            .validatorUrl("")
            .build();
    }
```

For devs of SpringFox I found workaround here https://github.com/swagger-api/swagger-ui/issues/3851 maybe this helps you to solve the problem.

**Comment by dilipkrish** [comment]
Thanks for researching the fix @Hronom

**Comment by ASaunin** [comment]
I'm confirming an issue.
Empty string as a parameter in `validatorUrl` method can fix this issue, but javadoc insists that `null` value has to disable validation. It might misleading.

**Comment by Hronom** [comment]
SpringFox devs, what the status of this?
According to [this release](https://github.com/swagger-api/swagger-ui/releases/tag/v3.4.3) you need upgrade to [Swagger-UI 3.4.3](https://github.com/swagger-api/swagger-ui/releases/tag/v3.4.3) or higher, to fix this issue?

Please check I'm not familiar with how springfox communicate with swagger ui.

**Comment by dilipkrish** [comment]
@Hronom will incorporate this thanks!

**Comment by kumarz** [comment]
@Hronom,  This is exactly , what I was looking for. I got rid of the validator service error in my swagger-ui.
