### ISSUE TITLE
Nested maps are not being converted properly to Swagger models

### ISSUE THREAD

**Issue by francocm** [springfox/springfox#2203]
- Springfox Version: 2.8.0
- Issue type: `Bug`.
- Description: Nesting a number of maps in each other as a response are not generating all the necessary models in the chain.

A sample API response of the implemented application (JSON) is:
```json
{
  "uuid": "8c2a44fc-a28e-4ef7-a0aa-f5f7618c69fb",
  "data": {
    "someapp": {
      "en": {
        "HELLO": {
          "TEXT": "Hello, World"
        }
      }
    }
  },
  "errors": null
}
```

That JSON is represented in Java as follows: `OuterWrapper<Map<String, Map<String, Map<String, LanguageText>>>>`.

In order to simplify the nesting above, I created a number of empty POJOs that extend `HashMap<String, OtherPojo>` and implement `Map<String, OtherPojo>` so as to hide the complexity of all such nesting.

The resultant Swagger is omitting the second level map when it comes to the models (not API). This ends up with the API referencing a non-existent model.

You can find an example project replicating this issue here: https://github.com/francocm/springfox-nested-issue

In my example project, http://localhost:8080/swagger-ui.html will give you the following error:
`Could not resolve reference because of: Could not resolve pointer: /definitions/Language does not exist in document`.

Generated Swagger JSON:
```json
{
  "swagger": "2.0",
  "info": {
    "description": "Hello World!",
    "version": "1.0",
    "title": "Springfox Nested Issue"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "tags": [
    {
      "name": "api-controller",
      "description": "Api Controller"
    }
  ],
  "paths": {
    "/api/{applicationName}": {
      "get": {
        "tags": [
          "api-controller"
        ],
        "summary": "getLanguageServicesByApplicationName",
        "operationId": "getLanguageServicesByApplicationNameUsingGET",
        "produces": [
          "application/json;charset=UTF-8"
        ],
        "parameters": [
          {
            "name": "applicationName",
            "in": "path",
            "description": "applicationName",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Response«LanguageResponse»"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApplicationLang": {
      "type": "object",
      "title": "ApplicationLang",
      "additionalProperties": {
        "$ref": "#/definitions/Language"
      }
    },
    "LanguageResponse": {
      "type": "object",
      "title": "LanguageResponse",
      "additionalProperties": {
        "$ref": "#/definitions/ApplicationLang"
      }
    },
    "LanguageText": {
      "type": "object",
      "properties": {
        "TEXT": {
          "type": "string"
        }
      },
      "title": "LanguageText"
    },
    "Response«LanguageResponse»": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "additionalProperties": {
                "$ref": "#/definitions/LanguageText"
              }
            }
          }
        },
        "errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "uuid": {
          "type": "string"
        }
      },
      "title": "Response«LanguageResponse»"
    }
  }
}
```

As you can see, the `definitions` in the JSON above, is missing the `Language` model even though referenced by `ApplicationLang`. Anything else, before and after that model is there.

**Comment by dilipkrish** [comment]
Thanks for the detailed report @francocm. 💸 for the example repo

**Comment by MaksimOrlov** [comment]
@dilipkrish, may be should I fix this as a part of Model Enhancement?

**Comment by dilipkrish** [comment]
👍 Im in the middle of merging your PR @MaksimOrlov (getting tests failing after merging master). Once that PR lands we should verify this bug.

**Comment by francocm** [comment]
Happy to see these comments :) let me know if I can help in one way or another.

**Comment by dilipkrish** [comment]
@francocm This is working as designed. The generated API docs is as you'd expect. Its a problem with swagger-ui that is not able to handle nested maps.

**Comment by francocm** [comment]
Hi @dilipkrish I'm not entirely sure it's a UI issue.

Reason being that when you look into the error:
`Could not resolve pointer: /definitions/Language`
and then check the items under the `definitions` JSON Node, there really is a missing `Language` node yet it's being referenced by `ApplicationLang`.

I don't think that should be missing?

**Comment by dilipkrish** [comment]
@francocm you are correct. I'll see whats the bug is

**Comment by pc-tvaishnav** [comment]
@dilipkrish is there a snapshot version with this fix?

**Comment by dilipkrish** [comment]
Yes there is
