### ISSUE TITLE
404 when upgrading from 2.6.1 to 2.8.0

### ISSUE THREAD

**Issue by rkaltreider** [springfox/springfox#2205]
I just tried to upgrade from 2.6.1 -> 2.8.0.  All i had to change was adding the VendorExtension parameter to ApiInfo and Parameter constructors.  When i try to call /api-docs, i get a 404.  The mapping is present, but i just get a 404.  Reverting for now, but any insight would be much appreciated!

**Comment by dilipkrish** [comment]
@rkaltreider it should be `/v2/api-docs` are you not using swagger2?

**Comment by rkaltreider** [comment]
I have this set

springfox.documentation.swagger.v2.path=/api-docs

I don’t want /v2 in my uri as it already contains a /v3 lol.

404 is what I get.  Thanks!

**Comment by ersinciftci** [comment]
I have the same problem, I have `springfox.documentation.swagger.v2.path:/api-docs` in properties and it was working before upgrading to `2.8.0`, now `/api-docs` gets 404, `/v2/api-docs` is working.

**Comment by dilipkrish** [comment]
Just checking but have you included the property source? @rkaltreider @ersinciftci

**Comment by ersinciftci** [comment]
@dilipkrish I have this:
```
<bean id="propertyPlaceholderConfigurer" class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
    <property name="systemPropertiesModeName" value="SYSTEM_PROPERTIES_MODE_OVERRIDE" />
    <property name="searchSystemEnvironment" value="true" />
    <property name="ignoreResourceNotFound" value="true" />
    <property name="ignoreUnresolvablePlaceholders" value="true" />
    <property name="locations">
        <list>
            <value>classpath:springfox.properties</value>
        </list>
    </property>
</bean>
```
It was working before upgrading to 2.8.0.

**Comment by ersinciftci** [comment]
@dilipkrish I changed it to this:
```
@Configuration
@EnableSwagger2
@PropertySource("classpath:springfox.properties")
public class SwaggerConfig {
```
And it's working now, so it seems the other way is not supported anymore. Thanks!

**Comment by rkaltreider** [comment]
I have this in my JavaConfig

@ImportResource({
    "classpath*:/META-INF/spring/dispatcher-servlet-*.xml", "/WEB-INF/spring/dispatcher-servlet.xml"
})

This in my dispatcher servlet xml


      
      
      <beans profile="default,local,development,quality,production,test,cache,monitor,monitorCache">
            
            
            
            <context:property-placeholder order="2"
                                                      location="classpath:${env:local}/api.properties"
                                                      ignore-unresolvable="true" />
      </beans>

And this in the api.properties file for every environment

# swagger config
swagger.base.proxy.path=
swagger.host.proxy.path=
springfox.documentation.swagger.v2.path=/api-docs
swagger.scheme=http

Still 404.  Properties files are being loaded

**Comment by rkaltreider** [comment]
Ok so I created a separate properties file called springfox.properties and loaded it with

@PropertySource("classpath:springfox.properties")

In my dispatcher config class with the line

springfox.documentation.swagger.v2.path=/api-docs

and I was able to retrieve the api doc.

Thanks!

**Comment by dilipkrish** [comment]
Might have to do with timing of when the property source is loaded. I'll make a note to describe this as something that can be documented. Thank you for clarifying @rkaltreider & @ersinciftci
