### ISSUE TITLE
CORS does not work on versions > 2.7.0

### ISSUE THREAD

**Issue by mKeRix** [springfox/springfox#2215]
**Version**: 2.7.0 - 2.8.0

**Bug**:

Starting with version 2.7.0 the CORS parameters are not applied anymore. This seems to be related to #1830. It works on all other paths, just not the Springfox api-docs one.

My web config includes:
```java
@Override
public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**")
        .allowedOrigins("https://docs.intern.example.net");
}
```

On Postman I request `http://localhost:8080/v2/api-docs?group=group-name` using the following headers to test:

```
Origin: https://docs.intern.example.net
Host: service.intern.example.net
```

It works fine on 2.6.1, any version after that is missing the `Access-Control-Allow-Origin` header.

**Comment by geojs** [comment]
Have the same problem, with Spring boot, to fix it:
```java
@Configuration
@EnableWebMvc
public class WebConfig extends WebMvcConfigurerAdapter {

    //https://stackoverflow.com/questions/31724994/spring-data-rest-and-cors
    @Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        
        CorsConfiguration config = new CorsConfiguration().applyPermitDefaultValues();
        config.setAllowCredentials(false);
        source.registerCorsConfiguration("/**", config);
        
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(0);
        
        return bean;
    }
}
```

**Comment by dilipkrish** [comment]
Thanks @geojs for researching that. 

Hints on how to fix -> https://github.com/spring-projects/spring-data-rest/pull/233/files

**Comment by gionn** [comment]
Hi, I was the original reporter of #1830 

I've just discovered that a missing ```@Import (SwaggerConfiguration.class)``` on top of my custom ```WebMvcConfigurerAdapter``` lead to the missing CORS headers issue, but swagger endpoint was working thanks to my `SwaggerConfig` class:

```
@Configuration
@EnableSwagger2
public class SwaggerConfig
{
    @Bean
    public Docket catalog()
    {
        return new Docket( DocumentationType.SWAGGER_2 )
                .groupName( "catalog" )
                .select().paths( catalogPaths() ).build()
                .apiInfo( apiInfo() );
    }
}
```

Maybe the problem is related to how spring bring up components at the startup, and cors mappings wasn't applied to swagger because get loaded later?

**Comment by gionn** [comment]
Hi, I am the reporter of #1830, today I retried upgrading from 2.6.1 to 2.8.0 but CORS headers is still missing (Spring 4.3.9)

I've taken a peek inside the internals of spring CorsFilter:

```
	protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
			FilterChain filterChain) throws ServletException, IOException {

		if (CorsUtils.isCorsRequest(request)) {
			CorsConfiguration corsConfiguration = this.configSource.getCorsConfiguration(request);
			if (corsConfiguration != null) {
				boolean isValid = this.processor.processRequest(corsConfiguration, request, response);
				if (!isValid || CorsUtils.isPreFlightRequest(request)) {
					return;
				}
			}
		}
```

getCorsConfiguration return an instance that hasn't any cors mapping configured while requesting a springfox endpoint.
For all the other requests, CorsConfiguration is set accordingly to my corsMappings.

Don't know what to do at this point.

**Comment by dilipkrish** [comment]
@gionn That is exactly the problem. Wondering how to load it at the same level as request mapping controllers

**Comment by gionn** [comment]
@dilipkrish code added to documentation will work only on spring boot, however for my spring mvc webapp I discovered that configuring CORS via spring-security did the trick:

```java
public class WebConfig extends WebMvcConfigurerAdapter
{
    @Bean
    CorsConfigurationSource corsConfigurationSource()
    {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.applyPermitDefaultValues();
        configuration.setAllowedOrigins( Collections.singletonList( "*" ) );
        configuration.setAllowedMethods( getAllHttpMethods() );
        configuration.setAllowCredentials( true );
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration( "/**", configuration );
        return source;
    }
}
```

and then in my `security-context.xml`

```
	<http>
		<cors configuration-source-ref="corsConfigurationSource"/>
	</http>
```

:beers:

**Comment by dilipkrish** [comment]
Thanks for the recipe for spring-mvc apps @gionn

**Comment by mbrezovsky** [comment]
@gionn It's not working on Spring MVC with version > 5.0.8.RELEASE. I wasn't able to configure CORS filter with any way. Configuration was applied for other endpoints, but it was skipped for swagger json endpoint. Is any chance to fix that?

**Comment by olaf-otto** [comment]
Hi all, I have an addition to @gionn 's findings using springfox 2.9.2 + Spring 5.0.8 + Spring Boot 2: 

When defining a global CORS config, like so:

```
@Configuration
@EnableWebMvc
public class WebConfig implements WebMvcConfigurer {
 
    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**");
    }
}
```

Spring registers this CORS config and calls org.springframework.web.servlet.handler.AbstractHandlerMapping#setCorsConfigurations on all handler mappings known to the org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport. The Springfox springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping is not among those (the handler mappings known to Spring appear somewhat hard coded).

Resulting, the global cors config is not known by the springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping. Perhaps it can be made to explicitly retreive the config upon initialization?

**Comment by dilipkrish** [comment]
Thanks for the tip @olaf-otto

**Comment by gandrade** [comment]
From the [docs](https://springfox.github.io/springfox/docs/current/#answers-to-common-questions-and-problems):

> *21. How to add CORS support? (thanks @gangakrishh)
> 
> Based on the spring guide, Creating a WebMvcConfigurer we can configure a request mapping to allow specific origins.
> ```java
>     @Bean
>     public WebMvcConfigurer corsConfigurer() {
>         return new WebMvcConfigurerAdapter() {
>             @Override
>             public void addCorsMappings(CorsRegistry registry) {
>                 registry.addMapping("/some-request-mapping").allowedOrigins("http://localhost:9000");
>             }
>         };
> ```
> 
> If that doesn’t work, most likely the cors registration is happening earlier than the SpringFox beans are registered. To fix this, we can register a CORS filter registration bean, that registers our endpoints. In the example below, we’ve registered it for all endpoints.
> 
> ```java
> @Configuration
> public class WebConfig extends WebMvcConfigurerAdapter {
> 
>     //https://stackoverflow.com/questions/31724994/spring-data-rest-and-cors
>     @Bean
>     public FilterRegistrationBean corsFilter() {
>         UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
> 
>         CorsConfiguration config = new CorsConfiguration().applyPermitDefaultValues();
>         config.setAllowCredentials(false);
>         source.registerCorsConfiguration("/**", config);
> 
>         FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
>         bean.setOrder(0);
> 
>         return bean;
>     }
> }
> ```

Not sure if it might help, but I've followed the second approach (`FilterRegistrationBean`) on a Spring Boot `2.1.1.RELEASE` project using SpringFox `2.9.2` version and it's working.

**Comment by jonseah** [comment]
I'm on springfox 2.9.2 and spring-boot 2.1.8.RELEASE and i was able to resolve this issue via [spring-security](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#cors)

```
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.cors().and()...
    }

    @Bean
    CorsConfigurationSource corsConfigurationSource() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", new CorsConfiguration().applyPermitDefaultValues());
        return source;
    }
}
```
