### ISSUE TITLE
Springfox Swagger UI [2.8] IE / Edge Support

### ISSUE THREAD

**Issue by gerard-pmh** [springfox/springfox#2216]
We just upgraded from 2.7 to 2.8, and we have a problem when opening swagger ui in IE 11 and Edge.
The error comes from the script springfox.js, which is written in ES2017, with arrow functions and async / await.
The problem is that IE 11 does not support arrow functions, and Edge does not support async / await.
Are those browsers still supposed to be supported ?
Thank you.

**Comment by weituotian** [comment]
so how to solve it now?
