### ISSUE TITLE
ApiListingScannerPlugin is ignored if no Spring controller is registered

### ISSUE THREAD

**Issue by raphw** [springfox/springfox#2219]
To resolve all APIs, Springfox resolves all relevant `RequestHandler`s via `ApiListingReferenceScanner::scan`. If no such request handlers are found, the resulting `requestMappingByResourceGroup` map is empty.

This is of course expected but in `ApiListingScanner::scan`, the `pluginsManager.additionalListings(context)` method is only invoked if at least one `ResourceGroup` is available.

In the GUI, the plugin-based mappings and the ones derived from Spring Controllers do not need to be related so I do not quite understand why those two are bound together within Spring Fox. Is this a bug or is there another way to make a mapping visible without any Spring controller present?

Previously, I worked around this by adding a pseudo controller with a hidden attribute what still works today. However, since the last update the section of the hidden controller is still shown in the GUI which is why I would prefer to remove the work-around controller that I only need to make Spring Fox display the manually registered mapping.

**Comment by dilipkrish** [comment]
@raphw big fan of your work on byte-buddy! 

I see your point. Perhaps the abstraction for the `ApiListingScannerPlugin` isn't correct. Since the purpose of that extensibility is to synthesize new `ApiDescriptions` it should've accounted for a synthesized `ResourceGroup` as well. If I understand correctly, that is what you're trying to do using a pseudo controller 😢 

Let me see how I can clean it up. Open to suggestions as well.

**Comment by raphw** [comment]
Thanks Dilip, I am myself a heavy user of SpringFox. Thanks for working out this integration!

Personally, I would aim to move or replicate the `ApiListingScannerPlugin` outside of the loop somehow. From a GUI perspective, even today, the registered `ApiDescription`s are unrelated to any resource group. However, I am not quite sure if and how these two are releated nevertheless. 

Maybe it is as simple as adding another type:
```java
public interface ApiGroupedListingScannerPlugin extends Plugin<DocumentationType> {
  Map<String, ApiDescription> apply(DocumentationContext context);
}
```
This listing could then be added to the map directly. By using this plugin, it would also be possible to completely replace a group if this was desired.
