### ISSUE TITLE
OperationParameterReader does not process optional path parameters correctly

### ISSUE THREAD

**Issue by raphw** [springfox/springfox#2220]
When a Spring controller offers an optional parameter such as in:

```java
@RequestMapping({"/foo", "/foo/{bar}"})
public void foo(@PathVariable(value = "bar", required = false) String bar) {
  if (bar == null) { ... } else { ... }
}
```

Springfox will correctly create two mappings for `/foo` and `/foo/{bar}` but define the `bar` parameter as required for both mappings. I think the problem lies in the `OperationParameterReader` which should detect that the parameter for `bar` should be ignored for the mapping of `/foo`.

I think that a solution could be as simple as adding a condition to the `OperationParameterReader:shouldIgnore` method that looks something similar to:

```java
if (parameter.hasParameterAnnotation(PathVariable.class)
  && !parameter.getAnnotation(PathVariable.class).required()
  && !context.requestMappingPattern().contains("{" + methodParameter.defaultName() + "}") {
    return true;
}
```

This way any parameter would be suppressed that is:
1. Representing a path variable
2. Is not required 
3. Is not part of the mapped path.

**Comment by dilipkrish** [comment]
There is an underlying assumption that `PathVariables` are always required. Thanks for catching this!
