### ISSUE TITLE
@XMLRootElement and @XmlAttribute ignored

### ISSUE THREAD

**Issue by rstmm** [springfox/springfox#2230]
- Version 2.8.0
- Question/Bug?

I have some issues setting up Springfox for usage in Swagger UI.
I got it working in general, but the XML examples which are created are partly wrong.

I have these models:

```
@XmlRootElement(name = "ApplicatorUnits")
@XmlAccessorType(XmlAccessType.FIELD)  
public class EHDTOApplicatorUnits
{
    @XmlElement(name = "UnitGroup")
    private List<EHDTOUnitGroup> ehdtoUnitGroups;

    public List<EHDTOUnitGroup> getEhdtoUnitGroups()
    {
        return ehdtoUnitGroups;
    }

    public void setEhdtoUnitGroups(List<EHDTOUnitGroup> ehdtoUnitGroups)
    {
        this.ehdtoUnitGroups = ehdtoUnitGroups;
    }
}
```

```
@XmlRootElement(name = "UnitGroup")
@XmlAccessorType(XmlAccessType.FIELD)  
public class EHDTOUnitGroup
{
    @XmlAttribute(name = "name")
    private String name;
    
    @XmlElement(name = "unit")
    private List<EHDTOUnit> ehdtoUnits;

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public List<EHDTOUnit> getEhdtoUnits()
    {
        return ehdtoUnits;
    }

    public void setEhdtoUnits(List<EHDTOUnit> ehdtoUnits)
    {
        this.ehdtoUnits = ehdtoUnits;
    }
}
```

You see some usages of `@XmlAttribute`, `@XmlRootElement` and `@XmlElement`.
After adding jackson jaxb annotation introspectors (I tried different ways) the XML was partly correct, as the `@XmlAttribute` annotations have been considered after this step:

```
        JaxbAnnotationModule jaxbAnnotationModule = new JaxbAnnotationModule();
        jaxbAnnotationModule.setPriority(Priority.PRIMARY);
        mapper.registerModule(jaxbAnnotationModule);
        /*AnnotationIntrospector primary = new JacksonAnnotationIntrospector();
        AnnotationIntrospector secondary = new XmlJaxbAnnotationIntrospector(mapper.getTypeFactory()); //new JaxbAnnotationIntrospector(mapper.getTypeFactory());
        AnnotationIntrospector pair = new AnnotationIntrospectorPair(primary,secondary);
        mapper.setAnnotationIntrospector(pair);*/
```
 However, the other 2 are still ignored, resulting in this example xml:

```
<?xml version="1.0"?>
<EHDTOApplicatorUnits>
  <UnitGroup>
    <name>string</name>
    <unit>
      <id>1</id>
      <name>string</name>
      <unitSystem>string</unitSystem>
    </unit>
  </UnitGroup>
</EHDTOApplicatorUnits>
```

While the real output of the API is:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ApplicatorUnits>
  <UnitGroup name="coefTempErrorSpan">
    <unit>
      <id>1</id>
      <name>% span /10K</name>
      <unitSystem>SI</unitSystem>
    </unit>
    <unit>
      <id>2</id>
      <name>% span /50F</name>
      <unitSystem>SI</unitSystem>
    </unit>
  </UnitGroup>
...
</ApplicatorUnits>
```

You see the different naming of the root element, and also the "name" of the UnitGroup which is not an attribute in the example xml but an own child-node.

Is there any step I missed?

**Comment by dilipkrish** [comment]
Xml support is not really great. I won't be surprised if its a bug.

**Comment by rstmm** [comment]
I would be very thankful if you could have a look at this and maybe provide a fix, as I am introducing this in a project right now where we use this annotations extensively :( ...

**Comment by rstmm** [comment]
I think this is related to this issue: https://github.com/springfox/springfox/issues/2076

**Comment by dilipkrish** [comment]
Let me investigate.

**Comment by rstmm** [comment]
Ok, thanks for your effort! Any quick workaround you know which I could use instead of `@XmlAttribute` to continue already now?

**Comment by rstmm** [comment]
Hey @dilipkrish,

without wanting to bring you in hurry/stress or getting on your nerves, can you give me some update on this if you already had time to look into it and maybe give some estimation until when there could be a fix? Or maybe you have some workaround for me? I just need to know some timeframe so I can update some planning for my team, that would help me a lot :)

But anyway: Thanks for your effort!

**Comment by dilipkrish** [comment]
@rstmm I'm planning to take a look at this, this week. Will let you know, sorry for the delay.

**Comment by dilipkrish** [comment]
Have you seen [the docs](http://springfox.github.io/springfox/docs/current/#dependencies)?

**Comment by rstmm** [comment]
Seems like i have overseen this part in the docs. Sorry! Thanks that's all I need I guess. Will try it later today. Thanks a lot for your effort!

**Comment by rstmm** [comment]
@dilipkrish Thanks again, I can confirm it's working. However, the swagger-ui.html is not working anymore in snapshot versions, I reported this here already, could you please have a look? https://github.com/springfox/springfox/issues/2281#issuecomment-372806807

**Comment by dilipkrish** [comment]
@rstmm [the demos](https://github.com/springfox/springfox-demos) project works just fine. If you load the project and run `./gradlew :spring-java-swagger:appRun` and follow instructions in readme it works just fine.

**Comment by rstmm** [comment]
The remaining issue was fixed in https://github.com/springfox/springfox/issues/2309.
Thanks!
