### ISSUE TITLE
Full URLs in /swagger-resources no longer works after 2.7.0 -> 2.8.0 Upgrade

### ISSUE THREAD

**Issue by gloeglm** [springfox/springfox#2235]
We are using multiple SwaggerResource objects to aggregate swagger-definitions from multiple hosts, which are not the same as the one hosting swagger-ui. This works fine in 2.7.0, the json generated /swagger-resources looks like this (example):

    [
        {"name":"xxx-Service",
         "location":"http://localhost:8080/api/swagger",
         "swaggerVersion":"2.0"}
    ]

With springfox-swagger-ui hosted on localhost:8014 this renders fine. 

After upgrading to 2.8.0 the generated /swagger-resources changes to 

    [
        {"name":"xxx-Service",
         "location":"http://localhost:8080/api/swagger",
         "swaggerVersion":"2.0",
         "url":"http://localhost:8080/api/swagger"}
    ]

and when swagger-ui attempts to render the documentation, the location gets prefixed with an additional base URL, resulting in the following error message in swagger-ui:

    Failed to load API definition.

    http://localhost:8014http://localhost:8080/api/swagger is not a valid URL. 

As far as I can see the issue happens in https://github.com/springfox/springfox/blob/36c53cf6d4dec0b720be6fc5dce2058a45d1725c/springfox-swagger-ui/src/web/js/springfox.js#L14 where the baseUrl should maybe only be prefixed in case the resource URL is a relative path. I can attempt a fix if you agree that should be changed.

**Comment by dilipkrish** [comment]
Thanks for reporting @gloeglm

**Comment by TJReinert** [comment]
Did this break again in 3.0.0?

https://github.com/springfox/springfox/blob/3.0.0/springfox-swagger-ui/src/web/js/springfox.js#L57

**Comment by TJReinert** [comment]
I'm seeing this bug at 3.0.0. Is this now intended functionality?

**Comment by dilipkrish** [comment]
@TJReinert That is a regression! thank you for catching that!

**Comment by TJReinert** [comment]
Not a problem, thanks for being so speedy!
