### ISSUE TITLE
@ApiParam not working in interface

### ISSUE THREAD

**Issue by piyushj90** [springfox/springfox#2239]
I have added @ApiParam annotation in interface method, but it is not working. Please let me know, if it is fixed in v2.8.0.
Below is code sample:
`@ApiOperation(value = "Find")
ResponseDto find(@ApiParam(value = "Filter Criteria", required = true) String filterCriteria,      HttpServletResponse response);`

I am using springfox v2.8.0

**Comment by dilipkrish** [comment]
@piyushj90 It is not fixed #1575

**Comment by 3t-dev** [comment]
Could you try to add more `@RequestParam` annotation, like as `@ApiOperation(value = "Find") ResponseDto find(@ApiParam(value = "Filter Criteria", required = true) @RequestParam() String filterCriteria, HttpServletResponse response);`?
It works for me.

**Comment by lafangyuan** [comment]
so which version solves this bug?

**Comment by astral-keks** [comment]
the issue is still reproducible for springfox-swagger2:2.9.2

**Comment by dilipkrish** [comment]
It isnt fixed yet please track #1575

**Comment by dilipkrish** [comment]
Closing as duplicate of #1575
