### ISSUE TITLE
Unable to infer base url

### ISSUE THREAD

**Issue by mmaryo** [springfox/springfox#2240]
Hello 

With Spring Boot 1.5.10 and Springfox Swagger / Swagger UI 2.8.0 and Java 9
I have this issue : 

Unable to infer base url. This is common when using dynamic servlet registration or when the API is behind an API Gateway. The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/. Please enter the location manually: 

    @Configuration
    @EnableSwagger2
    public class SwaggerConfig {
        @Bean
        public ApiInfo apiInfo() {
            return new ApiInfoBuilder()
                    .title("Horus API")
                    .description("API Documentation")
                    .termsOfServiceUrl("http://www.test.fr")
                    .license("private")
                    .version("1.0")
                    .build();
        }
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        super.addResourceHandlers(registry);
        registry.addResourceHandler("/static/images/**").addResourceLocations("/images/");
        registry.addResourceHandler("/static/css/**").addResourceLocations("/css/");
        registry.addResourceHandler("/static/js/**").addResourceLocations("/js/");
        registry.
                addResourceHandler("/swagger-ui.html**")
                .addResourceLocations("classpath:/META-INF/resources/swagger-ui.html");
        registry.
                addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }

And Spring Security : 

        @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .......
                .antMatchers("/v2/api-docs").hasAnyAuthority(RoleEnum.DEVOPS.name())
                .antMatchers("/swagger-ui.html").hasAnyAuthority(RoleEnum.DEVOPS.name())
                .antMatchers("/webjars/**").hasAnyAuthority(RoleEnum.DEVOPS.name())
                .antMatchers("/swagger-resources/**").hasAnyAuthority(RoleEnum.DEVOPS.name()) <--HERE-->
                .antMatchers("favicon.ico").hasAnyAuthority(RoleEnum.DEVOPS.name())

                .anyRequest().hasAnyAuthority(RoleEnum.USER.name())

The strang thing is when I open url /swagger-resources/** to public, swagger-ui works 
I don't want to do that 

![capture du 2018-02-08 12-48-26](https://user-images.githubusercontent.com/1669985/35971500-771609e0-0cce-11e8-91a6-ba59996783c5.png)

**Comment by predrag-viceic** [comment]
Same here with Spring Boot 2.0.0.RC1, Swagger-ui 2.8.0 and Java 8.

**Comment by dilipkrish** [comment]
I think that not relying on unsecured access to `swagger-resources` has been fixed in 2.8.1-SNAPSHOT. Couple of things I noticed are
- You don't need to add resource handlers for spring boot. It should autoconfigure
- If you have a dynamic servlet, you need to use `docket.pathMapping(...)` to add the path so that swagger ui can find the endpoints correctly

**Comment by predrag-viceic** [comment]
Difficult to say as io.springfox:springfox-swagger-ui:2.8.1-SNAPSHOT pulled from the repo is almost empty, containing only META-INF/MANIFEST.MF

**Comment by harish0000** [comment]
@dilipkrish any updates when 2.8.1 is going to release ? any workaround to fix this ?

**Comment by dilipkrish** [comment]
@predrag-viceic that should be fixed via #2309 

@harish0000 there is no workaround or fix for the "Unable to infer base url", You need to configure spring security to either permit all the springfox endpoints, or make the whole app protected such that anonymous access to any of the resources is not allowed.

**Comment by predrag-viceic** [comment]
Thanks, works perfectly !!

**Comment by harish0000** [comment]
@dilipkrish after permit all swagger resources it works ,but then swagger resources are not protected and can be open by anyone.

```
@Override
	protected void configure(HttpSecurity http) throws Exception {
		http.csrf().disable().authorizeRequests().antMatchers(AUTH_WHITELIST).permitAll().anyRequest().authenticated()
				.and().httpBasic().authenticationEntryPoint(authEntryPoint);
	}
```
if i remove the `antMatchers(AUTH_WHITELIST).permitAll()` and then try i get the 

> Unable to infer base url

![image](https://user-images.githubusercontent.com/22025958/37693525-50bb340e-2ce6-11e8-8687-52b3a474af30.png)

**Comment by dilipkrish** [comment]
Yes, you could protect those resources using basic auth

**Comment by mahesh-mehandiratta-nagarro** [comment]
Hey!

Where can I get the 2.8.1 version jars ?
Forgive me if it is a stupid question.

**Comment by maheshm2195** [comment]
Hey! Where can I get the 2.8.1 version updated jars ? Forgive me if it is a stupid question.

**Comment by dilipkrish** [comment]
@maheshm2195 2.8.1 is not released yet. It will be soon. Are you looking for the 2.8.1-SNAPSHOT?  3.0.0 is definitely not released. Where are you seeing this?

**Comment by maheshm2195** [comment]
Yes. Sorry for being unclear. I have the exact same issue as mentioned in this thread. I'm currently on 2.8.0 version and using different 2.8.0-SNAPSHOT.jars.

As you mentioned that issue has been solved in 2.8.1 so I just needed the 2.8.1-SNAPSHOT.jars. All core, ui etc of 2.8.1 version.

Hope I'm able to clear what I'm asking. Please let me know if I can clarify anything else.

**Comment by dilipkrish** [comment]
Have you read [the docs](http://springfox.github.io/springfox/docs/current/#dependencies)? You need to add the snapshot repository to you list of repositories `http://oss.jfrog.org/artifactory/oss-snapshot-local` and you can find it there

**Comment by maheshm2195** [comment]
Oh, okay. Thanks a ton!
I'll try it as soon as possible.

**Comment by maheshm2195** [comment]
Earlier I got the 2.8.0 jar from the maven repository itself so I assumed rest will be uploaded there too. Thanks for the information.

**Comment by dilipkrish** [comment]
Snapshots are published to the snapshot repository.

**Comment by maheshm2195** [comment]
Found the jars I needed. The issue is resolved very well in 2.8.1. 
Thanks a lot @dilipkrish ! 
Was stuck at it for more than required. Made my day.

**Comment by maheshm2195** [comment]
@dilipkrish There are 2 other issues that I am facing while documenting some of my APIs and I'm not sure if Swagger supports it or not.
If you could tell me, it would be of great help!
1. Can we make the number of attachments possible while making a POST request **variable** ? I mean to say that the **number** of files that can be sent in the POST request are not fixed in advance by developer and user can send as many as required ?
2. Can the user decide the name of the files/attachments dynamically in the UI instead of developer fixing it in the code. I've attached a snip to clarify which part I'm trying to make changeable by user. Please see the yellow highlighted area.
![capture](https://user-images.githubusercontent.com/31432600/38148174-f7f13f78-3472-11e8-88ba-48c4aa5e02b1.PNG)

**Comment by maheshm2195** [comment]
Yes. Multipart request is being sent but the user might attach a different named file than already fixed by the developer and code might break. If only we could give the freedom to enter the name dynamically on UI. Just wanted to know if that is supported or not.

**Comment by dilipkrish** [comment]
You can override the fixed file name that you have when you process the request no? Not clear what is expected of springfox. In any case, the file upload feature is a browser feature and cannot be changed.

**Comment by maheshm2195** [comment]
Sure. I understand that. Thank you again for all the help!

**Comment by maheshm2195** [comment]
@dilipkrish Hey!
I started using 2.8.1-snapshot and I also have base authentication enabled. If I haven't entered the username and password from the main UI of my application (where there are text fields to enter the same) and directly access the swagger-ui, it shows me the "infer base url" pop-up again. Once I login from the main UI and reload swaggerUi the popup is gone.

Is there anyway I can redirect from swaggerui page to my login page when authentication is not done instead of showing the popup ?
Also, please redirect me to (if any) docs of swagger to integrate it well with a Java spring application.
Thanks.

**Comment by dilipkrish** [comment]
@maheshm2195 thats great! Thanks for reporting back.

**Comment by maheshm2195** [comment]
Hey @dilipkrish  !
Hope you're doing good.

Faced another issue when I shifted to 2.8.1-SNAPSHOT from 2.8.0.
All the webservices that had path-params are not showing up in the UI now. One implemented example is as below:
`@ApiImplicitParam(name = "id", value = "id for the record", required = true, dataType = "string", paramType = "path")`

They were visible in 2.8.0 UI but they've disappeared now. 
Any help would be really great!

**Comment by dilipkrish** [comment]
@maheshm2195 Could you share what the signature of the request mapping looks like? Also if you feel its a new issue, please create one. Adding to a conversation about an unrelated issue isnt useful to anyone and doesnt help me track bugs effectively

**Comment by maheshm2195** [comment]
@dilipkrish Sure. Did that here: https://github.com/springfox/springfox/issues/2341
Please let me know as we're stuck because of this issue.

**Comment by harish0000** [comment]
@dilipkrish i dont want the swagger url to be open ,because anyone can access it. After permit all swaggers urls ,i can open it without providing any username and password

```
public class ApiSecurityConfiguration extends WebSecurityConfigurerAdapter {

	@Autowired
	private ApiAuthenticationHandler authEntryPoint;
	private static final String[] AUTH_WHITELIST = {

			// -- swagger ui
			"/swagger-resources/**", "/swagger-ui.html", "/v2/api-docs", "/webjars/**" };

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http.csrf().disable().authorizeRequests().antMatchers(AUTH_WHITELIST).permitAll().anyRequest().authenticated()
				.and().httpBasic().authenticationEntryPoint(authEntryPoint);
	}

}
```
how can i secure it ?

**Comment by MartinX3** [comment]
Using 2.9 now.
I still can't send an http auth header to
- ui
- security
- swagger-ressources

**Comment by dilipkrish** [comment]
@MartinX3 Just to better my understanding of your situation. Do you have the springfox endpoints protected by basic authentication and the APIs themselves protected by oauth or other mechanisms?

**Comment by MartinX3** [comment]
Swagger and the entire Rest Backend is behind a reverse proxy called "[Membrane](https://github.com/membrane/service-proxy)"
Every HTTP request require an "Authorization: Basic abcdef1235" HTTP-Header.

**Comment by sandyscoffable** [comment]
I ran into this issue recently. Something seems to have changed between Springfox 2.7.0 and 2.8.0 which makes it not play nicely with a library we were using to log request / response payloads in testing (https://github.com/isrsal/spring-mvc-logger if you are interested).

So, this issue might also be due to a rogue request filter interfering. Hope this helps someone..

**Comment by dilipkrish** [comment]
@sandyscoffable thanks for the repo! What other library out of curiosity?
