### ISSUE TITLE
Remove dependency on org.reflections.Reflections

### ISSUE THREAD

**Issue by leewinder** [springfox/springfox#2243]
- [X] 2.8.0

The released library has a dependency on org.reflections 0.9.11.  As [shown here](https://github.com/ronmamo/reflections/issues/159), this library is licensed under the WTFPL licence which is often rejected by enterprise companies due to it's lack of clarity on the use of this licence.

Even though the pom file lists BSD 2, often this is not enough given the readme stats WTFPL only.

Because of this, even though this project is listed as Apache 2.0, many companies won't allow this project to be used internally due to it's dependency tree.

**Comment by dilipkrish** [comment]
Thanks for bringing it to the attention. It is used by `swagger-core` which is apache 2.0 as well.

https://github.com/swagger-api/swagger-core/blob/f34c101613be26fcc4f300de6bce2fa76159390a/pom.xml#L474-L478

Which is why I assumed its ok to use the library. Open to suggestions/alternatives

**Comment by leewinder** [comment]
I don’t have any suggestions unfortunately but we did notice that if we excluded it from our build and denied the dependency, the Swagger UI still worked as expected.

I don’t know enough about Swagger to say what would be missing if we’d tried to use the Swagger UI in a different way.

**Comment by dilipkrish** [comment]
@leewinder Scanning the repo for conventions will not work for e.g. jackson serliazation convention `JacksonSerializerConvention` will not work if configured.

**Comment by PascalSchumacher** [comment]
@dilipkrish Reflections can usually be replaced by https://github.com/lukehutch/fast-classpath-scanner, which has a Apache compatible MIT License (see https://www.apache.org/legal/resolved.html#category-a), no dependencies and better performance.

I could try to create a pull request, if is welcome.

**Comment by dilipkrish** [comment]
@PascalSchumacher Absolutely welcome. Currently Reflections is a provided dependency, so it is an opt-in library and you use the `JacksonSerializerConvention` only if users are ok with taking on that license. 

I would recommend adding another implementation of the same `JacksonSerializerFastClassPathScannerConvention` (namings hard I know!). 

Java 7+ is ok to go with post 3.0, So if you do endup with a PR please expect that it will only be pulled in post 2.9 (which is sometime in April
