### ISSUE TITLE
Wording of "Done" Button => "Cancel"?

### ISSUE THREAD

**Issue by hoereth** [springfox/springfox#2245]
Version: [ 2.8.0]

What kind of issue is this? Change Request.

We experienced usability issues with the springfox-swagger-ui. The authorization window shows a "Done" button (see screenshot) which acts like a "Cancel" button. I like to suggest to rename it, because users might be tempted to click "Done" to perform the authorization. In fact they should click "Authorize". You would improve awareness by renaming "Done" to "Cancel".

![swagger-authorization](https://user-images.githubusercontent.com/22708947/36038404-e971a188-0dbf-11e8-9d5f-85ddb42e613b.PNG)

**Comment by dilipkrish** [comment]
@hoereth this would be a request for [Swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by hoereth** [comment]
I am sorry! I created another issue as recommended there https://github.com/swagger-api/swagger-ui/issues/4211 and will close this one. Thanks for your hint!

**Comment by dilipkrish** [comment]
👍
