### ISSUE TITLE
Request parameters in POJO cannot be set as required

### ISSUE THREAD

**Issue by fabriziocucci** [springfox/springfox#2246]
### Description

I'm not entirely sure whether this classifies as a `springfox` enhancement, a `swagger-ui` enhancement or there is simply a better way to do this in `spring`, so please bear with me.

Let's consider an endpoint which accepts many request parameters (here only two for simplicity):

```java
@PostMapping(path = "/fruits", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public MyResponse addFruit(
        @RequestParam(value = "param1", required = true) String param1,
        @RequestParam(value = "param2", required = false) String param2) {
    // whatever implementation!
}
```
 
In the Swagger UI, only `param1` will show up in bold since it is required.

If we group all request parameters inside a POJO, let's say:

```java
public class FruitParameters {

    private String param1;
    private String param2;
   
    public String getParam1() { ... }
    public void setParam1(String param1) { ... } // required by Spring unfortunately! :(

    public String getParam2() { ... }
    public void setParam2(String param2) { ... } // required by Spring unfortunately! :(
 
}
```

and update the endpoint as follows:

```java
@PostMapping(path = "/fruits", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public MyResponse addFruit(FruitParameters fruitParameters) {
    // whatever implementation!
}
```

everything will still work fine but, at best of my limited knowledge, there is no way to specify that `param1` is required, so it will **not** show up in bold in the Swagger UI and it will indeed be treated as not required.

---

### Workaround

A workaround for enforcing a parameter to be required is using the Bean Validation API:

##### FruitController.java
```java
@PostMapping(path = "/fruits", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public MyResponse addFruit(@Valid FruitParameters fruitParameters) {
    // whatever implementation!
}
```

##### FruitParameters.java
```java
public class FruitParameters {
    
    @NotNull
    private String param1;
    private String param2;
   
    // getters and setters
 
}
```

Although, `param1` will still **not** show up in bold and, again, it will still be treated as not required as far as the Swagger UI is concerned.

---

### Questions

1. Am I missing something?

2. Is there a way to make a request parameter required in the Swagger UI when using a POJO for aggregating request parameters?

3. If there is no way to currently do it, would that be possible by leveraging the Bean Validation API? (e.g. if the instance field in the POJO is annotated with `@NotNull` then it is a required parameter)

---

### Affected Version
* 2.7.0

**Comment by fabriziocucci** [comment]
My bad, I didn't know that the bean validation support needs to be explicitly enabled (as reported in the [documentation](http://springfox.github.io/springfox/docs/current/#springfox-support-for-jsr-303)). 

So, after enabling it, all POJO fields annotated with `@NotNull` are correctly shown as required in the Swagger UI.

**Comment by nobe0716** [comment]
Hello dear,
I am a stranger here but I may have a chance to give some tips for you.

You can use [@ApiParam](http://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/ApiParam.html) in your POJO.

There some annotations(cf. ApiParam, ApiModelProperty, ...) in Swagger-ui, which describes properties of params.

```java
@Data
public class FruitParameters {
    
    @ApiParam(required=true)
    private String param1;
    private String param2;
}
```
