### ISSUE TITLE
Use name() instead of toString() for enums

### ISSUE THREAD

**Issue by jonatan-ivanov** [springfox/springfox#2247]
This is a follow-up on #1745:
Springfox uses `toString()` to get the unique id of an enum instead of `name()`. This seems to be a bug since `toString()` is intended to return the user-friendly name and `name()` is intended to return the unique name of the enum. On the web-ui the result of `toString()` could be shown but the value which will be sent in the request should be the result of `name()`.

**Comment by dilipkrish** [comment]
Sure.  Would you mind helping with a PR?

**Comment by jonatan-ivanov** [comment]
@dilipkrish I would love to, is it ok if I get back to you sometime next week?

Could you please give me some guidance? Do you happen to know if there is any spot where I can bump into issues or it should be as easy as replacing the `toString()` calls to `name()`?

Could you please help me (if it is on the top of your head) where can I found the part which will render the input dropdown on the UI? I think it would be great to use the `toString()` on the UI but sending the `name()` to the backend as the value.

**Comment by dilipkrish** [comment]
🔔
