### ISSUE TITLE
How to avoid the automatic number convertion for example

### ISSUE THREAD

**Issue by thelo-gaultier** [springfox/springfox#2249]
Hi,

I noticed that if I give a  number in an ApiModelProperty's example, this one will be automatically converted into a number type in the swagger document ( despite the returned type of the function), which will result as a number in the Swagger ui. 

Although this is handy in some case, is there a way to enforce the example type as a String?

For example:

`
@ApiModelProperty(value = "An id, for ", example = "6789")
String getId() {
     ...
}
`

This will result in a json document looking like this
`
    ....
   "id": 6789,
    ....
`

Now assuming that I want all of my id to be treated as String ( even if they could be a number ). Is there a way to avoid the automatic conversion and get this Json document :
`
    ....
   "id": "6789",
    ....
`

version: 2.8.0

Many thanks

**Comment by nobe0716** [comment]
'api-docs' seems to be misformed.
If I test a example with "numeric example", example of property parsed as number
It may be hard to enforce example types as string.
```json
properties": {
  "key": {
    "type": "string",
    "example": 173,
    "description": "test key",
    "allowEmptyValue": false
  }
}
```

**Comment by dilipkrish** [comment]
@thelo-gaultier @nobe0716 I think it needs to be escaped for it to be a string. For e.g. if you intended it to be a string it should be ` ... example = "'6789'"`

**Comment by thelo-gaultier** [comment]
In this case, I get `"example": "'1234'"` in the swagger file, and `"id": "'1234'"` in the swagger ui

**Comment by dilipkrish** [comment]
Let me investigate

**Comment by mustafababil** [comment]
I have the similar problem with recent versions. Even though, example value for string property is double quoted integer value, it is parsed into integer value. If I surround first with single quote then double quotes, it works. Here are the cases :

```
stringIntProperty:
  minLength: 4
  maxLength: 10
  pattern: ^(?!\s*$).+
  type: string
  example: "12345"
```
--> becomes `{..., "stringIntProperty": 12345, ... }` on Swagger UI, and `@ApiModelProperty(example = "12345", required = true, value = "")` in generated Java class.

```
stringIntProperty:
  minLength: 4
  maxLength: 10
  pattern: ^(?!\s*$).+
  type: string
  example: "'12345'"
```
--> becomes `{..., "stringIntProperty": "12345", ... }` on Swagger UI, and   `@ApiModelProperty(example = "'12345'", required = true, value = "")` in generated Java class.

Springfox v.2.9.2
OpenAPI generator v4.1.0

**Comment by tbwork** [comment]
It would be better if it could recognize the type in the filed definition and convert it according to the type.

**Comment by Andre6738** [comment]
The best workaround I found is to use a "full width plus sign":

`example = "\uFF0B27"` generates `+27`
