### ISSUE TITLE
Docket SecurityContexts to filter by HTTP methods

### ISSUE THREAD

**Issue by vadimkim** [springfox/springfox#2256]
Hello,
     I don't know whether it is implemented or not. Documentation for Docket says:

> **securityContexts**(java.util.List<SecurityContext> securityContexts)Configures which api operations (via regex patterns) **and HTTP methods** to apply security contexts to apis.

All examples and source code look-up showed that only path filtering is implemented. I need to define security context not only by path, but also by HTTP method (for ex. restricting DELETE)
Basic class contains only "forPaths" method
>private SecurityContext securityContext() {
    return SecurityContext.builder()
        .securityReferences(defaultAuth())
        **.forPaths(PathSelectors.regex("/anyPath.*"))**
        .build();
  }

Is it possible somehow to add also HTTP method restrictions to SecurityContexts?

**Comment by dilipkrish** [comment]
@vadimkim You're right, its an oversight in the documentation

**Comment by vadimkim** [comment]
@dilipkrish is it something I can help to implement? Probably I am missing a view of big picture, but think that authorization for API endpoints is not good at all. Would like to show the API for authorized users **after** authentication, not before. Having unauthorized user to see all the specification is a bit strange way of implementing security don't you think so?

**Comment by dilipkrish** [comment]
Its already working just like you'd expect. Its a matter of configuration. Have you seen the [jhipster sample app](https://github.com/jhipster/jhipster-sample-app)

**Comment by vadimkim** [comment]
@dilipkrish Yes, I have seen this piece of ...  
If you open this application and go to : `http://localhost:9000/swagger-ui/index.html` (front-end app) you can see all documentation without being authenticated at all. Obviously all back-end URL-s are also open: `http://localhost:8080/swagger-ui/index.html `and `http://localhost:8080/v2/api-docs` JHipster generates nice interface, but regarding security it worth nothing.
What I would like to achieve is granular user access to API-s not like everything or nothing.
