### ISSUE TITLE
@RequestPart "name/value" attribute ignored

### ISSUE THREAD

**Issue by fschmager** [springfox/springfox#2263]
# Summary
The `name`/`value` attribute of `@RequestPart` is not used. Springfox uses the method parameter name instead.
I would assume the method name should only be used if there is no `name`/`value` otherwise the annotations's value should be used.

# Example

```java
@RestController
public class ExampleController {

	@PostMapping(path = "endpoint", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
	public void endpoint(@RequestPart(name = "annotationName") MultipartFile parameterName) {
		
	}
}
```
# Expected
The parameter name in UI/json should be `annotationName` (the `name`/`value` of `@RequestPart`).

# Actual
The parameter name in UI/json is `parameterName` (the method argument name).

<img width="742" alt="screen shot 2018-02-22 at 09 55 33" src="https://user-images.githubusercontent.com/10031576/36545313-9eb2400c-17b6-11e8-8185-d53d02d3f937.png">

```javascript
        "/endpoint": {
            "post": {
                "tags": [
                    "example-controller"
                ],
                "summary": "endpoint",
                "operationId": "endpointUsingPOST",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "name": "parameterName",
                        "in": "formData",
                        "description": "parameterName",
                        "required": true,
                        "type": "file"
                    }
                ],
```

Springfox version: 2.8.0

**Comment by dilipkrish** [comment]
Thanks for reporting!
