### ISSUE TITLE
Optional query parameters are marked as required in the UI

### ISSUE THREAD

**Issue by ok11** [springfox/springfox#2268]
Using springfox 2.8.0 to generate UI out of annotations, generated by the swagger-codegen.
Generated code (actually correct, **see last line**):
 ```
   @ApiOperation(value = "Get all users", nickname = "getUsers", notes = "Get all users ", response = User.class, responseContainer = "List", authorizations = {
        @Authorization(value = "user_auth", scopes = {
            @AuthorizationScope(scope = "ADMIN", description = "Manage users"),
            @AuthorizationScope(scope = "USER", description = "Maintain own user")
            })
    }, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = User.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid ID", response = Error.class),
        @ApiResponse(code = 404, message = "User not found", response = Error.class) })
    @RequestMapping(value = "/users",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<User>> getUsers(@ApiParam(value = "Filter the list") @Valid @RequestParam(value = "$filter", required = false) String filter);
```
 The UI insists that the filter query parameter is required:

![image](https://user-images.githubusercontent.com/1530712/36795954-98e4e75e-1ca4-11e8-9539-756f07f94b29.png)

There is no additional springfox relevant configuration in the service.
I may be wrong, but for me looks like a bug. Please let me know if I can provide any additional input to help investigating/resolving it. Thanks!

**Comment by dilipkrish** [comment]
Certainly seems like it. Thanks for reporting

**Comment by nikonovitch** [comment]
It looks like the problem still exists. 
With version **2.9.2** and the following the code:

![image](https://user-images.githubusercontent.com/3875631/66217347-693d0d80-e6c7-11e9-8c33-e22cbefb390b.png)
you can still see the params marked as required:
![image](https://user-images.githubusercontent.com/3875631/66217445-97225200-e6c7-11e9-9eb2-2ea35589d98d.png)

**Comment by kimgysen** [comment]
```
    @GetMapping({ "/v1.0" })
    public Flux<Post> getPosts(@RequestParam Optional<String> maxId) {
```
<img width="551" alt="Screenshot 2021-02-01 at 23 49 26" src="https://user-images.githubusercontent.com/4547364/106527847-376cce80-64e8-11eb-928b-2b49d4dbf510.png">

Version 3.0.

**Comment by hmanoharan-12** [comment]
Any resolution for this issue? It still exists

**Comment by hmanoharan-12** [comment]
Works fine in version 2.9.2 when require=true is specified in @ApiParam 

![Screenshot_2021-08-23_13-34-25](https://user-images.githubusercontent.com/54938784/130412517-a5440697-0849-4d01-9270-445f149cd56a.png)

Ignore the required = false in @RequestParam
