### ISSUE TITLE
springfox-data-rest - spring-data 3 support

### ISSUE THREAD

**Issue by PascalSchumacher** [springfox/springfox#2272]
I to upgrade a project using springfox-data-rest `2.8.0` to spring boot `2.0.0.RELEASE` (with uses spring-data `3.0.5`) but got:

`org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;`

We are using springfox-data-rest like this:

```
@Import(SpringDataRestConfiguration.class)
public class MyApp extends SpringBootServletInitializer
```

Sorry if this is a duplicate, I could not find any existing issue.

BTW: Thanks you very much for providing springfox!

**Comment by PascalSchumacher** [comment]
I guess https://github.com/springfox/springfox/pull/2273 would fix this issue.

**Comment by PascalSchumacher** [comment]
Closed because this issue already covered by https://github.com/springfox/springfox/issues/1773

**Comment by dilipkrish** [comment]
@PascalSchumacher thank you for reporting.
