### ISSUE TITLE
Q: Unable to call swagger json url with an ajax call

### ISSUE THREAD

**Issue by rajeevnaikte** [springfox/springfox#2284]
What version of the library are you using? Is it the latest version? 
Yes, am using v2.8.0

What kind of issue is this?
Question.

Am unable to call swagger json url (http://127.0.0.1:8888/v2/api-docs) with an ajax call.
Is there a way i can get the swagger json with ajax call?

**Comment by dilipkrish** [comment]
@rajeevnaikte I think you need to correctly set the spring security settings

**Comment by rajeevnaikte** [comment]
Yup, that was the problem. I was using 'WebMvcConfigurer corsConfigurer()', but it had some problems. Later i created bean of CorsFilter, it is working.

**Comment by rajeevnaikte** [comment]
Was creating JS utility to get all Rest APIs from swagger json, for my project. Have made this utility available public at - https://www.npmjs.com/package/rn-swagger2-client

**Comment by dilipkrish** [comment]
@rajeevnaikte thank you for reporting your solution back!

**Comment by dilipkrish** [comment]
@rajeevnaikte also thank you for being a awesome fellow OSS participant!
