### ISSUE TITLE
Question: Spring Boot - Swagger - Change default json loaded on swagger-ui

### ISSUE THREAD

**Issue by monodisco** [springfox/springfox#2291]
I am trying to change the default json that is loaded in / swagger-ui.

Basically, I have a custom swagger.json in src/main/resources and I'm trying to get this json loaded by default, however I can not get it to work.

My SwaggerConfig file is:

```java
@Configuration
@EnableSwagger2
@Import(SpringDataRestConfiguration.class)
public class SwaggerConfig  extends WebMvcConfigurationSupport{
	
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
          .select()
          .apis(RequestHandlerSelectors.any()) 
          .paths(PathSelectors.any())
          .build();
    }	
   
    @Override
    protected void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");

    }
```
I think the problem could be in the configuration or in some missing property ... could someone help me?

**Comment by dilipkrish** [comment]
You need to create your own `SwaggerResourceProvider` make it a `@Primary` bean and implement it such that it points to your swagger.json location.

**Comment by monodisco** [comment]
Thanks for the approach. I have implemented the SwaggerResourcesProvider but I still have problems when loading the json in swagger-ui:

`    @Primary
    @Bean
    public SwaggerResourcesProvider swaggerResourcesProvider(InMemorySwaggerResourcesProvider defaultResourcesProvider) {
        return () -> {
            SwaggerResource wsResource = new SwaggerResource();
            wsResource.setName("ws endpoints");
            wsResource.setSwaggerVersion("2.0");
            wsResource.setLocation("/config/swagger.json");

            List<SwaggerResource> resources = new ArrayList<>(defaultResourcesProvider.get());
            resources.add(wsResource);
            return resources;
        };
    }`

The error I get in swagger-ui is "Can't read swagger JSON from http://localhost:8089/config/swagger.json"

My json is located in src/main/resources/config/swagger.json

I understand that my mistake is that I am not indicating well the location of the json, how it could indicate that the json is in src/main/resources/config/swagger.json?

**Comment by dilipkrish** [comment]
You're real close @monodisco 

If you're using spring boot and haven't customized the auto configuration of the web mvc, you dont have to do anything. Sounds like thats not your case.

You'd need to register a resource handler similar [to this](http://springfox.github.io/springfox/docs/current/#q13). This so that spring knows that it can serve up the resource. For e.g. in your case it tells spring that `**/config/swagger.json` is located in `/config/swagger.json` in the class path.

**Comment by dilipkrish** [comment]
Try changing your SwaggerConfig.java file to

```java
@Configuration
@EnableSwagger2
@Import(SpringDataRestConfiguration.class)
public class SwaggerConfig  {
	
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
          .select()          
          .apis(RequestHandlerSelectors.any()) 
          //.paths(matchPathRegex("/cars(/\\{id\\}|$)"))
          .paths(PathSelectors.any())
          .build();
    }	

    
    private static Predicate<String> matchPathRegex(final String... pathRegexs) {
        return new Predicate<String>() {
            @Override
            public boolean apply(String input) {
                for (String pathRegex : pathRegexs) {
                    if (input.matches(pathRegex)) {
                        return true;
                    }
                }
                return false;
            }
        };
    }    
}
```

**Comment by monodisco** [comment]
Doing that (removing the overrrided addResorceHandler method from my SwaggerConfig) the URL's / swagger-ui and / v2 / api-docs are no longer mapped:

![image](https://user-images.githubusercontent.com/12752411/37331727-0413f0b0-26a5-11e8-89a0-d923b0e95e87.png)

So that seems not to solve the problem :(

**Comment by dilipkrish** [comment]
Hmmm, it appears like you have a request mapping that is handling your root (`/`) endpoint... Do you have a controller like this 👇 

```java
@RestController
@RequestMapping("/") //<----- like this
class SomeController {}
```

**Comment by monodisco** [comment]
My CarController is like this:

```java
@RepositoryRestController
public class CarController {

	
	@Autowired
	private CarRepository carRepository;
	
	@RequestMapping(value = "/cars", method = RequestMethod.POST)
	public ResponseEntity<Car> createCar(@RequestBody @Valid Car car) {
		
		carRepository.updatePreviousDefault(car.getIdCar());
		
		return new ResponseEntity<>(carRepository.save(car), HttpStatus.CREATED);
	}
}
```

I'm using @RepositoryRestController to take advantage of Spring Data REST’s settings, message converters, exception handling...

I'm not using a "global" @RequestMapping("/cars") because that RequestMapping generates conflicts with CRUD.

**Comment by dilipkrish** [comment]
I've created a PR https://github.com/monodisco/spring-boot-springfox-custom-json-at-swagger-ui/pull/1 it should work now.

**Comment by monodisco** [comment]
Yes! works perfectly now! thanks for the help @dilipkrish

I hope [this example](https://github.com/dilipkrish/spring-boot-springfox-custom-json-at-swagger-ui) can help other people.

**Comment by sourjya123** [comment]
Hi, I have a controller which accepts request body as string. Later I convert that string to the particular object using object mapper. Now when I start the application I can see only string in example on swagger ui. If I want the exact object structure in the example , then how to put that in swagger. Note in the service class I convert the string to employee object class. Please let me know how to put the employee structure in swagger ui
