### ISSUE TITLE
Seeing cookies array as query parameters in generated JSON.

### ISSUE THREAD

**Issue by LethiferousMoose** [springfox/springfox#2295]
- [x] What version of the library are you using? 2.8.0

What kind of issue is this?
 - [x] Question.

I've been trying to integrate SpringFox with a Spring MVC application, I've declared my bean as the following:
```java
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }
```

After navigating to the /swagger-ui.html path, I am seeing the following listed as query parameters for all my defined endpoints:
![cookies](https://user-images.githubusercontent.com/24547864/37305568-e165d724-2602-11e8-986a-81aa05416944.png)

I didn't see anything in the documentation or online explaining why this is getting generated or how to turn it off. These are not query parameters accepted by my services. The only thing I saw that mentioned cookies was #1345 which talks about cookies/headers being implicit.

**Comment by LethiferousMoose** [comment]
I believe I figured it out, it appears to be expanding an parameter I pass in the holds cookie data. I'll read over the documentation to figure out how to exclude it.

**Comment by LethiferousMoose** [comment]
I figured it out, it appears to be expanding an parameter I pass in the holds cookie data. I fixed it by adding an ignoredParameterTypes() call on my docket builder. Closing this issue.

**Comment by dilipkrish** [comment]
@LethiferousMoose great! the best kinds of issues :)
