### ISSUE TITLE
@RequestParam field with default value "" (empty string) is marked required

### ISSUE THREAD

**Issue by Mumi-aboaya** [springfox/springfox#2296]
Taken from the documentation:

> String org.springframework.web.bind.annotation.RequestParam.defaultValue() : 
> "\n\t\t\n\t\t\n\uE000\uE001\uE002\n\t\t\t\t\n"
> The default value to use as a fallback when the request parameter is not provided or has an empty value.  Supplying a default value **implicitly sets required to false**.

Pull request #782 does solve some of the problem mentioned in #778 
Basically the code in #782 should be changed from:
` boolean missingDefaultValue = ValueConstants.DEFAULT_NONE.equals(defaultValue) || (defaultValue == null || defaultValue.length() == 0);`

to:
` boolean missingDefaultValue = ValueConstants.DEFAULT_NONE.equals(defaultValue);`

Anything other than **ValueConstants.DEFAULT_NONE** should be considered set by code, hence required should be set to false.

**Comment by dilipkrish** [comment]
Fixed via #2276
