### ISSUE TITLE
Swagger-ui web jar is not producing the artifact correctly

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#2309]
From https://github.com/springfox/springfox/issues/2281#issuecomment-372806807 Thanks @rstmm

After upgrading to 2.8.1-SNAPSHOT I also see a 404 for swagger-ui.html.

So this works:
http://localhost:8080/xxxx/publicapi/v2/api-docs

And this does not work anymore (404), although it used to work before jumping to 2.8.1-SNAPSHOT. I was on 2.7.0 before:
http://localhost:8080/xxxx/publicapi/swagger-ui.html
Adding it like this to my project which I did not change:
```
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry)
    {
        registry.addResourceHandler("swagger-ui.html")
            .addResourceLocations("classpath:/META-INF/resources/");
           
        registry.addResourceHandler("/webjars/**")
            .addResourceLocations("classpath:/META-INF/resources/webjars/");
        
        super.addResourceHandlers(registry);
    }
```
I guess it might be the same as @arnabguptadev  is experiencing right now.

edit: I figured out why but I am not sure how to solve:
The springfox-swagger-ui.jar in latest snapshot versions is almost empty, only a MANIFEST.MF file in it. 
While the filesize in 2.7.0 (http://oss.jfrog.org/simple/oss-snapshot-local/io/springfox/springfox-swagger-ui/2.7.0-SNAPSHOT/) was 413.72 KB in latest version, and in 2.7.1 it was 4.12 MB, it decreased to 454 bytes starting with 2.8.0 and never recovered (see http://oss.jfrog.org/simple/oss-snapshot-local/io/springfox/springfox-swagger-ui/2.8.1-SNAPSHOT/).

Is there some build failure?

**Comment by rstmm** [comment]
I can confirm its working now. Thanks a lot!
