### ISSUE TITLE
Getting regex failure when running checkStyle

### ISSUE THREAD

**Issue by dangoslen** [springfox/springfox#2310]
- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

    I'm using the latest from master for development.

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

    Question about `./gradleW check`

Hey team. I've been working on some code for an older feature request my team would like to see in this project, but I'm running into a check-style problem that I haven't been able to solve.

I've created a new class, and the class header comment block was generated that _seems_ to match the comment block on other files. However, the checkstyle fails with the following error:
```
3: Line does not match expected header line of '^\Q *  Copyright \E(20\d\d\-)?20\d\d\Q the original author or authors.\E$'. [RegexpHeader]
```

The comment block is attached is below.
```
/*
 *
 * Copyright 2018 the original author or authors.
 *
... 
```

What is funny is that I have even tried copying and pasting the line from another file to just see if it passes the checkstyle, but to no avail.

Any thoughts?

**Comment by dilipkrish** [comment]
Sorry this is a primitive way to enforce a copyright header. Seems like it should work if you copy it from another file. Im not entirely sure. The checkstyle version used is the one bundled with gradle.

**Comment by dangoslen** [comment]
Yeah... I hadn't been able to get it to pass. I was able to get it to work eventually, but I had to try a few different header comment blocks before finding one that passed.

All good now.
