### ISSUE TITLE
Swagger 2.8.0 not working on IE11

### ISSUE THREAD

**Issue by Snina88** [springfox/springfox#2315]
I use swagger 2.8.0, it works on Chrome and FireFox but on IE11 I have the errors:
HTML1300: Une navigation s’est produite.
Fichier : swagger-ui.html
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : swagger-ui.html, ligne : 41, colonne : 7
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : swagger-ui.html, ligne : 45, colonne : 7
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : swagger-ui.html, ligne : 49, colonne : 7
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : swagger-ui.html, ligne : 53, colonne : 7
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : swagger-ui.html, ligne : 58, colonne : 7
SCRIPT1002: Erreur de syntaxe
Fichier : springfox.js, ligne : 1, colonne : 20

**Comment by dilipkrish** [comment]
Duplicate of #2283
