### ISSUE TITLE
Swagger support when wrap handler response with generic type

### ISSUE THREAD

**Issue by tienducitt** [springfox/springfox#2317]
Hi, I am learning to build a RESTful service using spring boot with springfox-swagger2 2.6.1

I have a handler which return User
```java
@GetMapping(value = "{userId}")
    public User get(@PathVariable int userId) {}
```

And it will wrap the handler response to a generic type called Response by using ResponseBodyAdvice
Response.java
```java
class Response<T> {

    private HttpStatus status;
    private T data;
}
```

ResponseBodyAdvice.java::beforeBodyWrite
```java
        if (!serverHttpRequest.getURI().getPath().startsWith("/v1/")
                || body instanceof Response) {
            return body;
        }

        return ResponseFactory.success(body);
```

My question is, how can I tell swagger to render Response type, I read some question and I think I should add an alternateTypeRules like this:
```java
               .alternateTypeRules(AlternateTypeRules.newRule(
                        // replace any T
                        typeResolver.resolve(WildcardType.class),
                        // with Response<T> of T
                        typeResolver.resolve(Response.class, WildcardType.class)
                ))
```
But it didn't work. Can somebody help me out, you can find my code here: [https://github.com/tienducitt/restful-service](url)

Thanks for your help!

**Comment by dilipkrish** [comment]
You have an interesting problem. We usually use alternate type rules to strip type information, 
i.e. `ResponseEntity<T>` => `T`
but in your case you want to add information, which is the exact opposite. Let me think about it and get back

**Comment by tienducitt** [comment]
My case is:
From the front-end requirement, all the response should be wrapped in the structure like Response<T>.
And from the back-end aspect, I would like to have clean handlers syntax, so that why I would like to return T instead of Response<T>.

And thank you, I looking forward to hearing from you.

**Comment by dilipkrish** [comment]
This is not very easy to do as you'd like it unfortunately. If you use your rule, you'd end up with wrapped models for even child properties.

**Comment by mobi-robert** [comment]
Hey there, I am also interested in this. Is support for these kind of wrapping situations planned? Could this be something that can be implemented by a newcomer in a reasonable timeframe?

**Comment by ptheohar** [comment]
Hey, I have the same wrapper 'data' in my Response object. I cannot find a way to tell swagger that my return object is actually nested in the top level object  'data'

**Comment by jpomykala** [comment]
Hey,
if somebody is also struggling with simmilar issue. I can recommend my library for that. You can enable response wrapping by @EnableResponseWrapping annotation and it works with SpringFox.
@ptheohar In my case suggested solution with TypeResolver also didn't work. 😭 

https://github.com/jpomykala/spring-higher-order-components

**Comment by phlppnhllngr** [comment]
This would be practical for use with Spring's ResponseBodyAdvice.

**Comment by christmagro** [comment]
Any Updates on this?

**Comment by liangjiezhu** [comment]
use spring ResponseBodyAdvice and set @RestControllerAdvice(basePackages = {"org.my.pkg"})
