### ISSUE TITLE
SpringFox 2.8.0 Error: "Could not resolve pointer: /definitions/String"

### ISSUE THREAD

**Issue by mrgrew** [springfox/springfox#2320]
The example application linked below has a `String` for `@RequestBody`. The application displays an error with SpringFox 2.8.0 and works as expected with SpringFox 2.7.0.

### How to reproduce:

1. Clone https://github.com/mrgrew/request-body-bug
1. Start application via `mvnw spring-boot:run`
1. Open URL http://localhost:8080/swagger-ui.html
1. An error about not resolving pointer /definitions/String is displayed
1. Change the pom.xml `springfox.version` to `2.7.0` and run again.
1. No error will be displayed. (You may need to hard-refresh the browser)

**Comment by dilipkrish** [comment]
I think this may be fixed in `2.8.1-SNAPSHOT` but I'll investigate

**Comment by mrgrew** [comment]
You're right @dilipkrish , the problem doesn't exist in `2.8.1-SNAPSHOT`. I created branch [2.8.1-SNAPSHOT](https://github.com/mrgrew/request-body-bug/tree/2.8.1-SNAPSHOT) that works as expected!

Thanks for the feedback!
