### ISSUE TITLE
Keep generated JSON in project

### ISSUE THREAD

**Issue by ghost** [springfox/springfox#2325]
i'am use springfox to generated documentation it's perfect , but i don't want to get this file through  request http://localhost:8080/v2/api-docs then save it , there are a way to keep this file in building time ? if it's not possible what is other suggest ?

**Comment by dilipkrish** [comment]
My recommendation is to use [swagger2markup](https://github.com/Swagger2Markup/swagger2markup). Here is a demo of [how to use it](https://github.com/Swagger2Markup/spring-swagger2markup-demo). It uses springfox, however it os active only when running tests and saves it part of the resources in the artifact.

**Comment by bondpp7** [comment]
That example is using springfox 1.5.0; is there an example that works with the latest springfox?

**Comment by dilipkrish** [comment]
You'd have to ask that project to update the instructions for 2.8.0. However I would posit that its the same.

**Comment by bondpp7** [comment]
Yes, I did add a question there (https://github.com/Swagger2Markup/spring-swagger2markup-demo/issues/20), but I noticed that the instructions are relying upon `systemProperty 'io.springfox.staticdocs.outputDir'`, which to my knowledge, has been deprecated/removed in 2.8.0

**Comment by dilipkrish** [comment]
Ah I see... unfortunately the project diverged @ 2.5.0 because of java 8 support.

**Comment by bondpp7** [comment]
It would be wonderful if SpringFox maintained some means of (optionally?) saving the generated json.  It would make using third party tools much easier.  Yes, I did manage to get the output by capturing it via a test, but I also use custom groups (the drop-downs in swagger-ui), so I end up generating multiple files and then having to glue them back together.

**Comment by dilipkrish** [comment]
Thats a great idea!

**Comment by sandyscoffable** [comment]
:+1: for an option to generate the JSON at compile time. 

We've been using SpringFox since 2.6.0 but we'd really like a way to automate the generation of client API libraries before the application is deployed.

**Comment by bastianleirpo** [comment]
Hi there,
why was this issue closed and added to 2.9.0, even when it was not included in 2.9.0. Or am I missing something?
