### ISSUE TITLE
403 error on accessing swagger ui - spring boot 2.0 springfox-swagger2 (2.7.0,2.6.0,2.6.1)

### ISSUE THREAD

**Issue by dushyanthbn** [springfox/springfox#2326]
Please find below the pom dependency

```xml
<dependency>
<groupId>io.springfox</groupId>
<artifactId>springfox-swagger2</artifactId>
<version>2.6.1</version>
			<exclusions>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-annotations</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.6.1</version>
		</dependency>
```
tried version 2.7.0, 2.6.1

security has been bypassed for swagger
http.authorizeRequests().antMatchers("/v2/api-docs", "/configuration/ui", "/swagger-resources", "/configuration/security", "/swagger-ui.html", "/webjars/**").permitAll();

it was working fine with spring boot 1.3
after upgrading to 2.0 facing 403 error

What kind of issue is this?

 - There was an unexpected error accessing swagger-ui(type=Forbidden, status=403).
   Access Denied

**Comment by dilipkrish** [comment]
First off update to 2.8.0

Secondly, [the docs](https://github.com/springfox/springfox/tree/master/docs/asciidoc) should provide instructions.

**Comment by dushyanthbn** [comment]
I Tried 2.8.0 as well getting same 403 error.
There was an unexpected error (type=Forbidden, status=403).
Access Denied

**Comment by sivadinesh1** [comment]
> in the documentation

This solution worked +1

**Comment by orwtech** [comment]
Can only get this to work if I add @EnableSwagger2 just below 
@SpringBootApplication
Then it works out of the box

But putting @EnableSwagger2 in a config class below @Configuration gives this error
Not sure why this is?

**Comment by EvgeniyOstapenko** [comment]
> Can only get this to work if I add @EnableSwagger2 just below
> @SpringBootApplication
> Then it works out of the box
> 
> But putting @EnableSwagger2 in a config class below @configuration gives this error
> Not sure why this is?

thanks
