### ISSUE TITLE
Select spec using a query param in swagger-ui.html

### ISSUE THREAD

**Issue by mikexliu** [springfox/springfox#2327]
Posted this in Gitter already. I've used springfox for a while now (really great project), but I was looking to see if I could select a spec ahead of time using a query param. For example, using this url: `/swagger-ui.html?spec=springboot` would select the `springboot` group while `/swagger-ui.html?spec=custom_spec` would select the `custom_spec` group.

This would be a great nice to have and probably not too difficult to implement (I might get around to doing a PR myself but haven't had much time lately).

**Comment by dilipkrish** [comment]
Thanks @mikexliu!

**Comment by dilipkrish** [comment]
🔔

**Comment by mikexliu** [comment]
What does that mean?

**Comment by dilipkrish** [comment]
Just a ping to see if you’re still up for a PR, it would be much appreciated. 😀

**Comment by mikexliu** [comment]
I'm not very good with javascript. I'm pretty sure if I submitted a PR, it would just need to be redone.. should be a simple addition to `springfox.js` right?

**Comment by dilipkrish** [comment]
@mikexliu Im on the same boat, so don't be afraid to take a shot.

**Comment by rukgar** [comment]
I would love that feature too

**Comment by mikexliu** [comment]
@dilipkrish @rukgar 
Sorry, I actually did give this a try a month back but couldn't figure it out. Can anyone else give it a try? This shouldn't be hard if I could devote more time to javascript.

**Comment by stephanpieterse** [comment]
I stumbled across this issue recently while we were trying to achieve something similar, I found that we could use the the `urls.primaryName` query parameter to achieve this behaviour.
The full url would then look like
http://ourserver.company.com/swagger-ui.html?urls.primaryName=our-pos-services#/pos-controller/queryOrderUsingGET

The documentation is at https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

Hopefully this helps someone, I'm not sure if we were trying to do same thing?
