### ISSUE TITLE
publishing 2.2.2 meet a problem

### ISSUE THREAD

**Issue by zhaojigang** [springfox/springfox#2335]
I have executed the following code:
git checkout -b jg222 2.2.2

then I use IDEA: publishToMavenLocal
![image](https://user-images.githubusercontent.com/14085645/38127417-9d7f399a-3428-11e8-87be-c8ab8ba2e18b.png)

then I find springfox-swagger2's version is 2.2.3 (I'm not familiar with gradle, I can easily find a place to set the version from 2.7.0, but can't from 2.2.2, where can I set a version number)
![image](https://user-images.githubusercontent.com/14085645/38127476-d61406e6-3428-11e8-9df7-27ff01fe2d3e.png)

then I import the generated jar to the springboot project
![image](https://user-images.githubusercontent.com/14085645/38127876-a6f1141a-342a-11e8-8b21-242439bb6acd.png)

then when I start the project, error appeared:
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'swaggerParameterDescriptionReader' for bean class [springfox.documentation.swagger.readers.parameter.ParameterDescriptionReader] conflicts with existing, non-compatible bean definition of same name and class [springfox.documentation.swagger.readers.parameter.ApiParamParameterBuilder]

Sorry,My English is very poor...

**Comment by dilipkrish** [comment]
@zhaojigang Not a problem. Why are you trying to publish 2.2.2/3? Why not use 2.8.0

**Comment by zhaojigang** [comment]
The spring'version of my project is too low, and it is difficult to upgrade it. when i use 2.7.0, there are some method of spring can't find, so I use 2.2.2

**Comment by zhaojigang** [comment]
I upgrade spring version of my project, and i use 2.7.0. then I perform the operation as above，the same error occur. but in springfox2.7.0, i can't find springfox.documentation.swagger.readers.parameter.ParameterDescriptionReader this class, why it can compile into springfox-swagger-common project

**Comment by dilipkrish** [comment]
Why not use 2.8.0 instead? thats the latest version. Not sure why you're seeing this error.

**Comment by zhaojigang** [comment]
Thanks. I use 2.7.0 because I perfer the UI style of 2.7.0. 
And I find that error is caused by maven compile.
I closed this issue.
