### ISSUE TITLE
Web-services with path-parameters not getting displayed on SwaggerUI in 2.8.1-SNAPSHOT

### ISSUE THREAD

**Issue by maheshm2195** [springfox/springfox#2341]
Hey @dilipkrish  !
Hope you're doing good.

Faced an issue when I shifted to 2.8.1-SNAPSHOT from 2.8.0.
All the webservices that had path-params are not showing up in the UI now. One implemented example is as below:
`@ApiImplicitParam(name = "id", value = "id for the record", required = true, dataType = "string", paramType = "path")`

My request-mapping looks like this:
`@RequestMapping(value = "/getDetails/{id}", method = RequestMethod.GET)` where id is the path-variable.

They were visible in 2.8.0 UI but they've disappeared now.
Any help would be really great!

**Comment by dilipkrish** [comment]
What about the method signature?

**Comment by maheshm2195** [comment]
@dilipkrish  Hope this helps

`@ResponseBody
	public ModelAndView getDetails(@PathVariable("id") final String identifier, final HttpServletResponse resp, final HttpServletRequest req) {

//code
                              return new ModelAndView("root", "object", rootElement);
	}
	`

**Comment by maheshm2195** [comment]
@dilipkrish Hey!
Please let me know about the above as we're looking forward to shipping a release and this issue is becoming a blocker.
Thanks!

**Comment by maheshm2195** [comment]
@dilipkrish Hello.

Hope you're doing good.
I didn't have `enableUrlTemplating ` enabled in my Docket so I did now but it still doesn't work. I also checked if I had multiple endpoints with same path but that isn't the case either.

I tried your solution, here's my Docket:

`@Bean public Docket api() { return new Docket(DocumentationType.SWAGGER_2).apiInfo(getAPIInfo()).useDefaultResponseMessages(false).pathMapping("/").enableUrlTemplating(true). securitySchemes(getSecurityScheme()).securityContexts(securityContext()).select() .apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class)).build(); }`

Let me know if you've any other guess.

**Comment by dilipkrish** [comment]
If thats not the cause, then try looking in the logs for clues. Im out of ideas. You may want to try reproducing this using the [the demos](https://github.com/springfox/springfox-demos) project.

**Comment by maheshm2195** [comment]
@dilipkrish Hey

I checked the sample projects but no help. I'm not experiencing this issue in 2.8.0 and only happens in 2.8.1-SNAPSHOT. Configurations are kept the same too.

**Comment by dilipkrish** [comment]
All things equal, could you see what the diff is when you navigate to `http://localhost:8080/v2/api-docs` with 2.8.0 and with 2.8.1-SNAPSHOT? Otherwise, nothing else I can think of, other than if you can share your  repository or some minimal copy of it that demonstrates the problem.

**Comment by maheshm2195** [comment]
I've already analysed `http://localhost:8080/v2/api-docs` and found that the APIs with path-parameter are missing.
I'm afraid I can't share the repository because it is a client project :-(

When I pulled the latest 2.8.1-SNAPSHOT I experienced other issues too. I guess there is some on-going code change that is causing my problem.
Any idea by when it'll be released on maven ?

**Comment by dilipkrish** [comment]
Im out of ideas, sorry. The only thing I would try is to update dependencies if you're using maven try `mvn -U....` gradle has ways to do that as well, but it appears yr using maven. Doesnt sound like a release will help, but I plan to release it this coming weekend.

**Comment by maheshm2195** [comment]
Sure. I'll try this too. Will wait for it to release and report back with whatever I can achieve. 

Thanks for the effort :)
