### ISSUE TITLE
Parameter.vendorExtensions doesn't show up in generated API(/v2/api-docs)

### ISSUE THREAD

**Issue by RisenZhong** [springfox/springfox#2347]
Version: 2.8.0
I want to add an attribute to springfox.documentation.service.Parameter , so I follow the [example-parameterbuilderplugin](http://springfox.github.io/springfox/docs/current/#example-parameterbuilderplugin) to add a plugin and save the attribute into Parameter.vendorExtensions.     
But the generated Json doesn't include this attribute.

![1](https://user-images.githubusercontent.com/21530821/38455017-4810188a-3aa4-11e8-9345-07e162a36f1c.PNG)

 It seems that It's ignored in following method when mapping the data:

![2018-04-07_20-37-08](https://user-images.githubusercontent.com/21530821/38454960-802f06f0-3aa3-11e8-94c5-bc89075f1438.PNG)

Do I have any trick to show this attribute in  generated API?

**Comment by dilipkrish** [comment]
@RisenZhong sounds like a bug. Thanks for reporting.
