### ISSUE TITLE
Add provision to mention Authorization Header using `SwaggerResourcesProvider`

### ISSUE THREAD

**Issue by ghsatpute** [springfox/springfox#2348]
## What version of the library are you using? Is it the latest version?

Maven SpringFox 2.6.1

## What kind of issue is this?

- [x]  Question.  
- [ ]  Bug
- [ ]  Feature Request

## Question details 

I've created a Gateway Proxy using Zuul. Gateway passes these requests to other microservices. I've aggregated swagger documents from all microservices on gateway proxy. 

```
@Component
@Primary
@EnableAutoConfiguration
public class SwaggerAggregatorController implements SwaggerResourcesProvider {
    @Override
    public List<SwaggerResource> get() {
        List<SwaggerResource> resources= new ArrayList<>();

        SwaggerResource cstSwagger = new SwaggerResource();
        cstSwagger.setName("cust-service");
        cstSwagger.setLocation("/cust/cust-service/v2/api-docs");
        cstSwagger.setSwaggerVersion("2.0");
        resources.add(cstSwagger);

        return resources;
    }
}
```

Now this works but on Swagger UI there's no way I can specify authorization header in format `bearer: <token>`.

**Comment by dilipkrish** [comment]
It should use the credentials from the browser. Thats how [jhipster](http://jhipster.tech/) does it. Take a look at that project.

**Comment by ghsatpute** [comment]
Thanks @dilipkrish for the response. I tried to look at the [code written](https://github.com/jhipster/jhipster-sample-app-gateway/blob/3c7370f73e07364bcf011ceb40f3199c23210d2f/src/main/java/io/github/jhipster/sample/config/apidoc/GatewaySwaggerResourcesProvider.java) here. 

I found the part where they are aggregating the swagger docs from different microservices but I'm unable to find the code which is used to add "Authorization Header" on Swagger UI. Could you please guide me towards that piece of code. 
Apologies for the trouble. Thanks.

**Comment by dilipkrish** [comment]
The login form puts the token in the cookies that is later used to protect the swagger ui page

**Comment by declanTreanor** [comment]
Did you get anywhere with this @ghsatpute ?

**Comment by ghsatpute** [comment]
@declanTreanor Unfortunately not. It's not very clear and the team here is not that much help regarding the documentation. 

But I've not tried the latest version (if any). Let us know if you're able to solve this so that it can help others.
