### ISSUE TITLE
swagger-ui.html in 2.8.0 contains references to 2.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by nahguam** [springfox/springfox#2357]
All links and scripts in the html contain `?v=2.8.0-SNAPSHOT` query parameter

**Comment by dilipkrish** [comment]
Seems like a bug to me 👍 thanks for reporting

**Comment by vkasarekar** [comment]
hi dilip, can i do anything in the interim? Cant get swagger to work with my spring boot app.

**Comment by dilipkrish** [comment]
@vkasarekar its not clear what this issue has to do with not working with your spring boot app.

**Comment by vkasarekar** [comment]
hi @dilipkrish , i have a very simple spring boot app. It does not have any web MVC component to it. It has a couple of REST services and some backend-kafka integration. I am trying to setup swagger.2.8.0. spring boot version: is 2.0.0. My Swagger config is very simple..Not using WebMvcConfigurationSupport.
The config looks like this
'@Configuration
@EnableSwagger2
public class SwaggerConfig { 
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()                 
                .apis(RequestHandlerSelectors.basePackage("com.cartera.dig"))
                .paths(regex("/dig.*"))
                .build();    
    }
}'
http://localhost:8080/v2/api-docs loads up.
But http://localhost:8080/swagger-ui.html/ does not load up. looking at the javascript console, see a bunch of errors: GET http://localhost:8080/swagger-ui.html/webjars/springfox-swagger-ui/swagger-ui.css?v=2.8.0-SNAPSHOT net::ERR_ABORTED
So i am speculating #2357 has got to do with this.

Can you help?

-Vaidehi

**Comment by dilipkrish** [comment]
@vkasarekar spring boot 2 is not officially supported. Also if it is working it would be only the aspects that are web mvc that will work.

**Comment by vkasarekar** [comment]
oh ok. thank you. do you know when will it be supported?

**Comment by dilipkrish** [comment]
In the next (3.0) release
