### ISSUE TITLE
how to  modify swagger-ui  /src/*  to make them happen？ 

### ISSUE THREAD

**Issue by JavaBingo** [springfox/springfox#2359]
I download latest code from  https://github.com/swagger-api/swagger-ui and modife the .jsx file in the path "swagger-ui-master\src\core\components\auth" .
How  to make this work.？ I try it that run deploy.sh, but nothing happen in the "/dist"  .
![image](https://user-images.githubusercontent.com/38209293/38777272-c842f106-40d7-11e8-9ff3-c4ed04b1f7d1.png)

how to  modify /src/*  to make them happen？ thanks .

**Comment by dilipkrish** [comment]
You need to follow [instructions in the swagger-ui project](https://github.com/swagger-api/swagger-ui/blob/master/docs/development/setting-up.md) @JavaBingo

**Comment by JavaBingo** [comment]
@dilipkrish  Follow your advice and execute it successfully. thanks!  and I run ”npm run build -dist“  the /src file is generated in the /dist.thank you every much.
