### ISSUE TITLE
SwaggerUI auto detect property type with wrong example value

### ISSUE THREAD

**Issue by gaozhe3321** [springfox/springfox#2363]
Here is the code.Notice the example value
In SwaggerUI,this example value change to 32000019740422281100 and its datatype is Long not String
	
```java
@ApiModelProperty(position = 9,value = "IdentityID",required = true,example = "320000197404222811 ",dataType = "string")
public String getLegalID() {
	return LegalID;
}
```

**Comment by dilipkrish** [comment]
If its a string you need to quote it `example="'320000197404222811'"`
