### ISSUE TITLE
Define custom formats with ApiModelProperty and ApiParam

### ISSUE THREAD

**Issue by thecomputerguyjeff** [springfox/springfox#2366]
- [x] What version of the library are you using? 
2.8.0

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? - Yes

We are trying to specify format in ApiParam. We see that it supports the field. When swagger is generated, the format field is not present. 

```
@ApiParam(
    value = "Example: 12345678-1234-1234-1234-123456789012", 
    required = true, 
    allowEmptyValue = false, 
    format = "testFormat")
@Size(min=36, max=36)
@RequestParam(value = "correlationID") String correlationID)
```

generates

```
{
    name: "correlationID",
    in: "query",
    description: "Example: 12345678-1234-1234-1234-123456789012",
    required: true,
    type: "string",
    maximum: 36,
    minimum: 36,
}
```

We also want to add custom formats to ApiModelProperty, but it does not appear to support the format field. Is that a potential feature that can be added, or is there a work-around for this?

**Comment by dilipkrish** [comment]
Yes it was only added in 1.5.11 of swagger-core. I'll see if I can add it before releasing 2.9

**Comment by kann181** [comment]
What about ApiModelProperty ?. It still doesn't seem to have. Is there any workaround for it?

**Comment by kann181** [comment]
password field should have the format as a password so that the swagger UI will not show the password typed. How can this be achieved?

**Comment by dilipkrish** [comment]
@kann181 this can be achieved by using an appropriate security mechanism like api key or oauth.

**Comment by sag1** [comment]
I don't want to show the password in clear text. Swagger ui annotations provides this functionality using @ApiParam(value = "Password", type = "string", format = "password")

When it will be corrected ?

**Comment by dilipkrish** [comment]
When this feature is implemented I suppose

**Comment by moezubair** [comment]
Hi
Is there any update on this? Has anyone been able to achieve this?

**Comment by tschmidt01** [comment]
Any ETA on this?

**Comment by Rajan2212** [comment]
How to add below lines in the json file using swagger annotation ? which annotation should be used ?

{
"type": "string",
"format": "password"
}

I am not able to get proper answer till now...is only by manual way we can achieved this ?
