### ISSUE TITLE
How to hidden modelproperties in specific http method?

### ISSUE THREAD

**Issue by shinji3887** [springfox/springfox#2375]
I use spring boot with swagger2  to create api docs and I use @ApiModelProperty(hidden=true) to hidden some properties and it works.Now I want to hidden some properties in **specific http methods**(like POST or PATCH) and not to hidden in GET method,is there any way to do this?thx a lot!

**Comment by dilipkrish** [comment]
Currently you cannot do it by method. Also there is currently an effort to be able to do that that will be part of the next release

**Comment by shinji3887** [comment]
@dilipkrish thank you！I‘m looking foward to the next release
