### ISSUE TITLE
how to design requestbody for header type parameters

### ISSUE THREAD

**Issue by kritika0205** [springfox/springfox#2380]
I have the following post request, how can I design the requestbody for the header type parameters

Authenticate API info:
/authenticate
request.ContentType = "application/json";
request.Headers.Add("X-username", userName);
request.Headers.Add("X-Password", password);

**Comment by kritika0205** [comment]
It is token based authentication, please help..

**Comment by dilipkrish** [comment]
Sounds like you need to define headers for all your operations. One easy way to do it is to use `Docket#globalParameters` or alternatively you can define `@ApiImplicitParams` for your authentication headers

**Comment by kritika0205** [comment]
Hi, thanks for the reply, in swagger 2.0 it would be easy just by adding 

-in: header  for both of them, but how to add the same in swagger 3.0.0 where we have request body for the post request @dilipkrish

**Comment by dilipkrish** [comment]
I dont understand your question. Springfox doesnt support swagger/OAS 3.0 yet.
