### ISSUE TITLE
Swagger 2.0 reusable parameters supported?

### ISSUE THREAD

**Issue by smitalm** [springfox/springfox#2384]
Version 2.9.0.
Question.

Swagger 2.0 supports [reusable parameters](https://github.com/OAI/OpenAPI-Specification/blob/master/fixtures/v2.0/json/resources/reusableParameters.json):

They are defined at top level:

  ```
"parameters": {
    "skipParam": {
      "name": "skip",
      "in": "query",
      "description": "number of items to skip",
      "required": true,
      "type": "integer",
      "format": "int32"
    },
    "limitParam": {
      "name": "limit",
      "in": "query",
      "description": "max records to return",
      "required": true,
      "type": "integer",
      "format": "int32"
    }
  },
```

And they can be reused (referenced) in multiple operations:
```
  "paths": {
    "/pets/{id}": {
      "get": {
        "description": "Returns pets based on ID",
        "summary": "Find pets by ID",
        "operationId": "getPetsById",
        "parameters": [
          { "$ref": "#/parameters/skipParam" },
          { "$ref": "#/parameters/limitParam" }
        ],
      }
    }
  }, 
```

Since i have lot parameters reused for multiple operations, this feature would save a lot of repetition in documenting these common parameters.  

**Does _springfox-swagger2_ support this feature? If yes, how?**

PS: I know springfox has feature `Docket.globalOperationParameters` but it duplicates parameters for each operation in resulting api-docs JSON, instead of using $ref. And it also cannot be used. Also, `globalOperationParameters` is unusable, if only several, but not all operations have the parameter.

**Comment by smitalm** [comment]
Short answer is that this isnt supported, as it would go against goals of springfox project. 
For more details, see question on [stackoverflow](https://stackoverflow.com/questions/50037744/using-swagger-2-0-reusable-parameters-with-springfox) that is commented on by @dilipkrish. 

Closing the issue.

**Comment by dilipkrish** [comment]
@smitalm Just to clarify, when you use request and response bodies, it is implicitly reused. For e.g. if you have an endpoint

```
Customer get(id)
void update(Customer)
```

It is implicitly reused in the schema. The reuse that isn't currently possible, that I can see some value in is reusing sets of scalar request params e.g. Paging parameters.

```
List<Customer> findCustomers(criteria, current, offset, pagesize)
List<Order> find0rders(criteria, current, offset, pagesize)
```

In anycase, since its generated by code it shouldn't matter, unless you want that level of reuse in client code generation.
