### ISSUE TITLE
How to rename the property

### ISSUE THREAD

**Issue by codebusta** [springfox/springfox#2391]
I have the following class
```
public class PackageCustomerFilter {
    @ApiModelProperty(name = "from_country_id", position = 1, required = true)
    private Long fromCountryId;

    public Long getFromCountryId() {
        return fromCountryId;
    }

    public void setFromCountryId(Long fromCountryId) {
        this.fromCountryId = fromCountryId;
    }
}
```

This my API:
```
@RequestMapping(value = "/api/v2/admin/packages/pricing", method = RequestMethod.POST)
public ResponseEntity<JSend<Void>> getPackagePrices(@Valid @ModelAttribute PackageCustomerFilter packageCustomerFilter) {
    return new ResponseEntity<>(JSend.success(Void), HttpStatus.OK);
}
```

The Swagger UI shows the API as I expected (the parameter is shown as "from_country_id") but when i provide the value and call the following request:

http://localhost:8080/api/v2/packages/prices?from_country_id=1

In the server, i still do NOT get this value 1, it is null. What is done wrong here?

But when I call this:

http://localhost:8080/api/v2/packages/prices?fromCountryId=1

In the server, i DO get this value 1

I'm using springfox version 2.9.0 with spring boot version 2.0.1.RELEASE

**Comment by codebusta** [comment]
Actually, I have gone through #1937 and #1919. But still, I wasn't able to figure out the solution.

**Comment by dilipkrish** [comment]
@ApiModelProperty is an annotation that spring knows nothing about. So as such it will not know what to do with it when it receives a parameter called `from_country_id`. You need to either rename the getter/setter accordingly or add another model attribute annotation to override the name (haven't tried this out, but Im hoping it works).

```
public class PackageCustomerFilter {
    @ApiModelProperty(name = "from_country_id", position = 1, required = true)
    @ModelAttribute("from_country_id")
    private Long fromCountryId;

    public Long getFromCountryId() {
        return fromCountryId;
    }

    public void setFromCountryId(Long fromCountryId) {
        this.fromCountryId = fromCountryId;
    }
}
```

**Comment by codebusta** [comment]
Thank you for your response, I also tried you suggestion related to @ModelAttribute, but this annotation is not designed to be used in fields nor methods. It is accepted only as an annotation for a method's parameters. 

The only way i made it work is by renaming my setter as following:
```
public void setFrom_country_id(Long fromCountryId) {
     this.fromCountryId = fromCountryId;
}
```
This is not compliant with Java method naming conventions and this is bugging me.

**Comment by dilipkrish** [comment]
You might also try adding the `@ApiModelProperty` to the getter/setter or `@ApiParam` to the field instead. Depends on your configuration you may need to experiment a bit.

**Comment by bthulu** [comment]
2.9.2 not work
`
	@ApiModelProperty(value = "生产排程订单id", name = "orderId")
	@JSONField(name = "orderId")
	private String id;
`
swagger-ui.html still shows id
`
{
  "code": "string",
  "data": {
    "rows": [
      {
        "customerName": "string",
        "fineQty": 0,
        "finishTime": "2018-08-31T09:42:03.411Z",
        "id": "string",
        "length": 0,
        "material": "string",
        "qty": 0,
        "saleOrderQty": 0,
        "sn": 0,
        "spec": "string",
        "stackerQty": 0,
        "width": 0
      }
    ],
    "total": 0
  },
  "msg": "string",
  "ok": true,
  "status": "string"
}
`

**Comment by dilipkrish** [comment]
@bthulu not sure, could you create a breaking test like [the commit above](url
https://github.com/springfox/springfox/commit/e0d128c0bd71717ec77b0aaf3ba6baba4fc406d6)

**Comment by bthulu** [comment]
@dilipkrish if the model is used for paramters in(like Query) , then it's ok, but for return value(like User), ApiModelProperty(name = "xxx") can not change field name, only annotation JsonProperty("newName") on field works. if this is not supposed, then i'll create a test.
`public User searchUsers(Query query)`

**Comment by Xzhengkai** [comment]
@ApiModelProperty(value = "ip range",name = "ip_range")
  private List<String> ipRange;
The field that Swagger expects to generate is called ip_range
actually is ipRange 
The name attribute does not take effect
