### ISSUE TITLE
add support for the showCommonExtensions configuration option of swagger-ui

### ISSUE THREAD

**Issue by guyv** [springfox/springfox#2402]
- What version of the library are you using?
2.9.0

What kind of issue is this?
 - Feature Request.
In version 3.14.0 of swagger-ui, a new configuration option was added, called showCommonExtensions (https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md). This allows formats of query parameters to be shown (https://github.com/swagger-api/swagger-ui/issues/4231 and https://github.com/swagger-api/swagger-ui/pull/4245).
In version 2.9.0 swagger-ui was bumped to 3.14 (https://github.com/springfox/springfox/commit/949fb06158a02eb38a9018fa233661d1c7e0ca51), however, no support was added for this new property...

**Comment by dilipkrish** [comment]
This is fixed via #2973
