### ISSUE TITLE
BasicAuth using @Api annotation does not work on method with Spring + Swagger2 

### ISSUE THREAD

**Issue by steffinho** [springfox/springfox#2403]
- Version: springfox-swagger2 // 2.9.0

We configured swagger the following:

```
        @Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).groupName(API_GROUP).select()
			.apis(RequestHandlerSelectors.basePackage("package.name")).build().apiInfo(
				new ApiInfo(...)
			.securitySchemes(Collections.singletonList(securityScheme()))
			.pathProvider(getPathProvider(...));
	}

	private SecurityScheme securityScheme() {
		return new BasicAuth("basicAuth");
	}
```

Annotating a Controller on class level with annotations like:

`@Api(tags = "MyName", authorizations = {@Authorization(value = "basicAuth") })`

does not enable the authentication in swagger for the whole controller with its methods. It does nothing. If we move that authorizations values within @ApiOperation method annotation it does work:

`@ApiOperation(value = "....", authorizations = {@Authorization(value = "basicAuth") })`

**Comment by steffinho** [comment]
Hi @dilipkrish Could you please have a look at this? Very important to know if it is not supported or a bug or something else... Otherwise, we need to add those annotations in a mass at all methods.

**Comment by dilipkrish** [comment]
I might be wrong here but I don't think basic auth is supported by swagger-ui for 2.0 version of the spec.

**Comment by steffinho** [comment]
@dilipkrish  But it works if the authentication schema is defined in the swagger spec. It is not if Api annotation is used with springfox but it is with ApiOperation....

**Comment by dilipkrish** [comment]
Oh now I see what you were trying to report. Let me look at it. Thanks for clarifying.

**Comment by steffinho** [comment]
Hi @dilipkrish any updates on this? Did you find something?

**Comment by senthilprabhut** [comment]
I'm using springfox swagger2 version 2.8.0
I do run into the same issue - if "authorizations" is defined in @ApiOperation, basic auth works in swagger ui
But when defined in @Api annotation (at controller level), basic auth doesn't work and the browser brings up the username/password popup

**Comment by dilipkrish** [comment]
@steffinho The authorization attribute in `@Api` is not supported, but the way to do it is to define security contexts in your docket.

**Comment by steffinho** [comment]
@dilipkrish Didn't find a working example without scopes and only basic authorization for all APIs. Can you provide?

**Comment by dilipkrish** [comment]
See [this example](http://springfox.github.io/springfox/docs/current/#springfox-spring-mvc-and-spring-boot) no. 14 and 15. And lines 115-133

**Comment by steffinho** [comment]
Thanks @dilipkrish. I already found the example but was not sure how to fill the scopes because removing it ends up in NPE. If I provide an empty array it works...

**Comment by SyedSaifi** [comment]
@dilipkrish 
Version: springfox-swagger2 // 2.9.1

I am trying to use basicAuth with @ApiOperation
@ApiOperation(value = "....", authorizations = {@Authorization(value = "basicAuth") })

1. If I don't pass the username and password in the authorize pop-up, I see browsers pop-up coming up asking the username and password.

2. If I enter the username and password in the authorize pop-up, the API is called properly. But if I go back and logout and try to hit the API again, it still lets me call the API without giving 401

**Comment by mlensment** [comment]
> @steffinho The authorization attribute in `@Api` is not supported, but the way to do it is to define security contexts in your docket.

Is it ever going to be supported?

**Comment by dilipkrish** [comment]
This is a swagger 2.x feature. I'd say its unlikely to be supported as part of the core library. However, there is extensibility to always build it yourself.
