### ISSUE TITLE
Getting javascript error with Springfox 2.8 on chrome

### ISSUE THREAD

**Issue by mandargit** [springfox/springfox#2405]
I am getting javascript error for springfox 2.8 with Spring boot when used on Chrome. The same URL works with firefox. 
Below is the javascript error.
springfox.js?v=2.8.0-SNAPSHOT:3 Uncaught SyntaxError: Unexpected token (

**Comment by dilipkrish** [comment]
Try using 2.9.0 and see if that works

**Comment by soyseeb** [comment]
In my case, I cant update the swagger version, so I had tried updating the google chrome, and it worked.
