### ISSUE TITLE
Controllers are being duplicated in swagger & swagger-ui? 

### ISSUE THREAD

**Issue by snimmagadda1** [springfox/springfox#2406]
I have my docket bean setup (in java) as follows:

```
    @Bean
    public Docket customImplementation() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.withMethodAnnotation(RequestMapping.class))
                .paths(PathSelectors.ant("/consent/*"))
                .build()
                .directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
                .directModelSubstitute(java.time.OffsetDateTime.class, java.util.Date.class)
                .apiInfo(apiInfo());
    }
```

And have implemented my Controller classes as an interface defining the methods w/ the api annotations and the respective implementation (class w/ the @Controller annotation). However, I am seeing an endpoint being created in swagger-ui for the annotated Interface class, as well as the controller implementation. Is there a way to stop this? (see image below) 
<img width="1332" alt="screen shot 2018-05-09 at 9 59 37 am" src="https://user-images.githubusercontent.com/19558427/39820051-e2b56a02-5372-11e8-954d-85b64f2721ea.png">

**Comment by dilipkrish** [comment]
Try removing the spring annotations on the interface and see if that helps

**Comment by thomasJoei** [comment]
Had the same problem, one empty "-api-controller" block for every controller... 
Check the tag used in your Interface and copy it to your controller, that should remove the empty duplicate.
ex: 
```
@Controller
@Api(tags = {"addresses"})
```

**Comment by snimmagadda1** [comment]
@thomasJoei you nailed it! This has been bugging me for some time. Interesting behavior..

**Comment by ankushjindal81** [comment]
The problem with this solution, is if there are multiple tags in single controller, then controller tag gets all the APIs. So APIs are duplicated. Is there any way to handle this?
