### ISSUE TITLE
SPEL not getting evaluated in @ApiOperation

### ISSUE THREAD

**Issue by himanshumps** [springfox/springfox#2408]
Springfox Swagger version: 2.9.0
Source code to create the issue: https://github.com/himanshumps/expressionIssue.git
URI's: / and /test

The SPEL are not getting evaluated in `@ApiOperation` (at least this one I checked) while they are part of string`(/)`. 

The rest of the string is ignored if it the first in the string`(/test)`.

Screenshots:
![middle_of_string](https://user-images.githubusercontent.com/22702284/39853412-befedbfc-543f-11e8-86c6-3dbfef6d6088.png)

![start_of_string](https://user-images.githubusercontent.com/22702284/39853416-c6aa8d7e-543f-11e8-831a-04ba7bd182b2.png)

**Comment by dilipkrish** [comment]
Based on your example, it currently only supports evaluating the whole value and not inline replacement. Thats a good idea however!

**Comment by himanshumps** [comment]
Is there any way I can use inline replacement. The issue has been in investigating past 4 days now.

**Comment by dilipkrish** [comment]
@himanshumps I'd suggest you replace the whole expression and not partial. The investigation is to see how to fix this for the next release
