### ISSUE TITLE
custom reason message for 200

### ISSUE THREAD

**Issue by BigGitWorld** [springfox/springfox#2411]
I'm using springfox 2.7 with spring mvc.
its working fine except below problem:
I want to return a string in one rest service. I can set reason for 400,401, 500 response codes.
but I can not show a reason for 200 status code.I dont want return "OK" message.
in the "Response Class (Status 200)" section I will get "string" message always: 

Response Class (Status 200)
string 

I'm using following code : 
```
 @ApiResponses(value = {
            @ApiResponse(code = 200, message = "my message 200", response = String.class),
            @ApiResponse(code = 400, message = "my message 400.", response = String.class),
            @ApiResponse(code = 500, message = "Failure", response = String.class),
    })
``` 
While if i use a custom pojo class instead of String.class, I can see "my message 200" in the "Response Class (Status 200)" section: 

```
@ApiResponse(code = 200, message = "my message 200", response = SamplePojo.class)
```
Response Class (Status 200)
my message 200

what is the problem?
thanks

**Comment by dilipkrish** [comment]
Could you try 2.9.0 and report back

**Comment by BigGitWorld** [comment]
I could not find version 2.9.0 in maven repository...
How can I add it to a maven project?

**Comment by paulosales** [comment]
@dilipkrish I tested on version 2.9.2. The problem didn't happen here.

**Comment by dilipkrish** [comment]
@paulosales thank you!

**Comment by dilipkrish** [comment]
Closing as not reproducable.
