### ISSUE TITLE
Support for SpringBoot 2.x WebFlux

### ISSUE THREAD

**Issue by ianhitlgang** [springfox/springfox#2416]
[advice]
IF it Support for SpringBoot 2.x WebFlux, maybe we can use `YAML`   To configure the  Api ApiOperation ApiImplicitParam Mapping and ......
Come on, I'm looking forward to your next version

**Comment by ianhitlgang** [comment]
#1809 https://github.com/springfox/springfox/issues/1809
#1773 https://github.com/springfox/springfox/issues/1773
tried to integrate springfox swagger & swagger-ui into a webflux application

@Bean
  public RouterFunction<ServerResponse> UserRouter(UserHandler handler) {
    return RouterFunctions.route(
            GET("/user/{id}").and(accept(MediaType.APPLICATION_JSON)), handler::get)
        .andRoute(POST("/user/list").and(accept(MediaType.APPLICATION_JSON)), handler::list)
        .andRoute(POST("/user/page").and(accept(MediaType.APPLICATION_JSON)), handler::page)
        .andRoute(POST("/user").and(accept(MediaType.APPLICATION_JSON)), handler::save)
        .andRoute(PUT("/user").and(accept(MediaType.APPLICATION_JSON)), handler::update)
        .andRoute(DELETE("/user/{id}").and(accept(MediaType.APPLICATION_JSON)), handler::delete)
        .andRoute(
            POST("/user/deleteIds").and(accept(MediaType.APPLICATION_JSON)), handler::deleteIds);
  }

**Comment by dilipkrish** [comment]
This has been fixed via #1773
