### ISSUE TITLE
Springfox not working on payara 5

### ISSUE THREAD

**Issue by luStopai** [springfox/springfox#2417]
Hi

It seems that springfox isn't working when deployed to payara 5

- [x] What version of the library are you using? [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/2.9.0)

What kind of issue is this?
 - [x] Bug report.

How to reproduce:
* Deploying springfox-petstore to payara 4.1 works
* Deploying springfox-petstore to payara 5 doesn't work. I get the "Unable to infer base url ..." dialog.

**Comment by dilipkrish** [comment]
Have never used Payara, so no idea sorry.

**Comment by luStopai** [comment]
Payara is a web application server similar to Glassfish and Tomcat. In fact, it's a fork of Glassfish, which by the way, has the same problem when switching from version 4 to version 5.
I assumed springfox would work on any application server just as spring does.

Is springfox supposed to work only with spring boot?

**Comment by dilipkrish** [comment]
@luStopai May be a little detail on why its not working would help. It appears to be a problem with not getting the right base url because of path mapping/ servlet context differences

**Comment by luStopai** [comment]
Sorry but I have no idea on why its not working. 
Since it works fine when deploying the webapp to payara 4 and it doesn't when deploying to payara 5, I guess there's nothing wrong with the webapp itself.

It seems that something changed in the new version of the webserver that is causing the issue, but I don't know what is it. Any idea on how can I find out?

**Comment by luStopai** [comment]
Nevermind. I just tried the lastest nightly build of glassfish 5 and it works now. It seems it was a bug in both webservers. It's a matter of time that it gets fix in payara 5 too.

**Comment by dilipkrish** [comment]
Thanks for reporting back @luStopai
