### ISSUE TITLE
customize swagger-ui skinny (step by step)

### ISSUE THREAD

**Issue by BigGitWorld** [springfox/springfox#2420]
I' using springfox in a rest spring mvc project.
everything is working fine and I have access to my web services by : 
localhost:8080/api/swagger-ui.html

Now I'm going to customize swagger-ui theme (css files).
I followed several stackoverflow questions and issues too. but I didn't realize how manage it.
now this is my WebConfig class:
```
@Configuration
@EnableWebMvc
@ComponentScan(basePackages = { "com.project" })
@PropertySource("classpath:documentation.properties")
@Import(SwaggerConfig.class)
public class WebConfig extends WebMvcConfigurerAdapter {
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
             .addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}
```
I used https://github.com/springfox/springfox/issues/1176 issue:

Namely I copied dist folder from swagger-ui github to my resources folder and change above WebConfig class: 

```
registry.addResourceHandler("**").addResourceLocations("classpath:/dist/");
OR:
registry.addResourceHandler("**/**").addResourceLocations("/dist/");
```
but i receive 404 error code.why?How can i manage this purpose?

**Comment by dilipkrish** [comment]
If you're using spring boot, you dont need to do anything special other than putting it in [one of the known resource folders](https://spring.io/blog/2013/12/19/serving-static-web-content-with-spring-boot)
