### ISSUE TITLE
PathVariable is generated as Query Param

### ISSUE THREAD

**Issue by ghost** [springfox/springfox#2425]
HI! I am using 2.8.0 version (also tried with 2.9.0) and I am getting an error.

Params with @PathVariable spring annotations are taken as query params in UI. You can see image below where I captured api-docs output.

![image](https://user-images.githubusercontent.com/37376435/40198957-52a1e724-59ee-11e8-8ec6-93c5ffe9c8db.png)

**Comment by dilipkrish** [comment]
What does your method signature look like?

**Comment by patricio-loduca-olx** [comment]
Sorry, I found the error yesterday afternoon. I was generating interfaces with the swagger code generator, and then I implemented these. I saw that the annotations declared in the method definition were not inherited by the implementation classes. So, It's not a bug, I was doing something wrong. [JIra Spring](https://jira.spring.io/browse/SPR-11055)

Thanks @dilipkrish.

**Comment by damian-sima-olx** [comment]
:trollface:
