### ISSUE TITLE
@Api(hidden = true) does not hide controller operations

### ISSUE THREAD

**Issue by anthofo** [springfox/springfox#2437]
Using springfox-swagger2:2.8.0 and springfox-swagger-ui:2.8.0 (same issue with 2.9.0):

When I set the `hidden=true` property on the `@Api` annotation, the controller and all its endpoints are still appearing on swagger-ui

```
@RestController
@Api(tags="Accounts", hidden=true)
@RequestMapping(value="/v2/accounts")
public class AccountsController {

    @ApiOperation(value = "Get account")
    @GetMapping(value = "/{reference}")
    public Account getAccount(@PathVariable String reference) {
        ....
    }
}
```

If I specifically set the hidden property directly on the `@ApiOperation`, it works correctly. But sometimes I want to hide all the endpoints of a controller. For now, I need to add a hidden=true on all the `@ApiOperation` of the controller, and that can be boilerplate.

The `hidden=true` property on the `@Api` annotation was working on old versions of springfox, like the 2.3.0 I think, so it might be a regression.

Thanks !

**Comment by anthofo** [comment]
After digging a bit it appears that it works if I put a `@ApiIgnore` on the controller.
But I don't know it is the intented way to do it because it is a Springfox specific annotation while `@Api` is a swagger annotation. Any guidance for doing this ? 

Thanks :)

**Comment by dilipkrish** [comment]
Thanks for reporting. Will add this to the list of features

**Comment by elamparuthik1991** [comment]
better use @ApiIgnore in controller level.

**Comment by ihgann** [comment]
Seems related to #1731, which was marked as closed. I can confirm as well the same functionality expectation is failing for us, but using `@ApiIgnore` alleviates the problem. If we can automate this functionality for `@Api(hidden = true)` -> `@ApiIgnore`, that would be extremely nice, but it's nice to know there's at least an alternative for now.

**Comment by xianlongbai** [comment]
@ApiIgnore    very good

**Comment by javaHelper** [comment]
@ApiIgnore shows the entry of Controller. How to completely hide this?

**Comment by ohoroyoi** [comment]
@javaHelper you can add "/test/" to @RequestMapping of controller

**Comment by MVTalent** [comment]
@ApiIgnore shows the entry of Controller
```java
@Deprecated
@RestController
@RequestMapping("/test/test-rest")
@Api(tags = "testRest", description = "test rest test rest", hidden = true)
@ApiIgnore
public class TestRest {
.....
}
```

**Comment by dilipkrish** [comment]
@MVTalent What version are you using. This totally works, infact its used internally as well.

**Comment by MVTalent** [comment]
checked on versions 2.8.0 and 2.9.2

**Comment by dilipkrish** [comment]
Not sure, it should work with 2.9.2

**Comment by kajh** [comment]
It does not work with 3.0.0.

**Comment by ripjal** [comment]
I am not sure why this regression has been marked as closed ?

**Comment by elamparuthik1991** [comment]
Hide controller or method?

Please use @ApiIgnore for that controller or method...

Thanks
