### ISSUE TITLE
Please add a constructor function for Docket.class

### ISSUE THREAD

**Issue by tbwork** [springfox/springfox#2443]
Here is the reason:
For now users can only register Docket using Spring @Bean annotation. And if you want to register the Docket by hand using `BeanDefinition`, you will fail because Docket creates instances using builder-mode, rather than the normal way (`setter` and `getter`). Spring context can not inject values for Docket's member variables.

@dilipkrish

**Comment by tbwork** [comment]
To solve this problem for temporary, I have to create a new class DocketWrapper to enhance the Docket class in my code. Following are the codes, just for reference to those people who encounter the same issue.
```
       @Data
	public static class DocketInfo{
		private String groupName;
		private ApiInfo apiInfo;
		private String apiPackagePath;
		private Tag [] tags;
	}

	public static class DocketWrapper extends Docket{ 
		
		public DocketWrapper(DocketInfo docketInfo) {
			super(dt);
			super.apiInfo(docketInfo.getApiInfo()) 
            .groupName(docketInfo.getGroupName())
            .forCodeGeneration(true)
            .useDefaultResponseMessages(false) 
            .select()
                .apis(RequestHandlerSelectors.basePackage(docketInfo.getApiPackagePath()))  
                .apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class))  
                .build()
            .tags(docketInfo.tags[0], copyArray(docketInfo.tags, 1, docketInfo.tags.length));
		} 
	}
```

> Note: @Data is a lombok annotation, you can remove it as you like and use `getter` and `setter` instead.

**Comment by dilipkrish** [comment]
@tbwork that is what I would do as well. Thanks for the solution!

**Comment by tbwork** [comment]
Has it been implemented?

**Comment by dilipkrish** [comment]
With functional bean creation supported in spring 5 is this even needed?

**Comment by tbwork** [comment]
OK. BTW, providing a easy way to create Docket bean would be nice.

**Comment by dilipkrish** [comment]
What in your mind is an easy way. There is a default docket if one isn't specified and there is a builder to customize its creation. It has too many options to use a meaningful constructor. Open to ideas

**Comment by tbwork** [comment]
This is simplely my method to optimize the usage of swagger in terms of convenience.

## 1. Define a new swagger definition annotation:
```
/**
 * <b>Please note</b> that one module is corresponding to one controller.
 * This annotation is used to define a module for a certain group of APIs.
 * 
 * @author tbwork
 */
@Target(value = {ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented   
@Inherited
public @interface SwaggerModule {

	/**
	 * The name of module. Please notice that the module names of different
	 * controllers should also differ from each other. The name will be shown
	 * in the <b>"spec" drop-list options</b> on the swagger-ui.html page. 
	 */
	public String name() default "";
	
	/**
	 * The summary title of APIs in this module.
	 */
	public String title() default "";
	
	/**
	 * The detailed description of this module.
	 */
	public String description() default "";
	
	/**
	 * The version of APIs.
	 */
	public String version() default "New" ;
	
	/**
	 * Tag this module with summary words so that users can find them easily 
	 * and friendly.
	 */
	public String [] tags() default {};
	
	/**
	 * The author or person in charge of this module. Please provider the full
	 * Chinese name so that others can contact you easily.
	 */
	public String author() default "stranger";
	
	/**
	 * The email of the author. Other users can contact the author by this email.
	 */
	public String email() default "";
	  
}

## 2. Providing an annotation as "SwaggerConfiguration", and use it to specify one package path for searching those swagger modules. Following is only an example:
```
	private void collect() {
		List<Class<?>> docketClasses = getClassWithSpecifiedAnnotation(SwaggerModule.class);
		for (Class<?> klass : docketClasses) {
			SwaggerModule annotation = klass.getAnnotation(SwaggerModule.class); 
			addDocket(annotation.name(), annotation.title(), annotation.description(), 
					  annotation.version(), annotation.author(), annotation.email(), klass,
					  annotation.tags());
		}
	}

	private List<Class<?>> getClassWithSpecifiedAnnotation(Class<? extends Annotation> annotation){
		List<Class<?>> result = new ArrayList<Class<?>>();
		ClassPathScanningCandidateComponentProvider scanner = new ClassPathScanningCandidateComponentProvider(false);
        scanner.addIncludeFilter(new AnnotationTypeFilter(annotation));
        for (BeanDefinition bd : scanner.findCandidateComponents("xxx.xxxx")) {
        	try {
				result.add(Class.forName(bd.getBeanClassName()));
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				throw new RuntimeException(e.getMessage());
			}
        } 
        return result;
	}
```


Hope it is helpful. Have a nice day!
