### ISSUE TITLE
Question: Swagger UI - Set JWT token

### ISSUE THREAD

**Issue by bollerdominik** [springfox/springfox#2444]
I have searched everywhere and tried a lot of different code examples but I never managed to achieve this simple goal.

I have a Swagger config like this

	@EnableSwagger2
    @Configuration
    public class SwaggerConfig {
        @Bean
        public Docket api() {
            List<SecurityScheme> schemeList = new ArrayList<>();
            schemeList.add(new ApiKey(HttpHeaders.AUTHORIZATION, "JWT", "header"));
            return new Docket(DocumentationType.SWAGGER_2)
                    .produces(Collections.singleton("application/json"))
                    .consumes(Collections.singleton("application/json"))
                    .ignoredParameterTypes(Authentication.class)
                    .securitySchemes(schemeList)
                    .useDefaultResponseMessages(false)
                    .select()
                    .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
                    .paths(PathSelectors.any())
                    .build();
        }
    }

In the Swagger UI when I click on the Authorize button I enter my JWT token in the value field `eyJhbGc..nN84qrBg`. Now I expect that any request I do through the Swagger UI will contain the JWT in the header. However, that is not the case.
As shown in the curl field in swagger UI there is no Authorization header being send at all.
What am I missing?

**Comment by dilipkrish** [comment]
@bollerdominik you've set the security schemes, however you've not told springfox which methods it needs to apply to. You need to setup either a security context or annotate your operations to use the scheme.

**Comment by bollerdominik** [comment]
@dilipkrish Thanks a lot. That was what was missing!

**Comment by RandyHBH** [comment]
@bollerdominik I'm facing the same error, please can you tell me how you fix it?
