### ISSUE TITLE
ApiParam allowableValues string with spaces is not supported

### ISSUE THREAD

**Issue by uriparush** [springfox/springfox#2446]
Hi,
APiParam annotation has a parameter allowableValue.
This takes a comma separated string. But if i have a space in one of the values, it is stripping it off. 
Which is not good. I can pass a string with spaces from the browser url. So i should be able to pass it from swaagger UI as well.

I think the issue is with this line
I found the below line in class "ApiModelProperties" 
String trimmed = allowableValueString.trim().replaceAll(" ", "");  // line 67

This issue was already discovered in previous versions (Issue number #1211) and was fixed for version 2.6.0 and in some future versions the bug was recreated.

I'm currently using version 2.8.0.

Thanks

**Comment by dilipkrish** [comment]
@uriparush since you've researched the issue a bit would you be able to submit a PR?

**Comment by ctruzzi** [comment]
I've created a PR that should resolve this

**Comment by uriparush** [comment]
@dilipkrish sorry for not handling I was on vacation, next time I will create a PR.
Thanks
