### ISSUE TITLE
Remove the default sort for resources.

### ISSUE THREAD

**Issue by tbwork** [springfox/springfox#2447]
In `InMemorySwaggerResourcesProvider`.get(), there is a line of code as ` Collections.sort(resources);` which sort the resources by their names. However when the resources's names are Chinese, the sort operation always works not so good (Chinese words are commonly sorted by [pinyin](https://en.wikipedia.org/wiki/Pinyin)). 
I'd like to propose to let the user determine the order of resources, that is to say Springfox does nothing with the resources' order by default. Springfox just need to use the order by which user create the Docket.

Just a proposal. :)

**Comment by dilipkrish** [comment]
Thanks for that tip! I'd never have known. Will look to provide an extensibility... or would you like to take  a shot at it?

**Comment by tbwork** [comment]
@dilipkrish  I have pulled a request~ It is a very small change, but it does mean a lot.
