### ISSUE TITLE
X-Forwarded-prefix not work as expected since spring version 4.3.15

### ISSUE THREAD

**Issue by rainoko** [springfox/springfox#2448]
Springfox version 2.8.0

Problem appeared since spring version 4.3.15 or 5.0.5
With issue fix of https://jira.spring.io/browse/SPR-16650 

This issue modified ServletUriComponentsBuilder to not use context path as suffix of X-forwarded-prefix value. Instead now spring replaces path.

springfox prepends base path with x-forwarded-prefix in HostNameProvider

```
private static String prependForwardedPrefix(
      HttpServletRequest request,
      String path) {

    String prefix = request.getHeader("X-Forwarded-Prefix");
    if (prefix != null) {
      return prefix + path;
    } else {
      return path;
    }
  }
```

**Comment by dilipkrish** [comment]
This solution needs to work correctly based on spring version it appears. Thanks for linking to the spring issue. Since you're experiencing the issue and have context, would love it if you could submit a PR to address this.

**Comment by rainoko** [comment]
Ok I try to fix it. 
Should be ok to use org.springframework.core.SpringVersion.getVersion() to determine version and then adding or replacing path.
Is it ok?

**Comment by dilipkrish** [comment]
I did not know that existed :), so yes that would be perfect
