### ISSUE TITLE
Restore ability to access HandlerMethod

### ISSUE THREAD

**Issue by dhay** [springfox/springfox#2450]
I'm attempting to upgrade from 2.5.0 to 2.8.0.  Unfortunately, this broke the `OperationBuilderPlugin` implementations we have written.  In 2.6.0, the `getHandlerMethod()` was removed from `OperationContext`.  We relied on this to get at the `Method` handling the request so we could look for custom annotations and add extensions to the operation (e.g. `context.operationBuilder().extensions(...)`)

I have been unable to find a way to get at the `HandlerMethod` or, more specifically, the `Method` object.

If there is an alternate way at getting at this information, great!  Otherwise, I'd like this functionality restored in some fashion.

**Comment by dhay** [comment]
Opened this a bit prematurely.  I found the operations on the OperationContext that provide the information I needed.

**Comment by dilipkrish** [comment]
@dhay thats great! Sorry for the inconvenience. Do share your solution for future posters

**Comment by dhay** [comment]
What I belatedly discovered was that there are additional methods on the `OperationContext` that allow me to look up annotations, get method parameters, etc. Under the hood, they just talk to the `HandlerMethod`, but it hides the details.

For example, to find an annotation on the method and fallback to the controller class, I do this:
```
Optional<T> methodAnnotation =
   context.findAnnotation(annotationType)
      .or(context.findControllerAnnotation(annotationType));
```

**Comment by dilipkrish** [comment]
@dhay thanks! Yes those were introduced to support non-handler methods based operations :) e.g. Spring Data Rest operations
