### ISSUE TITLE
how to add a wrapper param in every request param

### ISSUE THREAD

**Issue by GreedyPirate** [springfox/springfox#2456]
i have a spring message converter class which extends MappingJackson2HttpMessageConverter, it will add a wrapper param like
`
{
    number : 1
} 
`
become to 
`
{
    params:{
         number：1
    }
}
`
so my question is how to add a “params” in swagger-ui.html for test expediently?
@dilipkrish

**Comment by dilipkrish** [comment]
Thanks for reporting @GreedyPirate
