### ISSUE TITLE
Question on oneOf support in v2.9.0

### ISSUE THREAD

**Issue by subbu107** [springfox/springfox#2457]
Hi,

I'm using version 2.9.0. 

As I understand, it contains polymorphic support, ie, which I am trying to use to generate "oneOf" in the swagger document to represent an inheritance hierarchy in my models. I tried using the annotation specified here: https://github.com/springfox/springfox/issues/1151 , but I am unable to get a oneOf generated for my polymorphic type. I would greatly appreciate it if you could give me a pointer as to what I'm doing wrong.

These are my models :
```java
@Apimodel(subTypes = {Dog.class, Cat.class}, discriminator = "type")
public class Animal {
private String type;
....getter and setter...
}

@Apimodel(value = "Dog", parent = Animal.class)
public class Dog extends Animal{
}

@Apimodel(value="Zoo")
public class Zoo {
   public Animal animal;
}
```
My controller method looks like this 

```java
@ApiOperation(value = "Create Zoo", nickname = "addZoo", notes = "Create Zoo", tags={ "config", })
    @ApiResponses(value = {
            @ApiResponse(code = 201, response = ZooResponse.class, message = "Resource created"),
            @ApiResponse(code = 400, response = ErrorModel.class, message = "Invalid input") })
    @PostMapping(value =  "/urest/v1/administration/zoo", consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity<Zoo> addIngestionConfiguration(@Valid @RequestBody Zoo zoo , @RequestParam Map<String, String> params);    
```
thanks and regards.

**Comment by guilhermegambetti** [comment]
Hi @subbu107, 

Unfortunately, those annotation attributes are misleading. I'm not sure whether they are used or not but the thing is that the new polymorphism support from `2.9.X` is made through Jackson's annotations.

Please take a look at this [@dilipkrish's pull-request](https://github.com/springfox/springfox/commit/741d51fd1e191a8ee24d79c5648480bca7618f60)

A potential annotation mapping for your use-case would be something like this:

````

**Comment by guilhermegambetti** [comment]
Hi @subbu107,

Unfortunately, those annotation attributes are misleading. I'm not sure whether they are used or not but the thing is that the new polymorphism support from 2.9.X is made through Jackson's annotations.

Please take a look at this @dilipkrish's pull-request

A potential annotation mapping for your use-case would be something like this:

**Comment by guilhermegambetti** [comment]
Hi @subbu107,

Unfortunately, those annotation attributes are misleading. I'm not sure whether they are used or not but the thing is that the new polymorphism support from 2.9.X is made through Jackson's annotations.

Please take a look at this @dilipkrish's pull-request

A potential annotation mapping for your use-case would be something like this:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = Dog.class, name = "DOG"),
        @JsonSubTypes.Type(value = Cat.class, name = "CAT")
})
public class Animal {
    protected String type;
}

class Dog extends Animal {

    Dog() {
        type = "DOG";
    }
}

class Cat extends Animal {

    Cat() {
        type = "CAT";
    }
}

class Zoo {
    public Animal animal;
}
```

I hope this answers your question.

**Comment by dilipkrish** [comment]
I researched this and realized that this is working as expected. OneOf is not supported in swagger 2.0, atleast springfox doesnt supports it, yet. 

Aside from that there are two subtle contracts for Zoo happening here.

`Zoo` as response entity, which has `Animal`s are contra variant, so as such so can only have Animal or a super class of `Animal`s on the response, that a client can rely on. IOW only least common attributes can be relied on as a contract, in this case the `Animal` class.

On the other hand, `Zoo` as a request parameter as, which is in a sense covariant, as in it behaves like you'd expect, can be any subclass of `Animal`, that can be passed in.

For your particular issue to be fixed it relies on flushed out OAS3 support as  well as support for #2056  to work.

**Comment by subbu107** [comment]
@guilhermegambetti , apologies, I was stuck with a few other things and could not try out your suggestion yet.
@dilipkrish , thank you for your response! Just one additional question/clarification - if  I do not use a response entity of Zoo, then with the Jackson annotations that @guilhermegambetti has suggested, would I be able to generate oneOf ? Or is it something I basically cannot look for with 2.9.0 and would have to wait for a later version ? 

thank you for your time in looking into this !

**Comment by guilhermegambetti** [comment]
@subbu107 if you test it, you'll see that it works. I've just implemented it and got the expected result. Cheers!

**Comment by dilipkrish** [comment]
@subbu107 

> if I do not use a response entity of Zoo, then with the Jackson annotations that @guilhermegambetti has suggested, would I be able to generate oneOf ? Or is it something I basically cannot look for with 2.9.0 and would have to wait for a later version ?

With 2.9.0, we don't support oneOf. So the contracts will mostly only support least common properties as of now. However like @guilhermegambetti, if you use it using the jackson `JsonSubTypes` annotation it should work, but the contract will not communicate that directly (i.e. no oneOf)

**Comment by subbu107** [comment]
@dilipkrish, @guilhermegambetti  Thank you  for your help and clarifications  !

**Comment by silentsea90** [comment]
When would oneOf be supported? I am currently having to modify all of the parent's documentations to include information of children manually, which isn't the best use of my life :)

**Comment by pgvertex** [comment]
> @dilipkrish When would oneOf be supported? I am currently having to modify all of the parent's documentations to include information of children manually, which isn't the best use of my life :)
> 
> Please let me know if I can make this change myself if not already in the works. Additionally, would it be advisable to work on master branch generated artifacts?

Got any update/solution for this problem?
