### ISSUE TITLE
No controller registered for swagger ui although rest endpoints returns response properly

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [springfox/springfox#2460]
A very strange issue cuurently i am facing and that is Swagger-ui not opening. I have spring boot with spring security and swagger2 2.8.0. I can see the responses for /v2/api-docs but error for /api/v2/api-docs. 
When I drilled down to mappings endpoint of actuator i cannot find the controller that handles such endpoint. What could be cause ?

**Comment by dilipkrish** [comment]
The cause is there is request handler mapping registered at the `/api` context map that handles `/v2/api-docs`
