### ISSUE TITLE
How to add maxLength, minLength, x-example and Pattern for @APIParam

### ISSUE THREAD

**Issue by ChandrasekharRajoli** [springfox/springfox#2467]
Version :  2.8.0
Tech Stack : Spring Boot 2

What kind of issue is this?

Question. How to add maxLength, minLength, x-example and Pattern for @APIParam. I want to document my @RequestParam and @HeaderParam with aforementioned attributes.

**Comment by ChandrasekharRajoli** [comment]
Thanks for your reply @dilipkrish. The x-example and Pattern are not working for @APIParam, but working fine for @APIModelProperty.

**Comment by dilipkrish** [comment]
Please use 2.9.0

**Comment by ChandrasekharRajoli** [comment]
Thank you @dilipkrish. As I read in other posts, that Spingfox team releasing 2.9.1 version for Maven Central. I will wait for the new version. Thank you.
