### ISSUE TITLE
2.9.0: missed comma between flow collection entries

### ISSUE THREAD

**Issue by power721** [springfox/springfox#2469]
Example value make parse failed. It works fine in 2.7.0.

The error message in swagger-ui:
```
Errors
Parser error 
missed comma between flow collection entries
```

The error in browser console:
> r
mark
:
r {name: null, buffer: "{"swagger":"2.0","info":{"description":"Api Docume…cription":"The username"}},"title":"UserDto"}}}↵", position: 30173, line: 0, column: 30173}
message
:
"missed comma between flow collection entries at line 1, column 30174:↵     ... type":"string","example":[test] n/a,"description":"The username" ... ↵                                         ^"
name
:
"YAMLException"
reason
:
"missed comma between flow collection entries"

The Java code:
```Java
@ApiModelProperty(value = "The username", example = "[test] n/a")
private String name;
```

Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
2.9.0
What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by power721** [comment]
```java
@ApiModelProperty(value = "The username", example = "[test] n/a")
private String name;
```
```json
"UserDto":{"type":"object","properties":{"name":{"type":"string","example":[test] n/a,"description":"The username"}},"title":"UserDto"}
```

```java
@ApiModelProperty(value = "The username", example = "n/a")
    private String name;
```
```json
"UserDto":{"type":"object","properties":{"name":{"type":"string","example":"n/a","description":"The username"}},"title":"UserDto"}
```

**Comment by dilipkrish** [comment]
Thanks for the example @power721

**Comment by dilipkrish** [comment]
@power721 you need to change your annotation to 
`@ApiModelProperty(value = "The username", example = "'[test] n/a'")` and then it will work. Note the added single quotes the example.
