### ISSUE TITLE
Showing extra information in header section

### ISSUE THREAD

**Issue by gaurav517** [springfox/springfox#2470]
- What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
2.9.0
What kind of issue is this?

 - Question. Is this a question about how to do a certain thing? Yes.
Is it possible to add some extra information on swagger-ui in header section (where we have description, license etc.). For example, I want to add Service Owner information (Not using Contact) and possibly some other information. I tried using vendorextensions:

```
List<VendorExtension> vendorExtensions = new ArrayList<>();
        vendorExtensions.add(new VendorExtension<String>() {
            @Override
            public String getName() {
                return "Service Owner";
            }

            @Override
            public String getValue() {
                return getServiceOwner().getName();
            }
        });

return new Docket(DocumentationType.SWAGGER_2)
                .useDefaultResponseMessages(false)
                .groupName(groupName)
                .select()
                .paths(PathSelectors.any())
                .build()
                .apiInfo(new ApiInfoBuilder().version(apiVersion)
                        .title(serviceName + " API")
                        .description(apiDescription)
                        .extensions(vendorExtensions)
                        .build());
```
But it does not show up.. not even in json api doc. Do I need to do something more? Thanks a lot.

**Comment by dilipkrish** [comment]
@gaurav517 you should use `StringVendorExtension` in the above case. I added a test that verifies that it works as expected

**Comment by gaurav517** [comment]
Thanks @dilipkrish, Using StringVendorExtension, I can see the property in json file now, but not in swagger-ui.html. I suppose if I want to render that in ui then will have to tell swagger-ui how to render that. Will skip that part, not important for now. Thanks a lot.
