### ISSUE TITLE
Upgrade to the swagger version 1.5.20

### ISSUE THREAD

**Issue by dwen77** [springfox/springfox#2472]
Hi,

I have noticed that the latest version of springfox is not using the latest version of swagger which is 1.5.20. In this version, there are some nice features like having the examples attribute in ApiResponse annotation (http://docs.swagger.io/swagger-core/v1.5.X/apidocs/index.html?io/swagger/annotations/ApiResponses.html) . Do you have any plan to support swagger 1.5.20 ?

Thanks!

**Comment by dilipkrish** [comment]
@dwen77 absolutely

**Comment by dwen77** [comment]
Nice!

**Comment by dwen77** [comment]
Just for your information, If I understand the code correctly, I guess there should be some code changes need to be done in order to support the new attribute "example" in the ApiResponse annotation.
