### ISSUE TITLE
Override tag/group names

### ISSUE THREAD

**Issue by sverhagen** [springfox/springfox#2476]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? **2.8.0** (just upgraded from 2.2.2)
- [x] Is it the latest version? **Yes**

What kind of issue is this?

 - [x] **Question**
 - [ ] Bug report. **Not yet** :wink: 

Please do consider starring this repository **Had it starred for a _long time_**

---

After a long time of hibernation, I just returned back to an old project, which originally lead me to #155, back in the day. I had extended some Springfox classes to deal with these problems, but that didn't work anymore after upgrading from 2.2.2 to 2.8.0 (understandably). So, I dialed the customizations back, and now just newly looking for: how to override tags/group names (whatever we call these).

The problem is that my API endpoints get listed as the proxies that Spring has wrapped around them:

![image](https://user-images.githubusercontent.com/2049860/41206529-4e117402-6cba-11e8-84d8-35b1df668513.png)

This is surely a consequence of the eleborate class model that I'm having. (My controllers extend a shared base class, and a specific interface, the relevant annotations are sprinkled across all of those.) What I really want to ask is, what is the appropriate extension point to influence the name of the tags/groups, so that I can override them to be something different than `$Proxy123`/`$-proxy-123` (since I know what interface to pull to get a decent name).

**Comment by dilipkrish** [comment]
FYI 2.9.0 is the latest version, its available only in jcenter however while I fix it for 2.9.1.

In any case, if you create an annotation in your apis like `@Api(tags={"Some Tag"})` at the controller level, it should fix this problem.

**Comment by sverhagen** [comment]
That works. I tried `@Api(basePath = "incident", value = "incident API")`, and I had expected the tags to then be derived from the `value`. But it works, thanks for the quick turnaround!
