### ISSUE TITLE
Different property description for the same class

### ISSUE THREAD

**Issue by gionn** [springfox/springfox#2479]
I have a class with different fields of the same type, that I annotate like:

```
    @ApiModelProperty( "The ordered productVersion" )
    private UrlEntityDTO productVersion;

    @ApiModelProperty( "Chosen bandwidth plan - only for managed applications" )
    private UrlEntityDTO bandwidthPricing;
```

When rendering the documentation, the first description if used for both fields. I think that this is somehow expected but I don't have figured how to handle this situation where I would like to describe the field in a different way even if they are of the same type.

Thanks.

**Comment by dilipkrish** [comment]
What version of springfox are you using. Seems like a bug that was fixed

**Comment by gionn** [comment]
Upgraded from 2.8.0 to 2.9.0 (didn't notice the new version earlier, thanks for pointing it) and behaviour changed, but not in the direction it would be good for what I am trying to achieve: now I can only set a global description via `@ApiModel` on the UrlEntityDTO class, and `@ApiModelPropery` it's ignored, but I would like to set different descriptions for each field that use this type, because it has different meaning in every context it is used.

Don't know if there is at least one way to achieve this, it looks like that I am stuck with a generic field description for every class that contains an UrlEntityDTO field. Is it correct?

Thanks!

**Comment by gionn** [comment]
I dug into the issue, the problem is at OpenAPI specification level and described here:
https://github.com/OAI/OpenAPI-Specification/issues/1514

So, springfox is generating a non-compliant schema and my renderer (Redoc) is simply ignoring the description field when a $ref exists.

I can workaround this issue only creating a whole new hierarchy of classes, each one with their own description :nauseated_face: 

Thanks for your support @dilipkrish

**Comment by dilipkrish** [comment]
@gionn thanks for letting me know about the transgression in the spec 😿 Will try and address as part of OAS 3.0 support
