### ISSUE TITLE
Correct use of the ModelBuilderPlugin not obvious

### ISSUE THREAD

**Issue by hennejg** [springfox/springfox#2480]
I am trying to expose an API with model class that uses @JsonAnyGetter/@JsonAnySetter to enable extensibility. 

For a minimal example and a demo of the problem please see https://github.com/hennejg/springfox-tests

The basic idea is that the model can be extended using plugins, a bit like custom fields are handled in JIRA's REST API, should you happen to be familiar with that.
Thus, the API published using springfox/swagger is dependent on the plugins that are enabled in the particular instance. To that end, I implemented a `ModelBuilderPlugin` that collects the properties controbuted by plugins (I call those facets) and adds those to the generated model like this:

```
@Component
public class ExposeFacetModels implements ModelBuilderPlugin {

  @Autowired(required = false)
  private List<Facet> facets;

  @Autowired
  private TypeResolver typeResolver;

  @Override
  public boolean supports(final DocumentationType delimiter) {
    return true;
  }

  @Override
  public void apply(final ModelContext context) {
    if (context.resolvedType(typeResolver).getErasedType().equals(Foo.class)) {
      Map<String, ModelProperty> facetProperties = new HashMap<>();

      facets.forEach(f -> {
        JavaType valueType = f.getValueType(TypeFactory.defaultInstance());
        ModelPropertyBuilder builder = new ModelPropertyBuilder().name(f.getName()).type(fromJackson(valueType));
        facetProperties.put(f.getName(), builder.build());
      });

      context.getBuilder().properties(facetProperties);
    }
  }
...
}
```

For details about `fromJackson(...)` see the full source code. _Short side rant: why are there both `com.fasterxml.classmate.ResolvedType` as well as `com.fasterxml.jackson.core.type.ResolvedType` which both provide very similar, but incompatible functionality? My facets expose types from the `com.fasterxml.jackson.core.type`-hierarchy since I use that to do some additional Jackson configuration (excluded from the example) which is why I need to convert the types to classmate._

I can see that the `apply` method is triggered and that it adds the correct properties. But lateron they are missing from the model at http://localhost:8080/v2/api-docs.

Any help would be greatly appreciated.

**Comment by hennejg** [comment]
Ok, so the reason for the problem was that the `ModelProperty` lacked a model ref. Updating the plugin like this did the trick:

```
public void apply(final ModelContext context) {
    if (context.resolvedType(typeResolver).getErasedType().equals(Foo.class)) {
      Map<String, ModelProperty> facetProperties = new HashMap<>();

      facets.forEach(f -> {
        JavaType valueType = f.getValueType(TypeFactory.defaultInstance());
        ModelProperty modelProperty = new ModelPropertyBuilder() //
            .name(f.getName()) //
            .type(fromJackson(valueType)) //
            .build();
        modelProperty.updateModelRef(ResolvedTypes.modelRefFactory(context, typeNameExtractor));
        
        facetProperties.put(f.getName(), modelProperty);
      });

      context.getBuilder().properties(facetProperties);
    }
  }
```

This may warrant an example in the documentation.

**Comment by dilipkrish** [comment]
I'll add some documentation and also see if I can make that a validation in the builder to catch that earlier

**Comment by hennejg** [comment]
Thanks!

**Comment by iawebwork** [comment]
Thanks for your answer. 

With springfox 3.0.0 now modelRefFactory requires 3 params, as following
`modelRefFactory​(ModelContext parentContext, EnumTypeDeterminer enumTypeDeterminer, TypeNameExtractor typeNameExtractor)`

https://springfox.github.io/springfox/javadoc/current/springfox/documentation/schema/ResolvedTypes.html

Kindly can you guide what can I use for EnumTypeDeterminer.
