### ISSUE TITLE
"Try it out" not work on JSON including line 

### ISSUE THREAD

**Issue by boyoyon8** [springfox/springfox#2483]
- [x] What version of the library are you using? 
2.8.0

 - [x] Question. Is this a question about how to do a certain thing? 

I use Spring fox 2.8.0 on Spring boot 1.5.2. and `@EnableSwagger2` annotation.
I tried "Try it out" of POST/PUT API on swagger-ui.html, but it does not work on JSON including line breaks.

JSON:
```json
{
    "id": 1,
    "name": "John Due"
}
```
Server Error:
```
Could not read document: Unexpected end-of-input: expected close marker for Object (start marker at [Source: java.io.ByteArrayInputStream@2433007c; line: 1, column: 1])\n at [Source: java.io.ByteArrayInputStream@2433007c; line: 1, column: 3]; nested exception is com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: java.io.ByteArrayInputStream@2433007c; line: 1, column: 1])\n at [Source: java.io.ByteArrayInputStream@2433007c; line: 1, column: 3]
```

JSON without line breaks goes well.
Is the setting of Jackson or Swagger wrong? Are there any ideas to resolve this error?

**Comment by boyoyon8** [comment]
Sorry Error log is wrong, and updated comment,

**Comment by dilipkrish** [comment]
What does your operations method signature look like

**Comment by boyoyon8** [comment]
I tried it with a simple application and it worked, It seems that springfox is not the cause of the error.
I will check my application a bit more. 

Thanks for reply !
