### ISSUE TITLE
Swagger UI - BigDecimal rendered in scientific notation.

### ISSUE THREAD

**Issue by ChandrasekharRajoli** [springfox/springfox#2489]
- [ ] What version of the library are you using?  2.8.0 
What kind of issue is this? Question

 - [ ] Question.  Swagger UI - Rendering BigDecimal in scientific notation. I want to render it as it is in Swagger UI. Please help how to enable this feature.

Please find the below BigDecimal value in Swagger UI and PostMan.
Swagger UI 
{
  "amount": 1.2345678912345679e+27,
}

PostMan Raw Body 
{
    "bigDecimal": 1234567891234567891234567891.1234
}

**Comment by dilipkrish** [comment]
This is a [Swagger-ui](https://github.com/swagger-api/swagger-ui) issue

**Comment by ChandrasekharRajoli** [comment]
Are we planning to fix this issue in near future?

**Comment by ChandrasekharRajoli** [comment]
Thanks
