### ISSUE TITLE
Additional models not loading. Filtered out in ApiModelReader

### ISSUE THREAD

**Issue by kerber** [springfox/springfox#2491]
**Version**
springfox-swagger2  v 2.9.0
**Issue**
The documentation for Docket.additionalModels() seems to be straight-forward. I'm attempting to load an additional enum that's available in the classpath at runtime, as such:
`.additionalModels(typeResolver.resolve(Unit.class))`
With debug logging enabled, I'm seeing the log on startup:
> springfox.documentation.spring.web.scanners.ApiModelReader Did not find any parameter models for com.example.common.units.Unit

Stepping through the execution of ApiModelReader, I see that the Unit enum is not found in the ModelProvider, but I'm not sure as to why.

Is this due to a bug, or some step I'm missing to get Unit to be loaded by the ModelProvider?

**Comment by dilipkrish** [comment]
@kerber enums are treated as strings. So as such they will not show up in the models collection.

**Comment by kerber** [comment]
Ahh! Looking at how models are presented, that makes perfect sense. Thanks for the follow-up!
