### ISSUE TITLE
StackoverflowException in 2.8.0

### ISSUE THREAD

**Issue by atereshkov** [springfox/springfox#2507]
Still getting the error (copy of https://github.com/springfox/springfox/issues/2339)

`springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.simpleFields(ModelAttributeParameterExpander.java:162) ~[springfox-spring-web-2.8.0.jar!/:2.8.0]`

in the 2.8.0 version.

```
 @OneToOne
    @JoinColumn(name = "organaizer_id")
    private Organaizer organaizer;

@OneToOne(mappedBy = "organaizer", cascade = CascadeType.ALL)
    private User user;
```

**Comment by dilipkrish** [comment]
Could you give 2.9.2 a shot

**Comment by atereshkov** [comment]
@dilipkrish it seems to be working now, thanks!
