### ISSUE TITLE
Question about working with oauth tokens

### ISSUE THREAD

**Issue by khadk** [springfox/springfox#2509]
I am using springfox-swagger2 and springfox-swagger-ui version 2.8.0 for documenting my api's. I am facing 2 issues listed below. 
1. I need to generate the oauth2 token using the token and the authorize endpoint,which I am able to authorize using the Authorize button.But the problem is that swagger provides a default redirect url,but how to provide a custom redirect url .Like the way,we are able to provide user specific clientId and client Secret.So that user can provide any redirect url and genearte the token. 
2. On click of authorize button I am unable to see the acces tokens and refresh tokens,instead I can only see statement 'authorized'.

How can I display even the token to the user after the user clicks on Authorize button in swagger??

**Comment by dilipkrish** [comment]
Swagger 2.0 does not support oauth flows very well. You may need to wait for OAS 3.0 support

**Comment by khadk** [comment]
Thank you for your reply...:)
But doesn't this version(2.8.0) support the display of access and refresh tokens,instead of just showing authorized??

**Comment by dilipkrish** [comment]
It doesnt because it only supports swagger specification 2.0
