### ISSUE TITLE
Can't get requestbody using @ModelAttribute

### ISSUE THREAD

**Issue by ricemaster** [springfox/springfox#2510]
I'm using swagger 2.8.0 and spring boot 2.0.2.

In my rest controller, when I'm using `@ModelAttribute` and I POST a JSON in request body from Postman, the request mapping doesn't work fine. The parameter is null. 

And when I use `@RequestBody` instead of `@ModelAttribute`, everything is perfect.

It also doesn't work if I add both of the annotations.

`
    @PostMapping("/ygjcData")
    public ResponseTest create(@ModelAttribute @RequestBody RequestTest req)
`

**Comment by dilipkrish** [comment]
Model attributes will not take a json body. It can only bind to scalar types

**Comment by ricemaster** [comment]
Thank you~@dilipkrish
