### ISSUE TITLE
 Using an API Key to Secure My API

### ISSUE THREAD

**Issue by cyohman** [springfox/springfox#2512]
I have been trying to use an API key to secure my API using Open API 2.0 in my Swagger file & Springfox. I have yet to find a way to make this work or a working example. Can anyone point me in the right direction?

I don't want bits of code. I want a real working example that actually checks the API key and it if it's invalid, then it does not allow the API call.

This is my 2nd go around. If I can't find something that works, then I am going to suggest my team not use Springfox.

**Comment by dilipkrish** [comment]
[The demos](https://github.com/springfox/springfox-demos) should have what you're looking for as far springfox goes (see here for [an example](https://github.com/springfox/springfox/blob/e45774540cef6173e08ae6cbc5e2c2dd296de6fd/springfox-petstore/src/main/java/springfox/petstore/controller/PetController.java#L62-L67)). In addition, you'd have to setup spring security to honor the api key based authentication.

**Comment by cyohman** [comment]
Can you point me in the direction of something that would explain how to have spring security honor the api key based authentication?

**Comment by dilipkrish** [comment]
@cyohman if your operations use the same security reference yes, it should respect it.
