### ISSUE TITLE
 How to properly annotate and present a Map type request body?

### ISSUE THREAD

**Issue by peerit12** [springfox/springfox#2519]
I am currently using swaggerUi 3.0.3 version

in controller param is of type ArrayList<Map<String, Object>> so error comes in swagger-ui
Resolver error at paths./forms.post.parameters.0.schema.items.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/Map«string,object» does not exist in document

Any solution to this???

**Comment by dilipkrish** [comment]
@peerit12 please move to 2.9.2

**Comment by peerit12** [comment]
I used 2.9.2 but still the same errors is coming i just want that the error on swagger-ui won't show

**Comment by dilipkrish** [comment]
Can you share the json that the swagger-ui is trying to display? or atleast the signature of the method that you believe is failing?

**Comment by dilipkrish** [comment]
What is the json you're getting for that?

**Comment by mmorel-35** [comment]
@peerit12, would it it be possible to change your model. So that it moves to something like List<MyObject> where MyObject can extends HashMap. if you absolutely need the use of a map which probably means that you don't have control over the possible values of the keys of those maps?

**Comment by peerit12** [comment]
@dilipkrish  I am getting json Line this:

"{"swagger":"2.0","info":{"description":"FranConnect SKY REST API Developer Portal","version":"1.0","title":"FranConnect SKY REST API","termsOfService":"Terms of service","contact":{"name":"FranConnect"},"license":{"name":"FranConnect","url":"http://www.franconnect.com/license.txt"}},"host":"fc.ritesh:8765","basePath":"/audit","tags":[{"name":"Audit Forms Api","description":"Set of endpoints to performs all crud operation on audit forms"},{"name":"Audit Visits Api","description":"Set of endpoints to performs all crud operation on audit visits"},{"name":"download-controller","description":"Download Controller"},{"name":"upload-controller","description":"Upload Controller"}],"paths":{"/downloadFile":{"get":{"tags":["download-controller"],"summary":"getSteamingFile","operationId":"getSteamingFileUsingGET","produces":["application/octet-stream"],"parameters":[{"name":"filename","in":"query","description":"filename","required":true,"type":"string"}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/StreamingResponseBody"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false}},"/forms":{"get":{"tags":["Audit Forms Api"],"summary":"get","description":"Fetch all audit forms","operationId":"get","produces":["application/xml","application/json"],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false},"post":{"tags":["Audit Forms Api"],"summary":"save or saveInBatch","description":"save the single audit forms or In batch","operationId":"save or saveInBatch","consumes":["application/xml","application/json"],"produces":["application/xml","application/json"],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false},"put":{"tags":["Audit Forms Api"],"summary":"update the single audit forms or In batch","operationId":"update or updateInBatch","consumes":["application/json"],"produces":["application/xml","application/json"],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false},"delete":{"tags":["Audit Forms Api"],"summary":"delete or deleteInBatch","description":"delete the single audit forms or In batch","operationId":"delete or deleteInBatch","produces":["application/xml","application/json"],"parameters":[{"in":"body","name":"datalist","description":"ParameterType:ArrayList<Map<String, Object>>","required":false,"schema":{"type":"array","items":{"$ref":"#/definitions/Map[0xc2][0xab]string,object[0xc2][0xbb]"}}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"204":{"description":"No Content"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}},"deprecated":false}},"/forms/dropdown":{"get":{"tags":["Audit Forms Api"],"summary":"getDropDown","description":"provide the audit forms dropdown","operationId":"getDropDown","produces":["application/xml","application/json"],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false}},"/forms/filter":{"post":{"tags":["Audit Forms Api"],"summary":"get(filters)","description":"provide the audit forms based on some filter","operationId":"get(filters)","consumes":["application/xml","application/json"],"produces":["application/xml","application/json"],"parameters":[{"in":"body","name":"filters","description":"ParameterType:AppFilter","required":false,"schema":{"$ref":"#/definitions/AppFilter"}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false}},"/forms/{id}":{"get":{"tags":["Audit Forms Api"],"summary":"getById","description":"provide the audit forms based on form Id","operationId":"getById","produces":["application/xml","application/json"],"parameters":[{"name":"id","in":"path","description":"ParameterType:Integer","required":false,"type":"integer","format":"int32","enum":["integer"]}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false},"delete":{"tags":["Audit Forms Api"],"summary":"deleteById","description":"delete the single audit forms based on formId","operationId":"deleteById","produces":["application/xml","application/json"],"parameters":[{"name":"id","in":"path","description":"id","required":true,"type":"integer","format":"int32"}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]VoidResult[0xc2][0xbb][0xc2][0xbb]"}},"204":{"description":"No Content"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}},"deprecated":false}},"/upload":{"post":{"tags":["upload-controller"],"summary":"upload","operationId":"uploadUsingPOST","consumes":["multipart/form-data"],"produces":["application/xml","application/json"],"responses":{"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"array","items":{"type":"string"}}}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false}},"/visits":{"get":{"tags":["Audit Visits Api"],"summary":"get","description":"Fetch all audit visits","operationId":"get_1","produces":["application/xml","application/json"],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false},"post":{"tags":["Audit Visits Api"],"summary":"save or saveInBatch","description":"save the single audit visit or In batch","operationId":"save or saveInBatch_1","consumes":["application/json"],"produces":["application/xml","application/json"],"parameters":[{"in":"body","name":"datalist","description":"ParameterType:ArrayList<Map<String, Object>>","required":false,"schema":{"type":"array","items":{"$ref":"#/definitions/Map[0xc2][0xab]string,object[0xc2][0xbb]"}}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false},"put":{"tags":["Audit Visits Api"],"summary":"update the single audit forms or In batch","operationId":"update or updateInBatch_1","consumes":["application/json"],"produces":["application/xml","application/json"],"parameters":[{"in":"body","name":"datalist","description":"ParameterType:ArrayList<Map<String, Object>>","required":false,"schema":{"type":"array","items":{"$ref":"#/definitions/Map[0xc2][0xab]string,object[0xc2][0xbb]"}}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false},"delete":{"tags":["Audit Visits Api"],"summary":"delete or deleteInBatch","description":"delete the single audit visit or In batch","operationId":"delete or deleteInBatch_1","produces":["application/xml","application/json"],"parameters":[{"in":"body","name":"datalist","description":"ParameterType:ArrayList<Map<String, Object>>","required":false,"schema":{"type":"array","items":{"$ref":"#/definitions/Map[0xc2][0xab]string,object[0xc2][0xbb]"}}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"204":{"description":"No Content"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}},"deprecated":false}},"/visits/filter":{"post":{"tags":["Audit Visits Api"],"summary":"get(type : VisitFilter)","description":"provide the audit forms based on some filter","operationId":"get(type : VisitFilter)","consumes":["application/json"],"produces":["application/xml","application/json"],"parameters":[{"in":"body","name":"filters","description":"ParameterType:VisitFilter","required":false,"schema":{"$ref":"#/definitions/VisitFilter"}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false}},"/visits/{id}":{"get":{"tags":["Audit Visits Api"],"summary":"getById","description":"provide the audit visits based on visit Id","operationId":"getById_1","produces":["application/xml","application/json"],"parameters":[{"name":"id","in":"path","description":"ParameterType:Integer","required":false,"type":"integer","format":"int32","enum":["Integer"]}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false},"delete":{"tags":["Audit Visits Api"],"summary":"deleteById","description":"delete the single audit forms based on formId","operationId":"deleteById_1","produces":["application/xml","application/json"],"parameters":[{"name":"id","in":"path","description":"ParameterType:Integer","required":false,"type":"integer","format":"int32","enum":["Integer"]}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Response"}},"204":{"description":"No Content"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}},"deprecated":false}}},"definitions":{"AppFilter":{"type":"object","properties":{"constraints":{"type":"object","example":"format: {db_field:{operation:dataValue}","xml":{"name":"constraints","attribute":false,"wrapped":false},"description":"page","additionalProperties":{"$ref":"#/definitions/FilterConstraint"}},"fields":{"type":"array","xml":{"name":"fields","attribute":false,"wrapped":false},"description":"fields","items":{"type":"string"}},"page":{"xml":{"name":"page","attribute":false,"wrapped":false},"description":"page","$ref":"#/definitions/Page"}},"title":"AppFilter","xml":{"name":"AppFilter","attribute":false,"wrapped":false},"description":"Used as common Filter for all services"},"Base":{"type":"object","title":"Base"},"FilterConstraint":{"type":"object","properties":{"clause":{"type":"string","enum":["EQUAL","NOT_EQUAL","GREATER_THAN","LESS_THAN","GREATER_THAN_OR_EQUAL","LESS_THAN_OR_EQUAL","LIKE","IN","NOT_IN","BETWEEN"]},"values":{"type":"array","items":{"type":"string"}}},"title":"FilterConstraint","description":"This model is used for filter-contraints having field operation and values  "},"Page":{"type":"object","properties":{"groupBy":{"type":"string"},"pageId":{"type":"integer","format":"int32"},"pageSize":{"type":"integer","format":"int32"},"size":{"type":"integer","format":"int32"},"sort":{"$ref":"#/definitions/Sort"},"totalPages":{"type":"integer","format":"int64"},"totalRecords":{"type":"integer","format":"int64"},"viewAll":{"type":"boolean"}},"title":"Page"},"Response":{"type":"object","properties":{"response":{"$ref":"#/definitions/Base"}},"title":"Response"},"Response[0xc2][0xab]Result[0xc2][0xab]VoidResult[0xc2][0xbb][0xc2][0xbb]":{"type":"object","properties":{"response":{"$ref":"#/definitions/Result[0xc2][0xab]VoidResult[0xc2][0xbb]"}},"title":"Response[0xc2][0xab]Result[0xc2][0xab]VoidResult[0xc2][0xbb][0xc2][0xbb]"},"Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]":{"type":"object","properties":{"response":{"$ref":"#/definitions/Result[0xc2][0xab]object[0xc2][0xbb]"}},"title":"Response[0xc2][0xab]Result[0xc2][0xab]object[0xc2][0xbb][0xc2][0xbb]"},"Result[0xc2][0xab]VoidResult[0xc2][0xbb]":{"type":"object","properties":{"data":{"xml":{"name":"data","attribute":false,"wrapped":false},"$refm":"#/definitions/VoidResult"},"page":{"xml":{"name":"page","attribute":false,"wrapped":false},"$ref":"#/definitions/Page"}},"title":"Result[0xc2][0xab]VoidResult[0xc2][0xbb]","xml":{"name":"Result[0xc2][0xab]VoidResult[0xc2][0xbb]","attribute":false,"wrapped":false},"description":"Return the Result of anyType along with data & Page attribute"},"Result[0xc2][0xab]object[0xc2][0xbb]":{"type":"object","properties":{"data":{"type":"object","xml":{"name":"data","attribute":false,"wrapped":false}},"page":{"xml":{"name":"page","attribute":false,"wrapped":false},"$ref":"#/definitions/Page"}},"title":"Result[0xc2][0xab]object[0xc2][0xbb]","description":"Return the Result of anyType along with data & Page attribute"},"Sort":{"type":"object","properties":{"columns":{"type":"array","items":{"type":"string"}},"direction":{"type":"string","enum":["ASC","DESC"]}},"title":"Sort","xml":{"name":"sort","attribute":false,"wrapped":false}},"StreamingResponseBody":{"type":"object","title":"StreamingResponseBody"},"VisitFilter":{"type":"object","properties":{"constraints":{"type":"object","example":"format: {db_field:{operation:dataValue}","xml":{"name":"constraints","attribute":false,"wrapped":false},"description":"page","additionalProperties":{"$ref":"#/definitions/FilterConstraint"}},"fields":{"type":"array","xml":{"name":"fields","attribute":false,"wrapped":false},"description":"fields","items":{"type":"string"}},"page":{"xml":{"name":"page","attribute":false,"wrapped":false},"description":"page","$ref":"#/definitions/Page"},"saveView":{"type":"boolean"}},"title":"VisitFilter","xml":{"name":"VisitFilter","attribute":false,"wrapped":false},"description":"Used as common Filter for all services"},"VoidResult":{"type":"object","properties":{"message":{"type":"string"},"success":{"type":"boolean"}},"title":"VoidResult"}}}[\r][\n]

**Comment by peerit12** [comment]
@dilipkrish  please suggest somthing????????????????

**Comment by dilipkrish** [comment]
What version of springfox are you using?

**Comment by peerit12** [comment]
@dilipkrish  i have told you before..swaggerUi 3.0.3 version and after you told me i moved to  2.9.2 springfox version

**Comment by dilipkrish** [comment]
Sorry I misunderstood. Why arent u using springfox-swagger-ui?
