### ISSUE TITLE
Question: How to make Swagger-UI with SpringBoot to display custom yaml instead of auto generated?

### ISSUE THREAD

**Issue by kkgr** [springfox/springfox#2520]
Hi,

I'm using swagger2 and swagger-ui 2.7.0 with Java and SpringBoot. Here is my Swagger config:
```
@Configuration
  @EnableSwagger2  
  public class SwaggerConfig {  
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .paths(Predicates.not(PathSelectors.regex("/error.*")))
                .build();
    }
} 
```

I would like to use my own defined yaml (or json), so I can have there examples, own descriptions etc. 

Here are nicely described options to define (https://swagger.io/docs/specification/2-0/basic-structure/) but my question is, how can I point Swagger to use my own yaml file.

**Comment by dilipkrish** [comment]
You need to
- add your yaml as a resource. 
- include the swagger-ui from the [Swagger-ui](https://github.com/swagger-api/swagger-ui) project as a resource/webjar.  
- point your swagger-ui to your yaml source.

You dont need springfox to do this.

**Comment by kkgr** [comment]
@dilipkrish 
Last point you mentioned is exactly what I described as my problem;)
HOW can I point swagger-ui to use it?

**Comment by dilipkrish** [comment]
You can just type in the location of your yaml file and hit explore. 
![swagger_ui](https://user-images.githubusercontent.com/73257/42035541-ce9de500-7aa8-11e8-93ec-4777e0ad867a.jpg)

See [here](https://petstore.swagger.io/?_ga=2.170627360.1611413214.1530153020-1816306401.1461171332) for an example of how it should appear. NOTE: that you are using [this Swagger-ui](https://github.com/swagger-api/swagger-ui) and not the one bundled with springfox.

**Comment by kkgr** [comment]
Ok, I've tried using 
```
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>  
    <version>2.9.2</version>
```
And I've tried with 2.7.0 also but there is no possibility to type location of file, only drop-down list with only one option is shown.
How I can add my file to that list (or preferred - override the default one)?

**Comment by dilipkrish** [comment]
Like I mentioned in the comment, you need to use this [Swagger-ui](https://github.com/swagger-api/swagger-ui) if you want that behavior.

**Comment by kkgr** [comment]
Ok, let's close this one, I will ask there.
