### ISSUE TITLE
Unable to infer base url when spring boot application deployed as war and has servlet mapping.

### ISSUE THREAD

**Issue by amelnikoff** [springfox/springfox#2526]
Good day.
I'm trying to make work swagger-ui.html in deployed war and has problem with detecting base url.

Application has one extra property:

`server.servlet-path=/api/v4`

Here is an example [demo repo](https://github.com/amelnikoff/springfox-boot-swagger-with-tomcat)

When application is started with embedded servlet container, everything works fine:
**swagger-ui.html** is accessible on url http://localhost:8080/springfox/api/v4/swagger-ui.html
and it determines base url as well.
json is accessible on url http://localhost:8080/springfox/api/v4/v2/api-docs?group=category-api

When application deployed as war file into Tomcat 8.5.24 with context 'springfox'
**swagger-ui.html** is accessible on different url http://localhost:8080/springfox/swagger-ui.html it ignores for some reason servlet path from application.properties and says cannot infer base url when it loads.
When I'm entering base url manually http://localhost:8080/springfox/api/v4, it loads data fine and shows api docs.

The question is, am I missing something from configuration, or is it bug?

Forgot to mention: Spring Boot version 1.5.14.RELEASE and Springfox version 2.9.2

**Comment by dilipkrish** [comment]
Thanks for the repro-repo. I'll take a look and let you know

**Comment by dilipkrish** [comment]
I don't think its related but I added 

`providedRuntime('org.springframework.boot:spring-boot-starter-tomcat')` to the gradle dependencies section. 

After that I  setup the application context root as `/springfox` in tomcat and I see the swagger-ui served up at `http://localhost:8080/springfox/api/v4/swagger-ui.html` just like if you ran it in the embedded container.

**Comment by amelnikoff** [comment]
Hm. Who can imagine that!
Don't know what tomcat-starter doing there but it works.

Thanks!

**Comment by dilipkrish** [comment]
@amelnikoff Its included by default in the spring-boot-starter-web. Setting it as provided runtime makes sure it doesnt have the embedded tomcat in the dependencies list of libraries.

**Comment by amelnikoff** [comment]
Seems to me it's time reread spring boot reference. Last time I read it 3 years ago )
