### ISSUE TITLE
@GetMapping Method can't resolve Camels properties to underline but @PostMapping do

### ISSUE THREAD

**Issue by wangboda** [springfox/springfox#2527]
I am using springfox-swagger2 2.7.0 and springBoot 2.0.2 to build my restWebApi , in my team we decision that all of private property should named begin with "_" , and all of method should named with  camels format , here comes a question , in @GetMapping method Swagger UI show no parameter .
Simple example:
```
@RestController
@RequestMapping("/api/test")
public class temp  {
    @GetMapping("")
    public void getDarenPriceCount(user theUser)
    {
        System.out.println(theUser.getName());
    }
}
```
```
public class user {
    private String _name;
    private String _age;

    public String getName() {
        return _name;
    }
    public void setName(String name) {
        this._name = name;
    }
    public String getAge() {
        return _age;
    }
    public void setAge(String age) {
        this._age = age;
    }
}
```
<img width="967" alt="2018-07-02 10 04 54" src="https://user-images.githubusercontent.com/28685241/42141988-6909f7d0-7ddf-11e8-8e4f-8635d2777dfa.png">
But if i named property without "_" it works fine

```
public class user {
    private String name;
    private String age;
    // get and set 
}
```

<img width="963" alt="2018-07-02 10 08 34" src="https://user-images.githubusercontent.com/28685241/42142059-e7a9879a-7ddf-11e8-9256-6e50f5860f73.png">

what should I do to make Swagger convert underline format to camels format automatically.

**Comment by dilipkrish** [comment]
Have you tried 2.9.2?

**Comment by wangboda** [comment]
@dilipkrish  It works ! thanks for ur answer
