### ISSUE TITLE
Question: How to handle wildcard in endpoints

### ISSUE THREAD

**Issue by khadk** [springfox/springfox#2533]
Need to know how should I handle the api endpoints which accepts wildcard characters. For example I have an endpoint "/version1/resources/**" defined in my controller and this endpoint accepts any string after the "/resource/". And in my swagger this endpoint looks like this GET: /version1/resource/**.But i don't know how to pass any string to this wildcard character from swagger. I am using springfox-swagger2 of version 2.5.0

**Comment by khadk** [comment]
i tried with using a pathparameter,but my path parameter contains a slash so it will not identify my resource as a whole and gives 405 unsupported method

**Comment by dilipkrish** [comment]
That level of dynamism is not supported in swagger ui
