### ISSUE TITLE
2.9.2 Object self reference crashes swagger-ui

### ISSUE THREAD

**Issue by lmeisegeier** [springfox/springfox#2535]
Since Version 2.9.2 swagger-ui crashes If one tries to open controller endpoint with an object that contains a self reference.
![firefoxswaggeruicrash](https://user-images.githubusercontent.com/40823834/42277658-6a730124-7f98-11e8-91ce-46a2ea709598.PNG)

Object that contains cyclic self reference: (ommited other attributes):
```
@Entity
@Table(name = "roles")
public class Role {

...

  @ManyToOne
  @JoinColumn(name = "ancestor_id")
  @JsonProperty
  private Role ancestor;

...

  public Role getAncestor() {
    return this.ancestor;
  }

  public void setAncestor(final Role ancestor) {
    this.ancestor = ancestor;
  }

...

}
```
Firefox show error:  "[Invalid Object]":
![firefoxinvalidobject](https://user-images.githubusercontent.com/40823834/42277657-6a5b4980-7f98-11e8-8dc4-71eff6397572.PNG)

Chrome shows error: "RangeError: Maximum call stack size exceeded":
![chromerangeerror](https://user-images.githubusercontent.com/40823834/42277656-6a4161b4-7f98-11e8-8295-6b55a9b4159d.PNG)

We used version 2.8.0 before and didnt get this issue. We want to use version 2.9.2 because support for Pageable has been added. Our current Workaround is using version 2.8.0 with ApiImplicitParams annotations.
 
- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

**Comment by dilipkrish** [comment]
This is a [Swagger-ui](https://github.com/swagger-api/swagger-ui) issue

**Comment by holgerstolzenberg** [comment]
Does that mean the issue needs to be moved to another subproject/tracker?

**Comment by dilipkrish** [comment]
Yes @holgerstolzenberg. Linked in my response above
