### ISSUE TITLE
Why show "Unable to render this definition"?

### ISSUE THREAD

**Issue by dengfengfeng** [springfox/springfox#2542]
this is my spring-mvc.xml
![image](https://user-images.githubusercontent.com/29336079/42367174-e05873ee-8135-11e8-9660-3357b35a9d1e.png)
this is my SwaggerConfig
![image](https://user-images.githubusercontent.com/29336079/42367312-57bdffc6-8136-11e8-9cff-b3e2f5a9dc5a.png)
this is SwaggerConfig`bean setting
![image](https://user-images.githubusercontent.com/29336079/42367330-68106fa8-8136-11e8-98b4-20c8609ca583.png)

 
I'm not sure my setting is ok .
```java

    @Bean
    public Docket createRestApi1() {
        System.out.println("SwaggerConfig.createRestApi--1");
        return new Docket(DocumentationType.SWAGGER_2)
        		.pathMapping("/")
                .apiInfo(apiInfo())
                .groupName("客户端操作")
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.tecsun.controller.client"))
                .paths(PathSelectors.any())
                .build();
    }
    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
            .title("德生")
            .description("文件中心文档")
            .termsOfServiceUrl("http://www.e-tecsun.com")
            .version("1.0")
            .build();
    }
}
```
![image](https://user-images.githubusercontent.com/29336079/42367409-b6ce8ed6-8136-11e8-8f4f-a3c3655f688f.png)

please save me from my BUG :)

**Comment by dilipkrish** [comment]
Looks like you figured it out @dengfengfeng

**Comment by dengfengfeng** [comment]
yes ,I figured it out.and thank you .

**Comment by navandres** [comment]
Hey @dilipkrish,
Can you share with me what the problem was?
I'm having the same issue and can't find the solution to it.

Thanks,
Andy

**Comment by LittleYann** [comment]
@navandres Try changing the version of the jar package.
