### ISSUE TITLE
How to fix 406 Not Acceptable in spring boot application

### ISSUE THREAD

**Issue by karunchinna** [springfox/springfox#2547]

**Comment by karunchinna** [comment]
hi 
how to resolve 406 Not Acceptable in spring boot application.
{
    "timestamp": 1531287256361,
    "status": 406,
    "error": "Not Acceptable",
    "exception": "org.springframework.web.HttpMediaTypeNotAcceptableException",
    "message": "Could not find acceptable representation",
    "path": "/test/ abc"

**Comment by dilipkrish** [comment]
You should move to 2.9.2

**Comment by karunchinna** [comment]
thanks

**Comment by VoTuanNguyen** [comment]
https://www.novatec-gmbh.de/en/blog/spring-boot-passing-uris-rest-path-parameters/
