### ISSUE TITLE
 How do I make a Release note for Spring fox?

### ISSUE THREAD

**Issue by cheese10yun** [springfox/springfox#2549]
The spring fox release note is really well organized.

![2018-07-11 3 47 42](https://user-images.githubusercontent.com/12086692/42555029-ef1a2310-8521-11e8-9f6c-2396909b4723.png)

Is this automated and working?

If so, which tool do you use?

**Comment by dilipkrish** [comment]
It is not automated, though I wish I could automate it. Its mostly a cut&paste and some vim magic that makes it semi automated.

**Comment by cheese10yun** [comment]
@dilipkrish Hi I'm sorry I'm not used to English.

I'm working on it manually.

https://github.com/github-tools/github-release-notes

I have not used the link above. It is an alternative that looks good. If you use it, I will leave a review again. Thank you for your comment.
