### ISSUE TITLE
Support for kotlin.Deprecated

### ISSUE THREAD

**Issue by arcuri82** [springfox/springfox#2551]
Hi,
  using SpringFox in a Kotlin project.

When an endpoint is marked with `java.lang.Deprecated`, then SpringFox shows it as deprecated in the GUI (as expected).

For Kotlin projects, it would be good to have the same support for when the annotation `kotlin.Deprecated`  is used. This would be particularly useful with IntelliJ, as `java.lang.Deprecated` is itself deprecated in Kotlin, and IntelliJ flags all of its usages (with warnings to rather replace it with `kotlin.Deprecated`)

**Comment by dilipkrish** [comment]
@arcuri82 that is easily accomplished using a plugin

**Comment by arcuri82** [comment]
thanks, I guess that would be a solution for now. But, considering the ongoing support of Kotlin in Spring (e.g., [here](https://spring.io/blog/2017/01/04/introducing-kotlin-support-in-spring-framework-5-0)), it would be great if this was handled out of the box.

**Comment by dilipkrish** [comment]
💯 agree. Its a great candidate for a `springfox-kotlin-extensions`. Since I dont use kotlin extensively, I could use help with maintaining it.

**Comment by adamdziedzic** [comment]
Hi, is there any workaround for this? I stumbled upon the same problem

**Comment by dilipkrish** [comment]
This can be easily implemented as a plugin. Perhaps the long term solution is to create a Kotlin module that configures the defaults for kotlin

**Comment by dinhani** [comment]
Upvoting this.

It took me some debugging to realize the APIs were not being marked as deprecated because I was using `kotlin.Deprecated` and not `java.lang.Deprecated`.

Maybe something about it could be added in the docs.

**Comment by fzyzcjy** [comment]
Here is a workaround:

```
/**
 * Support [kotlin.Deprecated], when the original Springfox only supports [java.lang.Deprecated]
 * modified from: https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/operation/OperationDeprecatedReader.java
 * see more at https://github.com/springfox/springfox/issues/2551
 */
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
class SwaggerKotlinOperationDeprecatedReader : OperationBuilderPlugin {
    override fun apply(context: OperationContext) {
        val annotationOnMethod = context.findAnnotation(Deprecated::class.java)
        val annotationOnController = context.findControllerAnnotation(Deprecated::class.java)
        val deprecated = annotationOnMethod.isPresent || annotationOnController.isPresent
        context.operationBuilder().deprecated(if (deprecated) "true" else null)
    }

    override fun supports(delimiter: DocumentationType): Boolean = true
}
