### ISSUE TITLE
swagger-ui bug, method not supported.

### ISSUE THREAD

**Issue by derstolz** [springfox/springfox#2552]
You havent resolved previous issue. There is a **bug** with accessing swagger-ui.html.
I was using springfox for some time and everything works just fine. Today i have added some @ApiModels and @ApiOperations info. I cant access swagger-ui after that. /v2/api-docs works ok. 
What can i do? 

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("packages.services"))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo());
    }
```

**Comment by dilipkrish** [comment]
@derstolz thats not enough information for me to help you. If you're not able to access swagger-ui.html there could be many causes. Also could you link to this __previous issue__ you're talking about.
