### ISSUE TITLE
Extra parameters generated for endpoint

### ISSUE THREAD

**Issue by mpapirkovskyy** [springfox/springfox#2554]
Just upgraded springfox-swagger2 from 2.6.1 to 2.9.2.

Noticed behavior change I don't fully get. 
For method signature
```java
  @PostMapping("/login")
  public ResponseEntity<TokenDto> login(@RequestParam(required = false) Boolean rememberMe,
      @RequestParam(required = false) String otp,
      Authentication authentication, UriComponentsBuilder uriBuilder)
```

weird param list generated
```json
"parameters": [
          {
            "name": "authenticated",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "authorities[0].authority",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "credentials",
            "in": "query",
            "required": false,
            "type": "object"
          },
          {
            "name": "details",
            "in": "query",
            "required": false,
            "type": "object"
          },
          {
            "name": "otp",
            "in": "query",
            "description": "otp",
            "required": false,
            "type": "string"
          },
          {
            "name": "principal",
            "in": "query",
            "required": false,
            "type": "object"
          },
          {
            "name": "rememberMe",
            "in": "query",
            "description": "rememberMe",
            "required": false,
            "type": "boolean"
          }
        ]
```

Prior to upgrade this method correctly had 2 params.
Didn't find anything related in changelog, where should I look at?

**Comment by dilipkrish** [comment]
Yes, this is related to a change in the behavior of jackson. this [has been addressed](https://github.com/iles-2e/springfox/commit/848d72517839b0857eda9690b0f08ded0c7d645c) in 3.0.0

**Comment by srlps** [comment]
Maybe this could help

    @Component
    @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 1000)
    public class SpringDefaultParametersFilter implements ExpandedParameterBuilderPlugin {

        // add as many as you like
        private String[] filteredNames = new String[] { "authenticated", "authorities[0].authority", "credentials",
                "details", "principal" };

        @Override
        public boolean supports(DocumentationType documentationType) {
            return true;
        }

        @Override
        public void apply(ParameterExpansionContext context) {
            String computedName = context.getParameterBuilder().build().getName();
            if (isFiltered(computedName)) {
                context.getParameterBuilder().hidden(true);
            }
        }

        private boolean isFiltered(String name) {
            // used java 8 stream but any search method on the filteredNames array will work
            return Stream.of(filteredNames).anyMatch(filteredName -> filteredName.equals(name));
        }

    }

**Comment by plathub** [comment]
You can use `@ApiIgnore` annotation until this has been fixed:

```
@PostMapping("/login")
  public ResponseEntity<TokenDto> login(@RequestParam(required = false) Boolean rememberMe,
      @RequestParam(required = false) String otp,
      @ApiIgnore Authentication authentication, 
      @ApiIgnore UriComponentsBuilder uriBuilder)
```

**Comment by olayinkasf** [comment]
I'm having the same issue with version 3.0.0

**Comment by dilipkrish** [comment]
You could do one of the following
- create an alternate type rule for UriComponentBuilder to convert into a type you want
- ignore the parameter using @ApiIgnore as shown above or via docket
