### ISSUE TITLE
Swagger UI doesn't show input for authorization token

### ISSUE THREAD

**Issue by theunreal** [springfox/springfox#2555]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? 
3.17.0

What kind of issue is this?

 - [x ] Bug report

I have set up JWT authentication in my spring boot app, but there is no option in my swagger UI to add the token to the requests.

The token is obtained by making a POST request to /login with username and password. (response is JSON with the token)

What do I need to configure/make sure in order to see an input in the Swagger UI that enters auth token to the headers of all requests?

**Comment by dilipkrish** [comment]
Have you read [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)?
