### ISSUE TITLE
Issue when integrating spring fox project with swagger2

### ISSUE THREAD

**Issue by iqbalnzls** [springfox/springfox#2560]
Hello, I've problem to integrate spring fox project with swagger2. I have added dependecies like this in my pom.xml

```xml
<!-- Dependency for Swagger -->
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.9.2</version>
		</dependency>
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger-ui</artifactId>
		    <version>2.9.2</version>
		</dependency>
		<dependency>
		    <groupId>org.webjars</groupId>
		    <artifactId>bootstrap</artifactId>
		    <version>4.1.1</version>
		</dependency>
		
		<!-- Spring security dependency -->
		<dependency>
		    <groupId>org.springframework.security</groupId>
		    <artifactId>spring-security-acl</artifactId>
		    <version>3.2.9.RELEASE</version>
		</dependency>`
```
And my config class like this 
```java 
@Configuration
@EnableSwagger2
public class SwaggerConfig{

	private static final String SWAGGER_API_VERSION = "1.0";
	private static final String LICENSE_TEXT = "Indivara";
	private static final String title = "Lifestyle API";
	private static final String description = "API for Lifestyle application";
	
	private ApiInfo apiInfo() {
		return new ApiInfoBuilder()
				.title(title)
				.description(description)
				.license(LICENSE_TEXT)
				.version(SWAGGER_API_VERSION)
				.build();	
	}
    
    @Bean
	public Docket lifestyleApi() {
		return new Docket(DocumentationType.SWAGGER_2)
				.select()
				.apis(RequestHandlerSelectors.basePackage("com.jatis.lifestyle.ws.rest.controller"))
				.paths(PathSelectors.any())
				.build();
	}
    
}
```

and in my controller class i've addes api and apiresponses annotation

The problem is when i tried hit url http://localhost:9092/swagger-ui.html, the page showed 404 response status. Anyone here can help me, i'had tried many possible answer but the result was still stuck on 404 response.

**Comment by dilipkrish** [comment]
are you using spring boot or vanilla spring mvc? If its the latter you need to add the resource handlers manually.

**Comment by iqbalnzls** [comment]
@dilipkrish Spring boot, but i've added the resource handlers too in my project  like this 
`@Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }`
But still the same, browser return 404 error responses. In ur opinion, is there something that i missed ?

**Comment by dilipkrish** [comment]
Seems like you need to ignore the springfox endpoints for spring security.

**Comment by iqbalnzls** [comment]
@dilipkrish hmm ican't figured out that u say, can u explain it clearly as well as the class which i need to my project ?

**Comment by dilipkrish** [comment]
@iqbalnzls [This is what](https://github.com/springfox/springfox/issues/1996#issuecomment-335155187) I was talking about
