### ISSUE TITLE
Programmatically add ApiDescription with JSON request body

### ISSUE THREAD

**Issue by l3ender** [springfox/springfox#2561]
We are using Springfox 2.9.2. Our application has Spring Security enabled so I am wanting to advise Springfox of the authentication methods that our API exposes.

We have POJOs for both input and output for our authentication API, and the spring security layer handles conversion of these objects to/from JSON for the client. However these are not automatically added to the Swagger doc because they are not in a controller.

I'm trying to find out how to inject the request/response detail to the documentation. Based on [this comment](https://github.com/springfox/springfox/issues/1931#issuecomment-317114739) and [related documentation page](http://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin), I can see that I need to implement `ApiListingScannerPlugin` to build the `ApiDescription`. I can't find any way to specify the request input/body, as the [Swagger documentation describes](https://swagger.io/docs/specification/2-0/describing-request-body/).

Any info on how to manually expose these API details (and related request/response objects) would be greatly appreciated. Thanks!

**Comment by dilipkrish** [comment]
Specifying the parameter doesnt work?

**Comment by l3ender** [comment]
I'm building the parameter like this, where `AuthenticationRequest` is my POJO:
```
Parameter input = new ParameterBuilder().name("body").description("Input")
	.parameterType("body").type(typeResolver.resolve(AuthenticationRequest.class))
	.modelRef(new ModelRef(AuthenticationRequest.class.getName()))
	.build();
```

When I do this and then load the Swagger UI endpoint, I get the following error:
> Resolver error at paths./api/authenticate.post.parameters.0.schema.$ref
> Could not resolve reference because of: Could not resolve pointer: /definitions/org.mycompany.rest.authentication.request.AuthenticationRequest does not exist in document

**Comment by rrathod05** [comment]
I have similar problem when I adding global error response message.

```
responseMessages.add(new ResponseMessageBuilder()
				.code(HttpStatus.BAD_REQUEST.value()).message(HttpStatus.BAD_REQUEST.getReasonPhrase() + " - Returns when <br> invalid request received (i.e. request is in not expected format) <br>"
						+ "validation fails <br> business error occurs.")
				.responseModel(new ModelRef("ErrorResponse"))
				.build());
```



![capture](https://user-images.githubusercontent.com/41487896/43024292-7c7e6b18-8c33-11e8-865c-4ea4c5c9b2da.PNG)


Console log
![image](https://user-images.githubusercontent.com/41487896/43024331-9db40a40-8c33-11e8-9503-e2c4e54e33ec.png)

**Comment by dilipkrish** [comment]
@l3ender you need to change that to `.modelRef(new ModelRef(AuthenticationRequest.class.getSimpleName()))`

**Comment by dilipkrish** [comment]
@rrathod05 you need to add `ErrorResponse` to `additionalModels` in your docket

**Comment by rrathod05** [comment]
@dilipkrish  Thanks !! It worked after adding additionalModels.

Also, I have same requirement as @l3ender and had tried what you suggested but did not work and giving same error as @l3ender listed.

**Comment by rrathod05** [comment]
@dilipkrish any further solution/info will be help much on the above said issue. Thanks!

**Comment by dilipkrish** [comment]
@rrathod05 see the solution I provided [here](https://github.com/springfox/springfox/issues/2561#issuecomment-407373949)

**Comment by rrathod05** [comment]
@dilipkrish the solution provided [here](https://github.com/springfox/springfox/issues/2561#issuecomment-407373949) is not working. Kindly, suggest any alternate fix.
