### ISSUE TITLE
Example Value content-type set as json in spring fox 2.8.0 version

### ISSUE THREAD

**Issue by sujittripathy** [springfox/springfox#2562]
- **Version** - springfox-swagger-ui v2.8.0 & springfox-swagger2 v2.8.0

- **Question** - 

I am using spring-fox (above version) in spring-boot 1.5. In swagger-ui.html I am seeing the Example Value is defaulted to `application/xml` however, I would like to select `application/json` as default while page loading. Is there anywhere it can be done via `Docket` configuration? Sample spring boot controller code and screenshot below.

```
@PostMapping(value = "/capture", produces = { "application/json", "application/xml" }, consumes = {
			"application/json", "application/xml" })
	ResponseEntity<?> capture(
			@ApiParam(value = "Capture request", required = true) @Valid 
			@RequestBody PaymentProcessorRequest paymentProcessorRequest) 
```
![image](https://user-images.githubusercontent.com/21118953/42974299-7e6c5890-8b6b-11e8-9baa-1f557d5a19d9.png)

**Comment by dilipkrish** [comment]
There is no way to do that. Would be a great feature request in [Swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by sujittripathy** [comment]
Good to know @dilipkrish. Will raise a feature request [Swagger-ui](https://github.com/swagger-api/swagger-ui). Thanks

**Comment by mmamyan** [comment]
@sujittripathy  Did you find a way to do that??? I have the same issue here now ...

**Comment by wojciech-soltys** [comment]
I've created feature request: https://github.com/swagger-api/swagger-ui/issues/5347

**Comment by wojciech-soltys** [comment]
I've created similar issue with PR but connected with Docket configuration: https://github.com/springfox/springfox/issues/3062
