### ISSUE TITLE
Can Springfox Swagger scan controller from package excluded by Spring @ComponentScan?

### ISSUE THREAD

**Issue by me-nageshkumar** [springfox/springfox#2564]
In my Spring MVC Application, I am using Springfox version: 2.5.0 and Spring version: 4.3.3.RELEASE, consider following configuration:

    package com.example.api.configuration;

    // import statements

    @Configuration
    @EnableWebMvc
    @ComponentScan(basePackages = "com.example.api", excludeFilters = @Filter(type = FilterType.REGEX, pattern = "com\\.example\\.api\\.mockcontroller\\..*"))
    public class SpringMvcConfiguration extends WebMvcConfigurerAdapter {
    
    // class code goes here

    }

I have classes (Controllers) annotated with `@Controller` in `com.example.api.controller` and `com.example.api.mockcontroller` packages, among which I don't want Spring to scan classes (Controllers) in `com.example.api.mockcontroller` package, so I used `excludeFilters` to exclude them from being scanned.

But I want classes (Controllers) in `com.example.api.controller` and `com.example.api.mockcontroller` packages to be picked up by Springfox swagger.

My Swagger configuration file is as follows:

    package com.example.api.configuration;

    // import statements

    @Configuration
    @EnableSwagger2
    public class SwaggerConfig {

	    @Bean
	    public Docket api() {
		    return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.basePackage(("com.example.api")))
            .paths(PathSelectors.any())
			.build();
	    }
    }

Springfox swagger is only picking controllers from `com.example.api.controller` package.
I also asked for solution on [Stackoverflow](https://stackoverflow.com/questions/51429709/can-springfox-swagger-scan-controller-from-package-excluded-by-spring-component).

**Comment by dilipkrish** [comment]
It will only pick the controllers that are registered components.

**Comment by nagesh-tm** [comment]
I am using Spring Security which actually handles Login end point. Now, I want login endpoint in swagger API documentation and to have login endpoint in API document, I created mockcontroller which I don't want to be registered as component by Spring. Is there a way to add login endpoint to Swagger API document?

**Comment by me-nageshkumar** [comment]
I am using Spring Security which actually handles login end point (No controller). Now, I want login endpoint in swagger API documentation and to have login endpoint in API document, I created mockcontroller which I don't want to be registered as component by Spring. Is there a way to add login endpoint to Swagger API document?

**Comment by dilipkrish** [comment]
@me-nageshkumar If you want to add your own login endpoint, then you can look at the [example in the docs](http://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin)

**Comment by lephix** [comment]
@dilipkrish 
I am facing the same situation. We have implemented our own DispatchServlet, some of the API is not a SpringMVC controller, just marked a @Controller for the class. 
We also mark @Api @Path at those the class, want those "Controller"s be included in the swagger. But it seems not.
Using Plugin is possible, but with a simple configuration like "package path" could do this better.

**Comment by dilipkrish** [comment]
@lephix thats not as easy. Will think about it, but seems easier to describe the API by hand.
