### ISSUE TITLE
Springfox 2.9.0 - Not really compatible with Java 6

### ISSUE THREAD

**Issue by lppedd** [springfox/springfox#2566]
The 2.9.0 release rely on jackson-databind 2.9.5, which is compiled for Java 7, and the JVM obviously throws an "unsupported" exception.
Any workaround?

Edit:
Also swagger-models and swagger-annotations 1.5.18 are compiled for Java 8.
But are you sure this was ever tested on Java 6? I'm not able to run even downgrading to 2.8.0, which is based on 1.5.14, that is compiled against Java 7.

**Comment by lppedd** [comment]
So basically I recompiled swagger-annotations and swagger-models for class level 6.

**Comment by dilipkrish** [comment]
@lppedd it is not compatible with java 6. There is no way to build using gradle and java 6 without support for TLS.

**Comment by lppedd** [comment]
@dilipkrish Ok, thanks! But than isn't it better to remove the "This is the last release supporting jdk 6" part?

**Comment by dilipkrish** [comment]
Totally! thanks for catching that. That was written before GitHub/bintray stopped supporting lower TLS version!

**Comment by lppedd** [comment]
@dilipkrish I think we can close this.
