### ISSUE TITLE
Is there anyway to hide some item of an Enum

### ISSUE THREAD

**Issue by mchen391** [springfox/springfox#2570]
Version: I'm using 2.8.0, can move to 2.9.2 if needed

Question:
I'm wondering if there's anyway to ignore certain items from an Enum, so it will not be shown in the models or allowableValues. It seems neither `@ApiIgnore` nor `@ApiModelProperty` works for Enum.

To be more specific, I have an Enum type field in the model, which can be `A`, `B`, `C` and `UNKNOWN`. In a request, only `A`, `B` and `C` is acceptable, and `UNKNOWN` is used as the default Enum value for Jackson deserializer. I wanna show `A`, `B` and `C` in the model and allowed values in the documentations.

**Comment by raderio** [comment]
+1
