### ISSUE TITLE
Api key header field is missing in swagger ui calls (version 2.9.2)

### ISSUE THREAD

**Issue by medialwerk** [springfox/springfox#2576]
Version: 2.9.2

Hello everybody,

this bug report is refering to https://github.com/springfox/springfox/issues/1804. 
It seems that the header field (here: `api_key`) is missing in the swagger ui calls. We see it for example at the generated curl commands (examples are below).

### Java code

```Java
public class SwaggerConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))
            .paths(PathSelectors.regex(Constants.REST_API_PATH_ROOT + ".*"))
            .build()
            .securitySchemes(Arrays.asList(apiKey()))
            .useDefaultResponseMessages(false);

    }

    private ApiKey apiKey() {
        return new ApiKey("APIKey", "api_key", "header");
    }
}
```
 
### Input at swagger-ui

```
name: APIKey
in: header
value: my_key_value
```

### curl at swagger-ui (current behaviour)
```
curl -X GET "http://localhost:8080/api/users" -H "accept: application/json"
```

### curl at swagger-ui (expected behaviour)
```
curl -X GET "http://localhost:8080/api/users" -H 'Accept: application/json' -H 'api_key: my_key_value' 
```

Thank you very much for your help!

**Comment by medialwerk** [comment]
Thank you very much! :-). That was the missing part! :-).

I only had to change `api_key` to `APIKey` in your code sample:

```
  private List<SecurityReference> defaultAuth() {
    final AuthorizationScope authorizationScope = new AuthorizationScope("global", "accessEverything");
    final AuthorizationScope[] authorizationScopes = new AuthorizationScope[]{authorizationScope};
    return Collections.singletonList(new SecurityReference("APIKey", authorizationScopes));
  }
```

**Comment by tholu** [comment]
You're right, it's a bit confusing where to put which name and I picked the wrong one from your code. Glad it works for you now as well!

**Comment by medialwerk** [comment]
Yes, it's a bit difficult. I'm rather a JavaScript developer and now I have to maintain some Java / Spring backend. The wiring and the documentation feels a little bit complicated to me. Thank you! :-)

**Comment by dilipkrish** [comment]
@medialwerk great its resolved and thanks @tholu for helping. It can be a little confusing. Would one of you be nice enough to create a new feature request with a proposal to make it better? If we want to break existing API's this is the time to do it :)

**Comment by daveleenew** [comment]
Thanks @tholu ~~~

**Comment by alexrochadealbuquerque** [comment]
Very good Congratulations!

**Comment by blaqniz** [comment]
> Thank you very much! :-). That was the missing part! :-).
> 
> I only had to change `api_key` to `APIKey` in your code sample:
> 
> ```
>   private List<SecurityReference> defaultAuth() {
>     final AuthorizationScope authorizationScope = new AuthorizationScope("global", "accessEverything");
>     final AuthorizationScope[] authorizationScopes = new AuthorizationScope[]{authorizationScope};
>     return Collections.singletonList(new SecurityReference("APIKey", authorizationScopes));
>   }
> ```

@medialwerk how do I do the authentication after setting up the API key to pass in header? Where do I set my key_value so that swagger can check against that? I am facing the same problem. Please help. 

Thanks.

**Comment by elvisbegovic** [comment]
I agree with @dilipkrish this should be less confusing/configurable.

As new user of this lib I expect adding 
```
...securitySchemes(Arrays.asList(apiKey()))
...
private ApiKey apiKey() {
    return new ApiKey("x-auth-token", "x-auth-token", "header"); 
}
```

to be enough to add it to headers auth on all webservices calls, and in swagger-ui button is really present
![image](https://user-images.githubusercontent.com/2789203/91564102-6337c700-e940-11ea-97e9-b769bf6ae66c.png)

in addition since of 3.0.0 `forPaths()`is deprecated and in docs we still have https://springfox.github.io/springfox/docs/current/#springfox-spring-mvc-and-spring-boot deprecated ways doing that.

What you think @dilipkrish ?
