### ISSUE TITLE
Springfox Swagger2 v.2.9.1 not working with large APIs

### ISSUE THREAD

**Issue by suzana-djuricic** [springfox/springfox#2585]
Hi!
I use swagger in spring mvc application. First, I used `v.2.9.1` and it was working fine while I was mapping controllers with few methods. Once I mapped controller with many methods, **java.lang.OutOfMemoryError: GC overhead limit exceeded** happened. 
I've changed version to `2.8.0` and it works.

**Comment by dilipkrish** [comment]
Thanks for reporting, its still not clear how 2.8.0 is better than 2.9.2. More information would help fix the problem.
