### ISSUE TITLE
SecurityContextHolder.getContext().getAuthentication().getPrincipal not updated

### ISSUE THREAD

**Issue by selvaebi** [springfox/springfox#2586]
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
this.createdBy = authentication.getPrincipal().toString();

the createdBy is still anonymousUser even after authorize

**Comment by dilipkrish** [comment]
Is this related to this project

**Comment by selvaebi** [comment]
how to get the username of authorised user

**Comment by dilipkrish** [comment]
You need to authorize before invoking the endpoint. Have you done that?

**Comment by selvaebi** [comment]
yes i authorised and trying to get the username via ,
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
this.createdBy = authentication.getPrincipal().toString();
but am getting anonymous user only

**Comment by dilipkrish** [comment]
> yes i authorised and trying to get the username

how? how in the ui? how have you configured your spring security, what does your contract look like?

**Comment by selvaebi** [comment]
![screen shot 2018-08-06 at 10 03 48 am](https://user-images.githubusercontent.com/33631243/43707493-271f9e64-9960-11e8-9c14-33518532fe0f.png)

**Comment by selvaebi** [comment]
but still i get anonymous user . IF i use spring security's formlogin i am able to get the user name using ,  
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
this.createdBy = authentication.getPrincipal().toString();
But this swaggerr's authorized username am not able to get it anywhere

**Comment by dilipkrish** [comment]
Ok, you need to make sure you're endpoints are protected as well. Have you set up the security context on your docket correctly?

**Comment by markskylarkxx** [comment]
After authentication, and I get the jwt. When I try to get the logged in user it returns anonymous user

**Comment by impeako** [comment]
same issue here
