### ISSUE TITLE
@ApiModelProperty(value = "email",required = true)   required property  invalid

### ISSUE THREAD

**Issue by xiaoymin** [springfox/springfox#2587]
my Model class like :
```java
@ApiModel(value = "SendUserRequest",description = "请求对应方法时使用")
public class SendUserRequest {

    private String id;

    @ApiModelProperty(value = "登录账户",required = true)
    private String email;
```
in my Spring application controller:
```java
@PostMapping("/sendUser")
    @ApiOperation(value = "用户注册",notes = "填写用户信息注册用户")
    public Rest<SendUserRequest> requestRest(@RequestBody SendUserRequest sendUserRequest){
        Rest<SendUserRequest> requestRest=new Rest<>();
        requestRest.setData(sendUserRequest);
        return requestRest;
    }
```

When we use Spring's @RequestBody annotation, when receiving the entity class parameter, when using @ApiModelProperty annotation to the entity class property for the entity class property, the required property parameter of the annotation is invalid. I found that in the swagger-models core jar package, In the io.swagger.models.properties.Property class, the @JsonIgnore annotation is used in the getRequired property, so when we use swagger to display the document, the property is not there, causing our developers to read the document while docking. , do not know whether the attribute is a mandatory parameter, to fix

**Comment by dilipkrish** [comment]
While it does ignore the property, it is used to populate the list of required properties. It should have a required properties section on the model itself.

**Comment by xiaoymin** [comment]
thks，I found it later.
