### ISSUE TITLE
API grouper for specs

### ISSUE THREAD

**Issue by guilhermefarto** [springfox/springfox#2592]
Hello there.

I would like to know if it's possible to use an API grouper for specs, e.g.:

![image](https://user-images.githubusercontent.com/7007095/43523800-ebeafc5c-9573-11e8-898b-83748a03f7c8.png)

This is possible using a '<optgroup label="Measurement">' with the spec combobox.

Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

springfox-swagger2 - 2.8.0
springfox-swagger-ui - 2.8.0

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.
Please do consider ***starring*** this repository if you do like this project and find it useful. 
- [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494)

**Comment by dilipkrish** [comment]
@guilhermefarto Not out of the box. sorry

**Comment by guilhermefarto** [comment]
Alright, thank you! 👍
