### ISSUE TITLE
POST request with MultipartFile[] param creates a problem

### ISSUE THREAD

**Issue by suzana-djuricic** [springfox/springfox#2593]
I'm trying to integrate springfox into SpringMVC (v.5.0.5) application. 
I've seen there was issue with requests that looks like: 
```
@PostMapping("/fileUpload")
public MyObject uploadFiles(@RequestPart("attachments") MultipartFile[] attachments){....}
```
and it was solved at 235e074. 
Yet, there are issues:
With Springfox 2.9.2. when I try to reach **"/v2/api-docs"** ` java.lang.OutOfMemoryError: Java heap space` happens;
With Springfox 2.8.0. `java.lang.StackOverflowError at ...	 at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:84) ~[springfox-spring-web-2.8.0.jar:2.8.0]` happens in build time; but **"/v2/api-docs"** is reachable and returns json, but without post methods which contain **MultipartFile[]** as parameters.
Do you know what could be the cause of this behavior?
Thanks!

**Comment by dilipkrish** [comment]
Multipart files arent really supported. However, I'm not sure about the out of memory error.
