### ISSUE TITLE
Wrong string type with @RequestMapping and params

### ISSUE THREAD

**Issue by gionn** [springfox/springfox#2594]
Springfox 2.9.2, I've a controller method with:

```
    @ApiOperation ( value = "Retrieve Application Metrics filtered by Product ID" )
    @RequestMapping ( method = RequestMethod.GET, params = { "productId" } )
    public List<ApplicationMetricDTO> getAllByProduct( @RequestParam int productId )
```

ProductId get documented as `type: string`.

```
    "/applicationMetric{?productId}": {
      "get": {
        "tags": [
          "Application Metric"
        ],
        "summary": "Retrieve Application Metrics filtered by Product ID",
        "operationId": "getAllByProductUsingGET",
        "parameters": [
          {
            "name": "productId",
            "in": "query",
            "description": "productId",
            "required": true,
            "type": "string"
          }
        ],
```

Workaround is to explicitly define an ApiParam:

```
@ApiParam( value = "Filter by Product ID" , type = "integer" )
@RequestParam int productId
```

It looks like it have been reported in https://github.com/springfox/springfox/issues/1994 but I think that the java method parameter type should be taken in account to avoid wrong spec generation.

**Comment by dilipkrish** [comment]
@gionn agreed, however you dont need to specify `..params = {"productId"})` which is the cause of the workaround.

**Comment by gionn** [comment]
I am using params intentionally to let spring handle two different methods with the same http method and path (but different query params): the other one is a deprecated API annotated with hidden = true, that I need to support for backward-compatibility.

I have no idea why RequestMapping.params attribute is used by springfox: whatever I specify on params should have a corresponding @RequestParam as a method parameter hence it will get documentation, or maybe I am simply ignoring the value of such param?

Thanks.

**Comment by dilipkrish** [comment]
@gionn well you can also have params with values or have an expression like `!productId`, `productId=abc`, thats why it is converting that to a string

**Comment by gionn** [comment]
I will switch to the negated expression, didn't know such possibility. Thanks!
