### ISSUE TITLE
[Question] Is there a possibility to skip "Try it out" button?

### ISSUE THREAD

**Issue by KrzysztofPerchlicki** [springfox/springfox#2595]
I have a recent version of springfox-swagger-ui and springfox-swagger2 (2.9.2)

After click on specific endpoint element
![1](https://user-images.githubusercontent.com/17547300/43586468-ffdfab50-9667-11e8-9634-04e666080e9f.png)

I want to not must click on "Try it out" button
![2](https://user-images.githubusercontent.com/17547300/43586500-11aaff2e-9668-11e8-839d-59bfd7fdb0e2.png)

But instead to have Execute button available to click - just after clicking on endpoint element 
![3](https://user-images.githubusercontent.com/17547300/43586523-2280187a-9668-11e8-83dc-f3ed79a1e5a2.png)

Is this possible?

**Comment by ArchangelX360** [comment]
Super :D, do you mind closing this issue?

**Comment by ArchangelX360** [comment]
I can't :), either you or @dilipkrish can.

**Comment by KrzysztofPerchlicki** [comment]
Ow right - it's my first issue on github :D
So for now I close the topic - maybe when this'll be added in the future in swagger-ui I will create other to support that. Thanks
