### ISSUE TITLE
isssue with links and basepath

### ISSUE THREAD

**Issue by selvaebi** [springfox/springfox#2599]
Hi dilip , am facing issue with same zuul but different issue, the swagger is fine as i overrided  relative base path , but directly get the objects via curl or other means the base path is still the server context.

eg : zuul proxy - > http://localhost:8890/ega/ampt2d/propRegistry/
application url -> http://localhost:8890/ega/t2d/registry/
 overrided host and base path,

```java
return new Docket(DocumentationType.SWAGGER_2)
                .host("localhost:8890")
                .pathProvider(new RelativePathProvider(servletContext) {
                    @Override
                    public String getApplicationBasePath() {
                        return "/ega/ampt2d/propRegistry";
                    }
                })
                .select() 
```

swagger is fine [ Base URL: localhost:8890/ega/ampt2d/propRegistry ] http://localhost:8890/ega/ampt2d/propRegistry/v2/api-docs

but when i directly access localhost:8890/ega/ampt2d/propRegistry
i get 
```json
 {
  "_links" : {
    "phenotypes" : {
      "href" : "http://localhost:8890/ega/t2d/registry/phenotypes{?page,size,sort}",
      "templated" : true
    },
    "properties" : {
      "href" : "http://localhost:8890/ega/t2d/registry/properties{?page,size,sort}",
      "templated" : true
    },
    "profile" : {
      "href" : "http://localhost:8890/ega/t2d/registry/profile"
    }
  }
}
```

**Comment by dilipkrish** [comment]
You need to tell zuul proxy to use the x-forward headers

**Comment by selvaebi** [comment]
i added  ctx.addZuulRequestHeader("X-Forwarded-Prefix", "/"); still it appends the servlet context to the links

**Comment by selvaebi** [comment]
no i resolved by creating post filter in zuul to replace all the links having context path to relative path.
```
@Override
    public Object run() {
        try {
            final RequestContext requestContext = RequestContext.getCurrentContext();
            String responseBody = CharStreams.toString(new InputStreamReader(requestContext.getResponseDataStream(), "UTF-8"));
            responseBody = responseBody.replaceAll("/ega/t2d/", "/ega/ampt2d/");
            RequestContext.getCurrentContext().setResponseBody(responseBody);
        } catch (Exception e) {
            throw new RuntimeException("Error parsing response json");
        }
        return null;
    }

```

**Comment by dilipkrish** [comment]
Thats a great workaround, but that still seems like bandaid

**Comment by selvaebi** [comment]
yes but i am not sure i tried all possibilities the response links always contains the context path
