### ISSUE TITLE
Leading underscores being removed from generated Swagger documents

### ISSUE THREAD

**Issue by j2ro** [springfox/springfox#2600]
Please take the time to search the repository, if your question has already been asked or answered.

- What version of the library are you using? Is it the latest version? 
2.9.2

What kind of issue is this?

 - Question. Is this a question about how to do a certain thing?
 
 Is it possible to generate Swagger documentation on the fly in which variables contain an underscore as their first character (e.g. '_name')?

The issue I am having at the moment I am trying to render an API containing a field which starts with an underscore, but the underscore gets removed from the generated documentation.

e.g. 

If I specify the following in the Java model.

```private String _name;```

appears in the generated documentation as

```
{
    "name": "string"
}

**Comment by dilipkrish** [comment]
It depends on how you configure your object mapper. If you use getters and setters, it needs to reflect in your object mapper or in how the getters and setters are named.
