### ISSUE TITLE
swagger-2.9.1  /csrf is 404

### ISSUE THREAD

**Issue by hxiugangxh** [springfox/springfox#2603]
When I visit swagger-ui.html
It shows localhost:8080 404
and localhost:8080/csrf 404
But the function is normal
Anybody know why？
Let a great god teach me to solve it！

**Comment by RegisE** [comment]
Same problem in 2.9.2

**Comment by herowzz** [comment]
plus one

**Comment by dilipkrish** [comment]
I believe this ill be fixed when #2578 is fixed.

**Comment by alessiofiore** [comment]
The problem is still there in version 2.9.2. Any news about a fix?

**Comment by dilipkrish** [comment]
Can someone articulate what the problem is, as in steps to reproduce? It is unclear to me.

**Comment by blacelle** [comment]
@dilipkrish It seems swagger-ui.html, when loaded but without needing to click anywhere, does a GET on <root>/csrf (i.e. next to <root>/swagger-ui.html). It is unclear if one should implement this endpoint or not. By default, /csrf leads to a 404.

Here is a stack (swagger-ui.html has been moved in /admin in my case):
```

VM239:1 GET http://localhost:8080/admin/csrf 404
(anonymous)	@	VM239:1
(anonymous)	@	springfox.js?v=2.9.2:1
x	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
t.(anonymous function)	@	springfox.js?v=2.9.2:1
e	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
a	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
Promise.then (async)		
(anonymous)	@	springfox.js?v=2.9.2:1
x	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
t.(anonymous function)	@	springfox.js?v=2.9.2:1
e	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
n.getCsrf	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
x	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
t.(anonymous function)	@	springfox.js?v=2.9.2:1
e	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
x	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
t.(anonymous function)	@	springfox.js?v=2.9.2:1
e	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
Promise.then (async)		
e	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
window.onload	@	springfox.js?v=2.9.2:1
load (async)		
(anonymous)	@	springfox.js?v=2.9.2:1
r	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
r	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1
(anonymous)	@	springfox.js?v=2.9.2:1

```

**Comment by vl4d1m1r4** [comment]
From what I could figure out from the source code of  [swagger-ui](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/csrf.js) it can work without those endpoints. Basically it uses the base url to search in the html for a csrf meta information or if that fails it checks an endpoint `/csrf` to check for csrf token. As last the cookies are checked if some contains the XSRF-TOKEN value. It is kind of bad to see 404 errors, maybe there can be a configuration property to disable csrf checks?

**Comment by kjsebastian** [comment]
The reason its calling `/csrf` is because of the csrf support added in #2434

**Comment by h44z** [comment]
when will this problem be fixed?

**Comment by Josh-Zhen** [comment]
The problem is still there in version 2.9.2. Any news about a fix?

**Comment by misselvexu** [comment]
fixed ?

**Comment by f-koerner** [comment]
fixed?

**Comment by h44z** [comment]
I switched to https://github.com/springdoc/springdoc-openapi because this project no longer seems to be actively developed

**Comment by choudewh** [comment]
fixed?

**Comment by huguangjun580** [comment]
I have the sample problem.How to solve it?

**Comment by f-koerner** [comment]
> I have the sample problem.How to solve it?

https://stackoverflow.com/questions/55582023/when-loading-the-swagger-ui-html-page-a-request-is-made-to-hostport-and-host/61908204#61908204

**Comment by GavinSheng** [comment]
The problem is still there in version 2.9.2.
