### ISSUE TITLE
css not loading in Swagger (Or broken css in swagger)

### ISSUE THREAD

**Issue by naveret** [springfox/springfox#2604]
Styles or css no loading in Swagger ui.

I am using swagger (JAR: springfox-swagger-ui-2.7.0.jar) in my spring boot application. Swagger functionality is working fine but the css / styles not loading.
![endpoint](https://user-images.githubusercontent.com/42199701/43823909-df31c932-9af0-11e8-8892-30f6aa353347.PNG)

Can someone already faced the issue before? Also please share your thoughts in this

Thanks in advance

**Comment by dilipkrish** [comment]
Please use 2.9.2 of the library

**Comment by naveret** [comment]
Hi @dilipkrish , thanks for your quick response.
Updates: Didn’t work the solutions that you suggested.

I can see it working absolutely fine, when I am downgrading my java version to 1.8, and the issue is with Java-10. What do you think. Do you know anyway to manage this.
Thanks in advance.

**Comment by dilipkrish** [comment]
Oh @naveret, Im not too familiar with how java 10 works, its a class loader issue, in conjunction with spring support for java 10.

**Comment by harrshiil** [comment]
hey, @naveret did you find any solution for this. I am getting the same kind of error.

**Comment by Kuldeepr-meditation-live** [comment]
iiii
