### ISSUE TITLE
Cannot execute request after a path variable(param) is given at swagger ui

### ISSUE THREAD

**Issue by JackEggie** [springfox/springfox#2605]
I am not sure if it is a bug of swagger-ui or my misusage of it.

I have given a value for path variable which is required, and then I still cannot execute the request.here is the screen shot.

![2018-08-08_16-05-11](https://user-images.githubusercontent.com/8253572/43824710-5181371e-9b25-11e8-8af3-884d68946c28.png)

My code snippet is as follows:

```
	@ApiOperation(value="Get parameter by id", notes="Get parameter by id")
	@ApiImplicitParams({
			@ApiImplicitParam(name = "id", value = "Parameter id", required = true, dataType = "Integer", paramType="path")
	})
	@GetMapping(value = "/{id}")
	@ResponseBody
	public Parameter getParameter(@PathVariable Integer id) {
		return parameterBiz.getParameter(id);
	}
```

maven dependencies:

```
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>2.9.2</version>
			</dependency>

			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>2.9.2</version>
			</dependency>
```

**Comment by dilipkrish** [comment]
It seems you have a cached version of the javascript/ui. Can you refresh and try with 2.9.2

**Comment by JackEggie** [comment]
Sorry for not making sense.

I found this issue with the version 2.9.2 first and then I tried to downgrade the version one by one. I found this issue away when there was version 2.7.0.

Therefore, I don't think I have an old version issue. Could you help to check this, please?

**Comment by dilipkrish** [comment]
Whats causing your issue is `dataType = "Integer"`. There is no need for the implicit parameter annotation, but leaving it blank will do the same trick

**Comment by JackEggie** [comment]
Thank you. Maybe there is a better way to tell user `dataType ` is unnessesary here.

Anyway, it can work without `dataType = "Integer"` now.

**Comment by dilipkrish** [comment]
Its typically used for only complex types. Additionally if you may need to add the model to the additional models via the `docket.additionalModels(...)` api.
