### ISSUE TITLE
how to feed ready-made swagger.json  data to springfox ?

### ISSUE THREAD

**Issue by dreaminplus** [springfox/springfox#2607]
Now I have a ready-made swagger.json, how can I feed the json data to springfox.?
（Up to now, I paste it into swagger-editor for displaying the api operations）

**Comment by dilipkrish** [comment]
You need to can implement your [`SwaggerResourcesProvider`](http://springfox.github.io/springfox/docs/current/#aggregating-multiple-swagger-specifications-in-the-same-swagger-ui)
