### ISSUE TITLE
dropdown or selectfile are not displayed with consumes attribute in Mapping

### ISSUE THREAD

**Issue by mferlay** [springfox/springfox#2614]
Hi all, I haven't found a solution or an open issue on this subject so i do it.
I have 2 methods which use the same piece of code ::
@ApiParam(
          value = "possible values (not case sensitive): CSV, XML, JSON") 
      @RequestParam("contentType") EnumType contentType,

For one, the UI shows a dropdown and for the second, it shows a textarea. After many comparisons and tests, I have discovered that the difference was provoc by the attribute consume in the second::
@PostMapping(path = /URL, consumes = "multipart/form-data")

Do you have any idea why and how to solve it?

Best regards

**Comment by dilipkrish** [comment]
Could you share the swagger specification that is generated for the two endpoints?
