### ISSUE TITLE
Can I add a global custom business response code?

### ISSUE THREAD

**Issue by xiaoymin** [springfox/springfox#2618]
At present, the json data structure returned by /v2/api-docs mainly contains the attribute information of the documents' paths, tags, basePath, info, etc. However, in actual development, only the above attributes are not enough. Sometimes, the developer targets The self-encapsulated technical architecture generally has a custom response code for the restful interface. The response code is not a response code of http.
such as:
```java
SUCCESS("18200","SUCCESS"),
FAIL("18300","FAIL")
```

More of this kind of enumeration custom business response code, currently can not be displayed in the swagger document, causing some trouble for developers

So, whether the new version can add some custom features, or provide a developer-defined top-level interface, the developer can implement the relevant implementation class according to their own business, and then display it through the swagger document.

**Comment by dilipkrish** [comment]
You could always use the `@ApiResponses(@ApiResponse)` annotations to override the default behavior. Is that not working?

**Comment by xiaoymin** [comment]
I want to define some global business codes that are not HTTP response codes (e.g. 200, 404, 500) and that are custom business codes, and all interfaces of the system return a business code to the front end that tells them the current request. What does each business code mean?

So, I think I need a place that I can configure individually to configure global business encoding, just like swagger configures global request parameters in a token-like manner

**Comment by dilipkrish** [comment]
Global response messages do not work for you?

https://github.com/springfox/springfox/blob/a04d57b6ac14e5aa8703e8947f981ef97a873974/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L182-L199

**Comment by xiaoymin** [comment]
@dilipkrish 

This approach works, but what I want is the same configuration item as JWT permission validation. There is a separate configuration item, or menu item, not listed in each interface document response status code. It is a bit cumbersome to list, because the global business response code is common to all interfaces in this system, so I hope to have a separate menu.

**Comment by xiaoymin** [comment]
![image](https://user-images.githubusercontent.com/7894406/44762886-3ac33980-ab7b-11e8-906c-a87ace0ce6b4.png)

In the json configuration file of the current swagger response, we can see that including interface, class description, grouping, etc.

This global response code I think can also be listed here as a separate attribute.

maybe like this?
![image](https://user-images.githubusercontent.com/7894406/44763025-e53b5c80-ab7b-11e8-8389-71b9b3229765.png)

**Comment by dilipkrish** [comment]
Sounds like you want to make a change to the open api spec

**Comment by xiaoymin** [comment]
@dilipkrish 

I just considered this issue from the perspective of the swagger-ui user, so I didn't consider the open API specification.

If you are from the interface specification alone, you should not add this attribute.

Thank you very much for your answer and solved some of my doubts.

**Comment by minhnguyenvan95** [comment]
You can use this method to custom your description as markdown table
`
                .apiInfo(
                        new ApiInfoBuilder()
                                .description(apiInfoDescription())
                                .build()
                )

`



![Screenshot from 2019-12-03 10-14-35](https://user-images.githubusercontent.com/14316578/70017466-bfd6a300-15b5-11ea-815a-660a3401ce50.png)
