### ISSUE TITLE
Can you add some custom <li> items in the ApiInfo build?

### ISSUE THREAD

**Issue by kkrgwbj** [springfox/springfox#2619]
- [ ] Feature Request

Adding this original intention is also to be able to display our signature rules and precautions directly in it, so that you don't have to let the development look at the word. Something like this moved to swagger。
such as..
![image](https://user-images.githubusercontent.com/6836934/44125389-ec18648e-a064-11e8-819b-880b71ea37c6.png)

**Comment by dilipkrish** [comment]
@kkrgwbj sorry I dont understand what you meant. Could you explain in a different way perhaps?
