### ISSUE TITLE
examples in global definitions section

### ISSUE THREAD

**Issue by billal001** [springfox/springfox#2625]
Hi,

Not sure if this question's been answered,.
I am using springfox release version: 2.9.2 with SpringBoot and Swagger2,
What I want to achieve is to get the example in the global definitions section showing up like this:

```json
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "name"
  ],
  **"example": {
    "name": "Puma",
    "id": 1
  }**
}
```

Currenty, I am using the swagger annotation @ApiModelProperty(..), but it sets the example like this (within the properties field):

```json
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64",
      **"example": 1**
    },
    "name": {
      "type": "string",
      **"example": "adam smith"**
    }
  },
  "required": [
    "name"
  ]
}
```
Thanks,

**Comment by billal001** [comment]
I've tried implementing a ModelBuilderPlugin, here is the apply method:

`@Override
  public void apply(ModelContext modelContext)
  {
    
    Class<?> modelClass = forClass(modelContext);
    Field[] fields = FieldUtils.getAllFields(modelClass);
    JSONObject jsonExample = new JSONObject();
    Object obj;
    for (Field field : fields)
    {
      
      ApiModelProperty property = field.getAnnotation(ApiModelProperty.class);
      if (property != null)
      {
        obj = property.example();
        jsonExample.put(field.getName(), obj);
      }
    }
   modelContext.getBuilder()
        .example(jsonExample)
        .build();
}`

This didn't work, I've noticed that the ModelBuilderPlugin updates all the models rather than the model in the modelContext. Any ways of updating models separately?

**Comment by billal001** [comment]
@dilipkrish

**Comment by dilipkrish** [comment]
If you have a property that is a complex object you can specify [as shown here](http://springfox.github.io/springfox/docs/current/#q27)
