### ISSUE TITLE
Example value for non-JSON response

### ISSUE THREAD

**Issue by akibabu** [springfox/springfox#2628]
When you have RequestMapping signatures like 
`CompletableFuture<ResponseEntity<Double>>`
or
`CompletableFuture<ResponseEntity<String>>`

how do you give an example value? I can not wrap in a response and use @ApiModelProperty as it would create a json structure for the example.

The default example values rendered for String is "string" and 0 for Double

**Comment by dilipkrish** [comment]
You can use `ApiResponses` annotation. Is that not working?
