### ISSUE TITLE
Discovery of endpoints defined using the functional variant of Webflux in Spring Boot 2

### ISSUE THREAD

**Issue by jakobkylberg** [springfox/springfox#2632]
I'm trying out the combination of Spring Boot 2.0.4.RELEASE and Springfox 3.0.0-SNAPSHOT. Defining endpoints using a class annotated with `@RestController` and methods annotated with `@GetMapping` etc. works just fine. However, I'm unable to get endpoints defined using the new functional variant of Webflux to be picked up by Springfox. E.g.: 

```java
@Configuration
public class RoutingConfiguration {

    @Bean
    public RouterFunction<ServerResponse> routerFunction(final IntegerHandler integerHandler) {
        return route(GET("/api/integer").and(accept(APPLICATION_JSON)), integerHandler::getInteger);
    }

}
```

1. Is the functional variant of Webflux supported?
2. If so, how does one get Springfox to discover endpoints defined the functional way?

**Comment by dilipkrish** [comment]
@jakobkylberg yes it is supported, however you need to include the web flux dependency and also use the `EnableSwagger2Webflux` annotation. Sorry its still fresh of the oven, so the documentation is a little lacking.

**Comment by jakobkylberg** [comment]
Don't worry about the lack of documentation, I understand that it takes time to write it.

I tried to create a very simple project with Spring Boot 2.0.4.RELEASE and the latest Springfox 3.0.0-SNAPSHOT. With one endpoint using the functional variant of Webflux. I've added the EnableSwagger2Webflux annotation, but I can't get Springfox to recognize my endpoint. Repo for the test project: https://github.com/jakobkylberg/spring-boot-2-webflux-swagger 

If someone can have I quick look it would be very appreciated, maybe I'm missing something obvious.

**Comment by ye1984** [comment]
Hi @jakobkylberg , did you find a solution, because I have the same issue.

With restcontroller, OK, but with functional way, Swagger don't recognize the endpoint.
Thanks,

**Comment by jakobkylberg** [comment]
@ye1984 Unfortunately I haven't been able to find a solution. I created a test project that highlights the issue and posted a link to it in my last post, but I haven't been able to make any progress solving the issue.

**Comment by dilipkrish** [comment]
@jakobkylberg thank you for putting together a sample. I'll take a look at it

**Comment by kimec** [comment]
You can still declare your endpoint definitions manually as a workaround via `ApiListingScannerPlugin` implementation.
When using `RouterFunction<ServerResponse>` API, patterns are stored in private fields inside predicates therefore I don't think it's going to be easy or even possible for springfox to extract the required metadata from those.
Maybe springfox could have some decorator that would collect the metadata at call site prior to passing them to  `RouterFunction<ServerResponse>` API.
This will not solve path parameters though, since you are supposed to extract them imperatively/manually from `ServerRequest` by your self. Same goes for request body for which you need to use `ServerRequest#bodyToMono(Class)`.
But I may be wrong.

**Comment by ajayv1986** [comment]
@dilipkrish - Just checking if there was an update on this for the functional endpoint. Any feature branch or sample of what @kimec suggested would help

**Comment by iamrdn** [comment]
> @jakobkylberg thank you for putting together a sample. I'll take a look at it

Hi @dilipkrish, thanks for the Springfox, But I am still facing same issue with functional endpoints. Is there any patch release for that. Please let me know anyone found any solution for this.?

@jakobkylberg did you find any solution for this..? Please help me to get out of this issue.

**Comment by farzer** [comment]
same issue

**Comment by aravindbargurhiriyannaiah** [comment]
Hello @dilipkrish Did you get a chance to look into why the repo posted by @jakobkylberg  isn't showing up on the Swagger UI? (Spring webflux, Routes instead of the regular controllers?)

**Comment by vlademaksimovic** [comment]
same issue

**Comment by rajeevprasanna** [comment]
any update on this?

**Comment by nicolas2lee** [comment]
Same issue. Any update ?

**Comment by jonasbark** [comment]
While it would be possible to put the list of routing paths in the swagger there is no way to get route parameters. Reason is that those are read at runtime and aren't defined using annotation that can easily be parsed from Springfox.

So Springfox would be pretty useless here.

**Comment by nicolas2lee** [comment]
> While it would be possible to put the list of routing paths in the swagger there is no way to get route parameters. Reason is that those are read at runtime and aren't defined using annotation that can easily be parsed from Springfox.
> 
> So Springfox would be pretty useless here.

I agree, but it is a pity that we cannont use functional handler.
At least, I suggest springfox should support some manual annotation to support the swagger documentation for theses who did not want to using traditional mvc

**Comment by homeofthewizard** [comment]
Is there a date on which you plan to deliver a fix for the issue ?
the work is ongoing or abondonned ?

**Comment by gvsandeep2647** [comment]
Will this be resolved?
Any suggestions on how should one go about setting up auto documentation for his Spring Webflux project?

**Comment by ronansayao** [comment]
Is there any updates on this?

**Comment by mesut** [comment]
any update on this ? Any workaround solutions are welcome.

**Comment by ronansayao** [comment]
> any update on this ? Any workaround solutions are welcome.
@mesut 
I fix this using open-api, Does it work for you?
https://github.com/springdoc/springdoc-openapi-demos

**Comment by mesut** [comment]
Thank you very much @ronansayao

**Comment by dilipkrish** [comment]
This isn't supported yet. It requires additional work to support it without creating an annotation hierarchy like springdocs does it. I'll see if it can be worked on in the 3.0 release, if not it will be only in 3.1, unless someone here has bandwidth to help out.

**Comment by asuri3** [comment]
@dilipkrish what's the tentative date of 3.0 release?

**Comment by dilipkrish** [comment]
Hopefully next week. if there aren't any unforeseen bugs

**Comment by bhumir81** [comment]
why is this closed and not sure if it is solved?

**Comment by chamithchathuka** [comment]
Is this feature added?
https://stackoverflow.com/questions/68266480/springboot-springfox-starter-3-0-0-unable-to-detect-webflux-routerfuntion
