### ISSUE TITLE
How disable csrf?

### ISSUE THREAD

**Issue by alexeyvip** [springfox/springfox#2633]
I use io.springfox:springfox-swagger2:2.9.2 in gradle project. I have API with BASIC authentication. I exclude some URNs for swagger:
```
@Override
public void configure(WebSecurity web) {
    web.ignoring().antMatchers("/v2/api-docs", "/swagger-resources/**",
        "/swagger-ui.html", "/webjars/**", "/null/swagger-resources/configuration/ui");
}
```
But then i open http://localhost:8080/swagger-ui.html i see authentication dialog twice because springfox.js try loads this resources:
![_999 1467](https://user-images.githubusercontent.com/1677013/44397007-35883e00-a52e-11e8-805f-ce7b04559cb6.png)
How i can disable it?

**Comment by dilipkrish** [comment]
@alexeyvip as @olOwOlo this is a result of assuming CSRF protection.

**Comment by alexeyvip** [comment]
Wow, it's need feature  :)

**Comment by minhnguyenvan95** [comment]
1

**Comment by skarpushin** [comment]
So.... How to disable it?

**Comment by fyerte** [comment]
jo puta, contesta que me quedo con las ganas
