### ISSUE TITLE
Question/Bug: Path-Parameter should be specified as required when @RequestMapping has multiple paths.

### ISSUE THREAD

**Issue by raghavkeesara** [springfox/springfox#2634]
Springfox Swagger version 2.9.2

when Request Mapping has multiple paths like this.
```
 @ApiOperation(value = "Creates a client application")
 @RequestMapping(method = POST,
        value = {
            "path1",
            "path2/{optionalSamplePathParam}/path"
        },
        produces = APPLICATION_JSON_VALUE)
public Response someControllerMethod(@PathVariable optionalSamplePathParam, @RequestBody someObject)
{
//some code within ApiOperation
}
```

Swagger UI though shows 2 different listing for each of the path, it still shows **_SamplePathParam_** in listing of "**_path1_**" where it is not applicable, It should ideally not show that at all. 

What is the solution or work-around for this?

**Comment by dilipkrish** [comment]
@raghavkeesara this is a result of #2220. I believe the behavior is correct as it was fixed.

**Comment by dilipkrish** [comment]
No there isnt unfortunately. Not to say that it wont be fixed, but at the moment that is the level of support that we have for multiple request mapping paths
