### ISSUE TITLE
About Apiparams a little suggest of swagger

### ISSUE THREAD

**Issue by poppycokey** [springfox/springfox#2635]
Sometime,When I define an interface parameter.I found that some fields of the entity class are not required.like this ↓
 `@RequestMapping(value = "/update", produces = {"application/json;charset=UTF-8"})
   public void update(@RequestBody Book param) {}`
But I only need a few fields in the entity,How do I hide the other fields.Do I have to define a new entity? That's a hassle.

**Comment by dilipkrish** [comment]
@poppycokey yes atleast until we get #2056 merged.
