### ISSUE TITLE
SwaggerUI blank PDF download

### ISSUE THREAD

**Issue by charunagpal** [springfox/springfox#2636]
SwaggerUI  is downloading blank PDF.
I am using springfox-swagger-ui 2.7.0

if i use produces={"application/pdf"} in @RequestMapping .I am able to download the pdf and get the content of it as well

But my end point supports all content type .I don't want to restrict my method by adding produces.
Can you please provide some insight here.Why swaggerUI is downloading blank PDF ?

Thanks,
Priyanka

**Comment by dilipkrish** [comment]
Swagger ui needs to specify an Accept header for it to request a PDF. This is typically possible by using the produces

**Comment by charunagpal** [comment]
Adding produces restrict my functionality.I am looking for solution where i can download any type of document .Is it not possible with swaggerUI?
or if i upgrade to latest version 2.9.2 is it going to  work without adding produces also.Please advice?

**Comment by charunagpal** [comment]
Even if i tried using multiple produces something like produces = {"application/*","application/json"}
this is also not working with swaggerUI.

**Comment by dilipkrish** [comment]
You need to at the very least have application/json and application/pdf in your produces list

**Comment by Ankitsinghalatjolly** [comment]
This is still a issue, I can see a valid file from postman but a blank one from swagger.
