### ISSUE TITLE
Hide "Models" section 

### ISSUE THREAD

**Issue by dtitov** [springfox/springfox#2637]
Hi! Is it possible to hide the "Models" section that appears at the bottom of the generated Swagger UI page? I use model classes in a bit "hacky" way - to generate sample responses for my endpoints - so it's not a real model, so to speak. That's why I don't want it to be displayed on a page.

**Comment by dilipkrish** [comment]
@dtitov unfortunately no there isnt.

**Comment by LilSebastian5000** [comment]
@dilipkrish Can this be a planned feature in the future? I would like to hide mine as well, our only needs for the API is for testing endpoints. We use JAXB to generate many objects in our requests which inundates the "Models" section with a lot of object data we don't care about

**Comment by dilipkrish** [comment]
There are ways to tailor the models accordingly. An example is probably in order here

**Comment by dtitov** [comment]
I mean... It should be quite simple to introduce some kind of a flag just to not render that HTML section. It doesn't seem to be a complicated solution. I'm not into implementational details though...

**Comment by dilipkrish** [comment]
@dtitov sure there might be, however that is not part of this project. 
Thank you for reporting. That  is an issue that belongs to the [Swagger-ui](https://github.com/swagger-api/swagger-ui) project.
