### ISSUE TITLE
@Deprecated annotation on class(Controller),the view does't show deprecated tag （horizontal line）

### ISSUE THREAD

**Issue by wdyun** [springfox/springfox#2638]
- [ ]I use the 2.8.0 and also try the latest version  [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion) 

What kind of issue is this?

 - [ ] Feature Request. 
@Deprecated annotation on the method can work mark the method deprecated tag, like 
![image](https://user-images.githubusercontent.com/11865618/44583605-8d49d200-a7d8-11e8-9c9b-b70ec297833f.png)
but @Deprecated on the Class level, does't work.

**Comment by dilipkrish** [comment]
thanks for reporting @wdyun!

**Comment by wdyun** [comment]
Will you support this feature? Expected your reply， thank you @dilipkrish ！

**Comment by dilipkrish** [comment]
Yes absolutely. Would love for a PR

**Comment by v3rtumnus** [comment]
Hi, I am new to the project and just added a PR for that. Please feel free to tell me if I missed something

**Comment by dilipkrish** [comment]
@v3rtumnus thank you for your PR. Will review shortly and pull it in!
