### ISSUE TITLE
Springfox swagger UI new version

### ISSUE THREAD

**Issue by CaptainAgilek** [springfox/springfox#2640]
Latest Springfox Swagger UI which Is version 2.9.2 uses not latest version of 
Swagger UI but IT uses version 3.17.1 where is this bug. https://github.com/swagger-api/swagger-ui/issues/4817#issue

My question Is when will be new version of Springfox available which will use more recent version of Swagger UI? 
Thanks

**Comment by dilipkrish** [comment]
Will get the latest when 3.0.0 is released
