### ISSUE TITLE
Some Spring 5 types should be hidden

### ISSUE THREAD

**Issue by drenda** [springfox/springfox#2642]
I'm using the last 3.0 snapshot and I've and endpoint like this:

```
@GetMapping(path = "/loggedAgent")
	public ResponseEntity<?> loggedAgent(Locale locale, PersistentEntityResourceAssembler resourceAssembler) {
		CustomUserDetail loggedUser = SecurityUtils.getLoggedUser();
		Agent loggedAgent = agentRepository.findByUsername(loggedUser.getUsername());

		if (loggedAgent != null)
			return new ResponseEntity<>(resourceAssembler.toResource(loggedAgent), HttpStatus.OK);
		throw new ResourceNotFoundException(ExceptionCode.RESOURCE_NOT_FOUND, "");
	}
```
In my application I'm using Spring (Spring MVC, Spring Data REST); `locale `and `resourceAssembler` are two parameters injected by Spring and they should not be displayed in Swagger.

Instead I see this. 

![error](https://user-images.githubusercontent.com/3420646/44667926-6c71be80-aa1c-11e8-82af-eb2eece65ed8.png)

If the method has some real addition parameter, then `locale `and `resourceAssembler` are not displayed anymore.

As mentioned [here ](https://github.com/springfox/springfox/issues/1773#issuecomment-416263317) a temporary solution is to call `.ignoredParameterTypes(Locale .class, PersistentEntityResourceAssembler .class)` from the `Docket`.

**Comment by eximius313** [comment]
Also remember about `AuthenticationPrincipal.class` and `ServerWebExchange.class`

**Comment by goodlifeinc** [comment]
I also notice extra parameters being shown on actuator endpoints

**Comment by dilipkrish** [comment]
Thank you all for the feedback! Keep them coming here!
