### ISSUE TITLE
Limiting model properties per API

### ISSUE THREAD

**Issue by dmcgeown-deveire** [springfox/springfox#2643]
Hi, thank you for implementing this fantastic library. Its brilliant but I've spent the best part of a day figuring out if it is possible to limit model properties for specific API endpoints. Consider the following basic Account.java model represented in JSON

{
  "firstName": "Joe",
  "lastName": "Bloggs",
  "roles": [{"authority": "ROLE_ADMIN"}, {"authority": "ROLE_USER"}]
}

Assuming I have two API endpoints (lets say /api/accounts and /api/accounts/123), is it possible to configure springfox (via annotations) to not return the roles property for just ONE of the above APIs. I know I can annotate it with @JsonIgnore or @ApiModelProperty(hidden=true) but that makes the property invisible to all API response. Is it possible to limit it on an API endpoint basis?

**Comment by dilipkrish** [comment]
@dmcgeown-deveire that is exactly the feature that @MaksimOrlov has been working on in #2056

**Comment by dmcgeown-deveire** [comment]
@dilipkrish thx. I’ll keep an eye on this ticket.
