### ISSUE TITLE
Wrong example for text/uri-list mime type in @ManyToMany and @OneToMany associations

### ISSUE THREAD

**Issue by predrag-viceic** [springfox/springfox#2647]
Hello,

I'm heavily using Springfox 3.0.0-SNAPSHOT with Spring data rest extension. There is a bug in how the example is created for MIME type text/uri-list.

Currently for the ``@ManyToMany`` and ``@OneToMany`` collection associations, appending new elements to the association collection is done with POST-ing a text/uri-list of associations URIs, and replacing of the elements in the association collection is done with PUTing the text/uri-list.

As per RFC-2483 (https://tools.ietf.org/html/rfc2483#section-5) text/uri-list is a list of newline character separated URIs.

Currently the schema generated is:

```json
schema": {
    "type": "array",
    "items": {
        "type": "string"
    }
}
```

which results in a following auto-generated example :

```json
[
  "string"
]
```

I would expect this to be shown as

```
"uri"
"uri"
```

instead.

**Comment by dilipkrish** [comment]
Is this a combination of what swagger 2.0 supports and a swagger-ui thing?

**Comment by predrag-viceic** [comment]
Not sure who's generating the examples, but you're probably right, it's should be swagger core. I see it being added here by springfox:

https://github.com/springfox/springfox/blob/32719ab582ad923651a2c7a4a0c7eff54473c19a/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/EntityAssociationSaveExtractor.java#L60

I dont' know if this is the issue, but SDR accepts only text/uri-list on association collection:

https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.association-resource

and not SPRING_DATA_COMPACT_JSON.
