### ISSUE TITLE
For Token Authorization to work need to specify authorizations = { @Authorization(value="Authorization") }

### ISSUE THREAD

**Issue by ngawor** [springfox/springfox#2661]
Using swagger2-2.9.2 and swagger-ui-2.9.2:

Previous token authentication stopped working from 2.5 (the token is no longer being passed).  In order to resolve this, I had to add:

authorizations = { @Authorization(value="Authorization") }

to every method I wanted to pass the token.  This wasn't necessary in previous versions, and my code did not change.

I see some discussion of this here:
https://github.com/springfox/springfox/issues/2194

but it is marked closed.

**Comment by ngawor** [comment]
This worked - thank you @selvaebi !  I think the documentation needs to be updated to reflect this is necessary.

**Comment by MartinTopchyan** [comment]
@ngawor  can you send me your swagger configuration?? the same bug in my swagger  but my conf does not work

**Comment by selvaebi** [comment]
Hi @MartinTopchyan the above config will work perfectly , can you paste ur config , let we check we can help.

**Comment by MartinTopchyan** [comment]
ApiInfo apiInfo() {
    return new ApiInfoBuilder()
        .title("")
        .description("")
        .termsOfServiceUrl("")
        .version(this.projectVersion)
        .contact(new Contact("", "", ""))
        .build();
  }

  @Bean
  public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2)
        .select()
        .apis(RequestHandlerSelectors.basePackage(""))
        .paths(PathSelectors.any())
        .build()
        .enable(true)
        .apiInfo(apiInfo())
        .securitySchemes(Arrays.asList(apiKey()))
        .securityContexts(Arrays.asList(securityContext));
  }

  private ApiKey apiKey() {
    return new ApiKey("apiKey", "Authorization", "header");
  }

  SecurityReference securityReference = SecurityReference.builder()
      .reference("Authorization")
      .scopes(new AuthorizationScope[0])
      .build();

  SecurityContext securityContext = SecurityContext.builder()
      .securityReferences(Arrays.asList(securityReference))
      .build();
This is my swagger config

**Comment by MartinTopchyan** [comment]
@selvaebi

**Comment by selvaebi** [comment]
ahh the reference name should match , change to SecurityReference.builder()
.reference("apiKey") or new ApiKey("Authorization", "Authorization", "header");

**Comment by MartinTopchyan** [comment]
@selvaebi  am I understand you right??
SecurityReference securityReference = SecurityReference.builder()
      .reference("apiKey")
      .scopes(new AuthorizationScope[0])
      .build();

**Comment by dilipkrish** [comment]
Thanks everyone for jumping in to answer questions! I'll add a note to document it. Would anyone of you have the bandwidth to help with a PR to help with documenting it?
