### ISSUE TITLE
Model Scene

### ISSUE THREAD

**Issue by ChiBenshuo** [springfox/springfox#2662]
- [ ] The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

 - [ ] Feature Request.

*********************************
I'm not good at English.
I hope the swagger can add the attribute "scense".
e.g.
I have the following apis.
 [post api/users].
  The model of request body is 
  {
     "name":"hello",
     "phone_no": "541123"
  } 

 [put api/users/{id}].
  The model of request body is 
  {
     "name":"hello"
  } 
 The "phone_no" can't be used.
Because  modifying "phone_no" is through api[put /api/users/{id}/phone_no].

For  [post api/users] and  [put api/users/{id}],I want to define one model.I hope the @ApiModelProperty and @ApiOperation to add  "scene" attribute.

**Comment by XQDD** [comment]
Same to me, some method need hide the model property but some needn't. I can't find something like json view or validation group

**Comment by dilipkrish** [comment]
This isnt currently possible until we merge #2056

**Comment by jawwadfarooq** [comment]
> This isnt currently possible until we merge #2056

Any expected date of releasing a new version with this fix?

**Comment by Splash34** [comment]
+1
