### ISSUE TITLE
2.8.0: can't disable default http StatusCodes at method level

### ISSUE THREAD

**Issue by jtviegas** [springfox/springfox#2664]
For instance, with class level responses as a default for the included methods:

```
...
@RequestMapping(value = "/api/carriers")
@Api(tags = { "carriers" }, value = "API root for carrier related functions.")
@io.swagger.annotations.ApiResponses(value = {
    @ApiResponse(code = 400, message = "Invalid status value", response = void.class),
    @ApiResponse(code = 500, message = "Internal server error", response = void.class) })
...
```
and then additionally in the method:
```
...
  @RequestMapping(method = RequestMethod.POST)
  @ApiOperation(value = "Creates a new carrier", notes = "", response = void.class)
  @io.swagger.annotations.ApiResponses(value = {
      @ApiResponse(code = 201, message = "successful operation", response = void.class),
      @ApiResponse(code = 422, message = "validation failure", response = void.class),
      @ApiResponse(code = 409, message = "uniqueness violation", response = void.class) })
  public ResponseEntity<Void> postCarrier(
...
```
...also config is disabling default codes:
```
...
@Bean
  public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2).securityContexts(securityContext()).useDefaultResponseMessages(false)
        .select().apis(RequestHandlerSelectors.any()).paths(PathSelectors.any()).build();
  }
...
```
...we should be seeing 201, 400, 409, 422 and  500, but we always also see the 200 there, for some reason:
![image](https://user-images.githubusercontent.com/3536754/40107298-c9f18dd4-58ef-11e8-8fc3-07cc7da2ef5a.png)

... are you also seeing this?

**Comment by Krokogator** [comment]
Add 
`@ResponseStatus(HttpStatus.CREATED)`
This will replace default 200 code

**Comment by dilipkrish** [comment]
@Krokogator thanks for jumping in. While that works, someone in the forum mentioned that it isnt accurate to use that solution.

this seems like a good feature to have. Thanks for reporting @jtviegas

**Comment by AlphaHinex** [comment]
I found `springfox.documentation.spring.web.readers.operation.ResponseMessagesReader#httpStatusCode` add default `200` code as below 
```
  public static int httpStatusCode(OperationContext context) {
    Optional<ResponseStatus> responseStatus = context.findAnnotation(ResponseStatus.class);
    int httpStatusCode = HttpStatus.OK.value();
    if (responseStatus.isPresent()) {
      httpStatusCode = responseStatus.get().value().value();
    }
    return httpStatusCode;
  }
```
and as @Krokogator said, add `@ResponseStatus(HttpStatus.CREATED)` will replace default code.

So I'm curious about 
> someone in the forum mentioned that it isnt accurate to use that solution
@dilipkrish could you provide the forum link to find some details?
