### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by figueroaRicardo** [springfox/springfox#2665]
What version of the library are you using? 
 [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

there is a typo in the docs
![image](https://user-images.githubusercontent.com/41128440/45231324-41dffb00-b291-11e8-92c4-22935c2bc46f.png)

**Comment by dilipkrish** [comment]
Fixed via #2666 

Thanks @figueroaRicardo
