### ISSUE TITLE
Change type of API Parameter for Springfox

### ISSUE THREAD

**Issue by bqcuong** [springfox/springfox#2667]
I'm using Springfox version 2.9.2. 
I use a custom request processor (detected by annotation `@DTOMapping`) for pre-processing every request parameters to API, maping DTOs from requests to Entities.

Springfox is now recognizing `Submission` as API parameter but I want `SubmissionCreateDTO` and `SubmissionUpdateDTO`.

Please tell me how can I do it?

```
    @PostMapping
    @ApiOperation("Create submission")
    public ResponseEntity<? extends OASResponse> create(@DTOMapping(SubmissionCreateDTO.class) Submission submission) {
        return ResponseFactory.ok(submissionService.create(submission));
    }

    @PutMapping
    @ApiOperation("Update submission")
    public ResponseEntity<? extends OASResponse> update(@DTOMapping(SubmissionUpdateDTO.class) Submission submission){
        return ResponseFactory.ok(submissionService.update(submission));
    }
```

**Comment by dilipkrish** [comment]
Simliar [to this](http://springfox.github.io/springfox/docs/current/#q27). In addition you may also need to add the DTOs to additional models
