### ISSUE TITLE
Adding Default Parameters at ApiSelector level

### ISSUE THREAD

**Issue by snithish** [springfox/springfox#2669]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? **2.9.2**

What kind of issue is this?
 - [x] Feature Request

Adding ability to specify operation parameters at `ApiSelector`. 

**Usecase:**
1. Micro-service has both authenticated and unauthenticated endpoints.
2. Only authenticated endpoints are required to have a `accessToken` as a default header parameter.
3. I believe this can not be done at a `ApiSelector` level as of now.
4. Hence to avoid this problem we end up creating separate `Docket`, one for authenticated another for  unauthenticated endpoints.

PS. Do let me know a solution already exists and I am not seeing it.

**Comment by dilipkrish** [comment]
If you use the standard security settings you can describe your apis in terms of security settings alone.

**Comment by snithish** [comment]
Unfortunately we don't use standard security settings. I was wondering we had anything along on the lines of `ParameterBuilderPlugin` but the annotation will be at the class level rather than at the method level.

**Comment by snithish** [comment]
Thanks, the example is very helpful.
