### ISSUE TITLE
How to properly annotate and present return ResponseEntity<Map>

### ISSUE THREAD

**Issue by sam2099** [springfox/springfox#2671]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
spring boot 2.0.3.RELEASE,  springfox 2.9.2

What kind of issue is this?

 - [x] Question. 
How to properly annotate and present the detail of return ResponseEntity`<`Map`>`?
Such as below , how can i present Responses detail , something like "{"jwt": "xxxxxxxxxxx",  "accessToken":"xxxxxxxxxxx"}"

controller
```
@PostMapping(value = "/s/login")
@ApiOperation(value = "第三方登录 - 授权", response = Map.class)
public ResponseEntity<Map> login() {
        ......
        HashMap<String, String> result = new HashMap<>();
        result.put("jwt", "xxxxxxxxxxx");
        result.put("accessToken", "xxxxxxxxxxx");
        return ResponseEntity.ok(result);
}
```

**Comment by fein91** [comment]
it's not working for me. Tried:

```java
    @RequestMapping(value = METHOD_GROUP_NAME, method = GET)
    @ApiOperation(value = "get permission", notes = "get permissions")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "permissions",
            examples = @Example(value = @ExampleProperty(mediaType = APPLICATION_JSON, value ="{\"test\":[\"test\"]}")))})
    public Map<String, List<String>> permissions(@ApiParam(value = "name", required = true, example = "profile")
                                                     @PathVariable("groupName") String groupName) {
        return service.permissions(groupName);
    }
```

**Comment by lcl1992421** [comment]
It doesn't work for me either. I copied your code directly
Has anyone solved this problem?
`@RestController
public class TestController {
    @RequestMapping(value = "/1570", method = RequestMethod.POST)
    @ApiOperation(value = "Demo using examples")
    @ApiResponses(value = {@ApiResponse(code = 404, message = "User not found"),
            @ApiResponse(
                    code = 405,
                    message = "Validation exception",
                    examples = @io.swagger.annotations.Example(
                            value =  {
                                    @ExampleProperty(
                                            mediaType = "Example json",
                                            value = "{\"invalidField\": \"address\"}"),
                                    @ExampleProperty(
                                            mediaType = "Example string",
                                            value = "The first name was invalid")}))})
    public void saveUser() {
        //No-op
    }
}`

then i got this result：
`"paths": {
    "/1570": {
      "post": {
        "tags": [
          "test-controller"
        ],
        "summary": "Demo using examples",
        "operationId": "saveUserUsingPOST",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "*/*"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "User not found"
          },
          "405": {
            "description": "Validation exception"
          }
        },
        "deprecated": false
      }
    },`
