### ISSUE TITLE
directModelSubstitute and docket specific request params

### ISSUE THREAD

**Issue by rahulaga** [springfox/springfox#2675]
Using spring fox 2.8.0 with spring boot.

This is a question. I am trying to create different swagger pages for internal and external APIs. I have created two dockets with different selectors and so far so good. The question I have is that for certain APIs I have different request/response types for internal vs external.
 
For example:
```
PagedResponse<AbstractResponse> getFoo(@RequestParam(value="param1") param1,
@RequestParam(value="param2") param2)
```

I this case I have two `InternalResponse` and `ExternalResponse` that extend the `AbstractResponse` and also I want to limit `param1` to internal and `param2` to external

I am using the `directModelSubstitute` and it works well if the method is `AbstractResponse getFoo...` but not with the `PagedResponse<AbstractResponse>` Any help on how I could do this? 

Also second question how do I assign a `@RequestParam` to a particular docket group name?

Any help will be much appreciated.

**Comment by rahulaga** [comment]
To answer the first part of my own question, I am able to successful configure this using `docket.alternateTypeRules` 

So the only question I have now is how I can filter certain `@RequestParam` to specific dockets?

**Comment by dilipkrish** [comment]
@rahulaga this is an interesting situation. There is no support for this yet. Would be a great feature addition

**Comment by rahulaga** [comment]
Ok, thanks @dilipkrish
