### ISSUE TITLE
springfox cannot distinguish type `List <Byte>`

### ISSUE THREAD

**Issue by huyuechy** [springfox/springfox#2677]
When the parameter tye is  `List <Byte>` like:
`public RestResult getIndexStatistics(List<Byte> bytes) {return null;}`

the swagger ui  show the type is "string($byte)"。
While I change the type to "Integer",
the swagger ui  show the type is  "array[integer]",that is the right result.
Can swagger ui distinguish type ”byte“ and convert   `List <Byte>` to array?

**Comment by dilipkrish** [comment]
List of bytes are interpreted as string, but you can create a rule to make that not be the case using alternate type rules

**Comment by huyuechy** [comment]
> List of bytes are interpreted as string, but you can create a rule to make that not be the case using alternate type rules

How Can I do is ?Can you give me an example?

**Comment by dilipkrish** [comment]
After some research it appears this is a possible enhancement/bug

https://github.com/springfox/springfox/blob/a04d57b6ac14e5aa8703e8947f981ef97a873974/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ParameterMapper.java#L75-L81
