### ISSUE TITLE
Springfox stop working with wrap-root-value

### ISSUE THREAD

**Issue by cristianoperez** [springfox/springfox#2679]
swagger-ui stop working when i add the follow configuration to application.properties
`spring.jackson.serialization.wrap-root-value=true`

```
Unable to infer base url. This is common when using dynamic servlet registration or when the API is behind an API Gateway. The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/. Please enter the location manually: 
```

springfox-swagger2 - 2.9.2
springfox-swagger-ui - 2.9.2
spring-boot - 2.0.5.RELEASE

**Comment by dilipkrish** [comment]
This is a long standing issue #597 that isnt supported. Closing this as a dupcliate
