### ISSUE TITLE
the meaning of allowableValues

### ISSUE THREAD

**Issue by orientzc** [springfox/springfox#2680]
springfox-swagger2: 2.8.0 & 2.9.2
springfox-swaggerui: 2.8.0 & 2.9.2

Q1:
i try to use @allowableValues to describe the range of params, but it is not shown in ui. and i find that the swagger json of @allowableValues in version 2.8.0 is both and maximum and minimum, and the param is limited by the @allowableValues. such as the param number, @allowableValues is range[1,10], and when using "try it out" in ui and the param is seted 11, it will not execute because of the range.
but in version 2.9.2, it is both maxlength and minlength and the param is not limited.

but i think @allowableValues is just description of params, and it should not limit the real use to param.
and it should just be shown in ui.
Q2:
i find the way to show the length of params, such as the param number, the length is 32. i know it works with @descriprion, but i want to know what special way to solve it.

what do i miss?
Thanks.

**Comment by dilipkrish** [comment]
> but i think @allowableValues is just description of params, and it should not limit the real use to param. and it should just be shown in ui.

That is something we dont control, you'd have to ask that question in [Swagger-ui](https://github.com/swagger-api/swagger-ui)

I dont follow the second question.

**Comment by orientzc** [comment]
Thanks. but i really want to know the real meaning of @allowableValues.  it is not match the description of Q2? they are different? the @allowableValues is not used to describe the length, for example, the length of params is 32?
Thanks very much.

**Comment by orientzc** [comment]
@dilipkrish Could you help me understand correctly?
