### ISSUE TITLE
Is it possible to filter parameters in Springfox dynamically?

### ISSUE THREAD

**Issue by abhi4151** [springfox/springfox#2691]
Hi Team,

I need support for using SwaggerSpecFilter. I googled so much but didn't find any working example for SwaggerSpecFIlter.

I'm using SpringBootFramework 1.5.15.

SwaggerCore - 1.5.14

Any Snippet please?

I tried but SwaggerSpecFIlter is not even invoked. I also set the filter in FilterFactory.

I'm using Springfox for Swagger Documentation.

Is it possible to filter parameters in Springfox dynamically?

**Comment by Antoniossss** [comment]
Its straightforward - You have 10 conditions you want swagger to list only some of them, and different on other conditions. It was possible  with swagger core using SwaggerSpecFIlter
