### ISSUE TITLE
Filter apis() using custom RequestHandlerSelectors

### ISSUE THREAD

**Issue by rahulaga** [springfox/springfox#2692]
This is a question. Using Springfox 2.7.0

I am trying to create multiple docs ("internal" and "external" and few more) from the same code. Some apis are part of all while some should only show in certain ones. I see `RequestHandlerSelectors` and I can create a custom annotation and using that I can do a **boolean** selection (`withMethodAnnotation`).

What I would like to do is have an annotation such as:
```
public @interface QualifiedMapping {
    public enum Qualifiers {
        FOO, BAR, BAZ;
    }

    Qualifiers[] value();
}
```
So I can annotate my method as:
```
@QualifiedMapping({Qualifiers.FOO, Qualifiers.BAR})
```

Now how do I author the `RequestHandlerSelectors` so that I can restrict the correct mappings to each of the dockets? (Each of Foo, Bar, Baz is its own docket). If I don't annotate this then it applies to all dockets. I would appreciate any guidance.

Thanks

**Comment by dilipkrish** [comment]
you can create your own Predicate that handles this. In 2.9.2 you can use

`RequestHandler.findAnnotation` to find that annotation and create a predicate that results in a  true or false to your liking

**Comment by Antoniossss** [comment]
I want to filter in runtime - not only on bootstrap. Reason behind this is that depending on user credentials, different endpoints might be listed.
