### ISSUE TITLE
When routing through a proxy server the wrong hostname is used

### ISSUE THREAD

**Issue by bgiaccio** [springfox/springfox#2693]
Using SpringFox 2.9.2

My configuration:
1. Multiple microservices
3. Nginx proxy, with multiple hostnames

So for example ngingx.conf 
```
server {
       listen          9091 ;
       allow            all;

       server_name     app.com;

       location / {
               proxy_pass                      http://localhost:8384;
               proxy_set_header                X-Nginx-Server-Name $server_name;
       }
}
```

If I connect to http://localhost:9091/swagger-ui.html  the baseUrl is localhost:8383/
So if I try to execute a method it fails with a 401 and the method type is OPTIONS

I know I can set host when calling Docket, but we are using many of these (basically to assert different users during authentication), so that won't work as I want the hostname to be dynamic.

I've worked around it by replacing Swagger2Controller.hostName() method, to check if there is a "referer", the fix probably really belongs in ServletUriComponentsBuilder but basically somewhere a check for 
```
String uri = request.getHeader("referer");
		if (uri == null) {
			uri = request.getRequestURL().toString();
		}
		try {
			URL url = new URL(uri);
			String host = url.getHost();
			int port = url.getPort();
			if (port > -1) {
				return String.format("%s:%d", host, port);
			}
			// TODO: set the host and port
		} catch (MalformedURLException e) {
			LOGGER.warn("Failed to create url from {}", uri, e); 
		}
```

**Comment by dilipkrish** [comment]
In your nginx you need to set the right X-FORWARD headers with the right upstream values
