### ISSUE TITLE
Feature Request - make ApiModelProperty applicable to ElementType.ANNOTATION_TYPE

### ISSUE THREAD

**Issue by andydunmore** [springfox/springfox#2698]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

Tried on 2.8.0 and 2.9.2

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

We're trying to use @ApiModelProperty provide more helpful documentation within our swagger documents as follows:

`@ApiModelProperty(example = "123456789")`

Instead of applying this to every single field in our model that it's applicable for, we wanted to be able to write an annotation so that we don't have to copy "123456789" or a reference to a constant throughout our code.

```
@Target({ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@ApiModelProperty(example = "123456789")
public @interface SwaggerNumberAnnotation {
}
```

However, the APIModelProperty isn't applicable to ElementType.ANNOTATION_TYPE

Is there any other way of doing this?

**Comment by dilipkrish** [comment]
This is an [issue for swagger-core](https://github.com/swagger-api/swagger-core)
