### ISSUE TITLE
3.0 RELEASE

### ISSUE THREAD

**Issue by prafsoni** [springfox/springfox#2699]
Hi, any timeline updates for 3.0 release ?

**Comment by donhill** [comment]
Can someone provide the release date for 3.0.0 as only SNAPSHOT is available? Thanks!

**Comment by Hronom** [comment]
Is project dead? If so, maybe try to communicate with guys from Pivotal, since I think it can be nice addition to the Spring ecosystem. So they will rule this project farther...

**Comment by LilSebastian5000** [comment]
@Hronom They made an update 17 days ago so I'm doubting that it's dead

**Comment by Hronom** [comment]
@LilSebastian5000 yep, wrong alarm, I was tracking `3.0 RELEASE`, but I was thinking that it should happen a way before now.

**Comment by dilipkrish** [comment]
@Hronom Not dead for sure :) Just havent had time recently to work on OAS 3.0 which will involve breaking changes for sure. Dont want to cut a 3.0 release without that being supported thats why its getting delayed. Sorry folks!

Also we're waiting for better handling of model rendering especially when the request side looks different than the response side for the same type.

**Comment by prafsoni** [comment]
@dilipkrish if changes involving support for Spring Webflux doesn't involve breaking changes and if your release and/or maintenance policy permits. Can we have a release say `2.10` with webflux support? 
Not having swagger in webflux services is becoming a major pain with their growing number.

**Comment by dilipkrish** [comment]
I understand. Let me see what I can do to speed it up. Unfortunately 2.10 boat has sailed because of a bunch of reasons; namely dropping of java 6/7 support, no dependency on guava among the bigger breaking changes.

**Comment by prafsoni** [comment]
I appreciate your quick response. Don't want to sound very demanding, would you consider to release a pre-release version on maven. Since we don't use swagger in production beta/RC will be fine until 3.0 is ready.

**Comment by prafsoni** [comment]
any updates here?

**Comment by dilipkrish** [comment]
@dbulla thank you for you kind offer! I would take it up, but Im not going to be a JavaOne. Nevertheless this is going to be my focus for the next couple weeks 🍻

**Comment by dilipkrish** [comment]
@dionren thank you for your words of encouragement! I hope to get this released in the next few weeks.

**Comment by eacdy** [comment]
@dilipkrish When Should 3.0 RELEASES? Thanks a lot.

**Comment by prafsoni** [comment]
@dilipkrish Any Updates on release timeline?

**Comment by msogrin** [comment]
@dilipkrish Should we consider this library abandoned?

**Comment by melloware** [comment]
I don't think its abandoned its just it seems like 3.0 is a pretty big change.

**Comment by N4zroth** [comment]
I'd appreciate anything on maven-central as long as it works with the newest Spring-Data-REST repositories as we don't want to document these manually :)
Any ideas on when that might be the case?

**Comment by dilipkrish** [comment]
All, sincere apologies. I've been a little busy with my day job the last couple of months and haven't been able to devote much time, at least as much as I'd like to. There have been some terrific contributions for 3.x by @MaksimOrlov, @deblockt, @dschulten, to name a few and I do plan to get it out in Feb for sure. 

**NOTE:** It would be nice not rely on just my bandwidth/availability to work on this. I am looking for contributors who can come in, partner and help shape the future of this project. You're experience doesn't matter, novice to senior. If you're just starting out and looking for a way to contribute to open source, I'd be happy to mentor you and we can figure this out together. If you're interested please drop me a line in the comments.

**Comment by jamesclark92** [comment]
@dilipkrish, how can I help?

**Comment by Hronom** [comment]
@dilipkrish one thing in this project blocking me and name is gradle, I'm a heavy user of maven and gradle makes me sad.

**Comment by KejieLiu** [comment]
come on！ @dilipkrish 3.0.0 will release in Feb? looking forward !

**Comment by Hronom** [comment]
@dilipkrish maybe really speak with developers of Spring and try to move this project on their maintenance? I think it's amazing addition to the Spring ecosystem!

**Comment by buyukim** [comment]
@dilipkrish how can I help out?

**Comment by IEnoobong** [comment]
@dilipkrish, please how can I help?

**Comment by MounArr** [comment]
@dilipkrish, how can I help? ;-)

**Comment by coolant9** [comment]
@dilipkrish I'd love to help. Please let me know how to get started.

**Comment by sudeepraovm** [comment]
Any idea when 3.0.0 will be released since only the SNAPSHOT is available?

**Comment by dilipkrish** [comment]
Im hoping by end of this week (Apr 27). Made some good progress, would probably need some feedback from all of you who've been waiting patiently

**Comment by AxelHeathnet** [comment]
Hello, is the release today then?

**Comment by dilipkrish** [comment]
I'm having some issues with the parameter abstraction I went with, especially in the context of how to render multipart parameters. I'm having to rework that completely. Thank you for your patience

**Comment by kdebski85** [comment]
Regarding multipart parameters, please make sure that swagger-ui sends content type for each part.
I am currently using springfox-swagger-ui 2.9.2 with spring-mvc 5.2.5 and commons-fileupload 1.4.

I have a request with two parts:
1. binary file
2. json

If content type application/json is not added to the second part, spring-mvc passes it to commons-fileupload because it thinks that this is a binary file. Then it fails because it doesn't map the json to an object and it doesn't have required object.

springfox-swagger-ui 2.9.2 does not send the content type for the second part, so I cannot invoke this endpoint in it.

2.9.2 sends (Content-Type is missing for the second part):

```
------WebKitFormBoundaryWuAAfRwsYq5lj7BO
Content-Disposition: form-data; name="file"; filename="test.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document


------WebKitFormBoundaryWuAAfRwsYq5lj7BO
Content-Disposition: form-data; name="metadata"

{"foo": "bar"}
------WebKitFormBoundaryWuAAfRwsYq5lj7BO--
```

Here is the endpoint.
It was generated from OpenAPI definition by openapi-generator-maven-plugin with spring generator:

```
    @ApiOperation(value = "Upload foo", nickname = "addFoo", notes = "", response = FooDto.class, tags={ "FooResource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Added foo", response = FooDto.class) })
    @RequestMapping(value = "/api/v1/foo",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.POST)
    ResponseEntity<FooDto> addFoo(@ApiParam(value = "", required=true, defaultValue="null") @RequestPart(value="metadata", required=true)  FooDto metadata,@ApiParam(value = "") @Valid @RequestPart(value = "file") MultipartFile file);
```

**Comment by msogrin** [comment]
@kdebski85 could you please create a separate GitHub issue for this problem?

> Regarding multipart parameters, please make sure that swagger-ui sends content type for each part.

**Comment by pcornelissen** [comment]
It would be great when at least the webflux support could be backported, when the 3.x release takes so long

**Comment by kdebski85** [comment]
Maybe if somebody needs OpenAPI (also webflux) support, he/she should consider SpringDoc project (https://github.com/springdoc/springdoc-openapi) until Springfox 3 is released.

**Comment by jamesclark92** [comment]
@kdebski is right. I think springdoc-openapi is a good alternative to this and possibly the way forward.

**Comment by dilipkrish** [comment]
@jamesclark92 have you tried the latest 3.0.0-SNAPSHOt? it should be availalble later this week.

**Comment by dilipkrish** [comment]
Closing this in lieu of https://github.com/springfox/springfox/issues/3070
