### ISSUE TITLE
Is it able to use in a non jackson project?

### ISSUE THREAD

**Issue by bthulu** [springfox/springfox#2702]
an old project used fastjson as json de/serializable for years, so it's hard to switch to jackson.
if import jackson, the Responses of Example Value was serialized by jackson, but in fact the rest-api return object was serialized by fastjson, some field will mistach in both fastjson and jackson.
i wondering why not just get one from spring's List<HttpMessageConverter<?>> which can resolve media type application/json?

**Comment by dilipkrish** [comment]
Currently there are folks using it with gson library, so yes, it should work, just needs a little bit of configuration
