### ISSUE TITLE
typeerror: failed to execute 'fetch' on 'window': request with get/head method cannot have body. in swagger(happens only for Spring Actuator)

### ISSUE THREAD

**Issue by GRajaMca** [springfox/springfox#2708]
_Originally posted by @GRajaMca in https://github.com/springfox/springfox/issue_comments#issuecomment-425806350_

**Comment by GRajaMca** [comment]
i knew the as the per the documentation swagger does not support this, but at least if you provide some work around to solve this issue (typeerror: failed to execute 'fetch' on 'window': request with get/head method cannot have body. in swagger). Note this issues are mainly happen only for spring boot actuator alone. thanks in advance

**Comment by nsriramulu** [comment]
There is a dirty workaround [here](https://github.com/rlippolis/spring-boot2-actuator-swagger).
We can use it till either springfox/springboot team fixes it.

**Comment by GRajaMca** [comment]
@nsriramulu , yes you are right, this solutions looks fine for now.

**Comment by is-simon** [comment]
@nsriramulu The link for the workaround is broken. Would it be possible for you to explain what is this workaround?? Or maybe provide another link?? Thanks!

**Comment by moussetc** [comment]
> @nsriramulu The link for the workaround is broken. Would it be possible for you to expolain a like what is this workaround?? Or maybe provide another link?? Thanks!

A bit late  answer, but for future people reading this thread: here's a link to a fork that also contains the workaround: https://github.com/jetune/spring-boot2-actuator-swagger/blob/master/src/main/java/com/rlippolis/spring/springboot2actuatorswagger/config/DirtyFixConfig.java
