### ISSUE TITLE
Ability to mask OAUTH credentials?

### ISSUE THREAD

**Issue by LilSebastian5000** [springfox/springfox#2712]
- [x] What version of the library are you using: 2.9.2

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 
 - [x] Feature Request (_possibly_) 

Hi folks. I'm working with SpringFox for the first time and it is a wonderful tool. I'm curious if there's an option for a certain piece of functionality I'm looking for, and if it does not exist, perhaps a feature request for this option.

I'm setting up my project to use OAUTH2 in its requests, which properly creates the "Authorize" button on my swagger-ui.html, and everything works great. My only issue is that the client_secret is _always_ shown. Is there a way to mask this so the user doesn't need to manually input, but so it's never seen on the UI? It only appears to be masked once you actually have authorized.

Thanks!

**Comment by dilipkrish** [comment]
Thank you for reporting. This is an issue that belongs to the [Swagger-ui](https://github.com/swagger-api/swagger-ui) project.
