### ISSUE TITLE
Hide Empty Controller API Tag

### ISSUE THREAD

**Issue by LilSebastian5000** [springfox/springfox#2713]
- [x] What version of the library are you using? 2.9.2

What kind of issue is this?
 - [x] Feature Request

I've found a very useful way to section off certain endpoints in a controller by using tags above each endpoint inside the @ApiOperation annotation:
`@ApiOperation(value = xxx, tags = {"Endpoint List 1"})`

However, I notice when I do this to every method in my Controller, there is still the original base API section of the entire controller, and it is empty when expanding it since I have sectioned each method into their own tagged groups.

Can a feature be added to hide empty groupings on swagger-ui.html? Does this already exist and I'm missing it?

**Comment by dilipkrish** [comment]
@LilSebastian5000 you do something similar at the Controller level by using the `@Api` annotation and adding that tag to the docket

**Comment by DirkHeijnen** [comment]
Please take a look at this issue again, there is still no solution for this as of today.

**Comment by Grannath** [comment]
FYI, also have this issue. I generate interfaces using swagger codegen, and this is the result. So changing my annotations is not really an option. Was not an issue in 2.7.

**Comment by marwin1991** [comment]
Same problem here, when you have many endpoint in one cotroller it is natural to use tags

**Comment by tk** [comment]
It can be solved with the solution described by @qianyan https://github.com/springfox/springfox/issues/2134#issuecomment-353942058

1.  Add union of all operation tags to the controller.
 ```
@Api(tags = {"tag1","tag2"})
 ```
2. Add additional Plugin to project
```
import static com.google.common.collect.FluentIterable.from;
import static com.google.common.collect.Lists.newArrayList;
import static com.google.common.collect.Sets.*;
import static springfox.documentation.service.Tags.emptyTags;

import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import com.google.common.base.Function;
import com.google.common.base.Optional;
import com.google.common.collect.Sets;
import com.google.common.collect.Sets.SetView;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.service.OperationBuilderPlugin;
import springfox.documentation.spi.service.contexts.OperationContext;
import springfox.documentation.spring.web.readers.operation.DefaultTagsProvider;
import springfox.documentation.swagger.common.SwaggerPluginSupport;

/*
 * Automatic generation of controller tags
 * Source: https://github.com/springfox/springfox/issues/2134
 */

@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 1) // later execution priority than SwaggerOperationTagsReader
public class DisableAutoGeneratedTagsPlugin implements OperationBuilderPlugin {
    
    private final DefaultTagsProvider tagsProvider;

    @Autowired
    public DisableAutoGeneratedTagsPlugin(DefaultTagsProvider tagsProvider) {
      this.tagsProvider = tagsProvider;
    }
    
    @Override
    public void apply(OperationContext context) {
        Set<String> defaultTags = tagsProvider.tags(context);
        Set<String> tagsOnController = controllerTags(context);
        Set<String> tagsOnOperation = operationTags(context);
        
        SetView<String> intersectionTags = intersection(tagsOnController, tagsOnOperation);
        SetView<String> allTags = union(tagsOnController, tagsOnOperation);
        
        if(allTags.isEmpty()) {
            context.operationBuilder().tags(defaultTags);
        } else if (intersectionTags.isEmpty()) {
            context.operationBuilder().tags(allTags); 
        } else {
            context.operationBuilder().tags(tagsOnOperation); 
        }
    }
    
    @Override
    public boolean supports(DocumentationType delimiter) {
        return true;
    }
    
    private Set<String> controllerTags(OperationContext context) {
        Optional<Api> controllerAnnotation = context.findControllerAnnotation(Api.class);
        return controllerAnnotation.transform(tagsFromController()).or(Sets.<String>newHashSet());
      }

      private Set<String> operationTags(OperationContext context) {
        Optional<ApiOperation> annotation = context.findAnnotation(ApiOperation.class);
        return annotation.transform(tagsFromOperation()).or(Sets.<String>newHashSet());
      }

      private Function<ApiOperation, Set<String>> tagsFromOperation() {
        return new Function<ApiOperation, Set<String>>() {
          @Override
          public Set<String> apply(ApiOperation input) {
            Set<String> tags = newTreeSet();
            tags.addAll(from(newArrayList(input.tags())).filter(emptyTags()).toSet());
            return tags;
          }
        };
      }

      private Function<Api, Set<String>> tagsFromController() {
        return new Function<Api, Set<String>>() {
          @Override
          public Set<String> apply(Api input) {
            Set<String> tags = newTreeSet();
            tags.addAll(from(newArrayList(input.tags())).filter(emptyTags()).toSet());
            return tags;
          }
        };
      }

}
```

**Comment by streuspeicher** [comment]
I did not want to manually add tags to all my controllers via @Api and found another solution:

You can replace `ApiListingReferenceScanner` by your own component to gain control over created resource groups.

```kotlin
class CustomizedApiListingReferenceScanner : ApiListingReferenceScanner() {

    override fun scan(context: DocumentationContext): ApiListingReferenceScanResult {

       // copied from ApiListingReferenceScanner and auto-converted to kotlin:

        val resourceGroupRequestMappings = ArrayListMultimap.create<ResourceGroup, RequestMappingContext>()
        val selector = context.apiSelector
        val matchingHandlers: Iterable<RequestHandler> = FluentIterable.from(context.requestHandlers)
                .filter(selector.requestHandlerSelector)
        for (handler in matchingHandlers) {
            val resourceGroup = ResourceGroup(
                    customizedGroupName(handler),
                    handler.declaringClass(),
                    0)
            val requestMappingContext = RequestMappingContext(context, handler)
            resourceGroupRequestMappings.put(resourceGroup, requestMappingContext)
        }
        return ApiListingReferenceScanResult(Multimaps.asMap(resourceGroupRequestMappings))
    }

  fun customizedGroupName(handler: RequestHandler) : String {
    // add your own logic here. 
    /// Returning the same name for all (e.g. "default") is possible.

    // this is the default:
    return handler.groupName()
  }
```

... and in spring boot config: 

```kotlin
    @Bean
    @Primary
    fun apiListingReferenceScanner(): ApiListingReferenceScanner = CustomizedApiListingReferenceScanner()
```

hope this helps

**Comment by dilipkrish** [comment]
@streuspeicher that's a great suggestion. Post 3.0.0 the API might change a little bit so Im pushing this feature request to a .1 release.

**Comment by streuspeicher** [comment]
> @streuspeicher that's a great suggestion. Post 3.0.0 the API might change a little bit so Im pushing this feature request to a .1 release.

Happy to be of any help - many thanks for all the time and energy you put into this project!

My goal was to use entity names taken from `@ExposesResourceFor` annotations as default tags for controllers. I replaced `DefaultTagsProvider` first, which worked quite well but left those empty groups created by `ApiListingReferenceScanner `. 

Maybe `DefaultTagsProvider` could play a bigger role here and be used by the default scanning process, as well? 
(I don't now about the implications on the API, though...)

**Comment by naineshmp** [comment]
@dilipkrish  - I am having similar issue, where empty controllers tags are showing up. I could not find any specific solution. Just wanted to check if you recommend any solution.

**Comment by thedevd** [comment]
This is getting so frustrating as there is no solution. I need to hide them without using annotation in scala play framework, and did not find even single solution which works.

**Comment by williaz** [comment]
It's due to the way springfox add tags, you can override the code on L68 to remove empty groupings(controllers)

https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/scanners/ApiDocumentationScanner.java#L68

For Spring, you can add a bean in your app like:
 @Bean
 @Primary
  public ApiDocumentationScanner customApiDocumentationScanner(){
  // return an object of the overriding class that extends ApiDocumentationScanner 
}
