### ISSUE TITLE
Path Parameter defaults to required = false, but spec says must be true

### ISSUE THREAD

**Issue by kerber** [springfox/springfox#2714]
- [x] What version of the library are you using?
2.9.2

What kind of issue is this?

 - [x] Bug report.

When using an @ApiParam annotation on path parameters, the default generated 'required' field value is true, which goes against spec for Swagger 2.0. [The spec states that required must be true for parameters of type Path](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7).
There have been a couple related issues, [2498](https://github.com/springfox/springfox/issues/2498) and [2419](https://github.com/springfox/springfox/issues/2419), but this specific spec issue remains. While it makes sense that the addition of @ApiParam expects the user to do things correctly, it is troublesome that the defaults go against the spec.
It does appear that a similar fix would work as what was implemented for 'allowEmptyValue', but I'm not sure if it's appropriate.

For a work-around it's easy enough to set required=true for each @ApiParam.

**Comment by dilipkrish** [comment]
@kerber this works as designed. Since we use the same annotations as swagger-core, the defaults supplied are the defaults that are [part of the annotation in swagger-core](https://github.com/swagger-api/swagger-core/blob/v1.5.21/modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiParam.java#L77).

**Comment by kerber** [comment]
That makes perfect sense. Thank you for getting back to me on this.
