### ISSUE TITLE
outdated spring-beans dependency causing compilation error

### ISSUE THREAD

**Issue by punkratz312** [springfox/springfox#2715]
only adding
`
io.springfox:springfox-swagger2:2.9.2
`
causing my project not to compile anymore (java 10). The remaining bean config uses @Autowired method params these work fine. But if a add the springfox-swagger2 dependency my project wont compile anymore. Not an ide error, mvn tells the same:
![image](https://user-images.githubusercontent.com/8830888/46464112-d91f6c00-c7c5-11e8-97ad-884cce1f38ca.png)
BeanConfig:
![image](https://user-images.githubusercontent.com/8830888/46464041-a7a6a080-c7c5-11e8-8168-2332c70177fe.png)

**Comment by punkratz312** [comment]
wrong transient dependency of spring beans:

![image](https://user-images.githubusercontent.com/8830888/46523594-7c37ba80-c886-11e8-9373-c36da0729ad1.png)

**Comment by punkratz312** [comment]
causes spring-boot 2 fail:

![image](https://user-images.githubusercontent.com/8830888/46524024-d2f1c400-c887-11e8-8740-b400ff056daf.png)

**Comment by punkratz312** [comment]
what a shame that i want but i can´t use this great tool.

**Comment by dilipkrish** [comment]
@punkratz312 I dont see in your stack trace how it relates to this library.
