### ISSUE TITLE
Show models that didn't use in application

### ISSUE THREAD

**Issue by jeus** [springfox/springfox#2716]
[ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

I user spring boot and create rest service. swagger load and show APIs and models but two model that don't use in application show there. I try to remove that with typeResolver but  I was not success.

`
"Link": {
"type": "object",
"properties": {
"href": {
"type": "string"
},
"templated": {
"type": "boolean"
}
},
"title": "Link"
},
"Map«string,Link»": {
"type": "object",
"title": "Map«string,Link»",
"additionalProperties": {
"$ref": "#/definitions/Link"
}
},
`

**Comment by dilipkrish** [comment]
If you use spring hates then you do use it, albeit indirectly
