### ISSUE TITLE
Bean Validation @NotBlank should be supported

### ISSUE THREAD

**Issue by ghost** [springfox/springfox#2719]
Bean Validation API 2.0 has introduced @NotBlank (which previously was Hibernate specific).
This annotation implies @NotNull, and NotEmpty for collections/strings.

Expected: If a field/parameter is annotated with @NotBlank, it should at least be regarded as required, as if it was annotated with @NotNull. If possible, it should also be marked as not empty as far as that's possible per the Swagger model.

Status quo: If a field/parameter is only annotated with @NotBlank, but not with @NotEmpty, then it's not marked as required.

**Comment by php-coder** [comment]
There 2 open PRs for that as I can see (#2660 and #2720) and the issue still here :(

**Comment by dilipkrish** [comment]
@php-coder hope to pull it in soon

**Comment by melloware** [comment]
Looking forward to this fix.
