### ISSUE TITLE
how to Translator to other language in springfox 2.9.2 

### ISSUE THREAD

**Issue by smallyaohailu** [springfox/springfox#2723]
how to Translator to other language in springfox 2.9.2 

i use  springfox 2.7.0 all work.

but when i change to 2.9.2  

<script src="webjars/springfox-swagger-ui/lang/translator.js?v=2.9.2" type="text/javascript"></script>
<script src="webjars/springfox-swagger-ui/lang/zh-cn.js?v=2.9.2" type="text/javascript"></script>

don't work

**Comment by dilipkrish** [comment]
That might be a question for [Swagger-ui](https://github.com/swagger-api/swagger-ui)
