### ISSUE TITLE
Springfox/swagger doesn't recognize the ** as query parameter

### ISSUE THREAD

**Issue by AfikGrinstein** [springfox/springfox#2727]
Hi all,
I'm using Springfox version 2.9.2 and i have a question.
I define a API which have a query parameter which define as ** under the API method which i pull using the HttpServletRequest (** is used for supporting special characters)
![image](https://user-images.githubusercontent.com/41281740/46594530-61f71a00-cadc-11e8-8fbc-052b05406ffd.png)

when accessing this API from swagger UI not parameter is defined and there is no way to use swagger in order to use this API (No query parameter text field)
![image](https://user-images.githubusercontent.com/41281740/46594517-4db31d00-cadc-11e8-9ec1-8066e29c5599.png)

Can someone help on how to define this parameter so i can use swagger to test this API?

**Comment by dilipkrish** [comment]
If you want swagger-ui to respect the wildcard endpoint, you need to describe all the things the UI has access to int the metadata. IOW your expectation that swagger-ui will allow a wildcard entry is not going to work.

**Comment by AfikGrinstein** [comment]
Thanks for the answer.
Can you give me an example how to do it? or it just cannot be done?

**Comment by dilipkrish** [comment]
@AfikGrinstein you could try using `@ApiImplicitParams` annotations, but its kinda awkward. In the endpoint, you're saying you'll accept anything, but for the purpose of the swagger specification, you'd end up describing the parameters. Why not describe the parameters natively?

**Comment by Lucas-C** [comment]
Thanks for the tip about `@ApiImplicitParams`, I used it and it solved my issue :
https://github.com/voyages-sncf-technologies/hesperides/pull/671/files

In my case I had to use a `HttpServletRequest` because this path parameter can contain slashes...

**Comment by GrigoriyVol** [comment]
I develop a web service API: http:///rest/{custName}/** by Spring. Double asterisk (**) are used to accept slash (/) in @PathVariable.
I use Swagger 2.8.0 to expose that API to web. @ApiImplicitParam is applied to get custCode passed to the URL.

With code below I expect customerCode= custName's value entered on Swagger-ui, but it is "**".

Can you guys help on this? @Lucas-C and @dilipkrish 
------------------------
@GetMapping("/rest/{custName}/**")
@ApiOperation("Get customer by name and code")
@ApiImplicitParams({
@ApiImplicitParam(name = "custCode", required = true, dataType = "string", paramType = "path"),})
public ResponseEntity getCustomer(@PathVariable("custName") final String custName, 
								  HttpServletRequest request)
{
	String customerCode = getCustCodeFromHttpRequest(request); //getCustCodeFromHttpRequest is a my private method.	
}
