### ISSUE TITLE
(Feature Request ?) Is there a mean to add header param EXCEPT on some endpoint(s) ?

### ISSUE THREAD

**Issue by Akamanouche** [springfox/springfox#2728]
Hi, 
I try to customize my Docket object to declare an header parameter on all endpoints EXCEPT some...

So i started - unsusccessfully - to play with :

- `ParameterBuilder`
- `docket.pathMapping(...)`

But there are no such : `Predicates.not()` features in methods signature on these objects (as there is elsewhere). So it is probably not the  fitting way to do the job !...

Any suggestion ?
May be it's not possible so far.
And i need to declare my header paarmeter on each controller method signature...

Thanks in advance

**Comment by dilipkrish** [comment]
It isnt possible to add headers for just some parameters so far
