### ISSUE TITLE
API that does not return a body includes 'produces' in generated swagger.json

### ISSUE THREAD

**Issue by dcp65** [springfox/springfox#2730]
I am seeing the following problem in Kotlin using Springfox 2.9.0.

I have the following POST API that does not expect a response body:

```
@ResponseStatus(CREATED)
    fun sendFoo(@RequestBody foo: Foo) {
        fooApiService.save(foo, session.id)
    }
```
However, the generated `swagger.json` shows this for the API:

```
"produces": [
    "*/*"
  ]
```

Since the API does not return a body, I expect there to be no `produces` field in the generated JSON.

**Comment by dilipkrish** [comment]
There is always a response, something produced in a http even if it is not a response body.

**Comment by dcp65** [comment]
That's not how I understand the usage of `produces`:

https://swagger.io/docs/specification/2-0/mime-types/

**Comment by dilipkrish** [comment]
@dcp65 that is not an swagger specification. That is a http specification :)

**Comment by dcp65** [comment]
> that is not an swagger specification. That is a http specification 

I don't understand what you mean. I linked to the Swagger spec.

Let me put it another way, if an API returned 204 No Content, would you include `produces` in the response?

**Comment by dilipkrish** [comment]
What I mean is that, http is always request response, whether you implementation returns a void or doesn't return anything. If there is 204 no content, that is still a response that the server returns to the client. Hope that makes sense.
