### ISSUE TITLE
@Size annotation doesn't work

### ISSUE THREAD

**Issue by ghsatpute** [springfox/springfox#2732]
-  What version of the library are you using? `2.9.2 `
- Is it the latest version? `yes`
- The latest released version is `2.9.2` [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

### Question 
I have a DTO which looks like this 
```
public class SupportReasonRequestDTO {

    @NotBlank
    @Size(max = 1000)
    private String reason;
   // Rest of the code omitted 
}
```
Controller method which looks like this 
```
    public ResponseEntity<Void> myMethod(
        @Valid @RequestBody SupportReasonRequestDTO supportReasonRequestDTO) {
// Code ommitted 
}
```
I have added following dependencies in my `pom.xml` with version `2.9.2` for all 
```
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-bean-validators</artifactId>
        </dependency>
```
After this the Swagger UI gets generated but the validation annotations are not shown on the UI 

![image](https://user-images.githubusercontent.com/3480767/46720340-ec32b000-cc8d-11e8-9189-dccf13b59e3e.png)

What am I missing here?

**Comment by dilipkrish** [comment]
Not sure the validation annotations show in the UI. If you could share the son that was generated for `SupportedReasonRequestDTO` that would be useful.

**Comment by ghsatpute** [comment]
>Not sure the validation annotations show in the UI. If you could share the **son** that was generated for `SupportedReasonRequestDTO` that would be useful.
son meaning?

**Comment by dilipkrish** [comment]
@ghsatpute json :)

**Comment by ghsatpute** [comment]
```
....
 "SupportReasonRequestDTO":{  
         "type":"object",
         "properties":{  
            "reason":{  
               "type":"string"
            },
            "status":{  
               "type":"string",
               "enum":[  
                  "ACTIVE",
                  "INACTIVE"
               ]
            }
         },
         "title":"SupportReasonRequestDTO"
      }
....
```

I think validation annotation should be shown on the Swagger UI, as they are part of API contract.

**Comment by dilipkrish** [comment]
Thank you for reporting. This is an issue that belongs to the [Swagger-ui](https://github.com/swagger-api/swagger-ui) project.

**Comment by ghsatpute** [comment]
@dilipkrish I may be wrong here, but shouldn't the generated JSON contain the field validation information? Swagger UI will only render the UI according to this JSON.

**Comment by YetAnotherMatt** [comment]
@ghsatpute have you imported the BeanValidatorPluginsConfiguration?
`@Import(springfox.bean.validators.configuration.BeanValidatorPluginsConfiguration.class) `

**Comment by ghsatpute** [comment]
Thanks @YetAnotherMatt, after adding that it worked. But it's not working for `@NotBlank`. 

```
@SpringBootApplication
@ComponentScan(basePackages = {
   ...
})
@Import(springfox.bean.validators.configuration.BeanValidatorPluginsConfiguration.class)
public class MyApplication {

    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }
}
```

**Comment by YetAnotherMatt** [comment]
@ghsatpute according to http://springfox.github.io/springfox/docs/current/#springfox-support-for-jsr-303 they only support @NotNull, @Min, @Max, and @Size currently.

**Comment by ghsatpute** [comment]
Thanks @YetAnotherMatt for the response.

**Comment by baldeomar** [comment]
Beside original question, is there a way to have Size annotation on List of objects documentes ?
Size annotation on String parameters gets documentation generated correcty (minLength and maxLength).
But how to do when annotating List of object ?

**Comment by shouldnotappearcalm** [comment]
@zomet Is there any good solution？For this, I mentioned a [pr](https://github.com/springfox/springfox/pull/3259) to solve the List problem
