### ISSUE TITLE
404 when using springfox 2.6.1 with spring 4.3.18.RELEASE

### ISSUE THREAD

**Issue by prisin** [springfox/springfox#2737]
<dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>2.6.1</version>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-spring-web</artifactId>
                <version>2.6.1</version>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-core</artifactId>
                <version>2.6.1</version>
            </dependency>
           <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-staticdocs</artifactId>
                <version>2.6.1</version>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-web</artifactId>
                <version>4.3.18.RELEASE</version>
            </dependency>

I am getting this error "org.springframework.web.servlet.PageNotFound.noHandlerFound No mapping found for HTTP request with URI [/docs] in DispatcherServlet with name '**'." 

Also mine is working for versions 2.5.0 and below but not 2.6.1.

**Comment by dilipkrish** [comment]
Please use springfox 2.9.2 which is the latest
