### ISSUE TITLE
Cannot generate swagger documentation for Spring Boot 2 RestRepositories

### ISSUE THREAD

**Issue by k9m** [springfox/springfox#2742]
Using Spring Boot 2 (2.0.5.RELEASE)

This has been a known issue for a while, and wondering if a hotfix can be released for swagger 2?

Exception I get and the application fails to start
Caused by: java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;

[https://github.com/springfox/springfox/issues/1957](url)

**Comment by dilipkrish** [comment]
This is fixed in 3.0.0 I believe. Dont have the bandwidth to release a hot fix. I hope to get that release out mid Nov

**Comment by k9m** [comment]
Ok, thanks for sharing will keep an eye on the new release then

**Comment by mwreppa** [comment]
@dilipkrish Don't wanna be a pain in the ass, nor do i wanna pressure, just would like to know if a hotfix release for den 2.X version is planned or if the fix is planned to arrive with 3.0?

Appreciating the work and effort, keep going! 👍

**Comment by dilipkrish** [comment]
@mwreppa making some progress on the 3.0, sorry that my day job has kept me busy

**Comment by jaschenk** [comment]
There have been claims that a version 3.0.0 will address this issue.  When will this be released?

Using Spring boot: 2.0.4.Release and Spring 5.1.3.RELEASE and getting:
java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;

Could a localized path be created and made available?  Or any alternative workaround?

Please advise.

Thanks,
Jeff
