### ISSUE TITLE
Meta annotation input (OverridesAttribute) is ignored

### ISSUE THREAD

**Issue by orangeIl** [springfox/springfox#2746]
Hello,

i am using springfox 2.9.2 and writing a meta annotation with Size:
```
@Pattern(regexp="[a-z]*")
@Size
@Target({FIELD,  TYPE, PARAMETER })
@Retention(RUNTIME)
@Constraint(validatedBy = {})
public @interface MyVerify {
    @OverridesAttribute(constraint = Pattern.class, name = "message")
    String message() default "Wrong text";

    @OverridesAttribute(constraint = Size.class, name = "min")
    int min()default 5;

    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
```

And using it in model:
```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class MyInfo {
    private int age;

    @MyVerify(min = 6)
    private String someText;
}
```

And the rest controller using the model:
```
    @RequestMapping(value = "/info", method = RequestMethod.POST)
    public MyInfo someInfo(@RequestBody @Valid MyInfo myInfo){
        myInfo.setAge(99);
        return myInfo;
    }
```

Java will enforce the MyVerify limit with min 5 chars if i will try to post wrong data, but the swagger file will ignore it and will use the min and max value of the Size annotation (0,2147483647):

    "definitions": {
        "MyInfo": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "format": "int32"
                },
                "someText": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 2147483647,
                    "pattern": "[a-z]*"
                }
            },
            "title": "MyInfo"
        }
    }

The issues will repeat itself if i will use annotation with input:
`MyVerify(min = 99, max = 200)`

**Comment by dilipkrish** [comment]
You need to write your own plugin if you want to use the values specified in `@MyVerify`. It will use the values specified in the size annotation.

**Comment by orangeIl** [comment]
but why its ignoring the OverridesAttribute?
i dont think it right to ignore it and require plugin for every meta annotation the user create.

i notice that the addOverrideAttributes in the org.hibernate.validator.internal.metadata.descriptor.ConstraintDescriptorImpl is called only in the first time i use the annotation (for example- post data to a class that use the meat annotion).
its seems to be the problem-the swaggerconfig create the file (just after the Spring is up) before the addOverrideAttributes  is runing.

do you know if i can activate the addOverrideAttributes  before the swaggerconfig create the file (just after the Spring is up)?

**Comment by dilipkrish** [comment]
@orangeIl not sure how that works, which implies springfox also probably doesnt know about it.
