### ISSUE TITLE
Value of 'x-example' is used as value in parameter fields in the Swagger UI since 2.9.2

### ISSUE THREAD

**Issue by mmeknowis** [springfox/springfox#2748]
Since we have updated from springfox version 2.8.0 to 2.9.2 we noticed that the 'x-example' value (swagger.json) is now used as initial value in the parameter fields in the swagger ui.

Please see the following part as an example swagger json file (see 'x-example'):
```
{
  "swagger": "2.0",
  "info": {
    "description": "",
    "version": "",
    "title": "API",
    "contact": {},
    "license": {}
  },
  "host": "localhost:8080",
  "basePath": "/",
  ...
  "paths": {
    "/api/": {
      "get": {
        "tags": [
          "Something"
        ],
        "summary": "Get something",
        "parameters": [
          {
            "name": "uuid",
            "in": "path",
            "description": "the id",
            "required": true,
            "type": "string",
            "allowEmptyValue": true,
            "x-example": "5cd2daf3-b304-4173-8654-927845799207"
          }
        ],
        "responses": {
          "200": {...},
  ...        
  "externalDocs": {}
}
```

And a screenshot of the associated swagger ui:
![image](https://user-images.githubusercontent.com/36509878/47158731-8f1da680-d2ec-11e8-9665-414d65184de1.png)

Is it configurable to avoid this? Because we would like to have examples in our swagger.json's, but the parameter fields in the swagger ui should initially be empty. 

Thanks.

**Comment by dilipkrish** [comment]
This is a function of [Swagger-ui](https://github.com/swagger-api/swagger-ui).

**Comment by mmeknowis** [comment]
Ok thanks for your answer.
