### ISSUE TITLE
Multiple mappings with same URL, different query parameters

### ISSUE THREAD

**Issue by l3ender** [springfox/springfox#2759]
I am using version 2.9.2 and am unable to get Springfox/Swagger UI to generate correct API documentation for each of my endpoints.

My endpoints have the same URL but different query parameters, like the following:
```java
@GetMapping(value = "/profiles", params = { "serverId" })
public List<String> getProfiles(@RequestParam("serverId") String serverId)

@GetMapping(value = "/profiles", params = { "serverId", "profileName" })
public List<String> getProfilesByName(@RequestParam("serverId") String serverId, @RequestParam("profileName") String profileName)

@GetMapping(value = "/profiles", params = { "serverId", "profileType" })
public List<String> getProfilesByType(@RequestParam("serverId") String serverId, @RequestParam("profileType") String profileType)
```

With this, the Swagger UI page shows only one of the endpoints. Do I need to configure something special?

**Comment by l3ender** [comment]
Thanks for the response. You mention a lower version of swagger-ui is required for URL templating: was support for it removed? Or broken with some other upgrade in newer version? I'd like to try and help out on this if possible--just need a nudge in the right direction. Thanks!

**Comment by dilipkrish** [comment]
@l3ender there was experimental support in the old swagger-ui. There hasn't been an opportunity to port that to the new version of swagger-ui. It still works minus a few bugfixes in swagger-ui with swagger 2.0. It will not work with OpenApi Spec 2.0

It would be amazing if you could take a look at that if you're familiar with react.
