### ISSUE TITLE
Performance issue with swagger in GAE standard/flex environment for spring-boot application

### ISSUE THREAD

**Issue by vijayakumar-psg587** [springfox/springfox#2760]
I Implemented springfox-swagger in a spring boot application. The below is the configuration used in pom.xml.

                <dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-bean-validators</artifactId>
			<version>2.9.2</version>
		</dependency>
And i have nearly 10 service endpoints defined in controller class. When i access swagger-ui.html in local, it's working fine and loading very fastly (Approximately 5 secs).

The same application had deployed to GAE standard/flex environment. But when i hit swagger-ui URL it is taking more time to load (Approximately 1-2 mins).. which leads to a performance issue.

Anybody can help me in this issue? Thanks.

**Comment by dilipkrish** [comment]
@vijayakumar-psg587 would love for feedback to make this better, but Its a little bit of an unknown why GAE isnt performing as well, perhaps the memory sizes/configuration of the environment is a factor?

**Comment by vijayakumar-psg587** [comment]
@dilipkrish Apologies for a very delayed response. I've contacted GCP support on this and enquired about the latency. Seems the routing configured which is global by default, produces an initial latency when accessing the app. The issue I had is latency with multiple access of the same service but different revisions. So the suggestion was to make the routing regional to reduce the latency. Also since I was trying to access a newly deployed service every time( the revision was more to do so with the resource /memory configuration in app.yaml file), every time the service is spun up by creating/rewiring the VMs at the backend and hence every call to the newly deployed revision was like making a new http request to the service. That was the reason behind latency. Subsequent calls reduced the latency albeit marginally. Hence our team decided to use GCR/GKE as a solution moving forward rather than using app engine.

**Comment by vijayakumar-psg587** [comment]
Also I haven't tried with the improved versions of GCP, which I believe render the services much more faster. So I do not want people to be discouraged by the fact that GCP  app engine might be slow. I suggest to try out with the newer versions.
