### ISSUE TITLE
Works as spring-boot:run but not in tomcat

### ISSUE THREAD

**Issue by oeresundsgruppen** [springfox/springfox#2762]
Using latest version 2.9.2, spring-boot 2.1, tomcat 9.

I can access localhost:port/webTest/v2/api-docs, when started with spring-boot:run, but not when deployed to tomcat.

Log states Mapped URL webTest/v2/api-docs to ..springfox.documentation, same log entry in both scenarios.

It might help if the DocumentationPluginsBootstrapper or the ApiListingReferenceScanner could write, that it created the json, except for just found 1 custom documentation plugin ?

Any ideas ?

**Comment by dilipkrish** [comment]
I think with tomcat you need to account for a possible context path/server path coming into play depending on how its configured.

**Comment by oeresundsgruppen** [comment]
Think we need to have more debug-level log. esp about size of json created. I have tried setting servlet.getContextPath() into Docket, group/pathMapping, plus setting server.context in application.properties, and springfox.documentation.swagger.v2.path=/webTest/v2/api-docs in swagger.properties - nothing seems to take effect.

**Comment by dilipkrish** [comment]
It uses the X-Forward headers to infer the context path etc. You can however override the host name

**Comment by oeresundsgruppen** [comment]
On number of objects/methods put into generated json (and the size of this json).

s.d.s.w.PropertySourcedRequestMappingHandlerMapping - Mapped URL path [/webTest/v2/api-docs] - which is not the case, as it returns 404.
