### ISSUE TITLE
Support spring-context-indexer or Provide auto configuration In Spring 5

### ISSUE THREAD

**Issue by wreulicke** [springfox/springfox#2763]
- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

This project uses ComponentScan like [here: Swagger2DocumentationWebMvcConfiguration](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/configuration/Swagger2DocumentationWebMvcConfiguration.java#L42)
But, if we use [spring-context-indexer](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-scanning-index), we can not find bean.

So, Will we provides `spring.components` using spring-contex-indexer, or provides auto configuration class.

In my opinion, it is happy to provide auto configuration
Even if you **do not** use spring-contex-indexer, you can not find bean when provides `spring.components` using spring-contex-indexer.

**Comment by dilipkrish** [comment]
@wreulicke Im not familiar with context-indexer. Would love for you to describe the solution, or better still would appreciate a PR.

**Comment by atsu85** [comment]
@wreulicke, either i don't unederstand following statement
> Even if you do not use spring-contex-indexer, you can not find bean when provides spring.components using spring-contex-indexer.

exactly, or this is wrong, because if i remove 
`annotationProcessor 'org.springframework:spring-context-indexer'`
from my project dependencies (that uses springfox-swagger), then application starts up without issues described in #2451:
`Parameter 2 of method swagger2ControllerMapping in springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration required a bean of type 'springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper' that could not be found.`

**Comment by atsu85** [comment]
> if i remove
`annotationProcessor 'org.springframework:spring-context-indexer'`
from my project dependencies (that uses springfox-swagger), then application starts up without issues

Note that is true if there are no jars with spring.components file in classpath. Othwrise spring 5 disables classpath scanning (unless indexer is expclitily disabled)

**Comment by atsu85** [comment]
Looks like currently spring-context-indexer doesn't work with Spring 4 (taht is used in this project). I created [this feature request](https://github.com/spring-projects/spring-framework/issues/23861) so it would be possible to generate spring.components file (for consumer applications using Spring 5) with spring-context-indexer even if this project still uses Spring 4

**Comment by snicoll** [comment]
My recommendation would be to stop using classpath scanning, this is a feature that is usually enabled in applications, not libraries. By removing classpath scanning here, you will be compatible with a larget set of apps.

**Comment by atsu85** [comment]
Considering, that the [spring-context-indexer Spring 4 feature request](https://github.com/spring-projects/spring-framework/issues/23861) was closed with:
> Support for Spring Framework 4.x ends in Q1 2020 so an upgrade of those components

following
> stop using classpath scanning, this is a feature that is usually enabled in applications, not libraries

makes sense. Just that it seems too much effort, so currently i'd say we have following options to support Spring 5 for applications that contain at least one spring.components file (could be in some dependency jar) without explicitly disabling indexer:
* create components.index manually (or with alternative generator)
* update springfox to Spring 5 (Spring stops support for Spring 4.x in Q1 2020)
* stop using classpath scanning in favor of 
> probably these options are in order of ease of implementation for springfox project

@snicoll, @dilipkrish what do you think?

**Comment by snicoll** [comment]
> create components.index manually (or with alternative generator)

This is worse as creating such a file here means that all applications using SpringFox will have to use the context indexer. While this is an important limitation of the feature, I think it only surfaces concretely in situation like this one. If SpringFox (a library) did not use classpath scanning (as it should IMO) then the problem wouldn't exist in the first place.

**Comment by atsu85** [comment]
> all applications using SpringFox will have to use the context indexer

Not necessarily, [indexer can be disabled](https://docs.spring.io/spring/docs/5.2.x/spring-framework-reference/core.html#beans-scanning-index) using 
`spring.index.ignore=true`,
so it would be easy to disable it.
> As i understand indexer is enabled in favor or classpath scanning if application itself or any dependency jar contains spring.components

**Comment by snicoll** [comment]
> As i understand indexer is enabled in favor or classpath scanning if application itself or any dependency jar contains spring.components

No. it will be enabled as soon as a `spring.components` file is found on the classpath.

**Comment by atsu85** [comment]
> it will be enabled as soon as a spring.components file is found on the classpath

that is exactly what i meant, i just wanted to emphasize the fact that it could also be any jar file containing `spring.components`, not necessarily the application itself.

@snicoll, i appreciate you (Spring Boot developer) a lot to take your time for this project, but my point was to suggest much easier way to achieve `spring-context-indexer` support (as per the title of this issue).

> My recommendation would be to stop using classpath scanning

I totally agree, that this would be the best as you said, and as i understand that is also what would happen when `spring.components` would be added (unless indexer is disabled via configuration). Clear downside of avoiding classpath scanning by adding `spring.components` is of course the fact, that all applications that start using next version of this library would disable classpath scanning by default and that is breaking change (even tough with benefits and option to restore old behavior with `spring.index.ignore=true`).

@wreulicke, i hope you find time to finish your [PR](https://github.com/springfox/springfox/pull/2971) to disable classpath scanning by removing `@Component` annotations in favour of `@Configuration` classes with `@Bean` definitions :)

**Comment by wreulicke** [comment]
I will try new proposal using auto configuration.

**Comment by ptahchiev** [comment]
Is there any update here? Do you need help adding the bean definitions?
