### ISSUE TITLE
Spring data rest auto generated spring fox swagger tags doesn't disappear

### ISSUE THREAD

**Issue by SamAyl** [springfox/springfox#2765]
I currently have a model class ("AwsKey.java") which is a mongoDB object , I am using springfox-data-rest to generate the documentation however, swagger spring fox does generate another tag 
{
Name : AwsKey Entity,
Description :"My simple mongoDB Entity"
}

The problem is that I don't want this tag to be displayed on my swagger UI as I want to use my own tag with the name and description, can someone please let me know how to remove the auto generated tag for model class from the swagger UI.

Appreciate your time and reply

**Comment by dilipkrish** [comment]
At the moment I don't believe this can be overriden. I'll chalk that up as a feature request

**Comment by nicktran29** [comment]
Is there a way to override that auto generated tag?
