### ISSUE TITLE
Example property on operations does not work

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#2767]
```
@ApiResponses(value = {
        @ApiResponse(code = 404, message = "Not Found",
                examples = @Example(
                        value = {
                                @ExampleProperty(
                                        mediaType = "Example json",
                                        value = "{\"invalidField\": \"address\"}"),
                                @ExampleProperty(
                                        mediaType = "Example string",
                                        value = "The first name was invalid")}),
response = Response.class)})
```
and the fields in Response class are annotated with `@ApiModelProperty(required = true, example = "Timeout exceeded")` then the example is also rendered. It's kind of a workaround,  but also not an option in my case, because I need to use class provided by library and I can't annotate it.

_Originally posted by @tgielbutowicz in https://github.com/springfox/springfox/issues/2352#issuecomment-432225240_

**Comment by prisin** [comment]
Examples are not getting reflected in @ApiResponses. I am using springfox 2.9.2. Any idea when this will be fixed ?

**Comment by sboursault** [comment]
Same behaviour with 3.0.0-SNAPSHOT :(

**Comment by lcl1992421** [comment]
Any update of this？

**Comment by prabhushrikant** [comment]
I am still facing problem with this, @Example is not rendered.

**Comment by prabhushrikant** [comment]
> I am still facing problem with this, @example is not rendered even with 3.0.0-SNAPSHOT when it's just a week before it's getting released.

I see it's fixed in 311aa95 when will it be available in SNAPSHOT?

**Comment by dilipkrish** [comment]
Yes it should be, would love to see your feedback

**Comment by prabhushrikant** [comment]
> Yes it should be, would love to see your feedback

Looks like issue is not yet solved. Something to note though, even when I reimported my dependencies but it's still showing old value for jar - springfox-oas-3.0.0-SNAPSHOT.jar, it should be a newer value correct?

Manifest-Version: 1.0
Implementation-Title: springfox-oas
Implementation-Version: 3.0.0-SNAPSHOT
Created-By: 11.0.2 (Oracle Corporation)
Built-With: gradle-6.5, groovy-2.5.11
Build-Time: 2020-07-08T11:13:48+0000
Built-By: circleci
Built-On: 82201b430220/192.168.16.3

**Comment by dilipkrish** [comment]
You need to force update your snapshot.

**Comment by prabhushrikant** [comment]
We have lost the regular example functionality though , other error codes expect example also even though it can be easily inferred from model
e.g. it's now coming as follows : 
![image](https://user-images.githubusercontent.com/6848200/87089816-d8fa9e80-c1eb-11ea-9669-560157480108.png)

but before this update it used come out like this .

![image](https://user-images.githubusercontent.com/6848200/87089966-13fcd200-c1ec-11ea-98fe-52840c697402.png)

**Comment by prabhushrikant** [comment]
> You need to force update your snapshot.

Thanks, I confirm after refreshing snapshot libraries to @Example started working as follows but it doesn't show up schema as in request body in following screen shot

![image](https://user-images.githubusercontent.com/6848200/87091735-06951700-c1ef-11ea-9890-59f55de79e07.png)

**Comment by dilipkrish** [comment]
Could you try using `OAS-30` in your Docket?

**Comment by prabhushrikant** [comment]
> Could you try using `OAS-30` in your Docket?

Yes I am using OAS-30 in my docket. @example annotation doesn’t work otherwise

**Comment by dilipkrish** [comment]
You clearly aren't using [these 3.0 annotations](https://github.com/springfox/springfox/commit/311aa95bb4e115b996d48d9cbcd4b4971b05920e#diff-a88750d91b820d2be1f4fe6c264e9782R84-R107)

**Comment by prabhushrikant** [comment]
what are the plans for releasing 3.0.0-SNAPSHOT into a official release?
