### ISSUE TITLE
Add The Output of Spring (Auto) Rest Docs to Springfox

### ISSUE THREAD

**Issue by rowi1de** [springfox/springfox#2769]
###  Feature Request: Add The Output of Spring (Auto) Rest Docs to Springfox

- The following Projects are really useful to provide a complete API Documenation: 
  - https://spring.io/projects/spring-restdocs
  - https://github.com/ScaCap/spring-auto-restdocs
It's picking up JavaDoc/KDOc, Integration Tests and outputting Snippets that are generated. 

- I love Swagger/OpenAPI as an API Specification Language
- I don't like Swagger Annotations in my Code. Also if you use both tools, you would need to duplicate the Documentation  

**Goal**: Pickup spring-(auto)-restdocs Snippets in Springfox

**Comment by dilipkrish** [comment]
That is a great idea, I love `rest-docs`. Unfortunately Im thinking its going to be a little harder to correlate the endpoints in restdocs with your request mappings. Plus reactive spring will pose some different challenges. There is another option [to use java docs](https://github.com/springfox/springfox-javadoc)

**Comment by rowi1de** [comment]
Thanks for the hint to https://github.com/springfox/springfox-javadoc 
I didn't knew that option exists, will try that.
Spring Rest Docs generates the *.json Output according to the Class/Object names, so the mapping should not be so hard. 

But if it's already possible the add the javadoc to the swagger-spec, the most important step is done.
