### ISSUE TITLE
Swagger1 api-docs 

### ISSUE THREAD

**Issue by arkosarkar343** [springfox/springfox#2772]
Hi,

I am using Swagger1 in our application and when I hit api-docs from the browser, I get the response of the api documentation as json. But it does not contain all the details of the controller.

So, when I launch swagger-ui.html I could see after the api-docs call it loads all the definition and details of each controller in separate ajax requests. 

Is there an option to load all the controller definitions and responses when I try to access api-docs?
This is required because I want to import the api-docs response in soap-ui and use it for testing. 

Thanks,
Arko

**Comment by arkosarkar343** [comment]
@dilipkrish - Thanks for your reply .. Is there an option to load all at once?

**Comment by dilipkrish** [comment]
Not that I know of.
