### ISSUE TITLE
How to write conditional attribute in springfox swagger

### ISSUE THREAD

**Issue by ChandrasekharRajoli** [springfox/springfox#2777]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?
 - [x] Question. Is this a question about how to do a certain thing? 

How to write conditional API attributes? Basically, I've 2 services with common attributs and few attributes will change based on API. How can i manage them in spring using SpringFox Swagger

**Comment by dilipkrish** [comment]
Can you give an example?

**Comment by ChandrasekharRajoli** [comment]
For example, I have a 2 GET service's EmployeeList and EmployeeDetail service, I'm using EmployeeModel object to return the response for two services, but few properties should be available only for EmployeeDetail service not in EmployeeList service.

Employee Model 

employeeId - EmployeeList and EmployeeDetail service
deptName- EmployeeDetail Service
empName - EmployeeList and EmployeeDetail service
address - EmployeeDetail Service
mobileNo - EmployeeDetail Service
accountDetails - EmployeeDetail Service

How can make Employee model attributes conditionally available to the different REST services? Please help here.
