### ISSUE TITLE
Unable to handle Map as Request Parameter v 2.9.2

### ISSUE THREAD

**Issue by vimal-vasukuttan** [springfox/springfox#2780]
Reopening closed issue #2338

Issue : Swagger 2.0 - Unable to handle Map as requestparameter.
Version : io.springfox:springfox-swagger2:2.9.2 && springfox-swagger-ui:2.9.2

**Part of Request definition :** 
`@RequestParam Map<String, String> allRequestParams`

**Part of swagger spec generated :** 
```json
     "parameters": [
                    {
                        "name": "allRequestParams",
                        "in": "query",
                        "description": "allRequestParams",
                        "required": true,
                        "items": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
```

**Part of request made from swagger UI :** 
`/mypath?allRequestParams=%7B%20%22test%22%20%3A%20%22TestUser%22%20%7D"`

Will the fix be available in any future releases ?

**Comment by dilipkrish** [comment]
Thank you for reporting. This is an issue that belongs to the [Swagger-ui](https://github.com/swagger-api/swagger-ui) project.

**Comment by vimal-vasukuttan** [comment]
@dilipkrish, Thanks for the support. I would like to report one more irregularities with the swagger spec generated. From the above example,  a map of strings as key and value, the spec generated doesn't seems to match with OAS2. SpecValidation is failing with message "type" is missing.
**Generated Spec**
```
{
                        "name": "allRequestParams",
                        "in": "query",
                        "description": "allRequestParams",
                        "required": true,
                        "items": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
}
```

**According to OAS2, I suppose the expected spec will be** 
{
                        "name": "allRequestParams",
                        "in": "query",
                        "description": "allRequestParams",
                        "required": true,
						"type": "object",
                        "additionalProperties": {
                           "type": "string"
                        }
}

**Open Api Spec Extract**
Model with Map/Dictionary Properties
For a simple string to string mapping:

{
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}

Can you please comment on the above issue also.

**Comment by dilipkrish** [comment]
It may be an edge case bug, AFAIK swagger 2.0 [doesn't support Map<String, String>](https://github.com/swagger-api/swagger-ui/issues/2241)
