### ISSUE TITLE
«, » in generated swagger.json

### ISSUE THREAD

**Issue by jannhendrik** [springfox/springfox#2784]
Please take the time to search the repository, if your question has already been asked or answered.

[ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?
**Bug Report**
The following java code:
https://gist.github.com/jannhendrik/7829ad026caae0e8beca2b2732573ed0

Results in this schema ref:

...
"schema":{"$ref":"#/definitions/Page«User»"}
...

Swagger Editor, AutoRest and some azure services cannot handle "«". Maybe it can be replaced by a supported character like _

**Comment by dilipkrish** [comment]
Please use `docket.forCodeGeneration(true)`

**Comment by suzhengit** [comment]
Thank you very much！

**Comment by jannhendrik** [comment]
Thank you!
