### ISSUE TITLE
Override default operationId produced by OperationBuilder

### ISSUE THREAD

**Issue by kenmccracken** [springfox/springfox#2785]
I'm using springfox-swagger2, Version: 2.9.2

This is a Question.

I am interested in overriding the default behavior of operationId generation.  I see in https://springfox.github.io/springfox/docs/snapshot/#configuring-the-output-of-operationid-in-a-swagger-2-0-spec that I can override the operationId on a per-controller-method basis.  However, I have to get that annotation right on _every_ Controller method, and there are dozens of these for my service.  Moreover, in my case, refactoring and renaming any Controller method requires remembering to rename the `@ApiOperation` nickname at the same time.

Is it possible to configure springfox-swagger2 to change the pattern used for generating the default operationId?  From a look at the source code, it seems the current pattern is caused by `OperationBuilder.uniqueOperationIdStem()`.  Is there a way to override either the OperationBuilder, or the ApiOperationReader, or both, to effectively override this behavior?

I am using spring version 5.0.8.RELEASE.

```
@RestController
@RequestMapping()
public class FooController {
    @RequestMapping(path = "/foos/{foo}, method = RequestMethod.GET)
    ResponseEntity<Foo> readFoo(
            @PathVariable String foo) {
        Foo fooObj = fooService.read(foo);

        return ResponseEntity.ok(fooObj);
    }
}
```

produces
`
"operationId": "readFooUsingGET",
`

and my desired outcome, without adding `@ApiOperation` to every controller method, is 
`
"operationId": "readFoo",
`

**Comment by dilipkrish** [comment]
You can create your own implementation of [OperationBuilderPlugin](https://github.com/springfox/springfox/blob/32cfb7de9b2ac6a3385330b09ae9d1f052561300/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OperationNicknameIntoUniqueIdReader.java#L35-L54) with a higher priority.
