### ISSUE TITLE
override few properties of default docket

### ISSUE THREAD

**Issue by sbelan** [springfox/springfox#2786]
I'm using springfox-swagger2, Version: 2.9.2

This is a Question.

Is there any way to override few properties of default docket instance like api info?
Documentation mentioned the way to customize the Docket instance. But if we create new docket instance then its mandatory to provide new group name else it will throw exception and that will duplicate the same thing for default group as well. Swagger UI shows same data for default and customized group.

**Comment by sbelan** [comment]
Got the solution

**Comment by dilipkrish** [comment]
@sbelan please share
