### ISSUE TITLE
SecurityScheme description attribute missing

### ISSUE THREAD

**Issue by lzavatsz** [springfox/springfox#2788]
Hi, 
I'm looking for a way to add description to a SecurityScheme which results in the following spec: 
...
  api_key:
    **description: "authentication description"**
    type: apiKey
    name: auth
    in: query
...

Couldn't find a way to achieve this using springfox, did I miss something or is there at least workaround for this? 
Thanks.

**Comment by dilipkrish** [comment]
No one has asked for it before, so Im guessing its a feature request

**Comment by lzavatsz** [comment]
Yes, we can say so, if it was intentionally left out, or we can consider as a gap. Anyway, io.swagger.models.auth.AbstractSecuritySchemeDefinition contains description attribute, while springfox.documentation.service.SecurityScheme doesn't. I guess then what I want is not doable at the moment using springfox.
