### ISSUE TITLE
How to send auth token in all requests and not force a user to write a password as a plain text

### ISSUE THREAD

**Issue by MrFigureSkating** [springfox/springfox#2792]
Hi, I have a problem and I thought that it's a very common case but I spent almost a day and didn't find a solution.

All our endpoints in controllers require some auth token. This token must be sent as a header.
In order to receive this token, a user has to send his login and password to an endpoint which is obviously open and implemented by Spring Security filter. So it's not a controller.
Since all the requests require this token, it's obvious that it will be very inconvenient to force a user to set this header manually in every single place. That's why we decided to use Swagger authentication feature which allows to log in by submitting this token.

So now the only question is how a user will receive this token?? I understand that we can add a "custom" endpoint implementing ApiListingScannerPlugin and it will work. But it's absolutely obvious that it's impossible to ask a user to write **his password as a plain text**. But I don't understand how to do it differently.

I've described it in details because maybe you have completely different ideas about how to make it... Because the initial problem is very trivial - just to send token as a header in all requests. But we need to fetch it somehow.

**Comment by dilipkrish** [comment]
@MrFigureSkating does the token retrieval have to be via swagger-ui?

**Comment by MrFigureSkating** [comment]
@dilipkrish I would say that yes
