### ISSUE TITLE
@Annotations are not included in ResolvedType 

### ISSUE THREAD

**Issue by justmin** [springfox/springfox#2794]
Hi

It would be nice if we could control behavior of AlternateTypeRule not only by resolved type but with some additional mecahnism.
Java 8 have type annotations, and why not to add info about all type annotations to ResolvedType?
It is cheap to implement imho and could be really useful.

**Comment by dilipkrish** [comment]
Could you provide an example of what you're proposing? Better still would really appreciate a PR to make that possible if it is what Im thinking
