### ISSUE TITLE
Add RouterFunction support

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#2799]
@dilipkrish Should I open a dedicated issue for `RouterFunction` support, or do you prefer to reopen this one?

_Originally posted by @sdeleuze in https://github.com/springfox/springfox/issues/1773#issuecomment-442392326_

**Comment by mirromutth** [comment]
Looks like `RouterFunction` can return the instance those any type (even different types in different logical branches) on runtime.
If Swagger still wants to auto generate the document using Java reflection, maybe we should wrap the response, like `interface SwaggerServerResponse<T> extends ServerResponse`, but if really want to achieve it, maybe should to proxy almost all `ServerResponse` methods (with all implementations), which will maybe a huge project. And this will break into the runtime, causing unnecessary performance loss of every web request.
If Swagger wants to auto generate the document using the JVM byte-code...not "maybe", it is definitely a massive project...
Other ways those like: using test results, using code comments...these are not like the design philosophy of Springfox, so I didn't propose them.
So, maybe just need support use "the least annotations" to semi-automatically generate the document? For this feature those first version?

**Comment by sdeleuze** [comment]
@mirromutth I tend to think the approach should be different with `RouterFunction`, and that it now provides the right infrastructure for proper Springfox support. As commented in #1773:

> We have added `RequestPredicate` visitor in Spring Framework 5.1.3 (see [SPR-17322](https://jira.spring.io/browse/SPR-17322)), which opens the door to `RouterFunction` support in SpringFox. The idea is to implement a visitor that implements both `RouterFunctions.Visitor` and `RequestPredicates.Visitor` like in [this example](https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/function/server/ToStringVisitor.java#L35) and [this test](https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/test/java/org/springframework/web/reactive/function/server/ToStringVisitorTests.java).

**Comment by iamrdn** [comment]
> @dilipkrish Should I open a dedicated issue for `RouterFunction` support, or do you prefer to reopen this one?
> 
> _Originally posted by @sdeleuze in [#1773 (comment)](https://github.com/springfox/springfox/issues/1773#issuecomment-442392326)_

Is there any plan to support for 'RouterFunction' reactive API documentation in recent releases or Can you provide any temporary solution for this case.

**Comment by mheidt** [comment]
I would be interested in a workaround as well.

**Comment by iamrdn** [comment]
> @dilipkrish Should I open a dedicated issue for `RouterFunction` support, or do you prefer to reopen this one?
> 
> _Originally posted by @sdeleuze in [#1773 (comment)](https://github.com/springfox/springfox/issues/1773#issuecomment-442392326)_

Hi, is there any update on this support plugin. Please help me in this issue. to support controller-less reactive API's documentation.

**Comment by sdeleuze** [comment]
Notice that with upcoming Spring Framework 5.2, `RouterFunction` is also available in Spring MVC, so this issue is now even more important. I guess this is an issue where some PR would be welcomed if somebody can work on that.

**Comment by chamithchathuka** [comment]
Is this feature added ?
https://stackoverflow.com/questions/68266480/springboot-springfox-starter-3-0-0-unable-to-detect-webflux-routerfuntion
