### ISSUE TITLE
/v2/api-docs page fails with unobvious error

### ISSUE THREAD

**Issue by MrFigureSkating** [springfox/springfox#2800]
Version: 2.9.2
When I open this page it gives me the following message and nothing more:
![image](https://user-images.githubusercontent.com/8093235/49151495-1fee9580-f321-11e8-9f1a-569f5a593622.png)
So it is not clear what does it exactly mean and how to debug it. I guess the error message should be more informative.
Also, I want to ask is it possible just to hide this link at all? I found a solution how to change it but is it possible not to show it?

**Comment by dilipkrish** [comment]
Can you share your swagger contract?

**Comment by MrFigureSkating** [comment]
Where we can find it?

**Comment by dilipkrish** [comment]
its available @ `http://yourhost:yourport/v2/api-docs`

**Comment by MrFigureSkating** [comment]
@dilipkrish That's exactly what I mean. A screenshot in the description of this issue was made on this particular page. I don't see there anything except this warning. That's why I said it's not clear even how to debug it.
![image](https://user-images.githubusercontent.com/8093235/49523015-f0f49880-f8b9-11e8-92ff-39b337a7c2f0.png)

**Comment by sushiesharma** [comment]
I am facing similar issue. However I am getting 404 on browser

![image](https://user-images.githubusercontent.com/33965118/49597360-3fea0e80-f94a-11e8-82e9-31ea6589dfb0.png)

Error on Console : 
2018-12-06 11:30:19.863  WARN 8120 --- [ctor-http-nio-1] s.d.s.web.Swagger2ControllerWebFlux      : Unable to find specification for group default

Please help as it is affecting the project delivery.

**Comment by malikin** [comment]
@MrFigureSkating You should use http client (for example Postman) and send get request with header "content-type application/json".

**Comment by MrFigureSkating** [comment]
[v2apiresponse.txt](https://github.com/springfox/springfox/files/2664166/v2apiresponse.txt)
Here it is, but I don't see anything unusual on line 1 column 43970

**Comment by dilipkrish** [comment]
@MrFigureSkating like @malikin suggested, I think your are most likely getting non-json content
