### ISSUE TITLE
Question : Detecting reuired paramters

### ISSUE THREAD

**Issue by vedydev** [springfox/springfox#2805]
Hi I'm using version 2.9.2
I've noticed that when the request parameters are of type `body` springfox detects if the request parameter is required or optional, and document that.

![screen shot 2018-12-04 at 5 44 58 pm](https://user-images.githubusercontent.com/33982637/49483289-dce46480-f7ef-11e8-963a-135295a93a39.png)

But when the parameters are 'query' it treats them all as optional.

![screen shot 2018-12-04 at 5 53 47 pm](https://user-images.githubusercontent.com/33982637/49483324-fb4a6000-f7ef-11e8-95d7-4cad85003488.png)

Is this expected behavior? if not,
 how can I influence it so as springfox can detect my required `query`parameters and document them accordingly?

@dilipkrish

**Comment by dilipkrish** [comment]
What does the operation signature look like in both cases

**Comment by ninjayoto** [comment]
Thanks @dilipkrish for looking:
The method that produces the documentation with required label is:
```
    @GetMapping
    @ResponseBody
        def getAvailability(@RequestHeader(value="Authorization", required=false) String token,
                        @Valid AvailabilityRequest req)
```

```
The one producing documentation with required label:    
@PostMapping
    def getAvailabilityForChange(@RequestHeader(value="Authorization") String token,
                     @Valid @RequestBody ChangeAvailabilityRequest req) 
```

**Comment by vedydev** [comment]
Thanks @dilipkrish for looking into this
The method which produces parameters documentation with no required label is:
```
    @GetMapping
    @ResponseBody

        def getAvailability(@RequestHeader(value="Authorization", required=false) String token,
                        @Valid AvailabilityRequest req)
```

The other method that produces parameters documentation with required label is : 

```
    @PostMapping
    def getAvailabilityForChange(@RequestHeader(value="Authorization") String token,
                     @Valid @RequestBody ChangeAvailabilityRequest req) 
```

thanks again

**Comment by vedydev** [comment]
were these snippets enough?

**Comment by vedydev** [comment]
I see the issue, thanks
