### ISSUE TITLE
Question: How to customize example of the method return type in SpringFox

### ISSUE THREAD

**Issue by PranavManiar** [springfox/springfox#2806]
I want to customize the example value automatically generated by springfox. 
Example will illustrate it better. 

My controller method returns list of entities along with total counts in the form of Page

```
public class Page<T> {
	List<T> content;
	long totalElements;
}
```
Now while generating response, I have ResponseBodyAdvice which intercepts this Page<T> response 
Adds the "Total" header with the value of "totalElements" and returns the List<T> content to the user. 

Something like 

```
public class TotalCountAdvice implements ResponseBodyAdvice<Object> {

	@Override
	public boolean supports(MethodParameter returnType, Class<? extends HttpMessageConverter<?>> converterType) {
		return Page.class.isAssignableFrom(returnType.getParameterType());
	}

	@Override
	public Object beforeBodyWrite(Object body, MethodParameter returnType, MediaType selectedContentType,
			Class<? extends HttpMessageConverter<?>> selectedConverterType, ServerHttpRequest request,
			ServerHttpResponse response) {
		if( Page.class.isAssignableFrom(returnType.getParameterType())) {
			Page<?> pageContent = (Page<?>) body;
			List<?> pageableList =  pageContent.getContent();  
			response.getHeaders().add("Total-Count", String.valueOf(pageContent.getTotalElements()));
			return pageableList; 
		} else {
			return body;
		}
	}
}
```

Now on the UI actual response is List<T>, but swagger example shows
```
 {
 "content" : [(contents of the returned object <T> in json form)],
 "totalElements"
} 

```
I want to customize it to 
```
{ [contents of the returned object <T> into json form] }
```
 to match with the actual values being returned. 

How can I customize springfox-swagger to do that ?? Any help is appreciated. 

Apologies, I could not find any IRC channel for springfox, so I created git issue. I know it's a question and not actually an issue.

**Comment by vedydev** [comment]
@PranavManiar did any these methods work for you?
[swagger-springfox-generating-response-example-automatically](https://stackoverflow.com/questions/53617466/swagger-springfox-generating-response-example-automatically)
warning : they didn't work for me.
