### ISSUE TITLE
using custom yaml file with already existing generated swagger-ui

### ISSUE THREAD

**Issue by lapots** [springfox/springfox#2809]
Hi!

I use the library to generate API for some of my REST services. 

```
return new Docket(DocumentationType.SWAGGER_2)
     .select()
     .apis(RequestHandlerSelectors.basePackage("com.project.rest."))
     .paths(getPaths())
     .build();
```
However for internal APIs (OAuth, login) I have implemented custom `yaml` file that contains additional mappings.

Can I integrate it with the existing API or I have to implement some other endpoint to display this yaml file?

**Comment by dilipkrish** [comment]
@lapots you can do that using your own [SwaggerResourcesProvider](https://github.com/springfox/springfox/blob/379f0ce84dae7fc70ea759b62ab0837d2c666ac1/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.java#L38)

**Comment by lapots** [comment]
@dilipkrish won't it replace existing documentation for REST?
