### ISSUE TITLE
Allow to set up the base path in the Docket configuration (Springfox 3.0.0-SNAPSHOT)

### ISSUE THREAD

**Issue by codependent** [springfox/springfox#2817]
- Version 3.0.0-SNAPSHOT
- Feature Request

I am using Springfox 3.0.0-SNAPSHOT in a Spring Boot 2.1.1 WebMvc project. It generates a documentation with basePath : "/" and paths like: /myapp/api/v1/customers. What I would like is basePath: "/myapp" and paths /api/v1/customers.

I have searched for information about how to customize the base path and the endpoints, found [this issue where jonaskoperdraat provides a solution](https://github.com/springfox/springfox/issues/1443) and tried it:

```
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
        		.host("localhost:8081")
                .pathProvider(new PathProvider() {
                	
                   private final String ROOT = "/myapp";
                	
                    @Override
                    public String getOperationPath(String operationPath) {
                        return operationPath.replace(ROOT, "");
                    }
                    @Override
                    public String getResourceListingPath(String groupName, String apiDeclaration) {
                        return null;
                    }
                })
```
My new paths are ok: /api/v1/customers, but the base path keeps being "/". I noticed the suggestion of explicitly setting Docket().host() but it didn't work either.

I have debugged the source code and found this on startup `springfox.documentation.spring.web.scanners.ApiDocumentationScanner`:

```
public Documentation scan(DocumentationContext context) {
    ApiListingReferenceScanResult result = apiListingReferenceScanner.scan(context);
    ApiListingScanningContext listingContext = new ApiListingScanningContext(context,
        result.getResourceGroupRequestMappings());

    Map<String, List<ApiListing>> apiListings = apiListingScanner.scan(listingContext);
    Set<Tag> tags = toTags(apiListings);
    tags.addAll(context.getTags());
    DocumentationBuilder group = new DocumentationBuilder()
        .name(context.getGroupName())
        .apiListingsByResourceGroupName(apiListings)
        .produces(context.getProduces())
        .consumes(context.getConsumes())
        .host(context.getHost())
        .schemes(context.getProtocols())
        .basePath(ROOT)
        .extensions(context.getVendorExtentions())
        .tags(tags);
```
 As you can see there's an explicit `.base(ROOT)` invocation. Couldn't `DocumentationContext` offer a context.getBasePath() method that was set based on another `Docket().basePath()` operation?

If not, what's the way to customize this?

**Comment by dilipkrish** [comment]
This is solved using `PathProvider` implementation and making that a primary bean. What is the problem we're trying to solve here?

**Comment by codependent** [comment]
Hi Dilip, summing up:

I have a Spring Boot 2 app using Springfox 3.0.0-SNAPSHOT. It exposes an endpoint like this: `GET /api/v1/customers`.

Docket definition:

```
@Configuration
@EnableSwagger2WebMvc
public class SwaggerConfiguration {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.codependent.api"))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(myApiInfo());
    }
    ...
```
The generated swagger info `/v2/api-docs` shows:

```
basePath : "/"
...
paths :   
   /myapp/api/v1/customer
```

However I need the following, with a base path containing /myapp/api/v1:

```
basePath : "/myapp/api/v1"
...
paths :   
   /customer
```

My first approach was using a PathProvider:

```
@Configuration
@EnableSwagger2WebMvc
public class SwaggerConfiguration {

    private final String BASE_PATH = "/myapp/api/v1";

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .pathProvider(new PathProvider() {
                    @Override
                    public String getOperationPath(String operationPath) {
                        return operationPath.replace(BASE_PATH, "");
                    }
                    @Override
                    public String getResourceListingPath(String groupName, String apiDeclaration) {
                        return BASE_PATH;
                    }
                })
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.codependent.api"))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(myApiInfo());
    }

```
The result is that `/myapp/api/v1` is removed from the endpoints, which is fine, but the base path is still `/`:
```
basePath : "/"
...
paths :   
   /customer
```
Following you advice I defined a Primary bean for the path provider:

```
@Configuration
@EnableSwagger2WebMvc
public class SwaggerConfiguration {

    private final String BASE_PATH = "/myapp/api/v1";

    @Bean
    @Primary
    public PathProvider customPathProvider() {
        return new PathProvider() {
            @Override
            public String getOperationPath(String operationPath) {
                return operationPath.replace(BASE_PATH, "");
            }
            @Override
            public String getResourceListingPath(String groupName, String apiDeclaration) {
                return BASE_PATH;
            }
        };
    }

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .pathProvider(customPathProvider())
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.codependent.api"))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(myApiInfo());
    }
```
But this doesn't work either:
```
basePath : "/"
...
paths :   
   /customer
```
Either the base path is not affected by the path provider or I am doing something wrong...

**Comment by codependent** [comment]
@dilipkrish Any comment about this please? `PathProvider` allows us to customize the endpoint paths but not the base path.

**Comment by cg-d** [comment]
In version 2.x you can override the getApplicationBasePath method of the PathProvider. Is that gone?

**Comment by codependent** [comment]
Yes, that method is not there anymore in 3.0.0:

https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/PathProvider.java#L22

package springfox.documentation;
```
public interface PathProvider {

  /**
   * Gets the sanitized and prepended with a "/" operation path
   * @param operationPath - raw operation path
   * @return sanitized and prepended with a "/" operation path
   */
  String getOperationPath(String operationPath);

  /**
   * Gets the resource listing path given a group name and api
   * @param groupName - group this resource listing belongs to
   * @param apiDeclaration - declared api name
   * @return this
   */
  String getResourceListingPath(String groupName, String apiDeclaration);
}
```
And this was in 2.9.2:

https://github.com/springfox/springfox/blob/2.9.2/springfox-core/src/main/java/springfox/documentation/PathProvider.java#L28

```
package springfox.documentation;

public interface PathProvider {

  /**
   * Gets the application base path
   * @return application base path
   */
  String getApplicationBasePath();

  /**
   * Gets the sanitized and prepended with a "/" operation path
   * @param operationPath - raw operation path
   * @return sanitized and prepended with a "/" operation path
   */
  String getOperationPath(String operationPath);

  /**
   * Gets the resource listing path given a group name and api
   * @param groupName - group this resource listing belongs to
   * @param apiDeclaration - declared api name
   * @return this
   */
  String getResourceListingPath(String groupName, String apiDeclaration);
}
```

**Comment by codependent** [comment]
@dilipkrish Could you have a look at this issue? I submitted a PR to allow setting the basePath at Docket level since we can't do it anymore from the PathProvider (the method getApplicationPath is not there anymore y 3.0.0).

It is a must in the project I'm working for so that I cant seamlessly integrate with an API Manager.

**Comment by Blokko** [comment]
My simple workaround, but I really hope 3.0.0 will released soon ;)
```
import java.util.List;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

import io.swagger.models.Swagger;
import springfox.documentation.spring.web.json.JacksonModuleRegistrar;
import springfox.documentation.spring.web.json.Json;
import springfox.documentation.spring.web.json.JsonSerializer;
import springfox.documentation.spring.web.paths.Paths;

@Component
@Primary
public class CustomBasePathJsonSerializer extends JsonSerializer {

    @Value("${server.servlet.context-path}")
    private String contextPath;

    public CustomBasePathJsonSerializer(List<JacksonModuleRegistrar> modules) {
        super(modules);
    }

    @Override
    public Json toJson(Object toSerialize) {
        if (toSerialize instanceof Swagger) {
            Swagger swagger = (Swagger) toSerialize;
            swagger.basePath(contextPath + Paths.ROOT);
        }
        return super.toJson(toSerialize);
    }

}
```

**Comment by frecco75** [comment]
I think the easiest way to add a base path is to use plugins and extend `WebMvcSwaggerTransformationFilter`.

Simply create the following bean :

```java
@Component
@Order(SWAGGER_PLUGIN_ORDER)
public class OverrideSwaggerBasePathFilter implements WebMvcSwaggerTransformationFilter {

    @Override
    public Swagger transform(final SwaggerTransformationContext<HttpServletRequest> context) {
        Swagger swagger = context.getSpecification();
        return swagger.basePath("/basePath" + swagger.getBasePath());
    }

    @Override
    public boolean supports(final DocumentationType documentationType) {
        return SWAGGER_2.equals(documentationType);
    }
}
```
If you use Spring Webflux, just inherit `WebFluxSwaggerTransformationFilter`.

Note to the swagger team :
I thing SwaggerTransformationFilter should be an abstract class implementing the supports method

**Comment by thomasmey** [comment]
can someone please reopen this issue?

I keeps me from updating to v3.

**Comment by EduardoFLima** [comment]
I was able to solve this issue by adding the context path to the paths regex. The ideal was to have the context path in the base path but if this is not that important and you just want to list your paths correctly, it might be the solution:

```
    @Autowired
    private ServletContext context;

    @Bean
    public Docket apiDoc() {
        return new Docket(DocumentationType.OAS_30)
                .apiInfo((new ApiInfoBuilder()).build())
                .useDefaultResponseMessages(false)
                .select()
                .paths(documentedPaths())
                .build();
    }

private Predicate<String> documentedPaths() {
        return regex(context.getContextPath() + "/.*");
    }
```

**Comment by kushsharma1001** [comment]
Hi Team,
I have 3 controller classes in my Springboot project exposing APIs. I have a query regarding configuring the SwaggerConfig. I wish to generate the swagger ui docs for the apis exposed in IECC class only. Now, I have 2 issues:

1) I have multiple classes exposing APIs within the same package. Hence, I strictly want to generate swagger ui docs for APIs in only 1 class i.e. IECC class.

com.abc.ISECC.class
 
  GET (ist/v1.0/{tenantID}/capabilities/{capability})
  GET (ist/v1.0/{tenantID}/capabilities)
  GET (ist/v1.0/capabilities) @RequestParam(capabilityName)
  
com.abc.ICC.class

  PUT (ist/v1.0/tenants/{tenantId}) @RequestBody
  GET (ist/v1.0/dependencies)
  DELETE (ist/v1.0/tenants/{tenantId})
  
com.abc.ISCC.class

  PUT (ist/v1.0/capabilities) @RequestBody
  DELETE (ist/v1.0/capabilities) @RequestBody
  GET (ist/v1.0/capabilities)
  
How can I achieve this? What should i write in apis() and paths():

@Configuration
public class SawggerConfig {
    @Bean
    public Docket databaseApi() {
        return new Docket(DocumentationType.SWAGGER_2).select()
        .apis(?)
        .paths(?)
        .build();
}

**Comment by nareshdeeti** [comment]
> My simple workaround, but I really hope 3.0.0 will released soon ;)
> 
> ```
> import java.util.List;
> 
> import org.springframework.beans.factory.annotation.Value;
> import org.springframework.context.annotation.Primary;
> import org.springframework.stereotype.Component;
> 
> import io.swagger.models.Swagger;
> import springfox.documentation.spring.web.json.JacksonModuleRegistrar;
> import springfox.documentation.spring.web.json.Json;
> import springfox.documentation.spring.web.json.JsonSerializer;
> import springfox.documentation.spring.web.paths.Paths;
> 
> @Component
> @Primary
> public class CustomBasePathJsonSerializer extends JsonSerializer {
> 
>     @Value("${server.servlet.context-path}")
>     private String contextPath;
> 
>     public CustomBasePathJsonSerializer(List<JacksonModuleRegistrar> modules) {
>         super(modules);
>     }
> 
>     @Override
>     public Json toJson(Object toSerialize) {
>         if (toSerialize instanceof Swagger) {
>             Swagger swagger = (Swagger) toSerialize;
>             swagger.basePath(contextPath + Paths.ROOT);
>         }
>         return super.toJson(toSerialize);
>     }
> 
> }
> ```
Hi @Blokko, I'm facing same issue, can you say how i can use this implementation with docket

**Comment by Bernardoklopf** [comment]
Solution Here > https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by Bernardoklopf** [comment]
I added the following config into my `application.yaml` file:

> springdoc:
>   swagger-ui:
>     configUrl: /pathProvider/v3/api-docs/swagger-config
>     disable-swagger-default-url: true
>     urls[0]:
>       url: /pathProvider/v3/api-docs/mobile-bff
>       name: <pathName>

where `pathProvider` should be replaced by the PathProvider config in the old swagger 2 yaml

and also, had do add a server into the OpenAPI object with the same PathProvider name.

`@Bean
    fun springShopOpenAPI(): OpenAPI? {
        return OpenAPI().addServersItem(Server().url("/pathProvider"))`
