### ISSUE TITLE
 springfox swagger generates api Doc in rather strange format

### ISSUE THREAD

**Issue by vijayakumar-psg587** [springfox/springfox#2821]
HI , this is a one of type question.  I am receiving a strange response from the swagger/json /the open-API spec 
![ui](https://user-images.githubusercontent.com/13768891/49924290-e77fb780-fedb-11e8-9ef4-6bba0cadd880.png)
![swagger-config](https://user-images.githubusercontent.com/13768891/49924297-ebabd500-fedb-11e8-8380-1be9d7a886c9.png)

Why is that an xml element is added  - <JSON> when the openAPI spec is expected to be in the JSON format. The result is neither a JSON nor an XML. I do not have any parsers specified in my springboot pom and by default it would take the JAX-RS for parsing. 

Please let me know if I could modify the v2/api-doc response to parse only the JSON and remove the XML element - <JSON>.

**Comment by vijayakumar-psg587** [comment]
Is there a way that I can get hold of the response of v2/api-docs so that I can write a filter to rewrite the response?

**Comment by vijayakumar-psg587** [comment]
Is there a way that I can capture the response in a filter, modify the response stream and then do chain.doFilter ()

**Comment by vijayakumar-psg587** [comment]
Could someone help me out please?

**Comment by dilipkrish** [comment]
@vijayakumar-psg587 I don't understand your question. Where are you seeing the xml? Also this project doesn't support JAX-RS. Have you read [the docs](http://springfox.github.io/springfox/docs/current/#plugins) for extensibility?

**Comment by vijayakumar-psg587** [comment]
@dilipkrish I did read the docs. 

The problem is the springfox implemented swagger-ui provides a link to the openAPI spec through /v2/api-docs (swagger2) . On click of it, the openApi spec needs to be generated in a JSON format. Surprisingly for me, it gets generated in a mix of XML and JSON format. I can find the spec in the JSON format, but before all the spec there is an xml element added -`<JSON>` and I do not know how to get rid of this. I am unsure how it is getting generated as well.  I understand that the crux of the issues lies elsewhere but since I have inherited the code , i am unable to find out where exactly the issue is. Hence I took the short route of just deleting the XML element alone -<JSON> and then provide the user with the API spec on click of the v2/api-docs link

I also made `MappingJackson2HttpMessageConverter `as my default by including the jackson jars in my dependency pom but that didn't help as well

So I was wondering if a filter can be implemented, catch the response before being sent to the client and modify its content.? I am unsure if it can be done, since it is implemented by the springfox jars and the control directly goes there. 

Please let me know if it is not clear. I understand that this is strange and probably be a one off. I  will try to explain it in a different manner if the above statements are not clear

**Comment by dilipkrish** [comment]
@vijayakumar-psg587 seems like the object mapper that you're using in your application is different than the one used by swagger. Try to see if JAXB is in your dependency tree and remove that if you're not using it. What version of springfox are you using?

**Comment by vijayakumar-psg587** [comment]
@dilipkrish I use version 2.9.2 . I will check if JAXB is present and let you know shortly

**Comment by vijayakumar-psg587** [comment]
@dilipkrish Yes there was jaxb instance imported via a transitive dependency. I did clear that out and added  jackson explicitly . But still I am endingup with the same issue. Can I redefine my objectMapper to something like this? [snippet](git clone https://Vijayakumar_psg587@bitbucket.org/snippets/Vijayakumar_psg587/LeaEa7/override-objectmapper-to-remove-which-is.git) I am unsure how to do that for OPENAPI spec as objectMapper.readValue expects a source class that is to be read and a destination class to which it should map to? Would this work?

**Comment by amutsch** [comment]
@vijayakumar-psg587 
Have you checked out the documentation on configuring the object mapper?
http://springfox.github.io/springfox/docs/current/#configuring-the-objectmapper

**Comment by vijayakumar-psg587** [comment]
Thanks @amutsch. I will check that out.  I did not do that before.

**Comment by vijayakumar-psg587** [comment]
@amutsch I am unable to define a deserializer in the Objectmapper of swagger. Could you please guide me?

```
@Component
public class SwaggerObjectMapperConfig implements ApplicationListener<ObjectMapperConfigured> {

    @Override
    public void onApplicationEvent(ObjectMapperConfigured event) {
        // TODO Auto-generated method stub
        System.out.println("application event is called" + event.getObjectMapper());
        event.getObjectMapper().reader(SwaggerJSONDeserializer.class);
        System.out.println("another log");
    }

}

```

**Comment by amutsch** [comment]
@vijayakumar-psg587 

Is your project available on github or another repository I would be able to take a look at otherwise if you provide information about your project dependencies I can try and setup a sample to reproduce what you are seeing and doing.

**Comment by vijayakumar-psg587** [comment]
@amutsch let me try uploading removing project specific details. Please give me a few min

**Comment by vijayakumar-psg587** [comment]
Here is the pom - [link](https://Vijayakumar_psg587@bitbucket.org/snippets/Vijayakumar_psg587/pexo4E/pom-dependency.git)

Here are the config files -  [webconfig](https://Vijayakumar_psg587@bitbucket.org/snippets/Vijayakumar_psg587/9eBo47/webconfig.git)
[SwaggerConfig](https://Vijayakumar_psg587@bitbucket.org/snippets/Vijayakumar_psg587/ReMgBq/swaggerconfig.git)

**Comment by vijayakumar-psg587** [comment]
@amutsch  I am sorry. there are a few confidential files I am unable to upload the module to repo

**Comment by amutsch** [comment]
@vijayakumar-psg587 
Let me create an example project out of what you have provided and see what I can find.

**Comment by amutsch** [comment]
@vijayakumar-psg587 

I set up a very small service to try and simulate the problem and my service looks fine,  swagger-ui.html came up without issue and the api-docs came up without issue as well.  There is something more inside your project that is causing problems.  

Do you have annotations or documentation on your rest methods in your controller that may be causing issues?

It didn't cause problems for me but I did notice you had many test only dependencies not marked test scope which impacts which libraries are on the classpath at runtime.

**Comment by vijayakumar-psg587** [comment]
@amutsch thank you for the effort. I really appreciate it.  I did setup a test project in my local with a few controllers and I wasn't able to replicate the issue as well. I guess its a very strange issue  and I am unsure as to what causes it. Hence thought of just removing the xml element - <JSON> before being served to the user. I guess the only way for me to write from scratch :(

**Comment by vijayakumar-psg587** [comment]
@amutsch Can you provide a sample where objectmapper of swagger is used to read or write the openAPI spec data? I guess if I figure that out then I would be able to add my snippet for modifying the response

**Comment by amutsch** [comment]
@vijayakumar-psg587 removing a json tag may or may not solve your issue but at the least I wouldn't think that to be an object mapper job.  I would lean towards using a controllerAdvice if you are looking to hack the response.

Like I mentioned before the problem could originate from data within additional annotations you are using, conflicting mappers in the system, unexpected libraries due to test dependencies not properly scoped.

**Comment by vijayakumar-psg587** [comment]
@amutsch That makes sense. Let me try scanning the entire app and remove any such discrepant annotations. Thanks though

**Comment by vijayakumar-psg587** [comment]
@amutsch I am trying to make use of the filter and I am almost there , but reading, modifying and rewriting to the filter is where I am stuck. Could you please take a look at this and let me know where I am making the mistake?

https://stackoverflow.com/questions/53867077/cannot-write-new-response-in-servlet-filter

**Comment by vijayakumar-psg587** [comment]
@amutsch and @dilipkrish I have found the answer and posted the same. Sorry that the resolution is not related to springfox implementation of swagger. I am closing the issue. Thanks again for the help and guideline

**Comment by Alokaryak** [comment]
@vijayakumar-psg587 Can you please let me know how you get the details in pretty format? I am also getting the documentation in strange format!

**Comment by Alokaryak** [comment]
> @amutsch and @dilipkrish I have found the answer and posted the same. Sorry that the resolution is not related to springfox implementation of swagger. I am closing the issue. Thanks again for the help and guideline

Where have you posted the answer? Thanks and am looking forward to it!

**Comment by vijayakumar-psg587** [comment]
@Alokaryak so I have posted the answer in stackoverflow. Here is the link to it again

https://stackoverflow.com/questions/53867077/cannot-write-new-response-in-servlet-filter
