### ISSUE TITLE
@ApiParam(example="..") doesn't work for @RequestBody

### ISSUE THREAD

**Issue by StasKolodyuk** [springfox/springfox#2822]
Hi!
`@ApiParam(example="..")` doesn't work for `@RequestBody`.
For example, in such case "message" is not rendered in Swagger UI.
```
    @PostMapping(path = "/simple")
    String simple(@ApiParam(example = "message") @RequestBody String body) {
        return body;
    }
```

I've already investigated the problem, will submit a PR soon.
Thanks

**Comment by jaco0646** [comment]
Per the documentation of [@ApiParam](http://docs.swagger.io/swagger-core/current/apidocs/io/swagger/annotations/ApiParam.html#example()), **example** is "for non-body type parameters" so it should not be expected to work with @RequestBody; **examples** "applies only to BodyParameters". The fix for this bug report seems to have been applied to the wrong element.

**Comment by jaco0646** [comment]
@mmamyan, that's correct: neither _example_ nor _examples_ work with @RequestBody. There are numerous reports of this, notably #2753 and #2783. My point was simply that _example_ should not be expected to work, whereas _examples_ should.

The only parameter I've seen actually affect the generated Swagger example is to implement a [ParameterBuilder](https://springfox.github.io/springfox/javadoc/current/springfox/documentation/builders/ParameterBuilder.html) and set the `modelRef`. The `complexExamples` method does not work either.

**Comment by mmamyan** [comment]
@jaco0646  it didn't solve my problems,, i guess it's ui problem ...

**Comment by nabarun12** [comment]
Any updates on this yet?

**Comment by ironijunior** [comment]
I'm facing the same problem. `v2.9.2`
Any news?

**Comment by dumbdonkey** [comment]
same problem here

**Comment by smily75** [comment]
I have the same problem, in the swagger ui it doesn't work, but in the editor I see the example. Is anything wrong with my configuration?
