### ISSUE TITLE
Alternate Type based on superclass or interface

### ISSUE THREAD

**Issue by stickhandle** [springfox/springfox#2823]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by stickhandle** [comment]
I'd like to create an alternate type rule where original type can be the super or interface of the class being processed. 
For example, if I have class Dog extends Animal, and the Docket builder defines:
```
.alternateTypeRules(AlternateTypeRules.newRule(Animal.class, String.class))
```
I would expect the swagger output to define Dog as a string. Is this possible? I've searched for this and looked at the codebase, and it doesn't seem to be there.

**Comment by dilipkrish** [comment]
Alternate type rules are explicit. You can [use conventions](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/schema/AlternateTypeRuleConvention.java) to solve that yourself, see [this example](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/JacksonSerializerConvention.java)

**Comment by monkeydp** [comment]
I have same problem, do you resolve it?
I declared a interface of enum, but I would expect enum to be shown on the swagger api debug page
I also try to use example of @ApiModelProperty or subType of @ApiModel, all useless

**Comment by monkeydp** [comment]
I have same problem, do you solve it?
I declared a interface of enum, but I would expect enum to be shown on the swagger api debug page
I also try to use example of @ApiModelProperty or subType of @apimodel, all useless

**Comment by monkeydp** [comment]
I have same problem, do you solve it?
I declared a interface of enum, but I would expect enum to be shown on the swagger api debug page
I also try to use example of @ApiModelProperty or subType of @ApiModel, all useless

**Comment by monkeydp** [comment]
I have same problem, do you solve it?
I declared a interface of enum, but I would expect enum to be shown on the swagger api debug page
I also try to use example of @ApiModelProperty or subType of \@ApiModel, all useless

**Comment by monkeydp** [comment]
I have same problem, do you solve it?
I declared a interface of enum, but I would expect enum to be shown on the swagger api debug page
I also try to use example of @ApiModelProperty or subType of @`ApiModel, all useless
