### ISSUE TITLE
Question: replace one parameter with multiple ones

### ISSUE THREAD

**Issue by jedrz** [springfox/springfox#2827]
Let's say I have a handler method that takes class `Example` that has couple of fields. By default fields are expanded into handler method parameters. What I want to achieve is to disable `Example` expanding and add some parameters manually (I have `HandlerMethodArgumentResolver` implemented which does the expansion on Spring side).

I managed to disable expanding - I added `Example` to `ignoredParameterTypes`. Then I started implementing `OperationBuilderPlugin` to add new parameters in place of ignored `Example` type. The problem is I have to build `Parameter` manually which requires a lot of code and I can't rely on provided model sustitutions and so on. Is it possible to read parameters from some kind of registry?

**Comment by dilipkrish** [comment]
You can use the `ApiImplicitParams` to customize the parameters you expect to receive after the `HandlerMethodArgumentResolver` does its magic

**Comment by jedrz** [comment]
Ok, I understand. Thank you for the help.
