### ISSUE TITLE
Swagger isn't working with @Validated annotation and implementing interface in REST Controller

### ISSUE THREAD

**Issue by rgampa** [springfox/springfox#2829]
```
<dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>2.9.2</version>
            </dependency>
```

The RESTController in our project is implementing an interface methods, which is working fine with Swagger, and /swagger-ui.html is correctly displaying the API. 

Recently we added bean and path param validations, so had to add `org.springframework.validation.annotation.Validated` annotation on REST Controller, on UI it's saying no API found. Then I have tried to narrow down the issue, if I removed interface implementation then it started working. is it known issue?

Another issue not related above issue, the base URL is shown as 120.0.0.0:8080, instead of host. However the /api-docs URL is correctly formed with Azure App service endpoint, can you send some pointers how to fix the base URL issue?

**Comment by mishatim** [comment]
We are seeing the same problem. It would be very helpful if this issue was addressed some time soon, please.

**Comment by zqq90** [comment]
+1

**Comment by mseiwert** [comment]
Same problem for me.

As far is I can tell, the problem is caused by `new Docket().apis(RequestHandlerSelectors.basePackage(...))` and `@Validated` annotation creating a proxy class. Due to the proxy class and the basePackage selector the filtering won't work.

Besides that, the `@Validated` annotation will lead to a swagger.json like this
![image](https://user-images.githubusercontent.com/927153/61215428-280e1080-a70b-11e9-9f47-21cde8d93d2f.png)

**Comment by black-jack-j** [comment]
@mseiwert Hi, I'd faced the same problem and found two workarounds: you can use either additional interface defined in the same classfile as your controller:
```java
interface Foo extends GeneratedFoo{}

public class Controller implements Foo{}
```
or you can change proxy_mode of the controller (this way no '$-proxy' will be displayed in swagger.json):
```java
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)
public class Controller implements GeneratedFoo{}
```

**Comment by d2sts2** [comment]
I have the same issue in version  3.0.0
The interface workaround did not work (may be because Im using 3 interfaces) 
Using @Scope(proxyMode = ScopedProxyMode.TARGET_CLASS) seems to work
