### ISSUE TITLE
Optional header parameter overrides the parameter for a query one called 'present'

### ISSUE THREAD

**Issue by ibianchi** [springfox/springfox#2831]
**Description**

Is there an issue while dealing with `Optional<>` header parameters? Instead of getting the expected values I'm getting a *query* parameter called *present*.

I want to override the handling of the BadRequests from missing values of several header params (injected with \@RequestHeader) with the Java's Optional. Here's an example:

```
@GetMapping
  @ApiOperation(
      value = "Demo",
      notes = "Demo optional header error"
  )
  @ApiResponses({
      @ApiResponse(code = 200, message = "okey"),
      @ApiResponse(code = 403, message = "ko"),
      @ApiResponse(code = 404, message = "ko")
  })
  public ResponseEntity<Object> fooMethod(
      @ApiParam(value = "foo msg", example = "foo example", type = "header", required = true) @RequestHeader("foo") Optional<String> foo,
      HttpServletRequest request
  ){
   {...}
}
```

Spring is reacting well, recognizing both valued and null states. The *required* value as true is important, as I want to be reflected that way on the documentation.

The issue then, is that I receive the following output in the swagger json output.

I can guarantee that the Optional in the query params (`@RequestParam` annotation) are accepted correctly, so I assume that the issue is with the HeaderParam.

Without the Optional header param I get the Desired example output below.

**Current Example Output**

```
paths": {
    "/foo": {
        "get": {
            "tags": [
                "Foo"
            ],
            "summary": "Foo summary",
            "description": "Foo description",
            "operationId": "fooUsingGET",
            "produces": [
                "application/json"
            ],
            "parameters": [
                {...},
                {
                    "name": "present",
                    "in": "query",
                    "required": false,
                    "type": "boolean"
                }
            ]
        }
    }
}
```

**Desired example output**

```
paths": {
    "/foo": {
        "get": {
            "tags": [
                "Foo"
            ],
            "summary": "Foo summary",
            "description": "Foo description",
            "operationId": "fooUsingGET",
            "produces": [
                "application/json"
            ],
            "parameters": [
                {...},
                {
                    "name": "fooParam",
                    "in": "header",
                    "description": "foo param from header",
                    "required": true,
                    "type": "string",
                    "x-example": "fooooo"
                }
            ]
        }
    }
}
```

**Versions**

- springBootVersion = '1.4.7.RELEASE'
- springfox-swagger2' = '2.9.2'
- springfox-swagger-ui' = '2.9.2'

---

Many thanks,

**Comment by YalaTest** [comment]
Have you tried adding `genericModelSubstitutes(Optional.class)` as mentioned in https://github.com/springfox/springfox/issues/1848?
