### ISSUE TITLE
Snake_case for Swagger documentation using spring-boot-starter-data-rest not working for POJO's.

### ISSUE THREAD

**Issue by ajkush** [springfox/springfox#2837]
I am using swagger for the documentation of spring-boot-starter-data-rest project. In application.properties file, I have configured: `spring.jackson.property-naming-strategy=SNAKE_CASE` naming strategy but unfortunately, I am getting camelCase in swagger documentation. But, the same configuration is working if I change the project from `spring-boot-starter-data-rest` to `spring-boot-starter-web`. Below are the dependencies I am using with `spring boot 2.1.1.RELEASE`.

        `<dependencies>
    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger-ui</artifactId>
        <version>2.9.2</version>
    </dependency>
    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger2</artifactId>
        <version>2.9.2</version>
    </dependency>
    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-data-rest</artifactId>
        <version>2.9.2</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-rest</artifactId>
    </dependency>
</dependencies>`

Now with this configuration, in API POST method is expecting snake_case and in the documentation, swagger is showing camelCase. I don't have the option neither to change from snake_case to camelCase nor spring-boot-starter-data-rest to spring-boot-starter-web.

**Comment by ajkush** [comment]
formatting

**Comment by ajkush** [comment]
Updated heading

**Comment by ajkush** [comment]
below code did the magic for me.

        @Configuration
        public class ObjectMapperAutoConfiguration implements WebMvcConfigurer {
        
            @Override
            public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
                ObjectMapper objectMapper = null;
                for (HttpMessageConverter converter : converters) {
                    if (converter instanceof MappingJackson2HttpMessageConverter ) {
                        MappingJackson2HttpMessageConverter jacksonConverter =
                                ((MappingJackson2HttpMessageConverter) converter);
        
                        if (objectMapper == null) {
                            objectMapper = jacksonConverter.getObjectMapper();
                        } else {
                            jacksonConverter.setObjectMapper(objectMapper);
                        }
                    }
                }
            }
        }

**Comment by ashishrawat2911** [comment]
> below code did the magic for me.
> 
> ```
>     @Configuration
>     public class ObjectMapperAutoConfiguration implements WebMvcConfigurer {
>     
>         @Override
>         public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
>             ObjectMapper objectMapper = null;
>             for (HttpMessageConverter converter : converters) {
>                 if (converter instanceof MappingJackson2HttpMessageConverter ) {
>                     MappingJackson2HttpMessageConverter jacksonConverter =
>                             ((MappingJackson2HttpMessageConverter) converter);
>     
>                     if (objectMapper == null) {
>                         objectMapper = jacksonConverter.getObjectMapper();
>                     } else {
>                         jacksonConverter.setObjectMapper(objectMapper);
>                     }
>                 }
>             }
>         }
>     }
> ```

This worked for me
```
@Configuration
    public class ObjectMapperAutoConfiguration implements WebMvcConfigurer {

        @Override
        public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
            ObjectMapper objectMapper = null;
            for (HttpMessageConverter converter : converters) {
                if (converter instanceof MappingJackson2HttpMessageConverter ) {
                    MappingJackson2HttpMessageConverter jacksonConverter =
                            ((MappingJackson2HttpMessageConverter) converter);

                    if (objectMapper == null) {
                        objectMapper = jacksonConverter.getObjectMapper();
                        //Added this
                        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
                    } else {
                        jacksonConverter.setObjectMapper(objectMapper);

                    }
                }
            }
        }
    }
```
