### ISSUE TITLE
SpringFox support x-logo

### ISSUE THREAD

**Issue by rabiehaed** [springfox/springfox#2846]
I use springfox and the following plugin to generate swagger from spring boot:	
groupid : com.github.kongchen</groupId>
<artifactId:> swagger-maven-plugin</artifactId>

----------------------------------------------------------------------								

	<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
-------------------------------------------------------------------------------

**They ask to add x-logo as below** 

  {
    "swagger": "2.0",
    "info": {
    "description": "",
    "version": "3.4.5",
    "title": "API",
    "x-logo": {
    "url": "/redoc/logo.png",
    "backgroundColor": "#FFFFFF"
    }

what I understand, that springfox do not support x-logo
I try to make classe  @SwaggerDefinition , but it is not invoking at all.
**what is the solution?**
use another plugin to generate swagger !

**Comment by atkawa7** [comment]
@rabiehaed Hi you can use springfox to generate x-logo. See https://github.com/atkawa7/httpsnippet for an example on how to do that using springfox swagger extensions
