### ISSUE TITLE
Springboot webapp takes over 6 minutes to start up due to swagger ApiListingReferenceScanner

### ISSUE THREAD

**Issue by cmachemer73** [springfox/springfox#2849]
I'm using version 2.9.2.

I've been trying to get swagger to find my controllers and produce docs for them, but when I succeed, it causes startup time to increase from 15-20 seconds, all the way up to nearly 7 minutes.

Is there a way to reduce this either by faster or more narrow PathSelectors, or perhaps even do it at build time rather than run time?

**Comment by amutsch** [comment]
@cmachemer73 
What does your docket setup look like.

You should be able to narrow the scan for swagger with defining the docket.
http://springfox.github.io/springfox/docs/current/#configuration-explained

**Comment by cmachemer73** [comment]
I am limiting its scope but it still takes over 6 minutes.  Am I doing it wrong?

@Bean |  
public Docket allEncompassingApi() {
      Docket aDocket = new Docket(DocumentationType.SWAGGER_2)
        .groupName("allApi")
        .select()
        .apis(RequestHandlerSelectors.basePackage("com.chewy.search.rest"))
        .paths(PathSelectors.ant("/v1/**"))
        .build();
        return aDocket;
    }

**Comment by bjconlan** [comment]
I guess the next question is how many controllers would be picked up from this? (Or how constrained is the environment your working in?)

**Comment by cmachemer73** [comment]
It should (and does) pick up just two controllers, totaling 11 method calls between them.  So I’m not sure what it’s spending all its time doing.  As for the environment, I’m running this so far, just on my MacBook Pro, using java 8.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by cmachemer73** [comment]
@amutsch Any other questions or suggestions?

**Comment by amutsch** [comment]
@cmachemer73 
I haven't had much time to dig into this as my day job is keeping me busy.  Do you have this on github where I could take a closer look?  

I have setup a number of microservices with springfox and haven't seen anything like this but the applications are tiny.  

How many 3rd party libraries are involved and how big is the code base you are adding springfox to?

**Comment by cmachemer73** [comment]
@amutsch A coworker was able to trace this to the fact that we're using protobuf objects that take a very long time for swagger to parse through.
