### ISSUE TITLE
"can't read swagger JSON from http://localhost:8080/project/api-docs"s question.

### ISSUE THREAD

**Issue by zhangzhenhua92** [springfox/springfox#2852]
hello,sir:
      i want to ask you a question link here:
      "https://github.com/zhangzhenhua92/swagger-spring "
      
     For my project has integrate the swagger ,my project use Spring(3.1.3.RELEASED) but it didn't work, which told me that "Can't read swagger JSON from http://localhost:8080/api-docs".
     
     i wonder these questions:
     1.whether spring 3.1.3.RELEASED could'nt integrate swagger ?
     2.did the  "Can't read swagger JSON from http://localhost:8080/api-docs" is a bug that belongs to swagger?
     3.could you please help to look my project , the question has made me confused for a long time.

      thank you.

**Comment by amutsch** [comment]
@zhangzhenhua92 
I reviewed your project and you are not using springfox swagger components in your pom file.

In general why are you using such old versions of spring and various other modules in the code setup.
Take a look at the springfox swagger example repository and there are many working examples there.
