### ISSUE TITLE
XML hints in the Model view show "OrderedMap" and other useless info.

### ISSUE THREAD

**Issue by mmamyan** [springfox/springfox#2853]
Cannot find a solution to get rid of all this xml info .. Have any ideas? 
![capture](https://user-images.githubusercontent.com/37372593/50832804-ba061c80-1368-11e9-8c42-5db9bf9ad335.PNG)
 
PS. I'm using the latest version of springfox-swagger(2.9.2).

**Comment by dilipkrish** [comment]
This should be fixed with the later versions of swagger-ui. Please open a new issue if its not working
