### ISSUE TITLE
Configure CORS Filter for oauth2 authentication (ClientCredentials)

### ISSUE THREAD

**Issue by kishm** [springfox/springfox#2857]
Hi,

I am new to SpringBoot, Springfox and Swagger2 as well. I am trying to generate Swagger2 API documentation with the help of Springfox.

I have gone through the documentation 'http://springfox.github.io/springfox/docs/current/' and able to generate API documentation.
But i am having issue to integrate with oauth2 authentication. I am trying to Implement oauth2 token to work on tryout option of each controller. With oauth/token (Client Credentials) implementation, able successfully connect my app login URL, but upon authentication the redirect URL is failing due to the following error.

The following exception is shown in browser"
Access to fetch at 'https://myauthserver/authserver/oauth/token' from origin 'http://myapp' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Token based implementation (jwt) working as expected. But I am looking to Implement oauth2 based login approach

Code:
springBootVersion = '2.1.1.RELEASE'
io.springfox:springfox-swagger-ui:2.9.2

@Configuration
@EnableSwagger2
public class SpringFoxConfig
{
   
   public static final String CLIENT_ID     = "client_id";
   public static final String CLIENT_SECRET = "client_secret";
   private static final String tokenEndpoint = "https://myauthserver/authserver/oauth/token";
   private static final String authorizationEndpoint = "https://myauthserver/authserver/oauth/authorize";
   
   
   @Bean
   public Docket apiDocket()
   {
      final List<ResponseMessage> globalResponses = Arrays.asList(
            new ResponseMessageBuilder().code(HttpStatus.OK.value()).message(StatusCodeConstants.OK).build(),
            new ResponseMessageBuilder().code(HttpStatus.ACCEPTED.value()).message(StatusCodeConstants.ACCEPTED)
                  .build(),
            new ResponseMessageBuilder().code(HttpStatus.BAD_REQUEST.value()).message(StatusCodeConstants.BAD_REQUEST)
                  .build(),
            new ResponseMessageBuilder().code(HttpStatus.INTERNAL_SERVER_ERROR.value())
                  .message(StatusCodeConstants.INTERNAL_SERVER_ERROR).build(),
            new ResponseMessageBuilder().code(HttpStatus.UNAUTHORIZED.value())
                  .message(StatusCodeConstants.UN_AUTHORIZED).build(),
            new ResponseMessageBuilder().code(HttpStatus.FORBIDDEN.value()).message(StatusCodeConstants.FORBIDDEN)
                  .build());
      
      return new Docket(DocumentationType.SWAGGER_2)
            .securitySchemes(Arrays.asList(new ApiKey("Token Access", HttpHeaders.AUTHORIZATION, In.HEADER.name()),
                  securityScheme()))
            .protocols(new HashSet<String>(Arrays.asList("https", "http"))).useDefaultResponseMessages(false)
            .globalResponseMessage(RequestMethod.GET, globalResponses)
            .globalResponseMessage(RequestMethod.POST, globalResponses)
            .globalResponseMessage(RequestMethod.DELETE, globalResponses)
            .globalResponseMessage(RequestMethod.PATCH, globalResponses).select()
            .apis(RequestHandlerSelectors.basePackage("com.example.app.docs")).paths(PathSelectors.ant("/v2/**"))
            .build().apiInfo(getApiInfo());
   }
   
   private SecurityScheme securityScheme()
   {
      GrantType grantType = new AuthorizationCodeGrantBuilder()
            .tokenEndpoint(new TokenEndpoint(tokenEndpoint, "oauthtoken"))
            .tokenRequestEndpoint(new TokenRequestEndpoint(authorizationEndpoint, CLIENT_ID, CLIENT_SECRET)).build();

      SecurityScheme oauth = new OAuthBuilder().name("oauth").grantTypes(Arrays.asList(grantType))
            .scopes(Arrays.asList(scopes())).build();

      return oauth;
   }

   private AuthorizationScope[] scopes()
   {
      AuthorizationScope[] scopes =
      { new AuthorizationScope("readwrite", "for read & write operations") };
      return scopes;
   }

   private ApiInfo getApiInfo()
   {
      return new ApiInfoBuilder().title("My Sample Swagger API")
            .description("My Sample Swagger API Description")
            .contact(new Contact("MyCompany", "http://mycompany.com", "support@domain.com")).version("1.0.0")
            .license("Apache 2.0")
            .licenseUrl("http://www.apache.org/licenses/LICENSE-2.0.html")
            .build();
   }
}

I tried the following suggested solutions to configure CORSFilter with the help of the following links, But seems to be none of them worked.

https://github.com/springfox/springfox/issues/2215
http://springfox.github.io/springfox/docs/current/#answers-to-common-questions-and-problems
https://stackoverflow.com/questions/45677048/how-do-i-enable-cors-headers-in-the-swagger-v2-api-docs-offered-by-springfox-sw?rq=1

@Configuration
public class WebConfig extends WebMvcConfigurerAdapter {

    @Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();

        CorsConfiguration config = new CorsConfiguration().applyPermitDefaultValues();
        config.setAllowCredentials(false);
        source.registerCorsConfiguration("/**", config);

        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(0);

        return bean;
    }
}
![image](https://user-images.githubusercontent.com/30115863/50959580-4c352e80-14e9-11e9-9bd4-5e9659aa3a55.png)

Is there a issue on Swagger-ui with 2.9.2 version? Any suggestions will greatly help.
Thank you

**Comment by Viktor-xx** [comment]
Hello  @kishm !
Configuration looks good, just use
**bean.setOrder(Ordered.HIGHEST_PRECEDENCE);** 
instead of 
**bean.setOrder(0);**

**Comment by Rebaiahmed** [comment]
> Hello @kishm !
> Configuration looks good, just use
> **bean.setOrder(Ordered.HIGHEST_PRECEDENCE);**
> instead of
> **bean.setOrder(0);**
> 
> security filters are registered with high priority, so you have to set higher order

Thanks, it helps me to resolve my problem
