### ISSUE TITLE
Problem with model generation using Mono in 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by xardas96** [springfox/springfox#2858]
Hi. I started using springfox-swagger2:3.0.0-SNAPSHOT in my project recently and changed all my endpoints to return a Mono value. The calls made from the swagger-ui are working fine, however there is a problem with model documentation generation. 
Before upgrading an example value used to be generated into the UI:
```
{
  "data": [
    {
      "id": "string",
      "type": "string",
      "attributes": {
        "elementType": "ELEMENT_TYPE",
        "friendlyName": "My element",
        "firmwareVersion": "0.1.2",
        "connectionStatus": "ONLINE",
        "batteryStatus": "GREEN",
        "positionState": "OPEN",
        "control": {
          "request": {},
          "state": {}
        }
      }
    }
  ]
}
```
After upgrading the value is empty:
`{}`

Example controller endpoint code:
```
@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    @ApiOperation(value = ListAllElements.VALUE, notes = ListAllElements.NOTES)
    Mono<JsonApiCollection<String, Element>> listAllElements(
            @RequestHeader(value = HeaderNames.USER_ID_HEADER) @ApiParam(hidden = true) String userId) {
        return elementRepository.findAll(userId)
                .map(JsonApiCollection::of);
    }
```

**Comment by nikita-clearscale** [comment]
**About the issue**
The problem that types like `Mono`, `Flux` are not added to springfox confuguration. Just cpoy and paste [RecursiveAlternateTypeRule.java](https://github.com/springfox/springfox/blob/master/springfox-petstore-webflux/src/main/java/springfox/documentation/schema/RecursiveAlternateTypeRule.java) po your sources and to `Docket` it as decribed [here](https://github.com/springfox/springfox/blob/master/springfox-petstore-webflux/src/main/java/springfox/petstore/webflux/PetStoreConfiguration.java).

**To springfox team**
Could springfox team please add `RecursiveAlternateTypeRule` with Flux,Mono, ResponseEntity etc. configuration to main code base? I think it can solve many issues like this one. And many recursive types can be easy added via pull request.

If there is a risk that this can break something consider to create separate configuration or mark this as experimental feature.
