### ISSUE TITLE
SpringFox and Swagger-ui misleading models if they have the same last name but in different packages

### ISSUE THREAD

**Issue by MarianMamdouh** [springfox/springfox#2859]
Hello, i have several generated classes from xsd files using jaxb like this:
com./////////////.a.x;
com./////////////.b.x;
com./////////////.c.x;
when i use them as request body or response model, only one of them is shown in swagger-ui overriding all the others.
i'm using version 2.9.2
any help?

**Comment by amertum** [comment]
You can use the `@ApiModel` annotation to override the naming.

But I agree that it is a problem. It would be great to have the possibility to enable errors for such behavior as it hides the fact that the model used is not the proper one.

**Comment by MarianMamdouh** [comment]
yeah it's a good work around but the models i'm talking about are XML ones, so when i'm changing the name using @ApiModel, the XML root elemant tag name is also changed which is not acceptable for me.
