### ISSUE TITLE
SwaggerConfig class break my Unit and integration tests

### ISSUE THREAD

**Issue by pagmaae** [springfox/springfox#2864]
<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.9.2</version>
		</dependency>
		
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger-ui</artifactId>
		    <version>2.9.2</version>
		</dependency>

**in app-context.xml:**

<mvc:resources location="classpath:/META-INF/resources/" mapping="swagger-ui.html"/>
	<mvc:resources location="classpath:/META-INF/resources/webjars/" mapping="/webjars/**"/>
  
 	<bean id="swagger2Config" class="springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration"/>
  
**Config class**
@Configuration
@EnableSwagger2
public class SwaggerConfig extends WebMvcConfigurationSupport{
	
	   /**
     * For for swagger configuration
     * @return Docket
     * 
     */
	
    @Bean
    public Docket newsApi() {
       // TypeResolver newRuletypeResolver;
		return new Docket(DocumentationType.SWAGGER_2).groupName("Email").apiInfo(apiInfo())
				.select()
        		.apis(RequestHandlerSelectors.basePackage("com...."))
        		.paths(PathSelectors.ant("/**")).build()
        		.genericModelSubstitutes(ResponseEntity.class);
    }
 
    private ApiInfo apiInfo() {
        return new ApiInfoBuilder().title("Email Service").description("Overview of Polling Procedure\r\n" + 
        		"\r\n" + 
        		"On a configurable basis (i.e. once every 60 seconds), the pre-established list of email boxes are polled by this service.\r\n" + 
        		
        		
        		"")
                .termsOfServiceUrl("/swagger-ui.html#/")
                .version("1.0").build();
    }
}

![image](https://user-images.githubusercontent.com/29925581/51144148-e5c84d00-1815-11e9-8755-25ec4bb23a4b.png)

**Comment by pagmaae** [comment]
When remove @Configuration, Unit test works but integration test not

**Comment by tsposato** [comment]
> When remove @configuration, Unit test works but integration test not

Did you ever get a resolution for this? I am experiencing the same problem with Spring boot 2.6 and Swagger 3.0.

**Comment by Kaushik27** [comment]
I am also facing similar issues, all my integration test are failing. Any resolution?
