### ISSUE TITLE
Problem with spring.jackson.property-naming-strategy.SNAKE_CASE 

### ISSUE THREAD

**Issue by Shaliov** [springfox/springfox#2865]
When you set _spring.jackson.property-naming-strategy.SNAKE_CASE_  to _**application.properties**_ all your json values are converted to lowercase. 

For example:

```
public class Test{

  @JsonProperty("Test_Test")
  private String test;
}
```

**Example value** would be :
```
{
  "test_test": "string"
}
```

but **expected**
```
{
  "Test_Test": "string"
}
```

And this example works correct: 

```
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class Test{

  @JsonProperty("Test_Test")
  private String test;
}
```

**Comment by sm-paul-schuette** [comment]
I was surprised by that behaviour as well. Wanted to open an issue and saw that there is already one.
