### ISSUE TITLE
i got a field with map(enum, Object),the key is a enum type, but is does not list the enum value, how to resolve the problem?

### ISSUE THREAD

**Issue by linzixiang199141** [springfox/springfox#2866]
i got a field with map(enum, Object),the key is a enum type, but is does not list the enum value, how to resolve the problem?

**Comment by linzixiang199141** [comment]
the version is 2.9.2

**Comment by dilipkrish** [comment]
Since open api doesn't support keys other than string, it cannot really be achieved.
