### ISSUE TITLE
@RequestBody annotation pulling up Class parms as Query type on swagger-ui

### ISSUE THREAD

**Issue by ss4852** [springfox/springfox#2870]
RequestMapping(value="search/members",  method = RequestMethod.POST,
            consumes = { "application/xml" },
            produces = {"application/xml","application/json"})
    @ApiImplicitParams({
            @ApiImplicitParam(name = "criteria", value = "\"$ref\": \"#/definitions/MemberDTO\"", dataType =  "Member" ,required = true, paramType = "body")
    })

    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content =  @Content(schema = @Schema(implementation = MemberDTO.class))),
            @ApiResponse(responseCode = "400", description = "Bad Request") }) 
    /**
     * Swagger implementation for the find  member service  - Ends
     */
    @POST
    @Path("search/members")
    @Produces({ServiceVersion.JSON ServiceVersion.XML})
    public Response findMem(@RequestBody MemberSCDTO criteria,DateParam eaoDate);

my swagger-ui displaying Request body and all the DTO parms as Query type in the Ui screen.

can someone please help.

**Comment by ss4852** [comment]
@dilipkrish @adrianbk @MaksimOrlov - can you please help

**Comment by ss4852** [comment]
Can someone plz help me

**Comment by mmamyan** [comment]
Are you using Jersey?

**Comment by ss4852** [comment]
No , we are using Jax-rs.
