### ISSUE TITLE
ParameterBuilderPlugin not being called

### ISSUE THREAD

**Issue by cbriarnold** [springfox/springfox#2871]
I am using 2.9.2

    <dependency>
    <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger2</artifactId>
        <version>2.9.2</version>
    </dependency>
    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger-ui</artifactId>
        <version>2.9.2</version>
    </dependency>

I have created a ParameterBuilder extending the ParameterBuilderPlugin to create custom documentation for the org.springframework.data.domain.Pageable. But this ParameterBuilder isn't being called

    @Component
    @ConditionalOnClass(value = Pageable.class)
    @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
    public class PageableParameterBuilder implements ParameterBuilderPlugin {
        private final TypeNameExtractor nameExtractor;
        private final TypeResolver resolver;
    
        @Autowired
        public PageableParameterBuilder(TypeNameExtractor nameExtractor, TypeResolver resolver) {
            this.nameExtractor = nameExtractor;
            this.resolver = resolver;
        }
    
        @Override
        public boolean supports(DocumentationType delimiter) {
            return true;
        }
    
        @Override
        public void apply(ParameterContext context) {
            ResolvedMethodParameter parameter = context.resolvedMethodParameter();
            ResolvedType type = parameter.getParameterType();
            if (type != null && Pageable.class.isAssignableFrom(type.getErasedType())) {
                Function<ResolvedType, ModelReference> factory = createModelRefFactory(context);
    
                ModelReference intModel = factory.apply(resolver.resolve(Integer.TYPE));
                ModelReference stringModel = factory.apply(resolver.resolve(List.class, String.class));
    
                List<Parameter> parameters = newArrayList(
                        context.parameterBuilder().parameterType("query").name("page")
                                .modelRef(intModel)
                                .description("Results page you want to retrieve (0..N)").build(),
                        context.parameterBuilder().parameterType("query").name("size")
                                .modelRef(intModel).description("Number of recods per page").build(),
                        context.parameterBuilder().parameterType("query").name("sort")
                                .modelRef(stringModel).allowMultiple(true)
                                .description("Sorting criteria in the format: property(,asc|desc). "
                                        + "Default sort order is ascending. "
                                        + "Multiple sort criteria are supported.")
                                .build());
    
                context.getOperationContext().operationBuilder().parameters(parameters);
            }
        }
    
        private Function<ResolvedType, ModelReference> createModelRefFactory(ParameterContext context) {
            ModelContext modelContext =
                    inputParam("", context.resolvedMethodParameter().getParameterType(),
                            context.getDocumentationType(), context.getAlternateTypeProvider(),
                            context.getGenericNamingStrategy(), context.getIgnorableParameterTypes());
            return (Function<ResolvedType, ModelReference>) modelRefFactory(modelContext,
                    nameExtractor);
        }
    }

Here is the controller endpoint that it should be describing

    @GetMapping("/list")
    public ResponseEntity<Page<String>> exampleEndpoint(Pageable pageable){

I have found that this is happening due to the shouldExpand logic in springfox.documentation.spring.web.readers.operation.OperationParameterReader

    private boolean shouldExpand(final ResolvedMethodParameter parameter, ResolvedType resolvedParamType) {
        return !parameter.hasParameterAnnotation(RequestBody.class)
            && !parameter.hasParameterAnnotation(RequestPart.class)
            && !parameter.hasParameterAnnotation(RequestParam.class)
            && !parameter.hasParameterAnnotation(PathVariable.class)
            && !isBaseType(typeNameFor(resolvedParamType.getErasedType()))
            && !enumTypeDeterminer.isEnum(resolvedParamType.getErasedType())
            && !isContainerType(resolvedParamType)
            && !isMapType(resolvedParamType);
    }

In the shouldExpand logic, there is no way to check to see if a parameter should be expanded, if it is supported, since the Pageable is automatically created and loaded.

I can't add the annotation of @RequestParam to the endpoint parameter, because then Spring won't process it the same way it currently processes Pageable classes. What would be the best way to handle this? Or does the OperationParameterReader need to be updated to handle this correctly?

**Comment by duberton** [comment]
Yeah, that would be good to have implemented. What are the options for this one?

Forced the **shouldExpand** method to return false (when the parameter was a Pageable), everything wen't great with your implementation @cbriarnold.

**Comment by cbriarnold** [comment]
@dilipkrish Do you have any insight into what could be done? I am willing to make the changes, but I don't understand why the shouldExpand logic was created instead of using the built in supports on the ParameterBuilderPlugin? (which isn't overriden correctly in this example)

**Comment by denis111** [comment]
I've come to the same problem, ParameterBuilderPlugin is not called because I use my own annotation on a POJO type which converts int to POJO but it gets expanded.
I found similar issue https://github.com/springfox/springfox/issues/1825 but I don't like the idea to copy-paste and mantain in sync with upstream the whole OperationParameterReader class just to change the shouldExpand method because it's private and we can't just override it.

**Comment by cbriarnold-gmail** [comment]
@dilipkrish I hear that you need help. I am willing to make a fix for this issue, since I will definitely benefit from it. Do you have any suggestions for it? Or should I just take a wack at it?
