### ISSUE TITLE
Support Java 11

### ISSUE THREAD

**Issue by lassounski** [springfox/springfox#2872]
Hello Swagger developers!

Java 9 has been around for a while with its Jigsaw module for modularization and I understand that this is breaking change for many libraries in the Java ecosystem.

I am starting a new project with Java 11 and my question is: When are you guys planning in releasing a Java 9+ compatible Swagger library?

Cheers!!!

**Comment by sabareeshkkanan** [comment]
Do you see any incompatibilities as of now ? I am not experiencing any issues on java 11

**Comment by lassounski** [comment]
Cool! Thanks for the feedback.

**Comment by yuryrep** [comment]
> Do you see any incompatibilities as of now ? I am not experiencing any issues on java 11

Can you, please, provide your module-info.java, because right now I can not run swagger 2.9.2 version with java 11 due such errors 
`Error:java: module spring.context reads package springfox.documentation.schema from both springfox.schema and springfox.core`

**Comment by SamyBacha** [comment]
Hi,
Same  problem for me  
[ERROR] module springfox.spring.web reads package springfox.documentation.service from both springfox.spi and springfox.core

**Comment by nullptr7** [comment]
Same issue here, I am not sure if there are any workaround.
