### ISSUE TITLE
@ApiResponses(examples = @Example(value = {@ExampleProperty(value="")})) not working 

### ISSUE THREAD

**Issue by prisin** [springfox/springfox#2873]
I am using springfox 2.9.2.  Examples from ApiResponse annotations not showing in both swagger json and swagger ui . I see that the fix is added for this in 3.0.0 springfox release. May i know when this release will be available and if there is any temporary fix i can use for now ?

**Comment by mmamyan** [comment]
@prisin Wanted so open the same issue... "Examples" don't work in swagger at all and I don't know what to do..

**Comment by ksrh** [comment]
Related issues are closed.

https://github.com/springfox/springfox/issues/2538
https://github.com/springfox/springfox/issues/2352

I really need that feature

**Comment by sboursault** [comment]
duplicates #2767 ?

**Comment by devatlant** [comment]
Any update on this issue?

**Comment by ogerardin** [comment]
This is becoming a problem. There hasn't been a 3.0.0-snapshot since august so I don't think we can expect a release soon.
Has anyone succeeded in implementing a workaround to include examples in 2.9.2?
