### ISSUE TITLE
Question: Next release.

### ISSUE THREAD

**Issue by mmamyan** [springfox/springfox#2875]
Could you tell me when is the next release(or approximately)? @dilipkrish @adrianbk @MaksimOrlov

**Comment by vfedoriv** [comment]
Looks like the main contributor busy or lost interest to the project.

**Comment by will08rien** [comment]
https://github.com/springfox/springfox/issues/2699#issuecomment-457835002

Please have patience people! This maintainer has done an amazing job with this project in his own time.
