### ISSUE TITLE
Response Model are not collected in a project without SpringMvc

### ISSUE THREAD

**Issue by 151250010** [springfox/springfox#2884]
1, The version of springfox I used is 2.9.2
2, How does this happen?
I am customizing ApiListingScannerPlugin to collect all my http interfaces info of my customized mvc framework.
I am trying to collect response model info like this:
```java
private Set<ResponseMessage> responseMessages(Method method) {
        Class returnType = method.getReturnType();
        docket.additionalModels(typeResolver.resolve(returnType));
        return Collections.singleton(new ResponseMessageBuilder().code(200)
                .responseModel(new ModelRef(returnType.getSimpleName()))
                .message("")
                .build());
    }
```

But I found no model info appeared in swagger-ui:
![image](https://user-images.githubusercontent.com/19546964/51897896-b5260d00-23ea-11e9-9b49-36731107b561.png)

3, My question
I found why this happened in ApiListingScanner#scan .

``` 
Map<String, Model> models = new LinkedHashMap<String, Model>();
      List<RequestMappingContext> requestMappings = nullToEmptyList(requestMappingsByResourceGroup.get(resourceGroup));
      for (RequestMappingContext each : sortedByMethods(requestMappings)) {
        models.putAll(apiModelReader.read(each.withKnownModels(models)));
        apiDescriptions.addAll(apiDescriptionReader.read(each));
      }
```

if no spring mvc RequestMapping info is collected,  method ApiModelReader#read will be missed so no additional models are collected.  

Is this a bug?
What would happen if global models are collected outside the foreach cycle?

**Comment by Cloudintheking** [comment]
I meet the same problem, do you solve it now?
