### ISSUE TITLE
springfox.documentation.swagger.v2.path=/whatever/v2/api-docs not working with 3.0.0-SNAPSHOT 

### ISSUE THREAD

**Issue by patpatpat123** [springfox/springfox#2886]
Hello Team, after switching to 3.0.0 SNAPSHOT, this property is not working anymore.
springfox.documentation.swagger.v2.path=...
With any version below 3.0.0, it works.
I am using Zuul to do gating one 100 Microservices based on /whateverservice/v2/api-docs
Could you please help fix this? :)
Thank you a lot.

@Override
    public List<SwaggerResource> get() {
        List<SwaggerResource> resources = new ArrayList<>();
        resources.add(swaggerResource(whateverservice, /whateverservice/v2/api-docs));
       ...
        return resources;
    }

 <repositories>
        <repository>
            <id>jcenter-snapshots</id>
            <name>jcenter</name>
            <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Finchley.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
 <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-spring-webflux</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

**Comment by jmcolyer** [comment]
This is working for me with dynamic Zuul routes.  I'm assuming that you've wired up your own SwaggerResourcesProvider.  Try setting the location explicitly.

    private SwaggerResource swaggerResource(String name, String location) {
        SwaggerResource swaggerResource = new SwaggerResource();
        swaggerResource.setName(name);
        swaggerResource.setLocation(location + "/v2/api-docs");
        return swaggerResource;
    }

**Comment by patpatpat123** [comment]
Hello,

Thank you for your answer.
This is exactly my point. In 2.9.2, without having to do 
private SwaggerResource swaggerResource(String name, String location) {
    SwaggerResource swaggerResource = new SwaggerResource();
    swaggerResource.setName(name);
    swaggerResource.setLocation(location + "/v2/api-docs");
    return swaggerResource;
}
But just with springfox.documentation.swagger.v2.path=/location/v2/api in the property could work.
Not in 3.0.0

**Comment by silentsnooc** [comment]
@jmcolyer Any chance you can post that `SwaggerResourcesProvider`?

**Comment by jmcolyer** [comment]
@Primary
    @Bean
    public SwaggerResourcesProvider swaggerResourcesProvider() {
        return () -> {
            List<SwaggerResource> resources = new ArrayList<>();
            this.routes.getRoutes().forEach(route ->
              resources.add(createResource(route.getId(), route.getPrefix(), "2.0")));
              resources.sort(Comparator.naturalOrder());
              return resources;
        };
    }

    private SwaggerResource createResource(String name, String location, String version) {
        SwaggerResource swaggerResource = new SwaggerResource();
        swaggerResource.setName(name);
        swaggerResource.setLocation(location + "/v2/api-docs");
        swaggerResource.setSwaggerVersion(version);
        return swaggerResource;
    }

**Comment by desiderati** [comment]
Why not just import the swagger.properties file in your configuration class using this: @PropertySource("classpath:swagger.properties")?

**Comment by kokhanchyk** [comment]
as a workaroud for this issue you can use:

````java
@Configuration
@Profile("swagger")
@EnableSwagger2WebFlux
public class SwaggerConfiguration {

private static final String SWAGGER_API_DOCS = "/v2/api-docs";

@Value("${springfox.documentation.swagger.v2.path}")
private String swagger2Endpoint;

@Bean
RouterFunction<ServerResponse> proxyRouterForSwagger() {
    return route(GET(swagger2Endpoint), req -> forwardRequest(SWAGGER_API_DOCS));
}

private Mono<ServerResponse> forwardRequest(String destinationUrl) {
    return ok().body(WebClient
           .create("http://localhost:8080")
           .get()
           .uri(destinationUrl)
           .retrieve()
           .bodyToMono(JsonNode.class), JsonNode.class);
}

@Bean
public Docket api(final TypeResolver typeResolver) {
    return new Docket(DocumentationType.SWAGGER_2)
          .host("api.your.host.com")
          .select()
          .apis(RequestHandlerSelectors.any())
          .paths(PathSelectors.any())
          .build()
            .protocols(newHashSet("http", "https"))
            .securitySchemes(newArrayList(jwtScheme()))
             .securityContexts(newArrayList(new SecurityContext(jwtAuth(),
                     regex("/xxxxx*"))));
  }
}
````


When you set swagger2Endpoint, and will call it, it will forward to standard "/v2/api-docs" under the hood.
Also dont forget to specify host in Docket bean, because it will overide by localhost. 
And port in localhost in   WebClient.create("http://localhost:8080") should be execly the same as your service is running on.

**Comment by theyellow** [comment]
If anyone (like me) is searching the property-name to set api-docs for OpenApi 3.0 (DocumentationType.OAS_30): You can override `springfox.documentation.open-api.v3.path` to set another path than the default `"/v3/api-docs"`
