### ISSUE TITLE
swagger maven plugin - to generate json/yaml

### ISSUE THREAD

**Issue by rkrgarlapati** [springfox/springfox#2887]
Hi,

Have used springfox dependencies in my spring boot application to show up swagger ui. Used annotation like @SwaggerDefinition and @EnableSwagger2.

I want to generate json/yaml file, referred the earlier post, which is similar to my requirement https://github.com/springfox/springfox/issues/2267

I can't use kongchen plugin because it's expecting me to keep @Api annotations all over my controller, which doesn't look pretty.

Any solution from Springfox for this issue ?

Thanks.

**Comment by wallbank** [comment]
I need this also so we can use Swagger output and swagger codegen to generate service clients

**Comment by SrikanthShyamanur** [comment]
Any update on this request ?

**Comment by nachogarrone** [comment]
you could use [https://github.com/kongchen/swagger-maven-plugin/](https://github.com/kongchen/swagger-maven-plugin/)

**Comment by dilipkrish** [comment]
You could simply generate it as part of an integration test, similar to how spring restdocs works. Also have you looked at https://github.com/Swagger2Markup/swagger2markup?

**Comment by philsturgeon** [comment]
I just asked this question over on springdoc-openapi-maven too: https://github.com/springdoc/springdoc-openapi-maven-plugin/issues/17

What's the export of OpenAPI got to do with integration-tests? And why is it not easy to do? Can we not just get an export command like PHP, Ruby, JavaScript, and all the other annotation systems?

**Comment by philsturgeon** [comment]
I just asked this question over on springdoc-openapi-maven too: https://github.com/springdoc/springdoc-openapi-maven-plugin/issues/17

What's the export of OpenAPI got to do with integration-tests? And why is it not easy to do? Can we not just get an export command like PHP, Ruby, JavaScript, and all the other annotation systems?

```shell
vendor/bin/openapi -o openapi.json
```

**Comment by philsturgeon** [comment]
Be gone stalebot, you are not useful.

**Comment by falk-stefan** [comment]
@wallbank Me too.. please tell me how you solved your issue ([see](https://stackoverflow.com/questions/65632370/how-to-dump-swagger-yaml-in-gradle-build-script)). Previously I did this with Maven but I decided to (finally) switch over to Gradle..

What I am looking for is basically a "Dump Swagger YAML"-mode for the server or just any way to produce the YAML file for me.

**Comment by michaelwangwangwang** [comment]
> date on this request
it just support swagger 2.0
