### ISSUE TITLE
Performance degrades in such pattern when using springfox swagger API for rest documentation

### ISSUE THREAD

**Issue by Ramprabu1983** [springfox/springfox#2890]
Hi,

************ Issue *************

We have swagger enabled in our Spring Boot Micro service project. It really works great. During performance testing we have identified one of request at every 30 seconds takes 8 times higher then the actual time. For instance our API takes usually 30 to 50 ms (milliseconds) to process the request, but the request comes at 30th second will take around 450 ms. We are using routing and load balancer components like Zuul, Eureka, Ribbon and thought some of these components might impact the performance, after removing all these 3 components we still had that performance issue.

Finally we removed the Swagger completely and gained all the performance back, like all request takes only 30 to 50 ms only. We are not sure what Swagger is trying to do at every 30th second, also we were trying to find a way to disable or extend the 30th second to some number. No luck.

We understand that 450 ms at 30th second costs less only, but we are having millions of requests everyday so we have to fix that.

********** Dependency details *************

compile group: 'io.springfox', name: 'springfox-swagger2', version: '2.8.0'
compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.8.0'

After Gradle build I see below JARs pulled from Maven artifactory.
springfox-swagger2-2.8.0.jar
springfox-swagger-ui-2.8.0.jar
springfox-spi-2.8.0.jar
springfox-schema-2.8.0.jar
springfox-swagger-common-2.8.0.jar
springfox-spring-web-2.8.0.jar
springfox-core-2.8.0.jar

Also I am seeing there are some other Swagger JARs in the classpath, I think that comes with Spring Boot.
swagger-annotations-1.5.14.jar
swagger-models-1.5.14.jar

***********Java Configuration******************

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Tag;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
@EnableWebMvc
public class SwaggerConfig extends WebMvcConfigurerAdapter {
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2)
				.select()
				.apis(RequestHandlerSelectors.basePackage("com.test"))
				.paths(PathSelectors.any())
				.build()
				.apiInfo(apiInfo())
				.tags(new Tag("Test","Microservices"));
	}

	private ApiInfo apiInfo() {
		return new ApiInfoBuilder()
				.title("Title")
				.description("Description")
				.termsOfServiceUrl("terms@test.com")
				.license("License")
				.licenseUrl("license@test.com")
				.version("2.0")
				.build();
	}
	
	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
	    registry.addResourceHandler("swagger-ui.html")
	      .addResourceLocations("classpath:/META-INF/resources/");
	 
	    registry.addResourceHandler("/webjars/**")
	      .addResourceLocations("classpath:/META-INF/resources/webjars/");
	}
}

Are you seeing any problem in the configuration, but this the constant configuration for all Spring Boot application. Please let me know your suggestions.

FYI. We deployed the application in Production without Swagger this time, and performance quite good.

**Comment by Ramprabu1983** [comment]
Its been more than 2 months, I just want to know if swagger is really impacting the performance of spring boot service calls. If so please let me know how to resolve that.

**Comment by Ramprabu1983** [comment]
@dilipkrish, Please take a look this issue.

**Comment by 0ffer** [comment]
@Ramprabu1983 
Hello! I also meet this problem.
I noticed that the problem is not in springfox.
I have test app with spring boot and springfox. When I use old version of spring boot (2.0.3 in my case) I see the problem. When I update spring boot from 2.0.4 to 2.0.5 then delays have become less, but more frequent (once at 10 seconds). With spring boot 2.0.7 to 2.0.8 update delays are gone.
With latest in my case srping boot 2.2.0 I am also not see delays.

I can see delays only when start application from jar (but not see when start from IDE).
I look at changelogs on spring and spring boot but not see some similar resolved issues.

As a result I didn't find the original problem =(
