### ISSUE TITLE
How to generate a PDF from OpenAPI 3.0?

### ISSUE THREAD

**Issue by karunchinna** [springfox/springfox#2896]
I have an OpenAPI 3.0 spec and I want to generate a PDF out of it so that it can be given to the end users.

Currently, tools like swagger-spec-to-pdf or swagger2markup only support Swagger 2.0 but not OpenAPI 3.0. Is it possible to generate a PDF from an OpenAPI 3.0 ?

**Comment by hc-codersatlas** [comment]
Don't think OpenAPI 3.0 is supported yet.

**Comment by ABoat365** [comment]
@karunchinna https://swagger-fly.com/,power by RapiPDF
