### ISSUE TITLE
empty swagger-resources with spring-cloud-stream

### ISSUE THREAD

**Issue by ilkerkorkut** [springfox/springfox#2899]
Issue:

```
Dependency                  |   Version
------------------------------------------
spring-cloud-stream         | 2.1.0.RELEASE
springfox-swagger2          | 3.0.0-SNAPSHOT
springfox-spring-webflux    | 3.0.0-SNAPSHOT
springfox-swagger-ui        | 3.0.0-SNAPSHOT

```
When adding **spring-cloud-stream** as a dependency ,Swagger-ui completely crashes because of **/swagger-resources** returns [] empty array.

UI Error : **Could not render e, see the console.**

Can we add manually swagger-resources when they ware empty or how to prevent overriding that swagger-resources?

**Comment by richard-vanneck** [comment]
I have the same issue, when calling /swagger-ui.html I get this error:

root-injects.js:95 TypeError: Cannot read property 'url' of undefined
    at e.value (topbar.jsx:127)
    at e.t.render (root-injects.js:93)
    at s._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at s._renderValidatedComponent (ReactCompositeComponent.js:819)
    at s.performInitialMount (ReactCompositeComponent.js:359)
    at s.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at s.performInitialMount (ReactCompositeComponent.js:368)
    at s.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)

This inly happens when I add the **spring-cloud-stream** dependency

**Comment by uhelmare** [comment]
The same on my side :(

**Comment by peter-kori** [comment]
I have the same issue on Swagger UI (3.0.0-SNAPSHOT) as @richard-vanneck 
Spring boot (2.1.3.RELEASE) Application with dependency on **spring-cloud-stream** (2.1.0.RELEASE)

In other spring boot (2.1.3.RELEASE) Application without dependency on spring-cloud-stream swagger UI works

**Comment by epoddubny** [comment]
I have the same problem. I use springfox-spring-webflux 3.0.0-SNAPSHOT and spring-cloud-starter-stream-rabbit 2.0.2-RELEASE

**Comment by Tavisco** [comment]
Up! Having the same issue using `spring-integration-core` and `spring-integration-file`

**Comment by Tavisco** [comment]
Was able to make the library work doing what's suggested here:
https://github.com/springfox/springfox/issues/2802#issuecomment-456283262

After adding `springfox-spring-integration-webmvc` and `spring-integration-http` to my `pom.xml` the `/swagger-resources` endpoint was populated without issues!

**Comment by jgaybjone** [comment]
I solved the problem.
```
@Bean
@Primary
DocumentationPluginsBootstrapper documentationPluginsBootstrapper(DocumentationPluginsManager documentationPluginsManager,
                                                                      List<RequestHandlerProvider> handlerProviders,
                                                                      DocumentationCache scanned,
                                                                      ApiDocumentationScanner resourceListing,
                                                                      TypeResolver typeResolver,
                                                                      Defaults defaults,
                                                                      PathProvider pathProvider,
                                                                      Environment environment) {
        final DocumentationPluginsBootstrapper documentationPluginsBootstrapper = new DocumentationPluginsBootstrapper(documentationPluginsManager, handlerProviders, scanned, resourceListing, typeResolver, defaults, pathProvider, environment);
        documentationPluginsBootstrapper.start();
        return documentationPluginsBootstrapper;
    }
```

**Comment by fabiojb** [comment]
> Was able to make the library work doing what's suggested here:
> [#2802 (comment)](https://github.com/springfox/springfox/issues/2802#issuecomment-456283262)
> 
> After adding `springfox-spring-integration-webmvc` and `spring-integration-http` to my `pom.xml` the `/swagger-resources` endpoint was populated without issues!

For **spring-webflux**, I solved the problem adding the dependencies `springfox-spring-integration-webflux` and `spring-integration-webflux`.

See the dependencies docs:
https://github.com/springfox/springfox/tree/master/springfox-spring-integration-webflux
https://github.com/spring-projects/spring-integration/blob/master/src/reference/asciidoc/webflux.adoc

**Comment by fabiojb** [comment]
> Was able to make the library work doing what's suggested here:
> [#2802 (comment)](https://github.com/springfox/springfox/issues/2802#issuecomment-456283262)
> 
> After adding `springfox-spring-integration-webmvc` and `spring-integration-http` to my `pom.xml` the `/swagger-resources` endpoint was populated without issues!

For **spring-webflux**, I solved the problem adding these two dependencies:

- springfox-spring-integration-webflux
- spring-integration-webflux

See the dependencies docs:
https://github.com/springfox/springfox/tree/master/springfox-spring-integration-webflux
https://github.com/spring-projects/spring-integration/blob/master/src/reference/asciidoc/webflux.adoc
