### ISSUE TITLE
Springfox ignores field annotations if spring.jackson.property-naming-strategy is set

### ISSUE THREAD

**Issue by xokker** [springfox/springfox#2904]
### The bug
If the property `spring.jackson.property-naming-strategy` is defined inside a spring boot application, field annotations `@JsonProperty("<new-name>")`, `@ApiModelProperty("<new-name>")`, `@ApiParam("<new-name>")` are ignored by the springfox.  

### How to reproduce
1. Clone this repo https://github.com/xokker/springfox-namingstrategy-bug
2. Run `mvn spring-boot:run` 
3. Open `http://localhost:8080/swagger-ui.html` in the browser and try to make a request to `/bug` endpoint – the model says the name of the field should be `some_value`, but the result is `someValue`

### Related issues
#2865 looks like the same issue
#1436 might be related to the current bug

**Comment by xokker** [comment]
@dilipkrish I can try to fix it if you show me where to start digging

**Comment by durimkryeziu** [comment]
It's happening the same here: https://github.com/durimkryeziu/demo-json-property-is-ignored

**Comment by dimovelev** [comment]
I have the same issue in the latest version. It has been around for a while without a solution - I would be happy if anyone has a workaround.

**Comment by dimovelev** [comment]
Actually, I have find the workaround and I advise anyone with issues to try it out https://springdoc.org/#getting-started

**Comment by burakturker** [comment]
I have the same issue in  2.9.2 version
