### ISSUE TITLE
Ignore the Object as a parameter in another Object.

### ISSUE THREAD

**Issue by arjenzhou** [springfox/springfox#2905]
There is an Object as a parameter in another Object, they are communicated by using mybatis.
But when I using Swagger UI there are always the related Object seen in the Swagger `Parameters`.

**e.g.** In Job Class there is a Company Object as a parameter, when run Swagger UI there are Company's parameters shown, like `company.companySize` which is not expected.

I have tried `@ApiModelProperty(hidden = true)` on `private Company company;`, but it does not work.

Thanks!

**Comment by imdreamrunner** [comment]
I am having the same issue using `2.9.2`. Is there any solutions / workaround?

**Comment by arjenzhou** [comment]
@imdreamrunner Not yet. :(

**Comment by dilipkrish** [comment]
This issue should no be fixed in 3.0.0-SNAPSHOT
