### ISSUE TITLE
How to configure BasicAuth for Swagger UI?

### ISSUE THREAD

**Issue by aknobloch** [springfox/springfox#2908]
Using SpringFox v. 2.9.2 and Spring Security v. 1.4.1.RELEASE

This is a question, and I'm sure is just a mistake in configuration on my end.

I have the following Docket configuration:

```
	@Bean
	public Docket api() {

		SecurityReference securityReference = SecurityReference.builder()
				.reference("basicAuth")
				.scopes(new AuthorizationScope[0])
				.build();

		ArrayList<SecurityReference> reference = new ArrayList<>(1);
		reference.add(securityReference);

		ArrayList<SecurityContext> securityContexts = new ArrayList<>(1);
		securityContexts.add(SecurityContext.builder().securityReferences(reference).build());

		ArrayList<SecurityScheme> auth = new ArrayList<>(1);
		auth.add(new BasicAuth("basicAuth"));

		return new Docket(DocumentationType.SWAGGER_2)
				.securitySchemes(auth)
				.securityContexts(securityContexts)
				.select()
					.apis(RequestHandlerSelectors.basePackage("com.my.package.directory"))
					.paths(PathSelectors.any())
					.build()
				.apiInfo(getApiInfo());
	}
```

The following Spring security configuration (defined in `boostrap` file):

```
security.user.name=jdoe
security.user.password=123456
```

When navigation to my swagger page, I see the following UI layout:

![image](https://user-images.githubusercontent.com/9557120/53030788-89ba9f00-3439-11e9-8a7e-65bb94353420.png)

I am able to access any of the endpoints at this time, and hit them as usual. When selecting the "authorize" button, I get the following UI:

![image](https://user-images.githubusercontent.com/9557120/53030846-abb42180-3439-11e9-884e-ec9143b78d75.png)

On that page, I can enter in literally any combination of username/passwords and it will display the following:

![image](https://user-images.githubusercontent.com/9557120/53030926-d00ffe00-3439-11e9-91eb-4410f9cfcfc1.png)

And, just like before I logged in, I am able to access any of the endpoints.

My expectation (desire) is that when navigating to the page, none of the endpoints will be usable by the user. They will receive a 401, or the "Try it Out" button will be disabled, until they login. The login credentials should only accept preconfigured combinations (jdoe/123456). 

Like I said, I'm sure this is just a misconfiguration on my end, but after a few days of spinning my wheels, digging through documentation and StackOverflow, I'm not sure what I'm missing. Any help or guidance would be appreciated!

**Comment by MrMedTech** [comment]
Same Problem here. Did you solve it?

**Comment by epiard13** [comment]
@dilipkrish Any thoughts on the above please? thx

**Comment by aknobloch** [comment]
> Same Problem here. Did you solve it?

@MrMedTech - Sorry for the delayed response, but no I was unable to solve this. I ended up going with securing the entire Swagger UI via Spring Security instead, so you cannot even access Swagger until entering credentials. I would prefer the integrated security so external users can still see the  available endpoints and associated documentation, though.

**Comment by MrMedTech** [comment]
@aknobloch thanks for reply. I also wasn't able to solve it. I digged around in swagger auth and I found out that with using token-based auth you can add a path where to get the token. So maybe that's a solution to go with. I'll give it a try in the future ( not highest priority right now) and report if it worked

**Comment by bgiaccio** [comment]
I'd be interested in seeing how you secured the page with spring-security.  I seem to be able to get /swagger-ui.html to load without auth and later when /v2/api-docs  is called then spring-security is trying to takeover which doesn't work properly.

**Comment by czgab** [comment]
I found the solution, also using SpringFox v. 2.9.2, hope it helps.

```java
    @Bean
    public Docket actuatorApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("Spring Actuator")
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.ant("/actuator/**"))
                .build()
                .apiInfo(apiInfo())
                .securityContexts(Arrays.asList(actuatorSecurityContext()))
                .securitySchemes(Arrays.asList(basicAuthScheme()));
    }

    private SecurityContext actuatorSecurityContext() {
        return SecurityContext.builder()
                .securityReferences(Arrays.asList(basicAuthReference()))
                .forPaths(PathSelectors.ant("/actuator/**"))
                .build();
    }

    private SecurityScheme basicAuthScheme() {
        return new BasicAuth("basicAuth");
    }

    private SecurityReference basicAuthReference() {
        return new SecurityReference("basicAuth", new AuthorizationScope[0]);
    }
```

**Comment by muneshshar** [comment]
this works very fine. thank you @czgab

**Comment by muneshshar** [comment]
I would like to hide the api-docs url from apiInfo section, can someone suggest me on this?

**Comment by ajith-om** [comment]
Thanks for sharing this. It works charm. 
I would like to have one more use case along with this. I would like to display some custom description like some message about what to be entered username below basic Authorization header/above username field. How do i achieve this ? Please help me.

**Comment by ynztrifork** [comment]
@czgab SecurityContext  doesn't have a builder method; which package was referred?

**Comment by RoyTal28** [comment]
Thanks for the examples.
Yet, I don't understand how I can verify the correct credentials?
I currently have a login verification logic that confirms the credentials and defined in spring security.
And I want to use it as basic authentication for swagger.
Do u have an example for that?

**Comment by ShawnWangNYT** [comment]
> Thanks for the examples.
> Yet, I don't understand how I can verify the correct credentials?
> I currently have a login verification logic that confirms the credentials and defined in spring security.
> And I want to use it as basic authentication for swagger.
> Do u have an example for that?

If you are using spring, you can add your AuthenticationManager implementation in the project. Every api call with basic auth with call the AuthenticationManager the do the authentication first.

**Comment by lunyi** [comment]
After clicking Authorize button, where I can get username/password in  AuthorizeAttribute or IOperationFilter ??  https://user-images.githubusercontent.com/9557120/53030846-abb42180-3439-11e9-884e-ec9143b78d75.png

**Comment by blaqniz** [comment]
How do I validate username and password when I have this code: 

@Configuration
@EnableSwagger2
@Profile({Constants.PROFILE_LOCAL, Constants.PROFILE_UAT})
public class SwaggerConfig {

    @Value("${version.number}")
    private String version;

    @Bean
    public Docket api() {

        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo())
                .securitySchemes(Arrays.asList(securityScheme()))
                .securityContexts(Arrays.asList(securityContexts()));
    }

    private ApiInfo apiInfo() {

        return new ApiInfoBuilder()
                .title("My API")
                .description("My API Documentation")
                .version(version)
                .build();
    }

    private SecurityContext securityContexts() {
        return SecurityContext.builder()
                .securityReferences(Arrays.asList(basicAuthReference()))
                .forPaths(PathSelectors.any())
                .build();
    }

    private SecurityScheme securityScheme() {
        return new BasicAuth("basicAuth");
    }

    private SecurityReference basicAuthReference() {
        return new SecurityReference("basicAuth", new AuthorizationScope[0]);
    }
}

At the moment I can login with any credentials and even when I don't provide any credentials, I can still access the APIS.

![image](https://user-images.githubusercontent.com/31017791/76896409-6d866d00-689a-11ea-87a2-e603d6537513.png)

**Comment by Reloadly** [comment]
> I found the solution, also using SpringFox v. 2.9.2, hope it helps.
> 
> ```java
>     @Bean
>     public Docket actuatorApi() {
>         return new Docket(DocumentationType.SWAGGER_2)
>                 .groupName("Spring Actuator")
>                 .select()
>                 .apis(RequestHandlerSelectors.any())
>                 .paths(PathSelectors.ant("/actuator/**"))
>                 .build()
>                 .apiInfo(apiInfo())
>                 .securityContexts(Arrays.asList(actuatorSecurityContext()))
>                 .securitySchemes(Arrays.asList(basicAuthScheme()));
>     }
> 
>     private SecurityContext actuatorSecurityContext() {
>         return SecurityContext.builder()
>                 .securityReferences(Arrays.asList(basicAuthReference()))
>                 .forPaths(PathSelectors.ant("/actuator/**"))
>                 .build();
>     }
> 
>     private SecurityScheme basicAuthScheme() {
>         return new BasicAuth("basicAuth");
>     }
> 
>     private SecurityReference basicAuthReference() {
>         return new SecurityReference("basicAuth", new AuthorizationScope[0]);
>     }
> ```

@czgab Great find, thanks! 
Do you know if there's a way to hide the url as well until the user is authenticated? thx

**Comment by epiard13** [comment]
> I found the solution, also using SpringFox v. 2.9.2, hope it helps.
> 
> ```java
>     @Bean
>     public Docket actuatorApi() {
>         return new Docket(DocumentationType.SWAGGER_2)
>                 .groupName("Spring Actuator")
>                 .select()
>                 .apis(RequestHandlerSelectors.any())
>                 .paths(PathSelectors.ant("/actuator/**"))
>                 .build()
>                 .apiInfo(apiInfo())
>                 .securityContexts(Arrays.asList(actuatorSecurityContext()))
>                 .securitySchemes(Arrays.asList(basicAuthScheme()));
>     }
> 
>     private SecurityContext actuatorSecurityContext() {
>         return SecurityContext.builder()
>                 .securityReferences(Arrays.asList(basicAuthReference()))
>                 .forPaths(PathSelectors.ant("/actuator/**"))
>                 .build();
>     }
> 
>     private SecurityScheme basicAuthScheme() {
>         return new BasicAuth("basicAuth");
>     }
> 
>     private SecurityReference basicAuthReference() {
>         return new SecurityReference("basicAuth", new AuthorizationScope[0]);
>     }
> ```

@czgab Great find, thanks!
Do you know if there's a way to hide the url as well until the user is authenticated? thx

**Comment by epiard13** [comment]
> > Same Problem here. Did you solve it?
> 
> @MrMedTech - Sorry for the delayed response, but no I was unable to solve this. I ended up going with securing the entire Swagger UI via Spring Security instead, so you cannot even access Swagger until entering credentials. I would prefer the integrated security so external users can still see the available endpoints and associated documentation, though.

Hi @aknobloch Can you show how you accomplished this please? thanks

**Comment by aknobloch** [comment]
@epiard13 - I don't work on that project anymore, and it's been so long I can't quite remember my solution. I'm fairly certain I did something similar to [this](https://www.baeldung.com/spring-security-basic-authentication), but modified the `configure` method to authenticate against the Swagger pages. Sorry I can't help more!

**Comment by aknobloch** [comment]
It looks like @czgab has provided a working solution. I'm going to close this issue, since it's over a year old and the remainder of comments are general discussion better fit for a help forum rather than a GitHub issue report.
