### ISSUE TITLE
Swagger doesn't generate definitions for Mono<ResponseEntity<User_Defined_class>> classes

### ISSUE THREAD

**Issue by AnkBurov** [springfox/springfox#2911]
Hi. I've just upgraded to 3.0.0-SNAPSHOT and noticed that Swagger doesn't generate definitions for response types like Mono<ResponseEntity<User_Defined_class>>. Here is an example: 
```kotlin
fun getFullData(@RequestBody request: Request): Mono<ResponseEntity<Response>>
```
For this method Swagger generates no definition: 
> Resolver error at definitions.Service response model.properties.techData.$ref
Could not resolve reference: Could not resolve pointer: /definitions/ResponseTechData does not exist in document

`/api-docs` url with `swagger.json` also doesn't contain models that are properties of Response class. When I removed reactive Mono type and left response type as ResponseEntity<Response> everything was working fine. I also checked that simple reactive types like Mono<Response> also work and their definitions are generated by Swagger as well. So the problem is precisely when a type is a reactive type wrapping Spring Web Response Type wrapping custom classes.

Is there a way to specify Springfox how to unwrap specific types?

**Comment by balasenthil-d** [comment]
There is a solution proposed at https://github.com/springfox/springfox/issues/2858
