### ISSUE TITLE
com.google.common.util.concurrent.UncheckedExecutionException

### ISSUE THREAD

**Issue by MiniApp** [springfox/springfox#2920]
spring project use springfox-swagger2 version 2.9.2;
this exception is happened on use shiro

**Comment by MiniApp** [comment]
> spring project use springfox-swagger2 version 2.9.2;
> this exception is happened on use shiro

springfox.documentation.schema.property.CachingModelPropertiesProvider - Exception calculating properties for model(..) -> ModelContext{..}. java.lang.NullPointerException

**Comment by doribd** [comment]
i am having the same problem as a warning
