### ISSUE TITLE
How to include Webflux and RouterFunctions

### ISSUE THREAD

**Issue by mheidt** [springfox/springfox#2921]
I made it work with @EnableSwagger2WebFlux
But it doesn't show any operations.
When I define

```java
return new Docket(DocumentationType.SWAGGER_2).select()
                .apis(RequestHandlerSelectors.any())
            .build().apiInfo(apiEndPointsInfo());
```

the read-operation-handler and web-flux-links-handler are shown at least.

I am not using @path annotations but
public RouterFunction monoRouterFunction

which defines routes like
.andRoute(GET("/any-route"),anyRouterHandler::test)

I added @ApiOperation to this anyRouterHandler.test function.
I tried @Api anotions at this handler or the RoutingConfiguration but all to no avail.

What am I missing?

And i have kotlin models and repositories. But I didn't expect those to show up anyways :)

**Comment by RandomChap** [comment]
Hey there buddy,

Were you able to get around this problem? I've got the same thing going on for me and don't seem to know how to figure it out - Kotlin RouterFunctions aren't picked up by @EnableSwagger2WebFlux. Got any advice on how to make it work?

**Comment by nebrass** [comment]
I have the same issue.. never could to make the RouterFunction appear in swagger-ui 😭

**Comment by bjab** [comment]
Looking at class WebFluxRequestHandlerProvider, it's not implemented yet :)

**Comment by dilipkrish** [comment]
Its definitely implemented to handle regular request mappings, but not router functions yet. Duplicate of #2799

**Comment by chamithchathuka** [comment]
Is this done?
https://stackoverflow.com/questions/68266480/springboot-springfox-starter-3-0-0-unable-to-detect-webflux-routerfuntion
