### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by EdwardDrapkin** [springfox/springfox#2924]
There's been no release since last June, almost a year.

There's been no feedback from developers on critical issues like Spring Boot 3 and Spring 5 support.

It doesn't look like there's been any work happening in the repository other than maintenance tasks.
  
Is this project fully abandonware?

**Comment by dilipkrish** [comment]
@EdwardDrapkin It is certainly not abandon ware... working on getting OAS 3.x support here #2022

**Comment by jpgough** [comment]
@dilipkrish it looks like there are a fair few issues that have been raised and some may need closing out, labelling etc. If you want help triaging some of these issues I'd be happy to help go through and add labels, ask for more information from the issue raiser where necessary.

**Comment by LukeButters** [comment]
should this ticket be closed? This is the second left open is this still maintained ticket.

**Comment by helt** [comment]
I bump this issue, because it still is valid. OpenApi 3.0 not yet supported, Spring-Boot 2.2.1+ causing lots of issues. Apart from a August 2019 message, progress seems infinitely slow.
