### ISSUE TITLE
How to document multiple return types with the same status code? (versioning an API action)

### ISSUE THREAD

**Issue by stowns** [springfox/springfox#2928]
- I am currently using 3.0.0-SNAPSHOT of springfox-swagger2, springfox-spring-webflux and springfox-swagger-ui.

My Controller Actions return different DTO objects based on the version of the API being requested. This allows me to maintain a single controller definition for multiple versions of my API. A user simply passes a 'version' header and Controller logic returns DtoV1, DtoV2, etc. However, if I attempt to decorate my Controller Action with the following, only 1 of the 200 statusCode responses is documented.

```
@ApiResponses(value = {
        @ApiResponse(code = 200, message = "v1 version of the response", response = Dto.class, responseContainer = "Page"),
        @ApiResponse(code = 200,  message = "v2 version of the response", response = DtoV2.class, responseContainer = "Page")
    })
```
Is there a way to annotate a single Controller Action to document different version behaviors?

**Comment by stowns** [comment]
I have been able to implement this behavior via a combination of custom annotation and OperationBuilderPlugin. will try and post some examples soon

**Comment by bastman** [comment]
@stowns, I'm facing the same issue. Could you please provide your example solution? Thanks a lot :)

The issue ...

Currently, it looks like it is impossible to define an api endpoint that returns a union type, e.g:

GET /api/foo-or-bar -> returns 200: Foo | Bar

If I remember the specs right, "oneOf" should be our friend.
