### ISSUE TITLE
Guava Dependency

### ISSUE THREAD

**Issue by DixonIvey** [springfox/springfox#2931]
I love what SpringFox offers and I really want to use it. I'm using the current released version of Swagger (2.9.2) in a Spring Boot app. This version of SpringFox seems to require guava 20+ at runtime. I want to use it in a project that is capped at guava 17. Is there any way around this? Besides maybe using an older version of SpringFox. Thank you!

**Comment by atkawa7** [comment]
@DixonIvey See #2935

**Comment by kalexmills** [comment]
EDIT: seems this will be fixed as part of 3.0, for which I see PRs that purport to remove guava as a dependency.
