### ISSUE TITLE
Maven repository for springfox-spring-webflux ?

### ISSUE THREAD

**Issue by arpitkh12** [springfox/springfox#2939]
In which maven repo can I find springfox-spring-webflux ?

I am trying to using springfox-spring-weblux for spring-weblflux project. Can someone please tell me in which maven repository can I find this project.

**Comment by msogrin** [comment]
Currently, it's only available in a shapshot repository as version `3.0.0-SNAPSHOT`. https://springfox.github.io/springfox/docs/snapshot/#dependencies

**Comment by arpitkh12** [comment]
Do we have a release plan or date when we will have a stable version?

**Comment by jgguevara** [comment]
Do you have an idea/plan when the 3.0.0 will be released on Maven Central?

**Comment by arpitkh12** [comment]
What is the timeline for release of 3.0.0 in maven central ?

**Comment by RestfulBlue** [comment]
any updates? ;_;

**Comment by Invoker-liu** [comment]
waiting  for release,dont cry for me

**Comment by Invoker-liu** [comment]
Avoid close,I leave a comment,looking forward to the release

**Comment by efsn** [comment]
https://repo1.maven.org/maven2/io/springfox/springfox-spring-webflux/2.10.5/

released

**Comment by dilipkrish** [comment]
@efsn thank you for that. FYI that is a temporary fix, until 3.0.0 goes out. Next week hopefully.
