### ISSUE TITLE
Springfox resolves incorrect required with @RequestHeader and @ApiParam

### ISSUE THREAD

**Issue by mikko-apo** [springfox/springfox#2944]
What version of the library are you using?: 2.9.2  Is it the latest version? yes 

What kind of issue is this?: Bug report

```
@RestController
class RequiredTestController() {
    @GetMapping("/requireShouldBeTrue")
    fun foo(
        @RequestHeader("Authorization") @ApiParam(example = SwaggerUIExampleAuthToken) authHeader: String
    ) {
    }
}
```
@RequestHeader has default `required=true` and @ApiParam has default `required=false`. In the resulting swagger json required is `false` when it should be `true`. Requests without Authorization won't pass Spring's validation so the generated documentation is wrong.

The issues related to this bug are:

1) Springfox generates incorrect value for the parameter because the ApiParam annotation is handled after RequestHeader and ApiParam's default overrides the correct value. Changing the resolving order might be an easy fix?

2) Developer can very easily make a mistake by adding an example value which breaks the documentation. It would be nice if SpringFox could warn if parameter resolving encounters a conflict.

Past issues:
https://github.com/springfox/springfox/issues/1083
https://github.com/springfox/springfox/issues/1948

**Comment by jjoslet** [comment]
This is the same problem with `@PathVariable`, `@RequestBody`, etc.

**Comment by jjoslet** [comment]
The question is answered in the FAQ: http://springfox.github.io/springfox/docs/current/#answers-to-common-questions-and-problems `Why are my API params marked as required=false?`.

Therefore, it would be nice to provide an alternative annotation to simply provide a description.

**Comment by mikko-apo** [comment]
I think in this case Springfox has incorrect default behaviour. The resulting document does not match reality and Springfox could make it easier for the developers to notice the incorrect combination of tag values.
