### ISSUE TITLE
swagger does not integrate with Spring X_FORWARDED_PREFIX as provided by ForwardedHeaderExtractingRequest

### ISSUE THREAD

**Issue by Beennnn** [springfox/springfox#2954]
Swagger with Spring 5.1.4 fails to extract X_FORWARDED_PREFIX.
In fact Spring provides a Request implemented by ForwardedHeaderExtractingRequest, removing X_FORWARDED_PREFIX form request Headers.

Fix : in class XForwardPrefixPathAdjuster, the call 
`this.request.Header(X_FORWARDED_PREFIX)` returning null is to be replaced with `this.request.getContextPath()`.

**Comment by vkennke** [comment]
I think this is related to https://github.com/springfox/springfox/issues/2622
