### ISSUE TITLE
Every api appears twice

### ISSUE THREAD

**Issue by greatyuqing** [springfox/springfox#296]
Hi i'm using version 0.8.2 and every api appears twice. I debugged a little and found the following line in class ApiListingReferenceScanner:
```java
for (RequestMappingHandlerMapping requestMappingHandlerMapping : this.requestMappingHandlerMapping) {
```
the dubugger showed that there are two instances of RequestMappingHandlerMapping, and that's why every api showed twice, every instance of RequestMappingHandlerMapping contains all the apis.

Any idea how to fix this problem?

Thanks a lot!

**Comment by StephanBeutel** [comment]
Same problem as I have. JSON contains every API twice.

**Comment by dilipkrish** [comment]
@StephanBeutel which version are you using?

**Comment by smelzer** [comment]
I was having the same problem.  Using 0.9.4.  This happened when I switched from the default SpringSwaggerConfig to a custom config.  I used the example in this page for creating a custom plugin.  In the code sample it shows:

```
@Configuration
@EnableWebMvc
@EnableSwagger
@ComponentScan("com.myapp.controllers")
public class CustomJavaPluginConfig {
```

If you remove the @EnableWebMvc it will stop duplicating lines.  I haven't looked into why this caused the problem.

**Comment by qq291462491** [comment]
+1 good！

**Comment by mjdenham** [comment]
We have started seeing this in one of our projects when we attempted to upgrade from swagger-springmvc 0.9.3 to anything greater - 0.9.4...1.0.2.  However, I discovered that if I downgraded to 0.9.2 the duplicate methods did not appear.

**Comment by JavaHelper** [comment]
I am still facing the same issue although I made all the changes. I see my log shows this twice in console

```Mapped "{[/api/student],methods=[POST],produces=[application/json]}" onto public org.springframework.http.ResponseEntity<java.lang.String> com.test.StudentController.getStudentDetails(com.test.model.StudentDetails,org.springframework.validation.BindingResult,java.lang.String) throws java.lang.Exception
Mapped "{[/api/student],methods=[POST],produces=[application/json]}" onto public org.springframework.http.ResponseEntity<java.lang.String> com.test.StudentController.getStudentDetails(com.test.model.StudentDetails,org.springframework.validation.BindingResult,java.lang.String) throws java.lang.Exception ```
