### ISSUE TITLE
swagger: Failed to load API definition

### ISSUE THREAD

**Issue by tonyyang924** [springfox/springfox#2961]
I attempt to import swagger to my project, but I got an issue "Failed to load API definition"
<img width="521" alt="螢幕快照 2019-04-01 下午10 46 32" src="https://user-images.githubusercontent.com/12247447/55336750-07a9a580-54d0-11e9-974c-c4d3ffcb347b.png">
I was refer to this repo(https://github.com/pgilad/spring-boot-webflux-swagger-starter) and using Swagger version 3.0.0-SNAPSHOT with Spring boot 2.1.3-RELEASE
This repo run as well and it works, but in my case not work, my repo in following:
https://github.com/tonyyang924/SpringBootDemo/tree/import_swagger

**Comment by JakubParzonka** [comment]
Hi, have You resolved that issue?
