### ISSUE TITLE
XForwardPrefixPathAdjuster when having multiple proxys

### ISSUE THREAD

**Issue by meonwax** [springfox/springfox#2962]
Hi i'm currently using v2.9.2 on my services.

I have a microservice environment, where all services are behind a Spring Cloud Gateway API proxy. Additional to this, the whole system is running on a Kubernetes cluster with a Traefik Ingress controller in place.
So Traefik and Spring Cloud Gateway act as reverse proxies until the request eventually reaches the service in the backend. There, Swagger2 is running and provides the API docs.

Unfortunately it generates the field `basePath` wrong, because the header contains a comma separated list of stripped prefixes for every proxy hop: `/api,/my-service`.

The logic in `XForwardPrefixPathAdjuster` only uses the value in this header as a whole, but should in my opinion merge all stripped prefixes again (i.e. just remove commas) to generate the base-path for use in the browser UI.

What do you think? Am i on the right path?

**Comment by xchz** [comment]
i have the same problem

**Comment by idrools** [comment]
i hava the same problem. 
`curl -X GET "http://127.0.0.1:20100/gateway,/foo-service/foos" -H "accept: */*"`

**Comment by JesseeUmasou** [comment]
I also encountered the same problem.swagger's basePath is affected by x-forwarded-prefix in HTTP request header.The spring cloud gateway will automatically add x-forwarded-prefix when forwarding the request.This is the cause of the problem.
So I disabled auto-add x-forwarded-prefix through the `spring.cloud.gateway.x-forwarded.prefix-enabled=false` configuration.Then added the correct `x-forwarded-prefix` through the `- AddRequestHeader=X-Forwarded-Prefix, /api/my-service` configuration.
This solved my problem, but I don't know if there's a better way.

**Comment by dilipkrish** [comment]
Also just FYI with 3.x you can now override existing behavior by using one of [these extensibility mechanisms](http://springfox.github.io/springfox/docs/current/#plugins-available-for-extensibility) (see table 6 and 7)

**Comment by george510257** [comment]
I have the same problem. In my gateway project the source like this.
```java
@Component
@Primary
@Slf4j
public class GatewaySwaggerResourcesProvider implements SwaggerResourcesProvider {

    private static final String API_URI = "/v3/api-docs";
    private static Map<String, SwaggerResource> swaggerResources = new HashMap<>();
    private final RouteDefinitionLocator routeLocator;

    @Value("${spring.cloud.gateway.discovery.locator.route-id-prefix}")
    private String routeIdPrefix;

    @Value("${spring.application.name}")
    private String gatewayName;

    public GatewaySwaggerResourcesProvider(RouteDefinitionLocator routeLocator) {
        this.routeLocator = routeLocator;
        loadSwaggerResources();
    }

    private void loadSwaggerResources() {
        // 从DiscoveryClientRouteDefinitionLocator 中取出routes，构造成swaggerResource
        routeLocator.getRouteDefinitions().subscribe(routeDefinition -> {

            String name = routeDefinition.getId().substring(routeIdPrefix.length());
            String location = routeDefinition.getPredicates().get(0).getArgs().get("pattern").replace("/**", API_URI);

            if (!gatewayName.equalsIgnoreCase(name)) {
                swaggerResources.put(name, swaggerResource(name, location));
            }
        });
    }

    @Override
    public List<SwaggerResource> get() {
        loadSwaggerResources();
        return new ArrayList<>(swaggerResources.values());
    }

    private SwaggerResource swaggerResource(String name, String location) {
        log.info("name: " + name + " url: " + location);
        SwaggerResource swaggerResource = new SwaggerResource();
        swaggerResource.setName(name);
        swaggerResource.setLocation(location);
        swaggerResource.setSwaggerVersion("3.0.3");
        return swaggerResource;
    }
```

the url is right.
![image](https://user-images.githubusercontent.com/4056671/89768683-7f5cfb00-db2e-11ea-85bb-d4f91d8ec08d.png)
but request url is not right.
![image](https://user-images.githubusercontent.com/4056671/89768786-ab787c00-db2e-11ea-90a7-e063da5bbbe4.png)

**Comment by dilipkrish** [comment]
Thanks for the work around @george510257 !

**Comment by george510257** [comment]
@dilipkrish for this basepath is not http://localhost:8080/${serviceid}. is also http://localhost:8080. how can I change it.
