### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by xchopin** [springfox/springfox#2969]
I see some new commits but why is the project not updated anymore? the last maven version is 1 year old  (2.9.2)

**Comment by larsnaesbye** [comment]
There has been 255 commits to the master branch since the 2.9.2 release, so no it's definitely not dead :-)

**Comment by xchopin** [comment]
Yes I got this but what is the point to make that much commits and never release them? 

Is there a particular Milestone to reach for a next version? :)

**Comment by larsnaesbye** [comment]
There are two branches being worked on : model-enhancements and oas-3-support. I presume they are both milestones, and a lot of us are of course eager to try out OAS 3. But it's @dilipkrish and @MaksimOrlov who can answer that question.

Perhaps we can have a 2.9.3 version soon, though ?

**Comment by MaksimOrlov** [comment]
There won't be 2.9.3 release. Branch for model-enhancement should be merged to OAS 3 branch and then released as 3.0 version. Work for model-enhancement finished (could be some optimization commits) and waiting for feedback from @dilipkrish . As I know he is little bit busy for now....
