### ISSUE TITLE
Swagger 2.9.2 generated incorrect request URL on optional request param

### ISSUE THREAD

**Issue by kevxwan** [springfox/springfox#2974]
Hi,

I'm currently using springfoxSwagger2-2.9.2 to generate swagger API doc for our spring boot application written in kotlin. I found swagger is not able to correctly generate request URL when there is an optional request param being annotated on controller with `@org.springframework.web.bind.annotation.RequestParam`

Following is a snippet of rest controller with Get mapping: (Some actual class / attribute name are redacted here)
```kotlin
@RestController
@RequestMapping("/api/v1/someAPI")
@Api(value = "", tags = ["someAPI"])
class SomeApiController @Autowired constructor(
    val someService: SomeService
) {

    @GetMapping("{account_id}/someAPI")
    fun get(
        @PathVariable("account_id") accountId: Long,
        @RequestParam("at", required = false) at: String? // ---> this optional request param is not correctly handled by swagger
    ): ResponseEntity<SomeReturnType> {

        val atTime: OffsetDateTime = if (at != null) {
            OffsetDateTime.parse(at)
        } else {
            OffsetDateTime.now()
        }
        val balance = someService.getRecordAtTime(accountId, atTime)
        return ResponseEntity(balance, HttpStatus.OK)
    }
}
```
When we generated swagger API doc, the URL path is shown as:
<img width="910" alt="Screen Shot 2019-04-16 at 11 23 50 AM" src="https://user-images.githubusercontent.com/48926401/56234494-42681d80-603a-11e9-92fe-4318aa975c35.png">

In the same swagger UI, when we actually "try it out", swagger will build a request URL for above API as, which is unexpected.
<img width="566" alt="Screen Shot 2019-04-16 at 11 25 24 AM" src="https://user-images.githubusercontent.com/48926401/56234600-7ba08d80-603a-11e9-8cd6-cc687520b1e8.png">

The expected URL should be without curve bracket as `/api/v1/accounts/1/someAPI?at=2019-01-01`

Can you please investigate the root cause? thx!

**Comment by ohuseyinoglu** [comment]
Any chance you're calling `enableUrlTemplating(true)` on your Docket?? (As explained in note 21 [here](http://springfox.github.io/springfox/docs/current/#configuration-explained))

**Comment by kevxwan** [comment]
> Any chance you're calling `enableUrlTemplating(true)` on your Docket?? (As explained in note 21 [here](http://springfox.github.io/springfox/docs/current/#configuration-explained))

Thanks @ohuseyinoglu ! this is exactly what has happened, I also found someone has similar problem here: https://stackoverflow.com/questions/33377388/using-requestparam-annotated-method-with-swagger-ui 

Changing to not using this feature solved the problem.
