### ISSUE TITLE
swagger ui is not showing any of rest resources

### ISSUE THREAD

**Issue by praveenambati1233** [springfox/springfox#2979]
I am not able see any of the resource in swagger UI [ http://localhost:8088/swagger-ui.html ],

Followed example - https://github.com/TechPrimers/spring-boot-swagger-example

Tried to see the base pacakage is correct or not , everything looks okay.. also change the code

.apis(RequestHandlerSelectors.any().paths(PathSelectors.any())

Expectation is to display the resources as configured in SwaggerConfig.java

**Comment by duduceolin** [comment]
Can you share more information about the problem? You are just cloning the repo that you mentioned and it still not working?

**Comment by praveenambati1233** [comment]
my spring boot tomact is running on port 8811

![image](https://user-images.githubusercontent.com/49944591/57169904-11079400-6e27-11e9-931b-41bc561e8ade.png)

**Comment by praveenambati1233** [comment]
I have observed one thing in spring boot start up logs , there are no swagger resources downloaded or mapped , that's why I am not able to see the content in swagger-ui.html

![image](https://user-images.githubusercontent.com/49944591/57170662-fab00700-6e2b-11e9-9857-7903465ac9ad.png)

**Comment by duduceolin** [comment]
i just cloned the repo that you've mentioned before and executed. all works fine

if you wanna help, share you files that we may help you

**Comment by praveenambati1233** [comment]
anyways I followed different approach to achieve this by adding spring mvc dependency. Now I can see swagger-ui html is loaded in my spring boot startup o.s.w.s.handler.SimpleUrlHandlerMapping [0;39m [2m:[0;39m Mapped URL path [/swagger-ui.html] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler] – Uday Kiran 2 hours ago   Delete
