### ISSUE TITLE
[Question] How to remove 'host' field from generated docs?

### ISSUE THREAD

**Issue by ashlanderr** [springfox/springfox#2983]
**Springfox version**: 3.0.0-SNAPSHOT.

The response of my `/v2/api-docs` looks like this:

```json
{
  "swagger": "2.0",
  "host": "localhost:8888",
  "basePath": "/"
}
```

But I want to remove the `host` field. This would allow to use "Try it out" from `/swagger-ui.html` relative to the current host. The [swagger reference](https://swagger.io/docs/specification/2-0/api-host-and-base-path/) (Omitting host and scheme) says, that it's allowed. So resulting JSON would look like this:

```json
{
  "swagger": "2.0",
  "basePath": "/"
}
```

I found no way to do this in the springfox configuration. I tried to set `Docket.host(null)`, but in this case, it will use default empty-string value. I'm using SNAPSHOT version, but it wouldn't work in stable versions too.

**Comment by dongze1213** [comment]
+1

**Comment by jackkoppa** [comment]
+1

**Comment by ClaudenirFreitas** [comment]
it is possible to use: 
> -Dspringfox.documentation.swagger.v2.host=

**Comment by dilipkrish** [comment]
@ClaudenirFreitas thanks for that

**Comment by ramiloif** [comment]
This still happening can the issue be reopened ?

**Comment by ramiloif** [comment]
Another option inspired by @ClaudenirFreitas's solution is:
Add the following to `application.yml`
```
springfox:
  documentation:
    swagger:
      v2:
        host:
```
