### ISSUE TITLE
Browser hangs/runs out of memory for large request/response model schema

### ISSUE THREAD

**Issue by vaibhavn** [springfox/springfox#2986]
- [ ] Question. I am working on Enterprise application, APIs are having very large set of  Model schema. I have generated Swagger JSON using SpringFox, API response object has number of fields like CreatedDate, ModifiedDate etc. and these fields again some Object for example Calendar object in this example. Same for other attributes/fields like modifiedBy, Owner etc. those attributes again refer to some XYZObject. These properties again present in nested objects( response object contains some inner object). Ultimately this creates very huge response  'Example Value'/Model( In my case one of the API response object's example value is more ~3 lakhs lines, which is not really useful).
How to solve such issues?
![OpenAPI_OutOfMemory](https://user-images.githubusercontent.com/3889855/57353618-b358ac00-7186-11e9-9980-ac635ffd9f9e.jpg)

**Comment by LukeButters** [comment]
I am having a similar issue. The json created is about 4.5MB in size this caused a OOM and is difficult for clients to consume.

Is it possible to cache the produced json?
Is it possible to break up the doc produced? e.g. I would like all paths that match a pattern to be returned at a different place to all paths that don't match that pattern.

**Comment by LukeButters** [comment]
I was able to make use of the group feature to cut down the size of the api docs json. Which made it easier for clients to consume such as the swagger UI.

I also got control of the swagger controller and ended up compressing and caching the json response in memory and added support for browser caching.
