### ISSUE TITLE
Reactive Web App using Spring Boot 2 - Context Path Issue with Swagger UI

### ISSUE THREAD

**Issue by vsk2017** [springfox/springfox#2989]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by vsk2017** [comment]
I'm using spring boot 2.1.1-RELEASE with swagger 3.0.0-SNAPSHOT. Since I wanted to use reactive web server, used the snapshot version. 

The reactive netty webserver  didn't recognize the context path specified via., server.servlet.context-path in the application.properties file.

Hence i manually configured this. Now the reactive webserver is able to work with the context path. The swagger gui is also loading with the context path correctly.
However when i try to send a POST request via., the swagger GUI, it doesn't recognize the context path.

Any thoughts !!

**Comment by bjconlan-fc** [comment]
No, that seems weird. We're using the swagger 3 'reactive' impl without any real issues. 

The docket allows pretty simple exchanges of reactive types via somthing like 
```
@Configuration
@ConditionalOnMissingClass({
    "org.springframework.boot.test.context.SpringBootTest",
    "org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest"
})
@EnableSwagger2WebFlux
public class OpenApiConfig {

  @Bean
  Docket v1SearchConfiguration(TypeResolver typeResolver) {
    return new Docket(DocumentationType.SWAGGER_2)
        .genericModelSubstitutes(Mono.class)
        .alternateTypeRules(
            new AlternateTypeRule(
                typeResolver.resolve(Flux.class, WildcardType.class),
                typeResolver.resolve(List.class, WildcardType.class)))
        .build()
  }
}
```

the context loading you're seeing sounds quite strange; but we are registering our controllers via annotations (not functionally) maybe this has something to do with it?
