### ISSUE TITLE
Generation of definitions (response classes) of API operations marked a shidden

### ISSUE THREAD

**Issue by SchlauFuchs** [springfox/springfox#2996]
- [ ] What version of the library are you using? 

Version 2.9.2

What kind of issue is this?
 - [ ] Bug report. 

I am supposed to create a limited swagger output, to keep some API undocumented. I have marked the RestController methods with @ApiOperation(hidden=true) but their response object classes are still returned in the list of definitions. I expect that only such definitions would be listed that are used in any public request path.

**Comment by jhoanmanuelms** [comment]
I had a similar situation with a parameter that I wanted to hide and I could solve it by using `@ApiIgnore`
