### ISSUE TITLE
Wrong parameter type determination

### ISSUE THREAD

**Issue by ercee** [springfox/springfox#3000]
![ScreenClip](https://user-images.githubusercontent.com/5452108/58152515-6b04b800-7c75-11e9-88f9-5a413f0715f3.png)

As you see in the picture I have two different method, with one **query** parameter on it.
But swagger shows one of them as body parameter type when I put **apiparam** annotation on it.

![ScreenClip](https://user-images.githubusercontent.com/5452108/58152713-e2d2e280-7c75-11e9-966e-285319203b49.png)

![ScreenClip](https://user-images.githubusercontent.com/5452108/58152761-085fec00-7c76-11e9-96c2-369815d366bb.png)

You can download example project 
https://github.com/ercee/swagger-param-type-issue

Spring boot allows us to use parameters without @RequestParam annotation. But springfox doesn't aware of this.

See:
springfox.documentation.spring.web.readers.parameter.ParameterTypeReader.findParameterType method.

**Comment by yuanbug** [comment]
see #2855
