### ISSUE TITLE
support password format for parameter

### ISSUE THREAD

**Issue by natrem** [springfox/springfox#3002]
- [x] What version of the library are you using? 2.9.2 -  The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

*Feature request*

OpenAPI defines the *password* format for [string](https://swagger.io/docs/specification/data-models/data-types/#string).
I'd expect that the following code
```java
@RestController
public class MyController {

	@GetMapping("/date")
	public Date date(@RequestParam("date") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) Date date) {
		return date;
	}
	
	@GetMapping("/secret")
	public String secret(@RequestParam("secret") @ApiParam(format="password") String secret) {
		return secret;
	}
}
```

would generate the equivalent doc:
```
parameters: [
  {
    name: "secret",
    in: "query",
    description: "secret",
    required: false,
    type: "string",
    allowEmptyValue: false
  }
],
```

The **format** is not present.

First question: do you consider this is the right way to define this use case?

I investigated using a date parameter (see the sample) that generates the following when looking at the `/v2/api-docs` endpoint:
```json
parameters: [
  {
    name: "date",
    in: "query",
    description: "date",
    required: true,
    type: "string",
    format: "date"
  }
],
```
I narrowed it to class `ParameterDataTypeReader` that creates a ModelRef "date" for the Date parameter. For "date" this is resolved by `springfox.documentation.schema.Types.typeNameLookup` called in `ParameterDataTypeReader`

In the case of _date_ the `ParameterMapper` called from `springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapOperation`  will generate default value from the `Properties.typeFactory` which has the expected format (class `DateProperty`).

My proposal is to:
- create a new `PasswordProperty` class registered in `Properties` with name `password`
- create a ModelRef with name "password" during the ParameterPlugin phase.
  I think we might create a new `ParameterBuilderPlugin`  that would detect parameter of type `String` with format "password".

Do you think this would be viable?
Do you see a better solution or a different approach (maybe to treat all specific formats) ?

## Reproduce
Project is [here](https://github.com/natrem/sample-swagger-password)
swagger doc available on http://localhost:8080/v2/api-docs

**Comment by DeaneKane** [comment]
Yeah currently the format="password" has no effect on masking my input . Are there any plans to implement the "password" format property?

**Comment by virendrachaudhary06** [comment]
I can see it has been marked with wontfix label. Do we have any workaround to mask password in swagger UI?
