### ISSUE TITLE
Spring Swagger change url for basic auth

### ISSUE THREAD

**Issue by MrMedTech** [springfox/springfox#3004]
Hi, 
I want to know if it is possible to configure an URL for Swagger ui do authenticate with basic auth.
Thing is, I have two Microservices. 
One Service is the auth service where all de basic auth stuff gets done.
The other one is my API-Service which I want to protect with spring security.
Atm I configured the scenario that I get an access denied when i want to try the endpoints with swagger ui before authenticating.
To authenticate I want to link to my auth service. 
Right now I got the icon of a safety lock on my top right corner and when I click on it I can enter my credentials. 

Config:
```
	@Bean
	public Docket createRestApi() {
		
		//Define security form for basic auth
		List<SecurityScheme> m_securitySchemes = new ArrayList<>();
		m_securitySchemes.add(new BasicAuth("BasicAuth"));
		
		
		
		return new Docket(DocumentationType.SWAGGER_2).groupName("userinterface-api").ignoredParameterTypes(ModelMap.class,RedirectAttributes.class,HttpServletRequest.class,HttpSession.class,Model.class,WebRequest.class)
				.apiInfo(apiInfo()).select().paths(PathSelectors.ant("/users/mobile/**")).build().securitySchemes(m_securitySchemes);
	}
```

So the exact question is: Can I configure an Link to my auth service when I entered my credentials in this basic auth popup and I want to authorize so that I can use map API endpoints?

**Comment by jhonatasfender** [comment]
https://stackoverflow.com/questions/59941082/swagger-springfox-basicauth-how-to-change-the-authentication-url-and-add-the-c
