### ISSUE TITLE
[Question] Using current date as example value for LocalDate field

### ISSUE THREAD

**Issue by lauriharpf** [springfox/springfox#3010]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? **2.9.2** Is it the latest version? **Yes**

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. **Unsure. Behavior appears inconsistent between LocalDate and LocalDateTime fields.**

 - [ ] Feature Request. 

## Question

How can I set the example for a LocalDate field to be the current date?

Some examples of things I've attempted:

### 1) LocalDate field, no example value

```java
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.NotNull;
import java.time.LocalDate;

public class Request {
    @ApiModelProperty(notes = "Reservation date as YYYY-MM-DD", required = true)
    @NotNull
    public LocalDate date;
}
```

This shows the following example in swagger-ui.html:

```json
{
  "date": "string"
}
```

### 2) LocalDate field, example value
```java
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.NotNull;
import java.time.LocalDate;

public class Request {
    @ApiModelProperty(example = "2019-05-29", notes = "Reservation date as YYYY-MM-DD", required = true)
    @NotNull
    public LocalDate date;
}
```

This shows the following example in swagger-ui.html:

```json
{
  "date": "2019-05-29"
}
```

Format-wise this is exactly what I'm looking for, but will still display the same value tomorrow (instead of "2019-05-30").

### 3) LocalDateTime field, no example value

```java
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;

public class Request {
    @ApiModelProperty(notes = "Reservation date as YYYY-MM-DD", required = true)
    @NotNull
    public LocalDateTime date;
}
```

This shows the following example in swagger-ui.html:

```json
{
  "date": "2019-05-29T06:28:31.382Z"
}
```

Again otherwise exactly what I'm looking for, but I don't want the time part T06:28:31.382Z. I have also asked this question on Stackoverflow as [Current date as example in Springfox & Swagger-UI](https://stackoverflow.com/questions/56354400/current-date-as-example-in-springfox-swagger-ui).

**Comment by JenniferStamm** [comment]
I have the same question. Have you figured out a solution yet?

**Comment by patoperpetua** [comment]
In version 2.9.2 this is still happening.
