### ISSUE TITLE
Swagger UI use application/json rather than application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by ruiruige** [springfox/springfox#3023]
What version of the library are you using? Is it the latest version? 

       <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.9.2</version>
        </dependency>

What kind of issue is this?
Question or a Bug?
 

Hi :
After I updated both `springfox-swagger2` and `springfox-swagger-ui` from `2.2.2`to `2.9.2`,
I found swagger-ui started to use the "wrong" content-type.

Here is my controller:

    @RestController
    public class TestSwaggerController {

        @ApiOperation(value = "test for swagger", consumes = "application/x-www-form-urlencoded")
        @ApiImplicitParams({
            @ApiImplicitParam(name = "paramOne", value = "paramOne", required = true, paramType = "form",
                dataType = "String"),
            @ApiImplicitParam(name = "paramTwo", value = "paramTwo", required = true, paramType = "form",
                dataType = "String"),

        })
        @PostMapping(value = "/openapi/testSwagger")
        public ApiResult scan(@RequestParam String paramOne
            , @RequestParam String paramTwo) {
            ApiResult apiResult = new ApiResult();
            return apiResult;
        }
    }

But the swagger-ui still send url using: `application/json`, while I expect it to be `application/x-www-form-urlencoded`.
I set `consumes = "application/x-www-form-urlencoded"` in `@ApiOperation` annotation, but it did not work:

![image](https://user-images.githubusercontent.com/8370100/59339873-8b390b80-8d37-11e9-9f65-b6f34fa7fe96.png)

Could anybody help?

**Comment by XhstormR** [comment]
You can try this:
```
@PostMapping("/login", consumes = [MediaType.APPLICATION_FORM_URLENCODED_VALUE])
```

**Comment by GabrielaRaluca** [comment]
I have the exact same problem, and adding "consumes" on the endpoint didnt help..

**Comment by ranmc** [comment]
@XhstormR 成功解决，鸣谢

**Comment by jeetds1994** [comment]
I know this is closed but try removing `@RequestBody`
