### ISSUE TITLE
Has this project died?

### ISSUE THREAD

**Issue by wangxi761** [springfox/springfox#3028]
Has this project died?

**Comment by jkeruzec** [comment]
I don't think so : 

![image](https://user-images.githubusercontent.com/3499632/60334256-5bc30980-999b-11e9-8e04-a56eddf4b429.png)

https://github.com/springfox/springfox/milestone/44

**Comment by dulong** [comment]
This project is not very active, and the last commit is pushed 2 months ago. Will the project continue to develop？

**Comment by rgoers** [comment]
You could always try contributing patches!

**Comment by hc-codersatlas** [comment]
@rgoers not sure how that helps? Lots of open PRs already.
