### ISSUE TITLE
@EnableSwagger2WebMvc has no effect w/o springfox-spring-webmvc

### ISSUE THREAD

**Issue by benjvoigt** [springfox/springfox#3045]
I tried to update our current springfox version to the latest 3.0.0-SNAPSHOT but that didn't work out of the box. The reason for that is that we're not using `springfox-data-rest` hence the newly introduced dependency `springfox-spring-webmvc` was not added to our dependency tree. This renders the `@EnableSwagger2WebMvc` annotation (provided by `springfox-swagger2`) useless since the annotation imports `Swagger2DocumentationWebMvcConfiguration` which relies on `SpringfoxWebMvcConfiguration` which is part of `springfox-spring-webmvc`.

Without a working `@EnableSwagger2WebMvc` the endpoints e.g. `/v2/api-docs` are not initialized.

I solved this issue by adding `io.springfox:springfox-spring-webmvc:3.0.0-SNAPSHOT` to my dependencies but this should be transitively provided by `springfox-swagger2` imho - or the `@EnableSwagger2WebMvc` annotation should be moved to `springfox-spring-webmvc`.

**Comment by ramnath30** [comment]
If 3.0.0-SNAPSHOT does not work, use the latest version from here: https://mvnrepository.com/artifact/io.springfox/springfox-spring-web

**Comment by dilipkrish** [comment]
@benjvoigt Going forward you shouldn't have to rely on the `@Enable... ` annotations. Just remove them and only take a dependency on `springfox-boot-starter` project. Everything should just work
