### ISSUE TITLE
Detect params from runtime

### ISSUE THREAD

**Issue by Shocter** [springfox/springfox#3048]
Hi,
I'm using lib called [Specification Argument Resolved](https://github.com/tkaczmarzyk/specification-arg-resolver) with Spring Boot, Spring Web, Spring Data etc. Is it possible for swagger to detect params defined like this:

```
@And({
        @Spec(path = "title", params = {"title"}, spec = LikeIgnoreCase.class),
        @Spec(path = "rented", params = {"isRented", "rented"}, spec = Equal.class),
        @Spec(path = "author.id", params = {"authorId"}, spec = Equal.class),
        @Spec(path = "author.firstName", params = {"firstName"}, spec = LikeIgnoreCase.class),
        @Spec(path = "author.lastName", params = {"lastName"}, spec = LikeIgnoreCase.class)
})
interface BookSpecification extends Specification<Book> {
}
```

```
@RestController
@CrossOrigin
@RequestMapping("/api/books")
public class BookController extends AbstractController<Book, BookDto> {

    private final BookService bookService;

    public BookController(BookService bookService) {
        super(bookService);
        this.bookService = bookService;
    }

    @GetMapping
    public ResponseEntity<Page<BookDto>> getAll(BookSpecification authorSpecification, Pageable pageable) {
        return ResponseEntity.ok(bookService.getAll(authorSpecification, pageable));
    }
```

Swagger detects only params used in paging:
![image](https://user-images.githubusercontent.com/23433076/61292631-0c217200-a7d2-11e9-867d-4f41613ae91f.png)

The problem is that this lib is generating specifications in run time, whereas swagger is working in compile time. Any ideas guys?

**Comment by dilipkrish** [comment]
It is definitely possible. You'd have to write your [own plugins for it](http://springfox.github.io/springfox/docs/current/#plugins)

**Comment by Shocter** [comment]
@dilipkrish that's true. My solution to this problem was to use [ApiImplicitParam](https://github.com/swagger-api/swagger-core/wiki/annotations#apiimplicitparam-apiimplicitparams) annotation in controllers. Maybe it's not clean as your but it done the job.
