### ISSUE TITLE
When are we expecting an official release of 3.0.0?

### ISSUE THREAD

**Issue by ilgrosso** [springfox/springfox#3054]

**Comment by msogrin** [comment]
@dilipkrish can we at least get a beta/rc version tagged on the current 3.x code and publish it to Maven Central/JCenter?  That will at least help people that are satisfied with the current snapshot but want predictable builds.

**Comment by springdoc** [comment]
Hi guys,

We have released a new version of springdoc-openapi library:
It supports OpenAPI 3 with the spring-boot.

More details are available on:
- http://springdoc.org

**Comment by demesne** [comment]
@springdoc tried it .. very simplistic approach with a lot of missing functionality. 
At the very least you need -
defaults to / as root context without reading server.servlet.context-path property.
only annotation support - means versions cannot be injected dynamically

**Comment by ilgrosso** [comment]
...and no Spring Webflux support either

**Comment by hc-codersatlas** [comment]
Will there be a version with OpenAPI 3.0 support?
