### ISSUE TITLE
Custom Gson Adapter not working with Swagger2

### ISSUE THREAD

**Issue by sayandg14** [springfox/springfox#3071]
I am trying to implement Swagger2 into my project . I have added custom Gson converters by extending WebMVCConfigurationSupport and overriding method : configureMessageConverters . I am registering the DTO s through RunTimeTypeAdapterFactory which will be sent/consumed through Rest . However while implementing Swagger I have added swagger-ui and swagger2 version as 2.9.2 in maven. Below given the Swagger configuration

@EnableSwagger2
@Configuration
public class SwaggerConfig extends WebMvcConfigurationSupport {

    public Docket api(){

        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors
                        .basePackage("com.example.demo"))
                .paths(regex("/api.*"))
                .build();

    }

    @Override
    protected void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}
However by hitting http://locahost:8080/swagger-ui.html it is showing : Unable to render this definition . Please indicate a valid Swagger or OpenAPI version field . Supported version fields are swagger:"2.0" or openAPI:"3.0.0" . When I hit : http://locahost:8080/v2/api-docs , in STS console I can see below error message : Unable to find specification details for group default

**Comment by FLXT-Qi** [comment]
same problem

**Comment by xjtushilei** [comment]
same problem

**Comment by xjtushilei** [comment]
@sayandg14   Have you fixed it

**Comment by sayandg14** [comment]
No , I could not fix it
