### ISSUE TITLE
Does version 3.0.0-SNAPSOT supports discriminator and subtypes for DTO`s objects?

### ISSUE THREAD

**Issue by iseniori** [springfox/springfox#3074]
Does version 3.0.0-SNAPSOT supports discriminator and subtypes for DTO`s objects?
I need smth like that:
@ApiModel(value = "ScreenTemplateBase", discriminator = "pageType", subTypes = {ScreenTemplateWithTenderButtonsDTO.class, GuestServiceScreenTemplateDTO.class, PackageSaleScreenTemplateDTO.class})
and have ability to choose concrete type of DTO in swagger ui example.

**Comment by dilipkrish** [comment]
Not yet @iseniori that plan is to support open api in full

**Comment by iseniori** [comment]
@dilipkrish when you plan to add this support?

**Comment by dilipkrish** [comment]
See #3070

**Comment by Darkvater** [comment]
Can I ask what the point is of the "subtypes" property in ApiModel if it is not used at all? I have tried to expose subtypes both in 2.9.2 and 3.0.0 but it doesn't work and nothing gets exposed even though #2407 seems to say it is resolved in 3.0.0.
What does work is defining all types in JsonSubTypes, but then "subTypes" is obsolete and could just as well be left off.
