### ISSUE TITLE
How to add Springfox/Swagger annotations in an existing Java source code.

### ISSUE THREAD

**Issue by vaibhavn** [springfox/springfox#3081]
- [ ] SpringFox 2.9.2

What kind of issue is this?

 - [ ] Question. I have an existing Java source files( without swagger annotations). I would like to add swagger annotations( 'ApiOperation', 'ApiParam' etc. ) in these Java source code files.
Is it possible to read Java docs through reflection/Doclet and update an existing plain Java files with swagger annotations to apply SpringFox library for further process?
Is there any available library or solution to my requirement?

**Comment by dilipkrish** [comment]
@vaibhavn Springfox is designed to work without any additional annotations. I would recommend trying that first.

**Comment by vaibhavn** [comment]
I might have not clearly mentioned in my question, my bad !
My Java code is not a spring project code.
How can I generate swagger JSON using Springfox without having spring annotations like '@RestController', I believe system is not going to scan Java source code unless it is annotated with Controller/RestController etc.
Currently I am adding these annotations manually to generate swagger JSONs.

**Comment by vaibhavn** [comment]
@dilipkrish did you get my concern?
Please let me know if you need more information.

**Comment by vaibhavn** [comment]
I am planning to use 'JavaParser' ( [https://javaparser.org/](https://javaparser.org/) )
