### ISSUE TITLE
Unable to use CustomAwsExtensionsReader as OperationContext not have getHandler

### ISSUE THREAD

**Issue by kadimulam** [springfox/springfox#3083]
As the current version of springfox does not have getHandlerMethod() in OperationContext, we are unable to utilize CustomAwsExtensionsReader. Could you please let me know if there is any alternative to get the method with spring fox?

**Comment by dilipkrish** [comment]
What is CustomAwsExtensionReader?

**Comment by brothertao** [comment]
see [http://springfox.github.io/springfox/docs/current/#steps-to-create-a-plugin](url)
