### ISSUE TITLE
Spring 2.2.0.M5 SpringDataRestSchemaExtensions

### ISSUE THREAD

**Issue by asifrashid** [springfox/springfox#3084]
I am adding Swagger to my project developed using Spring Boot 2.2.0.M5, Spring Hateaos () and Spring Data Rest. Not doing any special setting yet, just added two annotations on my application class. 

``
@EnableSwagger2
@Import(SpringDataRestConfiguration.class)*
``
When I try to run my application I am getting following error message,

``
Caused by: java.lang.IllegalStateException: Failed to introspect Class [springfox.documentation.spring.data.rest.schema.SpringDataRestSchemaExtensions] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
``

I have searched everywhere and couldn't find any solution for it. Any suggestion is appreciated.

Thanks!

**Comment by dilipkrish** [comment]
What version of java are you using

**Comment by asifrashid** [comment]
I am using JDK 1.8.0.201.

**Comment by gigecogary** [comment]
same problem, any fix?

**Comment by judsona** [comment]
This is caused because Springfox Data Rest relies on hateoas 0.24.0.RELEASE and the latest version of Spring Data Rest Core relies on hateoas 1.0.1.RELEASE

**Comment by vlad2** [comment]
Springfox Data Rest 3.0.0 (which has support for Spring Data Rest  of SpringBoot 2) relies on the hateoas 1.0.2-RELEASE, and it works.

**Comment by j3ernhard** [comment]
Springfox Swagger 3.0.0 works with SpringBoot 2.2.x which includes hateoes 1.0.x.

**Comment by dilipkrish** [comment]
Thanks for reporting back @j3ernhard. Closing this issue
