### ISSUE TITLE
Is there any way to disable or change the order of XmlModelPlugin?

### ISSUE THREAD

**Issue by tndavidson** [springfox/springfox#3085]
Because of the way Swagger UI is rendering the example xml (Class names, instead of property names), I want to eliminate the `xml.name` property from the schema completely. I tried writing a custom `ModelBuilderPlugin` but the `XmlModelPlugin` overwrites the `xml` property entirely.

I have tried playing around with `@Order`, but `XmlModelPlugin` always seems to show up as the last entry in the modelEnrichers plugin registry.

I have created a temporary solution using AOP with advice around the apply() method, but it is ugly.

Is there a simple way to disable this plugin or change the order of it in relation to user-supplied plugins?

**Comment by dilipkrish** [comment]
Can you provide an example of this maybe created an endpoint in [bugs controller ](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java)

**Comment by tndavidson** [comment]
@dilipkrish if I get some time, I will provide a sample project - I was able to skirt around the issue in the meantime by implementing a BeanPostProcessor that replaced the XmlModelPlugin with my own plugin component
