### ISSUE TITLE
cannot pull springfox-swagger-ui.jar with gradle (version 2.9.2 )

### ISSUE THREAD

**Issue by ssochi** [springfox/springfox#3086]
I use gradle
`// https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui
    compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.9.2`
but can't find springfox-swagger-ui.jar
then i use 
`// https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui
    compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.7.0'`
i got springfox-swagger-ui.jar

**Comment by dilipkrish** [comment]
Its certainly there @ https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui
