### ISSUE TITLE
Cannot get 0.8.3 (or 0.8.4-SNAPSHOT) to work (with gradle)

### ISSUE THREAD

**Issue by jmcazaux** [springfox/springfox#309]
Hi there,
I am having no luck making swagger-springmvc to work on our (baby) Spring project (using gradle).

I copied the code from the example, and "mixed" it with the example [here](https://github.com/adrianbk/swagger-springmvc-demo/tree/swagger-springmvc--0.8.2-SNAPSHOT-swagger-ui--oauth) (as read on ticket #305) but I am having no luck and I spent the last day pulling my hair on it...

When using 0.8.3, I add a few of missing classes/methods, I eventually got it to compeil when commenting out  the following lines in method swaggerApiResourceListing()

``` java
        // Set the model provider, uses the default autowired model provider.
        swaggerApiResourceListing.setModelProvider(modelProvider);

        // Global authorization - see the swagger documentation
        swaggerApiResourceListing.setAuthorizationTypes(authorizationTypes());

        // Sets up an auth context - i.e. which controller request paths to apply global auth to
        swaggerApiResourceListing.setAuthorizationContext(authorizationContext());
```

The issue is that it does not fly when launching Tomcat.
I have

```
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[/carsys-api]]
.../..
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'swaggerConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.mangofactory.swagger.configuration.SpringSwaggerConfig biz.carsystems.api.setup.SwaggerConfig.springSwaggerConfig; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.mangofactory.swagger.configuration.SpringSwaggerConfig] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

I am not sure where/how I could get those beans created (we do not use any XML).

And when trying ti use 0.8.4-SNAPSHOT (to be as close as possible from the example) Gradle seems to be unable download the package...

Any help will be much appreciated... and sorry for the so long question.

JM

**Comment by ratnesh93** [comment]
please someone which is the right dependencies of @EnableSwagger , i added : 	                compile "org.ajar:swagger-spring-mvc-ui:0.4"
	compile('com.wordnik:swagger-core_2.9.1:1.1-SNAPSHOT.120119') 
	compile('com.github.pjagielski.spring-boot-swagger:spring-boot-swagger:0.1')
	compile(group: 'com.mangofactory', name: 'swagger-springmvc', version: swagger_springmvc_version) {
        exclude(module: 'jackson-module-scala_2.10')
        exclude(module: 'scalap')
        exclude(module: 'scala-compiler')
    }

The @EnableSwagger error is gone, but my swagger ui is not coming
