### ISSUE TITLE
RangeError: Maximum call stack size exceeded - Swagger 4.0.1 - ASP.Net Core 2.1

### ISSUE THREAD

**Issue by rattada** [springfox/springfox#3093]
i am using 4.01 version for asp.net core 

this is the error i am getting after implementaion of api versioning
system.js:464 
RangeError: Maximum call stack size exceeded
    at kt (immutable.js:2494)
    at immutable.js:2408
    at pt.Ue.withMutations (immutable.js:1353)
    at immutable.js:2405
    at pt.set (immutable.js:2096)
    at jt (immutable.js:2780)
    at Pt.set (immutable.js:2686)
    at immutable.js:2651
    at immutable.js:3016
    at immutable.js:2699

![image](https://user-images.githubusercontent.com/2851831/63506277-d79c8680-c4f2-11e9-98de-486e474c05b2.png)

![image](https://user-images.githubusercontent.com/2851831/63506493-44b01c00-c4f3-11e9-8c2f-c9181e901bc2.png)

This issue is still exist, please response any one
Thannks in Advance

**Comment by rnietoe** [comment]
hi @rattada , i reproduced the same issue. still looking for the solution. i have also checked a model is displayed as empty, without properties...
