### ISSUE TITLE
swagger-ui.html : Parameter content type didn't show

### ISSUE THREAD

**Issue by shiguang0122** [springfox/springfox#3101]
version: 2.7.0
spring-boot: 2.0.4
spring: 5.0.8

Initialization:

`@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket createRestApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.jmgc"))
                .paths(PathSelectors.any())
                .build()
                //.globalOperationParameters(setHeaderToken());
                .consumes(new HashSet<String>(){
                    {add("application/x-www-form-urlencoded");add("application/json");}
                });
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("")
                .description("http://127.0.0.1")
                .version("4.0")
                .build();
    }
}`

api_1:
`   @RequestMapping(value = "listParam", method = RequestMethod.POST)
    @ApiOperation(value = "demo1", consumes="application/x-www-form-urlencoded")
    public void insertDemo(@RequestParam("beds") @Valid BedsQueryParameter beds){
        this.setData("beds", beds.toString());
        this.success();
    }`

api_2:
`    @PostMapping("jsonParam")
    @ApiOperation(value = "demo2")
    public void testJson(@RequestBody @Valid BedsQueryParameter beds){
        this.setData("beds", beds.toString());
        this.success();
    }`

results:
1. swagger-ui.html , Parameter content type, default is "application/json"
2. swagger-ui.html , Parameter content type, is "<select><option>application/json<option><option>application/x-www-form-urlencoded</option></select>"

can i choose "Parameter content type" option every  request ?
or  when      the "Parameter content type" hide ,  and when it show ?
I'm confused,  because  i want choose "application/x-www-form-urlencoded", but   the "Parameter content type" is hided and value was "application/json" ...

Sorry. I'm not good at English.

**Comment by yus7391** [comment]
I had the same problem ，did you fixed it?
