### ISSUE TITLE
Swagger UI is not loading after adding @PathVariable Resource to Controller

### ISSUE THREAD

**Issue by ppb1984** [springfox/springfox#3102]
I have Spring Boot and Swagger Integration in my application. I have added one more resource in my existing controller after that, swagger ui stops loading

`http://localhost:8080/swagger-ui.html` page is not loading and giving `HTTP ERROR 406` Error

If I type `http://localhost:8080/api-docs` then this one is returning newly added resource response json.

One more thing if I remove @PathVariable from below API then swgger-ui is loading successfully. 

Added below resource in existing controller

    @ApiOperation(value = "Get Employee Information")
    @GetMapping("/{employeeId}")
    public EmployeeResponse employeeInfo(
        @PathVariable("employeeId") String employeeId,
        @RequestHeader(value = "x-client-id", required = false) String xclientId){
        return service.getEmployeeInfo();
    }

Below library versions I am using - 

    classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.5.10.RELEASE'    
    compile 'io.springfox:springfox-swagger-ui:2.6.1'
    compile 'io.springfox:springfox-swagger2:2.6.1'

When I try to load swagger-ui.html, getting 

    Client : [UnknownClient] - An exception was thrown by a controller Could not find  acceptable representation:
    org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find  acceptable representation

I think newly added resource path is conflicting with swagger-ui.html root path. I cannot change the resource path  and also swagger ui path as api contract is already decided .

**Comment by jpwilliams000** [comment]
Yes, your controller is defining a PathVariable /{employeeId} which is conflicting with the /swagger-ui.html.

So just change @GetMapping("/{employeeId}") -> @GetMapping("/**employee**/{employeeId}")

**Comment by ppb1984** [comment]
Hi @jpwilliams000 , I cannot change the newly added resource path because API contract is already fix and send to client also. Is there any other way?

**Comment by dilipkrish** [comment]
This should be fixed shortly in the 3.0 release, swagger-ui is its own self contained path under `/<context-path>/swagger-ui/*`
