### ISSUE TITLE
Infer wrong base URL behind gateway (docker)

### ISSUE THREAD

**Issue by davinwang** [springfox/springfox#3104]
- [X] What version of the library are you using?
2.9.2
What kind of issue is this?
 - [X] Bug report.
----
Hi, reproduce steps are as following:

- Firstly, I'm using following commands to start springfox on server xx.xx.xx.xx .

    `sudo docker run -d -p 28080:8080 swagger-image`
    Swagger-ui documents can be accessed via [http://xx.xx.xx.xx:28080/swagger-ui.html](http://xx.xx.xx.xx:28080/swagger-ui.html) directly. And the base URL is detected automatically as http://xx.xx.xx.xx:28080/.    

- Then, I put a gateway [kong](konghq.com) before the springfox on server yy.yy.yy.yy

    `sudo docker run -d -p 31531:8000 kong`
    Swagger-ui documents can be accessed via [http://yy.yy.yy.yy:31531/swagger-ui.html](http://yy.yy.yy.yy:31531/swagger-ui.html). The apidocs is detected as [http://yy.yy.yy.yy:31531/v2/api-docs](http://yy.yy.yy.yy:31531/v2/api-docs) correctly. However, the base URL is **not on same port** as api-docs, it is [http://yy.yy.yy.yy:8000](http://yy.yy.yy.yy:8000).
     I also tried to change port 8000 to 9000 and the base URL will move to 9000. So 8000 is not some magic number as default value.
<img width="202" alt="1" src="https://user-images.githubusercontent.com/5567847/63820593-663e5700-c97c-11e9-810f-3421b8fd2db1.png">

- Then I tried to proxy the request to [mockbin.org](http://mockbin.org/request) for analysis.

    but I didn't find any http header _(such as X-Forward)_ containing 8000 or 9000. So I wonder how springfox figure out the port. Here is the response from mockbin.org.
    `{
  "startedDateTime": "2019-08-28T03:18:04.744Z",
  "clientIPAddress": "10.42.3.0",
  "method": "GET",
  "url": "http://mockbin.org/request",
  "httpVersion": "HTTP/1.1",
  "cookies": {
    "ajs_user_id": "null",
    "ajs_group_id": "null",
    "ajs_anonymous_id": "\"ebac3e1f-32b1-477b-aeed-938a070b5fd2\"",
    "_ga": "GA1.2.1512146895.1558492372",
    "CSRF": "6dadd5580e",
    "_gid": "GA1.2.1322947759.1566954367"
  },
  "headers": {
    "host": "mockbin.org",
    "connection": "close",
    "x-forwarded-for": "10.42.3.0, 10.1.192.233, **.**.**.**",
    "x-forwarded-proto": "http",
    "x-forwarded-host": "mockbin.org",
    "x-forwarded-port": "80",
    "x-real-ip": "**.**.**.**",
    "kong-cloud-request-id": "5d82f4f8f3b381016f17dac867ce533c",
    "kong-client-id": "mockbin",
    "cache-control": "max-age=0",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
    "accept-encoding": "gzip, deflate",
    "accept-language": "zh-CN,zh;q=0.9",
    "cookie": "ajs_user_id=null; ajs_group_id=null; ajs_anonymous_id=%22ebac3e1f-32b1-477b-aeed-938a070b5fd2%22; _ga=GA1.2.1512146895.1558492372; CSRF=6dadd5580e; _gid=GA1.2.1322947759.1566954367",
    "if-none-match": "W/\"40b7-0QU5RyOQXaFTQ1tCYgU0BwvO0j8\"",
    "x-consumer-id": "213d622a-5d9e-45b9-bed5-9d0761c76bba",
    "x-consumer-custom-id": "anonymous",
    "x-consumer-username": "anonymous",
    "x-anonymous-consumer": "true",
    "x-consumer-groups": "anonymous",
    "x-request-id": "6744a371-a687-48a1-bb5d-fa779b8946f1",
    "via": "1.1 vegur",
    "connect-time": "0",
    "x-request-start": "1566962284743",
    "total-route-time": "0"
  },
  "queryString": {},
  "postData": {
    "mimeType": "application/octet-stream",
    "text": "",
    "params": []
  },
  "headersSize": 1259,
  "bodySize": 0
}`

    Is there a solution to this? Or how can I set the base URL on the fly instead of auto detect? Thanks~

**Comment by mantissa-t** [comment]
same issue,when i use nginx proxy
![IMG20190903_012132](https://user-images.githubusercontent.com/8416876/64128488-652c8000-cde9-11e9-8478-5a8fe08c68db.png)

**Comment by minhnguyenvan95** [comment]
up

**Comment by Velemis** [comment]
Up
Still actual on io.springfox:springfox-boot-starter:3.0.0

**Comment by albertmatyi** [comment]
I have the same issue with path detection.

Definition recognized; inferred base URL ignores path

```
# service runs on
http://servicehost/api/v1

# proxy proxies
http://proxy/services/servicehost/(.*)
to 
http://servicehost/$1

# swagger-ui/index.html  shows
http://proxy/services/serviceshost/v3/api-docs
# CORRECTLY

# swagger-ui/index.html  shows inferred basepath as 
http://servicehost/
# WRONG
```

![image](https://user-images.githubusercontent.com/1370078/169287414-999447a2-b166-4671-a09c-3b6a7827f0ed.png)

Using ` io.springfox:springfox-boot-starter:3.0.0`
