### ISSUE TITLE
spring integration is very slow for classpath scanning

### ISSUE THREAD

**Issue by Beennnn** [springfox/springfox#3109]
I use spring integration in a big project and **startup time take several minutes scanning classes**, more than all the spring initialization for the whole project.

**I found the origin of the slow processing**.
It is located in SpringRestDocsOperationBuilderPlugin.apply() method.
See here : https://github.com/springfox/springfox/blob/master/springfox-spring-integration/src/main/java/springfox/documentation/spring/web/plugins/SpringRestDocsOperationBuilderPlugin.java#L64

In fact, the plugin read the context each time the apply method is called, that means for each RequestMappingContext found in ApiListingScanner.scan().

Then it scans for all file matching this pattern : "classpath*:contextName*/http-response.springfox"

**For my project, there is no class matching this pattern !** So it spends several minutes for... nothing !

I suggest several approaches :
- killing approach: removing this scan (what is it for ?)
- testing once if there is at least one resource matching "classpath*:**/http-response.springfox" and save it to cache [RECOMMENDED] and skipping all tests if none is found
- else the result for **the call to resourceResolver.getResources() could be save in local cache**.

Do you agree ?
Can someone help me for a fix for this issue ?

Thanks,

Ben.

**Comment by sh4wn** [comment]
anything new?

**Comment by sh4wn** [comment]
anything new?
