### ISSUE TITLE
One swagger-ui.html for several spring projects

### ISSUE THREAD

**Issue by BigGitWorld** [springfox/springfox#3115]
Swagger-ui is working fine in my own projects.
Every spring project must include swagger in itself to be able to use it.
But I want to have a separated swagger-ui spring project, so that it can show (use) docs of restful endpoints in other spring projects that are in same domain but different subdomains / ports.
How do I have to do this scenario?

**Comment by siggz0r** [comment]
I haven't done this myself but have you looked at [Netflix Eureka](https://github.com/Netflix/eureka/wiki) project? [DZone](https://dzone.com/articles/centralized-documentation-in-microservice-spring-b) seems to have a nice tutorial explaining how it can be implemented.
