### ISSUE TITLE
parameter  with @ModelAttribute hidden has no effect

### ISSUE THREAD

**Issue by thomas1001-cyber** [springfox/springfox#3116]
@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 1000)
public class ApiParameterBuilderPlugin implements ParameterBuilderPlugin {

    @Override
    public void apply(@ApiIgnore ParameterContext parameterContext) {
        // 解析modelAttribute参数
        Optional<ModelAttribute> modelAttributeOptional = methodParameter.findAnnotation(ModelAttribute.class);
        if(modelAttributeOptional.isPresent()){
            parameterContext
                    .parameterBuilder()
                    .hidden(true);
        }
    }

    @Override
    public boolean supports(DocumentationType delimiter) {
        return true;
    }
}

**Comment by thomas1001-cyber** [comment]
I found another solution, that is to add ModelAttribute.class to the Docket; It works,But parameterContext.parameterBuilder().hidden(true) should also work, isn't it? It is a bug or not support

**Comment by jhoanmanuelms** [comment]
Thanks, this worked for me
