### ISSUE TITLE
Unexpected double chevron characters in JSON  - Possible bug ?

### ISSUE THREAD

**Issue by codesqueak** [springfox/springfox#3117]
I was interested in using Swagger in conjunction with Spring Boot & Flux

I started from the example project [here](https://github.com/pgilad/spring-boot-webflux-swagger-starter): , and added an additional end point to the controller.

```java
    @PostMapping(path = "/capture", produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
    public Mono<ResponseEntity<CaptureDto>> createCapture(@RequestBody CaptureDto captureDto) {
        return Mono.just(ResponseEntity.ok(captureDto));
    }
```

The CaptureDto class is trivial.

When I loaded at the JSON generated via the UI, I saw that double chevron characters had been used, e.g. ```Mono«ResponseEntity«CaptureDto»»``` instead of ```Mono<ResponseEntity<CaptureDto>>"``` that I was expecting

```json
   "Mono«ResponseEntity«CaptureDto»»": {
      "type": "object",
      "title": "Mono«ResponseEntity«CaptureDto»»"
    },
    "Mono«string»": {
      "type": "object",
      "title": "Mono«string»"
    }
```

If I feed this into the swagger-codegen tool, this then causes invalid Java to be generated (The double chevron characters are preserved)

Is this an issue ?, did I misunderstand something ?

Any help appreciated. Thanks.

[swagger.zip](https://github.com/springfox/springfox/files/3596714/swagger.zip)

**Comment by sblommers** [comment]
Please use  .forCodeGeneration(true) on your Docket
