### ISSUE TITLE
problem with resolve same class names in different packages

### ISSUE THREAD

**Issue by fac30ff** [springfox/springfox#3123]
Env:
spring boot 2.17 (web, web-services)
springfox 2.9.2
spring cloud (openfeign, sleuth, stream, binder-rabbit)

Due to limit of external service controller consume and send text/xml http request/response;
Config: 
`@Bean
   public Docket api() {
     return new Docket(DocumentationType.SWAGGER_2)
         .globalOperationParameters(getParameters())
         .select()
         .apis(RequestHandlerSelectors.basePackage("package"))
         .paths(PathSelectors.any())
         .build()
         .apiInfo(apiInfo());
   }

   private ApiInfo apiInfo() {
     return new ApiInfoBuilder()
         .title("title")
         .description("desciption")
         .version("v1")
         .build();
    }

   private List<Parameter> getParameters() {
     ParameterBuilder requestId = new ParameterBuilder();
     requestId
         .name("X-Flow-ID")
         .description("X-Flow-ID header")
         .modelRef(new ModelRef("string"))
         .parameterType("header").required(true);

    List<Parameter> parameters = new ArrayList<>();
    parameters.add(requestId.build());

    return parameters;
  } `
  

But this xml object has same name but different structure;
So both class has full qualified name in method signature and return type;

Problem: springfox generate both output and input body as one merged object;

**Comment by MaksimOrlov** [comment]
Hi, @fac30ff. Version 2.9.2 doesn't support difference in models with same names but in different packages. You should update to 3.0.0- SNAPSHOT version.
