### ISSUE TITLE
Compatibility with Spring Boot 2.2 

### ISSUE THREAD

**Issue by cemo** [springfox/springfox#3124]
Latest version of SpringFox unfortunately is not compatible with some API's of Spring Boot 2.2. So far I noticed that spring-plugin-core some methods has changed such as `org.springframework.plugin.core.PluginRegistry#getPluginFor(S, java.util.function.Supplier<E>)` which requires `Supplier` anymore. What do you suggest to migrate to Spring Boot 2.2?

**Comment by ghostd** [comment]
Duplicate of #2932
