### ISSUE TITLE
How to configure multiple swagger-ui based on servlet context path in spring boot

### ISSUE THREAD

**Issue by srijithchandran** [springfox/springfox#3128]
https://stackoverflow.com/questions/30670327/spring-boot-with-multiple-dispatcherservlet-each-having-their-own-controllers/30686733

Have created the spring boot application with multiple dispatcherservlet. Want to configure swagger-ui for each context path

http://localhost:8080/foo/swagger-ui.html (foo controller)
http://localhost:8080/bar/swagger-ui.html (bar controller)

I'm getting below error. 

when i hit http://localhost:8080/foo/
**Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Sep 24 14:41:31 IST 2019
There was an unexpected error (type=Internal Server Error, status=500).
Could not resolve view with name 'redirect:swagger-ui.html' in servlet with name 'foo'**

when I hit http://localhost:8080/foo/swagger-ui.html

**Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Sep 24 14:43:15 IST 2019
There was an unexpected error (type=Not Found, status=404).
No message available**

**In log:**

2019-09-24 14:43:15.358  WARN 1220 --- [nio-8443-exec-5] o.s.web.servlet.PageNotFound             : **No mapping for GET /foo/swagger-ui.html**

**Comment by srijithchandran** [comment]
https://github.com/springfox/springfox/issues/2396

**Comment by mohamadbasij** [comment]
why this happens? 
i expect swagger to be a api documentation just !
not much more...
but context-paths effect on swagger ;)
