### ISSUE TITLE
Unable to infer base url.

### ISSUE THREAD

**Issue by mjrother** [springfox/springfox#3129]
I am trying to integrate springfox-swagger 2 (2.9.2) into our spring boot 2.0.8 web application. The api-docs URL works fine. I am seeing the infamous "Unable to infer base url..." dialog when i try the swagger-ui.html URL. I have security disabled so that is not the issue. I see the following requests from the web server log and the requests are returning 200. As far as I can tell, an exception is thrown in the springfox.js . 
The api-docs request:
GET /XXXXX/api-docs HTTP/1.1 200 5688

The swagger-ui.html requests:
GET /XXXXX/swagger-ui.html HTTP/1.1 200 3318
GET /XXXXX/webjars/springfox-swagger-ui/springfox.css?v=2.9.2 HTTP/1.1 200 2894 http://localhost:8080/XXXXX/swagger-ui.html
GET /XXXXX/webjars/springfox-swagger-ui/swagger-ui.css?v=2.9.2 HTTP/1.1 200 154488 http://localhost:8080/XXXXX/swagger-ui.html 
GET /XXXXX/webjars/springfox-swagger-ui/springfox.js?v=2.9.2 HTTP/1.1 200 96207 http://localhost:8080/XXXXX/swagger-ui.html 
GET /XXXXX/webjars/springfox-swagger-ui/swagger-ui-standalone-preset.js?v=2.9.2 HTTP/1.1 200 440850 http://localhost:8080/XXXXX/swagger-ui.html 
GET /XXXXX/webjars/springfox-swagger-ui/swagger-ui-bundle.js?v=2.9.2 HTTP/1.1 200 1448844 http://localhost:8080/XXXXX/swagger-ui.html 
GET /XXXXX/swagger-resources/configuration/ui HTTP/1.1 200 513 http://localhost:8080/XXXXX/swagger-ui.html 
GET /XXXXX/swagger-resources/configuration/security HTTP/1.1 200 70 http://localhost:8080/XXXXX/swagger-ui.html 
GET /XXXXX/swagger-resources HTTP/1.1 200 171 http://localhost:8080/XXXXX/swagger-ui.html 

How can we further narrow down the problem?

**Comment by jayzh1010** [comment]
same with you, who knows how to resolve it

**Comment by jayzh1010** [comment]
i resolve my problem, because i implements ResponseBodyAdvice, when i remove it, swagger run successfully

ref: https://github.com/springfox/springfox/issues/3001#issuecomment-542488043
