### ISSUE TITLE
Description added to non-json-primitive fields with @ApiModelProperty does not work

### ISSUE THREAD

**Issue by aklatt1194** [springfox/springfox#3138]
This is potentially related to https://github.com/springfox/springfox/issues/2982, but this ticket is adding more detail (including a project that can repro it).

- Setup
I am using a webflux service, but I am not sure whether or not that is relevant. I have created this project which is a very small service that reproduces the issue: https://github.com/aklatt1194/springfox-bug/.

- What version of the library are you using?
3.0.0-SNAPSHOT (downloaded from http://oss.jfrog.org/oss-snapshot-local/io/springfox/)

- What kind of issue is this?
This is a bug.

- Description
I have added a text "description" to both my `Double` and `LatLong` fields with the `@ApiModelProperty` annotation (see: https://github.com/aklatt1194/springfox-bug/blob/master/src/main/java/com/example/springfoxbug/model/Response.java#L12-L15), but only the description on the primitive object seems to appear in the model section of the generated UI (see attached screenshot), the other one has no visible description. I assume this has to do with the fact that this one is a reference to the other model in the JSON.

<img width="1603" alt="Screen Shot 2019-10-09 at 2 28 47 PM" src="https://user-images.githubusercontent.com/9541498/66522273-e5f23200-eaa1-11e9-9366-c3ce3ca5415e.png">

**Comment by InnuceEAN** [comment]
I like it when unfixed bugs are closed due to inactivity...

**Comment by bnegrao** [comment]
I would like to see it fixed, I am facing that same issue and it's not cool...
