### ISSUE TITLE
Implement refreshtoken flow in SwaggerUI

### ISSUE THREAD

**Issue by samuelj90** [springfox/springfox#3139]
I would like to know whether swagger ui will implement the refresh token flow when a 401 error occurs by refreshing the access token with the refresh token 

What version of the library are you using?

springfox-swagger2:2.9.2

What kind of issue is this?
Question

**Comment by samuelj90** [comment]
This question in not answered yet

**Comment by dilipkrish** [comment]
@samuelj90 that as a bot as you can tell. It should be fixed with the latest 3.0.0-SNAPSHOT
