### ISSUE TITLE
@ApiParam(hidden = true) not working in 3.0?

### ISSUE THREAD

**Issue by gigecogary** [springfox/springfox#3154]
I'm using the 3.0 snapshot. Is this broken in that version? 
```
@PutMapping("/users/{id}")
public User updateUser(
@ApiParam(hidden = true) Principal principal)
{}

```
Still shows in the swagger ui website

**Comment by jhoanmanuelms** [comment]
I'm using `2.9.2` and it isn't working for me either 😞
