### ISSUE TITLE
SpringFox 3.0.0-SNAPSHOT boot time is unacceptably slow

### ISSUE THREAD

**Issue by sgri** [springfox/springfox#3171]
We have a web app with 200 REST functions, Spring Fox initialization phase is from 3 to 5 minutes.
The bottleneck is springfox.documentation.spring.web.scanners.ApiModelReader#mergeModelBranch  which merges models recursively.

**Comment by MaksimOrlov** [comment]
Good evening, @sgri 

Could you provide some kind of test repository, so I can find the reason, that makes merging of models slow.

**Comment by MaksimOrlov** [comment]
@sgri, could you, please, try latest SNAPSHOT version? There were some PR's with fixes. Does it still work slow with you project?

**Comment by dilipkrish** [comment]
@sgri I believe @MaksimOrlov has addressed the performance issues and made it much faster. Closing this issue for now as fixed. Please report back if it isn't

**Comment by sgri** [comment]
`@sgri, could you, please, try latest SNAPSHOT version?`
Unfortunately I could not verify because the latest version 3.1.0-SNAPSHOT is build with java 11.0.7. We still using version 1.8 in production, and when compiling the source code with java 1.8 I get
"startup failed:
/home/sgr/Work/springfox-original/springfox-spring-webmvc/build/classes/groovy/test/springfox/documentation/spring/web/readers/MixedMultipartRequestParameterBuilderSpec$_expectedModel_closure8$_closure24$_closure25$_closure30$_closure33$_closure36$_closure37$_closure38.class (File name too long)"

**Comment by sgri** [comment]
Eventually I could compile code after moving the directory to root folder. Now  I need to publish the jar files to my local maven repository, how can I do that ?

**Comment by dilipkrish** [comment]
@sgri while its built with java 11, it still compiles down to java 8. Looking @ your bug
