### ISSUE TITLE
Swagger UI displays white page. SpringBoot: 2.1.9 & SpringFox: 2.9.2

### ISSUE THREAD

**Issue by prinal10** [springfox/springfox#3173]
Im trying to use swagger in a spring boot project. It was working before with spring boot 2.0.5. I upgraded the version to 2.1.9 and now it displays blank page when i hit the "swagger-ui.html" endpoint.  In the dev console in browser it shows the following error. I did some googling but i cant find any solution for this. Can anyone help me with this issue.?

![image](https://user-images.githubusercontent.com/23653871/68161113-6164c900-ff12-11e9-8f03-7df6c5473787.PNG)

**Comment by boomesh** [comment]
Getting the same issue, spring boot 2.2.0

**Comment by zanio** [comment]
This issues occurs because you are making use of spring security which automatically locks all path, be it path to js file, css file. You would need to configure swagger docs using spring security. In my case this was the fixed i used

```
@Configuration
@EnableSwagger2
@Import(BeanValidatorPluginsConfiguration.class)
@Order(100)
public class SpringFoxConfig  extends WebSecurityConfigurerAdapter {


    public static String[] SWAGGER_URL_PATHS = new String[] { "/swagger-ui/index.html", "/swagger-resources/**",
            "/v2/api-docs**", "/webjars/**", "/swaggerfox.js", "/swagger-ui/**" };

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.csrf().disable();
        http.requestMatchers()
                .antMatchers(SWAGGER_URL_PATHS)
                .and().authorizeRequests().antMatchers(SWAGGER_URL_PATHS)
                .permitAll();
    }
...
}
```
