### ISSUE TITLE
How to make springfox work with Spring-Hateoas 1.0

### ISSUE THREAD

**Issue by gigecogary** [springfox/springfox#3174]
I'm already using Springfox snapshot 3.0 but it is still dependent on Spring-Hateoas 0.25. Recently 1.0 was released and my project depends on it, but also springfox. How do I get both to work together?

**Comment by Samyssmile** [comment]
Actually you cant do that easy way

**Comment by chadmalla-ff** [comment]
see [#2932](https://github.com/springfox/springfox/issues/2932#issuecomment-551073343)
