### ISSUE TITLE
Spring boot 2.2 and lazy bean initialization

### ISSUE THREAD

**Issue by orousseil** [springfox/springfox#3182]
I've found a bug with lazy bean initialization (when the property "spring.main.lazy-initialization" is set to true). In that case the "models" part (located at the bottom of the swagger-ui page) contains objects without any attributes !

I found that passing back "RequestMappingHandlerAdapter" bean to a standard initialization fix this issue.

So in my case I've had to add a Spring Configuration class with

<pre>
/**
 * This class is used to fix the bug with spring boot 2.2 which lead to have no attributes in the "models" in swagger-ui
 * when spring.main.lazy-initialization" is set to true (i.e when lazy bean initialization is activated)
 * cf https://github.com/springfox/springfox/issues/3182
 */
@Configuration
public class SpringFoxConfig implements BeanFactoryPostProcessor {

    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) {

        BeanDefinition definition = beanFactory.getBeanDefinition("requestMappingHandlerAdapter");
        definition.setLazyInit(false);
    }

}
</pre>

**Comment by chadmalla-ff** [comment]
By any chance are you using `Sping Hateoas` alongside with `springfox` ?

**Comment by orousseil** [comment]
no sorry

**Comment by Laess3r** [comment]
Same issue occurs in our project. We are using  springfox-swagger2 version 2.9.2.
As soon as following property is set, the model definitions are empty:

`spring.main.lazy-initialization= true`

@orousseil your configuration **fixed it for us too**, but it's not very nice to mess around with Spring internals. Thank you!

**Comment by orousseil** [comment]
seems that issue #2925 is the same bug but with a older version of spring boot (less than 2.2)

**Comment by wyso-rdb** [comment]
same issue with spring-fox 3.0.0

**Comment by Guilherme-Cosso** [comment]
+1
