### ISSUE TITLE
springfox support to spring boot 2.2.1

### ISSUE THREAD

**Issue by regojoyson** [springfox/springfox#3187]
version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

When will be the support version for spring boot 2.2  is available? Due to this issue, we are not able to upgrade our projects to get new features of the spring framework. 

Is there any teaser/hint about what's happening to support spring boot 2.2?

Are these projects still exist or degraded?

**Comment by kaoding** [comment]
希望可以快点支持 spring boot 2.2.X https://github.com/springfox/springfox/issues/2932

**Comment by utkarsh-bodake-n26** [comment]
Any updates on this ticket, please.

**Comment by mmornati** [comment]
In the end guys I just migrated the documentation over OpenAPI and it is working good with the latest spring version: https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#server

**Comment by stovocor** [comment]
> Due to this issue, we are not able to upgrade our projects to get new features of the spring framework.

Can you please elaborate what problems you ran into? We updated our project to Spring Boot 2.2.1 and SpringFox works as expected, including OAuth authentication.

**Comment by andersonbalves** [comment]
I believe the problem happen when you use spring data. I've added springfox on my spring boot application and when I run it, I get noClassDefFound from a class that was removed from spring core.
If I remove spring data then I can downgrade spring core and the error doesn't happen.

**Comment by jwenting** [comment]
Using Spring Boot 2.2.1 and Spring Data REST I get the following:

>  ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> An attempt was made to call a method that does not exist. The attempt was made from the following location:
> 
>     org.springframework.data.rest.core.support.UnwrappingRepositoryInvokerFactory.<init>(UnwrappingRepositoryInvokerFactory.java:57)
> 
> The following method did not exist:
> 
>     org.springframework.plugin.core.PluginRegistry.of(Ljava/util/List;)Lorg/springframework/plugin/core/PluginRegistry;
> 
> The method's class, org.springframework.plugin.core.PluginRegistry, is available from the following locations:
> 
>     jar:file:/C:/.m2/repository/org/springframework/plugin/spring-plugin-core/1.2.0.RELEASE/spring-plugin-core-1.2.0.RELEASE.jar!/org/springframework/plugin/core/PluginRegistry.class

Spring Boot Data REST 2.2.1 imports version 2.0.0.RELEASE of that plugin, which isn't compatible at all with the 1.2.0 version (different methods, different method arguments for those methods that have the same names).
