### ISSUE TITLE
@ApiIgnore doesn't hide multiple (selected ) apis  from @Requestmapping values

### ISSUE THREAD

**Issue by PriyankaKoppad** [springfox/springfox#3195]
I want to hide selected api paths from @Requestmapping where we mention multiple paths as values, please find below example.

@RequestMapping( value = {"/data/otn/connection/trail", "/data/otn/connections/trails", "/data/otn/trails"}, method=RequestMethod.GET, produces=MediaType.APPLICATION_JSON_VALUE)

here,
I want to hide only "/data/otn/connection/trail" not the others, in this scenario we can't use @ApiIgnore,if i use all 3 will be hidden in swagger doc.

@dilipkrish can you guys please suggest how to hide such apis in swagger doc.

**Comment by PriyankaKoppad** [comment]
@rajatvig  can you please look into this ?? we have some urgent requirements

**Comment by rajatvig** [comment]
I have no idea what this is and why I am tagged. Maybe you got the wrong person?

**Comment by PriyankaKoppad** [comment]
@rajatvig  ohhh sorry i tagged you wrongly here

**Comment by PriyankaKoppad** [comment]
@dilipkrish I hope you are the correct person I should concern for this , can you please look into this and let me know how I should proceed with this ?
