### ISSUE TITLE
'/csrf' 401 and '/' 404 when loading swagger-ui.html

### ISSUE THREAD

**Issue by rsteaburdea** [springfox/springfox#3196]
- [ ] What version of the library are you using? 
It is the latest version.
[ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?
 - [ ] Support needed. @dilipkrish 

**Additional details:**
- Browser: Google Chrome
- IDE: IntelliJ IDEA: Ultimate 2019.2
- Java: 1.8
- Spring Boot: Latest - 2.2.1
- Spring Boot Stater Security: Latest - 2.2.1
- Spring Security Test: Latest - 5.2.1

When I try to load http://localhost:server.port/swagger-ui.html page loads but with inspect I see this two bad requests:
![WhatsApp Image 2019-11-26 at 20 33 05](https://user-images.githubusercontent.com/40496269/69667683-267c2e00-1097-11ea-9f7b-f55cc7bc5194.jpeg)
![WhatsApp Image 2019-11-26 at 20 33 23](https://user-images.githubusercontent.com/40496269/69667690-2845f180-1097-11ea-9b6f-1a409c54e156.jpeg)

On server side it throws an exception: `org.springframework.security.access.AccessDeniedException: Access is denied`.
![image](https://user-images.githubusercontent.com/40496269/69672747-6cd68a80-10a1-11ea-9864-4c5e14340b2e.png)
![image](https://user-images.githubusercontent.com/40496269/69672814-8d064980-10a1-11ea-9b2e-9faa82a1a3f8.png)

I tried with debug mode and it looks like the problem is in: `JwtAuthenticationFilter` -> `doFilterInternal(...)` -> `filterChain.doFilter(request, response);`.
Also `bearerToken` is **null**.

I tried to follow this tutorial: [Part1](https://www.callicoder.com/spring-boot-spring-security-jwt-mysql-react-app-part-1/) and [Part2](https://www.callicoder.com/spring-boot-spring-security-jwt-mysql-react-app-part-2/) and add Swagger to the project.

I am not sure if this is a normal behavior.
I also checked some similar issues on this channel also on stackoverflow like [this](https://stackoverflow.com/questions/55582023/when-loading-the-swagger-ui-html-page-a-request-is-made-to-hostport-and-host) with no result.

**Comment by rsteaburdea** [comment]
In #2639 I found a comment of @matthewh86 where he bypassed server side errors by adding `.antMatchers("/", "/csrf").permitAll()` to `HttpSecurity http` but how he said if feels like 
> hacky

Also I still have this two errors in browser:
![image](https://user-images.githubusercontent.com/40496269/69710334-e1dcab00-1107-11ea-9092-bd8c57fcbc85.png)

`csrf` is disabled for `http` and I have an `AuthWhiteList` for 
```
// -- swagger ui
"/swagger-resources/**",
"/swagger-ui.html",
"/v2/api-docs",
"/webjars/**",
"/configuration/ui",
"/configuration/security"
```

**Comment by GaganBhat** [comment]
Hi, were you able to solve this? Having a similar issue with 401s for my springfox-swagger ui files regardless of my security config. 
![image](https://user-images.githubusercontent.com/25236969/86621423-cda53a00-bf83-11ea-9533-0aa4fcfd0e19.png)
 @rsteaburdea

**Comment by rsteaburdea** [comment]
Hello @GaganBhat I did that workaround, could't find any other solution.
If you find a fix please add it here to close this issue.

**Comment by dilipkrish** [comment]
For everyones benefit, outside of the permit all fix for the `401` error, the reason we see the `404` is that the `/csrf` endpoint doesn't exit. The only reason for its existence is to return a cookie based csrf token that swagger ui uses.
