### ISSUE TITLE
How to hide service url from swagger ui page

### ISSUE THREAD

**Issue by ashok1979sharma** [springfox/springfox#3198]
I am using SwaggerResourcesProvider to serve two different json files already available in my resources folder. 

Using Springfox 2.9.1

I have created two specification which gets displayed in "Select a Spec" dropdown.

When I select any one out of these two specifications swagger calls url like below internally 
For first option: https://localhost:9451/service/default
For second option: https://localhost:9451/service/tpp

My problem is, by default swagger ui displays this service url in ui, which I want to hide.

Screenshot attached.

![image](https://user-images.githubusercontent.com/20903468/69702128-8cf36180-1114-11ea-8bb5-ceefb271d260.png)

I am sure there should be some way to do that.

Thanks

**Comment by kbt18** [comment]
I came up with the following workaround:

In /src/style/_information.scss I changed the style for hgroup.main to the following:

`   
 hgroup.main
    {
        margin: 0 0 20px 0;
        a
        {
            font-size: 12px;
        }
        span.url
        {
            display: none;
        }
    }
`

Adding display:none for span.url should fix this.

This will also require a rebuild of the minified files. 

These commands should be run from the top directory for swagger ui:

>npm install 
>npm run build

**Comment by sameer-mhd** [comment]
> I came up with the following workaround:
> 
> In /src/style/_information.scss I changed the style for hgroup.main to the following:
> 
> ` hgroup.main { margin: 0 0 20px 0; a { font-size: 12px; } span.url { display: none; } }`
> 
> Adding display:none for span.url should fix this.
> 
> This will also require a rebuild of the minified files.
> 
> These commands should be run from the top directory for swagger ui:
> 
> > npm install
> > npm run build

This helped, Thanks
