### ISSUE TITLE
Springfox Producing Bad JSON Documentation When Wrap_Root_Value Is Enabled

### ISSUE THREAD

**Issue by dan-whitehouse** [springfox/springfox#3202]
I know that there are issues related to the documentation not rendering correctly in the Swagger UI when wrap root value is enabled. However, when setting spring.jackson.serialization.wrap-root-value=true, Springfox generates a json file that can't be read. 

I am using: 
springfox-swagger2 v.2.9.2
spring-boot-starter-parent v2.2, 
As well as Swagger 3 UI

When going to the Swagger 3 UI I am presented with the following error: 
> Unable to render this definition
> The provided definition does not specify a valid version field.
> 
> Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

However, I know that there is a version tag being generated, and I know that it's value is 2.0. 

`{"Json": {"swagger": "2.0", etc... } }`

The problem is (I think) that the entire output is being wrapped in a Json tag. If I disable wrap root value I get:

`{"swagger": "2.0", etc..}`

And the error goes away, and I can view the Swagger UI. 

However, when returning data my output is incorrect. Is there a work around, where I can ignore the wrap root value property when generating the json file? Or is the some recommendation to work around this until this gets fixed?

**Comment by gauravshelangia** [comment]
@dwriconeapi I am also facing the same issue. Did you manage to get it working?

**Comment by gauravshelangia** [comment]
@dilipkrish Can you please suggest some workaround for this issue?
