### ISSUE TITLE
@Api(hidden = true) not working in 2.9.2?

### ISSUE THREAD

**Issue by pog2g** [springfox/springfox#3203]
I'm using the 2.9.2. Is this broken in that version?
```
@Api(tags = "BaseConfig", value = "BaseConfigApi", description = "BaseConfigApi接口相关", hidden = true)
```
Still shows in the swagger ui website

**Comment by ryandanielspmc** [comment]
@pog2g see https://github.com/springfox/springfox/issues/2437

**Comment by ryandanielspmc** [comment]
Maybe this should be marked as a bug instead of being marked stale?
