### ISSUE TITLE
Springfox swallows one of the controller methods when it has same url

### ISSUE THREAD

**Issue by amelnikoff** [springfox/springfox#3205]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? 
2.9.2

What kind of issue is this?

 - [ ] Bug report. 
When controller has two mappings on same url, result json will contain only one method description

```java
  @GetMapping(value = "/has", params = {"permName", "dictId", "sectionId"})
  public Boolean hasAccessForDictionary(@RequestParam String permName,
                                        @RequestParam Long dictId,
                                        @RequestParam(required = false) Long sectionId
  ) {
  }

  @GetMapping(value = "/has", params = {"permName", "conceptId"})
  public Boolean hasAccessForConcept(@RequestParam String permName, @RequestParam Long conceptId) {
  }
```
    - [ ] spring xml/java config that is relevant
java config

    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
![image](https://user-images.githubusercontent.com/3614457/70527810-cc32a100-1b5d-11ea-9ba2-4748455883f7.png)

**Comment by FML3426** [comment]
same problem

**Comment by FML3426** [comment]
Can set enableUrlTemplating(true) in your docket configuration.

**Comment by amelnikoff** [comment]
Will try this. Thanks @FML3426.

**Comment by caducbraga** [comment]
When I set enableUrlTemplating(true) I started getting this error:
https://github.com/springfox/springfox/issues/1419

According to @dilipkrish:
> Dont set the url template to true if you're using a version greater than 2.7.0
https://github.com/springfox/springfox/issues/1419#issuecomment-416553977

Any ideas?
