### ISSUE TITLE
Remove tags at the base of the swagger json document

### ISSUE THREAD

**Issue by sp4ce** [springfox/springfox#3213]
- Version: 2.9.2
- What kind of issue is this? **Feature Request**

Hello,  we started using SpringFox, and we don't want to generate any tag at document root level. 

For example, right now, if I have a Controller like this.
```
@RestController
@RequestMapping("/publicapi/v1/trips")
public class TripPublicController {
   ...
}
```

Then the swagger document contains default tags like this:
```
tags: [
  {
    name: "trip-public-controller",
    description: "Trip Public Controller"
  }
]
```

I tried to set the following annotations `@Api(tags = {})`, but it is ignored. Debugging, it looks like it is  coming from that code in the `SwaggerApiListingReader`: https://github.com/springfox/springfox/blob/09d4a734b64a216bb5c26c0329f3d15b8276c0e4/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/SwaggerApiListingReader.java#L55

So I would like to know how you would like to see a feature to actually set not tag if you don't want them.

**Comment by DavidDev21** [comment]
Would like an answer for this as well

**Comment by dilipkrish** [comment]
@DavidDev21 could you create a new issue describing your problem and which springfox version you're using.

**Comment by sp4ce** [comment]
@DavidDev21 we are gradually switching to springdoc witch provide such feature, but for our existing services using springfox, we did the following customization (be careful it removes all the tags):

```java
/**
 * Custom plugin to empty the tag value in the operations. The {@link Order} is set after the
 * {@link SwaggerPluginSupport#SWAGGER_PLUGIN_ORDER} in order to make sure it overwrite any
 * existing logic in spring fox {@link SwaggerOperationTagsReader}.
 */
@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 1)
public class SwaggerEmptyTagOperationPlugin implements OperationBuilderPlugin {

  @Override
  public void apply(OperationContext context) {
    context.operationBuilder().tags(emptySet());
  }

  @Override
  public boolean supports(DocumentationType documentationType) {
    return true;
  }
}
```

**Comment by didierbreedt** [comment]
Setting `@Api(tags = {"Endpoints"})` removed the auto generated tag for that controller.

**Comment by Tai-ch0802** [comment]
This solution may can work.

Set `@Tag(name="something")` to override the `default tag (trip-public-controller)`.

In example
```java
@RestController
@Tag(name="your-tag")
@RequestMapping("/publicapi/v1/trips")
public class TripPublicController {
   ...
}
```
