### ISSUE TITLE
How to add multiple spec to Swagger-UI?

### ISSUE THREAD

**Issue by hisivasankar** [springfox/springfox#3223]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I am using SpringFox in one of my projects for generating the API docs. A default spec is generated from the RestControllers, but I also have another endpoint which is exposing another spec file. 

I see that there is a section in the UI header for selecting different spec and if in the Swagger-UI configuration, we can set multiple spec Urls for loading many spec files.

My question, how do I achieve the same using SpringFox?

Any hint would be really helpful and I thank you in advance!

**Comment by hisivasankar** [comment]
I found the answer myself from the documentation.

https://springfox.github.io/springfox/docs/snapshot/#aggregating-multiple-swagger-specifications-in-the-same-swagger-ui

Hence, closing the issue.

**Comment by nunocruz** [comment]
I am returning 2 resources but the UI just uses the first one returned. There's an issue with this still.
