### ISSUE TITLE
ApiImplicitParam impossible to specify type of parameter

### ISSUE THREAD

**Issue by Vendelieu** [springfox/springfox#3225]
i'm just want get NOT STRING type of parameter

tried to specify like(in Kotlin):
```
@ApiImplicitParam(value = "Count of minutes", name = "timeout", required = true, dataTypeClass = Int::class, paramType = "body")
```
in output i get String type
and doesn't matter which type I use i get String everytime

next try:
```
@ApiImplicitParam(value = "Count of minutes", name = "timeout", required = true, dataTypeClass = Int::class, dataType = "Integer", format = "int32", paramType = "body")
```
(Int, Integer tried both)
it would seem, how much more precisely?
but i get an error
```
Illegal DefaultValue null for parameter type integer
java.lang.NumberFormatException: For input string: ""
```
even if i use defaultValue i get same error

is there at least some opportunity to determine them? I'm don't understand

**Comment by Vendelieu** [comment]
or i get String type and doesn't matter if there was other type
or i get empty field in swagger-ui
or i get error

**Comment by eldontc** [comment]
I have the same problem mentioned by @Vendelieu. I have tried String, String::class and I still get the WARN below

> 2021-09-09 11:14:54.387  WARN 755100 --- [  restartedMain] d.s.r.o.OperationImplicitParameterReader : Unable to interpret the implicit parameter configuration with dataType: String, dataTypeClass: class java.lang.Void

The Kotlin code that  cause the warning is
> @ApiImplicitParams(
            ApiImplicitParam(name = "Authorization", required = true, dataType = "String", paramType = "header", value = "Authorization"),

I'm using springfox 3.0.0 

>  implementation "io.springfox:springfox-boot-starter:3.0.0"
    implementation 'io.springfox:springfox-swagger-ui:3.0.0'
