### ISSUE TITLE
ApiModelProperty notes not working for Enum type

### ISSUE THREAD

**Issue by minhnguyenvan95** [springfox/springfox#3228]
I tried annotation @ApiModelProperty in my @RequestBody object but look like it's not working with Enum type .

I tried to replace MyEnum to String and my note is shown.

Thank you

For e,g:

```
    @NotNull
    @ApiModelProperty(notes = "My note")
    private MyEnum myEnum;
```

**Comment by pgi-jsanchez** [comment]
Hello.
DId you check with "/v2/api-docs"?
If there is not the notes property for that enum, it's most likely to have the same bug just like I do.
