### ISSUE TITLE
WebFlux Multipart File Upload - not possible to use FilePart in Swagger Version: 3.23.11

### ISSUE THREAD

**Issue by codemasterbish** [springfox/springfox#3232]
For an endpoint using Spring WebFlux to upload a file, the Swagger UI documentation is not generating properly the File Input Button. It doesn't allow to choose a file and send it as a multipart request for FilePart:

![image](https://user-images.githubusercontent.com/36158047/72140030-676ba000-33c2-11ea-8315-0ae9ba5d06ec.png)

Controller

```
public String upload(
@RequestPart(value = "uploadedBy", required = true) String uploadedBy,
@RequestPart(value = "file",required = false) FilePart file)
{
   .....
}
```

Swagger Version: 3.23.11
Below are the Swagger Maven dependencies.

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-bean-validators</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-spring-webflux</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>

API Doc Json :
```
"paths": {
        "/upload": {
            "post": {
                "tags": [
                    "document-controller"
                ],
                "summary": "uploadDocument",
                "operationId": "uploadDocumentUsingPOST",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "formData",
                        "name": "file",
                        "description": "file",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/FilePart"
                        }
                    },
                    {
                        "name": "uploadedBy",
                        "in": "formData",
                        "description": "uploadedBy",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        }
    }
```

**Comment by sylvain-rouquette** [comment]
in the meantime, you can do this:

```
    @ApiImplicitParams({
            @ApiImplicitParam(name = "file1", dataType = "__file", paramType="form", required = true),
            @ApiImplicitParam(name = "file2", dataType = "__file", paramType="form", required = true)
    })
```

**Comment by matpil** [comment]
Great!
as workaround @sylvain-rouquette solution works fine
![image](https://user-images.githubusercontent.com/546865/81926620-85504800-95e2-11ea-9f16-144cc1e94c23.png)

**Comment by dilipkrish** [comment]
Is this still an issue? As an aside in 3.x onwards the __file won't work very well, instead use `MultipartFile.class` in dataTypeClass.

**Comment by bastman** [comment]
@dilipkrish are there any updates or work-a-rounds?

I'm facing the same issue with spring-boot (webmvc) and "MultipartFile".

Since I switched to springfox:3.0.0 - I can no longer upload a file using the swagger-ui.

Thanks a lot for your help.

```
    @PostMapping("/upload")
    fun upload(
            @ApiIgnore authentication: Authentication,
            @RequestParam("theFile") uploadedFile: MultipartFile,
            @RequestParam(required = false) jmesPath: String?
    ): Any? {
       return mapOf("size" to uploadedFile.size)
    }
```

**Comment by philipplewe** [comment]
Had the same issue and followed this guide: https://stackoverflow.com/questions/63275134/springfox-swagger-ui-3-0-0-does-not-bring-up-swagger-ui-html-page

@RequestPart("file") instead of @RequestParam("file") did the trick.

**Comment by Svishwajeet04** [comment]
`@PostMapping(value = "/add", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public Mono<ResponseEntity<Object>> addItem(@RequestPart("data") String data, Authentication authentication,
                                                @RequestPart(value = "images", required = false) Flux<Part> images) {
        return itemService.addItem(AuthUtil.getCurrentUserId(authentication), DaoUtils.fromJson(data, CreatorDtos.AddItemDto.class), images);
    }`
    
`<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
            <version>2.1.0</version>
        </dependency>`
still not getting file upload button at swagger, any one could help ?
