### ISSUE TITLE
Wich repository springfox 3.0.0-SNAPSHOT is in?

### ISSUE THREAD

**Issue by viniciuscarneiro** [springfox/springfox#3237]
I don't know where i could download this dependencies:
```
	compile 'io.springfox:springfox-swagger2:3.0.0-SNAPSHOT'
	compile 'io.springfox:springfox-swagger-ui:3.0.0-SNAPSHOT'
	compile 'io.springfox:springfox-spring-webflux:3.0.0-SNAPSHOT'
```

Please help me!

It is not in the maven central...

**Comment by nielsbasjes** [comment]
This is mentioned in the documentation here:
https://springfox.github.io/springfox/docs/snapshot/#snapshot-3

**Comment by viniciuscarneiro** [comment]
thank you!!! @nielsbasjes
