### ISSUE TITLE
[3.0.0] Optional params are printed as required

### ISSUE THREAD

**Issue by ssentanoe** [springfox/springfox#3240]
Hi!
I found a bug that an Optional parameter will be rendered as required :)
This happens when I use `Optional<T>`, but if I use `@RequestParam(.... , required = false)`, it works fine. 

Version 2.9.2 does not have this problem.

Other than that, I want to say, huge thank you for this project :)

**Comment by dilipkrish** [comment]
This was fixed in 3.0.0

**Comment by ssentanoe** [comment]
hi! thanks for the update, just now I tried in kotlin with nullable, it still says required. But if I add `required = false` then it is fine
![Screen Shot 2020-07-22 at 20 52 41](https://user-images.githubusercontent.com/4618600/88184752-4af7cc80-cc5d-11ea-85f7-f1547dc15710.png)

**Comment by dilipkrish** [comment]
Kotlin nullable types aren't directly supported... however java native Optionals are
