### ISSUE TITLE
url query problem

### ISSUE THREAD

**Issue by yangganboy** [springfox/springfox#3252]
![QQ截图20200213155626](https://user-images.githubusercontent.com/34567847/74413816-1fd1ab80-4e7b-11ea-865c-e5cc69aa580e.png)
![QQ截图20200213160937](https://user-images.githubusercontent.com/34567847/74413885-3ed03d80-4e7b-11ea-84cf-1cbbd24f60d0.png)
Am I using it correctly?

**Comment by yangganboy** [comment]
version 3.0.0
query param {?.*} in url lead to request fail

**Comment by dilipkrish** [comment]
You need to set `enableUrlTemplating` to false in your docket
