### ISSUE TITLE
Unable to infer base url

### ISSUE THREAD

**Issue by hellerEkc** [springfox/springfox#3253]
springfox-swagger2 - 2.9.2. I get Unable to infer base url when I try to access swagger-ui.html.

here is my SwaggerConfig 

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {
    @Bean
    public Docket api() {
        Parameter parameter = new ParameterBuilder()
                .name("Authorization")
                .modelRef(new ModelRef("string"))
                .parameterType("header")
               .required(false)
                .build();
        List<Parameter> parameters = Lists.newArrayList(parameter);
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
               .build().globalOperationParameters(parameters).pathMapping("/");
    }



   private Predicate<RequestHandler> paths() {
        return Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot"));
    }
}


```
Can someone give me a point how to solve this issue?

**Comment by bharatchauhan51** [comment]
@dilipkrish @brunomendola I m facing the same issue, and this is the sample im using. The pom file contains

`
<repositories>
   <repository>
     <id>jcenter-snapshots</id>
     <name>jcenter</name>
     <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
   </repository>
</repositories>

<dependency>
   <groupId>io.springfox</groupId>
   <artifactId>springfox-swagger2</artifactId>
   <version>3.0.0-SNAPSHOT</version>
</dependency>
`
And the swagger configuration is like 
`
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2WebMvc;

import static springfox.documentation.builders.PathSelectors.ant;
import static springfox.documentation.builders.RequestHandlerSelectors.basePackage;
import static springfox.documentation.spi.DocumentationType.SWAGGER_2;

@SpringBootApplication
@Configuration
@EnableSwagger2WebMvc
public class DemoApplication {

	@Bean
	public Docket api() {
		return new Docket(SWAGGER_2)
				.select()
				.apis(basePackage("com.example.demo"))
				.paths(ant("/api/test"))
				.build()
				.useDefaultResponseMessages(false);
	}

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}

`
Please provide a way to overcome this

**Comment by bharatchauhan51** [comment]
@dilipkrish @brunomendola I m facing the same issue, and this is the sample im using. The pom file contains

`<repositories>
   <repository>
     <id>jcenter-snapshots</id>
     <name>jcenter</name>
     <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
   </repository>
</repositories>

<dependency>
   <groupId>io.springfox</groupId>
   <artifactId>springfox-swagger2</artifactId>
   <version>3.0.0-SNAPSHOT</version>
</dependency>`

And the swagger configuration is like

`@SpringBootApplication
@configuration
@EnableSwagger2WebMvc
public class DemoApplication {

@Bean
public Docket api() {
	return new Docket(SWAGGER_2)
			.select()
			.apis(basePackage("com.example.demo"))
			.paths(ant("/api/test"))
			.build()
			.useDefaultResponseMessages(false);
}

public static void main(String[] args) {
	SpringApplication.run(DemoApplication.class, args);
}
}`

Please provide a way to overcome this
