### ISSUE TITLE
NullPointerException if Spring Boot is set to lazy bean initialization

### ISSUE THREAD

**Issue by Fleshgrinder** [springfox/springfox#3260]
I’m using the latest snapshot and have globally set Spring to initialize beans lazily. Doing so results in a NPE in `OptimizedModelPropertiesProvider` because the `objectMapper` property never got initialized. Once switched back to eager bean initialization everything works.

You can reproduce it by creating a Spring Boot application with `spring.main.lazy-initialization=true`.

**Comment by rxxy** [comment]
+1

**Comment by Fleshgrinder** [comment]
😢
