### ISSUE TITLE
Spring Boot Data Rest - No page object in the CollectionModel definition if paged

### ISSUE THREAD

**Issue by Nirostar** [springfox/springfox#3261]
- What version of the library are you using?
3.0.0-SNAPSHOT

- What kind of issue is this?
Bug report.

The definition of a CollectionModel does not contain the `page` object. If the response is of type `Page<Entity>`, the Spring Data Rest response contains

```
  "page": {
    "size": 20,
    "totalElements": 1012,
    "totalPages": 51,
    "number": 0
  }
```
alongside the `_embedded` and `_link` object. This is not present in the corresponding swagger definitions. Please add them, to make the generated client methods able to use this information.

For example: 
The definition contains:
```
       "CollectionModel«Person»": {
            "type": "object",
            "required": ["_embedded", "_links"],
            "properties": {
                "_embedded": {
                    "$ref": "#/definitions/EmbeddedCollection«Person»"
                },
                "_links": {
                    "type": "object",
                    "description": "Link collection",
                    "additionalProperties": {
                        "$ref": "#/definitions/Link"
                    }
                }
            },
            "title": "CollectionModel«Person»",
            "xml": {
                "name": "entities",
                "attribute": false,
                "wrapped": false
            },
            "description": "Resources of Person"
        },
```
and the response looks like:
```
{
  "_embedded": {
	...
  },
  "_links": {
    ...
  },
  "page": {
    "size": 20,
    "totalElements": 1012,
    "totalPages": 51,
    "number": 0
  }
}
```

**Comment by MaksimOrlov** [comment]
HI, @Nirostar.

Did you try 2.9.2 version? Is behavior the same?

**Comment by Nirostar** [comment]
No I didn't and its not that easy to switch in my Application. I dug into the springfox code and found `springfox.documentation.spring.data.rest.schema.ResourcesModelProvider#properties(ModelContext context)` to be the best entry point of this problem. I added:

```
ResolvedType page = resolver.resolve(Page.class);
```
before the return and

```
,
                new ModelPropertyBuilder()
                        .name("page")
                        .type(page)
                        .qualifiedType(page.getSignature())
                        .position(2)
                        .isHidden(false)
                        .required(false)
                        .description("Page")
                        .build()
                        .updateModelRef(modelRefFactory(
                                context,
                                enumTypeDeterminer,
                                typeNameExtractor))
```
to the Stream.of parameters. Unfortunately, I have no clue how resolver.resolve works and I'm also quite new to GitHub so I'm a bit stuck how to submit pull requests, etc. Maybe you can help me out?

**Comment by MaksimOrlov** [comment]
You can fork this project and then add your changes in separate branch. Then @dilipkrish will review it.
I will mark that issue as enhancement.

**Comment by Nirostar** [comment]
Can anyone point me into the direction where I have to implement the resolve for the Page class?
