### ISSUE TITLE
Failed to convert value of type 'java.lang.String' to required type 'java.util.List'

### ISSUE THREAD

**Issue by bma6026** [springfox/springfox#3263]
Hello,
I upgraded springfox from 2.8.0 to 3.0.0.SNAPSHOT and spring boot from 1.5 to 2.2.
I have an issue with items parameter (type List()).
Here the openApi code :
/services/rest/..../{idPersonne}/.../{idPreferenceContact}: put: tags: - "Personne V4" summary: "Modifier ....." description: "" operationId: "modifierPreferenceContact" parameters: - name: "idPersonne" in: "path" description: "Id de ..." required: true schema: type: "integer" format: "int64" - name: "idPreferenceContact" in: "path" description: "Id de ..." required: true schema: type: "integer" format: "int64" - name: "canauxContact" in: "query" description: "Liste des Id de ..." schema: type: "array" items: type: "integer" format: "int64" responses: 200: description: "OK" 400: description: "erreur dans la requête" 404: description: "élement non trouvé"

My dependencies in pom.xml :

`
io.springfox
springfox-swagger2
${swagger.version}
compile

io.springfox
springfox-swagger-ui
${swagger.version}
compile

io.swagger.core.v3
swagger-core
${swagger.core.version}

io.swagger.core.v3
swagger-annotations
${swagger-annotations.version}
compile
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-data-rest</artifactId>
            <version>${swagger.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.plugin</groupId>
            <artifactId>spring-plugin-core</artifactId>
            <version>2.0.0.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-spring-web</artifactId>
            <version>${swagger.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-http</artifactId>
            <version>5.1.4.RELEASE</version>
        </dependency>`
and the error is

{ "timestamp": "2020-03-05T11:42:55+0100", "status": 400, "error": "Bad Request", "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.List'; nested exception is java.lang.NumberFormatException: For input string: \"newArrayList<Long>()\"", "path": "/bic-service-webapp/services/rest/.../1002590762/preference-contact/20" }

Any Help please !

**Comment by MaksimOrlov** [comment]
Hi, @bma6026. 

Could you share your configuration for springfox?

And if it's possible full stack trace of the exception?

**Comment by bma6026** [comment]
Hi @MaksimOrlov,

I have a configuration class inwich i put @EnableSwagger2WebMvc and i create many Docket like this :

` @Bean
    public Docket postsApiV3() {
        return new Docket(DocumentationType.SWAGGER_2)
                .enable(enabled)
                .groupName("Personne V3")
                .apiInfo(apiInfo("Services V3.0"))
                .select()
                .apis(isImplementationOf(fr.enedis.keigo.rfc.api.v30.ServicesApi.class))
                .paths(PathSelectors.any())
                .build();
    }
private static Predicate<RequestHandler> isImplementationOf(final Class<?>... classes) {
        return input -> Arrays.stream(classes).anyMatch(c -> c.isAssignableFrom(input.declaringClass()));
    }
`
I don't have exception server side, i have a message client side 
`"message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.List'; nested exception is java.lang.NumberFormatException: For input string: \"newArrayList<Long>()\""`

Ithink that swagger cannot understand that "newArrayList<Long>()\" is not a string, but default value (init the list of Long).

regards.

**Comment by bma6026** [comment]
Hi,
any suggestion please ? 

Thanks

**Comment by MaksimOrlov** [comment]
@bma6026. There are not enough information to find out the cause for that behavior.

If you provide some test repository, that can reproduce the issue, then I will be able to help you.

Regards.
