### ISSUE TITLE
access stored swagger document for particular api (support)

### ISSUE THREAD

**Issue by RAHULRAJSONU** [springfox/springfox#3264]
Is it possible to access the documents generated by swagger inside the spring boot app, eg;

I have four APIs in an application

```
GET /api/read-api

PATCH /api/update-api

DELETE /api/delete-api

POST /api/create-api
```
and I have swagger configured in the application.

I have another class in the same project where I wanted to access the document for a particular input URL

```
public class SwaggerDocument{

    Map<String, Document>getDocument(String url){

       //I wanted to search generated document for input url

    }

}
```

```
<dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger2</artifactId>
      <version>2.9.2</version>
</dependency>
<dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>2.9.2</version>
</dependency>
```
Any help would be highly appreciated.

**Comment by RAHULRAJSONU** [comment]
Any help please..

**Comment by RAHULRAJSONU** [comment]
Hi Team,
Any help, please.

**Comment by dilipkrish** [comment]
Autowire a dependency in your `SwaggerDocument` class to use `DocumentationCache`. And it should contain all the specifications you need.
