### ISSUE TITLE
Unable to infer base url

### ISSUE THREAD

**Issue by nitishsati82** [springfox/springfox#3269]
I am trying to use swagger UI with spring boot 2, but when I visit URL
http://localhost:9095/swagger-ui.html
then it shows alert with below message:
**Unable to infer base url. This is common when using dynamic servlet registration or when the API is behind an API Gateway. The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/. Please enter the location manually:** 

and in page console errors are
Failed to load resource: the server responded with a status of 404 ()
swagger-resources/configuration/security:1 Failed to load resource: the server responded with a status of 404 ()
swagger-resources:1 Failed to load resource: the server responded with a status of 404 ()
ui:1 Failed to load resource: the server responded with a status of 404 ().

my maven is 
`<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger-ui</artifactId>
		    <version>2.9.2</version>
		</dependency>
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.9.2</version>
		</dependency>`
and Swagger configuration class is 

`public class SwaggerConfig {
	@Bean
	public Docket postsApi() {
		return new Docket(DocumentationType.SWAGGER_2).groupName("public-api").apiInfo(metadata()).
				select().paths(regex("/service/*")).build();
	}

	@SuppressWarnings("deprecation")
	private ApiInfo metadata() {
		return new ApiInfoBuilder().title("API Docs").
				description("API reference guide for developers").
				termsOfServiceUrl("https://newsoftware.com/").contact("newteam, newteam").version("1.0").build();	
	}
}
controller class has below code
`import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.apache.poi.EncryptedDocumentException;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import com.fasterxml.jackson.databind.exc.InvalidFormatException;

@RestController
@RequestMapping(path = "/service")
public class ServiceController implements AnnotBeanConfig {
	private final GetResponseCode getRespCode = GetResponseCode.instance;
	private final Settings setting = Settings.instance;
	private static final Logger logger = LoggerFactory.getLogger(ServiceController.class);
	DefaultServices defServ = null;
	ApplicationContext ctx = null;
	ControllerFactory controller = null;
	@GetMapping(path="/", produces = "application/json")
	public DefaultServices getServices(){
		annotBeanInject();
		defServ = ctx.getBean(DefaultServices.class);
		defServ.getServiceList().add(new DefaultService(JsonKey.ERROR, getRespCode.getResponseCode("accessdenied")));
		return defServ;

	}
	@PostMapping(path= "/", produces = "application/json")
	public DefaultServices postServices(){
		annotBeanInject();
		defServ = ctx.getBean(DefaultServices.class);
		defServ.getServiceList().add(new DefaultService(JsonKey.ERROR, getRespCode.getResponseCode("accessdenied")));
		return defServ;

	}
	@PutMapping(path= "/", produces = "application/json")
	public DefaultServices putServices(){
		annotBeanInject();
		defServ = ctx.getBean(DefaultServices.class);
		defServ.getServiceList().add(new DefaultService(JsonKey.ERROR, getRespCode.getResponseCode("accessdenied")));
		return defServ;

	}
	@DeleteMapping(path= "/", produces = "application/json")
	public DefaultServices deleteServices(){
		annotBeanInject();
		defServ = ctx.getBean(DefaultServices.class);
		defServ.getServiceList().add(new DefaultService(JsonKey.ERROR, getRespCode.getResponseCode("accessdenied")));
		return defServ;

	}
	@Override
	public void annotBeanInject(){
		try{
			ctx = new AnnotationConfigApplicationContext(DefaultConfig.class);
		}catch(Exception ex){
			logger.error("Exception in ServiceController");
			logger.error(DownloadException.stackTraceToString(ex));
		}
	}
}
`
![swagger](https://user-images.githubusercontent.com/22949099/76823619-c0c8d300-683a-11ea-9ebe-38ca259ab9b7.jpg)
![swagggerNetwork](https://user-images.githubusercontent.com/22949099/76823682-ece45400-683a-11ea-9d46-65512b645b81.jpg)

`

**Comment by nitishsati82** [comment]
I was missing @Configuration
@EnableSwagger2 from swagger config.

**Comment by SNebiyev** [comment]
At SpringSecurity config add "/swagger-resources/**" to permitted antMatchers
