### ISSUE TITLE
Swagger UI is blank: Spring boot 

### ISSUE THREAD

**Issue by strivedi7** [springfox/springfox#3273]
Getting hundred of this error,

Refused to load http://localhost:8080/webjars/springfox-swagger-ui/swagger-ui-bundle.js?v=2.8.0-SNAPSHOT because it does not appear in the script-src directive of the Content Security Policy.

It seems like "Content Security Policy" is the issue.

Spring boot application with the following dependencies.

```
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>
```

I see a few other bugs are closed but did not find any suitable solution.

**Comment by strivedi7** [comment]
It was internally disabled by the team only, I fixed the issue.

**Comment by gdinant** [comment]
Hello @strivedi7 could you explain what you actually did to fix the issue? I'm facing the exact same one :).

**Comment by strivedi7** [comment]
In my case "Content Security Policy" was manually disabled. I had to enable it.

**Comment by gdinant** [comment]
Thanks for you answer @strivedi7. I eventually pinpointed the defect on my side. Oddly some policies were added by an internal proxy overriding the ones I could have mapped via Spring Security.
