### ISSUE TITLE
Field typeResolver SwaggerConfig required a bean of type TypeResolver 

### ISSUE THREAD

**Issue by anup-khanal** [springfox/springfox#3275]
I am using the current 3.0.0.SNAPSHOT version of SpringFox Swagger with SpringFramework 2.1.13.RELEASE.  If I change to SpringFox Swagger 2.9.2 everything works fine as expected. But when I change the version to 3.0.0.SNAPSHOT it gives me following error (even with the latest SpringFramework 2.2.5):

**
***************************
APPLICATION FAILED TO START
***************************

Description:

Field typeResolver in ****.SwaggerConfiguration required a bean of type 'com.fasterxml.classmate.TypeResolver' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.fasterxml.classmate.TypeResolver' in your configuration.
**

**Comment by dilipkrish** [comment]
I take it that this issue is fixed now?

**Comment by EuniceB** [comment]
This issue is present in version 2.10.5

**Comment by iawebwork** [comment]
I am getting the exact same error but in the reverse scenario. I was using SpringFox Swagger 3.0.0 but when changed to SpringFox Swagger 2.9.2 (due to errors for modelRefFactory), I started getting the same error. May I know, what was the fix?

Thanks

**Comment by fengsam6** [comment]
I take it that this issue is fixed now?

**Comment by K-J-HYEON** [comment]
When I used the swagger 3.0.0 version from the spring boot 3.2.4 version, I got the following phrase. Has anyone solved it? If you did, how would you have solved it?

```
Parameter 0 of method api in hhplus.ecommerce.config.SwaggerConfig required a bean of type 'com.fasterxml.classmate.TypeResolver' that could not be found
```

**Comment by sebastian-wien-europace** [comment]
Same here with v3.0.0 and Spring Boot v3.3.4. When i am trying to downgrade to 2.9.2 I get the error that this version doesn't exist. Strange is that this 3.0.0 version worked before the upgrade from Spring Boot 2.7 to 3.3.4
