### ISSUE TITLE
How do I disable pageable sort param from showing in docs? 

### ISSUE THREAD

**Issue by micobarac** [springfox/springfox#3276]
Version: 2.9.2

What kind of issue is this?

 - [x] Question.

How do I disable pageable **sort** param from showing in docs?

I am using **Cassandra** database, where sorting doesn't apply like with relational databases, so I want to use **page** and **size** only with **pageable** param. How do I do this?

![image](https://user-images.githubusercontent.com/16001837/78007067-0f4b9680-733e-11ea-8dfb-b3a124fadfbe.png)

**Comment by dilipkrish** [comment]
Interesting, are you using spring data JPA/rest?
