### ISSUE TITLE
Release version for 3.0.0

### ISSUE THREAD

**Issue by mcnealjw63** [springfox/springfox#3278]
Do we have projected release date for 3.0.0 ?   Currently using 3.0.0-SNAPSHOT because it is the only version that will work with SpringBoot 2.2.5.  2.9.2-RELEASE does not work with SpringBoot 2.2.5 and I am getting pushback for using SNAPSHOT versions in production.  IS there a work around to get 2.9.2-RELEASE to work with SpringBoot 2.2.5 ?

**Comment by SledgeHammer01** [comment]
> Do we have projected release date for 3.0.0 ? Currently using 3.0.0-SNAPSHOT because it is the only version that will work with SpringBoot 2.2.5. 2.9.2-RELEASE does not work with SpringBoot 2.2.5 and I am getting pushback for using SNAPSHOT versions in production. IS there a work around to get 2.9.2-RELEASE to work with SpringBoot 2.2.5 ?

I have 2.9.2 working in 2.2.5/2.2.6. 3.0 doesn't work period. It breaks Neo4j for some reason if you can believe that. I know the guy is doing it on his own time and a volunteer, but it looks like he gave up and stopped maintaining. So unfortunately I have to give up too. I was putting off migrating to something else until now because I spent a lot of time tweaking springfox... but... at a certain point... 2.9.2 works for me today, but next week there will be some other issue...

**Comment by dilipkrish** [comment]
I’m sorry folks. I’ve have been working on it, and I was making good progress to release this mid April. Unfortunately I’ve been affected by the covid downturn and now my focus is to get back to work. I do plan to work on this library while I do that, but I can’t promise dates. Thank you for understanding. 

Also if there is anyone in this forum with open engineering opportunities, please consider sending them my way. It will be much appreciated. 🙏🏼

**Comment by SledgeHammer01** [comment]
> I’m sorry folks. I’ve have been working on it, and I was making good progress to release this mid April. Unfortunately I’ve been affected by the covid downturn and now my focus is to get back to work. I do plan to work on this library while I do that, but I can’t promise dates. Thank you for understanding.
> 
> Also if there is anyone in this forum with open engineering opportunities, please consider sending them my way. It will be much appreciated. 🙏🏼

Sorry to hear that :(. And I do apologize if my response was rude. I didnt mean it like that. More of being in a "stuck" situation. Hope you get back to work soon, that is #1.

**Comment by yuecels** [comment]
I just wanted to know if there is any new information about the release date?

**Comment by pcornelissen** [comment]
*nudge* *nudge*

**Comment by dilipkrish** [comment]
Plan to release it tomorrow ... here is the progress report #3070
