### ISSUE TITLE
Abstract method leads to model property

### ISSUE THREAD

**Issue by mjuchli** [springfox/springfox#3279]
Version: 2.9.2
Kind: Bug report

I just came across an odd behaviour of springfox with classes (ApiModels) that extend an abstract class: the methods defined in the abstract class (with body) will be shown as properties in the api doc. In my particular case,

Abstract class:
```java
public abstract class PortfolioRequest {
    ...
    public List<String> getInstrumentKeySymbols() {
        return getPositions().stream()
                .map(position -> position.getInstrumentKey().getSymbol())
                .collect(Collectors.toList());
    }
}
```

Child class (being used in the controller, e.g. ApiOperation):
```java
public class PortfolioRiskRequest extends PortfolioRequest {
    @NotEmpty
    @Valid
    private List<Position> positions;
    
    ...
}
```

will result in **instrumentKeySymbols** being listed as a property of the model **PortfolioRequest**, even though it is a method, which doesn't make sense to me.

I was able to resolve this by annotating the method `getInstrumentKeySymbols()` with `@ApiModelProperty(hidden=true)`.

Is this behaviour on purpose?

Thank you and kind regards,
Marc

**Comment by dilipkrish** [comment]
@mjuchli This is expected behavior from Jackson or any other bean serializer. For all intents and purposes that is a getter for a bean and libraries cannot distinguish it as being a method.
