### ISSUE TITLE
How to disable swagger when Junit runs?

### ISSUE THREAD

**Issue by legshort** [springfox/springfox#328]
I have two profiles, default and test, and I use test profile when I run Junit using annotation like @ActiveProfiles("test").

so, I was wondering how I disable swagger building when test runs?
because swagger takes some of time so that total testing time increased.

Thanks

**Comment by srss-raju** [comment]
Thanks dude.. u saved my day........ thank u so much.. 
Adding @Profile("local","dev","qa")
worked for me
