### ISSUE TITLE
What is the alternative for @ApiIgnore ? Where I don't want to add this annotation to 50 controllers from 15 different packages ?

### ISSUE THREAD

**Issue by SubinrajS0493** [springfox/springfox#3280]
What is the alternative for @ApiIgnore ? Where I don't want to add this annotation to 50 controllers from 15 different packages ?

 - [x] Question. Is this a question about how to do a certain thing?

**Comment by MaksimOrlov** [comment]
Hi, @SubinrajS0493 . 

You can ignore them by setting regex path selector or namespace selector at the Docker class.
