### ISSUE TITLE
Request parameters, lead to an incorrecty generated cURL request 

### ISSUE THREAD

**Issue by marcauberer** [springfox/springfox#3281]
**Version: 2.9.2 (latest)**
**Kind: Bug report**

Hey,
I think I've found a bug in the generation of the curl request, when clicking on 'Try it out'.

I've got following endpoint:
```java
@RequestMapping(method = RequestMethod.GET, path = "/ranking/country", produces = MediaType.APPLICATION_JSON_VALUE)
@ApiOperation(value = "Returns a ranking of the top countries with the most sensors")
public List<RankingItemCountry> getRankingByCountry(
        @RequestParam(defaultValue = "10") int items
) throws RankingDataException {
    if(items < 1) throw new RankingDataException(ErrorCodeUtils.INVALID_ITEMS_NUMBER);
    return sensorRepository.getRankingByCountry(items);
}
```

On the UI page it looks like this:
![Capture](https://user-images.githubusercontent.com/59527509/78948547-0c347100-7ac9-11ea-94e3-0199c7a05807.PNG)

Look at the generated curl request. It is wrong isn't it?
The expected request should look like this:
`https://<api-url>.com/ranking/city?items=2`

This results in a 404 response code.
I would appreciate, if it can be fixed.
Thanks for your awesome implementation!

Marc

**Comment by MaksimOrlov** [comment]
Hi, @marcauberer . It look like, that you turned on "urlTemplating" feature.

**Comment by marcauberer** [comment]
Hi,
you're right. If I disable it, the request url is generated correctly.
Just for education purposes: What is the "urlTemplating" setting doing?

**Comment by MaksimOrlov** [comment]
If you have two `@RequestMappings` with **same** url but **different** `@RequestParam`, with enabled `urlTempkating` SpringFox will generate two endpoints. Otherwise only one,the second mapping will be lost. But unfortunately, Swagger-UI doesn't support that feature. So, it won't be able to generate correct curl request.

More about feature https://tools.ietf.org/html/rfc6570

**Comment by marcauberer** [comment]
Ok, thank you! I already wondered, why I added this to my Docket ...
I also need to apply your behaviour of having two seperate endpoints with different `@RequestParam`.
Can I somehow achieve both things together?

**Comment by MaksimOrlov** [comment]
I think, you can declare two `Docker` beans, one with enabled _url templating_ and other one with disabled. Then by setting appropriate _path selector_ for each `Docker`, you can distinguish controllers, which you want add to `Docker` with enabled feature.

**Comment by marcauberer** [comment]
Can I also distinguish by mapping and not only by the controller?

**Comment by marcauberer** [comment]
I have two mappings with the same parameters. One returns the values in a normal way and the other mapping converts the result to a dto.

**Comment by MaksimOrlov** [comment]
Yes,  you can also distinguish by mapping.

**Comment by dilipkrish** [comment]
Im guessing this is answered. Closing this issue.

**Comment by studeyang** [comment]
add `@ApiImplicitParam` may solve your problem, like this:
````java
@RequestMapping(method = RequestMethod.GET, path = "/ranking/country", produces = MediaType.APPLICATION_JSON_VALUE)
@ApiImplicitParam(name = "items", value = "items", dataType = "int", paramType = "param")
@ApiOperation(value = "Returns a ranking of the top countries with the most sensors")
public List<RankingItemCountry> getRankingByCountry(
        @RequestParam(defaultValue = "10") int items
) throws RankingDataException {
    if(items < 1) throw new RankingDataException(ErrorCodeUtils.INVALID_ITEMS_NUMBER);
    return sensorRepository.getRankingByCountry(items);
}
````
