### ISSUE TITLE
@dilipkrish我正在使用2.9.2版，仍然面临相同的问题。

### ISSUE THREAD

**Issue by STZG19991208** [springfox/springfox#3283]
@dilipkrish我正在使用2.9.2版，仍然面临相同的问题。
@dilipkrish I am using version 2.8.0 and still facing same issue. 
_Originally posted by @STZG19991208 in https://github.com/springfox/springfox/issues/388#issuecomment-612925981_

**Comment by dilipkrish** [comment]
Could you translate please?

**Comment by dilipkrish** [comment]
Closing this as duplicate of #1575

**Comment by dilipkrish** [comment]
1.
