### ISSUE TITLE
error code 404 on /swagger-ui.html, non spring boot app

### ISSUE THREAD

**Issue by sam1502** [springfox/springfox#3285]
Application is a non-boot app, I've tried almost all the possible solutions present on here but none of them seemed to work,

spring-boot-version: 2.1.6.RELEASE
spring-webmvc : 5.1.8.RELEASE
springfox-swagger2 : 2.9.2
springfox-swagger-ui : 2.9.2

the server starts but when I try /swagger-ui.html or api-docs it returns a 404. Other api(s) are working perfectly fine.

`@EnableWebMvc
@EnableSwagger2
@Configuration
public class SwaggerConfig extends WebMvcConfigurerAdapter {

	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any()).build();
	}

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("swagger-ui.html")
				.addResourceLocations("classpath:/META-INF/resources/swagger-ui.html");
		registry.addResourceHandler("/webjars/**")
				.addResourceLocations("classpath:/META-INF/resources/webjars/");

		super.addResourceHandlers(registry);
	}
}
`

let me know if you need anything else. Please help

**Comment by sam1502** [comment]
I added 
`<servlet-mapping>
		<servlet-name>default</servlet-name>
		<url-pattern>/swagger-ui.html</url-pattern>
	</servlet-mapping>
`


to my web.xml and now I see an empty page, while inspecting I saw an error in console which is:


`Loading failed for the <script> with source “http://localhost:9095/mobile/webjars/springfox-swagger-ui/swagger-ui-bundle.js?v=2.9.2”.`

any idea or any suggestions on the same?

**Comment by oodmi** [comment]
Ok, just delete @EnableWebMvc  from your configuration classes.
I can explain why, if you need.

**Comment by oodmi** [comment]
> I added
> `<servlet-mapping> <servlet-name>default</servlet-name> <url-pattern>/swagger-ui.html</url-pattern> </servlet-mapping> `
> 
> to my web.xml and now I see an empty page, while inspecting I saw an error in console which is:
> 
> `Loading failed for the <script> with source “http://localhost:9095/mobile/webjars/springfox-swagger-ui/swagger-ui-bundle.js?v=2.9.2”.`
> 
> It's not giving 404 anymore. The ui page is empty. Any idea or any suggestions on the same?

And delete this

@Override
public void addResourceHandlers(ResourceHandlerRegistry registry) {
	registry.addResourceHandler("swagger-ui.html")
			.addResourceLocations("classpath:/META-INF/resources/swagger-ui.html");
	registry.addResourceHandler("/webjars/**")
			.addResourceLocations("classpath:/META-INF/resources/webjars/");

	super.addResourceHandlers(registry);
}
and 
extends WebMvcConfigurerAdapter

**Comment by dilipkrish** [comment]
This should be fixed in 3.0.0. the new url in 3.0.0 is  `/swagger-ui/index.html` or `/swagger-ui/` rather than `/swagger-ui.html`

**Comment by kvndkm** [comment]
Hello, I am seeing the same error 404 on swagger end point. My application non-spring boot app (Using Spring 5.3.6 web application).

I am able to access /v2/api-docs but when I try /swagger-ui/ or /swagger-ui/index.html, I am seeing 404 not found error. Your suggestion on what I am doing wrong here, is much appreciated

POM 
<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>3.0.0</version>
        </dependency>
Spring services XML

    <bean id="saSwaggerConfig"
          class="com.silverrailtech.ui.configuration.SASwaggerConfig">
    </bean>

Swagger Config class
@EnableSwagger2
public class SASwaggerConfig implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.
                addResourceHandler("/swagger-ui/**")
                .addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("**/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }

    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        registry.addViewController("/swagger-ui/")
                .setViewName("forward:" + "/swagger-ui/index.html");
    }
}

**Comment by pablohdzvizcarra** [comment]
> This should be fixed in 3.0.0. the new url in 3.0.0 is `/swagger-ui/index.html` or `/swagger-ui/` rather than `/swagger-ui.html`

oooooo men you are save my life thank
