### ISSUE TITLE
@ExampleProperty not working properly with redoc

### ISSUE THREAD

**Issue by LishaZ** [springfox/springfox#3286]
springfox version: 3.0.0-SNAPSHOT

I want to manually specify a json for my example response. My code is 
```
@ApiResponses({
        @ApiResponse(code = 200, message = "",
            examples = @Example(value =
                {
                    @ExampleProperty(
                        mediaType = "application/json",
                        value = "{\n" +
                            "  \"resourceType\": \"Parameters\",\n" +
                            "  \"parameter\": [\n" +
                            "    {\n" +
                            "      \"name\": \"basis-of-calculation\",\n" +
                            "      \"valueString\": \"projected\"\n" +
                            "    }\n" +
                            "  ]\n" +
                            "}")
                }
            ))
    })
```

It is working well in swagger UI:
![image](https://user-images.githubusercontent.com/53823962/79375802-1fc05b80-7f51-11ea-9b58-18877da30dbb.png)

However in redoc the input is just read as a string rather than parsed correctly as json:
![image](https://user-images.githubusercontent.com/53823962/79375334-5ba6f100-7f50-11ea-90ed-b14fcf177a1e.png)

Do you know why this would be the case?

**Comment by dilipkrish** [comment]
Not really sure as I dont know much about redoc
