### ISSUE TITLE
Disable enumerative behavior for name collisions across controllers

### ISSUE THREAD

**Issue by silentsnooc** [springfox/springfox#3288]
After a month I still got no answer on stackoverflow which is why I'd like to ask the same question here.

I am generating code for my Angular Clients using Springfox.

One of my controllers `MenuCardController` has a method `getAll()` which looks as follows:

```java
@RequestMapping(value = CONTROLLER_ROOT + "/menu-cards", method = RequestMethod.GET)
@PageableAsQueryParam
public Page<MenuCard> getAll(
        @PathVariable(name = "businessId") Long businessId,
        @Parameter(hidden = true) Pageable pageable
) {
    return this.menuCardService.getAll(businessId, pageable);
}
```

However, the generated code looks like this:

```typescript
getAll1(businessId: number, page?: number, size?: number, sort?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<PageMenuCard>;
getAll1(businessId: number, page?: number, size?: number, sort?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageMenuCard>>;
getAll1(businessId: number, page?: number, size?: number, sort?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageMenuCard>>;
``` 

This is essentially correct but for some reason there is a `1` appended to the name. This controller does not have any other method which is called `getAll`.

Looking at other generated code I got:

```typescript
getAll3(businessId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<PaymentMethodModel>>;
getAll3(businessId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PaymentMethodModel>>>;
getAll3(businessId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PaymentMethodModel>>>;
```

So the question is whether it is possible to turn this behavior off. It seems that e.g. `getAll` gets "reserved" globally for the entire API and not just for one `<name>ControllerService` object.

Here is the [link](https://stackoverflow.com/questions/60467692/disable-enumerative-behavior-for-name-collisions-across-controllers) to the similar stackoverflow question.

Thank you for any help on this.

**Comment by MaksimOrlov** [comment]
Hi, @silentsnooc. Did you try turning off  "urlTemplating" feature.

**Comment by silentsnooc** [comment]
@MaksimOrlov Hi!

From what I see, `urlTemplating` seems to take care of the use of path variables e.g. `/users/{userId}`. Since I make use of such templates I am not sure if I should turn this off?

**Comment by MaksimOrlov** [comment]
The other side of that feature is distinguish controllers with same url address by adding digits in the end.
