### ISSUE TITLE
swagger-ui.min.js and jquery1.8.0.min.js fail to load on AWS Lambda using Sprint Boot 2

### ISSUE THREAD

**Issue by thomashoef** [springfox/springfox#3289]
## Version
2.6.1

## Problem
I have deployed spring boot 2 lambda function on AWS using the aws serverless container and added auto swagger generation and swagger ui to the project. Locally, the swagger-ui.html is correctly generated and populated. Remotely, on AWS the content of /v2/api-docs is perfectly fine, but the swagger-ui.html file renders blank (without the content of my API).

I have noticed that there is an HTTP 502 error on serving 
api-url/webjars/springfox-swagger-ui/swagger-ui.min.js, the same goes for jquery. 

## Expected
I would expect the swagger-ui file to render just as it does locally, what could be the cause of this?

**Comment by thomashoef** [comment]
Update:

After upgrading to 2.9.1, even more resources are not accessible:

![image](https://user-images.githubusercontent.com/28622050/79869021-13208500-83e1-11ea-87e8-925f55437991.png)

This is my whitelist:

    private static final String[] AUTH_WHITELIST = {
            // -- swagger ui
            "/swagger-resources/**",
            "/swagger-ui.html",
            "/v2/api-docs",
            "/webjars/**"
    };

Thanks
Thomas

**Comment by dilipkrish** [comment]
This should be fixed in 3.0.0
