### ISSUE TITLE
CORS problem and possibility to generate JSON spec in java app

### ISSUE THREAD

**Issue by noittom** [springfox/springfox#3292]
Hi,
I am using springfox 2.9.2 it all works fine and I get the spec in /v2/api-docs
but then when I try to feed it into swagger-ui I got 
Possible cross-origin (CORS) issue
(hosted on different server).
I tired everything I could google (setting up CorsFilter, registry,allowOrigin(*) etc) - it does not work.

so is thee a way that I programatically jet the Json ?
i.e. smth OpenApi has OpenAPI o = ...; Json.pretty(o);

**Comment by dilipkrish** [comment]
Not sure about this. You'd have to setup a cors filter in your service application that tells swagger-ui its ok to access origin.
