### ISSUE TITLE
Cannot Define Interface Schema for Swagger UI

### ISSUE THREAD

**Issue by JasonSmiley** [springfox/springfox#3293]
Here is my interface java class:
```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        property = "type")
@JsonSubTypes(value = {
        @JsonSubTypes.Type(value = impl1.class, name = "IMPL_1"),
        @JsonSubTypes.Type(value = impl2.class, name = "IMPL_2"),
        @JsonSubTypes.Type(value = impl3.class, name = "IMPL_3"),
})
public interface InterfaceClass {
}
```
Here is my Request Java Class:

```
public class IncomingRequest {
   private String name;
   private InterfaceClass content;

  //getters and setters
}
```

When I look at my Controller (which takes IncomingRequest.java as a request body), I see this:

```
{
   "name" : "String",
   "content" : {} 
}
```

I tried using `@Schema` from maven dependency below with `anyOf()` filled with all my implementation classes but I cannot get the Swagger API to pick up the Model Schemas.

```
<dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.0.9</version>
        </dependency>
```

Please help!

**Comment by MaksimOrlov** [comment]
Hi, @JasonSmiley.

As I understand, you are trying to use annotations from OAS 3.0. that is not currently supported. 
For now release witch will support them is under work and will be releases in a few weeks.

I think that is related question https://github.com/springfox/springfox/issues/2457

**Comment by JasonSmiley** [comment]
@MaksimOrlov yes, it is trying to do the same thing as me, but, it seems like it's not working even using only Jackson Annotations - as you can see in my code I am also using Jackson Annotations but it doesn't seem to help
