### ISSUE TITLE
[Question] How to fully disable/Not compile swagger into production jar ?

### ISSUE THREAD

**Issue by Alceatraz** [springfox/springfox#3294]
I already read the doc and search the answer, None of them can figure out his question.

I mean total disable, even "swagger.enable=false" will register a controller

I try the scope (Im using maven). Of couse that won't work beacause the code still there, Thay will make compile error.

Is there any way to avoid swagger compile into production jar ?

**Comment by trongcauhcmus** [comment]
i think using spring profile gonna work with your request
more detail: https://www.baeldung.com/spring-profiles

**Comment by dilipkrish** [comment]
The only way to do that is to pre-generate the specification and serve it up as a resource
