### ISSUE TITLE
merge documents in gateway, basePath  is wrong. 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by dodolook8716** [springfox/springfox#3295]
Sorry, I don't speak English, I used google translation.
I tried to merge documents in gateway, the basePath of webmvc is correct, but it is wrong in webflux. I think the cause of the error is in Swagger2ControllerWebFlux.

![图片](https://user-images.githubusercontent.com/34698754/80301804-d1c11880-87d8-11ea-92a2-83ef01ed5282.png)

![图片](https://user-images.githubusercontent.com/34698754/80301775-b229f000-87d8-11ea-984d-ca1430d450a3.png)

![图片](https://user-images.githubusercontent.com/34698754/80301891-4c8a3380-87d9-11ea-969b-d1cb5563a4df.png)

**Comment by dilipkrish** [comment]
Webflux doesn't have a concept of context-path. Not sure how to fix it

**Comment by dilipkrish** [comment]
Added [extensibility mechanisms](http://springfox.github.io/springfox/docs/snapshot/#plugins-available-for-extensibility) to override this behavior, specifically the ones for swagger 2.0 and open api 3.0
