### ISSUE TITLE
Question: how to specify which security scheme from securify definations to apply to given endpoint??

### ISSUE THREAD

**Issue by simple-value-dev** [springfox/springfox#3296]
I am unable to figure out how to apply given security scheme from securify definations to apply to given endpoint.
I could do the same manually in the apidoc json.
I am new to springfox and  swagger please guide me...:)

**Comment by dilipkrish** [comment]
Please read  [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)?
