### ISSUE TITLE
Response Model with Map can not be showed the details in response

### ISSUE THREAD

**Issue by dianfenzhan** [springfox/springfox#3297]
Hi my response model is generic and has a column  'errorInfo' which type is Map,then swagger can not show the response details,If i change the type from Map to other type (String or other Class),then it works.(swagger.version=2.9.2,springboot.version=2.2.4.RELEASE)
```java
@Data
@NoArgsConstructor
@ApiModel("Standard response model")
public class ApiResult<T> implements Serializable {

    @ApiModelProperty(value = "success or fail")
    private Boolean success;

    @ApiModelProperty(value = "result status", reference = "IResultMsg", required = true)
    private Integer status;

    @ApiModelProperty(value = "result message", required = true)
    private String message;

    @ApiModelProperty(value = "response data")
    private T data;

    @ApiModelProperty(value = "error info")
    private Map errorInfo;

    @ApiModelProperty(value = "error message")
    private String errorMessage;
```

![21588064974_ pic](https://user-images.githubusercontent.com/34612707/80469782-a7f02900-8973-11ea-9767-bfc4013ecf06.jpg)
![31588065022_ pic](https://user-images.githubusercontent.com/34612707/80469800-ac1c4680-8973-11ea-8e63-77e812e52661.jpg)

**Comment by dilipkrish** [comment]
This should be fixed in the latest 3.0.0 version releasing shortly
