### ISSUE TITLE
Bad interaction between springfox and openapi codegen

### ISSUE THREAD

**Issue by Anonymous-Coward** [springfox/springfox#3299]
Versions which I believe are relevant:
springfox and springfox-ui 2.9.2.
openapi-generator-maven-plugin 4.2.3

I can't decide whether this is a feature request or a bug. I tend towards bug, however.

It's trivial to explain, but I don't have a simple, minimalistic project to demo it yet - will add one.

Here's what happens:
For each tag in an openapi spec, openapi-codegen generates an interface onto which it puts all swagger annotations. Then it generates a controller implementing that interface, on which it only puts a `@RequestMapping` annotation.

The generated controller does not contain any method implementations. The interface defines a delegate and default implementations deferring to the delegate, so the controller just implements the interface and a constructor taking a delegate.

Now, when springfox generates the api documentation, it correctly generates a tag and endpoints for the annotations on the interface, but then also generates a tag with no endpoints underneath for the controller name transformed from camel-case to dash-separated words.

Now, this, in effect, means that springfox generates duplication - it documents both the interface and the controller implementing it. It only generates endpoint documentation for what's in the interface, and not for what's in the controller.

I searched the docs, and couldn't find a way to avoid this. What should I do about it?

**Comment by Anonymous-Coward** [comment]
[bug-demo.tar.gz](https://github.com/springfox/springfox/files/4570512/bug-demo.tar.gz)

The attached archive contains the source code, the api spec and the pom file for a maven-built Java project which demo-es the bug.

Download, cd to where you downloaded it, then:

```
tar -zxvf bug-demo.tar.gz
mvn clean install
cd target
java -jar springfox-0.0.1-SNAPSHOT-exec.jar
```
Then open [the swagger UI](http://localhost:8080/swagger-ui.html) in a browser. Although the interface has the `@Api` annotation, and the controller implements it, a tag based on the controller name is still generated for the controller. Thus, you have a tag `example-api-controller` with no paths and a path `example` for tag `example` in the [swagger api def](http://localhost:8080/v2/api-docs) - accessible while the app is running.

**Comment by dbinkele** [comment]
I can conform having the same issue when putting together springfox and openapi codegen.

**Comment by dilipkrish** [comment]
Is this an open api codegen issue. On a side note, the tag generation behavior has been fixed o no generate the default tags.

**Comment by dilipkrish** [comment]
@Anonymous-Coward and @dbinkele would you be able to provide feedback on the latest 3.0.0-SNAPSHOT in combination with `OAS_30` documentation type and how that works as regards this.

**Comment by Anonymous-Coward** [comment]
@dilipkrish Can you give a concise and simple instruction on how to update the test project I attached above to use the latest snapshot? Either that, or you can download and test yourself, after having upgraded the springofx dependencies - it's really the simplest thing I can think of that reproduces the error.

**Comment by dilipkrish** [comment]
Ok here is what I found

in your app... replace your pom that has this current

```xml
		<!-- https://mvnrepository.com/artifact/io.springfox/springfox-swagger2 -->
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui -->
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/io.swagger/swagger-annotations -->
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>1.6.1</version>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>20.0</version>
			<exclusions>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

with 

```xml
		<!-- https://mvnrepository.com/artifact/io.springfox/springfox-swagger2 -->
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/io.swagger/swagger-annotations -->
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>1.6.1</version>
		</dependency>
```

... to upgrade your project. Optionally you could use the auto configuration. So you could do the following (in which case you dont need this configuration bean)

```java

@Configuration
//@EnableSwagger2 <-- comment this
public class SpringFoxConfiguration {

/** Comment this as you wouldn't need  to specifically configure this, unless you want o use SWAGGER_2. Auto configuration produces OAS_30 Spec by default.
	@Bean
	public Docket api() { 
		return new Docket(DocumentationType.SWAGGER_2) 
				.select()
				.apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any())
				.build();
	}
*/	
}
```

lastly, codegen generates the following which is incorrect

It should generate the following to generate the right tags

```java
@Api(value = "example", tags="example", description = "the example API")
public interface ExampleApi {
...
}
```

**Comment by Akhlys** [comment]
As this comes up as the first relevant site in google to this problem, I'll add a workaround.
I know it's a codegen issue, but it may help people, so I hope you'll not mind

In the generated XApi.java classes, change the `@Api` to include the tags, E.g. with the petstore sample, change
`@Api(value = "pet", description = "the pet API")`
to
`@Api(value = "pet", description = "the pet API", tags={"pet"})`

See: https://stackoverflow.com/questions/50229661/how-to-remove-controller-list-from-swagger-ui
Manual edit of generated code is never fun, but what can you do
