### ISSUE TITLE
502 bad gateway when deploying to AWS, works locally.

### ISSUE THREAD

**Issue by AliZarrouk** [springfox/springfox#3300]
Im using 2.9.2 version of the springfox-swagger-ui and springfox-swagger2.

I added a dist of swagger to do some customisation, replaced the petstore parts with `window.location.origin + "/v2/api-docs"` in a variable in the JS files (not the map files). It works fine locally but when deployed on AWS I have this unable to infer base url error.

Anyone knows what the issue is about ?

<img width="1137" alt="Screenshot 2020-05-04 at 17 46 46" src="https://user-images.githubusercontent.com/5500253/80992432-d0779780-8e39-11ea-9d7b-25a5c916a943.png">

**Comment by AliZarrouk** [comment]
I know have the base URL set with
`var swaggerUrl = window.location.origin + "/v2/api-docs"
      const ui = SwaggerUIBundle({
        url: swaggerUrl,
`
Same in other js files with things like 
`var swaggerUrl = window.location.origin + "/v2/api-docs"; return Object(r.parseYamlConfig)('---\nurl: "' + swaggerUrl +'
` and now I have a 502 when trying to browse the swagger-ui.html.

Any help ?

**Comment by dilipkrish** [comment]
@AliZarrouk This should be fixed in the upcoming 3.0.0 snapshot. Note the change in location for the `/swagger-ui.html`. it will now be available @ `/swagger-ui/[index.html]` (optional index.html)
