### ISSUE TITLE
Dynamic @ApiImplicitParam(allowableValues) using XBuilderPlugin

### ISSUE THREAD

**Issue by villamx** [springfox/springfox#3305]
I've created query-parameter allowed values using Enum and the Model validation is validated with Hibernate Bean Validator, so the dynamic part missing; if any change in Enum allowed values is not automatically reflected in the documentation (runtime).

- Springfox Swagger2 2.9.2

I found out that there was a request before to support this feature "Dynamic @ApiParam(allowableValues) [#1877](https://github.com/springfox/springfox/issues/1877)"

I've exhausted the suggestions on the #1877 but I could not find a way to reach the annotation (@ApiImplicitParam) outside the method. _Another thing I discovered is that_ `springfox.documentation.service.Parameter` _is abstracted in the way that it cannot be updated_.

Isolating my use case, I wrote the following code and found that I can use:
`springfox.documentation.builders.ParameterBuilder`.
`springfox.documentation.builders.OperationBuilder#parameters`
![image](https://user-images.githubusercontent.com/3997634/81324653-427ff480-9065-11ea-964a-b24f3e938231.png)

But if the `Parameter`.**name** already exists, in an upgrade attempt (_perhaps to avoid duplication_) the entire annotation is discarded (_not merged_).
`springfox.documentation.builders.ParameterMerger#merged()`
![image](https://user-images.githubusercontent.com/3997634/81322930-a654ee00-9062-11ea-80fb-1a3307d2c006.png)

![image](https://user-images.githubusercontent.com/3997634/81322385-e8316480-9061-11ea-96e8-bc95b7611b6d.png)

So far, the only possible way to get my use case working is to use an existing annotation as a reference, and then use ParameterBuilder to create the elements with `allowable` "dynamic" values to document my query-parameters.
Please let me know if I'm on the right way, I don't find it too obvious since I had to review the code and use code snippets, thank you in advance.

**Comment by dilipkrish** [comment]
This should no longer be an issue. Can you confirm with the latest 3.0.0 SNAPSHOT?
