### ISSUE TITLE
Error creating bean with name 'docRepository'

### ISSUE THREAD

**Issue by sivasudharsh** [springfox/springfox#3306]
I am getting the below mentioned exception in my java program.

Error creating bean with name 'docRepository' , invocation of init method failed;nested exception is java.lang.NoSuchMethodError : org.springframework.transaction.interceptor.TransactionInterceptor.setTransactionManagerBeanName()Ljava/lang/String;)V

spring config : 
`<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:solr="http://www.springframework.org/schema/data/solr"
    xmlns:context="http://www.springframework.org/schema/context"
    xsi:schemaLocation="http://www.springframework.org/schema/data/solr 
    http://www.springframework.org/schema/data/solr/spring-solr.xsd 
    http://www.springframework.org/schema/beans  
    http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
    http://www.springframework.org/schema/context 
    http://www.springframework.org/schema/context/spring-context-4.0.xsd">`

**Comment by dilipkrish** [comment]
This doesn't seem like its related to springfox. Closing this, please reopen if its a problem with additional details
