### ISSUE TITLE
cannot work with newest version of Spring Data Rest

### ISSUE THREAD

**Issue by semonw** [springfox/springfox#3312]
When I am  using Spring Data Rest with springfox swagger-ui 2.9.2,  my application cannot start because of the dependency conflict.  

I did some digging and found out the reason is 

swagger-ui 2.9.2  ------depend on ---> spring plugin core 1.2.0-release
spring data rest ---depend on ---> spring plug core 2.0.0 release.

and this issue cannot be sovled by Gradle "exclude". 

In my opinion, the only way to solve this is to upgrade dependent jar version. 

LOGS:

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    springfox.documentation.spring.web.plugins.DocumentationPluginsManager.createContextBuilder(DocumentationPluginsManager.java:152)

The following method did not exist:

    org.springframework.plugin.core.PluginRegistry.getPluginFor(Ljava/lang/Object;Lorg/springframework/plugin/core/Plugin;)Lorg/springframework/plugin/core/Plugin;

The method's class, org.springframework.plugin.core.PluginRegistry, is available from the following locations:

    jar:file:/C:/.gradle/caches/modules-2/files-2.1/org.springframework.plugin/spring-plugin-core/2.0.0.RELEASE/95fc8c13037630f4aba9c51141f535becec00fe6/spring-plugin-core-2.0.0.RELEASE.jar!/org/springframework/plugin/core/PluginRegistry.class

It was loaded from the following location:

    file:/C:/.gradle/caches/modules-2/files-2.1/org.springframework.plugin/spring-plugin-core/2.0.0.RELEASE/95fc8c13037630f4aba9c51141f535becec00fe6/**spring-plugin-core-2.0.0.RELEASE.jar**

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.plugin.core.PluginRegistry

**Comment by MaksimOrlov** [comment]
@semonw, you should exclude `spring plugin core` *1.2.0-release* and add dependency to `spring plugin core` *2.0.0.RELEASE*

**Comment by weihmannj** [comment]
> @semonw, you should exclude `spring plugin core` _1.2.0-release_ and add dependency to `spring plugin core` _2.0.0.RELEASE_

DocumentationPluginsManager#resourceGroupingStrategy calls PluginRegistry#getPluginFor which does not exist in version 2.0.0.RELEASE.

**Comment by dilipkrish** [comment]
The resourceGroupingStrategy API has been removed and the plugin dependency has been upgraded.
