### ISSUE TITLE
Adding dependency on firefox to project 'removes' hal like json properties

### ISSUE THREAD

**Issue by basven** [springfox/springfox#3313]
I am using spring boot 2.2.4.RELEASE and spring-boot-starter-hateoas
My rest is producing application/hal+json.
It correctly creates json like:
`{
    "_embedded": {
        "films": [
            {
                "lang": "English",
                "title": "RULES HUMAN",
                "description": "A Beautiful Epistle of a Astronaut And a Student who must Confront a Monkey in An Abandoned Fun House",
                "rentalRate": 4.99,
                "rentalDuration": 6,
                "length": 153,
                "releaseYear": "2006",
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/api/films/com.asimio.demo.domain.Film@50aa1d5f"
                    }
                },
                "id": 749
            },
            {
`

After adding dependencies on spring fox 2.9.2 the json that gets generated no longer conforms to hal:

`{
    "links": [
        {
            "rel": "parent",
            "href": "http://localhost:8080/api/actors/com.asimio.demo.domain.Actor@4c1622d3"
        },
        {
            "rel": "self",
            "href": "http://localhost:8080/api/actors/com.asimio.demo.domain.Actor@4c1622d3/films"
        }
    ],
    "content": [
        {
            "lang": "English",
            "title": "ANACONDA CONFESSIONS",
            "description": "A Lacklusture Display of a Dentist And a Dentist who must Fight a Girl in Australia",
            "rentalRate": 0.99,
            "rentalDuration": 3,
            "length": 92,
            "releaseYear": "2006",
            "links": [
                {
                    "rel": "self",
                    "href": "http://localhost:8080/api/films/com.asimio.demo.domain.Film@4b16b9a0"
                }
            ],
            "id": 23
        },
`
Note how the __links and _embedded json properties are no longer present.

There is another issue reported here that seems to indicate that spring fox doesn't work nice with spring's hateos. Is there a workaround for this issue?

**Comment by MaksimOrlov** [comment]
Hi, @basven. Could you try 3.0.0-SNAPSHOT version, would behavior be the same?

**Comment by basven** [comment]
Works like a dream; any idea on the ETA for that ?

**Comment by MaksimOrlov** [comment]
@basven, there is a lot of [work]( https://github.com/springfox/springfox/tree/feature/2022/oas-3-support-experiment1) have already done. We are trying to force release version in the next few weeks.

**Comment by basven** [comment]
Good news, I will close this issue then since it is addressed in 3.0

**Comment by basven** [comment]
I pulled in the *released* version of 3.0 and the problem described above resurfaced.  This is now with spring boot version 2.3.0.RELEASE (originally was with 2.2.4)

**Comment by dilipkrish** [comment]
It seems to be working [fine here](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/test/resources/contract/swagger2/declaration-spring-data-rest.json) in the tests. It might be something environmental, if you can replicate it wth a fork of the [the demos](https://github.com/springfox/springfox-demos) project that would be helpful to fix
