### ISSUE TITLE
ApiInfo in Docket will not contain old value if parameter is null.

### ISSUE THREAD

**Issue by Snap252** [springfox/springfox#3314]
The implementation of `apiInfo` fluent Interface in `springfox.documentation.spring.web.plugins.Docket` is not consistent to other methods like `groupName` or `host` - the old value will not be kept due to a missing `this` qualifier in 2nd parameter:

https://github.com/springfox/springfox/blob/c651680a9f377b4d3e225785af79fdb5987fc5fd/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L127

see:
https://github.com/springfox/springfox/blob/c651680a9f377b4d3e225785af79fdb5987fc5fd/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L163

https://github.com/springfox/springfox/blob/c651680a9f377b4d3e225785af79fdb5987fc5fd/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L238

**Comment by dilipkrish** [comment]
Thank you for reporting. This should be fixed!
