### ISSUE TITLE
Multi-module microservice spring boot swagger introduction

### ISSUE THREAD

**Issue by mickey4u** [springfox/springfox#3316]
I have a multi-module spring-boot project and I want to configure a project wide swagger documentation. What I have done now is to create another module where I have the swagger configurations setup. However, this doesn't work. Is the way to achieve this or it is just not possible.

**Comment by ayounsi** [comment]
Did you import the swagger configuration into the Spring Boot application ?

Because by default, Spring Boot will auto scan for components in the current package (containing the @SpringBoot main class) and its sub packages, so check if your configuration will be discovered by default otherwise do it mannually.

**Comment by mickey4u** [comment]
@ayounsi  This what I have. I think the SpringBootApplication handles component scanning or? 
```
@SpringBootApplication
public class BackendDocumentation {
    public static void main(String[] args) {
        SpringApplication.run(BackendDocumentation.class, args);
    }
}
```

```
@Configuration
@EnableSwagger2
public class SwaggerConfiguration {
    @Bean
    public Docket api(){
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.regex("/api.*"))
                .build();
    }

    private ApiInfo  apiInfo(){
        return new ApiInfoBuilder().title("Research Backend API")
                .build();
    }
}
```

**Comment by ayounsi** [comment]
@mickey4u It depends on the hierarchy of your package. Your Swagger Configuration class must be at the same level as your Backend Documentation class or in one of its sub-package.

You can try add @Import({ SwaggerConfiguration.class }) on your BackendDocumentation class.

**Comment by mickey4u** [comment]
@ayounsi I don't think there is any annotation like Import for component scanning; did you mean @ComponentScan.  The problem is it at the moment it only works when swagger is placed in one of the modules. However, what I want to achieve is a single swagger configuration that documents all the microservices.

**Comment by ayounsi** [comment]
@mickey4u did you try the import ?

The annotation import is used to aggregate multiples configuration files : 
https://docs.spring.io/spring-javaconfig/docs/1.0.0.M4/reference/html/ch04s03.html

**Comment by mickey4u** [comment]
@ayounsi I have seen what you meant but the project is multi-module so basically you have independent projects within their respective directories. For example
```
ParentProject
   --Microservice1
        --MicroserviceController
   --Microservice2
        --Microservice2Controller
   --Microservice3
        --Microservice3Controller
```

Is it possible to have a unified swagger documentation. Swagger documentation at the moment works when I do it for a single microservice.

**Comment by ayounsi** [comment]
@mickey4u your micro services are deployed separately ? so you want to deploy a only one swagger instance that documents all your web services ?

**Comment by mickey4u** [comment]
@ayounsi Yes, sorry if that wasn't clear in the question.

**Comment by ayounsi** [comment]
@mickey4u In my opinion, you can either have a Swagger module that avoids code duplication and share it with all micro service but in this case you will have a swagger ui for each service ! Or adding to that you can deploy an instance that will aggregates them into a single UI : 
https://dzone.com/articles/centralized-documentation-in-microservice-spring-b
I hope that will help you

**Comment by dilipkrish** [comment]
@mickey4u This issue should give you [some guidance](https://github.com/springfox/springfox/issues/1954). @ayounsi thanks for helping out! Much appreciated 🤘

**Comment by BLemine** [comment]
You can do : 

`
@Configuration
@EnableSwagger2
public class SpringFoxConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2).select()
                .apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo());
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder().title("Rest Services")
                .description("Some description")
                .version("1.0")
                .build();
    }

}
`

to include all the controllers.
