### ISSUE TITLE
how can I inject my generated model class into  global Models

### ISSUE THREAD

**Issue by jarvan4dev** [springfox/springfox#3318]
version: 2.9.2

this is my code: https://github.com/jarvan4dev/swagger/blob/master/src/main/java/com/example/swagger/context/JsonParameterReader.java

@dilipkrish 

![image](https://user-images.githubusercontent.com/9948677/82738895-b6acde80-9d6d-11ea-89d7-a7cf50b9766b.png)

**Comment by MaksimOrlov** [comment]
Hi, @jarvan4dev
You can try to implement your own `OperationModelsProviderPlugin`

Or just simply use `additionalModels` method of `Docket` class.

**Comment by jarvan4dev** [comment]
@MaksimOrlov thx, but the model class is generated at runtime

**Comment by MaksimOrlov** [comment]
So, as I understand, you've implemented `OperationBuilderPlugin` to generate at runtime **Operation** listing, same way you can generate models at runtime by implementing `OperationModelsProviderPlugin`.

**Comment by MaksimOrlov** [comment]
Just keep in mind that **Operations** and **models** are generated separately.

**Comment by jarvan4dev** [comment]
@MaksimOrlov I create an annotation `@JsonParam`, the method parameters which are annotated by `@JsonParam` will be used to create a Model class (by javassist) at runtime. if I implement `OperationModelsProviderPlugin`, this custom plugin can not get **all** parameters of controller method in the meantime,  so I can not do that, I'm seeking for another solution.
