### ISSUE TITLE
Hide or filter fields for different requests not using additional DTO models

### ISSUE THREAD

**Issue by splekhanov** [springfox/springfox#3324]
Is that possible to filter (hide) specific fields for different requests using Spring Boot and Springfox Swagger 2.9.2?

**Given:**
I got model "Genres":
```
{
  "id": 0,
  "type": "string"
}
```
And another one "Book" with the first included:
```
{
  "id": 0,
  "genres": [
    {
      "id": 0,
      "type": "string"
    }
  ],
  "isbn": "string",
  "title": "string",
  "author": "string",
  "publishedYear": "string",
  "price": "string",
  "quantity": 0
}
```
**Problematic:**
I want to show ALL fields for the first model "Genres" in Swagger-UI `GET /genres` and "Book" `GET /book{id}`
 but hide `"type": "string"` for "Book" `POST /books` since it's not mandatory and basically duplicate info about book genre.

**Question:**
Is there any possibility to do that? I don't want to use DTO or any separate models to do this, but to my astonishment, it's seems there is no other choice since Swagger developers didn't leave such a possibility.

I tried:
```
@ApiModelProperty(readOnly = true)
private String type;
```
And:
```
@ApiModelProperty(accessMode = ApiModelProperty.AccessMode.READ_ONLY)
private String type;
```
But it didn't help.

@JsonIgnore hides field for every request which is not what I'm looking for:
```
@JsonIgnore
private String type;
```
I viewed [this](https://stackoverflow.com/questions/54595540/springfox-hide-certain-fields-in-swagger-ui-that-arent-required-for-the-call#) and [this](https://stackoverflow.com/questions/53454357/swagger-ui-does-not-hide-readonly-nested-object-from-example-body), but it seems like there is no solution. Do I miss something? Googling this issue I found a lot of people who look for this feature for years :(

**Comment by MaksimOrlov** [comment]
Hi, @splekhanov.

That features has been added to *3.0.0-SNAPSHOT* version.

You can use @JsonView, @JsonProperty, @JsonIgnore, etc...

**Comment by splekhanov** [comment]
> Hi, @splekhanov.
> 
> That features has been added to _3.0.0-SNAPSHOT_ version.
> 
> You can use @JSONVIEW, @JsonProperty, @JsonIgnore, etc...

Thank you! This is exactly what I was looking for!
