### ISSUE TITLE
@Order ignored for plugin ordering

### ISSUE THREAD

**Issue by shederman** [springfox/springfox#3325]
Please take the time to search the repository, if your question has already been asked or answered.

Using 2.9.2

Bug Report: See https://gist.github.com/shederman/b6f7d18fdaca8f42cac4ba04c4c2d549

The Order sequence indicates that the CustomLisingScannerPlugin should run last, and therefore have access via the static the the operations. It does not. It runs first, no matter what ordering is specified. This means it we cannot add custom CORS API Integration methods to the Swagger output (note: we are not using CORS in Spring, we are handling it in API GW, so need to create custom OPTIONS operations, one for each actual operation).

**Comment by dilipkrish** [comment]
Thanks for the detailed issue report. This seems like a bug, tho I dont know why the order aware plugin registry wouldn't kick in.

**Comment by dilipkrish** [comment]
Cant seem to reproduce this issue. The entire plugin system is predicated on this working so Im not sure why its not working
