### ISSUE TITLE
Pageable + JsonView not working on 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by Artheriom** [springfox/springfox#3333]
Hi,

According to other issues, i've heard that Springfox will support JsonView on 3.0.0-SNAPSHOT and upcoming releases. I've tested it, and it greatly works, except for a specific case.

I am using JsonView, with Pageable on Spring REST Controllers. Here is an example :
```java
@RestController
@RequestMapping("/")
public class CapabilityController {
   @Autowired
    private final CapabilityService capabilityService;

    @GetMapping
    @JsonView(CustomJsonView.CapabilityJsonView.class)
    public ResponseEntity<Page<Capability>> getAll(Pageable pageable){
        Page<Capability> capabilities = capabilityService.getAll(pageable);
        return ResponseEntity.ok(capabilities);
    }
```

When I try to start my project, the generated doc about this endpoint is the following : 
```
"Page«Capability»":{"type":"object","title":"Page«Capability»"}
```
As you can see, there is no properties in there. No information about pageable, or my "Capability" structure.

If I remove the `@JsonView` annotation, it works great: springfox gives me structure with pageable and "Capability" structure. But, I'm unable to filter fields to display. :/ 

Did I do something wrong, or still WIP or just a bug ?

My Springfox configuration : 
```java

@Configuration
@EnableSwagger2WebMvc
public class SwaggerConfig implements WebMvcConfigurer {
    @Bean
    public Docket productApi() {

        return new Docket(DocumentationType.SWAGGER_2)
                .host("http://localhost:8080")
                .pathMapping("")
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.test.api.controller"))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiInfo());

    }

    private ApiInfo apiInfo() {
        return new ApiInfo( "REST API", "Provide a REST API.", "0.0.1-SNAPSHOT", "", new Contact("", "", ""), "", "", Collections.emptyList());
    }
}
```

Just a final thought to say you are doing an amazing (and helpful) work with this project; thank you!

**Comment by MaksimOrlov** [comment]
Hi, @Artheriom.
Could you, please, provide source code of the `Capability` class?

Also. did you try property `spring.jackson.mapper.default-view-inclusion=true` ?

**Comment by Artheriom** [comment]
Hello,

I didn't tried `spring.jackson.mapper.default-view-inclusion=true`... It solved my problem, thanks !

FYI, the `Capability` class (which is really basic) :

```java
@Entity
public class Capability {
    @Id
    @NotBlank
    @JsonView(JsonView.MinimalJsonView.class)
    private String id = UUID.randomUUID().toString();

    @NotBlank
    @JsonView(JsonView.MinimalJsonView.class)
    private String name;

    @ManyToOne(cascade = {CascadeType.PERSIST})
    @JsonView(JsonView.CapabilityJsonView.class)
    private CourseOfAction courseOfAction;

    @ManyToMany
    @JoinTable(name="process_capability",
            joinColumns = @JoinColumn(name = "process_id", nullable = false),
            inverseJoinColumns = @JoinColumn(name = "capability_id", nullable = false))
    @JsonView(JsonView.CapabilityJsonView.class)
    private Collection<Process> processes = new HashSet<>();

    public Capability() {
        //Ignored
    }
   
    // Getters & setters here...
```

I'm closing this issue as it is fixed. Thanks again !
