### ISSUE TITLE
GET endpoint with complex object results in booleans for top level class

### ISSUE THREAD

**Issue by dani-t** [springfox/springfox#3334]
I have described the issue on StackOverflow so I will attach the link to it

[https://stackoverflow.com/questions/62473171/generating-spring-api-docs-using-swagger-over-get-endpoints-with-complex-objects](https://stackoverflow.com/questions/62473171/generating-spring-api-docs-using-swagger-over-get-endpoints-with-complex-objects)

Springfox version: 2.9.2

What kind of issue is this?

In a controller, for a GET request, in the parameter list, if I use a nested/complex object then in the documentation, instead of seeing the fields of the complex objects I see only the fields of the first level class, as booleans.

I believe in spring boot 2.2 (I do not recall where I read this) they introduced this feature of using complex objects for mapping request params from query string in the form of `GET .../search?firstLevelField.secondLevelField.thirdLevelField=dog`

**Comment by MaksimOrlov** [comment]
Hi, @dani-t.

Could you, please, provide full source code of your dto's with getters and setters.

Also, did you try annotating controller's parameters with `@ModelAttribute` annotation?

**Comment by dani-t** [comment]
I have found the problem.

In my DTOs I had some getters which return `Optional<Something>`. By adding `.genericModelSubstitutes(Optional.class)` to my swagger config I managed to obtain the configuration I was looking for.

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build()
                .genericModelSubstitutes(Optional.class)  // added this line
                .securityContexts(Lists.newArrayList(securityContext()))
                .securitySchemes(Lists.newArrayList(apiKey()));
    }
