### ISSUE TITLE
Upgrade from 2.9.2 to 2.10.0 causes /swagger-resources to be unavailable

### ISSUE THREAD

**Issue by mikesmithson** [springfox/springfox#3336]
We recently upgraded spring-fox-swagger2 and spring-fox-swagger-ui to 2.10.0 from 2.9.2. We are running SpringBoot version 2.2.8.RELEASE and have changed the annotation on our Swagger config class from @EnableSwagger2  to @EnableSwagger2WebMvc. When starting up our container locally, trying to reaching the swagger endpoint on localhost with path /swagger-ui.html causes every static resource under /swagger-resources to return a 404 when looking at the Network tab in FIrefox. It is unclear to us what the proper configuration should be. Is there documentation about the upgrade path from 2.9.X to 2.10.X? Should it just work out of the box other than changing to the @EnableSwagger2WebMvc annotation?

**Comment by Deviruchi1** [comment]
Did same upgrade today and exactly same problem I am facing.

**Comment by dilipkrish** [comment]
Oh please dont use 2.10... it was an intermediate step so that people who were on 3.0.0-SNAPSHOT can continue using a released version if needed. Please continue 3.0.0-SNAPSHOT.  Thats the version with the OAS support. Its not ready yet, should be available tomorrow 🤞

**Comment by dilipkrish** [comment]
Would love your feedback once 3.0.0-SNAPSHOT build is fixed

**Comment by dilipkrish** [comment]
The [latest snapshot ](https://github.com/springfox/springfox/issues/3070#issuecomment-648578094)has landed with open API 3.0.3 support!

**Comment by jebeaudet** [comment]
We just updated from 2.9.2 to 2.10.5 too. Spring boot application, our swagger endpoint not working anymore. Dug into it a bit to realize `@EnableSwagger2WebMvc` imports `Swagger2DocumentationWebMvcConfiguration` which is conditional on class `springfox.documentation.spring.web.SpringfoxWebMvcConfiguration` but the class name is `springfox.documentation.spring.web.SpringfoxWebConfiguration` so the condition is never matched. Could you fix that?

**Comment by dilipkrish** [comment]
It shouldn't be incorrectly linked for sure. I just released what was in 3.0.0-SNAPSHOT as is. Possibly some issues with that. I can check and see. In the mean while, since you're using spring boot would love your feedback on transitioning to the 3.0.0 from pre open api support. I put up some preliminary instructions on the readme.md

**Comment by mikesmithson** [comment]
I am happy to provide feedback for the 3.0.0-SNAPSHOT. However, I wouldn't expect as a 2.9.X user who upgrades to 2.10.X to be broken.

**Comment by dilipkrish** [comment]
@mikesmithson Definitely agree 💯 . It was released only so as to get people currently using 3.0.0 from seeing stability issues as we approach the release. Perhaps the current release could've been 4.0 and 3.0 would've just been a buggy temporary release.

**Comment by dilipkrish** [comment]
The dependencies should be fixed now. Please give it a whirl and let me know. Also polished/tightened the auto configuration. Would love feedback

**Comment by jebeaudet** [comment]
Are you going to publish a 2.10.6 version?

**Comment by dilipkrish** [comment]
No, Trying to get 3.0.0 out the door. Besides 2.10.6 will look a whole lot different as it has all the Open API 3.x support

**Comment by jakubmalek** [comment]
It seems that [springfox-spring-webmvc](https://github.com/springfox/springfox/tree/2.10.5/springfox-spring-webmvc) artifact dependency is missing where required [SpringfoxWebMvcConfiguration](https://github.com/springfox/springfox/blob/2.10.5/springfox-spring-webmvc/src/main/java/springfox/documentation/spring/web/SpringfoxWebMvcConfiguration.java) class is. The artifact was also not pushed to maven repository. Previously this class was part of springfox-spring-web project.

**Comment by jakubmalek** [comment]
Addition on springfox-spring-webmvc dependency seems to fix problem.
@dilipkrish  could you at least push the missing artifact to public maven repository so it can be referenced manually ?

**Comment by dilipkrish** [comment]
If you're using spring boot see here [for a better experience](https://github.com/springfox/springfox#spring-boot-applications). You dont need to manage the dependencies or annotations other than adding the `springfox-boot-starter` dependency

**Comment by jakubmalek** [comment]
@dilipkrish   Is `springfox-boot-starter` available for version `2.10.5` ? I don't see it in this tag.

**Comment by dilipkrish** [comment]
Its not, 2.10.5 was an intermediate release so that existing 3.0.0 users are not affected by the changing SNAPSHOT builds due the the work we're doing on it. I should be released shortly tho'.

**Comment by jakubmalek** [comment]
Found it: https://mvnrepository.com/artifact/io.springfox/springfox-spring-webmvc
Thanks for releasing it.

**Comment by gijsleussink** [comment]
Please update the notes at the 2.10.x if they should not be used.
https://github.com/springfox/springfox/releases
Now consumers of the dependency need to dive into Github issues. Thanks and good luck.

**Comment by dilipkrish** [comment]
@gijsleussink appologies 2.10.x was a way to freeze the existing work getting 3.0.0 released so that existing 3.0.0-SNAPSHOTS can work with a stable base. It was never intended to be consumed which is why it wasn't announced nor part of the releases. You should see 3.0.0 land end of this week.

**Comment by mjustin** [comment]
I usually go to the Maven repository to see what versions are out there, e.g. https://mvnrepository.com/artifact/io.springfox/springfox-swagger2.  So when I saw 2.10.0, and no release notes saying there were breaking changes, my first assumption was that it must be some minor changes, possibly stabilizing things prior to the 3.x branch.

So I guess I'm +1ing @gijsleussink's [comment](https://github.com/springfox/springfox/issues/3336#issuecomment-656086326) about documenting the purpose of the 2.10 branch.

**Comment by dilipkrish** [comment]
@mjustin Yeah I understand, it wasn't meant to be advertised, but with tooling these days the news propagates really fast. like I said [before](https://github.com/springfox/springfox/issues/3336#issuecomment-656122027). This was just a way to isolate folks still depending on 3.0.0 snapshot from the avalanche of changes that came after to support open api 3.0.

The idea being, people depending on 3.0.0-SNAPSHOT will be shielded from the breaking changes coming as a result of the new work to support OpenApi 3.0. They could switch to a 2.10 dependency temporarily so that the work isn't disrupted while I fix the 3.0.0 before release. It was never really meant to serve as a release, which is why there are not release notes for it. Does that make sense?

**Comment by jebeaudet** [comment]
The proper way to do this is to have RC or milestones releases, `3.0.0-M1` for example. [Spring does this](https://spring.io/blog/2020/07/02/spring-security-5-4-0-m2-released). These can easily be filtered out in any automated version bumping tool and if not automated, not being proper semver, these are also easily filtered out.

Other option is publishing the version on an alternate maven repo, not maven central.

**Comment by dilipkrish** [comment]
Agreed. However the current release system isn't setup for that. Its a homegrown release system that I haven't prioritized to upgrade to a more standard mechanism. Rather than futz with that this was the quickest way to deliver 3.0.0.
