### ISSUE TITLE
ConditionalOnMissingBean blocking autowiring of spring beans in 2.10.5

### ISSUE THREAD

**Issue by petebeegle** [springfox/springfox#3337]
**Version:** 2.10.5

When updating to springfox 2.10.5, we are seeing errors with missing beans such as `TypeResolver` as well as `404` results from endpoints exposed via `ApiResourceController`. 

I believe this is due to `@ConditionalOnClass(name = "springfox.documentation.spring.web.SpringfoxWebMvcConfiguration")` in `Swagger2DocumentationWebMvcConfiguration` as this class does not seem to exist. If this condition fails, then it appears that none of the *WebMvc spring components are autowired.

![image](https://user-images.githubusercontent.com/16722006/85452472-ea477800-b568-11ea-8dab-b56615251b74.png)

If there is a way around this, please let me know. Thanks!

**Comment by dilipkrish** [comment]
Oh please dont use 2.10... it was an intermediate step so that people who were on 3.0.0-SNAPSHOT can continue using a released version if needed. Please continue 3.0.0-SNAPSHOT. Thats the version with the OAS support. Its not ready yet, should be available tomorrow 🤞

**Comment by dilipkrish** [comment]
Would love your feedback once 3.0.0-SNAPSHOT build is fixed.

**Comment by petebeegle** [comment]
Good to know, thank you!
