### ISSUE TITLE
SwaggerSpringMvcPlugin returning JSON with "/default/" in the path

### ISSUE THREAD

**Issue by maverick530** [springfox/springfox#334]
I'm using the example CustomJavaPluginConfig that uses a SwaggerSpringMvcPlugin in my SpringMVC framework, and have annotated my controller as such:

@Api(value = "orghierarchies", description="Org Hierarchies Resource")
@Controller
@RequestMapping(value = "/v1/orgHierarchies")
public class OrgHierarchyControllerV1 implements Serializable
{
    @RequestMapping(value = "/generate", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
    @ApiOperation(value = "Generates an Org Hierarchy", notes = "notes for generating an org hierarchy", response = String.class)
    public @ResponseBody
    StatusResponse generateOrgHierarchy(
        @ApiParam(required = true, name = "orgHerarchy", value = "The Org Hierarchy Object!")
        @RequestBody OrgHierarchy orgHierarchy)
    {
...
        }

but the resultant JSON from /api-docs is:

{
  "apiVersion": "1.0",
  "swaggerVersion": "1.2",
  "apis": [
    {
      "path": "/default/orghierarchies",
      "description": "orghierarchies"
    }
  ]
 }

notice the /default/ in the path. Why is '/default' being added to my path, and furthermore, why isn't my description being used from my @Api annotation? Also why am I not getting _ANY_ other relevant documentation for my @ApiOperations and @ApiParams?

**Comment by joshita14** [comment]
Hi,

I am new to swagger.
I have the same issue.

I am accessing index.html , with entry http://localhost:8080/rest/api-docs.json

I do get the response as :i tried this call seprately in browser :http://localhost:8080/rest/api-docs.json
{"apiVersion":"1.0","apis":[{"description":"Location Controller","path":"/default/location-controller","position":0}],"authorizations":{},"info":{"contact":"Contact Email","description":"Api Description","license":"Licence Type","licenseUrl":"License URL","termsOfServiceUrl":"Api terms of service","title":"default Title"},"swaggerVersion":"1.2"}

The problem is when i hit the index.html its saying this 
Unable to read api 'location-controller' from path http://localhost:8080/tomcat-mysql-2.0.0/api-docs.json/default/location-controller (server returned undefined)

Is the problem with the URL that is formed ?
/api-docs.json/default/ should be api-docs/default ?

I am using swagger 1.2 , i tried with the latest 2.0 UI and 1.2 UI.

Also i noticed that in my UI, the basePath is defined as 
base url: http://localhost:8080/tomcat-mysql-2.0.0/api-docs.json , api version: 1.0

Thanks in Advance

Regards
Joshita

**Comment by dilipkrish** [comment]
@joshita14 You dont need the *.json* extension.

**Comment by joshita14** [comment]
It's not working if I don't append. Json.
Also in index.html, the discovery url should have ApApi-docs.json as entry?

**Comment by dilipkrish** [comment]
Can you share your project or at the very least share your configuration. Its hard to help without knowing any details about how you've set things up. See here for [issue submission guidelines](https://github.com/martypitt/swagger-springmvc/wiki/Issue-Submission). Have you looked at the [demo project](https://github.com/adrianbk/swagger-springmvc-demo)?

**Comment by joshita14** [comment]
And I want to use swagger 2.0 version. Is there support for spring mvc?  Although I am using the latest dependency,  why it is showing 1.2 instead 2.0?

**Comment by joshita14** [comment]
Here is the project configuration 

I added this 

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

import com.mangofactory.swagger.configuration.SpringSwaggerConfig;
import com.mangofactory.swagger.models.dto.ApiInfo;
import com.mangofactory.swagger.plugin.EnableSwagger;
import com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin;

@Configuration
@EnableWebMvc
@EnableSwagger
@ComponentScan("com.package.repositories")
public class CustomJavaPluginConfig {

	private SpringSwaggerConfig springSwaggerConfig;

	@Autowired
	public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
		this.springSwaggerConfig = springSwaggerConfig;
	}

	@Bean
	// Don't forget the @Bean annotation
	public SwaggerSpringMvcPlugin customImplementation() {
		return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(
				apiInfo()).includePatterns(".*api.*");
	}

	private ApiInfo apiInfo() {
		ApiInfo apiInfo = new ApiInfo("Application",
				"Api Docs For application", "My Apps API terms of service",
				"My Apps API Contact Email", "My Apps API Licence Type",
				"My Apps API License URL");
		return apiInfo;
	}
}

**Comment by joshita14** [comment]
Swagger.props 
documentation.services.basePath=http://localhost:8080/rest
documentation.services.version=1.0

**Comment by joshita14** [comment]
pom.xml

 <dependency>
		    <groupId>com.mangofactory</groupId>
		    <artifactId>swagger-springmvc</artifactId>
		    <version>0.9.5</version>
		</dependency>

<spring.version>3.2.3.RELEASE</spring.version>

**Comment by joshita14** [comment]
code snippet for Index.html

<script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "http://localhost:8080/rest/api-docs.json";
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            /*
            initOAuth({
              clientId: "your-client-id",
              realm: "your-realms",
              appName: "your-app-name"
            });
            */
          }
          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });

**Comment by joshita14** [comment]
<script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "http://localhost:8080/rest/api-docs.json";
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            /*
            initOAuth({
              clientId: "your-client-id",
              realm: "your-realms",
              appName: "your-app-name"
            });
            */
          }
          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });

**Comment by dilipkrish** [comment]
@joshita14 I dont think you need to create the property file. That isnt even used. Why dont you create a new issue rather than tagging on to an old issue that may not be your problem?

Also what does your web.xml... or your corresponding java config look like? You shouldnt need to add the __.json__ extension
