### ISSUE TITLE
When @EnableSwagger2WebFlux is used, Failed to start bean 'documentationPluginsBootstrapper'

### ISSUE THREAD

**Issue by DongDDo** [springfox/springfox#3340]
Version:
Java 11
springBootVersion = '2.1.5.RELEASE'
springfoxVersion = '3.0.0-SNAPSHOT'

Maybe, Because of patch today, this error seems to have occurred
it is simlier to https://github.com/springfox/springfox/issues/3282
I'm getting:
```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.springframework.util.MultiValueMap.addIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)V

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    springfox.documentation.spring.web.scanners.ModelSpecificationRegistryBuilder.lambda$add$0(ModelSpecificationRegistryBuilder.java:37)

The following method did not exist:

    org.springframework.util.MultiValueMap.addIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)V
```

After spring boot 2.2.x(spring-core 5.2), addIfAbsent is added to MultiValueMap
So I solved by updating the version of spring-core.

I am wondering if this error from today's patch is intended or is there another way?

Thanks

**Comment by dilipkrish** [comment]
Thanks for catching that. Its targeting 2.3 as of now. I'll see if I can revert to an alternate
