### ISSUE TITLE
springfox-swagger2:3.0.0-SNAPSHOT Generates conflict of the beans 'requestMappingHandlerAdapter

### ISSUE THREAD

**Issue by josuemojena** [springfox/springfox#3342]
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'requestMappingHandlerAdapter', defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/web/reactive/config/DelegatingWebFluxConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Process finished with exit code 1

**Comment by dilipkrish** [comment]
Not sure what's causing this. Does the error go away when you remove springfox-swagger2? Is this a spring boot app?

Would you be able to create a failing test or [replicate it here fixed](https://github.com/springfox/springfox-demos/blob/master/boot-webflux/src/main/java/io/springfox/demo/bootwebflux/BootWebfluxApplication.java)?  so this can be fixed.

**Comment by mfalowski** [comment]
springfox-* seems to use webmvc which causes problems on reactive stack. I've noticed you have made changes in that area recently https://github.com/springfox/springfox/commit/c9b41dc915398667c6d5c05ac31f679ec5dc2cc6#diff-4fe0b8294479ac5f5c20c7604ab4cece

**Comment by josuemojena** [comment]
> No estoy seguro de qué está causando esto. ¿El error desaparece cuando elimina springfox-swagger2? ¿Es esta una aplicación de arranque de primavera?
> 
> ¿Sería capaz de crear una prueba fallida o [replicarla aquí arreglada](https://github.com/springfox/springfox-demos/blob/master/boot-webflux/src/main/java/io/springfox/demo/bootwebflux/BootWebfluxApplication.java) ? así que esto se puede arreglar.



> Not sure what's causing this. Does the error go away when you remove springfox-swagger2? Is this a spring boot app?
> 
> Would you be able to create a failing test or [replicate it here fixed](https://github.com/springfox/springfox-demos/blob/master/boot-webflux/src/main/java/io/springfox/demo/bootwebflux/BootWebfluxApplication.java)? so this can be fixed.



> Not sure what's causing this. Does the error go away when you remove springfox-swagger2? Is this a spring boot app?
> 
> Would you be able to create a failing test or [replicate it here fixed](https://github.com/springfox/springfox-demos/blob/master/boot-webflux/src/main/java/io/springfox/demo/bootwebflux/BootWebfluxApplication.java)? so this can be fixed.

The problem happens to me using spring boot 2.3.0 and springfox-swagger2:3.0.0-SNAPSHOT, once I remove the springfox dependency it works as it should.

**Comment by pmrocha-mindera** [comment]
you need to add 

`spring.main.web-application-type=reactive`

to your application.properties

**Comment by josuemojena** [comment]
> you need to add
> 
> `spring.main.web-application-type=reactive`
> 
> to your application.properties

Gracias, resolvi de esa manera, aunque no renderiza los endpoints, dice lo siguiente: 

"Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0)."

**Comment by pmrocha-mindera** [comment]
@josuemojena are you setting the DocumentationType.SWAGGER_2 when you initialize a new Docket?

**Comment by josuemojena** [comment]
> @josuemojena are you setting the DocumentationType.SWAGGER_2 when you initialize a new Docket?

Yes, I do.

**Comment by josuemojena** [comment]
> @josuemojena are you setting the DocumentationType.SWAGGER_2 when you initialize a new Docket?

Look at this.

![image](https://user-images.githubusercontent.com/66492537/85768188-c316b500-b6e6-11ea-9916-47f5974c7e11.png)

**Comment by pmrocha-mindera** [comment]
@josuemojena try to downgrade to 2.10.5 and see if that solves your issue

**Comment by josuemojena** [comment]
@pmrocha-mindera  I can't, because it doesn't support webflux

**Comment by pmrocha-mindera** [comment]
@josuemojena it does, 2.10.5 is the latest stable version of the old 3.0.0 snapshot, as their are upgrading the snashopt and some things are in a W.I.P. state they released the 2.10.5

**Comment by dilipkrish** [comment]
Thanks everyone for 

> Have the same issue. It's caused probably by the fact that people who had spring boot version below 2.2.X or below within their projects and were using springfox 3.0.0-SNAPSHOT after upgrade have spring-boot conflict. Springfox is using spring boot 2.3.1 now that's why there is such issue.
> ![image](https://user-images.githubusercontent.com/59466333/85696903-a1fb9780-b6d9-11ea-9cec-3c1d4a50c3ea.png)
> 
> If someone is using only webflux stack then he should get above issue cause webmvc is included as well and there is a spring boot autoconfiguration conflict

This is an inadvertent change. I'll fix this. Thank you everyone for jumping in with the explanation! Y'all rock!🤘

**Comment by dilipkrish** [comment]
If y'all are using spring boot, remove the explicit dependency on swagger2 and add just the dependency on `springfox-boot-starter` and remove any explicit annotations like `@EnableSwagger2WebFlux` etc. let me know if that is any better.

**Comment by josuemojena** [comment]
> @josuemojena it does, 2.10.5 is the latest stable version of the old 3.0.0 snapshot, as their are upgrading the snashopt and some things are in a W.I.P. state they released the 2.10.5

Thank you, that's how I solved my problem.

**Comment by dilipkrish** [comment]
This should now be fixed
