### ISSUE TITLE
Unable to render this definition

### ISSUE THREAD

**Issue by josuemojena** [springfox/springfox#3344]
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

I think this is what caused the mistake with the apidoc

![image](https://user-images.githubusercontent.com/66492537/85767474-0ae90c80-b6e6-11ea-99e5-b37474bd53ab.png)

**Comment by dilipkrish** [comment]
Could you try[ these instructions](https://github.com/springfox/springfox/blob/master/README.md#migrating-from-earlier-snapshot) to see if that helps? Really interested in your feedback to make the transition smooth.

**Comment by dilipkrish** [comment]
This is working as expected Closing this issue
