### ISSUE TITLE
Missing #ref in JSON when using Map<String,Map<String,List<Something>>> as a response type. 

### ISSUE THREAD

**Issue by vpm911** [springfox/springfox#3356]
I have a response of type : Map<String, Map<String, List<Something>>>.
This produces invalid JSON/YAML documentaiton:

```json
swagger: '2.0'
info:
  description: Test Service
  version: '1.0'
  title: Test Service
  termsOfService: 'https://www.test123.com/en/terms'
  license:
    name: Test License
    url: 'https://www.test123.com'
host: 'localhost:8080'
basePath: /
tags:
  - name: test-controller
    description: Test Controller
paths:
  /hello:
    get:
      tags:
        - test-controller
      summary: hello
      operationId: helloUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
              additionalProperties:
                type: array
                items:
                  $ref: '#/definitions/Something'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  MapOfstringAndListOfSomething:
    type: object
    title: MapOfstringAndListOfSomething
    additionalProperties:
      $ref: '#/definitions/List'
  Something:
    type: object
    properties:
      string:
        type: string
    title: Something
```

The error is as follows: 
`Resolver error at definitions.MapOfstringAndListOfSomething.additionalProperties.$ref
Could not resolve reference: #/definitions/List
Jump to line 47`

I am using springfox-swagger2 version: 2.9.1 and swagger-ui 2.9.1

```xml
              <dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.1</version>
			<scope>runtime</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/io.springfox/springfox-swagger2 -->
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.1</version>
		</dependency>`
```
Appreciate any help / fix on this.

**Comment by vpm911** [comment]
Link for my code 
https://github.com/vpm911/test-swagger

**Comment by dilipkrish** [comment]
First off, you need to use 2.9.2 at the very least. Secondly, 3.0.0 is going to be released shortly, and this issue has been fixed in the current build. So I'd say try 2.9.2 to see if works for you, if not wait a week or so and the latest release should be out

**Comment by vpm911** [comment]
@dilipkrish Thanks for the quick response. No luck using 2.9.2. I think I'll wait for the 3.0.0 release.
Many thanks!

**Comment by amitarora15** [comment]
Is 3.0.0 available for SNAPSHOT version to be used to see if the fix version is working?

**Comment by dilipkrish** [comment]
@amitarora15 yes it is See [the docs](http://springfox.github.io/springfox/docs/current/) on how to set that up.

**Comment by dilipkrish** [comment]
This should be fixed now

**Comment by stevebor1** [comment]
> @amitarora15 yes it is See [the docs](http://springfox.github.io/springfox/docs/current/) on how to set that up.

Can I get a pointer to this? Can't find anything in the docs.
