### ISSUE TITLE
is there documentation for fields of json of swagger web's request such as "/swagger-resouces"?

### ISSUE THREAD

**Issue by XSun771** [springfox/springfox#3358]
Thanks for author's work firstly.

In the process of loading the swagger webpage, in addition to static resources, the webpage will initiate four requests to the server to obtain four json to configure itself, for example, "/swagger-resouces", "/swagger-resources/configuration/ui"....

Is there any documentation to explain the fields in these json?

Thanks a lot.

**Comment by dilipkrish** [comment]
@XSun771 There is documentation in the [Swagger-ui](https://github.com/swagger-api/swagger-ui) and [documentation site](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/), to tell you what swagger-ui expects. From a springfox perspective. You have in [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) everything you have at your disposal to configure it (see 19/20).

**Comment by XSun771** [comment]
> @XSun771 There is documentation in the [Swagger-ui](https://github.com/swagger-api/swagger-ui) and [documentation site](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/), to tell you what swagger-ui expects. From a springfox perspective. You have in [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) everything you have at your disposal to configure it (see 19/20).

Thanks for your answer very much!
