### ISSUE TITLE
SecurityContext#securityForOperation unespected behaviour if using only operationSelector

### ISSUE THREAD

**Issue by Aitor1405** [springfox/springfox#3361]
Hi,

I'm new to opening issues but I would like to help this project as it is saving me a lot of time, thanks a lot for all the work!

I have read the submitting issues guidelines and searched for opened/closed issues about this and did not found anything. It is still on `master` and it is causing what I think is a reasonable unexpected behavior. I'm seeing this while using `io.springfox:springfox-boot-starter:3.0.0-20200628.175806-24` dependency.

As the `path` and `method` selectors are deprecated in favor of the 'operation' one, it is supposed to get rid of these and use the `operationSelector` only. When this situation is met, the 'path' and 'method' selectors are set to `(each) -> true` and this is causing the `SecurityContext#securityForOperation` method to return the `securityReferences` even if it is not meant to:

https://github.com/springfox/springfox/blob/03a10e6c4ac8a38212d435b3e9827753134a89a4/springfox-spi/src/main/java/springfox/documentation/spi/service/contexts/SecurityContextBuilder.java#L33
https://github.com/springfox/springfox/blob/03a10e6c4ac8a38212d435b3e9827753134a89a4/springfox-spi/src/main/java/springfox/documentation/spi/service/contexts/SecurityContextBuilder.java#L75-L77

On the `SecurityContext#securityForOperation` method, it is checked if the `operationSelector` is null and also if it gives `true` to return the `securityReferences`. If the `operationSelector` is not null but it gives `false` when tested, I think this is because it is intended to not return any securityReferences but, instead, the old deprecated `path` and `method` selectors are checked, which were set to `(each) -> true` and so the `securityReferences` are being returned:

https://github.com/springfox/springfox/blob/03a10e6c4ac8a38212d435b3e9827753134a89a4/springfox-spi/src/main/java/springfox/documentation/spi/service/contexts/SecurityContext.java#L54-L63

I think that `SecurityContext#securityForOperation` method should check the deprecated `path` and `method` selectors only if the `operation` one is null.

**Comment by dilipkrish** [comment]
@Aitor1405 This is a great issue for someone who hasn't opened many issues. Thank you for your detailed analysis and help making this a great library!
