### ISSUE TITLE
Is there a simple project that demonstrates how springfox works?

### ISSUE THREAD

**Issue by XSun771** [springfox/springfox#3363]
The project is really very simple.

https://github.com/XSun771/ImgBed/blob/master/spring-fox.7z

Every time I visit "localhost:8080/swagger-ui.html" and then I am told that "Please enter the location manually"....

and how about writing a simplest configuration to quick start for sprig boot?  http://springfox.github.io/springfox/docs/current/#quick-start-guides is a  good documentation, but if I just would like to start a very simple project with very simple swagger api documentation web, what is the simplest configuration?

Thanks a lot!

**Comment by dilipkrish** [comment]
Your spring-fox.7z is empty 🤷‍♂️ Here is a simple Quickstart project [the demos](https://github.com/springfox/springfox-demos). specially look at the boot-webmvc and boot-webflux if you want to get started. The simplest configuration is no configuration and have `springfox-boot-starter` auto configure itself.

**Comment by XSun771** [comment]
> Your spring-fox.7z is empty 🤷‍♂️ Here is a simple Quickstart project [the demos](https://github.com/springfox/springfox-demos). specially look at the boot-webmvc and boot-webflux if you want to get started. The simplest configuration is no configuration and have `springfox-boot-starter` auto configure itself.

Thanks for your answer very much, I've uploaded a new file here : http://img.d613.top/srping-fox-demo.zip. Could you please check it? And I googleed "springfox-boot-starter maven" but didn't find appropriate artifact whose groupid is "io.springfox", is `springfox-boot-starter` simply equal to 
```xml
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.10.5</version>
        </dependency>
```
?

Thanks a lot.

**Comment by dilipkrish** [comment]
Its not. Thats the released version of one of the modules. Its available in the snapshot repo. Read [the docs](http://springfox.github.io/springfox/docs/snapshot/#dependencies) to see how to set it up

**Comment by XSun771** [comment]
> Its not. Thats the released version of one of the modules. Its available in the snapshot repo. Read [the docs](http://springfox.github.io/springfox/docs/snapshot/#dependencies) to see how to set it up

Thanks for your answer.

Could you please check this demo and point out how to modify it?  http://img.d613.top/srping-fox-demo.zip
