### ISSUE TITLE
Need way to override XForwardPrefixPathAdjuster behavior

### ISSUE THREAD

**Issue by skylar-stark** [springfox/springfox#3370]
My team is currently using version 2.8.0, but attempting to upgrade to use version 2.9.2 in sync with upgrades to the Spring Boot version we are using. We currently have many microservices running behind a Zuul API Gateway implementation. 

The microservices are reachable behind their own specific URLs:
http://service1host:8080/service1/restservices/asdf
http://service2host:8080/service2/restservices/defg

Then we have Zuul API Gateway running on its own host:
http://apigatewayhost:8080/api-gateway/...

To reach the microservices behind the Gateway, they call the context path that is given for the microservice they are trying to reach; i.e to reach service1 they would call
http://apigatewayhost:8080/api-gateway/service1/restservices/asdf

To reach service2, they would call
http://apigatewayhost:8080/api-gateway/service2/restservices/defg

In the API Gateway, before we forward the request to the microservice, we attach a "X-Forwarded-Prefix" header of "/api-gateway/". In Springfox 2.8.0, the contextPath of the microservice was appended to this prefix, and everything was working fine - the Swagger basePath would be "/api-gateway/service1" and the Swagger "try it out" would work from the API Gateway - as in, it makes the call correctly to
http://apigatewayhost:8080/api-gateway/service1/restservices/asdf

However, when we upgrade to Springfox 2.9.2, this contextPath is no longer appended to the prefix. So the Swagger basePath always appears as "/api-gateway/". This breaks Swagger's "try it out" from the API Gateway when trying to call these microservices. As in, when trying to call "http://apigatewayhost:8080/api-gateway/service1/restservices/asdf", the context path of the microservice is cut out and it is instead trying to call "http://apigatewayhost:8080/api-gateway/restservices/asdf", which is not valid.

The change appears to be in the XForwardPrefixPathAdjuster class:
https://github.com/springfox/springfox/blob/71553ac5e8142aed1c2e809c852959e177d4fd4f/springfox-swagger-common/src/main/java/springfox/documentation/swagger/common/XForwardPrefixPathAdjuster.java#L47-L51

In 2.8.0, the behavior was to always return "prefix + path" but now it will only return "prefix" if the Spring Boot version supports x-forwarded.

Is there anyway to override this behavior? My initial thought was to simply attach the context path to the X-Forwarded-Prefix header from the API Gateway, but any microservice that is still running with Springfox version 2.8.0 would then have this context path duplicated in the Swagger basePath. I do not have control over the microservices in order to force them to upgrade Springfox versions.  We would like a way to be able to control whether or not to return "prefix + path" no matter which version of Spring Boot we are on.

**Comment by dilipkrish** [comment]
@skylar-stark Plan to release 3.0.0 in the coming few days. Id be interested in learning how 3.0.0 compares. I'd like to fix this in 3.0.0 and I suspect it may work. Would you mind checking this and reporting back?

**Comment by skylar-stark** [comment]
@dilipkrish I've tested it with 3.0.0-SNAPSHOT and it appears to be working as I hoped - the context path is getting appended to the X-Forwarded-Prefix and it is working through our API Gateway as intended. Much thanks!

**Comment by dilipkrish** [comment]
Awesome! Thanks for reporting back @skylar-stark

**Comment by skylar-stark** [comment]
@dilipkrish This is not working in 3.0.0 when upgrading to it this morning - I am thinking that when I tested using 3.0.0-SNAPSHOT, it was actually an invalid test and I wasn't correctly using the new version (instead using version 2.8.0 still).

After upgrading to 3.0.0, /v2/api-docs does not contain any mappings for my APIs and the swagger-ui page show the message 'No operations defined in spec!'. The /v2/api-docs json does include the app info including name, description, and contact info, so I know that the configuration class is getting picked up correctly.

My SwaggerConfig class looks like:

```
package com.skylarstark.spring.configuration;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.env.Environment;

import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;

import java.util.Collections;

import static springfox.documentation.builders.PathSelectors.regex;

@Configuration
public class SwaggerConfig {

	@Bean
	public Docket apiDocket(Environment environment) {
		Contact contact = new Contact(
			environment.getProperty("info.app.contact.name"),
			environment.getProperty("info.app.contact.url"),
			environment.getProperty("info.app.contact.email"));

		ApiInfo apiInfo = new ApiInfo(
			environment.getProperty("info.app.name"),
			environment.getProperty("info.app.description"),
			environment.getProperty("info.version"), null, contact, null, null, Collections.emptyList());

		return new Docket(DocumentationType.SWAGGER_2)
			.apiInfo(apiInfo)
			.select()
			.apis(RequestHandlerSelectors.any())
			.paths(regex("/restservices/.*"))
			.build();
	}
}
```

The only thing I changed in this config class after upgrading to 3.0.0 was the removal of the EnableSwagger2 annotation.

Am I missing something here?
