### ISSUE TITLE
Documenting Iterable<T> with Spring Boot

### ISSUE THREAD

**Issue by affanshahid** [springfox/springfox#3371]
- Version 2.10.5

What kind of issue is this?

 - [x] Bug report.
    - [x] spring xml/java config that is relevant
    - [x] springfox specific configuration if it makes sense
    - [x] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

I have a pretty simple Spring Boot REST API using Spring Data. This is my Repository:

```java
public interface TodoRepository extends CrudRepository<Todo, Integer> {}
```

Here is my controller:

```java
@RestController
@RequestMapping(path = "/todos")
public class TodosController {
    @Autowired
    private TodoRepository todoRepository;

    @PostMapping(path = "")
    public Todo addTodo(@RequestParam String content) {
        Todo todo = new Todo();
        todo.setContent(content);
        todo.setDone(false);
        return todoRepository.save(todo);
    }

    @GetMapping(path = "")
    public Iterable<Todo> findAll() {
        return todoRepository.findAll();
    }
}
```

When I use springfox to generate swagger docs, pretty much every thing looks fine except the `findAll` endpoint. The response model is documented as an empty object `{}` instead of an Array of `Todo`. 

[![Incorrect model][1]][1]

However when I use a `List<T>` instead of the default `Iterable<T>` provided by the repository, by adding the following to my controller:

```java
    ...
    @GetMapping(path = "/asList")
    public List<Todo> asList() {
        var result = new ArrayList<Todo>();
        todoRepository.findAll().forEach(result::add);
        return result;
    }
```

Then it shows up correctly.

[![Correct model][2]][2]

Is there a way I can get the same behavior for the default `Iterable<T>` that the repository returns so that I wouldn't have to convert to a `List<T>` every time?

Configuration: 

```java
@Configuration
@EnableSwagger2WebMvc
@Import({ springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration.class, })
public class Config {

    @Bean
    public Docket petApi() {
        return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any()).build().pathMapping("/").useDefaultResponseMessages(false);
    }

    @Bean
    UiConfiguration uiConfig() {
        return UiConfigurationBuilder.builder().deepLinking(true).displayOperationId(false).defaultModelsExpandDepth(1)
                .defaultModelExpandDepth(1).defaultModelRendering(ModelRendering.EXAMPLE).displayRequestDuration(false)
                .docExpansion(DocExpansion.NONE).filter(false).maxDisplayedTags(null)
                .operationsSorter(OperationsSorter.ALPHA).showExtensions(false).showCommonExtensions(false)
                .tagsSorter(TagsSorter.ALPHA).supportedSubmitMethods(UiConfiguration.Constants.DEFAULT_SUBMIT_METHODS)
                .validatorUrl(null).build();
    }
}
```

  [1]: https://i.stack.imgur.com/tBEeg.png
  [2]: https://i.stack.imgur.com/1wECb.png

**Comment by dilipkrish** [comment]
The reason Iterables aren't supported out of the box is cos we dont know the concrete type It represents

**Comment by affanshahid** [comment]
What would be the correct workaround?

**Comment by dilipkrish** [comment]
As demonstrated by [the commit](https://github.com/springfox/springfox/commit/cb587db480d78850a7f8acacd88e49e8c16c2ac5#diff-260df37eb373354cc96f04f4e12571a8R85-R87), you as a library consumer needs to tell it how you want to represent iterable. I the case of the commit it creates a rule that treats `Iterable` as `List`
