### ISSUE TITLE
Currupted file using the download funktion

### ISSUE THREAD

**Issue by mueller-jens** [springfox/springfox#3372]
- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
 2.9.2
What kind of issue is this?

 - [ X] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

I found an issue while downloading files using  springfox-swagger2. 
I have service that delivers files from the backend, where the type is configured by the request accept header.
When i use it swagger shows me the right accept header in the generated curl command : ```curl -X GET --header 'Accept: application/vnd.openxmlformats-officedocument.wordprocessingml.document ...```. But as the section *Request Headers* shows ```{
  "Accept": "application/octet-stream"
}```

But this is not the thing. When i use the download link i get a corrupted file. I have analized the downloaded file. It is much bigger than the content length.

The *Response Headers* section shows:
```
{
  "cache-control": "private",
  "connection": "keep-alive",
  "content-disposition": "attachment;filename=<filename>.docx",
  "content-length": "91567",
  "content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "date": "Wed, 08 Jul 2020 12:52:06 GMT",
  "expires": "Thu, 01 Jan 1970 00:00:00 GMT",
  "keep-alive": "timeout=60",
  "strict-transport-security": "max-age=31536000 ; includeSubDomains",
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY",
  "x-xss-protection": "1; mode=block"
}
```

But if i download the file using the download link it has a size of 164.223 bytes

If i download the file with the generated curl command the downloaded file is correct

Please let me know if you need more informations.

![grafik](https://user-images.githubusercontent.com/14818895/86922156-84441e80-c12c-11ea-9cc7-be447ef4f353.png)

**Comment by dilipkrish** [comment]
@mueller-jens could you share what your api-docs looks like for this operation? Also did you select the right consumes for the API in the ui when you executed the request?

**Comment by mueller-jens** [comment]
@dilipkrish sorry i am not sure what you need to see? Do you want me to share the Spring REST configuration?

**Comment by mueller-jens** [comment]
@dilipkrish  The requst api doc looks like:

![grafik](https://user-images.githubusercontent.com/14818895/87024479-78fafc80-c1d9-11ea-970f-369039121c2a.png)


Yes i have selected the correct consumes type. As I wrote in my report it worksfine with curl.

The API-mapping looks like: 
 ```
   @GetMapping(value = "/{id}/download", 
        produces = { MediaType.APPLICATION_OCTET_STREAM_VALUE, "application/vnd.openxmlformats-officedocument.wordprocessingml.document" })
 
```

Maybe the problem occurs if you have more than one *produces* declaration

**Comment by mueller-jens** [comment]
I have now checked it with only one *produces* declaration and the section *Request Headers* than is correct. But the downloaded files is not valid. The same situation, the downloaded file is too big

**Comment by dilipkrish** [comment]
Even if you have multiple produces, you should be able to select the appropriate accept types via the `Response Content Type` drop down. I dont think the swagger tool (at least the version you're using) is capable of downloading files.

**Comment by mueller-jens** [comment]
@dilipkrish i can select the Response type. And as you can see in the content length I get the correct information but using the link in the UI i get something different. Not only the response or it is converted in an other characterset or something else.

**Comment by dilipkrish** [comment]
Just FYI, The swagger-ui isn't great for demonstrating file downloads. At least the last time I checked it was not great

**Comment by mueller-jens** [comment]
@dilipkrish Mybe it is not great. But is should work. Can you explain why you closed the issue?

**Comment by dilipkrish** [comment]
Because swagger ui is not maintained by this project unfortunately.
