### ISSUE TITLE
JsonView Is not working as expected

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#3373]
@dilipkrish  I noticed two issues in the current 3.0.0-SNAPSHOT:
- 'position' attribute of '@ApiModelProperty' has stopped working.
- JsonView support has also stopped working. It is working (not perfectly) in 2.10.5

_Originally posted by @singhjoga in https://github.com/springfox/springfox/issues/3070#issuecomment-655580882_

**Comment by dilipkrish** [comment]
@singhjoga would you mind providing details for an example of a scenario that is not working?

**Comment by MaksimOrlov** [comment]
@singhjoga, what did you mean , when you were saying that is ***not perfectly*** working in 2.10.5 ? Could you, please, provide some cases when it worked not as expected?

**Comment by singhjoga** [comment]
@dilipkrish  @MaksimOrlov I will try to add a test project along with the steps to test it.

**Comment by singhjoga** [comment]
@MaksimOrlov attached you will find the document explaing my code and the issue with JsonView in 2.10.5. Zip includes the demo project to reproduce the behavior.
[demo.zip](https://github.com/springfox/springfox/files/4896256/demo.zip)
[swagger-plugin-2105-defect.pdf](https://github.com/springfox/springfox/files/4896259/swagger-plugin-2105-defect.pdf)

**Comment by singhjoga** [comment]
@dilipkrish attached you will find document explaining the issues related to 'position' element of ApiModelProperty and JsonView in 3.0.0-SNAPSHOT. Also attached is the demo project.
[swagger-plugin-300-defect.pdf](https://github.com/springfox/springfox/files/4896457/swagger-plugin-300-defect.pdf)
[demo-300.zip](https://github.com/springfox/springfox/files/4896465/demo-300.zip)

**Comment by dilipkrish** [comment]
The first issue @singhjoga is just a function of the spec. It cannot be sorted based on position. For the second issue, do you know what's going on @MaksimOrlov?
