### ISSUE TITLE
springfox-swagger 3.0.0 - SNAPSHOT: In the WebFlux application, SpringFox does not get the original 'host' and 'basePath'

### ISSUE THREAD

**Issue by PC-Chiu** [springfox/springfox#3375]
In the WebFlux application, SpringFox does not adjust the original 'host' and 'basePath',  so API documentation generated through gateways or reverse proxies cannot be used.

springfox.documentation.swagger2.web.Swagger2ControllerWebFlux, line: 90
```
swagger.basePath(isEmpty(request.getPath().contextPath().value()) ? "/" : request.getPath().contextPath().value());
if (isEmpty(swagger.getHost())) {
  swagger.host(request.getURI().getAuthority());
}
```

**Comment by dilipkrish** [comment]
Swagger 2.0 has always been tricky with respect to ALB's/gateways. You'd have to manually override the host and set the X-Forward headers correctly. Happy to look at it if you provide a breaking test or scenario

**Comment by PC-Chiu** [comment]
In the Web Servlet application, SpringFox adjust the original 'host' and 'basePath' by ALB's/gateways 'X-Forward-*' headers, for example: X-Forwarded-Host, X-Forwarded-Port, X-Forwarded-Prefix. But In the WebFlux application, it does not. I think there should be the same processing logic here.

**Comment by dilipkrish** [comment]
@PC-Chiu WebFlux doesn't support the concept of concept paths. Open to suggestions.

**Comment by PC-Chiu** [comment]
It can be solved by set properties in webflux application.

```
server:
  forward-headers-strategy: framework
```

**Comment by dilipkrish** [comment]
Oh cool! Thank you for letting me know. I'll add this to the docs!

**Comment by conet** [comment]
> It can be solved by set properties in webflux application.
> 
> ```
> server:
>   forward-headers-strategy: framework
> ```

I seem to be experiencing the exact opposite, if I have `server.forward-headers-strategy=framework` and fetch the specs using `X-Forwarded-Prefix` then `basePath` is not set while if I remove `server.forward-headers-strategy=framework` it works.

**Comment by conet** [comment]
It's because of [this line](https://github.com/springfox/springfox/blob/3.0.0/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/WebMvcBasePathAndHostnameTransformationFilter.java#L33):
```
            String basePath = StringUtils.isEmpty(uriComponents.getPath()) ? "/" : uriComponents.getPath();
            swagger.basePath(basePath.replace(servletRequest.getContextPath(), ""));
```
after correctly setting the `basePath` it then clears it (the `replace` call).

**Comment by conet** [comment]
I would consider using openapi (`v3`) but unfortunately `ForwardedHeaderExtractingRequest` [also ignores the prefix](https://github.com/springfox/springfox/blob/ab5868471cdbaf54dac01af12933fe0437cf2b01/springfox-oas/src/main/java/springfox/documentation/oas/web/ForwardedHeaderExtractingRequest.java#L89):
```
public String adjustedRequestURL() {
    return String.format("%s://%s:%s",
        getScheme(),
        getServerName(),
        getServerPort());
  }
```
The above ends up in the `servers` section.
