### ISSUE TITLE
[Question] springfox-boot-starter on Maven Central?

### ISSUE THREAD

**Issue by gdinant** [springfox/springfox#3381]
Hello guys,

Any ETA on the springfox-boot-starter on Maven Central? I'm still on the previous dependencies (2.9.2) and would like to migrate to the latest at some point.

Cheers

**Comment by dilipkrish** [comment]
It will be released this weekend. Take a look at the pinned issue to track progress.

**Comment by dilipkrish** [comment]
Its been released @gdinant

**Comment by gdinant** [comment]
Great news! Thanks for the heads-up.
