### ISSUE TITLE
BUG: @ApiImplicitParam no longer honours allowableValues

### ISSUE THREAD

**Issue by sigand** [springfox/springfox#3390]
implementation "io.springfox:springfox-boot-starter:3.0.0"
Spring boot version: 2.3.1.RELEASE

`ApiImplicitParam(name = "perPage", allowableValues = "range[1, 100]", example = "5"))`

This part is lost in the generated documentation
`"maximum": 100,
  "exclusiveMaximum": false,
   "minimum": 1,
   "exclusiveMinimum": false,`

**Comment by dilipkrish** [comment]
Thanks for reporting!

**Comment by sigand** [comment]
I dug a bit. Seems like it goes wrong in the springfox.documentation.builders.EnumerationElementFacetBuilder. Specifically, this little piece here
`  public static Set<String> from(AllowableValues allowableValues) {
    if (allowableValues instanceof AllowableListValues) {
      return new HashSet<>(((AllowableListValues) allowableValues).getValues());
    }
    return new HashSet<>();
  }`

The allowableValues as specified above are parsed into an instance of AllowableRangeValues  by springfox.documentation.swagger.schema.ApiModelProperties#allowableValueFromString method.
