### ISSUE TITLE
BUG: @ApiImplicitParam does not support required=true when paramType = "header"

### ISSUE THREAD

**Issue by kishorepurushothaman20** [springfox/springfox#3394]
implementation "io.springfox:springfox-boot-starter:3.0.0"
Spring boot version: 2.3.0.RELEASE

When we define @ApiImplicitParam like below,
@ApiImplicitParams({
            @ApiImplicitParam(name = Headers.AUTHORIZATION, required = true, dataType = "String", paramType = "header"),
            @ApiImplicitParam(name = Headers.CLIENT_CHANNEL, required = true, dataType = "String", paramType = "header", example = "mobile-app", value = "Source of initiation")
    })

Swagger allows the form submission to the api and the page is kept on loading and the web console has the error written
![image](https://user-images.githubusercontent.com/36532751/87445470-624d0f00-c5f8-11ea-8885-ca7dcf8014d0.png)
![image](https://user-images.githubusercontent.com/36532751/87445514-6ed16780-c5f8-11ea-9091-28149d94206a.png)

**Comment by dilipkrish** [comment]
I confirmed that this is a bug in swagger-ui. You should [report it there](https://github.com/swagger-api/swagger-ui).

**Comment by kishorepurushothaman20** [comment]
Hi I reported the same issue in swagger-ui
https://github.com/swagger-api/swagger-ui/issues/6225

And it looks like a compatibility issues for springfox with swagger-ui
