### ISSUE TITLE
X-ForwardPrefix not working as expected for swagger 2.0

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#3400]
@dilipkrish This is not working in 3.0.0 when upgrading to it this morning - I am thinking that when I tested using 3.0.0-SNAPSHOT, it was actually an invalid test and I wasn't correctly using the new version (instead using version 2.8.0 still).

After upgrading to 3.0.0, /v2/api-docs does not contain any mappings for my APIs and the swagger-ui page show the message 'No operations defined in spec!'. The /v2/api-docs json does include the app info including name, description, and contact info, so I know that the configuration class is getting picked up correctly.

My SwaggerConfig class looks like:

```
package com.skylarstark.spring.configuration;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.env.Environment;

import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;

import java.util.Collections;

import static springfox.documentation.builders.PathSelectors.regex;

@Configuration
public class SwaggerConfig {

	@Bean
	public Docket apiDocket(Environment environment) {
		Contact contact = new Contact(
			environment.getProperty("info.app.contact.name"),
			environment.getProperty("info.app.contact.url"),
			environment.getProperty("info.app.contact.email"));

		ApiInfo apiInfo = new ApiInfo(
			environment.getProperty("info.app.name"),
			environment.getProperty("info.app.description"),
			environment.getProperty("info.version"), null, contact, null, null, Collections.emptyList());

		return new Docket(DocumentationType.SWAGGER_2)
			.apiInfo(apiInfo)
			.select()
			.apis(RequestHandlerSelectors.any())
			.paths(regex("/restservices/.*"))
			.build();
	}
}
```

The only thing I changed in this config class after upgrading to 3.0.0 was the removal of the EnableSwagger2 annotation.

Am I missing something here?

_Originally posted by @skylar-stark in https://github.com/springfox/springfox/issues/3370#issuecomment-658298247_

**Comment by dilipkrish** [comment]
Its possible that it might be a bug? not sure without looking at your example. Can you reproduce this in the springfox demos?

**Comment by skylar-stark** [comment]
@dilipkrish I was able to reproduce this in the demos. It appears to be an error when a context path is configured for the application.

In the boot-swagger demo, in the [application.properties](https://github.com/springfox/springfox-demos/blob/master/boot-swagger/src/main/resources/application.properties) file, this is using "server.contextPath=/springfox" - I believe this is an incorrect property, as Spring Boot 2.x uses instead "server.servlet.contextPath" as the property name. So the demo, by default, will start a Spring Boot service with '/' as the contextPath. In this scenario, Swagger loads just fine.

When I change this property to "server.servlet.contextPath=/springfox", I see the error as described above.

In my local application which prompted this question, I am setting server.servlet.contextPath to "/my-awesome-api", and I am getting the error message as stated above when accessing "http://localhost:8080/my-awesome-api/swagger-ui.html". However, when I remove this property altogether, the Swagger page loads just fine when accessing "http://localhost:8080/swagger-ui.html".


(On another note - to get the boot-swagger demo to work, I had to make a few other changes as well to the build.gradle file and the Application.java file, notably having to include the springfox-boot-starter dependency and then removing the annotations for EnableSwagger and EnableSwagger2WebMvc)

**Comment by skylar-stark** [comment]
Here is a PATCH file that contains the changes I made to the demo to get it to work
[Changes-to-boot-swagger-demo.txt](https://github.com/springfox/springfox/files/4920740/Changes-to-boot-swagger-demo.txt)

**Comment by dilipkrish** [comment]
Those seem like normal changes... however boot-swagger was meant to showcase the non-autoconfigured way of doing things. Im curious what your experience was with the context path etc. especially with the boot-webmvc and/or the boot-webflux modules

**Comment by skylar-stark** [comment]
I found a working solution

In my case, all of my REST endpoints were behind /context-path/restservices/xyz
So my configuration was:
server.servlet.contextPath=context-path

And in the Docket config, I had:

```
return new Docket(DocumentationType.SWAGGER_2)
    ...
    .paths(regex("/restservices/.*"))
    ...
```

By keeping the context path property as-is, I modified the Docket config to instead be:

```
return new Docket(DocumentationType.SWAGGER_2)
    ...
    .paths(regex("/context-path/restservices/.*"))
    ...

```

It is now working correctly, and the original issue with the X-Forwarded-Prefix header has been resolved.

**Comment by dilipkrish** [comment]
Oh perfect thank you for reporting back. Closing this issue
