### ISSUE TITLE
cannot open swagger-ui.html, it return 404 not found 

### ISSUE THREAD

**Issue by bytesmithing** [springfox/springfox#3401]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

here is my maven pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.jizhang</groupId>
    <artifactId>rpa-master</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>rpa-master</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.1.3</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/ch.qos.logback/logback-core -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/ch.qos.logback/logback-classic -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>3.0.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.springfox/springfox-swagger2 -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>3.0.0</version>
        </dependency>



    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

and the following code is the swagger config  bean

```java

package com.jizhang.rpamaster.conf;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig  {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.jizhang.rpamaster"))
                .paths(PathSelectors.any())
                .build();
    }



    private ApiInfo apiInfo(){
        return new ApiInfoBuilder().title("rpa").version("1.0.0").build();
    }

}
```

What kind of issue is this?
this question is when i run my app, then i cannot open the swagger-ui.html.
 i switch  version 2.10.5 of the swagger-ui, it works.  the ui is rendered correctly

It's that my configuration has something problem? or the version 3.0.0 of swagger-ui cannot works with spring-boot 2.3.1?

whether the problem i met is a bug?  or something else? thank you!

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by felpower** [comment]
What worked for me was to implement the WebMcvConfigurer and follow the [Documentation](http://springfox.github.io/springfox/docs/current/#migrating-from-existing-2-x-version) by adding a resourceHandler and a vie Controller to the registry: 

```
@Configuration
@EnableSwagger2
public class SwaggerConfig implements WebMvcConfigurer {

  private String baseUrl = "";

  public SwaggerConfig(DescriptionResolver descriptions,
      ModelSpecificationFactory modelSpecifications) {
    super(descriptions, modelSpecifications);
  }

@Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    String baseUrl = StringUtils.trimTrailingCharacter(this.baseUrl, '/');
    registry.
        addResourceHandler(baseUrl + "/swagger-ui/**")
        .addResourceLocations("classpath:/META-INF/resources/webjars/springfox-swagger-ui/")
        .resourceChain(false);
  }

  @Override
  public void addViewControllers(ViewControllerRegistry registry) {
    registry.addViewController(baseUrl + "/swagger-ui/")
        .setViewName("forward:" + baseUrl + "/swagger-ui/index.html");
}
```

**Comment by bytesmithing** [comment]
@felpower  thank you very much, i opened the swagger-ui/index.html and find it !!!!!

**Comment by manvydasu** [comment]
> What worked for me was to implement the WebMcvConfigurer and follow the [Documentation](http://springfox.github.io/springfox/docs/current/#migrating-from-existing-2-x-version) by adding a resourceHandler and a vie Controller to the registry:
> 
> ```
> @Configuration
> @EnableSwagger2
> public class SwaggerConfig implements WebMvcConfigurer {
> 
>   private String baseUrl = "";
> 
>   public SwaggerConfig(DescriptionResolver descriptions,
>       ModelSpecificationFactory modelSpecifications) {
>     super(descriptions, modelSpecifications);
>   }
> 
> @Override
>   public void addResourceHandlers(ResourceHandlerRegistry registry) {
>     String baseUrl = StringUtils.trimTrailingCharacter(this.baseUrl, '/');
>     registry.
>         addResourceHandler(baseUrl + "/swagger-ui/**")
>         .addResourceLocations("classpath:/META-INF/resources/webjars/springfox-swagger-ui/")
>         .resourceChain(false);
>   }
> 
>   @Override
>   public void addViewControllers(ViewControllerRegistry registry) {
>     registry.addViewController(baseUrl + "/swagger-ui/")
>         .setViewName("forward:" + baseUrl + "/swagger-ui/index.html");
> }
> ```
> 
> as well as your pom.xml, you should remove
> 
> ```
>         <dependency>
>             <groupId>io.springfox</groupId>
>             <artifactId>springfox-swagger2</artifactId>
>             <version>3.0.0</version>
>         </dependency>
>         
>         <dependency>
>             <groupId>io.springfox</groupId>
>             <artifactId>springfox-swagger-ui</artifactId>
>             <version>3.0.0</version>
>         </dependency>
> ```
> 
> and add:
> 
> ```
>  <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-boot-starter</artifactId>
>         <version>3.0.0</version>
>   </dependency>
> ```

How did this work for you? Documentation says that you should remove @EnableSwagger2... The annotation is not even exported from the newest version of library.
