### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by chinausers** [springfox/springfox#3409]
2.6.1 upgrade to 3.0 / swagger- ui.html But it doesn't work. Is it backward compatible?

**Comment by chinausers** [comment]
@configuration
@EnableOpenApi
@EnableSwagger2
public class Swagger2Config {

@Bean
public Docket createRestApi() {
    return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.basePackage("com"))
            .paths(PathSelectors.any())
            .build();
}
}

**Comment by chinausers** [comment]
spring boot version is "'2.1.6.RELEASE'" He seems to need it spring-boot-plugin 2.0.0.
Demo Version  is spring boot 2.3.1 .It's so new

**Comment by dilipkrish** [comment]
@chinausers Here are [the release notes](https://github.com/springfox/springfox/releases/tag/3.0.0) (updated with compatibility). Also please read the documentation on [how to migrate(http://springfox.github.io/springfox/docs/current/#migrating-from-existing-2-x-version). I believe it should work with 2.1.6 but its not been tested. Would love feedback on how to improve it.

**Comment by chinausers** [comment]
Same question #3401. he seems to need to solve this problem.

**Comment by chinausers** [comment]
Good. Thank You.

**Comment by dilipkrish** [comment]
He _**has**_ solved the problem. Swagger ui is available at `/swagger-ui/index.html` going forward.
