### ISSUE TITLE
One reason of TypeError: Failed to fetch 

### ISSUE THREAD

**Issue by zhugw** [springfox/springfox#3415]
This is not a bug or feature request, just remind others there is such a question which could let you maddening.

Recently I developed a spring boot project, there are api like below
```
GET admin/banners
POST admin/banners
PUT admin/banners
DELETE admin/banners/{id}
GET admin/banners/{id}
```
very strangely,  the first three api could execute successfully, but the last two execute failed,

![image](https://user-images.githubusercontent.com/4953871/87616532-d813c080-c747-11ea-8c6b-5f51a202a7fa.png)

and from chrome develop tools Console could get below error info
```
index.js:581 GET http://localhost:8081/admin/banners/1 net::ERR_BLOCKED_BY_CLIENT
actions.js:440 TypeError: Failed to fetch
```
then know it is blocked by AdBlock, and disable AdBlock the problem is solved
![image](https://user-images.githubusercontent.com/4953871/87616868-b830cc80-c748-11ea-8c21-37544556b532.png)

**Comment by dilipkrish** [comment]
Thank you for that! I know I've encountered this many a time 😅
