### ISSUE TITLE
springfox-boot-starter:3.0.0  'position' attribute of '@ApiModelProperty' has stopped working.

### ISSUE THREAD

**Issue by mastar3104** [springfox/springfox#3416]
It is described in this comment.
https://github.com/springfox/springfox/issues/3070#issuecomment-655580882

But, I created the issue because the this issue is close.

**Comment by sigand** [comment]
Duplicate of https://github.com/springfox/springfox/issues/3391

**Comment by dilipkrish** [comment]
Closing this a duplicate of #3391
