### ISSUE TITLE
HttpAuthenticationScheme - Authorization header is not sent

### ISSUE THREAD

**Issue by kdebski85** [springfox/springfox#3425]
I am using SpringFox 3.0.0.

When I use HttpAuthenticationBuilder to build HttpAuthenticationScheme, authorize in swagger-ui and invoke any API, the Authorization header with token is not being sent by swagger-ui.

**My configuration:**
```
@Configuration
public class SwaggerConfiguration {

    @Bean
    public Docket api () {
        return new Docket(DocumentationType.OAS_30)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.regex("/api.*"))
                .build()
                .securitySchemes(singletonList(securityScheme()))
                .securityContexts(singletonList(securityContext()));
    }

    private SecurityScheme securityScheme() {
       return new HttpAuthenticationBuilder().name("Authorization").scheme("Bearer").build();
    }

    private SecurityContext securityContext() {
        return SecurityContext.builder()
                .securityReferences(securityReferences())
                .build();
    }

    private List<SecurityReference> securityReferences() {
        return singletonList(
                new SecurityReference("Authorization", new AuthorizationScope[] {new AuthorizationScope("global", "global")}));
    }

}
```

As a workaround, I currently use ApiKey scheme:
```
    private SecurityScheme securityScheme() {
       return new ApiKey("Authorization", "Authorization", "header");
    }
```
With ApiKey, when I authorize in swagger-ui and then invoke any API, the Authorization header is being sent by swagger-ui,.

I think HttpAuthenticationScheme should always attach Authorization header.
Alternatively, some option should be added to it to allow sending the header.
Currently, HttpAuthenticationScheme is useless because a user provides a token, but it is not used later.

**Comment by dilipkrish** [comment]
Try using the available builders. it might be a problem with the constants used. In your case HttpAuthenticationBuilder .JWT_BEARER_BUILDER. or try changing `Bearer` to `bearer`

**Comment by kdebski85** [comment]
Changing 'Bearer' to 'bearer' fixed it. Thank you.

Both:
1. `return new HttpAuthenticationBuilder().name("Authorization").scheme("bearer").build();`
2. `return HttpAuthenticationScheme.JWT_BEARER_BUILDER.name("Authorization").build();`

work fine - swagger-ui sends "Authorization: Bearer ...".
I will use option 1, because my token does not have JWT format.

I will close this ticket.
Please reopen if you want to:
-add a comment to HttpAuthenticationBuilder::scheme that the argument should be in lower-case
-call toLowerCase in HttpAuthenticationBuilder::scheme
