### ISSUE TITLE
SpringFox 3.0.0 @Content annotation schema value throws undefined error.

### ISSUE THREAD

**Issue by prabhushrikant** [springfox/springfox#3428]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is 
SpringFox 3.0.0 released recently.

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 
I want to have special ErrorResponse schema for status codes other than 200 but schema seems to get neglected in latest library 3.0.0

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       Following is the annotations I am using for my controller 
```
       @PostMapping("/conversion/controller")
    @Operation(
        summary = "Submit request to convert.",
        description = "Submit request to convert to lower or upper.",
        responses = {
            @io.swagger.v3.oas.annotations.responses.ApiResponse(
                responseCode = "200",
                description = "Returns the converted results.",
                content = {
                    @Content(mediaType = "application/json",
                        schema = @Schema(implementation = Baz.class))
                }
            ),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(
                responseCode = "400",
                description = "Invalid request body",
                content = {
                    @Content(mediaType = "application/json",
                        examples = @ExampleObject(value = "{'errorCode':'400', 'message': 'Bad input request.'}"),
                        schema = @Schema(implementation = ErrorResponse.class))
                }
            ),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(
                responseCode = "500",
                description = "If service encountered errors communicating with other services that it depends on",
                content = {
                    @Content(mediaType = "application/json",
                        examples = @ExampleObject(value = "{'errorCode':'500', 'message': 'Internal server error.'}"),
                        schema = @Schema(implementation = ErrorResponse.class))
                }
            )}
    )
    public ResponseEntity<Baz> convert(@RequestBody Baz baz) {
        return new ResponseEntity(baz, HttpStatus.OK);
    }
```
I have ErrorResponse class defined in same class as follows

```
    /** Describe the error message and code */
    @ApiModel(description = "Describe the error message and code")
    @Validated
    public static class ErrorResponse {

        @ApiModelProperty(required = true, value = "Different Error Conditions")
        @JsonProperty("errorCode")
        public String errorCode = null;

        @ApiModelProperty(required = true, value = "Provides description of error")
        @JsonProperty("message")
        public String message = null;

        public ErrorResponse errorCode(String errorCode) {
            this.errorCode = errorCode;
            return this;
        }
    }
```
However in swagger page I see following 

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/6848200/87889645-825d4380-c9e7-11ea-8802-ad88cf0c7549.png">

Also endpoint can't seem to infer the schema 

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/6848200/87889676-ade02e00-c9e7-11ea-99f4-fc3b953b7d4b.png">

Schema & Example for response code of 200 seems to work fine.

Here is the branch for reproducing the bug quickly....I am using the project springfox-integration-webmvc

https://github.com/prabhushrikant/springfox-demos/tree/Bug_3428

Thank,
Shrikant.

**Comment by prabhushrikant** [comment]
@dilipkrish any update on this?

**Comment by prabhushrikant** [comment]
@dilipkrish bump ^^

**Comment by ShelterApp** [comment]
This is still an issue, I would like to fix it if someone can provide me any pointers.

**Comment by prabhushrikant** [comment]
This is still an issue, I would like to fix it if someone can provide me any pointers.
