### ISSUE TITLE
Why flux's basePath is different from webMvc ,I request them over spring gateway ,the flux is always "/",but the mvc is service name!

### ISSUE THREAD

**Issue by flowclouds** [springfox/springfox#3429]
this is flux server
![image](https://user-images.githubusercontent.com/40859714/87893185-b54c1980-ca71-11ea-9d58-d268d66ed689.png)
this is mvc server
![image](https://user-images.githubusercontent.com/40859714/87893205-cdbc3400-ca71-11ea-9829-737351a0ca49.png)

**Comment by dilipkrish** [comment]
Assuming you figured out why it was doing that.
