### ISSUE TITLE
NullPointerException on WebFlux /v3/api-docs - Starter 3.0.0

### ISSUE THREAD

**Issue by awilhelmer** [springfox/springfox#3436]
Hello!

Good work and nice to finally have version 3.0.0. I've been using the 3.0.0-SNAPSHOT starter all the time, but today I suddenly get NPE (everything worked a week ago). 
I bumped the starter directly, with the same result. It is the WebFlux variant with Gradle, as in your examples with Java 1.8 and is therefore reproducible.
Enpoint:
`/v3/api-docs`

Exception:
```
java.lang.NullPointerException: null
	at springfox.documentation.oas.mappers.ModelSpecificationInheritanceDeterminer.lambda$new$0(ModelSpecificationInheritanceDeterminer.java:29)
```

Source: https://github.com/springfox/springfox/blob/master/springfox-oas/src/main/java/springfox/documentation/oas/mappers/ModelSpecificationInheritanceDeterminer.java#L29

Subclasses have a null element.

The null element is added here:

https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/schema/ApiModelBuilder.java#L77

Do not add the element if the Optional isn't present ...

**Comment by dilipkrish** [comment]
Thank you for the details explanation!
