### ISSUE TITLE
ApiOperation support dynamically Generic

### ISSUE THREAD

**Issue by zhugw** [springfox/springfox#3437]
#consult#

When developing management system, basically all are CRUD operations , e.g.
```
GET /foos
GET /foos/{id}
POST /foos
PUT /foos
DELETE /foos/{id}
```
so for reducing development work, I put common logic in BaseController and concrete Controller extend BaseController e.g.

```
public abstract class BaseController<V, F extends BaseForm> {
    @GetMapping("/{id}")
    protected ApiResult detail(@PathVariable String id) {
        V v = getService().getById(id);
        return ApiResult.success(v);
    }
}
```

but in this case I have to override detail to add @ApiOperation respectively
```
    @Override
    @ApiOperation(value = "Detail info",  response = BarVO.class)
    public ApiResult detail(@PathVariable String id) {
        return super.detail(id);
    }
```
Because ApiOperation annotation cannot support generic 
```
@ApiOperation(value = "Detail info",  response = V.class)
```
even below manner also not support
```
@ApiOperation(value = "Detail info",  response = getClazz())

public abstract Class<V> getClazz();
```

So any idea could help ?

**Comment by dilipkrish** [comment]
It might be easier if ApiResult would be generic and `ApiResult<V>` could make it very easy to inform the types without having you do so many things to get that to work, what do you think?

**Comment by zhugw** [comment]
@dilipkrish It indeed feasible.

**Comment by dilipkrish** [comment]
Awesome! Do reach out if you need help with that

**Comment by zhugw** [comment]
@dilipkrish Another question 
sometimes need override method just because want to override notes in ApiOperation e.g. Some domain has special requirement

```
    @Override
    @ApiOperation(value = "Add", notes = "At most add 6 records, if reach 6 , should delete one than add new record")
    public void add(@Valid @RequestBody BannerForm form, HttpServletRequest request) {
        super.add(form, request);
    }
```

**Comment by dilipkrish** [comment]
I'd recommend doing something like this then

```java
 @Override
    @OperationDescription //<-- custom annotation
    public void add(@Valid @RequestBody BannerForm form, HttpServletRequest request) {
        super.add(form, request);
    }
```

Then create an OperationBuilderPlugin with an order higher than `SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER` like this. Check for that annotation and then come up with a key for e.g. `package.class.methodName` You can get that from the method and then define those in a property file with those keys. The `DescriptionResolver` should be able to resolve the property name for you. If it finds the key you'll get the description if not you'll get the key.

https://github.com/springfox/springfox/blob/561b10791195ad3748c4b8b996b5225af384094e/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OperationNotesReader.java#L51-L55

Makes sense?

**Comment by zhugw** [comment]
@dilipkrish Sorry! Your manner I do not understand and it seems it still need override.
 More ideally do not override and could dynamically  resolve notes, e.g.
```
BaseController:

@ApiOperation(value = "Add", notes = "${add_notes_of_#{this.getFlag()}:default notes}")

protected abstract String getFlag();

application.properties:
add_notes_of_bar=XXX
add_notes_of_foo=XXX
```

**Comment by dilipkrish** [comment]
Here are the steps
1. You need to implement your own `OperationBuilderPlugin` plugin that reads your custom annotation like I mentioned above `@ OperationDescription ` 
2. In you plugin
```java
 Optional<OperationDescription> methodAnnotation = context.findAnnotation(OperationDescription.class); 
 if (methodAnnotation.isPresent()) { 
   context.operationBuilder() 
          .notes(descriptions.resolve("add_notes_of_" + context.getName())); 
 } 
```
