### ISSUE TITLE
[Question] Configuration of Response Content-Type for spring-data-rest

### ISSUE THREAD

**Issue by UglyBarnacle** [springfox/springfox#3438]
SpringBoot 2.3.0
SpringFox 3.0.0

We have set up our spring-data-rest so it returns JSON instead of HAL. In the UI now the dropdown for the response content-type has a different order: instead of putting application/json on top, it shows application/hal+json. if we do not select application/json, the request fails because of wrong content-type.

![grafik](https://user-images.githubusercontent.com/22610610/88163142-87520b00-cc12-11ea-80e1-1ca0cd5cb615.png)

before the 3.0.0 release, application/json was the default value.

How to configure the Docket to represent our spring-data-rest config to show only application/json?
(the example value shown is in HAL-format too - but always was)

We tried configuring the docket like this
```java
docket.produces(new LinkedHashSet<>(Arrays.asList("*/*", "application/json")));
```
but it seems it does not take any effect on the `findAll()`.

**Comment by dilipkrish** [comment]
The change in behavior was to sort it alpabetically. However I dont think there is a concept of a default media type for accept headers in the spec. While it seems annoying, Im not sure how best to address this because any order one picks for this use case is bound to affect some other use case.

**Comment by UglyBarnacle** [comment]
just thinking:
as mentioned we configured spring-data-rest to return JSON instead of HAL

```java
        @Override
	public void configureRepositoryRestConfiguration(final RepositoryRestConfiguration config)
	{
		SpringDataRestCustomization.log.info("configure RepositoryRestConfiguration");
		Set<Class<?>> documentClasses = this.findDocumentAnnotatedClasses();
		SpringDataRestCustomization.log.info("configure following repositories: {}", documentClasses);
		config.setReturnBodyOnCreate(true).setReturnBodyOnUpdate(false).setDefaultMediaType(MediaType.APPLICATION_JSON_UTF8);
		config.exposeIdsFor(documentClasses.toArray(new Class[] {}));
	}
```

shouldn't there be just the application/json in the selectable list (and the example in JSON format) ? or do I misunderstand?
