### ISSUE TITLE
[Question] Configuration of Athorization-Header with OAS3

### ISSUE THREAD

**Issue by UglyBarnacle** [springfox/springfox#3439]
SpringBoot 2.3.0
SpringFox 3.0.0

We used to have configured a globalRequestParameter to add an Authorization-Header.
This still work with the Docket configured for SWAGGER2 - but the header seems to be dropped when setting the Docket up for OAS3.

The Authorization-Header does not show up anymore in the curl-block when using OAS3.

```java
// Docket docket = new Docket(DocumentationType.OAS_30);
Docket docket = new Docket(DocumentationType.SWAGGER_2);
RequestParameterBuilder parameterBuilder = new RequestParameterBuilder()
    .in(ParameterType.HEADER)
    .name("Authorization")
    .required(true)
    .query(param -> param.model(model -> model.scalarModel(ScalarType.STRING)));
docket.globalRequestParameters(Collections.singletonList(parameterBuilder.build()));
```

![grafik](https://user-images.githubusercontent.com/22610610/88163902-9e452d00-cc13-11ea-806f-cef68f6a0473.png)

How can we achieve the same behaviour in OAS3 like with SWAGGER2? We have a mix of BasicAuth and JWT, so both should still work.

**Comment by qrqhuang** [comment]
same question.

**Comment by dilipkrish** [comment]
Im really surprised this doesn't work but this seems like a bug in [Swagger-ui](https://github.com/swagger-api/swagger-ui) 😱. Maybe you should report it there

**Comment by UglyBarnacle** [comment]
if I am allowed to show a different example from the springdoc fork, this is how a "Docket" is configured there with OAS3

```java
        @Bean
	public OpenAPI customOpenApi()
	{
		OpenAPI openAPI = new OpenAPI().components(new Components());
		openAPI.getComponents().addSecuritySchemes("basic", new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("basic"));
		openAPI.addSecurityItem(new SecurityRequirement().addList("basic", Arrays.asList("read", "write")));
		return openAPI;
	}
```

which results in an UI like this, with a global Authorize

![grafik](https://user-images.githubusercontent.com/22610610/88181132-b2e2ee80-cc2e-11ea-94c2-a97ec84bedd7.png)

it works there, so I do not think that is a bug in the swagger-ui, isn't it?

**Comment by dilipkrish** [comment]
The way you'd do that is not by specifying a header. Here is how you'd do the same globally with springfox.

https://github.com/springfox/springfox/blob/861764c7823e51b0805e554ccfda0361b3e3bd7e/oas-contract-tests/src/main/java/springfox/test/contract/oas/OpenApiTestConfig.java#L50-L61

Also note you can specify targeted security contexts using the `docket.securityContext` API which is [also documented](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)?

**Comment by dilipkrish** [comment]
What I meant about the swagger-ui problem is that it doesn't send header parameters...you could try it out yourself by pasting this contract in https://editor.swagger.io/ and see for youself

https://github.com/springfox/springfox/blob/861764c7823e51b0805e554ccfda0361b3e3bd7e/oas-contract-tests/src/test/resources/contracts/features.json#L58-L68

**Comment by UglyBarnacle** [comment]
looks like it is an restricted value to set the Authorization-header and we are left to use the SecurityScheme then in case we move to OAS3

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject

> If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.

**Comment by dilipkrish** [comment]
Ah! good to know! Thanks for reponding back with the reason
