### ISSUE TITLE
Error starting application with tomcat and springFox 3.0.0

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#3440]
Hi Dilip,

I am currently working on adding support for swagger with certain endpoints in Spring MVC. I am getting an error while starting up tomCat stating running into the following error when I start up Tomcat.
 
UnsatisfiedDependencyException: Error creating bean with name 'apiModelReader'

Following artifacts in pom.xml

1. springfox-swagger-ui
2. springfox-swagger2
3. springfox-swagger-common
4. springfox-schema
5. springfox-core

<properties>
<springfox.swagger.version>3.0.0</springfox.swagger.version>
</properties>

<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>${springfox.swagger.version}</version> -> red symbol here
    <scope>compile</scope>
</dependency>

_Originally posted by @Viswanath1984 in https://github.com/springfox/springfox/issues/1638#issuecomment-662736348_

**Comment by dilipkrish** [comment]
Is this a boot application? If you're using tomcat I'm going to assume it's not. In the [springFox demos project](https://github.com/springfox/springfox-demos/tree/master/spring-java-swagger) take a look at spring-java-swagger project. You don't need all the dependencies like you've listed. Also please read [the docs](http://springFox.io) on how to set it up manually. 

Please report back on what you've tried and we can take it from there.

**Comment by Viswanath1984** [comment]
I had annotated the Swagger configuration(Java) class with @Configuration and @EnableSwagger2 annotations and running into a unsatisfied dependency exception -> ModelApiReader class. I didn’t see this annotation in the spring-java swagger project. If I switch it with @Component, the error disappears but CORS results.

Following Dependencies added in pom.xml with swagger version 3.0.0-SNAPSHOT.

<springfox.swagger.version>3.0.0-SNAPSHOT</springfox.swagger.version>

1) springfox-spring-webmvc
2) springfox-swagger2
3) springfox-spring-web
4) springfox-swagger-ui
5) springfox-spring-integration-webmvc

**Comment by Viswanath1984** [comment]
Hi Dilip,
I am currently running into an exception while starting up tomcat with swagger support, stating "CORS error", you might not have the appropriate access control settings."

**Comment by 02Ian** [comment]
The annotation your using is @EnableSwagger2 which is a swagger2 annotation.
Your pom file version is incorrect as per the annotation.
So it's giving an error please use appropriate annotation.

**Comment by Viswanath1984** [comment]
Hi Mohit,
Which annotation do you suggest using in place of @EnableSwagger2.
https://github.com/springfox/springfox-demos/commit/cba3c4eca90d0efef10116022db5d78ea05acd20
This swagger config uses springfoxopenAPI. could you please share a
sample project where swagger is configured with springmvc along with
correct pom.
Regards
Viswanath

**Comment by Viswanath1984** [comment]
Hi Mohit,

Could you please share any updates as to which annotation needs to be used
to enable Swagger.?
https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api, am
following the current link to enable swagger in a spring-webmvc app.

**Comment by dilipkrish** [comment]
@Viswanath1984 we're trying too many things all at once. I'd recommend starting from the [springfox-demos project](https://github.com/springfox/springfox-demos/tree/master/spring-java-swagger) that starts with a simple application that can run as a war in tomcat.

If you're trying baeldung article, then I would start by taking it as-is (it is a pre-3.0.0 guide). Start by
- removing `springfox-spring-web`, `springfox-spring-integration-webmvc`, `springfox-swagger-common`, `springfox-schema` and `springfox-core`  dependencies. You should only need `springfox-swagger2` and `springfox-swagger-ui`.
- [Enable swagger-ui](http://springfox.github.io/springfox/docs/current/#changes-in-swagger-ui) using a `WebMvcConfigurer`. 

Also if you made no other changes, you should see your docs in `/v2/api-docs`

**Comment by dilipkrish** [comment]
Also @Viswanath1984 [this repo](https://github.com/mfvanek/spring5-mvc-with-embedded-tomcat) might be useful to you thanks to @mfvanek

**Comment by Viswanath1984** [comment]
Hi Dilip,
Thanks for sharing the repo.. Though i did follow the steps listed in
springfox-demos
project
<https://github.com/springfox/springfox-demos/tree/master/spring-java-swagger>,
I am running into a CORS(Cross-Origin) issue.
I tried adding the snippet below, but that didn't work as well. Is this any
other filter config in Tomcat that needs to be added?

@Override
public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**").allowedMethods("GET", "POST");
}


Regards,

Viswanath

**Comment by Viswanath1984** [comment]
Hi Dilip,


Thanks for the pointers.

I have a class extending WebMvcConfigurer with the code given below.x


*public static final String API_DOCS = "/docApi/v2/api-docs";*

*public static final String API_DOCS_LOCATION = "/v2/api-docs";*


*loading the server locally with /v2/api-docs/api.html complains link not
found.*

but when I don't have v2 it works, but keep running into the CORS issue.


@Override

public void addViewControllers(ViewControllerRegistry registry) {

    registry.addRedirectViewController("/docApi/v2/api-docs",
"/v2/api-docs");


registry.addRedirectViewController("/docApi/swagger-resources/configuration/ui",
"/swagger-resources/configuration/ui");


registry.addRedirectViewController("/docApi/swagger-resources/configuration/security",
"/swagger-resources/configuration/security");

    registry.addRedirectViewController("/docApi/swagger-resources",
"/swagger-resources");

}


@Override

public void addResourceHandlers(ResourceHandlerRegistry registry) {


registry.addResourceHandler("/docApi/swagger-ui.html**").addResourceLocations("classpath:/META-INF/resources/swagger-ui.html");


registry.addResourceHandler("/docApi/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");

}


Would be great if you could share some pointers?

Regards,

Viswanath

**Comment by dilipkrish** [comment]
Its easier if you have a repo that you can share. Hard to read comments and assume a project
