### ISSUE TITLE
OAuth2(Client Credentials Flow) authorization option is not shown on the available authorizations screen: migration from 2.9.2 to 3.0.0

### ISSUE THREAD

**Issue by phm-paulomorais** [springfox/springfox#3442]
Hi, Dilip! 

When I use this configuration by sending the document type as **DocumentationType.SWAGGER_2**:

`@Bean
 public Docket api() {
	
	return new Docket(DocumentationType.SWAGGER_2).protocols(Sets.newHashSet("https")).host(authServerUri).select()...
}`

In the available authorizations screen is shown the two configured authorization options :

![screen1](https://user-images.githubusercontent.com/9214795/88318000-7b3c7b00-ccf0-11ea-920c-9e7ff6fac724.png)

But when I change the configuration by sending the document type as **DocumentationType.OAS_30**:

`@Bean
public Docket api() {
	
	return new Docket(DocumentationType.OAS_30).protocols(Sets.newHashSet("https")).host(authServerUri).select()...

}`

In the available authorizations screen, only one authorization option is shown:

![screen2](https://user-images.githubusercontent.com/9214795/88318345-f7cf5980-ccf0-11ea-830f-08a05fa1d1d9.png)

Do I need to keep the document type as DocumentationType.SWAGGER_2 ?

Thank you!

**Comment by roll57** [comment]
You can try to add your security scheme using OAuth2Scheme
```
.securitySchemes(
    Arrays.asList(
        new OAuth2Scheme(
                    "login",
                    "Your flow type",//implict or clientCredentials or...
                    "Connect with oauth",
                    null,
                    oauthProperties.getOauthEndpoint(),
                    null,
                    Collections.emptyList(),
                    Collections.emptyList()
            )
)
```

**Comment by phm-paulomorais** [comment]
Thank you!

After making this change, when I click on the button that has the text Authorize the Oauth2 authorization option is shown on the screen, however when I click on the API service lock icon (**post /v1/certificateReports**) the Oauth2 option is not shown .

![screen-doc-api-1](https://user-images.githubusercontent.com/9214795/88575039-a3dab280-d019-11ea-8a68-6de552ea7a28.png)

I tried to do this configuration, but it didn't work either:

`public SecurityScheme getOauth2() {

	AuthorizationScope authorizationScope = new AuthorizationScope("global", "accessEverything");
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
	authorizationScopes[0] = authorizationScope;

	return new OAuth2Scheme("login", "clientCredentials", "Connect with oauth", null,
			"https://my.api.com/api/auth-server/oauth/token", null, 
                         Arrays.asList(authorizationScopes),
		         Collections.emptyList());
}`


In **version 2.9.2**, I configured this part like this:

`private List<SecurityReference> defaultAuth2() {
	
       AuthorizationScope authorizationScope = new AuthorizationScope("global", "accessEverything");
       AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
       authorizationScopes[0] = authorizationScope;
       return Arrays.asList(new SecurityReference("oauth2", authorizationScopes));
}`

`private SecurityContext securityContext2() {

         return SecurityContext.builder().securityReferences(defaultAuth2()).forPaths(PathSelectors.regex("/v1.*")).build();
}`


`@Bean
public Docket api() {
      
       . . .
      return new Docket(DocumentationType.SWAGGER_2).protocols(Sets.newHashSet("https")).host(authServerUri).select().
                 .securityContexts(Arrays.asList(securityContext(), securityContext2())) . . .

}`


In version **3.0.0**, How do I configure which api operations and HTTP methods to apply security contexts to apis ?

**Comment by roll57** [comment]
Hi,
I dont know about that but you could try to get rid of the scope to test.

```
.securityContexts(
	Collections.singletonList(
		SecurityContext.builder()
            .securityReferences(Collections.singletonList(new SecurityReference.SecurityReferenceBuilder().scopes(new AuthorizationScope[0]).reference("login").build()))
            .build()
	)
)
```

**Comment by phm-paulomorais** [comment]
Hi, 
For me it worked with this configuration:

	private SecurityReference securityReferenceApiKey() {
		AuthorizationScope authorizationScope = new AuthorizationScope("global", "accessEverything");
		AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
		authorizationScopes[0] = authorizationScope;

		return new SecurityReference.SecurityReferenceBuilder().scopes(authorizationScopes)
				.reference("Authorization").build();
	}

	private SecurityReference securityReferenceOauth2() {
		return new SecurityReference.SecurityReferenceBuilder().scopes(new AuthorizationScope[0]).reference("login")
				.build();
	}

	private SecurityContext securityContext() {
		return SecurityContext.builder()
				.securityReferences(Arrays.asList(securityReferenceApiKey(), securityReferenceOauth2())).build();
	}

    @Bean
    public Docket api() {
           . . .
           return new Docket(DocumentationType.OAS_30).protocols(Sets.newHashSet("https")).host(authServerUri).select().
                           .securityContexts(Collections.singletonList(securityContext())) . . .
    }

Thank you!!!

**Comment by dilipkrish** [comment]
Closing this as a duplicate, see here for explanation https://github.com/springfox/springfox/issues/3455#issuecomment-665401519
