### ISSUE TITLE
How to create and use those plugin with Dropwizard framework ? 

### ISSUE THREAD

**Issue by vikas-harness** [springfox/springfox#3447]
Hi,

My application is built using dropwizard framework https://www.dropwizard.io/en/latest/

In my application I am want to create plugin like ApiOperationBuilderPlugin and use it enhance swagger documentation.

I referred to the steps mentioned https://github.com/springfox/springfox/issues/1180#issuecomment-185523244 
but the my plugin code was not invoved.

I would like to know whether we can use this library with Dropwizard ?  If yes, any example will be really helpful.

**Comment by dilipkrish** [comment]
@vikas-harness drop wizard isn't really supported in this library unfortunately.

**Comment by vikas-harness** [comment]
thnx @dilipkrish for confirming.
