### ISSUE TITLE
BaseType for Currency changed from String to BigDecimal

### ISSUE THREAD

**Issue by m7stock** [springfox/springfox#3453]
The Java class `java.util.Currency` identifies a currency by its alphabetical and numerical currency code [defined in ISO 4217](https://www.iso.org/iso-4217-currency-codes.html). The class can be instantiated [from the alphabetical representation](https://docs.oracle.com/javase/8/docs/api/java/util/Currency.html#getInstance-java.lang.String-). To my knowledge, Jackson also uses the string representation and I think this change was unintentional.

In Springfox 2.9.2 it was [represented as a string](https://github.com/springfox/springfox/blob/2.9.2/springfox-schema/src/main/java/springfox/documentation/schema/Types.java#L80).

```
"properties": {
  "myCurrency": {
    "type": "string"
  }
}
```

With Springfox 3 its type [became a BigDecimal](https://github.com/springfox/springfox/blob/acaaf3e4a7360a9920b85a4ee8c5da6e18e64c48/springfox-core/src/main/java/springfox/documentation/schema/ScalarTypes.java#L46).

```
"properties": {
  "myCurrency": {
    "type": "number"
  }
}
```

Workaround: The earlier behavior can be achieved with

```
springfox.documentation.spring.web.plugins.Docket.directModelSubstitute(Currency.class, String.class)
```

**Comment by dilipkrish** [comment]
Thanks for reporting!

**Comment by m7stock** [comment]
closed due to inactivity
