### ISSUE TITLE
Render dynamic response types in the UI

### ISSUE THREAD

**Issue by sura2k** [springfox/springfox#3454]
I have a set of controllers and all of them return a generic type of response as follows.
```
public class GenericResponse {
     private Object responseObject;
}
```

For example, if I have following setup, would Swagger UI be able to render the final response object?
Currently it renders as follows for all controllers
```
{
   "responseObject" : {}
}
```

Example:

```
@RequestMapping(value = "/some/path/")
public GenericResponse someOperation() {
	GenericResponse response= new GenericResponse();
        response.setResponseObject(new User());
        return response;
}

@RequestMapping(value = "/some/other/path/")
public GenericResponse someOtherOperation() {
	GenericResponse response= new GenericResponse();
        response.setResponseObject(new Department());
        return response;
}

public class User {
    private String name;
    private String email;
}

public class Department {
    private Address address;
    private List<Section> sections;
}
```

I couldn't find a suitable resource anywhere, so I want to get confirmation whether there is a way to handle this adding some sort of directives to the controller methods or this is not supported. I'm using 2.9.2.

**Comment by dilipkrish** [comment]
Why not just make it a generic type and it should just work. e.g.

```java
public class GenericResponse<T> {
     private T responseObject;
}
```

**Comment by sura2k** [comment]
@dilipkrish that is working. Thank you very much
