### ISSUE TITLE
What is the qualified class for the value "__file" of the data type property ? migration: from 2.9.2 to 3.0.0

### ISSUE THREAD

**Issue by phm-paulomorais** [springfox/springfox#3456]
In version 2.9.2 I configured the file type parameter like this:

    @ApiImplicitParam(name = "certificates[0][content]", value = "Certificate [ cer | crt]", required = true, dataType = "__file", paramType = "form")

In version 3.0.0 it is necessary to inform the  qualified class for the data type. 

Is it correct to change the value of the data type from "__file" to "java.io.File" ?

**Comment by dilipkrish** [comment]
@phm-paulomorais There is an open bug to fix issues with `@ApiImplictParam` however try using the dataTypeClass instead and set it to either `File` or `MultipartFile`. That is the recommended way going forward.

**Comment by phm-paulomorais** [comment]
Thanks Dilip!
