### ISSUE TITLE
Re initialize of swagger definition using BeanConfig, cause /api/swagger.json to return 404

### ISSUE THREAD

**Issue by nitin065** [springfox/springfox#3458]
I have followed this documentation: [Swagger-Core-RestEasy](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-RESTEasy-2.X-Project-Setup-1.5#using-swaggers-beanconfig).
I placed my code in init method of servlet.

	BeanConfig beanConfig = new BeanConfig();
	beanConfig.setVersion("1.0.0");
	beanConfig.setSchemes(new String[] { "http", "https" });
	beanConfig.setBasePath("/an-example/api");
	beanConfig.setResourcePackage("io.swagger.resources,com.example.rest");
	beanConfig.setScan(true);

Now, when my I run my Tomcat server, I am able to access `/an-example/api/swagger.json`. But when I try to redeploy my application (from Tomcat Manager), it calls the same init method again, causing above code to run again.
Now, if I try to access the end point, it throws 404 error, and only solution, I could see is, to restart the server.

**Comment by dilipkrish** [comment]
I dont think this belongs to this project, please report in swagger-core
