### ISSUE TITLE
Add support for DeferredResult

### ISSUE THREAD

**Issue by omayevskiy** [springfox/springfox#346]
Hello,

if using DeferredResult Swagger does not provide the proper Model types.

Spring controller:

```
@RequestMapping(value = "/{id}", method = RequestMethod.GET)
    DeferredResult<List<MyData>> byId( ... );
```

Swagger: 

```
DeferredResult<List<MyData>> {
  result (object, optional),
  setOrExpired (boolean, optional)
}
```

But it should be:

```
List<MyData> {
   id (Long, required),
   somethingElse (String, required)
   ...
}
```

As DefferedResult is just a technical type helping you to provide non blocking controller logic and not visible in the json result anywhere.
At the moment if using DeferredResult and you want to find out, what is the resulting model, then you need to try out the call (and hope that the resulting json contains all the possible fields)

**Comment by dhruvasa** [comment]
How to make this work if I have DeferredResult<ResponseEntity<UserDTO>> and want it to be substituted by UserDTO ?

**Comment by shivangshah** [comment]
Same question as @dhruvasa .. 

even if you do put both in substitutions: 
```
.genericModelSubstitutes(DeferredResult.class, ResponseEntity.class)
```
it shows a weird json object
```
{
type: "object",
properties: {
body: {
$ref: "#/definitions/ShipBag"
},
shipId: {
type: "string"
},
statusCode: {
type: "string",
enum: [
"100" ...
```
The only property it should show is `shipId`

**Comment by dilipkrish** [comment]
Have you see [the docs](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot)?  see # 10.

**Comment by shivangshah** [comment]
Ahh yes. Let me try this out ! Thank you

**Comment by shivangshah** [comment]
@dilipkrish That worked! Thank you so much for the quick response !
