### ISSUE TITLE
Is there a possibility in version 3.0.0 to make the configuration to send the Bearer value without the user having to type ?

### ISSUE THREAD

**Issue by phm-paulomorais** [springfox/springfox#3461]
In version 2.9.2, the user must type Bearer + access_token value to be sent as authorization value in the header:

![screen_apiKey](https://user-images.githubusercontent.com/9214795/88806708-26cd4b80-d187-11ea-9d61-6b731718de50.png)

Is there a possibility in version **3.0.0** to send only the access_token value and configure the library to send the Bearer value under the table ?

If there is no such possibility, it would be a great improvement as a suggestion.

Thank you!

**Comment by dilipkrish** [comment]
duplicate of #1812 
duplicate of #3455
