### ISSUE TITLE
Is there a way to NOT generate localAddress.*, remoteAddress.*, and sslInfo.*

### ISSUE THREAD

**Issue by x80486** [springfox/springfox#3471]
I have a Spring Boot WebFlux `2.3.2.RELEASE` application that uses Gradle `6.5.1`. I'm using `implementation("io.springfox:springfox-boot-starter:3.0.0")` in order to generate the Swagger documentation for the RESTful API, along with this configuration:

```java
@Configuration
@Import(BeanValidatorPluginsConfiguration.class)
class SwaggerConfig {
  @Bean
  public Docket docket() {
    return new Docket(DocumentationType.OAS_30)
        .apiInfo(apiInfo())
        .select()
        .apis(RequestHandlerSelectors.basePackage("tld.domain"))
        .paths(PathSelectors.regex("/endpoint.*"))
        .build();
  }

  private ApiInfo apiInfo() {
    return new ApiInfoBuilder()
        .contact(new Contact("Team", null, "identifier@domain.tld"))
        .description("RESTful API Reference for Developers")
        .title("RESTful API")
        .version("1.0")
        .build();
  }
}
```

The problem is that Swagger is generating an enormous amount of parameters that aren't used (first hand): `localAddress.address.MCGlobal`, `localAddress.address.MCLinkLocal`, `localAddress.address.MCNodeLocal`, `localAddress.address.MCOrgLocal`, `localAddress.address.canonicalHostName`, `remoteAddress.address.MCGlobal`...and so on.

[![enter image description here][1]][1]

Is there a way to filter those, minimize the amount, or just don't generate them as part of the documentation (read: the final HTML). I don't fully understand why Swagger is generating those query parameters. It looks like it generates everything pretty well, expect for that detail: *the extra (useless for me) parameters*.

> I'm not using any other annotation(s) in the code, nor any other setting(s) in the `application.[properties|yml]` file.

  [1]: https://i.stack.imgur.com/amyBF.png

**Comment by dilipkrish** [comment]
Seems like if you prefer (Im not sure what type `localAddress` is), but if you dont need those parameters, Im guessing its one of these scenarios
1. If those are optional, that dont expect to get passed in, but still do expect certain properties on that object.
  1a. if you own the type for `localAddress` then you could annotate it with @ApiModeProperty(hidden=true)
  1b. if you dont own it you could create an alternate type rule to substitute the type with another type that is more in like with the parameters you're looking for. 
2. or are you not expecting properties at all ... for e.g. URL is a type that can be used as a parameter, but dont expect properties like host, port, scheme etc. but rather treat it as a string.

**Comment by x80486** [comment]
Currently, the application has only one endpoint:

```java
@Validated
@RestController
@RequestMapping("/endpoint")
public class FooController {
  private final Logger logger = LoggerFactory.getLogger(getClass());

  private final FooService service;

  @Autowired
  public FooController(final FooService service) {
    this.service = service;
  }

  @GetMapping(value = "/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
  public Mono<Foo> getById(final @PathVariable("id") @Range(min = 1L, message = "{field.id.Range}") String id,
      final ServerHttpRequest request) {
    logger.info("{} {}", request.getMethod(), request.getPath());
    return service.findById(id)
        .switchIfEmpty(Mono.error(new ResponseStatusException(HttpStatus.NOT_FOUND)));
  }
}
```

That's why I said that I didn't fully understand why Swagger was generating those query parameters. I don't have any of those.

> I was playing with the `Docket` options and I noticed that if I use `.ignoreParameterTypes(org.springframework.http.server.reactive.SslInfo.class)`, for instance, that one is not displayed anymore in the HTML documentation. I couldn't find anything for `localAddress` or `remoteAddress` (the only `LocalAddress` class that I have didn't chance anything when put in the aforementioned `ignoreParameterTypes` calls).

**Comment by dilipkrish** [comment]
Sounds like you need to add `ServerHttpRequest` to the ignorable types

`docket.ignoredParameterTypes(ServerHttpRequest.class)` should do the trick

**Comment by x80486** [comment]
OK, you got this one right in the middle. Thanks for the tip! :partying_face: :tropical_drink:

I infer that Swagger will inspect `ServerHttpRequest`, at that level, and based on the result(s) will expect to pass as query parameter(s) all those values.

If you have a StackOverflow account you can answer over there...in the meantime, feel free to close this one.

Thanks again! :1st_place_medal:

**Comment by SadabSiddiqui** [comment]
T

> Sounds like you need to add `ServerHttpRequest` to the ignorable types
> 
> `docket.ignoredParameterTypes(ServerHttpRequest.class)` should do the trick

I was facing the same issue and now resolved, So thank you.
