### ISSUE TITLE
Unable to configure Docket specifications after upgrading to 3.x

### ISSUE THREAD

**Issue by lucasoares** [springfox/springfox#3473]
Hello.

Today I tried to upgrade my springfox from 2.x to 3.x.

I followed the migration guide. Removed annotations, old dependencies and added starter dependency.

I also commented my entire SwaggerSetup class (which defines Docket and security scheme/context) just to start simple. I added just few custom configurations:

On application.yaml
```yaml
springfox:
  documentation:
    swagger-ui:
      base-url: /docs
```

On my own `WebMvcConfigurer`
```java
  @Override
  public void addViewControllers(@NonNull ViewControllerRegistry registry) {
    if (this.swaggerEnabled) {
      registry
          .addRedirectViewController("/docs", "/docs/swagger-ui/index.html")
          .setKeepQueryParams(true);
      registry
          .addRedirectViewController("/docs/", "/docs/swagger-ui/index.html")
          .setKeepQueryParams(true);
    }
  }
```

I'm also using the OAS3 since its now the default:

![image](https://user-images.githubusercontent.com/10624972/89345128-509ddb00-d67d-11ea-9d2b-f911c7798d23.png)

The documentation seems to work with those configurations.

The problem is that I need to configure api info, group name, security and other resources. After using the `@Bean` to create a `Docket` instance I got this error:

![image](https://user-images.githubusercontent.com/10624972/89345281-8642c400-d67d-11ea-9f55-9197487d8f76.png)

Even with this simple Docket definition I got the same error.  Both SWAGGER_2 and OAS_30 has the same result.
```java
  private Docket createDocket() {
    return new Docket(DocumentationType.SWAGGER_2);
  }
```

There is anything special to do to be able to use springfox starter and also customize the Docket?

Thank you.

**Comment by dilipkrish** [comment]
That is weird. is this a spring boot project? Maybe if you can share a repo replicating the problem, it might be easier

**Comment by lucasoares** [comment]
Here you are @dilipkrish 

https://github.com/lucasoares/springfox-3-update

Run this application and try to access http://localhost:8080/docs/swagger-ui/index.html

You will see an error: 
![image](https://user-images.githubusercontent.com/10624972/93244252-d07c9200-f75f-11ea-9460-b4e4519da0b8.png)

**Comment by lucasoares** [comment]
Hello @dilipkrish any news here?

**Comment by lucasoares** [comment]
Still waiting for any interaction here.

**Comment by lucasoares** [comment]
Still waiting for any interaction here.

Edit: 
> I just migrated to [springdoc](https://springdoc.org/) and I didn't have any of these problems. Thanks.
