### ISSUE TITLE
Support of custom attributes in Open api spec

### ISSUE THREAD

**Issue by santhosh-v** [springfox/springfox#3475]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using?
3.0.0

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 
Yes

To overcome issue with javascript limitation on maximum property when converting from bigdecimal, we are trying to relay on x-maximum as a custom attribute. We tried to add this in the  @ApiModelProperty but since the annotation dont have the definition, we are getting error. Where to start adding custom annotation support.

   @ApiModelProperty(value = "This is the reference Id ", required = true, x-minimum = "1", x-maximum = "9")
                                                                                                  ^

**Comment by dilipkrish** [comment]
You could implement a plugin to add that to the model, all builders support the notion of vendor extensions.

**Comment by dilipkrish** [comment]
Also @ApiModelProperty annotation is not part of this project.
