### ISSUE TITLE
[Question] RequestParameterBuilder default value

### ISSUE THREAD

**Issue by cacoguaa** [springfox/springfox#3477]
Hi, I'm using the v3.0.0, in past versions the ParameterBuilder have the attribute defaultValue that can be used globally, but in the newer version the RequestParameterBuilder doesn't have a defaultValue, can add it please?

**Comment by dilipkrish** [comment]
In the new world, you'd have to do that in the SimpleParameterSpecificationBuilder.. 

basically, `requestParameterBuilder.query(q -> q.defaultValue(...))`

**Comment by d00d171** [comment]
I don't think it's working as described. I'm trying to define default global header using `globalRequestParameters` like so:
```
return new RequestParameterBuilder()
            .name("HEADER")  
            .in(ParameterType.HEADER)
            .query(q -> q.defaultValue("DEFAULT")
                         .model(modelSpecificationBuilder -> modelSpecificationBuilder.scalarModel(ScalarType.STRING)))
            .required(false)
            .build();
```
which results in:
```
{
	"name": "HEADER",
	"in": "header",
	"required": false,
	"allowReserved": false,
	"schema": {
		"type": "string"
	}
}
```
seems like defaultValue is ignored.

**Comment by mgimenoroman** [comment]
Hello,

We are struggling with a similar issue

We define the global request parameter like so but it will not show any value

`RequestParameterBuilder()
          .name(userInfoHeader)
          .required(true)
          .description("Base64 encoded. See UserInfo")
          .in(ParameterType.HEADER)
          .query {
            SimpleParameterSpecificationBuilder()
              .model {
                ModelSpecificationBuilder()
                  .scalarModel(ScalarType.STRING)
                  .build()
              }
              .defaultValue("eyJyb2xlIjoiQ0FORElEQVRFIiwic3ViIjoiMTIzIn0=")
          }
          .build()
`

We've also tried the following with no success

`RequestParameterBuilder()
          .name(userInfoHeader)
          .required(true)
          .description("Base64 encoded. See UserInfo")
          .in(ParameterType.HEADER)
          .example(
            ExampleBuilder()
              .value("example vlaue")
              .build()
          )
          .query {
            SimpleParameterSpecificationBuilder()
              .model {
                ModelSpecificationBuilder()
                  .scalarModel(ScalarType.STRING)
                  .build()
              }
          }
          .build()
`

**Comment by Wilson-He** [comment]
I think d00d171 has described this issue in detail because his results is the same as mine like so:
```
return new Docket(DocumentationType.OAS_30)
        .globalRequestParameters(Lists.newArrayList(
                new RequestParameterBuilder()
                        .name("debug")
                        .description("ignore authorization")
                        .in(ParameterType.HEADER)
                        .query(parameterSpecificationBuilder -> parameterSpecificationBuilder.defaultValue("1")
                                .allowEmptyValue(true))
                        .build()
        ))
        .securityContexts(Arrays.asList(SecurityContext.builder()
                .securityReferences(Arrays.asList(SecurityReference.builder()
                        .reference("Authorization")
                        .scopes(new AuthorizationScope[]{new AuthorizationScope("global", "accessEverything")})
                        .build()))
                .build()))
        .securitySchemes(Arrays.asList(new ApiKey("Authorization", "Authorization", "header")))
        .select()
        .paths(PathSelectors.regex("^(?!/error).*"))
        .build();
```
json doc:
```
[
    {
        "name":"debug",
        "in":"header",
        "description":"ignore authorization",
        "required":false
    }
]
```
In fact I think since spring boot is integrated, it will be more convenient to manage these configurations in property class than in builder or functional interface. At that time we just need to config in `application.yml/application.properties` like that:
![image](https://user-images.githubusercontent.com/22442006/103750608-fea11d00-5041-11eb-82e2-3cb58adb0ae6.png)

> I don't think it's working as described. I'm trying to define default global header using `globalRequestParameters` like so:
> 
> ```
> return new RequestParameterBuilder()
>             .name("HEADER")  
>             .in(ParameterType.HEADER)
>             .query(q -> q.defaultValue("DEFAULT")
>                          .model(modelSpecificationBuilder -> modelSpecificationBuilder.scalarModel(ScalarType.STRING)))
>             .required(false)
>             .build();
> ```
> 
> which results in:
> 
> ```
> {
> 	"name": "HEADER",
> 	"in": "header",
> 	"required": false,
> 	"allowReserved": false,
> 	"schema": {
> 		"type": "string"
> 	}
> }
> ```
> 
> seems like defaultValue is ignored.

**Comment by iameshapalta** [comment]
Hi, is this issue resolved? We still see this in our application. Default values are not editable. User need to copy from description and fill in the value for globalParameters
This is what we have:
                .globalRequestParameters(Lists.newArrayList<RequestParameter>(RequestParameterBuilder()
                        .name("name")
                        .query { SimpleParameterSpecificationBuilder().model { ModelSpecificationBuilder().scalarModel(ScalarType.STRING) .build() }
                                .defaultValue("super-user") }
                        .description("User")
                        .`in`(ParameterType.HEADER)
                        .required(true)
                        .build()

**Comment by iaincd** [comment]
Hi @iameshapalta, equivalent to the below works for me with `springfox-boot-starter` @3.0.0
```
new RequestParameterBuilder()
        .name("name")
        .query(simpleParameterSpecificationBuilder -> simpleParameterSpecificationBuilder
                .model(modelSpecificationBuilder -> modelSpecificationBuilder.scalarModel(ScalarType.STRING))
                .defaultValue("super-user"))
        .description("User")
        .in(ParameterType.HEADER)
        .required(true)
        .build();
```

**Comment by twerszko** [comment]
Hi,
It was working fine for Docket of type SWAGGER_2, bu it's not working for OAS_30.
I assume this is a related issue: https://github.com/springfox/springfox/issues/3422 .
