### ISSUE TITLE
Springfox 3.0.0 generates 3 classes instead of 1 (Class, ClassReq, ClassRes) and ClassReq is missing required fields

### ISSUE THREAD

**Issue by BernhardPosselt** [springfox/springfox#3487]
- What version of the library are you using? 3.0.0

For a single class 3.0.0 generates 3 classes: the original class, one with the Req and one with the Res postfix. Req seems to be used if @RequestBody is being used. Res I suppose when @ResponseBody is in use (do not use it, class is still generated). The original Class name is used when the class is present on another object.

This makes it impossible to pass a response object to a request API in Java and other other languages that rely on nominal typing because they are completely separate classes.

Even worse: it seems that the ParsedBusinessScheduleReq object does not properly generate the required fields. Below is the used class. Take a look at the **required** field which is absent for the ParsedBusinessScheduleReq object.
```kt
@ApiModel(value = "ParsedBusinessSchedule")
data class OpeningHours(
    val daysInWeek: List<WeeklyOpeningHours> = emptyList(),
    val daysInYear: List<YearlyOpeningHours> = emptyList(),
    val winterSeason: WinterSeason? = null,
    val closedOnHoliday: Boolean = true
)
```

```json
{
  "ParsedBusinessSchedule": {
    "type": "object",
    "required": [
      "closedOnHoliday",
      "daysInWeek",
      "daysInYear"
    ],
    "properties": {
      "closedOnHoliday": {
        "type": "boolean"
      },
      "daysInWeek": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/WeeklyOpeningHours"
        }
      },
      "daysInYear": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/YearlyOpeningHours"
        }
      },
      "winterSeason": {
        "$ref": "#/definitions/WinterSeason"
      }
    }
  },
  "ParsedBusinessScheduleReq": {
    "type": "object",
    "properties": {
      "closedOnHoliday": {
        "type": "boolean"
      },
      "daysInWeek": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/WeeklyOpeningHoursReq"
        }
      },
      "daysInYear": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/YearlyOpeningHoursReq"
        }
      },
      "winterSeason": {
        "$ref": "#/definitions/WinterSeasonReq"
      }
    }
  },
  "ParsedBusinessScheduleRes": {
    "type": "object",
    "required": [
      "closedOnHoliday",
      "daysInWeek",
      "daysInYear"
    ],
    "properties": {
      "closedOnHoliday": {
        "type": "boolean"
      },
      "daysInWeek": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/WeeklyOpeningHoursRes"
        }
      },
      "daysInYear": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/YearlyOpeningHoursRes"
        }
      },
      "winterSeason": {
        "$ref": "#/definitions/WinterSeasonRes"
      }
    }
  }
}
```

 - [ ] Question. Is this a question about how to do a certain thing? Not sure if this is a bug or feature, couldn't find any docs on that.

**Comment by dilipkrish** [comment]
Thanks for reporting, Not sure what's going on, could you share the operation signature that use these classes as well? I suspect that the Kotlin module is rendering properties that are differentiating the models. 

Keep in mind that if the request is different from the response (recursive properties included) then the whole tree is different.

**Comment by BernhardPosselt** [comment]
That one generates the ParsedBusinessScheduleReq:

```kt
    @PostMapping("/businessareasopeninghours")
    fun updateOpeningHoursForBusinessAreas(
        @RequestBody idsAndHours: OpeningHours
    ): ResponseEntity<Void>
```

That one the ParsedBusinessSchedule:

```kt
    @GetMapping("/cooperatives/{cooperativeId}/locations/{locationId}/businessareas/{businessAreaId}")
    fun getBusinessArea(
        @CooperativeId @PathVariable("cooperativeId") cooperativeId: String,
        @LocationId @PathVariable("locationId") locationId: String,
        @IsLong @PathVariable("businessAreaId") businessAreaId: String
    ): BusinessArea

@JsonInclude(Include.NON_NULL)
data class BusinessArea(
    val openingHours: OpeningHours
)
```

**Comment by pitzcarraldo** [comment]
I have the same issue. Using a 3.0.0 version from release repository.

**Comment by pitzcarraldo** [comment]
@dilipkrish 
This class seems to be related to this issue.  
https://github.com/springfox/springfox/blob/e7f0a8fc7d23708f8ab3e90e3f3ed3f5b89b9f6a/springfox-spring-web/src/main/java/springfox/documentation/spring/web/scanners/DefaultModelNamesRegistryFactory.java#L129
Could you let me know what's the condition that is applied to this pattern?

**Comment by dilipkrish** [comment]
@pitzcarraldo The condition is when the request model differs from the response model (one has more/less properties than the other) then we distinguish the model as Req/Response

@BernhardPosselt It seems like WinterSeason, YearlyOpeningHours, WeeklyOpeningHours all have properties that differ between request and response, which is why OpeningHours/ParsedBusinessSchedule has a request response pair

**Comment by BernhardPosselt** [comment]
@dilipkrish nope, they are exactly the same.

**Comment by larsgroeber** [comment]
We have the same issue. We recently switched to version 3.0.0 and use spring-boot 2.3.4 together with kotlin 1.4.10.
The following contrived example generated a `AnalysisPortfolioReq` and `AnalysisPortfolioRes` schema.
```kotlin
@ApiOperation(value = "testAnalysisPortfolios", notes = "Returns all AnalysisPortfolio entities.")
@PostMapping(path = ["/portfolios"], produces = [MediaType.APPLICATION_JSON_VALUE])
fun testAnalysisPortfolios(@RequestBody model: AnalysisPortfolio): ResponseEntity<AnalysisPortfolio> {
    return ResponseEntity.ok(AnalysisPortfolio());
}
```
```kotlin
@ApiModel(value = "AnalysisPortfolio", description = "")
class AnalysisPortfolio(
    @ApiModelProperty(required = true)
    var id: Long? = null,

    var test: AnalysisBattery? = null,
)

@ApiModel(value = "AnalysisBattery", description = "")
class AnalysisBattery(
    @ApiModelProperty(required = true)
    var id: Long? = null,
)
```
Removing the `@RequestBody` or the `test` property on the model fixes the issue. So I guess the tree generation might not work correctly using the sources generated by kotlin?

**Comment by larsgroeber** [comment]
During testing we noticed that adding `@ApiModelProperty` to every property also fixes the issue.

**Comment by jens-krogsboll** [comment]
I am seeing this problem as well after upgrading to 3.0.0. I have not been able to confirm that adding @ApiModelProperty rigorously solves my problem. Instead I have had success replacing all @RequestBody annotations with a corresponding RequestEntity<MyModel> - eg.

This works:
```
public ResponseEntity<BasketResponse> setOrderContactInfo(
   @ApiParam(value = "Conctact information for the order.", required = true)
   final RequestEntity<OrderContactInfo> contactInfo) {
 }
```

This does not:
```
public ResponseEntity<BasketResponse> setOrderContactInfo(
   @ApiParam(value = "Conctact information for the order.", required = true)
   @RequestBody final OrderContactInfo contactInfo) {
 }
```
Though this can be used as a workaround it is not optimal as it changes the type of the contactInfo parameter and thus requires changes in the method body as well.

**Comment by devstructor** [comment]
Also having this issue. Sometimes we use the same ObjectDTO type on input and output. On 3.0.0 version ObjectDTORes and ObjectDTOReq definitions are generated. While on 2.9.2 there was only one definition (only ObjectDTO)

**Comment by jens-krogsboll** [comment]
The workaround I posted earlier (https://github.com/springfox/springfox/issues/3487#issuecomment-706133266) only solved the original 3-class problem. But another problem - also related to request body and response body sharing models - is not solved: It turns out that the api being described in such cases features individual operation parameters for each property in the request body - instead of the previous single request body object parameter - as well as some strange apparently generic parameters named "method", "type" and "url" ???. This is absolutely horrible - I am going to downgrade to 2.9 :-(

**Comment by jens-krogsboll** [comment]
A colleague of mine has pointed out that it is actually my workaround that introduces the individual request body properties as parameters in the api. He also discovered that the 3-class problem stems from the fact that one of my models appearing in both request and response has a read only property in the form of a getter deriving a value from other properties, making it effectively different in request and response. By simply adding a dummy setter for this property the 3-class problem disappeared.

**Comment by aspich** [comment]
@dilipkrish The main issue with the Req/Res approach is that it forces all models to have getters and setters. And this is not  a valid assumption as there are other ways of creating beans such the example below using constructors

```
public class Sorting {
    public Integer index;
    public Direction direction;
    @JsonCreator
    public Sorting(@JsonProperty("index") Integer index, @JsonProperty("direction") Direction direction) {
        this.index = index;
        this.direction = direction;
    }
    public Integer getIndex() {
        return index;
    }
    public Direction getDirection() {
        return direction;
    }
}
```

Maybe this decision could be based on some configuration, to let each consumer to decide whether create the req/res automatically depending on their API.

**Comment by nedge** [comment]
There doesn't seem to be a consensus as to how to fix this or make 3.0.0 compatible with e.g. 2.9.2. 
We've reverted to 2.9.2 for the time being

**Comment by BernhardPosselt** [comment]
This is still an issue.

**Comment by krisgerhard** [comment]
It's causing a lot of discomfort for us still. Could someone address this issue?

**Comment by npaul-cs** [comment]
Label > `waiting-for-more-info`  
What else information do you need on this?

**Comment by ericklemos** [comment]
This is still an issue.

**Comment by ghost** [comment]
> The main issue with the Req/Res approach is that it forces all models to have getters and setters. And this is not a valid assumption as there are other ways of creating beans such the example below using constructors

I have a simlar problem using Kotlin with a data class.

My class looks something like this:

```kotlin
data class SomeClass(
    override val propertyA: String,
    override val propertyB: String,
    @field:SomeAnnotation
    override val propertyC: String,
) : SomeInterface
```

Since all my properties are readonly, I guess that SpringFox differentiates between Request and Response model. But I am not definitely sure though. In the model section of the Swagger-UI, the Req and the Res version are completely identical.

**Comment by krisgerhard** [comment]
This is still an issue.

**Comment by porfirioribeiro** [comment]
I found a way to hotfix this in my projects:
```kotlin
/**
 * Fixes springfox bug: https://github.com/springfox/springfox/issues/3487
 * Where it generates ModelReq/ModelRes when we use the same model on @RequestBody and response
 */
@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
class SwaggerName : ModelNamesRegistryFactoryPlugin {
  val factory = DefaultModelNamesRegistryFactory()

  override fun modelNamesRegistry(registry: ModelSpecificationRegistry): ModelNamesRegistry =
    Registry(factory.modelNamesRegistry(registry))

  override fun supports(dt: DocumentationType) = true

  private class Registry(private val registry: ModelNamesRegistry) : ModelNamesRegistry {
    private val re = Regex("(Req|Res)?$")
    override fun modelsByName(): Map<String, ModelSpecification> =
      registry.modelsByName()
        .mapKeys { re.replace(it.key, "") }
        .mapValues {
          ModelSpecificationBuilder().copyOf(it.value).facets { f -> f.title(it.key) }.build()
        }

    override fun nameByKey(key: ModelKey?): Optional<String> =
      registry.nameByKey(key).map { re.replace(it, "") }
  }
}
```

It's really sad to see that this library is not being developed anymore.

**Comment by fzyzcjy** [comment]
Same problem here. This bug occurs when I migrate from Java to Kotlin (using same Spring Boot and Springfox, of course)

**Comment by fzyzcjy** [comment]
Here is another hack without using Regex and a bit shorter:

```kotlin
@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
class SwaggerFixReqResPostfix(val delegate: DefaultModelNamesRegistryFactory = DefaultModelNamesRegistryFactory()) :
    ModelNamesRegistryFactoryPlugin by delegate {

    override fun modelNamesRegistry(registry: ModelSpecificationRegistry): ModelNamesRegistry =
        delegate.modelNamesRegistry(HackModelSpecificationRegistry(registry))

    class HackModelSpecificationRegistry(delegate: ModelSpecificationRegistry) :
        ModelSpecificationRegistry by delegate {
        // HACK
        override fun hasRequestResponsePairs(test: ModelKey?) = false
    }
}
```

**Comment by wattazoum** [comment]
Java version of the Hack by @fzyzcjy  (included in a spring Swagger configuration class)

``` java
    @Bean
    @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
    public ModelNamesRegistryFactoryPlugin swaggerFixReqResPostfix() {
        return new DefaultModelNamesRegistryFactory() {
            @Override
            public ModelNamesRegistry modelNamesRegistry(ModelSpecificationRegistry registry) {
                return super.modelNamesRegistry(hackModelSpecificationRegistry(registry));
            }

            private ModelSpecificationRegistry hackModelSpecificationRegistry(ModelSpecificationRegistry delegate) {
                return new ModelSpecificationRegistry() {
                    @Override
                    public ModelSpecification modelSpecificationFor(ModelKey key) {
                        return delegate.modelSpecificationFor(key);
                    }

                    @Override
                    public boolean hasRequestResponsePairs(ModelKey test) {
                        return false;
                    }

                    @Override
                    public Collection<ModelKey> modelsDifferingOnlyInValidationGroups(ModelKey test) {
                        return delegate.modelsDifferingOnlyInValidationGroups(test);
                    }

                    @Override
                    public Collection<ModelKey> modelsWithSameNameAndDifferentNamespace(ModelKey test) {
                        return delegate.modelsWithSameNameAndDifferentNamespace(test);
                    }

                    @Override
                    public Set<ModelKey> modelKeys() {
                        return delegate.modelKeys();
                    }
                };
            }

        };
    }

```

**Comment by ghost** [comment]
For those still waiting for a fix, have a look at [https://springdoc.org/](https://springdoc.org/). It might be a replacement for springfox for some of you.
