### ISSUE TITLE
NotBlankAnnotationPlugin  and NotNullAnnotationPlugin order   before ApiModelPropertyPropertyBuilder is bad idea.

### ISSUE THREAD

**Issue by leerenbo** [springfox/springfox#3489]
NotBlankAnnotationPlugin  and NotNullAnnotationPlugin order  before ApiModelPropertyPropertyBuilder is bad idea.

ApiModelPropertyPropertyBuilder overwrite require which make NotBlankAnnotationPlugin/NotNullAnnotationPlugin not work。
 
@Order can't be change manually。So i have to write NotBlankAnnotationPlugin2 ，NotNullAnnotationPlugin2, plugin twice before and after 。

Maybe add Ordered interface and let user controller is better.

**Comment by dilipkrish** [comment]
Out of curiosity, why isn't the ApiModelPropertyBuilder working? It is designed to be a arbiter of ambiguity. As in anything that cannot be inferred the Swagger annotations are a way to have the last say. Depending your answer I might have some suggestions.

**Comment by leerenbo** [comment]
@dilipkrish 
I think , Reality or Code has the last say。Document describes reality。Swagger/Springfox make document writing easy , which is very well done. I love plugin design.

**Code say @NotNull that make param required and validated**,defualt (required=false) should overwrite by @NotNull.

Too lazy to write required=true,that make me read a lot of codes. I write document base reality,less ApiModelProperty is better.

**Comment by rxxy** [comment]
> NotBlankAnnotationPlugin and NotNullAnnotationPlugin order before ApiModelPropertyPropertyBuilder is bad idea.
> 
> ApiModelPropertyPropertyBuilder overwrite require which make NotBlankAnnotationPlugin/NotNullAnnotationPlugin not work。
> 
> @order can't be change manually。So i have to write NotBlankAnnotationPlugin2 ，NotNullAnnotationPlugin2, plugin twice before and after 。
> 
> Maybe add Ordered interface and let user controller is better.


I found a way to change the order value with a dynamic proxy class，can also be used to temporarily solve problems.

```java
    @Bean
    public ParameterBuilderPlugin notBlankAnnotationPlugin(){
        NotBlankAnnotationPlugin notBlankAnnotationPlugin = new NotBlankAnnotationPlugin();
        InvocationHandler invocationHandler = new InvocationHandler() {
            @Override
            public Object invoke(Object o, Method method, Object[] objects) throws Throwable {
                System.out.println("execute proxy... " + method.getName());
                if (method.equals(ReflectUtil.getMethodByName(Ordered.class, "getOrder"))){
                    return Integer.MAX_VALUE - 1;
                }
                return method.invoke(notBlankAnnotationPlugin, objects);
            }
        };
        return (ParameterBuilderPlugin)Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{Ordered.class, ParameterBuilderPlugin.class}, invocationHandler);
    }
```
