### ISSUE TITLE
swagger 3.0 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by qmdx** [springfox/springfox#3511]
springfox.documentation.schema.Example 

java.lang.NullPointerException: null

```
[ERROR] 2020-08-22 15:15:40,491 - (AbstractDocumentationPluginsBootstrapper.java:98) - Unable to scan documentation context default
java.lang.NullPointerException: null
	at springfox.documentation.schema.Example.equals(Example.java:131) ~[springfox-core-3.0.0.jar:3.0.0]
	at java.util.Objects.equals(Objects.java:59) ~[?:1.8.0_231]
	at springfox.documentation.service.RequestParameter.equals(RequestParameter.java:132) ~[springfox-core-3.0.0.jar:3.0.0]
	at java.util.HashMap.putVal(HashMap.java:635) ~[?:1.8.0_231]
	at java.util.HashMap.put(HashMap.java:612) ~[?:1.8.0_231]
	at java.util.HashSet.add(HashSet.java:220) ~[?:1.8.0_231]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_231]
```

![1111](https://user-images.githubusercontent.com/1481125/90951133-73f0c480-e48a-11ea-87d5-f19d7429d40a.png)

**Comment by dilipkrish** [comment]
The snapshot versions are published, just not to maven central.

**Comment by mapway** [comment]
when to publish to maven central

**Comment by patrickbray** [comment]
I have also run into this issue and would appreciate any updates on target publish date to maven central. Or any workarounds?

**Comment by luojinbai** [comment]
I have also run into this issue and would appreciate any updates on target publish date to maven central. Or any workarounds?

**Comment by blankhang** [comment]
> I have also run into this issue and would appreciate any updates on target publish date to maven central. Or any workarounds?

i have the same issue. plz publish 3.0.1 to the maven central ASAP!

**Comment by MilkWangStudio** [comment]
I also meet the issue, plz publish a fix version!

**Comment by ThxGodNovember** [comment]
I also meet the issue, plz publish a fix version!

**Comment by yqw2023** [comment]
I also meet the issue, plz publish a fix version!

**Comment by dchecheb** [comment]
I also meet the issue, plz publish a fix version!

**Comment by olivergg** [comment]
Apart from waiting for the release of 3.0.1, is there any workaround for this ? Is it related to the presence of "example" in the request param  ?

>  The snapshot versions are published, just not to maven central.

Where then ? jcenter.bintray.com has been closed for a while (and it is referenced in the springfox documentation as the main repository). Moreover, for snapshots releases it seems to be hosted on https://oss.jfrog.org, but how do you access it ? Is it even publicly accessible ? 
Is there any way to build the 3.0.1-SNAPSHOT locally, I can't find any branch or tag for the ongoing development.

Thanks in advance for your response

**Comment by stolario** [comment]
So, what's the fix for year 2023?

**Comment by Restlol** [comment]
We can define the same package named `springfox.documentation.schema` ,and define a java file named `Example` in our project   just copy this code into the java file 
`https://github.com/springfox/springfox/blob/master/springfoxcore/src/main/java/springfox/documentation/schema/Example.java`
the problem will be solved
