### ISSUE TITLE
使用3.0.0版本后文件类型不能识别， MultipartFile不在页面上提供上传按钮 After using version 3.0.0, the file type is not recognized, and MultipartFile does not provide an upload button on the page

### ISSUE THREAD

**Issue by YAGAMIL** [springfox/springfox#3513]
在2.9.2及之前的版本不可以引入webflux，
但现在又可以支持
<repository>
            <id>jcenter-snapshots</id>
            <name>jcenter</name>
            <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
        </repository>
版本原本的额3.0.0-SNAPSHOT被大量修改，导致我重新import时无法编译通过不得不切换版本
让我不得不怀疑你们是否在更改发布在maven中的代码

**Comment by dilipkrish** [comment]
This is a known issue. I'll link to the actual issue here
