### ISSUE TITLE
How to custom scan package path

### ISSUE THREAD

**Issue by bbqtk** [springfox/springfox#3524]
I tried to use the new dependency. There were some problems in the previous project. I am not sure whether the current configuration can support it.

```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-boot-starter</artifactId>
    <version>3.0.0</version>
</dependency>
```

There are multiple @Api annotation-modified Controllers in my project, but some third-party jar packages also have Controllers decorated with @Api annotations. I don’t want to scan and display the interfaces in these third-party jar packages. At present, I have not found a way to exclude it.

```java
return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .select()
                .apis(Predicates.or(Swagger2Config.basePackage("com.dnkj.smart.controller"), Swagger2Config.basePackage("com.dnkj.digital.controller")))
                .paths(PathSelectors.any())
                .build()
        	.globalOperationParameters(pars);
```

I want to be able to set the scan package path by myself like in the above configuration.

**Comment by dilipkrish** [comment]
Are the predicates not working? Why aren't you using `RequestHandlerSelectors.handlerPackage("com.dnkj.smart.controller")` instead?

**Comment by bbqtk** [comment]
- Sorry, I may not express it clearly. My question is actually whether springfox-boot-starter provides a configuration similar to 
```
springfox.handlerPackage = com.dnkj.smart.controller
```
 to quickly configure the scan package, so that I don’t have to configure it through javaconfig.

- At present, I still achieved it through the original configuration method

```java
@Bean
    public Docket swaggerDocket() {
        return new Docket(DocumentationType.OAS_30)
                .enable(enableSwagger)
                .select()
                .apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))
                .paths(PathSelectors.regex("/api/v1/.*"))
                //.paths(PathSelectors.any())
                .build();
                //.groupName("rest");
    }
```

- Of course, your configuration method can also achieve the same effect

**Comment by bbqtk** [comment]
If the current dependency clearly cannot use this function quickly, I decide to turn off this
