### ISSUE TITLE
Spring Boot and SpringFox Swagger  - bean RepositoryRestConfiguration not found

### ISSUE THREAD

**Issue by gerbirn** [springfox/springfox#3528]
During startup of the application the app failed with:

Parameter 0 of constructor in springfox.documentation.spring.data.rest.BasePathAwareServicesProvider required a bean of type 'org.springframework.data.rest.core.config.**RepositoryRestConfiguration**' that could not be found.

I am using io.springfox.springfox-boot-starter:3.0.0 (following the[ migration instructions](https://springfox.github.io/springfox/docs/current/) )and Spring Boot 2.2.2.Release.

Tried with and without: SwaggerConfiguration, @EnableSwagger2 annotation

Detailed Exception is:
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'documentationPluginsBootstrapper' defined in URL [jar:file:/....jar!/BOOT-INF/lib/springfox-spring-web-3.0.0.jar!/springfox/documentation/spring/web/plugins/DocumentationPluginsBootstrapper.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'basePathAwareServicesProvider' defined in URL [jar:file:/....jar!/BOOT-INF/lib/springfox-data-rest-3.0.0.jar!/springfox/documentation/spring/data/rest/BasePathAwareServicesProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.data.rest.core.config.RepositoryRestConfiguration' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by gerbirn** [comment]
Solution: remove
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>

**Comment by dilipkrish** [comment]
Is there are a version of the repo you can share. Consuming applications having to remove those dependencies doesn't seem right

**Comment by gabrielperes97** [comment]
I have the same problem, but I can't remove the spring-boot-starter-data-rest because I use Rest Repositories. How can I handle this?

**Comment by gabrielperes97** [comment]
I've made this repo to show this error 
https://github.com/gabrielperes97/rest-repositories-springfox-bug
