### ISSUE TITLE
Unable to override the inferred server url when using springfox with a proxy

### ISSUE THREAD

**Issue by rowleyn** [springfox/springfox#3531]
What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
Latest, 3.0.0

What kind of issue is this?

Question. Is this a question about how to do a certain thing? 
I'm using springfox with an api that is behind a proxy. The proxy requires that the api have its address set to the local loopback address (127.0.0.1). Because of this, springfox is inferring the server url as https://127.0.0.1:443, instead of the actual url of the api. This causes requests sent from the swagger ui to fail, because they are being sent to local loopback instead of to the actual public api address. How can I override the inferred url to point the swagger ui at the correct address?

**Comment by dilipkrish** [comment]
Couple of things here
- Are you using the x-forward headers as recommended by spring in your proxy?
- Have you see the other issues where you have a work around available?

**Comment by rowleyn** [comment]
Our issue is not a base path issue, but a case of being unable to set the server url. We tried to override it using the servers method on the Docket class, but it seems that is bugged as per [#3483 ](https://github.com/springfox/springfox/issues/3483). Our paths after the server url are just fine.

**Comment by dilipkrish** [comment]
Yeah, until the fix is out [this is a work around](https://github.com/springfox/springfox/issues/3445#issuecomment-664967822)

**Comment by rowleyn** [comment]
The workaround worked, except I needed to use `WebMvcOpenApiTransformationFilter` instead because we are upgraded to Open Api. Also, I'm using it to set the server of the swagger docs, not the base path.

In Java:
```
@Component
  public class SpringfoxSwaggerHostResolver implements WebMvcOpenApiTransformationFilter {

    @Value("${swagger.host}") String hostUri;

    @Override
    public OpenAPI transform(OpenApiTransformationContext<HttpServletRequest> context) {
      OpenAPI swagger = context.getSpecification();
      Server server = new Server();
      server.setUrl(hostUri);
      swagger.setServers(Arrays.asList(server));
      return swagger;
    }

    @Override
    public boolean supports(DocumentationType docType) {
      return docType.equals(DocumentationType.OAS_30);
    }
  }
```

**Comment by zhugw** [comment]
I think just add this config could work 
```
 proxy_set_header Host $host;
```
and you also could dynamically substitute servers url of `/v3/api-docs` e.g

```
location /v3/api-docs {
    proxy_pass http://XXX:8081/v3/api-docs;
    sub_filter 'http://XXX' 'https://YYY';
    sub_filter_types application/json;
}
```
