### ISSUE TITLE
Upgrading to springfox-boot-starter version 3 causes spring error

### ISSUE THREAD

**Issue by tj-noronha** [springfox/springfox#3532]
I have recently tried to upgrade my spring project to spring-fox-boot-starter version 3.0.0

perviously i had the following dependencies:
  ```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.9.2</version>
</dependency>
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>2.9.2</version>
</dependency>
<dependency>
    <groupId>io.swagger.core.v3</groupId>
    <artifactId>swagger-core</artifactId>
    <version>2.0.8</version>
    <exclusions>
        <exclusion>
            <artifactId>jackson-databind</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
        </exclusion>
    </exclusions>
</dependency>
  ```

Whilst trying to move to the new version, I followed the instructions of commenting out all references to "@EnableSwagger2" and I also removed the 2 io.springfox dependencies. My dependencies are now as follows:
  ```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-boot-starter</artifactId>
    <version>3.0.0</version>
</dependency>
<dependency>
    <groupId>io.swagger.core.v3</groupId>
    <artifactId>swagger-core</artifactId>
    <version>2.1.4</version>
    <exclusions>
        <exclusion>
            <artifactId>jackson-databind</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
        </exclusion>
    </exclusions>
</dependency>
  ```

However, I seem to be getting the following issue....

The following classes could not be excluded because they are not auto-configuration classes:
- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguation
- org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
- org.springframework.boot.autoconfigure.orm.jpa.HibernateJpAutoConfiguration
at org.springframework.boot.autoconfigure.AutoonfigurationImportSelctor.handleInvalidExcludes(AutoConfigurationImportSelector.java.:223)

**Comment by dilipkrish** [comment]
Id recommend removing the swagger-core dependency altogether, since it springfox comes with the right dependency. However Im not sure why you're seeing the autoconfiguraiton issue. Could you share your project or perhaps a test project?

**Comment by tj-noronha** [comment]
[SwaggerTest.zip](https://github.com/springfox/springfox/files/5182052/SwaggerTest.zip)
