### ISSUE TITLE
ReferenceModelSpecificationToPropertyConverter Error log when missing 200 return code

### ISSUE THREAD

**Issue by arey** [springfox/springfox#3546]
Hi,

I have upgraded springfox from 2.9.2 to 3.0.0. I'm now using the Spring Boot starter for Springfox.
I've got a non blocking error log when Swagger UI is loading;
```
2020-09-09 09:30:16.265 ERROR 42536 — [nio-9090-exec-6] nceModelSpecificationToPropertyConverter : Unable to find a model that matches key ModelKey{qualifiedModelName=ModelName {namespace='java.lang', name='Void'}
, viewDiscriminator=null, validationGroupDiscriminators=[], isResponse=true}
```

It happens when my PUT API just return a 204 HTTP code:
```
@ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Resource updated") })
```

Temporary, I've patch my API by adding a code 200:
```
@ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Fix springfox issue"),
        @ApiResponse(code = 204, message = "Resource updated") })
```
Could you please help me to qualify this issue?

**Comment by florian-fischer-swarm** [comment]
I have the same problem, however the workaround does not help for me.
Something like:

`  
@ApiResponses(value = {
@ApiResponse(code = 204, message = "Expected response to a valid request"),
@ApiResponse(code = 500, message = "unexpected error", response = Error.class) })
@RequestMapping(value = "/path/{id}", produces = { "application/json" }, method = RequestMethod.DELETE)

ResponseEntity<Void> method( UUID sometId);
`
results in 
 ERROR: Unable to find a model that matches key ModelKey{qualifiedModelName=ModelName{namespace='java.lang', name='Void'}, viewDiscriminator=null, validationGroupDiscriminators=[], isResponse=true}

**Comment by florianfischerx** [comment]
But ... that's quite clearly a bug.

**Comment by gilvangobbato** [comment]
I'm getting this error too when I open my request on http://localhost:8080/swagger-ui/index.html

`Resolver error at paths./v1/endereco/{cep}.get.responses.500.schema.$ref
Could not resolve reference: Could not resolve pointer: /definitions/Error-ModelName{namespace='br.com.corporacaoti.endereco.provider.presentation.dto', name='ErroNegocioDTO'} does not exist in document`

``` yml
    ErroNegocio:
      type: object
      properties:
        statusCode:
          type: integer
        statusMessage:
          type: string
        dateTime:
          type: string
          format: date-time
```

**Comment by JamesHare** [comment]
@arey @florian-fischer-swarm

I was running into this same issue and resolved it. It was occurring because I was returning `ResponseEntity<Void>` in my method signature but was specifying that I was producing a json in my RequestMapping annotation `@RequestMapping(value = "/{something}", produces = { "application/json" }, method = RequestMethod.DELETE)`.

@arey , you didn't post your method signature so I'm not sure if this is the problem. @florian-fischer-swarm it's worth looking into removing the "produces" attribute as it may resolve your particular issue.

Hope that helps.

**Comment by arey** [comment]
@JamesHare my issue comes too from the `ResponseEntity<Void>` returning type.
The Java code is generated `openapi-generator-maven-plugin`  from this openapi 3.0.2 spec :
```
  post:
    operationId: operation
    responses:
      "200":
        description: abc
      "401":
        description: abc
      "403":
        description: abc
      "404":
        description: abc
        content:
          application/json:
            schema:
              $ref: "xyz/common.yaml#/error"
      "500":
        description: Erreur interne du serveur
```
For a 200 error code, the REST API return no body.
For an erreur, we are returning a `application/json` body through an `@ControllerAdvice`.

**Comment by fisco-unimatic** [comment]
If you expect to return 204, then you should add `@ResponseStatus(HttpStatus.NO_CONTENT)`. Otherwise, SpringFox assumes the expected response is 200.

**Comment by arey** [comment]
You're right @fisco-unimatic. There is maybe a design issue. We could fix it in the next major version. The problem is that we couldn't add any annotation because the code is generated.
