### ISSUE TITLE
Question: How to provide a model substitute for java.time.LocalTime?

### ISSUE THREAD

**Issue by abuechler** [springfox/springfox#3547]
The [documentation](http://springfox.github.io/springfox/docs/current/#answers-to-common-questions-and-problems) suggests to map java.**util**.LocalDate to java.sql.Date. This seems not work for java.**time**.LocalDate. Adding a model substitute:

`
docket.directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
`

Still gives me the error

`
ReferenceModelSpecificationToPropertyConverter - Unable to find a model that matches key ModelKey{qualifiedModelName=ModelName{namespace='java.time', name='LocalDate'}, viewDiscriminator=null, validationGroupDiscriminators=[], isResponse=true}
`

How can I add a mapping for it?

Using Springfox 3.0.0 and Spring Boot 2.3.3.

**Comment by shollander** [comment]
I get a similar error when using `docket.directModelSubstitute()` with other classes also. This error seems to have started ocurring when I upgraded to Springfox 3.0.0. I was able to use the same exact `docket.directModelSubstitute()` call with Springfox 2.9.2 without any problems.

Note this error only occurs when I hit the `/swagger-ui/ ` page.

**Comment by abuechler** [comment]
@dilipkrish or @adrianbk: Maybe you can provide some hints here?

**Comment by YBCoding** [comment]
@abuechler 
After taking time and reading the source code. I have found a solution : 
`       ResolvedType o = typeResolver.resolve(List.class, LocalDate.class);
        ResolvedType t = typeResolver.resolve(List.class, java.sql.Date.class);
        AlternateTypeRule rule = AlternateTypeRules.newRule(o, t);`
        
 Add this rule to your Docket 
 `new Docket(DocumentationType.OAS_30)
                .groupName("public")
                .directModelSubstitute(LocalDate.class, java.sql.Date.class)
                .directModelSubstitute(LocalDateTime.class, java.util.Date.class)
                .alternateTypeRules(rule)
                ....omited`

**Comment by ssimm** [comment]
reopened (#3879)
