### ISSUE TITLE
Aggregating SwaggerResource generates wrong url at Spring Cloud Gateway / Zuul 

### ISSUE THREAD

**Issue by xomidar** [springfox/springfox#3559]
I have multiple spring boot services with swagger enabled. 
for example

1. customer-service
API e.g. http://{server-ip}:{port}/customer ✅

2. merchant-service
API e.g  http://{server-ip}:{port}/merchant ✅

I aggregated all microservice swagger by SwaggerResource at Spring Cloud Gateway
```java

  @Primary
  @Bean
  public SwaggerResourcesProvider swaggerResourcesProvider() {
    return ()->{
      SwaggerResource swaggerResource = new SwaggerResource();
      swaggerResource.setLocation("/customer-service/v3/api-docs?group=Customer Service 0.0.1-SNAPSHOT");
      swaggerResource.setName("Customer Service 0.0.1-SNAPSHOT");
      swaggerResource.setSwaggerVersion("3.0.3");
      swaggerResource.setUrl("/customer-service/v3/api-docs?group=Customer Service 0.0.1-SNAPSHOT");
      return Collections.singletonList(swaggerResource);
    };
  }
```

**2.9.2 - Swagger 2 - generates expected URL (at Zuul)** 
http://{gateway-server-ip}:{port}/customer-service/customer✅
http://{gateway-server-ip}:{port}/merchant-service/merchant ✅

**3.0.0 - Swagger 2 - generates expected URL (at Zuul)**
http://{gateway-server-ip}:{port}/customer-service/customer✅
http://{gateway-server-ip}:{port}/merchant-service/merchant ✅

**3.0.0 - Open API - generates wrong URL (at Zuul / Gateway)**
http://{gateway-server-ip}:{port}/customer❌
http://{gateway-server-ip}:{port}/merchant ❌

at version 3.0.0
For docket configuration `DocumentationType.SWAGGER_2` URL generates as expected 
For docket configuration `DocumentationType.OAS_30` generates **wrong** URL.

```java
  @Bean
  public Docket api() {
    return new Docket(DocumentationType.OAS_30)
        .groupName(buildProperties.getName() + " " + buildProperties.getVersion())
        .select()
        .paths(PathSelectors.any())
        .build()
        .apiInfo(
            new ApiInfoBuilder()
                .build());
  }
```
is there any workaround to override generated server url from **SwaggerResource** at version 3.0.0 (DocumentationType.OAS_30) ?

**Comment by LuisAlfonsoPonce** [comment]
I had this same problem, you can generate the documentation correctly as follows

 swaggerResource.setLocation("/customer-service/**v2**/api-docs?group=Customer Service 0.0.1-SNAPSHOT");
 swaggerResource.setUrl("/customer-service/**v2**/api-docs?group=Customer Service 0.0.1-SNAPSHOT");

you can try to move the @RequestMapping or stripPrefix: false in yml zuul but don´t work
