### ISSUE TITLE
Unable to disable springfox-data-rest in Spring Boot application

### ISSUE THREAD

**Issue by benwarfield-usds** [springfox/springfox#3562]
I am trying to upgrade a Spring Boot project to SpringFox 3.0.0. The project uses Spring Data Rest for admin access to the database, and has a small API that does most of the day-to-day work. Following the upgrade instructions (using springfox-boot-starter 3.0.0), I find that springfox-data-rest (though still marked "incubating" in the main docs) is activated unconditionally. Since it does not actually appear to work very well with my Spring Data setup, I don't particularly want to use it—is there a way I haven't seen to disable it? Or should I ignore the starter module and just set up as if I were running a non-boot Spring MVC application?

I would be happy to attempt a pull request to make it property-configurable, but I don't want to start such a thing and discover I'm barking up the wrong tree. 🙂

**Comment by eidottermihi** [comment]
I was also stumbling about this issue and would appreciate an option to opt-out if using the spring boot starter module.
