### ISSUE TITLE
3.0.0 @ApiModel note doesn't work

### ISSUE THREAD

**Issue by dictionaryshi** [springfox/springfox#3571]
![image](https://user-images.githubusercontent.com/33995567/93769782-e7365380-fc4d-11ea-94f0-eb9efdb1f93c.png)

![image](https://user-images.githubusercontent.com/33995567/93769811-f3221580-fc4d-11ea-8d75-a69515b189fe.png)

![image](https://user-images.githubusercontent.com/33995567/93769859-0208c800-fc4e-11ea-8fee-fd3ef8d3182b.png)

**Comment by revkov** [comment]
@dictionaryshi  Use tags and description params

**Comment by dictionaryshi** [comment]
> @dictionaryshi Use tags and description params

According to what you said, I tried, but it still doesn't work.

**Comment by DoraemonAndRat** [comment]
Example and description for @requestpart #3527
https://github.com/springfox/springfox/issues/3527

And it also has some problems when using @ApiParam.
When media type is multipart/form-data,

@ApiParam(value="my description") doesn't show description in swagger ui,
however @ApiParam(name="my description") did work.

`   @PostMapping(value = "/uploadPhoto",consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @ApiOperation(value="uploadPhoto")
    public JsonResult uploadPhoto(
                                          @ApiParam(name = "description showed") @RequestPart String param1,
                                          @ApiParam(value = "description doesn't show") @RequestPart String param2,
                                          ) throws IOException {
        
    }`

**Comment by lmpampaletakis** [comment]
I also submit a multipart form with an object that contains fields including upload field and the order and required attributes are ignored at swagger-ui.

**Comment by RicardoAlvaro88** [comment]
Hi there,
Is there any plan to fix this issue in next release?
