### ISSUE TITLE
Documentation for springfox-boot-starter

### ISSUE THREAD

**Issue by manolan1** [springfox/springfox#3575]
Referring to the current documentation (http://springfox.github.io/springfox/docs/current/):

Section 2.1.1 and 2.1.2 show how to use springfox-boot-starter: 3.0.0.

Section 2.1.3 says "Remove the @EnableSwagger2 annotations" and "Springfox 3.x removes dependencies on guava and other 3rd party libraries".

Section 3.1 shows some code with @EnableSwagger2 and then says "This library extensively uses googles guava library."

Am I to conclude that section 2 is the only one updated with the new dependency and section 3.1 is out of date? Or is there an error in section 2 and the annotation is still required? What about the rest of the documentation? Can I trust any of it now?

Incidentally, section 2.1 says "Below outlines how to include the springfox-swagger2 module which produces Swagger 2.0 API documentation". This may be slightly misleading, though it *is* what gets included transitively. I would not even point this out were it not for the other points. The way it is phrased makes me wonder if it is also not updated.

**Comment by CovenantObserver** [comment]
the same problem.

**Comment by ypkkhatri** [comment]
Same problem, documentation is totally confused

**Comment by ypkkhatri** [comment]
Any update?
