### ISSUE TITLE
Graalvm native image failure "@Configuration classes need to be marked as proxyBeanMethods=false"

### ISSUE THREAD

**Issue by sendev1** [springfox/springfox#3577]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
2.9.2

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 
while creating windows native image using Oracle graalvm during image compilation phase following error occurs and image building process stops.
```org.springframework.beans.factory.BeanDefinitionStoreException: @Configuration classes need to be marked as proxyBeanMethods=false. Found: [springfox.documentation.schema.configuration.ModelsConfiguration, springfox.documentation.spring.web.SpringfoxWebMvcConfiguration, springfox.documentation.swagger.configuration.SwaggerCommonConfiguration, springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration]```

Graal vm needs all @Configuration to use proxyBeanMethods=false

**Comment by mwiede** [comment]
FYI no need to set `proxyBeanMethods=false` any more using https://spring.io/blog/2020/11/23/spring-native-for-graalvm-0-8-3-available-now
