### ISSUE TITLE
Swagger does not mark not-nullable values as required

### ISSUE THREAD

**Issue by nik-lazer** [springfox/springfox#3585]
Hi,
  I am using:
- Spring Boot 2.3.4.RELEASE
- SpringFox 3.0.0
- Kotlin 1.4.10
- Open JDK 14.0.1

The issue is that numeric (Long, Int, double) not-nullable filelds in Kotlin Dtos are not marked with asterisk for request models, but marked correctly for response one:
![изображение](https://user-images.githubusercontent.com/1555606/94918218-c924ea80-04ba-11eb-8074-3a6a8d485327.png)

Of course, it is possible to use @ApiModelProperty(required = true), but it seems to be redundant, since Kotlin's declaration can be used for that.

My expectation would be that Swagger should document both input and output models in the same way.

There are couple of bit similar issues, which not exactly the same and pretty old:
- https://github.com/springfox/springfox/issues/2474
- https://github.com/springfox/springfox/issues/2308

Sample repository can be found [here](https://github.com/nik-lazer/kotlin-validation/tree/master)

**Comment by nik-lazer** [comment]
I do not think that closing this way makes sense. I is already frustrating enough that there is no reaction on the issue for 3 months already. Please remove the tag.

**Comment by RoXuS** [comment]
+1

**Comment by nik-lazer** [comment]
any updates?

**Comment by nik-lazer** [comment]
+

**Comment by nik-lazer** [comment]
+

**Comment by nik-lazer** [comment]
+

**Comment by nienienienie** [comment]
wtf is going on here?
