### ISSUE TITLE
Swagger UI requires unsafe-inline style-src CSP

### ISSUE THREAD

**Issue by lol768** [springfox/springfox#3587]
Please take the time to search the repository, if your question has already been asked or answered.

- [X] What version of the library are you using?

```
implementation("io.springfox:springfox-boot-starter:3.0.0")
```

Is it the latest version? 

**Yes**

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test.

https://github.com/springfox/springfox/blob/758113378de02fd339916f60810abc1d12bb547b/springfox-swagger-ui/src/web/swagger-ui.html#L11-L29

https://github.com/springfox/springfox/blob/758113378de02fd339916f60810abc1d12bb547b/springfox-swagger-ui/src/web/swagger-ui.html#L34

Are both incompatible with a strict CSP and require `style-src: unsafe-inline`, which is not acceptable from a security perspective.

**Comment by gdinant** [comment]
Any ETA on when this will be fixed?

**Comment by lol768** [comment]
#3726

Frankly I find these integrations to be disrespectful to the folks who take the time to report issues and write patches to fix them.

**Comment by lol768** [comment]
.

**Comment by lol768** [comment]
.

**Comment by lol768** [comment]
.

**Comment by lol768** [comment]
.
