### ISSUE TITLE
addExtraOperations with body params in 3.0.0 [Documentation required]

### ISSUE THREAD

**Issue by Halynsky** [springfox/springfox#3589]
- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?
 - [x] Question. Is this a question about how to do a certain thing?  
 
Versions:
kotlin - 1.3.72
org.springframework.boot - 2.3.4.RELEASE
io.springfox:springfox-swagger2 - 3.0.0
io.springfox:springfox-swagger-ui - 3.0.0

I'm am trying to describe API operation from autogenerated security methods of the Spring framework. In our implementation, they have body params email and password. I found old examples on StackOverflow but they are outdated. 
https://stackoverflow.com/questions/34386337/documenting-springs-login-logout-api-in-swagger

```
class FormLoginOperations @Autowired constructor(apiDescriptionReader: ApiDescriptionReader?, apiModelReader: ApiModelReader?, modelSpecificationReader: ApiModelSpecificationReader, pluginsManager: DocumentationPluginsManager?)
    : ApiListingScanner(apiDescriptionReader, apiModelReader, modelSpecificationReader, pluginsManager) {

    @Autowired private val typeResolver: TypeResolver? = null

    override fun scan(context: ApiListingScanningContext): Map<String, List<ApiListing>> {
        val def: MutableMap<String, MutableList<ApiListing>> = super.scan(context)
        val apis: LinkedList<ApiDescription> = LinkedList()
        val loginOperations: ArrayList<Operation> = ArrayList()
        val logoutOperations: ArrayList<Operation> = ArrayList()
        val apiListings: ArrayList<ApiListing> = ArrayList()

        loginOperations.add(OperationBuilder(CachingOperationNameGenerator())
                .method(HttpMethod.POST)
                .uniqueId("login")
                .requestParameters(Arrays.asList(
                        RequestParameterBuilder()
                                .name("email")
                                .description("User email")
                                .`in`(ParameterType.QUERY)
                                .required(true)
                                .build(),
                        RequestParameterBuilder()
                                .name("password")
                                .description("User password")
                                .`in`(ParameterType.QUERY)
                                .required(true)
                                .build()
                        ))
                .summary("Log in") //
                .tags(mutableSetOf("auth-controller"))
                .build())

        logoutOperations.add(OperationBuilder(CachingOperationNameGenerator())
                .method(HttpMethod.POST)
                .uniqueId("logout")
                .summary("Log out")
                .tags(mutableSetOf("auth-controller"))
                .build())

        apis.add(ApiDescription("Auth", "/api/auth/login", "Authentication documentation", "Auth api", loginOperations, false))
        apis.add(ApiDescription("Auth", "/api/auth/logout", "Authentication documentation", "Auth api", logoutOperations, false))


        apiListings.add(ApiListingBuilder(context.documentationContext.apiDescriptionOrdering)
                .apis(apis)
                .tags(mutableSetOf(Tag("auth-controller", "Auth Controller")))
                .build())

        def.put("authentication", apiListings)

        return def
    }
}
```

This is code from examples with some updates. I had success with query params. But I can't handle the same with body params. 
If I change ParameterType.QUERY to ParameterType.BODY it fails. I think some more inputs required to make it works. But I don't know which of them exactly.

Can somebody provide documentation or examples? Would be nice to have an example with the custom response body also.
Best regards

**Comment by zx0506** [comment]
> * [x]  What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://camo.githubusercontent.com/cc8b89a71fc6161c41818a0bd359fd803c728c292d250f1dd193c715d88cef20/68747470733a2f2f6170692e62696e747261792e636f6d2f7061636b616765732f737072696e67666f782f6d6176656e2d7265706f2f737072696e67666f782f696d616765732f646f776e6c6f61642e737667) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
> 
> What kind of issue is this?
> 
> * [x]  Question. Is this a question about how to do a certain thing?
> 
> Versions: kotlin - 1.3.72 org.springframework.boot - 2.3.4.RELEASE io.springfox:springfox-swagger2 - 3.0.0 io.springfox:springfox-swagger-ui - 3.0.0
> 
> I'm am trying to describe API operation from autogenerated security methods of the Spring framework. In our implementation, they have body params email and password. I found old examples on StackOverflow but they are outdated. https://stackoverflow.com/questions/34386337/documenting-springs-login-logout-api-in-swagger
> 
> ```
> class FormLoginOperations @Autowired constructor(apiDescriptionReader: ApiDescriptionReader?, apiModelReader: ApiModelReader?, modelSpecificationReader: ApiModelSpecificationReader, pluginsManager: DocumentationPluginsManager?)
>     : ApiListingScanner(apiDescriptionReader, apiModelReader, modelSpecificationReader, pluginsManager) {
> 
>     @Autowired private val typeResolver: TypeResolver? = null
> 
>     override fun scan(context: ApiListingScanningContext): Map<String, List<ApiListing>> {
>         val def: MutableMap<String, MutableList<ApiListing>> = super.scan(context)
>         val apis: LinkedList<ApiDescription> = LinkedList()
>         val loginOperations: ArrayList<Operation> = ArrayList()
>         val logoutOperations: ArrayList<Operation> = ArrayList()
>         val apiListings: ArrayList<ApiListing> = ArrayList()
> 
>         loginOperations.add(OperationBuilder(CachingOperationNameGenerator())
>                 .method(HttpMethod.POST)
>                 .uniqueId("login")
>                 .requestParameters(Arrays.asList(
>                         RequestParameterBuilder()
>                                 .name("email")
>                                 .description("User email")
>                                 .`in`(ParameterType.QUERY)
>                                 .required(true)
>                                 .build(),
>                         RequestParameterBuilder()
>                                 .name("password")
>                                 .description("User password")
>                                 .`in`(ParameterType.QUERY)
>                                 .required(true)
>                                 .build()
>                         ))
>                 .summary("Log in") //
>                 .tags(mutableSetOf("auth-controller"))
>                 .build())
> 
>         logoutOperations.add(OperationBuilder(CachingOperationNameGenerator())
>                 .method(HttpMethod.POST)
>                 .uniqueId("logout")
>                 .summary("Log out")
>                 .tags(mutableSetOf("auth-controller"))
>                 .build())
> 
>         apis.add(ApiDescription("Auth", "/api/auth/login", "Authentication documentation", "Auth api", loginOperations, false))
>         apis.add(ApiDescription("Auth", "/api/auth/logout", "Authentication documentation", "Auth api", logoutOperations, false))
> 
> 
>         apiListings.add(ApiListingBuilder(context.documentationContext.apiDescriptionOrdering)
>                 .apis(apis)
>                 .tags(mutableSetOf(Tag("auth-controller", "Auth Controller")))
>                 .build())
> 
>         def.put("authentication", apiListings)
> 
>         return def
>     }
> }
> ```
> 
> This is code from examples with some updates. I had success with query params. But I can't handle the same with body params. If I change ParameterType.QUERY to ParameterType.BODY it fails. I think some more inputs required to make it works. But I don't know which of them exactly.
> 
> Can somebody provide documentation or examples? Would be nice to have an example with the custom response body also. Best regards

is this issue solved?
