### ISSUE TITLE
Add Localization (L10N) supporting multiple languages for our swagger ui users

### ISSUE THREAD

**Issue by bruceadowns** [springfox/springfox#3592]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

2.9.2

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I would like to add multiple languages in my swagger ui by supporting localization (l10n) in the swagger ui using springfox integration. I have a message bundle that includes a messages*.properties file for each language and would like to leverage the bundle in the swagger ui.

Here are my annotations:

![image](https://user-images.githubusercontent.com/1503908/95493922-00c7e280-0952-11eb-91fb-f9f83429a94b.png)

That pull strings from a messages bundle:

![image](https://user-images.githubusercontent.com/1503908/95494102-3d93d980-0952-11eb-88b4-90e81aaa572a.png)

That match to the ui:

![image](https://user-images.githubusercontent.com/1503908/95493786-d0804400-0951-11eb-864a-72a0f80b9fb2.png)

**Comment by rajdeepg** [comment]
This will be ideal to support since it solves a big customer need to provide localized swagger documentation in different languages.

**Comment by 4liG4t0r** [comment]
finally this issue has not been fixed ?
