### ISSUE TITLE
Description is not showing up in UI for @ResponseHeader in springfox-boot-starter:3.0.0

### ISSUE THREAD

**Issue by sumantdonthivvsrs** [springfox/springfox#3594]
**Description is not showing up in UI for @ResponseHeader in springfox-boot-starter:3.0.0**

@ApiResponse(code = 201,
                    response = void.class, message = "No Content",
                    responseHeaders = {@ResponseHeader(name ="Name",description = "Displays Name",response = String.class),
                            @ResponseHeader(name ="Place", description = "Displays Place", response = String.class)}

                            ),

Please let me know if i am doing some thing wrong in using of @ResponseHeader...I am able to see "name" and "response" as expected in the UI.Please find the attachment
<img width="1403" alt="UI" src="https://user-images.githubusercontent.com/52141126/95609206-37196680-0a13-11eb-842b-28e760d8d747.png">

**Comment by Nadja-Z** [comment]
@sumantdonthivvsrs Did you find a fix for this issue?
