### ISSUE TITLE
Authorization value is lost on refresh

### ISSUE THREAD

**Issue by constantine008** [springfox/springfox#3595]
Describe the bug you're encountering
Authorization value is lost on refresh

To reproduce...

Click on 'Authorize'
Enter value
Press 'Authorize'
Refresh the page
Click 'Authorize' again
Expected behavior
I should see "Value: ******"

Screenshots
screenshot from 2018-09-06 06-26-58
screenshot from 2018-09-06 06-27-47

Additional context or thoughts
I thought that's the whole purpose of authorize button - to save user session so that it's not lost on refresh

**Comment by dilipkrish** [comment]
This would be an issue with [Swagger-ui](https://github.com/swagger-api/swagger-ui)
