### ISSUE TITLE
@EnableSwagger2 update documentation

### ISSUE THREAD

**Issue by Dos4dev** [springfox/springfox#3599]
I start to use this library and found these conflicts of documentations.

 Should I use **@EnableSwagger2** annotation for 3.0.0 version?
 Is documentation requires updates? 
![image](https://user-images.githubusercontent.com/26284875/95988634-d6829300-0e31-11eb-927b-fcd7a40299b8.png)

**Comment by sergey-morenets** [comment]
Hi @Dos4dev 

Yes, I guess documentation is outdated as examples relate to 2.9.x version
