### ISSUE TITLE
Swagger UI doesn't show up for springfox 3.0.0 in Springboot application

### ISSUE THREAD

**Issue by pradeep-017** [springfox/springfox#3608]
I am using Spring boot 2.3.1.RELEASE. My code snippets of SpringFox configuration and main application class are as below:

```
@Configuration
@EnableWebMvc
public class SpringFoxConfig {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.abc.controllers"))
                .paths(PathSelectors.any())
                .build();
    }
}
```

```
@SpringBootApplication
@EnableConfigurationProperties
@PropertySource("classpath:application.properties")
@EnableOpenApi
public class ABCServiceApplication {

    public static void main(String[] args) {
        Installation.init( ABCServiceApplication.class );
        SpringApplication.run(ABCServiceApplication.class, args);
    }
}
```
Dependency added in build.gradle :
"io.springfox:springfox-boot-starter:3.0.0"

I run this application via terminal using following command:
java -jar build/libs/abc-application.jar

I can see http://localhost:8080/v3/api-docs working, but swagger ui is not working. 
Tried accessing http://localhost:8080/swagger-ui/index.html but shows 404. I have tried all possible urls which I saw in documentation and few other sites.

Can someone please help me out here?

**Comment by mfvanek** [comment]
@pradeep-017 please try http://localhost:8080/swagger-ui/
See changes in documentation https://springfox.github.io/springfox/docs/current/#changes-in-swagger-ui

**Comment by parallelthought** [comment]
Observing the same issue with Spring Boot v2.3.2.RELEASE.

The UI is not available at http://localhost:8080/swagger-ui/

Maven dependecy used
```
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
```

**Comment by parallelthought** [comment]
Had the same issue but was able to resolve it by properly configuring the Swagger. I'm not using any annotations for my application which runs on Spring Webflux.

**Comment by pradeep-017** [comment]
> @pradeep-017 please try http://localhost:8080/swagger-ui/
> See changes in documentation https://springfox.github.io/springfox/docs/current/#changes-in-swagger-ui

I have tried this too. It's not working.
Seems we need to take of something while packaging into a jar. Not sure what.

**Comment by IshanDogra** [comment]
@pradeep-017 Can you share your pom file?

**Comment by adorearun** [comment]
I have similar issue returning 404 while accessing http://localhost:8080/swagger-ui/  . My POM.xml is below


```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.4.0</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>

<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-test</artifactId>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-boot-starter</artifactId>
        <version>3.0.0</version>
    </dependency>
<dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-bigquery</artifactId>
        <version>1.116.0</version>
    </dependency>
</dependencies>

```



My swagger config file 
```

@Configuration
public class SwaggerConfig implements WebFluxConfigurer {

    @Bean
    public Docket createRestApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(new ApiInfoBuilder()
                        .description("My Reactive API")
                        .title("My Domain object API")
                        .version("1.0.0")
                        .build())
                .enable(true)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.comp.pr.demoproj.router"))
                .paths(PathSelectors.any())
                .build();

    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {

        registry.addResourceHandler("/swagger-ui.html**")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}
```

Can someone pls help @IshanDogra @mfvanek  ?

**Comment by Y175** [comment]
you can add this into your swaggerconfig
```
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/swagger-ui/**")
            .addResourceLocations("classpath:/META-INF/resources/webjars/springfox-swagger-ui/")
            .resourceChain(false);
    }
```
then you can access  http://localhost:8080/swagger-ui/index.html

**Comment by Y175** [comment]
> I have similar issue returning 404 while accessing http://localhost:8080/swagger-ui/ . My POM.xml is below
> 
> ```
> <parent>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-parent</artifactId>
>     <version>2.4.0</version>
>     <relativePath/> 
> </parent>
> 
> <dependencies>
>     <dependency>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-webflux</artifactId>
>     </dependency>
>     <dependency>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-web</artifactId>
>     </dependency>
>     <dependency>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-test</artifactId>
>         <scope>test</scope>
>     </dependency>
> 
>     <dependency>
>         <groupId>io.projectreactor</groupId>
>         <artifactId>reactor-test</artifactId>
>         <scope>test</scope>
>     </dependency>
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-boot-starter</artifactId>
>         <version>3.0.0</version>
>     </dependency>
> <dependency>
>         <groupId>com.google.cloud</groupId>
>         <artifactId>google-cloud-bigquery</artifactId>
>         <version>1.116.0</version>
>     </dependency>
> </dependencies>
> ```
> 
> My swagger config file
> 
> ```
> 
> @Configuration
> public class SwaggerConfig implements WebFluxConfigurer {
> 
>     @Bean
>     public Docket createRestApi() {
>         return new Docket(DocumentationType.SWAGGER_2)
>                 .apiInfo(new ApiInfoBuilder()
>                         .description("My Reactive API")
>                         .title("My Domain object API")
>                         .version("1.0.0")
>                         .build())
>                 .enable(true)
>                 .select()
>                 .apis(RequestHandlerSelectors.basePackage("com.comp.pr.demoproj.router"))
>                 .paths(PathSelectors.any())
>                 .build();
> 
>     }
> 
>     @Override
>     public void addResourceHandlers(ResourceHandlerRegistry registry) {
> 
>         registry.addResourceHandler("/swagger-ui.html**")
>                 .addResourceLocations("classpath:/META-INF/resources/");
> 
>         registry.addResourceHandler("/webjars/**")
>                 .addResourceLocations("classpath:/META-INF/resources/webjars/");
>     }
> }
> ```
> 
> Can someone pls help @IshanDogra @mfvanek ?

you can add this into your swaggerconfig
```
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/swagger-ui/**")
            .addResourceLocations("classpath:/META-INF/resources/webjars/springfox-swagger-ui/")
            .resourceChain(false);
    }
```
then you can access http://localhost:8080/swagger-ui/index.html

**Comment by uguisu** [comment]
Please invite following dependence into pom.xml

```xml
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-boot-starter</artifactId>
    <version>3.0.0</version>
</dependency>
```
