### ISSUE TITLE
Multiple @RequestPart not showing up in swagger generated. 3.0.0

### ISSUE THREAD

**Issue by anudeep-mj** [springfox/springfox#3618]
Issue: When having multiple @RequestPart parameters in @PostMapping, the swagger generated doesnt generate it.

Spring-boot: `2.2.6.RELEASE`

Current springfox dependencies.
```
<dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-boot-starter</artifactId>
      <version>3.0.0</version>
    </dependency>
    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>3.0.0</version>
    </dependency>
```

API signature is as follows:

```
@PostMapping(value = "/v1/validate")
    public FileResuls validateFile (
        @RequestPart("file") final MultipartFile multipartFile,
        @RequestPart(name = "context", required = false) final ValidationContext context,
        @RequestPart("traceinfo") final TraceInfo traceInfo,
        @RequestParam(value = "compressed", required = false, defaultValue = "false")
        final boolean compressed)
 
```

But when the swagger is generated, all I see is the following: 
```
"parameters": [
          {
            "name": "file",
            "in": "formData",
            "required": false,
            "type": "file"
          },
          {
            "name": "compressed",
            "in": "query",
            "description": "compressed",
            "required": false,
            "type": "boolean",
            "default": false
          }
        ],

```
Seems like the other @RequestPart parameters arent even considered. (Also if you notice, the "file" parameter should have required=true which is not correct).

Can you please help me out.

**Comment by Halynsky** [comment]
**+1 Same issue**

I have tried to handle it with ApiImplicitParam but I can't set paramType to formData
```
    @ApiImplicitParams(
            ApiImplicitParam(name = "firmwareInfo", required = false, 
            dataType = "com.partizan.firmwares.dto.models.FirmwareInfoModel", paramType = "body")
    )
```

**Comment by SheikhZayed** [comment]
> **+1 Same issue**
> 
> I have tried to handle it with ApiImplicitParam but I can't set paramType to formData
> 
> ```
>     @ApiImplicitParams(
>             ApiImplicitParam(name = "firmwareInfo", required = false, 
>             dataType = "com.partizan.firmwares.dto.models.FirmwareInfoModel", paramType = "body")
>     )
> ```

It should be like the following 
`@ApiImplicitParams(
>             ApiImplicitParam(name = "firmwareInfo", required = false, 
>             dataType = "com.partizan.firmwares.dto.models.FirmwareInfoModel", paramType = "body")
>     )`
