### ISSUE TITLE
Context-Path missing in Swagger-ui links/try when behind Proxy

### ISSUE THREAD

**Issue by fgiquel** [springfox/springfox#3621]
I am using Springfox swagger 3.0.0 (via springfox-boot-starter maven dependency).
I encounter exactly the same problem as explained in old issue [https://github.com/springfox/springfox/issues/1210], with apache httpd configuration for the reverse proxy.

Direct links on the host look like this:
"http://service-host:8081/api"

whereas links to be routed via reverse proxy like this:
"https://portal-host/service-context/api"

The problem was declared as solved in 2.5.0, within this commit [https://github.com/springfox/springfox/pull/1217]
However with 3.0.0, my swagger-ui page has "try-out" links like "https://portal-host/api/XXXX" wich do not contain anymore the context-path "/service-context"

With debugger, i have inspected in _WebMvcBasePathAndHostnameTransformationFilter#transform_. I am not sure that is the most appropriate class to debug, but i see : 
- the _HttpServletRequest_ instance received is of type _org.springframework.web.filter.ForwardedHeaderFilter$ForwardedHeaderExtractingRequest_
- this request incudes one field _ForwardedHeaderFilter$ForwardedPrefixExtractor.forwardedPrefix_ = "/service-context/api", and invocation of getContextPath() returns "/service-context/api"
- i do not know the role of the "swagger" feeded instance, but i see that the _WebMvcBasePathAndHostnameTransformationFilter_ simply erases the complete base path "/service-context/api""

Does anyone have an idea of the problem in 3.0.0 ? Is it possible that some code refactoring disabled the 2.5.0 1217 fix, OR is my context different from the original issue ...
Best Regards.
Fabien.

**Comment by BorjaSalazar** [comment]
same issue here,` DocumentationType.SWAGGER_2 `works fine, where `DocumentationType.OAS_30` does not use the context-path for try-out feature.
