### ISSUE TITLE
Swagger infers URL with HTTP instead of HTTPS

### ISSUE THREAD

**Issue by Maxeh** [springfox/springfox#3628]
I'm using the newest springfox-boot-starter 3.0.0 with a Docket of DocumentationType OAS_30. Everything works fine, except the inferred URL for the "Try out" uses HTTP instead of HTTPS, so it is basically not usable. Is there a way to change this inferred URL to use HTTPS? If I use DocumentationType Swagger2 then this issue does not come up and everything works, but I want to use the new OAS_30.

The URL which is used to call swagger uses HTTPS.

In the attached images you see that HTTP with port 80 is shown instead of HTTPS. The JSON is from the /v3/api-docs endpoint.
![swagger-upload-2](https://user-images.githubusercontent.com/10271898/97980633-62ecf980-1dd1-11eb-8f50-08345ef1eebf.png)

That's how it looks like when swagger UI is opened: HTTP is shown instead of HTTPS in the inferred URL dropdown.
![swagger-upload](https://user-images.githubusercontent.com/10271898/97980646-68e2da80-1dd1-11eb-996f-4de6eac3159c.png)

My docket code:

```   
return new Docket(DocumentationType.OAS_30)
   .select()
   .apis(RequestHandlerSelectors.withClassAnnotation(Api.class))
   .build()
   .apiInfo(apiInfo())
   .securitySchemes(Collections.singletonList(
      BASIC_AUTH_BUILDER
         .name("basicAuth")
         .build()));

**Comment by rvhuang** [comment]
Facing the exact same issue. Why has the issue been closed?

**Comment by StefanDragan92** [comment]
Did anyone fixed it? I have the same issue.
