### ISSUE TITLE
RequestParam Array as parameter in OpenAPI 3.0

### ISSUE THREAD

**Issue by ilueckel** [springfox/springfox#3629]
I'm using the latest release of 

```
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
```

What kind of issue is this?

**Bug Report**

Repository: https://github.com/ilueckel/springfox-bug-repo

**Description**

Using an array-like `RequestParam` like

```
  @GetMapping("test.json")
  public void test(@ApiParam(allowMultiple = true) @RequestParam Collection<Long> ids) {  }
```

fails to represent the array type when using `DocumentationType.OAS_30`. When you use `DocumentationType.SWAGGER2` instead, the parameter is mapped as array.

The Repository linked above creates to `Docket`s that show this behavior.

**Screenshots**

![image](https://user-images.githubusercontent.com/1216059/97986422-f6c2c380-1dd9-11eb-81ee-92136835d845.png)
_Array Parameter with OAS_30_

![image](https://user-images.githubusercontent.com/1216059/97986506-1823af80-1dda-11eb-8c01-676e8e1c2074.png)
_Array Parameter with SWAGGER_2_

**Comment by YAGAMIL** [comment]
I also encountered this problem

**Comment by Rizzen59** [comment]
Me too

**Comment by gideruette** [comment]
Me too

**Comment by mkotra** [comment]
Same issue here. For DocumentationType.SWAGGER_2 works fine, but for DocumentationType.OAS_30 it does not.

**Comment by asibross** [comment]
Same here.

**Comment by CthulhuOfStars** [comment]
Same here. And if you set @ApiParam, the documentation of this method is not generated for me.

**Comment by jimrueaster** [comment]
Same here.

**Comment by Delirante** [comment]
+1

**Comment by thejavator** [comment]
To make this happen, put the request params inside an object as below : 

 ```
   @GetMapping(value = "/filter")
    public ResponseEntity filterValues(RequestFilter requestFilter) {
```

```
public class RequestFilter {
    private List<String> filters;
    private List<Long> ids;
}

```


The rendered swagger operation is : 

![image](https://user-images.githubusercontent.com/6198887/210096886-e100bee1-0549-4d92-898b-471b9d7271d6.png)

**Comment by blackc716** [comment]
+1
