### ISSUE TITLE
Unpublished Gradle metadata is breaking builds

### ISSUE THREAD

**Issue by dreis2211** [springfox/springfox#3636]
Hi,

our builds don't really work at the moment because the Gradle metadata file is not published, although the pom.xml marker suggests it.

https://repo1.maven.org/maven2/io/springfox/springfox-swagger2/3.0.0/springfox-swagger2-3.0.0.pom

```
<!--  This module was also published with a richer model, Gradle metadata,   -->
<!--  which should be used instead. Do not delete the following line which   -->
<!--  is to indicate to Gradle or any Gradle module metadata file consumer   -->
<!--  that they should prefer consuming it instead.  -->
<!--  do_not_remove: published-with-gradle-metadata  -->
```
This currently breaks when doing `./gradlew build --refresh-dependencies` and is a show-stopper for us at the moment because Artifactory is returning 403 on virtual repos when it doesn't find artifacts (https://www.jfrog.com/jira/browse/RTFACT-8765)

A quick fix would be to disable metadata generation
```
    tasks.withType(GenerateModuleMetadata) {
        enabled = false
    }
```
Or by including the respective `.module` file in the publication step.

Cheers,
Christoph

**Comment by dreis2211** [comment]
Still relevant

**Comment by dreis2211** [comment]
Still valid

**Comment by dreis2211** [comment]
Still valid

**Comment by dreis2211** [comment]
Still valid

**Comment by dreis2211** [comment]
Still valid

**Comment by thorntonrp** [comment]
This issue is breaking builds in my organization as well. There's been no new release for almost 2 years. Is this project still active???
