### ISSUE TITLE
Disable swagger-resources endpoint when springfox.documentation.swaggerUi.enabled is false

### ISSUE THREAD

**Issue by maksutspahi** [springfox/springfox#3645]
Using springfox-boot-starter 3.0.0

With configuration `springfox.documentation.swaggerUi.enabled : false` only /swagger-ui request mapping is disabled.
But springfox.documentation.swagger.web.ApiResourceController.java bean is still created and the following endpoints are still exposed.
 ```
 /swagger-resources
 /swagger-resources/configuration/security
 /swagger-resources/configuration/ui
```
I think when springfox.documentation.swaggerUi.enabled is false all the ui controllers should not be mapped.

Thank you

**Comment by persiliao** [comment]
You can disable using below property

`springfox.documentation.enabled=false`
