### ISSUE TITLE
Why can't the springboot project manually define Api in swagger

### ISSUE THREAD

**Issue by xhc-code** [springfox/springfox#3653]
The springboot project cannot define the Post request in ApiDescription, the request content is an API mapping in JSON format, and the body content of the request body will be empty, which is inexplicable
. I have referenced http://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin; but I did not find the answer I need

The code is:
`package cn.dmahz.jwt.api;

import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import springfox.documentation.builders.*;
import springfox.documentation.schema.ScalarType;
import springfox.documentation.service.*;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.service.ApiListingScannerPlugin;
import springfox.documentation.spi.service.contexts.DocumentationContext;
import springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static java.util.Collections.singletonList;

/**
 * @author Dream
 */
@SuppressWarnings({
        "WhitespaceAround",
        "ParenPad",
        "deprecation"})
@Component
public class JwtLoginWebApi implements ApiListingScannerPlugin{

        private final CachingOperationNameGenerator operationNames;

        /**
         * @param operationNames - CachingOperationNameGenerator is a component bean
         *                       that is available to be autowired
         */
        public JwtLoginWebApi(CachingOperationNameGenerator operationNames) {//<9>
            this.operationNames = operationNames;
        }

        @Override
        public List<ApiDescription> apply(DocumentationContext context) {

            RequestParameter requestParameter = new RequestParameterBuilder()
                    .name("loginUserDTO")
                    .in(ParameterType.BODY)
                    .description("loginUserDTO")
                    .required(true)
                    .hidden(false)
                    .parameterSpecificationProvider(new BodyParameterSpecificationProvider())
                    .content(content -> content.representation(MediaType.APPLICATION_JSON)
                            .apply(
                                    representationBuilder -> representationBuilder
                                            .mediaType(MediaType.APPLICATION_JSON)
                                            .model(modelSpecificationBuilder -> modelSpecificationBuilder.scalarModel(ScalarType.OBJECT).referenceModel(referenceModelSpecificationBuilder -> referenceModelSpecificationBuilder.key(modelKeyBuilder -> modelKeyBuilder.qualifiedModelName(new QualifiedModelNameBuilder().namespace("cn.dmahz.dto.user").name("LoginUserDTO").build()).isResponse(false).build()).build()))
                            ))
                    .query(simple -> simple.style(ParameterStyle.SIMPLE))
                    .build();

            List<ApiDescription> apiDescriptions = singletonList(new ApiDescription(
                    "登录",
                    "/login",
                    "用户登录Api",
                    "用户登录API(手动添加API)",
                    Arrays.asList(
                            new OperationBuilder(operationNames)
                                    .authorizations(new ArrayList<>())
                                    .method(HttpMethod.POST)
                                    .notes("登录")
//                                    .requestBody(
//                                            new RequestBody(
//                                                    "登录请求主体",
//                                                    new HashSet<>(Arrays.asList(new RepresentationBuilder().model(modelSpecificationBuilder -> modelSpecificationBuilder.facets(modelFacetsBuilder -> modelFacetsBuilder.examples(Arrays.asList(new ExampleBuilder().mediaType(MediaType.APPLICATION_FORM_URLENCODED_VALUE).description("用户名des").summary("用户名").id("用户名").value("id1").build() ))).scalarModel(ScalarType.OBJECT).build()).mediaType(MediaType.APPLICATION_FORM_URLENCODED_VALUE).build())),
//                                                    true,
//                                                    Arrays.asList(obj)
//                                            ))
                                    .requestParameters(Arrays.asList(requestParameter))
                                    .responses(singletonList(new ResponseBuilder().code("200").description("成功响应").representation(MediaType.APPLICATION_JSON).apply(r -> r.model(m -> m.scalarModel(ScalarType.OBJECT))).build()))
                                    .build()
                    ),
                    false
            ));

            return apiDescriptions;
        }

        @Override
        public boolean supports(DocumentationType delimiter) {
            return DocumentationType.OAS_30.equals(delimiter);
        }

}
`

**Comment by xhc-code** [comment]
The problem caused by the above is that the request body is empty or only {} content without any actual valid value, which is very confusing

**Comment by 1415749952** [comment]
我已经解决该问题了。具体代码如下
```

package com.reststyle.framework.swagger.config;

import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import springfox.documentation.builders.*;
import springfox.documentation.schema.ScalarType;
import springfox.documentation.service.*;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.service.ApiListingScannerPlugin;
import springfox.documentation.spi.service.contexts.DocumentationContext;
import springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;

import static java.util.Collections.singletonList;

/**
 * Created with IntelliJ IDEA.
 * Description:手动添加swagger接口，如登录接口等
 *
 * @version 1.0
 * @author: TheFei
 * @Date: 2021-07-14
 * @Time: 17:22
 */
@Component
public class SwaggerAddition implements ApiListingScannerPlugin
{

    @Override
    public List<ApiDescription> apply(DocumentationContext context)
    {
        String loginJsonStr = "{\n" +
                "    \"username\":\"admin\",\n" +
                "    \"password\":\"123456\",\n" +
                "    \"code\":\"5\",\n" +
                "    \"uuid\":\"ea34a4554f55418c83011b4cd403fb22\"\n" +
                "}";

        RequestBody requestBody = new RequestBody(
                "登录请求主体",
                new HashSet<>(Arrays.asList(new RepresentationBuilder()
                        .model(modelSpecificationBuilder -> modelSpecificationBuilder.facets(modelFacetsBuilder -> modelFacetsBuilder.examples(Arrays.asList(new ExampleBuilder().mediaType(MediaType.APPLICATION_JSON_VALUE).value(loginJsonStr).build()))).scalarModel(ScalarType.OBJECT).build()).mediaType(MediaType.APPLICATION_JSON_VALUE).build())),
                true,
                Arrays.asList(new StringVendorExtension("name", "value"))
        );

        List<ApiDescription> apiDescriptions = singletonList(new ApiDescription(
                "登录",
                "/login/userLogin",
                "用户登录Api",
                "用户登录API(手动添加API)",
                singletonList(
                        new OperationBuilder(new CachingOperationNameGenerator())
                                .authorizations(new ArrayList<>())
                                .tags(new HashSet()
                                {{
                                    add("登录模块");
                                }})
                                .method(HttpMethod.POST)
                                .notes("username/password登录")
                                .summary("用户登录获取token")
                                .requestBody(requestBody)
                                .responses(singletonList(new ResponseBuilder().code("200").description("ok").representation(MediaType.ALL).apply(r -> r.model(m -> m.scalarModel(ScalarType.OBJECT))).build()))
                                .build()
                ),
                false
        ));

        return apiDescriptions;
    }

    @Override
    public boolean supports(DocumentationType delimiter)
    {
        return DocumentationType.OAS_30.equals(delimiter);
    }
}
```

**Comment by frankelyns** [comment]
> 我已经解决了该问题了。具体代码如下
> 
> ```
> 
> package com.reststyle.framework.swagger.config;
> 
> import org.springframework.http.HttpMethod;
> import org.springframework.http.MediaType;
> import org.springframework.stereotype.Component;
> import springfox.documentation.builders.*;
> import springfox.documentation.schema.ScalarType;
> import springfox.documentation.service.*;
> import springfox.documentation.spi.DocumentationType;
> import springfox.documentation.spi.service.ApiListingScannerPlugin;
> import springfox.documentation.spi.service.contexts.DocumentationContext;
> import springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator;
> 
> import java.util.ArrayList;
> import java.util.Arrays;
> import java.util.HashSet;
> import java.util.List;
> 
> import static java.util.Collections.singletonList;
> 
> /**
>  * Created with IntelliJ IDEA.
>  * Description:手动添加swagger接口，如登录接口等
>  *
>  * @version 1.0
>  * @author: TheFei
>  * @Date: 2021-07-14
>  * @Time: 17:22
>  */
> @Component
> public class SwaggerAddition implements ApiListingScannerPlugin
> {
> 
>     @Override
>     public List<ApiDescription> apply(DocumentationContext context)
>     {
>         String loginJsonStr = "{\n" +
>                 "    \"username\":\"admin\",\n" +
>                 "    \"password\":\"123456\",\n" +
>                 "    \"code\":\"5\",\n" +
>                 "    \"uuid\":\"ea34a4554f55418c83011b4cd403fb22\"\n" +
>                 "}";
> 
>         RequestBody requestBody = new RequestBody(
>                 "登录请求主体",
>                 new HashSet<>(Arrays.asList(new RepresentationBuilder()
>                         .model(modelSpecificationBuilder -> modelSpecificationBuilder.facets(modelFacetsBuilder -> modelFacetsBuilder.examples(Arrays.asList(new ExampleBuilder().mediaType(MediaType.APPLICATION_JSON_VALUE).value(loginJsonStr).build()))).scalarModel(ScalarType.OBJECT).build()).mediaType(MediaType.APPLICATION_JSON_VALUE).build())),
>                 true,
>                 Arrays.asList(new StringVendorExtension("name", "value"))
>         );
> 
>         List<ApiDescription> apiDescriptions = singletonList(new ApiDescription(
>                 "登录",
>                 "/login/userLogin",
>                 "用户登录Api",
>                 "用户登录API(手动添加API)",
>                 singletonList(
>                         new OperationBuilder(new CachingOperationNameGenerator())
>                                 .authorizations(new ArrayList<>())
>                                 .tags(new HashSet()
>                                 {{
>                                     add("登录模块");
>                                 }})
>                                 .method(HttpMethod.POST)
>                                 .notes("username/password登录")
>                                 .summary("用户登录获取token")
>                                 .requestBody(requestBody)
>                                 .responses(singletonList(new ResponseBuilder().code("200").description("ok").representation(MediaType.ALL).apply(r -> r.model(m -> m.scalarModel(ScalarType.OBJECT))).build()))
>                                 .build()
>                 ),
>                 false
>         ));
> 
>         return apiDescriptions;
>     }
> 
>     @Override
>     public boolean supports(DocumentationType delimiter)
>     {
>         return DocumentationType.OAS_30.equals(delimiter);
>     }
> }
> ```

The request parameter cannot appear in the body
