### ISSUE TITLE
open-api 3 spec includes swagger internal exampleSetFlag Property

### ISSUE THREAD

**Issue by jmuenchenberg** [springfox/springfox#3655]
using springfox 3.0.0 and swagger 2.1.5 to access swagger on an open-api 3 springboot project.

when retrieving the open-api 3 specs from <my-service>/v3/api-docs every node in the schema contains a swagger-internal "exampleSetFlag" property.
this makes it impossible to use this spec in other open-api3 projects

Might be related to the springfox use of ObjectMapper: 
https://github.com/swagger-api/swagger-core/issues/3702
https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287

Is there a way to suppress this property in the output from /v3/api-docs?

**Comment by bianjp** [comment]
This issue should be resolved.

**Comment by samikshan** [comment]
@jmuenchenberg Did you find any resolution to this issue?

**Comment by jmuenchenberg** [comment]
@samikshan only fix known to me is downgrading swagger-core to 2.1.3

@bianjp I do not see a new version of springfox, is there any other dependency I need to upgrade to have this issue resolved?

**Comment by AryaShafiee** [comment]
Hello, have you found any solution for this issue?

**Comment by jmuenchenberg** [comment]
@AryaShafiee Kind of: We moved from Springfox to SpringDoc

**Comment by AryaShafiee** [comment]
@jmuenchenberg Thanks

**Comment by alebastrov** [comment]
https://github.com/swagger-api/swagger-core/issues/4381

**Comment by jaychoww** [comment]
this code works for me:
```java
public static abstract class Oas3Mixin {

        @JsonIgnore
        public abstract boolean getExampleSetFlag();

    }
YamlMapper yamlMapper = new YamlMapper();
yamlMapper.addMixIn(Schema.class, Oas3Mixin.class);
String output = yamlMapper.writeValueAsString(openApi);
```    
this is  another solution:
https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287
