### ISSUE TITLE
What is the replacement for RelativePathProvider from 

### ISSUE THREAD

**Issue by Nadja-Z** [springfox/springfox#3658]
Hi, 

I am opening this issue since I started migrating from springfox `2.9.2` to `3.0.0` for my Spring Boot Application. For the published api path I am using `RelativePathProvider.java` which does not exist in version `3.0.0` anymore.
I have checked the documentation of `springfox-spring-web` version `3.0.0` but unfortunately I was not able to find `RelativePathProvider.java` class. Also the release notes are not mentioning this as changed/removed/deprecated, so I was not able to find a suitable replacement. 

[2.9.2 paths folder](https://github.com/springfox/springfox/tree/2.9.2/springfox-spring-web/src/main/java/springfox/documentation/spring/web/paths)

[3.0.0 paths folder](https://github.com/springfox/springfox/tree/3.0.0/springfox-spring-web/src/main/java/springfox/documentation/spring/web/paths)

Can you provide more information on why this was removed in version `3.0.0` and how I can replace it?

Thanks in Advance.

**Comment by twonky4** [comment]
The `RelativePathProvider` was replaced by `DefaultPathProvider` in 2.10.0
