### ISSUE TITLE
generate-executable failed: Ambiguous mapping

### ISSUE THREAD

**Issue by josephabijaoude** [springfox/springfox#3664]
Hello,
It seems that two method are mapped to the same endpoint.
While compiling my project, I'm getting the following error:
```
Execution generate-executable of goal com.murex.serviceframework.tools:java-rest-runtime-maven-plugin:1.3.9:generate-executable failed: Ambiguous mapping. Cannot map 'springfox.documentation.oas.web.OpenApiControllerWebFlux' method public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.oas.web.OpenApiControllerWebFlux.getDocumentation(java.lang.String,org.springframework.http.servr.reactive.ServerHttpRequest) to {GET /v3/api-docs, produces [application/json || application/hal+json]}: There is already 'springfox.documentation.oas.web.OpenApiControllerWebMvc' bean method public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.oas.web.OpenApiControllerWebMvc.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest) mapped.
```
The project is spring boot and I've added the following dependency:
`<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-boot-starter</artifactId>
	<version>3.0.0</version>
</dependency>`

And on my configuration:
`  @Bean
  public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(PathSelectors.any())
            .build();
  }`

**Comment by VincentTran1994** [comment]
I am facing the same issue. Any solution in this case?

**Comment by Vergilon** [comment]
@VincentTran1994 use comand ``mvn dependency:tree`` and find out which dependency (most likely **webflux**) is using **springfox**. After that remove this dependency, or use [maven exclusion](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#dependency-exclusions) to exclude springfox from it.

**Comment by jfkubraozdemir** [comment]
> @VincentTran1994 use comand `mvn dependency:tree` and find out which dependency (most likely **webflux**) is using **springfox**. After that remove this dependency, or use [maven exclusion](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#dependency-exclusions) to exclude springfox from it.

How?
