### ISSUE TITLE
Can't find only Swagger UI endpoint when the app is running in docker container

### ISSUE THREAD

**Issue by sapkotasuren** [springfox/springfox#3680]
I have included swagger dependency in my project, when i run it locally on my machine without using container then everything works, able to access swagger ui endpoint.

when the app is running inside docker container then it gives: 404 error/not found when i visit the url: http://localhost:8080/swagger-ui.html

dependency i've used for swagger:

<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.8.0</version>
		</dependency>

It's a springbootApplication, with one configuration class. 
I have created one by myself configuration for swagger:

@Configuration
@EnableSwagger2
public class SwaggerConfig {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2).select()
                .apis(RequestHandlerSelectors.basePackage("com.bsf.quiz.bsfQuiz"))
                .paths(PathSelectors.any())
                .build();
    }
}

All the requestmapping are under /api/projectname/......

@dilipkrish

**Comment by murilokprado** [comment]
I passed to the same problem, there is a way to solve this on version 3.0.0. The main solution was add in my swagger config the `WebMvcConfigurationSupport` and two overload methods. they are `addResourceHandlers` and `addViewControllers`

After that I abble to access my documentation using docker and I've done deploy in AWS. If you are questions feel free to ask. I hope this help you.

Here's the code.

```
@Configuration
@EnableSwagger2
public class SwaggerConfig extends WebMvcConfigurationSupport {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.
                addResourceHandler("/swagger-ui/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/springfox-swagger-ui/")
                .resourceChain(false);
    }

    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        registry.addViewController("/swagger-ui/")
                .setViewName("forward:/swagger-ui/index.html");
    }

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .paths(PathSelectors.any())
                .apis(RequestHandlerSelectors.basePackage("com.br"))
                .build()
                .apiInfo(buildApiInfo());
    }

    private ApiInfo buildApiInfo() {
        return new ApiInfo(
                "Gerenciador de ganhador do jogo da velha",
                "API para verificar se existe ou não um ganhador no jogo da velha.",
                "1.0",
                "",
                new Contact("Murilo Prado", "https://www.linkedin.com/in/murilokprado/", "mrlkprado@gmail.com"),
                null,
                null,
                Collections.emptyList()
        );
    }
}
```

**Comment by hungnv-sr** [comment]
@murilokprado Does it work with lower swagger version? or it has to be 3.0.0 or above?

**Comment by murilokprado** [comment]
> @murilokprado Does it work with lower swagger version? or it has to be 3.0.0 or above?

I don't think so

**Comment by hungnv-sr** [comment]
@murilokprado can you share you pom file? I can't find a work-able version

**Comment by murilokprado** [comment]
> @murilokprado can you share you pom file? I can't find a work-able version

Of course.

```
     ...
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>io.springfox</groupId>
                            <artifactId>springfox-boot-starter</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.21.0</version>
            </plugin>
        </plugins>
    </build>    
```

That's it @hungnv-sr

**Comment by hungnv-sr** [comment]
@murilokprado Thanks a lot! I managed to get it to work inside docker. Now I got a new problem when deploying it to Kubernetes. it returned 401. Log:
```
f.e.b.f.s.CustomAuthenticationEntryPoint : Unauthorized error: Full authentication is required to access this resource
```
It's the same image. I tried to kubectl exec to it to curl on localhost, it also returned 401. Other paths work just fine.

**Comment by murilokprado** [comment]
> @murilokprado Thanks a lot! I managed to get it to work inside docker. Now I got a new problem when deploying it to Kubernetes. it returned 401. Log:
> 
> ```
> f.e.b.f.s.CustomAuthenticationEntryPoint : Unauthorized error: Full authentication is required to access this resource
> ```
> 
> It's the same image. I tried to kubectl exec to it to curl on localhost, it also returned 401. Other paths work just fine.

You're welcome, for this error please check if you're exponsing on dockerfile and config kubectl the port of swagger and your application, if the error persists check your route are available on cors.
