### ISSUE TITLE
@AliasFor not working on @ApiOperation in Spring Boot

### ISSUE THREAD

**Issue by sombochea** [springfox/springfox#3682]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 
 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Code example here: [Full Example](https://gist.github.com/SomboChea/0324964054c8269ce5f21e7f8ff4c01a)
```java
@ApiOperation("Default Api Operation : not working")
@Retention(RetentionPolicy.RUNTIME)
@RequestMapping(value = "/request-path-default-NOT_WORKING" ,method = RequestMethod.GET )
@Inherited
@interface OverrideApiOperation {
    @AliasFor(annotation = ApiOperation.class, attribute = "value")
    String value() default "Default In Override : working in override";

    @AliasFor(annotation = RequestMapping.class, attribute = "value")
    String path11() default "/request-path-override-default : working-default";
}
```
![image](https://user-images.githubusercontent.com/7059827/102609102-825f9c00-415d-11eb-9f1c-bdbaa728bf54.png)

**Describe**
I have testing with Request Mapping value is working with AliasFor that override the attribute. But for ApiOperation does not working with AliasFor. Because I want to override the Authorization in ApiOperation annotation, but it keep the default value in annotation attributes.

***Noted***: I tested with Swagger 2.9.2 and Swagger 3.0.0 and Spring Boot 2.4.1.

Best regards and Thank you!

**Comment by bbrouwer** [comment]
I've investigated this and it appears that what you are looking for are merged annotations, as that is what honors the `@AliasFor` annotations. I would like this ability too. It looks like it might be fairly straight-forward to replace all usage of `AnnotationUtils.findAnnotation` with `AnnotatedElementUtils.findMergedAnnotation`.

**Comment by Medivh-z** [comment]
Why not solve？:(

**Comment by cyy0974** [comment]
Why not solve！！！！！！！！！！！！！！！！！！！！！！
