### ISSUE TITLE
Where to find the reference documentation for springfox 2.x?

### ISSUE THREAD

**Issue by chongchaoyu** [springfox/springfox#3684]
Question:
I can't find the reference documentation for springfox 2.x, just release and snaphot refs are in the springfox website, I am a springfox newbie, and my project uses springfox2.7.0, no plan for update to 3.x

thanks.

**Comment by eguller** [comment]
Hello @chongchaoyu , 
you can add just version number at the end of url.
e.g
https://springfox.github.io/springfox/docs/2.9.2/

In your case 
https://springfox.github.io/springfox/docs/2.7.0/
