### ISSUE TITLE
Bug: Java Collection of Byte Arrays creates nested Integer Collection in swagger.json

### ISSUE THREAD

**Issue by martinpalic** [springfox/springfox#3687]
Version 2.9.2 (replicated also after migration to v3)

In our app we receive Collection of byte arrays (base64 data). We create swagger.json from these entities which is later used to generate client code. Code is swagger.json creates List<List<Integer>>  which causes problems in client. 

Although I've found some similar problems, I have not encountered any solution for this in Issues, Docs or other places.

What I tried without luck:
- AlternateTypeRules 
- migrate to latest version
- use byte[][]
- use String as byte64 representation (not really suitable)

Field declaration:
```java
@JsonProperty("probes")  
@ApiModelProperty(value = "An array of Base64 encoded probes", position = 1, example = "[\"BASE64\"]")  
private List<byte[]> probes;
````
Generated swagger.json entry:
```json
"probes": {
          "type": "array",
          "example": [
            "BASE64"
          ],
          "description": "An array of Base64 encoded probes",
          "items": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int32",
              "minimum": -128,
              "maximum": 127
            }
          }
```

Expected swagger.json entry:
```json
"probes": {
      "type": "array",
      "example": [
        "BASE64"
      ],
      "description": "An array of Base64 encoded probes",
      "items": {
        "type": "string",
        "format": "byte"
      }
```
I will be thankful for any support or point in the right direction.

**Comment by petr-bartusek** [comment]
Is there any progress in resolving this issue in springfox 3.0.0?
