### ISSUE TITLE
Question: Can I use java 14 record type with Swagger?

### ISSUE THREAD

**Issue by JayAhn2** [springfox/springfox#3691]
Please take the time to search the repository, if your question has already been asked or answered.

- [ 2.9.2] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [X] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful. 

Hi guys, 

I use java 14 record type as DTO, but in swagger UI, it shows as empty. 
![image](https://user-images.githubusercontent.com/25868002/103444632-6afad580-4c6a-11eb-9f14-61bf630e62e1.png)

Could you let me know whether java 14 record type can be used or not?

```
public record NewLocationCommandDTO(
    String locationId,
    String name,
    LocationLevel locationLevel,
    CoordinateDTO coordinate,
    Set<LocationType> locationTypes,
    String parentLocationId
) {}
```

Thanks.

**Comment by JayAhn2** [comment]
I found a reason 
I need to annotate @JsonProperty on each field as below.

```
public record NewLocationCommandDTO(
    @JsonProperty("id") String id,
    @JsonProperty("name") String name,
    @JsonProperty("level") LocationLevel level,
    @JsonProperty("coordinate") CoordinateDTO coordinate,
    @JsonProperty("types") Set<LocationType> types,
    @JsonProperty("parentId") String parentId
) {}
```

**Comment by someshrathi02** [comment]
Hi @JayAhn2 , 
Im facing similar issue and above solution not working for me. 
im using springfox swagger 3.0 , java 17 record and when i passed record as input (instead of using @RequestParam annotation )  to GET request , its not showing request object at all.

Your help is really appreciated..

**Comment by victorduransilva** [comment]
I'm not sure if it is related, but I can't use @Parameter(description =...) with Java Record, it only works with class.
Is there any workaround or solution for this?
