### ISSUE TITLE
Multiple swagger instances for a single application

### ISSUE THREAD

**Issue by ParagKadam101** [springfox/springfox#3693]
I want to host public and internal APIs on swagger UI and want to separate them out into different URLs like:-

/public/swagger-ui.html
/internal/swagger-ui.html

Currently, all my APIs are placed under /swagger-ui.html. Is there a way how I can achieve it using spring boot?

**Comment by PancakeInvaders2** [comment]
We achieved this by  defining in the SwaggerConfig class two distinct Dockets

> public Docket apiPrivate()
and
public Docket apiPublic()

In which I set two different groupName

> .groupName("apiPrivate")
and
.groupName("apiPublic")

And in which I set two different apis

> .apis(RequestHandlerSelectors.basePackage("myPackage"))
and
.apis(Predicates.and(RequestHandlerSelectors.basePackage("myPackage"), RequestHandlerSelectors.withMethodAnnotation(MyCustomAnnotationForWhiteListingPublicMethods.class)))

accessing the two via

> /api-docs?group=apiPublic
/api-docs?group=apiPrivate
and
/swagger-ui.html?urls.primaryName=apiPublic
/swagger-ui.html?urls.primaryName=apiPrivate

With MyCustomAnnotationForWhiteListingPublicMethods being 

> @Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface MyCustomAnnotationForWhiteListingPublicMethods { }

**Comment by ParagKadam101** [comment]
Thanks, @PancakeInvaders2 this segregates the public and private APIs in different URLs but then those with who we share the public API link can still access our private API using the "Select a spec" dropdown. Is there a way the dropdown can be hidden altogether?

<img width="1089" alt="Screenshot 2021-01-08 at 9 57 58 PM" src="https://user-images.githubusercontent.com/30956635/104040086-3b654380-51fd-11eb-832b-9eeecb2f7d59.png">

**Comment by PancakeInvaders2** [comment]
Sorry I don't know, we just retrieve the json from /api-docs?group=apiPublic, convert it to yaml, and send it via email without worrying about that. Good luck

**Comment by gustavopo** [comment]
Has anyone managed to do this somehow?
I have the same problem as @ParagKadam101 , I have the 2 urls:
/public/swagger-ui.html
/internal/swagger-ui.html

I want to limit access, whoever accesses the public cannot see the private and with the specs tabs this is not possible, they are all listed there.
 However, I am using OpenApi3.

**Comment by yurii-chikh-vitech** [comment]
> 

Hi.
Example how I implemented it - https://stackoverflow.com/a/76237886/4676400 

Long story short - I am filtering response for swagger-config based on current user role/
[swagger-config-to-filter](https://i.stack.imgur.com/f0LBw.png)

As result I control which API is available in swagger definition drop-down
