### ISSUE TITLE
REOPEN @ApiModelProperty.position not respected #1280

### ISSUE THREAD

**Issue by honza-zidek** [springfox/springfox#3707]
Please reopen the [issue #1280](https://github.com/springfox/springfox/issues/1280). 

See there in the comments that a lot of people complain that it has not been solved. 

I can confirm the same issue in version 3.0.0 (transitive dependency from springfox-boot-starter).

**Comment by akoni50** [comment]
This is still a problem, apiModelProperty position is ignored and properties are placed in a lexicographical order

**Comment by Wayne-Sun** [comment]
same issue found in springfox-boot-starter 3.0.0 with springboot 2.4.2

**Comment by akoni50** [comment]
is there an update?

**Comment by yunusb** [comment]
There is a PR that solves the problem. But It has been closed : 
https://github.com/springfox/springfox/pull/3573
There is also this ticket that is still open : 
https://github.com/springfox/springfox/issues/3391

There is too much duplicate ^^" Could you please close this one ?
