### ISSUE TITLE
Handling of complex data structures into standard interfaces

### ISSUE THREAD

**Issue by nigelsim** [springfox/springfox#3715]
Spring Fox 3.0.0

We accept and return GeoJSON object from our API. This results in `*Req` and `*Res` classes being generated, which are incorrect, and appear to be based on naive reflection on the objects.

The objects (`org.locationtech.jts.geom.*`) themselves are provided by https://github.com/locationtech/jts and we use https://github.com/graphhopper/jackson-datatype-jts to configure Jackson to correctly map these.

There exists [hand coded](https://app.swaggerhub.com/domains/ModelRocket/GeoJSON/1.0.0) schemas that could be used, but I can't see how to reference this using Spring Fox.

I have also tried to use the `JacksonSerializerConversion` for this package

```java
       @Bean
        AlternateTypeRuleConvention jacksonSerializerConvention(TypeResolver resolver) {
            return new JacksonSerializerConvention(resolver, "org.locationtech.jts.geom");
        }
```

What is the correct approach to this?

**Comment by drakulavich** [comment]
Have exactly the same problem.
