### ISSUE TITLE
additionalModels issue

### ISSUE THREAD

**Issue by paz-raon** [springfox/springfox#3731]
Please take the time to search the repository, if your question has already been asked or answered.

- v3.0.0

What kind of issue is this?

- [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

here is my model

```
    data class ErrorResponse(
        val errorCode: Int,
        val message: String,
        var xRequestId: String? = null
    )
```

in my swagger-ui

<img width="382" alt="스크린샷 2021-02-17 오후 10 02 07" src="https://user-images.githubusercontent.com/1497209/108208383-52884100-716c-11eb-9eb6-677fa329377c.png">

What happened to xRequestId property? 

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by ebrahimmfadae** [comment]
I'm using springfox 3.0.0 and spring-boot 2.6.2 with Kotlin 1.6.0 and i have a similar issue.

![image](https://user-images.githubusercontent.com/46930905/156374606-b05273fb-f09f-442a-bbac-38c5f81ea706.png)

Note: I tried to explicitly tell to springfox that it is a response model.

Only difference is commissionRewardsId which in one model is not required and in another, it is required!

Here is my class definiition in kotlin.
```kotlin
data class CheckoutRecordBody(
    val commissionRewardsId: Long,
    val rewardedUuid: String,
    val referentUuid: String,
    val referralCode: String,
    val richTrade: Long,
    val referentOrderDirection: OrderDirection,
    val share: BigDecimal,
    val createDate: Date,
    val checkoutState: CheckoutState,
    val transferRef: String?,
    val updateDate: Date
)
```

Probably there is an issue with `id` keyword in model properties.

EDIT:
I removed `id` from property name and result was the same. Also reordered properties which also failed. The only correct outcome i could get, was when the class only had one property of `String` type.
