### ISSUE TITLE
"No API definition provided" after upgrading from 2.9.2 to 3.0.0

### ISSUE THREAD

**Issue by kmiestmoore** [springfox/springfox#3743]
Hello,

I'm having some problems when upgrading to the latest springfox version, and I can't pinpoint the exact issue. Looking in the console, the /swagger-resources call is coming back empty: []

All the calls give a 200 response and seem to be working otherwise. The closest issue I've found was this one: #3345 

I think I've followed all the steps in the migration guide or in that issue. I removed the old dependencies, added the new one, removed @EnableSwagger2 from my swagger config file. I tried changing the documentation type as well. I'm sort of assuming the issue is some problem with how the project is set up, it's been ongoing for several years with a variety of developers so...who knows. Hopefully it's some obvious thing I'm missing, but any guidance would be appreciated.

pom.xml
```xml
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-boot-starter</artifactId>
    <version>3.0.0</version>
</dependency>
<dependency>
    <groupId>org.springframework.plugin</groupId>
    <artifactId>spring-plugin-core</artifactId>
    <version>2.0.0.RELEASE</version>
</dependency>
```
Swagger config
```java
@Configuration
@ConditionalOnProperty(prefix="jhipster.swagger", name="enabled")
public class SwaggerConfiguration {
    @Bean
    public Docket swaggerSpringfoxDocket(JHipsterProperties jHipsterProperties) {

        ApiInfo apiInfo = new ApiInfo(
            jHipsterProperties.getSwagger().getTitle(),
            jHipsterProperties.getSwagger().getDescription(),
            jHipsterProperties.getSwagger().getVersion(),
            jHipsterProperties.getSwagger().getTermsOfServiceUrl(),
            jHipsterProperties.getSwagger().getContactName(),
            jHipsterProperties.getSwagger().getLicense(),
            jHipsterProperties.getSwagger().getLicenseUrl());

        return new Docket(DocumentationType.SWAGGER_2) //also tried OAS_30 and SWAGGER_12
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(PathSelectors.any())
            .build()
            .apiInfo(apiInfo);
    }
}
```
Sample endpoint
```java
@RequestMapping(value = "/user-documents",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    @Secured(AuthoritiesConstants.ROLE_VIEW_DOCUMENTS)
    public ResponseEntity<List<UserDocumentDTO>> getAllDocumentsForSpecifiedUser(Pageable pageable, @ModelAttribute(value = "criteria") UserDocumentCriteria userDocumentCriteria)
        throws URISyntaxException {
        User loggedUser = userLoggedService.getLoggedUser();
        log.debug("REST request to get all the userDocuments for the specified user id {}", loggedUser.getId());
        final Page<UserDocumentDTO> page = userDocumentService.findAllForSpecifiedUser(loggedUser, pageable);
        final HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(page, "/api/user-documents");

        return new ResponseEntity<>(page.getContent(), headers, HttpStatus.OK);
    }
```
What I'm seeing in the UI
![image](https://user-images.githubusercontent.com/79465373/108734250-e489a400-74f4-11eb-9af4-4b0d65a8982e.png)
![image](https://user-images.githubusercontent.com/79465373/108734432-1569d900-74f5-11eb-8e15-544d38ef6cc7.png)

**Comment by exsinod** [comment]
Any luck fixing it? I am having the same issue.

**Comment by kmiestmoore** [comment]
Unfortunately no, we ended up just using this as a catalyst to convince the powers that be to update our project wholesale. We're in the middle of upgrading a 5 year old project to newer Spring versions, among other things.
