### ISSUE TITLE
SecurityContextBuilder.forPaths Deprecation / Migrating to SecurityContextBuilder.operationSelector

### ISSUE THREAD

**Issue by shnewton-CLGX** [springfox/springfox#3746]
**Using**: 
3.0.0

**Question**:
Does documentation exist for how to use `SecurityContextBuilder.operationSelector` instead of `SecurityContextBuilder.forPaths`?

I see that `SecurityContextBuilder.forPaths` [is deprecated since this 3.0.0 version](https://github.com/springfox/springfox/blob/ab5868471cdbaf54dac01af12933fe0437cf2b01/springfox-spi/src/main/java/springfox/documentation/spi/service/contexts/SecurityContextBuilder.java#L48).

But the documentation/examples I've found still use `SecurityContextBuilder.forPaths` so I'm not sure what the expected replacement logic should look like. 

For instance 
- https://springfox.github.io/springfox/docs/current/#springfox-spring-mvc-and-spring-boot 
- https://github.com/springfox/springfox-demos/blob/0c31da356e7463cd405652c7bde25c100a7efbf6/boot-swagger/src/main/java/springfoxdemo/boot/swagger/Application.java

Thanks for any pointers you can provide 😃

**Comment by ikarol-gomel-iba-by** [comment]
I might be doing it wrong, but probably something like this

SecurityContext.builder().operationSelector(o -> PathSelectors.regex("path_pattern").test(o.requestMappingPattern())).build();

**Comment by t0r0X** [comment]
Another example. Replace:
```
SecurityContext.builder()
        .forPaths(PathSelectors.any())
[...]
```
with:
```
SecurityContext.builder()
        .operationSelector(operationContext -> true)
[...]
```

**Comment by Runrioter** [comment]
```java
return SecurityContext.builder()
  .operationSelector(
    oc -> oc.requestMappingPattern().matches("path_regex")
  )
  .build();
```
