### ISSUE TITLE
Cannot override basepath in springfox3.0

### ISSUE THREAD

**Issue by linuradu** [springfox/springfox#3779]
I'm trying with springfox 3, to overwrite the basePath, but there is no chance.

The only workaround that I've found is to add a prefix to all endpoints, but not this is the behavior we need to have.

 ```
   @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("My API")
                .pathProvider(new DefaultPathProvider() {
                    @Override
                    public String getOperationPath(String operationPath) {
                        return "/my-path".concat(super.getOperationPath(operationPath));
                    }
                })
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.abc"))
                .paths(PathSelectors.any())
                .build()
                .apiInfo(apiDetails());
    }
```

**Comment by HoustonPagtakhan1** [comment]
Are you trying to override the basePath because it gets appended twice into the url used when testing through the swagger page?

**Comment by linuradu** [comment]
> Are you trying to override the basePath because it gets appended twice into the url used when testing through the swagger page?

No, I'm trying because my API when is deployed to Kubernetes has a basepath. And the problem is that swagger is trying to call my API endpoints calling them to the root (this is obvious that is not working).

**Comment by linuradu** [comment]
Here is the workaround that I've decided to use: https://stackoverflow.com/a/66786778/4507034

**Comment by miguelcabanes** [comment]
> Are you trying to override the basePath because it gets appended twice into the url used when testing through the swagger page?

Hi. How can I avoid this? (basePath in every http method). Thanks
