### ISSUE TITLE
Model scan missing properties that are visible during serialization only

### ISSUE THREAD

**Issue by gorjusborg** [springfox/springfox#378]
When a model class has a property that is only visible to jackson during serialization (due to a @JsonIgnore on the setter and @JsonInclude on the getter, for instance), the ApiModelReader returns a model that does not include the property. 

Example model class:

```
class ModelWithSerializeOnlyProperty {
  String alwaysVisible;
  @JsonIgnore
  private Long visibleForSerialize;

  @JsonProperty
  public Long getVisibleForSerialize() {
    return visibleForSerialize;
  }

  @JsonIgnore
  public void setVisibleForSerialize(Long visibleForSerialize) {
    this.visibleForSerialize = visibleForSerialize;
  }
}
```

Current scan result: 

```
models: {
    ...
    ModelWithSerializeOnlyProperty: {
        properties {
            alwaysVisible: { ... }
        }
    }
...
}
```

Correct scan result: 

```
models: {
    ...
    ModelWithSerializeOnlyProperty: {
        properties {
            alwaysVisible: { ... },
            visibleForSerialize: { ... }
        }
    }
   ...
}
```

**Comment by mkarasik** [comment]
Hi
I have 0.9.4 and I still have the described issue in my project. I have looked ApiModelReader and it has the method mergeModelMap, so I assume that it supposed to be fixed. However I see the same model for get and set methods.


My code is
...
@JsonIgnore
private Boolean built_in;

..
 @JsonProperty
    public Boolean isBuilt_in() {
        return built_in;
    }

    @JsonIgnore
    public void setBuilt_in(Boolean built_in) {
        this.built_in = built_in;
    }
..

This field isn't present in the swagger model at all. Jackson is working as expected, the field is returned on get and ignored on set.

Is there anything I am missing?

**Comment by dilipkrish** [comment]
@mkarasik Just so I understand.. 

You have Model with this particular set of annotations. What are you doing with the model? 
  - Is this a model returned from a method?
  - is this a model that also a method parameter?

The merge kicks in only if the model is used in the context of serialization (input param) as well as deserialization (return value).

**Comment by mkarasik** [comment]
It is used as the returned value of GET method and as input value @RequestBody in POST method.
