### ISSUE TITLE
How to modify collection format style with 3.0.0?

### ISSUE THREAD

**Issue by Cyronlee** [springfox/springfox#3780]
I am using springfox-boot-starter:3.0.0 to generate openApi 3.0 with SwaggerUI.

I have learned that if I want to use comma-separated query in SwaggerUI, 
The format style need  to be "simple" but not "pipeDelimited".

I tried using 
`@ApiImplicitParam(allowMultiple = true, dataType = "string", collectionFormat = "csv")`
and
`@Parameter(style = ParameterStyle.SIMPLE)`
but it didn't work.

So how to modify the collection format style?
Thanks for help!!!

Sample code
```java
@GetMapping("/test")
public void test(TestParams testParams) {    
}

public class TestParams {
    List<String> list1;
}
```

json data of /v3/api-docs
```json
{
    // ...
    "parameters": [
        {
            "name": "list1",
            "in": "query",
            "required": false,
            "style": "pipeDelimited", << How to modify this to simple?
            "schema": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    ]
    // ...
}
```

**Comment by night-crawler** [comment]
Have the same issue here. The final style seems to be chosen in `springfox.documentation.builders.QueryParameterSpecificationProvider#create`:

```java
} else if (model.getCollection().isPresent()) {
  ParameterStyle style =
      VALID_COLLECTION_STYLES.contains(simpleParameter.getStyle())
          ? simpleParameter.getStyle()
          : simpleParameter.nullSafeIsExplode()
          ? ParameterStyle.FORM
          : ParameterStyle.PIPEDELIMITED;
```

For some reason, it prefers `pipeDelimited` over the `form`.

**Comment by Cyronlee** [comment]
@night-crawler yep, I found that the `VALID_COLLECTION_STYLES` just have those three styles.

I don't know how to add `SIMPLE` into it.

```java
class QueryParameterSpecificationProvider implements ParameterSpecificationProvider {
  static final List<ParameterStyle> VALID_COLLECTION_STYLES =
      Arrays.asList(
          ParameterStyle.FORM,
          ParameterStyle.SPACEDELIMITED,
          ParameterStyle.PIPEDELIMITED
      );
}
```

**Comment by ATAKing1023** [comment]
found the same issue... it comes with expanded parameters, just as @night-crawler pointed out

**Comment by Delirante** [comment]
+1

**Comment by Brikkbaby87** [comment]
Help

**Comment by pperevoznyk** [comment]
+1

**Comment by duffyishere** [comment]
+1
