### ISSUE TITLE
@ApiParam(example ="EXAMPLE_VALUE") is ignored in Swagger UI for @PathVariable and @RequestParam in springfox 3.0.0

### ISSUE THREAD

**Issue by honza-zidek** [springfox/springfox#3799]
### Summary
`@ApiParam(..., example ="EXAMPLE_VALUE")` does not work, neither for `@PathVariable` nor for `@RequestParam` in springfox 3.0.0.

The **`example`** is completely ignored in the Swagger UI.

### Versions:
``` lang-xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.4.4</version>
</parent>
...
<dependencies>
    ....
    <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-boot-starter</artifactId>
        <version>3.0.0</version>
    </dependency>
    ....
</dependencies>
```

### Code:
``` lang-java
import io.swagger.annotations.ApiParam;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(value = "/hello")
public class HelloController {
    @GetMapping("/hello1/{name}")
    public String helloPathVariable(
            @ApiParam(value = "Greeting via path variable", example = "Honza") @PathVariable String name
    ) {
        return "Hello, " + name + "!";
    }

    @GetMapping("/hello2")
    public String helloRequestParam(
            @ApiParam(value = "Greetings via request param", example = "Honza") @RequestParam String name
    ) {
        return "Hello, " + name + "!";
    }
}
```

### Behaviour:

In the "Try it out" section, the `name` fields generated in Swagger UI do not contain the expected value `"Honza"` from the `example`.

### Attached:

Screenshots from Swagger UI.

![SwaggerUI-PathVariable](https://user-images.githubusercontent.com/5145994/115051264-eb250e00-9edc-11eb-9d15-7a87cc15948a.png)
![SwaggerUI-RequestParam](https://user-images.githubusercontent.com/5145994/115051265-eb250e00-9edc-11eb-9946-4c7bada779d3.png)

**Comment by tokiodeo** [comment]
Use  `@Parameter`

**Comment by Demactus** [comment]
Just encountered the same problem, still no fix for this?

**Comment by honza-zidek** [comment]
@Demactus Just a warning - Springfox is dead, use [Springdoc Open API](https://springdoc.org/v2/) instead.
I am not promising that the bug is fixed there either, but waiting for the fix in springfox is no good.

**Comment by Demactus** [comment]
Yes, after I further read into it I migrated our project to Springdoc 
But thanks for the answer anyway 👍
