### ISSUE TITLE
Almost half of year without any commit, this repo is dead?

### ISSUE THREAD

**Issue by pumano** [springfox/springfox#3800]
half of year without any commit, 318 issues, mostly without response, 56 pull requests mostly without response...Bugs with years in issues...

What future of this project?

@dilipkrish @adrianbk @MaksimOrlov

**Comment by lucheng2** [comment]
I've met at least 4 bugs not fixed. Is there an alternative? It seems that swagger-ui is a better choice.

**Comment by pumano** [comment]
@lucheng2 check out https://github.com/springdoc/springdoc-openapi, i don't test it, but want to try.

**Comment by jfougere** [comment]
I was also waiting for some fixes, but now I am also wondering about switching to springdoc!

**Comment by lucheng2** [comment]
@pumano Thanks, I think springdoc-openapi worth a shot. The official doc pointed out how to migrate from springfox, linking: https://springdoc.org/#migrating-from-springfox. Migration needs to convert all related annotations, maybe need several hours to finish replacement. @jfougere can give it a try.

**Comment by jfougere** [comment]
@lucheng2 yes I think I'll give it a try. On JHipster they thought about switching to springdoc but the release of the 3.0.0 make them keep springfox. But since there was zero activity... I suppose they will be a general move for other alternatives!

**Comment by atkawa7** [comment]
@dilipkrish Is it possible to give others commit access to this so they can fix bugs if you have a lot on plate. I am sure a others would be happy to take the load off your shoulders.

**Comment by lucheng2** [comment]
I've finished the migration from springfox to springdoc, so far so good.

**Comment by atkawa7** [comment]
@lucheng2 I currently use api first with https://github.com/OpenAPITools/openapi-generator. So I am stuck
