### ISSUE TITLE
enum order is shuffled in generated swagger

### ISSUE THREAD

**Issue by ekuleshov** [springfox/springfox#3805]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

3.0.0

What kind of issue is this?

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [x] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [x] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

Springfox is shuffling enum values in generated swagger.

The Java enum in the data model look like this:

```
@JsonFormat(shape = JsonFormat.Shape.NUMBER)
public enum ResponseType {
    // order is important - ordinal
    Succeeded, // = 0
    TimeOut, // 1
    SystemError, // 2
    NotImplemented, // 3
    NotConnected, // 4
    MessageSize // 5
}
```
And generated type in swigger is like:

```
          "type" : {
            "type" : "string",
            "enum" : [
              "MessageSize",
              "NotConnected",
              "NotImplemented",
              "Succeeded",
              "SystemError",
              "TimeOut"
            ]
          }
```          

Note that java model uses `JsonFormat.Shape.NUMBER` to have enum serialized as integer ordinal value. But string values in swagger have different order, so the ordinal values does not match with the java model.

I traced this to constructor of `springfox.documentation.schema.EnumerationFacet`, which is forcefully reordering enum elements and does not provide any alternative to override this behaviour.

```
  public EnumerationFacet(Collection<String> allowedValues) {
    this.allowedValues.addAll(allowedValues);
    this.allowedValues.sort(Comparator.naturalOrder());
  }
```

and also `springfox.documentation.builders.EnumerationElementFacetBuilder` is loading enum values into a `HashSet`. Using the `LinkedHashSet` would allow to preserve the original enum order:

```
public class EnumerationElementFacetBuilder implements ElementFacetBuilder {
  private final Set<String> allowedValues = new HashSet<>();
  
  ...
  public static Set<String> from(AllowableValues allowableValues) {
    if (allowableValues instanceof AllowableListValues) {
      return new HashSet<>(((AllowableListValues) allowableValues).getValues());
    }
    return new HashSet<>();
  }
```

**Comment by gqxie** [comment]
Is the problem fixed?I've had this problem too
