### ISSUE TITLE
@ApiModel(hidden=true)

### ISSUE THREAD

**Issue by sean-n-riley** [springfox/springfox#3806]
I am using 

```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-boot-starter</artifactId>
    <version>3.0.0</version>
</dependency>
```
 and I am looking for a way to hide a model.

So similar to how we can do
```
@ApiOperation(value = "This is a hidden ,method", hidden = true)
```
I would like to know how to do
```
@ApiModel(hidden=true)
```
so that it doesn't show up in the swagger documentation.

**Comment by SXI-XLayer** [comment]
I was looking for a way to hide a model.

So similar to how we can do 

<@ApiOperation(value = "This is a hidden ,method", hidden = true)>

I would like to know how to do

<@ApiModel(hidden=true)>

so that it doesn't show up in the swagger documentation.

**Comment by muwn** [comment]
`@ApiModelProperty(value = "createTime", hidden = true)
private List<Timestamp> createTime;`
同样出现这个问题
![image](https://user-images.githubusercontent.com/9361471/116674736-98b51880-a9d7-11eb-9d8f-4394b7b27ca0.png)
