### ISSUE TITLE
3.0.0 to be work for spring 4 mvc and java 1.8.

### ISSUE THREAD

**Issue by sweetypreety** [springfox/springfox#3809]
I have tried with version 2.9.2 and it was working fine on locally..but when the same deployed on AWS it won't run over there and throws error 502 Bad Gateway.

Then, Again i tried to use by refering this issue https://github.com/springfox/springfox/issues/3300 setup for version 3.0.0

But, I guess it has  swagger 3.0.0 version compatibility issue with spring 4.x version.

Can you please suggest, What to implement for swagger version 3.0.0 to make Spring4 MVC project work swagger-UI.

**Comment by esotericman** [comment]
I use version 3.0.0 and spring boot 2.3.2, It's okay
