### ISSUE TITLE
SpringFox is incompatible with spring-boot-starter-validation

### ISSUE THREAD

**Issue by sercheo87** [springfox/springfox#3814]
Actually add dependency **_io.springfox:springfox-boot-starter:3.0.0_** with **_org.springframework.boot:spring-boot-starter-validation:2.4.0_**.

The incompatibility is between _Javax Validation_ and _Jakarta Validation_ depend by **Spring Validation**

**Comment by flmelody** [comment]
you could just remove springfox-boot-starter,and create another one starter youself

**Comment by esotericman** [comment]
you could just remove springfox-boot-starter,and create another one starter yourself
