### ISSUE TITLE
Upgrading to 3.0.0 forces 401 response code to /swagger-ui.html

### ISSUE THREAD

**Issue by KathrynN** [springfox/springfox#3817]
### What is the problem?
After upgrading to 3.0.0 I am unable to access my /swagger-ui.html page, instead getting a 401 response.  The only thing that has changed inbetween builds is the version of swagger-fox libraries.  I have WebSecurityConfigurerAdapter with a configuration ignoring the swagger-ui.html endpoint, and this works correctly when using 2.9.2.

```    
    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring().antMatchers("/v2/api-docs",
                "/swagger-resources/**",
                "/swagger-ui.html");
    }
```

```
<oauth>
<error_description>Full authentication is required to access this resource</error_description>
<error>unauthorized</error>
</oauth>
```

v2/api-docs, swagger-resources/configuration/ui still works, but GET /swagger-ui.html does not (401) -  (I was/am using  http://localhost/swagger-ui.html )

I get this error message regardless of whether I'm logged in or not - not that it should matter as I need the API to be fully open to the public.

Does anybody have any ideas on things I might have missed migrating between the two?  Documentation much appreciated!

### More Information:
I upgraded from 2.9.2 to 3.0.0 in all three artifacts (springfox-swagger2, springfox-swagger-ui, springfox-bean-validators.
I also tried including additional dependency from announcement post, swagger-core, and then later using bundled dependencies for spring-boot, springfox-boot-starter.  The only thing that worked was downgrading to 2.9.2 again.
I could not see anything in the logs when hitting the page.

### What kind of issue is this?
Call for help!  🍵

**Comment by KathrynN** [comment]
Further investigation:
This is my docket:
```
    @Bean
    public Docket swaggerDocumentation() {
        return new Docket(DocumentationType.SWAGGER_2)
                .ignoredParameterTypes(Authentication.class)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.example.not.mine"))
                .build()
                .apiInfo(appApiInfo());
    }
```

**Comment by porfirioribeiro** [comment]
The url is now `/swagger-ui/index.html`

**Comment by KathrynN** [comment]
That would be it!  Thank you.  Must have missed that in the announcement / docs :)
