### ISSUE TITLE
Springfox Swagger UI doesn't show description and parameters for post operation.

### ISSUE THREAD

**Issue by sharathkolibyle** [springfox/springfox#3831]
I have my yaml file with get and post operation which are having description. 

But springfox swagger ui does show description for get operation. However doesn't show description for post operation. Is it a bug or am I doing something wrong. 

I am using springfox 3.x version. 

<img width="941" alt="Screen Shot 2021-06-10 at 12 30 42 PM" src="https://user-images.githubusercontent.com/19248979/121585685-b66a9a00-c9e7-11eb-9c4b-295c0176db10.png">

**Comment by ebrahimmfadae** [comment]
I have the same issue. When I change @PostMapping to @PutMapping or @GetMapping it is working correctly.
