### ISSUE TITLE
Inferred url is http, not https

### ISSUE THREAD

**Issue by agilehorse** [springfox/springfox#3835]
Hello, 
we have a problem on our project. 
Our server uses HTTPS protocol, but the swagger ui has HTTP as inferred url.

We are using the version 3.0.0. The app is plan spring (not boot).

Additionally here is the Docket
![image](https://user-images.githubusercontent.com/39390272/122110172-87588c00-ce1e-11eb-9f68-1b1f241a89dc.png)

**Comment by mrjavascript** [comment]
I'm having the same issue.  The change to OAS_30 broke it for me, and my inferred URL reads something like http://dev-api.example.com:443.  I've tried setting "host" and also "servers" on the docket object, and this server URL won't change.
