### ISSUE TITLE
springfox-boot-starter-3.0.0 @ArraySchema doesn't work

### ISSUE THREAD

**Issue by dimayasyuk** [springfox/springfox#3852]
Hi
I migrated from swagger 2.9.2 to springfox-boot-starter-3.0.0 in spring boot application and I ran into a problem
I have rest endpoint that returns ResponseEntity<String> but String is json that can contain some different objects
So I tried to define the following:
    @Operation( responses = @ApiResponse(
                    responseCode = "200",
                    content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                           array = @ArraySchema(schema = @Schema(implementation = Some.class))
            )
    )

but it doesn't work and schema is defined just as string
![image](https://user-images.githubusercontent.com/22641418/125074797-6f46f600-e0c6-11eb-8cf7-6ec47c8da639.png)

@Parameter array has the same situation

**Comment by hawk-jakub-wieczorek** [comment]
Please reopen. It doesn't work
