### ISSUE TITLE
Question: Request Body parameter - how to provide different json examples for a common object used across multiple endpoints

### ISSUE THREAD

**Issue by robsquireq** [springfox/springfox#3855]
- Tried with version 2.9.2 and 3.0.0

I'll try to explain my problem as clearly as possible...

We have numerous endpoints in our system that specify the same @requestbody object and essentially we would like to provide example json requests to each specific endpoint. The request object itself has fields we wish to exclude in some cases and not in others. Ideally I am looking to annotate our Spring Rest controller methods each with an exact json string which would show as a useful visual for the user in the swagger UI.

Lets say I have a Request object class that represents our object for multiple endpoints:

```
public class PrepRequest{

    String name;
    String type;
    Location location;
    Destination destinaton;
}
```

If I have two different endpoints that both receive the PrepRequest above - for the first one I want the example to show on swagger UI as let's say:

{
   'name' : 'A',
   'type' : 'search'
}
and for the second endpoint I would like to display the example json to the user as:

{
   'type' : 'compute',
   'location': {
       'state': 'CA'
   }
}
This is just a super basic example - I hope it makes sense but we basically need to modify the example json per endpoint so that the user will know which style of request to provide.

I have seen in numerous places the possibility of using @ApiImplicitParams just above the controller endpoint method or by tagging the request body parameter as @ApiParam(examples = @example(...

But in both cases I cannot seem to get the example json window of swagger to actually show what I would like to see...in all cases it seems to give me the full requestBody object and all of it's fields.

Is there a way to tag per controller endpoint or at the Api parameter level - the exact json I want to show to the end user in swagger as an example?

**Comment by superlucky8848** [comment]
I meet a similar issue and find a workaround. Please check issue [#3903](https://github.com/springfox/springfox/issues/3903) to see if the workaround can adress your issue, too.

**Comment by robsquireq** [comment]
I ended up finding another approach using 

```
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
 </dependency>
```

I was able to annotate the request body by using the annotation for RequestBody in open api: 
@io.swagger.v3.oas.annotations.parameters.RequestBody

This allowed me to provide multiple schema definitions and also multiple json string examples:



```
@io.swagger.v3.oas.annotations.parameters.RequestBody(content = @Content(mediaType = "application/json",
            schema = @Schema(oneOf = {FirstSchema.class, SecondSchema.class, ThirdSchema.class}),
            examples = {
                    @ExampleObject(name = "Example A", summary = "Summary for A", value = RequestExampleStrings.EXAMPLE_A_JSON),
                    @ExampleObject(name = "Example B", summary = "Summary for B", value = RequestExampleStrings.EXAMPLE_B_JSON)
            })) @RequestBody @NotNull GenericRequest
```
            
You can see in the above there are now two annotations for @RequestBody - the first is the version 3 open api one which allows us to specify schemas and examples for that Request body, the second annotation is the default spring bind to allow the incoming request to bind its values to the object.

Hopefully this helps others.
