### ISSUE TITLE
documentation for migrating to 3.0.0 for regular web mvc doesnt seem to be correct

### ISSUE THREAD

**Issue by ripjal** [springfox/springfox#3869]
This is question regarding the documentation for[ migration to 3.0.0](https://github.com/springfox/springfox#migrating-from-earlier-snapshot) for regular webmvc .
As per link I removed springfox-swagger2 and added spring-oas. Tried adding EnableSwagger2WebMvc as per recommendation as I want to continue using swagger 2 specs but it is not resolving with this new librarys

**Comment by ducquoc** [comment]
```
@EnableSwagger2 was deprecated in swagger 2.10+

@EnableSwagger2WebMvc is deprecated in 3.0.0+

Funny but true :)
```
Source: https://stackoverflow.com/questions/62539860/replace-enableswagger2-after-update-to-latest-version

Also, the 2.10.x seems not working with SpringBoot 1.5.x , when I open the page it's blank though used to be fine with 2.9.2, 2.8, 2.7 . 
There are a few other tickets about 2.10.x not to be used - so I think the `@EnableSwagger2WebMvc` is not in practical usage.
