### ISSUE TITLE
Wrong content type when using OpenAPI 3

### ISSUE THREAD

**Issue by MrAxxy** [springfox/springfox#3892]
I sadly encountered fairly similar problem to https://github.com/springfox/springfox/issues/1539.

Using _Springfox 3.0.0_ with _OpenAPI 3_(`DocumentationType.OAS_30`)

Example:
```
@RequestMapping(path = "/apples/", consumes = "application/merge-patch+json", method = RequestMethod.PATCH)
public ResponseEntity<?> storeApples(@RequestBody @Nonnull List<Apple> apples) {
    // some code
}
```

`contentType` in generated docs should be only `application/merge-patch+json`. The thing is, there are two content types:
![IncorrectContentTypeDocs](https://user-images.githubusercontent.com/11676585/130986703-6821abc8-5a87-411b-98f4-8cfffaff4f0b.png)
And unwanted content type(`application/json`) is default in dropdown.

If I change doc type to _Swagger 2_(`DocumentationType.SWAGGER_2`), `contentType` behaves as expected.
![correctContentType](https://user-images.githubusercontent.com/11676585/130991110-039ef527-16f9-43b9-b902-421803b3a541.png)

Solution proposed in https://github.com/springfox/springfox/issues/1539 not wok for me, when I use  _OpenAPI 3_(_Swagger 2_ works as mentioned). 

Therefore I decided to create new issue(solution in original issue works for version used by reporter, this problem seems to be connected only to use of _OpenAPI 3_).

**Comment by fisco-unimatic** [comment]
You can delete the unwanted content types from the specification by implementing WebMvcOpenApiTransformationFilter as a Spring bean (annotate the class `@Component`). Someting like this:

    @Override
    public OpenAPI transform(OpenApiTransformationContext<HttpServletRequest> context) {
        OpenAPI specification = context.getSpecification();
        forEachPathOperation(specification, this::restrictRequestsTypes);
        return specification;
    }

    private void forEachPathOperation(OpenAPI specification, Consumer<Operation> task) {
        specification.getPaths().values().forEach(path -> path.readOperations().forEach(task));
    }

    private void restrictRequestsTypes(Operation operation) {
        if (nonNull(operation.getRequestBody()) && nonNull(operation.getRequestBody().getContent())) {
            operation.getRequestBody().getContent().remove(APPLICATION_JSON_VALUE);
        }
    }
