### ISSUE TITLE
springfox swagger 3 annotation @ApiResponse doesn't work

### ISSUE THREAD

**Issue by arthur37231** [springfox/springfox#3907]
I'm using the springfox latest version and the maven dependency is
```xml
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-boot-starter</artifactId>
    <version>3.0.0</version>
</dependency>
```

Issue:

Annotations `io.swagger.v3.oas.annotations.responses.ApiResponse (@ApiResponse)` and `io.swagger.v3.oas.annotations.responses.ApiResponses (@ApiResponses)` defined in swagger 3.0 are not rendered on the UI page. I checked a similar issue was addressed in an old version in https://github.com/springfox/springfox/issues/2767#issue-378136054

I experimented with the solution on my demo program and it still works. However, the page rendering had no effect if I tried to write it with new annotations provided in 3.0 version.

Below is my imitated solution if my understanding of annotations and attributes is correct.

![image](https://user-images.githubusercontent.com/48077414/135279794-91b04a42-a8b4-4c4b-9911-a830b55f404d.png)

But there is nothing on the corresponding UI page.

![image](https://user-images.githubusercontent.com/48077414/135280337-ff88a92e-71d0-4394-8494-2f169a755863.png)

I have seen @dilipkrish encouraged us to continue to use annotations in the 2.x version because they will be still supported in the new version. But I am curious about how to use the new features to generate API documentation.

In addition, there is almost no tutorial about 3.x new features in the reference doc. This has brought great difficulties to beginners who use the latest version. I hope someone can update it as soon as possible.

**Comment by DaviesDiDo** [comment]
In my honest point of view the project is not active. There are many pull requests that are pending, many issues without response. There is another library that is compatible with this that is called spring-doc. I have not any kind of relation with that project, but I'm trying to help another developer to solve its problems

**Comment by arthur37231** [comment]
Hi Davide, can you show me any link to that project you mentioned? I don't mind whether any of you are related to other projects. I'm just a normal developer, so it would be great if it is exactly a helpful tool.

**Comment by DaviesDiDo** [comment]
Hi Artur, here the homepage of the project https://springdoc.org/ and here the specific page of migration from the Springfox annotations to the Springdoc ones https://springdoc.org/#migrating-from-springfox . Let me say that the Springdoc's annotations are more compliant to the OpenAPI documentation and to adhere better to the standards of MicroProfile interfaces.
