### ISSUE TITLE
Migration guide clarification.

### ISSUE THREAD

**Issue by akuma8** [springfox/springfox#3911]
Hi there,
I am using Spring Boot and would like to migrate from version 2.9.2 to 3.0.0 but looking at the migration guide [here](https://github.com/springfox/springfox#migrating-from-existing-2x-version) I noticed this:
>5. If you are using WebMvc but you don't use the @EnableWebMvc annotation yet, add this annotation.

Why adding `@EnableWebMvc ` in a Spring Boot application since it will disable spring mvc auto-configuration?
Thanks for your clarification

**Comment by uniquejava** [comment]
@akuma8 
I used this migration guide: https://springdoc.org/#migrating-from-springfox, it's a very smooth migration, the code/annotations are much less and conciser.
