### ISSUE TITLE
Do you plan to no longer maintain this project?

### ISSUE THREAD

**Issue by akuma8** [springfox/springfox#3912]
This is not really an issue but a request of information. 
I would like to know the future of this great project, do you plan to no longer maintain it? 
We can see that the last commit dates from last year and the issue backlog is growing, so should users think to switch to another solution. I know it's really hard to have time, in my case I would like to occasionally contribute if possible. 
Please let me know. 
Thank you again for that project.

**Comment by wacaine** [comment]
I have been using springfox for +3 years.  Each time it comes close to not being updated and I consider switching to a different api springfox comes out with a newer release.  Better late than never, a release comes out with what I need.   I am at the "I need a new release" stage again.   I want to upgrade to spring 2.5.  I have been looking at https://springdoc.org/#faq as a possible replacement.   Still need to try it out to see how big the gap is.

**Comment by babyhuey** [comment]
@dilipkrish @martypitt @adrianbk ?

**Comment by wacaine** [comment]
Is no answer after about a week answer enough?

**Comment by babyhuey** [comment]
I'd like to at least hear from a maintainer. Maybe they could hand off to people that want to take care of it. There is obviously a large amount of people that want to use this tool.

**Comment by zsm5833** [comment]
the [last commit](https://github.com/springfox/springfox/commit/ab5868471cdbaf54dac01af12933fe0437cf2b01) a year ago  might be a sign of deprecation, and i think there was merely one maintainer who was actually doing the work. However, i found out the sole maintainer of the repo has landed a job at Oracle just after the last commit, so I suspect he doesn't wanna take time into this in anytime soon (that's just my observation).

**Comment by slogic** [comment]
https://search.maven.org/artifact/org.thingsboard/springfox-boot-starter/3.0.4/jar

is it official now?

**Comment by kdebski85** [comment]
Springdoc is a good replacement, but it supports Swagger 3 annotations only. Springfox supports both Swagger 2 and 3 annotations.
The issue is that when you use OpenAPI Generator (https://github.com/OpenAPITools/openapi-generator) to generate classes from OpenAPI definitions, generated classes contain Swagger 2 annotations (https://github.com/OpenAPITools/openapi-generator/issues/10814).

**Comment by t0r0X** [comment]
@martypitt  @dilipkrish @adrianbk 
Do you plan to no longer maintain this project?

**Comment by martypitt** [comment]
Hi.

I've moved on to other projects, and at this stage have no plans to
contribute to this project further.

Best


Marty

**Comment by MartinX3** [comment]
Switch to SpringDoc.
