### ISSUE TITLE
where is ServiceModelToSwagger2MapperImpl.java?

### ISSUE THREAD

**Issue by lnsane** [springfox/springfox#3916]
i not found ServiceModelToSwagger2MapperImpl.java in source code!!

**Comment by kampatra** [comment]
I'ts springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl;
This is under springfox-swagger2-3.0.0.jar

I used it to customize the response example to read from json file (from resource path).

**Comment by lnsane** [comment]
@kampatra 
hi, I'm not found ServiceModelToSwagger2MapperImpl file in springfox/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ dir!!!

**Comment by kampatra** [comment]
Check the bellow dependencies, I used to customize  and override the method from ServiceModelToSwagger2MapperImpl.java


		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>3.0.0</version>
		</dependency>
<dependency>
		<groupId>org.mapstruct</groupId>
		<artifactId>mapstruct</artifactId>
		<version>1.4.2.Final</version>
	</dependency>

-------------------

I override the method mapResponses() to replace response example from json file:

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;

import org.mapstruct.factory.Mappers;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

import io.swagger.models.Model;
import io.swagger.models.Response;
import springfox.documentation.schema.Example;
import springfox.documentation.service.Header;
import springfox.documentation.service.ModelNamesRegistry;
import springfox.documentation.service.Representation;
import springfox.documentation.swagger2.mappers.ModelSpecificationMapper;
import springfox.documentation.swagger2.mappers.PropertyMapper;
import springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl;
import springfox.documentation.swagger2.mappers.VendorExtensionsMapper;

@Component
@Primary
public class Swagger2MapperExtensionImpl extends ServiceModelToSwagger2MapperImpl {

	@Override
	protected Map<String, Response> mapResponses(Set<springfox.documentation.service.Response> from,
			ModelNamesRegistry modelNamesRegistry) {
		Map<String, Response> responses = new TreeMap<>();
		for (springfox.documentation.service.Response each : from) {
			Response response = new Response().description(each.getDescription());
			for (Representation representation : each.getRepresentations()) {
				Model responseModel = Mappers.getMapper(ModelSpecificationMapper.class)
						.mapModels(representation.getModel(), modelNamesRegistry);
				response.setResponseSchema(responseModel);
			}
			response.setHeaders(each.getHeaders().stream().collect(Collectors.toMap(Header::getName, h -> Mappers
					.getMapper(PropertyMapper.class).fromModel(h.getModelSpecification(), modelNamesRegistry))));
			Map<String, Object> extensions = new VendorExtensionsMapper().mapExtensions(each.getVendorExtensions());
			response.getVendorExtensions().putAll(extensions);
			Map<String, Object> examples = mapExamples(each.getExamples());
			response.setExamples(examples);
			responses.put(String.valueOf(each.getCode()), response);
		}
		return responses;
	}

	 public Map<String, Object> mapExamples(List<Example> from) {
		    Map<String, Object> examples = new TreeMap<>();
		    for (Example each : from) {
		    	String exampleValue = (String)each.getValue();
		    	if (exampleValue.startsWith("file:")) {
		    		exampleValue = readFileContent(exampleValue);
				}
		    	examples.put(each.getMediaType().orElse(""), exampleValue);
		    }
		    return examples;
		  }
}


---------
public String readFileContent(String example) {
		String fileContent = "";
		try {
			String fileName = example.replace("file:", "");
			File resource = new ClassPathResource(fileName).getFile();
			fileContent = new String(Files.readAllBytes(resource.toPath()));
		} catch (Exception e) {
			LOGGER.error("Cannot read swagger documentation from file {}", example);
		}
		return fileContent;
	}

**Comment by lnsane** [comment]
@kampatra  Why can I find it in the dependencies, but I can’t find this class in the source code ServiceModelToSwagger2MapperImpl.java

**Comment by lnsane** [comment]
@kampatra ServiceModelToSwagger2MapperImpl.java 
 automatically generated when packaging?
