### ISSUE TITLE
[Bug] About using Spring Cloud Gateway, the "X-Forwarded-Prefix" header isn't work...

### ISSUE THREAD

**Issue by wuyueqpwoa** [springfox/springfox#3918]
Sorry, I'm bad in English...

I'm using latest released version 3.0.0.
There has 2 project: gateway and commodity.

1. commodity status
- Port=8081
- DOC Address=http://127.0.0.1:8081/v3/api-docs
- UI Address=http://127.0.0.1:8081/swagger-ui/index.html
- `"servers":[{"url":"http://127.0.0.1:8081","description":"Inferred Url"}]`

2. gateway status
- Port=8080
- DOC Address=http://127.0.0.1:8080/commodity/v3/api-docs
- UI Address=http://127.0.0.1:8080/commodity/swagger-ui/index.html
- `"servers":[{"url":"http://127.0.0.1:8080","description":"Inferred Url"}]`

The problem is, using gateway UI to access api, will get 404.
I think the gateway servers url is missing a "/commodity".

If DOC return `"servers":[{"url":"http://127.0.0.1:8080/commodity","description":"Inferred Url"}]`
That's great!

**Comment by esotericman** [comment]
you can add a bean of type WebMvcOpenApiTransformationFilter,and do it yourself.
