### ISSUE TITLE
upgrade swagger-ui version

### ISSUE THREAD

**Issue by JohannesProbst** [springfox/springfox#3921]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

version 3.0.0 of springfox-boot-starter

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [x] Bug report.
 examples for requestbody are not showing up in the ui.

 - [x] Feature Request.

Current version shipped by springfox-boot-starter via springfox-swagger-ui of swagger-ui is version 3.26.2. Could u please upgrade to latest stable version (as of writing this should be version 3.52.5).

Currently i face the issue that the dropdown for requestbody examples is not showing up in the ui. To be able to show multible different possible requestbodies the user can try to use via the ui is a relevant feature missing for via swagger-codegen generated server stubs using springfox. 

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by t0r0X** [comment]
The fork https://github.com/thingsboard/springfox seems to contain the `swagger-ui` version you wanted, 3.52.5: https://github.com/thingsboard/springfox/commit/3c055e8931d257888d0a9239be4dda0e1a0a863e
