### ISSUE TITLE
Mark repository as abandoned

### ISSUE THREAD

**Issue by lol768** [springfox/springfox#3923]
No longer actively maintained, should be archived: https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

**Comment by DaviesDiDo** [comment]
Here a valid alternative https://springdoc.org/ (disclaimer: i'm not involved in any way in that project, I'm only a developer that whants help other people to create better code, too many blogs and video tutorial suggesting to use this abandoned library)
