### ISSUE TITLE
how to manually adding api Infomation by dynamic params

### ISSUE THREAD

**Issue by aya-momo** [springfox/springfox#3939]
springboot：2.5.6
springfox-boot-start: 3.0

I use the dynamic controller of springboot. When I adding a new controller, I also want to add the  Api documentation to Swagger.
I tried to use ApiListingScannerPlugin, but I found that the plugin can only generate some fixed API documentation when the project starts.Can you give me some suggestions?

**Comment by t0r0X** [comment]
@a2011318824  Is this what you're looking for?
https://docs.swagger.io/swagger-core/current/apidocs/io/swagger/annotations/package-summary.html
