### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Deathkon** [springfox/springfox#3946]
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null

**Comment by zaenk** [comment]
the source of the seems to be line 80 here: 

https://github.com/springfox/springfox/blob/ab5868471cdbaf54dac01af12933fe0437cf2b01/springfox-spring-webmvc/src/main/java/springfox/documentation/spring/web/plugins/WebMvcRequestHandlerProvider.java#L71-L82

which uses this method, and here `this.condition` is null in some cases:

https://github.com/springfox/springfox/blob/ab5868471cdbaf54dac01af12933fe0437cf2b01/springfox-spring-webmvc/src/main/java/springfox/documentation/spring/web/WebMvcPatternsRequestConditionWrapper.java#L55-L59

The code above relies on this property:

https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/RequestMappingInfo.java#L88-L89

not being null which is not always true

If all the endpoints are defined in some kind of `@Controller` annotated methods, the `org.springframework.web.servlet.mvc.method.RequestMappingInfo#patternsCondition` is populated and springfox is happy.

Issue occurs when actuator is enabled, as this property is not initialised for actuator endpoints.

On the other hand, actuator endpoints seem to have `org.springframework.web.servlet.mvc.method.RequestMappingInfo#pathPatternsCondition` initialised. This is also somewhat reflected in the class javadoc:

```
Request mapping information. A composite for the following conditions:
<ol>
<li>{@link PathPatternsRequestCondition} with parsed {@code PathPatterns} or
{@link PatternsRequestCondition} with String patterns via {@code PathMatcher}
<li>{@link RequestMethodsRequestCondition}
<li>{@link ParamsRequestCondition}
<li>{@link HeadersRequestCondition}
<li>{@link ConsumesRequestCondition}
<li>{@link ProducesRequestCondition}
<li>{@code RequestCondition} (optional, custom request condition)
</ol>
```

So when initialising here

https://github.com/springfox/springfox/blob/ab5868471cdbaf54dac01af12933fe0437cf2b01/springfox-spring-webmvc/src/main/java/springfox/documentation/spring/web/WebMvcRequestHandler.java#L80-L84

both property should be taken into consideration.
