### ISSUE TITLE
Springfox compatibility issue with spring boot 2.6*

### ISSUE THREAD

**Issue by srinivaspeddireddy** [springfox/springfox#3948]
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException

**Comment by srinivaspeddireddy** [comment]
handlerMappings.stream().filter(mapping -> mapping.getPatternParser() == null)
        .collect(Collectors.toList());

**Comment by zeners** [comment]
dublicate of #3462
