### ISSUE TITLE
In 3.0.3 spec example of property not rendered properly

### ISSUE THREAD

**Issue by SButterfly** [springfox/springfox#3956]
Hi,
I have custom config of 3.0.3 spec ([here](https://github.com/SButterfly/springfox-swagger-ui-example-bug/blob/swagger-ui_with_example_bug/boot-swagger/src/main/resources/META-INF/openapi/openapi.json)). And I created example for some of my properties [here](https://github.com/SButterfly/springfox-swagger-ui-example-bug/blob/swagger-ui_with_example_bug/boot-swagger/src/main/resources/META-INF/openapi/openapi.json#L235-L250).

But when I open swagger, I see `null` instead of my custom example.
![Screenshot 2022-01-11 at 11 10 56](https://user-images.githubusercontent.com/4300612/148904797-a8914d79-2328-4089-b8e8-887e0925eae0.png)

I expected to see correct example value.

I'm using springfox-swagger2:3.0.0 and springfox-swagger-ui:3.0.0.
Also using org.openapitools:openapi-generator-cli:5.3.1 for generate config.json out of config.yaml file
I made simple project to reproduce an issue. https://github.com/SButterfly/springfox-swagger-ui-example-bug

**Comment by Nit-1997** [comment]
Hi @SButterfly, I am facing the same issue, Raised  #3973
