### ISSUE TITLE
Jenkins Dependency issue critical

### ISSUE THREAD

**Issue by elizarpongracz** [springfox/springfox#3957]
Hi,

I've added Springfox-Boot-Starter 3.0.0 to my project to have the swagger ui for my API. 

However we are having some issues with it on our Jenkins. While building the projects and checking the library it finds some security issues in your Core library. Is that issue known?

Here is a screen of the report which jenkins provides.

![grafik](https://user-images.githubusercontent.com/36076242/149198948-7480b994-4a73-42b8-98b4-c7aad3384866.png)

**Comment by BHANU2705** [comment]
[Whitesource Issue](https://saas.whitesourcesoftware.com/Wss/WSS.html#!securityVulnerability;id=WS-2020-0407;orgToken=74cbbb27-f32c-474e-bb6b-d99fbffddee4)

Please fix it on priority.
