### ISSUE TITLE
WS-2021-0461 question

### ISSUE THREAD

**Issue by Keinang** [springfox/springfox#3970]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ X] Question. Is this a question about how to do a certain thing? 
We are using springfox version 3.0.0 and I see it is uses swagger-ui version 3.26
We received alert from WhiteSource scan https://www.whitesourcesoftware.com/vulnerability-database/WS-2021-0461 
that we need to upgrade to version swagger-ui - 4.1.3;swagger-ui-dist - 4.1.3.
My question is if springfox has plan to upgrade to this versions of swagger-ui?

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by shalomyasap** [comment]
We also using springfox-swagger-ui-3.0.0, and facing with the same vulnerability
