### ISSUE TITLE
swagger3 doesn't work in springboot 2.6

### ISSUE THREAD

**Issue by WlisonChan** [springfox/springfox#3972]
Our team plans to upgrade the springboot version from 2.3 to 2.6. But we found that once springboot was upgraded to 2.6, swagger could not work.  Does springfox have any plans to update it in the near future? 

same question：
https://github.com/springfox/springfox/issues/3462
https://github.com/springfox/springfox/issues/3963

**Comment by WlisonChan** [comment]
I see some people migrate it to springdoc. What should I do to achieve the purpose of migrating to springdoc without modifying the swagger annotations?

**Comment by MartinX3** [comment]
You use the SpringDoc migration guide and your brain.

**Comment by daixixidai** [comment]
Is SpringDoc  useful?

**Comment by daixixidai** [comment]
> You use the SpringDoc migration guide and your brain.

I find a more powerful tool，Smart-doc,Try for it

**Comment by rowi1de** [comment]
Are you using spring fox 3.x?
This helped me when upgrading to spring 2.6/2.7 http://springfox.github.io/springfox/docs/current/#migrating-from-existing-2-x-version
