### ISSUE TITLE
如何重写swagger的接口

### ISSUE THREAD

**Issue by tech-xs** [springfox/springfox#3987]
- 我使用的是最新的版本最新版本

 - 请问如何重写swagger的接口,我这样写发现并不会被调用,是需要添加什么配置吗?

```java
@RestController
public class TestController {

    @GetMapping("/v3/api-docs")
    public String test(){
        return "{\"openapi\":\"3.0.3\",\"info\":{},\"servers\":[{\"url\":\"http://127.0.0.1:7788\",\"description\":\"SJW Inferred Url\"}],\"components\":{}}";
    }

}

```

**Comment by lzs5091** [comment]
兄弟你知不知道怎么重写@ApiModelProperty这个注解，我项目在启动的时候因为@ApiModelProperty中的example属性默认是“”，最后再Example类中的Example.equals(Example.java:131)就会报出来空指针，不知道你有没有遇到过类似的状况。

**Comment by ltmoxi** [comment]
> 

更新版本就行了现在springfox的swagger版本为<version>1.5.20</version>,更新为1.5.21就可以了

**Comment by ltmoxi** [comment]
> 兄弟你知不知道怎么重写@ApiModelProperty这个注解，我项目在启动的时候因为@ApiModelProperty中的example属性默认是“”，最后再Example类中的Example.equals(Example.java:131)就会报出来空指针，不知道你有没有遇到过类似的状况。
更新版本就行了现在springfox的swagger版本为1.5.20,更新为1.5.21就可以了

**Comment by litian-98** [comment]
> 兄弟你知不知道怎么重写@ApiModelProperty这个注解，我项目在启动的时候因为@ApiModelProperty中的example属性默认是“”，最后再Example类中的Example.equals(Example.java:131)就会报出来空指针，不知道你有没有遇到过类似的状况。

更新版本就行了现在springfox的swagger版本为1.5.20,更新为1.5.21就可以了
