### ISSUE TITLE
base path missing in v2/api-docs 

### ISSUE THREAD

**Issue by kobi171** [springfox/springfox#3992]
- springfox-boot-starter 3.0.0 
- @EnableSwagger2
- application.properties: server.servlet.context-path= /value
base path is missing in v2/api-docs :
![image](https://user-images.githubusercontent.com/22445894/158391617-61a3cd2a-31fe-4296-a02c-a37685b8ac4e.png)
when server.servlet.context-path not appear base path appear with "/"

**Comment by dventurait** [comment]
Hi, we migrated from springfox-swagger2 and springfox-swagger-ui to springfox-boot-starter:3.0.0, but I noticed the basePath which was shown in  springfox-swagger2, is not present in springfox-boot-starter:3.0.0 api definitions (v2 definitions).

Is there any update on this?
