### ISSUE TITLE
is that project still maintained

### ISSUE THREAD

**Issue by hezhangjian** [springfox/springfox#3997]
Hello, guys, I want to know Is that project still maintained? I saw the last updated is on year 2020.

**Comment by gsolecki** [comment]
I think it is completely dead, which is a big shame.
The worst part is that there is no other alternative platform.

**Comment by JanHron** [comment]
@gsolecki Isn't https://springdoc.org/#migrating-from-springfox a suitable replacement?

**Comment by hezhangjian** [comment]
+1, maybe we should port to springdoc project

**Comment by TyinOne** [comment]
but,It's very ugly

**Comment by TyinOne** [comment]
> @gsolecki Isn't https://springdoc.org/#migrating-from-springfox a suitable replacement?

but,It's very ugly
