### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by JohnNiang** [springfox/springfox#4005]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

According to development document: http://springfox.github.io/springfox/docs/current/#development-environment, I was trying to build this project. At last, I got the errors below.

```java
> ./gradlew build
> }
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip
.........10%..........20%..........30%..........40%.........50%..........60%..........70%..........80%.........90%..........100%

Welcome to Gradle 6.5!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildSrc:compileGroovy
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/workspace/.gradle/wrapper/dists/gradle-6.5-bin/6nifqtx7604sqp1q6g8wikw7p/gradle-6.5/lib/groovy-all-1.3-2.5.11.jar) to method java.util.AbstractCollection.hugeCapacity(int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :buildSrc:test
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/workspace/.gradle/wrapper/dists/gradle-6.5-bin/6nifqtx7604sqp1q6g8wikw7p/gradle-6.5/lib/groovy-all-1.3-2.5.11.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

FAILURE: Build failed with an exception.

* What went wrong:
Receiver class org.ajoberstar.grgit.operation.OpenOp does not define or inherit an implementation of the resolved method 'abstract void setProperty(java.lang.String, java.lang.Object)' of interface groovy.lang.GroovyObject.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 35s
```

BTW, I was building the project using JDK 11.

```bash
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
```

It might be caused by Gradle plugin `org.ajoberstar.grgit" version "4.0.2`.

**Comment by jaychoww** [comment]
> Please take the time to search the repository, if your question has already been asked or answered.
> 
> * [x]  What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://camo.githubusercontent.com/cc8b89a71fc6161c41818a0bd359fd803c728c292d250f1dd193c715d88cef20/68747470733a2f2f6170692e62696e747261792e636f6d2f7061636b616765732f737072696e67666f782f6d6176656e2d7265706f2f737072696e67666f782f696d616765732f646f776e6c6f61642e737667) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
> 
> What kind of issue is this?
> 
> * [ ]  Question. Is this a question about how to do a certain thing?
> * [x]  Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or
>   steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
>   
>   * [ ]  spring xml/java config that is relevant
>   * [ ]  springfox specific configuration if it makes sense
>   * [ ]  include any output you've received; logs, json snippets etc.; and what the expected output should be
>   * [ ]  if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494)
> * [ ]  Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
>   already exists! Don’t send pull requests to implement new features without first getting our
>   support. Sometimes we leave features out on purpose to keep the project small.
> 
> According to development document: http://springfox.github.io/springfox/docs/current/#development-environment, I was trying to build this project. At last, I got the errors below.
> 
> ```java
> > ./gradlew build
> > }
> Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
> Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip
> .........10%..........20%..........30%..........40%.........50%..........60%..........70%..........80%.........90%..........100%
> 
> Welcome to Gradle 6.5!
> 
> Here are the highlights of this release:
>  - Experimental file-system watching
>  - Improved version ordering
>  - New samples
> 
> For more details see https://docs.gradle.org/6.5/release-notes.html
> 
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> > Task :buildSrc:compileGroovy
> Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/workspace/.gradle/wrapper/dists/gradle-6.5-bin/6nifqtx7604sqp1q6g8wikw7p/gradle-6.5/lib/groovy-all-1.3-2.5.11.jar) to method java.util.AbstractCollection.hugeCapacity(int)
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 
> > Task :buildSrc:test
> Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/workspace/.gradle/wrapper/dists/gradle-6.5-bin/6nifqtx7604sqp1q6g8wikw7p/gradle-6.5/lib/groovy-all-1.3-2.5.11.jar) to method java.lang.Object.finalize()
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Receiver class org.ajoberstar.grgit.operation.OpenOp does not define or inherit an implementation of the resolved method 'abstract void setProperty(java.lang.String, java.lang.Object)' of interface groovy.lang.GroovyObject.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 35s
> ```
> 
> BTW, I was building the project using JDK 11.
> 
> ```shell
> Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
> openjdk version "11.0.13" 2021-10-19 LTS
> OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
> OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
> ```
> 
> It might be caused by Gradle plugin `org.ajoberstar.grgit" version "4.0.2`.

same issue on Mac M1

**Comment by sash-kp** [comment]
Did anyone get any resolution for this? I am also facing this same issue.

**Comment by AloneMou** [comment]
Remove the following from the build.gradle file
```
  id "org.ajoberstar.grgit" version "5.2.0"
  id "org.ajoberstar.git-publish" version "3.0.0-rc.1"
```
Replace the gradle/documentation.gradle content

```
import springfox.gradlebuild.BuildInfo
import springfox.gradlebuild.utils.ProjectDefinitions




asciidoctor {
  asciidoctorj {
    version = '2.1.0'
  }
  baseDir = file('docs/asciidoc')
  sourceDir = file('docs/asciidoc')
  logDocuments = true
  outputOptions {
    separateOutputDirs = false
    backends = ['html5']
  }
  outputDir = file("${buildDir}/all-docs/docs/snapshot")
  attributes 'source-highlighter': 'coderay',
          'springfox-current-version': project.version.toString(),
          'springfox-released-version': project.rootProject.buildInfo.currentVersion.asText(),
          'springfox-swagger-ui-rfc6570-version': "${rootProject.ext.springfoxRfc6570Version}",
          toc: 'left',
          idprefix: '',
          sectanchors: '',
          idseparator: '-',
          icons: 'font',
          encoding: 'utf-8'
}

task allJavadoc(type: Javadoc) {
  final def publishables = ProjectDefinitions.publishables(project)
  source publishables.collect { it.sourceSets.main.allJava }
  classpath = files(publishables.collect { it.sourceSets.main.compileClasspath })
  destinationDir = file("${buildDir}/all-docs/javadoc/snapshot")
}


task allDocs {
  dependsOn asciidoctor, allJavadoc
  doLast {
    logger.lifecycle "[RELEASE] Asciidoctor attributes: ${asciidoctor.attributes}"
    logger.lifecycle "[RELEASE] Asciidoctor properties: ${asciidoctor.properties}"
  }
}

task publishDocs {
  dependsOn
}

task createReleaseDocs(type: Exec, dependsOn: allDocs) {
  description = "Creates released version of documentation"
  group = "release"

  BuildInfo buildInfo = project.rootProject.buildInfo
  String symlink = 'current'
  String docVersion = buildInfo.currentVersion.asText()

  String releaseCommands = ""
  ["${buildDir}/all-docs/docs/snapshot"    : "${buildDir}/all-docs/docs",
   "${buildDir}/all-docs/javadoc/snapshot": "${buildDir}/all-docs/javadoc"].each { source, destination ->
    String releaseVersionDir = "${destination}/${docVersion}/"
    releaseCommands += """
      cp -r $source $releaseVersionDir
      ln -sf $releaseVersionDir ${destination}/${symlink}
"""
  }

  def commands = """
  $releaseCommands
  """
  
  if (buildInfo.dryRun) {
    logger.warn("Will run the following commands:")
    logger.warn(commands)
    commandLine "sh", "-c", "echo This is a dry run"
    return
  }

  commandLine "sh", "-c", commands
}

task releaseDocs {
  dependsOn createReleaseDocs, publishDocs
}

gitPublishPush.dependsOn allDocs

```
