### ISSUE TITLE
Getting issue while migrating swagger in springfox from 2.9.2 to 3.0.0

### ISSUE THREAD

**Issue by Rinku375** [springfox/springfox#4006]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
I am using 3.0.0 of springfox
What kind of issue is this?
I am getting below issue while migrating.

ApiResourceController is complaining about below.

Parameter 1 of constructor in MyApiResourceController required a bean of type 'java.lang.String' that could not be found.

How to pass the swaggerUiBaseUrl to the MyApiResourceController constructor.

Previously in 2.9.2, ApiResourceController was only requiring SwaggerResourcrProvider. but now it ask for swaggerUiBaseUrl .

How to configure that.

I have followed all config and property changes required for migration but not able to access swagger-ui.

However I can access V2 and V3 api-docs json.

I want swagger-ui with my context like this.

http://localhost:10000/myapp/documentation/swagger-ui/

I have written two controllers one for /documentation mapping (extending Swagger2ControllerMvc). Previously it was extended by swagger2Controller in 2.9.2.

Second one for /documentation/swagger-resources extending ApiResourceController.

Could you please guide me.

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by Rinku375** [comment]
Can anyone suggest any solution

**Comment by lucasoares** [comment]
Hello. Check https://github.com/springfox/springfox/issues/4007#issuecomment-1136598858 for a suggestion.
