### ISSUE TITLE
When will the next version be released?

### ISSUE THREAD

**Issue by childewuque** [springfox/springfox#4007]
When will the next version be released? Do you have any plans?

I hope to use @ApiImplicitParam's allowableValues function instead of @ApiParam, because @ApiParam makes the annotation and interface definition too coupled, but @ApiImplicitParam has a bug in 3.0.0 : https://github.com/springfox/springfox/issues/3390.

Thank you!

**Comment by lucasoares** [comment]
Hello @childewuque 

Apparently springfox is no longer updated. I suggest you to migrate to springdoc instead.

I also suggest you to read this: https://springdoc.org/#differentiation-to-springfox-project

And to migrate your application you can follow this guide: https://springdoc.org/#migrating-from-springfox

The migration is very simple if there is no clients consuming your swagger JSON definition.

Cheers.
