### ISSUE TITLE
[Vulnerability] Springfox springfox-swagger2 /api-docs group Parameter Improper Logging Issue

### ISSUE THREAD

**Issue by Praveen2099** [springfox/springfox#4009]
Springfox contains a flaw in the Swagger2ControllerWebFlux and Swagger2ControllerWebMvc classes in the springfox-swagger2 component. The issue is triggered as input to the 'group' parameter in the /api-docs endpoint is not properly sanitized before being logged. This may allow a remote attacker to use new line characters to inject log entries or HTML code that may be rendered when a user views log data in a browser session.

Vulnerable version====>

<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>3.0.0</version>
</dependency>

Team please fixed vulnerability in this version and provide latest version.

**Comment by kevinjnguyen** [comment]
For more information, this vulnerability is documented here: https://security.snyk.io/vuln/SNYK-JAVA-IOSPRINGFOX-1317096

**Comment by kevinjnguyen** [comment]
Duplicate of: https://github.com/springfox/springfox/issues/3508 

Previous resolution attempts: https://github.com/springfox/springfox/pull/3549 and https://github.com/springfox/springfox/pull/3568 

The maintainers of the code align with Snyk's viewpoint of: 
```
Amendment
This was deemed not a vulnerability.
```
and unfortunately this won't be resolved.
