### ISSUE TITLE
Change swagger-ui.html location without affecting APIs

### ISSUE THREAD

**Issue by jasonfilippou** [springfox/springfox#4012]
I have a bunch of REST APIs accessible under a certain domain, let's call it `mydomain.com`. The REST endpoints themselves are of form `mydomain.com/sys1/api/v1/data`, `mydomain.com/sys2/api/v1/coi/foruser/{user}`, etc. and they **must** stay that way. 

When accessing `mydomain.com`, I am served the Swagger UI page, such that my address bar reads `mydomain.com/swagger-ui.html`. My goal is to have the UI be launched from a custom directory, e.g `customDir`, WITHOUT affecting the API endpoints. So, when I access `mydomain.com`, I want my address bar to read `mydomain.com/customDir/swagger-ui.html`. I need to do this for security reasons related to my organization; we want to control access to our Swagger UI so that it's viewed only by appropriately authorized users, so we intend to protect `customDir` under specific access groups.

For users of Springfox Swagger 3.0.0, like us, the top-voted answer [in this 2020 SO post](https://stackoverflow.com/questions/49924266/how-to-do-friendly-base-url-for-swagger-2-8-0) references [this discussion on this GitHub](https://github.com/springfox/springfox/issues/2250#issuecomment-667454685), where it is suggested that the following is added to the `application.yml`:

```
springfox:
  documentation:
    swaggerUi:
      baseUrl: /customDir
    openApi:
      v3:
        path: /customDir/v3/api-docs
    swagger:
      v2:
        path: /customDir/v2/api-docs
```

Unfortunately, when attempting this fix, I get an "Unable to infer base url" popup that keeps popping up no matter what I type:

![Screen Shot 2022-06-03 at 1 54 02 PM](https://user-images.githubusercontent.com/2993858/171925321-cd605fc3-5a2e-4d94-ad56-8bb4fb7a2234.png)

[This 2017 SO post](https://stackoverflow.com/questions/47425048/why-does-springfox-swagger2-ui-tell-me-unable-to-infer-base-url)'s accepted solution suggests that one moves the `@EnableSwagger2` annotation from the configuration class to the central `@SpringBootApplication` - annotated class, but this has _not_ worked for me; I am _still_ getting that error.

`pom` dependencies of interest:

```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>3.0.0</version>
</dependency>
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>3.0.0</version>
</dependency>
```

And my `application.yml`:

```
spring:
  application:
    name: case-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
management:
  health.jms.enabled: false
  info.env.enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      base-path: /
      exposure.include: info, health, status
server:
  port: 8084

logging:
  file:
    name: ${APP_LOG_PATH:/tmp}/rcm.log
  pattern:
    level: "%5p %8X{user} %36X{acid}" 
```

**Comment by meridbt** [comment]
Hi Jason, Looking through the whole internet (twice), it looks like the only thing which is actually helps - disable authentication on all swagger-ui endpoints and enable built-in auth engine instead

Try this in your (spring-security) config:
```
@Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        http
                .authorizeRequests()
                    .antMatchers(
                            "/swagger-ui/**",
                            "/swagger-ui/index.html",
                            "/v2/api-docs",
                            "/v3/api-docs",
                            "/swagger-resources",
                            "/swagger-resources/**"
                        ).permitAll()
```

Most probably the cause is that swagger-ui can't make a step to auth provider and get a token itself

**Comment by subhanbee** [comment]
Could any one please answer for this question ?
