### ISSUE TITLE
Project is DEAD now?

### ISSUE THREAD

**Issue by mirackle-spb** [springfox/springfox#4017]
Looks like there is no updates for last couple of years.
Much changes in spring makes hard to use springfox.
But springdoc does not have many usable features.

springfox is dead?

**Comment by DickensTone** [comment]
Although there are still some prs,  at least, the community is not inactive.

**Comment by FireRedDev** [comment]
https://github.com/springfox/springfox-javadoc/issues/25

This is definitely dead though and springfox itself is way less useful without this

**Comment by DickensTone** [comment]
@dilipkrish

**Comment by zxuanhong** [comment]
@mirackle-spb you can use spring doc https://github.com/springdoc/springdoc-openapi
