### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tnessn** [springfox/springfox#4027]
![image](https://user-images.githubusercontent.com/5991683/185532834-330db9db-647c-4cbd-974f-8f5f6a1d3c9a.png)
![image](https://user-images.githubusercontent.com/5991683/185532873-7eb178d9-8eba-4c55-a3cd-22112a54c83d.png)

**Comment by OneCricketeer** [comment]
This is not a bug. Disable the JSON extension in your browser to view the raw response. 

JSON needs commas between key-value pairs.

**Comment by tnessn** [comment]
> This is not a bug. Disable the JSON extension in your browser to view the raw response. 
> 
> JSON needs commas between key-value pairs. 

I mean loss of accuracy

**Comment by OneCricketeer** [comment]
Accuracy in what? It's the exact same data. It's your browser that's hiding the commas , not the server response

**Comment by esotericman** [comment]
java long value is bigger than javascripts number,value overflow. you can try to serialized your value to string instead;also it's not bug..

**Comment by huangjinfeng91** [comment]
> java long value is bigger than javascripts number,value overflow. you can try to serialized your value to string instead;also it's not bug..

ok
