### ISSUE TITLE
404 Not Found when calling /v2/api-docs with spring boot 3.0.0

### ISSUE THREAD

**Issue by InigoCrespoSoria** [springfox/springfox#4040]
404 Not Found returned when calling /v2/api-docs?group=My%20Group

Current versions:
-  id 'org.springframework.boot' version '3.0.0'
-   implementation 'io.springfox:springfox-boot-starter:3.0.0'

Is there any workaround? It was working with 2.x.x version

**Comment by guillaume-1** [comment]
Hi, I have the same problem since the migration to springboot 3.0.0

**Comment by guillaume-1** [comment]
Works with this project : https://springdoc.org/v2/  and springboot 3 .

**Comment by NaccOll** [comment]
springfox has not been maintained for a long time, it is recommended to use springdoc.

**Comment by leolimas** [comment]
> Works with this project : https://springdoc.org/v2/ and springboot 3 .

This one do not works with Jersey :(
I'm looking how to upgrade from Swagger 1.5 to 2.x, missing BeanConfig :(
