### ISSUE TITLE
Inappropriate warning "SwaggerSpringMvcPlugin have already been initialized!" 

### ISSUE THREAD

**Issue by stammi** [springfox/springfox#415]
It seems to be default behaviour of SpringMVC to initialize more than one Application-Context an thus send more than one ContextRefreshedEvent.

See figure 16.2 here: 

http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#d4e13071

The WebApplicationContext is initialized first and likely contains all config relevant for swagger.

In our case we have additionally to the root application context a context-servlet.xml which causes an additional ContextRefreshedEvent. This leads to the warning "SwaggerSpringMvcPlugin have already been initialized!" on every server startup.

The warning was introduced by this commit: https://github.com/martypitt/swagger-springmvc/commit/8c2f7c1ac17b152a227826f0a65520c56418b1dd

In our opinion this should either be changed to be a debug message or the new context should be scanned for additional relevant configuration.

**Comment by anshumanpurohit** [comment]
I am getting the same issue with Atmosphere and Swagger.

**Comment by henri-tremblay** [comment]
I'm not sure about where the issue is really coming from. However, some kind of optimisation could be to tell swagger to scan once and leave us alone afterwards. It's quite rare that someone will dynamically add rest services after startup.

Can we just tell swagger to stop reacting after the first refresh or only to scan at startup?

**Comment by dilipkrish** [comment]
@henri-tremblay Per [the documentation](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/event/ContextRefreshedEvent.html)

> Event raised when an ApplicationContext gets initialized or refreshed.

I think whatever the host/container is, decides when to refresh the context. Do anyone of you have a repo with a very basic atmosphere setup that I can play around with? I'm not very familiar with Atmosphere but I'd like to try and understand the nature of the problem.

**Comment by henri-tremblay** [comment]
Why was it closed? It's fixed or we gave no feedback? I'm really sorry that I never came back to you. The issue occurred using JHipster. Version 1, before Atmosphere was removed (it wasn't behaving correctly in spring-boot). I don't know if it still occurs in version 2.

**Comment by dilipkrish** [comment]
Closed it because it's an old issue. Plus were on to 2.0 so if it comes again feel free to reopen the issue

**Comment by henri-tremblay** [comment]
Cool. Let me see
