### ISSUE TITLE
Support subTypes in @ApiModel

### ISSUE THREAD

**Issue by bvulaj** [springfox/springfox#425]
It seems that there is no support of the subTypes property of @ApiModel.  If this isn't true, then maybe the configuration requires more than what is apparent.  Is this scheduled for a later release?

It would be extremely useful when using abstract base entities and the like to have these sub-classes in the documentation.

**Comment by chrisdostert** [comment]
+1 for support of inheritance

**Comment by wxjlibra** [comment]
@fgaule How do you register this customed modelProvider to docket?

**Comment by dilipkrish** [comment]
@wxjlibra The library is a little different than when this feature was requested. So I will probably take more than the suggestions to support subtypes. In general subclassing of messages is weird in services, which is why this feature is prioritized as _Someday_. Open to pull request for sure however.

**Comment by wxjlibra** [comment]
@dilipkrish I'm trying to impl subTypes, I wonder if the spec for swagger2 still support subTypes. which means as long as I pass a sibiling property 'subTypes' to 'properties' property(both within definitions property under root node) the ui(js) end will still able to solve this?

**Comment by dilipkrish** [comment]
Not sure how well inheritance is supported in the swagger specification 2.0 will have to investigate

**Comment by sbuettner** [comment]
Here is an example of for the composition support: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#models-with-composition

**Comment by huiwang** [comment]
It seems that swagger 2.0 supports inheritance. An example is provided here https://github.com/swagger-api/swagger-core/issues/851

I'm willing to help if contribution is needed :)

**Comment by dilipkrish** [comment]
@huiwang definitely looking for contributions on this one. There is [already a PR](https://github.com/springfox/springfox/pull/1152) in here but I think we should re-think the way it was implemented. Reasons being:
1. It depends on the swagger annotations _ONLY_
2. It doesn't account for real runtime behavior defined using jackson annotations
3. It doesn't model our internal models agnostic of the spec

Just to outline what Im thinking, this is what needs to happen
- We need to either add the idea of `super class` to the [`Model`](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/schema/Model.java) or add the notion of `subclasses` to the model depending on the implementation. 
- Add to the [model dependency provider](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/ModelDependencyProvider.java) to seek out model subtypes 
- Add a model ref(s) to the Model to reference the inferred model sub-types/ super-types
- Handle the changes in the mappers to accommodate this.

Let me know if you need any help, Id be happy to answer any questions you might have.

**Comment by AhahaGe** [comment]
@dilipkrish does springfox 2.6.1. or 2.3 support inheritance and subClass, I can't finish it by tying all the examples both in swagger-examples and some idea from google group. Could you help me?

**Comment by raderio** [comment]
Is there any news?

**Comment by francescopeloi** [comment]
> As an aside, having object inheritance hierarchy leak outside of service boundaries is not ideal. To that end unless we're getting a lot of feature requests for it, I'd almost be tempted to not support it :-)

hi @dilipkrish , I found your quote intriguing, do you mind expanding why you think that? I don't have a strong opinion about why that should be and looking for food for thought.

**Comment by dilipkrish** [comment]
@francescopeloi to add to your food for thought more questions which might lead you to a similar conclusion or just the opposite direction :)
- How is the inheritance perceived beyond the line of the service? 
- What if the service was implemented on the jvm (spring mvc/boot) but the client was implemented in go or ruby or javascript?
- Are you leaking your platform semantics accross your serialization boundary? How are you implementing your discriminator? Jacksons default behavior is to add a `@class` attribute.
- What if you add a new class to the hierarchy? How do you communicate that to the client.
- How do you describe to clients what you are expecting. How do you document the fact that you expose an `Animal` request but can take in any subclass of animal.?

**Comment by raderio** [comment]
> How do you describe to clients what you are expecting. How do you document the fact that you expose an Animal request but can take in any subclass of animal.?

https://github.com/Rebilly/ReDoc/blob/master/docs/images/discriminator-demo.gif
From https://github.com/Rebilly/ReDoc

**Comment by dilipkrish** [comment]
Fixed via #1151
