### ISSUE TITLE
Support for swagger 2 example in Schema Object

### ISSUE THREAD

**Issue by tleveque23** [springfox/springfox#458]
It would be very useful to support the Schema Object "example" field (https://github.com/wordnik/swagger-spec/blob/master/versions/2.0.md#schema-object-).

That could be done by adding a parameter to the ApiModelProperty annotation.

**Comment by tshah010** [comment]
Has this been released? I am using 2.0. How does it render in UI? I don't see it. My object definition is like this but it doesn't show anywhere in UI. Please help.

"definitions":{
	"Communication": {
		"description": "Represents user's emails and phone numbers.",
		"externalDocs": {
			"description": "This is a EA defined Resource reused here.",
			"url": "https://xyz"
		},
		"example": {
			"communication": {
				"mobiles": {
					"itemID": "1",
					"nameCode": {
						"codeValue": "personal",
						"shortName": "Personal"
					},
					"formattedNumber": "2015551212"
				},
				"emails": {
					"itemID": "1",
					"nameCode": {
						"codeValue": "personal",
						"shortName": "Personal"
					},
					"emailUri": "jsmitty@gmail.com"
				}
			}
		}
	}
}

**Comment by aleksz** [comment]
same here.
