### ISSUE TITLE
How can I override Model and ModelSchema to appear in snake case instead of simple Java property Names?

### ISSUE THREAD

**Issue by sameer11sep** [springfox/springfox#460]

**Comment by mrkingdom75** [comment]
@dilipkrish I got a problem with CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES, swagger core serialize all its properties too, Ex:
+ "basePath" in Swagger Object --> "base_path" 
+ "operationId" in Operation Object --> "operation_id"
This issue lead to my `swagger UI` could not render the whole documentation Api
`spec-converter.js:362 Uncaught TypeError: Cannot read property '$ref' of undefined`

And also the `error message` from `Swagger UI` make me confusing
thanks

**Comment by dilipkrish** [comment]
@mrkingdom75 that should not be the case. what version of springfox are you using and could you please create a new issue as this ☝️ one is really old

**Comment by mrkingdom75** [comment]
thanks @dilipkrish, I will file a new issue
