### ISSUE TITLE
cannot integrate swagger springmvc using SwaggerSpringMvcPlugin

### ISSUE THREAD

**Issue by magnusmagister** [springfox/springfox#462]
The problem is:
org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mySwaggerConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.List com.mangofactory.swagger.configuration.SpringSwaggerConfig.handlerMappings; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] found for dependency [collection of org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

MySwaggerConfig is the same in sample 'SwaggerSpringMvcPlugin XML Configuration'.
Spring config is:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:context="http://www.springframework.org/schema/context" xmlns:mvc="http://www.springframework.org/schema/mvc" xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd                 http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.1.xsd                 http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.1.xsd">
                
    
    <context:component-scan base-package="com.mycompany.report" use-default-filters="false">
        <context:include-filter expression="org.springframework.stereotype.Controller" type="annotation"/>
    </context:component-scan>
    
    
    <mvc:annotation-driven conversion-service="applicationConversionService"/>
    

    
    <mvc:resources location="/, classpath:/META-INF/web-resources/" mapping="/resources/**"/>

    
    <mvc:default-servlet-handler/>

    
    <mvc:interceptors>
        <bean class="org.springframework.web.servlet.theme.ThemeChangeInterceptor"/>
        <bean class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor" p:paramName="lang"/>
    </mvc:interceptors>

    
    <mvc:view-controller path="/" view-name="index"/>
    <mvc:view-controller path="/uncaughtException"/>
    <mvc:view-controller path="/resourceNotFound"/>
    <mvc:view-controller path="/dataAccessFailure"/>

<bean class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter" />

    

    <bean class="com.mycompany.report.config.MySwaggerConfig" />

    
    <bean class="org.springframework.context.support.ReloadableResourceBundleMessageSource" id="messageSource" p:basenames="WEB-INF/i18n/messages,WEB-INF/i18n/application" p:fallbackToSystemLocale="false"/>

    
    <bean class="org.springframework.web.servlet.i18n.CookieLocaleResolver" id="localeResolver" p:cookieName="locale"/>

    
    <bean class="org.springframework.ui.context.support.ResourceBundleThemeSource" id="themeSource"/>

    
    <bean class="org.springframework.web.servlet.theme.CookieThemeResolver" id="themeResolver" p:cookieName="theme" p:defaultThemeName="standard"/>

    
    <bean class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver" p:defaultErrorView="uncaughtException">
        <property name="exceptionMappings">
            <props>
                <prop key=".DataAccessException">dataAccessFailure</prop>
                <prop key=".NoSuchRequestHandlingMethodException">resourceNotFound</prop>
                <prop key=".TypeMismatchException">resourceNotFound</prop>
                <prop key=".MissingServletRequestParameterException">resourceNotFound</prop>
            </props>
        </property>
    </bean>

    
    <bean class="org.springframework.web.multipart.commons.CommonsMultipartResolver" id="multipartResolver"/>
<bean class="org.springframework.web.servlet.view.UrlBasedViewResolver" id="tilesViewResolver">
    <property name="viewClass" value="org.springframework.web.servlet.view.tiles2.TilesView"/>
  </bean>
    <bean class="org.springframework.web.servlet.view.tiles2.TilesConfigurer" id="tilesConfigurer">
    <property name="definitions">
      <list>
        <value>/WEB-INF/layouts/layouts.xml</value>
        
        <value>/WEB-INF/views/**/views.xml</value>
      </list>
    </property>
  </bean>
<bean class="com.mycompany.report.controller.ApplicationConversionServiceFactoryBean" id="applicationConversionService"/>
</beans>

There are no issues to use by 'quick guide(Spring xml Configuration)' of docs, but when I try to use custom config I got the error. Could you please help me to resolve the problem?

**Comment by ericsodt** [comment]
I seem to be running into similar issues described here, however separating the swagger config from the MVC config doesn't seem to be fixing our problem.

If I comment out the `@Import` statement, then our application runs normally with all services starting up correctly.  However, when it is uncommented I get the following:

> Caused by: java.lang.IllegalStateException: Cannot map handler 'projectController' to URL path [/heartbeat]: There is already handler of type [class ...FormMVCController] mapped.
>...

Below is the configuration files we are using:

Config.java

    @Configuration
    @ComponentScan("my.pkg")
    @EnableMvc
    @PropertySources({
        @PropertySource("/WEB-INF/resources/path/to/file")
    @Import(SwaggerConfig.class)

    public class Config extends WebMvcConfigurerAdapter {

       @Override
       public void configureMessageConverters (List<..> converters) {}

      @Override
       public void addResourceHandlers (ResourceHandlerResistry reg) {
           reg.addResourceHandler("/css/**").addResourceLocations("css/");
           reg.addResourceHandler("/fonts/**").addResourceLocations("fonts/");
           reg.addResourceHandler("/img/**").addResourceLocations("img/");
           reg.addResourceHandler("/js/**").addResourceLocations("js/");
       }
 
      @Override
      public void configureDefaultServletHanding(DefaultServletHandlerConfigurer conf) {
         conf.enable();
      }
   
      @Bean
      public InternalResourceViewResolver getInternalResourceViewResolver() {
         InternalResourceViewResolver resolver = new InternalResourceViewResolver ();
         resolver.setPrefix("/WEB-INF/jsp/");
         resolver.setSuffix(".jsp");
         return resolver;
      }
  
       @Bean
       public static PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer() {
            return new PropertySourcesPlaceholderConfigurer();
       }
    }

WebApp.java

    public class WebApp implements WebApplicationInitializer, ApplicationContextAware {

        private ApplicationContext context;

       @Override
       public void setApplicationContext(ApplicationContext context) {
           this.context = context;
       }
        @Override
       public void onStartup(ServletContext sc) {
           AnnotationConfigWebApplicationContext ctx  = new AnnotationConfigWebApplicationContext();
           ctx.register(Config.class);
           ctx.setServletContext(sc);

           DispatcherServlet ds = new DispatcherServlet(ctx);
           Dynamic servlet = sc.addServlet("dispatcher", ds);
           servlet.addMapping("/services/*");
           servlet.setLoadOnStarup(1);
       }

      @Bean
      //  RestTemplate creation below
    }

SwaggerConfig.java

    @EnableSwagger2
    public class SwaggerConfig {}

Any thoughts on what might be causing this issue?

**Comment by dilipkrish** [comment]
Based on the error 
> Caused by: java.lang.IllegalStateException: Cannot map handler 'projectController' to URL path [/heartbeat]: There is already handler of type [class ...FormMVCController] mapped.

It seems like you have two controllers with request mappings `/heartbeat`.

**Comment by ericsodt** [comment]
@dilipkrish, I agree and when looking through the controller code I see all controllers are extends from Abstract `BaseController` that contains the 'heartbeat' method.  From what I'm seeing Spring allows this and can service responses when calling the 'heartbeat' service.  

For testing, I commented out the method and the stacktrace goes away, however our application still isn't starting properly.  It looks as though I am missing a configuration file that should contain "springfox.documentation.swagger.v2.path:/v2/api-docs".  I followed the instructions [here](https://github.com/springfox/springfox/issues/645) but looks as though I am missing something since I am still getting
>DefaultAnnotationHandlerMapping.registerHandler Mapped URL path [$springfox.documentation.swagger.v2.path:/v2/api-docs}] onto handler 'swagger2Controller'

**Comment by dilipkrish** [comment]
@ericsodt You don't need a config file for that, it has a default value already set. Try removing any `PropertySourcesPlaceholderConfigurer` or `PropertyPlaceholderConfigurer` beans that you may have defined.

**Comment by ericsodt** [comment]
@dilipkrish, Originally, I didn't have the config file and I was still receiving that error.  I just removed the configuration and am still seeing the same message in the logs.

**Comment by dilipkrish** [comment]
Its really hard to know whats going on without seeing all the pieces. Do you have a repo you can share or perhaps create a small application that demonstrates your issue? Also is this a boot app or a vanilla mvc app?

**Comment by ericsodt** [comment]
This is a vanilla MVC app.  Unfortunately, I am unable to share the code at the moment but all the configuration files have been [copied above](https://github.com/springfox/springfox/issues/462#issuecomment-120002191)

**Comment by dilipkrish** [comment]
Couple of things

remove the following line from `WebMvcConfigurerAdapter`

```java
@Bean
   public static PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer() {
        return new PropertySourcesPlaceholderConfigurer();
   }
```

remove the following from `SwaggerConfig`

```java
//@Value("${springfox.documentation.swagger.vs.path}")
   //private String swagger2Endpoint

   //@Value("${springfox.documentation.swagger.v1.path}")
  // private String swagger1Endpoint
}
```

replace your `WebApp` with this

```java
public class WebApp extends AbstractAnnotationConfigDispatcherServletInitializer {
    @Override
    protected Class<?>[] getRootConfigClasses() {
        return null;
    }

    @Override
    protected Class<?>[] getServletConfigClasses() {
        return new Class[]{Config.class};
    }

    @Override
    protected String[] getServletMappings() {
        return new String[]{"/services/*"};
    }
}
```

Its not a dynamic servlet but I suspect you don't need that.

**Comment by dilipkrish** [comment]
Beyond that Im not sure... I'd recommend creating a standalone app with just the simplest case that demonstrates your problem. To get a jumpstart create a fork of the spring-demos project with your changes that don't work. 

Also create a new issue rather than piling on to this one as it may be unrelated and noise for the original issue creators.

**Comment by ericsodt** [comment]
@dilipkrish I'm in the process of getting the project over to you. 

Also, I wanted to update the error we are seeing.  We dug further into the Tomcat logs and found the underlying issue is:

>java.long.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: WebApplicationContext for namespace 'dispatcher-servlet':  startup date [Thu Jul 09 14:44:21 EDT 2015]
...
...

**Comment by mirceade** [comment]
There are two contexts, the default spring context and the spring MVC context. If you're using the @Configuration annotation that gets picked up by the default spring context which has no visibility of the RequestMappingHandlerMapping. That's why it's important that the SwaggerConfig is a bean defined in the MVC context.

**Comment by dilipkrish** [comment]
@mirceade thanks for the explanation! :+1:

**Comment by jasusy** [comment]
Mine work by adding @WebAppConfiguration

**Comment by ankushs92** [comment]
I second it, running springfox 2.6.1 with Spring Boot 1.5.2 and was running into the same error. Just remove the ```java @Configuration ``` and just have ```java @EnableSwagger2@``` and you are good to go
