### ISSUE TITLE
custom annotation reader order

### ISSUE THREAD

**Issue by nguyeda** [springfox/springfox#500]
Hi,

Our REST endpoints are annotated with @RequestMapping similar to:

    @RequestMapping(value = "foo/bar", method = GET, produces = { "application/json", "application/*+json" })

The idea is to be able to specify the version in the Content-Type header with something like **application/foo-v1+json**. The problem is that Swagger only offer the **application/*+json** subtype. To solve this, I've created a custom annotation reader to override the produce/consume values. Basically, it will retrieve for the consumes and produces values in the context, look for the json subtype and replace it with the versioned one.

For this to work, I obviously need to be sure that my custom annotation reader is going to be executed after the default one (in particular the MediaTypeReader). Could you confirm this is indeed the case ?

Thanks

**Comment by dilipkrish** [comment]
@nguyeda ITs a lot simpler to do in the [2.0 work[(https://github.com/springfox/springfox/tree/refactor/538/spike-to-seperate-models-and-dtos) we've been doing. I would wait to implement this.

**Comment by nguyeda** [comment]
It was actually not so complicated, I've added an implementation of RequestMappingReader to the list of customAnnotationReaders in SwaggerSpringMvcPlugin. It's clearly a hack but so far it works.

 Anyway, I'm glad to hear about version 2, I'l definitely update that part when it will become available.

    @Component
    public class FooMediaTypeReader implements RequestMappingReader {
      private static final String VERSIONED_JSON_SUBTYPE = "application/foo-v%s+json";
      private static final String JSON_SUBTYPE = "application/*+json"
    
      @Autowired
      private ApiVersions apiVersions;
    
      private final List<String> jsonTypes = new ArrayList<>();
    
      @PostConstruct
      private void init() {
        // The apiVersions bean returns a list of defined versions, in our case 1, 2, 3, ...
        for (String versionId : apiVersions.getVersionIds()) {
          jsonTypes.add(String.format(VERSIONED_JSON_SUBTYPE, versionId));
        }
      }
    
      @Override
      public void execute(RequestMappingContext context) {
        @SuppressWarnings("unchecked")
        List<String> consumes = new ArrayList<>((Collection<String>) context.get("consumes"));
        @SuppressWarnings("unchecked")
        List<String> produces = new ArrayList<>((Collection<String>) context.get("produces"));
    
        replaceWildcard(consumes);
        replaceWildcard(produces);
    
        context.put("consumes", consumes);
        context.put("produces", produces);
      }
    
      private void replaceWildcard(final List<String> list) {
        // if the consumes/produces list contains the subtype with the wildcard,
        // remove it and add versionned content types
        if (list.remove(JSON_SUBTYPE)) {
          list.addAll(jsonTypes);
        }
      }
    }
