### ISSUE TITLE
MediaTypeReader does not work as expected

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#506]
When certain RequestMappings do not specify a produces/consumes the ApiListing level produces and consumes do not reflect that set of expected produces and consumes correctly

``` java
class SomeController {

    @RequestMapping(value ="/method1", produces={"image/jpeg"})
    public void method1(){...}

    @RequestMapping(value ="/method2")
    public void noProducesOrConsumes(){...}
}
```

should render

``` json
apiVersion: "1.0",
swaggerVersion: "1.2",
basePath: "/context-path",
resourcePath: "/method1",
produces: [
"*/*", //<- Needs this
"image/jpeg"
],
consumes: [
"*/*"
],
apis: [{
    "path": "/method2",
    "produces": [
        "*/*",  //<- Needs this
    ],
    "consumes": [
       "*/*",  //<- Needs this
    ]
}]
```

**Comment by hestad** [comment]
This is not in 1.0.0 :( 

See: https://github.com/springdox/springdox/blob/master/swagger-springmvc/src/main/java/com/mangofactory/swagger/readers/MediaTypeReader.java

Line 60.

Do you know any workaround?
