### ISSUE TITLE
Could it work without RequestMapping annotations?

### ISSUE THREAD

**Issue by ilya-martynov** [springfox/springfox#511]
Hello guys!

Could you please tell me will Swagger Spring MVC work without RequestMapping annotations?
I have Spring project and using Spring MVC Router library for mapping. There are no RequestMapping annotations, but other ones are. Therefore I would like to use the native Swagger annotation instead of RequestMapping.

**Comment by leohsu91** [comment]
i hava the same question. but i don't find anything about this on swagger-core page. - -.

**Comment by dilipkrish** [comment]
@leohsu91 It can but it might be a little work as it's not been flushed out and is just in incubation. What is your usecase may be I might be able to guide you.

**Comment by 8448** [comment]
@dilipkrish @magnusmagister i using Spring MVC Router library for mapping too.

controller
` 
@Controller
public class TestController2 {
    @ResponseBody
    public String custom() {
        return "custom";
    }
    
    @ResponseBody
    public String index() {
        return "index";
    }
    
    @ResponseBody
    public int delete(@PathVariable(value="id") Integer id) {
    	System.out.println(id);
        return 1;
    }
} 

routers.conf：

POST      /test1/custom       testController2.custom
GET       /test1/index		testController2.index
DELETE    /test1/delete/{id}		testController2.delete

How can I solve this problem ? Thanks

**Comment by dilipkrish** [comment]
You probably need to implement [your own plugins](http://springfox.github.io/springfox/docs/current/#plugins) to do that

**Comment by 8448** [comment]
@dilipkrish Thanks for the reply. But i don't know which plugin need me  to implement.In my example,i want to load my handlerMapping
`    <bean id="handlerMapping"
     class="org.resthub.web.springmvc.router.RouterHandlerMapping">
       <property name="routeFiles">
           <list>
           		<value>classpath:routes.conf</value>                     
           </list>
       </property>
    </bean>`

what should i do?

**Comment by dilipkrish** [comment]
Its a little bit involved... You'd have to implement a version of the [RequestHandlerProvider](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/service/RequestHandlerProvider.java). This will have to manually create the `RequestHandler`s based on the `RouterHandlerMapping`.

**Comment by synFireCloud** [comment]
@dilipkrish @8448 I also encountered this problem, now I am in accordance with the @dilipkrish said the implementation of the plugin, but encounter this problem, and I don't know how to use the Router get RouterHandlerMapping, want to help me
`org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [springfox.documentation.spi.service.RequestHandlerProvider] is defined: expected single matching bean but found 2: springRouterRequestHandlerProvider,webMvcRequestHandlerProvider`

**Comment by synFireCloud** [comment]
@8448 I made it,use https://github.com/synFireCloud/springfox-router-plugin

**Comment by 8448** [comment]
@synFireCloud You are so cool.Thanks very much. ^_^

**Comment by dilipkrish** [comment]
👏🏼 @synFireCloud!! 🤘🏻

**Comment by dilipkrish** [comment]
@synFireCloud @8448  Keep in mind the `RequestHandler` Is going to change a little bit in 2.6. It will be breaking change to support #238 ... More details coming soon

**Comment by synFireCloud** [comment]
@dilipkrish I will update it after the 2.6 release

**Comment by gitforpushpak** [comment]
@dilipkrish I am seeing the below error 
`Semantic error at paths./{baseSiteId}/{lang}/{areaCode}/users
`
Using swagger 2, this above mapping is at the controller level not the method. Please suggest.
