### ISSUE TITLE
Is there a way to specify the defaultValue of an ApiModelProperty?

### ISSUE THREAD

**Issue by handavid** [springfox/springfox#525]
Is there a way to specify the defaultValue of an ApiModelProperty? The ```@ApiModelProperty``` annotation does not support defaultValue.

I have a model where the default for an optional value is not the same as the Java default for that type. In this case, I have a boolean that I want to default to ```true```. I would like this default to be reflected property in the documentation, swagger-ui, etc.
```
public class Model {
  @ApiModelProperty(value = "Flag indicating property x ...")
  private final boolean flag;

  @JsonCreator
  Model(Boolean flag) {
    this.flag = Nullables.defaultIfNull(flag, true);
  }
}
```

**Comment by knicholes** [comment]
This would be great for me, too.  When testing an API, the Model Schema tab shows only defaults like empty string, 0, and false.  It'd be great if we could set defaults, especially for things like a string (for use so people won't have to look up an ISO 8601 datetime string each time they want to test creating an entity).

**Comment by murkein** [comment]
Hi, I also began to use swagger and I want to set default values on class attributes . It would be wonderfull...

**Comment by dilipkrish** [comment]
Closing this issue as it should be an issue with [swagger-core](https://github.com/swagger-api/swagger-core). Please re-open once the default value attribute has been added to ```@ApiModelProperty``` annotation
