### ISSUE TITLE
Support java Collection type

### ISSUE THREAD

**Issue by apkobozev** [springfox/springfox#526]
Why swagger.models.Collections doesn't support java.util.Collection interface? 
Could it be implemented? 
At this time, if I have Collection<E> type in ResponseBody, it parsed poorly and has no info about collection element type. 

Thank you.

**Comment by rlogiacco** [comment]
Please consider a `Collection` cannot be a `Map` as the latter doesn't inherit from the former.
This means a `Collection` can be safely mapped to a JSON `array` as much as `List` and `Set` do: any possible representation of `Collection` provides a `toArray` method which returns its array representation.

I belive this should be the default implementation and configuration should be used to override it, rather than the other way around as suggested by previous answer.

**Comment by hestad** [comment]
Added the workaround without effect, so I had to change my implementation to using Set/List instead of Collection. Waiting for a patch.

**Comment by rlogiacco** [comment]
@hestad if you think it might be worth it, you can try my fork

**Comment by dilipkrish** [comment]
@hestad Are you using Collections as a generic or are you using it as a vanilla type. 

in the case that you're using it as a vanilla type, you'd need to use the ```directModelSubstitute``` option.

```java 
// substitutes Collection with List for all instances of collection 
plugin.directModelSubstitute(Collection.class, List.class);
```

In case you're using the generics version you need to create a new rule for that. Some examples [here](https://github.com/springdox/springdox/blob/master/swagger-models/src/main/java/com/mangofactory/swagger/models/configuration/SwaggerModelsConfiguration.java#L26-L34).

Explicitly this is the code you'd need to use
```java
...
AlternateTypeRule collectionRule 
       = newRule(
                    //replace Collection<T>
                    typeResolver.resolve(Collection.class, WildcardType.class), 
                    //with List<T>
                    typeResolver.resolve(List.class, WildcardType.class));
plugin.alternateTypeRules(collectionRule);
....
```

__NOTE:__ you need to use ```WildcardType``` from the package```com.mangofactory.swagger.models.alternates```

Let me know if you have any issues with getting that to work.

**Comment by dilipkrish** [comment]
@rlogiacco let me know if that resolves your issue with collections as well. Swagger the specification, supports sets and lists distinctly, with a ```uniqueItems``` attribute that is set to true or false based on type. And having this library arbitrarily pick one based on your PR is not the right solution.

**Comment by hestad** [comment]
I'm using generics. I tried your last example and that works, thanks a lot. Based on your last message about uniqueItems and the difference in the Swagger specification between a list and a set, I'm actually redesigning my implementation to use Set<>, instead of Collection because that is clearer to my consumers.

**Comment by rlogiacco** [comment]
I've used the `alternateTypeRules` configuration successfully with a `Collection<MyModel>`, but it still doesn't work when used with a `Collection<Resource<MyModel>>` with `Resource` being listed as `genericModelSubstitutes`.

**Comment by akurdyukov** [comment]
Here's s little snippet, hope it helps
```
    @Bean
    public Docket buildApi() {
        TypeResolver typeResolver = new TypeResolver();
        AlternateTypeRule collectionRule
                = AlternateTypeRules.newRule(
                //replace Collection<T> for any T
                typeResolver.resolve(Collection.class, WildcardType.class),
                //with List<T> for any T
                typeResolver.resolve(List.class, WildcardType.class));

        return new Docket(DocumentationType.SWAGGER_2)
                .alternateTypeRules(collectionRule, AlternateTypeRules.newRule(LocalDateTime.class, Date.class))
                .select()
                .paths(regex("/api/.*"))
                .build();
    }
```

**Comment by kevinconaway** [comment]
@akurdyukov what library is `TypeResolver` from?

**Comment by dilipkrish** [comment]
From fasterxml/classmate. The maven/gradle coordinates  are available in the build file.
