### ISSUE TITLE
Excludeannotations not working correctly

### ISSUE THREAD

**Issue by trycatchblock** [springfox/springfox#539]
I am trying to create two groups via SwaggerSpringMvcPlugin. One uses excludeAnnotation, the other one doesn't. However, they both pick it up. Can you confirm this is an existing bug?

Thanks!

**Comment by leofromgroza** [comment]
Hello, I still have problem with this exclude annotations. I have such configuration code 
`new SwaggerSpringMvcPlugin(springSwaggerConfig).excludeAnnotations(MyApiIgnore.class)`
And two methods in Controller
`public String  test1(@MyApiIgnore testParam1) throws Exception { ... }`
`public String  test2(@ApiIgnore testParam2) throws Exception { ... } `
When I'm opening Swagger UI^ 
- For method test1 I can see testParam1;
- For method test2 I cannot see testParam2.

I've expected that in both methods I couldn't see any params.

**Comment by dilipkrish** [comment]
@leofromgroza exclude annotations are only used to mark request mappings as ignored. Not parameters.

**Comment by leofromgroza** [comment]
@dilipkrish Thank you for your answer. 
As I understand I should continue use such code:
` public String test1(@ApiIgnore @MyAnnotation testParam1) throws Exception { ... } `
In my case it would be great if I can create annotation that will exclude parameters. Maybe you can add such improvement, please?
