### ISSUE TITLE
Request Parameters not correctly analyzed

### ISSUE THREAD

**Issue by owahlen** [springfox/springfox#544]
I am using com.mangofactory:swagger-springmvc:0.9.4.
In most of the application's MVC Controllers I have code similar to this:
```
@RequestMapping(method = RequestMethod.GET)
@ApiOperation(value = "Returns all organizations matching the passed criteria")
public List<OrganizationDto> searchOrganizations(@Valid OrganizationSearchCommand command) {
    return organizationService.searchOrganizations(command);
}
```
This means that the constraints of the request parameters are defined in the ```command``` object.
Unfortunately the JSON from calling ```http://localhost:8080/api-docs/default/organization-controller``` incorrectly shows the command as ```paramType``` ```body```. It contains the following code (excerpt):
```
"parameters":[{
    "allowMultiple":false,
    "defaultValue":"",
    "description":"command",
    "name":"body",
    "paramType":"body",
    "type":"OrganizationSearchCommand",
    "required":false
}]
```
Furthermore the OrganizationSearchCommand is not contained in the JSON's model section.

Consequently the OrganizationSearchCommand is just shown as parameter type in swagger-ui but does not contain any information of the included parameters or their constraints.

Note that the code above works if the parameters are past as ```@RequestBody```.

**Comment by adrianbk** [comment]
@owahlen you could use a spring HandlerMethodArgumentResolver and then LoginCommand can be added as a method parameter.

see: http://stackoverflow.com/questions/17200327/spring-requestmapping-parameter-custom-annotation
