### ISSUE TITLE
Dependency on old javax.ws.rs (jsr311-api)

### ISSUE THREAD

**Issue by marting456** [springfox/springfox#549]
Is it possible to upgrade the jsr311-api dependency? It is quite old, from java 1.6. There were lots of additions to the javax.ws.rs in java 1.7 and this causes depenency conflicts when building projects that also require the later version.

So this is a request to make this module more compatible with other modules.

**Comment by dilipkrish** [comment]
@marting456 to my knowledge there is no explicit have any dependency to jsr311. The dependency tree confirms that. Im not really sure why/how its showing up as a dependency as a result of this library. Is it possible that some other dependency is bringing it in? 

@adrianbk any ideas?
