### ISSUE TITLE
Extending for spring-integration

### ISSUE THREAD

**Issue by uttrasey** [springfox/springfox#550]
Hey, the framework looks great. Have there ever been requests or discussion to extend `swagger-springmvc` to work with projects that use 'spring-integration'? 

We define a large number of http-inbound-gateways rather than defining `@Controllers`. It looks like there might be a way to extend your scanner functionality to facilitate this.

Would you entertain a PR for this or would you consider this a separate module project etc?

Thanks

Matt

**Comment by dilipkrish** [comment]
@uttrasey Ofcourse we entertain PRs! We're currently working on exactly that. There is a [WIP](https://github.com/martypitt/swagger-springmvc/issues/538) that is formalizing a plugin infrastructure to do exactly the kinds of things you're looking for. So feel free to review that as well as comment on the issues.

Now in its current incarnation everything is driven off of request handler mappings. My guess is that we'd need to add support for [IntegrationRequestMappingHandlerMapping](http://docs.spring.io/spring-integration/api/org/springframework/integration/http/inbound/IntegrationRequestMappingHandlerMapping.html).
