### ISSUE TITLE
upgrade to 0.9.4 - parameter types are absolute

### ISSUE THREAD

**Issue by cruisemessages** [springfox/springfox#551]
Upgraded from 0.9.3 to 0.9.4

parameters.parameter types are now objects instead of strings. How do i change it back to a string dataType instead of the object. This also causes an issue at line 613 in swagger.js.

Eg Model:
{
    "name": {
      "absoluteType": "string"
    },
    "type": {
      "absoluteType": "string"
    },
    "method": {
      "absoluteType": "string"
    },
    "parameters": {
      "absoluteType": "Set"
    },
    "origin": {
      "absoluteType": "string"
    },
    "other": {
      "absoluteType": "string"
    },
    "author": {
      "absoluteType": "string"
    }

Thank you.

**Comment by dilipkrish** [comment]
@cruisemessages this should be fixed in 1.0.1
