### ISSUE TITLE
How to configure two Swagger groups

### ISSUE THREAD

**Issue by fenkam** [springfox/springfox#558]
The original issue is posted at: http://stackoverflow.com/questions/27843565/how-to-configure-two-swagger-groups
I am trying to configure two groups in my application. The following example I thought would work doesn't. Any suggestion?

@Configuration
@EnableSwagger
public class MySwaggerConfig {
    private SpringSwaggerConfig springSwaggerConfig;

    @Autowired
    public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
      this.springSwaggerConfig = springSwaggerConfig;
    }

    @Bean
    public SwaggerSpringMvcPlugin customImplementation() {
      return new SwaggerSpringMvcPlugin(this.springSwaggerConfig)
            .swaggerGroup("my-group1")).includePatterns("/admin/.*");
    }

    @Bean
    public SwaggerSpringMvcPlugin customImplementation() {
      return new SwaggerSpringMvcPlugin(this.springSwaggerConfig)
        .swaggerGroup("my-group2")).includePatterns("/users/.*");
    }

}

**Comment by dilipkrish** [comment]
When you say it doesn't work ... what do you mean? What does the output look like when you hit the api-docs url? 

What version are you suing? Do you have any configs/ logs etc.? See [these tips on creating an effective issue/question](https://github.com/martypitt/swagger-springmvc/wiki/Issue-Submission)
