### ISSUE TITLE
Add support for @JsonView

### ISSUE THREAD

**Issue by trycatchblock** [springfox/springfox#563]
Hi,

I would like to show different fields in the same model depending on the swagger group. Is there a way I can configure SwaggerSpringMvcPlugin to do this? (maybe through different mixins?)

Thanks!

**Comment by dilipkrish** [comment]
Unfortunately, thats a lot harder to do with the current setup. But hopefully with [the 2.0 version we're working](https://github.com/martypitt/swagger-springmvc/issues/538) on It should be much easier to try and tackle

**Comment by dilipkrish** [comment]
Possibly supporting ```@JsonView``` will solve this issue

**Comment by zvving** [comment]
+1

**Comment by ersinciftci** [comment]
+1

**Comment by Diego-Rocha** [comment]
+1

**Comment by ye3i** [comment]
+1

**Comment by qfrank** [comment]
+1

**Comment by totomaze** [comment]
+1 for jsonView Support

**Comment by jcarnus** [comment]
I just posted this https://github.com/springfox/springfox/pull/2004
Let me know if another changes are needed

**Comment by dilipkrish** [comment]
@jcarnus Thank you!!

**Comment by s20307** [comment]
+1

**Comment by EnterKey** [comment]
+1

**Comment by godekdls** [comment]
+1

**Comment by GregorioPerego** [comment]
+1

**Comment by kellerassel007** [comment]
+1

**Comment by SystemOutPrint** [comment]
ping

**Comment by MaksimOrlov** [comment]
@SystemOutPrint, that feature is being under work.

**Comment by totomaze** [comment]
That's my plug in to show or hide properties with an JsonView annotation :
```import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import com.anzcro.o3.api.Application;
import com.anzcro.ozone.commons.util.View.ApiSecure;
import com.fasterxml.jackson.annotation.JsonView;

import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.schema.ModelPropertyBuilderPlugin;
import springfox.documentation.spi.schema.contexts.ModelPropertyContext;
import springfox.documentation.swagger.common.SwaggerPluginSupport;

@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 1)
public class ModelPropertyPlugin implements ModelPropertyBuilderPlugin {

    @Override
    public void apply(ModelPropertyContext context) {
        boolean showProperty = false;
        boolean containsApplicationName = false;
        if (context.getBeanPropertyDefinition().isPresent()) {
            JsonView jv = null;
            if (context.getBeanPropertyDefinition().get().getField() != null) {
                jv = context.getBeanPropertyDefinition().get().getField().getAnnotation(JsonView.class);
                containsApplicationName = context.getBeanPropertyDefinition().get().getField().getDeclaringClass()
                        .getPackage().getName().contains(Application.class.getPackage().getName());
            } else if (context.getBeanPropertyDefinition().get().getAccessor() != null) {
                jv = context.getBeanPropertyDefinition().get().getAccessor().getAnnotation(JsonView.class);
                containsApplicationName = context.getBeanPropertyDefinition().get().getAccessor().getDeclaringClass()
                        .getPackage().getName().contains(Application.class.getPackage().getName());
            }

            // if no JsonView annotation defined for the endpoint we will only
            // show the model/properties annotated assigned to View.Api.class
            if (jv != null) {
                Class<?>[] listClasses = jv.value();
                for (Class<?> class1 : listClasses) {
                    if (class1.isAssignableFrom(ApiSecure.class)) {
                        showProperty = true;
                    }
                }
            }
        }

        if (!showProperty && !containsApplicationName) {
            context.getBuilder().isHidden(!showProperty);
        }
    }

    @Override
    public boolean supports(DocumentationType delimiter) {
        return SwaggerPluginSupport.pluginDoesApply(delimiter);
    }
}```

**Comment by zodikadem** [comment]
is jsonview still not supported ?

**Comment by MaksimOrlov** [comment]
Branch with **JsonView** support has been merged to master and now available in 2.9.2-snapshot version. I would be grateful for feedback of this functionality.

**Comment by dominik42** [comment]
Support for JsonView doesn't work as expected:

I have 2 controller methods. M1 and M2. M1 is annotated with JsonView, M2 not.
Both methods return the response R. R is an object with two attributes A1 and A2.
A1 is annotated with JsonView, A2 not.

The expected result is the following:  
swagger-ui.html contains both methods. The responses of M1 and M2 differs in their number of attributes.

But current result is:  
swagger-ui.html contains both methods. The responses of M1 and M2 are equals in their number of attributes.

All those results are based on the official demo project [boot-swagger](https://github.com/springfox/springfox-demos/tree/master/boot-swagger). I only edit the versions:  

Spring Boot 1.4.1 => 2.1.6. 
springfox 2.9.2 => 3.0.0.SNAPSHOT (because of your last comment)

**Comment by MaksimOrlov** [comment]
Hi @dominik42. Could you, please, provide full code example with your case?

**Comment by dominik42** [comment]
Hi,
I've created a repository demonstrating the issue 
https://github.com/dominik42/springfox-563-jsonview

**Comment by MaksimOrlov** [comment]
@dominik42 , thanks for the example.

As I can see, there is 2.9.2 version in pom file and configuration for that version. Have you tried to run your example with 3.0.0-SNAPSHOT version ?

**Comment by dominik42** [comment]
yep, same result.

**Comment by MaksimOrlov** [comment]
@dominik42, that is my fault. I missed functionality that looking for `JsonView` annotation in `ReturnTypeOverride` function. This [line](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/operation/ResponseMessagesReader.java#L84) must same as [that](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/operation/OperationResponseClassReader.java#L71).

Will fix it shortly.

Thanks for the report.

For now it produces two models, but link for the second model is incorrect.
![fault](https://user-images.githubusercontent.com/7836239/61237685-ab4b5880-a743-11e9-8a7f-dc18c0db2250.jpg)

**Comment by dominik42** [comment]
fine, give me a hint when you've committed something I should test ....

**Comment by ranjithap7576** [comment]
+1 for @JsonView support

**Comment by dominik42** [comment]
any progress on this issue ?

**Comment by MaksimOrlov** [comment]
@dominik42, bugfix is under progress. The are a few more issues concerning model rendering and I'm working on stabilization. Going to finish to the beginning of September.

**Comment by dilipkrish** [comment]
Thanks @dominik42 for identifying and helping @MaksimOrlov fix the issue!

**Comment by mikhilvikram** [comment]
Hi, Is this issue fixed?

**Comment by xiaoqiangjava** [comment]
springfox2.9.2 is not support JsonView always?

**Comment by kishore-pothireddy** [comment]
Any update on the fix for this issue?

**Comment by MaksimOrlov** [comment]
Here is the PR #3247 to fix this issue.

**Comment by MaksimOrlov** [comment]
PR with fixes has been merged.

And I'll be grateful for your feedback, if the issue was gone. 
Otherwise feel free to reopen the issue.

**Comment by RabidTunes** [comment]
Out of curiosity which version has implemented this? I'm trying 2.9.2 but can't get it to work

**Comment by MaksimOrlov** [comment]
@RabidTunes , `JsonView `is only supported by 3.0.0-SNAPSHOT version. Release is planed on this month.

To use SNAPSHOT version you have to add repository

```
repositories {
maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
}

dependencies {
compile "io.springfox:springfox-swagger2:3.0.0-SNAPSHOT"
}
```

**Comment by Abhi87555** [comment]
I am using @JsonView in my application but models name is appended with JsonView.

@Schema(name ="DemoContext")
public class DemoApiContext{
//code
}

@JsonView(ApiView.class)
@RequestMapping(mathod = {Request.POST}, value={"apiName"}, produces={application/json}, consumes={application/json})
@Operation(summary="Demo Api")
public Response<T> ApiMethod(@RequestBody @JsonView(ApiView.class) ApiRequest request){
//code
}

Now for the above example : 
Expected ModelName : DemoContext
Actual ModelName : DemoContextApiView

Please correct me if I am wrong at any place in the whole explanation above, I am new to this.
