### ISSUE TITLE
Model properties return sometimes empty value in version 0.9.4

### ISSUE THREAD

**Issue by i022098** [springfox/springfox#567]
Hi 
i am using version 0.9.4 and i like it very much. i have encounter a problem regarding the return Model.
i have compiled my code twice without changing the code and got different json results each time:

1:  
"models": {
        "AuditConfigurationBL": {
            "id": "AuditConfigurationBL",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "absoluteType": "boolean",
                    "required": false,
                    "description": null,
                    "allowableValues": null
                }
            },
            "description": ""
        }
2:  
"models": {
        "AuditConfigurationBL": {
            "id": "AuditConfigurationBL",
            "properties": {},
            "description": ""
        }

here is my controller signature :
public ResponseEntity<AuditConfigurationBL> updateAuditConfiguration(@RequestBody AuditConfigurationBL auditConfigurationBL)

and i have also add this annotation:
@ApiOperation(value = "updates the audit configuration and returns current audit configuration", response = AuditConfigurationBL.class)

is this a known issue? please help.

Best Regards
i022098

**Comment by i022098** [comment]
i have found the problem:
i have 2 functions in the controller, 1. put 2. get
the put is serve first and it has @RequestBody so the parameter is added (function readParametersApiModel in class ApiModelReader) later on the get function is called and it has no @RequestBody so the model property in not add, 
later on you you merger all models in class ApiListingScanner  in line 104, so it overwrite the first model. and i get model without properties.
can you please fix it. this is a stopper!!!!

**Comment by dilipkrish** [comment]
@i022098 Thanks for catching that. Would you like to try and issue a PR?

**Comment by dilipkrish** [comment]
I verified this is no longer an issue with 2.0.x. Closing this issue.
