### ISSUE TITLE
the parameter include map object can't execute？

### ISSUE THREAD

**Issue by bluelovecute** [springfox/springfox#571]
when parameter include map object it throw error： The request sent by the client was syntactically incorrect.

**Comment by bluelovecute** [comment]
how can I change the mapProperty：“object”  to mapProperty：{}

**Comment by dilipkrish** [comment]
@bluelovecute a ```Map``` object thats an open generic is the same as object. An object in json is represented as ```{}```. Now that may not be what youre application is looking for. Without much detail in your issue we cant really be of much help. Have you looked at the [help on how to create issues](https://github.com/martypitt/swagger-springmvc/wiki/Issue-Submission)?

**Comment by adrianbk** [comment]
Closing due to lack of response.
