### ISSUE TITLE
Missing Response Messages with repeated code (0.9.5)

### ISSUE THREAD

**Issue by fgaule** [springfox/springfox#587]
Hi folks, 

After you remove scala from the project (great work, btw), I have been experiencing missing response message. I only get one per code (200, 400, 404, etc)

I think the problem lies in using a TreeSet structure for 
```java 
context.get("responseMessages")
```
here com.mangofactory.swagger.readers.operation.SwaggerResponseMessageReader
```java 
  private Set<ResponseMessage> newSet(Set<ResponseMessage> responseMessages, Collection<ResponseMessage> read) {
    TreeSet<ResponseMessage> toSet = new TreeSet<ResponseMessage>(new Comparator<ResponseMessage>() {
      @Override
      public int compare(ResponseMessage first, ResponseMessage second) {
        return first.getCode() - second.getCode();
      }
    });
    toSet.addAll(responseMessages);
    toSet.addAll(read);
    return toSet;
  }
```

In addition, it would be cool to have #equals and #hashcode implemented  in com.mangofactory.swagger.models.dto.ResponseMessage 

Anything you need, just ring my bell

**Comment by dilipkrish** [comment]
@fgaule Have completely revamped the framework in order to support swagger spec v2.0. Currently in the midst of adding 2.0 support. Would be great to get your feedback. Here is the [WIP](https://github.com/martypitt/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos)

**Comment by fgaule** [comment]
@dilipkrish Will check this cool stuff out ;)

**Comment by adrianbk** [comment]
@fgaule do you expect to get more than one response message per http status code?

**Comment by fgaule** [comment]
@adrianbk Yep, in my case i have lot of 400 status codes. When i'm creating a resource i have N validations, each having a concrete error code (i want to put in my api documentation), all mapping to 400. Do you think it is not a valid use case?

**Comment by dilipkrish** [comment]
@fgaule having one response code per different validation will not work any more in 2.x. Having the message describe the various situations is probably a more appropriate solution in any case. Closing this issue for now.

**Comment by ekochnev** [comment]
IMHO: I understand that they probably discontinue multiple responses support for the same http code because of client auto-generation perspective.
But for example now I have already implemented APIs in production and just want to document it and APIs was done this way, returning 400 http code with different sub-codes inside in json response.
So, I would like to vote to live ability and allow just document API operation with different error responses.
