### ISSUE TITLE
swagger2asciidoc converter

### ISSUE THREAD

**Issue by RobWin** [springfox/springfox#590]
Hello, 

i'm currently developing a Swagger to AsciiDoc converter. It takes an swagger.json or swagger.yaml as an input file and generates an AsciiDoc file. The primary goal of this project is to simplify the documentation of RESTful APIs. The result is intended to be an easy-to-read, on- and offline user guide, comparable to GitHub’s API documentation. 

See https://github.com/RobWin/swagger2asciidoc

You can use it together with swagger-springmvc. Thats why I would be interested in your thoughts and improvement suggestions.

Kind regards,

Robert Winkler

**Comment by dilipkrish** [comment]
@RobWin Nice work! :) We're getting ready to start rolling out a snapshot of the swagger spec 2.0 in the following weeks. Its a WIP, but a sneak peak is available [at this branch](https://github.com/martypitt/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos). Its quite a bit of rework, and we're just now getting into implementing the 2.0 spec. Any feedback you might have would be great!

There is definitely some overlap here between where the 2.0 work is going and your project. One thing I'd like to see is possibly have the same test-driven workflow using mockmvc as the [spring rest docs project](https://github.com/wilkinsona/spring-restdocs) by @wilkinsona does.

**Comment by RobWin** [comment]
https://github.com/RobWin/swagger2markup has support for spring-restdocs now.

**Comment by dilipkrish** [comment]
@RobWin wondering if we can create an optional module (with importable configuration) i.e. springfox-swagger-asciidoc to enable a html message converter that can generate the ascii doc in html form? Would you be interested in shepherding that feature.

I'm thinking just like

```curl
GET /api-docs HTTP/1.1
Accept: application/json
``` 

produces the swagger json. Adding a text/html accept header

```curl
GET /api-docs HTTP/1.1
Accept: text/html
``` 

produces ascii doc?

**Comment by RobWin** [comment]
Hi,
you mean as an alternative to swagger-ui?
Could you please elaborate the purpose?

Greetings Robert

**Comment by dilipkrish** [comment]
I think having the ability for springfox to produce a *readonly* documentation format definitely has value. I would even go so far as to be able to produce a pdf when you have an application/pdf as the accept header. Its a communication tool after all. It totally increases the reach of the documentation for even offline scenarios. 

More importantly, I believe not every organization wants to expose an unprotected UI for end users to consume, especially not in production. I would typically see swagger-ui as an admin ONLY capability. This is where I see the main value for  [what you've built](https://github.com/RobWin/swagger2markup). BTW the screenshots look fantastic!

I'm thinking it would be an independent module that library users could pull in optionally, similar to how we pull in the ```springfox-swagger-ui``` module. 

@adrianbk you might want to weigh in on this as well.

**Comment by RobWin** [comment]
Sounds interesting. I would even say that you should be able to mix manual AsciiDoc documentation with   generated API documentation.

**Comment by RobWin** [comment]
Anyway, why did you rename your project?

**Comment by adrianbk** [comment]
@RobWin we are hoping to support formats other than swagger like RAML. We also had a lot of users looking for ways to generate swagger documentation from different types of spring based projects (integration, spring data rest, etc). It felt like the project was becoming more than just swagger integration for spring-mvc.

**Comment by adrianbk** [comment]
@RobWin BTW it would be awesome to have you onboard contributing!

**Comment by adrianbk** [comment]
@dilipkrish I think this would be really good addition and we should flesh it out further with @RobWin.

**Comment by RobWin** [comment]
@adrianbk @dilipkrish Do you have a Gitter chat room?

**Comment by adrianbk** [comment]
Added a Gitter chat room

**Comment by adrianbk** [comment]
@RobWin @dilipkrish lets use this to flesh it out. @RobWin it would be awesome to have you drive this as a community contribution! 

I've added the [springfox-staticdocs](https://github.com/springfox/springfox/tree/master/springfox-staticdocs) module where the code will live.

Here's an initial brain dump:
- User can add an annotation `@EnableStaticDocs` similar to how `@EnableSwagger` works
- This module should have a spring controller which serves the static docs file: 
```
Urls:
/static-docs?format=asciidocs
/static-docs?format=markdown
(request params are more portable than http headers)

The files would not be generated each time they are requested, instead once at startup.
``` 
- A really quick way to integrate would be to use Swagger2MarkupConverter like [this](https://github.com/RobWin/swagger2markup#using-swagger2markup) but it feels wrong to me. I'm thinking the springfox-staticdocs module should not be tied to, or depend on, anything swagger. Instead hook in to springfox using the appropriate [springfox modules and models](https://github.com/springfox/springfox/blob/master/transitioning-to-v2.md) @dilipkrish will need your help here to figure this out!!

- There may end up being a Springfox2MarkupConverter similar to how Swagger2MarkupConverter works. Springfox2MarkupConverter would understand the springfox core models - most likely `springfox.documentation.service.Documentation`.

- Should consider that this module may be extended to work as a Gradle or maven plugin to generate static documents at build time rather than runtime.

**Comment by RobWin** [comment]
@dilipkrish @adrianbk 
I would love to drive the community contribution, but unfortunately I can't commit to a timeframe/milestones, because I currently have to concentrate on my job.

**Comment by dilipkrish** [comment]
@RobWin we both have day jobs we have to concentrate on :) All our dates are driven by our own ability to contribute. This project is strictly driven by our free time. So far we've been kind of lucky that either @adrianbk or I have been able to pick up the slack when the other is busy, but its hard to sustain that without more people getting involved. Over the last couple of years Adrian and I have established a great understanding and its worked out really well.

The reason we'd like to have you drive this module is 
- We really like your work on the swagger2markdown project and think it would be a valuable addition to the product feature set. Who better to drive it that the person who created it!
- Secondly, and more importantly its our effort to grow the project. 98% of the folks who create issues don't ever contribute back in terms of PRs. Its hard to even get them to provide enough information to help them with their *OWN* issues :) So we are always looking to engage passionate people like you.

The main reason we're actually looking forward to having you drive the static-docs module is that we see it as an opportunity for you to  familiarize yourself with the way we work and how we like things; and also for us to get to know how you work, in the hope that you'll continue on as a core contributor. 

If you do decide to take it up, we're always here to answer your questions, brainstorm ideas and even chip in if you think it might be more expedient for us to work on something. Our only expectation is that once the module is done you also support the module at least for some time until its stabilized. We're spread a little thin and the last thing we'd want is for another module to maintain ;-) 

If you'd like we could set up a google hangout or a gitter chat room and chat a bit more about it. :beers:

**Comment by RobWin** [comment]
Do you think you have time to give me an introduction into the code via a video/call session? I would send you an invitation.

**Comment by RobWin** [comment]
@dilipkrish @adrianbk 
I think I would prefer the approach from @dilipkrish. It's more RESTful. :)
I could reuse Swagger2Controller and ServiceModelToSwagger2Mapper and just use Swagger2MarkupConverter as-is. 
If "we" want to support RAML, I would just create a new RAML2MarkupConverter project. 
The standalone converter libraries encourage other people to contribute, because they can use the converters even without using springfox.

What do you think?

**Comment by adrianbk** [comment]
@RobWin what timezone are you in and we can plan a hangout to discuss.

**Comment by RobWin** [comment]
@adrianbk Germany, Frankfurt
UTC/GMT +2:00

**Comment by adrianbk** [comment]
@RobWin it could be difficult to get a time that works for us all.[Here are the zones] (http://www.worldtimebuddy.com/?pl=1&lid=2925533,2158177,4683217&h=2925533).  We will work something out over the next few days. We are busy preparing for a 2.0 release within the next week.

**Comment by RobWin** [comment]
@adrianbk Could you join gitter? do you have time now?

**Comment by adrianbk** [comment]
Merged
