### ISSUE TITLE
Also scan interfaces for allowable values in @ApiParam annotation

### ISSUE THREAD

**Issue by thomasanderegg** [springfox/springfox#596]
If the `@ApiParam` annotation is placed on a method parameter in an interface, the `allowableValues` are not scanned. I found that scanning the parameter name was added with https://github.com/martypitt/swagger-springmvc/commit/18c265be1f0265ac5f08631b1f1a95030c57f5ac (see issue https://github.com/martypitt/swagger-springmvc/issues/388) so I am not sure whether this is a regression or was never implemented. I suspect that in `ParameterAllowableReader#findAnnotatedAnnotatedAllowableValues()`, the implemented interfaces should be scanned in a similar way as in `ParameterAnnotationReader`.

How to reproduce (with swagger-springmvc 0.9.5):
Move the `@ApiParam` annotation from the parameter of a controller method to an interface, e.g. `
```java
public void foo(@ApiParam(allowableValues = "a, b, c") String bar) {...}
```

Edit: is it possible that the `name` attribute is the only working one? The description (`value`) apparently does not work neither, and from a quick look at the code, the `ParameterNameReader` appears to be the only reader that also scans interface annotations.

**Comment by MathieuGilet** [comment]
Still occurs with the 1.0.0 version.

**Comment by dilipkrish** [comment]
I looked at this problem a while back. Walking the stack of interfaces is possibly a performance problem. Might be easier solved using ```ApiParamsImplicit```?

**Comment by thomasanderegg** [comment]
@dilipkrish Which version of swagger-springmvc are you talking about? I don't see that annotation in 0.9.5, is that new? Or did you mean `ApiImplicitParam`? Is there then an easy way so that swagger-springmvc does not pick up the parameter (`bar` in the above example) automatically?

And why is it a performance problem? You traverse the parent interfaces for the  `name` anyway.

**Comment by dilipkrish** [comment]
@thomasanderegg yup THAT ```ApiImplicitParam```! :smile: 

Here is a [googled example](http://stackoverflow.com/questions/13325319/method-parameter-annotations-access). What it would take to read through all the annotations is
1. Check if the method is annotated in the current class
2. For the super class of the given class to see if that method is present and annotated
    2a. Find all the interfaces on each of the super class to see if that method is present and annotated
3. Repeat step 2 till we reach an ```Object``` or null

Once we find the method, its a jagged array of annotations so we have to do some hardcoding of indexes to get to what we want. Now, If you have a deep object hierarchy this can get out of hand. Thats why Im not sure if its worth the trouble.

**Comment by thomasanderegg** [comment]
@dilipkrish I am still not sure why this would be any different from traversing the interfaces for the `name` parameter as it is done in `ParameterAnnotationReader`. Doing the same for the other attributes of the `ApiParam` annotation would be a constant increase in run time. However, I have not checked the 1.0 or 2.0 code base, maybe something changed there which I am not aware of.

Also, step 3 is quite theoretical in my opinion. I don't have any statistics about how other people use the annotations on interfaces of course, but in my case, my controllers implement exactly one interface with swagger annotations so that the implementation classes are not cluttered with swagger annotations.

As for your workaround, I still am not aware of an elegant solution to exclude the automatically generated swagger doc for this single parameter, as I cannot use the ignored parameter types when configuring the `SwaggerSpringMvcPlugin` for String classes of course :)

Nevertheless, if there is too little need to invest time in this issue, I can live with the workaround of having the `ApiParam` annotation in the controller classes themselves, even though it is a bit confusing.

**Comment by dilipkrish** [comment]
This is fixed via https://github.com/springfox/springfox/issues/388
