### ISSUE TITLE
Nickname not used

### ISSUE THREAD

**Issue by jbm4sa** [springfox/springfox#598]
Hi,

It seems that the "nickname" property in the "Api" annotation is never being used, is it so? And can it be added?

I checked the code and it seems to only use the method name for it.

Thanks!

**Comment by dilipkrish** [comment]
@jbm4sa It can be added. I'll see if I can add it in an upcoming release

**Comment by dilipkrish** [comment]
This should be fixed in the 2.0 branch. Closing this issue. Please reopen if it doesnt work after 2.0 is released
