### ISSUE TITLE
Support for xml request bodies?

### ISSUE THREAD

**Issue by cwstenberg** [springfox/springfox#599]
Hi there!

Are rest api:s like below supported by swagger-springmvc and swagger-spring-mvc-ui
The type StateEntry is generated from xsd. I am hoping for swagger to hounour jabx annations and swagger ui to handle xml request bodies.
****
```java
@RequestMapping(
            method = RequestMethod.POST
            ,consumes = "application/vnd.com.acme.foorepository.stateentry.+xml"
            ,produces = MediaType.TEXT_HTML_VALUE
    )
    @ApiOperation(value = "Pushes a state ",
    notes = "Returns reference",
    response = String.class)
    public DeferredResult<String> push_1_0(
            @ApiParam(value="The state to be pushed") 
            final HttpEntity<com.acme.foorepository.StateEntry> request) {
        return ;
    }
```
****

**Comment by dilipkrish** [comment]
@cwstenberg well you could use the [jackson jaxb module](http://wiki.fasterxml.com/JacksonJAXBAnnotations); but the swagger ui is a little more _json_ friendly that you'd want it to be. While it may document the model fairly well based on your jaxb annotations, its not going to generate or help with xml snippets, that you can use the _Try It_ button easily

**Comment by cwstenberg** [comment]
@dilipkrish Thanks for answering.
How do I inject the jackson jaxb module, Is there a example I could look at?

Regards

**Comment by dilipkrish** [comment]
See the link :point_up:

**Comment by cwstenberg** [comment]
@dilipkrish Ok yes I actually followed the instructions described in the link but I must be doing something wrong. I also saw this thread https://github.com/martypitt/swagger-springmvc/issues/482 In some of my jaxb objects generated from xsd there is properties annotated as required which is not reflected by generated jackson json.
How can I check or debug that jackson-module-jaxb-annotations actually is used?

Here is my part of my WebAppConfig
```java
@Bean(name = "customJacksonObjectMapper")
    public ObjectMapper objectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        AnnotationIntrospector introspector = new JaxbAnnotationIntrospector(TypeFactory.defaultInstance());
        // if using BOTH JAXB annotations AND Jackson annotations:
        AnnotationIntrospector secondary = new JacksonAnnotationIntrospector();
        AnnotationIntrospector pair = AnnotationIntrospector.pair(introspector, secondary);
        mapper.setAnnotationIntrospector(introspector);

        return mapper;
    }
```
Here is a component to inject the correct objectmapper into all instances of MappingJackson2HttpMessageConverter 
```Java
@Component
public class CustomJacksonObjectMapperInjectionConfig
{
    private ObjectMapper customObjectMapper;

    private RequestMappingHandlerAdapter requestMappingHandlerAdapter;

    @Resource(name="customJacksonObjectMapper")
    public void setCustomObjectMapper(ObjectMapper customObjectMapper)
    {
        this.customObjectMapper = customObjectMapper;
    }

    @Resource
    public void setRequestMappingHandlerAdapter(
        RequestMappingHandlerAdapter requestMappingHandlerAdapter
    )
    {
        this.requestMappingHandlerAdapter = requestMappingHandlerAdapter;
    }

    @PostConstruct
    public void injectCustomObjectMapperIntoDefaultMappingJacksonHttpMessageConverter()
    {
        List<HttpMessageConverter<?>> converters =
            this.requestMappingHandlerAdapter.getMessageConverters();
        for ( HttpMessageConverter<?> converter : converters )
        {
            if ( converter instanceof MappingJackson2HttpMessageConverter )
            {
                MappingJackson2HttpMessageConverter m =
                    (MappingJackson2HttpMessageConverter)converter;
                m.setObjectMapper(this.customObjectMapper);
            }
        }
    }
}
```

Here is part of my pom.
```Xml
<dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>1.0.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.ajar</groupId>
			<artifactId>swagger-spring-mvc-ui</artifactId>
			<version>0.4</version>
		</dependency>
		
		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-jaxb-annotations</artifactId>
			<version>2.5.1</version>
		</dependency>
```

**Comment by dilipkrish** [comment]
@cwstenberg Have you been able to resolve your problem? I believe things are much simpler with 1.0.1 to override the object mapper

**Comment by cwstenberg** [comment]
Hi! Thanks for following up on this. 
Not successful in getting jaxb annotations like required to be picked by jackson jaxb module and reflected in generated swagger docs. 
So I basically injected xml sample and xml schema into implementation notes of corresponding operation using a custom annotation reader. A little bit ugly, but gives all info needed and not to complicated to change thinking of new versions of this excellent project.

Is 1.0.1 on master now?

**Comment by cwstenberg** [comment]
Ok. So now I am using SpringFox 2.0.0.

I need help on how to register jackson-module-jaxb-annotations to be used by swagger?

**Comment by dilipkrish** [comment]
Just following [this](http://wiki.fasterxml.com/JacksonJAXBAnnotations) should get you all setup.

**Comment by cwstenberg** [comment]
Still no luck getting it to read and reflect jaxb annotations. I am also looking at this issue in swagger-core which may be related ? https://github.com/swagger-api/swagger-core/issues/960#issuecomment-100484695

Tried setting it up by using ApplicationListener<ObjectMapperConfigured> but that breaks springfox documentation controller claiming spring can't find any matching response content.

Is there a test for jaxb 2 annotions in springfox source?

**Comment by dilipkrish** [comment]
It's possibly getting an exception rendering the content. Could u please share more details/ logs. 

There are no tests for jaxb. Mainly because that's completely outside the scope of this library. If Jackson supports something we also support it.

**Comment by cwstenberg** [comment]
Ok. I can't find any code which would actually reflect jaxbannotations to springfox*s modelproperty. This i didn't understand until now.

So i guess the solution would be to provide a implementation for this using ModelPropertyBuilderPlugin

**Comment by tjuchniewicz** [comment]
Any success? To make SpringFox read JAXB annotations? 
I believe I've installed my `ObjectMapper` correctly. SpringFox is probably using it but JAXB annotations are not still used.

My code used to install `ObjectMapper` with JAXB support in SpringFox:
```
 ObjectMapper objectMapper = new ObjectMapper();
 JaxbAnnotationModule module = new JaxbAnnotationModule();
 objectMapper.registerModule(module);
 ObjectMapperConfigured objectMapperConfigured = new ObjectMapperConfigured(appContext, objectMapper);
 appContext.publishEvent(objectMapperConfigured);
```

I also tried to reconfigure Spring global `ObjectMapper`:

```
@Bean
public Jackson2ObjectMapperBuilder objectMapperBuilder() {
   Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
   JaxbAnnotationModule module = new JaxbAnnotationModule();
   builder.modules(module);
   return builder;
}
```

but with no luck.

**Comment by dilipkrish** [comment]
I believe this should work as is. There is a fix we added to the way object mapper is configured in the latest snapshot. I suspect that should fix your problem. Could you try with the snapshot build and report back. Also please create a new issue for this as its a really old issue

**Comment by tjuchniewicz** [comment]
Discussion moved to https://github.com/springfox/springfox/issues/1293.
