### ISSUE TITLE
Range in @ApiParam not working

### ISSUE THREAD

**Issue by ashwinivadivel** [springfox/springfox#600]
Hi,

Following is a piece of code which I cam across for the usage of allowableValues in @ApiParam : @RequestMapping(value = {"/operations/parameters/allowableRange/{id}"}, method = GET, produces = APPLICATION_JSON_VALUE)
   @ResponseBody
   public String allowableRange(
         @ApiParam(defaultValue = "1", allowableValues = "range[1, 99]")
         @PathVariable Integer id) {
      return "";
   }

   @RequestMapping(value = {"/operations/parameters/allowableValues/{id}"}, method = GET, produces = APPLICATION_JSON_VALUE)
   @ResponseBody
   public String allowableValues(
         @ApiParam(defaultValue = "1", allowableValues = "1,2,3,4,5")
         @PathVariable Integer id) {
      return "";
   }

I tried out the same and the part where we provide a range does not work, I am even able to give id as 1000(range is 1-99) and it still works .My swagger version is 0.8.8. Anything that i'm missing?

**Comment by dilipkrish** [comment]
@ashwinivadivel We'll add this to the backlog of features in an upcoming 2.0 branch

**Comment by dilipkrish** [comment]
This is a swagger-ui issue. This works as designed so closing this issue
