### ISSUE TITLE
@JsonView support

### ISSUE THREAD

**Issue by squalloser** [springfox/springfox#601]
Are there any plans to support @JsonView annotation so that you can control the serialization on a per handler method basis?
Here is an example: https://spring.io/blog/2014/12/02/latest-jackson-integration-improvements-in-spring

**Comment by dilipkrish** [comment]
@squalloser We're tracking spring versions one dot version behind. Just so people don't have to be in the bleeding edge to catchup. However the good news is that the upcoming 2.0 version, now has good extensibility points to support what you might be looking for.

**Comment by cemo** [comment]
@dilipkrish ETA for 2.0?

**Comment by batcer** [comment]
I believe, this feature is not supported yet as in 2.2.2.

**Comment by dilipkrish** [comment]
It is not here is an issue for it #807
