### ISSUE TITLE
Need a mockable SpringSwaggerConfig

### ISSUE THREAD

**Issue by kurtymckurt** [springfox/springfox#607]
When writing some tests, someone may want to use the SpringJUnitClassRunner annotations and pass the context configuration like so:

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { WebServiceConfiguration.class })

This however, might be outside the scope where a servletcontext doesn't exist and therefore a SpringSwaggerConfig bean instantiation would fail.  So I thought I could extend the Configuration class (for testing) and override the bean with a mockable SpringSwaggerConfig.  Unfortunately,  SpringSwaggerConfig isn't an interface, nor does the project provide a mocked config.  This would be really helpful for writing these kinds of tests.

**Comment by kurtymckurt** [comment]
As a workaround,  I created a separate Configuration class just for swagger so that it doesn't affect existing code using the other configuration class.

**Comment by dilipkrish** [comment]
@kurtymckurt are you trying to mock/test **this** library or your own services? Simply don't include SpringSwaggerConfig in your WebServiceConfiguration configuration. In general ```@Configurations``` beans are composable units of spring configuration; so Im not sure what you mean by being a interface. Could you elaborate on what you're trying to do?

**Comment by kurtymckurt** [comment]
I'm trying to test my own services and I don't want it to try to autowire the servlet context in this one particular case.

**Comment by dilipkrish** [comment]
Clearly you don't need the swagger inference engine to participate in your test. Why don't you create a test configuration that doesn't pull in SpringSwaggerConfig.
