### ISSUE TITLE
position of @ApiOperation is not recognized

### ISSUE THREAD

**Issue by heapifyman** [springfox/springfox#610]
I specified the `position` parameter in all `@ApiOperation` annotations in my Controller, but the operations are listed in a different order in the generated swagger-ui.

Am I missing something?

**Comment by dilipkrish** [comment]
@heapifyman You can change the ordering by providing your own ordering logic using [apiDescriptionOrdering](https://github.com/martypitt/swagger-springmvc/blob/master/swagger-springmvc/src/main/java/com/mangofactory/swagger/plugin/SwaggerSpringMvcPlugin.java#L354).

**Comment by heapifyman** [comment]
That does not seem to be working. I just tried with the following:
```java
.apiDescriptionOrdering(new Ordering<ApiDescription>() {
    @Override
    public int compare(ApiDescription left, ApiDescription right) {
        return left.getDescription().compareTo(right.getDescription());
    }
});
```

If I am not mistaken that should order the descriptions by method names of the controller?
However, that is not what I am get to see in the browser. What am I missing?

**Comment by yetti4** [comment]
I encounter the same issue. The expected behavior would be that the `@ApiOperation` annotations get sorted in ascending order by `position` attribute. Would be nice to have this fixed in 1.x branch if not too much work.

**Comment by jfiala** [comment]
I'm facing the same with the latest 1.x version 1.0.2.
Additionally, also the @Api - position attribute seems to be ignored, the controllers are always listed in alphabetical order.
This is also not working in version 0.8.8.

**Comment by anishgopalan** [comment]
Is the issue still open? I'm see this in 2.x also.

**Comment by dilipkrish** [comment]
Its not open and the position is deprecated.

**Comment by anishgopalan** [comment]
Okay , thanks for the update.

**Comment by fanjianhang** [comment]
@dilipkrish Hi, if i want to order apis, what should i do?

**Comment by dilipkrish** [comment]
@fanjianhang Currently it is ordered by path

**Comment by fanjianhang** [comment]
@dilipkrish Thanks, i recommend it can order by position or some smart parameter

**Comment by jinyahuan** [comment]
I also encountered the same problem.
And found an extended solution, I hope to help you, and may submit a PR later.
Version 2.7.0 is work.
https://github.com/springfox/springfox/issues/732#issuecomment-524518542
