### ISSUE TITLE
Incorrect type information being generated for models

### ISSUE THREAD

**Issue by chamakits** [springfox/springfox#611]
Hi everyone,

I'm having issues getting 'Date' and other date-like (from joda time) objects to auto generate their type information correctly on the model.

I've been integrating a project with swagger-springmvc, and I was running into some issues with it displaying the correct type information.  I wasn't sure if it was a problem with my project or not.  So I checked out the demo project to replicate it.

I added one 'java.util.Date' field to the 'swagger-springmvc-demo' project:
https://github.com/chamakits/swagger-springmvc-demo/commit/43a0cc20bce7351a087e6c1cb931605ccd61fbfd

If you run with './gradlew :spring3-music:tomcatRun', and open up 'http://localhost:9080/spring3-music/sdoc.jsp' on your browser, you'll see that the field I inserted is being shown as a string, defaulting to an 'empty string', and the other date object already being used also default to a string, even though it is actually returning an array. 

Image of swagger ui here:
![swaggerincorrecttypes](https://cloud.githubusercontent.com/assets/274557/6650715/66e40f6c-c9f7-11e4-8353-6e7a78f4ac99.png)

I would have expected a type like the one shown in the petstore sample given by swagger here:
http://petstore.swagger.io/#!/store/placeOrder
![petstore-correct-model-type](https://cloud.githubusercontent.com/assets/274557/6650727/c8bea9e0-c9f7-11e4-8783-145eca7eb00e.png)

And also for it to have some default value as shown also in petstore sample:
![petstore-correct-good-default](https://cloud.githubusercontent.com/assets/274557/6650733/f8dbdf8a-c9f7-11e4-93c1-5d5dd1ad1cac.png)

So I was wondering, is this a bug with this implementation of swagger?

This might be a separate issue, but is there a way for me to insert my own custom converter to be used by swagger, and swagger only? By that I mean, something I can insert into the 'SwaggerSpringMvcPlugin' like with the customAnnotationReaders? I found the 'alternateTypeProvider', but I didn't understand how to use them, or if they were even what I was looking for.

Anyways, any help would be appreciated, and let me know if theres anything I can do to help.
Cheers!

**Comment by chamakits** [comment]
Hey team, has anybody had a chance to take a look at this?

Any help would be appreciated.

**Comment by dilipkrish** [comment]
@chamakits So the reason releaseDate is rendered as a string is because of [this configuration](https://github.com/chamakits/swagger-springmvc-demo/blob/master/spring3-music/src/main/java/com/ak/spring3/music/SpringConfig.java#L51-L52). The AlternateTypeProvider is a way for you to inject type substitution. So like in the above configuration example, it internally uses the type provider to register a direct model substitute for ```LocalDate``` and substitutes it to be a ```string```. 

There is a gap in what the library can infer and what happens at runtime. One of the gaps that you encountered was that the knowledge of how Joda dates are serializated, by your object mapper. The way to bridge this gap is via one of 4 ways.
- swagger annotations
- ```SwaggerSpringMvcPlugin#directModelSubstitute``` for non-generic types to be substituted
- ```SwaggerSpringMvcPlugin#genericModelSubstitutes``` convenience option for substituting r generic types with 1 type parameter
- Everything else has a custom rule like how we do  [here](https://github.com/springfox/springfox/blob/master/swagger-models/src/main/java/com/mangofactory/swagger/models/configuration/SwaggerModelsConfiguration.java#L26-L34)

Default values arent supported in 1.0.1. 

Now the interesting thing is in your example the ```javaUtilDateField``` should have been rendered as date-time.

**Comment by dilipkrish** [comment]
@chamakits I reckon you're using an older version of swagger-ui. It is actually rendered as 

```json
...
               "taxDate": {
                    "format": "date-time",
                    "required": false,
                    "type": "string"
                }
...
```

**Comment by chamakits** [comment]
@dilipkrish thanks for looking into this, really appreciate it. Sorry for the delayed answer, busy week.

I'll definitely check and rerun this weekend with an updated swagger-ui to verify if thats the case.  But I thought that the model type was drive by the 'type' field, and not the 'format' field.  Is that not the case?

Regardless, the option of using SwaggerSpringMvcPlugin#directModelSubstitute or SwaggerSpringMvcPlugin#genericModelSubstitutes definitely seem like something I'd like to use with some of my custom models.

I had looked at it before, but at the time I didn't really understand how the conversion occurred or how to use it.  Specifically, it confuses me how just sending one class to another would make the conversion occurred.  But my confusion is likely more related to not having used the 'TypeResolver' before.  At the time I tested it, it didn't seem to have the effect desired.

So I'll definitely try this out during the weekend, and I hope you don't mind if I keep adding comments here if I can't really understand how to use those methods.

Thanks for the help!

**Comment by dilipkrish** [comment]
@chamakits :+1: let us know if you see any issues.

**Comment by chamakits** [comment]
Hey @dilipkrish, I took a look at the issue, and I think the problem is that springfox (or at least the demo) generates by default documentation for swagger 1.2, instead of 2.0.

If you see the output of the spring3-music, you'll see
```
{
   "apiVersion":"1.0",
...
   "swaggerVersion":"1.2"
}
```

Versus, if you see the output of the petstore example json:
http://petstore.swagger.io/v2/swagger.json
At the very top you'll see swagger 2
```
{
   "swagger":"2.0",
...
}
```

Not sure if this is an issue on the demo side, or springfox side.
Is this something that's configurable that I can specify to springfox to use swagger 2.0 instead of 1.2.

Let me know any extra information I can provide, or any recommendations you may have.

Thanks in advance!
