### ISSUE TITLE
Update contribution guidlines to facilitate design discussions

### ISSUE THREAD

**Issue by adrianbk** [springfox/springfox#619]
Encourage design discussion/questions prior to contributors working on or submitting PR's. Trying to avoid scenarios where contributors work on and submit a PR which gets declined.

**Comment by dilipkrish** [comment]
:+1:

**Comment by dilipkrish** [comment]
@adrianbk not sure what we want to do about this

**Comment by adrianbk** [comment]
Let's close it. It's covered here: https://github.com/springfox/springfox/blob/master/CONTRIBUTING.md#before-starting-to-work-on-a-pr
