### ISSUE TITLE
What will be best approach for aggregating rest api from various end points?

### ISSUE THREAD

**Issue by xhe** [springfox/springfox#622]
We have several micro services and each one is providing rest api, we now need to have an unique documentation which can display all the apis. We do not want user to jump between different urls in order to see that urls, so I plan to build a swagger server which is aggregating apis and provide that master api-docs to swagger ui.
May I ask what will be the best solution for this purpose?
Also is this project supporting swagger2?

**Comment by dilipkrish** [comment]
I suspect your best answer is to use spring-restdocs and use that as an aggregating too.

**Comment by xhe** [comment]
I realized that the simpliest solution is to feed a json file under
/api-dcos which includes all different endpoints to various micro-services,
and then swaggerUI will auto  retrieve from them seperately. But we have to
make sure no cross domain violation happened
