### ISSUE TITLE
How do you set the SWAGGER_VERSION?

### ISSUE THREAD

**Issue by who** [springfox/springfox#627]
I am working on a project that will conform to the Swagger 2.0 spec.

The Swagger version used by this project is [hardcoded to 1.2](https://github.com/springfox/springfox/blob/3082282471be6f0bd2020d136ffee5d9d73a786b/swagger-springmvc/src/main/java/com/mangofactory/swagger/scanners/ApiListingScanner.java#L43). This causes my output api-doc json file to show `swaggerVersion` as "2.0"

What's the recommended way to override this and set the `swaggerVersion` to 2.0 ?

**Comment by who** [comment]
Closing this. I will just hold off until fully-fledged Swagger 2.0 support is available.

**Comment by dilipkrish** [comment]
:+1: Would love to get some preliminary [feedback on v2](https://github.com/springfox/springfox/tree/refactor/538/spike-to-seperate-models-and-dtos). The *getting started* on the changes is sparse, but I hope to fill that hole in the next couple of days. If you have any questions let us know
