### ISSUE TITLE
[question] How to exclude the basic-error-controller from being added to the swagger description?

### ISSUE THREAD

**Issue by bertrand-quenin** [springfox/springfox#631]
Hi,

The basic-error-controller gets added to the api listing and I would like to get rid of it. I've seen that you're able to specify which package to include, but I just want to exclude the error one.

I didn't find any easy way to do it.

Thanks,
BQ.

**Comment by dilipkrish** [comment]
there isnt a good way to exclude a controller in 1.0.x. You could try giving a regex in your includePatterns when you setup the SwaggerSpringmvcPlugin, tho' that can get out of hand pretty quickly.

**Comment by bertrand-quenin** [comment]
Thanks. Is there any plan to add an "exclude" filter as well ?

**Comment by dilipkrish** [comment]
In 2.0 it's a predicate, so you have a lot more control. Exclude is simply adding a ```Predicates.not(...)```

**Comment by jfiala** [comment]
In 0.8.8/1.0.2 you can easily exclude a controller by using the @ApiIgnore annotation at the class-level.

**Comment by paulofaria** [comment]
I'm having the same problem. Where should I put the .not() call?

**Comment by dilipkrish** [comment]
@paulofaria What version of of the library are you using ? I'd suggest creating a new issue or post your question on the gitter chat with more details

**Comment by jfiala** [comment]
I just tried the following: 

´´´java
@Bean
    public Docket swaggerSpringMvcPlugin() {
      return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).select() 
             .paths(paths())
             .build();
    }

private Predicate<String> paths() {
    	return Predicates.not(PathSelectors.regex("/basic-error-controller.*"));
    }
´´´
However, the Basic-Error-Controller is still listed in the service list.

It seems that it isn't affected by the paths()-method at all, it also doesn't work to show only the basic-error-controller:
´´´java
private Predicate<String> paths() {
    	return PathSelectors.regex("/basic-error-controller.*");
    }
´´´
==> will *not* display the basic-error-controllers, it displays an empty service list.

**Comment by jfiala** [comment]
Right now, the only way to get rid of the basic-error-controller seems to create a @RestController named "BasicErrorController" and put annotate it with  @ApiIgnore. Then it will no longer show up in the service list.

**Comment by dilipkrish** [comment]
That doesn't sound correct... You could also try using the `RequestHandlerSelectors#basePackage` predicates to exclude classes belonging to a certain base package. Or write your own predicates. In any case, would be good to create a failing test and a new issue to if you feel that something is not working as expected.

**Comment by jfiala** [comment]
Thank you, the RequestHandlerSelectors did it:
```java
return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).select() 
 		  .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
             .build();
```
Now the "basic-error-controller" no longer shows up in the service list (in a clean way).

**Comment by shirishp** [comment]
```java
return new Docket(DocumentationType.SWAGGER_2)
            .apiInfo(apiInfo())
            .select()
            .paths(Predicates.not(PathSelectors.regex("/error"))) // Exclude Spring error controllers
            .build();
```
This seems to work for me. The path of these controllers is `/error` not `"/basic-error-controller.*"`

**Comment by AntonRand** [comment]
@eddturner Do you have LogFileMvcEndpoint showing appearing on the UI? It's in the org.springframework package but it doesn't get excluded like the basic-error-controller

I've got round this by using RequestHandlerSelectors.withClassAnnotation(RestController.class)

I can't see why your solution isn't picking this up though?

**Comment by eddturner** [comment]
@AntonRand So sorry for the delay in replying, this slipped by! We used the solution which @jfiala posted and all works great.

**Comment by malkochoglu** [comment]
Hi,
None of the solutions worked for me. I copied and pasted solutions posted by both @jfiala  and @shirishp . Any other work around?
Here is my config class

@Configuration
@EnableSwagger2
public class SwaggerConfig {
    @Bean
    public Docket api() {
    	return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).select() 
    	          .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
    	             .build();
    }
}

And relevant dependencies

	<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.2.RELEASE</version>
		<relativePath>spring-boot-parent</relativePath>
	</parent>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.7.0</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.7.0</version>
		</dependency>

Thank you...

**Comment by dilipkrish** [comment]
@malkochoglu Not sure. If you feel its an issue please create a new issue with a corresponding example or a test that breaks this expectation.

**Comment by dagnelies** [comment]
Here is one more alternative.

Spring boot adds an error handling controller by default to show a "whitelabel error page" instead of the usual tomcat stacktrace error page.

You can disable it by adding `server.error.whitelabel.enabled=false` in your `application.properties`. It'll disable the controller and not show up in swagger either.

**Comment by dilipkrish** [comment]
Thanks @dagnelies!

**Comment by vkarthikesan** [comment]
Use these
`.apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
.apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.cloud")))              .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.data.rest.webmvc")))
`

**Comment by almasry** [comment]
this shitty error of the basic-error-controller  showing in the documentation doesn't seem to be fixable ! 

I followed all the possible solutions in this ticket, yet this seems unsolvable. Nothing works at all.

on top of that the Docket doesn't seem to be picked by swagger, whether it's there or not, the default configuration is loaded and none of the parameters I set has any effect.

**Comment by dilipkrish** [comment]
Most likely you're having multiple/nested application contexts  and the one that you're trying to configure is a named docket i.e. a docket with a group name.

**Comment by CharlesWatsonUK** [comment]
Adding the Spring @Configuration annotation to the class (in which I configure Swagger) worked for me.

**Comment by ali-faizan** [comment]
instead of giving predicates to not include, i gave path to my controller folder like
`.apis.RequestHandlerSelectors.basePackage("com.package.pathto.controllers")`

**Comment by BEllis** [comment]
The below lambda expression should work,

```java
 .apis(r -> !ErrorController.class.isAssignableFrom(r.declaringClass()) && RequestHandlerSelectors.any().apply(r));
```

**Comment by dilipkrish** [comment]
The problem is you're endpoints are consuming the endpoint mappings, you can create a regular expression that resolves it?

`@DeleteMapping(value = "{vaultTitleId:^((?!swagger-ui.html).)*$}")` Seems al lil clunky but not sure what the right answer is.

(See here](https://www.logicbig.com/how-to/code-snippets/jcode-spring-mvc-requestmapping-regex.html) for examples.

**Comment by easmith03** [comment]
This solution of using regex in the definition of the path parameter actually did fix the issue.  So, thank you for the suggestion.  It is not obvious to me why regex resolves the problem.  But, I am glad to discover that it does work.

**Comment by dilipkrish** [comment]
@easmith03 it resolves the problem because it tells spring that this endpoint has a path expression for vaultTitleId that excludes any path with swagger-ui.html in it. for e.g `/vaultTitleId=1` is valid but `/swagger-ui.html`or `/swagger-ui.html?abc=1` will not resolve to this path mapping

**Comment by user370305** [comment]
What I observer, by default Docket configuration takes "RequestHandlerSelectors.any()" as api doc.  Which includes all spring framework default rest controller handlers or models like "ModelAndView" and "View". If you want to include controller doc only from your application code than explicitly providing ".apis(RequestHandlerSelectors.basePackage("com.abc"))" or ".apis(RequestHandlerSelectors.basePackage(<SpringBootApplicationMainClass>.class.getPackage().getName()))" help you to avoid default spring framework controllers and models.

**Comment by naeemsiddiq** [comment]
> Use these
> `.apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot"))) .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.cloud"))) .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.data.rest.webmvc")))`

we can also use simply this
.apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework")))

**Comment by ankushadd123** [comment]
Hi all, 
I have tried all the above mentioned solutions but not work for me . Then I got to know that I was missing a very basic thing i.e.  whether configuration file is accessible to when the application starts. I found that my application was not able to access  the swagger configuration file as it was in  the different package.
So please make sure that your swagger configuration file should be annoted with @configuration annotation and should be in the same package as your main method file so that application can configure it while starting.
Finally I got my solution.
 Please check the below image :
![screenshot from 2019-02-14 18-17-35](https://user-images.githubusercontent.com/25196800/52833782-a9358d00-3104-11e9-9dd4-577ac774482b.png)

**Comment by vyaghini** [comment]
> Thank you, the RequestHandlerSelectors did it:
> 
> ```java
> return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).select() 
>           .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
>              .build();
> ```
> 
> Now the "basic-error-controller" no longer shows up in the service list (in a clean way).

This should be default behavior

**Comment by dagnelies** [comment]
Seeing how common this problem is, it would really make sense to exclude this endpoint *by default and out of the box*.

**Comment by rushabhOrdex** [comment]
private Predicate<String> paths() {
        return PathSelectors.regex("/basic-error-controller.*");
    }

**Comment by zhanghaiyang1** [comment]
> 

![微信图片_20200722151957](https://user-images.githubusercontent.com/12377710/88146789-e32a8d00-cc2e-11ea-8ab3-886322022010.png)


its not worker for me

**Comment by dilipkrish** [comment]
`Predicates.not` Is a guava function. It will not compile. You should just use the `negate` [method instead](https://stackoverflow.com/questions/21488056/how-to-negate-a-method-reference-predicate)

**Comment by zhanghaiyang1** [comment]
sorry,I don't quite understand ,do you have a example?tks

**Comment by dilipkrish** [comment]
Try changing it to `        .apis(RequestHandlerSelectors.basePackage("org.springframework.boot").negate())`

**Comment by zhanghaiyang1** [comment]
tks,but its still out there,i used swagger3(openapi)
![微信图片_20200723084230](https://user-images.githubusercontent.com/12377710/88242694-8a0b3980-ccc0-11ea-9ecb-2e2dc70e68da.png)

**Comment by dilipkrish** [comment]
It works perfectly fine in [the demos](https://github.com/springfox/springfox-demos) application.

See here in this branch

https://github.com/springfox/springfox-demos/blob/1e9eb738e5d6e84f55cc510e877ebc690ff68389/boot-webmvc/src/main/java/io/springfox/demo/bootwebmvc/BootWebmvcApplication.java#L45-L51

If you switch to https://github.com/springfox/springfox-demos/blob/631/showcase and run `./gradlew :boot-webmvc:bootRun` you can see that it is filtered out. Are you sure you're filtering the `lucky` Docket?

**Comment by zhanghaiyang1** [comment]
what is maven command?

**Comment by dilipkrish** [comment]
It's not a maven project. Gradle or maven shouldn't matter. Just run the gradle command 👆 to see the filtered endpoint.

**Comment by zhanghaiyang1** [comment]
like this?
![co](https://user-images.githubusercontent.com/12377710/88249305-b2059780-ccd6-11ea-9202-3a5d26c2d030.png)

**Comment by dilipkrish** [comment]
Sure yes. It should work, if it doesn't 🤷 it's gotta be something in your environment

**Comment by zhanghaiyang1** [comment]
tks very much,i sovled it ,The reason is that the configuration file is in Common, not Zuul



在 2020-07-23 12:33:03，"Dilip Krishnan" <notifications@github.com> 写道：

Sure yes. It should work, if it doesn't 🤷 it's gotta be something in your environment

**Comment by huangzhaomin** [comment]
> tks very much,i sovled it ,The reason is that the configuration file is in Common, not Zuul 在 2020-07-23 12:33:03，"Dilip Krishnan" <notifications@github.com> 写道： Sure yes. It should work, if it doesn't 🤷 it's gotta be something in your environment — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

hallo, may I ask how you solved this problem? I have tried some methods，but they are not work

**Comment by xuhongfei** [comment]
> > tks very much,i sovled it ,The reason is that the configuration file is in Common, not Zuul 在 2020-07-23 12:33:03，"Dilip Krishnan" [notifications@github.com](mailto:notifications@github.com) 写道： Sure yes. It should work, if it doesn't 🤷 it's gotta be something in your environment — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> hallo, may I ask how you solved this problem? I have tried some methods，but they are not work

hi @huangzhaomin  & @zhanghaiyang1 ,
I met the same problem, can you share your solution? Thanks!

**Comment by lucasmello** [comment]
I was able to make it work using the "basePackage" solution. My problem was I wasn't annotating my method with @Bean. I hope it helps.
