### ISSUE TITLE
objectMapper NPE on branch refactor/538/spike-to-seperate-models-and-dtos

### ISSUE THREAD

**Issue by who** [springfox/springfox#635]
I have been working over the [new documentation](https://github.com/springfox/springfox/blob/refactor/538/spike-to-seperate-models-and-dtos/transitioning-to-v2.md) that @dilipkrish has been putting together for the Swagger 2.0 strategy.

However, I seem to hit a roadblock. When I start my app, my configuration class, annotated with `@EnableSwagger2`, kicks in. After my Docket instance is created in this class, `DocumentationPluginsBootstrapper.onApplicationEvent.(ContextRefreshedEvent contextRefreshedEvent)` kicks in to fire off a `scanDocumentation` call.  Eventually, `FieldModelPropertyProvider.beanDescription` is called, but **before** `FieldModelPropertyProvider.onApplicationEvent`, which means `FieldModelPropertyProvider.objectMapper` is still null.  When `FieldModelPropertyProvider.beanDescription` tries to invoke `objectMapper.getSerializationConfig()`, the `NullPointerException` is triggered.

**Comment by dilipkrish** [comment]
@who do you have the repo for me to look at? Im interested in the configuration you have. I suspect you're missing an ```@EnableWebMvc``` in one of your configuration classes.

**Comment by who** [comment]
Unfortunately the codebase I'm working on isn't shareable at the moment.  

However, your suspicion seems to be correct - I had a separate `@Configuration` class that was setting up my `ObjectMapper`, and it did not have the `@EnableWebMvc` annotation. After adding it, the application event is successfully fired with the ObjectMapper config, and I no longer see a `NullPointerException` in `FieldModelPropertyProvider.beanDescription`!  

Are there any guidelines as to which `@Configuration` classes need the `@EnableWebMvc` in order to work with the new Swagger 2.0 strategy of Springfox?

**Comment by dilipkrish** [comment]
@who Its also on my list to document. However, just to help people with the similar issues like you've had, could I ask you to provide a little bit of background, albeit with a contrived example to demonstrate your configuration setup?

Setting up the ObjectMapper has been one of the most contentious issues we've faced in the past. Since this is a different approach, we'd like to document gotchas.

**Comment by dilipkrish** [comment]
@who Closing this as its no longer an issue

**Comment by byshome** [comment]
/**
    * publishEvent ObjectMapperConfigured to OptimizedModelPropertiesProvider
    */
    @PostConstruct
    public void setObjectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        SimpleModule module = new SimpleModule();
        objectMapper.registerModule(module);

        ApplicationContext applicationContext = applicationContextUtil.getApplicationContext();
        ObjectMapperConfigured objectMapperConfigured = new ObjectMapperConfigured(applicationContext, objectMapper);
        applicationContext.publishEvent(objectMapperConfigured);
    }

**Comment by tjuchniewicz** [comment]
Any success? To make SpringFox read JAXB annotations? 
I believe I've installed my `ObjectMapper` correctly. SpringFox is probably using it but JAXB annotations are not still used.

My code used to install `ObjectMapper` with JAXB support in SpringFox:
```
 ObjectMapper objectMapper = new ObjectMapper();
 JaxbAnnotationModule module = new JaxbAnnotationModule();
 objectMapper.registerModule(module);
 ObjectMapperConfigured objectMapperConfigured = new ObjectMapperConfigured(appContext, objectMapper);
 appContext.publishEvent(objectMapperConfigured);
```

I also tried to reconfigure Spring global `ObjectMapper`:

```
@Bean
public Jackson2ObjectMapperBuilder objectMapperBuilder() {
   Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
   JaxbAnnotationModule module = new JaxbAnnotationModule();
   builder.modules(module);
   return builder;
}
```

but with no luck.

**Comment by ezraroi** [comment]
Hi, i have this issue in Spring Boot application using Springfox 2.4

**Comment by dilipkrish** [comment]
@ezraroi please use 2.5.0

**Comment by ezraroi** [comment]
Looks like the swagger ui in version 2.5.0 is not working properly with spring boot... it is not displaying most of my endpoints although the json includes them all

**Comment by ezraroi** [comment]
I am seeing:
Finished Loading Resource Information. Rendering Swagger UI...

forever....
