### ISSUE TITLE
Feature: Add errorprone to the build

### ISSUE THREAD

**Issue by hestad** [springfox/springfox#640]
You should check out http://errorprone.info/

**Comment by dilipkrish** [comment]
@hestad We already have PMD and Findbugs. What does this do additionally?

**Comment by hestad** [comment]
It breaks your build when you have an errorprone-error, but they also operate with warnings. It evaluates the source-code and not the bytecode like PMD/Findbugs. I have used it with maven and it's configured under maven-build-plugin. The gradle version is here: https://github.com/tbroyer/gradle-errorprone-plugin. I see that it only supports Java 7 and 8, while you guys still support 6. But, I also see that you try build with 7/8 and should add it then :)

You can read more about it here: https://www.reddit.com/r/java/comments/30hjui/error_prone_google_library_to_catch_common_java/

**Comment by dilipkrish** [comment]
Closing this unless someone is willing to submit a PR for this
