### ISSUE TITLE
Incorrect url in sdoc.jsp for Swagger 2.0

### ISSUE THREAD

**Issue by Aloren** [springfox/springfox#642]
Library springfox-swagger-ui by default uses sdoc.jsp page from org.ajar:swagger-spring-mvc-ui:0.4.
In this JSP url for swagger json is defined:
url: window.location.origin + "${pageContext.request.contextPath}/api-docs",
But for Swagger 2.0 that is incorrect since default url is: v2/api-docs

**Comment by dilipkrish** [comment]
@Aloren trying using this dependency instead
```gradle
  compile 'io.springfox:springfox-swagger-ui:2.0.0-SNAPSHOT'
```

**Comment by Aloren** [comment]
@dilipkrish , I'm using it already:)

Had to add custom PropertySource with redefining urls like that:
springfox.documentatation.swagger.v2.path=/api-docs
springfox.documentatation.swagger.v1.path=/v1/api-docs

The problem is exactly in JSP definition not in springfox-swagger-ui.

Thanks

**Comment by dilipkrish** [comment]
@Aloren if you add the following it should resolve it

```gradle
  provided 'org.apache.tomcat.embed:tomcat-embed-jasper:8.0.21'
  provided 'javax.servlet:jstl:1.2'
```

**Comment by Aloren** [comment]
@dilipkrish, tomcat-embed-jasper is a must (since i'm using spring-boot), without it I would not get "${pageContext.request.contextPath}/api-docs" processed at all. What jasper makes -- it parses jsp and replaces placeholder ${pageContext.request.contextPath} with real value, something like MySuperServer. So when I open page localhost:PORT/MySuperServer/sdoc.jsp in field with Swagger json url is set value 'localhost:PORT/MySuperServer/api-docs'. But 'api-docs' is a standart endpoint for swagger 1.x. Swagger 2.0 default endpoint is 'v2/api-docs'. As I wrote in previous comment I fixed it, but I wonder if it should be fixed by such hack?

**Comment by dilipkrish** [comment]
Ah! Well it's not a hack. It's an extensibility mechanism you're using :)

In any case, your point is taken that the swagger-ui library ought to be able to intelligently route the property derferencing based on the if v1 or v2 is available. 

Since we don't really own swagger-ui it's a little harder to do generically. You possibly have some ideas? Defly let us know.

**Comment by Aloren** [comment]
@dilipkrish I suppose that could be done on level of annotations like @EnableSwagger and @EnableSwagger2. If developer adds @EnableSwagger2 default uri should be /api-docs. Or it is possible to enable both versions 2.0 and 1.0 at runtime? I don't see any issue with backward comatability. Or am I mistaking?

**Comment by dilipkrish** [comment]
@Aloren you can technically add both ```@EnableSwagger``` and ```@EnableSwagger2``` and it'll serve both descriptions. 

By backwards compatibility I mean if someones already got swagger-ui (may be an older version or swagger or a version not using the springfox library) pointing to ```/api-docs``` expecting v 1.2 then their clients wouldn't break.

**Comment by Aloren** [comment]
@dilipkrish Hmmm. It's bad, that first api version wasn't versioned :)
Will the following solution work?
if only @EnableSwagger is present: /api-docs will point to v1
if @EnableSwagger and @EnableSwagger2 are present: /api-docs will point to v1 (and if developer wants he can change it to point on v2)
if only @EnableSwagger2 is present: /api-docs will point to v2

**Comment by dilipkrish** [comment]
:+1: do I sense a PR coming? :)

**Comment by Aloren** [comment]
@dilipkrish, I hope on weekends I'll have some free time. Tomorrow will investigate some other issues that appeared after migration from 1.x to 2.0. :)

**Comment by adrianbk** [comment]
@dilipkrish @Aloren should we default the swagger 2 url to `swagger.json` as is the trend for swagger 2?

**Comment by eheb** [comment]
@dilipkrish when i deploy jhispter/swagger2 application in tomcat8 with a root web context (by exemple  ods-0.0.1-SNAPSHOT) , swagger api url is http://127.0.0.1:8080/v2/api-docs instead of  http://127.0.0.1:8080/ods-0.0.1-SNAPSHOT/v2/api-docs
what can i do ? best regards
Can't read swagger JSON from  http://127.0.0.1:8080/v2/api-docs

**Comment by dilipkrish** [comment]
I suspect that its a dynamic servlet. You could try and add the following to your docket configuration *([using this api](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L377)) and see if that helps.

```java
    docket.pathMapping("/ods-0.0.1-SNAPSHOT");
```
