### ISSUE TITLE
Missing artifact io.springfox:springfox-core:jar:2.0.0

### ISSUE THREAD

**Issue by navom1** [springfox/springfox#643]
when I place the dependencies in my pom file, eclipse shows an error: Missing artifact io.springfox:springfox-core:jar:2.0.0  for each dependency.

when I build, I get the following Maven error:

 The following artifacts could not be resolved: io.springfox:springfox-core:jar:2.0.0, io.springfox:springfox-spi:jar:2.0.0, io.springfox:springfox-spring-web:jar:2.0.0, io.springfox:springfox-swagger2:jar:2.0.0, io.springfox:springfox-swagger:jar:2.0.0: Could not find artifact io.springfox:springfox-core:jar:2.0.0

**Comment by dilipkrish** [comment]
you need to add the jfrog snapshot repository to your repositories

```xml
<repositories>
    <repository>
      <id>jcenter-snapshots</id>
      <name>jcenter</name>
      <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
    </repository>
</repositories>
```

```xml
<repositories>
    <repository>
      <id>jcenter-snapshots</id>
      <name>jcenter</name>
      <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
    </repository>
</repositories>
```

```gradle
  maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
```

**Comment by who** [comment]
@navom1 Alternatively, you can also install the artifacts to your local maven repository.

Here's how I do it:

```
git clone https://github.com/springfox/springfox.git
cd springfox
./gradlew clean build
./gradlew publishToMavenLocal
```

**Comment by Aloren** [comment]
@who I don't think that is a good idea :) As it won't work on continious integration server, for example :)

**Comment by who** [comment]
@Aloren 

Yes, that is correct, but it works fine if your scope is just experimentation on a dev environment.

**Comment by dilipkrish** [comment]
Closing this as it is no longer an issue

**Comment by KostyaSha** [comment]
jcenter-snapshots for release version?
