### ISSUE TITLE
2.0: ModelAttributeParameterExpander ignores defined ApiModelProperty's

### ISSUE THREAD

**Issue by Aloren** [springfox/springfox#644]
In my controller I have ModelAttribute parameter. 
Like that

---------
```
@RequestMapping(...)
public void handle(@ModelAttribute UserData userData)
```
--------
```
@ApiModel(
    description = "User's data"
)
public class UserData {

@ApiModelProperty(
        value = "User id",
        required = true
    )
private Long userId;
}
```
--------
```
    @Bean
    public Docket customDocket() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo());
    }
```
Issue is that ModelAttributeParameterExpander on expanding parameter executes:
```
parameters.add(pluginsManager.expandParameter(parameterExpansionContext));
```
and pluginManager
```
parameterExpanderPlugins.getPluginsFor(context.getDocumentationType())
```
returns 2 plugins:
SwaggerExpandedParameterBuilder and ExpandedParameterBuilder

SwaggerExpandedParameterBuilder parses ApiModelPropertys correctly, but after that ExpandedParameterBuilder is called and rewrites parameters definition. So userId parameter is not actually set as required parameter.

I'm using springfox version 2.0.0-SNAPSHOT

**Comment by dilipkrish** [comment]
@Aloren thanks for reporting! Its an ordering issue, i'll take a look

**Comment by dilipkrish** [comment]
@Aloren this should be fixed with appropriate priorities for the swagger plugins. Feel free to re-open if its not working still
