### ISSUE TITLE
Use fest assert library for assertions

### ISSUE THREAD

**Issue by Aloren** [springfox/springfox#646]
I would recommend using the following library ( https://github.com/alexruiz/fest-assert-2.x ) in tests, that provides clear assertion API.

**Comment by dilipkrish** [comment]
@Aloren Are you talking about replacing spock and its built in assertions? Seems like that might be quite an undertaking considering the volume of tests we have.

**Comment by Aloren** [comment]
@dilipkrish Spock assertions are great. But in case of java test cases fest assertions is a great library to use.

**Comment by adrianbk** [comment]
@Aloren all of our tests are written in spock and we have no intention of changing back to junit. spock and  groovy allow us to write less test code without the noise of matchers or asertions as are required in java/junit.
