### ISSUE TITLE
2.0: Parameter required field not set

### ISSUE THREAD

**Issue by Aloren** [springfox/springfox#648]
Springfox 2.0.0-SNAPSHOT
If you have method:
```
@RequestMapping(...)
public void foo(@ApiParam("Activation code") @RequestParam("code") String code) {
...
}
```
Parameter 'code' will have field 'required' set to false, but should be true (since required=true is set via @RequestParam annotation, description is added via @ApiParam annotation).

I was investigating and found that there are 2 ParameterRequiredReaders (one that reads spring's annotations, seconds one that reads swagger's annotations).Problem is that spring's reader sets required to true, after that swagger's reader sets required to false.

This behavior worked with 1.x version.

**Comment by Aloren** [comment]
In version 1.0.2 there was one ParameterReuiredReader and it looked through all annotations of a parameter like that:
```
if (annotation instanceof ApiParam) {
          requiredSet.add(((ApiParam) annotation).required());
        } else if (annotation instanceof RequestParam) {
          requiredSet.add(!optional && ((RequestParam) annotation).required());
        } else if (annotation instanceof RequestHeader) {
          requiredSet.add(!optional && ((RequestHeader) annotation).required());
        } else if (annotation instanceof PathVariable) {
          requiredSet.add(true);
        }
```

**Comment by adrianbk** [comment]
@Aloren would you like to take on a fix and pull request for this?

**Comment by Aloren** [comment]
@adrianbk, for not I don't know how it should be fixed properly. I don't like the previous implementation, although it works. Current implementation is ok, spring and swagger annotations are separated, but the flow is incorrect. Changing the order of readers will fix the issue, but I don't think that is a good idea to rely on ordering. 
Maybe one of the annotations should have more priority? 
Or if any of the annotations sets value to true, the other one should not reset it?

I suppose, that there will be other issue regarding such separation..

**Comment by dilipkrish** [comment]
@Aloren Not sure how you're getting the order mixed up. The swagger reader [should run](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/parameter/ParameterRequiredReader.java#L38) *after* the spring reader. Wonder what might be causing the plugins to load in a different order. Any clues would be helpful.
