### ISSUE TITLE
2.0: Support for ControllerAdvice

### ISSUE THREAD

**Issue by Aloren** [springfox/springfox#649]
Typically ControllerAdvice is used as a place for defining exceptionHandlers, initbinders and modelattributes for all controllers. It would be great if springfox supported parsing of ControllerAdvice.

**Comment by dilipkrish** [comment]
@Aloren there are extensibility mechanisms that should let library users build plugins that match their services and environments. I don't think this is a core library feature.

**Comment by Aloren** [comment]
@dilipkrish, I looked through issues and found issue regarding ExceptionHandler support, so I thought that ControllerAdvice would be a great plus.

**Comment by dilipkrish** [comment]
@Aloren thats a little more of an interesting feature support (the ExceptionHandler). IMO, Controller advice un-related to restful descriptions are better left for someone to extend.

**Comment by dilipkrish** [comment]
Closing this as its open for extension

**Comment by dilipkrish** [comment]
Exception handler relates to #521
