### ISSUE TITLE
ApiModelProperty dataType is ignored

### ISSUE THREAD

**Issue by Aloren** [springfox/springfox#650]
Version: 1.0.2
Is it correct behavior that BaseModelProperty ignores dataType set to @ApiModelProperty annotation?
For the following code:
```
@ApiModel
public class SomeInfo {

    @ApiModelProperty(required = false, dataType = "java.lang.String")
    public final Optional<String> code;
```
I expect to get swagger json with dataType `string`, but I still get `optional<String>`

Model schema is rendered like that:
```
{
  "code": {
    "present": false
  }
}
```

**Comment by dilipkrish** [comment]
@Aloren unfortunately that is a true statement. Pre-2.0 we don't support overriding model properties. For that particular use-case however you could use ```genericModelSubstitute``` for ```Optional```. I'd use that solution for 2.x as well.

**Comment by Aloren** [comment]
@dilipkrish Thank you! That works like magic :)
