### ISSUE TITLE
README.md 1.0.2 needs update to com.mangofactory.swagger.configuration.SpringSwaggerConfig

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#657]
https://github.com/springfox/springfox/tree/pre-2.0/README.md

The class springfox.documentation.swagger.configuration.SpringSwaggerConfig has not yet been refactored to springfox.* in 1.0.2.
There the correct classname in 1.0.2 and before is: com.mangofactory.swagger.configuration.SpringSwaggerConfig

Paragraph:
Spring xml Configuration

    To get the default implementation simply define a bean of type: springfox.documentation.swagger.configuration.SpringSwaggerConfig
CORRECT: com.mangofactory.swagger.configuration.SpringSwaggerConfig

<mvc:annotation-driven/> 
<bean class="springfox.documentation.swagger.configuration.SpringSwaggerConfig" />
CORRECT: 
<bean class="com.mangofactory.swagger.configuration.SpringSwaggerConfig" />

SwaggerSpringMvcPlugin Spring Java Configuration
@EnableWebMvc
is not really necessary and could be omitted.
With no @EnableWebMvc tag, static content is immediately accessible and no mvc:resources config is necessary.

Best regards,
J. Fiala

**Comment by dilipkrish** [comment]
@jfiala the joy of find an replace! :-)

**Comment by dilipkrish** [comment]
This should be fixed now
