### ISSUE TITLE
Hot reloading of Spring Swagger API-docs during development (hints + question)

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#658]
A hint for anybody wanting to use hot reload capabilities during API development to refresh the API-docs:

To enable hot reload of the apidocs during development I did:
1.) Activate Spring-Loaded 1.2.0 or higher
java -javaagent:<pathTo>/springloaded-{VERSION}.jar -noverify
(https://github.com/spring-projects/spring-loaded)
This makes it possible to add new methods/fields/etc. during development and access it immediately using the Request Path.
However, the mappings updated in AbstractHandlerMethodMapping.registerHandlerMethod do not get propagated to SpringSwaggerConfig.handlerMappings, so they won't show up in the /api-docs

2.) To allow API-changes in existing controller classes to show up, I did the following:

a) add a Controller class to allow refresh:

``` java
....
@RestController
@ApiIgnore
public class SpringSwaggerController {

	@Autowired
	private ApplicationContext applicationContext;

	@Autowired
	private SpringSwaggerConfig springSwaggerConfig;

	@RequestMapping(method = RequestMethod.GET, value = "/refresh")
	@ResponseBody
	public String refresh() {
		SwaggerReloadUtil.reload(applicationContext, springSwaggerConfig);
		return "Swagger config refreshed";
	}
}
```

SwaggerReloadUtil (has to be in the same package com.mangofactory.swagger.plugin because initialize() is protected:

``` java
package com.mangofactory.swagger.plugin;
...
public class SwaggerReloadUtil {

	public static Map<String, SwaggerSpringMvcPlugin> reload(
			ApplicationContext applicationContext,
			SpringSwaggerConfig springSwaggerConfig) {
		new SwaggerSpringMvcPlugin(springSwaggerConfig).build().initialize();

		Map<String, SwaggerSpringMvcPlugin> plugins = BeanFactoryUtils
				.beansOfTypeIncludingAncestors(applicationContext,
						SwaggerSpringMvcPlugin.class);
		
		return plugins;
	}
}
``` 
Then by calling http://localhost:8080/refresh the Swagger configuration get's rebuilt and API changes will show up.

This is however, valid only for all changes at the operation level (@ApiOperation, @ApiResponses).
Changes in a Controller class (@Api) or adding new Controllers won't show up.

3.) To allow new controller classes to be picked up by Spring, you can use JHipster Core:
http://tux2323.blogspot.co.at/2014/06/hot-reload-support-with-spring-loaded.html

This allows you to use new Controllers immediately and test them using the Tomcat container.

However, here the new controllers don't get picked up by ApiListingReferenceScanner because the SpringSwaggerConfig.handlerMappings are not refreshed. So these new controllers currently don't show up in the Swagger API-docs listing.
Only a complete restart seems to re-read the SpringSwaggerConfig.handlerMappings.

Question: can you at least make the SpringSwaggerConfig.handlerMappings accessible, so they can be re-injected from outside?

**Comment by adrianbk** [comment]
@jfiala great post! Spring loaded and hot reloading are things we haven't considered and need to.

**Comment by dilipkrish** [comment]
:+1: spring-loaded has been on my radar for a while too. However it seems a bit niche and geared towards spring-boot. 

@jfiala In 2.0.x everything is auto wired, so would you mind trying it out in the current snapshot? Would love to get PR to support this is a way that doesn't impose on non-spring-boot applications.

**Comment by jfiala** [comment]
spring-loaded itself works with any JEE project and is not spring-specific at all.
In fact, it doesn't support refreshing of Spring beans itself, you have to use Jhipster-core for this (which is actually funny anyway).

Yes, I'll have a look at this!

**Comment by jfiala** [comment]
I just tested using 2.0.0-SNAPSHOT.

Unfortunately the hot reloading of the RequestMappingHandlerMappings are still not picked up by the Swagger-Spring-Integration classes.

However, they are accessible using REST directly.

My former solution to re-create the SwaggerSpringMvcPlugin of 1.0.2 seems now no longer available.

```java
new SwaggerSpringMvcPlugin(springSwaggerConfig).build().initialize();

		Map<String, SwaggerSpringMvcPlugin> plugins = BeanFactoryUtils
				.beansOfTypeIncludingAncestors(applicationContext,
						SwaggerSpringMvcPlugin.class);
```
What is the equivalent of this in 2.0.0?

**Comment by dilipkrish** [comment]
Its ```Docket```; should be in the transition document!!

**Comment by jfiala** [comment]
ok, I'll try to re-create Docket.

**Comment by jfiala** [comment]
I'm sorry, but Docket doesn't contain any RequestMappingHandlerMapping references.

I tracked down:
ApiListingReferenceScanner (contains RequestMappingHandlerMapping references) => ApiDocumentationScanner => ApiDocumentationScanner => DocumentationPluginsBootstrapper.scanDocumentation => DocumentationPluginsBootstrapper.onApplicationEvent

However, I cannot refresh the ApplicationContext as this will shutdown the Application server without it starting again.

So probably the most promising step seems to re-create the private final DocumentationCache scanned;
However, currently this doesn't seem intendend, I'd have to patch it.

**Comment by qfrank** [comment]
So..reloading still not working in version 2.5.0?

**Comment by divStar** [comment]
I am sorry to necro this issue, but is there a way to say refresh the swagger configuration using springfox upon changing restcontroller without the need of restarting the whole application?
