### ISSUE TITLE
swagger-2.0.0-SNAPSHOT: Swagger 1.2 - /api-docs produces 404 Not Found (empty page)

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#660]
swagger-2.0.0-SNAPSHOT

1. http://localhost:8080/api-docs/
produces 404 not found (empty page)

2. However, concrete API-Docs URLs for Services 
produces correct Swagger 1.2 API docs
e.g. http://localhost:8080/api-docs/business-api/search-services

The configuration:
* @EnableSwagger
* DocumentationType.SWAGGER_12

``` java
@SpringBootApplication
@EnableSwagger
public class Application {
	
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }  

    
    @Bean
    public Docket swaggerSpringMvcPlugin() {
      return new Docket(DocumentationType.SWAGGER_12)
              .groupName("business-api")
              .select() 
                 //Ignores controllers annotated with @CustomIgnore
                //.apis(not(withClassAnnotation(CustomIgnore.class)) //Selection by RequestHandler
                //.paths(paths()) // and by paths
                .build()
              .apiInfo(apiInfo());
              //.securitySchemes(securitySchemes())
              //.securityContext(securityContext());
    }
    

    private ApiInfo apiInfo() {
	      ApiInfo apiInfo = new ApiInfo(
	              "My Apps API Title", "My Apps API Description", "1.0",
	              "My Apps API terms of service", "My Apps API Contact Email",
	              "My Apps API Licence Type", "My Apps API License URL"
	        );
	      return apiInfo;
	    }

    //Here is an example where we select any api that matches one of these paths
    /*private Predicate<String> paths() {
      return or(
          regex("/business.*"),
          regex("/some.*"),
          regex("/contacts.*"),
          regex("/pet.*"),
          regex("/springsRestController.*"),
          regex("/test.*"));
    }*/
    
    
}
```

Additional question: which static package is regex() contained in?
(Predicate probably com.google.common.base.Predicate?)

**Comment by dilipkrish** [comment]
@jfiala its in the [transition documentation](https://github.com/springfox/springfox/blob/master/transitioning-to-v2.md)

> For a list of handy predicates Look at RequestHandlerSelectors and PathSelectors.

You'd need to statically import those classes of course.

**Comment by dilipkrish** [comment]
Also take a look at [springfox-demos](https://github.com/springfox/springfox-demos)

**Comment by jfiala** [comment]
guava-18.0.jar - com.google.common.base.Predicates only contains "or", not "regex".

Thank you, is it better to look at https://github.com/springfox/springfox-demos or at https://github.com/adrianbk/swagger-springmvc-demo/tree/feature/2.0-showcase?
Or is 2.0-showcase only for transition?

**Comment by dilipkrish** [comment]
@jfiala springfox-demos is a better option at the moment as we slowly port the older demo application into the spring fox organization. Yes we're using the Predicates from guava.

**Comment by jfiala** [comment]
After updating the Maven dependencies according to the demos, version 1.2 and 2.0 work perfect.
