### ISSUE TITLE
swagger-2.0.0-SNAPSHOT: Swagger 2.0 throws NoSuchBeanDefinitionException during startup when using both springfox-swagger2 + springfox-swagger dependencies

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#661]
swagger-2.0.0-SNAPSHOT

The configuration:
* EnableSwagger2
* DocumentationType.SWAGGER_2

``` java
@SpringBootApplication
@EnableSwagger2
public class Application {
	
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }  

    
    @Bean
    public Docket swaggerSpringMvcPlugin() {
      return new Docket(DocumentationType.SWAGGER_2)
              .groupName("business-api")
              .select() 
                 //Ignores controllers annotated with @CustomIgnore
                //.apis(not(withClassAnnotation(CustomIgnore.class)) //Selection by RequestHandler
                //.paths(paths()) // and by paths
                .build()
              .apiInfo(apiInfo());
              //.securitySchemes(securitySchemes())
              //.securityContext(securityContext());
    }
    

    private ApiInfo apiInfo() {
	      ApiInfo apiInfo = new ApiInfo(
	              "My Apps API Title", "My Apps API Description", "1.0",
	              "My Apps API terms of service", "My Apps API Contact Email",
	              "My Apps API Licence Type", "My Apps API License URL"
	        );
	      return apiInfo;
	    }

    //Here is an example where we select any api that matches one of these paths
    /*private Predicate<String> paths() {
      return or(
          regex("/business.*"),
          regex("/some.*"),
          regex("/contacts.*"),
          regex("/pet.*"),
          regex("/springsRestController.*"),
          regex("/test.*"));
    }*/
    
    
}
```

causes Exception during startup:
``` java
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [springfox.documentation.swagger.mappers.ServiceModelToSwaggerMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

The class ServiceModelToSwaggerMapper is not mentioned in the transition guide (https://github.com/springfox/springfox/blob/master/transitioning-to-v2.md), should it be configured somewhere?

**Comment by dilipkrish** [comment]
@jfiala It should automatically be pulled in if you have the ```@EnableSwagger[2]``` annotation.

**Comment by jfiala** [comment]
I have set the @EnableSwagger2 annotation (see above), but I get the exception during startup.

**Comment by dilipkrish** [comment]
Could you look at whats different between the demo application and what you have? Also how are you launching the application

**Comment by jfiala** [comment]
I copied my controllers to the demo, now it is working.

Minor: 
http://localhost:8080/swagger2/webjars/springfox-swagger-ui/2.0.0-SNAPSHOT/sdoc.jsp
SwaggerUI has by default the wrong API-URL:

current: http://localhost:8080/swagger2/api-docs
correct: http://localhost:8080/swagger2/v2/api-docs

**Comment by jfiala** [comment]
In fact, including both dependencies to springfox-swagger2 and springfox-swagger was responsible for the exception. 

```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
<!-- for swagger spec 1.2 optionally -->
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
```

After I remove one of the both dependency, everything is working fine.

**Comment by jfiala** [comment]
maybe a hint should be added in the docs that they are not usable in parallel.

**Comment by dilipkrish** [comment]
hmm thats weird because they totally work together in our [contract-tests](https://github.com/springfox/springfox/tree/master/swagger-contract-tests)

**Comment by adrianbk** [comment]
@dilipkrish I reckon we shouldn't support both spec versions 1.2 and 2.0 in parallel?

**Comment by dilipkrish** [comment]
I'll test it out in the demo app and see if its a problem

**Comment by dilipkrish** [comment]
Verified via [this commit](https://github.com/springfox/springfox-demos/commit/a83b9c55d8f8acc000210bbe99de823fa2f0641d)

**Comment by jfiala** [comment]
Here you can reproduce:
https://github.com/jfiala/swagger-spring-demo/tree/master/user-rest-service-2.0.0
simply check out user-rest-service-2.0.0 and do mvn spring-boot:run and you get  

```Java
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [springfox.documentation.swagger.mappers.ServiceModelToSwaggerMapper]
```
during startup.

**Comment by jfiala** [comment]
Just for own interest: Why is there no reference to the issue in your commit comment (which would it probably make easier to track commits)?

**Comment by dilipkrish** [comment]
@jfiala thats because its in a different repo

**Comment by dilipkrish** [comment]
@jfiala I've not been able to reproduce it using my fork. Here is the [relevant commit](https://github.com/dilipkrish/swagger-spring-demo/commit/29bf24c8df86dd9360f5b7e82824be3a09bfc2cf)

**Comment by jfiala** [comment]
I justed committed the same change as you did.
https://github.com/jfiala/swagger-spring-demo/commit/466991dbace6c201beb6c0bdd979afe0a875e87f

In fact, the behaviour changes to:
With Swagger / DocumentationType.SWAGGER_12
Exception in thread "main" java.lang.NullPointerException: null key in entry: null=springfox.documentation.spring.web.plugins.Docket@1b35db6f

With parallel + Swagger2 / DocumentationType.SWAGGER_2 it's still the same:
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [springfox.documentation.swagger.mappers.ServiceModelToSwaggerMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
