### ISSUE TITLE
2.0.0-SNAPSHOT: transitioning-to-v2.md contains broken links

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#662]
https://github.com/springfox/springfox/blob/master/transitioning-to-v2.md

1.) These two links are broken:
For a list of handy predicates Look at <RequestHandlerSelectors> and <PathSelectors>.

2.) The packages of Predicate/or/regex should probably better be mentioned in the listing.

**Comment by dilipkrish** [comment]
@jfiala thanks for catching these nuances! :+1: 

Also if you do find discrepancies in the documentation would be great if you could send in the changes as a PR!
