### ISSUE TITLE
2.0.0 - Array[enum] parsed as Array[String] in request

### ISSUE THREAD

**Issue by hestad** [springfox/springfox#664]
''' java
@RequestMapping
public Set<Foo> bar()(
@RequestParam(defaultvalue="",required=false) final enum[] enums) {}

Expecting api-docs json Array[enum], but get Array[string]. Same result with Collection, List and Set.

**Comment by dilipkrish** [comment]
@hestad this is a tricky one! dont want to hold 2.0 release back because of this.

**Comment by hestad** [comment]
@dilipkrish okay, it works in 1.0.0, btw.

**Comment by hestad** [comment]
I would love to get some input on how I could quick-fix this, as this is currently my last "major" issue before production. Any pointers on types, methods, fields to change?

**Comment by dilipkrish** [comment]
I looked at this a while back and the reason I felt it might be hard was because, enums perse cannot be represented as models (atleast in swagger 1.2 and 2). Enums are only attributes of a property, kind of like *required*, *defaultValue*, *allowedValues* etc. It would be considerable effort to make them first class types and behave differently, and I'm not even sure its worth the effort.

Why is still a show stopper. because my guess is that the array item documents the enum values already.

**Comment by hestad** [comment]
Just to clear up. I just want my enum to be mapped to a so called allowedValues enum defined by the swagger spec. And defaultValue and required is also what I need. I don't want it mapped to a custom type. But I want them inside a set or enumset.

**Comment by RobWin** [comment]
@dilipkrish @adrianbk 
I have a similar issue. I'm not sure if it is related to this one.

```
@RequestParam(value = FILTER_BY, required = false) ContactField[] filterBys,
```
The ContactField[] is parsed as a string array.

{
                    "name": "filterBy",
                    "in": "query",
                    "description": "filterBys",
                    "required": false,
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "collectionFormat": "csv"
                },

**Comment by hestad** [comment]
As a sidenote, when using single enums as parameters, we are observing the same problem. allowableValues and enum is excluded from the api-docs.

Tolerable quickfix for us: Adding @ApiParam(value="allowMultiple: true, allowableValues: ENUM1, ENUM2, ENUM3") on every parameter which uses enum. A sidenote here is that all the other fields than 'value' is ignored by springfox 2.0.0.

**Comment by hestad** [comment]
As a sidenote, when using single enums as parameters, we are observing the same problem. allowableValues and enum is excluded from the api-docs.

Tolerable quickfix for us: Adding @ApiParam(value="allowMultiple: true, allowableValues: ENUM1, ENUM2, ENUM3") on every parameter which uses enum. A sidenote here is that all the other fields than 'value' is ignored by springfox 2.0.0.

**Comment by dilipkrish** [comment]
@hestad @RobWin :christmas_tree: :)

**Comment by RobWin** [comment]
great thx. is it already in 2.0.1-SNAPSHOT? or 2.1?

**Comment by dilipkrish** [comment]
in 2.0.1 snapshot

**Comment by hestad** [comment]
lovely! thanks a lot :)
