### ISSUE TITLE
ApiModelProperty: dataType attruibute usage

### ISSUE THREAD

**Issue by vlopato** [springfox/springfox#666]
Hi!

As far as I know @JsonView annotation of the Jakson library is not supported now. I try to find workaround to close the problem. 

Situation:
I have class Model and class Collection which contains model property. If user requests /model/@id action all properties of the Model object should be received. If user requests /collection/@id action he should get collection with model but model should be serialized partially. I use @JsonView annotation for this purpose.

My thoughts: 
I make new class ModelInfo which extend the Model class and try to hide unnecessary property (this works if I use .directModelSubstitute() method and replace Model with ModelInfo everywhere)

<pre>

public class ModelInfo extends Model{

    @ApiModelProperty(hidden = true)
    @Override
    public List<ModelImage> getImages() {
        return super.getImages();
    }

}
</pre>

After I tried to replace Model with Model info in Collection class using @ApiModelProperty with custom dataType attribute:

<pre>
@Entity
@Table(name = "collection")
@ApiModel
public class Collection {

    @JsonView(CollectionView.Info.class)
    @Id
    @GeneratedValue
    private Long id;

    @JsonView(CollectionView.Info.class)
    @ManyToOne
    @ApiModelProperty(dataType = "com.company.model.ModelInfo")
    private Model model;
</pre>

But this doesn't work. I get Model entity in this case.

I can see in json the data like this:

<pre>
        "Collection": {
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "model": {"$ref": "#/definitions/Model"}
            }
        },
</pre>

Is it possible to do it in this way? I tried to find another way but with no luck.

Thanks for your work!

**Comment by dilipkrish** [comment]
@vlopato are you using 1.0.2? If so, its not going to work. This feature is only implemented in 2.x

**Comment by vlopato** [comment]
No, 2.0.0-SNAPSHOT.

**Comment by dilipkrish** [comment]
@vlopato this is a great catch! Thanks for reporting. The problem is that while the type is getting overriden the model ref is not. I'll fix this shortly

**Comment by vlopato** [comment]
Thank you.

Could you say how soon it will be available via maven repo? in a week, in a month?

**Comment by dilipkrish** [comment]
@vlopato in a bit :)

**Comment by vlopato** [comment]
It works! Super! Thank you very much.
