### ISSUE TITLE
Handling of java.util.Calendar not consistent between model and transfer object

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#669]
2.0.0-SNAPSHOT

Currently springfox provides a java.util.Calendar (https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html) as a model structure by default in the api-docs:
```
"ShowcaseDatatypeDate":{"properties":{"calendar":{"$ref":"#/definitions/Calendar"},"date":{"type":"string","format":"date-time"}}}
...
"Calendar":{"properties":{"firstDayOfWeek":{"type":"integer","format":"int32"},"lenient":{"type":"boolean"},"minimalDaysInFirstWeek":{"type":"integer","format":"int32"},"time":{"type":"string","format":"date-time"},"timeInMillis":{"type":"integer","format":"int64"},"timeZone":{"$ref":"#/definitions/TimeZone"},"weekDateSupported":{"type":"boolean"},"weekYear":{"type":"integer","format":"int32"},"weeksInWeekYear":{"type":"integer","format":"int32"}}}}
```

However, the Calendar object itself will be sent over the wire as a long value:
```
"calendar": 1428909372307
```

This resulted in an error with the generated code using Swagger-Codegen (and will do so for every client trying to consume a java.util.Calendar):
https://github.com/swagger-api/swagger-codegen/issues/624#issuecomment-92149355

So the java.util.Calendar should be sent as a real model structure to allow clients to pick it up correctly.
(as a workaround, we can simply use java.util.Date, which is handled correctly).

**Comment by dilipkrish** [comment]
@jfiala Please use the model substitution to tell the library how to represent the Calendar object. If your clients expect to use a long then ```directModelSubstitute(Calendar.class, Long.class)``` if your client expect a date formatted in mm-dd-yyyy then use ```directModelSubstitute(Calendar.class, String.class)```

**Comment by jfiala** [comment]
Perfect, works like a charm (verified Long with 1.0.2 + 2.0.0-SNAPSHOT)!

**Comment by dilipkrish** [comment]
@jfiala can we ask what you're working on? Seems like you flushed out quite a few esoteric bugs. Thanks!

**Comment by jfiala** [comment]
I already used the Swagger-Spring integration in November for a small project. I did a presentation of the Swagger-Spring integration with Codegen yesterday at the Confess in Vienna.

One question asked was if it would also be possible to access comments instead of having to add the api-annotations: To my mind this should be definitely a decision up to the developer, as Javadoc comments are possibly internal. However, I think in some cases it would make sense, escpecially as developers don't like to migrate comments. A different possibility would be to simply use codegen to pick up the comments and copy the generated java source back to the server. Then this decision would be at the sole discretion of the user. What do you think?
