### ISSUE TITLE
@RequestBody is creating parameters named "body", and cannot be over-ridden

### ISSUE THREAD

**Issue by who** [springfox/springfox#671]
When using `@RequestBody` annotation on an object, the `name` attribute of the `@ApiParam` annotation is ignored, and instead "body" is used.

Here's my repro:

This source:

```
    @RequestMapping(
        value = "/books", 
        method = RequestMethod.POST, 
        consumes = MediaType.APPLICATION_JSON_VALUE,       
        produces = MediaType.APPLICATION_JSON_VALUE)
    @ApiOperation(
        value = "Create a book",
        notes = "Creates a book so that it can be managed by this api.",
        response = Book.class,
        authorizations = @Authorization(value = "basicAuth", type = "basicAuth")
    )
    @ApiImplicitParams(@ApiImplicitParam(name="custom-auth-header", value="",required=false,dataType = "string", paramType = "header"))
    public Book createBook(
        @ApiParam(value = "Book object", required = true, name = "book") @RequestBody @Valid Book book) {
        return bookService.createBook(book);
    }
```

Yields this output:

```
{
  ...
  "paths": {
    "/books": {
      "post": {
        "summary": "Creates a book",
        "description": "Creates a book so that it can be managed by this api.",
        "schemes": [],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Book object",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Book"
            }
          },
          {
            "name": "custom-auth-header",
            "in": "header",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "404": {
            "description": "Not Found",
            "examples": {},
            "headers": {}
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Book"
            },
            "examples": {},
            "headers": {}
          },
          "201": {
            "description": "Created",
            "examples": {},
            "headers": {}
          },
          "401": {
            "description": "Unauthorized",
            "examples": {},
            "headers": {}
          },
          "403": {
            "description": "Forbidden",
            "examples": {},
            "headers": {}
          }
        },
        "security": [
          {
            "basicAuth": []
          }
        ]
      }
    }
  }
  ...
}
```

**Comment by who** [comment]
This may be another occurrence of https://github.com/springfox/springfox/issues/502

**Comment by who** [comment]
I found this issue while generating a PHP client with swagger-codegen, using the spec as generated by springfox.

I filed a separate issue with swagger-codegen, as parameters named "body" shouldn't collide with code generation templates.

https://github.com/swagger-api/swagger-codegen/issues/628

**Comment by dilipkrish** [comment]
So the parameter name shouldn't matter if its a body right? Whats the issue here?

**Comment by who** [comment]
I agree that the parameter name should not matter if it is a body parameter.

However, some downstream code generators, which consume the Swagger api doc, use the name of the  body parameter in order to name the generated variable.  In the case with swagger-api/swagger-codegen#628, this creates conflicts.

**Comment by dilipkrish** [comment]
@who it seems like the code-generator shouldn't break no matter what I decide to call the parameter. I dont see this as a pressing issue with this library. Do you?

**Comment by who** [comment]
I agree that this is more of an issue at the generator side.

However, I still think overriding the "body" parameter name should be possible with the `@ApiParam` annotation. 

If I had the option to over-ride the name of the parameter generated by springfox, I would use that as an interim workaround until all downstream consumers of the api-doc file have been fixed.

**Comment by adrianbk** [comment]
I  believe there is something in the swagger spec which specifies the param must be named 'body'

**Comment by dilipkrish** [comment]
That seems vaguely familiar :grin: Don't think thats true for v2.0

**Comment by who** [comment]
From https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameter-object

> The name of the body parameter has no effect on the parameter itself and is used for documentation purposes only.

**Comment by adrianbk** [comment]
True - it's not required  be named 'body' for spec 2.0. @who would you be interested in submitting a fix for this? We can point you in the right direction if you are.

**Comment by dilipkrish** [comment]
I started out an initial work on this. Unfortunately that exposed a gaping whole in the test coverage for the swagger 2 mappers.

**Comment by adrianbk** [comment]
@dilipkrish where is the gap with coverage?

**Comment by dilipkrish** [comment]
There were no tests in swagger2 module

**Comment by dilipkrish** [comment]
This issue should now be fixed.
