### ISSUE TITLE
Reuse documentation across methods/types

### ISSUE THREAD

**Issue by hestad** [springfox/springfox#679]
This is a feature request / question for quickfix.

I have six header-parameters that all my rest-methods requires. I have extended Spring's HandlerInterceptorAdapter, so I can validate and collect those values. But now their missing in the api-docs, so I can add them with @ApiImplicitParams(6x@ApiImplicitParam) for every method I have. I wish that this ApiImplicitParams/ApiImplicitParams supported target=ElementType.TYPE in addition to ElementType.METHOD. I see that springfox's OperationImplicitParameterReader scans for this annotation on a method-level. Do someone have a tip on how I can not duplicate the documentation 20x+ times?

How could i quick fix this for myself? Aspects? Meta-annotations? Extending Springfox to support custom readers? Anything else?

PS. This problem could possible arise on other parameters than headers, I suppose.

**Comment by adrianbk** [comment]
@hestad I think you are on to something very useful here and extending Springfox would be the way to go!!
We already have the notion of [globalResponseMessages](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L169-169) which I think is somewhat analogous to what you are describing (except it deals with HTTP responses). We are not entirely happy with how globalResponseMessages work so it would be good for us to address how to model crosscutting concerns of API's using this a a concrete requirement.
Would you be interested in working on this?

**Comment by dilipkrish** [comment]
Implementing ```OperationBuilderPlugin``` is the place to start. It gives you access to a ```OperationContext``` where you can add header ```parameters```. Here is an [example](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OperationImplicitParametersReader.java)

Like @adrianbk mentioned, it would ben elegant to create a cross-cutting configuration via a fluent dsl using ```Docket```. This would be useful to all library users. Similar to the [ApiSelector](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L347-L349). This configuration could be made available via ```OperationContext```.

**Comment by hestad** [comment]
@adrianbk What exactly do you mean by extending springfox? Standalone module? Inside springfox? Or as a standalone github repo? I'm mostly doing this related to work, so I can't use any more work-time on this than i already do. But if it's small enough I would at least be able to contribute at my free time.

@dilipkrish I'll look at the example and the source code, thanks for the pointer =)

**Comment by adrianbk** [comment]
@hestad yes I mean inside Springfox. We would be providing a way to specify headers that apply to the entire API. 

Both @dilipkrish  an I have day jobs outside of Springfox so we really do appreciate when people gve back by contributing :+1:

**Comment by dilipkrish** [comment]
This is now fixed via #861. Closing this issue
