### ISSUE TITLE
RequestParam when the consumed content type is set to application/x-www-form-urlencoded should produce paramType: form

### ISSUE THREAD

**Issue by nikolavp** [springfox/springfox#680]
RequestParam parameters should be interpreted as form parameters when the consumes attribute is set to application/x-www-form-urlencoded but they generate invalid documentation(they have paramType: query). I can see that the logic for that can be found [here](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/parameter/ParameterTypeReader.java) but there is no context information about ApiOperation or RequestMapping there

**Comment by nikolavp** [comment]
Ok it seems that this can be inspected with the help of DocumentationContext. I will try to build a simple patch tomorrow?

Not sure what has to be done if there are multiple consumes content types and only one of them is x-www-form-urlencoded?

**Comment by dilipkrish** [comment]
@nikolavp doesnt ```@ModelAttribute``` in combination with ```application/x-www-form-urlencoded``` media type not work?

**Comment by nikolavp** [comment]
Although I don't want to use ModelAttribute, I tried and the result is the same. For example this
{code}
    @ApiOperation(value = "Foo description")
    @RequestMapping(
            value = "foo",
            produces = MediaType.TEXT_PLAIN_VALUE,
            consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE,
            method = RequestMethod.POST)
    @ResponseBody String test(@ModelAttribute("bean") Bean location) {
        return "test";
    }
{code}

shows the arguments as query parameters.

**Comment by dilipkrish** [comment]
@nikolavp thanks for reporting! give it a shot and let us know if its fixed

**Comment by nikolavp** [comment]
Yes this fixes it for me!

**Comment by smthpickboy** [comment]
@dilipkrish I've tested with springfox 2.7.0 and 2.7.1-SNAPSHOT, the ModelAttribute support is not working.

I find that parameter type "query" is hard coded in ExpandedParameterBuilder.java
https://github.com/springfox/springfox/blob/4427e23933629d1dce3ac2a80f7c8cd4d75f8ef6/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/parameter/ExpandedParameterBuilder.java#L97

Is there any way to produce parameter type "form" when using modelattribute with application/x-www-form-urlencoded like the old behavior?

Thanks!

**Comment by dilipkrish** [comment]
@smthpickboy That is a bug. Would you mind reporting it as a separate/new issue. Thanks
