### ISSUE TITLE
Need to provide a way to override swagger host attribute

### ISSUE THREAD

**Issue by adrianbk** [springfox/springfox#689]
```java 
swagger.host(String.format("%s:%s", uri.getHost(), uri.getPort()));
```

https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L66

**Comment by dilipkrish** [comment]
Why is this a bug. This is per spec the right way to get the host name.

**Comment by adrianbk** [comment]
Remember the historical AbsoluteSwaggerPathProvider...? See [this issue](https://github.com/springfox/springfox/issues/236#issuecomment-37798411)

**Comment by dilipkrish** [comment]
Yup, bad memories :) but you'd think spring framework would've solved that problem if it's in the library. It uses the x-forwarded... headers algorithm. In any case the better fix is if it's optional in the spec we should not render it even. :)

**Comment by adrianbk** [comment]
Yep it's not guaranteed the be the right thing. Should we allow configuring it as a property via PropertyPlaceHolderConfigurer?

**Comment by dilipkrish** [comment]
I'm up for that. If it's overridden use it if not fall back to this approach?

**Comment by adrianbk** [comment]
:+1:
