### ISSUE TITLE
Please fill operationId

### ISSUE THREAD

**Issue by RobWin** [springfox/springfox#690]
Please fill the operationId: A friendly name for the operation. 
The operationId is already used as a default value for summary and description, if not specified manually. 
See example for method "deleteAddressBook:

```
    "paths": {
        "/rest/contacts/v1/addressbook": {
            "delete": {
                "tags": [
                    "address-book-controller"
                ],
                "summary": "deleteAddressBook",
                "description": "deleteAddressBook",
```

it should be: 

```
    "paths": {
        "/rest/contacts/v1/addressbook": {
            "delete": {
                "tags": [
                    "address-book-controller"
                ],
                "summary": "deleteAddressBook",
                "description": "deleteAddressBook",
                "operationId": "deleteAddressBook",
```

Greetings, 
Robert

**Comment by dilipkrish** [comment]
It should already be populating the operationid. :confused: There is already a bug to make that unique across the api.

**Comment by adrianbk** [comment]
@RobWin can you verify that the operationId is not being generated. Are you using swagger spec version 1.2 or 2.0?

**Comment by RobWin** [comment]
Indeed very strange. I debug again.
I can see that it is set in DefaultOperationReader.java.

**Comment by dilipkrish** [comment]
@RobWin close?

**Comment by RobWin** [comment]
Ok
