### ISSUE TITLE
[Question] - Springfox 2.0.0 release dates/timelines

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#693]
Hi All,

This is not an issue. I was not sure where to ask this question.

What is the timeline/ETA for the first GA release of this springfox 2.0.0. Any rough timelines would also help.

Regards,
Rajesh Kamal.

**Comment by adrianbk** [comment]
@rajeshkamal we are expecting within the next week. The more people we have testing out the 2.0.0-SNAPSHOT version and reporting and fixing issues the sooner 2.0.0 will be released :)

**Comment by hestad** [comment]
2.0.0 is released. Close?
