### ISSUE TITLE
RelativePathProvider does not contain methods for extending the context path

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#694]
Using springfox 2.1.0 SNAPSHOT.

RelativePathProvider does not contain methods for extending the context path.?

Any inputs.

**Comment by adrianbk** [comment]
@rajeshkamal pleas elaborate on the issue you are having?

**Comment by rajeshkamal** [comment]
a. The root context path for the web application is /vrm

b. In the web.xml I have the servlet mapping as 
	<servlet-mapping>
		<servlet-name>some-api</servlet-name>
		<url-pattern>/api/evorm/*</url-pattern>
	</servlet-mapping>

c. The rest controllers have something like /users, /users/{userId} etc.

The resulting url would look like this,
-- https://hostname/vrm/api/evorm/users
-- https://hostname/vrm/api/evorm/users/{userId}

When I use the default RelativePathProvider. It uses the ServletContext's getContextPath() and gets the basePath as /vrm. Then onto the individual controllers it gets /users or /users/{userId}. Forms the URL as /vrm/users or /vrm/users/{userId}.

Inorder to get the proper path, I had to write a custom relative path provider to get the proper full URL's.

import static com.google.common.base.Strings.isNullOrEmpty;

import javax.servlet.ServletContext;

import springfox.documentation.spring.web.AbstractPathProvider;

public class CustomRelativePathProvider extends AbstractPathProvider {
	public static final String ROOT = "/";
	private final ServletContext servletContext;

	public CustomRelativePathProvider(ServletContext servletContext) {
		super();
		this.servletContext = servletContext;
	}

	@Override
	protected String applicationPath() {
		return isNullOrEmpty(servletContext.getContextPath()) ? ROOT
				: servletContext.getContextPath() + "/api/evorm";
	}

	@Override
	protected String getDocumentationPath() {
		return ROOT;
	}
}

**Comment by adrianbk** [comment]
@rajatvig the intention is that you provide your own implementation as you have done and set it using springfox.documentation.spring.web.plugins.Docket#pathProvider

**Comment by dilipkrish** [comment]
```Docket#pathMapping``` allows you to add the path mapping (the prefix) you need to get the urls correct. In your case if would be ```Docket.pathMapping("/api/evorm")```

**Comment by rajeshkamal** [comment]
Thanks used Docket.pathMapping("/api/evorm") and it works !!.
