### ISSUE TITLE
swagger-springmvc and spring security

### ISSUE THREAD

**Issue by Mikhail88** [springfox/springfox#695]
Hi.
I'm trying to use swagger-springmvc 1.0.2 in my project and I can't figure out how to configure authorizations using Oauth.

I investigated an example given here I learned an example
https://github.com/adrianbk/swagger-springmvc-demo/blob/master/spring3-testsuite/src/main/java/com/ak/spring3/testsuite/config/SwaggerConfig.java

This is a part of my security config 

`
<beans:bean id="clientAuthenticationEntryPoint"
                class="org.springframework.security.oauth2.provider.error.OAuth2AuthenticationEntryPoint"/>

    <beans:bean id="oauthAccessDeniedHandler"
                class="org.springframework.security.oauth2.provider.error.OAuth2AccessDeniedHandler"/>

    <beans:bean id="clientCredentialsTokenEndpointFilter"
                class="org.springframework.security.oauth2.provider.client.ClientCredentialsTokenEndpointFilter">
        <beans:property name="authenticationManager" ref="clientAuthenticationManager"/>
    </beans:bean>

    <http pattern="/oauth/token" create-session="stateless" authentication-manager-ref="clientAuthenticationManager">
        <intercept-url pattern="/oauth/token" access="IS_AUTHENTICATED_FULLY" method="POST"/>
        <anonymous enabled="false"/>
        <http-basic entry-point-ref="clientAuthenticationEntryPoint"/>
        <access-denied-handler ref="oauthAccessDeniedHandler"/>
        <custom-filter ref="clientCredentialsTokenEndpointFilter"
                       after="BASIC_AUTH_FILTER"/>
    </http>

    <http pattern="/**" create-session="never"
          entry-point-ref="oauthAuthenticationEntryPoint" use-expressions="true">
        <anonymous enabled="true"/>
        <custom-filter ref="resourceServerFilter" before="PRE_AUTH_FILTER"/>
        <access-denied-handler ref="oauthAccessDeniedHandler"/>
        <intercept-url pattern="/cms/**" access="hasRole('ROLE_CMS_USER')"/>
    </http>

    <beans:bean id="oauthAuthenticationEntryPoint"
                class="org.springframework.security.oauth2.provider.error.OAuth2AuthenticationEntryPoint"/>
`
and I'm receiving Oauth token on myAppContext/oauth/token endpoint. 
Then I just add Authorization:Bearer token to request header

Could you please explain what I should pass in authorizationContext() and authorizationTypes() to
get work authorization on swagger UI?

**Comment by dilipkrish** [comment]
@Mikhail88 before I answer, we're very close to releasing 2.0.0, which has better support for all of this anyways and it supports swagger spec 2.0. So would you be willing to be our test subject in verifying that the security related work we've been doing works in 2.0 of the library as well. 

The bonus is ofcourse you'll be already on the  2.0 upgrade path :)
