### ISSUE TITLE
Publishing test artifacts springfox-schema

### ISSUE THREAD

**Issue by adrianbk** [springfox/springfox#696]
https://github.com/springfox/springfox/blob/master/springfox-schema/build.gradle#L11

@dilipkrish any idea why?

**Comment by dilipkrish** [comment]
Yup. That was a shortcut so that test artifacts can be shared. For eg the types, some traits/mixins. Might be a better way to do this?

**Comment by adrianbk** [comment]
Nope, my bad!!  At a first glance I though it meant we were publishing the test classes. The real publishing config is in https://github.com/springfox/springfox/blob/master/gradle/artifacts.gradle. :sleeping:

**Comment by dilipkrish** [comment]
close?
