### ISSUE TITLE
Integration with Spring-Data-Rest

### ISSUE THREAD

**Issue by raranzueque** [springfox/springfox#699]
I am using Spring-Data-Rest to expose my entities as REST endpoints. I like to know if is there any way to integrate with springfox ?

SpringMVC libraries looks for @RequestMapping annotation or @Api annotations to generate swagger documentaion. In SpringDataRest, we don't use the @RequestMapping annotation to expose REST endpoints. SpringDataRest exposes your Entity class as REST endpoints. It looks for a Repository interface for your entities, and if there is one, your entity is exposed as REST endpoint. 

I think the Request mapping is generated behind the scenes and you don't have control over it.  Any idea, how springfox can be configured in this case ?

**Comment by adrianbk** [comment]
@raranzueque The timing of your question is perfect. We are just about to release v2.0.0 and a big focus of that release has been laying a foundation to support other spring projects like spring-data-rest and spring-integration.
 
It would be really good to get some community involvement to help drive this. 

Including others which may be interested: 
@uttrasey 
@vivekpandian
@skallio 
@jewellcj 
@ghorwitchsmith
@jhiemer 
@jxc876 

The following 2 issues are related: 
https://github.com/springfox/springfox/issues/238
https://github.com/springfox/springfox/issues/550

**Comment by ddelizia** [comment]
Spring Data Rest is producing Alps metadata, maybe you can use that implementation to get started with swagger metadata generation.

https://spring.io/blog/2014/07/14/spring-data-rest-now-comes-with-alps-metadata

**Comment by apitt** [comment]
That would be great!

We're starting to use Spring Data Rest, but having a hard time trying to figure out how we are going to have some nice documentation to go with the APIs.

With ALPS, it wouldn't be too hard to create custom documentation by having a JavaScript library point at the ALPS root for the app and build some tables based on the the data available and documentation that's included in a rest-messages.properties file.

However, it would be much nicer to be able to provide docs that people will immediately recognize (such as Swagger docs).

If this feature is still on the table, I definitely vote for it.

**Comment by apitt** [comment]
After reading some of the comments from @olivergierke (particularly this one https://github.com/springfox/springfox/issues/238#issuecomment-63219435), I'm tending to agree that Swagger-style documentation isn't a fit.  In fact, if you're going to use Spring Data Rest, then you need to do your best to discourage clients from treating your API as a static API.

I'm actually re-thinking my use of Spring Data Rest.  We are planning on plugging our APIs into an API Gateway (WSO2), so the non-static API that Spring Data Rest provides would actually be a terrible fit.

My current thinking is that a happy medium (for me) will be using Spring Data (to get the automatic data layer) and normal RestController controllers to expose a static API.  This will also allow me to use SpringFox out of the box.

**Comment by xbmono** [comment]
@adrianbk Version 2.0 is released now but Spring Data Rest is not supported yet. And now Katharsis is coming into the play... We are at the point to decide whether to go with Swaggerfox or Spring RestDoc. Can you please let me know if there is any plan to support Spring Data Rest? I also need to know how soon it will be because we need to make a decision pretty quick.
Thanks

**Comment by dilipkrish** [comment]
@xbmono Before getting into when you can expect this to be completed, thought it would be to get a couple of things out of the way, so that you're better informed.
1. `spring-restdocs` is inherently a better choice to document `spring-data-rest` services. Especially if you want to document hypermedia services that has links and relations.
2. swagger is url centric and the specification does not have a focus on building hypermedia aware applications.
3. However the BIG difference between `swagger` and `spring-restdocs` from the perspective of documentation is that one is machine readable while the latter is not (see :point_down:  5).
4. There is a great tool build by @RobWin [swagger2markup](https://swagger2markup.readme.io) that can leverage your swagger service description to generate documentation just like `spring-restdocs`
5. swagger has an amazing amount of tooling and has a strong ecosystem/community, i.e. swagger-code-gen. One would argue that you don't need all this tooling if you're building RESTful services, but thats where the great divide lies.

I would strongly discourage you from making a choice based on availability of not-availability of this feature in time for your project; rather make your choice on how you see the services documentation _being consumed_. At the moment this feature is scheduled for [March 1st](https://github.com/springfox/springfox/milestones), but its very dependent on the amount of bandwidth available for us to work on it. It ***is*** an open source project!

Needless to say, anything that you or your team can contribute to this library it will only help getting the long list of feature request accomplished and make this project better. IOW, PRs will be much appreciated! :metal: 

/c: @adrianbk

**Comment by xbmono** [comment]
@dilipkrish Thanks so much for the prompt reply. I think we will go with spring-restdocs and perhaps will combine it with swagger using the tool you mentioned. Just one question: I know it's not easy to explain here but in case we want to use ALPs metadata provided by spring and utilize them in swaggerfox, how can we do this customization? Any hint on how to start and what classes/interfaces are involved?

**Comment by xbmono** [comment]
@dilipkrish Thanks so much for the prompt reply. I think we will go with spring-restdocs and perhaps will combine it with swagger using the tool you mentioned. Just one question: I know it's not easy to explain here but in case we want to use ALPs metadata provided by spring and utilize them in swaggerfox, how can we do this customization? Any hint on how to start and what classes/interfaces are involved?

**Comment by bitsofinfo** [comment]
Any updates on a release for this?

**Comment by tduchateau** [comment]
+1

**Comment by Manuel83** [comment]
+1

**Comment by benleibert** [comment]
+1

**Comment by git03394538** [comment]
+1

**Comment by hasega** [comment]
+1

**Comment by guillaumegarcia13** [comment]
+1

**Comment by ahmni01** [comment]
Any updates on this?

**Comment by thomasbiesaart** [comment]
+1

**Comment by 94b** [comment]
+1

**Comment by anacesponda** [comment]
+1

**Comment by dilipkrish** [comment]
Initial implementation has landed in master!

**Comment by vzoran** [comment]
Great news! Is it possible to generate swagger API document out of @RepositoryRestResource repositories? (I.e. without RequestMapping annotation)
I would use kongchen/swagger-maven-plugin.

**Comment by dilipkrish** [comment]
@vzoran absolutely! feedback much appreciated if you use it.

**Comment by jewellcj** [comment]
Thanks, and sorry I haven't had time to participate  in this one, other than to state the problem. At the time I worked around it with somewhat a hack adapting the spring source for my specific project overriding  some methods and etc.

**Comment by vramku5** [comment]
I used 2.6.0 version of springfox for swagge2 and swagger-ui. Added a dependency to (as found in one of the doc checkins)
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-data-rest</artifactId>
            <version>${springfox.version}</version>
        </dependency>

I still dont see repositories annotated with @RepositoryRestResource show up in swagger ui.

What else needs to be done to utilize the new spring-data-rest support?

**Comment by dilipkrish** [comment]
Did you add the configuration as described?

**Comment by vramku5** [comment]
Thanks for the prompt reply.

I have added configuration as described for swagger in general. Created a docket, ApiInfoBuilder. 

I am able to see a swagger-ui with the default basic-error-controller. But not able to see the APIs defined below

`@RepositoryRestResource(collectionResourceRel = "myapi", path = "myapi")
interface MyApiRepository extends PagingAndSortingRepository<MyEntity, Long> {`

Is there any other configuration to be added for springfox support for spring-data-rest?

**Comment by dilipkrish** [comment]
@vramku5 explicitly have you added [this configuration](http://springfox.github.io/springfox/docs/current/#java-config)?

```java
//For java config
@Import({ ... springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration.class, ...})
```

**Comment by vramku5** [comment]
It works now after adding the above config.

I had interpreted the doc as maven | gradle | java | xml and hence had stopped at adding a maven dependency. However, makes sense as we have to tell somewhere to use that.

**Comment by Fredeli** [comment]
@vramku5 What exactly did you add to your @RepositoryRestResource? I still get the basic-error-controller.

**Comment by MarcoNiemann** [comment]
+1

**Comment by dilipkrish** [comment]
@Fredeli/ @MarcoNiemann `basic-error-controller` is a spring-boot controller. Its got nothing to do with spring-data-rest. If you don't want it to show up, you can specify that in the predicate (apis `RequestHandlerSelectors` or paths `PathSelectors`) in your docket to ignore.

**Comment by vramku5** [comment]
@Fredeli 
My code looks like this 

```
@SpringBootApplication
@EnableSwagger2
@Import({springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration.class})
public class ServletInitializer extends SpringBootServletInitializer {
```

It worked after I added the above import line. Hope it helps.

**Comment by xdom** [comment]
@dilipkrish Is there any way to show only exported resources, i.e. those which are not annotated with `@RepositoryRestResource(exported = false)` ?

**Comment by dilipkrish** [comment]
Yes you can create a predicate for that in your request handler selection

**Comment by xdom** [comment]
@dilipkrish But I cannot access `Repository` class through `RequestHandler`.. I think there is currently no way to check if the rest resource is exported or not.

**Comment by dilipkrish** [comment]
You should be able to get to the annotation using [this method](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/RequestHandler.java#L67)

**Comment by Ramblurr** [comment]
Any chance we could get a minimal spring-data-rest + spring boot example?

**Comment by BrunoEberhard** [comment]
Attached my working example. Had to click around a little bit in the browser to trigger the refresh

[example-springfox-rest-data.zip](https://github.com/springfox/springfox/files/1138658/example-springfox-rest-data.zip)

![image](https://user-images.githubusercontent.com/10797221/28066045-9d157e6c-663b-11e7-85b1-38b34464358a.png)

**Comment by GravesDevelopment** [comment]
@BrunoEberhard thx, works perfectly!

**Comment by lefkatis** [comment]
The example cannot be started on tomcat using spring-boot:run

**Comment by BrunoEberhard** [comment]
If you have maven installed try

`mvn compile exec:java -Dexec.mainClass="org.minimalj.sandbox.springrest.SpringRestApplication"`

Or import the project with eclipse as maven project and run the SpringRestApplication .

Then you can access the swagger ui with http://localhost:8080/swagger-ui.html#/

( please thank me by looking at https://github.com/BrunoEberhard/minimal-j and maybe give it a star :) )

**Comment by lefkatis** [comment]
Thanks for the prompt reply. 
I have been working to resolve this for weeks now. This discussion is a godsend for me! :D

I have maven installed and I managed to run the application although the only operators I get is the basic-error-controller. 

By the way I have tried to do my own spring-boot application and I have used spring-data-rest with JpaRepository for my objects instead of CrudRepository. I know this shouldnt be a problem because the JpaRepository extends CrudRepository, but I get the same result as @BrunoEberhard 's example above.

**How come you run the same example and you see all the operators and I don't?**

**Comment by BrunoEberhard** [comment]
For me JpaRepository works as good as CrudRepository. I really don't know why in your case it doesn't work. Maybe you can attach your example?

**Comment by dilipkrish** [comment]
@lefkatis Most likely you're not pulling in the [spring data rest configuration](http://springfox.github.io/springfox/docs/current/#springfox-spring-data-rest).

**Comment by lefkatis** [comment]
Thanks @dilipkrish and @BrunoEberhard. Much appreciated! 
Here is my code if you can help please.
Thanks

```
// ------   Object Class -------
@Entity
@Table(name = "category")
@NamedQuery(name = "Category.findAll", query = "SELECT c FROM Category c")
public class Category implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;

	private boolean isLocked;

	private String name;

	// bi-directional many-to-one association to Question
	@OneToMany(mappedBy = "category")
	private List<Question> questions;

	public Category() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(boolean isLocked) {
		this.isLocked = isLocked;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	public Question addQuestion(Question question) {
		getQuestions().add(question);
		question.setCategory(this);

		return question;
	}

	public Question removeQuestion(Question question) {
		getQuestions().remove(question);
		question.setCategory(null);

		return question;
	}

	public String toString() {
		return String.format("category=[id=%d, isLocked=%b, name=%s]", id, isLocked, name);
	}
}

// ------   JPARepository Class -------

import com.hellen.apiprojects.domain.Category;
import org.springframework.data.jpa.repository.JpaRepository;
public interface CategoryRepository extends JpaRepository<Category, Integer> {

}

// ------   POM FIle -------

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hellen.apiprojects</groupId>
    <artifactId>antavreis-web-api</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>antavreis-web-api</name>
    <description>Antavreis Game Web REST API</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.2.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.7.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-data-rest</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.7.0</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>


</project>
```

**Comment by BrunoEberhard** [comment]
Works for me. Had to change the parent to

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.6.RELEASE</version>
</parent>
```

And of course add Application and SwaggerConfig class. Took the from my example. Had also to remove the list of question from category as you didn't provide that class.

![grafik](https://user-images.githubusercontent.com/10797221/29632630-da1ab5be-8843-11e7-9c55-5da64241ebaa.png)

**Comment by lefkatis** [comment]
Thanks very much for the help @BrunoEberhard ! I have copied all my code into your project and it worked! dont know what was my problem though. But at least it works now.

**Comment by dilipkrish** [comment]
Thank you @BrunoEberhard and @lefkatis  for updating the fixes and in the process documenting it for future visitors.

**Comment by suiwenfeng** [comment]
@BrunoEberhard the example you give is not accessible now. can you help move the example to a github repo? example-springfox-rest-data.zip.

**Comment by silentsnooc** [comment]
This is probably a little outdated but I am not seeing these endpoints under `/v3/api-docs`.

I have created a question on stackoverflow in case somebody can help me with this issue: https://stackoverflow.com/questions/59868163/why-is-springfox-not-exposing-repositoryrestresource
