### ISSUE TITLE
Asciidocs #590 Code Review

### ISSUE THREAD

**Issue by adrianbk** [springfox/springfox#700]
@RobWin @dilipkrish 
https://github.com/springfox/springfox/issues/590

Some thoughts after merging this and setting up the [boot-static-docs demo application] (https://github.com/springfox/springfox-demos/tree/master/boot-static-docs)

1. We should remove the use of properties from  `springfox.documentation.staticdocs.Swagger2MarkupResultHandler`, specifically the need for `documentation.properties`. It should  be fine that the User will specify and absolute directory in the test as follows:
    ```groovy
   File target = ...
    Swagger2MarkupResultHandler resultHandler = convertIntoFolder(target).build()
   ```

1. I'd like to rename  `convertIntoFolder()` to `outputDirectory()`
1. We should add a `Swagger2ResultHandler` which just saves swagger.json - users have been looking for this for a while.

I think no. 1 and no. 2 need to happen before 2.0 is released.

**Comment by RobWin** [comment]
1. The property `io.springfox.staticdocs.outputDir` is nice, because you can declare in the gradle file a variable called `generatedDocumentation`

```
ext {
    generatedDocumentation = file('build/generated-snippets')
}

```

**Comment by adrianbk** [comment]
Regarding no. 2 heres what I'm thinking:
This is a groovy/spock test but the same should be doable with any java test.

```groovy
def "generates the petstore api asciidoc"() {
  setup:
    File outputDir = new File(System.getProperty('org.springframework.restdocs.outputDir'))
    Swagger2MarkupResultHandler resultHandler = Swagger2MarkupResultHandler
              .convertIntoFolder(outputDir).build()

   expect:
     this.mockMvc.perform(get("/v2/api-docs").accept(MediaType.APPLICATION_JSON))
              .andDo(resultHandler)
              .andExpect(status().isOk())

}
```
This would still work with the Gradle system property you have above. I think I'd prefer put the onus on the user to supply a `File` object to `Swagger2MarkupResultHandler` rather than force them to include the `documentation.properties` properties file. @dilipkrish any opinions on this?

**Comment by dilipkrish** [comment]
I'll preface saying that I know barely enough, but just briefly looking through it, I kind of prefer ```outputDirectory(...)``` as well. 

Also, I feel its simpler for the result handler to accept a fully qualified path/file. I suspect, its easier for the test author to construct that than for the result handler to infer it. 

Things are really shaping up. thanks for your efforts @RobWin :metal:

**Comment by RobWin** [comment]
Ok I'm convinced. In general I'm also more a fan of explicit than implicit.
