### ISSUE TITLE
@ApiResponses 2.0.0 Snapshot - not rendering - disabled useDefaultResponseMessages

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#702]
Hi,

I am using the 2.0.0 snapshot versions. Earlier I had the default response messages like 400, 401 etc.

I had disabled that using,
		plugin.useDefaultResponseMessages(false);

Now, I have the @ApiResponses in the Controller methods. Those are not getting rendered in the swagger ui and also I don't see them in the spec.
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "OK", response = Resources.class),
			@ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })

Any inputs, I on this.

Regards,
Rajesh Kamal.

**Comment by dilipkrish** [comment]
@rajeshkamal what does your configuration look like. Are you pulling in all the springfox modules?

**Comment by dilipkrish** [comment]
Could you check if you have ```springfox-swagger-common``` in your classpath?

**Comment by rajeshkamal** [comment]
Hi,

The only dependency I have it this in my project.

		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.1.0-SNAPSHOT</version>
		</dependency>

**Comment by rajeshkamal** [comment]
I have this as a maven deps - 
/Users/kamalr/.m2/repository/io/springfox/springfox-swagger-common/2.1.0-SNAPSHOT/springfox-swagger-common-2.1.0-SNAPSHOT.jar

**Comment by rajeshkamal** [comment]
I am have these in my classpath, anything wrong you see.

/Users/kamalr/.m2/repository/io/springfox/springfox-core/2.0.0-SNAPSHOT/springfox-core-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-spi/2.0.0-SNAPSHOT/springfox-spi-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-spring-web/2.0.0-SNAPSHOT/springfox-spring-web-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-swagger1/2.0.0-SNAPSHOT/springfox-swagger1-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-swagger2/2.1.0-SNAPSHOT/springfox-swagger2-2.1.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/com/wordnik/swagger-annotations/1.5.3-M1/swagger-annotations-1.5.3-M1.jar
/Users/kamalr/.m2/repository/com/wordnik/swagger-models/1.5.3-M1/swagger-models-1.5.3-M1.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-schema/2.1.0-SNAPSHOT/springfox-schema-2.1.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-swagger-common/2.1.0-SNAPSHOT/springfox-swagger-common-2.1.0-SNAPSHOT.jar

**Comment by dilipkrish** [comment]
Defenitely not the right dependencies. You have a version we experimented with our release process (2.1.0-SNAPSHOT). Anyways what you're listing there is the maven local repository NOT your projects dependencies. Could you update the dependencies so that all of them are 2.0.0-SNAPSHOT?

**Comment by rajeshkamal** [comment]
Hi,

I did changed eveything to 2.0.0-SNAPSHOT. but still I see the issue. I am not showing stuff from my repo below. This is the list of deps in my projects maven dependencies section. Copying and pasting it shows the whole local file path.

/Users/kamalr/.m2/repository/io/springfox/springfox-swagger2/2.0.0-SNAPSHOT/springfox-swagger2-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/com/wordnik/swagger-annotations/1.5.3-M1/swagger-annotations-1.5.3-M1.jar
/Users/kamalr/.m2/repository/com/wordnik/swagger-models/1.5.3-M1/swagger-models-1.5.3-M1.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-spi/2.0.0-SNAPSHOT/springfox-spi-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-core/2.0.0-SNAPSHOT/springfox-core-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-schema/2.0.0-SNAPSHOT/springfox-schema-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-swagger-common/2.0.0-SNAPSHOT/springfox-swagger-common-2.0.0-SNAPSHOT.jar
/Users/kamalr/.m2/repository/io/springfox/springfox-spring-web/2.0.0-SNAPSHOT/springfox-spring-web-2.0.0-SNAPSHOT.jar

**Comment by dilipkrish** [comment]
> I am not showing stuff from my repo below. 

why not? The stuff in your maven repo does not matter if you're project doesnt pull them in.

**Comment by rajeshkamal** [comment]
Ok, I just ran the mvn dependency:tree under my project. My project only uses the 2.0.0-SNAPSHOT.

In the spec and also in the UI, I am not able to see the stuff annotated under @ApiResponses.

[INFO] com.acme.rest.bundle:bundle-rest-service:war:1.0.0
[INFO] +- com.google.code.gson:gson:jar:2.3.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.2.2.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.2.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.2.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.2.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.2.2.RELEASE:compile
[INFO] |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.10:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.10:compile
[INFO] |  |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.10:compile
[INFO] |  |  |  \- ch.qos.logback:logback-classic:jar:1.1.2:compile
[INFO] |  |  |     \- ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.14:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.1.3.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  +- org.springframework:spring-core:jar:4.1.5.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.1.5.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:4.1.5.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.2.2.RELEASE:provided
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.0.20:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.20:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.0.20:provided
[INFO] |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.0.20:provided
[INFO] +- org.apache.tomcat.embed:tomcat-embed-jasper:jar:8.0.15:compile
[INFO] |  \- org.eclipse.jdt.core.compiler:ecj:jar:4.4:compile
[INFO] +- org.springframework:spring-web:jar:4.1.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.1.5.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.1.5.RELEASE:compile
[INFO] |  \- org.springframework:spring-context:jar:4.1.5.RELEASE:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.4.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.4.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.4.5:compile
[INFO] +- io.springfox:springfox-swagger2:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- org.mapstruct:mapstruct:jar:1.0.0.Beta4:compile
[INFO] |  +- com.wordnik:swagger-annotations:jar:1.5.3-M1:compile
[INFO] |  +- com.wordnik:swagger-models:jar:1.5.3-M1:compile
[INFO] |  +- io.springfox:springfox-spi:jar:2.0.0-SNAPSHOT:compile
[INFO] |  |  \- io.springfox:springfox-core:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-schema:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-swagger-common:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-spring-web:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.1.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] |  +- joda-time:joda-time:jar:2.7:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
[INFO] |  \- org.springframework.hateoas:spring-hateoas:jar:0.17.0.RELEASE:compile
[INFO] |     \- org.objenesis:objenesis:jar:2.1:compile
[INFO] +- io.springfox:springfox-swagger:jar:2.0.0-SNAPSHOT:compile
[INFO] \- org.ajar:swagger-spring-mvc-ui:jar:0.4:compile

**Comment by dilipkrish** [comment]
Could you remove the dependency on  ```io.springfox:springfox-swagger:jar:2.0.0-SNAPSHOT:compile``` we recently renamed the jar

**Comment by rajeshkamal** [comment]
I removed and the deps does not contain the same.

Still I do not get them.

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ bundle-rest-service ---
[INFO] com.acme.rest.bundle:bundle-rest-service:war:1.0.0
[INFO] +- com.google.code.gson:gson:jar:2.3.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.2.2.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.2.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.2.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.2.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.2.2.RELEASE:compile
[INFO] |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.10:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.10:compile
[INFO] |  |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.10:compile
[INFO] |  |  |  \- ch.qos.logback:logback-classic:jar:1.1.2:compile
[INFO] |  |  |     \- ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.14:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.1.3.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  +- org.springframework:spring-core:jar:4.1.5.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.1.5.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:4.1.5.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.2.2.RELEASE:provided
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.0.20:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.20:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.0.20:provided
[INFO] |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.0.20:provided
[INFO] +- org.apache.tomcat.embed:tomcat-embed-jasper:jar:8.0.15:compile
[INFO] |  \- org.eclipse.jdt.core.compiler:ecj:jar:4.4:compile
[INFO] +- org.springframework:spring-web:jar:4.1.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.1.5.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.1.5.RELEASE:compile
[INFO] |  \- org.springframework:spring-context:jar:4.1.5.RELEASE:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.4.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.4.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.4.5:compile
[INFO] +- io.springfox:springfox-swagger2:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- org.mapstruct:mapstruct:jar:1.0.0.Beta4:compile
[INFO] |  +- com.wordnik:swagger-annotations:jar:1.5.3-M1:compile
[INFO] |  +- com.wordnik:swagger-models:jar:1.5.3-M1:compile
[INFO] |  +- io.springfox:springfox-spi:jar:2.0.0-SNAPSHOT:compile
[INFO] |  |  \- io.springfox:springfox-core:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-schema:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-swagger-common:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-spring-web:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.1.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] |  +- joda-time:joda-time:jar:2.7:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
[INFO] |  \- org.springframework.hateoas:spring-hateoas:jar:0.17.0.RELEASE:compile
[INFO] |     \- org.objenesis:objenesis:jar:2.1:compile
[INFO] \- org.ajar:swagger-spring-mvc-ui:jar:0.4:compile

**Comment by dilipkrish** [comment]
Could you try with spring 4.0.9.RELEASE version and see if that fixes your problem? Could you share your repo perhaps?

**Comment by rajeshkamal** [comment]
I have shared the repo - https://github.com/rajeshkamal/spring-rest-swagger

**Comment by dilipkrish** [comment]
@rajeshkamal Thanks for catching this really hard to debug problem! Your repository was super useful in fixing the problem! :metal: 

Could you give it a shot and let me know if the 2.0.1-SNAPSHOT fixes your problem? Keep in mind that [this is incorrect](https://github.com/rajeshkamal/spring-rest-swagger/blob/master/spring-rest-service/src/main/java/com/acme/spring/rest/bundle/SwaggerConfig.java#L48) unless you plan on having a documentation format you plan to generate on your own. It should be [one of these 3](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/DocumentationType.java#L26-L28)

**Comment by rajeshkamal** [comment]
I will try with 2.0.1-SNAPHOT and post the updates. I din't know that the documentation type should be one of those. Will probably be changing it to SWAGGER_2.

But for educational purposes, what kind of differences are there between SWAGGER_2 and SPRING_WEB. I can understand spec changes between SWAGGER_2 and SWAGGER_12.
