### ISSUE TITLE
required="true" on a String parameter causes enum to be set in swagger schema

### ISSUE THREAD

**Issue by dev-d** [springfox/springfox#705]
Hi,

If I add the following code in a Java Model:

```
@ApiModel
public class SomeModel{
     @ApiModelProperty(required = true)
      private String fooBar;
}
```
Then I get the following Model:

```
"SomeModel": {
                        "description": "",
                        "id": "SomeModel",
                        "properties": {
                            "fooBar": {
                                "enum": [],
                                "required": true,
                                "type": "string"
                            }
                        "subTypes": []
                    }
```
The extra "enum" is incorrect and should not be there.

I'm using version 1.0.2 on swagger-springmvc

**Comment by dilipkrish** [comment]
@dev-d Its quite possible this is a bug with the way your ObjectMapper is set up. We're going to be releasing 2.0 soon, which has this bug fixed. So I'd recommend migrating to 2.0

**Comment by hestad** [comment]
@dev-d 2.0.0 is released. Is this working for you here? Can the issue be closed?

**Comment by dilipkrish** [comment]
Closing this issue as its against 1.0.2. Please migrate to 2.0
