### ISSUE TITLE
Post release tasks

### ISSUE THREAD

**Issue by adrianbk** [springfox/springfox#708]
Some observations/tasks after the new release process.
 
- Document add a `--stacktrace` to the release related tasks
- Asciidoctor task can result in a Permgen
- The publish documentation task changes users git config username and email address (springfox bot) 
- Document how sem versions and that version.properties file is always production version
- Clean up the SoftwareVersion subclasses and decorators - do decorators even make sense here
- Move the release stuff out to a separate Gradle plugin

**Comment by hestad** [comment]
* Move the 2.0.0 documentation to springfox/springfox and refer to the 1.0.2 documentation.

**Comment by dilipkrish** [comment]
@adrianbk Closing this as most of this is done and its hanging out forever. Reopen or create a separate story for moving the release stuff to a gradle plugin (or use the nebula release plugin)? I kinda don't want to touch this well oiled machine :)

**Comment by adrianbk** [comment]
:+1:
