### ISSUE TITLE
springfox-swagger2:2.0.0: default implementation via SwaggerCommonConfiguration

### ISSUE THREAD

**Issue by pragnyap** [springfox/springfox#709]
Hi,
Initially I was trying to use swagger-springmvc 0.5.2 to expose my rest services via swagger ui.
I was successful in  integrating it with my spring app on top of my servlet, but it failed to generate any model schema for methods taking object type parameters.(Not sure of the purpose of @ApiModel). 
I moved to springfox (Got to know that swagger-springmvc has moved to springfox). I tried following this : http://springfox.github.io/springfox/docs/current/
details of my project:
my dependency:
compile  'io.springfox:springfox-swagger2:2.0.0'
In applicationContext.xml I added the bean 
<context:component-scan base-package="path.to.mypackage" />
<mvc:annotation-driven/>
<bean class="springfox.documentation.swagger.configuration.SwaggerCommonConfiguration" />
Am getting below error in my tomcat logs:
==============================================================
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiModelBuilder' defined in URL [jar:file:/codemill/pandapra/tomcat/apache-tomcat-7.0.57/webapps/ROOT/WEB-INF/lib/springfox-swagger-common-2.0.0.jar!/springfox/documentation/swagger/schema/ApiModelBuilder.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.fasterxml.classmate.TypeResolver]: : No qualifying bean of type [com.fasterxml.classmate.TypeResolver] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.fasterxml.classmate.TypeResolver] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:747)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1115)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:706)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4994)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5492)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1245)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1895)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.fasterxml.classmate.TypeResolver] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1118)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:967)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:862)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:811)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:739)
        ... 28 more
========================================================
I am not sure what am i missing. 
Any pointers will be useful.

Thanks,
Pragnya

**Comment by pragnyap** [comment]
This is the content of my applicationContext.xml:
<context:component-scan base-package="path.to.mypackage" />
<mvc:annotation-driven/>
<bean class="springfox.documentation.swagger.configuration.SwaggerCommonConfiguration" />

Please let me know if I should follow any other approach.
Basically my requirement is to expose my rest services via swagger ui so that users can easily interact with the services.

**Comment by dilipkrish** [comment]
@pragnyap 0.5.2 is a *VERY OLD* version! You'd be better off at least moving 1.0.2, but if you want swagger 2.0 support you should consider moving to 2.0. 

This is the [documentation](https://github.com/springfox/springfox/blob/pre-2.0/README.md) for the 1.0.2 version to setup your application with springfox. To transition from 1.0.2 to 2.0 we have another document that [explains the changes](https://github.com/springfox/springfox/blob/master/docs/transitioning-to-v2.md).

We are still chipping away at making the documentation great! In the mean while there are some [great demos for 1.0.2](https://github.com/adrianbk/swagger-springmvc-demo) and the [new version has some great demos](https://github.com/springfox/springfox-demos) as well.

If all of that still doesn't work, we're available on [Gitter](https://gitter.im/springfox/springfox) to answer any questions you might have.

**Comment by pragnyap** [comment]
I followed 1.0.2 documentation. I suppose using SpringSwaggerConfig bean we can get the default behavior .
my dependencies:
compile  'com.mangofactory:swagger-springmvc:1.0.2'
compile  'com.fasterxml.jackson.core:jackson-databind:2.2.4'
compile  'com.google.guava:guava:18.0'

(Not sure if guava:18 is a required dependency then why does swagger-springmvc has guava 15)
|    \--- com.mangofactory:swagger-models:1.0.2
|         +--- com.wordnik:swagger-annotations:1.3.11
|         +--- com.google.guava:guava:15.0
|         +--- com.fasterxml:classmate:1.1.0
|         +--- org.slf4j:slf4j-api:1.7.7
|         +--- joda-time:joda-time:2.5
|         +--- org.springframework:spring-web:3.2.9.RELEASE (*)
|         \--- org.springframework:spring-webmvc:3.2.9.RELEASE (*)

my applicationContext has this bean initialized:
com.mangofactory.swagger.configuration.SpringSwaggerConfig

still my api-docs page says requested resource is not available.

Any trivial thing that I am missing??

**Comment by dilipkrish** [comment]
can you share your applicationContext? That doesnt look right, where are you including the ```@EnableSwagger``` annotation?. Using the [markdown syntax](https://guides.github.com/features/mastering-markdown/) will preserve xml. 

Anyways try this

create at bean
```java
@Configuration
@EnableWebMvc
@EnableSwagger
@ComponentScan("your packages etc.")
public class YourAppConfig {
 ...
}
```

Instead of including ```com.mangofactory.swagger.configuration.SpringSwaggerConfig``` in your applicationContext, define your ```YourAppConfig``` bean instead.

**Comment by pragnyap** [comment]
Just to clarify,
Even without defining our own Config we can get atleast the documentation page right this is what your documentation page says.

To get the default implementation simply define a bean of type: springfox.documentation.swagger.configuration.SpringSwaggerConfig

The generated swagger json Resource Listing is available at /api-docs

**Comment by dilipkrish** [comment]
You're right, it should just work. :confused:

**Comment by pragnyap** [comment]
I tried creating my own config, Pasting the error here:

SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.sample.service.MySwaggerConfig#0': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void com.sample.service.MySwaggerConfig.setSpringSwaggerConfig(com.mangofactory.swagger.configuration.SpringSwaggerConfig); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.mangofactory.swagger.configuration.SpringSwaggerConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.List com.mangofactory.swagger.configuration.SpringSwaggerConfig.handlerMappings; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerMapping()] threw exception; nested exception is java.lang.ClassCastException: org.springframework.web.accept.ContentNegotiationManagerFactoryBean$$EnhancerByCGLIB$$c55fcc7c cannot be cast to org.springframework.web.accept.ContentNegotiationManager

This is my **applicationContext.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:aop="http://www.springframework.org/schema/aop"
    xmlns:context="http://www.springframework.org/schema/context"
    xmlns:mvc="http://www.springframework.org/schema/mvc"
    xsi:schemaLocation=
       "http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/mvc 
        http://www.springframework.org/schema/mvc/spring-mvc.xsd
        http://www.springframework.org/schema/aop
        http://www.springframework.org/schema/aop/spring-aop.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context.xsd">
<mvc:annotation-driven/>
 <bean class="com.sample.service.MySwaggerConfig" />
 <context:annotation-config />
</beans>
```

MySwaggerConfig.java:
package com.sample.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ComponentScan;
import com.mangofactory.swagger.configuration.SpringSwaggerConfig;
import com.mangofactory.swagger.plugin.EnableSwagger;
import com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

@Configuration
@EnableWebMvc
@EnableSwagger
@ComponentScan(basePackages = "com.sample.service")
public class MySwaggerConfig {

        private SpringSwaggerConfig springSwaggerConfig;

        @Autowired
        public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
                this.springSwaggerConfig = springSwaggerConfig;
        }

        @Bean
        public SwaggerSpringMvcPlugin customImplementation() {
                return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).includePatterns(".*documentations.*");
        }
}

**Comment by dilipkrish** [comment]
I don think you need the ``` <context:annotation-config />```. Also what is the intent behind ```includePatterns(".*documentations.*")```. What that does is it will only document controllers that have documentation in the path. Don't believe that was the intention, was it?

**Comment by pragnyap** [comment]
Yes that's intentional as I have my servlet in web.xml that follows a different route so I wanted my documentation url to have a different route.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app id="sample_app" version="2.4" xmlns="http://java.sun.com/xml/ns/j2ee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:context="http://www.springframework.org/schema/context"
    xsi:schemaLocation=
          "/WEB-INF/lib/servlet-api.jar!/javax/servlet/resources/web-app_2_4.xsd
           http://www.springframework.org/schema/context
           ttp://www.springframework.org/schema/context/spring-context.xsd">
    <display-name>Sample Web Application</display-name>
    <description>Sample Web Application</description>

    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
            <!-- NOTE: Bring in services and other beans definitions -->
            /WEB-INF/classes/cfg/com/sample/applicationContext.xml
        </param-value>
    </context-param>

    <listener>
            <listener-class>
                        org.springframework.web.context.ContextLoaderListener
            </listener-class>
    </listener>

    <listener>
            <listener-class>   
                     org.springframework.web.context.request.RequestContextListener
            </listener-class>
    </listener>

<servlet>
            <servlet-name>spring-servlet</servlet-name>
            <servlet-class>
org.springframework.web.servlet.DispatcherServlet</servlet-class>
            <init-param>
              <param-name>contextConfigLocation</param-name>
              <param-value>/WEB
INF/classes/cfg/com/sample/applicationContext.xml</param-value>
            </init-param>
            <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
            <servlet-name>spring-servlet</servlet-name>
                    <url-pattern>/documentations/*</url-pattern>
                        </servlet-mapping>
<servlet>
        <servlet-name>remoting</servlet-name>
        <servlet-class>com.framework.web.RemotingServlet</servlet-class>
        <load-on-startup>2</load-on-startup>
    </servlet>
    <servlet-mapping>
      <servlet-name>remoting</servlet-name>
      <url-pattern>/service/*</url-pattern>
   </servlet-mapping>
   <servlet-mapping>
</web-app>
```

**Comment by pragnyap** [comment]
After removing ```xml <context:annotation-config />```  I am able to start my app but the page ```<myserver>:<myport>/api-docs``` is just empty. What I expect is that atleast it should show the swagger version (It was the case with 0.5.2 swagger-springmvc) , so that atleast it will be confirmed that my app is up with swagger.

**Comment by dilipkrish** [comment]
@pragnyap Unfortunately, I'm not really sure how well 1.0.2 supported dynamic servlet mappings. You might try overriding the path provider in ```SwaggerSpringMvcPlugin.pathProvider(myPathProvider)``` with a new instance of ```RelativePathProvider```, only difference being you set the apiResourcePrefix to */documentations* using the  ```setApiResourcePrefix```. See if that works for you. 

In anycase this is not a supported version of the library; by that I mean we won't be making an more incremental updates to this version. We might entertain a bug or two that are critical, but the chances of that are fairly remote; not because of anything, other than we don't have the bandwidth to support 2 concurrent versions. I'd strongly recommend moving towards 2.0.0 which has been released.

**Comment by pragnyap** [comment]
@dilipkrish  Please correct me if I am wrong, but I feel this is not an issue with dynamic servlet mappings. I feel the issue is with some wrong configuration.

If you see my custom swaggerConfig class:

@Configuration
@EnableWebMvc
@EnableSwagger
@ComponentScan(basePackages = {"com.sample.service"})
public class MySwaggerConfig {

        private SpringSwaggerConfig springSwaggerConfig;

        private ServletContext servletContext;

        @Autowired
        public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
                this.springSwaggerConfig = springSwaggerConfig;
        }

        @Bean
        public SwaggerSpringMvcPlugin customImplementation() {
                RelativeSwaggerPathProvider relativeSwaggerPathProvider = new RelativeSwaggerPathProvider(servletContext);
                relativeSwaggerPathProvider.setApiResourcePrefix("documentations");
                
                return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).pathProvider(relativeSwaggerPathProvider).includePatterns(".*documentations.*");
        }
}

AS SpringSwaggerConfig is autowired I need to define that bean and also use annotation-config so that these annotations can be picked .

My applicationContext:
```xml
<mvc:annotation-driven/>
    <context:component-scan base-package="com.sample.service"/>
    <context:annotation-config />
    <bean class="com.mangofactory.swagger.configuration.SpringSwaggerConfig" />
```
annotation-config is required because I have autowired SpringSwaggerConfig.

With this setup I get below error:

SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mySwaggerConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void com.sample.service.MySwaggerConfig.setSpringSwaggerConfig(com.mangofactory.swagger.configuration.SpringSwaggerConfig); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.mangofactory.swagger.configuration.SpringSwaggerConfig#0': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.List com.mangofactory.swagger.configuration.SpringSwaggerConfig.handlerMappings; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerMapping()] threw exception; nested exception is java.lang.ClassCastException: org.springframework.web.accept.ContentNegotiationManagerFactoryBean$$EnhancerByCGLIB$$f30594a7 cannot be cast to org.springframework.web.accept.ContentNegotiationManager

I feel the problem is with the configuration , please if you can suggest me anything.

**Comment by dilipkrish** [comment]
I think your application context should be this instead

```xml
<mvc:annotation-driven/>
    <context:component-scan base-package="com.sample.service"/>
    <context:annotation-config />
    <bean class="your.package.goes.here.MySwaggerConfig" />
```

There is nothing pulling in that configuration bean. Also I dont think you need ``context:*```. I'd suggest moving the component scan to ```MySwaggerConfig``` and removing the annotation config.

**Comment by dilipkrish** [comment]
@pragnyap i suspect your issue is resolved. closing this issue. Please reopen if its not resolved

**Comment by pragnyap** [comment]
Hi @dilipkrish ,

I am again in trouble here so seeking help :( 
I am able to have a sample api using swagger 1, Now I am trying to explore swagger 2

My dependency in gradle:
``` compile 'io.springfox:springfox-swagger2:2.0.3' ``` 

Configuration class:
```xml
@EnableSwagger2
@Configuration
@ComponentScan(basePackageClasses = {
    SampleService.class
})
public class SwaggerConfig {

  public static void main(String[] args) {
        ApplicationContext ctx = SpringApplication.run(SwaggerConfig.class, args);
  }
   
    @Bean
    public Docket petApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("sample-api")
                .apiInfo(apiInfo())
                .select()
                .paths(paths())
                .build();
    }
 
    private Predicate<String> paths() {
    return (
        regex("/sample.*"));
    }

```
My SampleService class:

```xml
@Controller
@RequestMapping(value = "/api/sample")
@Api(value = "/sample", description = "Operations in sample service")
public class SampleService {
 
  @ApiOperation(value = "This is a sample service")
  @RequestMapping(value = "/sample", method = GET)
  @ResponseBody
  public String viewGet(@PathVariable("someIntParam") int id, @PathVariable("someStringParam") String name) {
    return "found";
  }

  @RequestMapping(value = { "/sample" }, method = POST, consumes = APPLICATION_JSON_VALUE,
            produces = APPLICATION_JSON_VALUE)
    @ResponseBody
    public TestModel playWithModel(@RequestBody TestModel model) {
        return model;
    }

  
}
```

My instance is coming up but I am not able to see anthing on swagger-ui.
Basically ``` <myhost>:<myport>/v2/api-docs/``` returns an empty page.

Any obvious thing that I am missing?? Can yoy point me to a good documentation, the one you gave is not very self descriptive.

Thank you,
Pragnya

**Comment by dilipkrish** [comment]
@pragnyap as [described here](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints) you need to change your url to `<myhost>:<myport>/v2/api-docs?group=sample-api` to get to your api-docs.

Also you theres a ton of documentation in http://springfox.io

**Comment by pragnyap** [comment]
@dilipkrish 
Yes It worked, thanks. I am now able to have my own servlet along with mvc-dispatcher-servlet.
The issue is,  from swagger-ui I want to redirect calls to my servlet. But even for get calls It does not append the parameters at the end.

I want something like  ``` <myhost>:<myport>/service/sampleService/viewGet?id=10&name=ppp``` 

But the UI creates ``` <myhost>:<myport>/service/sampleService/viewGet```  and with this format my call fails.

Here is my Sample code:
``` 
@Controller
@RequestMapping(value = "/service/sampleService")
@Api(value = "/sample", description = "Operations in sample service")
public class SampleService {

  @ApiOperation(value = "This is a sample service")
  @RequestMapping(value = "/viewGet", method = GET)
  @ResponseBody
  public String viewGet(@PathVariable("someIntParam") @RequestParam("id") int id, @PathVariable("someStringParam") @RequestParam("name") String name) {
    return "found"; 
  }}
``` 
Please Can you help me here!!

**Comment by pragnyap** [comment]
What I see from my last swagger integration(swagger-springmvc 0.5.2) with my servlet. In the UI the Parameter Type for these parameters were query, and it was generating the url correctly (Appending parameters). 
In the latest swagger 2 , The parameter Type is Path. Is this a reason??
How Can I configure it to take the parameters in the URL??

**Comment by dilipkrish** [comment]
Not sure why you have `@PathVariable("someIntParam") @RequestParam("id")` together? they are mutually exclusive. If something is in the path it cannot be in the query string and vice versa. Secondly if you did intend to have the path variable to be there your request mapping would've looked like this

`@RequestMapping(value = "/viewGet/{someIntParam}/{someStringParam}", method = GET)`

So not really sure what you're trying to do here

**Comment by pragnyap** [comment]
Yes got you. Thanks . 
One last question, With Swagger-ui , if my parameter is a model object then do I need to pass the json string of it, I mean is there a way that I can pass directly the field values. (Like form fields and internally it will take care of constructing my model objects).
![swagger](https://cloud.githubusercontent.com/assets/12109167/8893053/86b77252-339c-11e5-8d9a-b1b52829c6d4.png)

Attaching the screenshot here.

**Comment by pragnyap** [comment]
@dilipkrish  Sorry if I am troubling you, but I seriously need your help here.

As far I understood at runtime all the swagger annotations and spring annotations are read and
dispatcher servlet (based on @Controller and @RequestMapping) dispatches request to swagger-ui ,based on the request mapping. 

So currently my Api looks like this:

``` 
@Controller("sampleService")
@RequestMapping(value = "/service/sampleService")
@Api(value = "/sample", description = "Operations in sample service")
public class SampleServiceImpl implements SampleService {

  @ApiOperation(value = "This is a sample service")
  @RequestMapping(value = "/viewGet", method = GET)
  @ResponseBody
  public String viewGet(@RequestParam("id") int id, @RequestParam("name") String name) {
    return "found";
  }

  @RequestMapping(value = { "/playWithModel" }, method = POST, consumes = APPLICATION_JSON_VALUE,
            produces = APPLICATION_JSON_VALUE)
    @ResponseBody
    public TestModel playWithModel(@RequestBody TestModel model) {
        return model;
    }
}

``` 

My only concern is I dont want to annotate my APi with these many annotations.
I want to take care of generating my own apidocs(We have the infra that reads our apis already)  and I just want Swagger-ui to read those pregenerated docs. Is there a way to do this, I suppose in that way I can avoid annotating my classes. 

One more question, Is there a way where I can avoid all these spring annotations as well (Like Controllers and RequestMapping). We are using xml to define our beans.
Any pointers will be useful. 

Thanks..

**Comment by dilipkrish** [comment]
@pragnyap If you already have infrastructure to pre-generate the docs then you don't need this library!!!

All you need to do is to have an application that can serve swagger-ui (either a node-js server that can serve swagger-ui or may be a tomcat instance that has swagger-ui static resources; MANY options there) and then you can point it to your pre-generated api-docs like below.

![swagger_ui](https://cloud.githubusercontent.com/assets/73257/9287176/3262a942-42ce-11e5-88ec-1fda214e7cf5.jpg)

**Comment by pragnyap** [comment]
@dilipkrish 

Pointing swagger-ui to generated swagger.json is not an option, we want to use springfox as such but without modifying the service code (ie, without introducing any new annotations).

I have successfully eliminated the need of Controller and RequestMapping annotations by registering the mapping on the fly using springs registerMapping method(spring 4.2.1).

I am currently stuck at the RequestBody annotation. It looks like swagger uses this annotation to display the schema of method parameters [Ex: public void testModel(ModelObject m) ]. I want to get the same behavior without using any annotations explicitly.

As per my understanding, RequestBody registers some messageConverters for http serialization and deserailization. I am trying to get the same behavior at code level that swagger in turn can use to display the schema in the UI.

Please provide some guidance on this. Any related examples/documentation will be helpful.

On the same note,
I understand that swagger annotations like @Api and @ApiOperations sets some properties internally. Is there a way to set those properties and avoid using these annotations at code level ?

Thanks ,
Pragnya

**Comment by dilipkrish** [comment]
Can I ask why u are trying to build your services with no spring annotations? I can understand no swagger annotations but no spring annotations as well??!! It seems like you'll be fighting against the grain all the way. 

In any case, i don't really know the answer to your question. Would be worth asking in the spring forums.

**Comment by pragnyap** [comment]
@dilipkrish 

Thanks for responding.
>> Can I ask why u are trying to build your services with no spring annotations? 
We distribute a jar similar to codegen  and we have our own custom annotations . On top of it we don't want our users to add any extra annotations. This swagger support should happen under the hood using our custom annotations. 

If spring annotations are unavoidable can you please tell me a way how can I avoid using Swagger annotations and get the same behavior. Probably a list of Properties that swagger is setting via these annotations(@Api/@ApiOperation) and a way to custom set them will solve my problem.

Thanks.
Pragnya

**Comment by dilipkrish** [comment]
For one you won't ever need to use swagger annotations. 

Could you elaborate on the "distributing a jar" piece.  It's still not clear to me what ur trying to do

**Comment by pragnyap** [comment]
We need to use swagger annotations because we need to see the api documentations in the swagger UI.

By distributing a jar I meant, we have our own  framework jar which can  be used to expose services restfully . We want to use swagger-UI to generate UI and documentations for these services . In this process we don't want to use any extra annotations apart from the existing ones.

Under the hood we want our framework to generate all the intermediate things required by your springfox-swagger UI jar basically the spring annotations and swagger annotations. 

So wondering if you can guide me here:
Avoid using Swagger annotations and get the same behavior in the UI (Like the description of the API and ApiOperations)

**Comment by dilipkrish** [comment]
You don't have to use any of the swagger annotations to document your Api. Just spring mvc alone should be enough.

Your explanation still isn't clear to me about the jar. From what I understand u have a jar that has _____ (what?) service interface? Implementation?. What does the jar do? It's not clear how u can distribute a reusable service. 

Also I thought u weren't using springfox based on earlier conversations. What in springfox are you using? And why?


May be you can share an repo with what your trying to do?

**Comment by pragnyap** [comment]
Hi @dilipkrish,

>>You don't have to use any of the swagger annotations to document your Api. Just spring mvc alone should be enough.

If, by documenting your Api, you mean getting listed it on UI, then yes I agree I need only spring annotations like Controller and RequestMapping. My requirement is along with this, I also want to have some information[API Documentation] about the method and method parameters on the UI itself ( The one we can achieve using @ApiOperation and @ApiParam). 

In the ```Expand Operations```  column you can see the description[API Documentation], I want the same behavior without annotating my code.

![image](https://cloud.githubusercontent.com/assets/12109167/9756936/399b5344-56fb-11e5-85bb-73b28f26c6d9.png)

>> Also I thought u weren't using springfox based on earlier conversations. What in springfox are you using? And why?

Earlier, I thought of generating my own json and feed it to swagger-ui, but that did not seem natural. So now I am trying to use springfox jars to generate the json and feed the same to swagger-ui for my services, which seems more natural. 
>> May be you can share an repo with what your trying to do?

I am afraid this is an in-house tool and i cannot share the same. Although, what I can say is,  we have a framework where you just need a single annotation[@MyService(description="My Sample Service",....)] on top of your Service Interface and it will take care of exposing that service restfully.  So, along with this framework, I don't want to introduce any new annotations and hence <b>i need a way to set these annotations on the fly without actually modifying my code</b>

I have achieved the same for Spring annotations [@Controller, @RequestMapping] using registerMapping method, however I am not sure how can I do the same for Swagger annotations [@ApiOperation, @ApiParam]. Repeating myself, "Probably a list of Properties that swagger is setting via these annotations(@Api/@ApiOperation) and a way to custom set them will solve my problem".

Thanks,
Pragnya
