### ISSUE TITLE
Offline generation?

### ISSUE THREAD

**Issue by thomaschristensen** [springfox/springfox#71]
Is there a requirement for the spec files to be generated at runtime rather than at compile time?

We are trying to minimise the jar files used in our apps and can see that swagger brings in a number of libs that could be avoided if a doclet generated the api-docs files. The api does not change at runtime AFAIK.

**Comment by robert-morschel** [comment]
Hi,

we follow the doclet approach with the IG RESTdoclet plugin, so it is feasible.  In general, I think a build time generation of the schema (including javadoc comments) would be a good feature.

Regards,
Robert

**Comment by dilipkrish** [comment]
Have you looked at the [maven plugin](https://github.com/kongchen/swagger-maven-plugin)
