### ISSUE TITLE
Is there a public maven location for the released version?

### ISSUE THREAD

**Issue by frkline** [springfox/springfox#710]
Didn't see anything in maven central or http://oss.jfrog.org/simple/oss-release-local/io/springfox/

**Comment by dilipkrish** [comment]
@adrianbk  I think collapsing the jars into on logical repo is causing issues syncing with maven central.[io_springfox_springfox-core_at_springfox_maven-repo](https://cloud.githubusercontent.com/assets/73257/7357864/39f326f0-ecf7-11e4-914d-633bf261fa47.jpg)

**Comment by adrianbk** [comment]
The repositories are listed on the reference documentation: http://springfox.github.io/springfox/docs/current/#dependencies

At the time we published 2.0.0 bintray wasn't configured to automatically sign the artifacts. it is now and subsequent releases can be synced to maven central.

**Comment by dilipkrish** [comment]
@adrianbk should we plan on releasing a 2.0.1 patch? I can fix a couple of low hanging bugs perhaps

**Comment by adrianbk** [comment]
Sure thing, lets get in touch before we release tho - I want to double check all the config on the Bintray side.

**Comment by dilipkrish** [comment]
I'll leave it to the experts :) Will it work if I let you know when I've finished up, so you can release?

**Comment by adrianbk** [comment]
No expert - I'm chancing my arm :)

Cool, let me know.

**Comment by marek-z** [comment]
Hello Guys, 
Regarding maven central repository - would it be possible to fix this issue with syncing, so 2.0.0 release would be available on central repo?
I would like to use springfox in one project which allows only internal nexus usage, where bintray repository is not mirrored...

**Comment by cternes** [comment]
Please consider releasing into maven central. No one likes it to configure custom repositories in their projects.

**Comment by dilipkrish** [comment]
Should be pushed over the weekend when we do the 2.0.1 release

**Comment by dilipkrish** [comment]
Closing this as its now been pushed
