### ISSUE TITLE
Support for multiple request/response models based on different query string parameters and also accept headers

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#711]
It should be perfectly legal to have two operations

- /pet/{id} which produces application/json implemented by a getPet()
- /pet/{id} which produces application/pdf implemented by a getPetDocument()

And instead of producing two different Path.gets in the new terminology, it should collapse the two into one operation with produces = [ 'application/json', 'application/pdf' ]. Its a totally different matter altogether what the resulting operationId should be :)

This is related to https://github.com/swagger-api/swagger-core/issues/935

**Comment by RobWin** [comment]
@dilipkrish +1. I would need this feature. At the moment springfox just discards one method and shows only one of them. 
But be aware that you can't collapse them easily, because they could have different return types.

For example, one operation could return just a String and another a JSON or XML response.

```
@ApiOperation(value = "Export all contacts as embedded CSV")
@RequestMapping(value="/csv", method = RequestMethod.GET, produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
public CsvContactsResponse exportAllContactsAsEmbeddedCsv()  {
        ...
}

@ApiOperation(value = "Export all contacts as CSV")
@RequestMapping(value="/csv", method = RequestMethod.GET, produces = "text/csv")
public String exportAllContactsAsCsv() {
       ...
}
```

**Comment by kevinconaway** [comment]
Will this be fixed?  We would like to implement an API with media type versioning.  See the following below:

```java
@Controller
@RequestMapping(value = "/api/service")
public class DemoController {

    @ApiOperation(value="Test v1")
    @RequestMapping(value = "/test", produces = "application/vnd.mycompany.v1+json", method = RequestMethod.GET)
    public String getV1() {
        return "v1";
    }

    @ApiOperation(value="Test v2")
    @RequestMapping(value = "/test", produces = {"application/vnd.mycompany+json", "application/vnd.mycompany.v2+json"}, method = RequestMethod.GET)
    public String getV2() {
        return "v2";
    }

}
```
In the above case, there are two methods mapped to `GET /api/service/test` with the media type differentiating between the two.

**Comment by orbfish** [comment]
"At the moment springfox just discards one method and shows only one of them."

It would be great if it consistently chose the first or the last method. I tried both and it kept changing whether or not it would respond to the annotations. That would mean the annotations would not have to be cut-and-pasted on the top of each method.
