### ISSUE TITLE
Swagger UI page with operations open: browser page refresh opens Swagger Petstore operations

### ISSUE THREAD

**Issue by keesvandieren** [springfox/springfox#713]
We have integrated Springfox 2.0 and Swagger in our application.

When opening a rest operation, url changes from http://localhost:8099/rest/swagger-ui.html to http://localhost:8099/rest/swagger-ui.html#!/helloworld/sayHelloUsingGET

When pressing CTRL+F5 in the browser, the Swagger Petstore operations are shown, instead of our own operations.

Created a small project that reproduces this problem: https://bitbucket.org/squins/springmvc-swagger-issues

**Comment by dilipkrish** [comment]
@keesvandieren thanks for reporting! I verified its a bug!

**Comment by birajchoudhury** [comment]
waiting for fix on this pet-store issue, this is really a stopper. Please try and fix it on priority.

**Comment by birajchoudhury** [comment]
@dilipkrish  -0 Now it shows Petstore all the time.

**Comment by keesvandieren** [comment]
IMO the reference to the petstore demo should be removed from the library. It is okay to have a demo project with it, but having references to the Pestore in the framework itself is something that should not be there.

**Comment by dilipkrish** [comment]
Its used for the contract tests, to ensure the generated contracts are conforming to the spec. None of those artifacts are released anyways. Once the library stabilizes there will be a lot of reorganizing for sure.
