### ISSUE TITLE
How could this work with Jersey2 ?

### ISSUE THREAD

**Issue by schmitch** [springfox/springfox#722]
Hello, I currently trying to get spring-boot, swagger and jersey2 working together, howerver, Api and ApiOperation won't get picked up if I only have a Jersey2 Resource where I annotate my class / function.

**Comment by dilipkrish** [comment]
Not very familiar with jersey2, do you have a repo what we could collaborate on to perhaps help create a *getting started* guide?

**Comment by schmitch** [comment]
Here is a demo repository:
https://github.com/schmitch/spring-boot-jersey2-demo

Currently you just need to run the Application.class. Also swagger is at /v2/api-docs and swagger-ui is just /swagger-ui.html.

**Comment by dilipkrish** [comment]
@schmitch Seems like we need a way to adapt jersey endpoints to spring's request mappings. Do you know how to get access to that endpoint information from the ResourceConfig?

**Comment by schmitch** [comment]
I don't think that spring uses request mappings to map to jersey2 resources.
Spring will publish a own Servlet which is mainly for Jersey2, thats why you need ```@ApplicationPath("anything")``` else it will use the default ApplicationPath of "" which will overwrite every other RequestMapping or custom Bean of Spring. If i don't use ApplicationPath my swagger-ui isn't accessible and swagger-docs, too.

I think the good way to implement that into springfox would be adding something that also scans for resources, since Swagger has native Jersey2 integration.

**Comment by dilipkrish** [comment]
The layer that we've built springfox on top off is the idea of `RequestMapping`s. So I'm trying to see how we could infer the `RequestMapping`'s for a `jersey` based service. We see that this is going to be needed if we are to support `spring-integration` and `spring-data-rest` applications as well. So it would be super useful if you had any ideas on how to adapt the jersey controllers to request mappings. For eg. is there a way to interrogate the ResourceConfig about the services registered etc.?

I know swagger-core already supports this integration, is it because of spring boot that you're pursuing documenting using springfox?

**Comment by schmitch** [comment]
Currently ResourceConfig has a method called "getClasses" which will list everything registerted. like Resources, Filters,etc...
Maybe this could help.
But be aware that the returning classes could also be filters or any other stuff you could register with jersey2.


Yeah it's cause of spring-boot. I mean it is really horrible to do this stuff by ourself and springfox is making swagger way easier, especially in spring boot.

**Comment by dilipkrish** [comment]
@schmitch would you like to help with creating the adapter? I'm out of my depths with the way jersey works

**Comment by eyaqub** [comment]
any update on springfox and jersey interoperability for springboot apps?

**Comment by senyor** [comment]
Please see my answer:
[http://stackoverflow.com/questions/37640863/springfox-swagger-no-api-docs-with-spring-boot-jersey-and-gardle/42228055#42228055](url)

**Comment by dilipkrish** [comment]
@senyor So you've got it working with a jersey application?

**Comment by senyor** [comment]
Yes, I've just configured both Springfox Swagger an Jersey Swagger bindings independently and added parameter for endpointV2 to tell swagger-ui from Springfox where to get swagger.json generated by Jersey from and it worked.

**Comment by senyor** [comment]
I also would be nice to have Jersey and Spring REST work together as springboot actuator has endpoints to check health and metrics.
