### ISSUE TITLE
ApiListingScanner doesn't work correctly for 2 ResourceGroups with the same name

### ISSUE THREAD

**Issue by dplacinta** [springfox/springfox#727]
I'm using the 2.0.1-SNAPSHOT, but this is also the case for 2.0.0. The issue I'm having is that if the same @Api("api_name") annotation is used in 2 different classes, only one of them will be picked up. The desired result, however, is that all the methods in both classes be listed under the same resource group. This is true across different ResourceGroupingStrategy implementations (I have a custom one that groups by request mapping).
The problem is in ApiListingscanner.java:114
```java
apiListingMap.put(resourceGroup.getGroupName(), pluginsManager.apiListing(apiListingContext));
```
Because put is used, the previously existing group will be overridden by the latest one.

**Comment by dilipkrish** [comment]
Thanks for reporting! :+1:

**Comment by dilipkrish** [comment]
@dplacinta give it a shot and let us know if its fixed for swagger spec 2.0.

**Comment by dplacinta** [comment]
Hi @dilipkrish , unfortunately this is not fixed. And from the 2ff2dcb check in, but maybe I'm missing the big picture here.
So, as stated before, my problem is located at ApiListingScanner.java:113 (in the latest shapshot version, whidh today is 2.0.1-20150506.053232-13):
```java
apiListingMap.put(resourceGroup.getGroupName(), pluginsManager.apiListing(apiListingContext));
```

The resource listing I have is the following:
```java
2015-05-06 09:27:32.834  INFO 4492 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Created resource listing Path: /default/audiences Description: /audiences Position: 2147483647
2015-05-06 09:27:32.838  INFO 4492 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Created resource listing Path: /default/audiences Description: /audiences Position: 2147483647
```
that is 2 different controllers that map to the same request path (one is for listing all the audiences on GET, the other contains the CRUD operations for a single audience)
In the resulting swagger 2.0 JSON I only get the operations from the first group, not their reunion.
The fix, I imagine would be to merge the API listings if they have the same group name, but that's beyond my knowledge of the springfox framework.

**Comment by dilipkrish** [comment]
Thats what this fix does, changed the map to be a multi map so the api listing scanner should not be overwriting any of the scanned api listings.

**Comment by dplacinta** [comment]
I've just debugged it, and when the execution reaches the apiListingMap.put statement, I still have 2 groups with the same name, and obviously one overrides the other. Any suggested workaround?

**Comment by dplacinta** [comment]
Sorry man, my bad. Looks I haven't cleared the cache entirely. Yes, it is working, and I can see all of the operations, the multimap values are also there.
Great work and I'm pleasantly surprise by the speed of the fix. Thanks a bunch, that was the last blocker to using the springfox library in our project.
