### ISSUE TITLE
Api annotation value should remain as-is

### ISSUE THREAD

**Issue by RobWin** [springfox/springfox#737]
When I configure an Api annotation manually as follows:

```
@Api(value="ContactsExport")
```

It should not be reformatted to `contactsexport` in the JSON output. The camelCase should remain as-is.
The path is taken from RequestMapping anyway.  

Kind regards,
Robert

**Comment by dilipkrish** [comment]
Is this for urls or for tags that you need it to preserve case?

**Comment by RobWin** [comment]
It is for tags. URL path is fine because it comes from RequestMapping

**Comment by RobWin** [comment]
thx!
