### ISSUE TITLE
Swagger UI does not display properly under IE 11

### ISSUE THREAD

**Issue by bogdatov** [springfox/springfox#738]
I'm using IE 11 and Swagger UI does not display list of API. In Chrome everything works.
Using Spring boot and JDK 1.7

This is what I have in pom.xml: 
<repository>
			<id>jcenter-snapshots</id>
			<name>jcenter</name>
			<url>https://jcenter.bintray.com/</url>
		</repository>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.0.0</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.0.0</version>
		</dependency>

For SwaggerConfig.java I use this:
@Configuration
@EnableSwagger2
public class SwaggerConfig  {

    @Bean
    public Docket restfulApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("topology-api")
                .select()
                .build()
                .apiInfo(apiInfo());
    }

    private ApiInfo apiInfo() {

        ApiInfo apiInfo = new ApiInfo(
                "Topology",
                "Topology services: TaaS",
                "1.0",
                "Path",
                "commented",
                "Licence",
                "Licance URL"
        );
        return apiInfo;
    }
}

I'm attaching screenshots from IE11 and Chrome.
I suspect something related to this (which I do not see in your HTMLs, but not sure):
<meta http-equiv="X-UA-Compatible" content="IE=Edge" /> 

![swagger-ie11](https://cloud.githubusercontent.com/assets/3028850/7572821/0627d822-f7ef-11e4-82aa-beee80cea727.JPG)
![swagger_chrome](https://cloud.githubusercontent.com/assets/3028850/7572823/0afcfee0-f7ef-11e4-9f88-a7cd254e8088.jpg)

**Comment by dilipkrish** [comment]
What is that a javascript error you're getting in IE?

**Comment by bogdatov** [comment]
There is no javascript error visible, but when I use F12 Developer Tools I have this that SwaggerClient is underfined ( see attachement)

![swagger-ie11_errors](https://cloud.githubusercontent.com/assets/3028850/7639782/857cee32-fa4c-11e4-9f63-f67b01e205d2.JPG)

**Comment by bogdatov** [comment]
Also if I switch "Document model emulated" level from "7 - Default" to "Edge" in Developer Tools, everything starts working

**Comment by bogdatov** [comment]
Resolved by unchecking "Compatibility mode for intranet sites" in IE11 properties
