### ISSUE TITLE
List<Map<String, String>> in models not rendered correctly

### ISSUE THREAD

**Issue by nyddogghr** [springfox/springfox#740]
Hi,

I have the following issue : one of my models has an attribute `List<Map<String,String>>`.
It is rendered as 
```
items: {
$ref: "#/definitions/Map«string,string»"
}
```
in the swagger.json. The problem is that not only it is not valid, but it doesn't help at all to describe the attribute.
As seen in swagger-editor online, the problem is  *Definition could not be resolved: #/definitions/Map«string,string»*
I have looked at `alternateTypeRules` and `directModelSubstitute` when creating the docket, but I haven't found how to solve this. I've also tried `datatype` attribute for @ApiModelProperty.
Moreover, it would be perfect if I could describe it more precisely, such as 
```
[{"id":"aeiuo"}]
```
Is there any way first to fix the json ?
Also, is there anything I could do to describe more precisely this attribute ? I've already put this in the description, so this part of my issue is less important.

Thanks

**Comment by dilipkrish** [comment]
So is there a definition for `Map«string,string»` in your model definitions? I suspect this is a bug with swagger-ui/swagger-editor.

**Comment by nyddogghr** [comment]
If I understand you well, according to the issues https://github.com/swagger-api/swagger-js/issues/46 and https://github.com/swagger-api/swagger-ui/issues/558, the swagger.json generated with springfox for this attribute is correct, but swagger-ui and swagger-editor don't support it yet. So with a `List<Map<String,String>>` I am supposed to get :
```
items: {
$ref: "#/definitions/Map«string,string»"
}
```
Is it correct ?
If so, then I will wait or open issues in these projects

**Comment by dilipkrish** [comment]
This is a bug :cry:

**Comment by nyddogghr** [comment]
A bit late, but thanks :)

**Comment by riva76** [comment]
is this bug fixed? i have the same problem.
springfox generates this json

 'Map«string,object»':
    type: object
    additionalProperties:
      type: object

but into PHP client class generates with swagger editor i have all empty attributes

swaggerTypes attribute is empty

**Comment by dilipkrish** [comment]
Thats because you have a map which is an __any__ type, you can create __any__ valid json and send it along.

**Comment by charithan1** [comment]
Is this bug fixed? If yes, which version is it available?

**Comment by vpm911** [comment]
Is this bug fixed? I have a `private Map<String, Map<String, List<Thumbnail>>> thumbnails;`
 which is causing the following json to be generated 

`"MapOfstringAndListOfThumbnail": {
            "type": "object",
            "title": "MapOfstringAndListOfThumbnail",
            "additionalProperties": {
                "$ref": "#/definitions/List"
            }
        }`
and the $ref: "#definitions/List" is not present in the documentation. This is causing **Semantic error at definitions.MapOfstringAndListOfThumbnail.additionalProperties.$ref
$refs must reference a valid location in the document**
