### ISSUE TITLE
Duplicate tags when having multiple @Api annotations with the same value

### ISSUE THREAD

**Issue by dplacinta** [springfox/springfox#742]
When having more than one class that shares the same @Api annotation, the tags will be duplicated in the list of tags. Here's a sample generated with v 2.0.1-SNAPSHOT today:
```java
tags: [
   {
      name: "/activities"
   },
   {
      name: "/activities"
   }
]
```

**Comment by dilipkrish** [comment]
Something's not right for sure. It shouldn't even look like a path. Have you by any chance created a group strategy plugin?

**Comment by dplacinta** [comment]
Sorry, @dilipkrish, it's my custom GrouppingStrategy. Feel free to close this

**Comment by dilipkrish** [comment]
Closing it then 👍🏻
