### ISSUE TITLE
api-docs is missing ServletRegistrationBean

### ISSUE THREAD

**Issue by omayevskiy** [springfox/springfox#743]
given:
```
import org.springframework.boot.context.embedded.ServletRegistrationBean;

    @Bean
    public ServletRegistrationBean myservlet() {
        return new ServletRegistrationBean(
            new MyServlet(),
            "/myservlet"
        );
    }
```

api-docs is missing /myservlet

**Comment by dilipkrish** [comment]
In your ```Docket```  you have access to the ```pathMapping``` method where you can specify "/myservlet"

**Comment by omayevskiy** [comment]
did not help
here is how my Docket config looks like:

```
    @Bean
    public Docket myApi() {
        return docket().groupName("mygroup")
            .pathMapping("/myservlet");
    }

    private Docket docket() {
        return new Docket(DocumentationType.SWAGGER_2).genericModelSubstitutes(DeferredResult.class)
            .useDefaultResponseMessages(false)
            .forCodeGeneration(false);
    }
```

**Comment by dilipkrish** [comment]
Is there a reason you don't have the path mapping on the second one? the default group doesn't have the path mapping set up, which is probably why you're not seeing it.

**Comment by omayevskiy** [comment]
I don't have a "second" one, the docket() method is a helper for creating a common docket.
If i go to .../v2/api-docs?group=mygroup

then all paths are prefixed with /myservlet, which is wrong:

```
"paths": {
"/myservlet/docs/**": {
...
```

it should be like:
```
"paths": {
"/myservlet": { ...
...
"/docs/**": { ...
...
}
```

I also tried to annotation the spring bean definition with @Api and @ApiOperation, but it didn't work.

**Comment by dilipkrish** [comment]
I misunderstood your question, plus I'm not so familiar with servlet registration bean. What does your Myservlet look like? It would be easier if you shared a example repo demonstrating the problem

**Comment by omayevskiy** [comment]
created example project:
https://github.com/omayevskiy/springfox-servlet-example

**Comment by dilipkrish** [comment]
Ah I see what's going on. Seems like this is a missed feature. When u register the servlet like that (that's not brought in by the request mapping) it totally ignores it! Thanks for reporting!
