### ISSUE TITLE
ApiParam at method level

### ISSUE THREAD

**Issue by jbm4sa** [springfox/springfox#745]
Hi,
Is it possible to define the list of parameters at the method level?

At the moment my code looks like this:

```
@ApiOperation(nickname="My Method", value="My method summary", notes="My method full description")
@RequestMapping(value = "/mymethod", method = RequestMethod.GET)
@ResponseBody
public MyMethodResponse mymethod(
    @ApiParam(value="The service name on which to apply this currect method") @RequestParam String service, 
    @ApiParam(value="The init flag, if true does it right, if false does it wrong") @RequestParam(defaultValue="false") boolean init) {
		
		....

	}
```
As you can see the ApiParam annotation is making the code less readable.

I was therefore wondering if it would be possible to move them above the method and link them with the name attribute or some other attributes, so that it would look like this:

```
@ApiOperation(nickname="My Method", value="My method summary", notes="My method full description")
@ApiParam(name="service", value="The service name on which to apply this currect method") 
@ApiParam(name="init", value="The init flag, if true does it right, if false does it wrong") 
@RequestMapping(value = "/mymethod", method = RequestMethod.GET)
@ResponseBody
public MyMethodResponse mymethod(@RequestParam String service, @RequestParam(defaultValue="false") boolean init) {	
	....
	}
```

Or is there a better way to do this (some sort of best practices)?

**Comment by dilipkrish** [comment]
Im not sure if ApiParam can be hanging off the method like that. It's not an annotation this library owns. I'm afraid if you're needing custom parameter readers (different from the default) you're going to have to create your own plugin using the extensibility mechanisms. The good news is it's very straightforward to do. If you need help with that or pointers don't hesitate to chime in.

**Comment by jbm4sa** [comment]
Good point, I didn't realized it wasn't part of this lib.

I will check it out, thanks
