### ISSUE TITLE
[Question] Spring HATEOAS PagedResources<Event> using alternateTypeRules

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#746]
Is there a way through which I can get this generics information PagedResources<Event> into the Swagger Spec and eventually into the swagger codegen for Java.

So that my client code contains the same generics semantics.
EventsApi.java generated from the swagger code gen.
PagedResources<Event> getEvents();

Controller method.

    @ApiOperation(value = "Get the list of all the events")
    @RequestMapping(method = RequestMethod.GET, produces = Resources.MEDIA_TYPE)
    @ResponseStatus(value = HttpStatus.OK)
    public PagedResources<Event> getEvents(
            @PageableDefault Pageable pageable,
            PagedResourcesAssembler<Event> pagedAssembler,
            @RequestParam(value = "search", required = false) String search) {
        try {
            return pagedAssembler.toResource(eventService.search(pageable, search), eventConverter);
        } catch (Exception e) {
            throw new InternalServerErrorException(e);
        }
    }

Swagger Spec

			"get" : {
				"tags" : [ "event" ],
				"summary" : "Get the list of all the events",
				"description" : "getEvents",
				"operationId" : "getEventsUsingGET",
				"consumes" : [ "application/json" ],
				"produces" : [ "application/vnd.acme.references+json" ],
				"parameters" : [ {
					"name" : "search",
					"in" : "query",
					"description" : "search",
					"required" : false,
					"type" : "string"
				} ],
				"responses" : {
					"200" : {
						"schema" : {
							"$ref" : "#/definitions/PagedResources«Event»"
						}
					}
				}
			}
		
Generated Code:
EventApi.java

  public PagedResources«Event» getEventsUsingGET (String search) throws ApiException {

**Comment by rajeshkamal** [comment]
@dilipkrish @adrianbk any inputs on this would be great.

**Comment by dilipkrish** [comment]
If you need to use the swagger service description for codegen you need to configure your Docket to use the `forCodeGeneration(true)` option. However you will not be able to recreate the generics semantics because swagger codegen doesn't support it with the same fidelity.
