### ISSUE TITLE
Support multiple pathMappings or pathProviders, one per docket

### ISSUE THREAD

**Issue by apissdks** [springfox/springfox#748]
Hi,

Currently I have multiple web application contexts(multiple dispatcher servlets) sharing the same root application context. These different dispatcher servlets in turn serves different api's.
Ex: 
root context  - /acme
web app context 1 - /acme/api/module1 - dispatcher servlet 1
web app context 2 - /acme/api/module2 - dispatcher servlet 2
@dilipkrish @adrianbk

Earlier without the web app context 2 I was fine with just putting using the -- swaggerSpecConfig.pathMapping("acme/api/module1");

Since I will be having more of these, is there a way to have multiple path mappings or path providers based on the REST Controllers types or some URL mappings etc.

Any inputs/suggestions would be great.

Regards,
Rajesh Kamal

**Comment by dilipkrish** [comment]
If you think about it what you're doing here is partitioning your Apis. So by extension you'd create a separate docket one for each path mapping. Only one path mapping is supported currently for each docket. However it's a great suggestion for a feature to apply conditional path mapping based on predicates.

**Comment by rajeshkamal** [comment]
I am having the swagger config like the below.
The server boots up fine, I can see all the logs of processing the controllers, models etc. But when I try to get the spec it doesn't throw a 404 but rather blank without any exception. Attached the logs below.

SWAGGER CONFIG

@Configuration
@EnableSwagger2
@ComponentScan(basePackages = { "com.acme.rest",
        "com.acme.lcm.api.rest.controller.v1" })
@PropertySource("classpath:swagger.properties")
public class SwaggerConfig {

    @Autowired
    private Environment environment;
    @Value("${springfox.documentation.swagger.v2.path}")
    private String swagger2Endpoint;

    public AlternateTypeRule getAlternateTypeRule(Type sourceType, Type sourceGenericType,
            Type targetType, Type targetGenericType) {
        TypeResolver typeResolver = new TypeResolver();
        ResolvedType source = typeResolver.resolve(sourceType, sourceGenericType);
        ResolvedType target = typeResolver.resolve(targetType, targetGenericType);
        AlternateTypeRule collectionRule = new AlternateTypeRule(source, target);
        return collectionRule;
    }

    public AlternateTypeRule getAlternateTypeRule(Type sourceType, Type sourceGenericType,
            Type targetType) {
        TypeResolver typeResolver = new TypeResolver();
        ResolvedType source = typeResolver.resolve(sourceType, sourceGenericType);
        ResolvedType target = typeResolver.resolve(targetType);
        AlternateTypeRule collectionRule = new AlternateTypeRule(source, target);
        return collectionRule;
    }

    Predicate<String> excludePath(final String path) {
        return new Predicate<String>() {
            @Override
            public boolean apply(String input) {
                return !input.contains(path);
            }
        };
    }

    Predicate<String> includePath(final String path) {
        return new Predicate<String>() {
            @Override
            public boolean apply(String input) {
                return input.contains(path);
            }
        };
    }

    Predicate<RequestHandler> excludeClass(final Class<?> clazz) {
        return new Predicate<RequestHandler>() {
            @Override
            public boolean apply(RequestHandler input) {
                return !input.getHandlerMethod().getBeanType().equals(clazz);
            }
        };
    }

    @Bean
    public Docket confDocContext() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("evorm")
                .apiInfo(getApiInfo())
                .useDefaultResponseMessages(false)
                .pathMapping("/api/evorm")
//                .forCodeGeneration(true)
                .alternateTypeRules(
                        getAlternateTypeRule(Collection.class, WildcardType.class, List.class,
                                WildcardType.class),
                        getAlternateTypeRule(Resources.class, WildcardType.class, Resources.class),
                        getAlternateTypeRule(PagedResources.class, WildcardType.class,
                                PagedResources.class))
                .directModelSubstitute(XMLGregorianCalendar.class, Date.class)
                .ignoredParameterTypes(PagedResourcesAssembler.class, Pageable.class).select()
                .paths(excludePath("lcm")).build();
    }

    @Bean
    public Docket confLCMDocContext() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("lcm")
                .apiInfo(getApiInfo())
                .useDefaultResponseMessages(false)
                .pathMapping("/api/1.0")
//                .forCodeGeneration(true)
                .alternateTypeRules(
                        getAlternateTypeRule(Collection.class, WildcardType.class, List.class,
                                WildcardType.class))
                .directModelSubstitute(XMLGregorianCalendar.class, Date.class)
                .ignoredParameterTypes(PagedResourcesAssembler.class, Pageable.class).select()
                .paths(includePath("lcm")).build();
    }

    private ApiInfo getApiInfo() {
        return new ApiInfo("ACME API's", "ACMEEEEEE", "1.0", "",
                "acme@acme.com", "Apache License 2.0", "");
    }

}

SERVER LOG
https://10.20.72.108:8443/acme/api/evorm/spec

2015-05-20 16:20:24,044 DEBUG: org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Looking up handler method for path /spec
2015-05-20 16:20:24,044 DEBUG: org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Returning handler method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String)]
2015-05-20 16:20:24,044 DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'swagger2Controller'
2015-05-20 16:20:24,044 DEBUG: org.springframework.web.servlet.DispatcherServlet - Last-Modified value for [/vrm-ui/api/evorm/spec] is: -1
2015-05-20 16:20:24,044 DEBUG: org.springframework.web.servlet.DispatcherServlet - Null ModelAndView returned to DispatcherServlet with name 'acme-api': assuming HandlerAdapter completed request handling
2015-05-20 16:20:24,044 DEBUG: org.springframework.web.servlet.DispatcherServlet - Successfully completed request
2015-05-20 16:20:24,044 DEBUG: org.springframework.security.web.access.ExceptionTranslationFilter - Chain processed normally

**Comment by dilipkrish** [comment]
Don't see the `/v2/api-docs` in the path? what do you see when you browse to `https://10.20.72.108:8443/v2/apidocs/acme/api/evorm/spec`?

**Comment by rajeshkamal** [comment]
Hi,

https://10.113.225.30:8443/v2/apidocs/acme/api/evorm/spec - throwing 404.
I don't think there should be any v2/apidocs in the URL because i have a swagger.properties and the swagger 2 endpoint has been overridden to springfox.documentation.swagger.v2.path=spec. So the root context is acme and the dispatcher servlet's mapping is api/evorm so it should be 
https://localhost:8443/acme/api/evorm/spec. I am not sure providing the second Docket is causing some issue.

**Comment by rajeshkamal** [comment]
OK this is what is happening. Not sure why...

I had two dockets. Commented out one of them and just had the below - swagger api spec url overriding, and swagger spec config. Server starts up fine. going to URL https://10.113.225.30:8443/acme/api/evorm/spec does not render anything. Looks like the URL is active but does not render anything. Not even a 404.

@Value("${springfox.documentation.swagger.v2.path}")
    private String swagger2Endpoint;

    @Bean
    public Docket confDocContext() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("evorm")
                .apiInfo(getApiInfo())
                .useDefaultResponseMessages(false)
                .pathMapping("/api/evorm")
                //                .forCodeGeneration(true)
                .alternateTypeRules(
                        getAlternateTypeRule(Collection.class, WildcardType.class, List.class,
                                WildcardType.class),
                        getAlternateTypeRule(Resources.class, WildcardType.class, Resources.class),
                        getAlternateTypeRule(PagedResources.class, WildcardType.class,
                                PagedResources.class))
                .directModelSubstitute(XMLGregorianCalendar.class, Date.class)
                .ignoredParameterTypes(PagedResourcesAssembler.class, Pageable.class).select()
                .paths(excludePath("lcm")).build();
    }

Now just commented out the below line from the docket. This contains the group name for the docket.
//                .groupName("evorm")

Now going to the URL https://10.113.225.30:8443/acme/api/evorm/spec renders the spec. Not sure what is happening with setting a group name and hows does it impact the spec generation.

**Comment by dilipkrish** [comment]
what are you using `swagger2Endpoint` for and what is its value?

**Comment by dilipkrish** [comment]
try going to` https://10.113.225.30:8443/acme/v2/api-docs?group=evorm` 

* - replace /v2/api-docs with what you've configured `springfox.documentation.swagger.v2.path` with

**Comment by rajeshkamal** [comment]
Wow it works... Now I got it... Thanks. Now I have two dockets with different groups working under.
https://10.113.225.30:8443/acme/api/evorm/spec?group=evorm
https://10.113.225.30:8443/acme/api/evorm/spec?group=lcm

Just a follow up question. If I want them to be together not in different specs but with different path mappings that is not possible right. Are there any workarounds for that.

Using the default group and creating different path mappings for different types of URL's or Controller classes. etc.

**Comment by dilipkrish** [comment]
Nopes unfortunately! That's why I said this is a great feature request :)

**Comment by rajeshkamal** [comment]
I will leave this issue open for tracking.. Hope you can get this feature quickly..

**Comment by rajeshkamal** [comment]
@dilipkrish @adrianbk  The swagger spec metadata is under the "default" swagger group. I tried to put all of it under a "custom" swagger group. It doesn't seem to work. Grouping works only if there are 2 or more groups?

**Comment by gakat2012** [comment]
Nice blog.. Is there a way to configure the hostname for different group (Docket)
For eg. 1) http://api-internal.com/service 2)https://api.com/service

**Comment by rajeshkamal** [comment]
@dilipkrish I thought this was a feature request as you said in one of the above comments. Closed ??

**Comment by atiwari54** [comment]
Hello Dilip,

I have two different application hosted on same tomcat.
Now i want a single Swagger page for tersting both app APIs, is there anyway to do this?

**Comment by dilipkrish** [comment]
Take a look at how [jhipster](https://jhipster.github.io) does it.

**Comment by VictorDenisov** [comment]
There is a great workaround at stackoverflow: https://stackoverflow.com/questions/44285341/customize-endpoints-of-dockets-with-springfox-swagger. Unfortunately it requires a redirect, but it's at least something.
