### ISSUE TITLE
How to set default value and read-only properties?

### ISSUE THREAD

**Issue by opallios** [springfox/springfox#749]
I'm using the latest Spring fox build, 2.0. It's working out great except two main issues,

1) I'm not able to set a field as read-only. Here is what I've tried,
   a)  JSON way - set ignore (@JsonIgnore) for the field (and setter) and use @JsonProperty in the getter.
    b) Using hidden annotation - I went through the https://github.com/springfox/springfox/issues/554 and enabled readOnly in the ApiModelProperty.

        @OneToOne
	@JoinColumn(name = "search_id")
	@JsonIgnore
	@ApiModelProperty(value = "xxx", readOnly = true)
	private Search lastSearch;

        @JsonProperty	
	public Search getLastSearch() {
		return lastSearch;
	}

	@JsonIgnore
	public void setLastSearch(Search lastSearch) {
		this.lastSearch = lastSearch;
	}

, where Search is a referenced object, which can't be set by use, but used only to show results.

What am I missing?

2) I'm not sure how do I set default value for a field. I want to show the default value for all my optional fields.

**Comment by dilipkrish** [comment]
This feature hasn't been flushed out completely. We're waiting for a more stable swagger library to be released

**Comment by dilipkrish** [comment]
Support for this feature was added in 2.0.1

**Comment by aleksz** [comment]
was readOnly support also implemented?

**Comment by dilipkrish** [comment]
@aleksz No just the default value support.

**Comment by aleksz** [comment]
is there any way to mark property as read only? Tried @JsonIgnoreProperties(ignoreUnknown = true, value={ "readOnly" }, allowGetters=true) from https://github.com/FasterXML/jackson-databind/issues/95 , seems to have no effect

**Comment by wind57** [comment]
Is there a milestone when readOnly will be implemented?

**Comment by javi-more-garc** [comment]
Hello,

is there ay workaround to get the read-only stuff working? Other than creating different classes...

Thanks

**Comment by dilipkrish** [comment]
@javi-more-garc Please track #1155
