### ISSUE TITLE
Being able to put alternateTypeRules before the default rules

### ISSUE THREAD

**Issue by ggtools** [springfox/springfox#751]
I have some methods returning `ResponseEntity<Collection<T>>` as there is currently an issue with a collection I wanted to convert my ResponseEntity to a `List<T>`. I added the following rule using `alternateTypeRules`:

```java
newRule(typeResolver.resolve(ResponseEntity.class, typeResolver.resolve(Collection.class, WildcardType.class)),
                                            typeResolver.resolve(List.class, WildcardType.class))
```

Then after some time under debugger I found out that my rules were added after the rules from `Defaults` and since there is a more general rule matching `ResponseEntity<T>` my rule is never applied.

My current workaround is to define my own bean with no default rules but there might be something simpler.

**Comment by dilipkrish** [comment]
@ggtools there might be a better extensibility story there. The idea with the default rules was that you get basic rules for free and the order of those rules wouldn't matter for rules in the library user space. Would love feedback/ideas if you have any.

In any case the intension was to allow users to provide their own plugins just like you did. Its similar to [SwaggerDefaultConfiguration](https://github.com/springfox/springfox/blob/master/springfox-swagger1/src/main/java/springfox/documentation/swagger1/web/SwaggerDefaultConfiguration.java), where you can specify a configuration plugin with your own `Order` annotation to prioritize your bean. Then you could just compose the default configuration within your bean.

**Comment by ggtools** [comment]
It's great to have a sensible set of default rules and I think my custom rules won't be needed anymore when a couple of issues (better handling of non List collections and Maps) will be fixed. However I think more logical to have the default rules applied after the user rules rather than the opposite as it is done today or to add a new configuration directive in order not to break compatibility.

Of course the plugin system with `Order` would be great

**Comment by dilipkrish** [comment]
Closing this as its not really an issue
