### ISSUE TITLE
allowableValues in ApiParam annotation is not shown properly

### ISSUE THREAD

**Issue by okohub** [springfox/springfox#753]
I expected to see dropdown for ApiParam annotated params which are also using allowableValues property, but they still exists with traditional input box.

**Comment by dilipkrish** [comment]
Please provide more information

**Comment by okohub** [comment]
@dilipkrish of course,

I am using a simple swagger configuration as described [here](https://github.com/springfox/springfox/blob/master/docs/transitioning-to-v2.md), nothing more. 

Here is a basic controller which includes my problem

```java

@ApiOperation(value = "Dummy")
@RequestMapping(value = "/dummy", method = RequestMethod.GET)
public ResponseEntity<String> getDummy(@ApiParam(name = "dummyParam", required = true, allowableValues = "1, 2, 3") @RequestParam(value = "dummyParam") Integer dummyParam) {
      return new ResponseEntity<>("dummy", HttpStatus.OK);
}

```

**Comment by dilipkrish** [comment]
Closing this as its not reproducible in 2.0.1
