### ISSUE TITLE
Can't get swaggerGroup working?

### ISSUE THREAD

**Issue by glencurran** [springfox/springfox#757]
Any chance anyone can help me with this issue http://stackoverflow.com/questions/30353529/trying-to-use-swaggergroup-but-i-cant-get-it-working-properly?

Any help would be greatly appreciated as this is driving me crazy, I'm pretty sure I have tried everything but can't get this feature to work.

**Comment by glencurran** [comment]
So on further examination and testing I think I was mistaken about the functionality of the "swaggerGroup", I'm pretty sure it only allows you to show a JSON representation of your api and doesn't actually affect the swagger ui stuff at all. 

If this is the case you can close this question.

**Comment by dilipkrish** [comment]
@glencurran that is correct. I'd suggest moving to 2.0 version

**Comment by glencurran** [comment]
Thanks for the quick reply and just a quick follow up does springfox 2.0 use java 8?

**Comment by dilipkrish** [comment]
No it does not. Still java 6 and up

**Comment by glencurran** [comment]
That's great thanks, I don't know why I thought it did. I will give it a go this evening so.

Thanks for your help.
