### ISSUE TITLE
Unable to access API via Docker

### ISSUE THREAD

**Issue by nickcodefresh** [springfox/springfox#758]
Hi,

When I run my Swaggered project via Spring boot I can access the Swagger UI page via ```http://localhost:9080/swagger-ui.html```

If I Dockerize my app and then run it. and then try to hit the same end point I get the error:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed May 27 16:39:52 UTC 2015
There was an unexpected error (type=Internal Server Error, status=500).
class path resource [META-INF/resources/swagger-ui.html] cannot be resolved in the file system for resolving its last-modified timestamp
```

Any ideas what the issue might be?

Thanks

Nick

**Comment by dilipkrish** [comment]
No idea frankly. If I were to guess the port mapping on your docker image isn't right

**Comment by nickcodefresh** [comment]
Turns out that if I use a Dockerfile to create the image with the Spotify docker plugin, Swagger works fine. It was only a problem if set the base image etc in my POM file directly.

```
FROM java:8
VOLUME /tmp
ADD content-link-service-*.jar app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```

Nick
