### ISSUE TITLE
getting "Can't read from server. It may not have the appropriate access-control-origin settings."

### ISSUE THREAD

**Issue by gaffa** [springfox/springfox#77]
Hi!
I did set up a pretty straightforward example app. I am getting:

"Can't read from server. It may not have the appropriate access-control-origin settings."

from ui all the time. That is somehow realated to CORS which i dont know anything about. 
Spring-mvc-app running on tomcat.

Anyone can give me directions?
Regards!

**Comment by AbsoluteTiger** [comment]
Hi, 
I'm using springfox-swagger2 and springfox-swagger-ui version:2.5.0 with spring boot 1.3.6.RELEASE
when i set this property:spring.jackson.serialization.wrap-root-value=true ,i get "Can't read from server. It may not have the appropriate access-control-origin settings." too.

**Comment by dilipkrish** [comment]
@AbsoluteTiger the issue you're seeing is a duplicate of #597
