### ISSUE TITLE
Duplicate Tags when multiple @Api have same value.

### ISSUE THREAD

**Issue by rkaltreider** [springfox/springfox#771]
I have an Abstract controller for all my controllers that handle users.  I have an @Api declaration on the abstract class so that all subclasses will be grouped under the same tag.  It looks like the swagger doc has multiple tags with the sane value of users though, so i am failing validation on swagger-ui

~~~
"tags": [
{
"name": "questions"
},
{
"name": "modifiers"
},
{
"name": "users"
},
{
"name": "users"
},
{
"name": "items"
},
{
"name": "recommendations"
},
{
"name": "terms"
},
{
"name": "caches"
},
{
"name": "users"
},
{
"name": "applicationinformation"
},
{
"name": "users"
}
],
~~~

**Comment by dilipkrish** [comment]
Thanks for reporting!

**Comment by rkaltreider** [comment]
I still have the same issue when upgrading to 2.0.3.  Is this part of 2.0.3 or do I need to wait for another verison?

**Comment by dilipkrish** [comment]
2.0.4
