### ISSUE TITLE
Swagger 2.0 - Cannot Have Blank Notes / Implementation Details

### ISSUE THREAD

**Issue by kevinconaway** [springfox/springfox#773]
The default value for @ApiOperation(notes) is "" but Springfox substitutes the _operationName_ (which appears to be the method name) instead.

With this logic, it doesn't appear that there is a way to have the Implementation Details section blank like the default Petstore application does: http://petstore.swagger.io/

**Comment by dilipkrish** [comment]
The idea was to surface that in the ui so library consumers will see that it needs to be overridden. Since its a plugin based system, you could override it back to blank.

**Comment by kevinconaway** [comment]
IMO it shouldn't need to be overridden.  Take the petstore reference application for example, most of the API listings are plenty clear with just the HTTP verb, path and summary statement.

I'll test out the plugin approach.

**Comment by dilipkrish** [comment]
I think just removing [this line](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/operation/DefaultOperationReader.java#L38) should do it :) and of course fixing the tests

**Comment by kevinconaway** [comment]
Thanks, do you want me to submit a PR for that?  Or are you suggesting doing that via a custom plugin?

**Comment by dilipkrish** [comment]
I think a plugin is probably overkill :) if you could do a pr that would be awesome
