### ISSUE TITLE
Swagger 2 - MultipartFile not detect/mapped correctly

### ISSUE THREAD

**Issue by RizziCR** [springfox/springfox#775]
Hi,

i use swagger 2 api (@EnableSwagger2)

My controller:

    @RequestMapping(value = "speculativeApplication", method = RequestMethod.POST, consumes = {"multipart/form-data","application/x-www-form-urlencoded"})
    @ApiOperation(value = "Submit a speculative application")
    public ResponseEntity<Void> speculativeApplication(
            @ApiParam(value = "The form content") @RequestPart Profile mainProfile,
            @ApiParam(value = "Applicant photo") @RequestPart(value = "applicant.upload.photo", required = false) MultipartFile photoFileData,
            @ApiParam(value = "Applicant letter") @RequestPart(value = "applicant.upload.letter", required = false) MultipartFile letterFileData,
            @ApiParam(value = "Applicant credentials") @RequestPart(value = "applicant.upload.credential", required = false) MultipartFile[] credentialFileData,
            @ApiParam(value = "Applicant vita") @RequestPart(value = "applicant.upload.vita", required = false) MultipartFile vitaFileData) {
 
My files mapped as "ref":

Here the path Output
{
   "post":{
      "tags":[
         "applicants"
      ],
      "summary":"Submit a speculative application",
      "description":"speculativeApplication",
      "operationId":"speculativeApplicationUsingPOST",
      "consumes":[
         "multipart/form-data"
      ],
      "produces":[
         "*/*"
      ],
      "parameters":[
         {
            "in":"body",
            "name":"mainProfile",
            "description":"The form content",
            "required":false,
            "schema":{
               "$ref":"#/definitions/Profile"
            }
         },
         {
            "name":"photoFileData",
            "in":"formData",
            "description":"Applicant photo",
            "required":false,
            "type":"ref"
         },
         {
            "name":"letterFileData",
            "in":"formData",
            "description":"Applicant letter",
            "required":false,
            "type":"ref"
         },
         {
            "in":"body",
            "name":"credentialFileData",
            "description":"Applicant credentials",
            "required":false,
            "schema":{
               "type":"array",
               "items":{
                  "$ref":"#/definitions/MultipartFile"
               }
            }
         },
         {
            "name":"vitaFileData",
            "in":"formData",
            "description":"Applicant vita",
            "required":false,
            "type":"ref"
         }
      ],
      "responses":{
         "200":{
            "description":"OK",
            "schema":{
               "type":"boolean"
            }
         },
         "201":{
            "description":"Created"
         },
         "401":{
            "description":"Unauthorized"
         },
         "403":{
            "description":"Forbidden"
         },
         "404":{
            "description":"Not Found"
         }
      },
      "security":[
         {
            "profilerAuth":[
               "global"
            ]
         }
      ]
   }
}

Can be the same like issue 768, which is already marked closed in 2.0.2. But i test my controller with the 2.0.2-SNAPSHOT yesterday and the type is also "ref"

regards
Rizzi

**Comment by dilipkrish** [comment]
this should be fixed via #787
