### ISSUE TITLE
swagger-ui endpoint doesn't seem to work

### ISSUE THREAD

**Issue by igilham** [springfox/springfox#776]
I'm trying to figure out how to get at the Swagger UI using the Springfox artifacts in a Spring Boot MVC application. Unfortunately the [reference documentation](http://springfox.github.io/springfox/docs/current/#swagger-ui) is rather misleading, since the neither documented endpoint or the (different) endpoint in the screenshot exist in my application.

I'm using the following dependencies in Maven:

```xml
<dependency>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-jaxrs</artifactId>
  <version>1.5.0</version>
</dependency>
<dependency>
  <groupId>io.springfox</groupId>
  <artifactId>springfox-swagger2</artifactId>
  <version>2.0.1</version>
  </dependency>
<dependency>
  <groupId>io.springfox</groupId>
  <artifactId>springfox-swagger-ui</artifactId>
  <version>2.0.1</version>
</dependency>
```

My Docket Bean is very simple for now:

```java
	@Bean
	public Docket myAPI() {
		return new Docket(DocumentationType.SWAGGER_2)
				.apiInfo(apiInfo())
				.select()
				.paths(paths())
				.build();
	}
```

Looking at `/mappings` in Spring Boot, I have `/swagger-resources` and `/v2/api-docs`, but can't find an endpoint for the UI.

Am I doing something wrong, experiencing a bug, or suffering from bad documentation?

**Comment by dilipkrish** [comment]
@igilham mappings will only list `RequestMapping`'s. `<HOST:PORT/CONTEXT_PATH>/swagger-ui.html` should reveal the ui. Not sure whats misleading [about this](http://springfox.github.io/springfox/docs/snapshot/)?

**Comment by igilham** [comment]
I find it misleading because the screenshot has a different URL to the text, both of which return 404s in my app.

There is nothing in that document about a `CONTEXT_PATH`. Could you clarify what you mean by this?

**Comment by dilipkrish** [comment]
[Context path](http://stackoverflow.com/questions/20405474/spring-boot-context-root) is dependent on your application. As a library, there is no way to know what your applications context path is. May be we should clarify that in the docs. Usually when you're testing locally that context path is `/`

The screenshot is a little misleading as you said because its based [on the demo](https://github.com/springfox/springfox-demos/blob/master/boot-swagger/src/main/java/springfoxdemo/boot/swagger/web/HomeController.java#L10) the home forwards to `/swagger-ui.html`.

Thanks for your feedback! :+1:

**Comment by igilham** [comment]
I see. That's not the source of my issue then.

To be clear, I have endpoints under `/myproprietarystuff`, `/mappings`, `/health` etc. and `/v2/api-docs`. `/swagger-ui.html` returns '404 Not Found'.

All I can think of right now is that I may have missed a step in upgrading from the `mangofactory` library.

**Comment by dilipkrish** [comment]
Have you added the springfox-swagger-ui dependency?

**Comment by igilham** [comment]
Yes. See above for the relevant dependency declarations in Maven.

**Comment by dilipkrish** [comment]
Do you by any chance have a custom webconfigurer adapter or perhaps a `@EnableWebMvc`?

Also 2.0.1 will not work with swagger 1.5.0 ( depends on milestone). The package names have changed between the milestone and release builds.

**Comment by igilham** [comment]
I have removed the extra swagger 1.5.0 dependency and ensured that I am using the wordnik package names for the API annotations. This appears to make no difference to the resulting behaviour.

My application is defined with the following annotations:

```java
@Configuration
@EnableAutoConfiguration
@ComponentScan
@EnableSwagger2
public class Application {
    // ...
}
```

I did have an `@Configuration` class with `@EnableWebMvc` on it. Removing the `@EnableWebMvc` annotation seems to fix the missing `/swagger-ui.html` endpoint. The documentation implies the opposite is true, stating that adding the annotation may fix a NullPointerException.

I had to disable security configurations for various swagger-ui related endpoints to get the UI to load properly, but I got there in the end. Thanks for your help.

**Comment by dilipkrish** [comment]
@igilham would be awesome if you could submit a pr with the discrepancies you found in the documentation.

**Comment by ankit2711** [comment]
I have a spring webmvc 4.X application without spring boot and I am trying to integrate SpringFox to generate documentation for the REST. 

I do get the response with filled JSON when accessing localhost:<port>/<context>/v2/api-docs 
but I do not get a response when hitting localhost:<port>/<context>/swagger-ui.html

I have the following configuration: -
Spring Servlet XML file - 

<mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/" />
<mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/" />
<mvc:default-servlet-handler />

<context:component-scan base-package="com.dummy.v1.controller" />
<bean name="swaggerConfig" class="com.hi.cdi.swagger.SwaggerConfig" />

SwaggerConfig.java 

@EnableSwagger2
@Configuration
@EnableWebMvc
public class SwaggerConfig {

    @Bean
    public Docket customImplementation() {
        return new Docket(DocumentationType.SWAGGER_2);
    }
}

I have added below dependencies to my project 
<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-swagger2</artifactId>
	<version>2.2.2</version>
</dependency>
<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-swagger-ui</artifactId>
	<version>2.2.2</version>
</dependency>

**Comment by ndtreviv** [comment]
+1 for this. It used to work, but now when going to /swagger-ui.html I get a hit on the server, logs:

`14:21:51.557 [qtp1318859753-19] WARN  org.springframework.web.servlet.PageNotFound - Request method 'GET' not supported`

And I get a Whitelabel Error Page (405 error - Method Not Allowed).
The weird thing is that I'm using all the same version dependencies as I was a couple of months ago. The only real difference is that this just doesn't work now...

**Comment by ndtreviv** [comment]
Weird. I've got two applications. Both have the same dependencies.

One one, /swagger-ui.html returns a 405, on the other it works.
On the one that works, trace logging says:
`15:09:02.411 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.DispatcherServlet - Testing handler map [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping@27084440] in DispatcherServlet with name 'dispatcherServlet'
15:09:02.411 [qtp1289862143-15 - /swagger-ui.html] DEBUG org.springframework.web.servlet.handler.SimpleUrlHandlerMapping - Matching patterns for request [/swagger-ui.html] are [/**]
15:09:02.412 [qtp1289862143-15 - /swagger-ui.html] DEBUG org.springframework.web.servlet.handler.SimpleUrlHandlerMapping - URI Template variables for request [/swagger-ui.html] are {}
15:09:02.415 [qtp1289862143-15 - /swagger-ui.html] DEBUG org.springframework.web.servlet.handler.SimpleUrlHandlerMapping - Mapping [/swagger-ui.html] to HandlerExecutionChain with handler [ResourceHttpRequestHandler [locations=[ServletContext resource [/], class path resource [META-INF/resources/], class path resource [resources/], class path resource [static/], class path resource [public/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@1aad30b9]]] and 1 interceptor
15:09:02.416 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.DispatcherServlet - Testing handler adapter [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter@6f3149d0]
15:09:02.416 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.DispatcherServlet - Testing handler adapter [org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter@41e69414]
15:09:02.416 [qtp1289862143-15 - /swagger-ui.html] DEBUG org.springframework.web.servlet.DispatcherServlet - Last-Modified value for [/swagger-ui.html] is: -1
15:09:02.416 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.resource.ResourceHttpRequestHandler - Applying "invalid path" checks to path: swagger-ui.html
15:09:02.417 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.resource.PathResourceResolver - Resolving resource: requestPath="swagger-ui.html"
15:09:02.417 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.resource.PathResourceResolver - Checking location: ServletContext resource [/]
15:09:02.418 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.resource.PathResourceResolver - No match for location: ServletContext resource [/]
15:09:02.418 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.resource.PathResourceResolver - Checking location: class path resource [META-INF/resources/]
15:09:02.418 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.resource.PathResourceResolver - Found match: class path resource [META-INF/resources/swagger-ui.html]
15:09:02.419 [qtp1289862143-15 - /swagger-ui.html] TRACE org.springframework.web.servlet.resource.ResourceHttpRequestHandler - Determined media type 'text/html' for class path resource [META-INF/resources/swagger-ui.html]
`

On the one that does not work, trace logging says:
`15:04:53.713 [qtp681413-17 - /swagger-ui.html] TRACE org.springframework.web.servlet.DispatcherServlet - Testing handler map [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping@665cc427] in DispatcherServlet with name 'dispatcherServlet'
15:04:53.715 [qtp681413-17 - /swagger-ui.html] TRACE org.springframework.web.servlet.handler.SimpleUrlHandlerMapping - No handler mapping found for [/swagger-ui.html]
15:04:53.715 [qtp681413-17 - /swagger-ui.html] TRACE org.springframework.web.servlet.DispatcherServlet - Testing handler map [org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping@44245d5f] in DispatcherServlet with name 'dispatcherServlet'
15:04:53.715 [qtp681413-17 - /swagger-ui.html] DEBUG org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping - Looking up handler method for path /swagger-ui.html
15:04:53.727 [qtp681413-17 - /swagger-ui.html] DEBUG org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping - Did not find handler method for [/swagger-ui.html]
15:04:53.727 [qtp681413-17 - /swagger-ui.html] TRACE org.springframework.web.servlet.DispatcherServlet - Testing handler map [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping@16325bbb] in DispatcherServlet with name 'dispatcherServlet'
15:04:53.727 [qtp681413-17 - /swagger-ui.html] DEBUG org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Looking up handler method for path /swagger-ui.html
15:04:53.735 [qtp681413-17 - /swagger-ui.html] DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Resolving exception from handler [null]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported
`

Weirdly, different *HandlerMapping classes are checked on each.

On the one that works:
* DispatcherServlet ->
* SimpleUrlHandlerMapping ->
* EndpointHandlerMapping ->
* RequestMappingHandlerMapping ->
* BeanNameUrlHandlerMapping ->
* SimpleUrlHandlerMapping (again - different instance)
* maps to ResourceHttpRequestHandler

On the one that doesn't:
* DispatcherServlet ->
* SimpleUrlHandlerMapping ->
* EndpointHandlerMapping ->
* RequestMappingHandlerMapping ->
* maps to ExceptionHandlerExceptionResolver

There seems to be a secondary SimpleUrlHandlerMapping in the one that works, which is catching the static resources...

**Comment by dilipkrish** [comment]
I think you need to have `ResourceHttpRequestHandler` for it to work... so something you're doing isn't detecting that. Is this a spring boot app?

**Comment by ndtreviv** [comment]
Ok figured it out. The dispatcherServlet is suppose to map /** to to ResourceHttpRequestHandler, but if you have a request mapping that takes one parameter in my case (`@RequestMapping("/{range}")`) then it will override it.

I thought this would be ok, because the @RestController class had @RequestMapping("/query") annotation (thus the full path being /query/{range}) but apparently not.

So there you go.

**Comment by ndtreviv** [comment]
PS: Yes! This was a springboot app.

**Comment by AntonRand** [comment]
@ndtreviv Thank you, spent ages trying to figure out what was wrong with my configuration until I saw your post!

**Comment by maruf-cefalo** [comment]
I have added following in the class where i put @EnableWebMvc annotation. It works fine for me.

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        
           registry.addResourceHandler("swagger-ui.html")
                    .addResourceLocations("classpath:/META-INF/resources/");

            registry.addResourceHandler("/webjars/**")
                    .addResourceLocations("classpath:/META-INF/resources/webjars/");

    }

**Comment by rehevkor5** [comment]
@ndtreviv how did you fix your issue? The fix @maruf-cefalo posted doesn't help me with Springfox Swagger2 (2.3.1) where the UI's request to "/swagger-resources/configuration/ui" returns 404 due to Spring Boot being unable to find a handler method for it. It ends up being handled by HandlerExecutionChain (which only recognizes "/", and some class path resources). `ApiResourceController` has a `@RequestMapping(value = "/configuration/ui")` and a `@RequestMapping(value = "/swagger-resources")` but nothing for "/swagger-resources/configuration/ui".

**Comment by dilipkrish** [comment]
@rehevkor5 2.5.0 is _mooaar_ better :)

**Comment by catalinnp** [comment]
@maruf-cefalo 
I had the same problem and it worked with this overriding of addResourceHandlers method.

Thank you, sir!

**Comment by bajaj** [comment]
@maruf-cefalo which class to add addResourceHandlers method ???

I have created the following class. 
But it is not working for me.
I am not using spring boot. I am using only spring mvc.

getting 405 error for http://localhost:8080/swagger-resources/configuration/ui 

`import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

/**
 * Created by bajaj on 22/02/17.
 */
@Configuration
@EnableWebMvc
public class SwaggerConfig extends WebMvcConfigurerAdapter {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {

        registry
                .addResourceHandler("**/**")
                .addResourceLocations("classpath:/META-INF/resources/");
        registry
                .addResourceHandler("**/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");

    }

}
`

**Comment by dilipkrish** [comment]
You can't do `**/**` its not equipped to serve all media types. Thats why ur getting an error.

**Comment by maruf-cefalo** [comment]
@bajaj,
Please see the above comment. Don't use **/**

**Comment by bajaj** [comment]
first i tried with `registry.addResourceHandler("swagger-ui.html")`
it was not working. Getting same 405 error code.

I am also using spring security. So i have all my application api url in the secuity.xml file.
Do i need to make any changes for the same ?

**Comment by raviksoni25** [comment]
for me after removing @EnableWebMvc it worked.

**Comment by shafsongithub** [comment]
I have downaloaded the spring project from swagger editor, localhost:8080/<any path> is not working. 
localhost:8080/v2/ - is working. Its a spring boot.
Any help will be appreciated.

**Comment by raviksoni25** [comment]
@shafsongithub 
I have pushed sample Spring boot with Swagger application. If you want you can use that.
https://github.com/raviksoni25/swagger-sample.git

**Comment by debuglevel** [comment]
@raviksoni25 well, that's interesting: I cloned your project into Spring Tools Suite and it does not work. Afterwards, I did exactly the same on another machine, and there it worked.

Unfortunately, I do not really have any clue what's going on there. There are just some really minor differences in the logs. I'm attaching them, though. 
[failing.txt](https://github.com/springfox/springfox/files/979862/failing.txt)
[working.txt](https://github.com/springfox/springfox/files/979861/working.txt)

**Comment by skarpushin** [comment]
Unbelievable, clearing ..m2 folder and rebuilding helped.

**Comment by ManikMaurya** [comment]
In my case the issues was with version number.
Changed from compile 'io.springfox:springfox-swagger-ui:2.4.0' to  compile 'io.springfox:springfox-swagger-ui:2.6.1' in build.gradle file.

**Comment by profullstack** [comment]
@ndtreviv You saved my day! My configuration is all right, but I just can't see swagger-ui.html and it always returns "Method not allowed". After reading your post, I checked all my controllers and find one with
``` 
@RequestMapping(method = RequestMethod.OPTIONS)
```
to handle all OPTIONS request. I deleted this controller and it just works!

**Comment by s1mm0t** [comment]
I had a similar issue to the one @ndtreviv was experiencing on 9 Mar 2016, however the request mapping for my controller was for "/". None of the suggestions above worked for, so I had to work around it as follows:

I added support for a different path for accessing swagger (http://localhost:8000/swagger/ui/swagger.html. This required the following resource handlers to be set up:
`public class SpringMvcConfiguration extends WebMvcConfigurerAdapter {
    private static final String SWAGGER_UI_PATH = "/swagger/ui";
    private static final String CONFIG_LOCATION = "classpath:/url-rewrite.xml";

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry
                .addResourceHandler(SWAGGER_UI_PATH + "/swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/")
                .resourceChain(true)
                .addResolver(new PathResourceResolver() {
                    @Override
                    protected Resource getResource(String resourcePath, Resource location) throws IOException {
                        return location.createRelative(resourcePath.substring(SWAGGER_UI_PATH.length()));
                    }
                });

        registry
                .addResourceHandler(SWAGGER_UI_PATH + "/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}`

I then needed to introduce [Tuckey](http://www.tuckey.org/urlrewrite/)  for URL rewriting with the following configuration:
`<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE urlrewrite
        PUBLIC "-//tuckey.org//DTD UrlRewrite 4.0//EN"
        "http://www.tuckey.org/res/dtds/urlrewrite4.0.dtd">
<urlrewrite>
    <rule>
        <from>^/swagger/ui/swagger-resources(.*)$</from>
        <to type="permanent-redirect">/api/stock/swagger-resources/$1</to>
    </rule>

    <rule>
        <from>^/swagger/ui/v2/api-docs</from>
        <to type="permanent-redirect">/api/stock/v2/api-docs</to>
    </rule>
</urlrewrite>`

Spring Boot: 1.5.4.RELEASE
Swagger: 2.8.0

**Comment by dilipkrish** [comment]
@s1mm0t ingenious! 👌

**Comment by yogeshbhuse** [comment]
@dilipkrish 

Can we integrate the Spring MVC(not boot) and JaxRs with Swagger-ui,

i tried to do this but not able to access the swagger-ui.html

**Comment by dilipkrish** [comment]
Do you have a repo you can share?

**Comment by yogeshbhuse** [comment]
@dilipkrish 
Sorry  i am not able to take the repo but i can provide the pom.xml

i have added to below dependency to work with Jaxrs and Swagger
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jersey2-jaxrs</artifactId>
            <version>1.5.9</version>
        </dependency>

**Comment by dilipkrish** [comment]
If your using `swagger-jersey2-jaxrs` then you need to check with [Swagger Core](https://github.com/swagger-api/swagger-core/) on how to use it.

**Comment by yogeshbhuse** [comment]
@dilipkrish 

How would configure the Swager-core its html component ?

**Comment by LuckyDudde** [comment]
Hi DilipKrish
In my code i have global exception to handle 404 exception and it was working fine, but when add swaggerui to my code and deployed but when i hit URL http://localhost:8080/swagger-ui.html#/
not able get view and console is:

2018-03-05 15:10:32.221  WARN 6360 --- [nio-8080-exec-3] .m.m.a.ExceptionHandlerExceptionResolver : Failed to invoke @ExceptionHandler method: public final org.springframework.http.ResponseEntity<com.hsbc.ucm.customerapi.exception.ErrorMessage> com.hsbc.ucm.customerapi.exception.GobalExceptionHandler.handleNotFoundException(org.springframework.web.servlet.NoHandlerFoundException,org.springframework.web.context.request.WebRequest)

org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:200) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:203) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:113) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:384) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:59) [spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:136) [spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:76) [spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1222) [spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1034) [spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) [spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]

After debugging my code and I removed @EnableWebMVC from global Exception handler class, then deployed and able get swaggerUI and working fine but 404 exception is not handling.

**Comment by dilipkrish** [comment]
Without looking at your project its very hard to tell. Rather than me or anyone else guessing could you perhaps share a repository that demonstrates the problem

**Comment by hmarggraff** [comment]
The solution, that has helped me, was to include the aforementioned resource handlers in the class, that enables @EnableWebMvc via a WebMvcConfigurerAdapter:

My class where I needed to activate @EnableWebMvc  was the SecurityConfiguration in order to set up Cors mappings. So I moved the swagger resource configuration there: (The solution is ugly, because swagger does not belong into security. But then, spring itself is ugly.)


    @Configuration
    @EnableWebMvc
    @EnableWebSecurity
    @EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
    public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
                        // ... a lot of security stuff
            @Bean
            public WebMvcConfigurer webMvcConfigurer() {
                        return new WebMvcConfigurerAdapter() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {  // this is the reason I needed             @EnableWebMvc 
                registry.addMapping("/api/**").allowedOrigins("*");
            }

            @Override
            public void addResourceHandlers(ResourceHandlerRegistry registry) { // this does not belong here, but now it gets picked up by spring
                registry.addResourceHandler("swagger-ui.html")
                        .addResourceLocations("classpath:/META-INF/resources/");
                registry.addResourceHandler("/webjars/**")
                        .addResourceLocations("classpath:/META-INF/resources/webjars/");
            }
        };
    }

**Comment by dapregala** [comment]
For anyone still encountering this problem, I tried almost everything from above but still can't to solve my issue. So, this is how I resolved mine.

Root cause: swagger-ui.html doesn't show up because it **doesn't recognize** any API.

I don't know the way how it recognizes APIs but I'm 100% sure that it doesn't recognize the controllers and methods I annotated with Spring shorthand annotations, annotations such as `@RestController`, `@PostMapping`, `@GetMapping`, etc. 

When I **changed** it to the traditional `@RequestMapping(value = "/foo", method = RequestMethod.POST)`, the API is now recognized and swagger-ui now shows.

Versions used:

- `springfox-swagger2:2.7.0`

- `springfox-swagger-ui:2.7.0`

- `spring-boot:2.0.0.RELEASE`

Hope this helps anyone.

**Comment by ibobak** [comment]
I had a similar issue and found the reason of what was wrong with my code.  I had a class marked by @Configuration derived from WebMvcConfigurationSupport.

Unfortunately,   WebMvcConfigurationSupport has an empry method configureDefaultServletHandling()  which has to be overriden like this:

@Override
protected void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
       configurer.enable();
}

**Comment by biniama** [comment]
Working example with complete code and dependencies using spring boot 2.0.3-RELEASE
https://gist.github.com/biniama/ba3e0e1df6fd7d320d1bf242de9d469e

It is a compilation of all the recommended options from the above comments.

**Comment by dilipkrish** [comment]
Thank you @biniama

**Comment by geektcp** [comment]
I found the really reason, because of @ComponentScan, and u must to annotate it , for example: 
//@ComponentScan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})

and then , it will be ok,  u can open the swagger-tui.html and /swagger-resources/configuration/ui

**Comment by geektcp** [comment]
swagger启动后，老是报错下面的url无法打开swagger-ui.html，
提示内部url无法打开swagger-resources/configuration/ui

原因是：
启用了组件扫描导致：@ComponentScan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})
这个问题真是费解。

解决办法：注释掉扫描注解即可：
//@componentscan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})

**Comment by pnaveenreddy966** [comment]
@dilipkrish 

I am trying to implement the swagger for one of our Multi module Spring Application which is configured with Apache.cxf 

I added the dependencies:
<dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-spring-web</artifactId>
      <version>2.9.2</version>
    </dependency>
    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger2</artifactId>
      <version>2.9.2</version>
    </dependency>
    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>2.9.2</version>
    </dependency>
, added the SwaggerConfig.java:

package com.walmart.cpc.checkout.service.bean;


import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
@EnableWebMvc

public class SwaggerConfig extends WebMvcConfigurerAdapter {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        System.out.println(" inside swaggerconfig class file ");
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}
Even though it is showing up with the following error:

"message":"Inbound Message\n----------------------------\nID: 4\nAddress: http://localhost:8080/checkoutservice/swagger-ui.html\nHttp-Method: GET\nContent-Type: \nHeaders: {Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3], accept-encoding=[gzip, deflate, br], accept-language=[en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,te;q=0.6,fr;q=0.5], cache-control=[max-age=0], connection=[keep-alive], Content-Type=[null], host=[localhost:8080], sec-fetch-mode=[navigate], sec-fetch-site=[none], sec-fetch-user=[?1], upgrade-insecure-requests=[1], user-agent=[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36]}\n--------------------------------------","context":"default"}
{"timestamp":"2019-09-16T15:51:26.915+0000","level":"WARN","thread":"http-bio-8080-exec-10","mdc":{"tracingId":"88d189e5-fe37-465a-8819-85f842af9267"},"logger":"org.apache.cxf.jaxrs.utils.JAXRSUtils","message":"No operation matching request path \"/checkoutservice/swagger-ui.html\" is found, Relative Path: /swagger-ui.html, HTTP Method: GET, ContentType: */*, Accept: text/html,application/xhtml+xml,image/webp,image/apng,application/signed-exchange;v=b3,application/xml;q=0.9,*/*;q=0.8,. Please enable FINE/TRACE log level for more details.","context":"default"}

can anyone help me with this issue?

**Comment by satishpatro44** [comment]
implementation group: 'io.springfox', name: 'springfox-swagger2', version: '3.0.0-SNAPSHOT'
    implementation group: 'io.springfox', name: 'springfox-swagger-ui', version: '3.0.0-SNAPSHOT'
    implementation group: 'io.springfox', name: 'springfox-spring-webflux', version: '3.0.0-SNAPSHOT'
It was working till yesterday, but now it is not working

I have one @GetMapping(value = "/fallBack")  in that service

the context path is blank
port = 9208

localhost:9208/swagger-resources **loading**
localhost:9208/swagger-ui.html **not loading**

`@Configuration
//@EnableWebMvc
public class ResourceHandlerConfig implements WebFluxConfigurer {


	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/resources/**").addResourceLocations("/resources/");
		registry.addResourceHandler("/swagger-ui.html**").addResourceLocations("classpath:/META-INF/resources/");
		registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
		//Resource Path for Hystrix Dashboard
		registry.addResourceHandler("/hystrix/**").addResourceLocations("classpath:/static/hystrix/");
	}}


`

**Comment by hala3k** [comment]
solved for me by using swagger 3 instead of 2 as swagger 2 might not integrate well with spring-boot 2. this [link](https://medium.com/@hala3k/setting-up-swagger-3-with-spring-boot-2-a7c1c3151545?sk=4a54b60572b200d4a2ea17bd54906d29) might be useful.

**Comment by NetRob** [comment]
You also have to be aware that Swagger 3 changed the URL of the UI from _/swagger-ui.html_ to _/swagger-ui/index.html_.

I was surprised by seeing the Whitelabel Error Page (404: NotFound) after upgrading from 2.8.0 to Swagger 3.

Thanks to @hala3k for the mentioned link that helped me clarify this.

**Comment by ingvard** [comment]
@NetRob I just added:
`@Configuration
class SwaggerUiWebFluxConfigurer : WebFluxConfigurer {
    override fun addResourceHandlers(registry: ResourceHandlerRegistry) {
        registry.addResourceHandler("/swagger-ui/**")
            .addResourceLocations("classpath:/META-INF/resources/webjars/springfox-swagger-ui/")
            .resourceChain(false)
    }
}`

**Comment by IonutCiuta** [comment]
@NetRob thank you! This should be more evidently stated in the docs!

**Comment by velheor** [comment]
> @NetRob I just added, for 3.0.0:
> 
> ```
> @Configuration
> class SwaggerUiWebFluxConfigurer : WebFluxConfigurer {
>     override fun addResourceHandlers(registry: ResourceHandlerRegistry) {
>         registry.addResourceHandler("/swagger-ui/**")
>             .addResourceLocations("classpath:/META-INF/resources/webjars/springfox-swagger-ui/")
>             .resourceChain(false)
>     }
> }
> ```

it works for me on swagger 3.0.0 and use http://localhost:8080/myapp/swagger-ui/index.html#/

**Comment by aravindhrs** [comment]
> You also have to be aware that Swagger 3 changed the URL of the UI from _/swagger-ui.html_ to _/swagger-ui/index.html_.
> 
> I was surprised by seeing the Whitelabel Error Page (404: NotFound) after upgrading from 2.8.0 to Swagger 3.
> 
> Thanks to @hala3k for the mentioned link that helped me clarify this.

It worked. 👏
