### ISSUE TITLE
Swagger2MarkupResultHandler.outputDir should have a getter

### ISSUE THREAD

**Issue by gmarziou** [springfox/springfox#779]
Hello,

Using 2.0.1, I'm trying to generate static docs as shown in demo in [StaticDocsTest.groovy](https://github.com/springfox/springfox-demos/blob/master/boot-static-docs/src/test/groovy/springfoxdemo/staticdocs/StaticDocsTest.groovy) but using java it seems that outputDir private field in Swagger2MarkupResultHandler should have a public getter.

I have an easy workaround, so it's not that important.

**Comment by dilipkrish** [comment]
@gmarziou the static-docs library itself is experimental. Its based on @RobWin's [awesome library](https://github.com/RobWin/swagger2markup) we're still trying to figure out what we need to do in static docs so that it provides more value on top of his library. Feedback is greatly appreciated!

**Comment by RobWin** [comment]
@gmarziou  You should use the builder to create a Swagger2MarkupResultHandler.

```
Swagger2MarkupResultHandler resultHandler = Swagger2MarkupResultHandler
              .outputDirectory(outDir)
              .build()
```

**Comment by gmarziou** [comment]
Thanks i have been able to statically generate API doc in adoc using JUnit test and then generate html and pdf formats using maven plugin. 

Really enjoying this feature, great work.

The only thing that I can't get to work are cross references to response types like UserDTO

paths.adoc
~~~~
== Paths
=== getAccount
----
GET /api/account
----

==== Description
:hardbreaks:
getAccount

==== Responses
[options="header"]
|===
|HTTP Code|Description|Schema
|200|OK|<<UserDTO>>
|401|Unauthorized|No Content
|403|Forbidden|No Content
|404|Not Found|No Content
|===
~~~~

The UserDTO definition is in another file: definitions.adoc

So I guess that either I should configure it somehow to generate a single adoc file or that cross references should be Inter-document cross references :+1: 

~~~~
|200|OK|<<defintions.adoc#UserDTO>>
~~~~

**Comment by RobWin** [comment]
If you like Swagger2Markup, I would love to get your star :)

Have a look at https://github.com/RobWin/swagger2markup#combine-generated-documentation-with-your-hand-written-documentation. It explains how to create an index.adoc and to combine hand-written documentation with the generated documentation.

**Comment by gmarziou** [comment]
Thanks you got starred ;)

**Comment by RobWin** [comment]
You are welcome.

**Comment by dilipkrish** [comment]
:+1:
