### ISSUE TITLE
Make Endpoint swagger-resources for swagger-ui configurable?

### ISSUE THREAD

**Issue by kaib** [springfox/springfox#780]
I have the problem, that in our application every endpoint which serves json is accessable via endpoint.json

When i want the /v2/api-docs i need to enter /v2/api-docs.json to access it. 
the same problem is with /swagger-resources . i need swagger-resources.json

Now if i want to use your swagger-ui package i cant get it to work because these endpoints are not configurable or am i wrong? 

Is there a way to configure these entpoints, so that your swagger-ui module will pick them up instead of the normal ones? Or is the only way to manually edit the jar file? 

I hope you understand my problem, if not, i will provide further information

**Comment by dilipkrish** [comment]
Have you looked at [this section](http://springfox.github.io/springfox/docs/snapshot/#customizing-the-swagger-endpoints) in the documentation? You can customize the swagger endpoints easily. 

Unfortunately swagger-resources cannot be customized. Its a *cool url* :sunglasses: and it serves the purpose of making the swagger-ui load the available services.

**Comment by kaib** [comment]
my problem is, that i need swagger-ui to load the service from swagger-ressources.json because with our setup i cannot access swagger-resources, but if i use swagger-ressources.json it is working fine

**Comment by dilipkrish** [comment]
In that case you cannot use the bundled swagger-ui and you'll have to roll your own unfortunately.

**Comment by kaib** [comment]
okay, thanks for your fast answers!!

**Comment by micw** [comment]
I had the same problem because I needed to Map everything to below /service/docs. So I simply created an own controller with custom RequestMapping:

```Java
@RequestMapping("/service/doc")
@Controller
@ApiIgnore
public class SwagerApiResourceController extends ApiResourceController
{

}
```
