### ISSUE TITLE
CORS error message displayed at top of the page

### ISSUE THREAD

**Issue by gmarziou** [springfox/springfox#781]
in dev on localhost:8081, I am getting CORS message "Can't read from server. It may not have the appropriate access-control-origin settings." at the top of the page as shown in screenshot below even though the documentation is correctly generated below.

![2015-06-09_16h35_03](https://cloud.githubusercontent.com/assets/361007/8062021/e438d676-0ecd-11e5-8c11-6028a62d3648.png)

As seen in the browser's console, it is due to attempting access to http://petstore.swagger.io/v2/swagger.json.

~~~~
XMLHttpRequest cannot load http://petstore.swagger.io/v2/swagger.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.
~~~~

This triggers another error at swagger-ui.html:51

~~~~
Uncaught ReferenceError: log is not defined
~~~~

**Comment by dilipkrish** [comment]
This should now be fixed as a result of https://github.com/springfox/springfox/commit/99c2d2b5ab5973d386f0542f3826d91c86c20dc8

**Comment by gmarziou** [comment]
Great, thanks
