### ISSUE TITLE
@RequestPart with @ApiParam not rendering a definition in 2.0.0

### ISSUE THREAD

**Issue by mrisney** [springfox/springfox#786]
This might be a duplicate, so apologize in advance.
I have tried  @ApiParam @ApiImplicitParam, everything, but I am not able to add the definition of an object in the swagger.json , in a POST fileupload multipart file 
mockMvc
				.perform(fileUpload("fileupload/service/endpoint")
				.file(file))
				.andDo(document("svc_file_upload"))
				.andExpect(status().isOk()).andReturn();
 (using rest-docs) to generate sample curl, http-post methods.
is there any way to force inclusion of an object into the defintions ? I added @ApiModel to the class, but that doesn't work either. frustrated.

**Comment by dilipkrish** [comment]
It is a bug i believe, I haven't had time to look at what to issue is.  If you share your method signature for your controller method that might be helpful in getting me a jumpstart. Even better if you can add a failing test in swagger-contract-tests.

**Comment by mrisney** [comment]
I found a work around, I add a response with the class that I am missing from definitions

@ApiOperation(value = "upload file svc", 
			notes = "multi part file upload.", 
			response = UploadFileLogInfo.class, 
			httpMethod = "POST")
		
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "OK", response = UploadFileDetail.class)}

...
public UploadFileLogInfo processUploadFile(
			HttpServletRequest request,
			@ModelAttribute("account") Account account,
			@ApiParam(name="fileDetail", required=true) @RequestPart(value = "fileDetail", required = true) @Valid UploadFileDetail fileDetail)
	
Now I have UploadFileDetail in the definitions section of the swagger.json. This is a hack, but it seems to work.

**Comment by dilipkrish** [comment]
Shoud be fixed via #787
