### ISSUE TITLE
OAuth password grant_type support

### ISSUE THREAD

**Issue by vivekpandian** [springfox/springfox#789]
I don't see the password Grant type support in spring fox. Does spring fox support password grant type  ? I see only Implicit and AuthtorizationCode grant.

**Comment by dilipkrish** [comment]
Once swagger core adds support for this it should be straight forward

**Comment by cbornet** [comment]
In https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/OAuth2AuthFactory.java there is
```java
} else if ("password".equals(each.getType())) {
// NOTE: swagger 1 doesn't support this
definition.password(each.getType());
```
Shouldn't it be definition.password(each..getTokenEndpoint().getUrl()) ?

**Comment by dilipkrish** [comment]
I think at the time we wrote this, swagger-core did not support it :)

**Comment by cbornet** [comment]
@dilipkrish I have started implenting it and have a question for you. Since Swagger 1.2 doesn't support password or client credentials grants, if one of those flows is used with a swagger12 docket, an UnsupportedOperationException is thrown in springfox.documentation.swagger1.mappers.AuthorizationTypesMapper.toSwaggerGrantType(). Is it OK for you ?

**Comment by cbornet** [comment]
Note that the same already happens with GrantType("password")

**Comment by dilipkrish** [comment]
@cbornet sorry for the late response... If the existing behavior is to throw an UnsupportedOperationException, lets keep it that way. However, I think going forward it should just degrade gracefully to not rendering things it doesn't know about

**Comment by cbornet** [comment]
Yes, I agree. But it is difficult to do because the GrantType is mapped at the end of authorizations.oauth2.grantTypes so when mapping the authorizations we must already know if the grantTypes in it will eventually be rendered.
