### ISSUE TITLE
New to Springfox

### ISSUE THREAD

**Issue by Cpruce** [springfox/springfox#795]
Hi,

I'm new to springfox, swagger, and maven and have recently taken over a project with an outdated version swagger-springmvc. I've got an idea of where to start with moving to springfox; however, the guidelines leave some questions unanswered. Should I now take the swaggerConfiguration bean out of the applicationContext-webmvc.xml file? In the pom.xml file, I should replace the swagger-annotations, swagger-core, and swagger-springmvc dependencies with

![fox](https://cloud.githubusercontent.com/assets/2712171/8170512/f3fe1282-1365-11e5-8eb8-dc5c5b1a6348.png)

right? As well as adding the repository the repository specified

Doing this, I now don't have access to imports like com.wordnik.swagger.annotations. Should I replace com.wordnik with spring.documentation like the com.mangofactory? In addition, can you tell if I am missing anything?

Thanks for your help!

**Comment by t0tec** [comment]
In my project (non-spring-boot) I use [this](https://github.com/t0tec/formula-one-api/blob/master/main/rest/src/main/java/org/formulaone/rest/config/SwaggerConfig.java) to configure Springfox/Swagger. I gues 

```xml
        <!-- Swagger/Springfox (api documentation) -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.0.1</version>
        </dependency>
```

Then you'll probably want to documentate your Spring REST controllers and such.

**Comment by dilipkrish** [comment]
@Cpruce take a look at the [transitioning guide](https://github.com/springfox/springfox/blob/master/docs/transitioning-to-v2.md) from v1.0.2 to v 2..0.x

**Comment by Cpruce** [comment]
Hi,

Thanks for the replies! I have taken a look at both but I still have some questions. Am I still supposed to use @Api and @ApiOperations annotations? I'm not seeing them in any examples and I can't get them to autocomplete (EnableSwagger2 works though). I do see in an example things like Docket and ApiInfo. Am I supposed to use these methods instead of the annotations? Also, should I still have the swaggerConfiguration in the applicationContext xml? I saw the other example that uses the spring mvc and that doesn't import from spring fox in the java files and uses the original annotations from wordnik. Should I still use those annotations or upgrade to springfox?

Thanks again!

**Comment by Cpruce** [comment]
Hi,

I have gotten the swagger-ui.html page up using springfox; however, I have not been able to pull up /v2/api-docs. I've allowed that path extension in my applicationContext security and followed the spring-xml-swagger springfox demo. The base-package hasn't changed from the springmvc one and @RequestMapping's are still in place. Is there anything I am missing?

**Comment by dilipkrish** [comment]
Could you perhaps share a repo with your configuration and setup. Its hard to diagnose without being able to visualize your application

**Comment by Cpruce** [comment]
Sure can I email you my configs? If so, what's your address? You can email me at corypruce [at] gmail [dot] com

**Comment by Cpruce** [comment]
My ApplicationSwaggerConfig looks like

import springfox.documentation.swagger2.annotations.EnableSwagger2;

import java.util.List;


@EnableSwagger2
public class ApplicationSwaggerConfig {

    private String apiVersion;
    private List excludedResources;
    private String basePath;

    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
    }

    public String getApiVersion() {
        return apiVersion;
    }

    public void setExcludedResources(List excludedResources) {
        this.excludedResources = excludedResources;
    }

    public List getExcludedResources() {
        return excludedResources;
    }

    public void setBasePath(String basePath) {
        this.basePath = basePath;
    }

    public String getBasePath() {
        return basePath;
    }
}

The applicationContext-webmvc.xml contains

<context:component-scan base-package="com.gram.pds" use-default-filters="true" />
    <context:annotation-config/>
    <aop:aspectj-autoproxy proxy-target-class="true"/>



    
    

    
    <mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/"/>
    <mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/"/>


    
    <bean name="/applicationSwaggerConfig" class="com.gram.pds.search.swagger.ApplicationSwaggerConfig">



and it used to contain 


<bean id="documentationController" class="com.mangofactory.swagger.spring.controller.DocumentationController" />

    <bean id="swaggerConfiguration" class="com.mangofactory.swagger.SwaggerConfiguration">
        <property name="basePath" value="${swagger.basePath}"/>
        <property name="apiVersion" value="1.0"/>
        <property name="excludedResources">
            <list>
                <value>/errors/*</value>
            </list>
        </property>

    </bean>


and in applicationContext-security.xml, I allowed

    <security:http pattern="/api-docs/**" security="none" />
    <security:http pattern="/v2/api-docs/**" security="none" />
    <security:http pattern="/swagger-ui.html" security="none" />
    <security:http pattern="/webjars/springfox-swagger-ui/**" security="none" />
    <security:http pattern="/springfox/**" security="none" />




Please let me know if you need more information. I am having trouble seeing the /v2/api-docs/

**Comment by dilipkrish** [comment]
This may not help much but could see what happens when you change the applicationContext-security.xml to

```xml
  <security:http pattern="/api-docs" security="none" />
    <security:http pattern="/v2/api-docs" security="none" />
    <security:http pattern="/swagger-ui.html" security="none" />
    <security:http pattern="/webjars/springfox-swagger-ui/**" security="none" />
```

Also your ApplicationSwaggerConfig doesn't look right, there is no `Docket` so your customizations like  setExcludedResources etc will not work.

what does your web.xml look like?

**Comment by Cpruce** [comment]
I took the springfox pattern out and changed the api-docs but I still got the 404 on /v2/api-docs. Here is practically all of the web.xml

<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<web-app xmlns="http://java.sun.com/xml/ns/j2ee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         version="2.4" xmlns:context="http://www.springframework.org/schema/context"
         xmlns:mvc="http://www.springframework.org/schema/mvc"
         xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">




    
    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
            classpath*:applicationContext-profiles.xml
            classpath*:applicationContext-cache.xml
            classpath*:applicationContext-security.xml

        </param-value>
    </context-param>

    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>

    <servlet>
        <servlet-name>spring</servlet-name>
        <servlet-class>
            org.springframework.web.servlet.DispatcherServlet
        </servlet-class>
        <init-param>
            <param-name>contextConfigLocation</param-name>
            <param-value>
                classpath*:applicationContext-profiles.xml
                classpath*:applicationContext-security.xml
                classpath*:applicationContext-cache.xml
                classpath*:applicationContext-webmvc.xml
            </param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
        <servlet-name>spring</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>

    <servlet-mapping>
        <servlet-name>default</servlet-name>
        <url-pattern>/web/*</url-pattern>
    </servlet-mapping>




    <filter>
        <filter-name>MDCCleanupServletFilter</filter-name>
        <filter-class>com.gram.pds.search.logging.v10.MDCCleanupServletFilter</filter-class>
    </filter>
    <filter>
        <filter-name>springSecurityFilterChain</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>
	<filter>
		<filter-name>CharacterEncodingFilter</filter-name>
		<filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
		<init-param>
			<param-name>encoding</param-name>
			<param-value>UTF-8</param-value>
		</init-param>
		<init-param>
			<param-name>forceEncoding</param-name>
			<param-value>true</param-value>
		</init-param>
	</filter>

    <filter-mapping>
        <filter-name>MDCCleanupServletFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
    <filter-mapping>
        <filter-name>springSecurityFilterChain</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
	<filter-mapping>
		<filter-name>CharacterEncodingFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>


Any think standout? Thanks for the help!!

**Comment by Cpruce** [comment]
Hey could you just list the necessary steps for generating the json?

**Comment by dilipkrish** [comment]
It's hard to give specific steps for your set up by looking at pasted code (which also happens to be verbose). Would you mind sharing your repository?

**Comment by Cpruce** [comment]
Well the repo is proprietary and I've already given all the config's relating to swagger so (also in retrospect now) giving you anymore would've been unhelpful. Regardless, I built another documentation service in so I will not be inquiring about this project anymore.
