### ISSUE TITLE
How to configure spring integration

### ISSUE THREAD

**Issue by ghost** [springfox/springfox#797]
Hi,

I am very interested in springfox, especially to use it with Spring Integration. We have a lot of REST services exposed via http inbound gateways. 
I have seen there is a closed question about that https://github.com/springfox/springfox/issues/550 but I could not figured out how to configure springfox to scan for Spring Integration resources.

Is there any documentation about it? Or could you give me a hint how to do that?

Thanks for your help!

**Comment by dilipkrish** [comment]
@szabosolticzky would like to provide support for spring integration via a pr? We totally don't have the bandwidth to support this for now

**Comment by monkeylon** [comment]
Hi, I have currently used springfox for REST APIs which works perfectly but would also like it to pickup Spring Integration created inbound APIs. I came across this post which is now 2 years old, has anyone found a way to do this now?

**Comment by the4dk** [comment]
Hi, another year has passed :) Is is now possible to document Spring Integration endpoints? Would it be possible for someone to at least provide a short example on how to do this?

**Comment by dilipkrish** [comment]
@the4dk actually, @dschulten is [working on adding support](https://github.com/escalon/springfox/tree/feature/spring-integration-support) for that and I'm pretty sure he could use some help with testing.

**Comment by dschulten** [comment]
@the4dk for testing, please build my version at https://github.com/escalon/springfox/tree/feature/spring-integration-support (clone, switch to branch feature/spring-integration and build) see the readme for details: https://github.com/escalon/springfox/blob/feature/spring-integration-support/springfox-spring-integration/README.md

**Comment by dilipkrish** [comment]
Thank you @dschulten for your help! Im about to release 3.0.0 ... finally!
