### ISSUE TITLE
Response of type "array" is not rendered in springfox swagger-ui

### ISSUE THREAD

**Issue by GitVhaos** [springfox/springfox#798]
<b>Having Controller-method:</b>

  @RequestMapping(value = "/someResource", method = RequestMethod.GET, produces = APPLICATION_JSON_UTF8_VALUE)
  public ResponseEntity<List<someResource>> readResources();

<b>Following swagger-json will be generated:</b>

"responses":{
               "404":{ },
               "200":{
                  "description":"OK",
                  "schema":{
                     "type":"array",
                     "items":{
                        "$ref":"#/definitions/someResource"
                     }
                  }
               },
...

=> Which seems OK for me!

<b>Checking the "Response Class" section the "Model Schema" is shown like:</b>

[
  {
    "attribute1": "string",
    "attribute2": true,
  }
]

<b>BUT switching to "Model" there`s only an empty array:</b>

 array {
} 

<b>Is there any known issue for rendering problems on using Lists in swagger-ui 2.0.0 ?</b>

**Comment by dilipkrish** [comment]
This may be an issue with swagger-ui, you will probably need to create an issue in that project.

**Comment by GitVhaos** [comment]
Sorry I don`t get the point. This is springfox issue management. There may be a bug in springfox-swagger-ui. In which other project I have to create an new issue? Can you please offer me some more details on the issue?

**Comment by dilipkrish** [comment]
[swagger-ui](https://github.com/swagger-api/swagger-ui) is the project that you need to creat the issue in. springfox-swagger-ui is only a shell that wraps some
Convenience features around it.

**Comment by GitVhaos** [comment]
So u were right ;-) https://github.com/swagger-api/swagger-js/issues/270
Will be fixed when springfox-swagger-ui is using 2.1-M2 swagger-ui!

**Comment by GitVhaos** [comment]
Working in Swagger-Springfox 2.2.2
