### ISSUE TITLE
Allowable Values for enumerations on response models do not render options

### ISSUE THREAD

**Issue by GitVhaos** [springfox/springfox#801]
I`m not shure if this has to be adressed for swagger-spec or springfox-swagger:

When returning an Java-Enum it would be nice to see the "allowable Values" of this enum as possible results in the generated json-output. For using enums as Parameters this is already working, but not for using enums as response-object.

Where do I need to adress this feature?

<b>Example:</b>
```java
@RequestMapping(value = "/someResource", method = RequestMethod.GET)
  public ResponseEntity<SomeEnum> readResource()
```

**Comment by dilipkrish** [comment]
This is probably already working. Just that the swagger-ui doesn't show it

**Comment by GitVhaos** [comment]
Unfortunately not... In JSON-Sepc the enum is only shown as:

   "200":{
                  "description":"OK",
                  "schema":{
                     "type":"string"
                  }
               },

**Comment by kevinconaway** [comment]
@dilipkrish WRT #810, I'm happy to work on this if you can provide direction on what the response should look like.  Is it not supported in the swagger 2.0 spec?  Or just not in springfox.

**Comment by dilipkrish** [comment]
That would be awesome! For sure, swagger 1.2 doesn't support this notion. Swagger 2.0 does. 

Haven't really seen what the effort to support this is. If I remember right, it's a matter of having either the model ref expose allowable values or introduce this in the mapping layer for 2.0 such that it doesn't break the case where enums or list of enums are properties of input parameters. Will provide more details when I look at the code

**Comment by kevinconaway** [comment]
@dilipkrish any idea on the above?  I'm still not sure what this should look like in the swagger json

**Comment by dilipkrish** [comment]
In swagger 2: [this](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/test/resources/contract/swagger2/declaration-business-service.json#L201-L234) would look like this

```json
        "/businesses/typeEcho": {
            "post": {
                "tags": [
                    "business-service"
                ],
                "summary": "businessTypeEcho",
                "operationId": "businessTypeEchoUsingPOST",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "business",
                        "description": "business",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string",
                            "enum": [ //<----
                              "PRODUCT", 
                              "SERVICE"
                            ]
                        }
                    }
                }
            }
        }
```
 after the fix. 

I think swagger 1 would remain as-is as it doesn't support a enums or list of enums in return types. Hope thats points you in the right direction.

**Comment by dilipkrish** [comment]
@kevinconaway you think you'd be able to get to this? planning a 2.1 release soon. If not ill push this to the next minor release (2.2.0)

**Comment by kevinconaway** [comment]
Sorry, I've been swamped lately.  Please don't wait on me for a release.

**Comment by dilipkrish** [comment]
@kevinconaway thanks for the heads-up. I've been swamped lately as well, so I moved it to 2.2.0 :)

**Comment by kevinconaway** [comment]
In the example I have in #810, it looks like this should be the desired outcome. Will you confirm?

```javascript
"permissions": {
                    "type": "array",
                    "description": "Permissions to apply",
                    "items": {
                        "type": "string"
                    },
                    "enum": [
                        "read",
                        "write"
                    ]
                }
```

**Comment by dilipkrish** [comment]
:+1: thats what I'd expect. however I'm not sure how the `@ApiModel` and `@ApiModelProperty` on the enum affects it. If I were to guess, I think `@ApiModelProperty` is going to be ignored.

**Comment by kevinconaway** [comment]
Looks like the Swagger model is incorrect then.  I would think (ArrayProperty)[https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/properties/ArrayProperty.java] would have an _enum_ field like `StringProperty` does.

**Comment by dilipkrish** [comment]
Sorry I mis-spoke...

```javascript
"permissions": {
    "type": "array",
    "description": "Permissions to apply",
    "items": {
        "type": "string"
        "enum": [
             "read",
             "write"
        ]
    },
}
```

**Comment by kevinconaway** [comment]
I tried that out and it doesn't render correctly in either Swagger UI or the Swagger editor (http://editor.swagger.io/=)

Try it out with the following Swagger JSON

```javascript
{
  "swagger": "2.0",
  "info": {
    "description": "Api Documentation",
    "version": "1.0",
    "title": "Api Documentation",
    "termsOfService": "urn:tos",
    "contact": {
      "name": "Contact Email"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "host": "localhost:__PORT__",
  "basePath": "/",
  "tags": [
    {
      "name": "enum-service",
      "description": "Service that return enums"
    }
  ],
  "produces": [
    "application/xml",
    "application/json"
  ],
  "paths": {
    "/enums/collection": {
      "get": {
        "tags": [
          "enum-service"
        ],
        "summary": "Example with enum collection",
        "operationId": "getCollectionValueUsingGET",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "*/*",
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/EnumCollection"
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "petstore_auth": {
      "type": "oauth2",
      "authorizationUrl": "http://petstore.swagger.io/api/oauth/dialog",
      "flow": "implicit",
      "scopes": {
        "write:pets": "modify pets in your account",
        "read:pets": "read your pets"
      }
    },
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "definitions": {
    "EnumCollection": {
      "properties": {
        "types": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "enum": [
            "ONE",
            "TWO"
          ]
        }
      }
    }
  }
}
```

**Comment by dilipkrish** [comment]
I need to dig in to it some more. I may be totally incorrect here :speak_no_evil:  but, it suspect that this is a bug with the swagger-editor rather than the models.

**Comment by kevinconaway** [comment]
That would be a bummer.  Both swagger editor and swagger UI render that model exactly the way I would expect them to.

Unfortunately both the swagger spec (and the JSON schema spec) are horribly confusing with respect to enums so I can't confirm what the syntax should be.

Do you want me to open an issue in swagger-core to follow up on this to get their opinion?

**Comment by kevinconaway** [comment]
After digging in to the code, it looks like the issue I reported in #810 is slightly different than what is reported here.  Your analysis below is spot on:

>Haven't really seen what the effort to support this is. If I remember right, it's a matter of having either the model ref expose allowable values or introduce this in the mapping layer for 2.0 such that it doesn't break the case where enums or list of enums are properties of input parameters. Will provide more details when I look at the code

The _responseModel_ field on the operation is just a `ModelRef`.  Since plain enums get represented as the _string_ type, there is no model to refer to per se.

Not sure what the best approach is.  Perhaps to carry around the `ResolvedType` in the `ModelRef` so that the allowable values can be calculated later?

**Comment by kevinconaway** [comment]
> I need to dig in to it some more. I may be totally incorrect here :speak_no_evil: but, it suspect that this is a bug with the swagger-editor rather than the models. 

Hmm, looks like swagger-ui considers this a [bug](https://github.com/swagger-api/swagger-ui/issues/1381)

**Comment by kevinconaway** [comment]
More information in [this issue](https://github.com/swagger-api/swagger-js/issues/198) from [swagger-js](https://github.com/swagger-api/swagger-js/)

It looks like you were correct above.

I guess the reason both Swagger UI and Swagger codegen exhibit the same behavior is that they both use the swagger-js API

**Comment by dilipkrish** [comment]
Wow thanks for getting to the bottom of it! :metal:

**Comment by kevinconaway** [comment]
So I'll implement it the way you specified in https://github.com/springfox/springfox/issues/801#issuecomment-121335666

Let me know your thoughts on https://github.com/springfox/springfox/issues/801#issuecomment-121343930 and what you think is the best way forward

**Comment by dilipkrish** [comment]
My personal inclination is to create an allowable values attribute on ModelRef. I'd rather *NOT* have the resolved types exposed in with the ModelRef objects because 99/:100: these will be primitive types, specifically numbers that support allowable ranges, and strings that support allowable lists. Secondly they are refs, so they are by definition, representations of models defined elsewhere. 

Since the swagger models are driving the design of some of the internal models, we're having to shoe horn this usecase into a `ModelRef`. The `allowableValues` property in the `ModelRef` itself seems like a bit of a hack to me. Since `ModelRef` is an internal data structure which is consumed by an internal mapping layer, it seems like a reasonable compromise. Something that we can fix without breaking library consumers.

Ideally, this should've been modeled as an inlined model primitive property perhaps an `InlinedModel`, which is what it is. I'll create a story to re-work the internal models to accommodate the right long term data structures.

Hope thats makes sense... :confused:?

**Comment by kevinconaway** [comment]
>Since the swagger models are driving the design of some of the internal models, we're having to shoe horn this usecase into a ModelRef. The allowableValues property in the ModelRef itself seems like a bit of a hack to me. Since ModelRef is an internal data structure which is consumed by an internal mapping layer, it seems like a reasonable compromise. Something that we can fix without breaking library consumers.

Yep, that was my read of the design as well, thanks.

**Comment by GitVhaos** [comment]
@dilipkrish / @kevinconaway 
Only for understanding: When returning plain java enum in Spring Controller Method, the allowable values should get listed in swagger-ui / json? Or is some additional Annotation e.g. needed?

Maybe you can add an example?

Using swagger 2.2.2 returning an java enum via "return new ResponseEntity<SomeJavaEnum>(SomeJavaEnum.Value, HttpStatus.OK);" I only get "{"description":"OK","schema":{"type":"string"}}" in generated json spec....
