### ISSUE TITLE
Swagger-client.js nullifies recieved content-type.

### ISSUE THREAD

**Issue by giscaion** [springfox/springfox#802]
Swagger-client.js removes consumes recieved from spring-fox server controller, this way the requests could not reach the server, cause content-type is not setted in headers.

**Comment by dilipkrish** [comment]
Could you provide an example that reproduces this issue? Is this a swagger-client bug Or a springfox bug?

**Comment by giscaion** [comment]
I have this kind of mapping from server side : @RequestMapping(value = "/projects", method = RequestMethod.GET, consumes = LIST_MEDIA_TYPE, produces = LIST_MEDIA_TYPE)
where LIST_MEDIA_TYPE is a custom type application/vnd.list-1+json, 
from swagger generated page api.html i have same type in combobox selected as the only one option , but the Header Content-Type is not send

**Comment by dilipkrish** [comment]
In that case could you please open a bug with the swagger-ui project?

**Comment by dilipkrish** [comment]
The swagger-ui project is [available here](https://github.com/swagger-api/swagger-ui) for issues. Closing this issue
