### ISSUE TITLE
Response Content Type down is NOT showing the proper content type in version above 0.8.8

### ISSUE THREAD

**Issue by ahmadimt** [springfox/springfox#808]
Hi,

The drop down against Response Content Type  is not showing proper content type.The below image is for com.mangofactory:swagger-springmvc:1.0.2
![image](https://cloud.githubusercontent.com/assets/10077189/8282474/aa773f36-190e-11e5-9354-f82194da4de1.png)

However, same thing is getting displayed properly with version: 0.8.8 as shown below:
![image](https://cloud.githubusercontent.com/assets/10077189/8282605/88e55172-190f-11e5-8def-3cfde8c19679.png)

**Comment by igilham** [comment]
I found the same thing in my Spring Boot application using Spring Web MVC.

In my case the fix was to ensure the [`@RequestMapping`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestMapping.html#produces--) included a definition for `produces`

```java
@RequestMapping(method = RequestMethod.GET, produces = "application/json")
@ApiOperation(value = "get a thing", response = Thing.class)
@ResponseBody
private Thing getThing() {
    // ...
}

```

**Comment by dilipkrish** [comment]
Will add this a feature to allow specification of default content type. Currently it's defaulted to the *any* media type when none is specified

**Comment by dilipkrish** [comment]
@ahmadimt, @igilham  The other way to do this is to add defaults to the docket during the configuration.

```java

    docket
    ...
        .produces(newArrayList("application/json") //Or whatever default value(s)
        .consumes(newArrayList("application/json") //Or whatever default value(s)
    ...
```
