### ISSUE TITLE
swagger springfox unable to initialize when moving from 2.0.1 to >2.0.2

### ISSUE THREAD

**Issue by roya2** [springfox/springfox#812]
Seems like a memory leak issue while initializing springfox 2.0.2+
Everything seems to work fine in 2.0.1 but any newer version than that seems to take up a lot of memory(>2GB) and the application is never able to start up.

While tailing swagger info logs we notice the endpoint initialization going slower and slower, until it runs out of memory and just stops. 

We have around 100 resources with CRUD+ endpoint for each resource and we use all the major swagger annotations.
Please note previous version (2.0.1) works fine, so we had to revert back.

Please let me know if there are any possible solutions for this, since it prevents us from upgrading to newer versions.

**Comment by dilipkrish** [comment]
@roya2 that is the truth! There is a fix in the works #806. Should have a fix out soon.

Closing this as a duplicate.
