### ISSUE TITLE
Announcement: Release 2.0.3 - Inprogress

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#814]
Includes major bug fix that caused degraded performance and a few minor bug fixes

# Bugs
- #806 Improve performance of model processing maintenance (Thanks @RizziCR and @RobWin for reporting)
    - #811 Slow Startup - Spring Boot @bryantp
    - #812 swagger springfox unable to initialize when moving from 2.0.1 to >2.0.2 @roya2 
- #805 ApiOperation response doesn't work Thanks! @EdwardsBean
#813 Duplicate Params - Swagger Spec and in Generated Code Thanks! @rajeshkamal  2.0.3

# Contributions
- #803 [Documentation] Added note on @EnableWebMvvc conflict when using Spring Boot Thanks! @igilham

# Maintenance
- #804 CircleCI no longer publishes the snapshot builds bug maintenance

**Comment by dilipkrish** [comment]
This has been released! Thanks everyone!

**Comment by rajeshkamal** [comment]
@dilipkrish Will it also be part of maven central.

**Comment by dilipkrish** [comment]
yes it takes a while to sync however

**Comment by RobWin** [comment]
Thx @dilipkrish
