### ISSUE TITLE
Swagger UI support for Maps in response models

### ISSUE THREAD

**Issue by cabbonizio** [springfox/springfox#815]
Hi, I came across an issue where I have a response model with an attribute of type Map and it's not being shown in the Swagger UI.   I'm currently using the 2.0.2-RELEASE of both springfox-swagger2 and springfox-swagger-ui.  I've done some research and this seems to be a limitation of Swagger UI not really an issue with SpringFox, but wanted to see if there were any known workarounds, suggestions, or at the very least could we keep this open to have visibility on this until Swagger UI supports it.  

For example:
@JsonProperty("products")
Map &lt;String, Product> products;

Here's how it shows up in the UI:
![image](https://cloud.githubusercontent.com/assets/6088654/8330261/2e8ec01a-1a4e-11e5-9530-266c3cd5214e.png)

I found this open issue for SwaggerUI that I'm pretty sure needs to get resolved in order for SpringFox to support it:
https://github.com/swagger-api/swagger-ui/issues/558

Thanks for your support!

**Comment by cabbonizio** [comment]
@dilipkrish guess what?   I just upgraded to 2.0.3 RELEASE for springfox-swagger2 and this issue is resolved!  I didn't notice it in the release notes, but I just tried upgrading it anyway and was pleasantly surprised!  Should I let you be the one to close it?

![image](https://cloud.githubusercontent.com/assets/6088654/8369817/6e911a24-1b8d-11e5-9aa0-c2685bf5258f.png)

**Comment by dilipkrish** [comment]
:metal: Closing it, but you could've closed it as well :)
