### ISSUE TITLE
Importing maven dependencies 

### ISSUE THREAD

**Issue by Cpruce** [springfox/springfox#816]
Hey,

So I am starting with a blank slate now without swagger dependencies and swagger-springmvc. However, when I put the dependencies 

 
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.0.1</version>
        </dependency>

They do not resolve. Any suggestions why? Would really appreciate some help :) @dilipkrish @t0tec

**Comment by dilipkrish** [comment]
Try 2.0.3 in a bit, It takes a day to sync maven central but it should work just fine.
