### ISSUE TITLE
Maps of maps are not correctly handled

### ISSUE THREAD

**Issue by cbornet** [springfox/springfox#817]
The following attribute:
```java
private Map<String, Map<String, Foo>> bar;
```
gets modeled as:
```json
 "bar": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/Map«string,Foo»"
          }
        }
```
instead of:
```json
 "bar": {
          "type": "object",
          "additionalProperties": {
                  "type": "object",
                  "additionalProperties": {
                    "$ref": "#/definitions/Foo"
                  }
          }
        }
```

**Comment by dilipkrish** [comment]
I think that's the right behavior. U should see the definition for `Map<string,Foo>` elsewhere in the definitions section.

**Comment by cbornet** [comment]
Indeed, the Map<string, Foo> is in the definitions. It may not be invalid but it is really really ugly ...
Most swagger-codegen will fail with such a curious name as it is generally used to name a class in the model (eg. I have a Map<string, Foo>.java file generated).
There is also a useless
```json
"Map«string,Map«string,Foo»»": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/Map"
      }
    }
```
that gets generated in the definitions (and no "Map" of course).

**Comment by dilipkrish** [comment]
It is a bug that you should see `"#/definitions/Map"` in the `$ref`. However if you need to use the swagger description for code generation there is a `.forCodeGeneration()` option in the Docket configuration (see [section 5.5.3](http://springfox.github.io/springfox/docs/current/#docket-spring-java-configuration))

**Comment by cbornet** [comment]
I think the bug is that ```"Map«string,Map«string,Foo»»"``` is present since no operation uses it (additionalproperties is used instead).
I didn't know about ```.forCodeGeneration()``` !. This looks exactly like what I need :-). I will try it asap, thx very much.

**Comment by dilipkrish** [comment]
BTW what version of the library are using?

**Comment by cbornet** [comment]
I use version 2.0.3.

**Comment by cbornet** [comment]
I tested with latest 2.3.1 and the issue with the unwanted class is still present.
```java
    @RequestMapping(value = "mapOfMapOfExample", method = RequestMethod.GET)
    public Example mapOfMapOfExample() {
        throw new UnsupportedOperationException();
    }

}

class Example {
    public Map<String, Map<String, Foo>> foo; 
}

class Foo {
    public Integer fooInt; 
}
```
generates an unwanted
```json
        "MapOfstringAndMapOfstringAndFoo":
        {
            "type": "object",
            "additionalProperties":
            {
                "$ref": "#/definitions/Map"
            }
        },
```
which causes problems when using clients such as swagger-codegen.
Can we reopen the issue or should I open a new one ?

**Comment by dilipkrish** [comment]
I think its fixed in the latest snapshot (should be releasing that pretty soon). Would be great if you could confirm with 2.4.0-SNAPSHOT.

**Comment by dilipkrish** [comment]
@cbornet Yeah I see that... would you mind opening another issue?
