### ISSUE TITLE
Request body schema empty in version 2.0.3

### ISSUE THREAD

**Issue by igilham** [springfox/springfox#819]
Upgrading my springfox library from 2.0.2 to 2.0.3 (#814) seems to have caused a regression.

The request parameters section for a POST to my API now shows an empty JSON hash `{}` in the model schema. In version 2.0.2, it works flawlessly.

I haven't had time to dig any deeper yet. I'll update the ticket if I get a chance to.

**Comment by dilipkrish** [comment]
Would appreciate if you could provide steps to reproduce or a breaking test perhaps.

**Comment by igilham** [comment]
Hi @dilipkrish. I can still reproduce this by only changing the dependency version in my `pom.xml`. I haven't had time to assemble a minimal example or test case. I'll let you know if I can get something together.

**Comment by dilipkrish** [comment]
@igilham any updates on this? Has this been resolved

**Comment by igilham** [comment]
@dilipkrish I'm afraid not. I haven't had the time to experiment or dig into a root cause.

**Comment by dilipkrish** [comment]
Im closing this issue for now. Please reopen when you have some details.
