### ISSUE TITLE
Body content is not sent in GET Method

### ISSUE THREAD

**Issue by Jacharp** [springfox/springfox#820]
Giving following method :
@RequestMapping(value = "/user/{id}", method = RequestMethod.GET, produces = APPLICATION_JSON_VALUE)
public ResponseEntity<User> get(@PathVariable String id, @RequestBody Context context) {
  // do get User with context
}
when I use swagger(and springfox), I get below reponse body:
{
  "timestamp": "2015-06-29T09:23:01.312+0000",
  "status": 400,
  "error": "Bad Request",
  "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
  "message": "Required request body content is missing: org.springframework.web.method.HandlerMethod$HandlerMethodParameter@2069cf57",
  "path": "/api/user/11"
}

It seems request body (i.e context) is not attached to the request.

**Comment by dilipkrish** [comment]
I think per the HTTP spec, the server-side support is really iffy at best. To [quote Roy Fielding](http://stackoverflow.com/a/983458/19219)

> So, yes, you can send a body with GET, and no, it is never useful to do so.

**Comment by Jacharp** [comment]
Thanks for your answer.

**Comment by wind57** [comment]
This is sort of harsh with would not fix actually. Suppose our case, when we might get a paginated result and we ask for a number of objects via @RequestBody. So this will not get ever fixed?
