### ISSUE TITLE
Configuring authorization 

### ISSUE THREAD

**Issue by poliveiraTDsis** [springfox/springfox#821]
I am trying to understand how i can configure security schemes to each of my services, but i cound not reach a proper configuration with the demos and samples, can give me a hand on this issue ?

actual code:
```java
@Bean
	public Docket swaggerSpringMvcPlugin() {
		return new Docket(DocumentationType.SWAGGER_2).groupName("xxxx").select().apis(RequestHandlerSelectors.any())
				.paths(paths()).build().apiInfo(apiInfo()).securitySchemes(scopes());
	}

	private List<SecurityScheme> scopes(){
		List<AuthorizationScope> scopes = new ArrayList<AuthorizationScope>();
		scopes.add(new AuthorizationScope("ECHO_GET_MSG", "see echo"));
		
		
		List<GrantType> grantTypes = new ArrayList<GrantType>();
		ImplicitGrant implicitGrant = new ImplicitGrant(new LoginEndpoint(applicationSettings.getBaseUrl()+"/oauth/token"), "access_token");
		grantTypes.add(implicitGrant);
		
		List<SecurityScheme> response = new ArrayList<SecurityScheme>();
		OAuth auth = new OAuth(AuthorizationType.OAUTH2.toValue(), scopes, grantTypes);
		response.add(auth);
		
		return response;
	}
```

**Comment by dilipkrish** [comment]
Just to give you a high level idea without getting into the code, security has different pieces that all work together in concert
- The API itself needs to be protected. This is achieved by using, for simplicity sake, spring security and may also use a combination of servlet container and tomcat/jersey etc.
- The security scheme which describes the techniques you've used to protect the api. Spring fox supports whatever schemes swagger specification supports (ApiKey, BasicAuth and OAuth2 (certain profiles))
- Finally the security contexts which actually provides information on which api's are protected by which schemes. 

I think in your example, you're missing the last piece of the puzzle, the [security context](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-boot) see **15**.
