### ISSUE TITLE
springfox-staticdocs does not supports Swagger api group.

### ISSUE THREAD

**Issue by hantsy** [springfox/springfox#823]
I configured SwaggerConfig with api group support. 

But when generated from `get("/v2/api-docs")`, it did not generate docs in `src/docs`. I have to appended `group` parameter to the url `v2/api-docs`, i.e.

    /v2/api-docs?group=user-api

But this url only generated the APIs defined as `user-api` group in the `SwaggerConfig`.

**Comment by dilipkrish** [comment]
@RobWin Do you know what needs to happen to fix this issue?

**Comment by RobWin** [comment]
How does the response from get("/v2/api-docs") look like? Is it the default group?
I thought you always have to specify the group name to get the correct Swagger JSON?

**Comment by hantsy** [comment]
Get nothing from `/v2/api-docs` directly(blank page in firefox). I have to append `group` parameter to get related API docs.

**Comment by RobWin** [comment]
Yes. That's as expected, since the default group does not exist if you specify a different group name in your SwaggerConfig .
Correct @dilipkrish ?

**Comment by hantsy** [comment]
If I repeat the generation codes for very group, how to merge the generated docs into one pdf/epub/html finally?

**Comment by RobWin** [comment]
Do you use maven or gradle?

**Comment by hantsy** [comment]
I used Maven.

**Comment by RobWin** [comment]
You can generate the docs into different folders, e.g. `${buildDir}/asciidoc/group1` and `${buildDir}/asciidoc/group2`.
Then you could create a `index.adoc` which looks as follows

include::{buildDir}/asciidoc/group1/paths.adoc[]
include::{buildDir}/asciidoc/group1/definitions.adoc[]

include::{buildDir}/asciidoc/group2/paths.adoc[]
include::{buildDir}/asciidoc/group2/definitions.adoc[]

**Comment by RobWin** [comment]
If you need more help. Please join https://gitter.im/Swagger2Markup/swagger2markup

**Comment by RobWin** [comment]
More help, costs you a Star on GitHub :)

**Comment by hantsy** [comment]
Thanks for your help.  I will try to add a custome index assiidoc for these docs.

I have used this project and former `swagger-springmvc` in several projects. Thanks for your work.

**Comment by RobWin** [comment]
I mean https://github.com/Swagger2Markup/swagger2markup not Springfox :)

**Comment by hantsy** [comment]
Thanks, I will read the reference documentation carefully, and use it with `spring-restdocs` together for producing our API docs.

**Comment by RobWin** [comment]
If you also want to use spring-restdocs, you should only generate the Swagger JSON in the unit test and do the Swagger2Markup conversion in the build phase via  https://github.com/redowl/swagger2markup-maven-plugin. (Unfortunatly it is not released yet)
Otherwise it is difficult to run the springfox-staticdocs unit test after the spring-restdocs unit tests. It results in an ugly unit test dependency chain.

You can generate the Swagger JSON like this:
```
 String outputDir = System.getProperty("io.springfox.staticdocs.outputDir");
        MvcResult mvcResult = this.mockMvc.perform(get("/v2/api-docs")
                .accept(MediaType.APPLICATION_JSON))
                .andDo(SwaggerResultHandler.outputDirectory(outputDir).build())
                .andExpect(status().isOk())
```

**Comment by hantsy** [comment]
OK, I will try it later. If I encounter new problems, I will chat in gitter.im. Thanks for your help.

**Comment by RobWin** [comment]
You are welcome

**Comment by dilipkrish** [comment]
Thanks for helping out @RobWin. Closing this issue as resolved
