### ISSUE TITLE
Support vendor extensions in operations

### ISSUE THREAD

**Issue by cbornet** [springfox/springfox#824]
This issue is for having support of swagger vendor extensions as described in:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#vendorExtensions
Note : the swagger core already has annotations to support the extensions
```java
 @ApiOperation(value = "foo", extensions = {
            @Extension(properties = @ExtensionProperty(name="x-foo", value="bar"))
    })
```

**Comment by dilipkrish** [comment]
@cbornet This is open for extension, would you like to submit a pr with an implementation of a [OperationBuilderPlugin](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/service/OperationBuilderPlugin.java) that reads the extension properties?

**Comment by cbornet** [comment]
WIP here : https://github.com/cbornet/springfox/tree/extensions_support
