### ISSUE TITLE
Generated spec is non-deterministic - different runs different outputs

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#825]
This is some what related to the issue - https://github.com/springfox/springfox/issues/750

UserController
*****************
```
@RestController
@Api(value = "USER")
@RequestMapping("/users")
public class UserController {

    @RequestMapping(method = RequestMethod.GET, produces="application/json")
    @ResponseStatus(value= HttpStatus.OK)
    public Collection<User> getUsers() {
        throw new NotImplementedException();
    }

    @RequestMapping(method = RequestMethod.GET, produces="application/json", params={"status"})
    @ResponseStatus(value= HttpStatus.OK)
    public Collection<User> getUsersByStatus(@RequestParam(value="status") String status) {
        throw new NotImplementedException();
    }

}
```

RUN 1 - Generated Spec
*****************************
Contain the spec for method getUsers() in the UserController
```
"/api/users": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Get the list of users",
        "description": "getUsers",
        "operationId": "getUsers",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Resources"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
```
RUN 2 - Generated Spec
*****************************
Contain the spec for method getUsersByStatus() in the UserController
```
"/api/users": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Get the list of users by status",
        "description": "getUsersByStatus",
        "operationId": "getUsersByStatus",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "status",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Resources"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
```
Though I completely understand that the Swagger Core SPEC by itself does not have support for this yet.

Until then whatever that gets produced should be deterministic and usable. Some issues that I can see here,
1. The generated spec is not backward compatible across multiple runs.
2. Once written an application using the generated code using the Swagger-Codegen. Because of this non-deterministic nature your client/consumer/user code might break.
3. Can we be deterministic in this. Always the same method's spec gets generated though you have many different query params based mappings.
Ex: 
1. api/users - getUsers()
2. api/users?status=single
3. api/users?status=single&sex=male

Can we get the third one because this contains all the query params. Also the generated code would look like this,
getUsersByStatusOrSex(String status, String sex); The reason I am asking to generated this method in the spec and in turn the codegen is because we could use this method and call 1 & 2 as well by passing null's accordingly.

What do you think? @dilipkrish @adrianbk

**Comment by dilipkrish** [comment]
Again thank you for pointing this out @rajeshkamal! This should be fixed (at least the ordering issue)

**Comment by dilipkrish** [comment]
This should now be fixed!
