### ISSUE TITLE
o2c.html not found

### ISSUE THREAD

**Issue by yukinami** [springfox/springfox#829]
The swagger-ui is packed as webjars in  jar `springfox-swagger-ui`. When using which oauth2, the redirecturi will be /{contextPath}/o2c.html whose path is '/webjars/springfox-swagger-ui/o2c.html' in actually (spring boot mapping /webjars/** to /resouces/webjars).  Then I have to add a redirectview to make it work.  Maybe `o2c.html` should be copied to the resouces root path too ...? Or Am I missing something ...?

**Comment by dilipkrish** [comment]
Thanks for pointing it out. Looks like we need to override the `window.oAuthRedirectUrl` property with the url to the o2c.html resource.
