### ISSUE TITLE
initOAuth in swagger-ui.html is not invoked.

### ISSUE THREAD

**Issue by yukinami** [springfox/springfox#833]
Hi~ I' m using `spring-boot` with `springfox` and my application is authenticated with oauth2.  I configured property `spring.jackson.property-naming-strategy` with value `CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES` so it would output property with underscore case. And the JSON output from springfox endpoint (/configuration/security) was underscore case too. But the `swagger-ui.html` inited with such code:

```
if (typeof initOAuth == "function" && security) {
    if (security.clientId && security.appName && security.realm) {
        initOAuth(security);
    }
}
```
As a result, the code was not invoked, and the button invoking access code was not invoke neither.

Is there some way to fix this?

**Comment by dilipkrish** [comment]
@yukinami thanks for reporting this. This is a little obscure, I think the solution is to be explicit about the property names for clientId and appName via `@JsonProperty`

**Comment by yukinami** [comment]
Understood. Thanks for the reply.  May I ask if there's a release plan recently.
