### ISSUE TITLE
@ApiResponses is suppressing "Response Content Type" drop down

### ISSUE THREAD

**Issue by dpatra1** [springfox/springfox#835]
Hi,
I am using springfox(Sagger2) for my microservice API documentation and i am having issue enabling "Response Content Type" drop down in all my APIs in Swagger-UI page.

When i am adding @ApiResponses in any method, i am not able to see the "Response Content Type" dropdown for that API in Swagger-ui.html page.

**Sample Method**
@ApiOperation(value = "createLocation", notes = "Create a business banking {@link Location}.")
@ApiResponses(value = {@ApiResponse(code = 201, message = "Successfully created a Location"),
    					   @ApiResponse(code = 409, message = "Unable to create a Location due to some error"),
    					   @ApiResponse(code = 500, message = "Internal server error")})
@SuppressWarnings("rawtypes")
@RequestMapping (method = RequestMethod.GET, value = "/fis/{fiId}/companies/{companyId}/locations")
    public ResponseEntity getLocation(@ApiParam(name = "fiId", value = "ID of the FinancialInstitution associated with the Location/Company", required = true)
    									 @PathVariable("fiId") String fiId, 
    									 @ApiParam(name = "companyId", value = "ID of the company to create a Location", required = true)
							    		 @PathVariable("companyId") String companyId, 
							    		 HttpServletRequest request, HttpServletResponse response) {
.....

On my controller class level i have declared : 
@RequestMapping (value = "/v1", consumes={MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE},
								produces={MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE})

Can someone please help me understanding whats going wrong here ? 

Thanks,
....

**Comment by dpatra1** [comment]
This is what i am using:

 		<dependency>
		    <groupId>org.apache.tomcat.embed</groupId>
		    <artifactId>tomcat-embed-jasper</artifactId>
	    	<scope>provided</scope>
		</dependency>
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.0.2</version>
		</dependency>

**Comment by dilipkrish** [comment]
Could you try with 2.0.3

**Comment by dpatra1** [comment]
Let me give a try with 2.0.3 and update you the result.

**Comment by dpatra1** [comment]
<img width="951" alt="screen shot 2015-07-07 at 7 02 09 am" src="https://cloud.githubusercontent.com/assets/12764176/8547843/60ce3056-2476-11e5-81b4-e6bc1dc52ef6.png">
<img width="952" alt="screen shot 2015-07-07 at 7 02 44 am" src="https://cloud.githubusercontent.com/assets/12764176/8547844/60d42f88-2476-11e5-9565-2e75b67e26f2.png">


After upgrading to 2.0.3, i am able to see the "Response Content Type" drop down even if i have the @ApiResponses but its completely breaking when i ma trying to test the API . I am not able to test my API from swagger-ui page. 
1) When i am selecting application/json, its giving 415 errror 
2) When i am selecting application/xml, its giving me 406 error.

I have attached the screenshot of both the scenarios.

Thanks,
D

**Comment by dpatra1** [comment]
One more point forgot to mention, in the curl command which shows in Swagger-UI, i can see always application/json no matter what i select from the "Response Content Type" dropdown

**Comment by dpatra1** [comment]
@dilipkrish - Looks like i have to declare "consumes" and "produces" in method level instead of class level declaration of @RequestMapping to make it work.

I removed 
@RequestMapping (value = "/v1", produces = {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE}, consumes = {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE})

from my class level and declaring in each method level. So its working fine.


But i am always seeing "application/json" against the curl command which shows up in swagger-ui.html. That needs to fixed i feel.

Thanks,
Deba

**Comment by dilipkrish** [comment]
I think thats a https://github.com/swagger-api/swagger-ui issue.

**Comment by dpatra1** [comment]
@dilipkrish - Do you want me to create a issue there ?

**Comment by dpatra1** [comment]
@dilipkrish - One more question, not sure who can help me with it.

I was thinking for making different groups for the APIs based upon different url patterns in the swagger-ui like:
- /v1/fis/{fiId}/businessCustomer - API urls ends with "businessCustomer" should display under "BusinessCustomer" as a hyperlink
- /v1/fis/{fiId}/companies - API urls ends with "companies" should display under "Company" as a hyperlink

Also i wanted to display the APIs in a order like GET, DELTE, PUT and POST. Something like that.

Any suggestions?

**Comment by dilipkrish** [comment]
@dpatra1 yes please create an issue in swagger-ui

You can create multiple dockets each with its own selector. and give it unique names "business" and "company". For more information on selectors look at the [reference documentation](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-boot), see items 5 and 6.

Closing this issue for now

**Comment by dpatra1** [comment]
@dilipkrish I am really confused with the withMethodAnnotation() method. When i say confused, i mean i am not sure what annotation i have to use in my methods so that it will be visible under that catagory only.

My Controller has two methods and both are having different urls in the @RequestMappings.

So i wanted to know what annotation i have to use in these two methods so that i can display them in two groups. Also that annotation has to be used in 'withMethodAnnotation' while configuring the Docket.

Example : 

@Api(value="businessCustomer", produces = "application/json, application/xml", consumes = "application/json, application/xml")
@RequestMapping (value = "/v1")
@RestController
class ApiController {
//Method 1
    @ApiOperation(value = "getBusinessCustomer", notes = "Returns a business customer resource for a Company", produces = "application/json, application/xml",
			      response = BusinessCustomer.class)
    @ApiResponses(value = {@ApiResponse(code = 200, message = "Successfully returns the business customer resource"),
					   	   @ApiResponse(code = 404, message = "Unable to found a business customer for the customerId"),
					   	   @ApiResponse(code = 400, message = "Error while retrieving business customer resource"),
					   	   @ApiResponse(code = 500, message = "Internal server error")})
    @RequestMapping (method = RequestMethod.GET, value = "/fis/{fiId}/businessCustomers/{businessCustomerId}")
    public ResponseEntity<BusinessCustomer> getBusinessCustomer(@ApiParam(name = "fiId", value = "ID of the FinancialInstitution Institution", required = true)
													    		@PathVariable String fiId, 
													    		@ApiParam(name = "businessCustomerId", value = "BusinessCustomerID is the user's unique authId that will retrieve the user's information", required = true)
													    		@PathVariable("businessCustomerId") String businessCustomerId,  
													    		HttpServletRequest request, HttpServletResponse response) {
        ......
    }

//Method 2
    @ApiOperation(value = "getCompany", notes = "Get a business banking {@link Company}, containing information that describes the company.", consumes = "application/json, application/xml",
    		      response = Company.class)
    @ApiResponses(value = {@ApiResponse(code = 200, message = "Successfully returns the Company"),
						   @ApiResponse(code = 404, message = "Not found a Company resource for the companyId"),
						   @ApiResponse(code = 400, message = "Error while retriving Company resource from repository"),
						   @ApiResponse(code = 500, message = "Internal server error")})
    @SuppressWarnings({ "rawtypes"})
    @RequestMapping (method = RequestMethod.GET, value = "/fis/{fiId}/companies/{companyId}")
    public ResponseEntity getCompany(@ApiParam(name = "fiId", value = "ID of the FinancialInstitution Institution", required = true)
						    		 @PathVariable("fiId") String fiId, 
						    		 @ApiParam(name = "companyId", value = "Unique ID of the Company", required = true)
						    		 @PathVariable("companyId") String companyId,  
						    		 HttpServletRequest request, HttpServletResponse response) throws JAXBException {
....}

}

**Comment by dilipkrish** [comment]
**:crying_cat_face: This followup question isn't related to the original issue :crying_cat_face:** 


You're welcome to create new issues at any time, but please don't pile unrelated questions on to the same thread! 

Now that you've asked, withMethodAnnotation is a predicate. If you see how we're using it in the [default ApiSelector](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/service/contexts/ApiSelector.java#L32-L34), what that is doing is saying that we DONT want to select `RequestHandlers` that have the controller annotated with `@ApiIgnore` or have the controller method annotated with `@ApiIgnore`.

In your case if you have a category called "category1" and "category2", you can create your own annotation called `@Category1` and `@Category2`. In one docket you can specify `withMethodAnnotation(Category1.class)` and in the other docket `withMethodAnnotation(Category2.class)`

Hopefully that makes sense.

**Comment by dpatra1** [comment]
Thank you for your reply !

Next time i will make sure i am create new issues for new questions.
