### ISSUE TITLE
@RequestPart that are in the body aren't represented correctly

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#836]
```java
    @RequestMapping(value = "addContactWithFile", method = RequestMethod.POST)
    @ApiOperation(value = "Add a new contact with file attachment")
    public ResponseEntity<Void> addContactWithFile(@RequestPart Contact contact, @RequestPart MultipartFile singleFile) {
        log.debug(contact.toString());
        log.debug(singleFile.getName());
        return new ResponseEntity<>(HttpStatus.OK);
    }
```

Causes an incorrect output
![swagger_ui](https://cloud.githubusercontent.com/assets/73257/8538318/63f3320e-2430-11e5-80b2-78dfb8729630.jpg)

Thanks for reporting @RizziCR!

**Comment by dilipkrish** [comment]
Looks like swagger-core doesn't support multipart-formData very well. This is a limitation with the swagger models so that it doesn't allow one to express request-parts to be expressed in as form bodys

**Comment by dilipkrish** [comment]
@RizziCR After a little bit of research [here](http://stackoverflow.com/a/30043213/19219) it seems like swagger-ui only supports the notion of form variables that are primitive types string, int etc. and not complex types that can be a `@RequestPart`

It appears the swagger-core is doing the right thing by not exposing the schema in a FormParameter. While http spec allows you to specify content types in a multipart/form-data request, its not common and it doesn't appear that its supported by tools like Postman. So until someone can tell me any different, really changing it to this style is your best bet as far as this issue is concerned.

```java
@RequestMapping(value = "addContactWithFile", method = RequestMethod.POST)
    @ApiOperation(value = "Add a new contact with file attachment")
    public ResponseEntity<Void> addContactWithFile(@RequestPart String contactId, @RequestPart MultipartFile singleFile) {
        log.debug(contactId); //<-- String variable
        log.debug(singleFile.getName());
        return new ResponseEntity<>(HttpStatus.OK);
    }

```

We can revisit this at a later point in time

**Comment by dilipkrish** [comment]
Closing this as its a very esoteric feature which has a work around. Feel free to reopen if required

**Comment by ttww** [comment]
I'v got the same problem. This case is esoteric (:-)).
It is well supported by curl and useful for transferring meta data to an an image.
If you use a simple string you lose the Swagger-GUI for easy testing and the code generation for the clients (like in our case 👎 )
So the real workaround is to change your api if you don't want to lose the code generation... :-(
How can I reopen this bug?

**Comment by dilipkrish** [comment]
I think swagger-ui doesnt support this feature. Im happy to reopen it but I don't think it belongs in this project. it should be reported in [swagger-ui](https://github.com/swagger-api/swagger-ui)
