### ISSUE TITLE
Swagger Spring MVC missing controller names

### ISSUE THREAD

**Issue by samillm** [springfox/springfox#839]
Hi,

I originally posted this [here](https://github.com/swagger-api/swagger-ui/issues/1464), but I think it might be more relevant in this repo.

Hi,

I'm trying to implement swagger and swagger ui on a spring mvc application.
I am using swagger-springmvc version 1.0.2 and swagger-spring-mvc-ui version 0.4.
Based on the instructions for implementing swagger ui and spring mvc here

I have tried both options 1 & 2
Option 1

Note: Only use this option if you don't need to customize any of the swagger-ui static content, otherwise use option 2.
Use the web-jar which packages all of the swagger-ui static content.
Requires that your app is using the servlet 3 specification.
For non-spring boot applications some extra spring configuration (ResourceHandler's) is required. See: https://github.com/adrianbk/swagger-springmvc-demo/tree/master/swagger-ui
dependencies {
...
compile "org.ajar:swagger-spring-mvc-ui:0.4"
}

![swaggerv1](https://cloud.githubusercontent.com/assets/13263272/8609456/375b2568-265a-11e5-9895-2df90390dc2a.png)

Option 2

Manually copy all of the static content swagger-ui's dist directory (https://github.com/wordnik/swagger-ui/tree/master/dist)
Provide the necessary view resolvers and resource handlers to serve the static content.
Consult the spring documentation on serving static resources.
The following is one way to serve static content from /src/main/webapp

mvc:default-servlet-handler/

![swaggerv2](https://cloud.githubusercontent.com/assets/13263272/8609443/1c030f74-265a-11e5-8fb7-4aa94794c074.png)

When I tried to implement option 1 everything worked correctly.
However, I need to use option 2 as I intend to modify the index.html page.
When trying option 2 the controller description is missing.

Here are my API-Docs:
{"apiVersion":"1.0","apis":[{"description":"Just a test","path":"/default/test","position":0}],"authorizations":{},"info":{"description":"Practice API","title":"Practice API"},"swaggerVersion":"1.2"}

I've looked at a similar question but I can't figure out what I'm doing wrong.

Please help me understand what's wrong and how I can fix it.

Thanks!

**Comment by dilipkrish** [comment]
Unfortunately, thats a very old version of the library. I would encourage you to move to 2.0.3 at the very least. There are instructions on [how to set it up from scratch](http://springfox.github.io/springfox/docs/current/#getting-started) or [migrate to the latest version](http://springfox.github.io/springfox/docs/current/#moving-from-swagger-springmvc).

**Comment by dilipkrish** [comment]
Closing this issue. If you have any problems with migrating to the newer version help is always available either in the gitter channel or issues
