### ISSUE TITLE
How To Display APIs Under Different Group Names In SwaggerUI

### ISSUE THREAD

**Issue by dpatra1** [springfox/springfox#841]
Hi

I have used springfox(swagger2) to generate the API documentation for my Micro Services.

I have almost configured all the features except one thing which i am not able to figure out yet. I saw the Petstore example and i have seen in Swagger UI , it has different group names under which the the respective APIs are listed. 

I am not sure what i am missing here. This is what i am doing but its not coming up the way i am explained.

I did created two different Docket configuration with different group name.
Filtering APIs based on the resource path.
I am able to see the dropdown on the top with the groups i have created the Docket instance.
On selection of a group from the drop down , the filtered APIs are showing up always under the name which is annotated in the controller with API(@Api(value="businessCustomer"))

*What i am expecting is, Two different groups should display in the UI with the group name i am setting on the Docket instances, with the respective APIS.

I am not sure whether this can be achieved by Docket configuration only or i have to do something on the swagger-ui side.

Thanks,
Deba

==========Docket Instance===========
@Configuration
@EnableSwagger2
@ComponentScan(basePackages = {"com.diginsite.microservices.web"})
public class SwaggerConfiguration {
	static final String detailDescription = "The `Business Banking Microservice` is a RESTful API that provides PD teams with out of the box functionality for Digital Insight's `Business Banking` suite of products. \n \n"
			+"Below is a list of available REST API calls for business banking resources.";

	@Bean
	public Docket swaggerSpringMvcPluginForCompany() {
		return new Docket(DocumentationType.SWAGGER_2)
				.groupName("bbCompany")
				.apiInfo(apiInfo())
				.select()
				.paths(bbCompanyPaths())
				.paths(bbNotCustomerPaths())
				.build()
				.useDefaultResponseMessages(false)
				.forCodeGeneration(true);
	}

	@Bean
	public Docket swaggerSpringMvcPluginForBusinessCustomer() {
		return new Docket(DocumentationType.SWAGGER_2)
				.groupName("bbCustomer")
				.apiInfo(apiInfo())
				.select()
				.paths(bbCustomerPaths())
				.build()
				.useDefaultResponseMessages(false)
				.forCodeGeneration(true);
	}

	@SuppressWarnings("unchecked")
	private Predicate<String> bbCustomerPaths() {
	      return or(
	          regex(".*businessCustomers.*"));
	}
	
	@SuppressWarnings("unchecked")
	private Predicate<String> bbCompanyPaths() {
		return or(regex(".*companies.*"));
	}
	
	@SuppressWarnings("unchecked")
	private Predicate<String> bbNotCustomerPaths() {
		return not(regex(".*businessCustomers.*"));
	}

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("Overview")
                .description(detailDescription)
                .termsOfServiceUrl("http://springfox.io")
                .contact("springfox")
                .license("Apache License Version 2.0")
                .licenseUrl("https://github.com/springfox/springfox/blob/master/LICENSE")
                .version("1.0")
                .build();
    }

====================Screenshots Of What I Am Seeing Now===================
<img width="999" alt="screen shot 2015-07-10 at 12 04 55 pm" src="https://cloud.githubusercontent.com/assets/12764176/8627072/5a55be9a-26fd-11e5-88fb-121e1a0e22bb.png">
<img width="980" alt="screen shot 2015-07-10 at 12 05 09 pm" src="https://cloud.githubusercontent.com/assets/12764176/8627073/5a55ffea-26fd-11e5-981d-a1213d2b2bcf.png">
<img width="958" alt="screen shot 2015-07-10 at 12 05 30 pm" src="https://cloud.githubusercontent.com/assets/12764176/8627074/5a575282-26fd-11e5-9323-b50dcd5daca9.png">

**Comment by dpatra1** [comment]
I did try creating different controllers for different resource type APIS and that works fine. But i wanted to achieve the same thing with a single controller which i am interested here.

**Comment by dilipkrish** [comment]
Looks like you have Customer and Company service grouped in the same controller. Its probably better anyways to group those under different controllers anyways no? 

The api description on the screen `businessCustomer` is not the name of the group. Its the name of the service. Add another service to  the docket and see what happens, it will illustrate the what I mean. 

Also swagger specification does not have a notion of a group. Its completely a springfox concept.

**Comment by dpatra1** [comment]
I did try adding a new controller and another instance of the Docket for the new controller as well.

But its coming as another option in the drop down . In that case its not solving the problem even if i will add separate controllers as well.

**Comment by dilipkrish** [comment]
what I mean to say was have one docket 2 services (in separate controllers with different names @Api is different)

```java
@Bean
public Docket swaggerSpringMvcPluginForCompany() {
    return new Docket(DocumentationType.SWAGGER_2)
            .groupName("bbCompanyOrCustomer") // < --
            .apiInfo(apiInfo())
            .select()
            .paths(bbCompanyPaths())
            .paths(bbCustomerPaths()) // < --
            .build()
            .useDefaultResponseMessages(false)
            .forCodeGeneration(true);
}
```

You should see why groups aren't displayed in the UI

**Comment by dpatra1** [comment]
Sorry did tried with a two different controllers and i can see the APIS getting listed with the service name.

I was thinking with single controller can i achieve the same thing but looks like its not feasible.

Thank you ! May be in the up coming releases some new features will come which can be enhanced later.

**Comment by gkozyryatskyy** [comment]
Is this already possible with swagger-ui?

**Comment by dilipkrish** [comment]
@gkozyryatskyy yes it is with the bundled version of swagger-ui

**Comment by kasturiswain** [comment]
@gkozyryatskyy were you able to achieve this?
which version of swagger-ui you used and what URL did you give.

**Comment by gkozyryatskyy** [comment]
@kasturiswain 
Yes I achieve this by adding my own "switch" component to index.html
```
var apiMap = {};
        apiMap["/api-docs/"] = "swagger.json";
        apiMap["/api-external/"] = "swagger-external.json";
        apiMap["/api-admin/"] = "swagger-admin.json";
```
and support it everythere

Im using swagger ui @version v2.2.10
