### ISSUE TITLE
Swagger Resources with different base paths

### ISSUE THREAD

**Issue by samillm** [springfox/springfox#843]
Hi,

I'm trying to set up swaggerresource objects pointing to two different jsons on different servers so I can display these via a swagger ui. Hence they have different base paths. 
One is at
http://localhost:8080/v2/api-docs?group=test1
The other at
http://localhost:8081/v2/api-docs?group=test2

However, when I try and set up swaggerResouces pointing to these two different pages, it seems like the location variable of a swaggerResource is a relative path.

How can I reference these two pages?

I am using swagger-springmvc version 1.0.2 and swagger-spring-mvc-ui version 0.4.

Thanks!

**Comment by dilipkrish** [comment]
@samillm Keep in mind that you need to implement a [CorsFilter](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/main/groovy/springfox/test/contract/swagger/CrossOriginFilter.java) in order to have no cross site scripting errors

**Comment by samillm** [comment]
Thanks Dilip. I am actually using springfox-swagger2 2.0.2 and springfox-swagger-ui version 2.0.0. sorry for the typo. Also thanks for the reminder on the CorsFilter, I used the one from [here](https://spring.io/guides/gs/rest-service-cors/) which looks pretty similar

**Comment by dilipkrish** [comment]
I' d recommend moving to 2.0.3 on both. Shortly 2.1.0 will be released as well
