### ISSUE TITLE
[Question] Configuration for global Operation-Parameters

### ISSUE THREAD

**Issue by GitVhaos** [springfox/springfox#845]
Im currently working on an internal API which uses two "parameters" for authentication. These two parameters have to be sent for each request to authenticate the user. The authentication mechanism is place in one central place, so no Spring Controller has these two parameters as its request-parameters. In Swagger (-UI) these parameters are now missing as Input Parameters.

In my opionion it`s no option to annotate every Controller with Swagger-Annotations declaring these parameters. Later developer will miss to configure it on new controllers. Also in a future api version I maybe want to change my authentication type without editing each Controller.

Is there an option (maybe via Docket) to configure parameters which will be added to each operation in swagger documentation?

I`m searching for something like this:

return new Docket(DocumentationType.SWAGGER_2)
    .select().build()
    .addGlobalRequestParameter(String.class, "user")
    .addGlobalRequestParameter(Integer.class, "department");

**Comment by dilipkrish** [comment]
Thats a great idea. Would you like to take a shot at implementing it.

**Comment by GitVhaos** [comment]
I will give it a try!

**Comment by GitVhaos** [comment]
I`m currenty working on this feature. It seem`s that in "OperationBuilder.parameters()" the ParameterMergers constructor arguments are incorrect. "Destination" should be the existing parameters, while "source" should be the new parameters. Internal that`s not causing a bug but is kind of confusing. Can u please check this?

**Comment by GitVhaos** [comment]
@dilipkrish I created a pull request for this feature.

**Comment by GitVhaos** [comment]
This feature is already merged with  #861 and can be closed as duplicate.

**Comment by dilipkrish** [comment]
This feature has been already implemented! via #861

**Comment by jihlee** [comment]
This is great contribution :) I recently started using SpringFox and this feature was inevitable to use OAuth2 as authentication method for my system.

My question is, is it possible to exclude some specific methods for this configuration? All of my API methods should include 'Authorization' header except some authentication related APIs. 

At the moment, I could not find the way to achieve that so my authentication API also requires 'Authorization' header which is not nice.

**Comment by GitVhaos** [comment]
Hi Jihun,
happy to hear that my contribution is also helpful for other people! 
Unfortunately I didn't had ur use case in our api. Cause we need authentication informations on every service.
You need to extend the current docket implementation to Support ur feature. I thought about a suggestion, but no "beautiful" way came to my mind...
Maybe you can replace "parameter" type with you own "GlobalParameter" type, which consist of "parameter" and a list of excluded "paths".
Regards Sven


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Jihun Lee <notifications@github.com> 
Datum: 02.02.2016  08:14  (GMT+01:00) 
An: springfox/springfox <springfox@noreply.github.com> 
Cc: GitVhaos <schulzsv@arcor.de> 
Betreff: Re: [springfox] [Question] Configuration for global
  Operation-Parameters (#845) 

This is great contribution :) I recently started using SpringFox and this feature was inevitable to use OAuth2 as authentication method for my system.

My question is, is it possible to exclude some specific methods for this configuration? All of my API methods should include 'Authorization' header except some authentication related APIs. 

At the moment, I could not find the way to achieve that so my authentication API also requires 'Authorization' header which is not nice.

**Comment by dilipkrish** [comment]
@jihlee A simple way to fix this is to have multiple dockets. One for all the other services and one for the login/logout endpoints. The login/logout endpoints don't add the global parameters

**Comment by puce77** [comment]
@dilipkrish unfortunately, multiplie dockets also means multiple group names
