### ISSUE TITLE
@ApiModelProperty annotation refuses to work in my model classes

### ISSUE THREAD

**Issue by ZMoose94** [springfox/springfox#846]
I have tried everything I cab imagine and still cannot get the @ApiModelPropery annotations in my Model classes to be reflected in the generated documentation. I am trying to use the hidden and example attributes. I have attached my swagger config class and one of my model classes. Thanks for all the help.
![code](https://cloud.githubusercontent.com/assets/12880171/8671715/29f98b2e-2a30-11e5-8881-88323016b477.PNG)

![swaggerconfig](https://cloud.githubusercontent.com/assets/12880171/8671707/20e8f204-2a30-11e5-97cb-a8fffb176d28.PNG)

**Comment by dilipkrish** [comment]
@zmoose94 unfortunately example isn't supported yet. About the hidden property, that should just work. Another thing to try to hide model attributes is to use `@JsonIgnore` Annotation.

**Comment by ZMoose94** [comment]
@dilipkrish Thank you for your quick response. Thinking about just putting an example in the notes section of @ApiOperation

**Comment by dilipkrish** [comment]
Closing this issue for now as it should've solved your problem
