### ISSUE TITLE
version 2.0.3 hidden support gone and range[] not working

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#850]
Hey,

I've upgraded to version 2.0.3 and now the hidden attribute is not not working, also the range has no effect.

    @ApiModelProperty(hidden = true, access = "hide")
    @JsonProperty(value = "_meta")

And this also:

            @ApiImplicitParam(name = "limit", "range[1, 10000]")

I have to admit that range did not work in 2.0.1 either.

**Comment by wind57** [comment]
I actually downgraded to 2.0.2 and still works fine (the hidden attribute).

**Comment by dilipkrish** [comment]
So it appears that you're not using the right packages to annotate your models. make sure your `@Api...` annotations are coming from `io.swagger.*` not the wordnik one.

**Comment by wind57** [comment]
I am using the io.swagger ones

**Comment by wind57** [comment]
I don't really care about hidden right now - I'm ok with 2.0.2 version, but what about range? Does springfox support it?

**Comment by dilipkrish** [comment]
I'm unable to reproduce this issue; for this definition

```java
@ApiOperation(value = "Delete a bundle")
    @ApiResponses(value = { @ApiResponse(code = 204, message = "NO_CONTENT"),
            @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/bundle/{bundleId}", method = RequestMethod.DELETE)
    @ResponseStatus(value = HttpStatus.NO_CONTENT)
    @ApiImplicitParams(value = {
            @ApiImplicitParam(name = "test", paramType = "header", allowableValues = "range[1,5]", dataType = "string")
    })
    public
    @ResponseBody
    ResponseEntity<Void> delete(@PathVariable String bundleId) {
        return new ResponseEntity<Void>(HttpStatus.OK);
    }
```

I get this

![swagger_ui](https://cloud.githubusercontent.com/assets/73257/8740425/11bb1402-2c0f-11e5-8d9d-f601c651568c.jpg)

**Comment by wind57** [comment]
I wish I could confirm this. I tried with io.springfox:springfox-swagger2:2.0.3. That's the only gradle deps I have. 

            @ApiImplicitParam(name = "test", paramType = "header", allowableValues = "range[1,5]")
@ApiImplicitParam(name = "limit", required = false, dataType = "int",
                    paramType = "query",
                    allowableValues = "range[1,10000]")

None of them work. I can provide any value at all - and all will pass :(
