### ISSUE TITLE
Fix for issue #552 was undone?

### ISSUE THREAD

**Issue by mikesaelim** [springfox/springfox#852]
Issue #552 dealt with the ApiResponses annotation being ignored when it was placed on an interface, and not directly on the implementing class, and it received a pretty simple fix in Issue/PR #555.  

However, it looks like some refactoring may have undone this fix, because the fix is no longer in the code and the same problem has arisen.

**Comment by dilipkrish** [comment]
More details?

**Comment by dilipkrish** [comment]
@mikesaelim Thanks for reporting! This should now be fixed!

**Comment by mikesaelim** [comment]
Great, it works now.  Thanks for fixing it so quickly!
