### ISSUE TITLE
Caching is not working for non-trivial use cases

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#858]
Externalized caches like ehcache need models to be serializable. 
Caches need to be easier to opt-in rather than be thrust on consumers.

**Comment by cabbonizio** [comment]
Adding the following cache definitions to my externalized ehcache.xml file allows 2.1.0 to work.    Please don't mind the ttl's and other properties I haven't tuned them but hoping I won't have to tune them since every client of Springfox having a cache manager would have to do this.  


	<cache name="models" maxElementsInMemory="1000"
		overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="0"
		timeToLiveSeconds="300" memoryStoreEvictionPolicy="LRU" />

	<cache name="modelProperties" maxElementsInMemory="1000"
		overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="0"
		timeToLiveSeconds="300" memoryStoreEvictionPolicy="LRU" />

	<cache name="modelDependencies" maxElementsInMemory="1000"
		overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="0"
		timeToLiveSeconds="300" memoryStoreEvictionPolicy="LRU" />

	<cache name="operations" maxElementsInMemory="1000"
		overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="0"
		timeToLiveSeconds="300" memoryStoreEvictionPolicy="LRU" />

**Comment by rkaltreider** [comment]
maybe by default springfox could use its own cacheManager which uses the concurrentMap based cache so as to not impact existing cacheManagers, and the end user would have the ability to override to use their cacheManager if they so choose? I believe spring caching abstraction supports that right?

**Comment by dilipkrish** [comment]
@cabbonizio/ @rkaltreider Couple of issues that I did not for see

- The models cached are designed to be used in-memory and not across clusters. The models are not serializable. That's the error that @rkaltreider is seeing.
- Secondly, they were introduced to improve performance of operations and models rendering. But it is not cool that its being thrust upon library consumers, whether they want to use it or not.

I went down the path of creating a cache manager thats isolated to springfox, but it seems like thats not possible with spring 4.0.x (1 version behind the latest released version). From what I could find, it seems like only one cache manager is allowed per app. I know there have been quite a few caching improvements in spring 4.1.x, but can't use those features yet.

ideas?

**Comment by kevinconaway** [comment]
Is the caching even necessary?  Isn't the entire model generated once when the spring context is refreshed and then served from memory via `DocumentationCache`?

**Comment by dilipkrish** [comment]
It is in non-trivial cases but its not critical that it be there. The moment you have more than one docket, it starts processing the graph of *documentables*. So in some cases it might process the same operations/models etc. n times depending on how the dockets configured. This was the cheap way to non-intrusively detect that a model has been processed, and have one copy of the model in memory.

Perhaps imperative caching might be in order. Unless I can find a good solution I might comment out the caching annotations and release a patch

**Comment by rkaltreider** [comment]
Ok so this is my current workaround configuration.  In a nutshell, it ignores caches that it can't find by assigning them a NoOp cache manager...I know its not what was intended, but its an option if you want to ignore caching the springfox objects for now.

~~~
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<!-- ~~~~~~~~~~~~~~~~~~~~~~ CACHE SETUP ~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<cache:annotation-driven />
		<bean id="cacheManager" class="org.springframework.cache.support.CompositeCacheManager">
		    <property name="cacheManagers">
		        <list>
		            <bean class="org.springframework.cache.ehcache.EhCacheCacheManager">
						<property name="cacheManager" ref="ehcache" />
					</bean>
		        </list>
		    </property>
		    <property name="fallbackToNoOpCache" value="true"/>
		</bean>
		<bean id="ehcache" class="org.springframework.cache.ehcache.EhCacheManagerFactoryBean">
			<property name="configLocation" value="${ehcache.config.location}" />
			<property name="shared" value="true" />
		</bean>
~~~

**Comment by dilipkrish** [comment]
That seems like a decent work around. I'll see if I can find a solution using that techinque.

**Comment by rkaltreider** [comment]
org.springframework.cache.support.CompositeCacheManager has been around since 3.1, so its certainly not spring 4.x specific, and i have tested both JMS and RMI ehcache configs and those models are simply ignored.  You could also potentially define a second cacheManager specifically for the springfox objects to just use in memory storage

**Comment by cabbonizio** [comment]
Also, keep in mind next version of Spring Boot is introducing auto-configured cache depending on what's in your classpath......I was looking to take advantage of this without having to write the boiler plate java code of defining a CacheManager and Factory bean.

**Comment by rkaltreider** [comment]
Here is a working config example that uses an ehcache manager and a concurrent map manager for the springfox stuff

~~~
     <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<!-- ~~~~~~~~~~~~~~~~~~~~~~ CACHE SETUP ~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		<cache:annotation-driven />
		<bean id="cacheManager" class="org.springframework.cache.support.CompositeCacheManager">
		    <property name="cacheManagers">
		        <list>
		            <bean class="org.springframework.cache.ehcache.EhCacheCacheManager">
						<property name="cacheManager" ref="ehcache" />
					</bean>
					<bean class="org.springframework.cache.support.SimpleCacheManager">
					    <property name="caches">
					        <set>
					            <bean class="org.springframework.cache.concurrent.ConcurrentMapCacheFactoryBean" p:name="models"/>
					            <bean class="org.springframework.cache.concurrent.ConcurrentMapCacheFactoryBean" p:name="modelProperties"/>
					            <bean class="org.springframework.cache.concurrent.ConcurrentMapCacheFactoryBean" p:name="modelDependencies"/>
					            <bean class="org.springframework.cache.concurrent.ConcurrentMapCacheFactoryBean" p:name="operations"/>
					        </set>
					    </property>
					</bean>
		        </list>
		    </property>
		    <property name="fallbackToNoOpCache" value="false"/>
		</bean>
		<bean id="ehcache" class="org.springframework.cache.ehcache.EhCacheManagerFactoryBean">
			<property name="configLocation" value="${ehcache.config.location}" />
			<property name="shared" value="true" />
		</bean>
~~~

**Comment by dilipkrish** [comment]
I'll rework this and have you guys review the changes. Would you guys be willing to verify snapshot before I release a patch?

**Comment by rkaltreider** [comment]
sure.  honestly i am pretty happy with what i have now so no rush. things are working smoothly with the config i have.  caching is enabled for everything again, just using specific cache managers for specific objects :D

**Comment by cabbonizio** [comment]
@dilipkrish i'm willing to test a snapshot absolutely!   I want to say I'm of the opinion a cache should be automatically defined behind the scenes and clients should not have to take on managing cache definitions in order to upgrade.   

@dilipkrish I think this is what you had in mind just want to provide my opinion on the matter.  I clearly can make it work the way it is right now, but I think upgrading to 2.1.0 should be more easier than it is now.

**Comment by cbornet** [comment]
Thanks for the workaround @rkaltreider . Working for me with springboot doing:
```java
    @Bean
    public CacheManager cacheManager() {
        cacheManager = net.sf.ehcache.CacheManager.create();
   ...
        EhCacheCacheManager ehCacheManager = new EhCacheCacheManager();
        ehCacheManager.setCacheManager(cacheManager);

        CompositeCacheManager compositeCacheManager = new CompositeCacheManager(ehCacheManager);
        compositeCacheManager.setFallbackToNoOpCache(true);
        return compositeCacheManager;
    }
```

**Comment by cbornet** [comment]
But I still have the crash I described in #856 when I add the SimpleCacheManager...

**Comment by rkaltreider** [comment]
Did you update to 2.1.1? The issue went away for me when I updated

Sent from my iPhone

> On Jul 17, 2015, at 5:53 PM, cbornet <notifications@github.com> wrote:
> 
> But I still have the crash I described in #856 when I add the SimpleCacheManager...
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
The information contained in this communication may be confidential, is 
intended only for the use of the recipient named above, and may be legally 
privileged.  It is the property of Vivanda, Inc.  If the reader of this 
message is not the intended recipient, you are hereby notified that any 
use, disclosure, dissemination, distribution, or copying of this 
communication, or any of its contents, is strictly prohibited.  If you have 
received this communication in error, please immediately re-send this 
communication to the sender and delete the original message and any copy of 
it, including all attachments, from your computer system.

**Comment by cbornet** [comment]
Sorry I meant #855, not the original groupName issue but a crash when getting api operations for the second docket

**Comment by dilipkrish** [comment]
Could you verify that the caches are getting autowired into your ehcache manager bean?

**Comment by cbornet** [comment]
Yes they do. Caches is a list of 4 cache objects with names models, operation, .... BTW I try now with the SimpleCacheManager, not the EhCacheManager. Adding the Autowired annotation doesn't change the behavior.

**Comment by dilipkrish** [comment]
Do you have a minimal reproducible repo I can investigate with

**Comment by dilipkrish** [comment]
btw what version of spring are u using?

**Comment by cbornet** [comment]
I am using a Jhipster 2.18 generated project (Spring Boot v1.2.5.RELEASE, Spring v4.1.7.RELEASE).

**Comment by cbornet** [comment]
@dilipkrish I pushed a minimal jhipster seed to https://github.com/cbornet/jhipster-springfox (no ehcache used) with sprinfox set to v2.1.1 and cache configured as per the springfox doc if you want to have a look.

**Comment by dilipkrish** [comment]
@cbornet just loaded your repo and everything seems to be working fine. So not sure what the problem is

**Comment by cbornet** [comment]
The NPE occurs when fetching http://localhost:8080/v2/api-docs?group=public (for instance from the swagger-ui)

**Comment by dilipkrish** [comment]
@cbornet thanks for catching that, it should now be fixed. 

@cabbonizio @rkaltreider @kevinconaway I fixed it in a non-intrusive way and is probably the better long term solution. Changed it such that it doesn't use the cache abstraction directly. Created a caching aspect that will not interfere with library consumers. Would you mind giving it a whirl and letting me know any feedback you might have. 

In the mean-while I'll update the documentation to reflect the caching changes.
