### ISSUE TITLE
Don't put the number on operationId for the first occurence

### ISSUE THREAD

**Issue by cbornet** [springfox/springfox#859]
On v2.1.0, the operationId is now of type methodUsingGET_x to guarantee uniqueness.
But for the first occurence it would be nicer to have methodUsingGET instead of methodUsingGET_1

**Comment by dilipkrish** [comment]
It [doesn't generate the a number on the first occurrence](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/operation/CachingOperationNameGenerator.java#L42-L45). It only generates it from the second one.

**Comment by cbornet** [comment]
Oh, I see. Then the issue is actually that the occurrence counter seems not to be reset when using several dockets.
For the same method() unique amongst controllers
OperationId in first docket : methodUsingPOST
OperationId in second docket : methodUsingPOST_1
