### ISSUE TITLE
api.getOperations returns null 

### ISSUE THREAD

**Issue by EranIsraeli** [springfox/springfox#864]
Hi,
I've upgraded from version 2.0.0 to version 2.1.1. 

For some reason, on ServiceModelToSwagger2Mapper, on the method mapOperations, on the for each loop, api.getOperations() returns null.

Everything works fine in version 2.0.0 yet I get this null pointer exception in version 2.1.1.
Anyone else ran into such bug ?

**Comment by dilipkrish** [comment]
Again this has been reported by @cbornet, details in #858. Closing this for now, but please reopen if you find that its not fixed in 2.1.2-SNAPSHOT
