### ISSUE TITLE
Weird behavior in version 2.1.1 due to RequestMapping value being named "rates"

### ISSUE THREAD

**Issue by EranIsraeli** [springfox/springfox#865]
With the following request mapping :
@RequestMapping(value = "/rates", method = RequestMethod.GET)
I'm getting a null pointer exception and no API as JSON.

Changing the value request mapping to "rateeeeeees" suddenly returns the API as JSON.

How weird is that ?

**Comment by dilipkrish** [comment]
That was totally a bug that @cbornet discovered. Its been fixed in the snapshot as well! :) Closing this for now but please reopen if you see that its not been fixed.
