### ISSUE TITLE
Missing REST API descriptions in JSON

### ISSUE THREAD

**Issue by EranIsraeli** [springfox/springfox#866]
I have 2 REST services:

1. 
@RequestMapping(value = "/flights/{id}", method = RequestMethod.GET, params = {"view=registerHedging", "step=1"})
public  FlightData registerHedgingBackToStep1() {
}

2. 
@RequestMapping(value = "/flights/{id}", method = RequestMethod.GET, params = {"view=takeoff", "step=1", "type=dailyFlight"})
public  DailyData dailyDataBackToStep1(@RequestParam(required=true) String type) {       
}

I'm only getting the API for the first REST services and the second one won't show up.

**Comment by dilipkrish** [comment]
Yeah... that is a limitation in the current swagger specification. I did add an [incubating feature](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-boot) (see #**21**) to help with that, but unfortunately swagger-ui doesn't play well with it yet.

**Comment by EranIsraeli** [comment]
@dilipkrish 
"but unfortunately swagger-ui doesn't play well with it yet" - can you please elaborate ? 

I've looked at the RFC. It seems like it should generate the output the way you've described.
Will enableUrlTemplating(true) generate that kind of output ? (and to my understanding it will not be readable by the Swagger UI ?)

What I'm trying to figure out is why params aren't fully supported in springfox. 
Is it an issue of one or a combination of the these :
1. The current swagger spec (http://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md)
2. Swagger UI (http://github.com/swagger-api/swagger-ui)
3. Springfox.

**Comment by EranIsraeli** [comment]
Going through other issues, my issue seems similar to issue #750 

Since I can't afford to have missing APIs in my UI, do you have any suggestions ?

**Comment by dilipkrish** [comment]
This is now enabled via incubating feature to `enableUrlTemplating` via the `Docket`. Please provide feedback if you're using it.

**Comment by chrisdostert** [comment]
wasn't sure where to leave feedback other than here. I've been using the enableUrlTemplating feature and it is totally awesome. Works in both swagger spec and swagger ui flawlessly. Thanks for the awesome work

**Comment by dilipkrish** [comment]
@chrisdostert are you using it with featured turned on? If so would love to get your feedback

**Comment by chrisdostert** [comment]
Yes, it's been working great so far. It's a very clever solution

**Comment by dilipkrish** [comment]
@chrisdostert Dint think swagger-ui supported RFC 6570... parameterized query parameters in uri templates, in particular. Im surprised its working even!

**Comment by chrisdostert** [comment]
Ah, I got so excited when all parameterized paths showed up I didn't actually submit a request. I just did and you are correct, swagger-ui does hydrate the parameterized query parameters but doesn't strip the variable template from the path when it executes a request. It's still much better than before in that all paths including those with parameterized query parameters show up and you can still successfully submit to paths without parameterized query parameters. We need to get swagger-ui updated to support this! : )

**Comment by dilipkrish** [comment]
:+1: thanks for plus+1ing that PR!

**Comment by ivelkov** [comment]
I apologize if the right place to leave feedback is not on this closed issue.

Looking at the comment on https://github.com/swagger-api/swagger-ui/issues/1665 , I'm not really sure whether the right path moving forward is RFC 6570 since it seems like it will not get any swagger-ui support.

Looking at https://github.com/domaindrivendev/Swashbuckle/issues/142 it looks the approach SwashBuckle is taking is merging multiple operations into one leveraging optional parameters. Perhaps this approach could make sense for springfox as well?

**Comment by dilipkrish** [comment]
I chatted with @webron a while back about this. His take on it is to try and discuss this as part of swagger spec next and decide on the way to go forward. So its not necessarily a dead end as his comment might suggest :) My hope is that we stick to standards when defining uris for services. The changes to support this in swagger ui has also been done and I've submitted a PR.

Having said, My opinion is that RFC 6570 is the way forward. I say this for a couple of reasons...
- Service descriptions need to be deterministic. So just bunching a whole lot of parameters together and calling them optional isn't going to cut it. For e.g. lets say we have two operations `findCustomerByNameAndEmail` which has two parameters *name and email* and `findCustomerByPhoneNumber`  which has one parameter *phone*. It makes no sense to club them into one operation `findCustomer` with three optional parameters. How does the api description speak to developers in that case, which parameters should I provide?
- When we design controller methods that reflect this expectation we would like to describe it via uri templates
- Its not clear how these operations can be realized as distinct operations in implementation when one is doing swagger-definition first service design.
- RFC 6570 is a standard and we want specifications to be built on standards.

**Comment by ivelkov** [comment]
Thanks @dilipkrish, I appreciate your prompt response.

**Comment by orbfish** [comment]
It's very nice for one of my endpoints, but not great for the others, because it adds a bunch of information that is unnecessary when the multiple endpoints per uri/verb is not present. Would be great to be able to limit this per endpoint/resource class, as well has to have swagger ui respond correctly.

**Comment by dilipkrish** [comment]
@orbfish Not sure what you mean. If its a suggestion, I'd recommend opening up a new feature request with more details and examples.

**Comment by Shaun-Yao** [comment]
@dilipkrish thanks for the reply! I have added springfox-swagger-ui-rfc6570 instead of springfox-swagger-ui and enableUrlTemplating， but the Request URL is http://localhost:9000/api/statistics{?days}&days=5

**Comment by dilipkrish** [comment]
You need to also use the [appropriate swagger-ui](http://springfox.github.io/springfox/docs/current/#springfox-rfc6570-support-strong-incubating-strong).

**Comment by wahnn** [comment]
please read https://stackoverflow.com/questions/33468129/springfox-404-error-when-testing-api-from-swagger-ui
