### ISSUE TITLE
Springfox support for polymorphism

### ISSUE THREAD

**Issue by sunaina-ishi** [springfox/springfox#868]
Hi , In swagger 1.2 we have a concept of subtypes to display polymorphism/inheritance in the JSON docs. I am using Springfox with Swagger2. My API has an input request which is an AbstractClass. The doc displays information about the "AbstractClass" but nothing about the "Concrete implementations". Can we do it using springfox. Help will be really appreciated.

**Comment by dilipkrish** [comment]
It doesn't support polymorphism yet. It seems like a stretch goal at the moment with both me and @adrianbk having very little bandwidth at the moment. A PR would be greatly appreciated.

**Comment by androidan** [comment]
Hi, wondering if someone has solved this issue...

**Comment by dilipkrish** [comment]
No. Looking for contributions for this feature. There is a PR but that isn't necessarily the right solution

**Comment by androidan** [comment]
is a PR a pull request? I'm completely newbie on springfox as a contrib but I can contribute there is a planning solution just to implement.

**Comment by dilipkrish** [comment]
@androidan yes PR is pull request. Here is [the PR](https://github.com/springfox/springfox/pull/1152). It solves the problem, however it is not complete yet. It doesn't support inferring inheritance using the jackson annotations i.e. no swagger annotations.

**Comment by theindra** [comment]
I would also need this feature.

**Comment by paulalex** [comment]
Is this feature going to be supported anytime soon? I have annotated my objects with @ApiModel and I have referenced the parent heirarchy but I do not see anything in the generated swagged file to indicate polymorphism and I also do not get objects which are not explicitly referenced in the  API present, so when a method returns an abstract type none of the concrete implimentations are present in my swagger file.

**Comment by dilipkrish** [comment]
Probably in the next release... 2.8 around March/April 2017

**Comment by ethlo** [comment]
I'm going to take a stab at this, but I need to understand what kind of data we should output in the swagger data json file. 

My initial test case would be a simple request parameter super-class (Dog) which have concrete impl Cat and Dog.

Also, should we require: 
* The specification of the inheritance hierarchy using Jackson annotations?
* The specification of the inheritance hierarchy using Swagger annotations?
* Search for any sub-classes of Dog?

**Comment by dilipkrish** [comment]
@ethlo That would be super awesome! thank you. II'll write something up for you that might help.

**Comment by ethlo** [comment]
Ok, that would be nice. Quite a big project to navigate. I have been able to add the `discriminator` and `subTypes` data to `ModelBuilder`, however that does not affect the rendered JSON data, so I assume I need to use those somewhere, like in `ModelMapper`.  My biggest showstopper ATM is gradle. I cannot seem to get it to work at all in Eclipse.

**Comment by ethlo** [comment]
I have had a closer look, and I need some guidance on how to solve this. My preliminary use case will be

```java
@RequestMapping(value = "/animals", method = RequestMethod.POST)
public void createAnimal(Animal animal){

}
```

Animal can be `Dog` or `Cat`. I have currently created a plugin that picks up subclasses and put them as `Model` subTypes. The beauty is that there is currently no requirement to change code outside of project `springfox-swagger2`. 

What I need is to know how the output should look. It feels a bit like a jungle on where the different specs and tools are moving, I believe [1] is a good example of the amount of churn which is upcoming.
Looking at examples and forums, like this post[2] there is no mention of the support of the above. From the spec it looks like it should be an `anyOf`, however that is not supported in Swagger 2.0 (but now it seems it finally will be in OpenAPI Spec 3.0[3]). Input is greatly appreciated! :-)

[1] https://github.com/OAI/OpenAPI-Specification/pull/741
[2] http://stackoverflow.com/questions/27862407/swagger-inheritance-and-composition
[3] https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md

**Comment by dilipkrish** [comment]
Im going to say this again, inheritance in services domain models is a slippery slope. Its always fraught with serialization issues and makes the service contracts unpredictable and un-enforceble. Given your example 

```java

@RequestMapping(value = "/animals", method = RequestMethod.POST)
public void createAnimal(Animal animal){

}
```

The only thing the service guarantees to be able to process is the `Animal`, and sending in a `Cat` or `Dog` is not guaranteed to be processed. 

Having said that, it is a real requirement for people to model it this way. So, I'll write up some notes

> The beauty is that there is currently no requirement to change code outside of project springfox-swagger2. 

That doesnt sound right. Springfox has an internal model to describe services, operations and models.  So, springfox-schema and may be springfox-core should be the module(s) that changes as inheritance is independent of specification format. There might be some changes to swagger2 as well.

There are some notes/comments on this other PR #1152.

**Comment by ethlo** [comment]
Sorry, I was not completely accurate. What I meant was that you already have the structure in the model pointing to sub-classes (subTypes) and with a PolymorphismModelBuilderPlugin that extends ApiModelBuilder, I was able to extract the data I need. However, I do not know how to express oneOf in Swagger 2.0, and from what I've read, it will not be supported until 3.0 of the spec. Bottomline, this cannot be supported at this point. 

Is there/should there be a branch starting to implement Open API 3.0 features?

**Comment by fankaigit** [comment]
looking forward to see this feature in 2.8.0 ~

**Comment by ctytgat** [comment]
Is anything happening around this? 
I find it confusing that springfox provides annotation support for inheritance while the actual feature is not implemented.

**Comment by dilipkrish** [comment]
@ctytgat  Nothing is happening around it at the moment. It is an open issue we need some help from contributors.

**Comment by ctytgat** [comment]
Ok. Do you have a rough estimate of the amount of work required (for someone not familiar with the code)? I might have some time to spare in the coming weeks.

**Comment by dilipkrish** [comment]
@ctytgat I believe it will be easier one we bring in OAS 3.0 support. Going to try and get that in next few weeks, given this is a slow time of the year :)

**Comment by TakumaNagai** [comment]
+1

**Comment by kunal-shah** [comment]
@dilipkrish Hi Dilip any update with this? Is there any work-around as swagger annotations kind of supports it. Why my ModelProperty annotations with subTypes and discriminator defined is not enough in this case?

**Comment by dilipkrish** [comment]
No support for it yet @kunal-shah

**Comment by kunal-shah** [comment]
Thanks Dilip, I assume no work-around as well with using modelproperty annotations directly right?

**Comment by phirzel** [comment]
Please consider the following as testcase: I can serialize proper JSON and also deserialize by Jackson ObjectMapper into the origin structure. With springfox-swagger2 v2.7.0 there is still only the parent-class in API-Model. v2.8.0 seems buggy to me, I get an LCache serialize failure at SpringBoot-startup time already!

Sample in my case:
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "type",
        visible = false 
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = LocationPOI.class, name = "poi"),
        @JsonSubTypes.Type(value = LocationAddress.class, name = "address"),
        @JsonSubTypes.Type(value = LocationStation.class, name = "station")
})
@ApiModel(value = "Location", subTypes = {LocationPOI.class, LocationAddress.class, LocationStation.class}, discriminator = "type")
public abstract class Location {
    /**
     * Inheritance discriminator: technical field
     * see JsonTypeInfo(.., property = type",..)
     */
    private String type; // setter, getter
}

**Comment by dilipkrish** [comment]
@phirzel that may be a bug, different from polymorphism support. Mind creating a bug for this?

**Comment by Farahabuhijleh** [comment]
Dear @dilipkrish  we have related issue i have abstract class general and there are subclass , our method accept the general object my problem it's the the example model display general object  properties . so it's possible to display subclass as example model.  
for example :  sendMessage(General object )

public  abstract class General{
private int templateId;
	private String type;
	private String message;
	}
public class TypeOne extends General{
String usersID;
}

public class TypeTwo extends General{
String email;
}
i expect to display two example model as the following :  
//example TypeOne
{  
"type":"String",
"message":"String",
"usersID":"String"
}
//example TypeTwo
{  
"type":"String",
"message":"String",
"email":"String"
}

**Comment by phirzel** [comment]
Dear @dilipkrish 
The article starts Juli 2015 with the term "**subtypes to display polymorphism/inheritance in the JSON docs**".
Well, that's exactly my problem (though I understand the title focusses more on polymorphism and I mean rather subclass-models). Anyway I don't see a reason to open another issue, there is even a PR from someone in this thread who should solve the problem, at least partially.
(If you relate to my comment Lcache Bug in 2.8.0 I agree, these are other matters. I am not sure, whether it is my fault or the libraries, anyway once I am convinced I will report separately.)

But I understand your point above, that inheritance in service-contracts is a delicate matter, I didn't see it that way yet. On the other hand as a service provider I shall exactly describe what kind of subclasses are available by API-doc, therefore I am convinced I can handle that, because a consumer won't be able to add any other subtypes as long as he does not require them from the provider. Even Rabits, Birds or whatever other Pets do no violate the contract if I bring in them later as a provider, as long as the abstract Pet/General class remains solid, in my opinion at least. If they do, there is the concept of another version.

**Comment by dpp77** [comment]
And have this error in swagger too:

![image](https://user-images.githubusercontent.com/56954705/67496942-80936900-f67d-11e9-88e6-759819a9eea2.png)
