### ISSUE TITLE
@ApiParam ignores Boolean.class

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#871]
I have a simple class annotated with @ApiModel :

       @ApiModel   public class PageRequest { ... }

It has one property of type Boolean:

         @ApiParam(name = "ascending", required = false, value = "ascending or not")
         private Boolean ascending;

It gets used like this:

       @ModelAttribute PageRequest pageRequest

When generating the swagger doc - that field is not present at all. Changing to boolean (primitive) solves it; but that's not the point. I do actually need the Boolean class - I care it is true/false/unknown.

**Comment by dilipkrish** [comment]
@wind57 By definition model attributes properties are supposed to be primitives. But I concur with you that the boxed representations of the primitives should also be allowed.

**Comment by dilipkrish** [comment]
Do you not have getters and setters for this property by any chance? By default only bean properties are supported.

**Comment by wind57** [comment]
I do have getter/setter for it:

       public class PageRequest {

               private Boolean ascending;

               public Boolean isAscending() {
                      return ascending;
               }

               public void setAscending(Boolean ascending) {
                     this.ascending = ascending;
               }

**Comment by dilipkrish** [comment]
Well going by the java beans introspector code it seems like your code doesn't conform to the bean spec. So either it needs to be a primitive `boolean` or  the method needs to be called `getAscending`

```java
                     if (argCount == 0) {
                        if (name.startsWith(GET_PREFIX)) {
                            // Simple getter
                            pd = new PropertyDescriptor(this.beanClass, name.substring(3), method, null);
                        } else if (resultType == boolean.class && name.startsWith(IS_PREFIX)) {
                            // Boolean getter
                            pd = new PropertyDescriptor(this.beanClass, name.substring(2), method, null);
                        }
                    }
```
