### ISSUE TITLE
Range not respected by swagger ui for validation

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#872]
So, I have already opened this one, but it was closed. This time, I took the springfox samples and tried running them. Here is the link I am trying to access:

     http://localhost:8080/spring-xml-swagger/swagger-ui.html#!/pet/getPetByIdUsingGET

If you look at that PetController:

     @ApiParam(value = "ID of pet that needs to be fetched", allowableValues = "range[1,5]", required = true)

I pass a 6 in there as a result I get the NotFoundException; which should not happen. 6 is invalid so swagger should actually block that request at all. This does not happen. Or did I misunderstood something about allowableValues?

**Comment by dilipkrish** [comment]
If you're referring to the UI not respecting the specified range and validating, that would be in the realm of swagger-ui. It would be an issue with this library if you're unable to see the specified range in the swagger json document (not ui).

**Comment by wind57** [comment]
I have one more question here, is range[1, 100_000] supposed to work? jdk7 style of numbers?

**Comment by dilipkrish** [comment]
Not familiar with that.. links? In anycase the answer is no, its not supported.
