### ISSUE TITLE
@ApiModelProperty hidden not working

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#873]
I've just updated to version 2.1.0 and here is the case that does not work:

      @ApiModel public class SomeModel { ... }

It has a field:

          @ApiModelProperty(hidden = true)
          @JsonProperty(value = "_meta")
          private final SomeResource meta;

Usage :

         @RequestBody SomeModel someModel;

In version 2.0.2 this field is indeed hidden, not anymore in 2.0.3 and above.

**Comment by dilipkrish** [comment]
This may be regression, i'll take a look
