### ISSUE TITLE
springfox-staticdocs usage

### ISSUE THREAD

**Issue by EranIsraeli** [springfox/springfox#874]
Hi,

Is there a way to configure springfox-staticdocs as a Maven reporting plugin ?

IMO, it makes much more sense to generate the staticdocs this way rather than during a unit test.

**Comment by dilipkrish** [comment]
There is a maven plugin available, Infact @RobWin is churning out a whole ecosystem. A good place to start [is here](https://github.com/Swagger2Markup/swagger2markup)

**Comment by EranIsraeli** [comment]
Alright. I'll take a look.

A question regarding the code sample at:
swagger2markup.readme.io/docs/springfox-staticdocs
(and on springfox's documentation)

Where exactly are the decelerations of the get (get("/v2/api-docs")) and status (status().isOk()) methods ? - it won't compile.

**Comment by RobWin** [comment]
@EranIsraeli  Please join the gitter chat to ask questions: https://gitter.im/Swagger2Markup/swagger2markup
