### ISSUE TITLE
Controller sorting issue in swagger-ui

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#876]
I have a lot of rest endpoints and using io.springfox:springfox-swagger2:2.1.1. I do not remember exactly when this broke (it used to work), fact is in version 2.1.1 sorting of all rest end-points is broken. :( Is this a known thing? I mean the @RestController annotated classes, not the methods itself. I don't care about the methods itself.

**Comment by dilipkrish** [comment]
Controllers are sorted by tags, and its upto swagger ui to render the order. Could you provide an example?

**Comment by wind57** [comment]
Sure, here is a small example:

      @RestContoller
      public class AController


      @RestController
      public class BController


Sorting used to work by name (it transforms it to a-controller and b-controller). Now, it does not. I have over 100 rest endpoints and no sorting is applied.

I could add tags (that would be a great hassle, but I could), but that seems to be ignored also.

I've added :

      @Api(tags = "AController")

      @Api(tags = "BController")

but these are ignored also.

**Comment by dilipkrish** [comment]
Sorry  dint mean to send you down the wrong path of annotating tags, what I meant was that automatically tags are created for each controller based on the name. So it should sort based on the controller name.

Not able to reproduce your problem unfortunately it seems to be sorting just fine. Are you using 2.1.2?

**Comment by wind57** [comment]
that's weird. I am on 2.1.2 indeed and no sorting is applied. :(

**Comment by dilipkrish** [comment]
I'm suspect that we may be talking about different things.... mind sending me a screenshot of what you mean?

**Comment by wind57** [comment]
Sure thing!
<img width="554" alt="screen shot 2015-07-27 at 4 34 03 pm" src="https://cloud.githubusercontent.com/assets/932639/8907256/7d0cf524-347d-11e5-9aa0-595d7c6d89b0.png">

This is what I get when going to localhost:8080/api.html

**Comment by wind57** [comment]
@dilipkrish was this enough?

**Comment by dilipkrish** [comment]
@wind57 not really sure. Could you perhaps create a fork of the [springfox-demo](https://github.com/springfox/springfox-demos) to demonstrate the problem

**Comment by igorko** [comment]
I see this issue with springfox 2.7.0. If apisSorter is set to method, mothods are sorted correctly, but controllers are not sorted with tagnames. If apisSorter is set to alpha, controllers are sorted using tags, and methods are not sorted in any way.

**Comment by dilipkrish** [comment]
@igorko Would you mind creating a new issue for it?
