### ISSUE TITLE
Swagger Annotations Not Working, Using Springfox

### ISSUE THREAD

**Issue by samillm** [springfox/springfox#877]
These are the method headers for the sample application I'm trying to make. Unfortunately I don't see the @ApiOperation or @ApiResponse or @ApiResponses annotations taking effect.
I also have a sample class and an Application class(which contains swagger configuration info and the like)

````
@Api(value = "/v1/", description = "Test API", produces = "application/json")
@RestController
@RequestMapping("/v1/")
class SampleRestController {

     @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successfully added"),
            @ApiResponse(code = 416, message = "List is empty") })
   @RequestMapping(produces = MediaType.APPLICATION_JSON_VALUE, value = "samples/{sb}",
    method = RequestMethod.GET)
   public Map<String, String> sbs(@PathVariable("sb") String sb) {

    }  

   @ApiOperation(
      value = "Seeing where this shows up",
      notes = "we should see this in the implememtation notes",
      response = Sample.class,
      httpMethod = "GET"
    )
        @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successfully added"),
            @ApiResponse(code = 416, message = "List is empty") })

   @RequestMapping(produces = MediaType.APPLICATION_JSON_VALUE, value = "samples/{pb}",
    method = RequestMethod.GET)
   public Sample ps(@PathVariable String pb) {

   }

   @RequestMapping(produces = MediaType.APPLICATION_JSON_VALUE, value = "samples",
    method = RequestMethod.GET)
   public Collection<Map<String, String>> cs(@RequestParam(value = "cid", required = true, defaultValue = "")
    String cid) {

   }


}
````
Here is the relevant portion of my swagger json

````
{"swagger":"2.0","info":{"description":"All about the Samples","title":"Samples API","contact":{},"license":{}},"host":"localhost:8080","basePath":"/","tags":[{"name":"sample-rest-controller","description":"Sample Rest Controller"}],



"paths":{


"/v1/samples":{"get":{"tags":["sample-rest-controller"],"summary":"cs","operationId":"csUsingGET","consumes":["application/json"],"produces":["application/json"],"parameters":[{"name":"cid","in":"query","description":"cid","required":true,"type":"string"}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Collection«Map«string,string»»"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}},


"/v1/samples/{pb}":{"get":{"tags":["sample-rest-controller"],"summary":"ps","operationId":"psUsingGET","consumes":["application/json"],"produces":["application/json"],"parameters":[{"name":"pb","in":"path","description":"pb","required":true,"type":"string"}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Sample"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}},


"/v1/samples/{sb}":{"get":{"tags":["sample-rest-controller"],"summary":"sbs","operationId":"sbsUsingGET","consumes":["application/json"],"produces":["application/json"],"parameters":[{"name":"sb","in":"path","description":"sb","required":true,"type":"string"}],"responses":{"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"string"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}}},
````

I'm using springfox-swagger2 version 2.1.1 and I'm viewing my UI through the default UI provided by swagger at their live demo app.

Can someone tell me what I'm doing wrong?
Thanks!

**Comment by dilipkrish** [comment]
Let me look

**Comment by dilipkrish** [comment]
Let me look

**Comment by samillm** [comment]
Hi Dilip,

I was playing around and changed my import from
 import com.wordnik.swagger.annotations.*;
to
import io.swagger.annotations.*;

and all the annotations appear to work.
I guess the com.wordnik.swagger.annotations import no longer works?

My Bad!
Thanks!

**Comment by dilipkrish** [comment]
No totally will not work. Swagger 1.5 moved its package name and so did we :)

**Comment by hanuman1988** [comment]
hi I am using springfox-swagger 2.1.2 and but getting issue with annotation. i have annotated with @apiopearation and given some value but i cant see any changes on UI. later i tried some more annotation like apiresponse but again no impact on ui.can you please let me know i am mising anything , package is correct for annotation.

import io.swagger.annotations.ApiOperation;

API : 

@ApiOperation(value = "Scoresheet Details")
	@RequestMapping(value = RequestPathURLs.GET_SCORESHEET, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON)
	public @ResponseBody ResponseEntity<Object> getScoresheet(@PathVariable("scoresheetId") Long scoresheetId, @RequestHeader(CommonConstants.ZYCUS_USER_ID) String tmsUserId, @RequestHeader(CommonConstants.ZYCUS_TENANT_ID) String tenantId, @RequestHeader(CommonConstants.ZYCUS_TRACKING_NUMBER) String trackingNumber) {

**Comment by dilipkrish** [comment]
Please use version 2.9.0

**Comment by hanuman1988** [comment]
Actually we have Java version 1.7 in prod, and latest swagger required 1.8 so cant upgrade now. any solution for java 1.7 level.

**Comment by hanuman1988** [comment]
could you please suggest swagger for java 1.7

**Comment by dilipkrish** [comment]
@hanuman1988 springfox supports java 6+. If you're using annotations from the latest swagger it will not work with springfox. You need to use the 1.5.x version with springfox.

**Comment by hanuman1988** [comment]
Hi Dilip, I using version 1.5.x only. below are the all jars i m using.

![image](https://user-images.githubusercontent.com/40462273/41843076-3204c7a6-788a-11e8-98de-250aafc50569.png)

**Comment by dilipkrish** [comment]
Please move to using springfox 2.9.2

**Comment by hanuman1988** [comment]
hi i have moved to 2.9.2 version but problem is same. i could not see this annotation @apiresponse taking effect.

**Comment by dilipkrish** [comment]
No idea. Please create a __new__ detailed issue. Hard to troubleshoot based on the information you've provided

**Comment by Akamanouche** [comment]
Hi all,

Same for me : some responses codes still appearing even if not mentionned as part of @ApiResponses

Attachments :
![controller-with-annotations](https://user-images.githubusercontent.com/1670555/46341531-a09e5780-c638-11e8-80b2-d1b0904d6412.PNG)
![swagger-documentation](https://user-images.githubusercontent.com/1670555/46341640-fe32a400-c638-11e8-840d-a5fbeb9d410e.PNG)


springfox : 2.9.2
Java: 1.8.0.77
Tomcat: 8.5.32

Thanks for an eventual feedback.
