### ISSUE TITLE
Overloaded RestController methods

### ISSUE THREAD

**Issue by lelininkas** [springfox/springfox#878]
Hi,

For overloaded methods ApiDescriptionBuilder fails to run ApiOperationReader.read() as it's value is read from cache.  Due to this issue when trying to access the documentation ServiceModelToSwagger2Mapper.mapOperations() will throw NullPointerException and no documentation will be available
On first method encounter OperationsKeyGenerator generates cache key solely on mapping pattern, method name and class name. All these would be the same for overloaded methods. Methods have "params" distinct values set.
Spring handles RestController method overloading with no issues, so IMHO should Springfox. 

I'm using springfox-swagger2 2.1.0 from maven repository.

**Comment by dilipkrish** [comment]
This has been fixed in 2.1.2

**Comment by dilipkrish** [comment]
Closing this as its been fixed in a later version

**Comment by lelininkas** [comment]
I confirm that this issue is not present in 2.2.1. Thank you.
