### ISSUE TITLE
@ModelAttriute is ignored

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#881]
This actually a question long time asked by me :) : http://stackoverflow.com/questions/26932187/swagger-spring-mvc-reponsebody

I am using it like this :

      @ModelAttribute Person person.

When I go to swagger-ui, that field (person) is not an option at all, I meant it is simply not present - neither it's fields nor a json of the entire Person for example.

**Comment by ejain** [comment]
`@ModelAttribute` appears to work as expected, at least with the current version (2.2.2)?

**Comment by wind57** [comment]
@ejain it does - but only with setters/getters. What if we care that the field class is immutable (no setters)? Then it does not

**Comment by dilipkrish** [comment]
@ejain that is a true statement. The expectation is that a model attributed classes must conform to the bean specification. Might revisit that in the next release

**Comment by dilipkrish** [comment]
Couple of observations 
- If the intent is immutability and passing in an object, the preferred approach is to make that a request body, in which case the immutability will follow the rules laid out by **jackson** to determine what constitutes a request "view" of the request object.
- getters/setters are a clean way to indicate what values can come in to a operation. While it may not be apparent in a trivial model with one level nesting; the design choice will become clear when we realize that model attributes can be arbitrarily nested. 

Consider (pseudo code in c# for brevity)
```c#
Person {String firstName {get;set;}, String lastName {get;set;}, Category category {get;set;}}
Category {String name {get;set;}, String description {get;}}
```
So one could set properties 
`firstName`
`lastName`
`category.name`

Now we don't want category to be able to set description via the operation, how do we control/specify that?

it makes it hard to reason about which fields in an objects are not intended to be mutated. This is the reason we chose to limit it to objects that expose getters and setters. 

As always @wind57/@ejain feedback/ideas are welcome

**Comment by wind57** [comment]
+1 for jackson. Especially since jackson (1.9 and up) can have :

@JsonIgnore on field and @JsonProperty on getter - which basically means ignore on request/not ignore on response (serialize/deserialize).

I can't think of a case where I (personally/biased?) I would want one behaviour with jackson and different in springfox. Usually you first think of your needs via jackson and only then if it is manageable via springfox; if you can sort of unify these together it would make complete sense for me, I think.
