### ISSUE TITLE
Can add but not remove Springfox's default @ApiResponses

### ISSUE THREAD

**Issue by ejain** [springfox/springfox#884]
e.g. 

    @RequestMapping(value = "/foo/{id}", method = RequestMethod.DELETE)
    @ResponseStatus(HttpStatus.NO_CONTENT)
    @ApiOperation(value = "Delete a foo")
    @ApiResponses({ @ApiResponse(code = 204, message = "Success") })
    public void delete(@PathVariable String id) { ... }

Results in:

- 204 - Success
- 401 - Unauthorized
- 403 - Forbidden

How do I get rid of the 401 and 403 response messages?

**Comment by john-roj87** [comment]
You can use  ```useDefaultResponseMessages(false)```In your ```SwaggerConfig``` class.
It seemed to be working for me.

**Comment by ejain** [comment]
Thanks, that works for me, too.
