### ISSUE TITLE
Issue Related to #586 - Empty properties when using @JsonProperty but not using @JsonCreator

### ISSUE THREAD

**Issue by jreckner** [springfox/springfox#885]
I am having an issue which seems related to issue #586. I am using Spring Boot and Groovy.

My Springfox dependencies are

    compile 'io.springfox:springfox-swagger2:2.1.2'
    compile 'io.springfox:springfox-swagger-ui:2.1.2'

I have created an example application to show what I am seeing [here](https://github.com/jreckner/springfox-requestbody-jsonproperty/) and I refer to that code in my description of the issue below.

I am **not** using a static `@JsonCreator` in my [RequestWithoutJsonCreator model](https://github.com/jreckner/springfox-requestbody-jsonproperty/blob/master/src/main/groovy/com/test/model/RequestWithoutJsonCreator.groovy) and the properties are left empty. I have a very similar [ResponseObject model](https://github.com/jreckner/springfox-requestbody-jsonproperty/blob/master/src/main/groovy/com/test/model/ResponseObject.groovy) also **not** using the `@JsonCreator` and it generates just fine when its added as a `response` on the `@ApiOperation`. I also created another [RequestWithJsonCreator model with a static](https://github.com/jreckner/springfox-requestbody-jsonproperty/blob/master/src/main/groovy/com/test/model/RequestWithJsonCreator.groovy) `@JsonCreator` to show that does work as expected and does generate the properties. [FunnyJsonPropertiesController](https://github.com/jreckner/springfox-requestbody-jsonproperty/blob/master/src/main/groovy/com/test/web/FunnyJsonPropertiesController.groovy) has an `@ApiOperation` for each request model so you can easily run the application with `gradlew bootrun` and see the Swagger JSON or UI.

Here is the relevant json generated with the empty properties:

```json
    {
	"definitions": {
        "RequestWithoutJsonCreator": {},
        "ResponseObject": {
            "required": [
                "OutField1",
                "OutField2"
            ],
            "properties": {
                "OutField1": {
                    "type": "string",
                    "readOnly": true
                },
                "OutField2": {
                    "type": "string",
                    "readOnly": true
                }
            }
        },
        "RequestWithJsonCreator": {
            "required": [
                "input_field_1",
                "input_field_2"
            ],
            "properties": {
                "input_field_1": {
                    "type": "string",
                    "readOnly": true
                },
                "input_field_2": {
                    "type": "string",
                    "readOnly": true
                }
            }
        }
    }
```

**Comment by dilipkrish** [comment]
@jreckner thanks for creating a detailed issue! :metal: 

without running the code I suspect that if you remove @Immutable from the `RequestWithoutJsonCreator` you're problem will dissapear. The reason it has no properties is that there are no setters for it to create objects with nor constructors nor factory method annotated with `@JsonCreator`

**Comment by jreckner** [comment]
Is there a reason why the Response Object does work then?

`@Immutable class ResponseObject` it also has the @**Immutable**  annotation as well. See [ResponseObject model](https://github.com/jreckner/springfox-requestbody-jsonproperty/blob/master/src/main/groovy/com/test/model/ResponseObject.groovy)

**Comment by dilipkrish** [comment]
I think there is a general problem in these use cases. I have a fix for this in the works.

**Comment by jreckner** [comment]
Sounds great, I misunderstood your first response. I thought you were giving me a permanent workaround. Thanks for the help.

**Comment by dilipkrish** [comment]
@jreckner actually I discovered a bug (the one you point out regarding ResponseObject), while investigating why scala support wasn't working :)

**Comment by jreckner** [comment]
I appreciate the help and support. In addition this library is amazing. Thank you. It's been very helpful in providing simple Swagger 2.0 documentation for our Spring Boot applications.

**Comment by jreckner** [comment]
Thanks for the fix. Everything is now working in my test program and my original app, where I first saw the issue.

**Comment by dilipkrish** [comment]
You're welcome! :+1:
