### ISSUE TITLE
Question regarding query params

### ISSUE THREAD

**Issue by rcruzper** [springfox/springfox#887]
Hi, I have a question regarding query params, I have some paginable methods, so I've created a class named PaginationRequest with page and size params, this way I add PaginationRequest to all my paginable methods, and also I can add more params as ordination, filters, etc...
But in swagger-ui this is the result:
![captura de pantalla 2015-08-03 a las 13 58 36](https://cloud.githubusercontent.com/assets/1263202/9037075/cd5d65a8-39e7-11e5-8a2b-165607183352.png)

If I ignore the param with @ApiIgnore and I add the @ApiImplicitParams the result is ok, but I want to avoid the @ApiImplicitParams annotation.

My controller mehod:
```Java
@RequestMapping(method = RequestMethod.GET)
@ResponseStatus(HttpStatus.OK)
public PublicationsResponse fooBar(
    @Valid PaginationRequest paginationRequest
    @Valid OrdinationRequest ordinationRequest
    ....) {

}
```

My PaginationRequest class:
```Java
@ApiModel
public class PaginationRequest extends BaseRequest {

    @ApiModelProperty(value = "The number of the requested page, from api model")
    @Min(value = 1, message = "error.pagination.page.min")
    private Integer page;

    @ApiModelProperty(value = "The size of the requested page, from api model")
    @Min(value = 10, message = "error.pagination.size.min")
    private Integer size;

}
```

Is there a solution to this?

**Comment by dilipkrish** [comment]
Couple of things that seem off about your `fooBar` operation
- a `GET` cannot have a body post, or atleast its not guaranteed to be supported by any server implementation of HTTP
- even if its a `POST`, it is not possible to have multiple `body`s in a request. It should probably be modeled as `RequestPart`s with `multipart/form-data` as the consumes media type.

In any case, If it were me I'd model it as such

```java
@RequestMapping(method = RequestMethod.GET)
@ResponseStatus(HttpStatus.OK)
public PublicationsResponse fooBar(
    @Valid @ModelAttribute QueryRequest querRequest
    ....) {

}
```

and make `QueryRequest` a list of all the query related query string params.

**Comment by rcruzper** [comment]
Hi, I think I didn't explain myself.
attributes inside of paginationrequest and ordinationrequest are part of the querystring. currently I'm using @ApiImplicitParam to set page and size as querystring params in swagger, also my api is expecting page and size as querystring.
So with springmvc I can use many object in the params of a method as I showed in my first post and it will expect them as querystring if request method is set to Get, but I would like to avoid the ApiImplicitParam annotation.

**Comment by dilipkrish** [comment]
Maybe I wasn't being clear.  These are the steps you need to do. 
- Remove `ApiImplicitParams` Annotation. 
- Make PaginationRequest and OrdinationRequest beans **with getters and setters**. There is no need to annotate them with ApiModel etc. 
- annotate your parameters with `@ModelAttribute` (In addition to @valid

**Comment by rcruzper** [comment]
Great! Thank you very much!
