### ISSUE TITLE
Support custom JsonPrefix in MappingJackson2HttpMessageConverter

### ISSUE THREAD

**Issue by jeffsheets** [springfox/springfox#888]
We have a custom JsonPrefix set for JSON Vulnerability Protection. The Springfox Swagger UI silently fails to load when this is enabled. Disabling the custom jsonPrefix allows the UI to work correctly.

I think a patch would be needed to the javascript in the Springfox Swagger UI, but I'm not sure how that would work since the JS doesn't have access to the value of this jsonPrefix.

So perhaps another workaround is to serve the resources needed by the UI with the prefix disabled, but I haven't been able to get this to work yet. I couldn't seem to find a workaround so I'm opening this bug here for now.

```
    @Bean
    MappingJackson2HttpMessageConverter mappingJackson2HttpMessageConverter() {
        MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
        converter.setObjectMapper(jaxonObjectMapper());

        //For JSON Vulnerability Protection
        //https://docs.angularjs.org/api/ng/service/$http
        //http://haacked.com/archive/2008/11/20/anatomy-of-a-subtle-json-vulnerability.aspx/
        converter.setJsonPrefix(")]}',\n");

        return converter;
    }
```

**Comment by dilipkrish** [comment]
Need to think about how to solve this issue.... ideas? Thanks for reporting! :+1:

**Comment by jeffsheets** [comment]
if we could pass params into the UI code, via URL or properties, then the JS could be modified to strip the JSON prefix. This is essentially what the angular.js codebase does.

But since the springfox swagger UI is served via a webjar, I'm not sure how we could set any properties on it besides adding a URL param for a custom json prefix.

A more brittle approach would be just hardcoding a couple of json prefixes to detect in JS that might be used. Would work great for me :-) but it wouldn't be a long term solution

**Comment by dilipkrish** [comment]
@jeffsheets How about reporting this issue on the  swagger-ui project. That way there is no maintenance on our end

**Comment by jeffsheets** [comment]
Looks like a similar bug is open on their end already
https://github.com/swagger-api/swagger-ui/issues/1354

**Comment by dilipkrish** [comment]
Closing this as it has a work around
