### ISSUE TITLE
Using API Key in header not working. 

### ISSUE THREAD

**Issue by mrgreen7** [springfox/springfox#891]
I'm using version 2.1.2 of both springfox-swagger2 and springfox-swagger-ui. I basically copied the example from http://springfox.github.io/springfox/docs/snapshot/#getting-started for using an api key in the header and after many hours of trying I still can not manage to get it to work. I'm access swagger-ui on the same server where my resources are deployed. Thus CORS should not be an issue I guess. 

No api key header is set when sending any request. Can I even use an api key in the header that I can set manually in swagger-ui using the field in the HTML-header? Because from looking at the Springfox js code it actually seems as if that is not possible:

         function addApiKeyAuthorization() {
            var key = encodeURIComponent($('#input_apiKey')[0].value);
            log("key: " + key);
            if (key && key.trim() != "") {
              var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", key, "query");
              window.swaggerUi.api.clientAuthorizations.add("api_key", apiKeyAuth);
              log("added key " + key);
            }
          }
Here, "query" is hard coded. I'd like to be able to set the api key in the swagger-ui though. Is that possible?

When I open swagger ui it gives me: Uncaught TypeError: Cannot read property 'clientAuthorizations' of null in the function above. This only happens every other refresh i.e. there seems to be some race condition. Here is what is sent to swagger-ui:

http://pastebin.com/Kbrzaupg

**Comment by dilipkrish** [comment]
I'll take a look at this, not sure what the problem is

**Comment by mongofish** [comment]
I can confirm this issue.  In to have better support for different type of authorization methods, all three parameters for ApiKeyAuthorization needs to be dynamic.
We currently only use the apiKey field in SecurityConfiguration class.  One possible solution is add additional field such as `authorizationKey` and `authorizationMethod`, which could then be used to create  `ApiKeyAuthorization` object in the front-end:
`var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization(security.authorizationKey, security.apiKey, security.authorizationMethod);`

**Comment by prabhat1790** [comment]
I am facing the same issue as described in the overview, what was the resolution for this? has this been released? I am using version 2.2.2
