### ISSUE TITLE
Docket.ignoredParameterTypes() removes classes completly

### ISSUE THREAD

**Issue by thomseno** [springfox/springfox#893]
Just migrated our project from swagger-springmvc to springfox 2.1.2 and recognized, that my ignoredParameterTypes are missing completely in swagger:
swagger-springmvc:
![swagger_ui](https://cloud.githubusercontent.com/assets/4829874/9060197/d64d88da-3ab1-11e5-83a4-35e99351312d.jpg)
![swagger_ui](https://cloud.githubusercontent.com/assets/4829874/9060207/ea8e1b66-3ab1-11e5-9c37-23f5b8fcd714.jpg)
springfox:
![swagger_ui](https://cloud.githubusercontent.com/assets/4829874/9060223/08dad910-3ab2-11e5-9be7-46bb8e3e240e.jpg)
![swagger_ui](https://cloud.githubusercontent.com/assets/4829874/9060227/166ec7b2-3ab2-11e5-8c0d-46645851b751.jpg)
SwaggerConfig:
Just ignoring org.joda.time classes
```java
        return new Docket(DocumentationType.SWAGGER_2)
            .apiInfo(new ApiInfo("IBS", "REST services", apiVersion, null, null, null, null))
            .ignoredParameterTypes(DateTime.class)
            .ignoredParameterTypes(LocalDate.class)
            .ignoredParameterTypes(LocalTime.class)
            .ignoredParameterTypes(LocalDateTime.class)
            .pathMapping("/api/v1")
            .groupName("1_rest")
            .select()
            .paths(ibsRestPaths())
            .build();
```

**Comment by dilipkrish** [comment]
@thomseno that was a bug unfortunately. the right way to hide properties is to either use an annotation to mark it as such `@ApiModelProperty(hidden=true)`. Or if you're only hiding it cos its generating deep models you don't care about consider using the `docket.directModelSubstitute(LocalDate.class, String.class)`

**Comment by thomseno** [comment]
Hi @dilipkrish thanks for the answer. The intention was to prevent generation of deep models. But if I use `docket.directModelSubstitute(LocalDate.class, String.class)` the original type of the field (`LocalDate`) will not be visible anymore, because something like this will be generated:
```javascript
{
    "printId": "string",
    "printDate": "string"
}
```
So if I have something like this
```javascript
{
    "validFrom": "string",
    "validTo": "string"
}
```
it's hard to decide what input the service expects (`LocalDate` or `LocalDateTime`). So how do I handle this?

**Comment by dilipkrish** [comment]
@thomseno that could go in the description via `@ApiModelProperty#notes`

**Comment by cbornet** [comment]
@thomseno you can use this:
```java
docket
.directModelSubstitute(LocalDate.class, java.sql.Date.class)
.directModelSubstitute(LocalDateTime.class, Date.class)
```
You will get
```json
                "localdate":
                {
                    "type": "string",
                    "format": "date"
                },
                "`localdatetime":
                {
                    "type": "string",
                    "format": "date-time"
                },
```
