### ISSUE TITLE
Is there a way to load my own ApiModelProperty annotation?

### ISSUE THREAD

**Issue by awenblue** [springfox/springfox#898]
I use swagger in my spring project which works as a server,  and there is a common module both used by server and android client . 

The common module contains request and response class. And i describe the property in these classes with @ApiModelProperty

when android client uses this common.jar, it also needs the dependence package swagger-annotations.jar. But it may not be good for app's size .

So, i want to declare a annotation as same as ApiModelProperty in common module  instead of the one in swagger-annotations.jar , let it load when the server starts , and android client will not need swagger-annotations.jar any more.

But i can't find a way to load my own ApiModelProperty annotation, can you help me? 

thanks

**Comment by dilipkrish** [comment]
Simpler than loading your own @ApiModelProperty is to not even use any of the swagger annotations. Your documentation may not be as complete as the annotations help you with but your runtime will be much lighter

**Comment by awenblue** [comment]
Thanks for you answer.

Yes, like you said, the reason i want to load my own ApiModelProperty  annotation is that when i build the common module for android client i can set annotation RetentionPolicy.SOURCE.

And i run server with RetentionPolicy.RUNTIME. So other developers can see the description of class‘s property  in common module  in the api-docs using browser.

class in  common module  like below:
public class BaseParam{

	@ApiModelProperty(value="Shop Id (10000~99999)",required=true)
	private long shopId;

	public long getShopId() {
		return shopId;
	}

	public void setShopId(long shopId) {
		this.shopId = shopId;
	}
}


In a word,  why i want to load my own ApiModelProperty  annotation is that i just need to change annotation RetentionPolicy type.

Sorry for my clearless description,  is there another way can do that i want?

Thanks

**Comment by awenblue** [comment]
I have found a way to solve the problem,  and i just got the source code and replaced the import of ApiModelProperty in source code with the common module one which i want to load.

Now all descriptions of properties in the common module can completely show for us again  without the dependency on swagger-annotations.jar

Thanks a lot.

**Comment by dilipkrish** [comment]
@awenblue you do realize that path means you'll never be able to apply incremental updates without recompiling from source right?

**Comment by awenblue** [comment]
yes, i see. But i have no idea about this problem without using that way. And the swagger is really suitable for the common module when android and ios  check the api documents. is there a better way to do that ?

thanks
