### ISSUE TITLE
@ApiModelProperty(allowableValues = "range[min, max]") not working

### ISSUE THREAD

**Issue by pn279j** [springfox/springfox#907]
I am using springfox library to generate swagger documentation. @ApiModelProperty(allowableValues = "range[min, max]") does not seem to work as expected. Any ideas? Thanks!

**Comment by dilipkrish** [comment]
No idea! May be some details would help. Please take a moment to look over our [issue submission guidelines](https://github.com/springfox/springfox/wiki/Issue-Submission)

**Comment by pn279j** [comment]
We have a JSR 303 annotation @Size(min = 1, max = 10) that we want to represent in Swagger documentation in our project. We are using the annotation @ApiModelProperty(allowableValues = "range[1, 10]" but it is not reflecting the range in Swagger UI. Springfox version used is 2.1.2.

**Comment by dilipkrish** [comment]
That is a limitation of swagger-ui
