### ISSUE TITLE
Bad URL when using "try it out!" swagger ui functionality with RequestParam (query param)

### ISSUE THREAD

**Issue by Fabrice-Deshayes-aka-Xtream** [springfox/springfox#909]
Hello,

my api method is design like this in my spring-boot application :

```java
@RequestMapping(value = "/api/v1/party/{msisdn}", method = RequestMethod.GET, produces = { MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE })
public ApiPartyResponse party(@PathVariable String msisdn, @RequestParam("source") PartySourceRestriction partySourceRestriction, @RequestParam String fileId) throws BusinessException {
```
i use theses dependency for dealing with swagger stuff
```xml
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.1.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.1.2</version>
		</dependency>
```
my api is working well, my swagger ui is ok too but the "try it out!" button don't work because generated path is not good.

as you can see on screenshot bellow, "{?source,fileId}" in path should not be here.
Is it a bug in swagger json generation, on swagger ui or in my usage of all of that ?

![image](https://cloud.githubusercontent.com/assets/7294270/9228322/48f5d2cc-4118-11e5-9eca-19291cb9d429.png)

thanks for helping.

regards.

**Comment by dilipkrish** [comment]
Disable `enableUrlTemplating` In your docket and that will fix your problem

**Comment by Fabrice-Deshayes-aka-Xtream** [comment]
thanks ! it's working now.

**Comment by pavel-mikhalchuk** [comment]
Hi!

If I disable '''enableUrlTemplating''' then we end up with https://github.com/springfox/springfox/issues/750 for some other APIs. What would you suggest?

Thanks!
