### ISSUE TITLE
Documentation generate empty model when input is an interface but not always

### ISSUE THREAD

**Issue by Richou** [springfox/springfox#911]
Hello, 

I'm using the springfox version 2.0.1
I have a controller and a RequestMapping with a RequestBody as arguments, the RequestBody argument is an Interface.

```java
@ApiOperation(value = "An Operation", httpMethod = "POST", response = AResponse.class)
@RequestMapping(value = "/anOperation", method = RequestMethod.POST)
@ApiResponses(value = {
        @ApiResponse(code = HttpServletResponse.SC_BAD_REQUEST, message = "Bad Request")
})
public @ResponseBody AResponse doPostAnOperation(
        @ApiParam(name = "inputValues", required = true) @RequestBody InputValues inputValues) // InputValues is an interface with others interface fields
        throws ApiException {
    // Do something
    return new AResponse();
}
```

The Model Schema generated is an empty object

```json
{}
```

But if I add an other RequestMapping with in ApiOperation the class of the Input of my first request as response the Model Schema generated is well formed

```java
@ApiOperation(value = "void", httpMethod = "GET", response = InputValues.class)
@RequestMapping(value = "/void", method = RequestMethod.GET)
public void avoid() {
}

@ApiOperation(value = "An Operation", httpMethod = "POST", response = AResponse.class)
@RequestMapping(value = "/anOperation", method = RequestMethod.POST)
@ApiResponses(value = {
        @ApiResponse(code = HttpServletResponse.SC_BAD_REQUEST, message = "Bad Request")
})
public @ResponseBody AResponse doPostAnOperation(
        @ApiParam(name = "inputValues", required = true) @RequestBody InputValues inputValues) // InputValues is an interface with others interface fields
        throws ApiException {
    // Do something
    return new AResponse();
}
```

Do you have an exponation for that ?
Thanks !
Regards.

**Comment by dilipkrish** [comment]
@Richou thanks for reporting! This has already been addressed via a seemingly unrelated issue #897  This issue should be fixed in the upcoming 2.2.0 release.

**Comment by dilipkrish** [comment]
Also you might want to atleast upgrade to 2.1.2

**Comment by Richou** [comment]
Okay, thanks a lot !

**Comment by agarwalroo** [comment]
I am able to reproduce the reported problem with versions 2.2.2 as well as 2.2.3-SNAPSHOT. 

Can you please retest and make sure that the fix is still in place.

**Comment by agarwalroo** [comment]
I would like to reopen this bug.

**Comment by Richou** [comment]
Hello, I did not test with versions 2.2.2 or 2.2.3-SNAPSHOT yet, but I will as soon as possible.
