### ISSUE TITLE
@BeanParam-type request parameters aren't handled properly

### ISSUE THREAD

**Issue by ejain** [springfox/springfox#912]
Given a controller like:

    @RequestMapping(value = "/", method = GET)
    @ApiOperation(value = "Find items")
    public List<Item> find(Query query) {
      ...
    }

    class Query {
      String text;
      int limit;
    }

Spring MVC lets me do requests like /items/?text=foo&limit=10. Unfortunately, the generated docs show this endpoint taking a single "query" (JSON object) parameter.

**Comment by dilipkrish** [comment]
`@BeanParam` === `@ModelAttribute`. As long as Query is a is a java bean (meaning conforms to the java bean spec, with getters and setters. It should be the behavior you're looking for.

**Comment by ejain** [comment]
Looks like the key is to both have getters/setters (setters alone are not sufficient) **and** use `@ModelAttribute` (which otherwise isn't necessary in Spring MVC).
