### ISSUE TITLE
@ApiModelProperty(hidden=true) does not work

### ISSUE THREAD

**Issue by zmitrok** [springfox/springfox#913]
@ApiModelProperty(hidden=true) does not seem to have any effect on the generated swagger2 JSON.

I am using Spring Boot 1.2.5, Jackson 2.6.0, Springfox 2.1.2

I stepped through the OptimizedModelPropertiesProvider and it did not seem to filter out hidden model properties.

**Comment by zmitrok** [comment]
I tried to use the new SPI and filter out hidden properties in a custom ModelBuilderPlugin but I could not find a way to modify the properties through the ModelContext or ModelBuilder.

**Comment by dilipkrish** [comment]
It should totally [filter hidden properties](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/property/OptimizedModelPropertiesProvider.java#L193). 

Its possible its a bug, Would you mind creating a reproducible use case by forking one of the [springfox-demo](https://github.com/springfox/springfox-demos) apps?

**Comment by zmitrok** [comment]
I am looking at the OptimizedModelPropertiesProvider@2.1.2 release and I don't see it filtering out hidden properties - the from(properties) filter() stanza is missing. It looks like this bug may have been fixed post 2.1.2 release? Is there a post 2.1.2 SNAPSHOT I could use?

**Comment by dilipkrish** [comment]
Yes 2.1.3-snapshot is available. You'd have to include the jfrog snapshot repository. However if you can wait the weekend we should be releasing 2.2.0.

**Comment by zmitrok** [comment]
Confirmed fixed in 2.1.3-SNAPSHOT. Will switch to 2.2.0 as soon as it's ready. Thanks!
