### ISSUE TITLE
Does swagger2 have any support for java.time introduced in java8

### ISSUE THREAD

**Issue by zhukboh** [springfox/springfox#914]
Hi. Unfortunately I can`t understand how to make swagger2 show in Model Schema classes from java.time in proper way. I use ISO format for dates but swagger2 shows, for instance, LocalDateTime like 
```
      {
        "endDate": {
          "chronology": {
            "calendarType": "string",
            "id": "string"
          },
          "dayOfMonth": 0,
          "dayOfWeek": "MONDAY",
          "dayOfYear": 0,
          "hour": 0,
          "minute": 0,
          "month": "JANUARY",
          "monthValue": 0,
          "nano": 0,
          "second": 0,
          "year": 0
        }
```
Does swagger2 have any support for java.time or maybe there`s a way to customize descriptions for objects shown in Model Schema, but I can`t find it.  eg I want to show for all my LocalDateTime fields message like
```
"date": "YYYY-MM-DDTHH:mm:ss"
```
where "YYYY-MM-DDTHH:mm:ss" is a constant string for message, "date" - field name.

**Comment by dilipkrish** [comment]
Typically these are handled via `Docket#directModelSubstitute(LocalDateTime.class, String.class)`. However you won't have any format or validation info.

**Comment by ejain** [comment]
I'm doing `Docket#directModelSubstitute(LocalDateTime.class, String.class)`, and then e.g. `@ApiModelProperty(value = "the creation date", dataType = "date-time", example = "2015-01-31T08:00:00")`. Unfortunately, neither the `dateType` nor the `example` show up anywhere in the generated docs. Am I doing something wrong, or is this just a limitation of SpringFox?

**Comment by dilipkrish** [comment]
Yes it is. I'll write up a feature request for this.

**Comment by zloster** [comment]
@ejain According to [`Springfox` documentation](http://springfox.github.io/springfox/docs/current/#overriding-property-datatypes) the `dataType` should be fully qualified Java-class name.
