### ISSUE TITLE
Support @ApiParam#hidden()

### ISSUE THREAD

**Issue by lukewpatterson** [springfox/springfox#920]
see swagger-api/swagger-core/issues/1188

I added Principal to my method arguments (see [more examples of available types](http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-ann-arguments)) 
intending for Spring to inject it rather than requiring it from the request.  Since I can't hide the param, API consumers incorrectly think they have to send it in the request.

Anyways, would be great to be able to hide that method argument.

**Comment by dilipkrish** [comment]
You should be able to use the `ignoredParameterTypes` In your docket to ignore these types

**Comment by lukewpatterson** [comment]
Thanks @dilipkrish!

That gets me through for now.  I'll ignore the types project-wide.

**Comment by dilipkrish** [comment]
:+1: Closing this issue! Let me know if u have any more questions

**Comment by tomb50** [comment]
Hi @dilipkrish 

Just checking if there a more general workaround for this lack of ApiParams#hidden support. Facing the same issue, though params are just Strings etc.

Can subclass and use the above method if required.

Thanks

**Comment by kyeung2** [comment]
HI,

I would also like this feature to work on a per @apiParam level. As I don't want to ignore an entire type via ignoredParameterTypes.

Guidance on this issue would be welcomed.

Thanks
