### ISSUE TITLE
@ApiModelProperty doesn't seem to generate elements 

### ISSUE THREAD

**Issue by eoliphan** [springfox/springfox#924]
I'm using @ApiModelProperty on some model classes in a spring boot project, but the annotated property doesn't show up in the swagger-ui site.  The @ApiModel annotation seems to work fine as for @ApiModel("My Model") I get the following:
````
My Model {
} 
````
but it's always empty.  Not sure what the problem is.

**Comment by dilipkrish** [comment]
@eoliphan what does your mode look like. If your model is not serializable according to jackson you're not going to see any property. Also what version are you using?

**Comment by eoliphan** [comment]
Hi, I thought, I'd updated this, I'm on 2.2.2 and yes the problem was that I was missing the Serializable interface, it's all good now.  Thanks!
