### ISSUE TITLE
java.net.UUID

### ISSUE THREAD

**Issue by ejain** [springfox/springfox#925]
SwingFox appears to be smart enough to know that a UUID is a `string` formatted as a `uuid`, but still includes an unnecessary definition of the type in the generated Swagger spec:

        "UUID": {
            "properties": {
                "leastSignificantBits": {
                    "type": "integer",
                    "format": "int64"
                },
                "mostSignificantBits": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        }

**Comment by dilipkrish** [comment]
This is a bug, tho' it will not affect your service specification other than adding this spurious unused model. thanks for reporting :+1:

**Comment by notyalca** [comment]
I found the same bug.  Looking forward to the 2.3.0 release!

**Comment by cleankod** [comment]
@ejain can you provide the code example of how you got the UUID to be `string` with `uuid` format? All I am getting is:
```json
"uuidExample": {
"type": "string"
}
```
I can't get it to add `"format": "uuid"`.

**Comment by dilipkrish** [comment]
@cleankod that is a bug, would you mind creating a new issue for that.
