### ISSUE TITLE
Change links in docs

### ISSUE THREAD

**Issue by webron** [springfox/springfox#928]
Looks like some of the links in the docs (gh-pages) link to the old wordnik repository instead of the new swagger-api. I'd submit a PR but not sure what's the proper procedure and how you maintain the docs.

**Comment by dilipkrish** [comment]
Np the docs are [in the repo](https://github.com/springfox/springfox/tree/master/asciidoc). The CI env updates the snapshot version in the gh pages and the release version isn't updated until we release. 

Alternatively u could point me to the right place as well. 


You could point me to the places as well.

**Comment by webron** [comment]
https://github.com/springfox/springfox/blob/gh-pages/docs/2.2.2/index.html#L1274 is one example. I'd do search and replace to all `github.com/wordnik` but it looks like you also reference an actual wordnik project there.
