### ISSUE TITLE
@ModelAttribute Generates Different Output than @RequestBody

### ISSUE THREAD

**Issue by timothysoehnlin** [springfox/springfox#929]
I'm currently running into an issue where the @ModelAttribute annotation on a GET request mapping, generates different output than the @RequestBody annotation on a POST request mapping.  One of the key things I'm seeing is the lack of support for arrays, and allowable values.

-----

Looking at 

https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/parameter/ExpandedParameterBuilder.java

Looking at the 'apply' method:
```
  @Override
  public void apply(ParameterExpansionContext context) {
    AllowableValues allowable = allowableValues(context.getField());

    String name = isNullOrEmpty(context.getParentName())
            ? context.getField().getName()
            : String.format("%s.%s", context.getParentName(), context.getField().getName());

    context.getParameterBuilder()
            .name(name)
            .description(null).defaultValue(null)
            .required(Boolean.FALSE)
            .allowMultiple(Boolean.FALSE)
            .type(resolver.resolve(context.getField().getType()))
            .modelRef(new ModelRef(context.getDataTypeName()))
            .allowableValues(allowable)
            .parameterType("query")
            .parameterAccess(null);
  }
```

The issue I'm seeing is that it doesn't allows multiple, and every field has a model ref.  So items that are lists of strings are not working properly.

**Comment by dilipkrish** [comment]
@timothysoehnlin this is by design. It's meant to only support scalar values. Plus it might be a little spotty 
- on multiple/array properties.
- these are parameters available in the query string. 
Really if u need a rich domain model it's better to use the `@RquestBody` As it utilizes the message converter machinery.

**Comment by timothysoehnlin** [comment]
I would prefer to use @RequestBody, but as far as I know, I can't use @RequestBody with GET requests.  Swagger supports non-scalar values in the Query String.  The @ApiParam's also seem to support it, but not honor it when generating the JSON.

**Comment by dilipkrish** [comment]
@timothysoehnlin sorry dint check to see that it was a `GET`. I think its a bug that allow multiples is not automatically detected.

**Comment by timothysoehnlin** [comment]
Allowable values and multiple also seems not to be honored via
@apiimplicitparam

**Comment by dilipkrish** [comment]
@timothysoehnlin It should work as expected. Could you perhaps provide a breaking test?

**Comment by timothysoehnlin** [comment]
@dilipkrish I stand corrected, the allowable values do appear to be used.  I realize now the issue for me was that @ApiModelProperty doesn't have the field for allowableValues, and since I'm using that to convert to an @ApiImplicitParam, I'm not able to copy that data over.
