### ISSUE TITLE
Type Rules are not completely working

### ISSUE THREAD

**Issue by blvp** [springfox/springfox#931]
I have strange behavior with spring-hateoas.
Controller method looks like: 
```java
public ResponseEntity<PagedResources<FrontendAuditLog>> getUserLoginLogoutJournal()
```

my Docket configured with following:
```java
.alternateTypeRules(newRule(
    typeResolver.resolve(ResponseEntity.class,
          typeResolver.resolve(PagedResources.class, 
              typeResolver.resolve(WildcardType.class))
           ),
    typeResolver.resolve(WildcardType.class)
)
```

So I'd like to see PagedResources description with my FrontendAuditLog description also, but I get only PagedResources description with erased FrontendAudiLog model description

**Comment by dilipkrish** [comment]
@blvp I don't follow. Could you perhaps share what your expectation of what the model should look like in contrast with what you're seeing (the swagger json)?

**Comment by dilipkrish** [comment]
Closing this has there hasn't been much activity on this question. Please feel free to reopen if your problem isn't solved yet
