### ISSUE TITLE
defaultValue parameter in RequestParam is ignored

### ISSUE THREAD

**Issue by rcruzper** [springfox/springfox#933]
Hi,
if you set a method param:
@RequestParam(defaultValue="10") String param
the json generated ignores defaultValue
I tried using @DefaultValue annotation and it is working, but I would prefer to use the @RequestParam option.

**Comment by dilipkrish** [comment]
I think `@DefaultValue` annotation is only working by chance. We don't really support that annotation. But for sure query string parameters should support default values

**Comment by dilipkrish** [comment]
This bug is related to https://github.com/swagger-api/swagger-core/issues/1402

Will provide a work around for this

**Comment by gsergiu** [comment]
For other developers which get in the same problem:
I needed to struggle a bit with springfox in order to see this working in my environment. 
Registering the following bean in the application-context.xml solved the problem
<bean class="springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper">
 </bean>

@dilipkrish 
It would be nice to add this bit of information into the documentation:
http://springfox.github.io/springfox/docs/current/#moving-from-swagger-springmvc

**Comment by dilipkrish** [comment]
@gsergiu what bean?  Also would be great if you could update [the docs](https://github.com/springfox/springfox/tree/master/docs/asciidoc) via a PR since you have all the context.

**Comment by gsergiu** [comment]
@dilipkrish  oh .. sorry .. I forgot to paste the bean registration. It is about DocumentationPluginsBootstrapper
<bean class="springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper">
 </bean>

**Comment by gsergiu** [comment]
@dilipkrish 
As I am using xml based configuration I would add this information in section 5.4
http://springfox.github.io/springfox/docs/current/#docket-xml-configuration

However I'm not sure about the following issues:
1) The section 5.4 and 5.5 should be kept in sync (xml and annotation based configurations) .
2) Is there is way to register the bean by default?  Both springfox-swagger-common and springfox-spring-web are in the springfox-swagger2 dependencies. Moreover there are two ParameterBuilderPlugin in dependencies, and (spring-web) ParameterDefaultReader has a higher precedence as (swagger-common) ApiParamParameterBuilder. So I would expect that the first one should be used by default... but I might be wrong... (I'm not sure if I miss something regarding the configurations or .. if there is still some bug around this functionality)
