### ISSUE TITLE
tags parameter in @Api is ignored by ApiOperation reader/mapper

### ISSUE THREAD

**Issue by rcruzper** [springfox/springfox#934]
Hi,

my @RestController classes have a tag set in Api annotation as follows:
@Api(tags = { "/api/example })
but the methods of the controller are ignoring it, they are setting tag by default as "class-name" in the resulting json.
I made a workaround setting the tag in all methods. Is it a bug or is it the correct way to solve the problem?

**Comment by dilipkrish** [comment]
Thanks for reporting

**Comment by dilipkrish** [comment]
@rcruzper this should be fixed via #919

**Comment by rcruzper** [comment]
Great, thank you!
