### ISSUE TITLE
Full Path for RequestMapping

### ISSUE THREAD

**Issue by flavouski** [springfox/springfox#935]
Example:

```
@RequestMapping(value = "/file/metadata/**", method = RequestMethod.GET, produces = {MediaType.APPLICATION_JSON_VALUE})
public Map getFileMetadata(@Path String path) throws IOException {
```

The file is located at **/folder/anotherFolder/.../file.xml**
@PathVariable doesn't work for this as it only would retrieve "folder".  We created our annotation for it.  But is there a way to tell SpringFox to insert the variable onto the URL rather than as a parameter?

**Comment by dilipkrish** [comment]
@flavouski This is pretty easily solved using [regex patterns](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-ann-requestmapping-uri-templates-regex). I think creating an annotation may not be required.

**Comment by flavouski** [comment]
@dilipkrish This is only applicable to one folder in the hierarchy (or parts in one level of that hierarchy).
i.e. I tried:
/file/metadata/{path:.+}
.../folder1/                works fine
.../folder1/folder2     Request method 'GET' not supported

Which reflects the same statements made on here for Spring 3 (though I am using Spring 4):  http://stackoverflow.com/questions/4542489/match-the-rest-of-the-url-using-spring-3-requestmapping-annotation

**Comment by dilipkrish** [comment]
@flavouski not sure if I have a good solution for you 😳

If you're interested in only getting it to work with swagger-ui, I suspect you can try jamming in the rest of the path in another (fake) path variable

```java
@RequestMapping(value = "/file/metadata/{fakePath}/**", method = RequestMethod.GET, 
     produces = {MediaType.APPLICATION_JSON_VALUE})
public Map getFileMetadata(@Path String fakePath) throws IOException {
...
//use request.getAttribute( HandlerMapping.PATH_WITHIN_HANDLER_MAPPING_ATTRIBUTE ) 
//and fakePath to get what you want.
}
```

**Comment by mattsheppard** [comment]
Just bumped into this myself - I don't suppose there's been any progress on it in the intervening years?

**Comment by dilipkrish** [comment]
Its kind of imprecise from a specification perspective, so no there hasn't been much progress to support this or matrix parameters.
