### ISSUE TITLE
Is there anyway that the @ResponseHeader is rendered in json?

### ISSUE THREAD

**Issue by MarkVanVenrooij** [springfox/springfox#937]
Is there anyway to get the response headers in the generated JSON. At this moment I have no clue how to do this.

Example:
```Java
@ApiResponse(code = 201, message = "Resource created.",
    responseHeaders = {
        @ResponseHeader(name = "ETag", 
              description = "The version id of the newly created resource", 
              response = String.class)})
.....
```
Should be available as.
```json
"responses": {
    "201": {
        "description": "Resource created.",
        "headers": {
            "ETag": {
                "type": "string",
                "description": "The version id of the newly created resource."
                }
.....
```

**Comment by dilipkrish** [comment]
This is currently not supported by the internal models. Thanks for reporting this gap 👍🏼

**Comment by dilipkrish** [comment]
@MarkVanVenrooij would you like to try and submit a pr for this?

**Comment by jjzabkar** [comment]
@dilipkrish : Could you perhaps point to where in the internal model it's not supported?  I would be happy to try my hand at a pull request.

**Comment by dilipkrish** [comment]
@jjzabkar absolutely! Any help is much appreciated. Below are the steps roughly. Please feel free to ask any questions you might have

- [ ] Start with adding a property to [ResponseMessageBuilder](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/builders/ResponseMessageBuilder.java#L28) 
```java
private Map<String, ModelProperty> headers; // springfox.documentation.schema.ModelProperty
```
- [ ] Add the property to [ResponseMessage](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/service/ResponseMessage.java)
- [ ] Read the annotation and populate the [header values here](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/SwaggerResponseMessageReader.java#L98-L102) using the response message builder you created :point_up: 
- [ ] Update the [response mapper](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ServiceModelToSwagger2Mapper.java#L134) to use the internal models.
