### ISSUE TITLE
Provide default descriptions for non-200 status codes

### ISSUE THREAD

**Issue by ejain** [springfox/springfox#941]
For 200 responses, SpringFox adds `"description" : "OK"`. Could do the same for other, common response code (e.g. 201, 204 etc)?

**Comment by dilipkrish** [comment]
using `@ApiResponses { {@ApiResponse ... })` annotations doesn't bring up descriptions?

**Comment by ejain** [comment]
I'm sure it does, but would be nice if a default description was generated for 201, 204 etc when no `@ApiResponses` annotation is present, as it does for 200.

**Comment by dilipkrish** [comment]
How are u currently describing that your Api produces 203, 204 etc.?

**Comment by ejain** [comment]
With annotations like `@ResponseStatus(HttpStatus.CREATED)`.

**Comment by dilipkrish** [comment]
That should work. If not I'll tag it as a bug

**Comment by ejain** [comment]
Looks like a bug then. The status codes show up in the Swagger spec, but some without a default description.
