### ISSUE TITLE
Swagger UI Hiding API listing

### ISSUE THREAD

**Issue by dpatra1** [springfox/springfox#942]
Hi All,

I have a two different spring boot applications getting deployed in a single tomcat server.

Initially i have integrated Swagger2 in one module and i am able to see the API documentation based on the groups i have defined. 

Issue : Now when i have integrated Swagger2 in the other module, i dont see the API list from the second application in swagger UI page. The URL which i am accessing for swagger page is "http://<host>:8080/swagger-ui.html" . I can only see the APIs from the first module which i have integrated. So i am not sure how i can access all the APIs from both the applications in a single swagger UI page. If thats not possible than how i have to access both of the API documentation when they are in the same host and same port ?

Please help me resolving this conflict.

Thanks,
Deba

**Comment by dilipkrish** [comment]
Could you clarify your question?

> Initially i have integrated Swagger2 in one module and i am able to see the API documentation based on the groups i have defined.

- What is does  _module_ mean? are you referring to the 2 springboot apps as modules? 
- Are you using springfox-swagger-ui?
- Which app is serving up swagger-ui.html

**Comment by dpatra1** [comment]
Question 1 : Yes there are two separate springboot apps
Question 2 : Yes i am using springfox-swagger-ui (swagger2 annotation)
Question 3 : For now only the one which i have added first is showing all the APIs but i dont see anything from the second app. But both should have swagger-ui.html

**Comment by dilipkrish** [comment]
see [this post to configure it](https://groups.google.com/forum/#!searchin/swagger-swaggersocket/multiple/swagger-swaggersocket/g8fgSGUCrYs/A8Ms_lFOoN4J). Basically you need 3 springboot applications. Post back if you have questions

**Comment by dpatra1** [comment]
Nope. I have two spring boot applications and both are configured with swagger and both are deployed to same server. I can see swagger page for one not for the other .

Let me know if it's still confusing .

**Comment by dilipkrish** [comment]
It's not confusing.  You NEED 3 applications to do what you need to do with springfox-swagger-ui

**Comment by dpatra1** [comment]
I am confused when you say 3 applications :)

**Comment by dilipkrish** [comment]
Ok :) lets break it down... for e.g. 

- spring boot app 1, has context path `/app1`, its `swagger-ui.html` is available @ `http://host/app1/swagger-ui.html`
- spring boot app 2, has context path `/app2`, its `swagger-ui.html` is available @ `http://host/app2/swagger-ui.html`

So its not clear to me how you are serving `http://host/swagger-ui.html` without a context path, and how you're determining which app is getting to serve it up.

The post I linked to is basically suggesting that you hand roll a third app and create a service similar to [ApiResourceController.java](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/ApiResourceController.java) that can provide you metadata on the other 2 apps. 

And of course, remove springfox-swagger-ui as a dependency in the 2 boot apps.

**Comment by dpatra1** [comment]
You are right. I am not providing any context path may be that's the reason it's only serving one. But why not other one.

So you want to create another service like you said ? Do you have any sample what u r talking here ?

**Comment by dpatra1** [comment]
@dilipkrish : I was looking at the post which you have mentioned but i am bit confused with the controlller which you have asked to add.

I dont need any security configurations so i cleaned up those lines of code and created the below class. But when i am starting my sprintboot applications its giving me error.

package com.diginsite.microservices.web;

import java.util.ArrayList;
import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger.web.SwaggerResource;

import com.google.common.base.Optional;

@Controller
public class ResourceController {
	public ResourceController() {
	}

	@RequestMapping(value = "/swagger-resources")
	@ResponseBody
	ResponseEntity<List<SwaggerResource>> swaggerResources() {

		List<SwaggerResource> resources = new ArrayList<SwaggerResource>();
                // Path for the micro services in one Controller.
		resources.add(resource("BFFBusinessCustomer", "/bff-web/v1/bbui/fis/*"));  
                // Path for the micro services in another Controller.
		resources.add(resource("Company", "/v1/fis/*"));
		resources.add(resource("BusinessCustomer", "/v1/fis/*"));
		return new ResponseEntity<List<SwaggerResource>>(resources,
				HttpStatus.OK);
	}

	private SwaggerResource resource(String swaggerGroup, String baseUrl) {
		SwaggerResource swaggerResource = new SwaggerResource();
		swaggerResource.setName(swaggerGroup);
		swaggerResource.setLocation(swaggerLocation(baseUrl, swaggerGroup));
		return swaggerResource;
	}

	private String swaggerLocation(String swaggerUrl, String swaggerGroup) {
		String base = Optional.of(swaggerUrl).get();
		if (Docket.DEFAULT_GROUP_NAME.equals(swaggerGroup)) {
			return base;
		}
		return base + "?group=" + swaggerGroup;
	}

}


======Error=====

Caused by: java.lang.IllegalStateException: Ambiguous mapping found. Cannot map 'apiResourceController' bean method 
org.springframework.http.ResponseEntity<java.util.List<springfox.documentation.swagger.web.SwaggerResource>> springfox.documentation.swagger.web.ApiResourceController.swaggerResources()
to {[/swagger-resources],methods=[],params=[],headers=[],consumes=[],produces=[],custom=[]}: There is already 'resourceController' bean method
org.springframework.http.ResponseEntity<java.util.List<springfox.documentation.swagger.web.SwaggerResource>> com.diginsite.microservices.web.ResourceController.swaggerResources() mapped.
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.registerHandlerMethod(AbstractHandlerMethodMapping.java:212)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:184)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:144)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:123)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:126)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	... 43 common frames omitted



I am not sure whether i am doing the right approach or i am missing something here.

Please help me resolving this issue

**Comment by dpatra1** [comment]
@dilipkrish : Do you have any other solution for this ? Like without creating another app how can i list out all the APIS from two different apps deployed in a single server ??

**Comment by dilipkrish** [comment]
Unfortunately no
