### ISSUE TITLE
Conform to Swagger 2.0 naming/output standards

### ISSUE THREAD

**Issue by webron** [springfox/springfox#944]
This has come across in a few other issues, but not a dedicated one.

I would ask that the Swagger 2.0 JSON is exposed using the `swagger.json` endpoint and not `api-docs` as it was with 1.2. This is of course for your consideration as there's no obligation, but rather a standard as introduced by the spec. 

Also, since YAML has become a first-class citizen in 2.0, I'd ask for the equivalent output of `swagger.yaml` to be available (following #651).

For your consideration.

**Comment by dilipkrish** [comment]
@webron Thanks for pointing these out. 

While `swagger.json`, seems to be a convention, we are deviating it for a couple of reasons. 
- springfox still supports swagger 1.2 and swagger 2.0 simultaneously. So from a library perspective we want a consistent experience across those two paths. Seems weird to have /api-docs for v1 and /swagger for v2.
- There are a bunch of downstream libraries like jHipster that are already using the api-docs endpoint. And they configure their product security with wildcards `**/api-docs`. So it would be a breaking change for consumers who are doing similar things even if not using jHipster.
- Lastly its [totally configurable](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints) so folks wanting that convention can totally use customize it :) 

About the yam support, there is already a story for that, but no bandwidth. If someone would lend a hand it would be super helpful.

**Comment by webron** [comment]
@dilipkrish - thanks for the clarification, and the reasoning is perfectly understandable. The main reason I brought it up is that support-wise it sometimes slows down our ability to provide assistance, but it's not anything too substantial.
