### ISSUE TITLE
Fail to load existing JSON schemas into Swagger definitions section.

### ISSUE THREAD

**Issue by cipresso** [springfox/springfox#947]
Hi.  I'm creating a tool that generates Swagger and it needs to pull in existing JSON schemas to set as  BodyParameters .  I've tried Json.mapper().readValue(schemaFile, Model.class), but the result is incomplete.  

>> In the following example, "CA_PATIENT_ID" is nowhere to be found in the Model instance.

```json
{
	"type": "object",
	"properties": {
		"HEALTH": {
			"type": "object",
			"properties": {
				"CA_PATIENT_ID": {
					"minimum": 0,
					"maximum": 10000000000,
					"type": "integer"
				}
			}
		}
	}
}
```

>> In this example, "definitions" is not in the Model instance.

```json
{
	"type": "object",
	"properties": {
		"HEALTH": {
			"$ref": "#/definitions/HEALTH_content"
		}
	},
	"definitions": {
		"HEALTH_content": {
			"type": "object",
			"properties": {
				"CA_PATIENT_ID": {
					"minimum": 0,
					"maximum": 10000000000,
					"type": "integer"
				}
			}
		}
	}
}
```

Essentially is there a way to pull in existing JSON schemas to produce a self-contained Swagger doc?

Thanks much, --Ted

**Comment by dilipkrish** [comment]
@cipresso So couple of questions. 
- `Model.class` belongs to which library? 
- Where are you doing the `Json.mapper().readValue(schemaFile, Model.class)`?

**Comment by cipresso** [comment]
Hi. Thanks for replying.
 I'm using swagger-core, swagger-models, swagger-annotations at level 1.5.3-M1
1. Model.class := com.wordnik.swagger.models.Model 
2. I'm doing it while populating a com.wordnik.swagger.models.Swagger object.

    Swagger swagger = new Swagger();
    Model healthDef = Json.mapper().readValue(schemaFile, Model.class);
    swagger.addDefinition("HEALTH", healthDef);

**Comment by dilipkrish** [comment]
@cipresso that seems wrong... you need to use the the `io.swagger` dependencies. for e.g. this [swagger-models](http://mvnrepository.com/artifact/io.swagger/swagger-models/1.5.3) dependency.

**Comment by cipresso** [comment]
Hi. I am using all of swagger-core, swagger-models, swagger-annotations from the 1.5.3-M1 driver. In the 1.5.3-M1 driver all of the packages are named com.wordnik.swagger.* whereas in the stable driver all of the packages have been renamed to io.swagger.*.

![image](https://cloud.githubusercontent.com/assets/10523271/9635673/6eb0280c-514c-11e5-9964-3b03728b1e10.png)

**Comment by dilipkrish** [comment]
@cipresso you just restated what I just told you :)

Your  need to change your dependencies to use the renamed swagger dependencies

**Comment by cipresso** [comment]
Hi. I moved up to the stable driver and it's working now.  Thanks for your help!
