### ISSUE TITLE
Issues with Swagger-codegen for C#

### ISSUE THREAD

**Issue by amitbansal012** [springfox/springfox#950]
Hi Team,

I am trying to generate client-side code using Swagger-codegen [java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i test.json -l csharp -o test/]. I am using the v2/api-docs[json] for codegen. I am facing the following issues:

1. The RestSharp.dll generated does not have RestClient.addQueryParameters. Looks like its being used when creating a REST Request.This looks like a dependency issue. This was fixed when i manually created a dll from the latest RestSharp library. It will be great if the auto-generated dll is the latest version. Error:
```stacktrace
      src\main\csharp\IO\Swagger\Client\ApiClient.cs(66,17): error CS1061:
        'RestSharp.RestRequest' does not contain a definition for
        'AddQueryParameter' and no extension method 'AddQueryParameter'
        accepting a first argument of type 'RestSharp.RestRequest' could be
        found (are you missing a using directive or an assembly reference?)
src\main\csharp\IO\Swagger\Client\ApiClient.cs(80,40): error CS1061:
        'RestSharp.RestClient' does not contain a definition for
        'ExecuteTaskAsync' and no extension method 'ExecuteTaskAsync' accepting
        a first argument of type 'RestSharp.RestClient' could be found (are you
        missing a using directive or an assembly reference?)
```
2. Is there a way to add some parameters to the url formed for server call ? Use case: My services returns xml response by default. I can override this by appending "format=json" to the url. SInce Swagger supports Deserialization only for Json response, i need a solution for this. Another alternative can be to plug-in a custom deserializer. Please let me know the feasibility of both the options.

3. Is there a option to override the default communication protocol - HTTPS? My services are HTTP based, So i need a way to override the basePath `https://<hostName>:<portNumber>` generated in ApiClient.cs, to `http://<hostName>:<portNumber>`, ie, use http protocol.

4. The Client was trying to use IO.Swagger.Model [using IO.Swagger.Model;] which was not needed and didn't exist, if we don’t have any model dependency. Please let me know if this is a bug.

5. Although C# has char as a primitive data type, char in java gets converted to string in C#. Is this a bug or an expected behavior? Example: 
My java method looks like :

Interface:
```java
          	char getChar();
```

Impl:
```java
              @Override	
              @ApiOperation(value = "This is test service - getChar")
	      @RequestMapping(value = "/getChar", method = GET)
      	      @ResponseBody
	      public char getChar() {
		return 'a';
	     }
```

C#:
```csharp
           string GetCharUsingGET ();
```

6. Is there a bug in the support of 2D arrays? The generated C# should say List<List<int>>, instead it says List<List>, which is a compilation issue.
My java method looks like :
Interface:
```java
          	int[][] getPrimitiveDouble3();
```
Impl:
```java
              @Override	
              @ApiOperation(value = "This is test service - getPrimitiveDouble3")
	      @RequestMapping(value = "/getPrimitiveDouble3", method = GET)
      	      @ResponseBody
	      public int[][] getPrimitiveDouble3() {
		return null;
	     }
```

C#:
```csharp
           List<List> GetPrimitiveDouble3UsingGET ();
```

7. Is there a way to overwrite the default namespace? Example: from "IO.Swagger.Api" to "MyService.Api" 

Please guide me on the above issues.
Thanks,
Amit Bansal

**Comment by dilipkrish** [comment]
> It will be great if the auto-generated dll is the latest version.

You'd have to create an issue in the https://github.com/swagger-api/swagger-codegen repository.

> Is there a way to add some parameters to the url formed for server call ? Use case: My services returns xml response by default. I can override this by appending "format=json" 

You need to add the produces/consumes media type to the request mapping. That way it can support more media types. The alternative is to declare an request parameter for `format`

```java
...
@RequestMapping(value = "/getChar", method = GET, produces = {"application/json', "application/xml"})
...
```

> Is there a option to override the default communication protocol - HTTPS? 

That is really a client concern. Frankly I'm not familiar with what the swagger-code-gen generates, but typically you don't want to use the host/port provided by the definition. Especially if you want to port your clients applications across environments like for e.g. dev/test/prod etc.

While I've tried to answer your queries, to the best of my knowledge, these questions are not pertinent to this project at all. You'd be better off reporting these issues to the https://github.com/swagger-api/swagger-codegen repo.

**Comment by amitbansal012** [comment]
Hi,
Thank you for responding. I will try these options and post any further queries. I already posted this on the google group [https://groups.google.com/forum/embed/?place=forum/swagger-swaggersocket&theme=default&fragments=true&showsearch=false&showtabs=true&hideforumtitle=true&hidesubject=true&parenturl=http%3A%2F%2Fswagger.io%2Fforum%2F#!topic/swagger-swaggersocket/AoNJh01yk_I ], but as there was no response, i thought i will post it here as well.

Thanks,
Amit

**Comment by MarcinKwiatkowski1988** [comment]
Good morning all, 
generating the csharp library i got this error:

error CS1061: 'RestSharp.RestClient' does not contain a definition for 'ExecuteTaskAsync' and no extension method 'ExecuteTaskAsync' accepting a first argument of type 'RestSharp.RestClient' could be found (are you missing a using directive or an assembly reference?)

I tried also to put in the bin folder the RestSharp.WindowsPhone.dll instead of RestSharp.dll(and changed the compile.bat file) but is still not working. Can you help me please

**Comment by dilipkrish** [comment]
@MarcinKwiatkowski1988 this is not related to this library.. could you report the in appropriate library (swagger-codegen I think).

**Comment by MarcinKwiatkowski1988** [comment]
@dilipkrish Hi, since I saw that amit solved the same error here, and the title of this issue "Issues with Swagger-codegen for C#" I was positive it was the right place to write

**Comment by dilipkrish** [comment]
@MarcinKwiatkowski1988 Just to clarify the original issue reported had to do with generating a service description that was usable to generate the right types when used in `swagger-codegen`. Your error description does not seem like it has to do with the way the specification was rendered by ***this library***. It probably has more to do with the code-gen itself or the version of it that you're using.
