### ISSUE TITLE
Regression disabling schema validator

### ISSUE THREAD

**Issue by g00glen00b** [springfox/springfox#951]
The solution for the issue described in #796 does no longer work. In 690c126e704879d10001fb8c4b918068924673ba (2.1.2) you decided to move the `validatorUrl` out the constructor and it seems that this broke the option to change the `validatorUrl`.

Right now, whatever value I use within the `UiConfiguration` bean, the validator keeps using the online version. I can no longer set it to `null` (for example). Downgrading to the latest version using the constructor (2.1.1) solves the issue.

**Comment by dilipkrish** [comment]
Thanks for reporting. Would you be able to submit a patch?

**Comment by g00glen00b** [comment]
I'll see if I can do that. Didn't have much time lately though.

**Comment by dilipkrish** [comment]
@g00glen00b any change of getting in a pr?

**Comment by wind57** [comment]
@dilipkrish so I guess that if Im on version 2.2.2 of swagger and 2.1.3 of swagger-ui then it's considered broken?

**Comment by dilipkrish** [comment]
Haven't confirmed it but I suspect its fixed in 2.3

**Comment by dilipkrish** [comment]
@g00glen00b Could you confirm if this is fixed or broken in 2.2.3-SNAPSHOT. Planning to release 2.3 shortly and it would be good to close this story if its fixed in the snapshot, before the release

**Comment by rockytriton** [comment]
I think this is the same as #1077

**Comment by dilipkrish** [comment]
Fixed via #1078

**Comment by g00glen00b** [comment]
Sorry for the late response, it does indeed work.
