### ISSUE TITLE
Updating from Swagger1 to Swagger2

### ISSUE THREAD

**Issue by vch78** [springfox/springfox#954]
Hi,

   I am a newbie to swagger, I am trying to update existing Swagger version to version2 in my
   maven spring web app.
   
To do that I have done the following:

  1. Added following dependencies :
  
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.0.4-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.0.4-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.5.2</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.5.2</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.5.0</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-jersey2-jaxrs</artifactId>
			<version>1.5.0</version>
		</dependency>

 2. Updated references to com.wordnik references with io.swagger.

I am getting error in two places:

1. In SwagerConfig 
import com.mangofactory.swagger.configuration.SpringSwaggerConfig;
import com.mangofactory.swagger.plugin.EnableSwagger;
import com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin;

2. in my serializer where i have the following reference:

 com.wordnik.swagger.core.util.JsonSerializer.asJson(value).

 Please advice.

**Comment by dilipkrish** [comment]
First up I'm not sure why you're using a snapshot build of springfox let alone it's an outdated version (2.2.2 is the latest). 

Secondly that version is not compatible with 1.5.0 where the swagger core package names changed to `io.swagger.*`

**Comment by vch78** [comment]
Thanks for your quick response. Let me make the suggested changes and see if that makes a difference.

**Comment by vch78** [comment]
Ok. So I think I read it wrong. I thought Swagger2 is backward compatible. But reading your comment it seems like its not.
I searched a lot to find a spring maven project, but was not able to find it. I will really appreciate if you can point me to some where I can get a sample app.

**Comment by vch78** [comment]
I was able to create a maven version of petstore app. I am soon going to share it here once I will finish the task i am working on :). If someone is in need for the same please let me know.

**Comment by dilipkrish** [comment]
@vch78 thanks! please do share!
