### ISSUE TITLE
strange problem

### ISSUE THREAD

**Issue by rongzhu8888** [springfox/springfox#957]
When I tried to integrate swagger into springmvc, i found  something like this: "the @Api annotation does not work , it should be showed as the value attribute"
![image](https://cloud.githubusercontent.com/assets/10624066/9762583/2013b240-5737-11e5-823e-e4deb39e193e.png)

Controller:
<code>@Api(value = "Moment API",description = "apis for moment",position = 0)
@RestController
@RequestMapping(value = "/api/moment", produces = MediaType.APPLICATION_JSON_VALUE)
public class MomentAPI {

    @ApiOperation(value="get Moment List", notes = "Get moment list with page", response = APIModel1001.class, responseContainer = "List")
    @RequestMapping(value = "/list", method = RequestMethod.GET)
    @ResponseBody
    public List<APIModel1001> getMomentList(
            @ApiParam(value = "pageNum", required = true, defaultValue = "1")@RequestParam("pageNum")int pageNum,
            @ApiParam(value = "rows", required = true, defaultValue = "10")@RequestParam("rows")int rows,
            HttpServletRequest request, HttpServletResponse response) {
        List<APIModel1001> list = new ArrayList<APIModel1001>();

        return list;
    }</code>

My Swagger Config:
<code>
@Component
@Configuration
@EnableSwagger
public class MySwaggerConfig {

    private SpringSwaggerConfig springSwaggerConfig;

    @Autowired
    public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
        this.springSwaggerConfig = springSwaggerConfig;
    }

    @Bean
    public SwaggerSpringMvcPlugin customImplementation()
    {

        return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(apiInfo()).includePatterns("/api.*");
                // .genericModelSubstitutes(XXX.class)
                // .swaggerGroup("default")
    }

    private ApiInfo apiInfo()
    {
        ApiInfo apiInfo = new ApiInfo(
                "Test Swagger-SpringMVC ",
                "Test the integration of swagger and springMVC",
                null,
                null,
                null,
                null);
        return apiInfo;
    }
}
</code>

swagger-springmvc:1.0.2
Swagger Annotations: 1.3.11

**Comment by dilipkrish** [comment]
Unfortunately strange as it is, this is an old and unsupported version of this library. Please upgrade to 2.x

**Comment by rongzhu8888** [comment]
thanks!
