### ISSUE TITLE
Hiding injected Spring parameters from the API

### ISSUE THREAD

**Issue by s5b** [springfox/springfox#960]
The controllers in my application are using Spring's dependency injection to include a `BindingResult` object, that I'm naming `errors`, in the parameters of my controller endpoint method. The problem is that the generated API specification thinks that `errors` is a parameter for the API and is included in the specification when viewed in, say, Swagger UI.

I want to be able to annotate (or something) this kind of injected parameter to exclude it from the API. Is there a way to exclude this kind of method parameter from the documentation.

I've had a hunt around the Internet for examples, and I've even read the source code for Springfox, but I can't seem to find a way to exclude this kind of parameter. Am I missing something here?

Thanks for any direction you can provide.

**Comment by s5b** [comment]
Okay. To help other _dummies_ like me, maybe, you can prefix parameters that you don't want included in the documentation with an `@ApiIgnore` annotation, and that parameter will not be included in the generated specification.

For example:
```public ResponseEntity<ContentGroupAndPresenceResponse> createContentGroup(@RequestBody @Valid CreateContentGroupRequest request,
            @ApiIgnore final Errors errors,
            @ApiIgnore final UriComponentsBuilder uriComponentsBuilder) { … }```

Problem solved, I reckon.

**Comment by ccschneidr** [comment]
Still, these parameters should not have been picked up, in the first place. They are not annotated with @RequestParam but e.g. with @AuthenticationPrincipal. It's not nice to annotate all of them with @ApiIgnore, is it?

**Comment by dilipkrish** [comment]
No its not. Are you using version 2.3.0?

**Comment by ccschneidr** [comment]
Well, 2.7.0 actually. Or does this refer to some other thing?
`      <dependency>
         <groupId>io.springfox</groupId>
         <artifactId>springfox-data-rest</artifactId>
         <version>2.7.0</version>
      </dependency>`

**Comment by d4rw1n1s7** [comment]
Seems that the problem with `@AuthenticationPrincipal` annotation is still there. I'm using the latest version 2.9.2, referring the `io.springfox:springfox-swagger2:2.9.2` and `io.springfox:springfox-swagger-ui:2.9.2` packages. We all will be happy if it will be possible to rid of the `@ApiIgnore` annotation (btw, @s5b thank you for the posted workaround). In any case, thank you very much guys for your work, SpringFox is an incredibly powerful tool =)

**Comment by dilipkrish** [comment]
You could also globally ignore types in your docket, if you don't use the model anywhere other than in the implementations itself

**Comment by fzyzcjy** [comment]
A quick gist for those who want to *globally* ignore types:

```
    @Bean
    public Docket createRestApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .ignoredParameterTypes(UserAuthentication.class) // <--- THIS!!!
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.hello.world"))
                .paths(PathSelectors.any())
                .build();
    }
```

**Comment by destan** [comment]
@fzyzcjy 's solution actually works but may causes problems if `UserAuthentication` type is actually used in another endpoint (i.e registration). Hence following is a better approach and working the same:

```java
.ignoredParameterTypes(AuthenticationPrincipal.class)
```
