### ISSUE TITLE
Is there a way around the lowercasing of the @api(value = "This will be Lowercased" ...) annotation?

### ISSUE THREAD

**Issue by Luthien-in-edhil** [springfox/springfox#962]
I'm using the @Api annotation on the class level to 1) include it in the Swagger output and 2) provide a user-friendly description instead of the default controller name. 

However, I noticed that the string assigned to the value = "User Friendly Controller Name" is forced to lowercase (& whitespaces converted to underscores) in the Swagger Json output and, subsequently, also in the Swagger UI header for the controller in question. e.g.:

`@Api(value = "Providers and Datasets", description = "Information about our data providers (...)")`

will result in (JSON)

`tags": [`
`    {`
`        "name": "providers_and_datasets",`
`        "description": "Information about our data providers (...)"`
`    },`

and in the Swagger UI:
#### providers_and_datasets : Information about our data providers (...)

Of course we could set **value** to a single whitespace (leaving it empty or omitting it causes it to default to the controller name) and use the **description** field only, but that leaves an awkward dangling colon in the UI:

#### : Information about our data providers (...)

After having read through all the documentation that I could find on Springfox and core Swagger I haven't found a straightforward way to achieve what we want: to provide a descriptive header to each block in the Swagger UI with Sentence case and white spaces left intact. 
Am I maybe overlooking something?
Thanks!

Using Springfox 2.2.2 Swagger, Java 7, Spring 2.2.0  (no JAX-RS),
Project: https://github.com/europeana/api2/ (develop)

**Comment by dilipkrish** [comment]
This should be fixed in the next version.

**Comment by Luthien-in-edhil** [comment]
great, thanks!
