### ISSUE TITLE
SpringExpressionLanguage Parameter should not be mapped to Swagger Spec

### ISSUE THREAD

**Issue by GitVhaos** [springfox/springfox#972]
Using spring expression language in methode siganture, parameters will be exposed to springfox swagger api, which are not part of the public API.

Example:

public HttpEntity<?> createRessource(
        @RequestBody final Ressource ressource,
        @Value("#{request.requestURL}") final StringBuffer requestURL ) {
...
}

The Parameter "requestURL" is only for internal framework use but gets Part of the Swagger generated Public API.

Is it possible to ignore every kind of spring expression language use in methode signature?
I think there`s no case where u want to publish this in ur API....

**Comment by dilipkrish** [comment]
There isn't a good way to do that unfortunately... May be if you're using StringBuffers solely for this purpose you could add an ignorable type `StringBuffer`

**Comment by GitVhaos** [comment]
I know, but ignoring StringBuffers seems a kind of an hack ^^
I think by checking for "@Value" annotated Parameters should fix it. What do u mean?

**Comment by dilipkrish** [comment]
@GitVhaos the alternative is to annotate the parameter with `@ApiParam(hidden=true)`
