### ISSUE TITLE
2.2.2 download application/zip

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#975]
Here is what I am trying to achieve:

    @RequestMapping(value = "/reports/{reportId}", method = RequestMethod.GET, produces = "application/zip")
    public ResponseEntity<byte[]> download(@PathVariable UUID reportId) {

But springfox does not download the file, it just shows the bytes in response page. This is pretty awkward. Is there something stupid I am doing may be?

**Comment by dilipkrish** [comment]
@wind57 May don't use swagger-ui for doing downloads?

**Comment by wind57** [comment]
:) that'a a funny piece of advise. How are users of the app going to know that there is a download then? this sounds like a bug to me ;)
