### ISSUE TITLE
RequestParameters of type enum are not recognized (Datatype = undefined)

### ISSUE THREAD

**Issue by GitVhaos** [springfox/springfox#976]
**The REST API Operation**

RequestMapping(value = "/someRessource", method = RequestMethod.GET)
public ResponseEntity<SomeRessource> serachRessource(@RequestParam(value = "someEnum") SomeEnum someEnum)

**will be rendered in Swagger-UI as**

"DataType = undefined"

**Generated JSON Spec:**

{"name":"someEnum","in":"query","description":"someEnum","required":true,"type":"ref"}

-----------------------

I would at least expect that enum will named and is linked to a definition.

Otherwise my API consumer are unable to recognize possible parameter values!

**Comment by dilipkrish** [comment]
@GitVhaos what version are u using? I verified it using [this branch](https://github.com/springfox/springfox-demos/tree/chore/976/demonstrate-enum-param). see [CategoryController](https://github.com/springfox/springfox-demos/blob/chore/976/demonstrate-enum-param/boot-swagger/src/main/java/springfoxdemo/boot/swagger/web/CategoryController.java)

```bash
./gradlew clean build :boot-swagger:bootRun
```
open `http://localhost:8080/springfox/swagger-ui.html#!/category-controller/searchUsingGET`

**Comment by monowai** [comment]
Ooh - I nearly thought this was an issue until i found the "model" link in swagger-ui 

![image](https://cloud.githubusercontent.com/assets/2443042/10414078/bee3d21a-701e-11e5-846c-42a43b15f822.png)

**Comment by GitVhaos** [comment]
@dilipkrish: In your test case "CategoryController" u r returning "someEnum.name()" of type string.
What I meant was that I return "someEnum" of type enum. I this case I would expect to see a datatype definition with all possible values for this API parameter.

**Comment by GitVhaos** [comment]
@dilipkrish : The issue is not solved and the last question was not answered, why is the issue marked closed?

**Comment by dilipkrish** [comment]
I thought I understood your question 

> {"name":"someEnum","in":"query","description":"someEnum","required":true,"type":"ref"}

the *query* implied the input parameter. Thats why its closed as not-reproducible. What happens when you return `ResponseEntity<SomeEnum>` instead of just `ResponseEntity`

**Comment by GitVhaos** [comment]
@dilipkrish : Ok, you are right! What I wrote in my previous comment is $%§!... ^^ Yes I was intentionally talking about enum aus "input-parameter" not response-entity... And your example is also perfectly fine... I have to check it in my app and will return with further error details...
