### ISSUE TITLE
[springfox][swagger-ui] change the default ui path for swagger ui for spring-mvc 

### ISSUE THREAD

**Issue by tckb** [springfox/springfox#977]
Hi, for spring-mvc the default swagger-ui path is /swagger-ui.html. Any to change it to different path?
the generated code comes with a config file SwaggerUiConfiguration. Anyway to change it here?

rg,
Chandra

**Comment by dilipkrish** [comment]
@tckb Unfortunately there isn't a way to do that.

**Comment by tckb** [comment]
@dilipkrish  I made a workaround by adding a custom swagger-ui and creating a custom viewcontroller for it :+1:  
eg:
```
 /api-console -> /swagger-ui-mod.html

**Comment by dilipkrish** [comment]
@tckb awesome. Just make sure you remove the springfox-swagger-ui dependency if you don't need it

**Comment by karthikchalla5** [comment]
Hi @tckb 

can you elaborate on how you changed the default /swagger-ui.html to custom path. I am completely new to this.

**Comment by tckb** [comment]
@karthikchalla5  create a local copy of swagger-ui and edit it as you please.  Then make redirect to the custom swagger-ui.html

**Comment by raderio** [comment]
```
@Override
public void addViewControllers(ViewControllerRegistry registry) {
    registry.addViewController("/custom-path").setViewName("forward:/documentation-folder/index.html");
}
```
