### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by maksimu** [springfox/springfox#979]
I'm using SpringFox (Swagger) to document my REST APIs. One of the nice features in Swagger is to show example model and the data type format.

Now, I configured my APIs to produce and consume dates in milliseconds but when I'm looking at the sample JSON model the date format is following: "2015-09-21T00:51:32.617Z". Is it possible to tell SpringFox (Swagger) how to format the date properly?

**Comment by dilipkrish** [comment]
@maksimu it is possible to annotate the date description or an example. Outside of that there are no facilities in the spec to render a format.

**Comment by dougbreaux** [comment]
For anyone else who finds this, this is what I've found to do, so far (for a slightly custom format our partner requires):
```java
    @ApiModelProperty(example = "2019-09-20 10:22:36.584")
```
