### ISSUE TITLE
Spring boot PagingAndSortingRepository problem on documentation

### ISSUE THREAD

**Issue by fritzZz** [springfox/springfox#982]
I've configured a basic springboot application (mvn archetype) that exposes rest crud API throught the PagingAndSortingRepository interface.
I've added the springfox support like your documentation description but when I show the swagger ui I can see different endpoint exposed from my springboot configuration like : endpoint-mvc adapter,...
and the following generic endpoint : 
repository-controller
repository-entity-controller
repository-property-reference-controller
repository-schema-controller
repository-search-controller

I want to know how is possible to expose the concrete repository api definition based on PagingAndSortingRepository interface.

I expect to show my repositories exposed correctly throught spring boot.

I paste the my Docket generation : 
```
@Bean
    public Docket petApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                 .paths(PathSelectors.any())
                //.paths(paths())
                .build()

                .pathMapping("/")
                //.directModelSubstitute(LocalDate.class, String.class)
                .genericModelSubstitutes(ResponseEntity.class)
                .alternateTypeRules(
                        newRule(typeResolver.resolve(DeferredResult.class,
                                        typeResolver.resolve(ResponseEntity.class, WildcardType.class)),
                                typeResolver.resolve(WildcardType.class)))
                .useDefaultResponseMessages(false)
                .globalResponseMessage(RequestMethod.GET,
                        newArrayList(new ResponseMessageBuilder()
                                .code(500)
                                .message("500 message")
                                .responseModel(new ModelRef("Error"))
                                .build()))
                .securitySchemes(newArrayList(apiKey()))
                .securityContexts(newArrayList(securityContext()))
                .enableUrlTemplating(true)
                ;
    } 
```
My spring configuration is declared in this way : 
```
@SpringBootApplication
@EnableSwagger2
public class Application extends SpringBootServletInitializer {
```

**Comment by dilipkrish** [comment]
@fritzZz this is really begging to be done... there is already a story to do that #699, unfortunately I don't have the bandwidth to work on it. Any chance I could ask for a PR?

**Comment by gigenthomas** [comment]
I am interested in this as well. Same issue - using CrudRepository and unable to generate api docs using swagger
