### ISSUE TITLE
springfox-swagger-ui cannot find swagger-resources when run outside of spring boot

### ISSUE THREAD

**Issue by jmandawg** [springfox/springfox#983]
Hi,

I'm running in springfox v2.2.2 inside JBoss.  My dispatch serverlet looks like this:

              <servlet>
			<servlet-name>RestServlet</servlet-name>
			<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
			<init-param>
				<param-name>contextConfigLocation</param-name>
				<param-value></param-value>
			</init-param>
			<load-on-startup>1</load-on-startup>
		</servlet>
		
		<servlet-mapping>
			<servlet-name>RestServlet</servlet-name>
				<url-pattern>/restservices/*</url-pattern>
		</servlet-mapping>

And it works fine, and i can get to the swagger-resources from here:
http://localhost:8080/rootContext/restservices/swagger-resources

And i can view the api from here:
http://localhost:8080/rootContext/restservices/v2/api-docs

And Swagger-UI is accessable from here: 
http://localhost:8080/rootContext/swagger-ui.html

The problem is when i load the http://localhost:8080/rootContext/swagger-ui.html page it is trying to access the swagger-resources from here:  
http://localhost:8080/rootContext/swagger-resources

And they are not available.  How can i fix this so that the swagger-ui.html either:
1. looks in the right location (http://localhost:8080/rootContext/restservices/swagger-resources)
or
2. Swagger-ui.html is available at: http://localhost:8080/rootContext/restservices/swagger-ui.html

Thanks.

**Comment by dilipkrish** [comment]
@jmandawg Hmmm the swagger-ui and swagger resource working together is predicated not the fact that they have the same context root. Unfortunately the way they are registered is different (resources vs. services) Wondering if you can create a servlet just for the swagger-resources to be at the same context path as the swagger-ui

**Comment by jmandawg** [comment]
I'll give it a try, can you give any hints on how to do this?  I searched around and can't find anything.

**Comment by dilipkrish** [comment]
Not sure myself, may be something [like this](http://www.scriptscoop.com/t/3f0696623102/how-to-create-multiple-dispatcher-servlets-using-spring-mvc-java-confi.html)?

**Comment by jmandawg** [comment]
Thanks for the tips, I was able to get it working by modifying the dispatcherServlet to listen on /* to this to let the swagger-ui.html bypass the dispatcherServlet.

<servlet>
			<servlet-name>RestServlet</servlet-name>
			<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
			<init-param>
				<param-name>contextConfigLocation</param-name>
				<param-value></param-value>
			</init-param>
			<load-on-startup>1</load-on-startup>
		</servlet>
		
		<servlet-mapping>
			<servlet-name>default</servlet-name>
				<url-pattern>/swagger-ui.html</url-pattern>
		</servlet-mapping>
		
		<servlet-mapping>
			<servlet-name>RestServlet</servlet-name>
				<url-pattern>/*</url-pattern>
		</servlet-mapping>

Also had to let the webjar through the dispatcher servlet:

<mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/"/>

Kinda tricky to get working, but it works.  Perhaps there is a better way to remap swagger-ui.html or let it pass through the dispatcherServlet.

Thanks again.

**Comment by dilipkrish** [comment]
:+1:

**Comment by jmandawg** [comment]
I figured out that adding `<mvc:default-servlet-handler/>` then i don't have to add the:
<servlet-mapping>
        <servlet-name>default</servlet-name>
            <url-pattern>/swagger-ui.html</url-pattern>
    </servlet-mapping>

**Comment by dilipkrish** [comment]
:+1:

**Comment by ankit2711** [comment]
@dilipkrish I have a similar issue with a spring-mvc and springfox integration. I can access 
http://localhost:8080/<context>/v2/api-docs and it shows the big JSON with all my REST controllers scanned. 
But when accessing http://localhost:8080/<context>/swagger-ui.html I get a 404 error. 

I already have <mvc:default-servlet-handler/> added in my servlet.xml file. 

Below my configuration 
servlet.xml
<mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/" />
<mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/" />
<mvc:default-servlet-handler />
<context:component-scan base-package="com.hi.cdi.v1.controller" />
<context:component-scan base-package="com.hi.cdi.hm.controller" />

SwaggerConfig.java 
@EnableSwagger2
public class SwaggerConfig {
    @Bean
    public Docket customImplementation() {
        return new Docket(DocumentationType.SWAGGER_2);
    }
}

applicationContext.xml has the swagger bean definition
<bean name="/swaggerConfig" class="com.hi.cdi.swagger.SwaggerConfig" />

NOTE: The project is not using Spring boot. 

Would appreciate your help, already struggled for more than a day to get this working.

**Comment by davidluckystar** [comment]
What if I already have a DispatcherServlet, registered under another URL pattern like /services/* and I can't change this (because of my application architecture constraints)? How do I use swagger-ui in this case?
My spring controller service is located under:
http://localhost:8080/services/my-service
so my swagger docs are under
http://localhost:8080/services/v2/api-docs
and swagger-ui is installed using webjars under
http://localhost:8080/swagger-ui
because / is the context root of my application
So swagger-ui expects to see 
http://localhost:8080/v2/api-docs
which are not there
--
The solution for me in this case is to change the swagger-ui query url to a custom one, because it cannot rely that swagger docs will be always under the same URL relatively. But how can I do that? Or maybe there is another solution?

**Comment by shollander** [comment]
@davidluckystar I had the same issue and I was able to get it working by mapping swagger-ui.html to the servlet path like this:

```
@Configuration
@EnableWebMvc
public class WebConfig extends WebMvcConfigurerAdapter {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("**/swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/webjars/"); 
        registry.addResourceHandler("**/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
  }
}
```

Then you should be able to access swagger at http://localhost:8080/services/swagger-ui.html

**Comment by davidluckystar** [comment]
@shollander Thanks a lot for your reply! 
I will try it later - didn't know you can use double asterisk as a prefix **/swagger-ui.html in the url mapping. I guess the same you can do in XML if you have multiple DispatcherServlet's.

**Comment by davidluckystar** [comment]
Dear @shollander your solution is not working, here is the correct one:
`registry.addResourceHandler("**/**").addResourceLocations("classpath:/META-INF/resources/");`

**Comment by rsmogura** [comment]
For those who use XML based configuration :)
`<mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/"/>
<mvc:resources mapping="/swagger-ui.html" location="classpath:/META-INF/resources/swagger-ui.html"/>`

**Comment by mandarnamdas** [comment]
@dilipkrish In our project our Dispatcher servlet maps to "*.do" with which Swagger does not working. But the moment I change it to "/*" it does work. We have a requirement to keep servlet mapping to "*.do". Can you please suggest the way forward or send me example link where this kind of situation is handled. Thanks.

**Comment by dilipkrish** [comment]
@mandarnamdas Not really sure how to do that, somehow you need to map the swagger resources differently.

**Comment by sumitit08** [comment]
@dilipkrish ... I am using springfox-swagger-ui with Spring boot and i am trying to do Api-Key authorization , i have gone through all the issues related to springfox-swagger-ui but still i am unable to find the solution.What changes i have made to achieve this is:

I have made all these changes to implement Api-Key security.

In SwaggerConfig class -
---------------------------------
@Bean
    public Docket parkingReservationServiceApi() {
        return new Docket(DocumentationType.SWAGGER_2).select()
                .apis(RequestHandlerSelectors.basePackage(REST_PACKAGE_PATH))
                .paths(PathSelectors.regex("/c2creservation.*"))
                .build().pathMapping("/")
                .directModelSubstitute(LocalDate.class, String.class)
                .genericModelSubstitutes(ResponseEntity.class)
                .alternateTypeRules(newRule(typeResolver.resolve(DeferredResult.class, typeResolver.resolve(ResponseEntity.class, WildcardType.class)), typeResolver.resolve(WildcardType.class)))
                .useDefaultResponseMessages(true)
                .globalResponseMessage(RequestMethod.GET,
                    newArrayList(new ResponseMessageBuilder()
                        .code(500)
                        .message("500 message")
                        .responseModel(new ModelRef("Error"))
                        .build()))
                .apiInfo(getApiInfo())
                .securitySchemes(newArrayList(apiKey()))
                /*.securityContexts(newArrayList(securityContext()))*/
                .protocols(protocols())
				.securitySchemes(securitySchemes())
				.securityContexts(securityContexts());
    }
    
    private ApiKey apiKey() {
        return new ApiKey("abcdef12345", "api_key", "header");
    }
    
/*    private SecurityContext securityContext() {
        return SecurityContext.builder().securityReferences(defaultAuth())
                .forPaths(PathSelectors.regex("/c2creservation.*")).build();
    }*/

    List<SecurityReference> defaultAuth() {
       /* AuthorizationScope authorizationScope = new AuthorizationScope(
                "global", "accessEverything");*/
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[0];
//        authorizationScopes[0] = authorizationScope;
        return newArrayList(new SecurityReference("abcdef12345", authorizationScopes));
    }


	private List<SecurityContext> securityContexts() {
    	List<SecurityContext> securityContexts   = Arrays.asList(SecurityContext.builder().forPaths(PathSelectors.regex("/.*")).securityReferences(securityReferences()).build());
		return securityContexts;
	}

	private List<? extends SecurityScheme> securitySchemes() {
		 List<SecurityScheme> authorizationTypes = Arrays.asList(new ApiKey("api_key", "abcdef12345", "header"));
	      return authorizationTypes;
	}

	private Set<String> protocols() {
		Set<String> protocols = new HashSet<>();
		protocols.add("http");
		protocols.add("https");
		return protocols;
	}

IN Controller class:
---------------------------
@RestController
@Validated
@Api(value = "Search Parking Spaces", description = "Endpint for C2C Parking Reservation")
@SwaggerDefinition(securityDefinition = @SecurityDefinition(
		apiKeyAuthDefintions = {
				@ApiKeyAuthDefinition(key = "api_key", name = "abcdef12345", in = ApiKeyLocation.HEADER) 
		}
	)
)
@RequestMapping(value = "/v1")
public class ABCController extends BaseController
{
}

In swagger-ui.html
-----------------

           function addApiKeyAuthorization() {
                var key = encodeURIComponent($('#input_apiKey')[0].value);
                if (key && key.trim() != "") {
                    var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", key, "header");
                    alert("apiKeyAuth:::"+apiKeyAuth);
                    alert("key:::"+key);
                    window.swaggerUi.api.clientAuthorizations.add(key, apiKeyAuth);
                    alert("added key " + key);
                }
            }

            $('#input_apiKey').change(addApiKeyAuthorization);

pom.xml

<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>1.5.15</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.7.0</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.7.0</version>
		</dependency>


It would be appreciable if you will help me on this.

Thanks,
Sumit

**Comment by dilipkrish** [comment]
What is the problem you're seeing @sumitit08

**Comment by gitforpushpak** [comment]
Hi @jmandawg / @dilipkrish , I am also facing same issue. My webservices are divided into two v1 and v2 versions. So there are two different servlets. I am implementing swagger for v2. From your comment I understand that you removed the "restservices" from <url-pattern>/restservices/*</url-pattern> and added 
   <servlet-mapping>
        <servlet-name>default</servlet-name>
            <url-pattern>/swagger-ui.html</url-pattern>
    </servlet-mapping>

are you able to access http://localhost:8080/rootContext/restservices/swagger-ui.html ?
In my case I can not remove "restservices" from mapping.
Please suggest.

**Comment by dilipkrish** [comment]
@gitforpushpak this is an old issue. The current version of the library is 2.7.0. So its likely older issues are no longer relevant or have been fixed if the issue is closed.

**Comment by tiddman** [comment]
I am having a variation of this issue using swagger 2.7.0.  We have a spring boot application and when running locally with spring boot we can hit http://localhost:8080/swagger-ui.html and it works fine, but when deployed to Tomcat we get the "Unable to infer base URL" dialogue with that URL.  The access log in Tomcat:

0:0:0:0:0:0:0:1 - - [18/Jan/2018:11:08:06 -0500] "GET /swagger-ui.html HTTP/1.1" 200 3246
0:0:0:0:0:0:0:1 - - [18/Jan/2018:11:08:06 -0500] "GET /swagger-resources/configuration/ui HTTP/1.1" 404 149
0:0:0:0:0:0:0:1 - - [18/Jan/2018:11:08:18 -0500] "GET /null/swagger-resources/configuration/ui HTTP/1.1" 404 154

In my case it finds swagger-ui.html but it can't find /swagger-resources (404), then I'm guessing tries again with a different context root which is not defined (/null).

I've tried the resource mapping changes recommended in this thread by @shollander and @davidluckystar but they have no effect.  I see other threads about this issue too but none with this issue.  Our dependencies:

    compile('io.springfox:springfox-swagger2:2.7.0')
    compile('io.springfox:springfox-swagger-ui:2.7.0')

Any tips or info very welcome this is an important blocker for us.

**Comment by dilipkrish** [comment]
Thanks for the detailed explanation. I think it has to do with how the classloader loads the application context.

**Comment by iver3on** [comment]
local run no problem,but when i deployed on k8s . not working.
eg：
java.io.IOException: Unable to open root Jar file 'war:file:/app.jar*/BOOT-INF/lib/springfox-swagger-ui-2.6.1.jar'

**Comment by dilipkrish** [comment]
@iver3on I don't know how k8s works, sorry.

**Comment by oeresundsgruppen** [comment]
springfox-swagger is truely so buggy that it needs a honest review and rewrite. tons of google-search shows problems.

**Comment by dilipkrish** [comment]
@oeresundsgruppen if you're available to review and rewrite, this project could certainly use help.

**Comment by oeresundsgruppen** [comment]
Will gladly inform you of the findings once I get it work, have spend countless hours, and will start to look into your code...

**Comment by dilipkrish** [comment]
Thanks great! Thanks for helping out @oeresundsgruppen

**Comment by oeresundsgruppen** [comment]
https://github.com/oeresundsgruppen/swaggerTest - now works in tomcat. Does springfox support old fashion servlets using @Api and @ApiOperation annotations ?

**Comment by oeresundsgruppen** [comment]
Got it working for old servlets with the appropriate annotations

**Comment by geektcp** [comment]
I found the really reason, because of @ComponentScan, and u must to annotate it , for example: 
//@ComponentScan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})

and then , it will be ok,  u can open the swagger-tui.html and /swagger-resources/configuration/ui

**Comment by geektcp** [comment]
swagger启动后，老是报错下面的url无法打开swagger-ui.html，
提示内部url无法打开swagger-resources/configuration/ui

原因是：
启用了组件扫描导致：@ComponentScan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})
这个问题真是费解。

解决办法：注释掉扫描注解即可：
//@componentscan(basePackages = {"com.haizhi.dao","com.haizhi.controll","com.haizhi.service"})

**Comment by ljrjain** [comment]
Version 2.9.2 is not working on AWS ALB, it has same issue as mentioned by 
it is still adding adding extra null...
/api/null/swagger-resources/configuration/ui is being accessed. not sure why null is being added.

At local it works OK though with localhost.

**Comment by satishpatro44** [comment]
In my case, a swagger was opened in browser, somehow it was calling from that browser's opened swagger

I changed port & started it worked
So, remove all swagger url opened in browser
Not may be the case fot others

**Comment by ketan-barapatre-sarvaha** [comment]
Just sharing my story, I was running into the same problem, during my attempt to implement Swagger UI, I stick to the official documentation to implement for non spring boot project, when I tried to add 

 <servlet-mapping>
    <servlet-name>default</servlet-name>
        <url-pattern>/swagger-ui.html</url-pattern>
  </servlet-mapping>

It did not work for me and I have a Java config project so no option to add below XML configuration 

<mvc:default-servlet-handler/>

So, instead of <mvc:default-servlet-handler/> I added 

public class CustomMvcConfiguration extends WebMvcConfigurerAdapter {

    _@Override
    public void configureDefaultServletHandling(final DefaultServletHandlerConfigurer configurer) {
        configurer.enable();
    }_
}

and it worked like charm.
