### ISSUE TITLE
Are query parameter templates for "path" entries valid?

### ISSUE THREAD

**Issue by cal101** [springfox/springfox#986]
Here is a simplified use case using swagger annotations 1.5.3 with springfox 2.2.2:

```
@ApiOperation(value = "Echos value", notes = "Echos value", tags="Testing")
   	@RequestMapping(method = RequestMethod.GET,
            value = "/hello",
   			produces = { APPLICATION_HAL_JSON, MediaType.APPLICATION_JSON_VALUE }
       )
    String getXY(@ApiParam(name = "message", required = true)
                 @RequestParam(name = "page", required = true) String message) {
        return "Hello " + message;
    }
```

That generates 
```
"/api/hello{?message}": {

    "get": 
```

This query params syntax "{?message}" is not supported by swagger ui 2.2.2.
From reading the swagger spec I got the impression, that only "path variables" are allowed, not "query param variables".
IMHO the path should read "/api/hello" in this case.

Opinions?

Cal

**Comment by dilipkrish** [comment]
You're most likely using a feature were incubating. I think it should revert to regular behavior if you set in your docket

```Java
      .enableUrlTemplating(false);
```

**Comment by cal101** [comment]
Just figured that seconds ago, you are absolutely right.
For whatever copy&paste reason I had ".enableUrlTemplating(true)" in the docket.
Thanks for the fast response!

**Comment by SenZh** [comment]
I had the same question.thanks!
