### ISSUE TITLE
Parameter wrapper for a List of objects

### ISSUE THREAD

**Issue by jmarinco** [springfox/springfox#988]
Hello.

I need to send a list of object parameters, in Spring MVC I used to do it using an object wrapper that contain the List of objects and I send the parameters using the index of the array like __"object[0].attrOne=value&object[0].attrTwo=value"__

Here is the __Object Wrapper__ and the __Object__.

```java
       public class OrderChargeAPI {
		private double charge;
		private List<Long> medications;
		public List<Long> getMedications() {
			return medications;
		}
		public void setMedications(List<Long> medications) {
			this.medications = medications;
		}
		public double getCharge() {
			return charge;
		}
		public void setCharge(double charge) {
			this.charge = charge;
		}
	}
	
	public class OrderChargeAPIWrapper {
		private List<OrderChargeAPI> orderCharges;

		public List<OrderChargeAPI> getOrderCharges() {
			return orderCharges;
		}

		public void setOrderCharges(List<OrderChargeAPI> orderCharges) {
			this.orderCharges = orderCharges;
		}

		public OrderChargeAPIWrapper() {
			super();
			this.orderCharges = new ArrayList<OrderChargeAPI>();
		}
	}
```

Here is the __Controller__ method signature and swagger annotations.

```java
	@RequestMapping(value = "/create", method = RequestMethod.POST)
	@ApiOperation(value = "New user order", response = OrderAPIResponse.class)
	@ApiResponses({@ApiResponse(code = 400, message = "Error"), @ApiResponse(code = 401, message = "Invalid credentials")})
	@ApiImplicitParams({
		@ApiImplicitParam(name = "token", value = "User token", required = true, dataType = "string", paramType = "header"),
	  })
	@Secure
    public ResponseEntity<?> create(OrderChargeAPIWrapper orderCharges) {
         return new ResponseEntity<>(new BaseResponse(), HttpStatus.OK);
    }
```

This is how swagger shows the input fields.

![swagger image]
(http://content.screencast.com/users/jmarin/folders/Jing/media/fc1c9769-cd9b-4de7-b486-bde7afac3f47/00000525.png)

The __Controller__ is working with this parameters using __CURL__ to call the end-point.

```bash
curl -X POST --header "token: TOKEN" -d "orderCharges[0].charge=1&orderCharges[0].medications=2&orderCharges[0].medications=3&orderCharges[1].charge=2&orderCharges[1].medications=5" "http://END-POINT-URL/create"
```

But if I use swagger the parameters are empty.

__I have tried with no luck__:

* Changed the parameter type for a `List<OrderChargeAPI>` and annotate it using `@ApiParam` with `allowMultiple=true`
* Annotate the method using `@ApiImplicitParam` changing the `paramType` to `"form"` and `"query"` 

The thing is that the parameter name swagger is sending does not have the `[index]` on it.

Thanks.

**Comment by dilipkrish** [comment]
@jmarinco Let me start by prefacing it with the fact that swagger-ui will not support you requirement, especially if the orderCharges collection is an unbounded list.

I'm not sure why you'd not want to use json to serialize the the `OrderChargeAPIWrapper`
Having said that, I would try annotating it with `@ModelAttribute` and see if that makes a difference.
