### ISSUE TITLE
Error with Json class

### ISSUE THREAD

**Issue by sandeepkk2005** [springfox/springfox#989]
I am using springfox 2.2.2 APIs downloaded from https://bintray.com/springfox/maven-repo/springfox/view. I am getting following error while trying to access "/v2/api-docs" resource. Can someone help me please.

Could not instantiate JAXBContext for class [class springfox.documentation.spring.web.json.Json]: 

Exception Description: The class springfox.documentation.spring.web.json.Json requires a zero argument constructor or a specified factory method.  Note that non-static inner classes do not have zero argument constructors and are not supported.; nested exception is javax.xml.bind.JAXBException: 

Exception Description: The class springfox.documentation.spring.web.json.Json requires a zero argument constructor or a specified factory method.  Note that non-static inner classes do not have zero argument constructors and are not supported.
 - with linked exception:
[Exception [EclipseLink-50001] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.JAXBException

Exception Description: The class springfox.documentation.spring.web.json.Json requires a zero argument constructor or a specified factory method.  Note that non-static inner classes do not have zero argument constructors and are not supported.]

**Comment by dilipkrish** [comment]
Not sure what your setup looks like, but it seems like it shouldn't be trying and use JAXB. May be you're missing json message converters?

**Comment by sandeepkk2005** [comment]
Hi Dilip, thanks for the quick response. I havent configured any JSON message converters, is it mandatory for using Springfox. I am using Spring REST APIs.

**Comment by dilipkrish** [comment]
Are you using only xml?

**Comment by sandeepkk2005** [comment]
I am using annotations to create controllers. Springfox was enabled using @EnableSwagger2 and @Configuration

Code used for configuring the Docket
        @Bean
	public Docket customDocket()
	{
		final Docket docket = new Docket(DocumentationType.SWAGGER_2);
		docket.useDefaultResponseMessages(false);
		docket.forCodeGeneration(false);
		return docket;
	}
