### ISSUE TITLE
Nicknames

### ISSUE THREAD

**Issue by ericbriere** [springfox/springfox#990]
Hi,

I'm unclear if the following issue will get fixed or not. Can I get a status? We are currently using the version 2.0 and do code generation for our APIs. We were relying on Nicknames in order to get nice APIs method calls. The fact that Nicknames are not working anymore prevents us to upgrade to the latest release of SpringFox.

https://github.com/springfox/springfox/issues/880.

Thanks.

**Comment by dilipkrish** [comment]
@ericbriere as a library we want to guarantee that the generated swagger definitions will produce valid documents. [Per spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operation-object) the operation id needs to be unique. Also code generation using the rendered swagger document, is not really in scope.

**Comment by rajeshkamal** [comment]
Isn't there any other way for users who want override the default behavior of auto-generated method names? That will be really useful for us @ericbriere @cbornet

**Comment by dilipkrish** [comment]
In 2.3 it is supported using nickNames like you would expect it. However if you have the method with the same name defined elsewhere it will append numbers to disambiguate them. for e.g. if you have a method with a nickname defined as findPet, it will generate `findPet` as long as there are no duplicates. The moment if finds duplicates it will start adding `findPet_1`, `findPet_2` to subsequent methods.

If nick is not defined, it will revert to using the names using the format `<method>Using<HttpMethod>`

**Comment by cbornet** [comment]
:+1:

**Comment by rajeshkamal** [comment]
Just curious - can you clarify me if this is how it works.

Pet resource or PetController - has findPet(). If it has one more nickname with findPet then it would add findPet_1 and findPet_2.

It shouldn't do anything if it has a findPet() in some other controller ex: SomeController or some resource ?

**Comment by ericbriere** [comment]
Good,

?

many thanks.

________________________________
