### ISSUE TITLE
Extra closing curly brace on endpoints defined with a regex containing a quantifier

### ISSUE THREAD

**Issue by erikthered** [springfox/springfox#991]
When using Springfox with endpoints containing URI path parameters with a defined regex containing a quantifier, an extra closing curly brace is inserted at the end of the URI parameter. The approach being used is described here: http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-ann-requestmapping-uri-templates-regex. 

For example, with the following annotation:

`@RequestMapping(value = "/scored/{path1}/{id:\\d{3}}/{code:\\d{5}}", produces = APPLICATION_JSON_VALUE, method = RequestMethod.GET)`

This is the generated path in the API spec:

`/scored/{path1}/{id}}/{code}}`

This also causes the Swagger UI to function improperly when testing out endpoints.

My guess is this is related to the curly braces on the quantifier that we're using in the regex.

If this is actually an issue with Swagger, please let me know and I can raise the defect with them.

**Comment by dilipkrish** [comment]
This is a bug! Thanks for pointing it out with an example

**Comment by erikthered** [comment]
Looks like the problem is [here](https://github.com/erikthered/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/Paths.java#L87). 

Things get very messy when there are multiple quantifiers in the regex portion of the RequestMapping pattern.

**Comment by dilipkrish** [comment]
@erikthered  I thought this was a closed book until u pointed it out :) Pretty sure it will pop right back when there is a more complex or different expression either of us did not thing about. Any ideas?

**Comment by erikthered** [comment]
I think I might have come up with a working solution, I'll open up a PR once I test it.

**Comment by erikthered** [comment]
It seems like my fix causes an unintended side-effect :cry:. API names defined in the annotations seem to be ignored now. Instead the class name is being expanded so that something like `MyFirstController` becomes `my-first-controller`.

Any ideas where I can start looking to see why this is happening?

**Comment by erikthered** [comment]
A little more detail: this is only happening when we use the `@Api` annotation with the `value` field defined. If we use the `tags` field instead this works as intended. I have no idea why this side effect was caused as part of my change. Any thoughts?

**Comment by dilipkrish** [comment]
Want to share your branch so I can take a look?

**Comment by erikthered** [comment]
Should be linked in the PR, here it is: https://github.com/erikthered/springfox/tree/requestparam-regex-fix

**Comment by ctapobep** [comment]
This is still an issue with 2.9.2 when path ends with pathVariable and then is followed by a query param:

```java
    @RequestMapping(method = GET, path = "blah/{experimentId}")
    @ApiOperation(httpMethod = "GET", value = "getFullExperiment",
            notes = "Returns full body of Experiment by internal ID.")
    public ResponseEntity getFullExperiment(@PathVariable Long experimentId,
            @RequestParam(value = "shortInfo", defaultValue = "false") boolean shortInfo) {
      ...
   }
```

Also tried 2.6.0 - same results. But 2.2.2 works fine.
