### ISSUE TITLE
Swagger produce IllegalArgumentException while using Spring HATEOAS classes

### ISSUE THREAD

**Issue by full-lounge** [springfox/springfox#997]
I'm using Spring HATEOAS library for creating RESTful service and springfox Swagger for documenting it. Documenting for this method:

    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    @Transactional
    @ApiOperation(value = "Get dictionary data")
    public Resource<DictInstResource> get(@PathVariable long id) {
        DictionaryInstance dictionaryInstance = storageApi.forDomain(domainId).forDictionary(dictionaryId).getById(id);
        return assembler.toResource(dictionaryInstance);
    }

produced an exception:

    At application launching throwing exception:
    
        java.lang.IllegalArgumentException: Multiple entries with same key: links=springfox.documentation.schema.ModelProperty@3e7161b8 and links=springfox.documentation.schema.ModelProperty@5c6970f

Method use this DTO:

    public class DictInstResource {
    
        @JsonProperty
        private Long PK;
    
        @JsonProperty
        private String name;
    
        @JsonProperty
        @JsonUnwrapped
        private Resources<RecordResource> records;
    
        public DictInstResource(Long PK, String name, Resources<RecordResource> records) {
            this.PK = PK;
            this.name = name;
            this.records = records;
        }
    }

Assembler:

    public class DictInstResourceAssembler {
    
        @Autowired
        private RecordResourceAssembler recordResourceAssembler;
    
        public Resource<DictInstResource> toResource(DictionaryInstance dictInstance) {
            Resources<RecordResource> recordResources = recordResourceAssembler.toResources(dictInstance.getRecords());
            DictInstResource resource = new DictInstResource(dictInstance.getId(), dictInstance.getName(), recordResources);
            return new Resource<DictInstResource>(resource);
        }
    }

I think it's due to the fact that Resource and Resources classes by Spring HATEOAS library both extend ResourceSupport class, which have this getter:

    @JsonProperty("links")
    public List<Link> getLinks() {
        return this.links;
    }

How I can solve this problem?

**Comment by dilipkrish** [comment]
@full-lounge Thanks for reporting this issue, not really sure about the solution or what the problem is. Its clearly a problem, but I've not encountered it and I don't have the bandwidth the research it. Would you mind creating  failing test?

**Comment by full-lounge** [comment]
@dilipkrish I modified code so that controller method return DTO (DictInstResource), that extend ResourceSupport class of Spring HATEOAS. This solved my issue. I think there is no need to find solution.

**Comment by irfandawood** [comment]
Hi @full-lounge I am having the same issue, I get the exception when I return my resource object. I tried your approach and made my controller method return DTO that extends ResourceSupport class, the output just had empty links tag without any actual link. Please see my created issue that I have referenced in this one. 
Wondering if you could help me with it.
Thanks!
